### ISSUE TITLE
Error when building Linux build

### ISSUE THREAD

**Issue by vnsharma-systango** [electron-userland/electron-builder#1009]
# I have added auther email in my package.json

```son
{
  "name": "CoDesktop",
  "version": "1.0.0",
  "description": "CoDesktop",
  "homepage": "https://app.onepgr.com/",
  "author": "OnePgr, Inc",
  "email" : "amsystango@gmail.com",
  "private": true,
  "scripts": {
    "postinstall": "install-app-deps",
    "start": "npm install && npm run compile && electron ./app",
    "compile": "rimraf app/out && tsc",
    "pack": "npm run compile && build --dir",
    "dist": "npm run compile && build",
    "release": "npm run compile && build",
    "installer": "node ./app/installer.js"
  },
  "build": {
    "appId": "org.develar.onshape",
    "category": "public.app-category.graphics-design",
    "dmg": {
      "contents": [
        {
          "x": 110,
          "y": 150
        },
        {
          "x": 240,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "publish": null,
      "msi": true,
      "icon": "./app/assets/img/CoDesktopLogoFinal_Icon.ico"
    },
    "linux": {
      "publish": null,
      "icon": "./app/assets/img/CoDesktopLogoFinal_Icon.ico",
      "target": [
        "deb",
        "AppImage"
      ]
    }
  },
  "devDependencies": {
    "asar": "^0.7.2",
    "electron": "1.4.3",
    "electron-builder": "^8.6.0",
    "electron-packager": "^8.4.0",
    "electron-prebuilt": "^0.31.0",
    "electron-winstaller": "^2.4.1",
    "fs-jetpack": "^0.7.0",
    "grunt": "^1.0.1",
    "gulp": "^3.9.0",
    "gulp-copy": "0.0.2",
    "gulp-uglify": "^1.3.0",
    "gulp-usemin": "^0.3.12",
    "q": "^1.4.1",
    "rcedit": "^0.3.0",
    "rimraf": "^2.5.4",
    "typescript": "^2.0.3"
  }
}
 ,
```

# **even then it is showing folloeing error** 

Error: Please specify author 'email' in the application package.json

See https://docs.npmjs.com/files/package.json#people-fields-author-contributors

It is required to set Linux .deb package maintainer. Or you can set maintainer in the custom linux options.
(see https://github.com/electron-userland/electron-builder#distributable-format-configuration).

    at /usr/local/lib/node_modules/electron-builder/src/targets/fpm.ts:89:15
    at Generator.next (<anonymous>)
From previous event:
    at FpmTarget.build (/usr/local/lib/node_modules/electron-builder/out/targets/fpm.js:210:11)
    at default.each.it (/usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:171:87)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at postAsyncTasks.push.default.map.then (/usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:171:35)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:171:8)
    at /usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:166:10
From previous event:
    at LinuxPackager.pack (/usr/local/lib/node_modules/electron-builder/out/platformPackager.js:219:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:146:22
From previous event:
    at Packager.doBuild (/usr/local/lib/node_modules/electron-builder/out/packager.js:271:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:114:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (/usr/local/lib/node_modules/electron-builder/out/packager.js:223:11)
    at /usr/local/lib/node_modules/electron-builder/src/builder.ts:241:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/usr/local/lib/node_modules/electron-builder/out/builder.js:89:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by develar** [comment]
Please see https://docs.npmjs.com/files/package.json#people-fields-author-contributors

**Comment by develar** [comment]
`"Barney Rubble <b@rubble.com>`

**Comment by vnsharma-systango** [comment]
@develar :As you can see,i have already gone through that doc and added email in package json as i had mentioned in my issue, even then it is showing error . I am stuck in this from 2 days pls sujest any solution.

**Comment by develar** [comment]
**is an object with a "name" field and optionally "url" and "email", like this:**

```
{ 
  "name" : "Barney Rubble", 
  "email" : "b@rubble.com"
}
```

Please use `"author": "OnePgr, Inc <amsystango@gmail.com>"`

**Comment by vnsharma-systango** [comment]
thanks , it worked .
