### ISSUE TITLE
Auto Updater instanceof error

### ISSUE THREAD

**Issue by naderhen** [electron-userland/electron-builder#1015]
* **Version**: electron-auto-updater@0.7.1
electron-builder@10.8.1

Using the Bintray Auto-Update Configuration.

* **Target**: Windows 7 64-bit

I'm suddenly seeing the following error in my app logs when it attempts to auto-update.

```
{"name":"AppLog","hostname":"IP-C61348F5","pid":4540,"level":30,"msg":"NSIS: Error TypeError: Right-hand side of 'instanceof' is not an object\n    at D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:24908:24\n    at next (<anonymous>)\n    at tryCatcher (D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:15173:24)\n    at PromiseSpawn._promiseFulfilled (D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:18916:50)\n    at D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:19020:16\nFrom previous event:\n    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:16834:20)\n    at Promise._then (D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:14609:18)\n    at Promise._passThrough (D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:17450:18)\n    at Promise.lastly.Promise.finally (D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:17459:18)\n    at new PromiseSpawn (D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:18855:35)\n    at D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:19016:22\n    at NsisUpdater.checkForUpdates (D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:14255:12)\n    at check (D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:306:29)\n    at App.<anonymous> (D:\\Users\\nader\\AppData\\Local\\Programs\\App\\resources\\app.asar\\main.js:310:6)\n    at emitTwo (events.js:111:20)\n    at App.emit (events.js:191:7)","time":"2016-12-15T18:20:48.013Z","v":0}
```

which is being caught by my event handler:
```
global.updater.on('error', error => {
    log.info('NSIS: Error', error);
});
```

Looking at the offending line in my compiled main.js, it seems to be pointing at `BintrayProvider#getLatestVersion`

![image](https://cloud.githubusercontent.com/assets/99392/21236827/87ef11b6-c2ca-11e6-86dc-acfdf5ef377f.png)

Any insight into this would be greatly appreciated! Thanks for your help

--
Nader

**Comment by develar** [comment]
Please try 0.7.2
