### ISSUE TITLE
GenericProvider getLatestVersion fails.

### ISSUE THREAD

**Issue by Johnz86** [electron-userland/electron-builder#1034]
* **Version**: 10.8.1

* **Target**:  win

In my application I am trying to just check the latest version on application on server. This is my simple server:
```
var express = require('express');
var app = express();
var path = require('path');

// Define the port to run on
app.set('port', 8000);
app.use('/version',express.static(path.resolve(__dirname, '../dist')));

// Listen for requests
var server = app.listen(app.get('port'), function() {
  var port = server.address().port;
  console.log('Distributing files on port ' + port);
});
```
And I try to do this:

```
import { GenericProvider } from "electron-auto-updater/out/nsis-auto-updater/src/GenericProvider";
 let provider: GenericProvider = new GenericProvider({ provider: "generic", channel:"latest", url:"http://localhost:8000/version/" });
provider.getLatestVersion().then((data)=>{console.log(data)});
```

I will get an error:

```
Unhandled rejection Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1092:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at doApiRequest (C:\GIT\SKBOfflineClientOld_refactored\node_modules\electron-auto-updater\out\src\publish\restApiRequest.js:104:12)
    at request (C:\GIT\SKBOfflineClientOld_refactored\node_modules\electron-auto-updater\out\src\publish\restApiRequest.js:95:12)
    at C:\GIT\SKBOfflineClientOld_refactored\node_modules\electron-auto-updater\out\nsis-auto-updater\src\GenericProvider.js:45:88
    at next (<anonymous>)
From previous event:
    at GenericProvider.getLatestVersion (C:\GIT\SKBOfflineClientOld_refactored\node_modules\electron-auto-updater\out\nsis-auto-updater\src\GenericProvider.js:54:11)
    at Main.checkVersion (C:\GIT\SKBOfflineClientOld_refactored\main.js:60:18)
    at Main.createWindow (C:\GIT\SKBOfflineClientOld_refactored\main.js:29:14)
    at Main.start (C:\GIT\SKBOfflineClientOld_refactored\main.js:40:18)
    at App.electron_1.app.on (C:\GIT\SKBOfflineClientOld_refactored\main.js:66:10)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```
What is the proper way to use GenericProvider with local node.js server?

**Comment by Daymannovaes** [comment]
in this line https://github.com/electron-userland/electron-builder/blob/master/nsis-auto-updater/src/GenericProvider.ts#L17

you can see that it try to catch the `.yml` at your server, which in your case, it'll try to request to `http://localhost:8000/version/latest.yml`, are you serving this file on your server?

Took a look at the source code is a good way to understand what's going on, as the docs can be misleading in some cases.

**Comment by develar** [comment]
Only `https` is supported due to security reasons.
