### ISSUE TITLE
pack-updater script is broken

### ISSUE THREAD

**Issue by badams** [electron-userland/electron-builder#1056]
* **Version**: 10.13.1
* **Target**:  N/A

```bash
npm run pack-updater
> electron-builder@0.0.0-semantic-release pack-updater /Users/byron/dev/electron-builder
> cd nsis-auto-updater && node ./test/vendor/yarn.js --production && cd ..

module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/byron/dev/electron-builder/nsis-auto-updater/test/vendor/yarn.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

As far as I can tell this has been broken since [eff85c38](https://github.com/electron-userland/electron-builder/commit/eff85c38e99a7e11c47c1e40464258dfcae069bd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

**Comment by badams** [comment]
https://github.com/electron-userland/electron-builder/pull/1057#issuecomment-269434192
