### ISSUE TITLE
Can't locate Mac/Finder/DSStore.pm in @INC

### ISSUE THREAD

**Issue by bkonkle** [electron-userland/electron-builder#1079]
* **10.17.1**: 

* **Mac**: 

I'm getting a perl error related to the [vendored DSStore module](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/vendor/Mac/Finder/DSStore.pm): **Can't locate Mac/Finder/DSStore.pm in @INC (you may need to install the Mac::Finder::DSStore module)**

The command: `cross-env GH_TOKEN=... build`

OS: Mac OS X v10.12.2 (16C67)
node -v: v6.9.1
npm -v: 4.0.5
perl -v: v5.18.2 (because why not?)

The full error:

```
Building macOS zip
Building DMG
Error: Exit code: 2. Command failed: /usr/bin/pd4cdf50bab944284b5876cc5548f6ebccbf3787f1defcc78d7b2bbd348921a1f (sha256 hash) /var/folders/lp/jg650t9x0bl5fcrqh3wskb7w0000gn/T/electron-builder-L0FPDG/0-2-dmgProperties.pl
Can't locate Mac/Finder/DSStore.pm in @INC (you may need to install the Mac::Finder::DSStore module) (@INC contains: /usr/local/lib/perl5/site_perl /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /var/folders/lp/jg650t9x0bl5fcrqh3wskb7w0000gn/T/electron-builder-L0FPDG/0-2-dmgProperties.pl line 3.
BEGIN failed--compilation aborted at /var/folders/lp/jg650t9x0bl5fcrqh3wskb7w0000gn/T/electron-builder-L0FPDG/0-2-dmgProperties.pl line 3.

Can't locate Mac/Finder/DSStore.pm in @INC (you may need to install the Mac::Finder::DSStore module) (@INC contains: /usr/local/lib/perl5/site_perl /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /var/folders/lp/jg650t9x0bl5fcrqh3wskb7w0000gn/T/electron-builder-L0FPDG/0-2-dmgProperties.pl line 3.
BEGIN failed--compilation aborted at /var/folders/lp/jg650t9x0bl5fcrqh3wskb7w0000gn/T/electron-builder-L0FPDG/0-2-dmgProperties.pl line 3.

    at /Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/util/util.ts:77:16
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
From previous event:
    at exec (/Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/util/util.ts:55:3)
    at /Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/targets/dmg.ts:153:7
From previous event:
    at /Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/targets/dmg.ts:294:24
From previous event:
    at attachAndExecute (/Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/out/targets/dmg.js:60:22)
    at /Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/targets/dmg.ts:64:5
    at next (native)
From previous event:
    at DmgTarget.build (/Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/out/targets/dmg.js:235:11)
    at postAsyncTasks.push.default.map.it (/Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/platformPackager.ts:172:85)
From previous event:
    at MacPackager.packageInDistributableFormat (/Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/platformPackager.ts:172:41)
    at /Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/macPackager.ts:80:26
From previous event:
    at /Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/macPackager.ts:80:10
    at next (native)
From previous event:
    at MacPackager.pack (/Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/out/macPackager.js:162:11)
    at /Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/packager.ts:146:22
From previous event:
    at Packager.doBuild (/Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/out/packager.js:275:11)
    at /Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/packager.ts:114:38
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/out/packager.js:227:11)
    at /Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/src/builder.ts:249:40
    at next (native)
From previous event:
    at build (/Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/out/builder.js:90:21)
    at Object.<anonymous> (/Users/brandon/code/pairboard/packages/pairboard-desktop/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

The "build" and related sections of _package.json_:

```json
"directories": {
  "buildResources": "resources",
  "output": "release"
},
"build": {
    "appId": "io.pairboard.Pairboard",
    "category": "public.app-category.tools",
    "files": [
      "build/",
      "public/",
      "assets/",
      "node_modules/firebase",
      "node_modules/electron-debug",
      "node_modules/debug",
      "node_modules/ms"
    ],
    "protocols": [
      {
        "name": "Pairboard",
        "schemes": [
          "pairboard"
        ]
      }
    ],
    "win": {
      "target": "nsis"
    },
    "linux": {
      "target": [
        "deb",
        "AppImage"
      ]
    }
  },
  "dependencies": {
    "axios": "^0.15.3",
    "dotenv": "^2.0.0",
    "electron-redux": "^1.2.5",
    "firebase": "^3.6.4",
    "localforage": "^1.4.3",
    "material-ui": "^0.16.6",
    "menubar": "^5.2.0",
    "pairboard": "^4.2.0",
    "qs": "^6.3.0",
    "ramda": "^0.23.0",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-redux": "^5.0.1",
    "react-router": "^3.0.0",
    "react-router-redux": "^4.0.7",
    "react-tap-event-plugin": "^2.0.1",
    "recompose": "^0.21.2",
    "redux-thunk": "^2.1.0",
    "roboto-fontface": "^0.6.0",
    "source-map-support": "^0.4.8",
    "styled-components": "^1.2.1"
  },
  "devDependencies": {
    "cross-env": "^3.1.4",
    "css-loader": "^0.26.1",
    "devtron": "^1.4.0",
    "electron": "^1.4.13",
    "electron-builder": "^10.17.1",
    "electron-debug": "^1.1.0",
    "electron-devtools-installer": "^2.0.1",
    "electron-packager": "^8.4.0",
    "electron-rebuild": "^1.5.5",
    "eslint": "^3.12.2",
    "express": "^4.14.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "html-webpack-plugin": "^2.26.0",
    "image-webpack-loader": "^3.1.0",
    "json-loader": "^0.5.4",
    "minimist": "^1.2.0",
    "react-transform-catch-errors": "^1.0.2",
    "react-transform-hmr": "^1.0.4",
    "redbox-react": "^1.3.3",
    "style-loader": "^0.13.1",
    "svg-jsx-loader": "0.0.16",
    "url-loader": "^0.5.7",
    "webpack": "^1.14.0",
    "webpack-configurator": "^0.3.1",
    "webpack-dev-middleware": "^1.9.0",
    "webpack-hot-middleware": "^2.14.0",
    "webpack-target-electron-renderer": "^0.4.0"
  },
```

**Comment by bkonkle** [comment]
Same result on 10.17.0, so I'm going back further.

**Comment by bkonkle** [comment]
Same issue back to 10.15.2, which I know was working before. I know a couple of other dependencies changed recently as well. I'll see if it's something related.

**Comment by bkonkle** [comment]
I'm wrong - 10.15.1 is what I was on before, and that's working. Regression happened between 10.15.1 and 10.15.2.

**Comment by bkonkle** [comment]
Probably related to [this change](https://github.com/electron-userland/electron-builder/commit/3bf8c9311657ce71211c35af39a575ae3587ba58#diff-628ed8d56d2b7406eac1ada34f262aa5L148), but I don't have time to dig further at the moment. When I've got more free time I'll follow up on this ticket and submit a patch if I can. 👍

**Comment by develar** [comment]
More robust solution is implemented, fix will be published soon.

**Comment by leonheess** [comment]
Encountering this issue on 20.44.4
