### ISSUE TITLE
Linux AppImage - xorriso error when building

### ISSUE THREAD

**Issue by ssboisen** [electron-userland/electron-builder#1140]
* **Version**: 11.4.4

* **Target**: Linux

I recently upgraded from 10.5.x to 11.4.4 and now it seems building Linux AppImage doesn't work anymore. It seems to be related to `xorriso`, here's the log:

```
Error: Exit code: 5. Command failed: /home/ssboisen/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /home/ssboisen/code/lix-app-shell-electron/dist/lix-1.0.7-x86_64.AppImage -padding 0 -map /home/ssboisen/code/lix-app-shell-electron/dist/linux-unpacked /usr/bin -map /home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-DZYtKy/0-2-Lix.desktop /lix.desktop -map /tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_16x16x32.png /usr/share/icons/default/16x16/apps/lix.png -map /tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_24x24x32.png /usr/share/icons/default/24x24/apps/lix.png -map /tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_32x32x32.png /usr/share/icons/default/32x32/apps/lix.png -map /tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_48x48x32.png /usr/share/icons/default/48x48/apps/lix.png -map /tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_64x64x32.png /usr/share/icons/default/64x64/apps/lix.png -map /tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_96x96x32.png /usr/share/icons/default/96x96/apps/lix.png -map /tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_128x128x32.png /usr/share/icons/default/128x128/apps/lix.png -map /tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_256x256x32.png /usr/share/icons/default/256x256/apps/lix.png -map /tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_512x512x32.png /usr/share/icons/default/512x512/apps/lix.png -map /tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_256x256x32.png /.DirIcon -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /
GNU xorriso 1.4.4 : RockRidge filesystem manipulator, libburnia project.

xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
Drive current: -dev '/home/ssboisen/code/lix-app-shell-electron/dist/lix-1.0.7-x86_64.AppImage'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 39.6g free
New volume id: 'AppImage'
xorriso : UPDATE : 71 files added in 1 seconds
Added to ISO image: directory '/usr/bin'='/home/ssboisen/code/lix-app-shell-electron/dist/linux-unpacked'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/AppRun'='/home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/templates/linux/AppRun.sh'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/lix.desktop'='/tmp/electron-builder-DZYtKy/0-2-Lix.desktop'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/16x16/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_16x16x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/24x24/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_24x24x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/32x32/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_32x32x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/48x48/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_48x48x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/64x64/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_64x64x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/96x96/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_96x96x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/128x128/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_128x128x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/256x256/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_256x256x32.png'
xorriso : FAILURE : Cannot determine attributes of source file '/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_512x512x32.png' : No such file or directory
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'

GNU xorriso 1.4.4 : RockRidge filesystem manipulator, libburnia project.

xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
Drive current: -dev '/home/ssboisen/code/lix-app-shell-electron/dist/lix-1.0.7-x86_64.AppImage'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 39.6g free
New volume id: 'AppImage'
xorriso : UPDATE : 71 files added in 1 seconds
Added to ISO image: directory '/usr/bin'='/home/ssboisen/code/lix-app-shell-electron/dist/linux-unpacked'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/AppRun'='/home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/templates/linux/AppRun.sh'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/lix.desktop'='/tmp/electron-builder-DZYtKy/0-2-Lix.desktop'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/16x16/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_16x16x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/24x24/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_24x24x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/32x32/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_32x32x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/48x48/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_48x48x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/64x64/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_64x64x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/96x96/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_96x96x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/128x128/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_128x128x32.png'
xorriso : UPDATE : 1 files added in 1 seconds
Added to ISO image: file '/usr/share/icons/default/256x256/apps/lix.png'='/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_256x256x32.png'
xorriso : FAILURE : Cannot determine attributes of source file '/tmp/electron-builder-DZYtKy/0-1-linux.iconset/icon_512x512x32.png' : No such file or directory
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'

    at /home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder-util/src/util.ts:75:16
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at exec (/home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder-util/src/util.ts:53:3)
    at /home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/src/targets/appImage.ts:79:11
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/out/targets/appImage.js:142:11)
    at postAsyncTasks.push.default.map.it (/home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/src/platformPackager.ts:103:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/src/platformPackager.ts:103:41)
    at /home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/src/platformPackager.ts:99:10
From previous event:
    at LinuxPackager.pack (/home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/out/platformPackager.js:160:11)
    at /home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/src/packager.ts:175:22
From previous event:
    at Packager.doBuild (/home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/out/packager.js:299:11)
    at /home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/src/packager.ts:143:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/out/packager.js:251:11)
    at /home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/src/builder.ts:214:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/home/ssboisen/code/lix-app-shell-electron/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by develar** [comment]
Incorrect icon path passed to xorriso. Strange, to investigate.

**Comment by develar** [comment]
Should be fixed in 13.
