### ISSUE TITLE
Error updating using generic provider

### ISSUE THREAD

**Issue by loziobiz** [electron-userland/electron-builder#1153]
* **11.4.4**: 

* **NSIS**: 

I'm trying to use generic provider with NSIS. 
I've uploaded artifacts to an s3 bucket as well as the latest.yml file. 
App-update.yml file is in the resource folder.
I've added handlers for the updater events.

When I trigger checkForUpdates I got this error
```
Error: TypeError: Cannot read property 'request' of undefined
    at default (C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\node_modules\electron-auto-updater\src\electronHttpExecutor.ts:85:13)
    at ElectronHttpExecutor.doApiRequest (C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\node_modules\electron-auto-updater\src\electronHttpExecutor.ts:84:5)
    at ElectronHttpExecutor.request (C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\node_modules\electron-builder-http\src\httpExecutor.ts:56:17)
    at request (C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\node_modules\electron-builder-http\src\httpExecutor.ts:174:38)
    at C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\node_modules\electron-auto-updater\src\GenericProvider.ts:19:22
    at next (<anonymous>)
From previous event:
    at GenericProvider.getLatestVersion (C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\node_modules\electron-auto-updater\out\GenericProvider.js:64:11)
    at C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\node_modules\electron-auto-updater\src\AppUpdater.ts:136:38
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\node_modules\electron-auto-updater\out\AppUpdater.js:217:11)
    at C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\node_modules\electron-auto-updater\src\AppUpdater.ts:123:25
    at next (<anonymous>)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\node_modules\electron-auto-updater\out\AppUpdater.js:180:11)
    at NsisUpdater.checkForUpdates (C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\node_modules\electron-auto-updater\src\AppUpdater.ts:102:35)
    at Object.<anonymous> (C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\app\main.js:127:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (C:\Users\IEUser\AppData\Local\Programs\bsmart-exe-reader\resources\electron.asar\browser\init.js:166:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
```

**Comment by develar** [comment]
Please specify electron version. Please use electron-updater 1.1.1

**Comment by loziobiz** [comment]
I was using Electron@1.2.13 and electron-auto-updater@1.0.0

I've upgraded to electron@latest and electron-updater@1.1.1 and now everything works like a charme :)

Thanks a lot for your input!
