### ISSUE TITLE
CI publish error

### ISSUE THREAD

**Issue by Timer** [electron-userland/electron-builder#1183]
Following the [suggested workflow](https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts) results in a nasty CI error. This happens once you release the version on github and triggers a rebuild.
This only happens on travis; appveyor is fine.

```js
"electron-builder": "^11.5.1",
```

```
reating Github Publisher — owner: timer, project: affiliate-sync, version: 1.0.1
Error: Cannot cleanup: 
Error #1 --------------------------------------------------------------------------------
Error: Release with tag v1.0.1 published at Fri Jan 27 2017 19:11:38 GMT+0000 (UTC), more than 2 hours ago
    at /Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/publish/gitHubPublisher.ts:81:19
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at GitHubPublisher.init (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/out/publish/gitHubPublisher.js:120:11)
    at new GitHubPublisher (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/publish/gitHubPublisher.ts:59:98)
    at createPublisher (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/publish/PublishManager.ts:248:12)
    at PublishManager.getOrCreatePublisher (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/publish/PublishManager.ts:116:19)
    at /Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/publish/PublishManager.ts:89:32
From previous event:
    at PublishManager.artifactCreated (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/out/publish/PublishManager.js:278:11)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/publish/PublishManager.ts:72:57)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Packager.dispatchArtifactCreated (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/packager.ts:78:23)
    at MacPackager.dispatchArtifactCreated (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/platformPackager.ts:88:15)
    at /Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/targets/ArchiveTarget.ts:42:14
    at next (native)
From previous event:
    at ArchiveTarget.build (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/out/targets/ArchiveTarget.js:71:11)
    at postAsyncTasks.push.default.map.it (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/platformPackager.ts:103:85)
From previous event:
    at MacPackager.packageInDistributableFormat (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/platformPackager.ts:103:41)
    at /Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/macPackager.ts:82:26
From previous event:
    at /Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/macPackager.ts:82:10
    at next (native)
From previous event:
    at MacPackager.pack (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/out/macPackager.js:165:11)
    at /Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/packager.ts:175:22
From previous event:
    at Packager.doBuild (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/out/packager.js:299:11)
    at /Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/packager.ts:143:38
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/out/packager.js:251:11)
    at /Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/src/builder.ts:214:40
    at next (native)
From previous event:
    at build (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/Users/travis/build/Timer/affiliate-sync/packages/app/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Error #2 --------------------------------------------------------------------------------
Error: Release with tag v1.0.1 published at Fri Jan 27 2017 19:11:38 GMT+0000 (UTC), more than 2 hours ago

-snip-
```

**Comment by develar** [comment]
It means that your release is already published and not a prerelease or draft . Is it not true?

**Comment by Timer** [comment]
It is true, the release is already published. But publishing the release causes a build to happen -- I figured it would be better to say "A release is already published" vs throwing errors, if this is the desired behavior then the issue can be closed. This issue was more of a usability concern.

Like I said though, appveyor rebuilds on tag but doesn't throw errors.

**Comment by develar** [comment]
Got your point. You are right.

**Comment by develar** [comment]
Is time check on CI was correct? Was it really two hours ago?

**Comment by develar** [comment]
If you use github to create tags, you can exclude tag branches — https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml#L42

**Comment by Timer** [comment]
The time check is sometimes 2+ hours - 1 day, it's the first time the publish was drafted -- not updated.

Did I misunderstand the suggested workflow?

And ah! I'll add that tag clause to prevent rebuilds.
