### ISSUE TITLE
Build for win/osx failes on linux machine 

### ISSUE THREAD

**Issue by elhachmi** [electron-userland/electron-builder#1217]
* **12.0.3**: 

* **OSX/Windows building on a linux CI "wercker"**: 

- I get this error when I build for OSX/Windows from linux.
- My build is ok if the target is linux
- I'm using libxml-xsd which is a native dependency
- From my mac machine all my build successed

Unhandled rejection Error: spawn hdiutil ENOENT
    at exports._errnoException (util.js:1023:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at spawn (/path/project/node_modules/electron-builder-util/src/util.ts:97:3)
    at /path/project/node_modules/electron-builder/src/targets/dmg.ts:49:11
    at Generator.next (<anonymous>)
    at /path/project/node_modules/graceful-fs/graceful-fs.js:99:16
    at /path/project/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:112:15)
From previous event:
    at DmgTarget.build (/path/project/node_modules/electron-builder/out/targets/dmg.js:234:11)
    at postAsyncTasks.push.default.map.it (/path/project/node_modules/electron-builder/src/platformPackager.ts:103:85)
From previous event:
    at MacPackager.packageInDistributableFormat (/path/project/node_modules/electron-builder/src/platformPackager.ts:103:41)
    at /path/project/node_modules/electron-builder/src/macPackager.ts:82:26
From previous event:
    at /path/project/node_modules/electron-builder/src/macPackager.ts:82:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/path/project/node_modules/electron-builder/out/macPackager.js:173:11)
    at /path/project/node_modules/electron-builder/src/packager.ts:210:22
From previous event:
    at Packager.doBuild (/path/project/node_modules/electron-builder/out/packager.js:335:11)
    at /path/project/node_modules/electron-builder/src/packager.ts:151:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/path/project/node_modules/electron-builder/out/packager.js:261:11)
    at /path/project/node_modules/electron-builder/src/builder.ts:214:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/path/project/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/path/project/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

You can build DMG only on macOS.
