### ISSUE TITLE
Unhandled rejection Error: ENOTDIR: not a directory, scandir 'H:\www\gif\build\icon.ico'

### ISSUE THREAD

**Issue by govenlive** [electron-userland/electron-builder#1242]
* **13.5**: 

* **Linux**: 

when  I pack the linux,throw an error: Unhandled rejection Error: ENOTDIR: not a directory, scandir 'H:\www\gif\build\linux.icns',but i pack the win is normal!, I use command line :  build --linux

The Error: 
`Unhandled rejection Error: ENOTDIR: not a directory, scandir 'H:\www\gif\build\linux.icns'
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\hasee\AppData\Roaming\npm\node_modules\electron-builder\node_modules\.3.4.7@bluebird\js\release\debuggability.js:397:19)
    at Promise._then (C:\Users\hasee\AppData\Roaming\npm\node_modules\electron-builder\node_modules\.3.4.7@bluebird\js\release\promise.js:231:17)
    at Promise._passThrough (C:\Users\hasee\AppData\Roaming\npm\node_modules\electron-builder\node_modules\.3.4.7@bluebird\js\release\finally.js:91:17)
    at Promise.lastly.Promise.finally (C:\Users\hasee\AppData\Roaming\npm\node_modules\electron-builder\node_modules\.3.4.7@bluebird\js\release\finally.js:100:17)
    at new PromiseSpawn (C:\Users\hasee\AppData\Roaming\npm\node_modules\electron-builder\node_modules\.3.4.7@bluebird\js\release\generators.js:36:34)
    at C:\Users\hasee\AppData\Roaming\npm\node_modules\electron-builder\node_modules\.3.4.7@bluebird\js\release\generators.js:197:21
    at build (C:\Users\hasee\AppData\Roaming\npm\node_modules\electron-builder\out\builder.js:71:21)
    at Object.<anonymous> (C:\Users\hasee\AppData\Roaming\npm\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
`

**Comment by develar** [comment]
Please provide your config.
