### ISSUE TITLE
libreadline.so.6 error in electron-builder 13.5.0

### ISSUE THREAD

**Issue by belltown** [electron-userland/electron-builder#1243]
Using version 13.5.0 of electron-builder:

```
$ npm list --depth=0
violetbug@0.0.1 /home/john/Documents/github/violetbug/source
├── electron@1.4.15
├── electron-builder@13.5.0
└── electron-packager@8.5.1
```

libreadline is installed:

```
$ dpkg -l |grep libreadline
ii  libreadline7:amd64                              7.0-0ubuntu2                                  amd64        GNU readline and history libraries, run-time libraries
```

Building AppImage on Ubuntu 16.10 using this script in package.json:

```
  "build": {
    "appId": "tk.belltown-roku.violetbug",
    "directories": {
      "buildResources": "images",
      "output": "../dist/"
    },
    "nsis": {
      "oneClick": true
    },
    "win": {},
    "linux": {
      "target": ["AppImage"],
      "category": "Development",
      "description": "A cross-platform Roku Debugger graphical interface",
      "synopsis": "Roku Debugger Graphical Interface",
      "icon": "."
    }
  },
```

The build fails because libreadline.so.6 is not installed.

```
$ npm run dist

> violetbug@0.0.1 dist /home/john/Documents/github/violetbug/source
> build

No native production dependencies
Packaging for linux x64 using electron 1.4.15 to ../dist/linux-unpacked
Building AppImage for arch x64
Error: Exit code: 127. Command failed: /home/john/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /home/john/Documents/github/violetbug/dist/violetbug-0.0.1-x86_64.AppImage -padding 0 -map /home/john/Documents/github/violetbug/dist/linux-unpacked /usr/bin -map /home/john/Documents/github/violetbug/source/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-FQnV1p/0-1-VioletBug.desktop /violetbug.desktop -map /home/john/Documents/github/violetbug/source/images/32x32.png /usr/share/icons/default/32x32/apps/violetbug.png -map /home/john/Documents/github/violetbug/source/images/32x32.png /.DirIcon -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /
/home/john/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

/home/john/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

    at /home/john/Documents/github/violetbug/source/node_modules/electron-builder-util/src/util.ts:75:16
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
From previous event:
    at exec (/home/john/Documents/github/violetbug/source/node_modules/electron-builder-util/src/util.ts:53:3)
    at /home/john/Documents/github/violetbug/source/node_modules/electron-builder/src/targets/appImage.ts:79:11
    at next (native)
From previous event:
    at AppImageTarget.build (/home/john/Documents/github/violetbug/source/node_modules/electron-builder/out/targets/appImage.js:142:11)
    at postAsyncTasks.push.default.map.it (/home/john/Documents/github/violetbug/source/node_modules/electron-builder/src/platformPackager.ts:103:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/john/Documents/github/violetbug/source/node_modules/electron-builder/src/platformPackager.ts:103:41)
    at /home/john/Documents/github/violetbug/source/node_modules/electron-builder/src/platformPackager.ts:99:10
From previous event:
    at LinuxPackager.pack (/home/john/Documents/github/violetbug/source/node_modules/electron-builder/out/platformPackager.js:160:11)
    at /home/john/Documents/github/violetbug/source/node_modules/electron-builder/src/packager.ts:222:22
From previous event:
    at Packager.doBuild (/home/john/Documents/github/violetbug/source/node_modules/electron-builder/out/packager.js:344:11)
    at /home/john/Documents/github/violetbug/source/node_modules/electron-builder/src/packager.ts:150:38
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (/home/john/Documents/github/violetbug/source/node_modules/electron-builder/out/packager.js:250:11)
    at /home/john/Documents/github/violetbug/source/node_modules/electron-builder/src/builder.ts:217:65
    at next (native)
From previous event:
    at build (/home/john/Documents/github/violetbug/source/node_modules/electron-builder/out/builder.js:71:21)
    at Object.<anonymous> (/home/john/Documents/github/violetbug/source/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Linux 4.8.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dist"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! violetbug@0.0.1 dist: `build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the violetbug@0.0.1 dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the violetbug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs violetbug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls violetbug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/john/.npm/_logs/2017-02-11T23_50_04_709Z-debug.log
```

There was a similar issue marked as 'Closed': https://github.com/electron-userland/electron-builder/issues/993 However, in the latest version of electron-builder, the issue still exists.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/375#issuecomment-269293414

**Comment by develar** [comment]
Duplicates #993
