### ISSUE TITLE
no such file or directory app-update.yml

### ISSUE THREAD

**Issue by YamiChat** [electron-userland/electron-builder#1261]
* **Version**: 
    "electron-updater": "^1.6.4",
    "electron-log": "^1.3.0"

* **Target**: macOS

I use auto-update for installed application
```
[2017-02-14 18:45:25:0741] [info] App starting...
[2017-02-14 18:45:30:0698] [info] Checking for update
[2017-02-14 18:45:30:0698] [info] Checking for update...
[2017-02-14 18:45:31:0713] [error] Error: Error: ENOENT: no such file or directory, open '/Volumes/Chat/Chat.app/Contents/Resources/app-update.yml'
    at Error (native)
From previous event:
    at /Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:238:27
    at next (<anonymous>)
From previous event:
    at MacUpdater.loadUpdateConfig (/Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:271:11)
    at /Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:147:33
    at next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:225:11)
    at /Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:137:25
    at next (<anonymous>)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at MacUpdater._checkForUpdates (/Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:181:11)
    at MacUpdater.checkForUpdates (/Volumes/Chat/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:119:35)
    at Timeout._onTimeout (/Volumes/Chat/Chat.app/Contents/Resources/app.asar/main.js:80:15)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-02-14 18:45:31:0713] [info] Error in auto-updater.
```
I use this example https://github.com/iffy/electron-updater-example

**Comment by develar** [comment]
Do you use electron-builder to build?

**Comment by YamiChat** [comment]
I use this command
```
npm run build-mac
```
with package.json
```
{
  "name": "Chat",
  "version": "1.0.8",
  "description": "Online chat",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "pack": "build --dir",
    "dist": "build",
    "build-release": "node_modules/.bin/build --win --mac -p always",
    "build-mac": "node_modules/.bin/build",
    "build-win": "electron-packager . Chat --platform win32 --arch ia32 --out dist/ --ignore \"(dist|node_modules/electron.*)\" --icon icon.ico --overwrite"
  },
  "keywords": [
    "Chat",
    "online chat"
  ],
  "author": "Author Name",
  "private": true,
  "devDependencies": {
    "electron": "^1.4.5",
    "electron-builder": "^7.24.1"
  },
  "dependencies": {
    "electron-updater": "^1.6.4",
    "electron-log": "^1.3.0"
  },
  "build": {
    "publish": [
      {
        "provider": "github",
        "owner": "Chat",
        "repo": "Chat-desktop"
      }
    ],
    "appId": "com.electron.Chat",
    "productName": "Chat",
    "mac": {
      "category": "public.app-category.business"
    },
    "dmg": {
      "title": "${productName}",
      "icon": "build/icon.icns",
      "contents": [
        {
          "x": 130,
          "y": 270
        },
        {
          "x": 410,
          "y": 270,
          "type": "link",
          "path": "/Applications"
        }
      ],
      "window": {
        "width": 540,
        "height": 380
      }
    }
  }
}
```
And open .dmg file

**Comment by develar** [comment]
Update electron-builder to 13.7.0

**Comment by YamiChat** [comment]
Thank you.
Now I use
```
"devDependencies": {
    "electron": "^1.6.0",
    "electron-builder": "^13.7.0"
  },
  "dependencies": {
    "electron-updater": "^1.6.4",
    "electron-log": "^1.3.0"
  }
```
And have this error:
```
[2017-02-14 20:17:27:0736] [info] App starting...
[2017-02-14 20:17:32:0863] [info] Checking for update
[2017-02-14 20:17:32:0863] [info] Checking for update...
[2017-02-14 20:17:35:0041] [error] Error: Error: Unable to find latest version on GitHub (https://github.com/YamiChat/YamiChat-desktop/releases/latest), please ensure a production release exists: SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.response.on (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-builder-http/src/httpExecutor.ts:129:56)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at ElectronHttpExecutor.doApiRequest (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/electronHttpExecutor.ts:40:30)
    at ElectronHttpExecutor.request (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-builder-http/src/httpExecutor.ts:77:17)
    at request (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-builder-http/src/httpExecutor.ts:211:38)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:56:34
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersionString (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:105:11)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:28:32
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:88:11)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:152:38
From previous event:
    at MacUpdater.doCheckForUpdates (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:225:11)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:137:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at MacUpdater._checkForUpdates (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:181:11)
    at MacUpdater.checkForUpdates (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:119:35)
    at Timeout._onTimeout (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/main.js:80:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    at JSON.parse (<anonymous>)
    at IncomingMessage.response.on (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-builder-http/src/httpExecutor.ts:129:56)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ElectronHttpExecutor.doApiRequest (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/electronHttpExecutor.ts:40:30)
    at ElectronHttpExecutor.request (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-builder-http/src/httpExecutor.ts:77:17)
    at request (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-builder-http/src/httpExecutor.ts:211:38)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:56:34
    at Generator.next (<anonymous>)
    at GitHubProvider.getLatestVersionString (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:105:11)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:28:32
    at Generator.next (<anonymous>)
    at GitHubProvider.getLatestVersion (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:88:11)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:152:38
    at MacUpdater.doCheckForUpdates (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:225:11)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:137:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
    at MacUpdater._checkForUpdates (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:181:11)
    at MacUpdater.checkForUpdates (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:119:35)
    at Timeout._onTimeout (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/main.js:80:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:60:13
    at Generator.throw (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at GitHubProvider.getLatestVersionString (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:105:11)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:28:32
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:88:11)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:152:38
From previous event:
    at MacUpdater.doCheckForUpdates (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:225:11)
    at /Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:137:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at MacUpdater._checkForUpdates (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:181:11)
    at MacUpdater.checkForUpdates (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:119:35)
    at Timeout._onTimeout (/Volumes/YamiChat/YamiChat.app/Contents/Resources/app.asar/main.js:80:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[2017-02-14 20:17:35:0041] [info] Error in auto-updater.
```

**Comment by ajbeaven** [comment]
I'm getting the same problem with the following installed:

* **Version**:
electron: 1.4.15
electron-builder: 14.4.0
electron-updater: 1.9.0

* **Target**: windows

I'm building using electron-builder with the following:
`build --win --x64 --ia32`

```
[16:51:19:0452] [error] Error: Error: ENOENT: no such file or directory, open 'D:\MyApp\node_modules\electron\dist\resources\app-update.yml'
    at Error (native)
From previous event:
    at D:\MyApp\node_modules\electron-updater\src\AppUpdater.ts:246:27
    at next (<anonymous>)
From previous event:
    at NsisUpdater.loadUpdateConfig (D:\MyApp\node_modules\electron-updater\out\AppUpdater.js:290:11)
    at D:\MyApp\node_modules\electron-updater\src\AppUpdater.ts:153:33
    at next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (D:\MyApp\node_modules\electron-updater\out\AppUpdater.js:243:11)
    at D:\MyApp\node_modules\electron-updater\src\AppUpdater.ts:143:25
    at next (<anonymous>)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at NsisUpdater._checkForUpdates (D:\MyApp\node_modules\electron-updater\out\AppUpdater.js:197:11)
    at NsisUpdater.checkForUpdates (D:\MyApp\node_modules\electron-updater\src\AppUpdater.ts:125:35)
    at App.<anonymous> (D:\MyApp\src\main.js:105:21)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

I'm using the two package.json structure like so:

development package.json
```
{
  "name": "my.app",
  "productName": "My App",
  "version": "0.0.0",
  "description": "My.App",
  "main": "main.js",
  "author": {
    "name": "ajbeaven",
    "url": "https://mysite.nz"
  },
  "license": "MIT",
  "build": {
    "appId": "my.app",
    "artifactName": "${productName}_${version}_${os}_${arch}-setup.${ext}",
    "mac": {
      "category": "public.app-category.business"
    },
    "nsis": {
    },
    "publish": [
      {
        "provider": "generic",
        "url": "http://download.mysite.nz/downloads"
      }
    ]
  },
  "dependencies": {
    "electron-log": "^1.3.0",
    "electron-updater": "^1.9.0"
  },
  "devDependencies": {
    "electron": "^1.4.15",
    "electron-builder": "^14.4.0"
  }
}
```

app package.json
```
{
  "name": "my.app",
  "productName": "My App",
  "version": "0.0.4",
  "description": "My.App",
  "main": "main.js",
  "author": {
    "name": "ajbeaven",
    "url": "https://mysite.nz"
  },
  "license": "MIT"
}
```

**Comment by keyurchitroda** [comment]
I'm using electron builder to auto-update my app for mac, windows & ubuntu OS. mac & windows are working fine. But, the Ubuntu deb package app is throwing errors while it's updating as I attach error logs below. I've tried some solutions available on web but didn't get the solution.

Error: Error: ENOENT: no such file or directory, open '/opt/Centroall Tracker/resources/app-update.yml'

electron=11.5.0,
electron-builder=22.11.7,
electron-updater=4.6.5
