### ISSUE TITLE
Spawn gm ENOENT on Ubuntu 16.04

### ISSUE THREAD

**Issue by ChannelOne** [electron-userland/electron-builder#1275]
* **Version**: 10.17.3

* **Target**: Linux

spawn gm ENOENT

```
No native production dependencies
Packaging for linux x64 using electron 1.4.15 to dist/linux-unpacked
Unhandled rejection Error: Exit code: ENOENT. spawn gm ENOENT
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/util/util.ts:77:16
    at exithandler (child_process.js:218:5)
    at ChildProcess.errorhandler (child_process.js:230:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:189:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at exec (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/util/util.ts:55:3)
    at resize (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:146:16)
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:149:46
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at LinuxTargetHelper.createFromIcns (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:186:11)
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:28:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:58:11)
    at new LinuxTargetHelper (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:16:23)
    at getHelper (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/linuxPackager.ts:42:18)
    at outDir (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/linuxPackager.ts:71:122)
    at mapper (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/targetFactory.ts:29:16)
    at LinuxPackager.createTargets (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/linuxPackager.ts:71:7)
    at createTargets (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/targetFactory.ts:36:12)
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/packager.ts:146:41
From previous event:
    at Packager.doBuild (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/packager.js:275:11)
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/packager.ts:114:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/packager.js:227:11)
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/builder.ts:249:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/builder.js:90:21)
    at Object.<anonymous> (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

Building deb
Error: Exit code: ENOENT. spawn gm ENOENT
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/util/util.ts:77:16
    at exithandler (child_process.js:218:5)
    at ChildProcess.errorhandler (child_process.js:230:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:189:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at exec (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/util/util.ts:55:3)
    at resize (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:146:16)
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:149:46
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at LinuxTargetHelper.createFromIcns (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:186:11)
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:28:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:58:11)
    at new LinuxTargetHelper (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:16:23)
    at getHelper (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/linuxPackager.ts:42:18)
    at outDir (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/linuxPackager.ts:71:122)
    at mapper (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/targetFactory.ts:29:16)
    at LinuxPackager.createTargets (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/linuxPackager.ts:71:7)
    at createTargets (/home/duzhong/Projects/MDE/node_modules/electron-builder/src/targets/targetFactory.ts:36:12)
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/packager.ts:146:41
From previous event:
    at Packager.doBuild (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/packager.js:275:11)
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/packager.ts:114:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/packager.js:227:11)
    at /home/duzhong/Projects/MDE/node_modules/electron-builder/src/builder.ts:249:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/builder.js:90:21)
    at Object.<anonymous> (/home/duzhong/Projects/MDE/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/duzhong/.nvm/versions/node/v7.5.0/bin/node" "/home/duzhong/.nvm/versions/node/v7.5.0/bin/npm" "run" "dist"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! mde@0.0.3 dist: `build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the mde@0.0.3 dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mde package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mde
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mde
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/duzhong/Projects/MDE/npm-debug.log
```

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux

Please see docs about Linux icon.
