### ISSUE TITLE
Native module is not being unpacked

### ISSUE THREAD

**Issue by pronebird** [electron-userland/electron-builder#1285]
* **13.8.2**: 

* **macOS**: 

Reporting based on the comment in source code:

```
/**
  Whether to package the application's source code into an archive, using [Electron's archive format](http://electron.atom.io/docs/tutorial/application-packaging/). Defaults to `true`.
  Node modules, that must be unpacked, will be detected automatically, you don't need to explicitly set [asarUnpack](#Config-asarUnpack) - please file issue if this doesn't work.
  */
  readonly asar?: AsarOptions | boolean | null
```

I have a native node module and it's not unpacked when bundled with the app which results in crash on startup.

**Comment by develar** [comment]
Please specify node module name. (and if you can provide project, it will be even better).

**Comment by develar** [comment]
For now, as workaround, please use `asarUnpack`

**Comment by pronebird** [comment]
I am trying to integrate my own module https://github.com/pronebird/NSEventMonitor.

My configuration:

```yml
asar: true
asarUnpack:
  - node_modules/nseventmonitor/**/*.node
```

Still get an error when running the app:

```
Uncaught Exception:
Error: Could not locate the bindings file. Tried:
 → /Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/nseventmonitor/build/nseventmonitor.node
 → /Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/nseventmonitor/build/Debug/nseventmonitor.node
 → /Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/nseventmonitor/build/Release/nseventmonitor.node
 → /Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/nseventmonitor/out/Debug/nseventmonitor.node
 → /Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/nseventmonitor/Debug/nseventmonitor.node
 → /Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/nseventmonitor/out/Release/nseventmonitor.node
 → /Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/nseventmonitor/Release/nseventmonitor.node
 → /Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/nseventmonitor/build/default/nseventmonitor.node
 → /Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/nseventmonitor/compiled/7.4.0/darwin/x64/nseventmonitor.node
    at bindings (/Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:88:9)
    at /Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/nseventmonitor/index.js:1:184
    at Object.<anonymous> (/Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar/node_modules/nseventmonitor/index.js:3:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by develar** [comment]
You also must unpack `bindings` because it is dependency of your module.

**Comment by develar** [comment]
Native node modules is not required to be unpacked, it can be executed directly from asar. Please provide original error text.

**Comment by pronebird** [comment]
The error message is above. Unpacking bindings does not help.

```iml
asarUnpack:
  - node_modules/bindings/**
  - node_modules/nseventmonitor/**/*.node
```

If I list unpacked folder, then file exists:
```ll "/Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar.unpacked/node_modules/nseventmonitor/build/Release/nseventmonitor.node"
-rwxr-xr-x  1 pronebird  staff    31K Feb 21 10:45 /Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar.unpacked/node_modules/nseventmonitor/build/Release/nseventmonitor.node
```

I tried to unpack ASAR but it's corrupted.
```
➜  Resources git:(master) ✗ asar extract app.asar app.asar.unpacked  
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/pronebird/APP/dist/mac/APP.app/Contents/Resources/app.asar.unpacked/node_modules/nseventmonitor/build/Release/NSEventMonitor.node'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.module.exports.readFileSync (/usr/local/lib/node_modules/asar/lib/disk.js:122:19)
    at Object.module.exports.extractAll (/usr/local/lib/node_modules/asar/lib/asar.js:223:24)
    at Command.<anonymous> (/usr/local/lib/node_modules/asar/bin/asar:59:15)
    at Command.listener (/usr/local/lib/node_modules/asar/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/asar/node_modules/commander/index.js:615:12)
```

**Comment by develar** [comment]
> The error message is above

Please provide error message when you don't unpack anything (without `asarUnpack`).

**Comment by develar** [comment]
If you debug own module — does it work if `asar: false`?

**Comment by pronebird** [comment]
I think the issue is related to the filename itself. Apparently my macOS volume is case insensitive, but ASAR is case sensitive. so I renamed target to lowercase `nseventmonitor` and everything works now.
