### ISSUE TITLE
Error code sign for Mac

### ISSUE THREAD

**Issue by bright-sea** [electron-userland/electron-builder#1318]
* **Version**:  15.0.0

* **Target**:  mac

Build without code sign is OK.
When add developer id application and do code sign, it will be failed with list below error:

```
Error: Command failed: codesign --sign Developer ID Application: Minghai Zhao (************) --force /Users/minghaizhao/WebstormProjects/databright/dist/mac/DataBright.app/Contents/Resources/app.asar.unpacked/node_modules/phantomjs/lib/phantom/bin/phantomjs
/Users/minghaizhao/WebstormProjects/databright/dist/mac/DataBright.app/Contents/Resources/app.asar.unpacked/node_modules/phantomjs/lib/phantom/bin/phantomjs: main executable failed strict validation

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
From previous event:
    at MacPackager.sign (/Users/minghaizhao/WebstormProjects/databright/node_modules/electron-builder/out/macPackager.js:272:11)
    at /Users/minghaizhao/WebstormProjects/databright/node_modules/electron-builder/src/macPackager.ts:82:26
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at /Users/minghaizhao/WebstormProjects/databright/node_modules/electron-builder/src/macPackager.ts:82:10
    at next (native)
From previous event:
    at MacPackager.pack (/Users/minghaizhao/WebstormProjects/databright/node_modules/electron-builder/out/macPackager.js:181:11)
    at /Users/minghaizhao/WebstormProjects/databright/node_modules/electron-builder/src/packager.ts:252:22
    at next (native)
    at /Users/minghaizhao/WebstormProjects/databright/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:54:16
    at /Users/minghaizhao/WebstormProjects/databright/node_modules/fs-extra-p/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager.doBuild (/Users/minghaizhao/WebstormProjects/databright/node_modules/electron-builder/out/packager.js:371:11)
    at /Users/minghaizhao/WebstormProjects/databright/node_modules/electron-builder/src/packager.ts:163:38
    at next (native)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/Users/minghaizhao/WebstormProjects/databright/node_modules/electron-builder/out/packager.js:263:11)
    at /Users/minghaizhao/WebstormProjects/databright/node_modules/electron-builder/src/builder.ts:217:33
    at next (native)
From previous event:
    at build (/Users/minghaizhao/WebstormProjects/databright/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/Users/minghaizhao/WebstormProjects/databright/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3



```

**Comment by develar** [comment]
Do you use latest Xcode?

I am on vacation and cannot check phantomjs module manually.

**Comment by bright-sea** [comment]
@develar Thanks for your quick response.

I will update xcode to the latest and try again. Will let you know the test result.

**Comment by bright-sea** [comment]
@develar  Just update xcode from 8.1 to 8.2 and the error is same.

I tried to revert both electron and electron-builder to previous versions and the error is still the same.

My project has no direct dependencies of phantomJS.

**Comment by develar** [comment]
`npm ls --production` To inspect from where phantomjs dep.

**Comment by bright-sea** [comment]
phantomjs is a dependncy of an old and inactive module my project used. I removed this module and everything is fine now. But phantomJS is a dependency of my project later (I need to use it to export pdf file) so this issue should be tested again. 

I attached a picture to identify the problem:

<img width="315" alt="screen shot 2017-03-02 at 3 00 48 am" src="https://cloud.githubusercontent.com/assets/2636836/23498351/639fb13c-fef5-11e6-8ec9-3b4c41c0d8f0.png">

**Comment by blahah** [comment]
@bright-sea Generally phantomjs as a node dependency is downloaded as a precompiled binary that might be pre-signed. Probably to re-sign it you would need to compile from scratch.

However, I would strongly recommend not using phantomjs - you'll add a lot of size to your final distributable files. A great alternative for a lot of use cases is to use nightmare [[website](http://www.nightmarejs.org/) : [github](https://github.com/segmentio/nightmare)], which does similar stuff to phantom except it uses electron as the engine, so you can reuse the electron binaries that are already in your app.

**Comment by bright-sea** [comment]
@blahah Thanks for your suggestion of nightmare. That's really helpful!
