### ISSUE TITLE
Getting ENOENT: no such file or directory  error when building.

### ISSUE THREAD

**Issue by matharumanpreet00** [electron-userland/electron-builder#1319]
13.11.1

win x64

Hi, Getting ENOENT: no such file or directory  error when building. Any help is really appreciated. Here is the output from the console. This is my first time submitting an issue, plz mind my formatting. 

`Error: ENOENT: no such file or directory, open 'C:\Users\Matharu\Desktop\rmt-dev\node_modules\npm-debug.log\package.json'
    at C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\src\readInstalled.ts:36:21
    at Generator.next (<anonymous>)
    at LOOP (fs.js:1611:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at _readInstalled (C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\out\readInstalled.js:85:22)
    at deps.default.map.concurrency (C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\src\readInstalled.ts:62:105)
From previous event:
    at C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\src\readInstalled.ts:62:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at _readInstalled (C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\out\readInstalled.js:85:22)
    at C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\src\readInstalled.ts:22:21
    at Generator.next (<anonymous>)
From previous event:
    at readInstalled (C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\out\readInstalled.js:34:21)
    at C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\src\yarn.ts:77:27
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\out\yarn.js:87:22)
    at C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\src\yarn.ts:16:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at installOrRebuild (C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\out\yarn.js:33:21)
    at C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\src\packager.ts:377:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\out\packager.js:457:11)
    at C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\src\packager.ts:220:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\out\packager.js:351:11)
    at C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\src\packager.ts:159:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\out\packager.js:257:11)
    at C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\src\builder.ts:217:33
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (C:\Users\Matharu\Desktop\rmt-dev\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Matharu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "package-win"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! rmt-app@0.1.0 package-win: `npm run build DEBUG=electron-builder && build DEBUG=electron-builder --win --x64`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the rmt-app@0.1.0 package-win script 'npm run build DEBUG=electron-builder && build DEBUG=electron-builder --win --x64'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rmt-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build DEBUG=electron-builder && build DEBUG=electron-builder --win --x64
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rmt-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rmt-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!        C:\Users\Matharu\Desktop\rmt-dev\npm-debug.log

**Comment by develar** [comment]
Why node module doesn't have package.json? Could you please try to install deps using yarn https://yarnpkg.com/en/? Or remove node_modules and install again (but yarn recommended in any case).

**Comment by develar** [comment]
Or just remove file node_modules\npm-debug.log

**Comment by matharumanpreet00** [comment]
Thanks @develar , deleting the npm-debug.log file fixed it.
