### ISSUE TITLE
Error when publishing to Amazon s3

### ISSUE THREAD

**Issue by Josan-Coba** [electron-userland/electron-builder#1332]
* **Version**:  15.0.0
* **Version (electron-publish)**: 15.0.0
* **Version (electron-publisher-s3)**: 15.0.0

* **Target**: linux (AppImage & .deb)

When trying to publish to Amazon S3 command fails:
```
$ AWS_ACCESS_KEY_ID="...", AWS_SECRET_ACCESS_KEY="..." npm run release
[...]
AuthorizationHeaderMalformed: The authorization header is malformed; the authorization header requires three components: Credential, SignedHeaders, and Signature.
```

* **package.json**:
```json
{
  [...]
  "scripts": {
    "release": "build"
  },
  "build": {
    [...]
    "publish": [
      {
        "bucket": "dipclient",
        "provider": "s3"
      }
    ]
  }
}
```

* **full error stack**:
```
> dinamica@1.1.2 release /home/josan/projects/dinamica
> build

No native production dependencies
Packaging for linux x64 using electron 1.6.1 to dist/linux-unpacked
Building AppImage for arch x64
Publishing to S3 (bucket: dipclient)
Building deb
[====================] 100% 0.0s | dinamica-1.1.2-x86_64.AppImage to S3
AuthorizationHeaderMalformed: The authorization header is malformed; the authorization header requires three components: Credential, SignedHeaders, and
 Signature.
    at Request.extractError (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/services/s3.js:539:35)
    at Request.callListeners (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/request.js:671:14)
    at Request.transition (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/josan/projects/dinamica/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/request.js:673:12)
    at Request.callListeners (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/request.js:671:14)
    at Request.transition (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/josan/projects/dinamica/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/josan/projects/dinamica/node_modules/aws-sdk/lib/request.js:38:9)
From previous event:
    at CancellationToken.createPromise (/home/josan/projects/dinamica/node_modules/electron-builder-http/src/CancellationToken.ts:51:5)
    at /home/josan/projects/dinamica/node_modules/electron-publisher-s3/src/s3Publisher.ts:31:43
    at next (native)
    at /home/josan/projects/dinamica/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at S3Publisher.upload (/home/josan/projects/dinamica/node_modules/electron-publisher-s3/out/s3Publisher.js:89:11)
    at /home/josan/projects/dinamica/node_modules/electron-builder/src/publish/PublishManager.ts:128:36
    at next (native)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at PublishManager.artifactCreated (/home/josan/projects/dinamica/node_modules/electron-builder/out/publish/PublishManager.js:388:11)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/home/josan/projects/dinamica/node_modules/electron-builder/src/publish/PublishManag
er.ts:100:57)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Packager.dispatchArtifactCreated (/home/josan/projects/dinamica/node_modules/electron-builder/src/packager.ts:86:23)
    at LinuxPackager.dispatchArtifactCreated (/home/josan/projects/dinamica/node_modules/electron-builder/src/platformPackager.ts:92:15)
    at /home/josan/projects/dinamica/node_modules/electron-builder/src/targets/appImage.ts:103:14
    at next (native)
    at /home/josan/projects/dinamica/node_modules/graceful-fs/polyfills.js:239:18
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at AppImageTarget.build (/home/josan/projects/dinamica/node_modules/electron-builder/out/targets/appImage.js:144:11)
    at postAsyncTasks.push.default.map.it (/home/josan/projects/dinamica/node_modules/electron-builder/src/platformPackager.ts:107:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/josan/projects/dinamica/node_modules/electron-builder/src/platformPackager.ts:107:41)
    at /home/josan/projects/dinamica/node_modules/electron-builder/src/platformPackager.ts:103:10
    at next (native)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at LinuxPackager.pack (/home/josan/projects/dinamica/node_modules/electron-builder/out/platformPackager.js:165:11)
    at /home/josan/projects/dinamica/node_modules/electron-builder/src/packager.ts:252:22
    at next (native)
    at /home/josan/projects/dinamica/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:54:16
    at /home/josan/projects/dinamica/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager.doBuild (/home/josan/projects/dinamica/node_modules/electron-builder/out/packager.js:371:11)
    at /home/josan/projects/dinamica/node_modules/electron-builder/src/packager.ts:163:38
    at next (native)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/home/josan/projects/dinamica/node_modules/electron-builder/out/packager.js:263:11)
    at /home/josan/projects/dinamica/node_modules/electron-builder/src/builder.ts:217:33
    at next (native)
From previous event:
    at build (/home/josan/projects/dinamica/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/home/josan/projects/dinamica/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by ngprasad** [comment]
Hi, can I take a look at your project? I am trying the same but for some reason it is not publishing to S3. I don't even get any error messages. Thanks.

**Comment by ngprasad** [comment]
@Josan-Coba

**Comment by Josan-Coba** [comment]
@ngprasad Shamefully the project is private right now but if you're interested in any specific section I can paste it here.

I may add that the tests I run on Windows went as you described: Everything going apparently OK but no file getting uploaded, so now I'm waiting for further advancements in #1331 to see if that changes anything.

**Comment by develar** [comment]
Should be ok now.
