### ISSUE TITLE
autoUpdater error: TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by ngprasad** [electron-userland/electron-builder#1350]
* **Version**: 13.9.0

* **Target**: Mac

I am trying to use autoUpdater to update my app but it gives me this error all the time.
**autoUpdater error: TypeError: Cannot read property 'request' of undefined**
The promise that gets returned when I call `autoUpdater.checkForUpdates()` gets rejected with reason as undefined.
I am using electron-updater version 1.8.2

@develar

**Comment by develar** [comment]
Please specify electron version.

**Comment by develar** [comment]
I guess you use old version of electron.

**Comment by ngprasad** [comment]
My electron version is 1.2.7

**Comment by develar** [comment]
Lease upgrade to latest stable 1.4.x

**Comment by navdeepsinghkhalsa** [comment]
@ngprasad @develar Hi there! Was this resolved? I'm facing the same issue with NSIS.
I made sure all the relevant plugins were updated and switched from electron-prebuilt to electron.

electron version: 1.6.2
electron-builder version: 16.6.1
electron-update version: 1.11.2

Here is the output of electron-log:

[2017-04-03 08:59:21:0329] [info] Checking for update
[2017-04-03 08:59:21:0490] [error] Error: TypeError: Cannot read property 'request' of undefined
    at cancellationToken.createPromise (C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-updater\out\electronHttpExecutor.js:85:64)
    at default (C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-builder-http\out\CancellationToken.js:74:13)
    at CancellationToken.createPromise (C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-builder-http\out\CancellationToken.js:57:16)
    at ElectronHttpExecutor.doApiRequest (C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-updater\out\electronHttpExecutor.js:84:34)
    at ElectronHttpExecutor.request (C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-builder-http\out\httpExecutor.js:102:21)
    at request (C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-builder-http\out\httpExecutor.js:210:40)
    at C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-updater\out\GenericProvider.js:68:98
    at next (native)
From previous event:
    at GenericProvider.getLatestVersion (C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-updater\out\GenericProvider.js:80:11)
    at C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:216:46
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:249:11)
    at C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:198:36
    at next (native)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:203:11)
    at NsisUpdater.checkForUpdates (C:\Program Files\SikhiToTheMax\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:182:39)
    at checkForUpdates (C:\Program Files\SikhiToTheMax\resources\app.asar\app.js:47:17)
    at EventEmitter.mainWindow.webContents.on (C:\Program Files\SikhiToTheMax\resources\app.asar\app.js:67:5)
    at emitOne (events.js:90:13)
    at EventEmitter.emit (events.js:182:7)

**Comment by navdeepsinghkhalsa** [comment]
My fault. I had an older electronVersion specified in package.json for the compatibility of an unrelated module.

**Comment by ovsokolov** [comment]
Can you explain where this compatibility version specified? It works on Mac for me but i got same error in Win.
