### ISSUE TITLE
Installed release app cannot found app-update.yml

### ISSUE THREAD

**Issue by changkun** [electron-userland/electron-builder#1367]
* **Version**: 15.4.2

* **electron-updater**: 1.9.0

* **Target**: macOS & Windows

Followed the document, here is my updater code:

```js
const electron = require('electron')
const { autoUpdater } = require('electron-updater')
const dialog = electron.dialog

let updater

function setupUpdateEvents () {
  autoUpdater.autoDownload = false
  autoUpdater.on('error', (event, error) => {
    dialog.showErrorBox('error', error)
  })
  autoUpdater.on('checking-for-update', () => {
  })
  autoUpdater.on('update-available', () => {
    dialog.showMessageBox({
      type: 'info',
      title: 'Found Updates',
      message: 'Found Updates, do you want update?',
      buttons: ['Sure', 'No']
    }, (buttonIndex) => {
      if (buttonIndex === 0) {
        autoUpdater.downloadUpdate()
      } else {
        updater.enabled = true
        updater = null
      }
    })
  })
  autoUpdater.on('update-not-available', () => {
    dialog.showMessageBox({title: 'Install Updates', message: 'No Updates Available.'})
    updater.enabled = true
    updater = null
  })
  autoUpdater.on('update-downloaded', () => {
    dialog.showMessageBox({title: 'Install Updates', message: 'Will start update, app will quit...'}, () => {
      autoUpdater.quitAndInstall()
    })
  })
}

function checkForUpdates (menuItem, focusedWindow, event) {
  updater = menuItem
  updater.enabled = false
  setupUpdateEvents()
  autoUpdater.checkForUpdates()
}

module.exports.checkForUpdates = checkForUpdates
```

Basically I was following the example given from the AutoUpdate example. The export function `checkForUpdates` is used for menuItem click callback. I signed my app and configured the pusher in package.json and successfully published to GitHub repo. Then I download the app from Github and installed into Application folder on macOS. However, it still give me an error for check the `app-update.yml`, why? Is there anything did I miss for implementation?

Here is the error:

```
Cannot check for updates: Error: ENOENT: no such file or directory, open '/Applications/MyApp.app/Contents/Resources/app-update.yml'
    at /Applications/MyApp.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:246:27
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.loadUpdateConfig (/Applications/MyApp.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:290:11)
    at /Applications/MyApp.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:153:33
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/MyApp.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:243:11)
    at /Applications/MyApp.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:143:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/MyApp.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:197:11)
    at MacUpdater.checkForUpdates (/Applications/MyApp.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:125:35)
    at checkForUpdates (/Applications/MyApp.app/Contents/Resources/app.asar/src/handlers/updater.js:49:15)
    at MenuItem.click (/Applications/MyApp.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Applications/MyApp.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)
```

**Comment by develar** [comment]
Have you custom targets for mac? Maybe you disabled zip?

**Comment by changkun** [comment]
@develar I only specified the dmg target, here is then build.mac filed:

```
"mac": {
  "category": "public.app-category.entertainment",
  "target": [ "dmg" ],
  "icon": "assets/icon.icns"
},
```

Is no zip target can be an issue for using of autoUpdater?

**Comment by develar** [comment]
zip must be — required for Squirrel.Mac.

**Comment by changkun** [comment]
@develar Thanks for the guidance, I would suggest adding this requirement on Auto Update wiki since there is no attention note for this, isn't it?

**Comment by develar** [comment]
@changkun PR welcome.
