### ISSUE TITLE
Use NSIS autoupdate get net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by divefox** [electron-userland/electron-builder#1383]
* **Version**: 
12.3.1

1.9.0

* **Target**: 
NSIS

Hi,
I build app with NSIS, and after I setup exe file, run the app on windows(win7), it emit the net error.
But the server is running. I put the updated file on the server and latest.yml and latest-mac.json. 
The error is net can't connected.But how I can fix it? Is that something wrong of my package.json?

The error is:
`
Cannot check for updates: Error: net::ERR_CONNECTION_REFUSED
    at CancellationToken.createPromise (C:\Program Files\Datayes\uqer\resources\app.asar\node_modules\electron-builder-http\src\CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (C:\Program Files\Datayes\uqer\resources\app.asar\node_modules\electron-updater\src\electronHttpExecutor.ts:39:30)
    at ElectronHttpExecutor.request (C:\Program Files\Datayes\uqer\resources\app.asar\node_modules\electron-builder-http\src\httpExecutor.ts:77:17)
    at request (C:\Program Files\Datayes\uqer\resources\app.asar\node_modules\electron-builder-http\src\httpExecutor.ts:212:38)
    at C:\Program Files\Datayes\uqer\resources\app.asar\node_modules\electron-updater\src\GenericProvider.ts:31:22
    at Generator.next (<anonymous>)
From previous event:
    at GenericProvider.getLatestVersion (C:\Program Files\Datayes\uqer\resources\app.asar\node_modules\electron-updater\out\GenericProvider.js:80:11)
    at C:\Program Files\Datayes\uqer\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:163:6
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files\Datayes\uqer\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:202:7)
    at C:\Program Files\Datayes\uqer\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:145:15
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Program Files\Datayes\uqer\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:149:4)
    at NsisUpdater.checkForUpdates (C:\Program Files\Datayes\uqer\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:125:35)
    at EventEmitter.<anonymous> (C:\Program Files\Datayes\uqer\resources\app.asar\app.js:720:17)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at WebContents.<anonymous> (C:\Program Files\Datayes\uqer\resources\electron.asar\browser\api\web-contents.js:240:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
`

And parts of my package.json is:
"build": {
    "appId": "com.electronupdaterexample",
    "mac": {
      "category": "your.app.category.type",
      "target": [
        "zip",
        "dmg"
      ]
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "menuCategory": true,
      "runAfterFinish": false
    },
    "publish": [
      {
        "provider": "generic",
        "owner": "mercury",
        "repo": "uqer",
        "url": "http://127.0.0.1:8007/update/${os}_${arch}"
      }
    ]
  },

The server is python SimpleHTTPServer,I put the files on update directory.

And the latest.yml is:

version: 3.35.0
releaseDate: '2017-03-17T08:18:47.230Z'
githubArtifactName: test-Setup-3.35.0.exe
path: test Setup 3.35.0.exe
sha2: 1e14c78badb4066c79fafbde0a333d5447e0008a981209aaecf7c6370c9be54f

the app-update.yml is:

provider: generic
owner: divefox
repo: test
url: 'http://127.0.0.1:8007/update/win_x64'

How can I fix it? 
What is the problem?
Is the server not correct? What is you suggest to the server?
Thank you very much!

**Comment by develar** [comment]
Maybe problem in the http protocol (https should be, but http should be also be supported). Could you please upgrade electron-builder to 15.6.1?

**Comment by divefox** [comment]
@develar Thank you for your reply！
I updated to the latest version of electron-builder. I modify the 'Config' instead of 'build' in the package.json. Others content is the same.
When I run publish.sh, it generate the file. But after I setup the file in the window 7 and run it.It also catch the problem of 'Error: ENOENT: no such file or directory '. I find because app-update.yml file is not generate in the resource directory! But the 12.3.1 version have!
Then there is another problem is ,the NSIS option have not take effect!  But the 12.3.1 version have!

What is the problem?
Wait for your reply!
Thank you very much.

**Comment by develar** [comment]
>  I setup the file in the window 7 and run it.It also catch the problem of 'Error: ENOENT: no such file or directory '.

You cannot run `publish.sh` on windows.  Execute directly `node_modules/.bin/build --win --mac -p always` https://github.com/iffy/electron-updater-example/issues/6

**Comment by caoweiping** [comment]
No native production dependencies
Packaging for win32 x64 using electron 1.6.2 to release\win-unpacked
⚠️  Application icon is not set, default Electron icon will be used
Building NSIS installer
  Packaging NSIS installer for arch x64
Publishing to null
Publishing to null

________________________________________
nothing published ??

**Comment by caoweiping** [comment]
attach my config :
"build": {
    "appId": "aaaaa",
    "directories": {
      "output": "release",
      "app": "dist"
    },
    "mac": {
      "category": "your.app.category.type",
      "target": [
        "zip",
        "dmg"
      ]
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "menuCategory": true,
      "runAfterFinish": false
    },
    "publish": [
      {
        "provider": "generic",
        "url": "http://172.16.0.97:8080/",
        "channel": "alpha"
      }
    ]
  },

**Comment by develar** [comment]
@caoweiping Yes, we don't publish to generic provider. I will check why "Publishing to null" printed.

**Comment by divefox** [comment]
@develar 
`You cannot run publish.sh on windows. Execute directly node_modules/.bin/build --win --mac -p always iffy/electron-updater-example#6`

I didn't run the publish.sh on Windows. I do it on OSX.The generate file exe I run it on Windows.

Wether I execute publish.sh or node_modules/.bin/build --win --mac -p always on OSX, it also wrong to me.
The same error as I sayed above...
