### ISSUE TITLE
Error raised when update is available

### ISSUE THREAD

**Issue by danielwestendorf** [electron-userland/electron-builder#1395]
electron-builder* **16.2.0**: 

electron-updater* **1.11.0**: 

I'm publishing updates to S3. When checking for updates via the [suggested code](https://github.com/electron-userland/electron-builder/wiki/Auto-Update#manual-update) and no update is available, the expected dialog is returned. When an update is available, however, an error is raised in the error dialog.

```
Cannot check for updates: TypeError: Error processing argument at index 1, conversion failure from undefined
    at Object.showErrorBox (/Applications/Auditor.app/Contents/Resources/electron.asar/browser/api/dialog.js:282:36)
    at MacUpdater.autoUpdater.on (/Applications/Auditor.app/Contents/Resources/app.asar/update.js:8:10)
    at emitOne (events.js:101:20)
    at MacUpdater.emit (events.js:188:7)
    at AutoUpdater.MacUpdater.nativeUpdater.on.it (/Applications/Auditor.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:18:12)
    at emitTwo (events.js:106:13)
    at AutoUpdater.emit (events.js:191:7)
    at MacUpdater.onUpdateAvailable (/Applications/Auditor.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:29:24)
    at /Applications/Auditor.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:194:10
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Auditor.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:246:11)
    at /Applications/Auditor.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:149:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/Auditor.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:200:11)
    at MacUpdater.checkForUpdates (/Applications/Auditor.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:131:35)
    at checkForUpdates (/Applications/Auditor.app/Contents/Resources/app.asar/update.js:50:15)
    at MenuItem.click (/Applications/Auditor.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Applications/Auditor.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)
```

The `latest.json` uploaded to S3 is as follows:

```json
{
  "version": "0.1.2",
  "releaseDate": "2017-03-22T22:42:50.236Z",
  "url": "https://bucket.s3.amazonaws.com/mac/Auditor-0.1.2-mac.zip"
}
```

Is this a user malfunction? Is there anything more I can do to troubleshoot the issue?

**Comment by develar** [comment]
Replace line 8 to `dialog.showErrorBox('Error: ', error == null ? "unknown" : (error.stack || error).toString())`
