### ISSUE TITLE
authenticode timestamping failed

### ISSUE THREAD

**Issue by hugosmarques** [electron-userland/electron-builder#1414]
* **Lastest**: 

Latest

* **MAC and WIN**: 

Hello all, sometimes when i use electron-builder with a signing code file (pfx) i get the following error: authenticode timestamping failed

the error only accurs sometimes, im building in MAC and this error appear when he trys to sign the code for windows exe file

if i run again after a while the error disappear, but after if i try to build again sometimes the error happen again.

**Comment by hugosmarques** [comment]
The detailed error is:

Signing FotoNavarras.exe (certificate file: "/Users/hugomarques/vsts-agent-mac/_work/1/s/sunpicsdesktopapp.pfx")
Error: Exit code: 255. Command failed: /Users/hugomarques/Library/Caches/electron-builder/winCodeSign/winCodeSign-1.7.0/darwin/ci/osslsigncode -in /Users/hugomarques/vsts-agent-mac/_work/1/s/dist/win-ia32-unpacked/FotoNavarras.exe -out /Users/hugomarques/vsts-agent-mac/_work/1/s/dist/win-ia32-unpacked/FotoNavarras-signed-sha1.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -pkcs12 /Users/hugomarques/vsts-agent-mac/_work/1/s/sunpicsdesktopapp.pfx -h sha1 -n FotoNavarras -pass 2606399bb600dad973abebda1ca63a2929083494c73a8370fb392c7b25c72205 (sha256 hash) failure: Couldn't resolve host name
authenticode timestamping failed
Failed
CURL failure: Couldn't resolve host name
authenticode timestamping failed
Failed
    at /usr/local/lib/node_modules/electron-builder/node_modules/electron-builder-util/src/util.ts:75:16
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)
From previous event:
    at exec (/usr/local/lib/node_modules/electron-builder/node_modules/electron-builder-util/src/util.ts:53:3)
    at /usr/local/lib/node_modules/electron-builder/src/windowsCodeSign.ts:136:16
From previous event:
    at spawnSign (/usr/local/lib/node_modules/electron-builder/out/windowsCodeSign.js:108:22)
    at /usr/local/lib/node_modules/electron-builder/src/windowsCodeSign.ts:60:11
    at Generator.next (<anonymous>)
From previous event:
    at sign (/usr/local/lib/node_modules/electron-builder/out/windowsCodeSign.js:44:21)
    at WinPackager.doSign (/usr/local/lib/node_modules/electron-builder/src/winPackager.ts:200:12)
    at /usr/local/lib/node_modules/electron-builder/src/winPackager.ts:183:16
From previous event:
    at WinPackager.sign (/usr/local/lib/node_modules/electron-builder/out/winPackager.js:258:11)
    at /usr/local/lib/node_modules/electron-builder/src/winPackager.ts:228:16
From previous event:
    at WinPackager.signAndEditResources (/usr/local/lib/node_modules/electron-builder/out/winPackager.js:283:11)
    at /usr/local/lib/node_modules/electron-builder/src/winPackager.ts:234:16
From previous event:
    at WinPackager.postInitApp (/usr/local/lib/node_modules/electron-builder/out/winPackager.js:292:11)
    at /usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:223:148
From previous event:
    at WinPackager.doPack (/usr/local/lib/node_modules/electron-builder/out/platformPackager.js:287:11)
    at /usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:103:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/usr/local/lib/node_modules/electron-builder/out/platformPackager.js:171:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:257:24
From previous event:
    at Packager.doBuild (/usr/local/lib/node_modules/electron-builder/out/packager.js:379:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:170:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Packager.build (/usr/local/lib/node_modules/electron-builder/out/packager.js:274:11)
    at /usr/local/lib/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/usr/local/lib/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:542:3
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! FotoNavarras@1.0.5 dist: `build -mw --ia32 -p always`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the FotoNavarras@1.0.5 dist script 'build -mw --ia32 -p always'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the FotoNavarras package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build -mw --ia32 -p always
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs FotoNavarras
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls FotoNavarras
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hugomarques/vsts-agent-mac/_work/1/s/npm-debug.log

**Comment by develar** [comment]
> CURL failure: Couldn't resolve host name

It is your network failure. electron-builder can only retry attempt to sign.
