### ISSUE TITLE
Problem while trying to build

### ISSUE THREAD

**Issue by Qti3e** [electron-userland/electron-builder#1424]
Hi
When I'm trying to build my application, It fails with a long error and it's saying `xx/address_bar.js/package.json` is not a directoty, I dont know what is address_bar.js.
```
Error: ENOTDIR: not a directory, open '/home/qti3e/projects/Slye/electron/node_modules/address_bar.js/package.json'
    at Error (native)
From previous event:
    at /home/qti3e/projects/Slye/electron/node_modules/electron-builder/src/readInstalled.ts:36:21
    at next (native)
    at LOOP (fs.js:1758:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at _readInstalled (/home/qti3e/projects/Slye/electron/node_modules/electron-builder/out/readInstalled.js:85:22)
    at deps.default.map.concurrency (/home/qti3e/projects/Slye/electron/node_modules/electron-builder/src/readInstalled.ts:62:105)
From previous event:
    at /home/qti3e/projects/Slye/electron/node_modules/electron-builder/src/readInstalled.ts:62:38
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at _readInstalled (/home/qti3e/projects/Slye/electron/node_modules/electron-builder/out/readInstalled.js:85:22)
    at /home/qti3e/projects/Slye/electron/node_modules/electron-builder/src/readInstalled.ts:22:21
    at next (native)
From previous event:
    at readInstalled (/home/qti3e/projects/Slye/electron/node_modules/electron-builder/out/readInstalled.js:34:21)
    at /home/qti3e/projects/Slye/electron/node_modules/electron-builder/src/platformPackager.ts:502:27
    at next (native)
From previous event:
    at dependencies (/home/qti3e/projects/Slye/electron/node_modules/electron-builder/out/platformPackager.js:31:21)
    at /home/qti3e/projects/Slye/electron/node_modules/electron-builder/src/platformPackager.ts:155:9
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

```

I'm using:
```
npm ERR! Linux 4.8.6-300.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dist"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Slye@0.0.1-alpha dist: `build -mwl --x64 --ia32`
npm ERR! Exit status 255
```

Thanks

**Comment by develar** [comment]
Do you use latest electron-builder?

**Comment by develar** [comment]
Workaround: remove node_modules and install `npm install` again.

**Comment by Qti3e** [comment]
I checked my node_module folder and I found the address_bar.js file.
I removed it and problem fixed.
