### ISSUE TITLE
Cannot copy files from parent directory of build output

### ISSUE THREAD

**Issue by kube** [electron-userland/electron-builder#1482]
* **Version**: 17.0.1
* **Target**: Mac and Windows

My root directory looks like this:
```
- build/
  - app/              # Output from Webpack
    - main.js
    - renderer.js
    - index.html
  - dist/             # Output from Electron Builder
- configs/
  - pack.yml
- src/
- package.json
```

#### `configs/pack.yml`
```yml
directories:
  output: build/dist
files:
  - build/app/**/*.js
  - build/app/**/*.html
asar: false
```

#### `package.json`
```json
{
  "main": "./build/app/main.js"
}
```

## Problem

When I run Electron Builder, the output won't contain any file except package.json.

Just to test, when I replace `files` with `src/**/*.ts`, Electron Builder effectively copies all my sources to `dist/mac/App.app/Resources/app`.

The problem seems to come from the fact that the `build/app/` folder where I want to output Electron app is in the same `build/` folder than `build/dist`.

So I get this error during build:
```
Error: Application entry file "build/app/main.js" does not exist. Seems like a wrong configuration.
```

A solution would be to create another **package.json** in the `build/` folder, and set it as the root of the project, but I don't really the idea of duplicating the package.json.

Is there any solution for this, just to enable the copy? If not, could this be patched?

**Comment by develar** [comment]
Thanks for clear report. 
Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by kube** [comment]
Here it is:

Normally both `forceCodeSigning` and `asar` are set to `true`:

```
yarn fastpack:mac v0.21.3
$ build --dir --mac --config=configs/pack.yml 
Using configs/pack.yml configuration file
Wed, 19 Apr 2017 20:33:32 GMT electron-builder Effective config: {
  "appId": "com.myproject.myproject",
  "copyright": "Copyright © 2017 MyProject",
  "productName": "MyProject",
  "directories": {
    "output": "build/dist"
  },
  "files": [
    "build/app/**/*.js",
    "build/app/**/*.html"
  ],
  "asar": false,
  "fileAssociations": [
    {
      "ext": [
        "myext"
      ],
      "name": "myext",
      "icon": "resources/icons/FileIcon.icns",
      "role": "Editor",
      "isPackage": true
    }
  ],
  "forceCodeSigning": false,
  "mac": {
    "icon": "resources/icons/icon.icns",
    "type": "distribution"
  },
  "win": {
    "target": [
      "nsis"
    ],
    "icon": "resources/icons/icon.ico"
  },
  "dmg": {
    "background": "resources/background.png",
    "icon": "resources/icons/icon.icns"
  },
  "nsis": {
    "oneClick": false,
    "perMachine": true,
    "runAfterFinish": true,
    "deleteAppDataOnUninstall": true
  }
}
No native production dependencies
Warning: Packaging using asar archive is disabled — it is strongly not recommended.
Please enable asar and use asarUnpack to unpack files that must be externally available.
Packaging for darwin x64 using electron 1.6.6 to build/dist/mac
Wed, 19 Apr 2017 20:33:38 GMT electron-builder Spawning /Users/johndoe/MyProject/DesktopApp/node_modules/7zip-bin-mac/7za x -bd /Users/johndoe/Library/Caches/electron/electron-v1.6.6-darwin-x64.zip -o/Users/johndoe/MyProject/DesktopApp/build/dist/mac

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 46095942 bytes (44 MiB)

Extracting archive: /Users/johndoe/Library/Caches/electron/electron-v1.6.6-darwin-x64.zip
--
Path = /Users/johndoe/Library/Caches/electron/electron-v1.6.6-darwin-x64.zip
Type = zip
Physical Size = 46095942

Everything is Ok

Folders: 143
Files: 181
Size:       117407107
Compressed: 46095942
Wed, 19 Apr 2017 20:33:40 GMT electron-builder /Users/johndoe/MyProject/DesktopApp/node_modules/7zip-bin-mac/7za (25932) exited with code 0
Wed, 19 Apr 2017 20:33:41 GMT electron-builder Dev or extraneous dependencies: ../electron-builder.yml, ../electron-builder.json, ../electron-builder.json5, 7zip-bin, 7zip-bin-mac, @types/base16, @types/classnames, @types/electron, @types/draft-js, @types/jest, @types/js-yaml, yargs-parser, yauzl, yargs, yallist, xtend, xmldom, y18n, xmlbuilder, xml-name-validator, xml-char-classes, xdg-basedir, write-file-atomic, wrappy, wrap-ansi, worker-farm, wordwrap, window-size, widest-line, wide-align, which-module, which, whatwg-url, whatwg-encoding, websocket-extensions, websocket-driver, webpack-sources, webpack-merge, webpack-dev-server, whatwg-url/node_modules/webidl-conversions, webpack-dev-middleware, webpack, wbuf, webidl-conversions, watch, watchpack, walker, vm-browserify, vinyl, verror, webpack/node_modules/acorn, webpack/node_modules/async, vary, validate-npm-package-license, uuid-1345, watchpack/node_modules/async, utils-merge, utila, util-deprecate, util, utf8-byte-length, url-parse-lax, url-parse, url, upper-case, update-notifier, unzip-response, unpipe, unique-string, util/node_modules/inherits, uid-number, url/node_modules/punycode, uglify-to-browserify, uglify-js, typescript, typedarray, type-is, type-check, tweetnacl, tunnel-agent, uglify-js/node_modules/camelcase, uglify-js/node_modules/cliui, uglify-js/node_modules/wordwrap, uglify-js/node_modules/yargs, tty-browserify, tsutils, tslint-loader, tslint, tsconfig, ts-loader, ts-jest, truncate-utf8-bytes, trim-right, trim-newlines, tslint-loader/node_modules/loader-utils, tslint/node_modules/resolve, tsconfig/node_modules/strip-bom, ts-loader/node_modules/loader-utils, tr46, tree-kill, ts-jest/node_modules/yargs, ts-jest/node_modules/yargs-parser, tough-cookie, toposort, to-fast-properties, to-arraybuffer, tmpl, timers-browserify, timed-out, time-stamp, through2, throttleit, throat, test-exclude, tempfile, term-size, tar-pack, tar, tapable, through2/node_modules/readable-stream, symbol-tree, supports-color, tar-pack/node_modules/rimraf, tempfile/node_modules/uuid, sumchecker, strip-json-comments, strip-indent, strip-eof, strip-bom, strip-ansi, stringstream, string_decoder, string.prototype.codepointat, string-width, string-length, stream-http, stream-browserify, statuses, stat-mode, strip-ansi/node_modules/ansi-regex, stackframe, sshpk, speedometer, spdy-transport, spdy, spdx-license-ids, spdx-expression-parse, spdx-correct, spawn-command, sparkles, source-map-loader, source-list-map, sntp, sockjs-client, sockjs, slide, slash, single-line-log, signal-exit, shellwords, shebang-regex, source-map-loader/node_modules/async, source-map-loader/node_modules/source-map, sockjs-client/node_modules/faye-websocket, shebang-command, sockjs/node_modules/uuid, sha.js, setprototypeof, set-immediate-shim, serve-static, set-blocking, serve-index, send, semver-diff, select-hose, sanitize-filename, sane, send/node_modules/debug, serve-index/node_modules/debug, serve-index/node_modules/ms, send/node_modules/http-errors, rx, safe-buffer, ripemd160, rimraf, right-align, sane/node_modules/fb-watchman, sane/node_modules/bser, resolve, requires-port, require-main-filename, require-directory, request, replace-ext, repeating, repeat-string, repeat-element, renderkid, remove-trailing-separator, remap-istanbul, relateurl, registry-url, registry-auth-token, regex-cache, redent, redbox-react, readdirp, readable-stream, read-pkg-up, read-pkg, react-proxy, react-hot-loader, readable-stream/node_modules/string_decoder, react-deep-force-update, rc, range-parser, randombytes, react-hot-loader/node_modules/source-map, querystringify, randomatic, querystring-es3, querystring, qs, punycode, public-encrypt, prr, pseudomap, proxy-addr, process-nextick-args, progress-stream, process, private, pretty-error, pretty-format, pretty-bytes, preserve, prepend-http, prelude-ls, progress-stream/node_modules/isarray, progress-stream/node_modules/readable-stream, progress-stream/node_modules/through2, progress-stream/node_modules/xtend, portfinder, plist, pinkie, pinkie-promise, pify, pretty-format/node_modules/ansi-styles, pretty-error/node_modules/utila, pretty-format/node_modules/color-convert, performance-now, pend, pbkdf2, path-type, path-to-regexp, path-parse, path-key, path-is-absolute, path-exists, path-browserify, parse5, parseurl, parse-glob, parse-json, parse-color, parse-asn1, param-case, package-json, p-locate, pako, p-limit, osenv, os-tmpdir, os-locale, os-homedir, original, os-browserify, optionator, opn, optimist, once, on-headers, on-finished, obuf, object.omit, object-keys, original/node_modules/url-parse, optimist/node_modules/minimist, optimist/node_modules/wordwrap, oauth-sign, nwmatcher, number-is-nan, nth-check, nugget, npm-run-path, npmlog, normalize-path, normalize-package-data, nopt, node-pre-gyp, node-notifier, node-libs-browser, node-int64, node-forge, node-emoji, no-case, negotiator, natural-compare, ncname, nan, multipipe, node-pre-gyp/node_modules/rimraf, node-pre-gyp/node_modules/nopt, minimist, minimatch, mkdirp, minimalistic-crypto-utils, min-document, minimalistic-assert, mime-types, mime, mime-db, micromatch, miller-rabin, merge-descriptors, methods, merge, mkdirp/node_modules/minimist, meow, memory-fs, media-typer, map-obj, makeerror, lru-cache, macaddress, lowercase-keys, lower-case, loud-rejection, lodash.template, longest, lodash.templatesettings, lodash.restparam, lodash.pickby, lodash.partition, lodash.keys, lodash.isarray, lodash.isarguments, lodash.includes, lodash.escape, lodash._root, lodash.assign, lodash._reescape, lodash._reinterpolate, lodash._reevaluate, lodash._isiterateecall, lodash._basevalues, lodash._basetostring, lodash._basecopy, locate-path, loader-utils, loader-runner, load-json-file, levn, leven, lcid, lazy-req, latest-version, lazy-cache, locate-path/node_modules/path-exists, jsprim, kind-of, klaw, jsonify, json5, json3, json-stringify-safe, json-stable-stringify, json-loader, json-schema, jsesc, jsdom, jsbn, jodid25519, jest-util, jest-validate, jest-snapshot, jest-runtime, jest-resolve-dependencies, jest-resolve, jest-regex-util, jest-message-util, jest-mock, jest-matchers, jest-matcher-utils, jest-runtime/node_modules/strip-bom, jest-jasmine2, jest-resolve/node_modules/resolve, jest-environment-node, jest-file-exists, jest-haste-map, jest-environment-jsdom, jest-diff, jest-config, jest-cli, jest-changed-files, istanbul-lib-source-maps, jest, istanbul-reports, istanbul-lib-report, istanbul-lib-instrument, istanbul-lib-coverage, istanbul-lib-hook, istanbul-api, istanbul, isstream, isobject, isexe, isarray, isbinaryfile, istanbul-api/node_modules/async, is-utf8, is-windows, is-typedarray, istanbul/node_modules/glob, is-retry-allowed, is-redirect, is-primitive, is-posix-bracket, is-obj, is-number, is-npm, is-glob, is-finite, is-fullwidth-code-point, is-extglob, is-extendable, is-equal-shallow, is-dotfile, is-ci, is-builtin-module, is-buffer, is-binary-path, is-arrayish, ipaddr.js, invert-kv, interpret, ini, inherits, inflight, indexof, indent-string, imurmurhash, immutable, iconv-lite, ieee754, https-browserify, http-signature, http-proxy-middleware, http-proxy, http-errors, http-deceiver, htmlparser2, html-webpack-plugin, html-minifier, http-signature/node_modules/assert-plus, html-entities, http-proxy-middleware/node_modules/is-extglob, http-proxy-middleware/node_modules/is-glob, html-encoding-sniffer, http-errors/node_modules/setprototypeof, hpack.js, htmlparser2/node_modules/readable-stream, htmlparser2/node_modules/isarray, html-minifier/node_modules/commander, hosted-git-info, home-path, home-or-tmp, hoek, hmac-drbg, he, hawk, hash.js, has-unicode, has-gulplog, has-flag, has-ansi, har-validator, har-schema, handlebars, handle-thing, gulp-util, gulplog, growly, graceful-readlink, has-ansi/node_modules/ansi-regex, got, handlebars/node_modules/source-map, glogg, gulp-util/node_modules/object-assign, globals, glob-parent, global, glob-base, glob-all, glob, getpass, get-stream, get-stdin, get-caller-file, gauge, global/node_modules/process, fstream-ignore, glob-all/node_modules/minimist, glob-all/node_modules/yargs, fstream, fsevents, fs.realpath, fresh, forwarded, form-data, fstream/node_modules/rimraf, fsevents/node_modules/ansi-styles, fsevents/node_modules/abbrev, fsevents/node_modules/ansi-regex, fsevents/node_modules/aproba, fsevents/node_modules/are-we-there-yet, fsevents/node_modules/asn1, fsevents/node_modules/assert-plus, fsevents/node_modules/asynckit, for-own, forever-agent, for-in, findup-sync, find-up, finalhandler, fill-range, fsevents/node_modules/xtend, fsevents/node_modules/wrappy, fsevents/node_modules/wide-align, fsevents/node_modules/verror, fsevents/node_modules/uuid, fsevents/node_modules/util-deprecate, fsevents/node_modules/uid-number, fsevents/node_modules/tweetnacl, fileset, filename-regex, file-loader, fd-slicer, findup-sync/node_modules/glob, fb-watchman, faye-websocket, fast-levenshtein, fsevents/node_modules/tunnel-agent, fsevents/node_modules/tough-cookie, fsevents/node_modules/tar-pack, fsevents/node_modules/tar, fsevents/node_modules/supports-color, fsevents/node_modules/strip-json-comments, fsevents/node_modules/strip-ansi, fsevents/node_modules/stringstream, fancy-log, file-loader/node_modules/loader-utils, extsprintf, extract-zip, extglob, extend, fsevents/node_modules/string_decoder, fsevents/node_modules/string-width, fsevents/node_modules/sshpk, fsevents/node_modules/sntp, fsevents/node_modules/signal-exit, fsevents/node_modules/set-blocking, fsevents/node_modules/tar-pack/node_modules/once, fsevents/node_modules/tar-pack/node_modules/readable-stream, fsevents/node_modules/semver, expand-range, express, expand-brackets, extract-zip/node_modules/debug, extract-zip/node_modules/minimist, execa, extract-zip/node_modules/mkdirp, evp_bytestokey, exec-sh, fsevents/node_modules/rimraf, fsevents/node_modules/request, fsevents/node_modules/readable-stream, fsevents/node_modules/rc, fsevents/node_modules/sshpk/node_modules/assert-plus, eventsource, fsevents/node_modules/punycode, fsevents/node_modules/qs, fsevents/node_modules/process-nextick-args, events, express/node_modules/debug, etag, eventemitter3, esutils, estraverse, fsevents/node_modules/pinkie-promise, fsevents/node_modules/pinkie, fsevents/node_modules/path-is-absolute, esprima, fsevents/node_modules/rc/node_modules/minimist, escodegen, fsevents/node_modules/once, fsevents/node_modules/object-assign, escape-string-regexp, fsevents/node_modules/oauth-sign, fsevents/node_modules/number-is-nan, escape-html, es6-promise, error-stack-parser, error-ex, errno, fsevents/node_modules/npmlog, fsevents/node_modules/nopt, fsevents/node_modules/node-pre-gyp, env-paths, fsevents/node_modules/ms, escodegen/node_modules/source-map, fsevents/node_modules/mkdirp, fsevents/node_modules/minimist, fsevents/node_modules/minimatch, fsevents/node_modules/mime-types, entities, enhanced-resolve, encodeurl, emojis-list, fsevents/node_modules/mime-db, fsevents/node_modules/jsprim, elliptic, fsevents/node_modules/jsonpointer, fsevents/node_modules/json-stringify-safe, electron-publish, fsevents/node_modules/json-schema, electron-osx-sign, fsevents/node_modules/jsbn, fsevents/node_modules/jodid25519, fsevents/node_modules/isstream, electron-download-tf, electron-download, fsevents/node_modules/isarray, fsevents/node_modules/is-typedarray, electron-builder-util, fsevents/node_modules/is-property, fsevents/node_modules/is-my-json-valid, electron-publish/node_modules/electron-builder-util, electron-builder-http, electron-builder-core, fsevents/node_modules/is-fullwidth-code-point, fsevents/node_modules/ini, fsevents/node_modules/inherits, fsevents/node_modules/inflight, electron-download-tf/node_modules/path-exists, electron-download-tf/node_modules/sumchecker, electron-download/node_modules/fs-extra, fsevents/node_modules/http-signature, electron-builder, electron, fsevents/node_modules/hoek, fsevents/node_modules/hawk, ee-first, ecc-jsbn, duplexer3, fsevents/node_modules/has-unicode, fsevents/node_modules/has-ansi, fsevents/node_modules/har-validator, fsevents/node_modules/graceful-readlink, fsevents/node_modules/graceful-fs, duplexer2, dot-prop, electron-builder/node_modules/ajv, electron-builder/node_modules/ajv-keywords, electron-builder/node_modules/electron-builder-http, electron-builder/node_modules/yargs, electron-builder/node_modules/yargs-parser, fsevents/node_modules/glob, domutils, domhandler, domelementtype, fsevents/node_modules/getpass, fsevents/node_modules/generate-object-property, fsevents/node_modules/gauge, fsevents/node_modules/generate-function, fsevents/node_modules/fstream-ignore, fsevents/node_modules/fstream, fsevents/node_modules/fs.realpath, duplexer2/node_modules/isarray, duplexer2/node_modules/readable-stream, domain-browser, dom-walk, dom-serializer, dom-converter, diffie-hellman, fsevents/node_modules/form-data, fsevents/node_modules/forever-agent, fsevents/node_modules/getpass/node_modules/assert-plus, fsevents/node_modules/extsprintf, fsevents/node_modules/extend, fsevents/node_modules/ecc-jsbn, fsevents/node_modules/escape-string-regexp, fsevents/node_modules/delegates, diff, detect-indent, destroy, des.js, depd, delegates, dom-serializer/node_modules/domelementtype, fsevents/node_modules/delayed-stream, fsevents/node_modules/deep-extend, fsevents/node_modules/debug, fsevents/node_modules/dashdash, fsevents/node_modules/cryptiles, fsevents/node_modules/core-util-is, fsevents/node_modules/console-control-strings, delayed-stream, fsevents/node_modules/concat-map, default-require-extensions, deep-is, deep-extend, decamelize, dateformat, fsevents/node_modules/commander, fsevents/node_modules/combined-stream, fsevents/node_modules/code-point-at, fsevents/node_modules/chalk, fsevents/node_modules/caseless, fsevents/node_modules/buffer-shims, date-now, date-fns, dashdash, currently-unhandled, fsevents/node_modules/dashdash/node_modules/assert-plus, cuint, fsevents/node_modules/brace-expansion, fsevents/node_modules/boom, fsevents/node_modules/bcrypt-pbkdf, fsevents/node_modules/block-stream, cssom, cssstyle, css-what, css-select, fsevents/node_modules/aws4, fsevents/node_modules/aws-sign2, fsevents/node_modules/balanced-match, crypto-random-string, crypto-browserify, cryptiles, cross-spawn-async, cross-spawn, cross-env, create-hmac, css-select/node_modules/domutils, create-hash, create-error-class, create-ecdh, core-util-is, cookie-signature, cookie, convert-source-map, content-type-parser, content-type, content-disposition, constants-browserify, console-control-strings, console-browserify, connect-history-api-fallback, configstore, concurrently, concat-stream, concat-map, compression, compressible, compare-version, commander, combined-stream, concurrently/node_modules/ansi-styles, concurrently/node_modules/chalk, concurrently/node_modules/has-ansi, concurrently/node_modules/strip-ansi, concat-stream/node_modules/readable-stream, colors, color-name, compression/node_modules/debug, compression/node_modules/ms, color-convert, code-point-at, co, clone-stats, concurrently/node_modules/chalk/node_modules/supports-color, clone, cliui, cli-boxes, clean-webpack-plugin, clean-css, cipher-base, ci-info, chromium-pickle-js, chokidar, chalk, center-align, caseless, capture-stack-trace, camelcase-keys, camelcase, camel-case, callsites, bytes, builtin-status-codes, chalk/node_modules/supports-color, builtin-modules, buffer-xor, camelcase-keys/node_modules/camelcase, buffer-shims, buffer, bser, browserify-zlib, browserify-sign, browserify-rsa, browserify-des, browserify-cipher, browserify-aes, browser-resolve, brorand, braces, brace-expansion, boxen, boom, boolbase, bn.js, block-stream, binary-extensions, boxen/node_modules/is-fullwidth-code-point, boxen/node_modules/camelcase, boxen/node_modules/string-width, big.js, beeper, bcrypt-pbkdf, batch, base64-js, balanced-match, babylon, babel-types, babel-traverse, babel-template, babel-register, babel-preset-jest, babel-plugin-jest-hoist, babel-messages, babel-plugin-istanbul, babel-jest, babel-helpers, babel-generator, babel-core, babel-code-frame, aws4, aws-sign2, asynckit, babel-plugin-istanbul/node_modules/find-up, async-each, async, assert-plus, assert, asn1.js, asn1, arrify, array-unique, array-uniq, array-flatten, array-find-index, array-equal, array-differ, arr-diff, arr-flatten, aproba, are-we-there-yet, append-transform, anymatch, ansi-styles, ansi-regex, ansi-html, ansi-align, ansi-escapes, amdefine, align-text, ajv-keywords, ajv, acorn-dynamic-import, acorn-globals, acorn, accepts, abbrev, abab, @types/webpack-merge, @types/webpack-env, @types/webpack, @types/uuid, @types/uglify-js, @types/tapable, @types/source-map, @types/redux-devtools-log-monitor, @types/redux-devtools-dock-monitor, @types/redux-devtools, @types/redux, @types/react-redux, @types/react, @types/react-hot-loader, @types/react-dom, @types/node
Wed, 19 Apr 2017 20:33:41 GMT electron-builder Copying /Users/johndoe/MyProject/DesktopApp to /Users/johndoe/MyProject/DesktopApp/build/dist/mac/Electron.app/Contents/Resources/app
Error: Application entry file "build/app/main.js" does not exist. Seems like a wrong configuration.
    at /Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/src/platformPackager.ts:311:15
From previous event:
    at MacPackager.checkFileInPackage (/Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/out/platformPackager.js:359:11)
    at /Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/src/platformPackager.ts:335:16
From previous event:
    at MacPackager.sanityCheckPackage (/Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/out/platformPackager.js:377:11)
    at /Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/src/platformPackager.ts:229:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at MacPackager.doPack (/Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/out/platformPackager.js:272:11)
    at /Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/src/macPackager.ts:81:71
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/out/macPackager.js:181:11)
    at /Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/src/packager.ts:257:24
From previous event:
    at Packager.doBuild (/Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/out/packager.js:379:11)
    at /Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/src/packager.ts:170:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/out/packager.js:274:11)
    at /Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/Users/johndoe/MyProject/DesktopApp/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
error Command failed with exit code 255.
```

**Comment by kube** [comment]
Ok, the problem seems to come from the fact that I use `build/` as parent folder for both input and output.

When I use `_build/` instead, everything works as expected.
Electron Builder takes input from `_build/app` and outputs app in `_build/dist`.

But I don't understand why. I rapidly took a look at the code of `electron-core`, but there's no direct reference to a particular `build` folder.

**Comment by develar** [comment]
Because `build` it is build resources directory. https://github.com/electron-userland/electron-builder/wiki/electron-builder-core#metadatadirectories You need to change it also. Set `buildResources` to another value.

**Comment by develar** [comment]
But as files are explicitly specified, we must include it. That's why issue is not closed.
