### ISSUE TITLE
Windows autoUpdater.checkForUpdates() => Cannot check for updates: TypeError: Cannot read property 'sha2' of undefined at validateUpdateInfo

### ISSUE THREAD

**Issue by Pentiado** [electron-userland/electron-builder#1500]
electron-builder
* **Version**: 1.6.6 (latest)

electron-updater
* **Version**: 1.14.2 (latest)

* **Target**: Windows

------------------

I'm building an app for Mac and Windows and I have a problem with electron-updater on Windows.

**Build and publish seems to be working just fine**

"dist:win64": "build --platform win32 --arch x64 --publish=always"

> CSC_LINK=[...]/windows-cert.p12 CSC_KEY_PASSWORD=password npm run dist:win64

Skip app dependencies rebuild because platform is different
Packaging for win32 x64 using electron 1.6.6 to dist/win-unpacked
Signing Solis Health.exe (certificate file: "[...]/windows-cert.p12")
Building NSIS installer
  Packaging NSIS installer for arch x64
  Signing NSIS uninstaller (certificate file: "[...]/windows-cert.p12")
Signing Solis Health Setup 1.2.5.exe (certificate file: "[...]/windows-cert.p12")
Publishing to S3 (bucket: bucket-name)

**The problem is when I open the app on Windows and run check autoUpdater.checkForUpdates();**

Cannot check for updates: TypeError: Cannot read property 'sha2' of undefined
    at validateUpdateInfo (D:\Users\pawel\AppData\Local\Programs\Solis\resources\app.asar\node_modules\electron-updater\src\GenericProvider.ts:69:7)
    at D:\Users\pawel\AppData\Local\Programs\Solis\resources\app.asar\node_modules\electron-updater\src\GenericProvider.ts:40:5
From previous event:
    at GenericProvider.getLatestVersion (D:\Users\pawel\AppData\Local\Programs\Solis\resources\app.asar\node_modules\electron-updater\out\GenericProvider.js:80:11)
    at D:\Users\pawel\AppData\Local\Programs\Solis\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:190:38
From previous event:
    at NsisUpdater.doCheckForUpdates (D:\Users\pawel\AppData\Local\Programs\Solis\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:261:11)
    at D:\Users\pawel\AppData\Local\Programs\Solis\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:175:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at NsisUpdater._checkForUpdates (D:\Users\pawel\AppData\Local\Programs\Solis\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:220:11)
    at NsisUpdater.checkForUpdates (D:\Users\pawel\AppData\Local\Programs\Solis\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:157:35)
    at EventEmitter.ipcMain.on (D:\Users\pawel\AppData\Local\Programs\Solis\resources\app.asar\desktop.js:128:15)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at WebContents.<anonymous> (D:\Users\pawel\AppData\Local\Programs\Solis\resources\electron.asar\browser\api\web-contents.js:247:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

**Comment by silaspedrosa** [comment]
Having a similar problem here!
Have you discovered anything?

**Comment by Pentiado** [comment]
Nope. Our desktop app is put on hold for now.

**Comment by develar** [comment]
Should be ok in the 2.x electron-updater.
