### ISSUE TITLE
AppX build fails

### ISSUE THREAD

**Issue by clusterberries** [electron-userland/electron-builder#1515]
* **Version**: 17.1.1

* **Target**: appx

Hi! I'm trying to build application with target 'appx', but I faced with error during compilation. 
Build for Windows with target nsis and for MacOS runs without issues.
Does anybody else have the same problem?

```
Fri, 28 Apr 2017 14:29:36 GMT electron-builder Copying D:\...\electron to D:\...\electron\dist\win-unpacked
TypeError: A value [object Object] was yielded that could not be treated as a promise

    See http://goo.gl/MqrFmX

From coroutine:
    at Promise.coroutine (D:\...\electron\node_modules\bluebird\js\release\generators.js:194:17)
    at AppXTarget.build (D:\...\electron\node_modules\electron-builder\out\targets\appx.js:84:68)
    at postAsyncTasks.push.default.map.it (D:\...\electron\node_modules\electron-builder\src\platformPackager.ts:106:85)
    at tryCatcher (D:\...\electron\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (D:\...\electron\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (D:\...\electron\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (D:\...\electron\node_modules\bluebird\js\release\promise_array.js:78:10)
    at AppXTarget.build (D:\...\electron\node_modules\electron-builder\out\targets\appx.js:84:68)
    at postAsyncTasks.push.default.map.it (D:\...\electron\node_modules\electron-builder\src\platformPackager.ts:106:85)
From previous event:
    at AppXTarget.build (D:\...\electron\node_modules\electron-builder\out\targets\appx.js:123:11)
    at postAsyncTasks.push.default.map.it (D:\...\electron\node_modules\electron-builder\src\platformPackager.ts:106:85)
From previous event:
    at WinPackager.packageInDistributableFormat (D:\...\electron\node_modules\electron-builder\src\platformPackager.ts:106:41)
    at D:\...\electron\node_modules\electron-builder\src\platformPackager.ts:102:10
    at next (native)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at WinPackager.pack (D:\...\electron\node_modules\electron-builder\out\platformPackager.js:169:11)
    at D:\...\electron\node_modules\electron-builder\src\packager.ts:257:24
    at next (native)
    at xfs.mkdir.er (D:\...\electron\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager.doBuild (D:\...\electron\node_modules\electron-builder\out\packager.js:379:11)
    at D:\...\electron\node_modules\electron-builder\src\packager.ts:170:52
    at next (native)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Packager.build (D:\...\electron\node_modules\electron-builder\out\packager.js:274:11)
    at D:\...\electron\node_modules\electron-builder\src\builder.ts:198:33
    at next (native)
From previous event:
    at build (D:\...\electron\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (D:\...\electron\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
```

**Comment by navdeepsinghkhalsa** [comment]
@clusterberries Were you able to find a solution?

**Comment by clusterberries** [comment]
@navdeepsinghkhalsa unfortunately no

**Comment by JensDebergh** [comment]
I'm experiencing the exact same problem. Could this issue be caused because the target needs more information while packaging to appx since all app information is stored inside?

**Comment by develar** [comment]
I am really sorry that this stupid bug was not fixed so long. CI check enabled to check Appx.
