### ISSUE TITLE
Appveyor consistent EBUSY during nsis build

### ISSUE THREAD

**Issue by blahah** [electron-userland/electron-builder#1537]
* **Version**: 17.3.1

* **Target**: Windows x64 & x86

I consistently get a `spawn EBUSY` error like this when building for Windows on Appveyor:

```
Building NSIS installer
  Packaging NSIS installer for arch x64
Error: spawn EBUSY
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at exports.execFile (child_process.js:143:15)
    at default (C:\projects\sciencefair\node_modules\electron-builder-util\src\util.ts:54:5)
    at exec (C:\projects\sciencefair\node_modules\electron-builder-util\src\util.ts:53:3)
    at C:\projects\sciencefair\node_modules\electron-builder\src\targets\nsis.ts:266:11
From previous event:
    at NsisTarget.computeScriptAndSignUninstaller (C:\projects\sciencefair\node_modules\electron-builder\out\targets\nsis.js:356:11)
    at C:\projects\sciencefair\node_modules\electron-builder\src\targets\nsis.ts:229:119
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at NsisTarget.buildInstaller (C:\projects\sciencefair\node_modules\electron-builder\out\targets\nsis.js:321:11)
    at C:\projects\sciencefair\node_modules\electron-builder\src\targets\nsis.ts:124:18
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (C:\projects\sciencefair\node_modules\electron-builder\out\targets\nsis.js:228:11)
    at C:\projects\sciencefair\node_modules\electron-builder\src\packager.ts:265:31
From previous event:
    at Packager.doBuild (C:\projects\sciencefair\node_modules\electron-builder\out\packager.js:379:11)
    at C:\projects\sciencefair\node_modules\electron-builder\src\packager.ts:170:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (C:\projects\sciencefair\node_modules\electron-builder\out\packager.js:274:11)
    at C:\projects\sciencefair\node_modules\electron-builder\src\builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\projects\sciencefair\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (C:\projects\sciencefair\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command exited with code 1
```

The project build history shows that this has consistently happened since I've tried to produce the nsis product:

https://ci.appveyor.com/project/blahah/sciencefair

Any help debugging would be much appreciated.

**Comment by blahah** [comment]
This has stopped happening for an unknown reason, so I am closing

**Comment by develar** [comment]
After upgrade? BTW, please add `image: Visual Studio 2017` to your `appveyor.yml`

**Comment by blahah** [comment]
@develar it was this change that fixed it: https://github.com/codeforscience/sciencefair/commit/1f84a8bfd6ace281f6d93537ae09d9d49f8f110e
