### ISSUE TITLE
NSIS build fails with error 4294967295, ZIP build works

### ISSUE THREAD

**Issue by sheinin** [electron-userland/electron-builder#1557]
* **Version**:  1.6.8

* **Target**: Windows NSIS

npm build dist fails with error code 4294967295 while ZIP build works without errors

```0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Gonki\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist' ]
2 info using npm@4.6.1
3 info using node@v6.10.3
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle MyAppplication@0.1.0~predist: MyAppplication@0.1.0
6 silly lifecycle MyAppplication@0.1.0~predist: no script for predist, continuing
7 info lifecycle MyAppplication@0.1.0~dist: MyAppplication@0.1.0
8 verbose lifecycle MyAppplication@0.1.0~dist: unsafe-perm in lifecycle true
9 verbose lifecycle MyAppplication@0.1.0~dist: PATH: C:\Users\Gonki\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\itechpros\NodeApps\onpolicy\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files\PHP\v5.3;C:\Program Files\ConEmu\ConEmu;C:\Program Files\ConEmu;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\User;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
10 verbose lifecycle MyAppplication@0.1.0~dist: CWD: C:\itechpros\NodeApps\onpolicy
11 silly lifecycle MyAppplication@0.1.0~dist: Args: [ '/d /s /c', 'build' ]
12 silly lifecycle MyAppplication@0.1.0~dist: Returned: code: 4294967295  signal: null
13 info lifecycle MyAppplication@0.1.0~dist: Failed to exec dist script
14 verbose stack Error: MyAppplication@0.1.0 dist: `build`
14 verbose stack Exit status 4294967295
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Gonki\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Gonki\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid MyAppplication@0.1.0
16 verbose cwd C:\itechpros\NodeApps\onpolicy
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gonki\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
19 verbose node v6.10.3
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 4294967295
23 error MyAppplication@0.1.0 dist: `build`
23 error Exit status 4294967295
24 error Failed at the MyAppplication@0.1.0 dist script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 4294967295, true ]
```

package.json

```{
  "name": "MyApplication",
  "description": "Automatic file uploader",
  "version": "0.1.0",
  "main": "main.js",
  "author": "Me",
  "icon": "./icon.ico",
  "dependencies": {
    "chokidar": "^1.6.0",
    "request": "^2.81.0",
    "tmp": "^0.0.31",
    "uuid": "^3.0.1",
    "electron-toaster": "^2.0.4"
  },
  "devDependencies": {
    "electron-builder": "^5.10.5"
  },
  "build": {
    "mac": {
      "category": "your.app.category.type"
    },
    "win": {"target":"nsis","iconUrl":"http://localhost:88/icon.ico"}
  },
  "scripts": {
    "pack": "build --dir",
    "dist": "build"
  }
}
```

**Comment by develar** [comment]
Please use latest version.
