### ISSUE TITLE
spctl returns rejected when building app with Developer ID

### ISSUE THREAD

**Issue by r0stig** [electron-userland/electron-builder#1558]
* **Version**: 17.8.0

* **Target**: macOS

Not able to sign application with Developer ID from Apple Development console. Full log (with DEBUG=electron-builder) set:
```

> AppName@3.0.0-beta6 predist:mac [PATH]
> gulp build --env=production

[09:40:06] Using gulpfile ~/[PATH]/gulpfile.js
[09:40:06] Starting 'bundle'...
[09:40:06] Starting 'less'...
[09:40:06] Starting 'environment'...
[09:40:06] Finished 'environment' after 2.39 ms
'nativeImage' is imported from external module 'electron' but never used
[09:40:07] Finished 'less' after 233 ms
[09:40:07] Finished 'bundle' after 252 ms
[09:40:07] Starting 'build'...
[09:40:07] Finished 'build' after 4.44 μs

> AppName@3.0.0-beta6 dist:mac [PATH]
> build

Thu, 18 May 2017 07:40:08 GMT electron-builder Effective config: {
  "appId": "se.company",
  "files": [
    "app/**/*",
    "node_modules/**/*",
    "package.json"
  ],
  "extraResources": [
    "dictionaries/**/*",
    "build/icon.ico"
  ],
  "mac": {
    "helperBundleId": "se.company.helper",
    "category": "public.app-category.productivity",
    "target": [
      "dmg",
      "pkg",
      "zip"
    ]
  },
  "nsis": {
    "include": "build/win/installer.nsh",
    "oneClick": false,
    "perMachine": false,
    "allowElevation": true,
    "allowToChangeInstallationDirectory": true
  },
  "linux": {
    "desktop": {
      "Categories": "GNOME;GTK;Network;InstantMessaging",
      "StartupWMClass": "se.company"
    },
    "target": [
      "deb",
      "rpm"
    ]
  }
}
Rebuilding native production dependencies for darwin:x64
Thu, 18 May 2017 07:40:11 GMT electron-builder Spawning /usr/local/Cellar/node/6.5.0/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js rebuild @paulcbetts/system-idle-time spellchecker

> @paulcbetts/system-idle-time@1.0.4 install [PATH]/node_modules/@paulcbetts/system-idle-time
> node-gyp rebuild

  CXX(target) Release/obj.target/system_idle_time/src/module.o
  CXX(target) Release/obj.target/system_idle_time/src/mac/idle.o
  SOLINK_MODULE(target) Release/system_idle_time.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> spellchecker@3.3.1 install [PATH]/node_modules/spellchecker
> node-gyp rebuild

  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affentry.o
../vendor/hunspell/src/hunspell/affentry.cxx:544:47: warning: while loop has empty body [-Wempty-body]
                        while (p && *p != ']' && (p = nextchar(p)));
                                                                   ^
../vendor/hunspell/src/hunspell/affentry.cxx:544:47: note: put the semicolon on a separate line to silence this warning
1 warning generated.
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affixmgr.o
In file included from ../vendor/hunspell/src/hunspell/affixmgr.cxx:12:
../vendor/hunspell/src/hunspell/affentry.hxx:30:105: warning: implicit conversion of NULL constant to 'unsigned short' [-Wnull-conversion]
  struct hentry *      check_twosfx(const char * word, int len, char in_compound, const FLAG needflag = NULL);
                                                                                                      ~ ^~~~
                                                                                                        0
../vendor/hunspell/src/hunspell/affentry.hxx:93:114: warning: implicit conversion of NULL constant to 'unsigned short' [-Wnull-conversion]
  struct hentry *   check_twosfx(const char * word, int len, int optflags, PfxEntry* ppfx, const FLAG needflag = NULL);
                                                                                                               ~ ^~~~
                                                                                                                 0
../vendor/hunspell/src/hunspell/affixmgr.cxx:3654:65: warning: 'strncmp' call operates on objects of type 'const char' while the size is based on a different type 'const char *' [-Wsizeof-pointer-memaccess]
                             if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                                                ~~~~~~~         ^~~~~~~
../vendor/hunspell/src/hunspell/affixmgr.cxx:3654:65: note: did you mean to provide an explicit length?
                             if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                                                                ^~~~~~~
3 warnings generated.
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/csutil.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/dictmgr.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/filemgr.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/hashmgr.o
In file included from ../vendor/hunspell/src/hunspell/hashmgr.cxx:9:
../vendor/hunspell/src/hunspell/hashmgr.hxx:17:21: warning: private field 'userword' is not used [-Wunused-private-field]
  int               userword;
                    ^
1 warning generated.
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/hunspell.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/hunzip.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/phonet.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/replist.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/suggestmgr.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/parsers/textparser.o
  LIBTOOL-STATIC Release/hunspell.a
  CXX(target) Release/obj.target/spellchecker/src/main.o
  CXX(target) Release/obj.target/spellchecker/src/spellchecker_hunspell.o
  CXX(target) Release/obj.target/spellchecker/src/spellchecker_mac.o
  CXX(target) Release/obj.target/spellchecker/src/transcoder_posix.o
  SOLINK_MODULE(target) Release/spellchecker.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
@paulcbetts/system-idle-time@1.0.4 [PATH]/node_modules/@paulcbetts/system-idle-time
spellchecker@3.3.1 [PATH]/node_modules/spellchecker
Thu, 18 May 2017 07:40:22 GMT electron-builder /usr/local/Cellar/node/6.5.0/bin/node (19253) exited with code 0
Packaging for darwin x64 using electron 1.4.16 to dist/mac
Thu, 18 May 2017 07:40:24 GMT electron-builder Spawning [PATH]/node_modules/7zip-bin-mac/7za x -bd /Users/username/Library/Caches/electron/electron-v1.4.16-darwin-x64.zip -o[PATH]/dist/mac

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 41407446 bytes (40 MiB)

Extracting archive: /Users/username/Library/Caches/electron/electron-v1.4.16-darwin-x64.zip
--
Path = /Users/username/Library/Caches/electron/electron-v1.4.16-darwin-x64.zip
Type = zip
Physical Size = 41407446

Everything is Ok

Folders: 143
Files: 180
Size:       107822546
Compressed: 41407446
Thu, 18 May 2017 07:40:25 GMT electron-builder [PATH]/node_modules/7zip-bin-mac/7za (20496) exited with code 0
Thu, 18 May 2017 07:40:25 GMT electron-builder Dev or extraneous dependencies: ../electron-builder.json, ../electron-builder.json5, 7zip-bin-mac, 7zip-bin, abbrev, accord, ajv, ajv-keywords, align-text, yauzl, zip-stream, yargs-parser, yargs, yallist, xtend, y18n, xmldom, xmlbuilder, xdg-basedir, write-file-atomic, wrap-ansi, zip-stream/node_modules/readable-stream, zip-stream/node_modules/isarray, yargs-parser/node_modules/camelcase, yargs/node_modules/camelcase, yargs/node_modules/execa, yargs/node_modules/find-up, yargs/node_modules/get-stream, yargs/node_modules/is-fullwidth-code-point, yargs/node_modules/load-json-file, yargs/node_modules/os-locale, yargs/node_modules/npm-run-path, wordwrap, window-size, widest-line, wide-align, which-module, which, yargs/node_modules/string-width, yargs/node_modules/strip-bom, yargs/node_modules/read-pkg-up, yargs/node_modules/read-pkg, yargs/node_modules/path-key, yargs/node_modules/path-type, when, wgxpath, webdriverio, vinyl-sourcemaps-apply, wdio-dot-reporter, vinyl-fs, vinyl-file, vinyl, validator, verror, validate-npm-package-license, webdriverio/node_modules/globule, webdriverio/node_modules/caseless, webdriverio/node_modules/gaze, webdriverio/node_modules/har-validator, webdriverio/node_modules/lodash, webdriverio/node_modules/qs, webdriverio/node_modules/request, webdriverio/node_modules/supports-color, wdio-dot-reporter/node_modules/core-js, wdio-dot-reporter/node_modules/babel-runtime, vinyl-fs/node_modules/graceful-fs, vinyl-fs/node_modules/readable-stream, vinyl-fs/node_modules/clone, vinyl-fs/node_modules/strip-bom, vinyl-fs/node_modules/through2, vinyl-fs/node_modules/vinyl, vinyl-fs/node_modules/xtend, vinyl-file/node_modules/vinyl, v8flags, uuid, uuid-1345, util-deprecate, utf8-byte-length, url-parse-lax, user-home, webdriverio/node_modules/tunnel-agent, url, update-notifier, urix, unzip-response, unique-string, universalify, unique-stream, url/node_modules/punycode, uglify-to-browserify, unc-path-regex, uglify-js, typedarray, tweetnacl, type-check, type-detect, tunnel-agent, trim-right, truncate-utf8-bytes, uglify-js/node_modules/window-size, uglify-js/node_modules/cliui, uglify-js/node_modules/camelcase, trim-newlines, uglify-js/node_modules/yargs, to-fast-properties, tough-cookie, timed-out, time-stamp, tildify, through2, through, throttleit, thenify, thenify-all, term-size, tempfile, tar-stream, tar, symbol-observable, supports-color, sumchecker, strip-json-comments, strip-indent, tempfile/node_modules/uuid, strip-eof, tar-stream/node_modules/end-of-stream, tar-stream/node_modules/isarray, tar-stream/node_modules/once, tar-stream/node_modules/readable-stream, tar-stream/node_modules/xtend, strip-bom, strip-ansi, strip-bom-stream, stringstream, string_decoder, string.prototype.codepointat, string-width, stream-exhaust, stream-array, stream-consume, stat-mode, strip-bom-stream/node_modules/first-chunk-stream, strip-bom-stream/node_modules/isarray, strip-bom-stream/node_modules/readable-stream, sshpk, sprintf-js, split, speedometer, spdx-license-ids, spectron, stream-array/node_modules/readable-stream, stream-array/node_modules/isarray, sshpk/node_modules/assert-plus, spdx-expression-parse, spdx-correct, spawn-sync, spawn-rx, sparkles, source-map-url, source-map-resolve, sntp, slide, slash, single-line-log, signal-exit, sigmund, set-immediate-shim, set-blocking, semver-diff, sequencify, semver, sanitize-filename, safe-buffer, rxjs, rx, run-async, rollup-pluginutils, rollup-plugin-istanbul, right-align, rgb2hex, restore-cursor, resolve-url, resolve-dir, require-main-filename, require-directory, resolve, request, replace-ext, repeating, repeat-string, repeat-element, registry-url, registry-auth-token, regex-cache, regenerator-runtime, redent, rechoir, readdirp, readable-stream, rc, read-pkg-up, read-pkg, randomatic, querystring, qs, readdirp/node_modules/isarray, readdirp/node_modules/readable-stream, punycode, prr, pseudomap, promise, progress-stream, process-nextick-args, private, pretty-hrtime, pretty-bytes, preserve, prepend-http, prelude-ls, plist, pinkie-promise, pinkie, pify, performance-now, pend, path-type, path-root, path-root-regex, path-parse, path-key, path-dirname, path-exists, parse-passwd, parse-json, parse-glob, parse-filepath, p-locate, package-json, parse-color, p-finally, p-limit, osenv, os-tmpdir, os-shim, os-homedir, os-locale, orchestrator, ordered-read-streams, ora, optionator, optimist, onetime, object.omit, object-keys, object-assign, oauth-sign, optionator/node_modules/wordwrap, optimist/node_modules/minimist, number-is-nan, npmlog, nugget, npm-run-path, npm-install-package, normalize-path, normalize-package-data, nopt, noop2, node-gyp, node-forge, node-emoji, node-abi, next-tick, natives, mz, multipipe, mute-stream, ms, mocha, minimist, mimic-fn, mime-db, mime-types, mime, mocha/node_modules/glob, mocha/node_modules/debug, mocha/node_modules/ms, mocha/node_modules/supports-color, micromatch, meow, mem, map-obj, map-cache, make-dir, macaddress, lowercase-keys, lru-cache, loud-rejection, loose-envify, longest, log-symbols, lodash.uniq, lodash.template, lodash.templatesettings, lodash.restparam, lodash.pick, lodash.partialright, lodash.merge, lodash.mapvalues, lodash.keys, lodash.isstring, lodash.isplainobject, lodash.isempty, lodash.isarray, lodash.isarguments, lodash.escape, lodash.flatten, lodash.create, lodash.defaults, lodash.clone, lodash.assignwith, lodash.assign, lodash._root, lodash._reinterpolate, lodash._reevaluate, lodash._isiterateecall, lodash._reescape, lodash._getnative, lodash._basevalues, lodash._basetostring, lodash._basecreate, lodash._baseassign, lodash._basecopy, locate-path, load-json-file, liftoff, levn, less, lazystream, lcid, lazy-req, lazy-cache, locate-path/node_modules/path-exists, klaw, latest-version, kind-of, jsprim, jsonify, jsonpointer, lazystream/node_modules/isarray, lazystream/node_modules/readable-stream, jsonfile, json5, json3, json-stringify-safe, json-stable-stringify, json-schema, jsesc, jsprim/node_modules/assert-plus, jsbn, js-yaml, js-tokens, jodid25519, istanbul, isstream, isobject, isexe, isbinaryfile, isarray, is-windows, is-utf8, is-unc-path, istanbul/node_modules/esprima, istanbul/node_modules/abbrev, istanbul/node_modules/glob, istanbul/node_modules/resolve, istanbul/node_modules/supports-color, is-typedarray, is-stream, istanbul/node_modules/wordwrap, is-retry-allowed, is-relative, isobject/node_modules/isarray, is-redirect, is-property, is-promise, is-primitive, is-obj, is-posix-bracket, is-number, is-npm, is-my-json-valid, is-glob, is-fullwidth-code-point, is-finite, is-extglob, is-extendable, is-equal-shallow, is-electron-renderer, is-my-json-valid/node_modules/xtend, is-dotfile, is-ci, is-builtin-module, is-buffer, is-binary-path, is-arrayish, is-absolute, invert-kv, invariant, interpret, inquirer, ini, indx, indent-string, image-size, imurmurhash, http-signature, hosted-git-info, homedir-polyfill, home-path, home-or-tmp, hoek, hawk, has-unicode, has-flag, has-gulplog, has-ansi, har-validator, har-schema, handlebars, gulplog, gulp-watch, gulp-util, gulp-plumber, gulp-less, gulp-batch, gulp, handlebars/node_modules/source-map, growl, gulp-watch/node_modules/glob-parent, gulp-watch/node_modules/is-extglob, gulp-watch/node_modules/is-glob, gulp-watch/node_modules/isarray, gulp-watch/node_modules/readable-stream, gulp-watch/node_modules/vinyl, gulp-util/node_modules/isarray, gulp-util/node_modules/object-assign, gulp-util/node_modules/readable-stream, gulp-util/node_modules/through2, gulp-util/node_modules/xtend, gulp-plumber/node_modules/isarray, gulp-plumber/node_modules/readable-stream, gulp-plumber/node_modules/through2, gulp-plumber/node_modules/xtend, graceful-readlink, gulp-less/node_modules/isarray, gulp-less/node_modules/readable-stream, gulp-less/node_modules/through2, gulp-less/node_modules/xtend, gulp/node_modules/semver, graceful-fs, got, glogg, globule, globals, global-prefix, global-modules, glob2base, glob-watcher, glob-stream, glob-parent, glob-base, globule/node_modules/glob, globule/node_modules/graceful-fs, globule/node_modules/inherits, globule/node_modules/lodash, globule/node_modules/lru-cache, globule/node_modules/minimatch, getpass, get-stream, get-stdin, glob-stream/node_modules/glob, glob-stream/node_modules/minimatch, glob-stream/node_modules/readable-stream, glob-stream/node_modules/through2, glob-stream/node_modules/xtend, generate-object-property, get-caller-file, generate-function, gaze, getpass/node_modules/assert-plus, gauge, fstream, fsevents, fs-promise, fs-extra-p, fs-extra, fs-exists-sync, form-data, forever-agent, for-own, fsevents/node_modules/ansi-regex, fsevents/node_modules/abbrev, fsevents/node_modules/ansi-styles, fsevents/node_modules/aproba, fsevents/node_modules/are-we-there-yet, fsevents/node_modules/asn1, fsevents/node_modules/assert-plus, fsevents/node_modules/asynckit, fs-promise/node_modules/fs-extra, for-in, fs-extra-p/node_modules/fs-extra, fs-extra-p/node_modules/jsonfile, flagged-respawn, first-chunk-stream, fined, findup-sync, find-up, fsevents/node_modules/wrappy, fsevents/node_modules/wide-align, fsevents/node_modules/verror, fsevents/node_modules/uuid, fsevents/node_modules/xtend, fsevents/node_modules/util-deprecate, fsevents/node_modules/uid-number, fsevents/node_modules/tweetnacl, find-index, fill-range, filename-regex, figures, fd-slicer, fast-levenshtein, fancy-log, fsevents/node_modules/tunnel-agent, fsevents/node_modules/tough-cookie, fsevents/node_modules/tar-pack, fsevents/node_modules/tar, fsevents/node_modules/supports-color, fsevents/node_modules/strip-json-comments, fsevents/node_modules/strip-ansi, extsprintf, extract-zip, fsevents/node_modules/stringstream, extglob, external-editor, extend, expand-tilde, expand-range, expand-brackets, fsevents/node_modules/string_decoder, fsevents/node_modules/sshpk, fsevents/node_modules/string-width, fsevents/node_modules/sntp, fsevents/node_modules/signal-exit, fsevents/node_modules/set-blocking, exit-hook, extract-zip/node_modules/debug, extract-zip/node_modules/minimist, extract-zip/node_modules/mkdirp, fsevents/node_modules/semver, fsevents/node_modules/tar-pack/node_modules/once, fsevents/node_modules/tar-pack/node_modules/readable-stream, external-editor/node_modules/tmp, execa, esutils, estree-walker, estraverse, esprima, escodegen, fsevents/node_modules/request, fsevents/node_modules/rimraf, fsevents/node_modules/readable-stream, fsevents/node_modules/rc, fsevents/node_modules/qs, fsevents/node_modules/sshpk/node_modules/assert-plus, fsevents/node_modules/punycode, fsevents/node_modules/process-nextick-args, escape-string-regexp, es6-promise, error-ex, errno, env-paths, end-of-stream, escodegen/node_modules/esprima, escodegen/node_modules/source-map, fsevents/node_modules/pinkie-promise, fsevents/node_modules/pinkie, fsevents/node_modules/path-is-absolute, fsevents/node_modules/once, fsevents/node_modules/rc/node_modules/minimist, fsevents/node_modules/object-assign, fsevents/node_modules/oauth-sign, fsevents/node_modules/number-is-nan, electron-window, electron-rebuild, electron-publish, electron-osx-sign, electron-notifications, electron-mocha, end-of-stream/node_modules/once, fsevents/node_modules/npmlog, fsevents/node_modules/nopt, fsevents/node_modules/node-pre-gyp, fsevents/node_modules/ms, electron-is-dev, fsevents/node_modules/mkdirp, fsevents/node_modules/minimist, fsevents/node_modules/minimatch, fsevents/node_modules/mime-types, electron-rebuild/node_modules/yargs, electron-publish/node_modules/mime, electron-is, electron-download, electron-chromedriver, electron-mocha/node_modules/fs-extra, electron-builder-util, fsevents/node_modules/mime-db, fsevents/node_modules/jsprim, fsevents/node_modules/jsonpointer, fsevents/node_modules/json-stringify-safe, electron-builder-http, fsevents/node_modules/json-schema, fsevents/node_modules/jsbn, fsevents/node_modules/jodid25519, fsevents/node_modules/isstream, electron-builder-core, electron-builder, electron, ejs, ecc-jsbn, electron-builder-util/node_modules/debug, electron-builder-util/node_modules/ms, electron-builder-util/node_modules/source-map-support, fsevents/node_modules/isarray, fsevents/node_modules/is-typedarray, fsevents/node_modules/is-property, fsevents/node_modules/is-my-json-valid, electron-builder-http/node_modules/debug, electron-builder-http/node_modules/ms, fsevents/node_modules/is-fullwidth-code-point, fsevents/node_modules/ini, fsevents/node_modules/inherits, fsevents/node_modules/inflight, duplexer3, duplexer2, electron-builder/node_modules/ajv, electron-builder/node_modules/brace-expansion, electron-builder/node_modules/debug, electron-builder/node_modules/electron-download-tf, electron-builder/node_modules/fs-extra, electron-builder/node_modules/hosted-git-info, electron-builder/node_modules/js-yaml, electron-builder/node_modules/jsonfile, dot-prop, diff, dev-null, fsevents/node_modules/http-signature, fsevents/node_modules/hoek, fsevents/node_modules/hawk, fsevents/node_modules/has-unicode, detect-indent, detect-file, deprecated, fsevents/node_modules/has-ansi, fsevents/node_modules/har-validator, fsevents/node_modules/graceful-readlink, fsevents/node_modules/graceful-fs, electron-builder/node_modules/rc, electron-builder/node_modules/path-exists, electron-builder/node_modules/sumchecker, electron-builder/node_modules/normalize-package-data, electron-builder/node_modules/ms, electron-builder/node_modules/minimatch, delegates, delayed-stream, defaults, deepmerge, deep-extend, deep-is, fsevents/node_modules/getpass, fsevents/node_modules/glob, fsevents/node_modules/generate-object-property, fsevents/node_modules/generate-function, fsevents/node_modules/gauge, fsevents/node_modules/fstream-ignore, fsevents/node_modules/fstream, fsevents/node_modules/fs.realpath, deep-eql, debug, decamelize, dateformat, dashdash, currently-unhandled, cuint, fsevents/node_modules/form-data, fsevents/node_modules/forever-agent, fsevents/node_modules/extsprintf, fsevents/node_modules/getpass/node_modules/assert-plus, fsevents/node_modules/extend, fsevents/node_modules/escape-string-regexp, fsevents/node_modules/ecc-jsbn, fsevents/node_modules/delegates, css-value, css-parse, deep-eql/node_modules/type-detect, css, cryptiles, crypto-random-string, dashdash/node_modules/assert-plus, fsevents/node_modules/delayed-stream, fsevents/node_modules/deep-extend, fsevents/node_modules/debug, fsevents/node_modules/cryptiles, fsevents/node_modules/dashdash, fsevents/node_modules/core-util-is, fsevents/node_modules/console-control-strings, cross-spawn-async, cross-spawn, create-error-class, fsevents/node_modules/concat-map, css/node_modules/source-map, crc32-stream, crc, core-util-is, fsevents/node_modules/commander, fsevents/node_modules/code-point-at, fsevents/node_modules/combined-stream, convert-source-map, core-js, console-control-strings, fsevents/node_modules/chalk, fsevents/node_modules/caseless, fsevents/node_modules/buffer-shims, fsevents/node_modules/brace-expansion, fsevents/node_modules/dashdash/node_modules/assert-plus, configstore, concat-stream, crc32-stream/node_modules/isarray, crc32-stream/node_modules/readable-stream, compress-commons, compare-version, fsevents/node_modules/boom, commander, fsevents/node_modules/block-stream, fsevents/node_modules/bcrypt-pbkdf, fsevents/node_modules/balanced-match, fsevents/node_modules/aws4, fsevents/node_modules/aws-sign2, combined-stream, concat-stream/node_modules/isarray, concat-stream/node_modules/readable-stream, color-convert, colors, code-point-at, co, compress-commons/node_modules/isarray, compress-commons/node_modules/readable-stream, clone-stats, clone, cli-width, cliui, cli-spinners, cli-cursor, cli-boxes, ci-info, chromium-pickle-js, chokidar, chalk, chai, center-align, caseless, capture-stack-trace, camelcase-keys, camelcase, builtin-modules, buffer-crc32, buffer-shims, browser-stdout, braces, boxen, boom, bluebird-lst, bluebird, block-stream, bl, binary-extensions, beeper, boxen/node_modules/camelcase, boxen/node_modules/is-fullwidth-code-point, boxen/node_modules/string-width, bcrypt-pbkdf, base64-js, bl/node_modules/isarray, bl/node_modules/readable-stream, babylon, babel-types, babel-traverse, babel-template, babel-runtime, babel-messages, babel-register, babel-helpers, babel-generator, babel-types/node_modules/babel-runtime, babel-traverse/node_modules/babel-runtime, babel-template/node_modules/babel-runtime, babel-runtime/node_modules/regenerator-runtime, babel-messages/node_modules/babel-runtime, babel-register/node_modules/babel-runtime, babel-helpers/node_modules/babel-runtime, babel-core, babel-generator/node_modules/babel-runtime, babel-code-frame, aws4, aws-sign2, atob, asynckit, async-each, babel-core/node_modules/babel-runtime, async-done, async, assertion-error, assert-plus, asn1, asap, arrify, array-unique, async-done/node_modules/end-of-stream, array-uniq, array-find-index, arr-flatten, array-differ, arr-diff, argparse, are-we-there-yet, archy, archiver-utils, aproba, archiver, async-done/node_modules/end-of-stream/node_modules/once, anymatch, any-promise, ansi-styles, ansi-regex, archiver-utils/node_modules/isarray, archiver-utils/node_modules/readable-stream, ansi-escapes, archiver/node_modules/isarray, archiver/node_modules/readable-stream, ansi-align, amdefine, ansi-align/node_modules/is-fullwidth-code-point, ansi-align/node_modules/string-width
Thu, 18 May 2017 07:40:26 GMT electron-builder Copying files using pattern: from: [PATH], to: [PATH]/dist/mac/AppName Beta.app/Contents/Resources, patterns: dictionaries/**/*, build/icon.ico
Thu, 18 May 2017 07:40:26 GMT electron-builder Copying [PATH] to [PATH]/dist/mac/AppName Beta.app/Contents/Resources
Thu, 18 May 2017 07:40:26 GMT electron-builder No publishConfigs, detect using repository info
Thu, 18 May 2017 07:40:26 GMT electron-builder No owner or project for github, call getInfo: owner: undefined, project: undefined
Thu, 18 May 2017 07:40:26 GMT electron-builder Executing security find-identity -v
Thu, 18 May 2017 07:40:26 GMT electron-builder Executing security find-identity -v -p codesigning
  1) XXX "iPhone Developer: XXX (XXX)"
  2) XXX "iPhone Distribution: XXX (XXX)"
  3) XXX "Developer ID Application: XXX (XXX)"
  4) XXX "Mac Developer: XXX (XXX)"
     4 valid identities found

  1) XXX "com.apple.idms.appleid.prd.XXX" (CSSMERR_TP_CERT_REVOKED)
  2) XXX "iPhone Developer: XXX (XXX)"
  3) XXX "Apple Development IOS Push Services: se.company.online"
  4) XXX "iPhone Distribution: XXX (XXX)"
  5) XXX "Apple Push Services: se.company.online"
  6) XXX "com.apple.idms.appleid.prd.XXX"
  7) XXX "Developer ID Application: XXX (XXX)"
  8) XXX "Mac Developer: XXX (XXX)"
     8 valid identities found

Signing app (identity: Developer ID Application: XXX (XXX))
Error: Command failed: spctl --assess --type execute --verbose --ignore-cache --no-cache [PATH]/dist/mac/AppName Beta.app
[PATH]/dist/mac/AppName Beta.app: rejected
source=Developer ID

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at module.exports.execFileAsync ([PATH]/node_modules/electron-osx-sign/util.js:44:10)
    at [PATH]/node_modules/electron-osx-sign/sign.js:99:16
From previous event:
    at verifySignApplicationAsync ([PATH]/node_modules/electron-osx-sign/sign.js:97:8)
    at [PATH]/node_modules/electron-osx-sign/sign.js:182:25
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at [PATH]/node_modules/electron-osx-sign/sign.js:179:10
From previous event:
    at signApplicationAsync ([PATH]/node_modules/electron-osx-sign/sign.js:122:6)
    at [PATH]/node_modules/electron-osx-sign/sign.js:335:14
From previous event:
    at module.exports.signAsync ([PATH]/node_modules/electron-osx-sign/sign.js:327:6)
    at [PATH]/node_modules/electron-builder/src/macPackager.ts:235:12
    at next (native)
    at MacPackager.doSign ([PATH]/node_modules/electron-builder/out/macPackager.js:288:11)
    at [PATH]/node_modules/electron-builder/src/macPackager.ts:218:56
    at next (native)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "run" "dist:mac"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! AppName@3.0.0-beta6 dist:mac: `build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the AppName@3.0.0-beta6 dist:mac script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the AppName package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs AppName
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls AppName
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     [PATH]/npm-debug.log
```

Any clues what's wrong? Need more information?

**Comment by develar** [comment]
Is Xcode updated to latest version? Is EULA accepted (http://developer.apple.com and on Xcode start)? Do you see your certs in the Xcode?

**Comment by r0stig** [comment]
@develar I have the latest version of Xcode my OS allows (8.1), using OS X El Captain 10.11.6 (Xcode not shown under updates in App Store). EULA is accepted in both Xcode and developer console.

**Comment by develar** [comment]
Could you please execute `spctl --assess --type execute --verbose --ignore-cache --no-cache [PATH]/dist/mac/AppName Beta.app` in the terminal?

**Comment by r0stig** [comment]
@develar 
Returns:
````
/Users/[PATH]/AppName Beta.app: rejected
source=Developer ID
```

**Comment by develar** [comment]
Please try 18.0.0 or on another machine.

**Comment by r0stig** [comment]
Sorry for late reply, works on another machine with xcodebuild 8.2 so I'm guessing that's the problem since I have 8.1.

**Comment by r0stig** [comment]
Update; I managed to get xcode 8.2 installed on my machine but no luck signing the app. Any other clues what's different on my machine compared to my colleague's computer? He has newer version of macOS, does that make a difference @develar?

**Comment by develar** [comment]
Yes, it is better to use latest macOS version.
