### ISSUE TITLE
Build fails: electron-builder 17.5.0, 17.8.0: cannot find module 'debug'

### ISSUE THREAD

**Issue by d9k** [electron-userland/electron-builder#1564]
* **Version**: 17.8.0, 17.5.0
* Electron version: 1.6.7

* **Target**: Windows 7 x64

```
> node_modules\.bin\build
Rebuilding native production dependencies for win32:x64
Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at _load_debug (C:\cr\MyElectronApp\node_modules\electron-builder\out\targets\nsis.js:25:45)
    at Object.<anonymous> (C:\cr\MyElectronApp\node_modules\electron-builder\src\targets\nsis.ts:21:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at _load_nsis (C:\cr\MyElectronApp\node_modules\electron-builder\out\winPackager.js:93:20)
    at C:\cr\MyElectronApp\node_modules\electron-builder\src\winPackager.ts:112:32
    at mapper (C:\cr\MyElectronApp\node_modules\electron-builder\src\targets\targetFactory.ts:49:16)
    at WinPackager.createTargets (C:\cr\MyElectronApp\node_modules\electron-builder\src\winPackager.ts:112:9)
From previous event:
    at Packager.doBuild (C:\cr\MyElectronApp\node_modules\electron-builder\out\packager.js:379:11)
    at C:\cr\MyElectronApp\node_modules\electron-builder\src\packager.ts:170:52
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Packager.build (C:\cr\MyElectronApp\node_modules\electron-builder\out\packager.js:274:11)
    at C:\cr\MyElectronApp\node_modules\electron-builder\src\builder.ts:198:33
    at next (native)
From previous event:
    at build (C:\cr\MyElectronApp\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (C:\cr\MyElectronApp\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

Successful build on electron-builder `16.8.4`

**Comment by d9k** [comment]
electron-builder `17.10.0` build works, thanks!  :relieved:

**Comment by sam26880** [comment]
I'm getting this issue still in version 20.38.4. Any ideas?
