### ISSUE TITLE
Error compiling for Linux under Windows

### ISSUE THREAD

**Issue by alexbcberio** [electron-userland/electron-builder#1588]
* Electron-builder version: **12.3.1**: 

* Target platform: **Linux**: 

I'm getting an "ENOENT" error trying to compile the app for any Linux distro, it creates correctly a non compiled version and packaged on a compressed file.
 
Here is the full command an error I get:

E:\Documentos\Escritorio\electron\musicPlayer\src>node_modules\.bin\build  --linux deb
Skip app dependencies rebuild because platform is different
Packaging for linux x64 using electron 1.4.15 to dist\linux-unpacked
⚠️  Application icon is not set, default Electron icon will be used
Building deb
Error: Exit code: ENOENT. spawn fpm ENOENT
    at E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder-util\src\util.ts:75:16
    at exithandler (child_process.js:213:5)
    at ChildProcess.errorhandler (child_process.js:225:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at exec (E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder-util\src\util.ts:53:3)
    at E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\src\targets\fpm.ts:168:11
    at next (native)
From previous event:
    at FpmTarget.build (E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\out\targets\fpm.js:218:11)
    at default.each.it (E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\src\platformPackager.ts:104:87)
From previous event:
    at postAsyncTasks.push.default.map.then (E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\src\platformPackager.ts:104:35)
From previous event:
    at LinuxPackager.packageInDistributableFormat (E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\src\platformPackager.ts:104:8)
    at E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\src\platformPackager.ts:99:10
From previous event:
    at LinuxPackager.pack (E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\out\platformPackager.js:160:11)
    at E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\src\packager.ts:210:22
From previous event:
    at Packager.doBuild (E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\out\packager.js:335:11)
    at E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\src\packager.ts:151:38
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\out\packager.js:261:11)
    at E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\src\builder.ts:214:40
    at next (native)
From previous event:
    at build (E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\out\builder.js:63:21)
    at Object.<anonymous> (E:\Documentos\Escritorio\electron\musicPlayer\src\node_modules\electron-builder\out\cli\build-cli.js:68:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#windows

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Docker

**Comment by alexbcberio** [comment]
Thanks for the fast reply, I was struggling with this for weeks
