### ISSUE TITLE
Checksum Validation Failing - After Downloading Update

### ISSUE THREAD

**Issue by daveywc** [electron-userland/electron-builder#1598]
"electron-builder": "^18.1.0"

"electron-updater": "^1.16.0"

Target: Windows (NSIS)
I have donated $50 USD as per above.

After fully downloading an update to my app from my own server (using npm run electron and dev-app-update.yml) at the end of the download I get the following error.  
`[18:46:42:0868] [info] Download speed: 1786450 - Downloaded 98.72720440361729% (313495174/317536768)
[18:46:43:0873] [info] Download speed: 1784075 - Downloaded 99.16062066865908% (314871430/317536768)
[18:46:44:0954] [info] Download speed: 1782256 - Downloaded 99.66627297787448% (316477062/317536768)
[18:46:45:0590] [info] Download speed: 1781842 - Downloaded 100% (317536768/317536768)`
`[18:46:48:0204] [error] Error: Error: SHA2 checksum mismatch, expected c0284eeb41846bc8af40ecc69a0d66715ba8f88b561ff75d4ee59781893e4629, got b9a9cfbe25ffdc2897cb6675ab6d63e174552a5121468776e0f32a0b72d37e99
    at DigestTransform._flush (C:\Data\Development\Projects\DocsOnTapV2\node_modules\electron-updater\node_modules\electron-builder-http\src\httpExecutor.ts:208:46)
    at DigestTransform.<anonymous> (_stream_transform.js:118:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at DigestTransform.emit (events.js:185:7)
    at prefinish (_stream_writable.js:503:12)
    at finishMaybe (_stream_writable.js:511:7)
    at endWritable (_stream_writable.js:523:3)
    at DigestTransform.Writable.end (_stream_writable.js:488:5)
    at ProgressCallbackTransform.onend (_stream_readable.js:511:10)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at ProgressCallbackTransform.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at CancellationToken.createPromise (C:\Data\Development\Projects\DocsOnTapV2\node_modules\electron-updater\node_modules\electron-builder-http\src\CancellationToken.ts:51:5)
    at C:\Data\Development\Projects\DocsOnTapV2\node_modules\electron-updater\src\electronHttpExecutor.ts:25:44
    at Generator.next (<anonymous>)
From previous event:
    at ElectronHttpExecutor.download (C:\Data\Development\Projects\DocsOnTapV2\node_modules\electron-updater\out\electronHttpExecutor.js:80:11)
    at download (C:\Data\Development\Projects\DocsOnTapV2\node_modules\electron-updater\node_modules\electron-builder-http\src\httpExecutor.ts:56:38)
    at C:\Data\Development\Projects\DocsOnTapV2\node_modules\electron-updater\src\NsisUpdater.ts:41:13
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:112:15)`

I have been unable to find a solution to this issue.

Kind regards,

David

**Comment by develar** [comment]
I guess it is dev-only issue. Consider to not use auto updater in dev mode (https://github.com/develar/onshape-desktop-shell/blob/master/src/AppUpdater.ts#L8).

**Comment by develar** [comment]
Have you tried to update dev-app-update.yml — set expected sha hash.

**Comment by daveywc** [comment]
I added the sha2 to dev-app-update.yml.  It now looks like:

`provider: generic
url: 'https://filesv2.docsontap.com.au:4343/updates/'
sha2: c0284eeb41846bc8af40ecc69a0d66715ba8f88b561ff75d4ee59781893e4629`

Is that correct?  It does not fix the error.  The download seems to be calculating a different sha2 value than what is in latest.yml.

**Comment by develar** [comment]
I strongly suggest you to not use `dev-app-update.yml` It is advanced feature for rare use cases. And not really tested. I recommend you simply build your app and test auto-update in the production app. If build is too slow for dev iteration, simply set `compression` to `store` (https://github.com/electron-userland/electron-builder/wiki/Options#Config-compression).

**Comment by develar** [comment]
To debug auto-update, you can enable debug logging (https://github.com/electron-userland/electron-builder/wiki/Auto-Update#debugging). No need to use dev. Better to test installed app.

**Comment by develar** [comment]
Solution — it seems that if we decided to add this feature, and users starts to use it (yeach...), we should disable sha2 check if running from dev — to simplify things.

**Comment by daveywc** [comment]
OK - so tried this on an installed app with the debug logging turned on.  Still get exactly the same checksum problem.

From log.log:
`[2017-05-30 20:14:56:0270] [info] Download speed: 880098 - Downloaded 100% (317536768/317536768)
[2017-05-30 20:14:58:0732] [error] Error: Error: SHA2 checksum mismatch, expected c0284eeb41846bc8af40ecc69a0d66715ba8f88b561ff75d4ee59781893e4629, got b9a9cfbe25ffdc2897cb6675ab6d63e174552a5121468776e0f32a0b72d37e99
    at DigestTransform._flush (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontapv2\resources\app.asar\node_modules\electron-updater\node_modules\electron-builder-http\src\httpExecutor.ts:208:46)
    at DigestTransform.<anonymous> (_stream_transform.js:118:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at DigestTransform.emit (events.js:185:7)
    at prefinish (_stream_writable.js:503:12)
    at finishMaybe (_stream_writable.js:511:7)
    at endWritable (_stream_writable.js:523:3)
    at DigestTransform.Writable.end (_stream_writable.js:488:5)
    at ProgressCallbackTransform.onend (_stream_readable.js:511:10)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at ProgressCallbackTransform.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at CancellationToken.createPromise (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontapv2\resources\app.asar\node_modules\electron-updater\node_modules\electron-builder-http\src\CancellationToken.ts:51:5)
    at C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontapv2\resources\app.asar\node_modules\electron-updater\src\electronHttpExecutor.ts:25:44
    at Generator.next (<anonymous>)
`

**Comment by daveywc** [comment]
I noticed that people reported a similar problem a few months ago with an earlier version of electron-updater.  However that issue was meant to be fixed in a much earlier build than what I am using.

**Comment by daveywc** [comment]
@develar This is the earlier fix that I am talking about that seems to be fixing a similar problem to the one that I am experiencing.  https://github.com/electron-userland/electron-builder/pull/1077

**Comment by wharri220** [comment]
I am seeing this same issue on an installed application.

**Comment by daveywc** [comment]
@develar Do you have any other thoughts on this issue?  It is my last hurdle to jump in getting the whole build/update thing working :-).

**Comment by develar** [comment]
Working on it. Probably I will give up and checksum will be not checked on the fly, but using file on disk.

**Comment by daveywc** [comment]
I just tried again using dev-app-update.yml, after making the other changes that I have been working on, and this time the checksum validation did not fail. My app no longer runs after the update... but I am putting that down to doing it in dev mode.  About to have another try with an installed application.

**Comment by daveywc** [comment]
@develar In fact I think I now know why the checksum was failing.  On my nodejs http server that was serving up the update I had mistakenly set the encoding on fs.ReadFile to utf8.  I removed that this morning because it was causing me some other problems.  I bet that was also the problem with the checksum.  My apologies if I have sent you on a "wild goose chase".

**Comment by develar** [comment]
So, close?
