### ISSUE TITLE
Call to doDownloadUpdate Failing

### ISSUE THREAD

**Issue by daveywc** [electron-userland/electron-builder#1599]
"electron-builder": "^18.1.0"

"electron-updater": "^1.16.0"

Target: Windows (NSIS)

I am trying to allow the user to choose whether or not to install the update.  Using the code below.  

`autoUpdater.on('update-available', (versionInfo) => {
        var dialogOptions = {
            type: 'question',
            defaultId: 0,
            buttons: ['Yes', 'No'],
            title: 'Updated Version of Docs On Tap V2',
            message: `Version ${versionInfo.version} is available. Do you want to download and install the update now?`
        }

        dialog.showMessageBox(mainWindow, dialogOptions, function (buttonIndex) {
            log.info(buttonIndex);
            if (buttonIndex === 0) {
                autoUpdater.doDownloadUpdate(versionInfo);//, fileInfo, cancellationToken);
            }
        });
    });`

If the user responds yes then I am calling dodownloadUpdate.  It is failing with the following error:

`Wait for app ready
[15:59:30:0481] [info] App starting...
[15:59:30:0637] [info] current version: 0.0.37
[15:59:30:0637] [info] Checking for update
[15:59:31:0162] [info] Found version 0.0.38 (url: https://filesv2.docsontap.com.au:4343/updates/Docs On Tap V2 Setup 0.0.38.exe)
[15:59:33:0806] [info] 0
Unhandled rejection TypeError: Cannot read property 'headers' of undefined
    at NsisUpdater.computeRequestHeaders (C:\Data\Development\Projects\DocsOnTapV2\node_modules\electron-updater\src\AppUpdater.ts:278:9)
    at C:\Data\Development\Projects\DocsOnTapV2\node_modules\electron-updater\src\NsisUpdater.ts:28:21
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Data\Development\Projects\DocsOnTapV2\node_modules\electron-updater\out\NsisUpdater.js:113:11)
    at Function.<anonymous> (C:\Data\Development\Projects\DocsOnTapV2\electron.js:97:29)`

Can you let me know what I am doing wrong?

Thanks,

David

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/blob/master/docs/encapsulated%20manual%20update%20via%20menu.js#L28

`downloadUpdate()`, not `doDownloadUpdate`

**Comment by daveywc** [comment]
Thank you!
