### ISSUE TITLE
Packaged app trying to read from asar as though it were a directory

### ISSUE THREAD

**Issue by mjswensen** [electron-userland/electron-builder#1642]
* **Version**: 18.6.2

* **Target**: MacOS

Hi, first of all, _thank you so much_ for your work on this project. It's fantastic! 👏❤️

The issue I'm running into may be specific to the [svg2png](https://github.com/domenic/svg2png) package when used with electron-builder.

I am working on an app that uses `svg2png` on the main process. When attempting to render, the following errors are thrown:

    Uncaught Exception:
    Error: write EPIPE
        at exports._errnoException (util.js:1022:11)
        at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)

More descriptively, the caught exception reads as follows:

    Error: Command failed: /(path...)/Themer.app/Contents/Resources/app.asar.unpacked/node_modules/phantomjs-prebuilt/lib/bin/phantomjs /(path...)/Themer.app/Contents/Resources/app.asar/node_modules/svg2png/lib/converter.js {}
      Can't open '/(path...)/Themer.app/Contents/Resources/app.asar/node_modules/svg2png/lib/converter.js'

It appears that the command is trying to read from `app.asar` as though it were a directory, rather than `app.asar.unpacked/`, perhaps.

It's worth noting that I tried packaging the app using `electron-packager` and the problem does not manifest—`svg2png` worked as expected.

**Steps to reproduce**

1. On MacOS, clone [mjswensen/themer-gui](https://github.com/mjswensen/themer-gui) and run `yarn` to install dependencies
2. `yarn run dist`
3. Run dist/mac/Themer.app
4. `cmd`-`Shift`-`O` and select one of the color sets, click "Prefill"
5. `cmd`-`E` and select "Block Wave", click "Export"

**Comment by mjswensen** [comment]
Update: I've found that setting `"asar": false,` in my `package.json` resolves the issue. Which is great!

I'd love to keep the asar in place and use `asarUnpack` to select the necessary file. With this setting in place

    "asarUnpack": "node_modules/svg2png/lib/converter.js",

I've verified that the `converter.js` file is correctly placed in the `app.asar.unpacked/` directory as expected, but the program still fails with the error listed above because `phantomjs` is still looking in `app.asar`. Is it possible to configure electron-builder such that the phantomjs binary will look in `app.asar.unpacked/` instead of `app.asar`?

**Comment by Hokkaidosunny** [comment]
you can judge if in asar package enviroment first
```
const isAsar = __dirname.indexOf('asar') >= 0;
if (isAsar) {
  const svg2png = require('../../app.asar.unpacked/node_modules/svg2png');
} else {
  const svg2png = require('svg2png');
}
```

**Comment by mjswensen** [comment]
Thanks for the idea @Hokkaidosunny . Unfortunately, `svg2png` is further down in the dependency tree (a dependency of one of my dependencies), so this won't be an option for me.

**Comment by mjswensen** [comment]
It's worth noting that setting `asar` to `false` in the build configuration fixes this issue for macOS/linux, but not for Windows.

**Comment by develar** [comment]
Have you tried to use asarUnpack option?

**Comment by mjswensen** [comment]
Great minds think alike 🙂 trying it right now.

**Comment by mjswensen** [comment]
Unfortunately the `asarUnpack` option also doesn't work:

    "asarUnpack": [
      "node_modules/svg2png/**",
      "node_modules/phantomjs/**"
    ],

Fails with the same error in the packaged apps for both macOS and Windows.

**Comment by mjswensen** [comment]
| | macOS | Windows |
| --- | --- | --- |
| `"asar": false` | ✅ Works | ❌ Error |
| `asarUnpack` phantomjs | ❌ Error | ❌ Error |

**Comment by Eshva** [comment]
I found a better solution than this hack with isAsar: [Hazardous](https://github.com/epsitec-sa/hazardous)

**Comment by mjswensen** [comment]
Ultimately, to work around the issue, I had to remove my dependency on `svg2png` (and therefore `phantomjs`), updating my application code to remove the relevant features.
