### ISSUE TITLE
node-gyp error while updating electron-builder

### ISSUE THREAD

**Issue by biroplane** [electron-userland/electron-builder#1652]
* **16.6.1**: 
* **MAC**: 

I'm trying to update electron builder from version 17.10.0 to the 18 (required for electron updater 2)

i was trying in different ways with no luck
`npm install --save-dev electron-builder@latest`
or deleting the entire node_modules folder and reinstall via npm install
gets me these errors:
`
> ursa@0.9.4 install /Users/gaetano/Desktop/sqlite/node_modules/ursa
> node-gyp rebuild

  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
  SOLINK_MODULE(target) Release/ursaNative.node

> sodium-native@1.10.1 install /Users/gaetano/Desktop/sqlite/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"

> electron@1.6.10 postinstall /Users/gaetano/Desktop/sqlite/node_modules/electron
> node install.js

> LookIn20@2.0.8 postinstall /Users/gaetano/Desktop/sqlite
> install-app-deps

Rebuilding native production dependencies for darwin:x64
Error: /usr/local/Cellar/node/8.1.0_1/bin/node exited with code 1
Output:

> ursa@0.9.4 install /Users/gaetano/Desktop/sqlite/node_modules/ursa
> node-gyp rebuild

  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o

Error output:
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:13:10: fatal error: 'openssl/rsa.h' file not found
#include <openssl/rsa.h>
         ^
1 error generated.
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/Cellar/node/8.1.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gaetano/Desktop/sqlite/node_modules/ursa
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gaetano/.npm/_logs/2017-06-12T14_53_33_467Z-debug.log

    at ChildProcess.childProcess.once.code (/Users/gaetano/Desktop/sqlite/node_modules/electron-builder-util/src/util.ts:135:14)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:548:12)
From previous event:
    at spawn (/Users/gaetano/Desktop/sqlite/node_modules/electron-builder-util/src/util.ts:103:3)
    at /Users/gaetano/Desktop/sqlite/node_modules/electron-builder/src/yarn.ts:135:5
From previous event:
    at rebuild (/Users/gaetano/Desktop/sqlite/node_modules/electron-builder/out/yarn.js:93:22)
    at /Users/gaetano/Desktop/sqlite/node_modules/electron-builder/src/yarn.ts:16:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at installOrRebuild (/Users/gaetano/Desktop/sqlite/node_modules/electron-builder/out/yarn.js:33:21)
    at /Users/gaetano/Desktop/sqlite/node_modules/electron-builder/src/cli/install-app-deps.ts:32:2
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
From previous event:
    at main (/Users/gaetano/Desktop/sqlite/node_modules/electron-builder/out/cli/install-app-deps.js:36:21)
    at Object.<anonymous> (/Users/gaetano/Desktop/sqlite/node_modules/electron-builder/out/cli/install-app-deps.js:72:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! LookIn20@2.0.8 postinstall: `install-app-deps`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the LookIn20@2.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

i've already installed ursa module and openssl

**Comment by develar** [comment]
> i've already installed ursa module and openssl

`brew install openssl`?

**Comment by biroplane** [comment]
yes. 
actually for me is ` brew update openssl ` because i already have it

**Comment by develar** [comment]
Could you please provide link to project?

**Comment by biroplane** [comment]
https://github.com/biroplane/lookin

**Comment by develar** [comment]
Ursa is outdated and doesn't work with latest openssl version — https://github.com/quartzjer/ursa/pull/147

**Comment by develar** [comment]
Consider to use ursa-purejs (https://github.com/quartzjer/ursa/pull/140).
