### ISSUE TITLE
Building not working since update

### ISSUE THREAD

**Issue by brandonhilkert** [electron-userland/electron-builder#1655]
* **Version**: 18.8.1

* **Target**: Mac/Windows

I just updated to `18.8.1` in hopes to get past https://github.com/electron-userland/electron-builder/issues/1641. I get the following when I build now:

```
> Bark@1.0.7 dist /Users/bhilkert/Dropbox/code/bark-desktop
> WIN_CSC_LINK=./.bark-electron-win.p12 CSC_LINK=./.bark-electron.p12 build -mw --x64 --ia32 --em.main=build/main.js

module.js:472
    throw err;
    ^

Error: Cannot find module '../builder'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at _load_builder (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/.bin/build:7:23)
    at Object.<anonymous> (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/.bin/build:71:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

**Comment by develar** [comment]
Please try 19.1.0

**Comment by brandonhilkert** [comment]
Updated and got:

```
> Bark@1.0.7 dist /Users/bhilkert/Dropbox/code/bark-desktop
> WIN_CSC_LINK=./.bark-electron-win.p12 CSC_LINK=./.bark-electron.p12 build -mw --x64 --ia32 --em.main=build/main.js

Error: Cannot find module 'electron-builder-core'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at _load_electronBuilderCore (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-builder/out/builder.js:90:35)
    at normalizeOptions (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-builder/out/builder.js:206:49)
    at /Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-builder/out/builder.js:22:25
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-builder/out/builder.js:70:21)
    at Object.buildCommandHandler [as handler] (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-builder/out/builder.js:353:5)
    at Object.self.runCommand (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-builder/out/cli/cli.js:42:174)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

**Comment by develar** [comment]
Please remove node_modules and do install again. Consider to use yarn instead of npm.

**Comment by brandonhilkert** [comment]
That was it. Thanks! Is the releases page on GH the page place to enumerate the different releases and their changes?

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/releases

Never, please never use buggy and unreliable npm. Please use yarn.

**Comment by brandonhilkert** [comment]
Ha, got it. I've switched and it was much smoother :)
