### ISSUE TITLE
On autoupdate download failure, app becomes unresponsive

### ISSUE THREAD

**Issue by jessica-pixvana** [electron-userland/electron-builder#1660]
Electron builder version: 18.6.2
electron-updater version: 2.1.2
Target: Mac

After upgrading to the newest electron-builder/updater, I have noticed that the app will hang and become unresponsive if the download begins and then there was an error.

To repo:
Set an incorrect SHA hash in the latest-mac.yml file. Or have the yml point to a nonexistent file. The app will attempt to download the update, fail to do so, and then hang and need to be killed.

Expected result:
App logs download error and then continues to function as normal

Stacktrace for invalid file: 
```2017-06-12 13:33:27:0907] [error] Error: Error: Cannot download "Pixvana SPIN Uploader-0.1.23-mac.zip", status 404: Not Found
    at ClientRequest.fe.httpExecutor.doRequest (/Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/~/electron-updater/out/MacUpdater.js:138:1)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
```
Stacktrace for invalid checksum:
```
[2017-06-12 13:44:33:0347] [error] Error: Error: Cannot download "Pixvana SPIN Uploader-beta-0.1.23-mac.zip": Error: sha512 checksum mismatch, expected 1IvW6xmjCOwLVVYgrcoE61Th6nerqOtKjzaSPimpCPt/vv0MGYiQbYl1XrdySiQYIUhI3u5r9ftPFpbaMwub9Q==, got 7B/MvyQoRTPCNfHc4D3Zjl+zTXxc/H/DnpRLPjn6cFCsdOyDCDriDQNojriTbJeitQCFk0clUL3nRBQnqOZK+w==
    at je.proxyUpdateFile (/Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/~/electron-updater/out/MacUpdater.js:109:1)
    at emitOne (events.js:101:20)
    at je.emit (events.js:191:7)
    at done (_stream_transform.js:178:19)
    at _stream_transform.js:119:9
    at je._flush (/Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/~/electron-updater/~/electron-builder-http/out/httpExecutor.js:187:1)
    at je.<anonymous> (_stream_transform.js:118:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at je.emit (events.js:188:7)
    at prefinish (_stream_writable.js:500:12)
    at finishMaybe (_stream_writable.js:508:7)
    at endWritable (_stream_writable.js:520:3)
    at je.Writable.end (_stream_writable.js:485:5)
    at H.onend (_stream_readable.js:513:10)
    at Object.onceWrapper (events.js:293:19)
From previous event:
    at ie.doDownloadUpdate (/Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/~/electron-updater/out/MacUpdater.js:82:1)
    at /Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/~/electron-updater/out/AppUpdater.js:284:1
    at Generator.next (<anonymous>)
From previous event:
    at ie.downloadUpdate (/Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/~/electron-updater/out/AppUpdater.js:290:1)
    at /Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/~/electron-updater/out/AppUpdater.js:253:1
From previous event:
    at ie.doCheckForUpdates (/Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/~/electron-updater/out/AppUpdater.js:256:1)
    at /Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/~/electron-updater/out/AppUpdater.js:210:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at ie._checkForUpdates (/Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/~/electron-updater/out/AppUpdater.js:215:1)
    at ie.checkForUpdates (/Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/~/electron-updater/out/AppUpdater.js:194:1)
    at WebContents.<anonymous> (/Users/Jessica/projects/Pixvana Uploader/release/mac/Pixvana SPIN Uploader-beta.app/Contents/Resources/app.asar/webpack:/app/main.development.js:299:12)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:191:7)
 ```

**Comment by develar** [comment]
macOS specific (2.x feature), to investigate and fix ASAP.

**Comment by develar** [comment]
Thanks for clear error report.
