### ISSUE TITLE
Electron update fails when using enterprise github

### ISSUE THREAD

**Issue by ofersadgat** [electron-userland/electron-builder#1661]
electron-builder: 18.6.2

electron-updater: 2.1.2

target: win

I'm trying to use an autoupdater for github, my build has the following block: 
```
"publish": [{
      "provider": "github",
      "host": "gh.enterprise.com",
      "repo": "launcher",
      "owner": "osadgat"
}]
```
and when I launch the app I see the following in the log: (obviously, updates dont occur)

[2017-06-12 16:45:52:0486] [info] App starting...
[2017-06-12 16:45:52:0554] [info] Checking for update
[2017-06-12 16:45:52:0575] [info] Checking for update...
[2017-06-12 16:45:53:0085] [error] Error: HttpError: 406 Not Acceptable
" "
Headers: {
  "cache-control": [
    "no-cache, no-store"
  ],
  "content-security-policy": [
    "default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src 'self'; connect-src 'self' gh.enterprise.com status.github.com wss://gh.enterprise.com; font-src 'self'; form-action 'self' gh.enterprise.com; frame-ancestors 'none'; img-src * data:; media-src 'none'; script-src 'self'; style-src 'unsafe-inline' 'self'"
  ],
  "content-type": [
    "application/xml; charset=utf-8"
  ],
  "date": [
    "Mon, 12 Jun 2017 23:45:54 GMT"
  ],
  "server": [
    "GitHub.com"
  ],
  "set-cookie": [
    "_fi_sess=sess%3D%3D--num; path=/; secure; HttpOnly"
  ],
  "status": [
    "406 Not Acceptable"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "vary": [
    "X-PJAX"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-request-id": [
    "id"
  ],
  "x-request-id": [
    "id"
  ],
  "x-runtime": [
    "0.004287"
  ],
  "x-ua-compatible": [
    "IE=Edge,chrome=1"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at IncomingMessage.response.on (C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\node_modules\electron-updater\node_modules\electron-builder-http\src\httpExecutor.ts:109:18)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at CancellationToken.createPromise (C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\node_modules\electron-updater\node_modules\electron-builder-http\src\CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\node_modules\electron-updater\src\electronHttpExecutor.ts:50:30)
    at ElectronHttpExecutor.request (C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\node_modules\electron-updater\node_modules\electron-builder-http\src\httpExecutor.ts:57:17)
    at C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\node_modules\electron-updater\src\GitHubProvider.ts:37:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\node_modules\electron-updater\out\GitHubProvider.js:130:11)
    at C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:184:38
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:255:11)
    at C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:169:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:214:11)
    at NsisUpdater.checkForUpdates (C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:151:35)
    at App.<anonymous> (C:\Users\osadgat\AppData\Local\Programs\launcher\resources\app.asar\app\src\update.js:142:15)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

**Comment by ofersadgat** [comment]
bump?

**Comment by develar** [comment]
Please try electron-updater 2.7.1

**Comment by dawangdw** [comment]
@develar I don't think updater supports enterprise Github. When I use demo code, I always got this 
```
[2017-08-05 10:24:47:0781] [info] App starting...
[2017-08-05 10:24:48:0166] [info] Checking for update
[2017-08-05 10:24:48:0166] [info] Checking for update...
[2017-08-05 10:24:51:0834] [error] Error: Error: Unable to find latest version on GitHub (https://github.***.com/repos/<owner>/<repo>/releases/latest), please ensure a production release exists: HttpError: 406 Not Acceptable
" "
Headers: {
  "cache-control": [
    "no-cache, no-store"
  ],
  "connection": [
    "keep-alive"
  ],
...
```
