### ISSUE TITLE
npm install on windows fails due to fcopy-pre-bundled

### ISSUE THREAD

**Issue by daikiuk** [electron-userland/electron-builder#1662]
* **Version**: 18.8.0

* **Target**: windows

when installing the latest version on windows it fails with the following error. tested with 18.5.1 that installs fine

```

$ npm install electron-builder

> fcopy-pre-bundled@0.1.2 install C:\curo\latest-ui\node_modules\fcopy-pre-bundled
> node-gyp rebuild


C:\curo\latest-ui\node_modules\fcopy-pre-bundled>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp: binding.gyp not found (cwd: C:\curo\latest-ui\node_modules\fcopy-pre-bundled) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\curo\latest-ui\node_modules\fcopy-pre-bundled
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok


```

**Comment by develar** [comment]
Duplicates #1651

Please use yarn and electron-builder 19.2.2
