### ISSUE TITLE
Transitive dependency of own dependency is not compiled against the right Node.js version

### ISSUE THREAD

**Issue by sebn** [electron-userland/electron-builder#1688]
* electron-builder 19.4.2
* macOS Sierra 10.12.5
* node 6.10.2
* electron 1.7.1 (prerelease)
* Target: dmg+zip

- [My electron app](https://github.com/cozy-labs/cozy-desktop/tree/dtrace-provider-issue/gui) depends on my own [`../cli` package](https://github.com/cozy-labs/cozy-desktop/tree/dtrace-provider-issue/cli)...
- ... which depends on [bunyan](https://www.npmjs.com/package/bunyan) v1.8.10...
- ... which depends on [dtrace-provider](https://www.npmjs.com/package/dtrace-provider) v0.8.3 (including native code)

Full build config [here](https://github.com/cozy-labs/cozy-desktop/blob/dtrace-provider-issue/gui/package.json#L26-L57).

Running `yarn install`, `electron-builder install-app-deps` and `electron-builder build`
 works, except electron-builder doesn't seem to rebuild dtrace-provider (see [build output](https://github.com/electron-userland/electron-builder/files/1082560/build-out.txt)) and running the app either directly with `electron .` or from the build output dir fails with the following error:

```
    Error: The module '/var/folders/hg/d2r42c1d1qz0mm83d37m71s00000gn/T/.io.cozy.desktop.FccNRh'
    was compiled against a different Node.js version using
    NODE_MODULE_VERSION 48. This version of Node.js requires
    NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
    the module (for instance, using `npm rebuild` or`npm install`).
        at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
        at Object.Module._extensions..node (module.js:598:18)
        at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/sebn/src/cozy/cozy-desktop/gui/dist/mac/Cozy Desktop.app/Contents/Resources/app.asar/node_modules/cozy-desktop/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Object.<anonymous> (/Users/sebn/src/cozy/cozy-desktop/gui/dist/mac/Cozy Desktop.app/Contents/Resources/app.asar/node_modules/cozy-desktop/node_modules/dtrace-provider/dtrace-provider.js:42:3)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)

    { Error: Cannot find module './build/default/DTraceProviderBindings'
        at Module._resolveFilename (module.js:470:15)
        at Function.Module._resolveFilename (/Users/sebn/src/cozy/cozy-desktop/gui/dist/mac/Cozy Desktop.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
        at Function.Module._load (module.js:418:25)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/sebn/src/cozy/cozy-desktop/gui/dist/mac/Cozy Desktop.app/Contents/Resources/app.asar/node_modules/cozy-desktop/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Object.<anonymous> (/Users/sebn/src/cozy/cozy-desktop/gui/dist/mac/Cozy Desktop.app/Contents/Resources/app.asar/node_modules/cozy-desktop/node_modules/dtrace-provider/dtrace-provider.js:42:3)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/sebn/src/cozy/cozy-desktop/gui/dist/mac/Cozy Desktop.app/Contents/Resources/app.asar/node_modules/cozy-desktop/node_modules/bunyan/lib/bunyan.js:79:18)
        at Object.<anonymous> (/Users/sebn/src/cozy/cozy-desktop/gui/dist/mac/Cozy Desktop.app/Contents/Resources/app.asar/node_modules/cozy-desktop/node_modules/bunyan/lib/bunyan.js:1629:3) code: 'MODULE_NOT_FOUND' }
```

The app still runs with a broken dtrace-provider module and other dependencies (like fsevents on macOS, fswin on Windows, or leveldown on both) seem to work as expected.

Does it look like a bug, or am I doing anything wrong?

Thanks!

**Comment by akosyakov** [comment]
Any updates on it?

**Comment by seekerlee** [comment]
I encountered the same case.

Tried:
./node_modules/.bin/electron-rebuild
./node_modules/.bin/electron-rebuild dtrace-provider -f
./node_modules/.bin/electron-rebuild -f

None works. Don't know if it's an issue.

**Comment by sebn** [comment]
Interestingly, I'm getting the 2nd `Cannot find module './build/default/DTraceProviderBindings'` error outside electron too, so I wonder wether it's relevant...

**Comment by sebn** [comment]
Closing as the layout of my repo was completely updated, the report may not be relevant anymore.
And it would probably be better to isolate the issue to help debugging anyway.
