### ISSUE TITLE
fcopy-pre-bundled not found, 19.5.0

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#1697]
* **Version**:  19.5.0

* **Target**: appx

Gave the new 19.5.0 a shot:

```
...
electron-builder 19.5.0
Using electron-builder.json5 configuration file
No native production dependencies
Packaging for win32 ia32 using electron 1.6.11 to dist\win-ia32-unpacked
CSC_KEY_PASSWORD is not defined, empty password will be used
Signing PhotoSync.exe (certificate file: "E:\xyz\build\cert\xyz.pfx")
Error: Cannot find module 'fcopy-pre-bundled'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
 at require (internal/module.js:11:18)
    at _load_fcopyPreBundled (E:\xyz\node_modules\electron-builder-util\out\fs.js:115:54)
    at E:\xyz\node_modules\electron-builder-util\src\fs.ts:148:5
    at copyOrLinkFile (E:\xyz\node_modules\electron-builder-util\src\fs.ts:147:3)
    at E:\xyz\node_modules\electron-builder-util\src\fs.ts:174:13
    at Generator.next (<anonymous>)
From previous event:
    at FileCopier.copy (E:\xyz\node_modules\electron-builder-util\out\fs.js:242:11)
    at default.map.it (E:\xyz\node_modules\electron-builder\src\util\asarUtil.ts:42:25)
    ...
```

I did a fresh install (deleting the lockfile) of electron builder.

**Comment by develar** [comment]
`fcopy-pre-bundled` is listed in both package.json files, for dev and production. Hmm...

**Comment by black-snow** [comment]
Giving it a quick shot on my mac. Just wondering, why does `yarn comile` yield `yarn compile v0.24.6` and `yarn test` yields `yarn compile v0.26.1`?
It's downloading couple thing in parallel leading to weird console output. Why is it downloading some tmp-xyz-electron-vxy-win*.zip? Also *linux*.zip and armv7l.
I must be doing something wrong. I thought running `yarn test` would be enough. What steps must I take in order to run the tests?

**Comment by develar** [comment]
> why does yarn comile yield yarn compile v0.24.6 and yarn test yields yarn compile v0.26.1?

Because electron-builder uses bundled yarn (https://github.com/electron-userland/electron-builder/blob/master/test/vendor/yarn.js) to avoid yarn installing on CI (CircleCi for example).

> It's downloading couple thing in parallel leading to weird console output. Why is it downloading some tmp-xyz-electron-vxy-win*.zip? Also linux.zip and armv7l.

All required electron versions are downloaded in advance.

**Comment by black-snow** [comment]
Okay. This is the result after `yarn && yarn compile && yarn test`:

```
Snapshot Summary
 › 3 snapshot tests failed in 2 test suites. Inspect your code changes or run with `yarn test -- -u` to update them.

Test Suites: 7 failed, 8 skipped, 12 passed, 19 of 27 total
Tests:       19 failed, 56 skipped, 69 passed, 144 total
Snapshots:   3 failed, 98 passed, 101 total
Time:        263.522s
Ran all test suites.
error Command failed with exit code 1.
```

MacOS 10.12.5 x64
no wine installed
yarn 0.24.6
node v8.1.2

**Comment by develar** [comment]
Should be better now.

**Comment by black-snow** [comment]
Re-test on my mac / yarn0.27.5 / node v8.1.3 / fresh sync with master:

```
console.error packages/electron-updater/out/AppUpdater.js:139
    Error: Error: sha512 checksum mismatch, expected Dj51I0q8aPQ3ioaz9LMqGYujAYRbDNblAQbodDRXAMxmY6hsHqEl3F6SvhfJj5oPhcqdX1ldsgEvfMNXGUXBIZ==, got Dj51I0q8aPQ3ioaz9LMqGYujAYRbDNblAQbodDRXAMxmY6hsHqEl3F6SvhfJj5oPhcqdX1ldsgEvfMNXGUXBIw==
        at DigestTransform._flush (/Users/Shared/electron-builder/packages/electron-builder-http/src/httpExecutor.ts:189:46)
...
    From previous event:
        at CancellationToken.createPromise (/Users/Shared/electron-builder/packages/electron-builder-http/src/CancellationToken.ts:51:5)
        at /Users/Shared/electron-builder/packages/electron-builder-util/src/nodeHttpExecutor.ts:28:44
...
    From previous event:
        at NsisUpdater.doDownloadUpdate (/Users/Shared/electron-builder/packages/electron-updater/out/NsisUpdater.js:128:11)


FAIL  test/out/filesTest.js (111.561s)
  ● extraResources on Linux and Windows

    Exit code: ENOENT. spawn mono ENOENT
      
      at packages/electron-builder-util/src/util.ts:64:16
  (I don't have mono installed - that's why?)


Test Suites: 1 failed, 7 skipped, 19 passed, 20 of 27 total
Tests:       1 failed, 59 skipped, 88 passed, 148 total
Snapshots:   125 passed, 125 total
Time:        419.554s
Ran all test suites.
error Command failed with exit code 1.
```

**Comment by develar** [comment]
Squirrel is deprecated and we do no provide prebuilt. Please brew install mono

**Comment by develar** [comment]
SHA mismatch is is ok — we test mismatch:)

**Comment by black-snow** [comment]
Weird that the exception is printed, though. :)
Will install mono and retry. Maybe it should be added to CONTRIBUTING how to run tests / that mono is required (on OSX at least).
