### ISSUE TITLE
Unable to upload files: Debian distribution, component and architecture were not found on repo and were not specified when deploying to Bintray

### ISSUE THREAD

**Issue by jviotti** [electron-userland/electron-builder#1702]
* **Version**: 19.5.0

* **Target**: debian

I'm testing automatic publishing to Bintray with a dummy application called "digital-clock". This is how my `package.json` file looks like:

```json
{
  "name": "digital-clock",
  "version": "1.0.0",
  "description": "Digital Clock is a dummy Electron application that displays the current time",
  "author": "John Doe <johndoe@example.com>",
  "license": "BSD",
  "main": "main.js",
  "homepage": "digitalclock.com",
  "build": {
    "appId": "com.example.digitalclock",
    "productName": "Digital Clock",
    "publish": [
      {
        "provider": "github",
        "repo": "digital-clock",
        "owner": "jviotti"
      }
    ],
    "linux": {
      "category": "Utils",
      "icon": "assets/icons",
      "packageCategory": "utils",
      "maintainer": "Jane Doe <janedoe@example.com>",
      "target": [ "deb", "rpm", "AppImage", "snap" ],
      "synopsis": "A minimalistic digital clock rendered in monospace font"
    },
    "deb": {
      "publish": [
        {
          "package": "digital-clock",
          "repo": "digital-clock-debian",
          "user": "jviotti",
          "provider": "bintray"
        }
      ],
      "depends": [
        "gconf2",
        "gconf-service",
        "libnotify4",
        "libappindicator1",
        "libxtst6",
        "libnss3"
      ]
    },
    "rpm": {
      "publish": [
        {
          "package": "digital-clock",
          "repo": "digital-clock-rpm",
          "user": "jviotti",
          "provider": "bintray"
        }
      ],
      "depends": [
        "GConf2",
        "libnotify",
        "nss",
        "libappindicator",
        "libXtst"
      ]
    },
    "snap": {
      "confinement": "strict",
      "summary": "A minimalistic digital clock rendered in monospace font",
      "grade": "stable",
      "buildPackages": [],
      "stagePackages": [
        "libnotify4",
        "libappindicator1",
        "libxtst6",
        "libnss3",
        "libxss1",
        "fontconfig-config",
        "gconf2",
        "libasound2",
        "pulseaudio"
      ],
      "plugs": [
        "default",
        "unity8-calendar"
      ]
    }
  },
  "scripts": {
    "pack": "build --dir",
    "dist": "build",
    "release": "build",
    "postinstall": "install-app-deps",
    "start": "electron ."
  },
  "devDependencies": {
    "electron": "1.6.6",
    "electron-builder": "^19.5.0"
  }
}
```

And this is my `digital-clock-debian` Bintray repository:

<img width="475" alt="screen shot 2017-06-18 at 5 38 56 pm" src="https://user-images.githubusercontent.com/2192773/27264464-0dad91ec-544d-11e7-9bf7-a95c73a7b917.png">

When I run this on Travis CI (which has a `BT_TOKEN` env var), I get the following error message:

```
HttpError: 400 Bad Request

{

  "message": "Unable to upload files: Debian distribution, component and architecture were not found on repo and were not specified"

}

Headers: {

  "server": "nginx",

  "date": "Sun, 18 Jun 2017 21:35:26 GMT",

  "content-type": "application/json",

  "transfer-encoding": "chunked",

  "connection": "close",

  "x-ratelimit-limit": "1440",

  "x-ratelimit-remaining": "0"

}

    at HttpError (/app/node_modules/electron-builder-http/src/httpExecutor.ts:40:5)

    at IncomingMessage.response.on.e (/app/node_modules/electron-builder-http/src/httpExecutor.ts:109:18)

    at emitNone (events.js:91:20)

    at IncomingMessage.emit (events.js:185:7)

    at endReadableNT (_stream_readable.js:974:12)

    at _combinedTickCallback (internal/process/next_tick.js:80:11)

    at process._tickCallback (internal/process/next_tick.js:104:9)

From previous event:

    at CancellationToken.createPromise (/app/node_modules/electron-builder-http/src/CancellationToken.ts:51:5)

    at NodeHttpExecutor.doApiRequest (/app/node_modules/electron-builder-util/src/nodeHttpExecutor.ts:52:30)

    at /app/node_modules/electron-publish/src/BintrayPublisher.ts:62:35

    at next (native)

    at runCallback (timers.js:672:20)

    at tryOnImmediate (timers.js:645:5)

    at processImmediate [as _immediateCallback] (timers.js:617:5)

From previous event:

    at BintrayPublisher.doUpload (/app/node_modules/electron-publish/out/BintrayPublisher.js:124:11)

    at /app/node_modules/electron-publish/src/publisher.ts:75:16

    at next (native)

    at /app/node_modules/graceful-fs/polyfills.js:287:18

    at FSReqWrap.oncomplete (fs.js:123:15)

From previous event:

    at BintrayPublisher.upload (/app/node_modules/electron-publish/out/publisher.js:91:11)

    at /app/node_modules/electron-builder/src/publish/PublishManager.ts:145:34

From previous event:

    at PublishManager.artifactCreated (/app/node_modules/electron-builder/out/publish/PublishManager.js:474:11)

    at EventEmitter.PublishManager.packager.artifactCreated.event (/app/node_modules/electron-builder/src/publish/PublishManager.ts:108:57)

    at emitOne (events.js:101:20)

    at EventEmitter.emit (events.js:188:7)

    at Packager.dispatchArtifactCreated (/app/node_modules/electron-builder/src/packager.ts:107:23)

    at LinuxPackager.dispatchArtifactCreated (/app/node_modules/electron-builder/src/platformPackager.ts:89:15)

    at /app/node_modules/electron-builder/src/targets/fpm.ts:189:19

    at next (native)

From previous event:

    at FpmTarget.build (/app/node_modules/electron-builder/out/targets/fpm.js:236:11)

    at default.each.it (/app/node_modules/electron-builder/src/platformPackager.ts:103:87)

    at runCallback (timers.js:672:20)

    at tryOnImmediate (timers.js:645:5)

    at processImmediate [as _immediateCallback] (timers.js:617:5)

From previous event:

    at postAsyncTasks.push.default.map.then (/app/node_modules/electron-builder/src/platformPackager.ts:103:35)

From previous event:

    at LinuxPackager.packageInDistributableFormat (/app/node_modules/electron-builder/src/platformPackager.ts:103:8)

    at /app/node_modules/electron-builder/src/platformPackager.ts:98:10

From previous event:

    at LinuxPackager.pack (/app/node_modules/electron-builder/out/platformPackager.js:159:11)

    at /app/node_modules/electron-builder/src/packager.ts:244:24

From previous event:

    at Packager.doBuild (/app/node_modules/electron-builder/out/packager.js:372:11)

    at /app/node_modules/electron-builder/src/packager.ts:164:52

    at next (native)

    at runCallback (timers.js:672:20)

    at tryOnImmediate (timers.js:645:5)

    at processImmediate [as _immediateCallback] (timers.js:617:5)

From previous event:

    at Packager.build (/app/node_modules/electron-builder/out/packager.js:273:11)

    at /app/node_modules/electron-builder/src/builder.ts:235:40

    at next (native)

From previous event:

    at build (/app/node_modules/electron-builder/out/builder.js:69:21)

    at Object.args [as handler] (/app/node_modules/electron-builder/src/cli/cli.ts:42:4)

    at Object.self.runCommand (/app/node_modules/yargs/lib/command.js:233:22)

    at Object.Yargs.self._parseArgs (/app/node_modules/yargs/yargs.js:1018:24)

    at Object.get [as argv] (/app/node_modules/yargs/yargs.js:927:19)

    at Object.<anonymous> (/app/node_modules/electron-builder/src/cli/cli.ts:37:15)

    at Module._compile (module.js:570:32)

    at Object.Module._extensions..js (module.js:579:10)

    at Module.load (module.js:487:32)

    at tryModuleLoad (module.js:446:12)

    at Function.Module._load (module.js:438:3)

    at Module.runMain (module.js:604:10)

    at run (bootstrap_node.js:389:7)

    at startup (bootstrap_node.js:149:9)

    at bootstrap_node.js:504:3
```

What am I missing? I double checked all the publish options I set for the Bintray provider, and I can't spot any issue.

**Comment by develar** [comment]
Is your repo `generic` on bintray?

**Comment by develar** [comment]
It seems you set type to `debian` on bintray and you are first user who did it :)

**Comment by jviotti** [comment]
Oh, interesting :) @develar Will a `generic` bintray type still work as an APT repository?

Looks like we need to send certain HTTP headers to Bintray:

```
X-Bintray-Debian-Distribution
X-Bintray-Debian-Component
X-Bintray-Debian-Architecture
```

**Comment by jviotti** [comment]
Is there a way to run `electron-builder` in debug mode, and see what HTTP requests, and with what headers are been sent?

**Comment by develar** [comment]
>  in debug mode, and see what HTTP requests, and with what headers are been sent?

set env DEBUG=electron-builder

**Comment by jviotti** [comment]
@develar Do you think we can add proper support for debian Bintray repositories? I'm happy to send a PR myself, or help with anything I can.

**Comment by develar** [comment]
PR welcome. Or I will move to backlog.

**Comment by jviotti** [comment]
I've been working on it for a bit, and the major issue is passing the architecture to the publisher instances (to the `.doUpload` methods), so we can use it in the HTTP header.

I have something, but I feel its hacky. I'll create a PR out of WIP and I guess we can improve it together.

**Comment by jviotti** [comment]
Hm, I can't seem to be able to push anything to my fork:

```
open /Users/jviotti/Projects/playground/electron-builder/templates/appx/assets/SampleAppx.150x150.png: no such file or directory
error: failed to push some refs to 'git@github.com:jviotti/electron-builder.git'
```

I don't have this `templates/` directory at all.

**Comment by develar** [comment]
>  feel its hacky

You don't need to create ready-to-push PR. I will polish/change as need.

> I can't seem to be able to push anything to my fork:

Are you on Windows? Is git lfs installed?

**Comment by jviotti** [comment]
Sounds good. I'm on macOS, and I can confirm I have `git-lfs` installed through `brew`:

```sh
Warning: git-lfs 2.1.1 is already installed
```

**Comment by develar** [comment]
On macOS should be ok. Have you cloned using `git lfs clone`? Or `git lfs pull` after pull?

**Comment by jviotti** [comment]
Yeah, I tried again, and no luck. Anyway, here's the patch: https://pastebin.com/64XdEVuc, so you can take a look at it while I keep trying to properly push the branch.

**Comment by solvingJ** [comment]
Found this issue while googling the error. I'm not using electron-builder, but I get the same error when doing curl according to this article: 
https://blog.bintray.com/2014/12/16/hosting-debian-packages-on-bintray-rocks/

`curl -X PUT -T libmypack_0.0.1_i386.deb -umyuser:<API_KEY> https://api.bintray.com/content/myorg/myrepo/mypack/0.0.1/pool/main/m/mypack/libmypack_0.0.1_i386.deb;deb_distribution=mydist;deb_component=main;deb_architecture=i386,amd64`

I create a new Bintray repository, use the default layout, create a package, and do the curl command.  I get the same error shown above.  I feel something might've changed on the bintray side. I'm about to open a ticket, but would like to know if you've had any progress on your side.

**Comment by jviotti** [comment]
@develar Did you have time to look at my patch? I'll see if I can now create a proper PR.

**Comment by jviotti** [comment]
See https://github.com/electron-userland/electron-builder/pull/1884. That implements the hardest needed part, which is to propagate the packages architecture to the actual publishers. Once that's merged, passing the remaining headers is trivial.

**Comment by develar** [comment]
Thanks for a nice feature.

**Comment by akashnimare** [comment]
@jviotti, @develar can you guys point me to a demo project which publishes `.deb` to bintray? Would be very helpful.

**Comment by chros73** [comment]
@akashnimare, I also found this issue while looking for a solution and it wasn't hard to deal with it:
- the small upload [script](https://github.com/chros73/rtorrent-ps-ch/blob/ffdea0254942007e6143be4c71b2030da76631d0/bintray.sh) does the following:
  - upload
  - publish
  - and display files in download list
- filenames look like: `foo-bar_x.y.z-c.b.a-debian-stretch_amd64.deb `
- you need your username and your API key for it

At least it works for now :)
