### ISSUE TITLE
Cross Compilation MacOS > Windows x64 fails.

### ISSUE THREAD

**Issue by nikhiljha** [electron-userland/electron-builder#1705]
* **Version**: 19.4.2

* **Target**: Windows x64

Cross compiling from MacOS Sierra to Windows x64 after doing `brew install wine --without-x11` and `brew install mono`:

```
Skip app dependencies rebuild because platform is different
Packaging for win32 x64 using electron 1.6.11 to dist/win-unpacked
Building Squirrel.Windows for arch x64
Unhandled rejection Error: ENOENT: no such file or directory, stat '/var/folders/m5/mjvtchmd695gl1g8f7jh4dbw0000gn/T/electron-builder-Dcp3aL/0-1-Update.exe'
    at /Users/nikhil/Dev/nemid/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:107:9
    at Generator.next (<anonymous>)
From previous event:
    at pack (/Users/nikhil/Dev/nemid/node_modules/electron-builder-squirrel-windows/out/squirrelPack.js:132:22)
    at /Users/nikhil/Dev/nemid/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:81:5
...
```

package.json:

```
    "win": {
      "target": "squirrel",
      "icon": "build/icon.ico"
    }
```

**Comment by jpthomasset** [comment]
Got a similar problem using the wine docker image to build windows version of our application : 

```
Downloading tmp-37-1-SHASUMS256.txt-1.6.10
[============================================>] 100.0% of 2.96 kB (2.96 kB/s)
Building Squirrel.Windows for arch x64
Unhandled rejection Error: ENOENT: no such file or directory, stat '/tmp/electron-builder-kYXqDE/0-1-Update.exe'
    at /project/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:108:9
    at Generator.next (<anonymous>)
From previous event:
    at pack (/project/node_modules/electron-builder-squirrel-windows/out/squirrelPack.js:133:22)
    at /project/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:82:5
From previous event:
    at buildInstaller (/project/node_modules/electron-builder-squirrel-windows/out/squirrelPack.js:62:21)
    at /project/node_modules/electron-builder-squirrel-windows/src/squirrelWindows.ts:37:11
    at Generator.next (<anonymous>)
From previous event:
    at SquirrelWindowsTarget.build (/project/node_modules/electron-builder-squirrel-windows/out/squirrelWindows.js:74:11)
    at postAsyncTasks.push.default.map.it (/project/node_modules/electron-builder/src/platformPackager.ts:106:85)
From previous event:
    at WinPackager.packageInDistributableFormat (/project/node_modules/electron-builder/src/platformPackager.ts:106:41)
    at /project/node_modules/electron-builder/src/platformPackager.ts:102:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at WinPackager.pack (/project/node_modules/electron-builder/out/platformPackager.js:169:11)
    at /project/node_modules/electron-builder/src/packager.ts:257:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/project/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager.doBuild (/project/node_modules/electron-builder/out/packager.js:379:11)
    at /project/node_modules/electron-builder/src/packager.ts:170:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (/project/node_modules/electron-builder/out/packager.js:274:11)
    at /project/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/project/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/project/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
Error: ENOENT: no such file or directory, open '/tmp/electron-builder-kYXqDE/0-3-stub.exe'
    at copyFile (/project/node_modules/electron-builder-util/src/fs.ts:148:3)
    at /project/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:238:13
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at /project/node_modules/electron-builder-squirrel-windows/out/squirrelPack.js:213:30
    at /project/node_modules/electron-builder-util/src/fs.ts:69:60
    at /project/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at /project/node_modules/electron-builder-util/src/fs.ts:64:10
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at /project/node_modules/electron-builder-util/src/fs.ts:61:51
    at Generator.next (<anonymous>)
    at go$readdir$cb (/project/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at walk (/project/node_modules/electron-builder-util/out/fs.js:110:22)
    at /project/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:222:3
    at Generator.next (<anonymous>)
From previous event:
    at encodedZip (/project/node_modules/electron-builder-squirrel-windows/out/squirrelPack.js:220:22)
    at /project/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:171:9
    at Generator.next (<anonymous>)
From previous event:
    at pack (/project/node_modules/electron-builder-squirrel-windows/out/squirrelPack.js:133:22)
    at /project/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:82:5
From previous event:
    at buildInstaller (/project/node_modules/electron-builder-squirrel-windows/out/squirrelPack.js:62:21)
    at /project/node_modules/electron-builder-squirrel-windows/src/squirrelWindows.ts:37:11
    at Generator.next (<anonymous>)
From previous event:
    at SquirrelWindowsTarget.build (/project/node_modules/electron-builder-squirrel-windows/out/squirrelWindows.js:74:11)
    at postAsyncTasks.push.default.map.it (/project/node_modules/electron-builder/src/platformPackager.ts:106:85)
From previous event:
    at WinPackager.packageInDistributableFormat (/project/node_modules/electron-builder/src/platformPackager.ts:106:41)
    at /project/node_modules/electron-builder/src/platformPackager.ts:102:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at WinPackager.pack (/project/node_modules/electron-builder/out/platformPackager.js:169:11)
    at /project/node_modules/electron-builder/src/packager.ts:257:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/project/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager.doBuild (/project/node_modules/electron-builder/out/packager.js:379:11)
    at /project/node_modules/electron-builder/src/packager.ts:170:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (/project/node_modules/electron-builder/out/packager.js:274:11)
    at /project/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/project/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/project/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! xivo-desktop-assistant@2017.6.0-dev-bb05a4e dist-win64: `build -w --x64`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the xivo-desktop-assistant@2017.6.0-dev-bb05a4e dist-win64 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Building manually the docker images from the github repo dockerfile seems to solve the problem.

**Comment by develar** [comment]
Please try 19.6.0 Is `electron-builder-squirrel-windows` also installed as latest version (in your case 19.4.2)? Please upgrade both `electron-builder` and `electron-builder-squirrel-windows` to `19.6.0`.

**Comment by jpthomasset** [comment]
I have the same issue with 19.6.0. I also test with 19.6.3 without luck. 

It's building fine on my dev environment (without docker image), the failure only occurs when using the `electronuserland/electron-builder:wine` docker image. I've also build my own docker image from your repo and it works fine also. As your docker image is not versioned, I cannot say when the problem occurred in the first place.

I think rebuilding your docker image will fix the problem however it probably should be versioned according to your release cycle of your main project.

Regards,
JP

**Comment by thobai** [comment]
I'm facing the same problem with the `electronuserland/electron-builder:wine` docker image. @jpthomasset, could you share your working docker image as a workaround?

**Comment by jpthomasset** [comment]
Sure, it's already public and available using the following image name `jpthomasset/electron-builder:wine`.

I hope it will help.
Regards,
Jp.

**Comment by thobai** [comment]
Thanks @jpthomasset, works for me!

**Comment by thobai** [comment]
While this solved the issue stated above, I now have the problem that if I just do 
1. `yarn`
2. `./node_modules/.bin/electron-builder --win`

It doesn't create any `node_modules` in the `app` directory and thus, they are missing when running the executable on Windows. I also tried to run `yarn` in the `app` directory, but that gave me other weird error when running the executable. 

Any ideas on how to solve that?
