### ISSUE TITLE
Can not download artifact for mac package

### ISSUE THREAD

**Issue by jeansebbaklouti** [electron-userland/electron-builder#1713]
Hello,

when i try to package my application for mac, i have this error: 
`> Error: Cannot download "https://dl.bintray.com/electron-userland/bin/AppImage-09-07-16-mac.7z", status 500: Internal Server Error
>     at ClientRequest.request.doRequest.response (/Users/vagrant/git/node_modules/electron-builder-http/src/httpExecutor.ts:156:18)
>     at ClientRequest.g (events.js:291:16)
>     at emitOne (events.js:96:13)
>     at ClientRequest.emit (events.js:188:7)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
>     at TLSSocket.socketOnData (_http_client.js:363:20)
>     at emitOne (events.js:96:13)
>     at TLSSocket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at TLSSocket.Readable.push (_stream_readable.js:134:10)
>     at TLSWrap.onread (net.js:548:20)`

and 

`Unhandled rejection Error: Cannot download "https://dl.bintray.com/electron-userland/bin/fpm-1.8.1-20150715-2.2.2-mac.7z", status 500: Internal Server Error
    at ClientRequest.request.doRequest.response (/Users/vagrant/git/node_modules/electron-builder-http/src/httpExecutor.ts:156:18)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)`

someone has a workaround ?
I use electron-builder 18.0.1
thank you

**Comment by develar** [comment]
Unpack attached file to `~/Library/Caches/electron-builder/AppImage`. Bintray sucks and AppImage will be moved to GitHub soon.
[AppImage-09-07-16-mac.zip](https://github.com/electron-userland/electron-builder/files/1088367/AppImage-09-07-16-mac.zip)

**Comment by jeansebbaklouti** [comment]
thank you a lot !!!

**Comment by balugege** [comment]
Great, i got internal server errors a lot too

**Comment by develar** [comment]
@balugege Should be fixed in 19.6.3
