### ISSUE TITLE
Building Windows App On Mac  gets error code 255

### ISSUE THREAD

**Issue by yiye** [electron-userland/electron-builder#1718]
* **19.6.3**: 

* **squirrel.windows**: 

squirrel windows also installed:

```
"electron-builder-squirrel-windows": "^19.6.0"
```
When signing code， got this error:

```
electron-builder 19.6.3
Skip app dependencies rebuild because platform is different
Packaging for win32 x64 using electron 1.6.11 to dist/win-unpacked
Installing app dependencies for arch x64 to /Users/puss/work/fusioncool/client/app
Packaging for darwin x64 using electron 1.6.11 to dist/mac
Signing app (identity: 97DE01EB8F628DC0AB1BAC0BBA240EE01CFF8F81 Developer ID Application: Nanjing Taobao Software Co., Ltd. (XZJYP6FM9P))
Signing FusionCool.exe (certificate file: "/var/folders/k3/8t3rv3911b53mq0dhrt43nzc0000gp/T/electron-builder-d6LuCr/3-4.p12")
Building Squirrel.Windows for arch x64
Signing 3-5-Update.exe (certificate file: "/var/folders/k3/8t3rv3911b53mq0dhrt43nzc0000gp/T/electron-builder-d6LuCr/3-4.p12")
Unhandled rejection Error: ENOENT: no such file or directory, stat '/var/folders/k3/8t3rv3911b53mq0dhrt43nzc0000gp/T/electron-builder-d6LuCr/3-5-Update.exe'
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/puss/work/fusioncool/client/node_modules/_bluebird@3.5.0@bluebird/js/release/debuggability.js:397:19)
    at new PromiseSpawn (/Users/puss/work/fusioncool/client/node_modules/_bluebird@3.5.0@bluebird/js/release/generators.js:43:17)
    at Object.<anonymous> (/Users/puss/work/fusioncool/client/node_modules/_bluebird@3.5.0@bluebird/js/release/generators.js:197:21)
    at Object.build (/Users/puss/work/fusioncool/client/node_modules/_electron-builder@19.6.3@electron-builder/out/builder.js:69:21)
    at pack (/Users/puss/work/fusioncool/client/pack/package.js:84:12)
    at platforms.forEach.plat (/Users/puss/work/fusioncool/client/pack/package.js:64:11)
    at Array.forEach (native)
    at build.then.then.then.paths (/Users/puss/work/fusioncool/client/pack/package.js:63:19)
    at <anonymous>

Building DMG
Building macOS zip
Signing 3-7-stub.exe (certificate file: "/var/folders/k3/8t3rv3911b53mq0dhrt43nzc0000gp/T/electron-builder-d6LuCr/3-4.p12")
Error: Exit code: 255. Command failed: /Users/puss/Library/Caches/electron-builder/winCodeSign/winCodeSign-1.9.0/darwin/10.12/osslsigncode -in /var/folders/k3/8t3rv3911b53mq0dhrt43nzc0000gp/T/electron-builder-d6LuCr/3-7-stub.exe -out /var/folders/k3/8t3rv3911b53mq0dhrt43nzc0000gp/T/electron-builder-d6LuCr/3-7-stub-signed-sha1.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -pkcs12 /var/folders/k3/8t3rv3911b53mq0dhrt43nzc0000gp/T/electron-builder-d6LuCr/3-4.p12 -h sha1 -n FusionCool -i http://fusion-cool.alibaba-inc.com/ -pass feef34935d19c92acbc4761226c92c927d208191b4e56facb36fc53d43d8be46 (sha256 hash) to read PKCS#12 file: /var/folders/k3/8t3rv3911b53mq0dhrt43nzc0000gp/T/electron-builder-d6LuCr/3-4.p12
140736511185928:error:02001002:system library:fopen:No such file or directory:bss_file.c:175:fopen('/var/folders/k3/8t3rv3911b53mq0dhrt43nzc0000gp/T/electron-builder-d6LuCr/3-4.p12','rb')
140736511185928:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:182:

Failed

Failed to read PKCS#12 file: /var/folders/k3/8t3rv3911b53mq0dhrt43nzc0000gp/T/electron-builder-d6LuCr/3-4.p12
140736511185928:error:02001002:system library:fopen:No such file or directory:bss_file.c:175:fopen('/var/folders/k3/8t3rv3911b53mq0dhrt43nzc0000gp/T/electron-builder-d6LuCr/3-4.p12','rb')
140736511185928:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:182:

Failed

    at /Users/puss/work/fusioncool/client/node_modules/_electron-builder-util@19.6.0@electron-builder-util/src/util.ts:67:16
    at ChildProcess.exithandler (child_process.js:259:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/puss/work/fusioncool/client/node_modules/_bluebird@3.5.0@bluebird/js/release/debuggability.js:397:19)
    at new PromiseSpawn (/Users/puss/work/fusioncool/client/node_modules/_bluebird@3.5.0@bluebird/js/release/generators.js:43:17)
    at Object.<anonymous> (/Users/puss/work/fusioncool/client/node_modules/_bluebird@3.5.0@bluebird/js/release/generators.js:197:21)
    at Object.build (/Users/puss/work/fusioncool/client/node_modules/_electron-builder@19.6.3@electron-builder/out/builder.js:69:21)
    at pack (/Users/puss/work/fusioncool/client/pack/package.js:84:12)
    at platforms.forEach.plat (/Users/puss/work/fusioncool/client/pack/package.js:64:11)
    at Array.forEach (native)
    at build.then.then.then.paths (/Users/puss/work/fusioncool/client/pack/package.js:63:19)
    at <anonymous>
```

It's seam that after XXX.exe was signed, the p12 file was deleted!

**Comment by develar** [comment]
Is it possible to provide project to reproduce?

**Comment by dmonay** [comment]
@develar I am running into the same issue. I'm attempting to sign a Windows app on my Mac.

This is the full stack trace:

```
yarn run v1.3.2
$ /Users/dima/workspace/work/XXX/node_modules/.bin/electron-builder -w
  • electron-builder version=20.0.6
  • loaded configuration file=package.json ("build" field)
  • loaded parent configuration preset=react-cra
  • writing effective config file=dist/electron-builder.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • rebuilding native dependency name=fsevents
  • packaging       platform=win32 arch=x64 electron=1.8.2 appOutDir=dist/win-unpacked
  • signing         file=dist/win-unpacked/XXX.exe certificateFile=win.p12
Error: Exit code: 255. Command failed: /Users/dima/Library/Caches/electron-builder/winCodeSign/winCodeSign-1.9.0/darwin/10.12/osslsigncode -in /Users/dima/workspace/work/XXX/dist/win-unpacked/XXX.exe -out /Users/dima/workspace/work/XXX/dist/win-unpacked/XXX-signed-sha1.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -pkcs12 win.p12 -h sha1 -n XXX -i http://./ -pass b055944f51fd0c104493963cbd386dfca19e6608862d282279d2b1572ef81f66 (sha256 hash) failed(PKCS7_add_signature)

Failed

Signing failed(PKCS7_add_signature)

Failed

    at /Users/dima/workspace/work/XXX/node_modules/builder-util/src/util.ts:124:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at doSign (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/windowsCodeSign.js:128:22)
    at defaultExecutor (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/windowsCodeSign.ts:61:12)
    at /Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/windowsCodeSign.ts:68:11
    at Generator.next (<anonymous>)
From previous event:
    at sign (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/windowsCodeSign.js:51:21)
    at /Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/winPackager.ts:250:15
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.doSign (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/winPackager.js:348:11)
    at /Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/winPackager.ts:238:16
From previous event:
    at WinPackager.sign (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/winPackager.js:328:11)
    at /Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/winPackager.ts:327:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.signAndEditResources (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/winPackager.js:405:11)
    at /Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/winPackager.ts:343:18
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/winPackager.js:423:11)
    at /Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/platformPackager.ts:211:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/platformPackager.js:268:11)
    at /Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/platformPackager.ts:115:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/platformPackager.js:188:11)
    at /Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/packager.ts:372:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/dima/workspace/work/XXX/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/packager.js:441:11)
    at /Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/packager.ts:316:52
    at Generator.next (<anonymous>)
    at /Users/dima/workspace/work/XXX/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/dima/workspace/work/XXX/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/packager.js:385:11)
    at /Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/packager.ts:278:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/packager.js:341:11)
    at /Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/src/index.ts:50:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/dima/workspace/work/XXX/node_modules/electron-builder-lib/out/index.js:47:21)
    at build (/Users/dima/workspace/work/XXX/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/dima/workspace/work/XXX/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/Users/dima/workspace/work/XXX/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/Users/dima/workspace/work/XXX/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/dima/workspace/work/XXX/node_modules/electron-builder/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/Users/dima/workspace/work/XXX/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/dima/workspace/work/XXX/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
```

**Comment by dmonay** [comment]
Turns out that I had not installed the Intermediate Certificated. Without having that in the certificate hierarchy, your certificate will not be valid and the signing process will fail.
