### ISSUE TITLE
macOS Sierra 10.12 Build Error: Invalid Version

### ISSUE THREAD

**Issue by naderhen** [electron-userland/electron-builder#1731]
* **Version**: 19.6.3

* **Version**: 2.4.1

* **Target**: 
Windows (NSIS)

After upgrading to 19.6.3, I'm seeing the following error when attempting to build for Windows:

```
electron-builder 19.6.3
  electron-builder Effective config: {
  electron-builder   "appId": "com.electron.my-app",
  electron-builder   "publish": {
  electron-builder     "repo": "my-app-alpha",
  electron-builder     "provider": "bintray",
  electron-builder     "user": "nader@mycompany",
  electron-builder     "package": "my-app",
  electron-builder     "owner": "mycompany"
  electron-builder   },
  electron-builder   "directories": {
  electron-builder     "app": "electron",
  electron-builder     "output": "release"
  electron-builder   },
  electron-builder   "icon": "/Users/naderhen/Developer/mycompany/mycompany/my-repo/build/icon"
  electron-builder } +0ms
  electron-builder Two package.json structure is used (dev: /Users/naderhen/Developer/mycompany/mycompany/my-repo/package.json, app: /Users/naderhen/Developer/mycompany/mycompany/my-repo/electron/package.json) +1s
Skip app dependencies rebuild because platform is different
Packaging for win32 x64 using electron 1.4.15 to release/win-unpacked
  electron-builder Spawning /Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/7zip-bin-mac/7za x -bd /Users/naderhen/Library/Caches/electron/electron-v1.4.15-win32-x64.zip -o/Users/naderhen/Developer/mycompany/mycompany/my-repo/release/win-unpacked +2s

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 54368789 bytes (52 MiB)

Extracting archive: /Users/naderhen/Library/Caches/electron/electron-v1.4.15-win32-x64.zip
--
Path = /Users/naderhen/Library/Caches/electron/electron-v1.4.15-win32-x64.zip
Type = zip
Physical Size = 54368789

Everything is Ok

Files: 74
Size:       137948750
Compressed: 54368789
  electron-builder /Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/7zip-bin-mac/7za (17406) exited with code 0 +4s
  electron-builder Found existing winCodeSign /Users/naderhen/Library/Caches/electron-builder/winCodeSign/winCodeSign-1.9.0 +291ms
TypeError: Invalid Version: 10.12
    at new SemVer (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/semver/semver.js:293:11)
    at compare (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/semver/semver.js:566:10)
    at Object.gte (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/semver/semver.js:615:10)
    at /Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/src/util/macosVersion.ts:20:17
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at isOsVersionGreaterThanOrEqualTo (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/out/util/macosVersion.js:21:22)
    at Lazy.<anonymous> (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/src/util/wine.ts:9:46)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder-util/src/util.ts:240:24)
    at execWine (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/src/util/wine.ts:33:12)
    at /Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/src/winPackager.ts:260:11
From previous event:
    at WinPackager.signAndEditResources (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/out/winPackager.js:334:11)
    at /Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/src/winPackager.ts:268:16
From previous event:
    at WinPackager.postInitApp (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/out/winPackager.js:343:11)
    at /Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/src/platformPackager.ts:193:148
From previous event:
    at WinPackager.doPack (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/out/platformPackager.js:252:11)
    at /Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/src/platformPackager.ts:96:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/out/platformPackager.js:153:11)
    at /Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/src/packager.ts:229:24
From previous event:
    at Packager.doBuild (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/out/packager.js:300:11)
    at /Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/src/packager.ts:161:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/out/packager.js:211:11)
    at Object.<anonymous> (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/src/builder.ts:234:40)
    at Generator.next (<anonymous>)
From previous event:
    at Object.build (/Users/naderhen/Developer/mycompany/mycompany/my-repo/node_modules/electron-builder/out/builder.js:69:21)
    at doBuild (/Users/naderhen/Developer/mycompany/mycompany/my-repo/deploy/build.js:55:37)
    at build (/Users/naderhen/Developer/mycompany/mycompany/my-repo/deploy/build.js:68:27)
    at go (/Users/naderhen/Developer/mycompany/mycompany/my-repo/deploy/prepackage.js:64:32)
    at Object.<anonymous> (/Users/naderhen/Developer/mycompany/mycompany/my-repo/deploy/prepackage.js:72:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

![image](https://user-images.githubusercontent.com/99392/27438566-b0d4ad18-5733-11e7-9571-fa97c7b2e629.png)

It's being thrown here: https://github.com/npm/node-semver/blob/master/semver.js#L293

Relevant PR which I believe fixes it: https://github.com/electron-userland/electron-builder/pull/1733

**Comment by develar** [comment]
Strange. In my case I have 10.12.5.
