### ISSUE TITLE
dependency problem when creating a deb file 

### ISSUE THREAD

**Issue by luimucar** [electron-userland/electron-builder#1747]
* **Version**: 
19.8.0 (latest)

* **Target**: 
linux -ia32 , trying to run in ubuntu 10.04 (32 bits :)) I have to use this old version

I created the deb package, and added the needed json conf params. However the deb package after installation fails to start, the error is that libnss3 does not pass the version check >3.14.3. However, as I understand from wiki, the dependency by default should include this libnss3. My question is: is this a bug and during the installation of the deb the upgrade of libnss3 does not occur? How can I specify that an update of this libnss3 must happen? or do I just simply add a "dependency" : ["libnss3"] because the default parameter is not working?

Thank you in advance. Awesome tool, electron-builder, by the way.
 "linux":{
      "target": "deb"
    },
    "deb":{
      "icon": "src/assets/fav-icon.ico"
    }

**Comment by develar** [comment]
If have to use such old version, maybe AppImage is a better solution?

**Comment by luimucar** [comment]
getting deeper into .deb specification I was able to at least stop installation of the deb package by adding the following as depends parameter:

 "depends":["libnotify4", "libappindicator1", "libxtst6", "libnss3 (>=3.13.3)", "libxss1", "fontconfig-config", "gconf2", "libasound2", "pulseaudio"],

so the user receives a message regarding the check >=3.13.3 and he/she may at least install it manually or whatever with apt-get -f install

I tried AppImage (just changing target parameter) but I got an ugly message. I guess I should update xorriso but do not know how to advance....

thank you

Error: Exit code: ENOENT. spawn xorriso ENOENT
    at /home/ubuntu/projects/parking-station-ui/node_modules/electron-builder-util/src/util.ts:64:16
    at exithandler (child_process.js:211:5)
    at ChildProcess.errorhandler (child_process.js:223:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at exec (/home/ubuntu/projects/parking-station-ui/node_modules/electron-builder-util/src/util.ts:42:3)
    at /home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/src/targets/appImage.ts:78:5
    at next (native)
From previous event:
    at AppImageTarget.build (/home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/out/targets/appImage.js:138:11)
    at postAsyncTasks.push.default.map.it (/home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/src/platformPackager.ts:101:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/src/platformPackager.ts:101:41)
    at /home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/src/platformPackager.ts:97:10
From previous event:
    at LinuxPackager.pack (/home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/out/platformPackager.js:153:11)
    at /home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/src/packager.ts:229:24
From previous event:
    at Packager.doBuild (/home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/out/packager.js:308:11)
    at /home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/src/packager.ts:161:52
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/out/packager.js:219:11)
    at /home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/src/builder.ts:228:40
    at next (native)
From previous event:
    at build (/home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/src/cli/cli.ts:41:4)
    at Object.self.runCommand (/home/ubuntu/projects/parking-station-ui/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/home/ubuntu/projects/parking-station-ui/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/home/ubuntu/projects/parking-station-ui/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/home/ubuntu/projects/parking-station-ui/node_modules/electron-builder/src/cli/cli.ts:36:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by luimucar** [comment]
ok, had to install xorriso: sudo apt-get install xorriso

**Comment by luimucar** [comment]
made a test. created the AppImage with a ubuntu 10.04. it worked in this ubuntu 10.04 (with libs updated properly). Created a new 10.04 version with no libs, executed the AppImage and sadly it did not work: it complained about the libnss3 check.....

**Comment by develar** [comment]
So, it works?

**Comment by luimucar** [comment]
well, no, it doesnot work. looking at AppImage wiki, my current problem may be similar to this:
(extracted from https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages)
"If you run into errors like this
failed to initialize: /lib/tls/i686/cmov/libc.so.6: version `GLIBC_2.11' not found
then the binary is compiled on a newer system than the one you are trying to run it on. You should use a binary that has been compiled on an older system. Unfortunately, the complication is that distributions usually compile the latest versions of applications only on the latest systems, which means that you will have a hard time finding binaries of bleeding-edge softwares that run on older systems. A way around this is to compile dependencies yourself on a not too recent base system, and/or to use LibcWrapGenerator. "

I feel that my problem is in the electron binary that is already compiled when electron-builder gets it to wrap it in the deb,AppImage or whatever. As the electron binary is compiled and it does not work in 10.04 32 bits ubuntu, it will not work either after packaging it through AppImage.

Probably it is easy to distribute the nonworking AppImage/deb and add the installations instructions (please update libnss3)

**Comment by luimucar** [comment]
probably, next step is this, build electron in linux in my distro 10.04 32bits:
https://electron.atom.io/docs/development/build-instructions-linux/

**Comment by develar** [comment]
@luimucar I am sorry, but I don't have time to support __7__  years old distro.

For your information — we provide prebuild packages for AppImage using Ubuntu 14 (trusty).

**Comment by develar** [comment]
Also see https://github.com/electron-userland/electron-builder-binaries/blob/master/appImage-p.sh
