### ISSUE TITLE
Error when building for squirrel windows with cert

### ISSUE THREAD

**Issue by tatgean** [electron-userland/electron-builder#1754]
* **Version**: 19.8.0

* **Target**: Windows Squirrel

When I try to build my app for Windows squirrel with `certificateFile` and `certificatePassword`, the following error pops up:
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at new BuildCacheManager (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/src/util/cacheManager.ts:26:26)
    at /Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/src/winPackager.ts:300:27
From previous event:
    at WinPackager.signAndEditResources (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/out/winPackager.js:422:11)
    at /Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:97:15
From previous event:
    at buildInstaller (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder-squirrel-windows/out/squirrelPack.js:64:21)
    at /Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder-squirrel-windows/src/squirrelWindows.ts:37:11
    at next (native)
From previous event:
    at SquirrelWindowsTarget.build (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder-squirrel-windows/out/squirrelWindows.js:74:11)
    at postAsyncTasks.push.default.map.it (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/src/platformPackager.ts:101:85)
From previous event:
    at WinPackager.packageInDistributableFormat (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/src/platformPackager.ts:101:41)
    at /Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/src/platformPackager.ts:97:10
From previous event:
    at WinPackager.pack (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/out/platformPackager.js:153:11)
    at /Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/src/packager.ts:229:24
From previous event:
    at Packager.doBuild (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/out/packager.js:308:11)
    at /Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/src/packager.ts:161:52
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/out/packager.js:219:11)
    at /Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/src/builder.ts:228:40
    at next (native)
From previous event:
    at build (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/src/cli/cli.ts:41:4)
    at Object.self.runCommand (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/user/Documents/dev/oursky/makeappicon-desktop/node_modules/electron-builder/src/cli/cli.ts:36:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```
However, If I remove the `certificateFile` and `certificatePassword`, it works fine.

**Comment by develar** [comment]
electron-builder-squirrel-windows version?

**Comment by tatgean** [comment]
My electron-builder-squirrel-windows version is 17.6.1.
Thank you.

**Comment by tatgean** [comment]
My build config is as follows:
```
{
	"appId": "some.app.id",
	"win": {
            "target": "squirrel",
            "certificateFile": "absolute-path-to-cert-file",
            "certificatePassword": "cert-pw"
	},
	"squirrelWindows": {
	    "useAppIdAsId": true
	}
}
```

**Comment by tatgean** [comment]
I've done some source code inspection and found that:
1. The code fails when it tries to sign the `Myapp Setup.exe`
2. the `outDir` [here](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/util/cacheManager.ts#L26) is somehow `undefined`

Hope it may help.

**Comment by develar** [comment]
> My electron-builder-squirrel-windows version is 17.6.1.

Must be 19.11.0

**Comment by develar** [comment]
If you use electron-builder 19.8.0, electron-builder-squirrel-windows should be also 19.x

**Comment by tatgean** [comment]
Works well. Thanks!

**Comment by stihie** [comment]
@develar Maybe upgrading the squirrel module wasn't the fix? I'm having the same problem using `electron-builder 19.11.1`  and `electron-builder-squirrel-windows 19.x`. It almost finishes signing and then this...

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at new BuildCacheManager (C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\electron-builder\src\util\cacheManager.ts:26:26)
    at C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\electron-builder\src\winPackager.ts:300:27
From previous event:
    at WinPackager.signAndEditResources (C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\electron-builder\out\winPackager.js:422:11)
    at C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\electron-builder-squirrel-windows\src\squirrelPack.ts:96:18
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```
