### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by Dave-Pham** [electron-userland/electron-builder#1756]
* **Version**: Latest

* **Target**: --l --ia32

On Ubuntu. Any ideas?

```
Error: Exit code: ENOENT. spawn xorriso ENOENT
    at /home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder-util/src/util.ts:64:16
    at exithandler (child_process.js:211:5)
    at ChildProcess.errorhandler (child_process.js:223:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at exec (/home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder-util/src/util.ts:42:3)
    at /home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/src/targets/appImage.ts:78:5
    at next (native)
From previous event:
    at AppImageTarget.build (/home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/out/targets/appImage.js:138:11)
    at postAsyncTasks.push.default.map.it (/home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/src/platformPackager.ts:101:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/src/platformPackager.ts:101:41)
    at /home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/src/platformPackager.ts:97:10
From previous event:
    at LinuxPackager.pack (/home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/out/platformPackager.js:153:11)
    at /home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/src/packager.ts:229:24
From previous event:
    at Packager.doBuild (/home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/out/packager.js:308:11)
    at /home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/src/packager.ts:161:52
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/out/packager.js:219:11)
    at /home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/src/builder.ts:228:40
    at next (native)
From previous event:
    at build (/home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/src/cli/cli.ts:41:4)
    at Object.self.runCommand (/home/dave/Desktop/twitter-stream-gui/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/home/dave/Desktop/twitter-stream-gui/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/home/dave/Desktop/twitter-stream-gui/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/home/dave/Desktop/twitter-stream-gui/node_modules/electron-builder/src/cli/cli.ts:36:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

**Comment by Dave-Pham** [comment]
>apt install xorriso
