### ISSUE TITLE
npm run build:dir failure / Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by psaren** [electron-userland/electron-builder#1768]
* **Version**: electron-builder 18.8.1

* **Target**: 

How can I solve this problem?
* **Error**: 
> electron-builder 18.8.1
No native production dependencies
Packaging for win32 x64 using electron 1.7.4 to build\win-unpacked
Downloading tmp-60820-0-electron-v1.7.4-win32-x64.zip
Error: connect ETIMEDOUT 52.216.82.152:443
Error: connect ETIMEDOUT 52.216.82.152:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
From previous event:
    at D:\wamp64\www\eletron\project-01\node_modules\electron-builder\src\packager\dirPackager.ts:51:7
    at next (native)
From previous event:
    at unpack (D:\wamp64\www\eletron\project-01\node_modules\electron-builder\out\packager\dirPackager.js:40:21)
    at unpackElectron (D:\wamp64\www\eletron\project-01\node_modules\electron-builder\src\packager\dirPackager.ts:36:10)
    at D:\wamp64\www\eletron\project-01\node_modules\electron-builder\src\platformPackager.ts:158:22
    at next (native)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at WinPackager.doPack (D:\wamp64\www\eletron\project-01\node_modules\electron-builder\out\platformPackager.js:280:11)
    at D:\wamp64\www\eletron\project-01\node_modules\electron-builder\src\platformPackager.ts:104:16
    at next (native)
From previous event:
    at WinPackager.pack (D:\wamp64\www\eletron\project-01\node_modules\electron-builder\out\platformPackager.js:177:11)
    at D:\wamp64\www\eletron\project-01\node_modules\electron-builder\src\packager.ts:270:24
From previous event:
    at Packager.doBuild (D:\wamp64\www\eletron\project-01\node_modules\electron-builder\out\packager.js:388:11)
    at D:\wamp64\www\eletron\project-01\node_modules\electron-builder\src\packager.ts:183:52
    at next (native)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (D:\wamp64\www\eletron\project-01\node_modules\electron-builder\out\packager.js:283:11)
    at D:\wamp64\www\eletron\project-01\node_modules\electron-builder\src\builder.ts:199:33
    at next (native)
From previous event:
    at build (D:\wamp64\www\eletron\project-01\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (D:\wamp64\www\eletron\project-01\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by develar** [comment]
NPM registry is not reliable and now, it seems, down. Please wait :(

**Comment by sadenwang** [comment]
@psaren 请问一下你解决了吗？我也遇到这个问题了，不知道是不是网络的问题

**Comment by Vis5** [comment]
그것을 해결 했습니까? 나는 또한이 문제를 겪었다. 네트워크 문제인지 여부는 아직 알 수 없습니다.
