### ISSUE TITLE
Electron-Updater upgrade error

### ISSUE THREAD

**Issue by ccorcos** [electron-userland/electron-builder#1794]
* **Version**: 
```
-		"electron-updater": "1.14.0",
+		"electron-updater": "2.4.4",
```

* **Target**:  Mac

After upgrading electron-updater, I get this error -- doesn't seem terribly helpful :/

```
[2017-07-05 13:04:18:0648] [info] Checking for update
[2017-07-05 13:04:18:0890] [info] Generated new staging user ID: 6be94196-6be5-5f55-90ed-d8306c319dd7
[2017-07-05 13:04:18:0915] [error] Error: Error: net::ERR_CONNECTION_REFUSED
    at CancellationToken.createPromise (/Users/chet/Desktop/Notion Local.app/Contents/Resources/app.asar/node_modules/electron-builder-http/out/CancellationToken.js:57:16)
    at ElectronHttpExecutor.doApiRequest (/Users/chet/Desktop/Notion Local.app/Contents/Resources/app.asar/node_modules/electron-updater/out/electronHttpExecutor.js:88:34)
    at ElectronHttpExecutor.request (/Users/chet/Desktop/Notion Local.app/Contents/Resources/app.asar/node_modules/electron-builder-http/out/httpExecutor.js:102:21)
    at /Users/chet/Desktop/Notion Local.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GenericProvider.js:67:90
    at Generator.next (<anonymous>)
From previous event:
    at GenericProvider.getLatestVersion (/Users/chet/Desktop/Notion Local.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GenericProvider.js:79:11)
    at /Users/chet/Desktop/Notion Local.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:268:46
From previous event:
    at MacUpdater.doCheckForUpdates (/Users/chet/Desktop/Notion Local.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:295:11)
    at /Users/chet/Desktop/Notion Local.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:249:37
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at MacUpdater._checkForUpdates (/Users/chet/Desktop/Notion Local.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:254:11)
    at MacUpdater.checkForUpdates (/Users/chet/Desktop/Notion Local.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:212:39)
    at Timeout._onTimeout (/Users/chet/Desktop/Notion Local.app/Contents/Resources/app.asar/main.js:109:44)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by ccorcos** [comment]
Hmm. I'm not getting this error anymore...
