### ISSUE TITLE
Auto-Update Issue, cannot check for updates

### ISSUE THREAD

**Issue by umairpro1** [electron-userland/electron-builder#1797]
My package.json
```json
{
  "name": "electrontask",
  "version": "2.1.0",
  "description": "Tasks assigned during third month internship",
  "main": "app/index.js",
  "scripts": {
    "start": "electron app",
    "pack": "build --dir",
    "dist": "build -w"
  },
  "build": {
    "asar": "true",
    "appId": "com.electrontask.browser",
    "productName": "Browser",
    "forceCodeSigning": true,
    "win": {
      "certificateFile": "umairpro1@outlook.com.pfx",
      "certificatePassword": "qwerty123"
    }
  },
  "author": "syed umair",
  "license": "ISC",
  "devDependencies": {
    "electron": "^1.6.11",
    "electron-builder": "^19.12.0"
  },
  "dependencies": {
    "electron-updater": "^2.4.4"
  }
}

```
**********************************************************************************************

my main.js

**********************************************************************************************
const {app, BrowserWindow, ipcMain, nativeImage} = require('electron');
let {autoUpdater} = require("electron-updater");

let win = null;

function sendStatusToWindow(text) {
  let title = win.getTitle();
  win.setTitle(title+": "+text);
}
app.on('ready', ()=>{
  win = new BrowserWindow({title:'Browser',show:false,icon:'./app/profile.png'});
	win.maximize();
	win.loadURL(`file://${__dirname}/index.html`);
	win.once('ready-to-show', () => {
  		win.show();
	});
  autoUpdater.allowDowngrade = true;
	autoUpdater.setFeedURL({
		"provider": "github",
    "owner": "umairpro1",
		"token": "86028e2ed545ba1eb61b06acc1c791106add0888",
		"repo": "electronTask"
	});
});

ipcMain.on('update-title',(event,title)=>{
	win.setTitle(title);
});

app.on('window-all-closed', () => {
  app.quit()
});

autoUpdater.on('checking-for-update', () => {
  sendStatusToWindow('Checking for update...');
});
autoUpdater.on('update-available', (ev, info) => {
  sendStatusToWindow('Update available.');
});
autoUpdater.on('update-not-available', (ev, info) => {
  sendStatusToWindow('Update not available.');
});
autoUpdater.on('error', (ev, err) => {
  sendStatusToWindow('Error in auto-updater.:'+err);
  process.stdout.write(ev,err);
});
autoUpdater.on('download-progress', (progressObj) => {
  let log_message = "Download speed: " + progressObj.bytesPerSecond;
  log_message = log_message + ' - Downloaded ' + progressObj.percent + '%';
  log_message = log_message + ' (' + progressObj.transferred + "/" + progressObj.total + ')';
  sendStatusToWindow(log_message);
});
autoUpdater.on('update-downloaded', (ev, info) => {
  sendStatusToWindow('Update downloaded; will install in 5 seconds');
  setTimeout(function() {
    autoUpdater.quitAndInstall();  
  }, 5000)
});
autoUpdater.checkForUpdates();

***********************************************************************************************

I get this error always, i cannot understand why and what is the source of this error please give some incite.

Error:::
Error: TypeError: Cannot read property 'url' of undefined
    at D:\myWorkspace\electronTask\node_modules\electron-updater\src\PrivateGitHubProvider.ts:99:12
    at Generator.next (<anonymous>)
From previous event:
    at PrivateGitHubProvider.getUpdateFile (D:\myWorkspace\electronTask\node_modules\electron-updater\out\PrivateGitHubProvider.js:150:11)
    at D:\myWorkspace\electronTask\node_modules\electron-updater\src\AppUpdater.ts:234:35
From previous event:
    at NsisUpdater.doCheckForUpdates (D:\myWorkspace\electronTask\node_modules\electron-updater\out\AppUpdater.js:295:11)
    at D:\myWorkspace\electronTask\node_modules\electron-updater\src\AppUpdater.ts:201:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at NsisUpdater._checkForUpdates (D:\myWorkspace\electronTask\node_modules\electron-updater\out\AppUpdater.js:254:11)
    at NsisUpdater.checkForUpdates (D:\myWorkspace\electronTask\node_modules\electron-updater\src\AppUpdater.ts:164:35)
    at Object.<anonymous> (D:\myWorkspace\electronTask\app\index.js:60:13)
    at Object.<anonymous> (D:\myWorkspace\electronTask\app\index.js:61:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (D:\myWorkspace\electronTask\node_modules\electron\dist\resources\default_app.asar\main.js:283:12)
    at Object.<anonymous> (D:\myWorkspace\electronTask\node_modules\electron\dist\resources\default_app.asar\main.js:325:5)
    at Object.<anonymous> (D:\myWorkspace\electronTask\node_modules\electron\dist\resources\default_app.asar\main.js:361:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (D:\myWorkspace\electronTask\node_modules\electron\dist\resources\electron.asar\browser\init.js:171:8)
    at Object.<anonymous> (D:\myWorkspace\electronTask\node_modules\electron\dist\resources\electron.asar\browser\init.js:173:3)

**Comment by develar** [comment]
Do you understand all caveats of PrivateGitHubProvider or you just use it and hope that it will work ;)?

**Comment by umairpro1** [comment]
I can't get you please help i am noobie

**Comment by umairpro1** [comment]
And mine is public repo is it possible to autoupdate from public repo

**Comment by develar** [comment]
`PrivateGitHubProvider` is used only when `private` is set in the publish options of the GitHub provider and `GH_TOKEN` env is set. Or when `token` is explicitly set. Please check your configs — must be no `private` or `token`.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.

**Comment by umairpro1** [comment]
yes i have set token in my main,js
autoUpdater.setFeedURL({
"provider": "github",
"owner": "umairpro1",
"token": "86028e2ed545ba1eb61b06acc1c791106add0888",
"repo": "electronTask"
});

**Comment by develar** [comment]
Please remove token. And remove `setFeedURL` call — electron-builder automatically produces meta info file (if repo is not detected, set `publish` in the electron-builder config).

**Comment by umairpro1** [comment]
Thank You @develar 

Thank you so much its working thank you i am very grateful to you
