### ISSUE TITLE
Docker | Build linux on windows 

### ISSUE THREAD

**Issue by DevCubeHD** [electron-userland/electron-builder#1807]
* **Version**:  1.6.6

* **Target**: Linux

Hey, when building on windows I get - of course - this error:
`electron-builder 18.5.1
Building tar.bz2
Error: spawn tar ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

So I researched a bit and found [Multi Platform Build](https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build).. I was sad that I cant build mac on windows but it should be possible to build linux and windows with docker..

https://github.com/electron-userland/electron-builder/wiki/docker
- BUT: when I enter this command it simply says:

`E:\CloudSystem.IO\Webpanel>docker run --rm -ti -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.electron:/root/.electron electronuserland/electron-builder:wine
docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/containers/create: open //./pipe/docker_engine: Das System kann die angegebene Datei nicht finden. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.`

-> Is there any better description / fix?

**Comment by DevCubeHD** [comment]
fixed by using hyperv
