### ISSUE TITLE
Cannot find module 'electron-builder-http'

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#1809]
* **Version**: 19.15.0

* **Target**: Windows ia32 NSIS

Running `build --ia32 --dir` works fine. But the resulting executable file crashes instantly during startup with the following error:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'electron-builder-http'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\dist\win-ia32-unpacked\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at _load_electronBuilderHttp (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\dist\win-ia32-unpacked\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:29:35)
    at AppUpdater (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\dist\win-ia32-unpacked\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:136:66)
    at NsisUpdater (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\dist\win-ia32-unpacked\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:72:9)
    at _load_autoUpdater (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\dist\win-ia32-unpacked\resources\app.asar\node_modules\electron-updater\out\main.js:51:24)
    at Object.get [as autoUpdater] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\dist\win-ia32-unpacked\resources\app.asar\node_modules\electron-updater\out\main.js:62:32)

[OK]
```

Only happens with version `19.15.0`. Version `19.14.0` does not have this issue.

**Comment by develar** [comment]
Thanks for using prerelease version, fixed in 19.15.1.
