### ISSUE TITLE
X-Platform Build - missing deps [macOS]

### ISSUE THREAD

**Issue by black-snow** [electron-userland/electron-builder#1820]
* **Version**: 19.5.1

* **Target**: Win built on Mac (10.12.5)

The wiki says:

> All required system dependencies (except rpm) will be downloaded automatically on demand on macOS 10.12+ (macOS Sierra).

But when I try to build for windows on my mac I get this:

```
electron-builder 19.5.1
Skip app dependencies rebuild because platform is different
Error: Cannot check wine version: Error: Exit code: ENOENT. spawn wine ENOENT
    at /Users/Shared/test/node_modules/electron-builder/src/packager.ts:382:13
    at Generator.throw (<anonymous>)
From previous event:
    at checkWineVersion (/Users/Shared/test/node_modules/electron-builder/out/packager.js:60:22)
    at /Users/Shared/test/node_modules/electron-builder/src/packager.ts:220:17
From previous event:
    at Packager.doBuild (/Users/Shared/test/node_modules/electron-builder/out/packager.js:366:11)
    at /Users/Shared/test/node_modules/electron-builder/src/packager.ts:163:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (/Users/Shared/test/node_modules/electron-builder/out/packager.js:267:11)
    at /Users/Shared/test/node_modules/electron-builder/src/builder.ts:235:40
    at Generator.next (<anonymous>)
    at build (/Users/Shared/test/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/Users/Shared/test/node_modules/electron-builder/src/cli/cli.ts:42:4)
    at Object.self.runCommand (/Users/Shared/test/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/Shared/test/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/Users/Shared/test/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/Shared/test/node_modules/electron-builder/src/cli/cli.ts:37:15)
From previous event:
    at build (/Users/Shared/test/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/Users/Shared/test/node_modules/electron-builder/out/cli/cli.js:121:9)
    at Object.self.runCommand (/Users/Shared/test/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/Shared/test/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/Users/Shared/test/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/Shared/test/node_modules/electron-builder/out/cli/cli.js:117:314)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

```

**Comment by develar** [comment]
Not clear why. Debug log added, will be released soon.

**Comment by develar** [comment]
Please try 19.5.4

**Comment by black-snow** [comment]
```
 FAIL  test/out/filesTest.js (58.933s)
  ● extraResources on Linux and Windows

    Exit code: ENOENT. spawn mono ENOENT
      
      at packages/electron-builder-util/src/util.ts:64:16
      at exithandler (child_process.js:277:5)
      at ChildProcess.errorhandler (child_process.js:289:5)
      at emitOne (events.js:115:13)
      at ChildProcess.emit (events.js:210:7)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:195:12)
      at onErrorNT (internal/child_process.js:366:16)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickCallback (internal/process/next_tick.js:161:9)
      From previous event:
      at exec (packages/electron-builder-util/src/util.ts:42:3)
      at packages/electron-builder-squirrel-windows/src/squirrelPack.ts:179:16
          at Generator.next (<anonymous>)
      From previous event:
      at releasify (packages/electron-builder-squirrel-windows/out/squirrelPack.js:156:22)
      at packages/electron-builder-squirrel-windows/src/squirrelPack.ts:88:30
      From previous event:
      at buildInstaller (packages/electron-builder-squirrel-windows/out/squirrelPack.js:62:21)
      at packages/electron-builder-squirrel-windows/src/squirrelWindows.ts:38:11
          at Generator.next (<anonymous>)
      From previous event:
      at SquirrelWindowsTarget.build (packages/electron-builder-squirrel-windows/out/squirrelWindows.js:75:11)
      at taskManager.addTask.default.map.it (packages/electron-builder/src/platformPackager.ts:105:85)
    ...

Test Suites: 1 failed, 7 skipped, 20 passed, 21 of 28 total
Tests:       1 failed, 62 skipped, 88 passed, 151 total
Snapshots:   124 passed, 124 total
Time:        299.77s
Ran all test suites.
error Command failed with exit code 1.
```

Latest master.

**Comment by develar** [comment]
Squirrel.Windows is deprecated and we are not going to pre bundle mono.

**Comment by black-snow** [comment]
@develar wrong ticket, here's the win-build-on-mac-retry:

```
electron-builder 19.5.1
Skip app dependencies rebuild because platform is different
Error: Cannot check wine version: Error: Exit code: ENOENT. spawn wine ENOENT
    at /Users/Shared/test/node_modules/electron-builder/src/packager.ts:382:13
    at Generator.throw (<anonymous>)
From previous event:
    at checkWineVersion (/Users/Shared/test/node_modules/electron-builder/out/packager.js:60:22)
    at /Users/Shared/test/node_modules/electron-builder/src/packager.ts:220:17
```

Can't see no debug output.

**Comment by develar** [comment]
@black-snow I am sorry for incorrect versioned 19.5.3 and 19.5.4. Please use 19.16.0.

**Comment by black-snow** [comment]
19.16.0 seems to work fine. Didn't try to run it but build passes! +1
