### ISSUE TITLE
Electron-Builder creates module mismatch with serialport package?

### ISSUE THREAD

**Issue by isaacOstler** [electron-userland/electron-builder#1826]
* **Version**: 19.16.0

* **Target**: OS X

I apologize if this the wrong place to post this, I've never posted questions on GitHub before.

I've been trying to build my application with electron-builder, and it compiles without issues.  When I attempt to run the application I get the following error:

`Uncaught Exception:
Error: The module '/var/folders/5t/tjx5q_k91pq8pwzmq8101_jw0000gn/T/.com.example.app.0eJOTo'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/Applications/Interstellar.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Applications/Interstellar.app/Contents/Resources/app.asar/node_modules/serialport/lib/bindings.js:3:35)`

This is a common (and frustrating) error I get with the serialport package.  The solution in the past has been to run:

`electron-rebuild --version=1.4.13 -f`

Which rebuilds serialport no problem and boom, good to go.  Electron-builder told me that electron-rebuild is not needed and recommended removing it from my dev-dependences (which I did).  Unfortunately the module mismatch is still an issue though.  I've been rather confused with how to fix this issue and tried adding `"postinstall": "install-app-deps"` to my scripts object in my package.json.  No luck though.  Does anybody know what I might be doing wrong here?

Thanks in advance!

**Comment by develar** [comment]
Duplicates #1812

**Comment by cdriouech** [comment]
Hello, I have the same problem between Electron Builder and SerialPort, did anyone came out with a solution? 
Thanks!
