### ISSUE TITLE
Upload order seems wrong on macOS / S3

### ISSUE THREAD

**Issue by elan** [electron-userland/electron-builder#1833]
With `electron-builder@^18.0.1`

Building for macOS.

The files upload like this:

```
Publishing to S3 (bucket: blah)
[====================] 100% 0.0s | Foo-1.0.11.dmg to S3
[====================] 100% 0.0s | latest-mac.json to S3
[====================] 100% 0.0s | latest-mac.yml to S3
[====================] 100% 0.0s | Foo-1.0.11-mac.zip to S3
```

The manifest files are uploaded _before_ the zip file, so it's possible for a client to run into a race condition. It's not a critical issue because presumably it'll work in a little bit, but it still leads to unnecessary errors for the app.

```
[2017-07-17 09:30:45:0074] [error] Error: Error: Cannot download "https://foo.s3.amazonaws.com/releases/Foo-1.0.11-mac.zip", status 404: Not Found
    at ClientRequest.downloadRequest.httpExecutor.doRequest.downloadResponse (/Applications/Foo.app/Contents/Resources/app.asar/webpack:/~/electron-updater/out/MacUpdater.js:122:1)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at URLRequest.ClientRequest.urlRequest.on (/Applications/Winamplex.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:188:7)
[2017-07-17 09:30:45:0075] [warn] Error: Update download failed. The server sent an invalid response. Try again later.

[2017-07-17 09:30:45:0076] [error] Error: Error: Update download failed. The server sent an invalid response. Try again later.
```

**Comment by develar** [comment]
Interesting, will be fixed.

**Comment by elan** [comment]
Thanks for the fix!
