### ISSUE TITLE
Codesing Command failed : signature too large to embed (size limitation of on-disk representation)

### ISSUE THREAD

**Issue by isNeilLin** [electron-userland/electron-builder#1834]
* **Version**: 
electron-builder: 19.16.0
electron: 1.4.13 

* **Target**: 
OSX

```javascript
Error: Command failed: codesign --sign 386D1D89C204824F22337EC75275EE4168F1DB8A --force /Users/neil/Documents/MyAppName/happy/dist/mac/happycoding.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
/Users/neil/Documents/MyAppName/happy/dist/mac/happycoding.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib: signature too large to embed (size limitation of on-disk representation)
at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/neil/Documents/MyAppName/happy/node_modules/.3.5.0@bluebird/js/release/debuggability.js:397:19)
    at new PromiseSpawn (/Users/neil/Documents/MyAppName/happy/node_modules/.3.5.0@bluebird/js/release/generators.js:43:17)
    at /Users/neil/Documents/MyAppName/happy/node_modules/.3.5.0@bluebird/js/release/generators.js:197:21
    at build (/Users/neil/Documents/MyAppName/happy/node_modules/.19.16.0@electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/Users/neil/Documents/MyAppName/happy/node_modules/.19.16.0@electron-builder/out/cli/cli.js:121:9)
    at Object.self.runCommand (/Users/neil/Documents/MyAppName/happy/node_modules/.8.0.2@yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/neil/Documents/MyAppName/happy/node_modules/.8.0.2@yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/neil/Documents/MyAppName/happy/node_modules/.8.0.2@yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/neil/Documents/MyAppName/happy/node_modules/.19.16.0@electron-builder/out/cli/cli.js:117:465)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! happycoding@4.1.2 dist: `build`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the happycoding@4.1.2 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by isNeilLin** [comment]
I tried to use a test certificate replace，it do work。But it has a warning： `  Mac Developer is used to sign app — it is only for development and testing, not for production`。

**Comment by develar** [comment]
Duplicates https://github.com/electron-userland/electron-osx-sign/issues/119 but not closed for now, since no solution.

Please set env `DEBUG=electron-builder,electron-osx-sign*` and attach log of the terminal output.

Please ensure that you use latest macOS and Xcode.

**Comment by isNeilLin** [comment]
@develar  there is terminal output:
```javascript
electron-builder 19.16.0
  electron-builder Effective config:
  electron-builder appId: com.vread.happycode
  electron-builder mac:
  electron-builder   category: public.app-category.developer-tools
  electron-builder   target:
  electron-builder     - dmg
  electron-builder productName: 快乐码字
  electron-builder asarUnpack:
  electron-builder   - '!**/node_modules/'
  electron-builder   - '!**/CONFIG/'
  electron-builder   - '!**/plugins/'
  electron-builder extraResources:
  electron-builder   - ./node_modules/
  electron-builder   - ./CONFIG/
  electron-builder   - ./plugins/
  electron-builder forceCodeSigning: true
  electron-builder compression: maximum
  electron-builder dmg:
  electron-builder   backgroundColor: '#556689'  electron-builder  +0msCSC_KEY_PASSWORD is not defined, empty password will be used  electron-builder Executing security list-keychains -d user +491ms  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-KDU2Fq/0-1.keychain"  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-8WbcEb/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-obZSfp/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-orkCRO/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-hrBiTu/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-JDfMAk/0-1.keychain"
  electron-builder     "/Users/neil/Library/Caches/electron-builder/electron-builder-root-certs.keychain"
  electron-builder     "/Users/neil/Library/Keychains/login.keychain-db"
  electron-builder  +69ms
  electron-builder Executing security create-keychain -p btXWJ6TyILo= /var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain +64ms
  electron-builder Executing security unlock-keychain -p btXWJ6TyILo= /var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain +51ms
  electron-builder Executing security set-keychain-settings /var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain +45ms
  electron-builder Executing security list-keychains -d user +42ms
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-KDU2Fq/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-8WbcEb/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-obZSfp/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-orkCRO/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-hrBiTu/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-JDfMAk/0-1.keychain"
  electron-builder     "/Users/neil/Library/Caches/electron-builder/electron-builder-root-certs.keychain"
  electron-builder     "/Users/neil/Library/Keychains/login.keychain-db"
  electron-builder  +44ms
  electron-builder Executing security list-keychains -d user -s /var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-KDU2Fq/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-8WbcEb/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-obZSfp/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-orkCRO/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-hrBiTu/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-JDfMAk/0-1.keychain /Users/neil/Library/Caches/electron-builder/electron-builder-root-certs.keychain /Users/neil/Library/Keychains/login.keychain-db +14ms
  electron-builder Executing security import /Users/neil/Documents/test.p12 -k /var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain -T /usr/bin/codesign -T /usr/bin/productbuild -P  +58ms
  electron-builder 1 identity imported.
  electron-builder  +141ms
No native production dependencies
Packaging for darwin x64 using electron 1.4.13 to dist/mac
  electron-builder Spawning /Users/neil/Documents/快乐码字/happy/node_modules/.1.0.1@7zip-bin-mac/7za x -bd /Users/neil/Library/Caches/electron/electron-v1.4.13-darwin-x64.zip -o/Users/neil/Documents/快乐码字/happy/dist/mac +10s

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 42118362 bytes (41 MiB)

Extracting archive: /Users/neil/Library/Caches/electron/electron-v1.4.13-darwin-x64.zip
--
Path = /Users/neil/Library/Caches/electron/electron-v1.4.13-darwin-x64.zip
Type = zip
Physical Size = 42118362

Everything is Ok

Folders: 143
Files: 180
Size:       112397286
Compressed: 42118362
  electron-builder /Users/neil/Documents/快乐码字/happy/node_modules/.1.0.1@7zip-bin-mac/7za (41514) exited with exit code 0 +2s
  electron-builder File patterns of first/default matcher:
  electron-builder      **/*
  electron-builder      !build{,/**/*}
  electron-builder      !dist{,/**/*}
  electron-builder      !**/node_modules/**/*.{dll,exe}
  electron-builder      !**/node_modules/*/{README.md,karma.conf.js,.coveralls.yml,readme.markdown,README,readme.md,readme,test,__tests__,tests,powered-test,example,examples}
  electron-builder      !**/*.{iml,o,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,xproj,cc,obj,pdb,h}
  electron-builder      !**/._*
  electron-builder      !**/electron-builder.{yaml,yml,json,json5,toml}
  electron-builder      !**/{.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,.DS_Store,thumbs.db,.gitignore,.gitkeep,.gitattributes,.npmignore,.idea,.vs,.editorconfig,.flowconfig,.jshintrc,.eslintrc,.yarn-integrity,.yarn-metadata.json,yarn-error.log,yarn.lock,package-lock.json,npm-debug.log,appveyor.yml,.travis.yml,circle.yml,.nyc_output} +30ms
  electron-builder Production dependencies in the /Users/neil/Documents/快乐码字/happy: abbrev, axios, binary, buffers, chainsaw, core-util-is, debug, decompress-zip, decompress-zip/node_modules/graceful-fs, decompress-zip/node_modules/readable-stream, echarts,follow-redirects, iconv-lite, inherits, isarray, jquery, jschardet, jszip, jszip/node_modules/pako, mkpath, ms, node-machine-id, nopt, q, sortablejs, string_decoder, touch, touch/node_modules/nopt, traverse, vue, zrender +75ms
  electron-builder Copying files using pattern: from: /Users/neil/Documents/快乐码字/happy, to: /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources, patterns: node_modules/, CONFIG/, plugins/ +4s
  electron-builder Copying /Users/neil/Documents/快乐码字/happy to /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources +1ms
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.2.2.3@fill-range/LICENSE permissions fixed from 0700 (-rwx------) to 0755 (-rwxr-xr-x) +40s
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.2.2.3@fill-range/README.md permissions fixed from 0700 (-rwx------) to 0755 (-rwxr-xr-x) +2ms
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.2.0.0@arr-diff/LICENSE permissions fixed from 0700 (-rwx------) to 0755 (-rwxr-xr-x) +3s
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.1.1.7@randomatic/LICENSE permissions fixed from 0700 (-rwx------) to 0755 (-rwxr-xr-x) +4s
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.1.1.0@arr-flatten/LICENSE permissions fixed from 0744 (-rwxr--r--) to 0755 (-rwxr-xr-x) +1s
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.1.1.0@arr-flatten/README.md permissions fixed from 0744 (-rwxr--r--) to 0755 (-rwxr-xr-x) +1ms
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.1.0.0@array-slice/LICENSE permissions fixed from 0700 (-rwx------) to 0755 (-rwxr-xr-x) +5s
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.1.0.0@array-slice/README.md permissions fixed from 0700 (-rwx------) to 0755 (-rwxr-xr-x) +1ms
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.1.0.0@array-slice/index.js permissions fixed from 0700 (-rwx------) to 0755 (-rwxr-xr-x) +1ms
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.0.2.1@array-unique/LICENSE permissions fixed from 0700 (-rwx------) to 0755 (-rwxr-xr-x) +2s
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.0.2.1@array-unique/README.md permissions fixed from 0700 (-rwx------) to 0755 (-rwxr-xr-x) +1ms
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.0.2.1@array-unique/index.js permissions fixed from 0700 (-rwx------) to 0755 (-rwxr-xr-x) +2ms
  electron-builder /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Resources/node_modules/.0.1.5@wrap-fn/History.md permissions fixed from 0600 (-rw-------) to 0644 (-rw-r--r--) +3s
  electron-builder Executing security find-identity -v /var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain +3s
  electron-builder Executing security find-identity -v -p codesigning /var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain +11ms
  electron-builder   1) 386D1D89C204824F22337EC75275EE4168F1DB8A "Developer ID Application: Beijing dream of micro literature Information Technology Co., Ltd. (RD7TJ35TVQ)"
  electron-builder      1 valid identities found
  electron-builder  +108ms
  electron-builder   1) 386D1D89C204824F22337EC75275EE4168F1DB8A "Developer ID Application: Beijing dream of micro literature Information Technology Co., Ltd. (RD7TJ35TVQ)"
  electron-builder      1 valid identities found
  electron-builder  +0ms
Signing app (identity: 386D1D89C204824F22337EC75275EE4168F1DB8A Developer ID Application: Beijing dream of micro literature Information Technology Co., Ltd. (RD7TJ35TVQ))
  electron-osx-sign `identity` passed in arguments. +22ms
  electron-osx-sign:warn No `entitlements` passed in arguments:
 * Provide `entitlements` to specify entitlements file for codesign. +1ms
  electron-osx-sign Pre-sign operation enabled for provisioning profile:
 * Disable by setting `pre-embed-previsioning-profile` to `false`. +0ms
  electron-osx-sign Pre-sign operation enabled for entitlements automation with versions >= `1.1.1`:
 * Disable by setting `pre-auto-entitlements` to `false`. +0ms
  electron-osx-sign No `provisioning-profile` passed in arguments, will find in current working directory and in user library... +2ms
  electron-osx-sign No provisioning profile found, will not embed profile in app contents. +2ms
  electron-osx-sign Signing application...
 > Application: /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app
 > Platform: darwin
 > Entitlements: undefined
 > Child entitlements: undefined
 > Additional binaries: undefined
 > Identity: { name: 'Developer ID Application: Beijing dream of micro literature Information Technology Co., Ltd. (RD7TJ35TVQ)',
  hash: '386D1D89C204824F22337EC75275EE4168F1DB8A' } +2ms
  electron-osx-sign Walking... /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents +6ms
  electron-osx-sign Signing... /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +686ms
  electron-osx-sign Executing... codesign --sign 386D1D89C204824F22337EC75275EE4168F1DB8A --force --keychain /var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +0ms
  electron-osx-sign Signing... /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib +2s
  electron-osx-sign Executing... codesign --sign 386D1D89C204824F22337EC75275EE4168F1DB8A --force --keychain /var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib +0ms
  electron-osx-sign Signing... /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib +446ms
  electron-osx-sign Executing... codesign --sign 386D1D89C204824F22337EC75275EE4168F1DB8A --force --keychain /var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib +1ms
  electron-osx-sign Error executing file:
 > Stdout:
 > Stderr: /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib: signature too large to embed (size limitation of on-disk representation)
 +587ms
Unhandled rejection Error: Command failed: codesign --sign 386D1D89C204824F22337EC75275EE4168F1DB8A --force --keychain /var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain /Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
/Users/neil/Documents/快乐码字/happy/dist/mac/快乐码字.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib: signature too large to embed (size limitation of on-disk representation)

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/neil/Documents/快乐码字/happy/node_modules/.3.5.0@bluebird/js/release/debuggability.js:397:19)
    at new PromiseSpawn (/Users/neil/Documents/快乐码字/happy/node_modules/.3.5.0@bluebird/js/release/generators.js:43:17)
    at Object.<anonymous> (/Users/neil/Documents/快乐码字/happy/node_modules/.3.5.0@bluebird/js/release/generators.js:197:21)
    at Object.build (/Users/neil/Documents/快乐码字/happy/node_modules/.19.16.0@electron-builder/out/builder.js:69:21)
    at Object.<anonymous> (/Users/neil/Documents/快乐码字/happy/build.js:13:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

  electron-builder Executing security list-keychains -d user +22ms
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-KDU2Fq/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-8WbcEb/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-obZSfp/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-orkCRO/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-hrBiTu/0-1.keychain"
  electron-builder     "/private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-JDfMAk/0-1.keychain"
  electron-builder     "/Users/neil/Library/Caches/electron-builder/electron-builder-root-certs.keychain"
  electron-builder     "/Users/neil/Library/Keychains/login.keychain-db"
  electron-builder  +19ms
  electron-builder Executing security list-keychains -d user -s /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-Ff6ZHl/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-KDU2Fq/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-8WbcEb/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-obZSfp/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-orkCRO/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-hrBiTu/0-1.keychain /private/var/folders/kf/m2l745lx5_d4xq513ysf51wc0000gn/T/electron-builder-JDfMAk/0-1.keychain /Users/neil/Library/Caches/electron-builder/electron-builder-root-certs.keychain /Users/neil/Library/Keychains/login.keychain-db +1ms
```

**Comment by isNeilLin** [comment]
hi, @develar . I resolved this problem by add `--timestamp=none` option in `electron-osx-sign/sign.js`.
```javascript
function signApplicationAsync (opts) {
  return walkAsync(getAppContentsPath(opts))
    .then(function (childPaths) {
      function ignoreFilePath (opts, filePath) {
        if (opts.ignore) {
          if (typeof opts.ignore === 'function') {
            return opts.ignore(filePath)
          } else if (typeof opts.ignore === 'string') {
            return filePath.match(opts.ignore)
          }
        }
        return false
      }

      if (opts.binaries) childPaths = childPaths.concat(opts.binaries)
      var args = [
        '--sign', opts.identity.hash || opts.identity.name,
        '--timestamp=none',  // add timestamp option there
        '--force'
      ]
      if (opts.keychain) {
        args.push('--keychain', opts.keychain)
      }
      if (opts.requirements) {
        args.push('--requirements', opts.requirements)
      }

      var promise
      if (opts.entitlements) {
        // Sign with entitlements
        promise = Promise.mapSeries(childPaths, function (filePath) {
          if (ignoreFilePath(opts, filePath)) {
            debuglog('Skipped... ' + filePath)
            return
          }
          debuglog(args)
          debuglog('Signing... ' + filePath)
          return execFileAsync('codesign', args.concat('--entitlements', opts['entitlements-inherit'], filePath))
        })
          .then(function () {
            debuglog('Signing... ' + opts.app)
            return execFileAsync('codesign', args.concat('--entitlements', opts.entitlements, opts.app))
          })
      } else {
        // Otherwise normally
        promise = Promise.mapSeries(childPaths, function (filePath) {
          if (ignoreFilePath(opts, filePath)) {
            debuglog('Skipped... ' + filePath)
            return
          }
          debuglog('Signing... ' + filePath)
          return execFileAsync('codesign', args.concat(filePath))
        })
          .then(function () {
            debuglog(args)
            debuglog('Signing... ' + opts.app)
            return execFileAsync('codesign', args.concat(opts.app))
          })
      }

      return promise
        .then(function () {
          // Verify code sign
          debuglog('Verifying...')
          var promise = verifySignApplicationAsync(opts)
            .then(function (result) {
              debuglog('Verified.')
            })

          // Check entitlements if applicable
          if (opts.entitlements) {
            promise = promise
              .then(function () {
                debuglog('Displaying entitlements...')
                return execFileAsync('codesign', [
                  '--display',
                  '--entitlements', ':-', // Write to standard output and strip off the blob header
                  opts.app
                ])
              })
              .then(function (result) {
                debuglog('Entitlements:', '\n',
                  result)
              })
          }
          return promise
        })
    })
}
```

**Comment by PierBover** [comment]
Thanks @isNeilLin I had the same problem and solved it with `--timestamp=none`.

**Comment by develar** [comment]
You should not use `timestamp=none` because in this case app will be not valid when certificate will be expired.

**Comment by hankbao** [comment]
@develar Do we get any solution of this signature issue currently?

**Comment by brenca** [comment]
I've found [here](https://discussions.apple.com/thread/2382180?tstart=0) and [here](https://forums.developer.apple.com/thread/85335) that the `--signature-size` option could help with this bug. I've tested it with my certificate, I picked a value of 12800, and it fixed this for me.

**Comment by ert78gb** [comment]
I got  same `signature too large to embed (size limitation of on-disk representation)` problem.
The travis log https://travis-ci.org/UltimateHackingKeyboard/agent/jobs/350962881
@brenca how do you set ` --signature-size` I could not find this option in electon-builder options

**Comment by ert78gb** [comment]
with travis `osx_image: xcode9.3beta` works
