### ISSUE TITLE
get request timeout error

### ISSUE THREAD

**Issue by chenyuncai** [electron-userland/electron-builder#1839]
* **18.5.1**: 

* **win32 x64**: 

When I use the electron-builder to build a exe file in unbuntu 16.04, I get this err below:

electron-builder 18.5.1
Building NSIS installer
  Packaging NSIS installer for arch x64
Error: Request timed out
    at TLSSocket.socket.setTimeout (/home/work/code/p2p/node_modules/._electron-builder-http@18.5.1@electron-builder-http/src/httpExecutor.ts:184:18)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket.Socket._onTimeout (net.js:351:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/debuggability.js:397:19)
    at new PromiseSpawn (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/generators.js:43:17)
    at /home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/generators.js:197:21
    at build (/home/work/code/p2p/node_modules/._electron-builder@18.5.1@electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/home/work/code/p2p/node_modules/._electron-builder@18.5.1@electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

what can i do to fix this?

Thanks

**Comment by develar** [comment]
1. Please use 19.16.0
2. Do you have proxy?

**Comment by develar** [comment]
@chenyuncai Please answer to a question about proxy. Are you in China?

**Comment by chenyuncai** [comment]
Yes, china. has no proxy

**Comment by chenyuncai** [comment]
I set a proxy and it succeed

**Comment by develar** [comment]
Well, if you are in China or Russia — say thanks to your government.

```
## Electron Mirror of China
ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"
```

https://github.com/electron-userland/electron-download
