### ISSUE TITLE
Where do I set S3 publishing options?

### ISSUE THREAD

**Issue by pupeno** [electron-userland/electron-builder#1846]
On

https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts

it says:

> Example (S3 publish configuration)
> ```
> {
>   "provider": "s3",
>   "bucket": "bucket-name"
> }
> ```

But I cannot find where you supposed to put that configuration.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#publish-options

> Can be specified in the configuration options or any platform- or target- specific options.

**Comment by pupeno** [comment]
So, I have this:

```
  "build": {
    "appId": "tech.dashman.Configurator",
    "mac": {
      "category": "public.app-category.business"
    },
    "win": {
      "icon": "build/icon.ico",
      "publish": "s3"
    }
  }
```

Where does that object go? on what key?

**Comment by develar** [comment]
In the `build`.

**Comment by pupeno** [comment]
I'm sorry, I don't get it, like this:

```
"build": {
    "appId": "tech.dashman.Configurator",
    "mac": {
      "category": "public.app-category.business"
    },
    "win": {
      "icon": "build/icon.ico",
      "publish": ["s3"]
    },
    "provider": "s3",
    "bucket": "dashman-app",
    "path": "/",
    "acl": "public-read"
  }
```

**Comment by pupeno** [comment]
I also tried:

```
"build": {
    "appId": "tech.dashman.Configurator",
    "mac": {
      "category": "public.app-category.business"
    },
    "win": {
      "icon": "build/icon.ico"
    },
    "publish": [
      {
        "provider": "s3",
        "bucket": "dashman-app",
        "path": "/",
        "acl": "public-read"
      }
    ]
  }
```

but I keep getting this error: Error!! TypeError: Cannot read property 'provider' of null

**Comment by pupeno** [comment]
This is the full error:

```
C:\Users\pupeno\Documents\Dashman\clients>node build\dist.js
Rebuilding native production dependencies for win32:ia32
Packaging for win32 ia32 using electron 1.7.4 to dist\win-ia32-unpacked
Copying Dashman.exe to Dashman.scr
Done copying Dashman.exe to Dashman.scr
Packaging NSIS installer for arch ia32
Building NSIS installer
Error!! TypeError: Cannot read property 'provider' of null
    at C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\src\publish\PublishManager.ts:181:22
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at writeUpdateInfo (C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\out\publish\PublishManager.js:115:22)
    at C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\src\publish\PublishManager.ts:103:22
From previous event:
    at PublishManager.artifactCreated (C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\out\publish\PublishManager.js:278:11)
    at EventEmitter.PublishManager.packager.artifactCreated.event (C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\src\publish\PublishManager.ts:72:57)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at Packager.dispatchArtifactCreated (C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\src\packager.ts:78:23)
    at WinPackager.dispatchArtifactCreated (C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\src\platformPackager.ts:88:15)
    at C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\src\targets\nsis.ts:216:14
From previous event:
    at NsisTarget.buildInstaller (C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\out\targets\nsis.js:260:11)
    at C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\src\targets\nsis.ts:59:18
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\out\targets\nsis.js:133:11)
    at C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\src\packager.ts:179:31
From previous event:
    at Packager.doBuild (C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\out\packager.js:299:11)
    at C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\src\packager.ts:143:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\out\packager.js:251:11)
    at Object.<anonymous> (C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\src\builder.ts:214:40)
    at Generator.next (<anonymous>)
From previous event:
    at Object.build (C:\Users\pupeno\Documents\Dashman\clients\node_modules\electron-builder\out\builder.js:63:21)
    at Object.<anonymous> (C:\Users\pupeno\Documents\Dashman\clients\build\dist.js:11:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

C:\Users\pupeno\Documents\Dashman\clients>
```

My full package.json:

```json
{
  "devDependencies": {
    "electron": "^1.7.4",
    "electron-builder": "^11.5.1"
  },
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "eccrypto": "^1.0.3",
    "electron-publisher-s3": "^19.16.0",
    "material-design-icons": "^3.0.1",
    "raven-js": "^3.17.0",
    "secp256k1": "^3.3.0"
  },
  "build": {
    "appId": "tech.dashman.Configurator",
    "win": {
      "icon": "build/icon.ico"
    },
    "publish": [
      {
        "provider": "s3",
        "bucket": "dashman-app",
        "path": "/",
        "acl": "public-read"
      }
    ]
  }
}
```

and my full app/package.json

```json
{
  "name": "Dashman",
  "version": "1.0.0-alpha-2",
  "description": "Dashman is the ultimate dashboard manager.",
  "homepage": "https://dashman.tech",
  "author": "Flexpoint Tech Ltd",
  "main": "main/main.js",
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "eccrypto": "^1.0.3",
    "electron-updater": "^2.7.1",
    "material-design-icons": "^3.0.1",
    "raven-js": "^3.17.0",
    "secp256k1": "^3.3.0"
  }
}
```

**Comment by develar** [comment]
>  "electron-builder": "^11.5.1"

Please use latest version.

**Comment by pupeno** [comment]
Oh my... I didn't realize I was using such an old version.

**Comment by naheller** [comment]
@pupeno did this fix it?
