### ISSUE TITLE
Failed to build on Ubuntu Linux with xorriso error

### ISSUE THREAD

**Issue by zhaoyi0113** [electron-userland/electron-builder#1849]
I am working on an electron application but I failed to run the build on Ubuntu Linux. My project dependent on `electron-builder ^19.10.0`.  Nodejs related versions are shown as below:

```
$ npm --version
5.3.0
$ node --version
v7.7.3
```

The unpacked version can be generated under `dist/linux-unpacked` correctly. But packed app can't be generated and below is the complete error log. 

```
Building AppImage for arch x64
Error: Exit code: 5. Command failed: /home/developer/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/dist/@southbanksoftware/dbkoda-0.6.0-x86_64.AppImage -padding 0 -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/dist/linux-unpacked /usr/bin -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-Ds8xcN/0-1-dbKoda.desktop /@southbanksoftwaredbkoda.desktop -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/build/icons/png/1024x1024.png /usr/share/icons/default/1024x1024/apps/@southbanksoftwaredbkoda.png -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/build/icons/png/128x128.png /usr/share/icons/default/128x128/apps/@southbanksoftwaredbkoda.png -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/build/icons/png/16x16.png /usr/share/icons/default/16x16/apps/@southbanksoftwaredbkoda.png -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/build/icons/png/24x24.png /usr/share/icons/default/24x24/apps/@southbanksoftwaredbkoda.png -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/build/icons/png/256x256.png /usr/share/icons/default/256x256/apps/@southbanksoftwaredbkoda.png -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/build/icons/png/32x32.png /usr/share/icons/default/32x32/apps/@southbanksoftwaredbkoda.png -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/build/icons/png/48x48.png /usr/share/icons/default/48x48/apps/@southbanksoftwaredbkoda.png -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/build/icons/png/512x512.png /usr/share/icons/default/512x512/apps/@southbanksoftwaredbkoda.png -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/build/icons/png/64x64.png /usr/share/icons/default/64x64/apps/@southbanksoftwaredbkoda.png -map /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/build/icons/png/1024x1024.png /.DirIcon -map /home/developer/.cache/electron-builder/AppImage-packages/10.03.17 /usr/lib -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /
GNU xorriso 1.4.4 : RockRidge filesystem manipulator, libburnia project.

xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
libburn : SORRY : Neither stdio-path nor its directory exist
xorriso : FAILURE : Cannot acquire drive '/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/dist/@southbanksoftware/dbkoda-0.6.0-x86_64.AppImage'
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'

GNU xorriso 1.4.4 : RockRidge filesystem manipulator, libburnia project.

xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
libburn : SORRY : Neither stdio-path nor its directory exist
xorriso : FAILURE : Cannot acquire drive '/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/dist/@southbanksoftware/dbkoda-0.6.0-x86_64.AppImage'
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'

    at /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder-util/src/util.ts:64:16
    at ChildProcess.exithandler (child_process.js:217:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)
From previous event:
    at exec (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder-util/src/util.ts:42:3)
    at /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/src/targets/appImage.ts:78:5
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/out/targets/appImage.js:138:11)
    at postAsyncTasks.push.default.map.it (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/src/platformPackager.ts:101:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/src/platformPackager.ts:101:41)
    at /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/src/platformPackager.ts:97:10
From previous event:
    at LinuxPackager.pack (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/out/platformPackager.js:153:11)
    at /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/src/packager.ts:229:24
From previous event:
    at Packager.doBuild (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/out/packager.js:308:11)
    at /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/src/packager.ts:161:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Packager.build (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/out/packager.js:219:11)
    at /home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/src/builder.ts:250:40
    at Generator.next (<anonymous>)
    at build (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/src/cli/cli.ts:41:4)
    at Object.self.runCommand (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/src/cli/cli.ts:36:15)
From previous event:
    at build (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/out/cli/cli.js:114:9)
    at Object.self.runCommand (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/home/developer/jenkins/agent/workspace/dbkoda-linux/dbkoda/node_modules/electron-builder/out/cli/cli.js:110:314)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
error Command failed with exit code 255.
```

**Comment by zhaoyi0113** [comment]
It is not an builder issue. It is my project structure issue. Sorryy for that.
