### ISSUE TITLE
[electron-updater] Error: New version 1.3.0 is not signed by the application owner

### ISSUE THREAD

**Issue by derek-duncan** [electron-userland/electron-builder#1856]
* **electron-builder**: 19.13.0

* **electron-updater**: 2.4.4

* **Target**: nsis

We have been using electron-updater to handle all of our updates for a while. It's been working great! For our most recent app update (1.2.0), I upgraded electron-builder to 19.13.0. However, after releasing 1.3.0 of our app, we're receiving an error we've never had before. `Error: New version 1.3.0 is not signed by the application owner`. We have not changed our signing certificate between updates, and the build process has remained the same. I believe the issue might be coming from #1619.

Any help would be greatly appreciated. We need to find a way to force this update through. I found that we can set `win.verifyUpdateCodeSignature` in our options to `false` to keep this extra validation from running, but we need a way to send this update to existing clients. Right now, our updates are being rejected.

_(some values have been removed for privacy)_
```
[2017-07-23 17:00:02:0653] [info] Error: New version 1.3.0 is not signed by the application owner: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "...",
    "NotBefore": "...",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "...",
    "SignatureAlgorithm": {
      "Value": "...",
      "FriendlyName": "..."
    },
    "Thumbprint": "...",
    "Version": 3,
    "Issuer": "CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US",
    "Subject": "..."
  },
  "TimeStamperCertificate": null,
  "Status": 0,
  "StatusMessage": "Signature verified."
}
    at C:\...\resources\app.asar\app\dist\webpack:\node_modules\electron-updater\out\NsisUpdater.js:121:1
From previous event:
    at E.doDownloadUpdate (C:\...\resources\app.asar\app\dist\webpack:\node_modules\electron-updater\out\NsisUpdater.js:129:1)
    at C:\...\resources\app.asar\app\dist\webpack:\node_modules\electron-updater\out\AppUpdater.js:321:1
    at Generator.next (<anonymous>)
From previous event:
    at E.downloadUpdate (C:\...\resources\app.asar\app\dist\webpack:\node_modules\electron-updater\out\AppUpdater.js:326:1)
    at C:\...\resources\app.asar\app\dist\webpack:\node_modules\electron-updater\out\AppUpdater.js:293:1
From previous event:
    at E.doCheckForUpdates (C:\...\resources\app.asar\app\dist\webpack:\node_modules\electron-updater\out\AppUpdater.js:296:1)
    at C:\...\resources\app.asar\app\dist\webpack:\node_modules\electron-updater\out\AppUpdater.js:250:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at E._checkForUpdates (C:\...\resources\app.asar\app\dist\webpack:\node_modules\electron-updater\out\AppUpdater.js:255:1)
    at E.checkForUpdates (C:\...\resources\app.asar\app\dist\webpack:\node_modules\electron-updater\out\AppUpdater.js:213:1)
    at EventEmitter.c.on (C:\...\resources\app.asar\app\dist\webpack:\lib\updateManager.js:53:4)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at WebContents.<anonymous> (C:\...\resources\electron.asar\browser\api\web-contents.js:247:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by develar** [comment]
Please tr to explicitly set publisherName option in the win. as workaround.

Please send me full and not stripped error message using Slack direct messages or by email.

**Comment by develar** [comment]
Also please use electron-builder 19.16.3

**Comment by neurosnap** [comment]
Latest release on npm is 19.6.3, are you suggesting we upgrade package via github?

**Comment by popod** [comment]
@derek-duncan have you special characters (or accents) in your certificate (in the field "Subject") ?

**Comment by javonclarke** [comment]
Yep!

**Comment by develar** [comment]
Latest version of electron-updater (~ several months already) is more tolerant than before, so, I will close this issue.
