### ISSUE TITLE
[electron-updater] Crashes / corrupts main process when no valid GH release available

### ISSUE THREAD

**Issue by johnmcdowall** [electron-userland/electron-builder#1866]
* **Version**:  electron-builder 19.6.3

electron-updater: 2.7.2

* **Target**: macOS

When using the Github provider for electron-updater, if there's no valid release available, the electron-updater errors out with a massive exception, which somehow destabilizes the main process , causing subsequent weird errors to happen. 

If I change the provider to generic with a fake URL, there's an error with a small exception, but it does not cause any subsequent problems with the main process. 

Here's the exception: 

```
[20:10:27:0483] [info] Checking for update
[20:10:28:0379] [error] Error: Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://github.com/trufflesuite/ganache/releases/latest), please ensure a production release exists: SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.response.on (/<snip>/node_modules/electron-builder-http/src/httpExecutor.ts:114:56)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
From previous event:
    at CancellationToken.createPromise (/<snip>/node_modules/electron-builder-http/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/<snip>/node_modules/electron-updater/src/electronHttpExecutor.ts:49:30)
    at ElectronHttpExecutor.request (/<snip>/node_modules/electron-builder-http/src/httpExecutor.ts:64:17)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:105:77
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersionString (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:135:11)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:55:30
From previous event:
    at GitHubProvider.getLatestVersion (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:121:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:217:38
From previous event:
    at MacUpdater.doCheckForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:295:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:201:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at MacUpdater._checkForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:254:11)
    at MacUpdater.checkForUpdates (/<snip>/node_modules/electron-updater/src/AppUpdater.ts:164:35)
    at WebContents.<anonymous> (/<snip>/app/main.development.js:108:17)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7)
    at JSON.parse (<anonymous>)
    at IncomingMessage.response.on (/<snip>/node_modules/electron-builder-http/src/httpExecutor.ts:114:56)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at CancellationToken.createPromise (/<snip>/node_modules/electron-builder-http/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/<snip>/node_modules/electron-updater/src/electronHttpExecutor.ts:49:30)
    at ElectronHttpExecutor.request (/<snip>/node_modules/electron-builder-http/src/httpExecutor.ts:64:17)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:105:77
    at Generator.next (<anonymous>)
    at GitHubProvider.getLatestVersionString (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:135:11)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:55:30
    at GitHubProvider.getLatestVersion (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:121:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:217:38
    at MacUpdater.doCheckForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:295:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:201:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
    at MacUpdater._checkForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:254:11)
    at MacUpdater.checkForUpdates (/<snip>/node_modules/electron-updater/src/AppUpdater.ts:164:35)
    at WebContents.<anonymous> (/<snip>/app/main.development.js:108:17)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:109:13
    at Generator.throw (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersionString (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:135:11)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:55:30
From previous event:
    at GitHubProvider.getLatestVersion (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:121:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:217:38
From previous event:
    at MacUpdater.doCheckForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:295:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:201:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at MacUpdater._checkForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:254:11)
    at MacUpdater.checkForUpdates (/<snip>/node_modules/electron-updater/src/AppUpdater.ts:164:35)
    at WebContents.<anonymous> (/<snip>/app/main.development.js:108:17)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7),
XML:
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <id>tag:github.com,2008:https://github.com/trufflesuite/ganache/releases</id>
  <link type="text/html" rel="alternate" href="https://github.com/trufflesuite/ganache/releases"/>
  <link type="application/atom+xml" rel="self" href="https://github.com/trufflesuite/ganache/releases.atom"/>
  <title>Release notes from ganache</title>
  <updated>2017-06-23T22:07:26Z</updated>
  <entry>
    <id>tag:github.com,2008:Repository/79269625/v0.0.5</id>
    <updated>2017-07-25T23:56:20Z</updated>
    <link rel="alternate" type="text/html" href="/trufflesuite/ganache/releases/tag/v0.0.5"/>
    <title>WIP DO NOT USE</title>
    <content type="html">&lt;p&gt;Testing the auto updater system&lt;/p&gt;</content>
    <author>
      <name>johnmcdowall</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars0.githubusercontent.com/u/237175?v=4&amp;s=60"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/79269625/v0.0.4</id>
    <updated>2017-07-25T23:15:16Z</updated>
    <link rel="alternate" type="text/html" href="/trufflesuite/ganache/releases/tag/v0.0.4"/>
    <title>WIP DO NOT USE</title>
    <content type="html">&lt;p&gt;Testing auto updater system&lt;/p&gt;</content>
    <author>
      <name>johnmcdowall</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars0.githubusercontent.com/u/237175?v=4&amp;s=60"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/79269625/v0.0.3</id>
    <updated>2017-07-25T22:50:02Z</updated>
    <link rel="alternate" type="text/html" href="/trufflesuite/ganache/releases/tag/v0.0.3"/>
    <title>0.0.3 - Internal WIP Build</title>
    <content type="html">&lt;p&gt;Probably broken - testing auto updating system. Do not use.&lt;/p&gt;</content>
    <author>
      <name>johnmcdowall</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars0.githubusercontent.com/u/237175?v=4&amp;s=60"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/79269625/v0.0.1</id>
    <updated>2017-06-01T22:51:14Z</updated>
    <link rel="alternate" type="text/html" href="/trufflesuite/ganache/releases/tag/v0.0.1"/>
    <title>0.0.1</title>
    <content type="html">&lt;p&gt;This is a first and alpha build for Windows and macOS, really to shake out the build process.&lt;/p&gt;</content>
    <author>
      <name>johnmcdowall</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars0.githubusercontent.com/u/237175?v=4&amp;s=60"/>
  </entry>
</feed>

    at JSON.parse (<anonymous>)
    at IncomingMessage.response.on (/<snip>/node_modules/electron-builder-http/src/httpExecutor.ts:114:56)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at CancellationToken.createPromise (/<snip>/node_modules/electron-builder-http/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/<snip>/node_modules/electron-updater/src/electronHttpExecutor.ts:49:30)
    at ElectronHttpExecutor.request (/<snip>/node_modules/electron-builder-http/src/httpExecutor.ts:64:17)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:105:77
    at Generator.next (<anonymous>)
    at GitHubProvider.getLatestVersionString (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:135:11)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:55:30
    at GitHubProvider.getLatestVersion (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:121:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:217:38
    at MacUpdater.doCheckForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:295:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:201:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
    at MacUpdater._checkForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:254:11)
    at MacUpdater.checkForUpdates (/<snip>/node_modules/electron-updater/src/AppUpdater.ts:164:35)
    at WebContents.<anonymous> (/<snip>/app/main.development.js:108:17)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7)
    at JSON.parse (<anonymous>)
    at IncomingMessage.response.on (/<snip>/node_modules/electron-builder-http/src/httpExecutor.ts:114:56)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at CancellationToken.createPromise (/<snip>/node_modules/electron-builder-http/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/<snip>/node_modules/electron-updater/src/electronHttpExecutor.ts:49:30)
    at ElectronHttpExecutor.request (/<snip>/node_modules/electron-builder-http/src/httpExecutor.ts:64:17)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:105:77
    at Generator.next (<anonymous>)
    at GitHubProvider.getLatestVersionString (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:135:11)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:55:30
    at GitHubProvider.getLatestVersion (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:121:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:217:38
    at MacUpdater.doCheckForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:295:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:201:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
    at MacUpdater._checkForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:254:11)
    at MacUpdater.checkForUpdates (/<snip>/node_modules/electron-updater/src/AppUpdater.ts:164:35)
    at WebContents.<anonymous> (/<snip>/app/main.development.js:108:17)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:109:13
    at Generator.throw (<anonymous>)
    at GitHubProvider.getLatestVersionString (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:135:11)
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:55:30
    at GitHubProvider.getLatestVersion (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:121:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:217:38
    at MacUpdater.doCheckForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:295:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:201:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
    at MacUpdater._checkForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:254:11)
    at MacUpdater.checkForUpdates (/<snip>/node_modules/electron-updater/src/AppUpdater.ts:164:35)
    at WebContents.<anonymous> (/<snip>/app/main.development.js:108:17)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7),
    at /<snip>/node_modules/electron-updater/src/GitHubProvider.ts:59:13
    at Generator.throw (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (/<snip>/node_modules/electron-updater/out/GitHubProvider.js:121:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:217:38
From previous event:
    at MacUpdater.doCheckForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:295:11)
    at /<snip>/node_modules/electron-updater/src/AppUpdater.ts:201:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at MacUpdater._checkForUpdates (/<snip>/node_modules/electron-updater/out/AppUpdater.js:254:11)
    at MacUpdater.checkForUpdates (/<snip>/node_modules/electron-updater/src/AppUpdater.ts:164:35)
    at WebContents.<anonymous> (/<snip>/app/main.development.js:108:17)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7)
```

The exception itself isn't so much of an issue, it's the strange effects it's having on the main process when it happens. Other libraries start raising their own exceptions with weird errors - and this does not happen if another provider is used, even one that errors or is unavailable.

**Comment by johnmcdowall** [comment]
@develar This is still happening in the latest release. 

```
[17:13:06:0152] [error] Error: Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://github.com/trufflesuite/ganache/releases/latest), please ensure a production release exists: SyntaxError: Unexpected end of JSON input
```

I don't think it's that the response is null, it's that its XML...

**Comment by FelikZ** [comment]
To reproduce an issue, try to fork repository and change an `owner` in `app-update.yml`.
Can't find a solution at the moment.

**Comment by FelikZ** [comment]
To fix this problem you have to make sure your fork has "Latest release". It does not transfer releases after fork. It is fixed now.
