### ISSUE TITLE
Cannot find module 'electron-updater' after build

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#1875]
* **Version**: 
"electron": "^1.7.5",
"electron-builder": "^19.18.0",
"electron-updater": "^2.8.0",

* **Target**: Windows & Linux

[My project](https://github.com/cawa-93/command-editor/tree/develop).
When I run the development mode, `electron-updater` is imported well. But for some reason, after the build module was not found.

[import { autoUpdater } from 'electron-updater'](https://github.com/cawa-93/command-editor/blob/develop/src/main/index.js#L64)
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-updater'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/tmp/.mount_hku8A9/usr/bin/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.b.__esModule (/tmp/.mount_hku8A9/usr/bin/resources/app.asar/dist/main/main.js:1:8501)
    at b (/tmp/.mount_hku8A9/usr/bin/resources/app.asar/dist/main/main.js:1:270)
    at Object.<anonymous> (/tmp/.mount_hku8A9/usr/bin/resources/app.asar/dist/main/main.js:1:7047)
    at b (/tmp/.mount_hku8A9/usr/bin/resources/app.asar/dist/main/main.js:1:270)
    at Object.module.exports.Object.defineProperty.value (/tmp/.mount_hku8A9/usr/bin/resources/app.asar/dist/main/main.js:1:6543)
```
I use a docker
```
$ npm run docker
```
And in docker container
```
$ npm run release
```

**Comment by yhostc** [comment]
It seem to be ignored by default file patterns. But i have tried failed, have anything news?

**Comment by cawa-93** [comment]
Yes. For a reason that I do not understand, I have to re-install all the dependencies inside the docker. Those. For development I installed
```
yarn add electron-updater
```
Then I have to perform inside the docker.
```
yarn install
```
