### ISSUE TITLE
"The specified file is not a valid PFX file" error on Appveyor code-signing using base64 encoded CSC_LINK

### ISSUE THREAD

**Issue by jviotti** [electron-userland/electron-builder#1902]
* **Version**: 19.19.1

* **Target**: nsis, portable

I have a p12 file that I encoded using base64 and set as a `CSC_LINK` environment variable in Appveyor, and I get the following error:

```
Warning: Cannot get publisher name using powershell: Exit code: 1. Command failed: powershell.exe (Get-PfxData "C:\Users\appveyor\AppData\Local\Temp\1\electron-builder-1LJBNM\0-1.p12" -Password (ConvertTo-SecureString -String 637a76f73d638b7143381abaae0b5e05109276ff2bb30bf313113b52f7bcfec1 (sha256 hash) -Force -AsPlainText)).EndEntityCertificates.Subject
Get-PfxData : The specified file is not a valid PFX file 
At line:1 char:2
+ (Get-PfxData "C:\Users\appveyor\AppData\Local\Temp\1\electron-builder ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PfxData], ArgumentExce 
   ption
    + FullyQualifiedErrorId : InvalidPFXFile,Microsoft.CertificateServices.Com 
   mands.GetPfxDataCommand
 
Get-PfxData : The specified file is not a valid PFX file 
At line:1 char:2
+ (Get-PfxData "C:\Users\appveyor\AppData\Local\Temp\1\electron-builder ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PfxData], ArgumentExce 
   ption
    + FullyQualifiedErrorId : InvalidPFXFile,Microsoft.CertificateServices.Com 
   mands.GetPfxDataCommand
 
Error: Cannot extract publisher name from code signing certificate, please file issue. As workaround, set win.publisherName: Error: Exit code: 1. Command failed: openssl pkcs12 -nokeys -nodes -passin pass:03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4 (sha256 hash) -nomacver -clcerts -in C:\Users\appveyor\AppData\Local\Temp\1\electron-builder-1LJBNM\0-1.p12
648:error:0D06B08E:asn1 encoding routines:ASN1_D2I_READ_BIO:not enough data:.\crypto\asn1\a_d2i_fp.c:247:
648:error:0D06B08E:asn1 encoding routines:ASN1_D2I_READ_BIO:not enough data:.\crypto\asn1\a_d2i_fp.c:247:
    at C:\projects\digital-clock\node_modules\electron-builder-util\src\util.ts:67:16
    at ChildProcess.exithandler (child_process.js:211:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at exec (C:\projects\digital-clock\node_modules\electron-builder-util\src\util.ts:45:3)
    at C:\projects\digital-clock\node_modules\electron-builder\src\winPackager.ts:386:24
    at next (native)
From previous event:
    at extractCommonNameUsingOpenssl (C:\projects\digital-clock\node_modules\electron-builder\out\winPackager.js:58:22)
    at Lazy.<anonymous> (C:\projects\digital-clock\node_modules\electron-builder\src\winPackager.ts:103:31)
    at throw (native)
From previous event:
    at Lazy.get value [as value] (C:\projects\digital-clock\node_modules\electron-builder-http\src\httpExecutor.ts:307:23)
    at C:\projects\digital-clock\node_modules\electron-builder\src\publish\PublishManager.ts:101:51
    at next (native)
From previous event:
    at PublishManager.packager.addAfterPackHandler (C:\projects\digital-clock\node_modules\electron-builder\out\publish\PublishManager.js:432:29)
    at default.each.it (C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:338:49)
From previous event:
    at Packager.afterPack (C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:338:28)
    at C:\projects\digital-clock\node_modules\electron-builder\src\platformPackager.ts:192:21
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at WinPackager.doPack (C:\projects\digital-clock\node_modules\electron-builder\out\platformPackager.js:248:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\platformPackager.ts:100:16
    at next (native)
From previous event:
    at WinPackager.pack (C:\projects\digital-clock\node_modules\electron-builder\out\platformPackager.js:171:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:244:24
From previous event:
    at Packager.doBuild (C:\projects\digital-clock\node_modules\electron-builder\out\packager.js:317:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:175:52
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (C:\projects\digital-clock\node_modules\electron-builder\out\packager.js:236:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\builder.ts:266:40
    at next (native)
From previous event:
    at build (C:\projects\digital-clock\node_modules\electron-builder\out\builder.js:69:21)
    at Object.args [as handler] (C:\projects\digital-clock\node_modules\electron-builder\src\cli\cli.ts:46:4)
    at Object.self.runCommand (C:\projects\digital-clock\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (C:\projects\digital-clock\node_modules\yargs\yargs.js:1018:24)
    at Object.get [as argv] (C:\projects\digital-clock\node_modules\yargs\yargs.js:927:19)
    at Object.<anonymous> (C:\projects\digital-clock\node_modules\electron-builder\src\cli\cli.ts:41:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
    at C:\projects\digital-clock\node_modules\electron-builder-util\src\util.ts:67:16
    at ChildProcess.exithandler (child_process.js:211:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
    at exec (C:\projects\digital-clock\node_modules\electron-builder-util\src\util.ts:45:3)
    at C:\projects\digital-clock\node_modules\electron-builder\src\winPackager.ts:386:24
    at next (native)
    at extractCommonNameUsingOpenssl (C:\projects\digital-clock\node_modules\electron-builder\out\winPackager.js:58:22)
    at Lazy.<anonymous> (C:\projects\digital-clock\node_modules\electron-builder\src\winPackager.ts:103:31)
    at throw (native)
    at Lazy.get value [as value] (C:\projects\digital-clock\node_modules\electron-builder-http\src\httpExecutor.ts:307:23)
    at C:\projects\digital-clock\node_modules\electron-builder\src\publish\PublishManager.ts:101:51
    at next (native)
    at PublishManager.packager.addAfterPackHandler (C:\projects\digital-clock\node_modules\electron-builder\out\publish\PublishManager.js:432:29)
    at default.each.it (C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:338:49)
    at Packager.afterPack (C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:338:28)
    at C:\projects\digital-clock\node_modules\electron-builder\src\platformPackager.ts:192:21
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at WinPackager.doPack (C:\projects\digital-clock\node_modules\electron-builder\out\platformPackager.js:248:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\platformPackager.ts:100:16
    at next (native)
    at WinPackager.pack (C:\projects\digital-clock\node_modules\electron-builder\out\platformPackager.js:171:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:244:24
    at Packager.doBuild (C:\projects\digital-clock\node_modules\electron-builder\out\packager.js:317:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:175:52
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at Packager.build (C:\projects\digital-clock\node_modules\electron-builder\out\packager.js:236:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\builder.ts:266:40
    at next (native)
    at build (C:\projects\digital-clock\node_modules\electron-builder\out\builder.js:69:21)
    at Object.args [as handler] (C:\projects\digital-clock\node_modules\electron-builder\src\cli\cli.ts:46:4)
    at Object.self.runCommand (C:\projects\digital-clock\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (C:\projects\digital-clock\node_modules\yargs\yargs.js:1018:24)
    at Object.get [as argv] (C:\projects\digital-clock\node_modules\yargs\yargs.js:927:19)
    at Object.<anonymous> (C:\projects\digital-clock\node_modules\electron-builder\src\cli\cli.ts:41:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
    at Lazy.<anonymous> (C:\projects\digital-clock\node_modules\electron-builder\src\winPackager.ts:106:15)
    at throw (native)
From previous event:
    at Lazy.get value [as value] (C:\projects\digital-clock\node_modules\electron-builder-http\src\httpExecutor.ts:307:23)
    at C:\projects\digital-clock\node_modules\electron-builder\src\publish\PublishManager.ts:101:51
    at next (native)
From previous event:
    at PublishManager.packager.addAfterPackHandler (C:\projects\digital-clock\node_modules\electron-builder\out\publish\PublishManager.js:432:29)
    at default.each.it (C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:338:49)
From previous event:
    at Packager.afterPack (C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:338:28)
    at C:\projects\digital-clock\node_modules\electron-builder\src\platformPackager.ts:192:21
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at WinPackager.doPack (C:\projects\digital-clock\node_modules\electron-builder\out\platformPackager.js:248:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\platformPackager.ts:100:16
    at next (native)
From previous event:
    at WinPackager.pack (C:\projects\digital-clock\node_modules\electron-builder\out\platformPackager.js:171:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:244:24
From previous event:
    at Packager.doBuild (C:\projects\digital-clock\node_modules\electron-builder\out\packager.js:317:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\packager.ts:175:52
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (C:\projects\digital-clock\node_modules\electron-builder\out\packager.js:236:11)
    at C:\projects\digital-clock\node_modules\electron-builder\src\builder.ts:266:40
    at next (native)
From previous event:
    at build (C:\projects\digital-clock\node_modules\electron-builder\out\builder.js:69:21)
    at Object.args [as handler] (C:\projects\digital-clock\node_modules\electron-builder\src\cli\cli.ts:46:4)
    at Object.self.runCommand (C:\projects\digital-clock\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (C:\projects\digital-clock\node_modules\yargs\yargs.js:1018:24)
    at Object.get [as argv] (C:\projects\digital-clock\node_modules\yargs\yargs.js:927:19)
    at Object.<anonymous> (C:\projects\digital-clock\node_modules\electron-builder\src\cli\cli.ts:41:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

Some notes:

- The exact same file works fine if I set `CSC_LINK` to the path of the file instead of to the base64 encoded version of the file
- p12 should equal pfx, but I still imported the certificate on Windows 10 and exported back to pfx using the "Certificates" management application, but I got the exact same error
- I tried encoding the file using various base64 tools in both Windows and macOS, including `base64` as recommended in the docs

Here is my `appveyor.yml`, in case that matters:

```yaml
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - npm install

build_script:
  - npm run dist

test: off
```

Any ideas?

**Comment by jviotti** [comment]
I locally put the base64 encoded data into the variable, and then read it back, and looks like Windows is only storing 8177 characters, and cutting off the rest :S

**Comment by jviotti** [comment]
OK, sorted. When exporting the certificate, I can choose to not include all the certificates in the certification path, like the parent COMODO certificate in my case, which results in a much, much smaller certificate, that nicely fits into a batch variable.

@develar Should we add this to the docs?

**Comment by develar** [comment]
PR welcome :)
