### ISSUE TITLE
Checking for update  Error: Error: sha512 checksum mismatch

### ISSUE THREAD

**Issue by AragornZJF** [electron-userland/electron-builder#1910]
C:\Users\user\Desktop\electron_test>npm run dev

> app@1.6.13 dev C:\Users\xxx\Desktop\electron_test
> electron src/main.js

Wait for app ready
http://xx.xx.x.xxxx:xxxx/updates/latest/
Checking for update
Found version 1.6.13 (url: http://xx.xx.x.xxxx:xxxx/updates/latest/app Setup 1.
6.13.exe)
Downloading update from http://xx.xx.x.xxxx:xxxx/updates/latest/app Setup 1.6.1
3.exe
Error: Error: sha512 checksum mismatch, expected M5Hfk/qzXBLdi/Wg3z3ShQsmhRK10b1
1RHJWPOJS7QU4gqjFctw8FxXz6p+NmYcmLREcuch/iciE+AlpWf9tVg==, got mhtAMJxAnsDMHk9tL
yG5eVLEKIpos+v2tnqJ2eYfPwKuRscsHo5A4BuJtsFMTIaZTIsp/Z93/P/ZSi2YcEmhBw==
    at DigestTransform._flush (C:\Users\tongfa\Desktop\electron_test\src\node_mo
dules\electron-builder-http\src\httpExecutor.ts:190:46)
    at DigestTransform.<anonymous> (_stream_transform.js:118:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at DigestTransform.emit (events.js:185:7)
    at prefinish (_stream_writable.js:503:12)
    at finishMaybe (_stream_writable.js:511:7)
    at endWritable (_stream_writable.js:523:3)
    at DigestTransform.Writable.end (_stream_writable.js:488:5)
    at ProgressCallbackTransform.onend (_stream_readable.js:511:10)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at ProgressCallbackTransform.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at CancellationToken.createPromise (C:\Users\tongfa\Desktop\electron_test\sr
c\node_modules\electron-builder-http\src\CancellationToken.ts:51:5)
    at C:\Users\tongfa\Desktop\electron_test\src\node_modules\electron-updater\s
rc\electronHttpExecutor.ts:24:44
    at Generator.next (<anonymous>)
From previous event:
    at ElectronHttpExecutor.download (C:\Users\tongfa\Desktop\electron_test\src\
node_modules\electron-updater\out\electronHttpExecutor.js:80:11)
    at C:\Users\tongfa\Desktop\electron_test\src\node_modules\electron-updater\s
rc\NsisUpdater.ts:57:31
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:112:15)
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Users\tongfa\Desktop\electron_test\src\n
ode_modules\electron-updater\out\NsisUpdater.js:134:11)
    at C:\Users\tongfa\Desktop\electron_test\src\node_modules\electron-updater\s
rc\AppUpdater.ts:274:25
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.downloadUpdate (C:\Users\tongfa\Desktop\electron_test\src\nod
e_modules\electron-updater\out\AppUpdater.js:325:11)
    at C:\Users\tongfa\Desktop\electron_test\src\node_modules\electron-updater\s
rc\AppUpdater.ts:248:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\tongfa\Desktop\electron_test\src\
node_modules\electron-updater\out\AppUpdater.js:295:11)
    at C:\Users\tongfa\Desktop\electron_test\src\node_modules\electron-updater\s
rc\AppUpdater.ts:201:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\tongfa\Desktop\electron_test\src\n
ode_modules\electron-updater\out\AppUpdater.js:254:11)
    at NsisUpdater.checkForUpdates (C:\Users\tongfa\Desktop\electron_test\src\no
de_modules\electron-updater\src\AppUpdater.ts:164:35)
    at updateHandle (C:\Users\tongfa\Desktop\electron_test\src\main.js:273:17)
    at App.createWindow (C:\Users\tongfa\Desktop\electron_test\src\main.js:67:5)

    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
Unhandled rejection Error: sha512 checksum mismatch, expected M5Hfk/qzXBLdi/Wg3z
3ShQsmhRK10b11RHJWPOJS7QU4gqjFctw8FxXz6p+NmYcmLREcuch/iciE+AlpWf9tVg==, got mhtA
MJxAnsDMHk9tLyG5eVLEKIpos+v2tnqJ2eYfPwKuRscsHo5A4BuJtsFMTIaZTIsp/Z93/P/ZSi2YcEmh
Bw==
    at DigestTransform._flush (C:\Users\tongfa\Desktop\electron_test\src\node_mo
dules\electron-builder-http\src\httpExecutor.ts:190:46)
    at DigestTransform.<anonymous> (_stream_transform.js:118:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at DigestTransform.emit (events.js:185:7)
    at prefinish (_stream_writable.js:503:12)
    at finishMaybe (_stream_writable.js:511:7)
    at endWritable (_stream_writable.js:523:3)
    at DigestTransform.Writable.end (_stream_writable.js:488:5)
    at ProgressCallbackTransform.onend (_stream_readable.js:511:10)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at ProgressCallbackTransform.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at CancellationToken.createPromise (C:\Users\tongfa\Desktop\electron_test\sr
c\node_modules\electron-builder-http\src\CancellationToken.ts:51:5)
    at C:\Users\tongfa\Desktop\electron_test\src\node_modules\electron-updater\s
rc\electronHttpExecutor.ts:24:44
    at Generator.next (<anonymous>)
From previous event:
    at ElectronHttpExecutor.download (C:\Users\tongfa\Desktop\electron_test\src\
node_modules\electron-updater\out\electronHttpExecutor.js:80:11)
    at C:\Users\tongfa\Desktop\electron_test\src\node_modules\electron-updater\s
rc\NsisUpdater.ts:57:31
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:112:15)
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Users\tongfa\Desktop\electron_test\src\n
ode_modules\electron-updater\out\NsisUpdater.js:134:11)
    at C:\Users\tongfa\Desktop\electron_test\src\node_modules\electron-updater\s
rc\AppUpdater.ts:274:25
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.downloadUpdate (C:\Users\tongfa\Desktop\electron_test\src\nod
e_modules\electron-updater\out\AppUpdater.js:325:11)
    at C:\Users\tongfa\Desktop\electron_test\src\node_modules\electron-updater\s
rc\AppUpdater.ts:248:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\tongfa\Desktop\electron_test\src\
node_modules\electron-updater\out\AppUpdater.js:295:11)
    at C:\Users\tongfa\Desktop\electron_test\src\node_modules\electron-updater\s
rc\AppUpdater.ts:201:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\tongfa\Desktop\electron_test\src\n
ode_modules\electron-updater\out\AppUpdater.js:254:11)
    at NsisUpdater.checkForUpdates (C:\Users\tongfa\Desktop\electron_test\src\no
de_modules\electron-updater\src\AppUpdater.ts:164:35)
    at updateHandle (C:\Users\tongfa\Desktop\electron_test\src\main.js:273:17)
    at App.createWindow (C:\Users\tongfa\Desktop\electron_test\src\main.js:67:5)

    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

**Comment by AragornZJF** [comment]
latest, I find generate latest.yml have githubArtifactName and sha512   why??
![image](https://user-images.githubusercontent.com/23381574/29082120-2f94d67c-7c97-11e7-9c1d-9408f1671aba.png)

**Comment by AragornZJF** [comment]
#or In other words, How to remove space the generator installation app.exe.  
such as ` electron-build-setup-0.4.2.exe `

**Comment by yhostc** [comment]
The `artifactName`option can be do it

**Comment by joenix** [comment]
error Error: sha512 checksum mismatch, expected U5pEyhsIZGHrEPA2+g+z662w5JdaUWK7jNFEvu0+mz0tY+BXaNiBtCCBxogQaQ1ALUud2+RbB+cXy9OBYPG9+w==, got +zFxCWvPfoqy4C231x9olXpflrt4aKsAOFUg3bBVl4jL8urx7dgvwtIrztyUFSgHLFyJwads7eNuj4gxUveAlw==
    at e.newError (C:\Program Files\channel-cooperation\resources\app.asar\background.js:2:5792)
    at E.validate (C:\Program Files\channel-cooperation\resources\app.asar\background.js:2:132051)
    at E._flush (C:\Program Files\channel-cooperation\resources\app.asar\background.js:2:131852)
    at E.prefinish (_stream_transform.js:140:10)
    at E.emit (events.js:210:5)
    at prefinish (_stream_writable.js:645:14)
    at finishMaybe (_stream_writable.js:653:5)
    at endWritable (_stream_writable.js:673:3)
    at E.Writable.end (_stream_writable.js:604:5)
    at i.onend (_stream_readable.js:691:10) Error: sha512 checksum mismatch, expected U5pEyhsIZGHrEPA2+g+z662w5JdaUWK7jNFEvu0+mz0tY+BXaNiBtCCBxogQaQ1ALUud2+RbB+cXy9OBYPG9+w==, got +zFxCWvPfoqy4C231x9olXpflrt4aKsAOFUg3bBVl4jL8urx7dgvwtIrztyUFSgHLFyJwads7eNuj4gxUveAlw==
    at e.newError (C:\Program Files\channel-cooperation\resources\app.asar\background.js:2:5792)
    at E.validate (C:\Program Files\channel-cooperation\resources\app.asar\background.js:2:132051)
    at E._flush (C:\Program Files\channel-cooperation\resources\app.asar\background.js:2:131852)
    at E.prefinish (_stream_transform.js:140:10)
    at E.emit (events.js:210:5)
    at prefinish (_stream_writable.js:645:14)
    at finishMaybe (_stream_writable.js:653:5)
    at endWritable (_stream_writable.js:673:3)
    at E.Writable.end (_stream_writable.js:604:5)
    at i.onend (_stream_readable.js:691:10)

i change the `artifactName`, but still cant run ...
