### ISSUE TITLE
error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by NTMan** [electron-userland/electron-builder#1998]
* **OS**: Linux Fedora 27
```
# dnf provides libbz2.so.1.0
Last metadata expiration check: 2:00:58 ago on Sat 26 Aug 2017 10:32:28 PM +05.
Error: No Matches found

# dnf install bzip2 bzip2-devel
Last metadata expiration check: 2:03:28 ago on Sat 26 Aug 2017 10:32:28 PM +05.
Package bzip2-1.0.6-24.fc27.x86_64 is already installed, skipping.
Package bzip2-devel-1.0.6-24.fc27.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

# ls /usr/lib64/libbz2.so* -la
lrwxrwxrwx. 1 root root    11 Aug  2 23:34 /usr/lib64/libbz2.so -> libbz2.so.1
lrwxrwxrwx. 1 root root    15 Aug  2 23:34 /usr/lib64/libbz2.so.1 -> libbz2.so.1.0.6
-rwxr-xr-x. 1 root root 71896 Aug  2 23:34 /usr/lib64/libbz2.so.1.0.6
```

* **Version**: 19.23.1

* **Target**: linux

```
$ ./node_modules/.bin/build --linux
electron-builder 19.23.1
No native production dependencies
Packaging for linux x64 using electron 1.7.5 to dist/linux-unpacked
Building AppImage for arch x64
Error: Exit code: 127. Command failed: /home/mikhail/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /home/mikhail/packaging-work/jumpfm/jumpfm/dist/jumpfm-1.0.0-x86_64.AppImage -padding 0 -map /home/mikhail/packaging-work/jumpfm/jumpfm/dist/linux-unpacked /usr/bin -map /home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-Q9AzIe/0-jumpfm.desktop /jumpfm.desktop -map /home/mikhail/packaging-work/jumpfm/jumpfm/build/icons/128x128.png /usr/share/icons/default/128x128/apps/jumpfm.png -map /home/mikhail/packaging-work/jumpfm/jumpfm/build/icons/16x16.png /usr/share/icons/default/16x16/apps/jumpfm.png -map /home/mikhail/packaging-work/jumpfm/jumpfm/build/icons/24x24.png /usr/share/icons/default/24x24/apps/jumpfm.png -map /home/mikhail/packaging-work/jumpfm/jumpfm/build/icons/256x256.png /usr/share/icons/default/256x256/apps/jumpfm.png -map /home/mikhail/packaging-work/jumpfm/jumpfm/build/icons/32x32.png /usr/share/icons/default/32x32/apps/jumpfm.png -map /home/mikhail/packaging-work/jumpfm/jumpfm/build/icons/48x48.png /usr/share/icons/default/48x48/apps/jumpfm.png -map /home/mikhail/packaging-work/jumpfm/jumpfm/build/icons/64x64.png /usr/share/icons/default/64x64/apps/jumpfm.png -map /home/mikhail/packaging-work/jumpfm/jumpfm/build/icons/96x96.png /usr/share/icons/default/96x96/apps/jumpfm.png -map /home/mikhail/packaging-work/jumpfm/jumpfm/build/icons/256x256.png /.DirIcon -map /home/mikhail/.cache/electron-builder/AppImage-packages/10.03.17 /usr/lib -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /
/home/mikhail/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

/home/mikhail/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

    at /home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder-util/src/util.ts:78:16
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
From previous event:
    at exec (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder-util/src/util.ts:56:3)
    at /home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/src/targets/appImage.ts:79:5
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/out/targets/appImage.js:139:11)
    at taskManager.addTask.default.map.it (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/src/platformPackager.ts:106:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/src/platformPackager.ts:106:41)
    at /home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/src/platformPackager.ts:102:10
From previous event:
    at LinuxPackager.pack (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/out/platformPackager.js:177:11)
    at /home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/src/packager.ts:253:24
From previous event:
    at Packager.doBuild (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/out/packager.js:340:11)
    at /home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/src/packager.ts:184:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/out/packager.js:259:11)
    at /home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/src/builder.ts:266:40
    at Generator.next (<anonymous>)
    at build (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/out/cli/cli.js:155:79)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.args [as handler] (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/out/cli/cli.js:155:68)
    at Object.self.runCommand (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/home/mikhail/packaging-work/jumpfm/jumpfm/node_modules/electron-builder/out/cli/cli.js:151:465)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

I don't know for which OS you doing packaging system, but for Fedora workaround:
```
# ln -s /usr/lib64/libbz2.so.1.0.6 /usr/lib64/libbz2.so.1.0
# dnf install compat-readline6
```
After this AppImage file created successfully,
1) I think electron-builder should use /usr/lib64/libbz2.so.1 instead of libbz2.so.1.0
2) electron-builder also should check dependencies and write that before use user must installed compat-readline6 package.

Or another way this library must compiled statically.

**Comment by develar** [comment]
Thanks, soon we will use another tool to produce AppImage and I will check Fedora compatibility. In any case you can use our docker image to avoid any such errors.
