### ISSUE TITLE
*** powershell doesn't return UTF-8 encoded result

### ISSUE THREAD

**Issue by yhostc** [electron-userland/electron-builder#2003]
half a month ago, I used the same code to package v1.3 and v2.0. It was normal to verify that the upgrade process between the two versions was normal.
But now that I'm using the same code to repackage the v2.0.3, I can't upgrade and report the following exceptions.

I've confirmed using the same USB TOKEN,  electron-builder (v19.20.0) and electron-updater(v2.8.7)  are the same version two times before and after.

Details are as follows:
```
[2017-08-28 14:14:59:0336] [info] Sign verification failed, installer signed with incorrect certificate: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=Symantec Class 3 Extended Validation Code Signing CA - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1594079999000)/",
    "NotBefore": "/Date(1502323200000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "125DDA1BCE57EEC7EFE95F3294F71A44",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "1037BE4D2BAD73A593F8A5C2031BF3BCB2382C90",
    "Version": 3,
    "Issuer": "CN=Symantec Class 3 Extended Validation Code Signing CA - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US",
    "Subject": "CN=�������׿Ƽ����޹�˾, O=�������׿Ƽ����޹�˾, L=Beijing, S=Beijing, C=CN, SERIALNUMBER=911101080805016993, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.1=Beijing, OID.1.3.6.1.4.1.311.60.2.1.2=Beijing, OID.1.3.6.1.4.1.311.60.2.1.3=CN"
  },
  "TimeStamperCertificate": null,
  "Status": 0,
  "StatusMessage": "ǩ����ͨ����֤��"
}
[2017-08-28 14:14:59:0359] [error] Error: Error: New version 2.0.3 is not signed by the application owner: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=Symantec Class 3 Extended Validation Code Signing CA - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1594079999000)/",
    "NotBefore": "/Date(1502323200000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "125DDA1BCE57EEC7EFE95F3294F71A44",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "1037BE4D2BAD73A593F8A5C2031BF3BCB2382C90",
    "Version": 3,
    "Issuer": "CN=Symantec Class 3 Extended Validation Code Signing CA - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US",
    "Subject": "CN=�������׿Ƽ����޹�˾, O=�������׿Ƽ����޹�˾, L=Beijing, S=Beijing, C=CN, SERIALNUMBER=911101080805016993, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.1=Beijing, OID.1.3.6.1.4.1.311.60.2.1.2=Beijing, OID.1.3.6.1.4.1.311.60.2.1.3=CN"
  },
  "TimeStamperCertificate": null,
  "Status": 0,
  "StatusMessage": "ǩ����ͨ����֤��"
}
    at C:\Program Files (x86)\VIPKID\resources\app\node_modules\electron-updater\src\NsisUpdater.ts:73:13
    at Generator.next (<anonymous>)
    at FSReqWrap.CB [as oncomplete] (C:\Program Files (x86)\VIPKID\resources\app\node_modules\fs-extra-p\node_modules\fs-extra\lib\remove\rimraf.js:57:5)
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Program Files (x86)\VIPKID\resources\app\node_modules\electron-updater\out\NsisUpdater.js:134:11)
    at C:\Program Files (x86)\VIPKID\resources\app\node_modules\electron-updater\src\AppUpdater.ts:275:25
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.downloadUpdate (C:\Program Files (x86)\VIPKID\resources\app\node_modules\electron-updater\out\AppUpdater.js:331:11)
    at C:\Program Files (x86)\VIPKID\resources\app\dist\main.js:871:282
    at Promise (C:\Program Files (x86)\VIPKID\resources\app\node_modules\handoff\handoff.js:31:37)
    at next (C:\Program Files (x86)\VIPKID\resources\app\node_modules\handoff\handoff.js:29:14)
    at notifyObjects (C:\Program Files (x86)\VIPKID\resources\app\node_modules\handoff\handoff.js:60:12)
    at publishNotification (C:\Program Files (x86)\VIPKID\resources\app\node_modules\handoff\handoff.js:78:10)
    at Object.publish (C:\Program Files (x86)\VIPKID\resources\app\node_modules\handoff\handoff.js:96:10)
    at EventEmitter.TARGET.on.args (C:\Program Files (x86)\VIPKID\resources\app\node_modules\electron-ipc\index.js:38:22)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (C:\Program Files (x86)\VIPKID\resources\electron.asar\browser\api\web-contents.js:247:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by yhostc** [comment]
OK, I should have found the problem, and the publisherName returned by powershell.exe is inconsistent with the encoding of the publisherName character set in the file, causing the problem

**Comment by develar** [comment]
What is your system locale (language)? Do you mean that powershell doesn't return UTF-8 encoded result?

**Comment by yhostc** [comment]
my language is chinese,  and the powershell return gbk encoded result. I looked up some information and seemed to set up utf8 encoding only through set-content and out-file ?

**Comment by yhostc** [comment]
how to detect the charset from powershell? 
```
[info] Sign check: �������׿Ƽ����޹�˾ [ '北京大米科技有限公司' ]
```

**Comment by develar** [comment]
For now please set `win.verifyUpdateCodeSignature` to `false` as workaround (https://github.com/electron-userland/electron-builder/wiki/Options#user-content-WinBuildOptions-verifyUpdateCodeSignature). I will fix this issue this week.

**Comment by yhostc** [comment]
yeah, thanks!
