### ISSUE TITLE
Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by daveywc** [electron-userland/electron-builder#2007]
"electron-builder": "^19.22.1",

"electron-updater": "^2.8.7",

Windows

See truncated output from update log below.

The update is being downloaded, then the auto install runs and opens the new version.  I can verify that the new version is opened (in this case version 0.53.0).  Then when I close and re-open the application it has reverted to the old version (0.51.0).

Can you advise what would cause the error in the log and the failure to properly update?

```
[2017-08-29 09:23:50:0398] [info] info Download speed: 1018150 - Downloaded 100% (356200680/356200680)
[2017-08-29 09:23:52:0059] [info] New version 0.53.0 has been downloaded to C:\Users\DAVIDC~1\AppData\Local\Temp\up-054fOl\Docs On Tap V2 Setup 0.53.0.exe
[2017-08-29 09:24:08:0046] [info] Auto install update on quit
[2017-08-29 09:24:38:0856] [info] App starting...
[2017-08-29 09:24:39:0081] [info] current version: 0.53.0
[2017-08-29 09:24:39:0084] [info] Checking for update
[2017-08-29 09:24:39:0311] [error] Error: Error: Cannot find module 'fs-extra'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\fs-extra-p\index.js:3:17)
    at Object.<anonymous> (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\fs-extra-p\index.js:58:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at _load_fsExtraP (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:47:24)
    at C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:305:27
From previous event:
    at NsisUpdater.loadUpdateConfig (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:344:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:82:53)
    at Lazy.get value [as value] (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\lazy-val\src\main.ts:18:23)
    at C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:212:33
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:301:11)
    at C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:202:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:260:11)
    at NsisUpdater.checkForUpdates (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:165:35)
    at configureAutoUpdates (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\electron.js:130:17)
    at initialiseApp (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\electron.js:19:5)
    at App.app.on (C:\Users\DavidCompton\AppData\Local\Programs\au.com.harboursoftware.docsontap.v2\resources\app.asar\electron.js:24:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
[2017-08-29 09:25:11:0737] [info] App starting...
[2017-08-29 09:25:11:0846] [info] current version: 0.51.0
[2017-08-29 09:25:11:0846] [info] Checking for update
[2017-08-29 09:25:13:0520] [info] Found version 0.53.0 (url: https://filesv2.docsontap.com.au/updates/Docs On Tap V2 Setup 0.53.0.exe)
```

**Comment by daveywc** [comment]
I worked out what the problem was.  Please ignore this issue.
