### ISSUE TITLE
Failed to download winCodeSign

### ISSUE THREAD

**Issue by pboymt** [electron-userland/electron-builder#2009]
* **Version**: 19.26.3

* **Target**: win32

```
electron-builder 19.26.3
No native production dependencies
Packaging for win32 x64 using electron 1.7.6 to package\win-unpacked
Downloading winCodeSign-1.9.0, please wait
Warning: Cannot download winCodeSign, attempt #1: Error: Request timed out
Error: connect ETIMEDOUT 192.30.255.112:443
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
From previous event:
    at CancellationToken.createPromise (E:\electron\myapp\node_modules\electron-builder-http\src\CancellationToken.ts:51:5)
    at E:\electron\myapp\node_modules\builder-util\src\nodeHttpExecutor.ts:27:44
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NodeHttpExecutor.download (E:\electron\myapp\node_modules\builder-util\out\nodeHttpExecutor.js:159:11)
    at Timeout._onTimeout (E:\electron\myapp\node_modules\builder-util\src\binDownload.ts:85:39)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! yyets@0.0.0 builder: `electron-builder`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the myapp@0.0.0 builder script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by develar** [comment]
You can download manually — https://github.com/electron-userland/electron-builder-binaries/releases/tag/winCodeSign-1.9.0

https://github.com/electron-userland/electron-builder/issues/1859#issuecomment-320922905

**Comment by aaronsedna** [comment]
My standard code-signing certificate is issued by Comodo CA and is valid till 2021 and the password I used is correct.

I tried setting the CSC_LINK environment variable as instructed in the video. My certificate have a password, so I used the CSC_KEY_PASSWORD to set the password as well.

But when I run "node run dist", it doesn't code sign the exe.

Can you please please help?
Has the  CSC_LINK syntax changed?

Here is the link to my package.json file: https://www.dropbox.com/s/hz2wq8jrnm5rvs9/package.json?dl=0

Thanks!
