### ISSUE TITLE
Codesigning fails when adding Puppeteer as a dependency

### ISSUE THREAD

**Issue by SabatinoMasala** [electron-userland/electron-builder#2010]
* **Version**: 19.27.0
* **Target**: MacOS
* **Node version**: 8.4.0
* **Yarn version**: 0.27.5

When adding [Puppeteer](https://github.com/GoogleChrome/puppeteer) as a dependency, codesigning fails since the module contains a local version of Chromium.

# Stack trace
```
Error: Command failed: codesign --sign [...] --force [...]/node_modules/puppeteer/.local-chromium/mac-496140/chrome-mac/Chromium.app/Contents/Versions/62.0.3193.0/Chromium Framework.framework/Versions/A/Chromium Framework
[...]/node_modules/puppeteer/.local-chromium/mac-496140/chrome-mac/Chromium.app/Contents/Versions/62.0.3193.0/Chromium Framework.framework/Versions/A/Chromium Framework: code object is not signed at all
In subcomponent: [...]/node_modules/puppeteer/.local-chromium/mac-496140/chrome-mac/Chromium.app/Contents/Versions/62.0.3193.0/Chromium Framework.framework/Versions/A/Helpers/crashpad_handler

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at MacPackager.sign (/MyProjectDir/node_modules/electron-builder/out/macPackager.js:253:11)
    at /MyProjectDir/node_modules/electron-builder/src/macPackager.ts:88:26
From previous event:
    at /MyProjectDir/node_modules/electron-builder/src/macPackager.ts:88:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/MyProjectDir/node_modules/electron-builder/out/macPackager.js:183:11)
    at /MyProjectDir/node_modules/electron-builder/src/packager.ts:259:24
From previous event:
    at Packager.doBuild (/MyProjectDir/node_modules/electron-builder/out/packager.js:338:11)
    at /MyProjectDir/node_modules/electron-builder/src/packager.ts:185:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/MyProjectDir/node_modules/electron-builder/out/packager.js:257:11)
    at /MyProjectDir/node_modules/electron-builder/src/builder.ts:266:40
    at Generator.next (<anonymous>)
    at build (/MyProjectDir/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/MyProjectDir/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (/MyProjectDir/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/MyProjectDir/node_modules/electron-builder/out/cli/cli.js:155:79)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.args [as handler] (/MyProjectDir/node_modules/electron-builder/out/cli/cli.js:155:68)
    at Object.self.runCommand (/MyProjectDir/node_modules/electron-builder/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/MyProjectDir/node_modules/electron-builder/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/MyProjectDir/node_modules/electron-builder/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/MyProjectDir/node_modules/electron-builder/out/cli/cli.js:151:465)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

# Things that I tried

When I remove Puppeteer as a dependency, signing works as it should, so the problem is definitely related to that package. I'm using version **0.10.1**

# Potential solutions

This can be fixed by adding the `--deep` flag to [args on line 138](https://github.com/electron-userland/electron-osx-sign/blob/master/sign.js#L138) in `node_modules/electron-osx-sign/sign.js` 

Or prevent electron-builder from signing automatically:
```
export CSC_IDENTITY_AUTO_DISCOVERY=false && node .electron-vue/build.js && electron-builder
```
And run the codesign command manually:
```
codesign --sign [...] --force --deep ./build/mac/my-app.app
```

It is my understanding though that the `--deep` flag [should be avoided](https://github.com/electron-userland/electron-osx-sign/issues/125#issuecomment-273386814), but in this case this proved to be the solution.

**Comment by Raidus** [comment]
Hi!

Including puppeteer doesn't work in my case either. I'm getting following error:

```
Error: EISDIR: illegal operation on a directory, read
    at w (/***/electron-quick-start/node_modules/electron-builder/src/asar/asarUtil.ts:191:11)
    at writeStream.write (***/electron-quick-start/node_modules/electron-builder/src/asar/asarUtil.ts:193:43)
    at afterWrite (_stream_writable.js:438:3)
    at onwrite (_stream_writable.js:429:7)
    at fs.js:2133:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:691:5)
```

My settings:

Node: 8.2.1
NPM: 5.2.0
electron: 1.7.9
electron-builder: 19.43.4

Did you found a solution?

**Comment by develar** [comment]
@Raidus It is another error. Is it possible to provide sample project to reproduce?

**Comment by Raidus** [comment]
@develar sure!

I've provided a minimal sample project to reproduce the error:
https://github.com/Raidus/electron-puppeteer-quick-start

**Comment by develar** [comment]
Strange to include another copy of Chrome into Electron. Fixed — now we just ignore `puppeteer/.local-chromium` — it is your responsibility to sign this 200 MB of junk if need :)

**Comment by natew** [comment]
I'm running into this still when signing a build with puppeteer. I use electron-osx-sign directly and get:

```
Sign failed:
Command failed: codesign --sign 118083DAF4871AA63DDBCF932516ED66C1AA0AC9 --force app/Orbit-darwin-x64/Orbit.app/Contents/Resources/app/node_modules/@mcro/api/node_modules/@mcro/crawler/node_modules/puppeteer/.local-chromium/mac-515411/chrome-mac/Chromium.app/Contents/Versions/64.0.3264.0/Chromium Framework.framework/Chromium Framework
app/Orbit-darwin-x64/Orbit.app/Contents/Resources/app/node_modules/@mcro/api/node_modules/@mcro/crawler/node_modules/puppeteer/.local-chromium/mac-515411/chrome-mac/Chromium.app/Contents/Versions/64.0.3264.0/Chromium Framework.framework/Chromium Framework: code object is not signed at all
In subcomponent: /Users/nw/projects/motion/orbit/apps/electron-build/app/Orbit-darwin-x64/Orbit.app/Contents/Resources/app/node_modules/@mcro/api/node_modules/@mcro/crawler/node_modules/puppeteer/.local-chromium/mac-515411/chrome-mac/Chromium.app/Contents/Versions/64.0.3264.0/Chromium Framework.framework/settings.dat
```

**Comment by natew** [comment]
Ah, I see the patch is to ignore, thanks.

**Comment by KynanBertulli** [comment]
> puppeteer/.local-chromium

Can you explain what you did to ignore/solve this code signing issue?
