### ISSUE TITLE
Error building a development mas

### ISSUE THREAD

**Issue by ivandroid** [electron-userland/electron-builder#2026]
Getting this error while trying to build a development mas (type=development). Any idea?

```
TypeError: entitlements.com.apple.security.application-groups.push is not a function
    at /myapp/node_modules/electron-builder/node_modules/electron-osx-sign/util-entitlements.js:88:67
    at /myapp/node_modules/update-notifier/node_modules/write-file-atomic/node_modules/graceful-fs/graceful-fs.js:43:10
    at /myapp/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by develar** [comment]
Please file issue to electron-osx-sign
