### ISSUE TITLE
Error when building installer in Windows 10 x64

### ISSUE THREAD

**Issue by AxelZaraki** [electron-userland/electron-builder#2037]
* **Version**: 19.27.3

* **Target**: win32 x64

Without updating any module of the project (iirc), electron-builder suddenly stopped working from one day to the other, I'm not sure what's causing the issue. Any help would be appreciated :)

The error I'm getting:

```
C:\Users\Axel\Desktop\angular-project>npm run electron:dist

> angular-project@0.0.1 electron:dist C:\Users\Axel\Desktop\angular-project
> electron-builder

electron-builder 19.27.3
Installing app dependencies for arch x64 to C:\Users\Axel\Desktop\angular-project\dist
Packaging for win32 x64 using electron 1.7.5 to dist\desktop\win-unpacked
⚠️  Application icon is not set, default Electron icon will be used
Building NSIS installer
  Packaging NSIS installer for arch x64
Error: spawn EPERM
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at exports.execFile (child_process.js:143:15)
    at default (C:\Users\Axel\Desktop\angular-project\node_modules\builder-util\src\util.ts:59:5)
    at exec (C:\Users\Axel\Desktop\angular-project\node_modules\builder-util\src\util.ts:58:3)
    at execWine (C:\Users\Axel\Desktop\angular-project\node_modules\builder-util\src\wine.ts:36:12)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\targets\nsis\nsis.ts:260:11
From previous event:
    at NsisTarget.computeScriptAndSignUninstaller (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\targets\nsis\nsis.js:346:11)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\targets\nsis\nsis.ts:215:114
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at NsisTarget.buildInstaller (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\targets\nsis\nsis.js:311:11)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\targets\nsis\nsis.ts:102:18
    at next (native)
From previous event:
    at NsisTarget.finishBuild (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\targets\nsis\nsis.js:202:11)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\packager.ts:268:36
From previous event:
    at Packager.doBuild (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\packager.js:338:11)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\packager.ts:186:52
    at next (native)
From previous event:
    at Packager.build (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\packager.js:257:11)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\builder.ts:266:40
    at next (native)
From previous event:
    at build (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\builder.js:69:21)
    at loadEnv.then (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\cli\cli.ts:49:4)    at Object.self.runCommand (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\node_modules\yargs\yargs.js:1018:24)
    at Object.get [as argv] (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\node_modules\yargs\yargs.js:927:19)
    at Object.<anonymous> (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! angular-project@0.0.1 electron:dist: `electron-builder`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the angular-project@0.4.1 electron:dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Axel\AppData\Roaming\npm-cache\_logs\2017-09-05T17_27_00_178Z-debug.log
```

I'm building on top of an angular project, in case that helps.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.

**Comment by AxelZaraki** [comment]
```
C:\Users\Axel\Desktop\angular-project>npm run electron:dist

> angular-project@0.0.1 electron:dist C:\Users\Axel\Desktop\angular-project
> cross-env DEBUG=electron-builder electron-builder

electron-builder 19.27.3
  electron-builder Effective config:
  electron-builder appId: org.axelzaraki.angularproject
  electron-builder mac:
  electron-builder   category: public.app-category.social-networking
  electron-builder asar: true
  electron-builder directories:
  electron-builder   buildResources: src/assets
  electron-builder   output: dist/desktop
  electron-builder   app: dist
  electron-builder  +0ms
  electron-builder Two package.json structure is used (dev: C:\Users\Axel\Desktop\angular-project\package.json, app: C:\Users\Axel\Desktop\angular-project\dist\package.json) +452ms
No native production dependencies
Packaging for win32 x64 using electron 1.7.5 to dist\desktop\win-unpacked
  electron-builder Spawning C:\Users\Axel\Desktop\angular-project\node_modules\7zip-bin-win\x64\7za.exe x -bd C:\Users\Axel\AppData\Local\electron\Cache\electron-v1.7.5-win32-x64.zip -aoa -oC:\Users\Axel\Desktop\angular-project\dist\desktop\win-unpacked +764ms

7-Zip (a) 17.00 beta (x64) : Copyright (c) 1999-2017 Igor Pavlov : 2017-04-29

Scanning the drive for archives:
1 file, 53895904 bytes (52 MiB)

Extracting archive: C:\Users\Axel\AppData\Local\electron\Cache\electron-v1.7.5-win32-x64.zip
--
Path = C:\Users\Axel\AppData\Local\electron\Cache\electron-v1.7.5-win32-x64.zip
Type = zip
Physical Size = 53895904

Everything is Ok

Files: 117
Size:       138463250
Compressed: 53895904
  electron-builder 7za.exe (4188) exited with exit code 0 +1s
⚠️  Application icon is not set, default Electron icon will be used
  electron-builder Executing C:\Users\Axel\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.9.0\rcedit.exe C:\Users\Axel\Desktop\angular-project\dist\desktop\win-unpacked\angular-project-electron.exe --set-version-string FileDescription angular-project-electron --set-version-string ProductName angular-project-electron --set-version-string LegalCopyright Copyright © 2017 Axel Zaraki --set-file-version 0.0.1 --set-product-version 0.0.1.0 --set-version-string InternalName angular-project-electron --set-version-string OriginalFilename  --set-version-string CompanyName Axel Zaraki +1s
wine&sign: 0s 733.611611ms
Building NSIS installer
  Packaging NSIS installer for arch x64
  electron-builder Spawning C:\Users\Axel\Desktop\angular-project\node_modules\7zip-bin-win\x64\7za.exe a -bd -mx=9 -mtc=off -mtm=off -mta=off C:\Users\Axel\Desktop\angular-project\dist\desktop\angular-project-electron-0.0.1-x64.nsis.7z . +787ms
  electron-builder cwd: C:\Users\Axel\Desktop\angular-project\dist\desktop\win-unpacked +2ms
  electron-builder 7za.exe (5740) exited with exit code 0 +2m
nsis package, x64: 92s 980.568182ms
  electron-builder Spawning C:\Users\Axel\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\Bin\makensis.exe -WX -DAPP_ID=org.axelzaraki.angularproject -DAPP_GUID=f7668344-8962-53ea-b705-6b8903c54d5b -DPRODUCT_NAME=angular-project-electron -DPRODUCT_FILENAME=angular-project-electron -DAPP_FILENAME=angular-project-electron -DAPP_DESCRIPTION=Electron Project for Angular Project -DVERSION=0.0.1 -DPROJECT_DIR=C:\Users\Axel\Desktop\angular-project -DBUILD_RESOURCES_DIR=C:\Users\Axel\Desktop\angular-project\src\assets -DCOMPANY_NAME=Axel Zaraki -DAPP_64=C:\Users\Axel\Desktop\angular-project\dist\desktop\angular-project-electron-0.0.1-x64.nsis.7z -DAPP_64_NAME=angular-project-electron-0.0.1-x64.nsis.7z -DCOMPRESSION_METHOD=7z -DONE_CLICK -DRUN_AFTER_FINISH -DSHORTCUT_NAME=angular-project-electron -DUNINSTALL_DISPLAY_NAME=angular-project-electron 0.0.1 -DCOMPRESS=auto -DBUILD_UNINSTALLER -DUNINSTALLER_OUT_FILE=C:\Users\Axel\AppData\Local\Temp\temp-files-aAqgD7\1-uninstaller.exe -XOutFile "C:\Users\Axel\Desktop\angular-project\dist\desktop\angular-project-electron Setup 0.0.1.exe" -XVIProductVersion 0.0.1.0 -XVIAddVersionKey /LANG=1033 ProductName "angular-project-electron" -XVIAddVersionKey /LANG=1033 ProductVersion "0.0.1" -XVIAddVersionKey /LANG=1033 LegalCopyright "Copyright © 2017 Axel Zaraki" -XVIAddVersionKey /LANG=1033 FileDescription "Electron Project for Angular Project" -XVIAddVersionKey /LANG=1033 FileVersion "0.0.1" -XVIAddVersionKey /LANG=1033 CompanyName "Axel Zaraki" -XUnicode true -XSetCompressor lzma - +86ms
  electron-builder cwd: C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\templates\nsis +4ms
  electron-builder makensis.exe (5960) exited with exit code 0 +2s
  electron-builder Executing C:\Users\Axel\Desktop\angular-project\dist\desktop\angular-project-electron Setup 0.0.1.exe  +4ms
  electron-builder Async task error: Error: spawn EPERM
  electron-builder     at exports._errnoException (util.js:1018:11)
  electron-builder     at ChildProcess.spawn (internal/child_process.js:319:11)
  electron-builder     at exports.spawn (child_process.js:378:9)
  electron-builder     at exports.execFile (child_process.js:143:15)
  electron-builder     at default (C:\Users\Axel\Desktop\angular-project\node_modules\builder-util\src\util.ts:59:5)
  electron-builder     at exec (C:\Users\Axel\Desktop\angular-project\node_modules\builder-util\src\util.ts:58:3)
  electron-builder     at execWine (C:\Users\Axel\Desktop\angular-project\node_modules\builder-util\src\wine.ts:36:12)
  electron-builder     at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\targets\nsis\nsis.ts:260:11
  electron-builder From previous event:
  electron-builder     at NsisTarget.computeScriptAndSignUninstaller (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\targets\nsis\nsis.js:346:11)
  electron-builder     at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\targets\nsis\nsis.ts:215:114
  electron-builder     at next (native)
  electron-builder     at runCallback (timers.js:672:20)
  electron-builder     at tryOnImmediate (timers.js:645:5)
  electron-builder     at processImmediate [as _immediateCallback] (timers.js:617:5)
  electron-builder From previous event:
  electron-builder     at NsisTarget.buildInstaller (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\targets\nsis\nsis.js:311:11)
  electron-builder     at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\targets\nsis\nsis.ts:102:18
  electron-builder     at next (native)
  electron-builder From previous event:
  electron-builder     at NsisTarget.finishBuild (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\targets\nsis\nsis.js:202:11)
  electron-builder     at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\packager.ts:268:36
  electron-builder From previous event:
  electron-builder     at Packager.doBuild (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\packager.js:338:11)
  electron-builder     at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\packager.ts:186:52
  electron-builder     at next (native)
  electron-builder From previous event:
  electron-builder     at Packager.build (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\packager.js:257:11)
  electron-builder     at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\builder.ts:266:40
  electron-builder     at next (native)
  electron-builder From previous event:
  electron-builder     at build (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\builder.js:69:21)
  electron-builder     at loadEnv.then (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\cli\cli.ts:49:4)
  electron-builder     at runCallback (timers.js:672:20)
  electron-builder     at tryOnImmediate (timers.js:645:5)
  electron-builder     at processImmediate [as _immediateCallback] (timers.js:617:5)
  electron-builder From previous event:
  electron-builder     at Object.args [as handler] (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\cli\cli.ts:49:4)
  electron-builder     at Object.self.runCommand (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\node_modules\yargs\lib\command.js:233:22)
  electron-builder     at Object.Yargs.self._parseArgs (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\node_modules\yargs\yargs.js:1018:24)
  electron-builder     at Object.get [as argv] (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\node_modules\yargs\yargs.js:927:19)
  electron-builder     at Object.<anonymous> (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\cli\cli.ts:43:15)
  electron-builder     at Module._compile (module.js:570:32)
  electron-builder     at Object.Module._extensions..js (module.js:579:10)
  electron-builder     at Module.load (module.js:487:32)
  electron-builder     at tryModuleLoad (module.js:446:12)
  electron-builder     at Function.Module._load (module.js:438:3)
  electron-builder     at Module.runMain (module.js:604:10)
  electron-builder     at run (bootstrap_node.js:389:7)
  electron-builder     at startup (bootstrap_node.js:149:9)
  electron-builder     at bootstrap_node.js:504:3 +4s
Error: spawn EPERM
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at exports.execFile (child_process.js:143:15)
    at default (C:\Users\Axel\Desktop\angular-project\node_modules\builder-util\src\util.ts:59:5)
    at exec (C:\Users\Axel\Desktop\angular-project\node_modules\builder-util\src\util.ts:58:3)
    at execWine (C:\Users\Axel\Desktop\angular-project\node_modules\builder-util\src\wine.ts:36:12)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\targets\nsis\nsis.ts:260:11
From previous event:
    at NsisTarget.computeScriptAndSignUninstaller (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\targets\nsis\nsis.js:346:11)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\targets\nsis\nsis.ts:215:114
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at NsisTarget.buildInstaller (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\targets\nsis\nsis.js:311:11)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\targets\nsis\nsis.ts:102:18
    at next (native)
From previous event:
    at NsisTarget.finishBuild (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\targets\nsis\nsis.js:202:11)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\packager.ts:268:36
From previous event:
    at Packager.doBuild (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\packager.js:338:11)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\packager.ts:186:52
    at next (native)
From previous event:
    at Packager.build (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\packager.js:257:11)
    at C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\builder.ts:266:40
    at next (native)
From previous event:
    at build (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\out\builder.js:69:21)
    at loadEnv.then (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.self.runCommand (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\node_modules\yargs\yargs.js:1018:24)
    at Object.get [as argv] (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\node_modules\yargs\yargs.js:927:19)
    at Object.<anonymous> (C:\Users\Axel\Desktop\angular-project\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! angular-project@0.0.1 electron:dist: `cross-env DEBUG=electron-builder electron-builder`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the angular-project@0.0.1 electron:dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Axel\AppData\Roaming\npm-cache\_logs\2017-09-05T18_44_14_043Z-debug.log
```

**Comment by AxelZaraki** [comment]
My guess is that it was some issue with Windows permissions when creating the uninstaller, but it got fixed since I reinstalled Windows (not entirely because of this). Thank you for the help, you can close this now :)

**Comment by anujmv** [comment]
I am facing this issue. I think this is happening after creator update.

**Comment by AxelZaraki** [comment]
@anujmv I did not have Windows Creators update when I had this issue, now I do and I'm not having any issues.

**Comment by anujmv** [comment]
I fixed it. The issue was with my avast antivirus, blocking the creation for package
