### ISSUE TITLE
Error: spawn EPERM when build windows version on MacOS

### ISSUE THREAD

**Issue by BigMoMo** [electron-userland/electron-builder#2056]
* **Version**: 19.27.7

* **Target**: win

this is the log with debug env, this is werid :< 

```
➜  xx-xx-xx-app git:(b2) ✗ node_modules/.bin/electron-builder --win
electron-builder 19.27.7
  electron-builder Effective config:
  electron-builder appId: xx.xx.xx.xx
  electron-builder publish:
  electron-builder   - provider: generic
  electron-builder     url: 'http://xx.com/dingpa/product/'
  electron-builder directories:
  electron-builder   output: build
  electron-builder files:
  electron-builder   - dist/electron/**/*
  electron-builder   - helper/**/*
  electron-builder dmg:
  electron-builder   contents:
  electron-builder     - x: 410
  electron-builder       'y': 224
  electron-builder       type: link
  electron-builder       path: /Applications
  electron-builder     - x: 130
  electron-builder       'y': 224
  electron-builder       type: file
  electron-builder mac:
  electron-builder   icon: build/icons/icon.icns
  electron-builder   target:
  electron-builder     - dmg
  electron-builder win:
  electron-builder   icon: build/icons/icon.ico
  electron-builder   target:
  electron-builder     - nsis
  electron-builder     - zip
  electron-builder nsis:
  electron-builder   oneClick: false
  electron-builder   allowToChangeInstallationDirectory: true
  electron-builder linux:
  electron-builder   icon: build/icons
  electron-builder  +0ms
No native production dependencies
Packaging for win32 x64 using electron 1.6.11 to build/win-unpacked
  electron-builder Spawning /Users/xx-user/work/code/xx-xx-xx-app/node_modules/7zip-bin-mac/7za x -bd /Users/xx-user/Library/Caches/electron/electron-v1.6.11-win32-x64.zip -aoa -o/Users/xx-user/work/code/xx-xx-xx-app/build/win-unpacked +6s

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 52284035 bytes (50 MiB)

Extracting archive: /Users/xx-user/Library/Caches/electron/electron-v1.6.11-win32-x64.zip

\--

Path = /Users/xx-user/Library/Caches/electron/electron-v1.6.11-win32-x64.zip
Type = zip
Physical Size = 52284035

Everything is Ok

Files: 74
Size:       134024085
Compressed: 52284035
  electron-builder 7za (14211) exited with exit code 0 +2s
  electron-builder node_modules/node-notifier is not packed into asar archive - contains executable code +3s
  electron-builder macOS version: 10.12.6 +1s
  electron-builder Executing /Users/xx-user/Library/Caches/electron-builder/wine/wine-2.0.1-mac-10.12/bin/wine /Users/xx-user/Library/Caches/electron-builder/winCodeSign/winCodeSign-1.9.0/rcedit.exe /Users/xx-user/work/code/xx-xx-xx-app/build/win-unpacked/xx-xx-xx-app.exe --set-version-string FileDescription xx-xx-xx-app --set-version-string ProductName xx-xx-xx-app --set-version-string LegalCopyright Copyright © 2017 xx-company --set-file-version 0.0.1 --set-product-version 0.0.1.0 --set-version-string InternalName xx-xx-xx-app --set-version-string OriginalFilename  --set-version-string CompanyName xx-company --set-icon /Users/xx-user/work/code/xx-xx-xx-app/build/icons/icon.ico +4ms
  electron-builder env: {
  electron-builder   "WINEDEBUG": "-all,err+all",
  electron-builder   "WINEDLLOVERRIDES": "winemenubuilder.exe=d",
  electron-builder   "WINEPREFIX": "/Users/xx-user/Library/Caches/electron-builder/wine/wine-2.0.1-mac-10.12/wine-home",
  electron-builder   "DYLD_FALLBACK_LIBRARY_PATH": "/Users/xx-user/Library/Caches/electron-builder/wine/wine-2.0.1-mac-10.12/lib"
  electron-builder } +1ms
Error: spawn EPERM
    at exports._errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at exports.execFile (child_process.js:208:15)
    at default (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/builder-util/src/util.ts:59:5)
    at exec (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/builder-util/src/util.ts:58:3)
    at wineExecutable.value.then.wine (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/builder-util/src/wine.ts:40:21)
From previous event:
    at execWine (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/builder-util/src/wine.ts:40:8)
    at /Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/src/winPackager.ts:320:11
From previous event:
    at WinPackager.signAndEditResources (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/out/winPackager.js:427:11)
    at WinPackager.signApp (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/src/winPackager.ts:336:17)
    at /Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/src/platformPackager.ts:199:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at WinPackager.doPack (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/out/platformPackager.js:251:11)
    at /Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/src/platformPackager.ts:105:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/out/platformPackager.js:174:11)
    at /Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/out/packager.js:338:11)
    at /Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/out/packager.js:257:11)
    at /Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/src/builder.ts:286:40
    at Generator.next (<anonymous>)
    at build (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/out/cli/cli.js:155:79)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.args [as handler] (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/out/cli/cli.js:155:68)
    at Object.self.runCommand (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/xx-user/work/code/xx-xx-xx-app/node_modules/electron-builder/out/cli/cli.js:151:418)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

```

**Comment by develar** [comment]
Please try to remove ~/Library/Caches/electron-builder
