### ISSUE TITLE
Missing credentials in config -  while publishing windows build into S3 from mac 

### ISSUE THREAD

**Issue by myfrndjk** [electron-userland/electron-builder#2063]
* **19.28.4**: 

* **NSIS  - win32-x64**: 

When I try to publish into S3 I am getting following error.
I set up my secret and access key as below

```
process.env.AWS_ACCESS_KEY_ID = "kfnrk";
process.env.AWS_SECRET_ACCESS_KEY = "wdbwkef";
```

I can able to print and verify from my code.

Building NSIS installer
  Packaging NSIS installer for arch x64
Publishing to S3 (bucket: release)
**Error: Cannot cleanup:** 
```

Error #1 --------------------------------------------------------------------------------
CredentialsError: Missing credentials in config
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at connect (net.js:880:16)
    at net.js:969:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
From previous event:
    at Request.promise (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/aws-sdk/lib/request.js:777:12)
    at /Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-publisher-s3/src/uploader.ts:81:94
    at Timeout.tryRun [as _onTimeout] (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-publisher-s3/src/uploader.ts:192:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

Error #2 --------------------------------------------------------------------------------
CredentialsError: Missing credentials in config
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at connect (net.js:880:16)
    at net.js:969:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
From previous event:
    at Request.promise (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/aws-sdk/lib/request.js:777:12)
    at /Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-publisher-s3/src/uploader.ts:81:94
    at Timeout.tryRun [as _onTimeout] (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-publisher-s3/src/uploader.ts:192:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at connect (net.js:880:16)
    at net.js:969:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at Request.promise (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/aws-sdk/lib/request.js:777:12)
    at /Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-publisher-s3/src/uploader.ts:81:94
    at Timeout.tryRun [as _onTimeout] (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-publisher-s3/src/uploader.ts:192:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at connect (net.js:880:16)
    at net.js:969:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at Request.promise (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/aws-sdk/lib/request.js:777:12)
    at /Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-publisher-s3/src/uploader.ts:81:94
    at Timeout.tryRun [as _onTimeout] (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-publisher-s3/src/uploader.ts:192:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    at NestedError (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/builder-util/src/promise.ts:42:5)
    at throwError (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/builder-util/src/asyncTaskManager.ts:91:11)
    at checkErrors (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/builder-util/src/asyncTaskManager.ts:54:9)
    at /Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/builder-util/src/asyncTaskManager.ts:68:7
From previous event:
    at AsyncTaskManager.awaitTasks (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/builder-util/out/asyncTaskManager.js:103:11)
    at PublishManager.awaitTasks (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-builder/src/publish/PublishManager.ts:175:29)
    at /Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-builder/src/builder.ts:292:29
    at /Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/builder-util/src/promise.ts:26:11
    at next (native)
From previous event:
    at executeFinally (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/builder-util/out/promise.js:37:21)
    at /Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-builder/src/builder.ts:286:10
    at next (native)
From previous event:
    at build (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.self.runCommand (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/blabla/Desktop/backup/testnewele/src/UmtElectronClient/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

Package.json

```
      "publish": {
        "provider": "s3",
        "bucket": "release"
      }
```

**Comment by myfrndjk** [comment]
Sorry for the false alarm.
I can able to fix that issue by doing this in my mac.
Now all are working fine

```
$ export AWS_ACCESS_KEY_ID=sfbrjkgnrkgn
$ export AWS_SECRET_ACCESS_KEY=asdbefbrfbgbe+sjdej
```

Thanks
Jk

**Comment by develar** [comment]
I hope posted credentials are fake and not real.
