### ISSUE TITLE
nsis-web build fails: "Error: What does empty stream mean?"

### ISSUE THREAD

**Issue by Zamiell** [electron-userland/electron-builder#2109]
**Operating system:** Windows 7 Professional

**Which version of electron-builder are you using?**
* **Version**: 19.30.1

**Which version of electron-updater are you using (if applicable)?**
* **Version**: 2.10.0

* **Target**: From my `package.json` file,
```
  "build": {
    "appId": "org.electron.IsaacRacingPlus",
    "win": {
      "target": "nsis-web"
    },
    "publish": {
      "provider": "github"
    }
  },
```

**Enter your issue details below this comment.**

I've been successfully building my Electron project using `NSIS` for the past year or so. It works great! Tonight, I decided to try using the brand new `NSIS-web`. But it didn't go so well.

Here's the output after running:
```
C:\Repositories\isaac-racing-client>npm run dist --python="C:/Python27/python.exe" > log.txt 2>&1
```

```
> RacingPlus@0.11.5 dist C:\Repositories\isaac-racing-client
> build

electron-builder 19.30.1
electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
Rebuilding native production dependencies for win32:x64
Packaging for win32 x64 using electron 1.7.6 to dist\win-unpacked
Building NSIS installer
  Packaging NSIS installer for arch x64
Error: What does empty stream mean?
    at BlockMapBuilder.buildFile (C:\Repositories\isaac-racing-client\node_modules\app-package-builder\src\blockMap.ts:83:13)
    at C:\Repositories\isaac-racing-client\node_modules\app-package-builder\src\blockMap.ts:113:15
    at next (native)
From previous event:
    at computeBlockMap (C:\Repositories\isaac-racing-client\node_modules\app-package-builder\out\blockMap.js:133:22)
    at C:\Repositories\isaac-racing-client\node_modules\app-package-builder\src\blockMap.ts:26:28
From previous event:
    at createDifferentialPackage (C:\Repositories\isaac-racing-client\node_modules\app-package-builder\out\blockMap.js:49:21)
    at C:\Repositories\isaac-racing-client\node_modules\electron-builder\src\targets\nsis\nsis.ts:94:20
    at next (native)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at WebInstallerTarget.buildAppPackage (C:\Repositories\isaac-racing-client\node_modules\electron-builder\out\targets\nsis\nsis.js:192:11)
    at C:\Repositories\isaac-racing-client\node_modules\electron-builder\src\targets\nsis\nsisUtil.ts:20:87
    at next (native)
From previous event:
    at AppPackageHelper.packArch (C:\Repositories\isaac-racing-client\node_modules\electron-builder\out\targets\nsis\nsisUtil.js:66:11)
    at C:\Repositories\isaac-racing-client\node_modules\electron-builder\src\targets\nsis\nsis.ts:180:51
    at next (native)
From previous event:
    at default.map (C:\Repositories\isaac-racing-client\node_modules\electron-builder\out\targets\nsis\nsis.js:287:37)
From previous event:
    at C:\Repositories\isaac-racing-client\node_modules\electron-builder\src\targets\nsis\nsis.ts:179:29
    at next (native)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at WebInstallerTarget.buildInstaller (C:\Repositories\isaac-racing-client\node_modules\electron-builder\out\targets\nsis\nsis.js:323:11)
    at C:\Repositories\isaac-racing-client\node_modules\electron-builder\src\targets\nsis\nsis.ts:105:18
    at next (native)
From previous event:
    at WebInstallerTarget.finishBuild (C:\Repositories\isaac-racing-client\node_modules\electron-builder\out\targets\nsis\nsis.js:205:11)
    at C:\Repositories\isaac-racing-client\node_modules\electron-builder\src\packager.ts:268:36
From previous event:
    at Packager.doBuild (C:\Repositories\isaac-racing-client\node_modules\electron-builder\out\packager.js:344:11)
    at C:\Repositories\isaac-racing-client\node_modules\electron-builder\src\packager.ts:186:52
    at next (native)
From previous event:
    at Packager.build (C:\Repositories\isaac-racing-client\node_modules\electron-builder\out\packager.js:263:11)
    at C:\Repositories\isaac-racing-client\node_modules\electron-builder\src\builder.ts:286:40
    at next (native)
From previous event:
    at build (C:\Repositories\isaac-racing-client\node_modules\electron-builder\out\builder.js:69:21)
    at loadEnv.then (C:\Repositories\isaac-racing-client\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Object.args [as handler] (C:\Repositories\isaac-racing-client\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\Repositories\isaac-racing-client\node_modules\electron-builder\node_modules\yargs\lib\command.js:226:22)
    at Object.parseArgs [as _parseArgs] (C:\Repositories\isaac-racing-client\node_modules\electron-builder\node_modules\yargs\yargs.js:998:24)
    at Object.get [as argv] (C:\Repositories\isaac-racing-client\node_modules\electron-builder\node_modules\yargs\yargs.js:912:21)
    at Object.<anonymous> (C:\Repositories\isaac-racing-client\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist" "--python=C:/Python27/python.exe"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! RacingPlus@0.11.5 dist: `build`
npm ERR! Exit status 4294967295
npm ERR! 
npm ERR! Failed at the RacingPlus@0.11.5 dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the RacingPlus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs RacingPlus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls RacingPlus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Repositories\isaac-racing-client\npm-debug.log
```

As always, thanks for your continued support to this project develar. <3

**Comment by Zamiell** [comment]
A tangential request:

In the command output, you can see `Building NSIS installer`.

Can you change this output to `Building NSIS-web installer` for NSIS-web builds?

**Comment by develar** [comment]
1. It is bug. Fixed, will be released soon.
2. You in any case should add to `files`: `!node_modules/greenworks/deps/**/*`

Add to your "build":

```
"files": ["!node_modules/greenworks/deps/**/*"]
```

**Comment by Zamiell** [comment]
Thank you! That worked and now I'm running `NSIS-web`. =D

**Comment by develar** [comment]
> Can you change this output to Building NSIS-web installer for NSIS-web builds?

Thanks, fixed.
