### ISSUE TITLE
TypeError: Buffer.allocUnsafe is not a function on Windows

### ISSUE THREAD

**Issue by markgillnz** [electron-userland/electron-builder#2110]
* **Version: 19.30.1**: 
* **Target: NSIS**: 

I'm seeing an error when using electron-builder of `TypeError: Buffer.allocUnsafe is not a function`. This only occurs on Windows, not Mac.

I understand Buffer.allocUnsafe was added to Node in v5.10.0 however as you can see I'm using v6.3.0 so I'm at a loss as to why it thinks it does not exist. Can you shed any light?

error	25-Sep-2017 11:24:27	Error: Application entry file "build\index.js" in the "E:\a1\EMRC-ELECTRON97-BW\dist\win-ia32-unpacked\resources\app.asar" is corrupted: TypeError: Buffer.allocUnsafe is not a function
error	25-Sep-2017 11:24:27	    at error (E:\a1\EMRC-ELECTRON97-BW\node_modules\electron-builder\src\util\asarUtil.ts:234:12)
error	25-Sep-2017 11:24:27	    at E:\a1\EMRC-ELECTRON97-BW\node_modules\electron-builder\src\util\asarUtil.ts:242:11
error	25-Sep-2017 11:24:27	    at throw (native)
error	25-Sep-2017 11:24:27	    at processImmediate [as _immediateCallback] (timers.js:383:17)
.
.
.
25-Sep-2017 11:24:27 | npm ERR! Windows_NT 6.1.7601
25-Sep-2017 11:24:27 | npm ERR! argv "E:\\nodejs\\node6.exe" "E:\\a1\\EMRC-ELECTRON97-BW\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
25-Sep-2017 11:24:27 | npm ERR! node v6.3.0
25-Sep-2017 11:24:27 | npm ERR! npm  v3.10.10
25-Sep-2017 11:24:27 | npm ERR! code ELIFECYCLE

**Comment by markgillnz** [comment]
This appears to be a bad environment setup whereby node4 was actually being used despite npm reporting node6 being used
