### ISSUE TITLE
Build fails if custom `fileAssociations` with custom file icon specified

### ISSUE THREAD

**Issue by guanxun14** [electron-userland/electron-builder#2112]
* **Version**:  19.30.1
* **Target**: macOS
* **Electron Version**: 1.6.6
* **Node Version**: 7.4.0

With `package.json` configured:
```
...
"fileAssociations": [
    {
        "ext": ["customextension"],
        "name": "CustomExtension",
        "role": "Editor"
    }
],
...
```

And the following files located in `build` folder:
- icon.icns
- icon.ico
- /icons
- customextension.icns
- customextension.ico

The `npm run release` build process fails with:
```
electron-builder 19.29.0
No native production dependencies
Packaging for darwin x64 using electron 1.6.6 to dist/mac
TypeError: Cannot read property 'mode' of undefined
    at default (/Users/username/Desktop/electron-boilerplate/node_modules/builder-util/src/fs.ts:175:82)
    at copyOrLinkFile (/Users/username/Desktop/electron-boilerplate/node_modules/builder-util/src/fs.ts:173:5)
    at /Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/src/packager/mac.ts:120:15
    at Generator.next (<anonymous>)
From previous event:
    at appPlist.CFBundleDocumentTypes.default.map (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/out/packager/mac.js:113:34)
From previous event:
    at /Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/src/packager/mac.ts:114:60
From previous event:
    at createMacApp (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/out/packager/mac.js:139:21)
    at /Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/src/platformPackager.ts:188:13
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at MacPackager.doPack (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/out/platformPackager.js:251:11)
    at /Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/src/macPackager.ts:87:71
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/out/macPackager.js:183:11)
    at /Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/out/packager.js:338:11)
    at /Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/out/packager.js:257:11)
    at /Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/src/builder.ts:286:40
    at Generator.next (<anonymous>)
    at build (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/out/cli/cli.js:155:79)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Object.args [as handler] (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/out/cli/cli.js:155:68)
    at Object.runCommand (/Users/username/Desktop/electron-boilerplate/node_modules/yargs/lib/command.js:226:22)
    at Object.parseArgs [as _parseArgs] (/Users/username/Desktop/electron-boilerplate/node_modules/yargs/yargs.js:998:24)
    at Object.get [as argv] (/Users/username/Desktop/electron-boilerplate/node_modules/yargs/yargs.js:912:21)
    at Object.<anonymous> (/Users/username/Desktop/electron-boilerplate/node_modules/electron-builder/out/cli/cli.js:151:418)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

From [docs](https://www.electron.build/configuration/configuration):
> Defaults to `${firstExt}.icns`/`${firstExt}.ico` (if several extensions specified, first is used) or to application icon.

The last version of electron-builder that works as per docs with this configuration is `19.28.4`, which I have reverted to as a workaround.

You can replicate this by cloning [electron-boilerplate](https://github.com/szwacz/electron-boilerplate) and configuring `devDependencies` of `package.json` (in addition to config mentioned above) with:
```
...
"electron": "1.6.6",
"electron-builder": "19.30.1",
...
```
Then placing custom icons in `/build`, followed by running `npm install` and then `npm run release`.

***
Would like to take this chance to say thanks for the phenomenal amount of work that has gone into electron-builder! 😊

**Comment by develar** [comment]
Please update to 19.30.2

> Node Version: 7.4.0

Consider to update to 8.5.0 :)

**Comment by guanxun14** [comment]
Works great, thanks!
