### ISSUE TITLE
electron-builder conflicted with bufferutil@3.0.2

### ISSUE THREAD

**Issue by dbarrios1907** [electron-userland/electron-builder#2133]
### Version of electron-builder I'm using
The version used is 19.31.1 but I also tested older versions and the problems persist.

### Target platform
* **Target**:  build --win --x64

The problem seems to be with the openvidu-browser dependencies "bufferutil@3.0.2" and "utf-8-validate@1.0.4",  and these same dependencies on "electron-builder": "19.31.1"

When try to package the app with "electron-builder" a compatibility issue shows up suggesting "bufferutil" dependency problems 

> ion-electron-test@0.0.1 package D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu
> build --win --x64

electron-builder 19.31.1
Rebuilding native production dependencies for win32:x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> bufferutil@3.0.2 install D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\bufferutil {git}{hg}
{lamb} if not defined npm_config_node_gyp (node "C:\Users\daniel\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "node C:\Users\daniel\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

Error output:
prebuild-install info begin Prebuild-install version 2.2.2
prebuild-install info install installing standalone, skipping download.
module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\bufferutil\node C:\Users\daniel\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\daniel\AppData\Roaming\npm-cache\_logs\2017-09-29T17_01_40_045Z-debug.log

    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
    at ChildProcess.childProcess.once.code (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\builder-util\src\util.ts:200:14)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\builder-util\src\util.ts:163:3)
    at D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\util\yarn.ts:172:5
From previous event:
    at rebuild (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\util\yarn.js:96:22)
    at D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\util\yarn.ts:21:11
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at installOrRebuild (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\util\yarn.js:34:21)
    at D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\packager.ts:338:7
    at next (native)
From previous event:
    at Packager.installAppDependencies (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\packager.js:408:11)
    at D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\packager.ts:234:20
    at next (native)
From previous event:
    at Packager.doBuild (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\packager.js:344:11)
    at D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\packager.ts:186:52
    at next (native)
From previous event:
    at Packager.build (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\packager.js:263:11)
    at D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\builder.ts:286:40
    at next (native)
From previous event:
    at build (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\out\builder.js:69:21)
    at loadEnv.then (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\yargs\lib\command.js:226:22)
    at Object.parseArgs [as _parseArgs] (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\yargs\yargs.js:998:24)
    at Object.get [as argv] (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\yargs\yargs.js:912:21)
    at Object.<anonymous> (D:\Desarrollo\Proyectos-Personales\Codigo\Ionic-Projects\electron-openvidu\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! ion-electron-test@0.0.1 package: `build --win --x64`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the ion-electron-test@0.0.1 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I hope someone could help me to resolve the issue.
Thanks, ahead

**Comment by develar** [comment]
Please use yarn instead of npm.

**Comment by dbarrios1907** [comment]
Saludos,

I make the test with yarn and npm. In both cases I experimented the same
error.
