### ISSUE TITLE
Cannot find specified resource "Name.app" during build for DMG

### ISSUE THREAD

**Issue by roby65** [electron-userland/electron-builder#2147]
* **Version**: 19.33.0
* **Target**:  NSIS & DMG

I updated from 19.27.0 to 19.33.0, now when i build, I get this error:

> Error: Cannot find specified resource "Name.app", nor relative to "[cwd]/build", neither relative to project dir ("[cwd]")

The file is in the mac folder, not in the 2 listed folders. How can i fix that? It was working before the update.

**Comment by develar** [comment]
MacOS version? Apfs or hfs?

**Comment by roby65** [comment]
MacOS 10.9.5, FileSystem "Mac Os Extended (Journaled)"

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.

If you can provide sample app, it will be helpful.

**Comment by develar** [comment]
I strongly recommend you to use at least macOS 10.12 because otherwise DMG will be not signed.

**Comment by roby65** [comment]
Here is the log, I had to remove some sensitive informations.

```

> appname@1.2.4 dist /Users/federico/Documents/Clienti/Appname/_build
> build --mac --win --ia32

electron-builder 19.33.0
2017-10-03T10:18:17.719Z electron-builder Effective config:
appId: appname
nsis:
  oneClick: false
  perMachine: true
  allowElevation: true
  allowToChangeInstallationDirectory: true
  runAfterFinish: false
  language: 1040
  artifactName: '${productName} ${version}.${ext}'
win:
  certificateFile: build/appname.pfx
  certificatePassword: <stripped sensitive data>
dmg:
  background: build/background.png
  window:
    width: 650
    height: 440
  contents:
    - x: 448
      'y': 244
      type: link
      path: /Applications
    - x: 192
      'y': 244
      type: file
      path: ''
    - x: 0
      'y': 480
      path: .background
    - x: 32
      'y': 480
      path: .DS_Store
    - x: 64
      'y': 480
      path: .Trashes
    - x: 96
      'y': 480
      path: .VolumeIcon.icns
electronVersion: 1.4.15

2017-10-03T10:18:18.202Z electron-builder Two package.json structure is used (dev: /Users/federico/Documents/Clienti/Appname/_build/package.json, app: /Users/federico/Documents/Clienti/Appname/_build/app/package.json)
No native production dependencies
Packaging for darwin x64 using electron 1.4.15 to dist/mac
2017-10-03T10:18:18.764Z electron-builder Spawning /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za x -bd /Users/federico/Library/Caches/electron/electron-v1.4.15-darwin-x64.zip -aoa -o/Users/federico/Documents/Clienti/Appname/_build/dist/mac

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 42120203 bytes (41 MiB)

Extracting archive: /Users/federico/Library/Caches/electron/electron-v1.4.15-darwin-x64.zip
--
Path = /Users/federico/Library/Caches/electron/electron-v1.4.15-darwin-x64.zip
Type = zip
Physical Size = 42120203

Everything is Ok

Folders: 143
Files: 180
Size:       112414322
Compressed: 42120203
2017-10-03T10:18:20.330Z electron-builder 7za (61506) exited with exit code 0
2017-10-03T10:18:27.086Z electron-builder Executing security find-identity -v
2017-10-03T10:18:27.091Z electron-builder Executing security find-identity -v -p codesigning

Signing app (identity: 0000000000000000000000000000000000000000 Developer ID Application: Certificate Name (0000000000))
Building macOS zip
Building DMG
2017-10-03T10:18:39.841Z electron-builder Spawning /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za a -bd -mx=9 -mtc=off -mm=Deflate -mcu /Users/federico/Documents/Clienti/Appname/_build/dist/Appname-1.2.4-mac.zip Appname.app
2017-10-03T10:18:39.841Z electron-builder cwd: /Users/federico/Documents/Clienti/Appname/_build/dist/mac
No native production dependencies
Packaging for win32 ia32 using electron 1.4.15 to dist/win-ia32-unpacked
2017-10-03T10:18:39.938Z electron-builder macOS version: 10.9.5
2017-10-03T10:18:39.939Z electron-builder Spawning hdiutil create -srcfolder /Users/federico/Documents/Clienti/Appname/_build/dist/mac/Appname.app -volname Appname 1.2.4 -anyowners -nospotlight -format UDRW -fs HFS+ -fsargs -c c=64,a=16,e=16 /private/var/folders/dz/4_qxmzw14tg_lnwkdh2nz07w0000gn/T/temp-files-oVGZxZ/0.dmg
2017-10-03T10:18:40.166Z electron-builder Spawning /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za x -bd /Users/federico/Library/Caches/electron/electron-v1.4.15-win32-ia32.zip -aoa -o/Users/federico/Documents/Clienti/Appname/_build/dist/win-ia32-unpacked

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 44056999 bytes (43 MiB)

Extracting archive: /Users/federico/Library/Caches/electron/electron-v1.4.15-win32-ia32.zip
--
Path = /Users/federico/Library/Caches/electron/electron-v1.4.15-win32-ia32.zip
Type = zip
Physical Size = 44056999

Everything is Ok

Files: 74
Size:       108530638
Compressed: 44056999
2017-10-03T10:18:42.604Z electron-builder 7za (61559) exited with exit code 0
2017-10-03T10:18:53.546Z electron-builder Copy cached /Users/federico/Documents/Clienti/Appname/_build/dist/.cache/ia32/app.exe executable to /Users/federico/Documents/Clienti/Appname/_build/dist/win-ia32-unpacked/Appname.exe
executable cache: 2s 447ms
Building nsis installer (ia32)
2017-10-03T10:18:56.140Z electron-builder Spawning /usr/local/lib/node_modules/electron-builder/node_modules/7zip-bin-mac/7za a -bd -mx=9 -mtc=off -mtm=off -mta=off /Users/federico/Documents/Clienti/Appname/_build/dist/appname-1.2.4-ia32.nsis.7z .
2017-10-03T10:18:56.140Z electron-builder cwd: /Users/federico/Documents/Clienti/Appname/_build/dist/win-ia32-unpacked
created: /private/var/folders/dz/4_qxmzw14tg_lnwkdh2nz07w0000gn/T/temp-files-oVGZxZ/0.dmg
2017-10-03T10:19:15.984Z electron-builder hdiutil (61555) exited with exit code 0
2017-10-03T10:19:15.991Z electron-builder Spawning hdiutil resize -size 163511917 /private/var/folders/dz/4_qxmzw14tg_lnwkdh2nz07w0000gn/T/temp-files-oVGZxZ/0.dmg
2017-10-03T10:19:16.023Z electron-builder hdiutil (61598) exited with exit code 0
2017-10-03T10:19:16.028Z electron-builder Executing hdiutil attach -noverify -noautoopen -readwrite /private/var/folders/dz/4_qxmzw14tg_lnwkdh2nz07w0000gn/T/temp-files-oVGZxZ/0.dmg
2017-10-03T10:19:17.281Z electron-builder /dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	Apple_HFS                      	/Volumes/Appname 1.2.4

2017-10-03T10:19:17.288Z electron-builder Executing ln -s /Applications /Volumes/Appname 1.2.4/Applications
2017-10-03T10:19:17.298Z electron-builder Executing hdiutil detach /dev/disk2
2017-10-03T10:19:17.969Z electron-builder "disk2" unmounted.
"disk2" ejected.

2017-10-03T10:19:17.970Z electron-builder Async task error: Error: Cannot find specified resource "Appname.app", nor relative to "/Users/federico/Documents/Clienti/Appname/_build/build", neither relative to project dir ("/Users/federico/Documents/Clienti/Appname/_build")
    at /usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:542:17
From previous event:
    at MacPackager.getResource (/usr/local/lib/node_modules/electron-builder/out/platformPackager.js:565:11)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:335:37
    at Generator.next (<anonymous>)
From previous event:
    at computeDmgEntries (/usr/local/lib/node_modules/electron-builder/out/targets/dmg.js:129:22)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:312:31
From previous event:
    at customizeDmg (/usr/local/lib/node_modules/electron-builder/out/targets/dmg.js:96:22)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:45:54
    at /usr/local/lib/node_modules/electron-builder/node_modules/dmg-builder/src/dmgUtil.ts:34:31
From previous event:
    at attachAndExecute (/usr/local/lib/node_modules/electron-builder/node_modules/dmg-builder/out/dmgUtil.js:40:21)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:45:10
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/usr/local/lib/node_modules/electron-builder/out/targets/dmg.js:247:11)
    at taskManager.addTask.default.map.it (/usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:110:85)
From previous event:
    at MacPackager.packageInDistributableFormat (/usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:110:41)
    at /usr/local/lib/node_modules/electron-builder/src/macPackager.ts:89:26
From previous event:
    at /usr/local/lib/node_modules/electron-builder/src/macPackager.ts:89:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/usr/local/lib/node_modules/electron-builder/out/macPackager.js:183:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/usr/local/lib/node_modules/electron-builder/out/packager.js:344:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/usr/local/lib/node_modules/electron-builder/out/packager.js:263:11)
    at /usr/local/lib/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
    at build (/usr/local/lib/node_modules/electron-builder/out/builder.js:63:21)
    at loadEnv.then (/usr/local/lib/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (/usr/local/lib/node_modules/electron-builder/out/builder.js:63:21)
    at loadEnv.then (/usr/local/lib/node_modules/electron-builder/out/cli/cli.js:155:79)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.args [as handler] (/usr/local/lib/node_modules/electron-builder/out/cli/cli.js:155:68)
    at Object.runCommand (/usr/local/lib/node_modules/electron-builder/node_modules/yargs/lib/command.js:226:22)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/electron-builder/node_modules/yargs/yargs.js:998:24)
    at Object.get [as argv] (/usr/local/lib/node_modules/electron-builder/node_modules/yargs/yargs.js:912:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/out/cli/cli.js:151:418)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
2017-10-03T10:19:36.833Z electron-builder 7za (61554) exited with exit code 0
2017-10-03T10:19:37.594Z electron-builder 7za (61583) exited with exit code 0
nsis package, ia32: 41s 460ms
2017-10-03T10:19:37.807Z electron-builder Spawning /Users/federico/Library/Caches/electron-builder/nsis/nsis-3.0.1.13/mac/makensis -WX -DAPP_ID=appname -DAPP_GUID=a2841f10-1b9b-5f78-a556-7a136fe5e8f5 -DPRODUCT_NAME=Appname -DPRODUCT_FILENAME=Appname -DAPP_FILENAME=Appname -DAPP_DESCRIPTION=Appname -DVERSION=1.2.4 -DPROJECT_DIR=/Users/federico/Documents/Clienti/Appname/_build -DBUILD_RESOURCES_DIR=/Users/federico/Documents/Clienti/Appname/_build/build -DCOMPANY_NAME=Company -DMUI_ICON=/Users/federico/Documents/Clienti/Appname/_build/build/icon.ico -DMUI_UNICON=/Users/federico/Documents/Clienti/Appname/_build/build/icon.ico -DAPP_32=/Users/federico/Documents/Clienti/Appname/_build/dist/appname-1.2.4-ia32.nsis.7z -DAPP_32_NAME=appname-1.2.4-ia32.nsis.7z -DAPP_32_HASH=955BB292F1072F40A98BF66C4C79907DA2DAB267418979D14940234D387D719D0F1836C57D4BFC1E9C963E538BDA62449F0FD6517EF0C248C0B0FA19D0938E95 -DCOMPRESSION_METHOD=7z -DMULTIUSER_INSTALLMODE_ALLOW_ELEVATION -DINSTALL_MODE_PER_ALL_USERS -DINSTALL_MODE_PER_ALL_USERS_REQUIRED -DallowToChangeInstallationDirectory -DSHORTCUT_NAME=Appname -DUNINSTALL_DISPLAY_NAME=Appname 1.2.4 -DMUI_WELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp -DMUI_UNWELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp -DCOMPRESS=auto -DBUILD_UNINSTALLER -DUNINSTALLER_OUT_FILE=Z:\Users\federico\Documents\Clienti\Appname\_build\dist\.__uninstaller-nsis-f040-15ee1bf81ca.exe -XOutFile "/Users/federico/Documents/Clienti/Appname/_build/dist/Appname 1.2.4.exe" -XVIProductVersion 1.2.4.0 -XVIAddVersionKey /LANG=1040 ProductName "Appname" -XVIAddVersionKey /LANG=1040 ProductVersion "1.2.4" -XVIAddVersionKey /LANG=1040 LegalCopyright "Copyright © 2017" -XVIAddVersionKey /LANG=1040 FileDescription "Appname" -XVIAddVersionKey /LANG=1040 FileVersion "1.2.4" -XVIAddVersionKey /LANG=1040 CompanyName "Company" -XUnicode true -XSetCompressor zlib -
2017-10-03T10:19:37.807Z electron-builder cwd: /usr/local/lib/node_modules/electron-builder/templates/nsis
2017-10-03T10:19:39.644Z electron-builder makensis (61621) exited with exit code 0
2017-10-03T10:19:39.651Z electron-builder Executing wine --version
2017-10-03T10:19:39.662Z electron-builder wine-1.8.2

2017-10-03T10:19:39.662Z electron-builder Executing wine /Users/federico/Documents/Clienti/Appname/_build/dist/Appname 1.2.4.exe
2017-10-03T10:19:44.711Z electron-builder err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib
err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0

  Signing NSIS uninstaller (certificate file: "build/appname.pfx")
2017-10-03T10:19:44.730Z electron-builder Executing /Users/federico/Library/Caches/electron-builder/winCodeSign/winCodeSign-1.9.0/darwin/osslsigncode -in /Users/federico/Documents/Clienti/Appname/_build/dist/.__uninstaller-nsis-f040-15ee1bf81ca.exe -out /Users/federico/Documents/Clienti/Appname/_build/dist/.__uninstaller-nsis-f040-15ee1bf81ca-signed-sha1.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -pkcs12 build/appname.pfx -h sha1 -n Appname -pass 4d77adc12bb24d3ae4d5b5553c1bf8ed7e8e96c78813e3574ef2185f478bebc5 (sha256 hash)
2017-10-03T10:19:44.731Z electron-builder env: {}
2017-10-03T10:19:45.149Z electron-builder Succeeded

2017-10-03T10:19:45.151Z electron-builder Executing /Users/federico/Library/Caches/electron-builder/winCodeSign/winCodeSign-1.9.0/darwin/osslsigncode -in /Users/federico/Documents/Clienti/Appname/_build/dist/.__uninstaller-nsis-f040-15ee1bf81ca.exe -out /Users/federico/Documents/Clienti/Appname/_build/dist/.__uninstaller-nsis-f040-15ee1bf81ca-signed-sha256.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -pkcs12 build/appname.pfx -h sha256 -n Appname -nest -pass 4d77adc12bb24d3ae4d5b5553c1bf8ed7e8e96c78813e3574ef2185f478bebc5 (sha256 hash)
2017-10-03T10:19:45.153Z electron-builder env: {}
2017-10-03T10:19:45.441Z electron-builder Succeeded

2017-10-03T10:19:45.451Z electron-builder Spawning /Users/federico/Library/Caches/electron-builder/nsis/nsis-3.0.1.13/mac/makensis -WX -DAPP_ID=appname -DAPP_GUID=a2841f10-1b9b-5f78-a556-7a136fe5e8f5 -DPRODUCT_NAME=Appname -DPRODUCT_FILENAME=Appname -DAPP_FILENAME=Appname -DAPP_DESCRIPTION=Appname -DVERSION=1.2.4 -DPROJECT_DIR=/Users/federico/Documents/Clienti/Appname/_build -DBUILD_RESOURCES_DIR=/Users/federico/Documents/Clienti/Appname/_build/build -DCOMPANY_NAME=Company -DMUI_ICON=/Users/federico/Documents/Clienti/Appname/_build/build/icon.ico -DMUI_UNICON=/Users/federico/Documents/Clienti/Appname/_build/build/icon.ico -DAPP_32=/Users/federico/Documents/Clienti/Appname/_build/dist/appname-1.2.4-ia32.nsis.7z -DAPP_32_NAME=appname-1.2.4-ia32.nsis.7z -DAPP_32_HASH=955BB292F1072F40A98BF66C4C79907DA2DAB267418979D14940234D387D719D0F1836C57D4BFC1E9C963E538BDA62449F0FD6517EF0C248C0B0FA19D0938E95 -DCOMPRESSION_METHOD=7z -DMULTIUSER_INSTALLMODE_ALLOW_ELEVATION -DINSTALL_MODE_PER_ALL_USERS -DINSTALL_MODE_PER_ALL_USERS_REQUIRED -DallowToChangeInstallationDirectory -DSHORTCUT_NAME=Appname -DUNINSTALL_DISPLAY_NAME=Appname 1.2.4 -DMUI_WELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp -DMUI_UNWELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp -DCOMPRESS=auto -DUNINSTALLER_OUT_FILE=/Users/federico/Documents/Clienti/Appname/_build/dist/.__uninstaller-nsis-f040-15ee1bf81ca.exe -XOutFile "/Users/federico/Documents/Clienti/Appname/_build/dist/Appname 1.2.4.exe" -XVIProductVersion 1.2.4.0 -XVIAddVersionKey /LANG=1040 ProductName "Appname" -XVIAddVersionKey /LANG=1040 ProductVersion "1.2.4" -XVIAddVersionKey /LANG=1040 LegalCopyright "Copyright © 2017" -XVIAddVersionKey /LANG=1040 FileDescription "Appname" -XVIAddVersionKey /LANG=1040 FileVersion "1.2.4" -XVIAddVersionKey /LANG=1040 CompanyName "Company" -XUnicode true -XSetCompressor zlib -
2017-10-03T10:19:45.451Z electron-builder cwd: /usr/local/lib/node_modules/electron-builder/templates/nsis
2017-10-03T10:19:48.121Z electron-builder makensis (61649) exited with exit code 0
Signing Appname 1.2.4.exe (certificate file: "build/appname.pfx")
2017-10-03T10:19:48.127Z electron-builder Executing /Users/federico/Library/Caches/electron-builder/winCodeSign/winCodeSign-1.9.0/darwin/osslsigncode -in /Users/federico/Documents/Clienti/Appname/_build/dist/Appname 1.2.4.exe -out /Users/federico/Documents/Clienti/Appname/_build/dist/Appname 1.2.4-signed-sha1.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -pkcs12 build/appname.pfx -h sha1 -n Appname -pass 4d77adc12bb24d3ae4d5b5553c1bf8ed7e8e96c78813e3574ef2185f478bebc5 (sha256 hash)
2017-10-03T10:19:48.128Z electron-builder env: {}
2017-10-03T10:19:48.921Z electron-builder Succeeded

2017-10-03T10:19:48.928Z electron-builder Executing /Users/federico/Library/Caches/electron-builder/winCodeSign/winCodeSign-1.9.0/darwin/osslsigncode -in /Users/federico/Documents/Clienti/Appname/_build/dist/Appname 1.2.4.exe -out /Users/federico/Documents/Clienti/Appname/_build/dist/Appname 1.2.4-signed-sha256.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -pkcs12 build/appname.pfx -h sha256 -n Appname -nest -pass 4d77adc12bb24d3ae4d5b5553c1bf8ed7e8e96c78813e3574ef2185f478bebc5 (sha256 hash)
2017-10-03T10:19:48.930Z electron-builder env: {}
2017-10-03T10:19:49.894Z electron-builder Succeeded

Error: Cannot find specified resource "Appname.app", nor relative to "/Users/federico/Documents/Clienti/Appname/_build/build", neither relative to project dir ("/Users/federico/Documents/Clienti/Appname/_build")
    at /usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:542:17
From previous event:
    at MacPackager.getResource (/usr/local/lib/node_modules/electron-builder/out/platformPackager.js:565:11)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:335:37
    at Generator.next (<anonymous>)
From previous event:
    at computeDmgEntries (/usr/local/lib/node_modules/electron-builder/out/targets/dmg.js:129:22)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:312:31
From previous event:
    at customizeDmg (/usr/local/lib/node_modules/electron-builder/out/targets/dmg.js:96:22)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:45:54
    at /usr/local/lib/node_modules/electron-builder/node_modules/dmg-builder/src/dmgUtil.ts:34:31
From previous event:
    at attachAndExecute (/usr/local/lib/node_modules/electron-builder/node_modules/dmg-builder/out/dmgUtil.js:40:21)
    at /usr/local/lib/node_modules/electron-builder/src/targets/dmg.ts:45:10
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/usr/local/lib/node_modules/electron-builder/out/targets/dmg.js:247:11)
    at taskManager.addTask.default.map.it (/usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:110:85)
From previous event:
    at MacPackager.packageInDistributableFormat (/usr/local/lib/node_modules/electron-builder/src/platformPackager.ts:110:41)
    at /usr/local/lib/node_modules/electron-builder/src/macPackager.ts:89:26
From previous event:
    at /usr/local/lib/node_modules/electron-builder/src/macPackager.ts:89:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/usr/local/lib/node_modules/electron-builder/out/macPackager.js:183:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/usr/local/lib/node_modules/electron-builder/out/packager.js:344:11)
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/usr/local/lib/node_modules/electron-builder/out/packager.js:263:11)
    at /usr/local/lib/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
    at build (/usr/local/lib/node_modules/electron-builder/out/builder.js:63:21)
    at loadEnv.then (/usr/local/lib/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (/usr/local/lib/node_modules/electron-builder/out/builder.js:63:21)
    at loadEnv.then (/usr/local/lib/node_modules/electron-builder/out/cli/cli.js:155:79)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.args [as handler] (/usr/local/lib/node_modules/electron-builder/out/cli/cli.js:155:68)
    at Object.runCommand (/usr/local/lib/node_modules/electron-builder/node_modules/yargs/lib/command.js:226:22)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/electron-builder/node_modules/yargs/yargs.js:998:24)
    at Object.get [as argv] (/usr/local/lib/node_modules/electron-builder/node_modules/yargs/yargs.js:912:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/out/cli/cli.js:151:418)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! appname@1.2.4 dist: `build --mac --win --ia32`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the appname@1.2.4 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/federico/.npm/_logs/2017-10-03T10_19_49_935Z-debug.log

```

**Comment by mywaystar** [comment]
Same issue on my end with the 19.35.0 using the latest MacOS.

**Comment by mywaystar** [comment]
This commit produces the error: https://github.com/electron-userland/electron-builder/commit/d1b3877bbcc50aae8f358cf076bacdd3a9a33cca#diff-628ed8d56d2b7406eac1ada34f262aa5 

It's not normal to use getRessource at this stage, the .app file shouldn't be in the build directory.

**Comment by develar** [comment]
@mywaystar Thanks, but if `path` specified, it should be path to source file. Otherwise use `name`.

@roby65 Remove empty path from config: `path: ''`

**Comment by develar** [comment]
Old behaviour (ignore empty path) is restored.

@roby65 For what do you need to set position for background and other internal files?

**Comment by roby65** [comment]
Thank you, that fixed my issue. I am setting the position of the internal files because if you have hidden files visible, you can see those files around in the DMG view, so I am moving them out of the window size.
