### ISSUE TITLE
"publish": "never" causes `Cannot find module 'electron-publisher-never'`

### ISSUE THREAD

**Issue by mim-Armand** [electron-userland/electron-builder#2153]
* **"^19.34.1"**: 

* **mac**: 

Setting publish to **never** causes to following error:
Also runing the release command will try to `publish` to Github by default!
```
Error: Cannot find module 'electron-publisher-never'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at requireProviderClass (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/publish/PublishManager.ts:238:14)
    at /Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/publish/PublishManager.ts:363:25
    at Generator.next (<anonymous>)
From previous event:
    at getResolvedPublishConfig (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/publish/PublishManager.js:182:22)
    at /Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/publish/PublishManager.ts:315:64
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at /Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/publish/PublishManager.ts:315:33
    at Generator.next (<anonymous>)
From previous event:
    at getPublishConfigs (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/publish/PublishManager.js:93:22)
    at /Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/publish/PublishManager.ts:87:83
    at Generator.next (<anonymous>)
From previous event:
    at PublishManager.packager.addAfterPackHandler (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/publish/PublishManager.js:340:29)
    at default.each.it (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/packager.ts:354:49)
From previous event:
    at Packager.afterPack (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/packager.ts:354:28)
    at /Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/platformPackager.ts:197:21
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at MacPackager.doPack (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/platformPackager.js:252:11)
    at /Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/macPackager.ts:87:71
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/macPackager.js:183:11)
    at /Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/packager.js:344:11)
    at /Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/packager.js:263:11)
    at /Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
    at build (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/builder.js:63:21)
    at loadEnv.then (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/builder.js:63:21)
    at loadEnv.then (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/cli/cli.js:155:79)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.args [as handler] (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/cli/cli.js:155:68)
    at Object.runCommand (/Users/mim/Desktop/[ * * * ]/node_modules/yargs/lib/command.js:226:22)
    at Object.parseArgs [as _parseArgs] (/Users/mim/Desktop/[ * * * ]/node_modules/yargs/yargs.js:998:24)
    at Object.get [as argv] (/Users/mim/Desktop/[ * * * ]/node_modules/yargs/yargs.js:912:21)
    at Object.<anonymous> (/Users/mim/Desktop/[ * * * ]/node_modules/electron-builder/out/cli/cli.js:151:418)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

```

**Comment by develar** [comment]
`never` it is valid for CLI param `publish`. For configuration, please use `null` to disable publish.

**Comment by islemaster** [comment]
@develar When did `never` become an invalid publish configuration?  It's still all over your docs and source code; it may be prudent to reopen this issue and use it to track clean-up.

https://github.com/electron-userland/electron-builder/blob/dd5c33ae8cc5e701379f0ab9c8228ef17aeaf2a9/docs/cli.md#L41-L44

https://github.com/electron-userland/electron-builder/blob/a202c3665139e4b0de133bf9419acd264e6bbce0/docs/configuration/publish.md#L26-L33

https://github.com/electron-userland/electron-builder/blob/fd2a1f0794d6f4ded47baa7091fe70fc1628f1b5/test/src/linux/linuxPackagerTest.ts#L88-L97

https://github.com/electron-userland/electron-builder/blob/c050b5206fc86584271644674590c31292d41f14/packages/electron-builder-lib/src/publish/PublishManager.ts#L64-L69

**Comment by develar** [comment]
@islemaster Please provide your config and your actual error stack trace.

**Comment by omeid** [comment]
How do I use "null" in JSON? if my config is part of `package.json`?

**Comment by mim-Armand** [comment]
@omeid share your config or `package.json` file,
The documentation is not very clear about it but I would suggest trying `"publish": null`,
`null` is now valid in a JSON

**Comment by m4heshd** [comment]
This is definitely misdocumented.

**Comment by rwwagner90** [comment]
100% documented incorrectly

**Comment by GuillermoFarias** [comment]
> @omeid share your config or `package.json` file, The documentation is not very clear about it but I would suggest trying `"publish": null`, `null` is now valid in a JSON

Thanks ❤️ 

<hr style="border:1px solid gray">

Problem GithubActions : `reason=CI detected`

```sh
INFO  Building app with electron-builder:
  • electron-builder  version=22.14.13 os=20.6.0
  • artifacts will be published if draft release exists  reason=CI detected
```

the correct way (works for me) : `"publish": null`
