### ISSUE TITLE
Error when npm install "electron-builder": "19.32.0"

### ISSUE THREAD

**Issue by celestale** [electron-userland/electron-builder#2155]
Version:  electron-builder@19.32.0
Target: windows 10 x64

```
module.js:529
    throw err;
    ^

Error: Cannot find module 'electron-builder/out/yarn'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\desk\Documents\projects\angular-electron\config\install-app-deps.js:3:26)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@2.2.2 postinstall: `node ./config/install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-electron@2.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**package.json**
```
"dependencies": {
    "electron-devtools-installer": "^2.2.0",
    "rxjs": "~5.4.0"
  },
  "devDependencies": {
    "@angular/animations": "^4.3.5",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/common": "^4.3.5",
    "@angular/compiler": "^4.3.5",
    "@angular/compiler-cli": "^4.3.5",
    "@angular/core": "^4.3.5",
    "@angular/forms": "^4.3.5",
    "@angular/http": "^4.3.5",
    "@angular/language-service": "^4.3.5",
    "@angular/platform-browser": "^4.3.5",
    "@angular/platform-browser-dynamic": "^4.3.5",
    "@angular/platform-server": "^4.3.5",
    "@angular/router": "^4.3.5",
    "@angularclass/conventions-loader": "^1.0.13",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.3",
    "@ngrx/router-store": "^1.2.6",
    "@ngrx/store": "^2.2.2",
    "@ngrx/store-devtools": "^3.2.4",
    "@swimlane/ngx-datatable": "10.2.3",
    "@types/chai": "^4.0.0",
    "@types/chai-as-promised": "^0.0.31",
    "@types/chart.js": "^2.6.4",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "^2.5.51",
    "@types/mocha": "^2.2.41",
    "@types/node": "^7.0.28",
    "@types/source-map": "^0.5.0",
    "@types/uglify-js": "^2.6.29",
    "@types/webdriverio": "^4.7.0",
    "@types/webpack": "^2.2.15",
    "add-asset-html-webpack-plugin": "^2.0.1",
    "angular2-template-loader": "^0.6.2",
    "assets-webpack-plugin": "^3.5.1",
    "awesome-typescript-loader": "~3.2.3",
    "chai": "^4.0.2",
    "chai-as-promised": "^7.1.1",
    "codelyzer": "~3.2.0",
    "copy-webpack-plugin": "^4.0.1",
    "core-js": "^2.4.1",
    "css-loader": "^0.28.4",
    "devtron": "^1.4.0",
    "electron": "~1.7.2",
    "electron-builder": "19.32.0",
    "electron-connect": "^0.6.1",
    "electron-connect-webpack-plugin": "^0.1.1",
    "electron-debug": "^1.1.0",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.3",
    "express": "^4.15.3",
    "extract-text-webpack-plugin": "~2.1.0",
    "file-loader": "^0.11.2",
    "find-root": "^1.0.0",
    "gh-pages": "^1.0.0",
    "html-webpack-plugin": "^2.28.0",
    "imports-loader": "^0.7.1",
    "istanbul-instrumenter-loader": "~3.0.0",
    "jasmine-core": "^2.6.2",
    "json-loader": "^0.5.4",
    "karma": "^1.7.0",
    "karma-chrome-launcher": "^2.1.1",
    "karma-coverage": "^1.1.1",
    "karma-electron": "^5.2.1",
    "karma-jasmine": "^1.1.0",
    "karma-mocha-reporter": "^2.2.3",
    "karma-remap-coverage": "^0.1.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "~2.0.3",
    "mocha": "^3.4.2",
    "ncp": "^2.0.0",
    "ng-router-loader": "^2.1.0",
    "ngc-webpack": "~2.0.0",
    "ngrx-store-freeze": "^0.1.9",
    "ngrx-store-logger": "^0.1.8",
    "node-sass": "^4.5.3",
    "npm-run-all": "^4.0.2",
    "optimize-js-plugin": "0.0.4",
    "parse5": "^3.0.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "^0.1.10",
    "rimraf": "~2.6.1",
    "sass-loader": "^6.0.5",
    "script-ext-html-webpack-plugin": "^1.8.1",
    "source-map-loader": "^0.2.1",
    "spectron": "~3.7.0",
    "string-replace-loader": "1.2.0",
    "style-loader": "^0.18.2",
    "to-string-loader": "^1.1.5",
    "ts-helpers": "1.1.2",
    "ts-node": "^3.0.6",
    "tslib": "^1.7.1",
    "tslint": "~5.7.0",
    "tslint-loader": "^3.5.3",
    "typedoc": "^0.7.1",
    "typescript": "^2.5.2",
    "url-loader": "^0.5.8",
    "v8-lazy-parse-webpack-plugin": "^0.3.0",
    "webpack": "~2.6.1",
    "webpack-dev-middleware": "^1.10.2",
    "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
    "webpack-hot-middleware": "^2.18.0",
    "webpack-md5-hash": "^0.0.5",
    "webpack-merge": "~4.1.0",
    "webpack-node-externals": "^1.6.0",
    "write-file-webpack-plugin": "^4.0.2",
    "zone.js": "~0.8.11"
  },
```
I tried to do a `npm clean` then `npm install` but still unable to bypass.

**Comment by celestale** [comment]
**FIXED:** There is something wrong with my own `install-app-deps.js`

**Comment by celestale** [comment]
**Fix found in builder-util:**

It turned out that `node_modules\builder-util` do not contain the folder `src`. Instead it contains folder `out`.

> Quoted from Error: `node_modules\builder-util\src\util.ts:200:14`.

 It is trying to access `src` folder.

Currently, I manually created the `src` folder and I was able to `run package:windows` with no problem. But what is the right way to fix this?

Current version:
```
"_from": "electron-builder@19.32.0",
 "_id": "electron-builder@19.32.0",
```

**Comment by develar** [comment]
Please remove node_modules, set electron-buidler version to `^19.34.0` and install again.
