### ISSUE TITLE
install-app-deps doesn't work for electron-spellchecker

### ISSUE THREAD

**Issue by ahallicks** [electron-userland/electron-builder#2158]
### Versions
* **Builder**: 19.34.1
* **Node**: 8.5.0
* **npm**: 5.4.2

### Target
* **Target**: Windows 10 - win32:x64

### Description
When using `electron-builder`'s `install-app-deps` it removes the `Releases` folder (created when the module is first compiled) in the `electron-spellchecker` directory, which means the spellchecker doesn't work.

I tested using `electron-rebuild` instead of the `electron-builder` native module compilation and the spellchecker package worked just fine. I'm just wondering what the one bundled with `electron-builder` does differently and why?

### Outputs
Here is the error:
```
Uncaught Error: Cannot find module '../build/Release/spellchecker.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Development\App\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Development\App\node_modules\@paulcbetts\spellchecker\lib\spellchecker.js:3:16)
    at Object.<anonymous> (C:\Development\App\node_modules\@paulcbetts\spellchecker\lib\spellchecker.js:116:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

And `package.json`:
```
{
  "name": "AppName",
  "version": "2.0.0",
  "productName": "AppName",
  "description": "AppName",
  "private": true,
  "main": "main.js",
  "scripts": {
    "postinstall": "electron-builder install-app-deps",
    "start": "set ELECTRON_ENABLE_LOGGING=true && electron ./main.js --debug --inspect"
  }
  "build": {
    "appId": "com.Company.AppName",
    "win": {
      "target": [
        "squirrel"
      ],
      "artifactName": "AppName-${version}-setup.${ext}"
    },
    "squirrelWindows": {
      "iconUrl": "https://raw.githubusercontent.com/Company/AppName/master/logo.ico?raw=true",
      "remoteReleases": "https://github.com/Company/AppName",
      "remoteToken": "..."
    },
    "mac": {
      "category": "public.app-category.productivity"
    },
    "dmg": {},
    "directories": {
      "output": "out"
    },
    "protocols": {
      "name": "AppName",
      "schemes": [
        "optimus"
      ]
    }
  },
  "dependencies": {
    "@paulcbetts/system-idle-time": "*",
    "active-win": "*",
    "electron-config": "*",
    "electron-google-analytics": "*",
    "electron-notify": "*",
    "electron-spellchecker": "*",
    "jquery": "*",
    "marked": "*",
    "moment": "*",
    "nedb": "*",
    "node-notifier": "*",
    "node-trello": "*",
    "request": "*"
  },
  "devDependencies": {
    "adm-zip": "*",
    "babel-eslint": "*",
    "babel-plugin-istanbul": "*",
    "babel-plugin-transform-class-properties": "*",
    "babel-preset-env": "*",
    "babel-preset-react": "*",
    "babel-register": "*",
    "chai": "*",
    "chai-as-promised": "*",
    "electron": "*",
    "electron-builder": "*",
    "electron-builder-squirrel-windows": "*",
    "electron-mocha": "*",
    "fs-extra": "*",
    "mocha": "*",
    "mocha-appveyor-reporter": "*",
    "mocha-testdata": "*",
    "node-fetch": "*",
    "rimraf": "*",
    "spec-xunit-file": "0.0.1-3",
    "spectron": "~3.4.0",
    "sync-request": "*"
  }
}
```

**Comment by develar** [comment]
Please latest release.
