### ISSUE TITLE
Build started to fail randomly on Travis CI

### ISSUE THREAD

**Issue by leonardorb** [electron-userland/electron-builder#2188]
I started to have failures on my Travis CI build 8 days ago, without any changes. For example, if I run the same build that passed 8 days ago, I'll get a failure now. This is my error:
```
> electron-builder
electron-builder 19.36.0
CI detected, so artifacts will be published if draft release exists
Unhandled rejection Error: Cannot download "[secure]", status 404: Not Found
    at ClientRequest.request.doRequest.response (<omitting>/node_modules/builder-util-runtime/src/httpExecutor.ts:153:18)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at TLSSocket.Readable.push (_stream_readable.js:136:10)
    at TLSWrap.onread (net.js:560:20)
From previous event:
    at CancellationToken.createPromise (<omitting>/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at <omitting>/node_modules/builder-util/src/nodeHttpExecutor.ts:23:44
From previous event:
    at NodeHttpExecutor.download (<omitting>/node_modules/builder-util/out/nodeHttpExecutor.js:141:11)
    at <omitting>/node_modules/electron-builder/src/codeSign.ts:109:28
    at Generator.next (<anonymous>)
From previous event:
    at downloadCertificate (<omitting>/node_modules/electron-builder/out/codeSign.js:96:22)
    at <omitting>/node_modules/electron-builder/src/codeSign.ts:215:36
From previous event:
    at <omitting>/node_modules/electron-builder/src/codeSign.ts:215:21
From previous event:
    at createKeychain (<omitting>/node_modules/electron-builder/out/codeSign.js:180:22)
    at new MacPackager (<omitting>/node_modules/electron-builder/src/macPackager.ts:27:12)
    at Packager.createHelper (<omitting>/node_modules/electron-builder/src/packager.ts:285:16)
    at <omitting>/node_modules/electron-builder/src/packager.ts:225:29
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (<omitting>/node_modules/electron-builder/out/packager.js:344:11)
    at <omitting>/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (<omitting>/node_modules/electron-builder/out/packager.js:263:11)
    at <omitting>/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
    at build (<omitting>/node_modules/electron-builder/out/builder.js:63:21)
    at loadEnv.then (<omitting>/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (<omitting>/node_modules/electron-builder/out/builder.js:63:21)
    at loadEnv.then (<omitting>/node_modules/electron-builder/out/cli/cli.js:155:79)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (<omitting>/node_modules/electron-builder/out/cli/cli.js:155:68)
    at Object.runCommand (<omitting>/node_modules/yargs/lib/command.js:226:22)
    at Object.parseArgs [as _parseArgs] (<omitting>/node_modules/yargs/yargs.js:998:24)
    at Object.get [as argv] (<omitting>/node_modules/yargs/yargs.js:912:21)
    at Object.<anonymous> (<omitting>/node_modules/electron-builder/out/cli/cli.js:151:418)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

This is with `electron-builder` *19.32.2* (I was testing)
```
electron-builder 19.32.2
CI detected, so artifacts will be published if draft release exists
Unhandled rejection Error: Cannot download "[secure]", status 404: Not Found
    at ClientRequest.request.doRequest.response (<omitting>/node_modules/builder-util-runtime/src/httpExecutor.ts:153:18)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at TLSSocket.Readable.push (_stream_readable.js:136:10)
    at TLSWrap.onread (net.js:560:20)
From previous event:
    at CancellationToken.createPromise (<omitting>/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at <omitting>/node_modules/builder-util/src/nodeHttpExecutor.ts:23:44
From previous event:
    at NodeHttpExecutor.download (<omitting>/node_modules/builder-util/out/nodeHttpExecutor.js:141:11)
    at <omitting>/node_modules/electron-builder/src/codeSign.ts:109:28
    at Generator.next (<anonymous>)
From previous event:
    at downloadCertificate (<omitting>/node_modules/electron-builder/out/codeSign.js:96:22)
    at <omitting>/node_modules/electron-builder/src/codeSign.ts:215:36
From previous event:
    at <omitting>/node_modules/electron-builder/src/codeSign.ts:215:21
From previous event:
    at createKeychain (<omitting>/node_modules/electron-builder/out/codeSign.js:180:22)
    at new MacPackager (<omitting>/node_modules/electron-builder/src/macPackager.ts:27:12)
    at Packager.createHelper (<omitting>/node_modules/electron-builder/src/packager.ts:285:16)
    at <omitting>/node_modules/electron-builder/src/packager.ts:225:29
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (<omitting>/node_modules/electron-builder/out/packager.js:344:11)
    at <omitting>/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (<omitting>/node_modules/electron-builder/out/packager.js:263:11)
    at <omitting>/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
    at build (<omitting>/node_modules/electron-builder/out/builder.js:63:21)
    at loadEnv.then (<omitting>/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (<omitting>/node_modules/electron-builder/out/builder.js:63:21)
    at loadEnv.then (<omitting>/node_modules/electron-builder/out/cli/cli.js:155:79)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (<omitting>/node_modules/electron-builder/out/cli/cli.js:155:68)
    at Object.runCommand (<omitting>/node_modules/yargs/lib/command.js:226:22)
    at Object.parseArgs [as _parseArgs] (<omitting>/node_modules/yargs/yargs.js:998:24)
    at Object.get [as argv] (<omitting>/node_modules/yargs/yargs.js:912:21)
    at Object.<anonymous> (<omitting>/node_modules/electron-builder/out/cli/cli.js:151:418)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

And this is the normal flow (without errors):
```
electron-builder 19.33.0
Rebuilding native production dependencies for darwin:x64
Packaging for darwin x64 using electron 1.6.11 to release/mac
Signing app (identity: ------ Developer ID Application: ------)
Building macOS zip
Building DMG
```

I was taking a look here:
https://github.com/electron-userland/electron-builder/blob/master/packages/builder-util-runtime/src/httpExecutor.ts#L153
where the error gets triggered.

Any thoughts? Btw, I don't get this error locally, so it can be something related with the CI.

**Comment by leonardorb** [comment]
My `package.json` file:

```
{
  "name": "<omitted>",
  "version": "0.0.1",
  "description": "<omitted>",
  "author": {
    "name": "<omitted>"
  },
  "repository": {
    "url": "<omitted>"
  },
  "main": "dist/main.js",
  "scripts": {
    "build": "babel src -s -D -d dist",
    "dist": "electron-builder",
    "pack": "electron-builder --dir",
    "postinstall": "electron-builder install-app-deps",
    "start": "cross-env electron -r babel-register ."
  },
  "babel": {
    "babelrc": ".babelrc"
  },
  "build": {
    "appId": "<omitted>",
    "artifactName": "${productName}.${ext}",
    "directories": {
      "output": "release"
    },
    "dmg": {
      "contents": []
    },
    "files": [
      "dist/",
      "node_modules/",
      "public/"
    ],
    "productName": "Scan",
    "publish": null
  },
  "dependencies": {
    "<omitted>": "^0.1.0",
    "<omitted>": "^0.1.0",
    "babel-cli": "^6.24.1",
    "babel-core": "^6.24.1",
    "babel-preset-electron": "^1.4.15",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.24.1",
    "electron-devtools-installer": "^2.2.0",
    "isomorphic-fetch": "^2.2.1",
    "lodash": "^4.17.4",
    "pdf-image-pack": "0.0.1",
    "prop-types": "^15.5.8",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-redux": "^5.0.4",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "redux": "^3.6.0",
    "redux-form": "^6.6.3",
    "redux-thunk": "^2.2.0",
    "uuid": "^3.1.0"
  },
  "devDependencies": {
    "asar": "^0.13.0",
    "cross-env": "^5.0.5",
    "devtron": "^1.4.0",
    "electron": "^1.7.9",
    "electron-builder": "19.32.2"
  }
}

```

**Comment by develar** [comment]
>  "asar": "^0.13.0",

Not required.

**Comment by develar** [comment]
electron-builder cannot download your code signing certificate, please check `CSC_LINK` env.

**Comment by leonardorb** [comment]
@develar thanks for the response. That was it.
A few rules got changed under a S3 Bucket and the download was failing.
If you want I can create a PR to improve the error message here and avoid confusion. Thoughts?

**Comment by develar** [comment]
> Thoughts?

👍
