### ISSUE TITLE
Packing issue

### ISSUE THREAD

**Issue by UltraDosaaf** [electron-userland/electron-builder#2189]
Some weird stuff happening with my app. I have two PCs. On the first one all packs as smooth as it can be. On the second:
```
electron-builder 19.36.0
No native production dependencies
Packaging for win32 x64 using electron 1.7.9 to build\win-unpacked
Building portable installer (x64)
Building nsis installer (x64)
Error: Cannot cleanup:

Error #1 --------------------------------------------------------------------------------
undefined

Error #2 --------------------------------------------------------------------------------
undefined
    at throwError (C:\Users\it\Desktop\-----\node_modules\builder-util\src\asyncTaskManager.ts:91:11)
    at checkErrors (C:\Users\it\Desktop\-----\node_modules\builder-util\src\asyncTaskManager.ts:54:9)
    at C:\Users\it\Desktop\-----\node_modules\builder-util\src\asyncTaskManager.ts:68:7
From previous event:
    at AsyncTaskManager.awaitTasks (C:\Users\it\Desktop\-----\node_modules\builder-util\out\asyncTaskManager.js:103:11)
    at C:\Users\it\Desktop\-----\node_modules\electron-builder\src\packager.ts:272:23
From previous event:
    at Packager.doBuild (C:\Users\it\Desktop\-----\node_modules\electron-builder\out\packager.js:344:11)
    at C:\Users\it\Desktop\-----\node_modules\electron-builder\src\packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (C:\Users\it\Desktop\-----\node_modules\electron-builder\out\packager.js:263:11)
    at C:\Users\it\Desktop\-----\node_modules\electron-builder\src\builder.ts:283:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\it\Desktop\-----\node_modules\electron-builder\out\builder.js:63:21)
    at loadEnv.then (C:\Users\it\Desktop\-----\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Object.args [as handler] (C:\Users\it\Desktop\-----\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\Users\it\Desktop\-----\node_modules\yargs\lib\command.js:226:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\it\Desktop\-----\node_modules\yargs\yargs.js:998:24)
    at Object.get [as argv] (C:\Users\it\Desktop\-----\node_modules\yargs\yargs.js:912:21)
    at Object.<anonymous> (C:\Users\it\Desktop\-----\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! test-app@3.0.1 dist: `build`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the test-app@3.0.1 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Both are win7 x64, and both has the save version of node (v8.7.0, npm v5.4.2).
Have no clue why this is keep happening...

Part of my **package.json**:
```json
   "build": {
      "productName": "My App",
      "appId": "my.app.my.app",
      "directories": {
         "output": "build"
      },
      "nsis": {
         "oneClick": false,
         "allowToChangeInstallationDirectory": true,
         "runAfterFinish": true,
         "artifactName": "${name}-${version}.${ext}",
         "createDesktopShortcut": true
      },
      "portable": {
         "artifactName": "${name}-${version}-portable.${ext}"
      },
      "win": {
         "icon": "app/i/icon.ico",
         "target": [
            "portable",
            "nsis"
         ]
      },
      "mac": {
         "category": "me.app",
         "target": [
            "zip",
            "dmg"
         ]
      }
   },
   "scripts": {
      "setup": "npm install",
      "preview": "electron .",
      "pack": "build --dir",
      "dist": "build"
   }
```

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.

**Comment by UltraDosaaf** [comment]
@develar, I put this `process.env.DEBUG=electron-builder;` into main process js. Is it correct?

**Comment by develar** [comment]
You need to set this env when do you build. On Windows please execute `set` command before executing `electron-builder`: `set DEBUG=electron-builder`

**Comment by UltraDosaaf** [comment]
Here is my log:
[debug-log.txt](https://github.com/electron-userland/electron-builder/files/1386983/debug-log.txt)

**Comment by develar** [comment]
I think obsolete now.

**Comment by UltraDosaaf** [comment]
Nope, still can't pack my app with latest builder:
[fail_2018-03.txt](https://github.com/electron-userland/electron-builder/files/1852074/fail_2018-03.txt)

**Comment by ss44** [comment]
Getting the same error in electron-builder version=20.44.4 on a recent project. 

@UltraDosaaf were you able to figure this out?
