### ISSUE TITLE
Calling autoUpdater.checkForUpdates() results in "Cannot read property 'indexOf' of null" error

### ISSUE THREAD

**Issue by arjun-g** [electron-userland/electron-builder#2191]
* **Version**: "electron-builder": "19.36.0", "electron-updater": "2.11.0"

* **Target**: Windows, Mac

When I call autoUpdater.checkForUpdates() its showing me "Cannot read property 'indexOf' of null" error. Here is the error stack,

```
Checking for update
Error: TypeError: Cannot read property 'indexOf' of null
    at Function.AppInsightsAsyncCorrelatedErrorWrapper.orig.prepareStackTrace (J:\Projects\electron-project\dist\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:155:47)
    at Function.NativeError.prepareStackTrace (J:\Projects\electron-project\dist\node_modules\applicationinsights\node_modules\zone.js\dist\zone-node.js:900:30)
    at captureStackTrace (<anonymous>)
    at J:\Projects\electron-project\dist\node_modules\bluebird-lst\node_modules\bluebird\js\release\debuggability.js:817:13
    at new CapturedTrace (J:\Projects\electron-project\dist\node_modules\bluebird-lst\node_modules\bluebird\js\release\debuggability.js:721:5)
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (J:\Projects\electron-project\dist\node_modules\bluebird-lst\node_modules\bluebird\js\release\debuggability.js:400:19)
    at new PromiseSpawn (J:\Projects\electron-project\dist\node_modules\bluebird-lst\node_modules\bluebird\js\release\generators.js:43:17)
    at J:\Projects\electron-project\dist\node_modules\bluebird-lst\node_modules\bluebird\js\release\generators.js:197:21
    at NsisUpdater.doCheckForUpdates (J:\Projects\electron-project\dist\node_modules\electron-updater\out\AppUpdater.js:329:11)
    at J:\Projects\electron-project\dist\node_modules\electron-updater\src\AppUpdater.ts:222:25
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (J:\Projects\electron-project\dist\node_modules\bluebird-lst\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (J:\Projects\electron-project\dist\node_modules\bluebird-lst\node_modules\bluebird\js\release\generators.js:97:49)
    at Async._drainQueue (J:\Projects\electron-project\dist\node_modules\bluebird-lst\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (J:\Projects\electron-project\dist\node_modules\bluebird-lst\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (J:\Projects\electron-project\dist\node_modules\bluebird-lst\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by souravm84** [comment]
Please share your code

**Comment by DominusKelvin** [comment]
Hey @arjun-g how did you resolve this issue. I think I'm having something similar right now in my app.
