### ISSUE TITLE
Cannot find module '../blake2s.js'

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#2210]
* **Version**: 19.38.0

* **Target**: Windows NSIS-Web ia32 & x64

Latest pre-release crashes in Windows when trying to create the `nsis-web` installer.

```
> build --x64 --ia32

electron-builder 19.38.0
Using electron-builder.yml configuration file
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for win32 x64 using electron 1.8.1 to dist\win-unpacked
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for win32 ia32 using electron 1.8.1 to dist\win-ia32-unpacked
Building nsis-web installer (x64 and ia32)
Error: Cannot find module '../blake2s.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\app-package-builder\src\ContentDefinedChunker.ts:80:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at _load_ContentDefinedChunker (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\app-package-builder\out\blockMap.js:214:37)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\app-package-builder\src\blockMap.ts:164:21
    at Generator.next (<anonymous>)
From previous event:
    at blocks.default.map (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\app-package-builder\out\blockMap.js:148:30)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\app-package-builder\src\blockMap.ts:163:40
    at Generator.next (<anonymous>)
From previous event:
    at doComputeBlockMap (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\app-package-builder\out\blockMap.js:183:22)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\app-package-builder\src\blockMap.ts:151:16
    at Generator.next (<anonymous>)
From previous event:
    at computeBlockMap (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\app-package-builder\out\blockMap.js:124:22)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\app-package-builder\src\blockMap.ts:37:28
From previous event:
    at createDifferentialPackage (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\app-package-builder\out\blockMap.js:51:21)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\targets\nsis\nsis.ts:91:20
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at WebInstallerTarget.buildAppPackage (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\targets\nsis\nsis.js:190:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\targets\nsis\nsisUtil.ts:32:28
    at FSReqWrap.oncomplete (fs.js:136:15)
From previous event:
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\targets\nsis\nsisUtil.ts:32:10
    at Generator.next (<anonymous>)
From previous event:
    at AppPackageHelper.packArch (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\targets\nsis\nsisUtil.js:94:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\targets\nsis\nsis.ts:177:51
    at Generator.next (<anonymous>)
From previous event:
    at default.map (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\targets\nsis\nsis.js:287:37)
From previous event:
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\targets\nsis\nsis.ts:176:29
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at WebInstallerTarget.buildInstaller (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\targets\nsis\nsis.js:337:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\targets\nsis\nsis.ts:102:18
    at Generator.next (<anonymous>)
From previous event:
    at WebInstallerTarget.finishBuild (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\targets\nsis\nsis.js:205:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\packager.ts:268:36
From previous event:
    at Packager.doBuild (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\packager.js:344:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\packager.js:263:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\builder.ts:283:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\builder.js:63:21)
    at then (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Object.args [as handler] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\lib\command.js:226:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\yargs.js:998:24)
    at Object.get [as argv] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\yargs.js:912:21)
    at Object.<anonymous> (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! media-presenter@2.4.4 dist:n: `build --x64 --ia32`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the media-presenter@2.4.4 dist:n script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\johann.rekowski\AppData\Roaming\npm-cache\_logs\2017-10-18T08_10_05_786Z-debug.log
```

**Comment by develar** [comment]
@HitomiTenshi Thanks for using pre-release versions, fixed in 19.39.0.
