### ISSUE TITLE
jaxx seems to have a lot of errors in appimage

### ISSUE THREAD

**Issue by jonnygrant** [electron-userland/electron-builder#2218]
* **Version**: 
jaxx

* **Target**: 

jonny@ubuntu1404:~/Downloads$ chmod 700 jaxx-1.3.3-x86_64.AppImage
jonny@ubuntu1404:~/Downloads$ ./jaxx-1.3.3-x86_64.AppImage
[21:57:54:0107] [info] App starting...
[21:57:54:0126] [info] Checking for update
[21:57:54:0126] [info] Checking for update...
[21:57:54:0291] [error] Error: Error: ENOENT: no such file or directory,
open '/tmp/.mount_CHUt0p/usr/bin/resources/app-update.yml'
    at
/tmp/.mount_CHUt0p/usr/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:325:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig
(/tmp/.mount_CHUt0p/usr/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:361:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator]
(/tmp/.mount_CHUt0p/usr/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:83:43)
    at Lazy.get value [as value]
(/tmp/.mount_CHUt0p/usr/bin/resources/app.asar/node_modules/electron-updater/node_modules/lazy-val/src/main.ts:18:23)
    at
/tmp/.mount_CHUt0p/usr/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:233:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates
(/tmp/.mount_CHUt0p/usr/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:11)
    at
/tmp/.mount_CHUt0p/usr/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:216:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at AppImageUpdater._checkForUpdates
(/tmp/.mount_CHUt0p/usr/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:272:11)
    at AppImageUpdater.checkForUpdates
(/tmp/.mount_CHUt0p/usr/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:165:35)
    at App.<anonymous>
(/tmp/.mount_CHUt0p/usr/bin/resources/app.asar/loadDesktop.js:110:33)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
[21:57:54:0291] [info] Error in auto-updater.
[21:57:59:0383] [info] 0

**Comment by probonopd** [comment]
@jonnygrant how can I reproduce this? When I download and execute https://jaxx.io/files/1.3.3/jaxx-1.3.3-x86_64.AppImage the application launches fine, I don't see an "update" menu entry or something like that.

@develar this appears to be related to the new differential AppImage updater?

**Comment by probonopd** [comment]
After having launched it and then just letting it run for a while, I also see these errors on the terminal:

```
me@host:~$ ./jaxx-1.3.3-x86_64.AppImage 
6122
[14:51:49:0728] [info] App starting...
[14:51:49:0752] [info] Checking for update
[14:51:49:0753] [info] Checking for update...
[14:51:49:0972] [error] Error: Error: ENOENT: no such file or directory, open '/tmp/.mount_NHupwp/usr/bin/resources/app-update.yml'
    at /tmp/.mount_NHupwp/usr/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:325:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/tmp/.mount_NHupwp/usr/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:361:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/tmp/.mount_NHupwp/usr/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:83:43)
    at Lazy.get value [as value] (/tmp/.mount_NHupwp/usr/bin/resources/app.asar/node_modules/electron-updater/node_modules/lazy-val/src/main.ts:18:23)
    at /tmp/.mount_NHupwp/usr/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:233:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/tmp/.mount_NHupwp/usr/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:11)
    at /tmp/.mount_NHupwp/usr/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:216:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/tmp/.mount_NHupwp/usr/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:272:11)
    at AppImageUpdater.checkForUpdates (/tmp/.mount_NHupwp/usr/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:165:35)
    at App.<anonymous> (/tmp/.mount_NHupwp/usr/bin/resources/app.asar/loadDesktop.js:110:33)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
[14:51:49:0973] [info] Error in auto-updater.
[14:53:03:0039] [info] 0
```

**Comment by jonnygrant** [comment]
I don't know anything about Jaxx or Appimage, so i'll leave it up to you. Not sure if jaxx or appimagine issue.

**Comment by probonopd** [comment]
I suspect this to be neither nor, but an electron-builder issue, actually.

**Comment by develar** [comment]
If you use latest electron-updater version, you must use latest electron-builder version to build your app.

**Comment by probonopd** [comment]
So @jonnygrant it is a Jaxx issue after all. If Jaxx wants to use the latest electron-updater version (as they appear to), they must use latest electron-builder version as well. Please report the issue to the Jaxx team. Thanks.

**Comment by jonnygrant** [comment]
Thank you

**Comment by jaxxThageesan** [comment]
@jonnygrant We noticed some users experiencing this issue.  Electron-updater has fixed this issue in their library a few days ago and we will be adding it to our next build.
