### ISSUE TITLE
optionalDependencies seems broken in 19.39.0+

### ISSUE THREAD

**Issue by omarkilani** [electron-userland/electron-builder#2220]
I'm using yarn v1.2.1 on macOS (in this instance).

I have an app/package.json which includes the following:

```  
"optionalDependencies": {
    "@nodert-win10/windows.data.xml.dom": "^0.2.95",
    "@nodert-win10/windows.ui.notifications": "^0.2.95"
}
```
Under electron-builder 19.38.0, this works fine on macOS (build --mac).

Under electron-builder 19.39.0 (and 19.40.0) it fails with this:

```
yarn run v1.2.1
$ build --mac
electron-builder 19.40.0
Error: Unresolved node modules: @nodert-win10/windows.data.xml.dom, @nodert-win10/windows.ui.notifications
    at [PATH]/node_modules/electron-builder/src/util/packageDependencies.ts:109:17
From previous event:
    at Collector.resolveUnresolvedHoisted ([PATH]/node_modules/electron-builder/out/util/packageDependencies.js:202:11)
    at [PATH]/node_modules/electron-builder/src/util/packageDependencies.ts:88:18
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Collector.collect ([PATH]/node_modules/electron-builder/out/util/packageDependencies.js:156:11)
    at computeDependencies ([PATH]/node_modules/electron-builder/src/util/packageDependencies.ts:51:26)
    at [PATH]/node_modules/electron-builder/src/util/packageDependencies.ts:46:28
    at Generator.next (<anonymous>)
From previous event:
    at getProductionDependencies ([PATH]/node_modules/electron-builder/out/util/packageDependencies.js:29:21)
    at Lazy ([PATH]/node_modules/electron-builder/src/util/packageDependencies.ts:40:25)
    at Lazy.get value [as value] ([PATH]/node_modules/lazy-val/src/main.ts:18:23)
    at [PATH]/node_modules/electron-builder/src/util/yarn.ts:124:81
    at Generator.next (<anonymous>)
From previous event:
    at rebuild ([PATH]/node_modules/electron-builder/out/util/yarn.js:94:22)
    at [PATH]/node_modules/electron-builder/src/util/yarn.ts:21:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at installOrRebuild ([PATH]/node_modules/electron-builder/out/util/yarn.js:32:21)
    at [PATH]/node_modules/electron-builder/src/packager.ts:338:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies ([PATH]/node_modules/electron-builder/out/packager.js:396:11)[PATH]
```

Has something changed in how this should be described in the package.json?

**Comment by sidneys** [comment]
I have the same problem with other modules (`fsevents`) which is nested optionalDependency somewhere. Had to revert to electron-builder version 19.37.2.

```bash
electron-builder 19.40.0
Error: Unresolved node modules: 7zip-bin-win, 7zip-bin-linux
    at /Users/sidneybofah/Documents/_REPOSITORY/pb-for-desktop/node_modules/electron-builder/src/util/packageDependencies.ts:109:17
From previous event:
    at Collector.resolveUnresolvedHoisted (/Users/sidneybofah/Documents/_REPOSITORY/pb-for-desktop/node_modules/electron-builder/out/util/packageDependencies.js:202:11)
    at /Users/sidneybofah/Documents/_REPOSITORY/pb-for-desktop/node_modules/electron-builder/src/util/packageDependencies.ts:88:18
From previous event:
    at Collector.collect (/Users/sidneybofah/Documents/_REPOSITORY/pb-for-desktop/node_modules/electron-builder/out/util/packageDependencies.js:156:11)
    at computeDependencies (/Users/sidneybofah/Documents/_REPOSITORY/pb-for-desktop/node_modules/electron-builder/src/util/packageDependencies.ts:51:26)
    at /Users/sidneybofah/Documents/_REPOSITORY/pb-for-desktop/node_modules/electron-builder/src/util/packageDependencies.ts:46:28
    at Generator.next (<anonymous>)
From previous event:
```

**Comment by develar** [comment]
Set env `ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true` as workaround.

**Comment by Leaking** [comment]
mark
