### ISSUE TITLE
Error: Exit code: ENOENT. spawn prlctl ENOENT - bitbucket pipelines

### ISSUE THREAD

**Issue by mavrick** [electron-userland/electron-builder#2238]
* **Version**:  19.42.2

* **Target**: win-nsis

Building win32 nsis via bitbucket pipelines

**Docker Image:**
``electronuserland/builder:wine``

**Crash Stack:**
```electron-builder 7za (896) exited with exit code 0 +372ms
  electron-builder Executing wine --version +4ms
  electron-builder wine-2.0.3
  electron-builder  +38ms
  electron-builder Executing wine /root/.cache/electron-builder/winCodeSign/winCodeSign-1.9.0/rcedit.exe /opt/atlassian/pipelines/agent/build/dist/win-unpacked/unity.exe --set-version-string FileDescription unity --set-version-string ProductName unity --set-version-string LegalCopyright Copyright © 2017 dfrag.tv --set-file-version 1.1.14 --set-product-version 1.1.14.0 --set-version-string InternalName unity --set-version-string OriginalFilename  --set-requested-execution-level highestAvailable --set-version-string CompanyName dfrag.tv --set-icon /opt/atlassian/pipelines/agent/build/static/icon/windows.ico +1ms
  electron-builder err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
  electron-builder err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
  electron-builder err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
  electron-builder err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
  electron-builder err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
  electron-builder err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
  electron-builder err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
  electron-builder err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
  electron-builder err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
  electron-builder err:mshtml:check_version Could not open VERSION file
  electron-builder err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
  electron-builder err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
  electron-builder err:mshtml:check_version Could not open VERSION file
  electron-builder Could not load wine-gecko. HTML rendering will be disabled.
  electron-builder wine: configuration in '/root/.wine' has been updated.
  electron-builder  +15s
  electron-builder Executing prlctl list -i -s name +15ms
Error: Exit code: ENOENT. spawn prlctl ENOENT
    at /opt/atlassian/pipelines/agent/build/node_modules/builder-util/src/util.ts:117:16
    at exithandler (child_process.js:278:5)
    at ChildProcess.errorhandler (child_process.js:290:5)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at exec (/opt/atlassian/pipelines/agent/build/node_modules/builder-util/src/util.ts:85:3)
    at /opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/vm/parallels.ts:8:23
    at Generator.next (<anonymous>)
From previous event:
    at parseVmList (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/out/vm/parallels.js:45:21)
    at /opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/vm/vm.ts:25:25
    at Generator.next (<anonymous>)
From previous event:
    at getWindowsVm (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/out/vm/vm.js:31:21)
    at Lazy.WinPackager.vm.Lazy (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/winPackager.ts:62:117)
    at Lazy.get value [as value] (/opt/atlassian/pipelines/agent/build/node_modules/lazy-val/src/main.ts:18:23)
    at Lazy.WinPackager.cscInfo.Lazy (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/winPackager.ts:34:22)
    at Lazy.get value [as value] (/opt/atlassian/pipelines/agent/build/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/winPackager.ts:226:40
From previous event:
    at WinPackager.sign (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/out/winPackager.js:370:11)
    at /opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/winPackager.ts:338:16
From previous event:
    at WinPackager.signAndEditResources (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/out/winPackager.js:447:11)
    at WinPackager.signApp (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/winPackager.ts:353:17)
    at /opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/platformPackager.ts:209:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at WinPackager.doPack (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/out/platformPackager.js:267:11)
    at /opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/platformPackager.ts:115:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/out/platformPackager.js:190:11)
    at /opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/out/packager.js:332:11)
    at /opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Packager.build (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/out/packager.js:261:11)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/src/builder.ts:283:40)
    at Generator.next (<anonymous>)
From previous event:
    at Object.build (/opt/atlassian/pipelines/agent/build/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/build.js:8:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by mavrick** [comment]
Worked this out, apologies. It was due to setting ``certificateSubjectName`` in the config.

**Comment by develar** [comment]
@mavrick Yes, this option supported only on Windows or using Parallels for Mac.
