### ISSUE TITLE
Error: spawn 7za ENOENT

### ISSUE THREAD

**Issue by Ortix92** [electron-userland/electron-builder#2250]
* **Version**: 19.43.3

* **Target**: Alpine Linux (from docker image `node:8.8.1-alpine`)

When I build my application on my server it works perfectly fine. Whenever I use docker (`node:8.8.1-alpine`) for my CI it fails at one of the last steps right after the checksum download:
```bash
Error: spawn /builds/rbionics/gui/ethercat-gui/node_modules/7zip-bin-linux/x64/7za ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by develar** [comment]
Please use our docker image https://www.electron.build/multi-platform-build#docker

Or install p7zip and set env USE_SYSTEM_7ZA to true if you really want to use alpine.
