### ISSUE TITLE
node_modules folder not included in the packaged Windows installer

### ISSUE THREAD

**Issue by JPaulPunzalan** [electron-userland/electron-builder#2252]
```
  "devDependencies": {
    "electron-builder": "^19.37.2",
    "electron-prebuilt": "^1.4.13"
  }
```

Building a `Windows NSIS` installer

The result of the `    "dist": "electron-builder --x64"` script does not seem to include the `node_modules` folder, resulting for the `require` code to fail.

However, when testing the app in the `win-unpacked` folder, ALL the features work smoothly.

It was validated using `mainWindow.webContents.openDevTools();` in the entry point JS file.

Below are the `dependencies` needed but are currently being left out:
```
"dependencies": {
    "chromedriver": "^2.33.1",
    "electron-log": "^2.2.9",
    "electron-updater": "^2.10.2",
    "file-saver": "^1.3.3",
    "geckodriver": "^1.9.0",
    "hammerjs": "^2.0.8",
    "iedriver": "^3.4.0",
    "jquery": "^3.2.1",
    "node-cmd": "^3.0.0",
    "path": "^0.12.7",
    "pretty": "^2.0.0",
    "pretty-js": "^0.2.0",
    "selenium-webdriver": "^3.6.0"
  }
```

Any help is appreciated. Thanks!

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.

Quick hint: if you use 2-package.json, dependencies must be in the app package.json

**Comment by JPaulPunzalan** [comment]
Based on the logs, it seems like the 3 browser drivers are **not packed** into `asar `archive? Would there be a workaround for that?

I also only see a `package.json` and a `package-lock.json` in the root project folder though. Thanks!

```
C:\Users\john.p.c.punzalan\Desktop\seleniumconverter>npm run dist

> seleniumconverter@1.0.0 dist C:\Users\john.p.c.punzalan\Desktop\seleniumconverter
> electron-builder --x64

electron-builder 19.37.2
  electron-builder Effective config:
  electron-builder {}
  electron-builder  +0ms
No native production dependencies
Packaging for win32 x64 using electron 1.4.13 to dist\win-unpacked
  electron-builder Spawning C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\node_modules\7zip-bin-win\x64\7za.exe x -bd C:\Users\john.p.c.punzalan\AppData\Local\electron\Cache\electron-v1.4.13-win32-x64.zip -aoa -oC:\Users\john.p.c.punzalan\Desktop\seleniumconverter\dist\win-unpacked +5s

7-Zip (a) 17.01 beta (x64) : Copyright (c) 1999-2017 Igor Pavlov : 2017-08-28

Scanning the drive for archives:
1 file, 54339658 bytes (52 MiB)

Extracting archive: C:\Users\john.p.c.punzalan\AppData\Local\electron\Cache\electron-v1.4.13-win32-x64.zip
--
Path = C:\Users\john.p.c.punzalan\AppData\Local\electron\Cache\electron-v1.4.13-win32-x64.zip
Type = zip
Physical Size = 54339658

Everything is Ok

Files: 74
Size:       137832472
Compressed: 54339658
  electron-builder 7za.exe (13552) exited with exit code 0 +2s
  electron-builder node_modules\chromedriver\lib\chromedriver\chromedriver.exe is not packed into asar archive - contains executable code +9s
  electron-builder node_modules\geckodriver\geckodriver.exe is not packed into asar archive - contains executable code +185ms
  electron-builder node_modules\iedriver\lib\iedriver64\IEDriverServer.exe is not packed into asar archive - contains executable code +51ms
  electron-builder Executing C:\Users\john.p.c.punzalan\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.9.0\rcedit.exe C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\dist\win-unpacked\Selenium JavaScript IDE.exe --set-version-string FileDescription Selenium JavaScript IDE --set-version-string ProductName Selenium JavaScript IDE --set-version-string LegalCopyright Copyright © 2017 John Paulo Punzalan --set-file-version 1.0.0 --set-product-version 1.0.0.0 --set-version-string InternalName Selenium JavaScript IDE --set-version-string OriginalFilename  --set-version-string CompanyName John Paulo Punzalan --set-icon C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\build\icon.ico +13s
wine&sign: 0s 830ms
Building nsis installer (x64)
  electron-builder Executing C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\node_modules\7zip-bin-win\x64\7za.exe a -bd -mx=9 -mtc=off -mtm=off -mta=off C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\dist\seleniumconverter-1.0.0-x64.nsis.7z . +897ms
  electron-builder cwd: C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\dist\win-unpacked +4ms
nsis package, x64: 97s 573ms
  electron-builder Spawning C:\Users\john.p.c.punzalan\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\Bin\makensis.exe -WX -DAPP_ID=com.electron.seleniumconverter -DAPP_GUID=18e73915-0cb0-5daf-933e-9649ed7c2e79 -DPRODUCT_NAME=Selenium JavaScript IDE -DPRODUCT_FILENAME=Selenium JavaScript IDE -DAPP_FILENAME=seleniumconverter -DAPP_DESCRIPTION=Convert Selenium IDE HTML files to JS and run it on a chosen browser -DVERSION=1.0.0 -DPROJECT_DIR=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter -DBUILD_RESOURCES_DIR=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\build -DCOMPANY_NAME=John Paulo Punzalan -DAPP_PRODUCT_FILENAME=Selenium JavaScript IDE -DMUI_ICON=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\build\icon.ico -DMUI_UNICON=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\build\icon.ico -DAPP_64=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\dist\seleniumconverter-1.0.0-x64.nsis.7z -DAPP_64_NAME=seleniumconverter-1.0.0-x64.nsis.7z -DAPP_64_HASH=C623A54C8E560A2E0CFDBA3717C8B382E324BA0D94E52220C9775A2645FE4E80645D3852374EE4686022BAACB90F420FD640F3156905448683A8BBA3EC5089C6 -DCOMPRESSION_METHOD=7z -DONE_CLICK -DRUN_AFTER_FINISH -DSHORTCUT_NAME=Selenium JavaScript IDE -DUNINSTALL_DISPLAY_NAME=Selenium JavaScript IDE 1.0.0 -DCOMPRESS=auto -DBUILD_UNINSTALLER -DUNINSTALLER_OUT_FILE=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\dist\.__uninstaller-nsis-seleniumconverter.exe -XOutFile "C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\dist\Selenium JavaScript IDE Setup 1.0.0.exe" -XVIProductVersion 1.0.0.0 -XVIAddVersionKey /LANG=1033 ProductName "Selenium JavaScript IDE" -XVIAddVersionKey /LANG=1033 ProductVersion "1.0.0" -XVIAddVersionKey /LANG=1033 LegalCopyright "Copyright © 2017 John Paulo Punzalan" -XVIAddVersionKey /LANG=1033 FileDescription "Convert Selenium IDE HTML files to JS and run it on a chosen browser" -XVIAddVersionKey /LANG=1033 FileVersion "1.0.0" -XVIAddVersionKey /LANG=1033 CompanyName "John Paulo Punzalan" -XUnicode true -XSetCompressor zlib - +2m
  electron-builder cwd: C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\node_modules\electron-builder\templates\nsis +0ms
  electron-builder makensis.exe (8164) exited with exit code 0 +1s
  electron-builder Executing C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\dist\Selenium JavaScript IDE Setup 1.0.0.exe  +0ms
  electron-builder Spawning C:\Users\john.p.c.punzalan\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\Bin\makensis.exe -WX -DAPP_ID=com.electron.seleniumconverter -DAPP_GUID=18e73915-0cb0-5daf-933e-9649ed7c2e79 -DPRODUCT_NAME=Selenium JavaScript IDE -DPRODUCT_FILENAME=Selenium JavaScript IDE -DAPP_FILENAME=seleniumconverter -DAPP_DESCRIPTION=Convert Selenium IDE HTML files to JS and run it on a chosen browser -DVERSION=1.0.0 -DPROJECT_DIR=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter -DBUILD_RESOURCES_DIR=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\build -DCOMPANY_NAME=John Paulo Punzalan -DAPP_PRODUCT_FILENAME=Selenium JavaScript IDE -DMUI_ICON=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\build\icon.ico -DMUI_UNICON=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\build\icon.ico -DAPP_64=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\dist\seleniumconverter-1.0.0-x64.nsis.7z -DAPP_64_NAME=seleniumconverter-1.0.0-x64.nsis.7z -DAPP_64_HASH=C623A54C8E560A2E0CFDBA3717C8B382E324BA0D94E52220C9775A2645FE4E80645D3852374EE4686022BAACB90F420FD640F3156905448683A8BBA3EC5089C6 -DCOMPRESSION_METHOD=7z -DONE_CLICK -DRUN_AFTER_FINISH -DSHORTCUT_NAME=Selenium JavaScript IDE -DUNINSTALL_DISPLAY_NAME=Selenium JavaScript IDE 1.0.0 -DCOMPRESS=auto -DUNINSTALLER_OUT_FILE=C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\dist\.__uninstaller-nsis-seleniumconverter.exe -XOutFile "C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\dist\Selenium JavaScript IDE Setup 1.0.0.exe" -XVIProductVersion 1.0.0.0 -XVIAddVersionKey /LANG=1033 ProductName "Selenium JavaScript IDE" -XVIAddVersionKey /LANG=1033 ProductVersion "1.0.0" -XVIAddVersionKey /LANG=1033 LegalCopyright "Copyright © 2017 John Paulo Punzalan" -XVIAddVersionKey /LANG=1033 FileDescription "Convert Selenium IDE HTML files to JS and run it on a chosen browser" -XVIAddVersionKey /LANG=1033 FileVersion "1.0.0" -XVIAddVersionKey /LANG=1033 CompanyName "John Paulo Punzalan" -XUnicode true -XSetCompressor zlib - +406ms
  electron-builder cwd: C:\Users\john.p.c.punzalan\Desktop\seleniumconverter\node_modules\electron-builder\templates\nsis +0ms
  electron-builder makensis.exe (12584) exited with exit code 0 +1s

C:\Users\john.p.c.punzalan\Desktop\seleniumconverter>
```

**Comment by develar** [comment]
Please remove `package-lock.json` and do not use npm. Please use yarn. Remove node_modules and `yarn`. After that build and provide full error message.

**Comment by JPaulPunzalan** [comment]
Log for `yarn install` command after removing `package-lock.json` and `node_modules`.

```
C:\Users\john.p.c.punzalan\Desktop\seleniumconverter>yarn install
yarn install v1.2.1
info No lockfile found.
[1/4] Resolving packages...
warning geckodriver > tar.gz@1.0.5: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
warning iedriver > rimraf > graceful-fs@1.1.14: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning iedriver > npmconf@0.0.24: this package has been reintegrated into npm and is now out of date with respect to npm
warning electron-builder > electron-download-tf > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
warning electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
[2/4] Fetching packages...
error electron-builder@19.43.3: The engine "node" is incompatible with this module. Expected version ">=6.11.4".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

C:\Users\john.p.c.punzalan\Desktop\seleniumconverter>
```

`yarn run dist` ERROR
```
C:\Users\john.p.c.punzalan\Desktop\seleniumconverter>yarn run dist
yarn run v1.2.1
$ electron-builder --x64
electron-builder 19.34.1
Installing app dependencies for win32:x64 to C:\Users\john.p.c.punzalan\Desktop\seleniumconverter
Error: C:\Program Files\nodejs\node.exe exited with code 1
Error output:
warning geckodriver > tar.gz@1.0.5: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
warning iedriver > rimraf > graceful-fs@1.1.14: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning iedriver > npmconf@0.0.24: this package has been reintegrated into npm and is now out of date with respect to npm
warning electron-builder > electron-download-tf > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
warning electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
error electron-builder@19.43.3: The engine "node" is incompatible with this module. Expected version ">=6.11.4".
error Found incompatible module

    at ChildProcess.childProcess.once.code (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\builder-util\src\util.ts:227:14)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\builder-util\src\util.ts:190:3)
    at installDependencies (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\src\util\yarn.ts:91:3)
    at C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\src\util\yarn.ts:18:11
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at installOrRebuild (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\out\util\yarn.js:34:21)
    at C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:338:7
    at next (native)
From previous event:
    at Packager.installAppDependencies (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:408:11)
    at C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:234:20
    at next (native)
From previous event:
    at Packager.doBuild (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:344:11)
    at C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:186:52
    at next (native)
From previous event:
    at Packager.build (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:263:11)
    at C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:283:40
    at next (native)
From previous event:
    at build (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\out\builder.js:63:21)
    at loadEnv.then (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\yargs\lib\command.js:226:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\yargs\yargs.js:998:24)
    at Object.get [as argv] (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\yargs\yargs.js:912:21)
    at Object.<anonymous> (C:\Users\john.p.c.punzalan\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\john.p.c.punzalan\Desktop\seleniumconverter>
```

**Comment by develar** [comment]
1. please update nodejs to 8
2. please change electron-prebuilt to electron (version 1.7.9)

**Comment by JPaulPunzalan** [comment]
I have upgraded to NodeJS v8 and built the installer successfully using `yarn`. However, the `require` syntax still does not seem to work. Kindly check the screenshot below.

![image](https://user-images.githubusercontent.com/14859857/32308793-ab754b3c-bfc2-11e7-9c01-fc4c02435669.png)

The node_modules folder still is not present as seen in the screenshot below.
![image](https://user-images.githubusercontent.com/14859857/32308876-1a6983dc-bfc3-11e7-8944-fe166834dcba.png)

**Comment by JPaulPunzalan** [comment]
Just an update..

All features **successfully work** _when_ I use the app from the `win-unpacked` folder. However, when I use the app through the built `Windows` installer using `electron-builder`, it **throws an error**, saying that the **npm package cannot be found**. The `Electron` app **revolves** around the `selenium-webdriver` npm package by the way.

Is there a workaround regarding this?

**Comment by develar** [comment]
Please `npm ls --production`

**Comment by JPaulPunzalan** [comment]
Here is the result of the `npm ls --production` command. It seems fine I think.

```
C:\Users\john.p.c.punzalan\Desktop\Initiatives\seleniumconverter>npm ls --prod
seleniumconverter@1.0.0 C:\Users\john.p.c.punzalan\Desktop\Initiatives\seleniumconverter
+-- chromedriver@2.33.2
| +-- del@3.0.0
| | +-- globby@6.1.0
| | | +-- array-union@1.0.2
| | | | `-- array-uniq@1.0.3
| | | +-- glob@7.1.2 deduped
| | | +-- object-assign@4.1.1 deduped
| | | +-- pify@2.3.0
| | | `-- pinkie-promise@2.0.1 deduped
| | +-- is-path-cwd@1.0.0
| | +-- is-path-in-cwd@1.0.0
| | | `-- is-path-inside@1.0.0
| | |   `-- path-is-inside@1.0.2
| | +-- p-map@1.2.0
| | +-- pify@3.0.0
| | `-- rimraf@2.6.2 deduped
| +-- extract-zip@1.6.6
| | +-- concat-stream@1.6.0
| | | +-- inherits@2.0.3
| | | +-- readable-stream@2.3.3 deduped
| | | `-- typedarray@0.0.6
| | +-- debug@2.6.9
| | | `-- ms@2.0.0
| | +-- mkdirp@0.5.0
| | | `-- minimist@0.0.8
| | `-- yauzl@2.4.1
| |   `-- fd-slicer@1.0.1
| |     `-- pend@1.2.0
| +-- kew@0.7.0
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| `-- request@2.83.0
|   +-- aws-sign2@0.7.0
|   +-- aws4@1.6.0
|   +-- caseless@0.12.0
|   +-- combined-stream@1.0.5
|   | `-- delayed-stream@1.0.0
|   +-- extend@3.0.1
|   +-- forever-agent@0.6.1
|   +-- form-data@2.3.1
|   | +-- asynckit@0.4.0
|   | +-- combined-stream@1.0.5 deduped
|   | `-- mime-types@2.1.17 deduped
|   +-- har-validator@5.0.3
|   | +-- ajv@5.3.0
|   | | +-- co@4.6.0
|   | | +-- fast-deep-equal@1.0.0
|   | | +-- fast-json-stable-stringify@2.0.0
|   | | `-- json-schema-traverse@0.3.1
|   | `-- har-schema@2.0.0
|   +-- hawk@6.0.2
|   | +-- boom@4.3.1
|   | | `-- hoek@4.2.0 deduped
|   | +-- cryptiles@3.1.2
|   | | `-- boom@5.2.0
|   | |   `-- hoek@4.2.0 deduped
|   | +-- hoek@4.2.0
|   | `-- sntp@2.1.0
|   |   `-- hoek@4.2.0 deduped
|   +-- http-signature@1.2.0
|   | +-- assert-plus@1.0.0
|   | +-- jsprim@1.4.1
|   | | +-- assert-plus@1.0.0 deduped
|   | | +-- extsprintf@1.3.0
|   | | +-- json-schema@0.2.3
|   | | `-- verror@1.10.0
|   | |   +-- assert-plus@1.0.0 deduped
|   | |   +-- core-util-is@1.0.2 deduped
|   | |   `-- extsprintf@1.3.0 deduped
|   | `-- sshpk@1.13.1
|   |   +-- asn1@0.2.3
|   |   +-- assert-plus@1.0.0 deduped
|   |   +-- bcrypt-pbkdf@1.0.1
|   |   | `-- tweetnacl@0.14.5 deduped
|   |   +-- dashdash@1.14.1
|   |   | `-- assert-plus@1.0.0 deduped
|   |   +-- ecc-jsbn@0.1.1
|   |   | `-- jsbn@0.1.1 deduped
|   |   +-- getpass@0.1.7
|   |   | `-- assert-plus@1.0.0 deduped
|   |   +-- jsbn@0.1.1
|   |   `-- tweetnacl@0.14.5
|   +-- is-typedarray@1.0.0
|   +-- isstream@0.1.2
|   +-- json-stringify-safe@5.0.1
|   +-- mime-types@2.1.17
|   | `-- mime-db@1.30.0
|   +-- oauth-sign@0.8.2
|   +-- performance-now@2.1.0
|   +-- qs@6.5.1
|   +-- safe-buffer@5.1.1
|   +-- stringstream@0.0.5
|   +-- tough-cookie@2.3.3
|   | `-- punycode@1.4.1
|   +-- tunnel-agent@0.6.0
|   | `-- safe-buffer@5.1.1 deduped
|   `-- uuid@3.1.0
+-- electron-log@2.2.11
+-- electron-updater@2.15.1
| +-- bluebird-lst@1.0.5
| | `-- bluebird@3.5.1
| +-- builder-util-runtime@2.5.0
| | +-- bluebird-lst@1.0.5 deduped
| | +-- debug@3.1.0
| | | `-- ms@2.0.0 deduped
| | +-- fs-extra-p@4.4.4 deduped
| | `-- sax@1.2.4
| +-- electron-is-dev@0.3.0
| +-- fs-extra-p@4.4.4
| | +-- bluebird-lst@1.0.5 deduped
| | `-- fs-extra@4.0.2
| |   +-- graceful-fs@4.1.11
| |   +-- jsonfile@4.0.0
| |   | `-- graceful-fs@4.1.11 deduped
| |   `-- universalify@0.1.1
| +-- js-yaml@3.10.0
| | +-- argparse@1.0.9
| | | `-- sprintf-js@1.0.3
| | `-- esprima@4.0.0
| +-- lazy-val@1.0.2
| +-- lodash.isequal@4.5.0
| +-- semver@5.4.1
| `-- source-map-support@0.5.0
|   `-- source-map@0.6.1
+-- file-saver@1.3.3
+-- geckodriver@1.9.0
| +-- adm-zip@0.4.7
| +-- bluebird@3.4.6
| +-- got@5.6.0
| | +-- create-error-class@3.0.2
| | | `-- capture-stack-trace@1.0.0
| | +-- duplexer2@0.1.4
| | | `-- readable-stream@2.3.3 deduped
| | +-- is-plain-obj@1.1.0
| | +-- is-redirect@1.0.0
| | +-- is-retry-allowed@1.1.0
| | +-- is-stream@1.1.0
| | +-- lowercase-keys@1.0.0
| | +-- node-status-codes@1.0.0
| | +-- object-assign@4.1.1
| | +-- parse-json@2.2.0
| | | `-- error-ex@1.3.1
| | |   `-- is-arrayish@0.2.1
| | +-- pinkie-promise@2.0.1
| | | `-- pinkie@2.0.4
| | +-- read-all-stream@3.1.0
| | | +-- pinkie-promise@2.0.1 deduped
| | | `-- readable-stream@2.3.3 deduped
| | +-- readable-stream@2.3.3
| | | +-- core-util-is@1.0.2
| | | +-- inherits@2.0.3 deduped
| | | +-- isarray@1.0.0
| | | +-- process-nextick-args@1.0.7
| | | +-- safe-buffer@5.1.1 deduped
| | | +-- string_decoder@1.0.3
| | | | `-- safe-buffer@5.1.1 deduped
| | | `-- util-deprecate@1.0.2
| | +-- timed-out@2.0.0
| | +-- unzip-response@1.0.2
| | `-- url-parse-lax@1.0.0
| |   `-- prepend-http@1.0.4
| `-- tar.gz@1.0.5
|   +-- bluebird@2.11.0
|   +-- commander@2.11.0
|   +-- fstream@1.0.11
|   | +-- graceful-fs@4.1.11 deduped
|   | +-- inherits@2.0.3 deduped
|   | +-- mkdirp@0.5.1 deduped
|   | `-- rimraf@2.6.2 deduped
|   +-- mout@0.11.1
|   `-- tar@2.2.1
|     +-- block-stream@0.0.9
|     | `-- inherits@2.0.3 deduped
|     +-- fstream@1.0.11 deduped
|     `-- inherits@2.0.3 deduped
+-- hammerjs@2.0.8
+-- iedriver@3.5.1
| +-- adm-zip@0.2.1
| +-- kew@0.1.7
| +-- md5-file@1.1.10
| +-- mkdirp@0.3.5
| +-- npmconf@0.0.24
| | +-- config-chain@1.1.11
| | | +-- ini@1.3.4
| | | `-- proto-list@1.2.4
| | +-- inherits@1.0.2
| | +-- ini@1.1.0
| | +-- mkdirp@0.3.5
| | +-- nopt@2.2.1
| | | `-- abbrev@1.1.1
| | +-- once@1.1.1
| | +-- osenv@0.0.3
| | `-- semver@1.1.4
| +-- request@2.83.0 deduped
| `-- rimraf@2.0.3
|   `-- graceful-fs@1.1.14
+-- jquery@3.2.1
+-- node-cmd@3.0.0
+-- path@0.12.7
| +-- process@0.11.10
| `-- util@0.10.3
|   `-- inherits@2.0.1
+-- pretty@2.0.0
| +-- condense-newlines@0.2.1
| | +-- extend-shallow@2.0.1 deduped
| | +-- is-whitespace@0.3.0
| | `-- kind-of@3.2.2
| |   `-- is-buffer@1.1.6
| +-- extend-shallow@2.0.1
| | `-- is-extendable@0.1.1
| `-- js-beautify@1.7.4
|   +-- config-chain@1.1.11 deduped
|   +-- editorconfig@0.13.3
|   | +-- bluebird@3.5.1 deduped
|   | +-- commander@2.11.0 deduped
|   | +-- lru-cache@3.2.0
|   | | `-- pseudomap@1.0.2
|   | +-- semver@5.4.1 deduped
|   | `-- sigmund@1.0.1
|   +-- mkdirp@0.5.1 deduped
|   `-- nopt@3.0.6
|     `-- abbrev@1.1.1 deduped
+-- pretty-js@0.2.0
| +-- complexion@0.2.0
| +-- complexion-js@0.2.0
| +-- option-parser@1.0.0
| `-- process-files@1.0.0
`-- selenium-webdriver@3.6.0
  +-- jszip@3.1.4
  | +-- core-js@2.3.0
  | +-- es6-promise@3.0.2
  | +-- lie@3.1.1
  | | `-- immediate@3.0.6
  | +-- pako@1.0.6
  | `-- readable-stream@2.0.6
  |   +-- core-util-is@1.0.2 deduped
  |   +-- inherits@2.0.3 deduped
  |   +-- isarray@1.0.0 deduped
  |   +-- process-nextick-args@1.0.7 deduped
  |   +-- string_decoder@0.10.31
  |   `-- util-deprecate@1.0.2 deduped
  +-- rimraf@2.6.2
  | `-- glob@7.1.2
  |   +-- fs.realpath@1.0.0
  |   +-- inflight@1.0.6
  |   | +-- once@1.4.0 deduped
  |   | `-- wrappy@1.0.2
  |   +-- inherits@2.0.3 deduped
  |   +-- minimatch@3.0.4
  |   | `-- brace-expansion@1.1.8
  |   |   +-- balanced-match@1.0.0
  |   |   `-- concat-map@0.0.1
  |   +-- once@1.4.0
  |   | `-- wrappy@1.0.2 deduped
  |   `-- path-is-absolute@1.0.1
  +-- tmp@0.0.30
  | `-- os-tmpdir@1.0.2
  `-- xml2js@0.4.19
    +-- sax@1.2.4 deduped
    `-- xmlbuilder@9.0.4
```

**Comment by DanielRuf** [comment]
Same here.

**Comment by DanielRuf** [comment]
Is there a reason to use yarn instead of npm?

**Comment by sethunath** [comment]
Same issue here also

**Comment by DanielRuf** [comment]
> Please remove `package-lock.json` and do not use npm. Please use yarn. Remove node_modules and `yarn`. After that build and provide full error message.

@sethunath did you try that?
