### ISSUE TITLE
BUG: ASAR Issues while building in OSX

### ISSUE THREAD

**Issue by purplekrayons** [electron-userland/electron-builder#2265]
**Environment:**
electron _v1.7.9_
electron-builder _v19.43.4_
nodejs _v6.11.5 (via nvm)_
npm _v3.10.10 (via nvm)_
Mac OSX _10.13.1 (high sierra)_

**Issue:**

When I try and build my app, with `asar=true` set in the build options, it fails. Refer to debug output. Any idea how to resolve this or further debug whats happening?

**Debug output:**
```
electron-builder 19.43.4
  electron-builder Effective config:
  electron-builder appId: com.PROJECTX.client
  electron-builder productName: PROJECTX
  electron-builder copyright: Copyright © 2017 PROJECTX
  electron-builder asar: true
  electron-builder compression: store
  electron-builder files:
  electron-builder   - dist/**/*
  electron-builder   - node_modules/**/*
  electron-builder   - package.json
  electron-builder publish: null
  electron-builder  +0ms
Rebuilding native production dependencies for darwin:x64
  electron-builder Spawning /Users/BATMAN/.nvm/versions/node/v6.11.5/bin/node /Users/BATMAN/.nvm/versions/node/v6.11.5/lib/node_modules/npm/bin/npm-cli.js rebuild zeromq@4.6.0 +8
  electron-builder cwd: /Users/BATMAN/GIT/PROJECTX +0ms

> zeromq@4.6.0 install /Users/BATMAN/GIT/PROJECTX/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/zeromq-v4.6.0-electron-v54-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/BATMAN/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.6.0-zeromq-v4.6.0-electron-v54-darwin-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /Users/BATMAN/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.6.0-zeromq-v4.6.0-electron-v54-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/BATMAN/GIT/PROJECTX/node_modules/zeromq/build/Release/zmq.node
prebuild-install info install Successfully installed prebuilt binary!

zeromq@4.6.0 /Users/BATMAN/GIT/PROJECTX/node_modules/zeromq
  electron-builder node (9527) exited with exit code 0 +4s
Packaging for darwin x64 using electron 1.7.9 to dist/mac
  electron-builder Executing unzip -oqq -d /Users/BATMAN/GIT/PROJECTX/dist/mac /Users/BATMAN/Library/Caches/electron/electron-v1.7.9-darwin-x64.zip +889ms
  electron-builder Async task error: Error: EISDIR: illegal operation on a directory, read
  electron-builder     at Error (native)
  electron-builder From previous event:
  electron-builder     at w (/Users/BATMAN/GIT/PROJECTX/node_modules/electron-builder/src/asar/asarUtil.ts:191:11)
  electron-builder     at writeStream.write (/Users/BATMAN/GIT/PROJECTX/node_modules/electron-builder/src/asar/asarUtil.ts:193:43)
  electron-builder     at afterWrite (_stream_writable.js:387:3)
  electron-builder     at onwrite (_stream_writable.js:378:7)
  electron-builder     at WritableState.onwrite (_stream_writable.js:90:5)
  electron-builder     at fs.js:2151:5
  electron-builder     at FSReqWrap.wrapper [as oncomplete] (fs.js:749:5) +3s
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
From previous event:
    at w (/Users/BATMAN/GIT/PROJECTX/node_modules/electron-builder/src/asar/asarUtil.ts:191:11)
    at writeStream.write (/Users/BATMAN/GIT/PROJECTX/node_modules/electron-builder/src/asar/asarUtil.ts:193:43)
    at afterWrite (_stream_writable.js:387:3)
    at onwrite (_stream_writable.js:378:7)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fs.js:2151:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:749:5)
```

**Attempted fixes / Noteworthy:**
[1] I have granted global read and write on every folder in that path `/Users/batman/Library/Caches/electron/`, but it had no effect.

[2] If I set asar to false, it builds successfully.

[3] As per issue #2259, someone suggested that extraFiles is failing unless from and to is defined in the build config. I removed extraFiles completely, but it still fails.

[4] As per a thread over on [StackOverflow](https://stackoverflow.com/questions/20417118/using-node-js-i-get-error-eisdir-read), **EISDIR** is an error thrown when the target of an operation is a directory, but its actually encountering something other than a directory -- which is odd. The error, as seen in the debug output simply says "Error: (native)", so im not entirely sure what the error is.

**package.json:**
```
{
  "name": "xxx",
  "productName": "xxx",
  "description": "xxx",
  "version": "1.0.0",
  "author": "xxx <hello@xxx.com>",
  "copyright": "xxx",
  "homepage": "https://xxx.com",
  "main": "dist/main.js",
  "scripts": {
    "init": "npm install",
    "start": "electron .",
    "pack": "electron-builder --dir",
    "release": "electron-builder"
  },
  "build": {
    "appId": "com.xxx.client",
    "productName": "xxx",
    "copyright": "Copyright © 2017 xxx",
    "asar": true,
    "compression": "store",
    "files": [
      "dist/**/*",
      "node_modules/**/*",
      "package.json"
    ],
    "extraFiles": [
      "zzz.app"
    ],
    "publish": null
  },
  "devDependencies": {
    "browser-sync": "^2.12.10",
    "del": "^3.0.0",
    "electron": "^1.7.6",
    "electron-builder": "^19.30.1",
    "gulp": "~3.9.0",
    "gulp-angular-filesort": "~1.1.1",
    "gulp-angular-templatecache": "~2.0.0",
    "gulp-autoprefixer": "^4.0.0",
    "gulp-concat": "^2.6.0",
    "gulp-csso": "^3.0.0",
    "gulp-filter": "^5.0.0",
    "gulp-if": "~2.0.0",
    "gulp-imagemin": "^3.2.0",
    "gulp-inject": "^4.1.0",
    "gulp-jscs": "~4.0.0",
    "gulp-jshint": "^2.0.0",
    "gulp-less": "^3.1.0",
    "gulp-load-plugins": "^1.2.4",
    "gulp-ng-annotate": "~2.0.0",
    "gulp-open": "~2.0.0",
    "gulp-plumber": "~1.1.0",
    "gulp-print": "~2.0.0",
    "gulp-pug": "~3.3.0",
    "gulp-rev": "^8.0.0",
    "gulp-rev-replace": "^0.4.3",
    "gulp-sass": "^3.1.0",
    "gulp-sourcemaps": "^2.6.0",
    "gulp-task-listing": "~1.0.0",
    "gulp-uglify": "^3.0.0",
    "gulp-useref": "^3.0.5",
    "gulp-util": "^3.0.8",
    "jshint": "^2.8.0",
    "jshint-stylish": "^2.1.0",
    "uglify-es": "^3.1.5",
    "wiredep": "^4.0.0",
    "yargs": "^8.0.2"
  },
  "engines": {
    "node": "=6.11.5"
  },
  "dependencies": {
    "electron-store": "^1.3.0",
    "request": "^2.83.0",
    "toastr": "^2.1.2",
    "zeromq": "^4.6.0"
  }
}
```

**Comment by purplekrayons** [comment]
**UPDATE**: I managed to resolve this by uninstalling electron-builder v19.43.4 and manually installing version 19.37.2 which is on my windows dev environment and working.

`npm uninstall electron-builder`
`npm install electron-builder@19.37.2`

This appears to have been the result of a recently introduced bug. Please let me know if I can provide any additional details.

**Comment by develar** [comment]
It is definitely bug. Is it possible to provide sample project to reproduce?

**Comment by develar** [comment]
19.44.1 will produce filename in the error message.

**Comment by Raidus** [comment]
Thanks for the bug fix. I had to link puppeteer to the local Chrome Canary:

``` Javascript
  const browser = await puppeteer.launch({
    headless: false,
    slowMo: 50,
    executablePath:
      '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary'
  });
```
