### ISSUE TITLE
Building 32 on 64 Linux

### ISSUE THREAD

**Issue by hovancik** [electron-userland/electron-builder#2267]
* **Version**: 
    "electron": "^1.7.9",
    "electron-builder": "^19.43.4",

* **Target**:  Linux (Debian)

I recently added dependency which needs to be rebuild and I am not able to build my 32 release on 64 linux. 

What I get is: 

```
Error: /home/conta/.nvm/versions/node/v7.9.0/bin/node exited with code 1
Output:

> @paulcbetts/system-idle-time@1.0.4 install /home/conta/stretchly/app/node_modules/@paulcbetts/system-idle-time
> node-gyp rebuild

make: Entering directory '/home/conta/stretchly/app/node_modules/@paulcbetts/system-idle-time/build'
  CXX(target) Release/obj.target/system_idle_time/src/module.o
  CXX(target) Release/obj.target/system_idle_time/src/linux/idle.o
  SOLINK_MODULE(target) Release/obj.target/system_idle_time.node
system_idle_time.target.mk:126: recipe for target 'Release/obj.target/system_idle_time.node' failed
make: Leaving directory '/home/conta/stretchly/app/node_modules/@paulcbetts/system-idle-time/build'

Error output:
/usr/bin/ld: cannot find -lX11
/usr/bin/ld: cannot find -lXext
/usr/bin/ld: cannot find -lXss
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/system_idle_time.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/conta/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.0-3-amd64
gyp ERR! command "/home/conta/.nvm/versions/node/v7.9.0/bin/node" "/home/conta/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/conta/stretchly/app/node_modules/@paulcbetts/system-idle-time
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @paulcbetts/system-idle-time@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @paulcbetts/system-idle-time@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/conta/.npm/_logs/2017-11-03T17_02_52_452Z-debug.log

    at ChildProcess.childProcess.once.code (/home/conta/stretchly/node_modules/electron-builder/node_modules/builder-util/src/util.ts:228:14)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (/home/conta/stretchly/node_modules/electron-builder/node_modules/builder-util/src/util.ts:191:3)
    at /home/conta/stretchly/node_modules/electron-builder/src/util/yarn.ts:174:5
From previous event:
    at rebuild (/home/conta/stretchly/node_modules/electron-builder/out/util/yarn.js:94:22)
    at /home/conta/stretchly/node_modules/electron-builder/src/util/yarn.ts:21:11
From previous event:
    at installOrRebuild (/home/conta/stretchly/node_modules/electron-builder/out/util/yarn.js:32:21)
    at /home/conta/stretchly/node_modules/electron-builder/src/packager.ts:338:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/home/conta/stretchly/node_modules/electron-builder/out/packager.js:396:11)
    at /home/conta/stretchly/node_modules/electron-builder/src/packager.ts:234:20
From previous event:
    at Packager.doBuild (/home/conta/stretchly/node_modules/electron-builder/out/packager.js:332:11)
    at /home/conta/stretchly/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/home/conta/stretchly/node_modules/electron-builder/out/packager.js:261:11)
    at /home/conta/stretchly/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
    at build (/home/conta/stretchly/node_modules/electron-builder/out/builder.js:63:21)
    at then (/home/conta/stretchly/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (/home/conta/stretchly/node_modules/electron-builder/out/builder.js:63:21)
    at then (/home/conta/stretchly/node_modules/electron-builder/out/cli/cli.js:127:128)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (/home/conta/stretchly/node_modules/electron-builder/out/cli/cli.js:127:117)
    at Object.runCommand (/home/conta/stretchly/node_modules/electron-builder/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/home/conta/stretchly/node_modules/electron-builder/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/conta/stretchly/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/conta/stretchly/node_modules/electron-builder/out/cli/cli.js:123:441)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

```

I guess the problem lies here: 

```
/usr/bin/ld: cannot find -lX11
/usr/bin/ld: cannot find -lXext
/usr/bin/ld: cannot find -lXss
```

Those are installed but 64 versions. Is there some lib 32 I need to install or I need to make 32 machine and build my releases from there? Or something else? 

Thanks!

**Comment by purplekrayons** [comment]
I'm really not sure if this is connected to your issue, but I am having issues with electron-builder 19.43.4. I resolved my issue by removing, and manually installing version 19.37.2.

Refer to my issue here: https://github.com/electron-userland/electron-builder/issues/2265

**Comment by develar** [comment]
See https://www.electron.build/multi-platform-build "To build app in 32 bit from a machine with 64 bit"

> sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib

**Comment by hovancik** [comment]
@develar those libs are installed. As I mentioned I was able to build 32 on 64 until recently, when I added dependency which needs to be rebuild natively ( "@paulcbetts/system-idle-time": "^1.0.4").

**Comment by hovancik** [comment]
If anyone comes here with same problem: right now I'm solving it with having 2 machines for build (32 and 64)

**Comment by akashnimare** [comment]
@hovancik what is the correct config to build for 32 bit on a 64 bit machine? I want to build the installer for both the arch on Linux.
```json
    "linux": {
      "category": "Chat;GNOME;GTK;Network;InstantMessaging",
      "target": [
        "deb",
        "zip",
        "AppImage"
      ],
      "arch": ["ia32", "x64"],
```
^^ doesn't work.

**Comment by hovancik** [comment]
What I have is this: 
```
    "linux": {
      "category": "Utility",
      "target": [
        "AppImage",
        "deb",
        "rpm",
        "freebsd",
        "pacman",
        "tar.xz"
      ]
    },
```

This worked before I added  `paulcbetts/system-idle-time`. Right now I have to build on 32 and then on 64 machine separately.

**Comment by hovancik** [comment]
Ah, and I have `npm run dist` where `"dist": "build --x64 --ia32",`

**Comment by akashnimare** [comment]
@Yeah I can build for both the arch using `build --x64 --ia32` but how do I specifically mention these arch in linux build so that I don't need to mention arch in `npm run dist`.
