### ISSUE TITLE
Puppeteer as Dependency [Error: EISDIR]

### ISSUE THREAD

**Issue by Raidus** [electron-userland/electron-builder#2273]
Hi!

My configuration

* **Versions**: 
Node: 8.2.1
NPM: 5.2.0
electron: 1.7.9
electron-builder: 19.43.4

* **Issue**: 
When adding Puppeteer as a dependency, I'll get following error message:

```
Error: EISDIR: illegal operation on a directory, read
    at w (/***/electron-quick-start/node_modules/electron-builder/src/asar/asarUtil.ts:191:11)
    at writeStream.write (***/electron-quick-start/node_modules/electron-builder/src/asar/asarUtil.ts:193:43)
    at afterWrite (_stream_writable.js:438:3)
    at onwrite (_stream_writable.js:429:7)
    at fs.js:2133:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:691:5)
```

* **Basic Example**: 
I've added a basic example to reproduce the error: https://github.com/Raidus/electron-puppeteer-quick-start

Does anybody know how to bundle puppeteer?

Kind regards

**Comment by develar** [comment]
Thanks for test project.

**Comment by develar** [comment]
Duplicates #2265
