### ISSUE TITLE
AppImage: GLib-CRITICAL **: g_ptr_array_set_size: assertion 'rarray' failed

### ISSUE THREAD

**Issue by Doccrazy** [electron-userland/electron-builder#2274]
* **Version**: 19.43.3 / 19.45.0

* **Target**: linux x64

Getting the following error on Arch when building test-app-one from the fixtures folder.

It appears to be looking for a file `testapp.appdata.xml`, which is not mentioned in the docs anywhere. Beside id and name, the auto-generated file contains only placeholders. Do I need to write this file? If yes, where should I put it in my repo?

Building worked fine with electron-builder 19.27.3, i think.

```> TestApp@1.1.0 package /home/Downloads/test-app-one
> build --publish never

electron-builder 19.45.0
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for linux x64 using electron 1.7.8 to dist/linux-unpacked
Building AppImage for arch x64
Error: Exit code: 1. Command failed: /home/.cache/electron-builder/appimage/appimage-9.0.2/linux-x64/appimagetool --runtime-file /home/.cache/electron-builder/appimage/appimage-9.0.2/runtime-x86_64 /home/Downloads/test-app-one/dist/__appimage-x64 /home/Downloads/test-app-one/dist/TestApp-1.1.0-x86_64.AppImage
End of checks
Using architecture x86_64
Deleting pre-existing .DirIcon
Creating .DirIcon symlink based on information from desktop file
WARNING: AppStream upstream metadata is missing, please consider creating it
         in usr/share/metainfo/testapp.appdata.xml
         Please see https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
         for more information.

(appstream-util:31905): GLib-CRITICAL **: g_ptr_array_set_size: assertion 'rarray' failed
AppStream template has been generated in in /home/Downloads/test-app-one/dist/__appimage-x64/usr/share/metainfo/testapp.appdata.xml, please edit it

WARNING: zsyncmake is missing, please install it if you want to use binary delta updates
WARNING: appstreamcli is missing, please install it if you want to use AppStream metadata
/home/Downloads/test-app-one/dist/__appimage-x64 should be packaged as /home/Downloads/test-app-one/dist/TestApp-1.1.0-x86_64.AppImage

End of checks
Using architecture x86_64
Deleting pre-existing .DirIcon
Creating .DirIcon symlink based on information from desktop file
WARNING: AppStream upstream metadata is missing, please consider creating it
         in usr/share/metainfo/testapp.appdata.xml
         Please see https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
         for more information.

(appstream-util:31905): GLib-CRITICAL **: g_ptr_array_set_size: assertion 'rarray' failed
AppStream template has been generated in in /home/Downloads/test-app-one/dist/__appimage-x64/usr/share/metainfo/testapp.appdata.xml, please edit it

    at /home/Downloads/test-app-one/node_modules/builder-util/src/util.ts:108:16
    at ChildProcess.exithandler (child_process.js:279:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at exec (/home/Downloads/test-app-one/node_modules/builder-util/src/util.ts:76:3)
    at /home/Downloads/test-app-one/node_modules/electron-builder/src/targets/AppImageTarget.ts:106:5
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/home/Downloads/test-app-one/node_modules/electron-builder/out/targets/AppImageTarget.js:188:11)
    at taskManager.addTask.default.map.it (/home/Downloads/test-app-one/node_modules/electron-builder/src/platformPackager.ts:120:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/Downloads/test-app-one/node_modules/electron-builder/src/platformPackager.ts:120:41)
    at /home/Downloads/test-app-one/node_modules/electron-builder/src/platformPackager.ts:116:10
From previous event:
    at LinuxPackager.pack (/home/Downloads/test-app-one/node_modules/electron-builder/out/platformPackager.js:190:11)
    at /home/Downloads/test-app-one/node_modules/electron-builder/src/packager.ts:310:24
From previous event:
    at Packager.doBuild (/home/Downloads/test-app-one/node_modules/electron-builder/out/packager.js:369:11)
    at /home/Downloads/test-app-one/node_modules/electron-builder/src/packager.ts:236:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/home/Downloads/test-app-one/node_modules/electron-builder/out/packager.js:298:11)
    at /home/Downloads/test-app-one/node_modules/electron-builder/src/builder.ts:277:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/Downloads/test-app-one/node_modules/electron-builder/out/builder.js:63:21)
    at then (/home/Downloads/test-app-one/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Object.args [as handler] (/home/Downloads/test-app-one/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/home/Downloads/test-app-one/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/home/Downloads/test-app-one/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/Downloads/test-app-one/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/Downloads/test-app-one/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! TestApp@1.1.0 package: `build --publish never`
npm ERR! Exit status 255
npm ERR! 
```

**Comment by develar** [comment]
Related to #1993

**Comment by develar** [comment]
Fixed, now `--no-appstream` is passed to disable this file generation.
