### ISSUE TITLE
TypeError: stat.isSymbolicLink is not a function

### ISSUE THREAD

**Issue by ddavidebor** [electron-userland/electron-builder#2288]
* **Version**: v19.39.0 to at leasr  v19.45.5, electron-compile '6.4.2'
* **Target**: Doesn't matter, on mac/linux even the bare bone directory does not work.

Error source: 

https://github.com/electron-userland/electron-builder/blob/d88236b715d3a899f68ae478cc7e16762def4a23/packages/electron-builder/src/asar/asarUtil.ts#L83 

A file path called "__shim.js" is processed. There is no such file anywhere in my project.
https://github.com/electron-userland/electron-compile/search?utf8=%E2%9C%93&q=shim&type= 

The source of the name is here https://github.com/electron-userland/electron-builder/blob/227d7791aa6fc7a122ef7152e2fe478f46cb64a0/packages/electron-builder/src/util/AppFileCopierHelper.ts#L120

I will try to make something to reproduce the issues

Log:
[2017-11-08T20_03_27_949Z-debug.log](https://github.com/electron-userland/electron-builder/files/1455239/2017-11-08T20_03_27_949Z-debug.log)

```
electron-builder 19.39.0
Rebuilding native production dependencies for darwin:x64
Packaging for darwin x64 using electron 1.7.8 to dist/mac
Compiling using electron-compile
TypeError: stat.isSymbolicLink is not a function
    at /Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/asar/asarUtil.ts:83:16
From previous event:
    at AsarPackager.createPackageFromFiles (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/out/asar/asarUtil.js:224:11)
    at /Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/asar/asarUtil.ts:34:52
    at next (native)
From previous event:
    at AsarPackager.pack (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/out/asar/asarUtil.js:134:11)
    at taskManager.addTask._computeFileSets.then.fileSets (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/platformPackager.ts:244:136)
From previous event:
    at MacPackager.copyAppFiles (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/platformPackager.ts:244:10)
    at /Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/platformPackager.ts:186:10
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at MacPackager.doPack (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/out/platformPackager.js:267:11)
    at /Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/macPackager.ts:87:71
    at next (native)
From previous event:
    at MacPackager.pack (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/out/macPackager.js:183:11)
    at /Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/out/packager.js:332:11)
    at /Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/packager.ts:186:52
    at next (native)
From previous event:
    at Packager.build (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/out/packager.js:261:11)
    at /Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/builder.ts:283:40
    at next (native)
From previous event:
    at build (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/out/builder.js:63:21)
    at then (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/node_modules/yargs/lib/command.js:226:22)
    at Object.parseArgs [as _parseArgs] (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/node_modules/yargs/yargs.js:998:24)
    at Object.get [as argv] (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/node_modules/yargs/yargs.js:912:21)
    at Object.<anonymous> (/Users/davidebortolami/Downloads/datalogger/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! NNGLogger@1.6.0 distpack: `build --dir`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the NNGLogger@1.6.0 distpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davidebortolami/.npm/_logs/2017-11-08T20_03_27_949Z-debug.log
```

**Comment by willyb321** [comment]
I too am getting this over at https://github.com/willyb321/media_mate - had to downgrade to a previous version (19.28.4). Happens on every OS I've tried it on (mac/win/linux).

**Comment by willyb321** [comment]
@develar Sorry to bother you, is there any update on this?

**Comment by koopa** [comment]
Same thing just happened here. It looks like `AppFileCopierHelper` inserts `__shim.js` into the main file array [without defining `isSymbolicLink`](https://github.com/electron-userland/electron-builder/blob/df07402/packages/electron-builder-lib/src/util/AppFileCopierHelper.ts#L157) for it's meta data.

**Comment by willyb321** [comment]
@koopa I did some testing, looks like you are correct, I was able to build properly by 
```diff
-  mainFileSet.metadata.set(shimPath, {isFile: () => true, isDirectory: () => false} as any)
+  mainFileSet.metadata.set(shimPath, {isFile: () => true, isDirectory: () => false, isSymbolicLink: () => false} as any)
```
to [here](https://github.com/electron-userland/electron-builder/blob/df07402/packages/electron-builder-lib/src/util/AppFileCopierHelper.ts#L157)
