### ISSUE TITLE
Cannot build NSIS target on Mac OS Sierra (10.12.6)

### ISSUE THREAD

**Issue by JohnPascololo** [electron-userland/electron-builder#2299]
* **Version**: 19.45.4

* **Target**: Windows NSIS 

Electron builder fails in creating an NSIS installer package on my machine with the following output. Any suggestions on what might be the problem here? It says it could not load a lib in a specific path, am i missing some sort of prerequisite?

```
Building nsis installer (x64)
Downloading nsis-3.0.1.13, please wait
Error: Exit code: null. Command failed: /Users/Johannes/Library/Caches/electron-builder/appimage/appimage-9.0.2/darwin/appimagetool --runtime-file /Users/Johannes/Library/Caches/electron-builder/appimage/appimage-9.0.2/runtime-x86_64 --no-appstream /Users/Johannes/Coding/AVG2/Avignon/dist/__appimage-x64 /Users/Johannes/Coding/AVG2/Avignon/dist/test-app.ui-0.1.0-x86_64.AppImage
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/Johannes/Library/Caches/electron-builder/appimage/appimage-9.0.2/darwin/appimagetool
  Reason: image not found

dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/Johannes/Library/Caches/electron-builder/appimage/appimage-9.0.2/darwin/appimagetool
  Reason: image not found

    at /Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/builder-util/src/util.ts:108:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
    at exec (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/builder-util/src/util.ts:76:3)
    at /Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/src/targets/AppImageTarget.ts:109:5
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/out/targets/AppImageTarget.js:188:11)
    at taskManager.addTask.default.map.it (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/src/platformPackager.ts:120:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/src/platformPackager.ts:120:41)
    at /Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/src/platformPackager.ts:116:10
From previous event:
    at LinuxPackager.pack (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/out/platformPackager.js:190:11)
    at /Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/src/packager.ts:310:24
From previous event:
    at Packager.doBuild (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/out/packager.js:369:11)
    at /Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/src/packager.ts:236:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/out/packager.js:298:11)
    at /Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/src/builder.ts:277:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/out/builder.js:63:21)
    at then (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/Johannes/Coding/AVG2/Avignon/TestApp.UI/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! test-app.ui@0.1.0 dist: `electron-builder -mwl`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the test-app.ui@0.1.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by develar** [comment]
10.13 is required, sorry.

**Comment by JohnPascololo** [comment]
I see! Would have been nice if electron builder would have told me so. Anyway, thanks for that ultra quick reply!

**Comment by jayhasyee** [comment]
I still have this problem. I updated mac os to 10.13, but `/usr/local/opt/gettext/lib/libintl.8.dylib` is not there. Actually the `gettext` folder is missing already.

- electron-builder: 19.46.4
- target: linux

**Comment by rvanmil** [comment]
`brew install gettext` fixed this for me.
