### ISSUE TITLE
Auto-update: random code signing issues on both Mac and Windows

### ISSUE THREAD

**Issue by TheSLX** [electron-userland/electron-builder#2309]
* **Electron-builder version**:  19.19.1

* **Electron-updater version**: 2.4.4

* **Target**: 
NSIS
DMG
ZIP
Windows and MacOS: exe and DMG installers

I'm having an issue with the auto-update functionality for both Windows and MacOS.
This has been working fine for months on the local machines and our test team. We have recently rolled out the software to some more field testers and some issues are starting to show.

The problem is that when an update is available (user manually chooses to download) the update is downloaded but not installed. When checking the logs you can see these errors

For windows: 

>[2017-11-02 21:16:23:0347] [error] Error: Error: Command failed: powershell.exe Get-AuthenticodeSignature 'C:\Users\karol\AppData\Local\Temp\up-AkLDyf\Software Setup 2.0.1425.exe' | ConvertTo-Json -Compress
> 
>     at ChildProcess.exithandler (child_process.js:217:12)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:194:7)
>     at maybeClose (internal/child_process.js:899:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> From previous event:
>     at C:\Program Files\Niko Home Control programming software\resources\app\node_modules\electron-updater\src\NsisUpdater.ts:95:12
> From previous event:
>     at NsisUpdater.verifySignature (C:\Program Files\Niko Home Control programming software\resources\app\node_modules\electron-updater\out\NsisUpdater.js:197:11)
>     at C:\Program Files\Niko Home Control programming software\resources\app\node_modules\electron-updater\src\NsisUpdater.ts:51:48
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:672:20)
>     at tryOnImmediate (timers.js:645:5)
>     at processImmediate [as _immediateCallback] (timers.js:617:5)
> From previous event:
>     at NsisUpdater.doDownloadUpdate (C:\Program Files\Niko Home Control programming software\resources\app\node_modules\electron-updater\out\NsisUpdater.js:128:11)
>     at C:\Program Files\Niko Home Control programming software\resources\app\node_modules\electron-updater\src\AppUpdater.ts:274:25
>     at Generator.next (<anonymous>)
> From previous event:
>     at NsisUpdater.downloadUpdate (C:\Program Files\Niko Home Control programming software\resources\app\node_modules\electron-updater\out\AppUpdater.js:325:11)
>     at EventEmitter.ipcMain.on (C:\Program Files\Niko Home Control programming software\resources\app\main.js:329:17)
>     at emitTwo (events.js:106:13)
>     at EventEmitter.emit (events.js:194:7)
>     at WebContents.<anonymous> (C:\Program Files\Niko Home Control programming software\resources\electron.asar\browser\api\web-contents.js:247:13)
>     at emitTwo (events.js:106:13)
>     at WebContents.emit (events.js:194:7)

(this is shown twice in the log, could be my own logging though)

For MacOS

> `[2017-11-16 19:21:34:0859] [warn] Error: Code signature at URL file:///Users/gileke/Library/Caches/be.niko.smart.configtool.ShipIt/update.YkpdUNS/Niko%20Home%20Control%20programming%20software.app/ did not pass validation: code voldoet niet aan opgegeven codevereiste(n)`

(also shown twice)
The dutch part means: code doesn't meet the required code requirements.

Now for the very strange part.
On windows, users reported this only happened once, after restarting and doing the auto-update again it works (which I can verify in the logs).
On mac I had 2 cases:
- The first had this issue until I invited him to do it next to mee, then it worked and it hasn't been broken since (also when connected to the network it initially failed on).
- The second person keeps having this issue consistently.

The windows issue occurs on Windows 10, the Mac issue happens on MacOS 10.12.6.
I can also add that I've locally tested both Windows 10 and MacOS 10.12.6 without issue.
This leads me to believe that the issue is either in networking or computer related, that however doesn't explain why a code signing issue should be shown.

I've been looking and searching and haven't found anyone else with this issue.
Could you please help on where to start looking to fix this issue?

The code signing seems to be fine as I've been doing the updates for months now without any issues on both Mac and Windows.

I can (and I will- update electron-builder to the latest version, but I'm not in the position for trial and error right now.

Thanks for reading!
If you need any more info or have some pointers for me, I'll be happy to try out.

Kind regards

**Comment by TheSLX** [comment]
I was able to reproduce this issue.
It seems such an error is also given when the tool from which you are updating isn't code signed. I assumed only the installer being downloaded needed to be signed.
I'm letting one of our problem cases test this again and I'll update if I have feedback.

Maybe the error could also indicate this?

**Comment by TheSLX** [comment]
I just had confirmation that everything works fine now that everybody has updated to a properly code signed version.
I guess it was not very clear to me that both the updating tool and the downloaded tool needed to be signed (combined with some confusion on which version was being used).
