### ISSUE TITLE
Cannot find module 'electron-download-tf'

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#2316]
* **Version**: 19.46.3

* **Target**: Windows (x64 and ia32)

```
> media-presenter@1.0.0 dist:n C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter
> build --x64 --ia32

electron-builder 19.46.3
CI detected, so artifacts will be published if draft release exists
Using electron-builder.yml configuration file
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for win32 x64 using electron 1.8.2-beta.2 to dist\win-unpacked
Error: Cannot find module 'electron-download-tf'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\src\packager\dirPackager.ts:10:84)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at _load_dirPackager (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\out\platformPackager.js:101:27)
    at C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\src\platformPackager.ts:160:27
From previous event:
    at WinPackager.doPack (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\out\platformPackager.js:267:11)
    at C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\src\platformPackager.ts:115:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\out\platformPackager.js:190:11)
    at C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\src\packager.ts:317:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:149:15)
From previous event:
    at Packager.doBuild (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\out\packager.js:386:11)
    at C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\src\packager.ts:261:52
From previous event:
    at Packager._build (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\out\packager.js:330:11)
    at C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\src\packager.ts:231:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder-lib\out\packager.js:290:11)
    at C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder\src\builder.ts:278:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder\out\builder.js:54:21)
    at build (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder\src\builder.ts:257:10)
    at then (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.args [as handler] (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\yargs\lib\command.js:228:22)
    at Object.parseArgs [as _parseArgs] (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\GitLab-Runner\Builds\f2b1d2b3\0\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

**Comment by develar** [comment]
Please `npm ls`

As workaround, you can explicitly `yarn add electron-download-tf --dev` Thanks for testing pre-reelease version.

**Comment by HitomiTenshi** [comment]
This error also happens with `19.46.2`.

`19.46.1` works fine.

`npm ls` output:
[output.txt](https://github.com/electron-userland/electron-builder/files/1491693/output.txt)

**Comment by HitomiTenshi** [comment]
`19.46.4` works again, thanks! 👍
