### ISSUE TITLE
Windows build failure with: __shim.js not under the source directory 

### ISSUE THREAD

**Issue by alexstrat** [electron-userland/electron-builder#2319]
* **Version**:  electron-builder@19.46.3 ([latest](https://yarnpkg.com/en/package/electron-builder) is 19.45.5 🤔 )

* **Target**: squirrel

On build, stack-trace:
```
Error: File "C:\Users\Alex\Documents\GitHub\browserX/__shim.js" not under the source directory "C:\Users\Alex\Documents\
GitHub\browserX"
    at getDestinationPath (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\src\util\appFileCop
ier.ts:24:15)
    at C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\src\asar\asarUtil.ts:81:71
From previous event:
    at AsarPackager.createPackageFromFiles (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\ou
t\asar\asarUtil.js:225:11)
    at C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\src\asar\asarUtil.ts:34:52
    at Generator.next (<anonymous>)
From previous event:
    at AsarPackager.pack (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\out\asar\asarUtil.js
:134:11)
    at taskManager.addTask._computeFileSets.then.fileSets (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron
-builder-lib\src\platformPackager.ts:244:136)
From previous event:
    at WinPackager.copyAppFiles (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\src\platformP
ackager.ts:244:10)
    at C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\src\platformPackager.ts:186:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at WinPackager.doPack (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\out\platformPackage
r.js:267:11)
    at C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\src\platformPackager.ts:115:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\out\platformPackager.
js:190:11)
    at C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\src\packager.ts:317:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Users\Alex\Documents\GitHub\browserX\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs
.js:56:16)
    at C:\Users\Alex\Documents\GitHub\browserX\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\out\packager.js:386:1
1)
    at C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\src\packager.ts:261:52
From previous event:
    at Packager._build (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\out\packager.js:330:11
)
    at C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\src\packager.ts:231:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Packager.build (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder-lib\out\packager.js:290:11)
    at C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder\src\builder.ts:278:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder\out\builder.js:54:21)
    at build (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder\src\builder.ts:257:10)
    at then (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.args [as handler] (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder\out\cli\cli.js:12
7:117)
    at Object.runCommand (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder\node_modules\yargs\lib\c
ommand.js:228:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder\node_modu
les\yargs\yargs.js:1041:24)
    at Object.get [as argv] (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder\node_modules\yargs\ya
rgs.js:957:21)
    at Object.<anonymous> (C:\Users\Alex\Documents\GitHub\browserX\node_modules\electron-builder\out\cli\cli.js:123:441)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by purplekrayons** [comment]
Probably something to do with the invalid path you see in the first line:

```
Error: File "C:\Users\Alex\Documents\GitHub\browserX/__shim.js" not under the source directory "C:\Users\Alex\Documents\
GitHub\browserX"
```

`GitHub\browserX/__shim.js`

You have both forward and backward slashes in there.

**Comment by AlaShiban** [comment]
I can confirm this only happens on newer versions; this doesn't repro on lets say 19.30.0

**Comment by thealexbaron** [comment]
Reverting to `19.30.0`. Ty @AlaShiban

**Comment by thealexbaron** [comment]
@AlaShiban and @purplekrayons I was able to narrow down the version that this issue originated to `19.38.0`. Release `19.37.2` does not cause this issue.

**Comment by purplekrayons** [comment]
https://github.com/electron-userland/electron-builder/commit/87896a8f720fded320f7540832c2549ec7b1eaf3

**Comment by thealexbaron** [comment]
@purplekrayons I saw this, but it's actually not the same bug, I don't think. This bug occurs when I run `npm run release`.

**Comment by thealexbaron** [comment]
Here's the full dump for version `19.47.1`

```
inlineofire@rsis-desktop MINGW64 ~/Desktop/native-scale-reader (master)
$ npm run release

> webship-scale-reader@0.0.5 release C:\Users\inlineofire\Desktop\native-scale-reader
> build

electron-builder 19.47.1
Rebuilding native production dependencies for win32:x64
Warning: "electron-squirrel-startup" dependency is not required for NSIS
Packaging for win32 x64 using electron 1.7.9 to dist\win-unpacked
Compiling using electron-compile
Error: File "C:\Users\inlineofire\Desktop\native-scale-reader/__shim.js" not under the source directory "C:\Users\inlineofire\Desktop\native-scale-reader"
    at getDestinationPath (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\src\util\appFileCopier.ts:24:15)
    at C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\src\asar\asarUtil.ts:81:71
From previous event:
    at AsarPackager.createPackageFromFiles (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\out\asar\asarUtil.js:225:11)
    at C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\src\asar\asarUtil.ts:34:52
    at Generator.next (<anonymous>)
From previous event:
    at AsarPackager.pack (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\out\asar\asarUtil.js:134:11)
    at taskManager.addTask._computeFileSets.then.fileSets (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\src\platformPackager.ts:244:136)
From previous event:
    at WinPackager.copyAppFiles (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\src\platformPackager.ts:244:10)
    at C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\src\platformPackager.ts:186:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\out\platformPackager.js:272:11)
    at C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\src\platformPackager.ts:115:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\out\platformPackager.js:195:11)
    at C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\src\packager.ts:345:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\out\packager.js:407:11)
    at C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\src\packager.ts:289:52
From previous event:
    at Packager._build (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\out\packager.js:351:11)
    at C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\src\packager.ts:259:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder-lib\out\packager.js:311:11)
    at C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder\src\builder.ts:287:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder\out\builder.js:61:21)
    at build (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder\src\builder.ts:257:10)
    at then (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder\node_modules\yargs\lib\command.js:228:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\inlineofire\Desktop\native-scale-reader\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webship-scale-reader@0.0.5 release: `build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webship-scale-reader@0.0.5 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\inlineofire\AppData\Roaming\npm-cache\_logs\2017-12-04T19_14_00_793Z-debug.log
```

**Comment by thealexbaron** [comment]
erict from the #general channel on slack says he was able to work around this issue: https://electron-builder.slack.com/archives/C3X4YCA14/p1501876607014224

**Comment by Megajin** [comment]
Are there any news on the issue? I did run into the same problem.

> erict from the #general channel on slack says he was able to work around this issue: https://electron-builder.slack.com/archives/C3X4YCA14/p1501876607014224
(actually, I think this may be related to the startup bug, not the build bug)

@thealexbaron could you, or somebody else please post the workaround? I am not able to see the site, since I'm not allowed without registration somehow.

However I am starting to think that this is an issue with `electron-compile` since the error shows up after this message: `compiling using electron-compile`

**Comment by thealexbaron** [comment]
@Megajin I actually ended up just manually defining my babel presets/plugins in a webpack config.

**Comment by Megajin** [comment]
Guys, it did work for me once I turned `asar: true` into this `asar: false`.
