### ISSUE TITLE
Unable to build distributable releases

### ISSUE THREAD

**Issue by ArekSredzki** [electron-userland/electron-builder#233]
Hi everyone, I only just now switched from `electron-complete-builder` to this, but I'm running into issues.

I'm running the latest release of OS X.

`build -d --platform darwin`: 
```
Packaging app for platform darwin x64 using electron v0.36.11
App is not signed: CSC_LINK or CSC_NAME are not specified
Creating DMG
Creating ZIP for Squirrel.Mac
Error: spawn zip ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
```

`build -d --platform win32`:
```
Removing snip/dist/win-x64
Packaging app for platform win32 x64 using electron v0.36.11
Unhandled rejection Error: Failed with exit code: 1
Output:
Attempting to build package from 'dbj-editor.nuspec'.
File not found: 'icudtl.dat'.

    at ChildProcess.<anonymous> (snip/node_modules/electron-winstaller-fixed/lib/spawn-promise.js:59:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
From previous event:
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.createWindowsInstaller (snip/node_modules/electron-winstaller-fixed/lib/index.js:204:16)
    at WinPackager.<anonymous> (snip/node_modules/electron-builder/src/winPackager.ts:115:50)
    at [object Generator].next (native)
From previous event:
    at tsAwaiter (snip/node_modules/electron-builder/src/awaiter.ts:10:51)
    at Object.build (snip/node_modules/electron-builder/src/builder.ts:30:55)
    at Object.<anonymous> (snip/node_modules/electron-builder/src/build-cli.ts:41:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

Error: Failed with exit code: 1
Output:
Attempting to build package from 'dbj-editor.nuspec'.
File not found: 'icudtl.dat'.
```

`build -d --platform linux`:
```
Packaging app for platform linux x64 using electron v0.36.11
Error: Command failed: fpm -s dir -t deb --architecture i386 --rpm-os linux --name dbj-editor --force --after-install /var/folders/8m/j1qc7x3d47v5lwjbhj83my912k46xh/T/electron-builder-67809h2UhRtQpTOO2/after-install --after-remove /var/folders/8m/j1qc7x3d47v5lwjbhj83my912k46xh/T/electron-builder-67809h2UhRtQpTOO2/after-remove --description An interactive desktop application for editing and visualizing DBJ data. --maintainer Tesla Motors <firmware-infrastructure-team@teslamotors.com> --version 0.1.0 --package <megasnip>
```

Thanks for your help

**Comment by develar** [comment]
Please provide the full logs in the future.

> Error: spawn zip ENOENT

Do you build on OS X? You can dist [only on OS X](https://github.com/loopline-systems/electron-builder/blob/master/docs/multi-platform-build.md#multi-platform-build).

> File not found: 'icudtl.dat'

Maybe it is a new electron issue (I mean unsupported), I will check, in any case please provide full log and electron-builder version.

> Error: Command failed: fpm

Please see https://github.com/loopline-systems/electron-builder/blob/master/docs/multi-platform-build.md#multi-platform-build about required system packages.

**Comment by valaxy** [comment]
The same problem appears in windows too.
After some digging, I found that:
What `File not found: 'icudtl.dat'`'s meaning is `File not found: snip/dist/win-ia32` in fact.
So, if you build to x64 and x64 only without ia32, the error happens

**Comment by develar** [comment]
Please try [3.0.0](https://github.com/electron-userland/electron-builder/releases/tag/v3.0.0) (`next` version). Please be aware of breaking changes (see release notes).
