### ISSUE TITLE
ERR unable to publish Linux target on s3

### ISSUE THREAD

**Issue by sProject** [electron-userland/electron-builder#2332]
* **electron-builder 19.46.4**: 

* **Linux, Fedora 27**: 

I've configured everything from the [docs](https://www.electron.build/configuration/publish) and set this [policy](https://github.com/electron-userland/electron-builder/issues/1618#issuecomment-314679128). Here is my [package.json](https://github.com/sProject/electron-updater-example/blob/master/package.json). I'm using a fork from the official docs. Here is my [log](https://drive.google.com/a/intouch.com/file/d/1OGjbOmZyVRfds4zy5tCE4hjcc5KhaGl7/view?usp=sharing) file

**Comment by purplekrayons** [comment]
Please post your log file -- that requires permissions to view.

**Comment by sProject** [comment]
```[fedora@localhost electron-updater-example]$ yarn pub
yarn run v1.3.2
$ electron-builder -p always
electron-builder 19.46.4
  electron-builder Effective config:
  electron-builder appId: this.app.id
  electron-builder publish:
  electron-builder   - provider: s3
  electron-builder     bucket: electron-bucket
  electron-builder  +0ms
No native production dependencies
Packaging for linux x64 using electron 1.7.9 to dist/linux-unpacked
  electron-builder Spawning /home/fedora/intouch/electron-updater-example/node_modules/7zip-bin-linux/x64/7za x -bd /home/fedora/.cache/electron/electron-v1.7.9-linux-x64.zip -aoa -o/home/fedora/intouch/electron-updater-example/dist/linux-unpacked +3s

7-Zip (a) [64] 15.14 : Copyright (c) 1999-2015 Igor Pavlov : 2015-12-31
p7zip Version 15.14.1 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,1 CPU Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (40661),ASM,AES-NI)

Scanning the drive for archives:
1 file, 51242189 bytes (49 MiB)

Extracting archive: /home/fedora/.cache/electron/electron-v1.7.9-linux-x64.zip
--
Path = /home/fedora/.cache/electron/electron-v1.7.9-linux-x64.zip
Type = zip
Physical Size = 51242189

Everything is Ok

Files: 71
Size:       134212644
Compressed: 51242189
  electron-builder 7za (19276) exited with exit code 0 +2s
Building AppImage for arch x64
  electron-builder Executing cp -d --recursive --preserve=mode --link /home/fedora/intouch/electron-updater-example/dist/linux-unpacked/ /home/fedora/intouch/electron-updater-example/dist/__appimage-x64/app/ +912ms
⚠️  Application icon is not set, default Electron icon will be used
⚠️  Application category is not set for Linux (linux.category).
Please see https://electron.build/configuration/configuration#LinuxBuildOptions-category
  electron-builder Copying /home/fedora/.cache/electron-builder/appimage/appimage-9.0.3/lib/x86_64-linux-gnu to /home/fedora/intouch/electron-updater-example/dist/__appimage-x64/usr/lib using hard links +364ms
  electron-builder Executing /home/fedora/.cache/electron-builder/appimage/appimage-9.0.3/linux-x64/appimagetool --runtime-file /home/fedora/.cache/electron-builder/appimage/appimage-9.0.3/runtime-x86_64 --no-appstream --verbose /home/fedora/intouch/electron-updater-example/dist/__appimage-x64 /home/fedora/intouch/electron-updater-example/dist/app-0.9.74-x86_64.AppImage +30ms
  electron-builder env: {
  electron-builder   "PATH": "/home/fedora/.cache/electron-builder/appimage/appimage-9.0.3/linux-x64:/home/fedora/intouch/electron-updater-example/node_modules/.bin:/home/fedora/.config/yarn/link/node_modules/.bin:/home/fedora/intouch/electron-updater-example/node_modules/.bin:/home/fedora/.config/yarn/link/node_modules/.bin:/home/fedora/.yarn/bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/fedora/.local/bin:/home/fedora/bin",
  electron-builder   "ARCH": "x86_64"
  electron-builder } +0ms
  electron-builder Name: app
  electron-builder Icon: app
  electron-builder Exec: AppRun
  electron-builder Comment: electron-updater example project
  electron-builder Type: Application
  electron-builder Categories: Utility;
  electron-builder Environmental variable ARCH used for determining architecture x86_64
  electron-builder Using architecture x86_64
  electron-builder App name for filename: app
  electron-builder Deleting pre-existing .DirIcon
  electron-builder Creating .DirIcon symlink based on information from desktop file
  electron-builder Generating squashfs...
  electron-builder Embedding ELF...
  electron-builder Marking the AppImage as executable...
  electron-builder Success
  electron-builder
  electron-builder Please consider submitting your AppImage to AppImageHub, the crowd-sourced
  electron-builder central directory of available AppImages, by opening a pull request
  electron-builder at https://github.com/AppImage/appimage.github.io
  electron-builder  +23s
  electron-builder WARNING: zsyncmake is missing, please install it if you want to use binary delta updates
  electron-builder Parallel mksquashfs: Using 1 processor
  electron-builder Creating 4.0 filesystem on /home/fedora/intouch/electron-updater-example/dist/app-0.9.74-x86_64.AppImage, block size 131072.
[=============================================================-] 1125/1125 100%
  electron-builder
  electron-builder Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
  electron-builder 	compressed data, compressed metadata, compressed fragments, compressed xattrs
  electron-builder 	duplicates are removed
  electron-builder Filesystem size 51270.77 Kbytes (50.07 Mbytes)
  electron-builder 	38.22% of uncompressed filesystem size (134159.93 Kbytes)
  electron-builder Inode table size 4416 bytes (4.31 Kbytes)
  electron-builder 	43.35% of uncompressed inode table size (10187 bytes)
  electron-builder Directory table size 1132 bytes (1.11 Kbytes)
  electron-builder 	51.60% of uncompressed directory table size (2194 bytes)
  electron-builder Xattr table size 75 bytes (0.07 Kbytes)
  electron-builder 	68.81% of uncompressed xattr table size (109 bytes)
  electron-builder Number of duplicate files found 0
  electron-builder Number of inodes 114
  electron-builder Number of files 87
  electron-builder Number of fragments 6
  electron-builder Number of symbolic links  2
  electron-builder Number of device nodes 0
  electron-builder Number of fifo nodes 0
  electron-builder Number of socket nodes 0
  electron-builder Number of directories 25
  electron-builder Number of ids (unique uids + gids) 1
  electron-builder Number of uids 1
  electron-builder 	root (0)
  electron-builder Number of gids 1
  electron-builder 	root (0)
  electron-builder Desktop file: /home/fedora/intouch/electron-updater-example/dist/__appimage-x64/app.desktop
  electron-builder /home/fedora/intouch/electron-updater-example/dist/__appimage-x64 should be packaged as /home/fedora/intouch/electron-updater-example/dist/app-0.9.74-x86_64.AppImage
  electron-builder Size of the embedded runtime: 100024 bytes
  electron-builder  +6ms
Publishing to S3 (bucket: electron-bucket)
  electron-builder Async task error: RequestTimeTooSkewed: The difference between the request time and the current time is too large.
  electron-builder     at Request.extractError (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/services/s3.js:577:35)
  electron-builder     at Request.callListeners (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
  electron-builder     at Request.emit (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
  electron-builder     at Request.emit (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:683:14)
  electron-builder     at Request.transition (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:22:10)
  electron-builder     at AcceptorStateMachine.runTo (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/state_machine.js:14:12)
  electron-builder     at /home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/state_machine.js:26:10
  electron-builder     at Request.<anonymous> (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:38:9)
  electron-builder     at Request.<anonymous> (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:685:12)
  electron-builder     at Request.callListeners (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  electron-builder     at Request.emit (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
  electron-builder     at Request.emit (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:683:14)
  electron-builder     at Request.transition (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:22:10)
  electron-builder     at AcceptorStateMachine.runTo (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/state_machine.js:14:12)
  electron-builder     at /home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/state_machine.js:26:10
  electron-builder     at Request.<anonymous> (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:38:9)
  electron-builder From previous event:
  electron-builder     at Request.promise (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:777:12)
  electron-builder     at /home/fedora/intouch/electron-updater-example/node_modules/electron-publisher-s3/src/uploader.ts:80:92
  electron-builder     at Timeout.tryRun [as _onTimeout] (/home/fedora/intouch/electron-updater-example/node_modules/electron-publisher-s3/src/uploader.ts:190:9)
  electron-builder     at ontimeout (timers.js:475:11)
  electron-builder     at tryOnTimeout (timers.js:310:5)
  electron-builder     at Timer.listOnTimeout (timers.js:270:5) +6s
RequestTimeTooSkewed: The difference between the request time and the current time is too large.
    at Request.extractError (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:38:9)
From previous event:
    at Request.promise (/home/fedora/intouch/electron-updater-example/node_modules/aws-sdk/lib/request.js:777:12)
    at /home/fedora/intouch/electron-updater-example/node_modules/electron-publisher-s3/src/uploader.ts:80:92
    at Timeout.tryRun [as _onTimeout] (/home/fedora/intouch/electron-updater-example/node_modules/electron-publisher-s3/src/uploader.ts:190:9)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
Cannot delete temporary "/tmp": Error: EACCES: permission denied, rmdir '/tmp'
    at Object.fs.rmdirSync (fs.js:846:18)
    at rmdirSync (/home/fedora/intouch/electron-updater-example/node_modules/fs-extra/lib/remove/rimraf.js:276:13)
    at rimrafSync (/home/fedora/intouch/electron-updater-example/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at callback (/home/fedora/intouch/electron-updater-example/node_modules/temp-file/src/main.ts:53:9)
    at runHook (/home/fedora/intouch/electron-updater-example/node_modules/async-exit-hook/index.js:56:10)
    at Array.map (<anonymous>)
    at exit (/home/fedora/intouch/electron-updater-example/node_modules/async-exit-hook/index.js:71:8)
    at process.events.(anonymous function) (/home/fedora/intouch/electron-updater-example/node_modules/async-exit-hook/index.js:116:3)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.emit (/home/fedora/intouch/electron-updater-example/node_modules/source-map-support/source-map-support.js:439:21)
    at process.exit (internal/process.js:157:15)
    at printErrorAndExit (/home/fedora/intouch/electron-updater-example/node_modules/builder-util/src/promise.ts:5:11)
    at tryCatcher (/home/fedora/intouch/electron-updater-example/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/fedora/intouch/electron-updater-example/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/fedora/intouch/electron-updater-example/node_modules/bluebird/js/release/promise.js:569:18)
error Command failed with exit code 1.
```
here it is

**Comment by purplekrayons** [comment]
S3 uses NTP to maintain accurate system clocks. It would appear your client machine’s clock is out of sync with the Amazon time and so the upload is failing.

**Comment by sProject** [comment]
huh, that is correct i'm running a fedora VM on my mac. Let me try and fix this and come back to you.

In the meantime do you have any idea why my linux based app keeps failing on update [ref](https://github.com/electron-userland/electron-builder/issues/2317) last commect.

Thanks in advance

**Comment by purplekrayons** [comment]
Your linux based app is being built successfully. Where things fail, is at the point it tries to publish to S3. The reason it is failing to publish (upload) to S3 is because the system time in your VM is wrong.

`RequestTimeTooSkewed: The difference between the request time and the current time is too large.`

You need to properly configure the system time in your VM. The link I posted previously, describes how to update your system time, and ensure it remains up-to-date.

**Comment by sProject** [comment]
You are awesome! I saw the log and I saw the message but it never clicked in my head that amazon can be checking unsync clock.

And now I'm even one step further on auto updating. Here is my app[app](https://s3-eu-west-1.amazonaws.com/electron-bucket/releases/app-0.9.74-x86_64.AppImage), one version before the latest and now it seems to be downloading the latest version. 

Thank you!

Now the remaining challenge is - how do I start the new app on linux and how to do staged rollout of the app. If you can point me in the right direction you'll be the hero of the day! 😄

**Comment by purplekrayons** [comment]
Sorry, I dont actually use Fedora so I can't test your application. I'm also not sure what you mean by 'start the new app on linux'. Please check out the docs for [Staged Rollouts](https://www.electron.build/auto-update#staged-rollouts). It requires you to manually update your `latest-linux.yml` with:

```
stagingPercentage
```

If you want to roll out your latest version to only half of your user-base, then you'd append the following to the bottom of your `latest-linux.yml` file:

```
stagingPercentage: 50
```

**Comment by sProject** [comment]
Thanks this explanation helps a lot!

So right now the app name is `app-0.9.74-x86_64.AppImage`, where `0.9.74` is the version and the newly downloaded app will be `0.9.75`. So the challenge is what mechanism do I use to start the new app. Shouldn't it be a constant name for my app, and if it should how do I configure that?

**Comment by purplekrayons** [comment]
Sorry, still don't really follow you. You shouldn't have to worry about the application name.

In your `main.js` file, you need to include:

```
const autoUpdater = require('electron-updater').autoUpdater;
autoUpdater.checkForUpdatesAndNotify();
```

When a user launches your application, it will check for an update (by looking at your `latest-linux.yml` file. If the version is greater in your `.yml` file, than the version the user is running, it will automatically download the updated version in the background and then notify the user that an update is available and to restart to install it.

While I can't say what that process would look like on a linux machine, this is what that looks like in windows:

![screenshot 68](https://user-images.githubusercontent.com/9218035/33219559-e15e5702-d110-11e7-9cd9-173fa7d649eb.png)

**Comment by sProject** [comment]
If I use github I see that notification but not when I use s3. I'll try and do screencast to demonstrate it. Hopefully i'll be able to do that in the next hour or two.

You've been of great help so far!

**Comment by purplekrayons** [comment]
Be sure that your bucket is publicly accessible and you are setting the appropriate acl config:

```
"publish": {
      "provider": "s3",
      "bucket": "yourBucketName",
      "path": "your/path/to/whatever/folder",
      "acl": "public-read"
    }
```

**Comment by sProject** [comment]
Hi @purplekrayons sorry for the deplay [here](https://www.youtube.com/watch?v=7x0nkrgdYg0&feature=youtu.be) is a youtube screencast of my VM. Unfortunately have removed annotations so I'll try and explain it here. There are 3 things that I want to show you in this video and [here](https://github.com/sProject/electron-updater-example) is the project:
1. **Events not triggered** - in my [main.js](https://github.com/sProject/electron-updater-example/blob/master/main.js) file I put printing messages for all the events that may happen while auto update is doing its magic. So when I start `v0.9.76` I expect to see the following events firing: `checking-for-update`, `update-available`, `download-progress`, `update-downloaded`, in this order, as I know that there is an update - `v0.9.77`. However, you can see in the video that only `update-downloaded` seems to be firing. Also later in the video when I successfully download and start the new update I expect to see the messages from `checking-for-update` and `update-not-available`, but neither of these events are fired.
1. **Successfully failed download** - versions `76` & `77` are the same but their version number. Now notice in the video how the 1st time I download `77` its file size is `52.2MB` - it is supposed to be as big as `76` (52.7MB). Sometimes the download is 0 bytes, sometimes is a few kb, sometimes is a few MB. And every time it says `update-downloaded` rather than firing `error` event.
1. **Update is a separate file** - as you can see the new version is downloaded in the same folder under its version name and when I use s3 there is no system notification while the one that you screenshot (however there is one when I used github). So I wonder how to proceed forward.

Thanks in advance and let me know if I can assist in any other way.

**Comment by purplekrayons** [comment]
Tricky indeed. I never actually noticed this until now -- but check out the [docs](https://www.electron.build/auto-update#module_electron-updater.AppUpdater+checkForUpdates) related to the eventEmitter.

`appUpdater.checkForUpdatesAndNotify() ⇒ Promise< | UpdateCheckResult>`

It would appear that `checkForUpdatesAndNotify()` will either return a promise, **OR** update the check result -- not both.

`checkForUpdates()` on the other hand, will update the check result. If you use `checkForUpdates()`, you'll find that your various listeners work.

Keep in mind, this means you will have to manually handle all events. But in my opinion, thats probably the better way to go anyways.

**Comment by sProject** [comment]
Thanks @purplekrayons I'll start digging and figuring things out and I'll report back. Hopefully @develar will be able to join us soon

**Comment by develar** [comment]
@purplekrayons Thanks a lot for your assistance.

1. Do not use VM to build Linux targets.
2. If your host platform is not able to build Linux targets — use our Docker images.
3. In 2 days we will launch free service to build Electron App on any platform for any platform. At first, for Linux ;)

I will close issue — auto-update please discuss in another issue ;)

auto-update — you or wait when #2200 will be fixed, or just use `autoUpdater.checkForUpdatesAndNotify()` without custom calls to quitAndInstall.
