### ISSUE TITLE
Issue with computer going to sleep and never checking for updates again?

### ISSUE THREAD

**Issue by mastergberry** [electron-userland/electron-builder#2333]
* **Version**: 15.4.4

* **Target**: nsis

This is from an older build, but it's something  I just want to understand more about. I put my computer to sleep with our client running. I turned back on my computer and it never checked for updates again because of the stack trace below.

Shouldn't this be covered/handled so that it continues to check for updates when our setInterval is setup?

```
08:12:55:0465 Checking for update
08:12:55:0466 checking-for-update
08:12:55:0492 Error: Error: net::ERR_NETWORK_IO_SUSPENDED
    at Error (native)
From previous event:
    at ElectronHttpExecutor.doApiRequest (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\src\electronHttpExecutor.ts:45:30)
    at ElectronHttpExecutor.request (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\node_modules\electron-builder-http\src\httpExecutor.ts:77:17)
    at request (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\node_modules\electron-builder-http\src\httpExecutor.ts:211:38)
    at C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\src\GenericProvider.ts:31:22
    at next (<anonymous>)
From previous event:
    at GenericProvider.getLatestVersion (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\out\GenericProvider.js:80:11)
    at C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:152:38
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:225:11)
    at C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:137:25
    at next (<anonymous>)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:181:11)
    at NsisUpdater.checkForUpdates (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:119:35)
    at Object.exports.checkForUpdates (C:\Program Files\Client\resources\app.asar\app\src\background.js:338:45)
    at callFunction (C:\Program Files\Client\resources\electron.asar\browser\rpc-server.js:227:18)
    at EventEmitter.<anonymous> (C:\Program Files\Client\resources\electron.asar\browser\rpc-server.js:342:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Program Files\Client\resources\electron.asar\browser\api\web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
08:12:55:0492 auto-updater-error
08:12:55:0492 Error: net::ERR_NETWORK_IO_SUSPENDED
    at Error (native)
From previous event:
    at ElectronHttpExecutor.doApiRequest (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\src\electronHttpExecutor.ts:45:30)
    at ElectronHttpExecutor.request (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\node_modules\electron-builder-http\src\httpExecutor.ts:77:17)
    at request (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\node_modules\electron-builder-http\src\httpExecutor.ts:211:38)
    at C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\src\GenericProvider.ts:31:22
    at next (<anonymous>)
From previous event:
    at GenericProvider.getLatestVersion (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\out\GenericProvider.js:80:11)
    at C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:152:38
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:225:11)
    at C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:137:25
    at next (<anonymous>)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:181:11)
    at NsisUpdater.checkForUpdates (C:\Program Files\Client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:119:35)
    at Object.exports.checkForUpdates (C:\Program Files\Client\resources\app.asar\app\src\background.js:338:45)
    at callFunction (C:\Program Files\Client\resources\electron.asar\browser\rpc-server.js:227:18)
    at EventEmitter.<anonymous> (C:\Program Files\Client\resources\electron.asar\browser\rpc-server.js:342:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Program Files\Client\resources\electron.asar\browser\api\web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by nbcnc** [comment]
Have you tried Power Save Blocker?

https://github.com/electron/electron/blob/master/docs/api/power-save-blocker.md

**Comment by mastergberry** [comment]
This wouldn't make sense for us. We don't want to stop the system from going to sleep, we just want to ensure that if fails gracefully with the update requests and then when the network is resumed and available again that it retries properly
