### ISSUE TITLE
`build -p always` throw `hdiutil` error 

### ISSUE THREAD

**Issue by cPhost** [electron-userland/electron-builder#2336]
* **Version**: 19.46.6

* **Target**: Mac

<details>
<summary>Error Output</summary>
<pre>
Error: hdiutil exited with code 1
Error output:
hdiutil: create failed - no mountable file systems
    at ChildProcess.childProcess.once.code (/Users/3020246/Downloads/test-app/node_modules/builder-util/src/util.ts:220:14)
    at Object.onceWrapper (events.js:254:19)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
From previous event:
    at spawn (/Users/3020246/Downloads/test-app/node_modules/builder-util/src/util.ts:183:3)
    at /Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/src/targets/dmg.ts:255:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at createStageDmg (/Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/out/targets/dmg.js:30:21)
    at /Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/src/targets/dmg.ts:31:27
    at Generator.next (<anonymous>)
    at LOOP (fs.js:1780:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at DmgTarget.build (/Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/out/targets/dmg.js:278:11)
    at taskManager.addTask.default.map.it (/Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/src/platformPackager.ts:120:85)
From previous event:
    at MacPackager.packageInDistributableFormat (/Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/src/platformPackager.ts:120:41)
    at /Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/src/macPackager.ts:97:26
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at /Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/src/macPackager.ts:97:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/out/macPackager.js:200:11)
    at /Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/src/packager.ts:326:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/Users/3020246/Downloads/test-app/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:149:15)
From previous event:
    at Packager.doBuild (/Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/out/packager.js:393:11)
    at /Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/src/packager.ts:270:52
From previous event:
    at Packager._build (/Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/out/packager.js:337:11)
    at /Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/src/packager.ts:240:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (/Users/3020246/Downloads/test-app/node_modules/electron-builder-lib/out/packager.js:297:11)
    at /Users/3020246/Downloads/test-app/node_modules/electron-builder/src/builder.ts:287:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/Users/3020246/Downloads/test-app/node_modules/electron-builder/out/builder.js:61:21)
    at build (/Users/3020246/Downloads/test-app/node_modules/electron-builder/src/builder.ts:257:10)
    at then (/Users/3020246/Downloads/test-app/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.args [as handler] (/Users/3020246/Downloads/test-app/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/3020246/Downloads/test-app/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/3020246/Downloads/test-app/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/3020246/Downloads/test-app/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/3020246/Downloads/test-app/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
</pre></detail>

**Comment by koala-koala** [comment]
I've got the same error, can you share your solution?

**Comment by priyankp10** [comment]
@koala-koala unfortunately i did not find any solutions for this. Building unpackaged electron apps works just fine, the problem is only with dmg as far as i know.

I closed this out because i think the reason was my mac, since it was a school computer it didn't allow working with dmgs so they blocked `hdiutil` in some way so dmg's could not be mounted and i think that the root cause of this error.

**Comment by bkniffler** [comment]
Also checkout https://github.com/electron-userland/electron-builder/issues/854
