### ISSUE TITLE
TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by JsseL** [electron-userland/electron-builder#2338]
### Versions:
* electron-builder: `19.46.4`
* electron-updater: `2.16.1`
* Node (Travis): `7.9.0` 

### Build target
* Building for **Mac** on Travis 

### Traceback from Travis:
```
Building DMG
Building macOS zip
Publishing to Github (owner: myOrg, project: myApp, version: 0.15.2)
myApp-0.15.2.dmg to GitHub
myApp-0.15.2-mac.zip to GitHubError: Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
TypeError: Cannot read property 'statusCode' of undefined
    at /Users/travis/build/myOrg/myApp/node_modules/electron-publish/src/gitHubPublisher.ts:157:17
    at Generator.throw (<anonymous>)
From previous event:
    at GitHubPublisher.doUpload (/Users/travis/build/myOrg/myApp/node_modules/electron-publish/out/gitHubPublisher.js:188:11)
    at /Users/travis/build/myOrg/myApp/node_modules/electron-publish/src/publisher.ts:80:18
    at Generator.next (<anonymous>)
From previous event:
    at GitHubPublisher.upload (/Users/travis/build/myOrg/myApp/node_modules/electron-publish/out/publisher.js:111:11)
    at PublishManager.scheduleUpload (/Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/publish/PublishManager.ts:117:40)
    at /Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/publish/PublishManager.ts:144:14
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at PublishManager.artifactCreated (/Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/out/publish/PublishManager.js:408:11)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/publish/PublishManager.ts:95:39)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at Packager.dispatchArtifactCreated (/Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/packager.ts:195:23)
    at /Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/targets/dmg.ts:91:19
    at Generator.next (<anonymous>)
    at /Users/travis/build/myOrg/myApp/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/travis/build/myOrg/myApp/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at DmgTarget.build (/Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/out/targets/dmg.js:278:11)
    at taskManager.addTask.default.map.it (/Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/platformPackager.ts:120:85)
From previous event:
    at MacPackager.packageInDistributableFormat (/Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/platformPackager.ts:120:41)
    at /Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/macPackager.ts:97:26
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at /Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/macPackager.ts:97:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/out/macPackager.js:200:11)
    at /Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/packager.ts:326:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/Users/travis/build/myOrg/myApp/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at Packager.doBuild (/Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/out/packager.js:393:11)
    at /Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/packager.ts:270:52
From previous event:
    at Packager._build (/Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/out/packager.js:337:11)
    at /Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/src/packager.ts:240:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/Users/travis/build/myOrg/myApp/node_modules/electron-builder-lib/out/packager.js:297:11)
    at /Users/travis/build/myOrg/myApp/node_modules/electron-builder/src/builder.ts:287:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/Users/travis/build/myOrg/myApp/node_modules/electron-builder/out/builder.js:61:21)
    at build (/Users/travis/build/myOrg/myApp/node_modules/electron-builder/src/builder.ts:257:10)
    at then (/Users/travis/build/myOrg/myApp/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (/Users/travis/build/myOrg/myApp/node_modules/electron-builder/out/cli/cli.js:127:117)
    at Object.runCommand (/Users/travis/build/myOrg/myApp/node_modules/electron-builder/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/travis/build/myOrg/myApp/node_modules/electron-builder/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/travis/build/myOrg/myApp/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/travis/build/myOrg/myApp/node_modules/electron-builder/out/cli/cli.js:123:441)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```
**P.s.** Really appriciate your work. Thank you.

**Comment by develar** [comment]
electron-builder 19.46.9 released for you.

**Comment by JsseL** [comment]
Noooo way! That's probably the fastest response/resolution ever! Thanks a ton @develar (assuming it solves the problem :wink:). Hahah.. talk about good open source service. :man_dancing:
