### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by andrewo0** [electron-userland/electron-builder#2342]
Hi 
Having some issues with autoUpdate.
It find's the update but before it's going to download the update it gives me a error

**TypeError: Cannot read property 'url' of undefined**
cant find out why it's giving me this error
 
**Version**: 
electron-updater = 2.16.1
electron = 1.7.9
electron-builder = 19.46.9

package.json
```
{
  "name": "Wired",
  "version": "0.1.0",
  "description": "Home assistant",
  "repository": {
    "type": "git",
    "url": "https://github.com/andrewo0/wired.git"
  },
  "scripts": {
    "postinstall": "install-app-deps"
  },
  "dependencies": {
    "electron-updater": "^2.16.1",
    "electron-log": "^1.3.0"
  },
  "devDependencies": {
    "electron-builder": "19.46.9",
    "electron-updater": "^2.16.1",
    "electron": "1.7.9",
    "gulp": "^3.9.1",
    "mocha": "^4.0.1",
    "spectron": "^3.7.2",
    "webpack-stream": "^3.2.0"
  },
  "build": {
    "appId": "com.electron.wired",
    "publish": [
      {
        "provider": "github",
        "owner": "andrewo0",
        "private": true
      }
    ],
    "win": {
      "target": "nsis"
    },
    "nsis": {
      "oneClick": false,
      "perMachine": false,
      "allowToChangeInstallationDirectory": true
    },
    "mac": {
      "category": "your.app.category.type"
    }
  }
}
```

index.js
```
const {app, BrowserWindow, Menu, protocol, ipcMain} = require('electron');
const log = require('electron-log');
const {autoUpdater} = require("electron-updater");

let window;
let path;
let json;

path = require('path');
json = require('settings.json');

autoUpdater.logger = log;
autoUpdater.logger.transports.file.level = 'info';
log.info('App starting...');

function sendStatusToWindow(text) {
  log.info(text);
  window.webContents.send('message', text);
}

function mainWindow(){
    window = new BrowserWindow({
        title: json.name,
        width: json.settings.width,
        height: json.settings.height,
        frame: json.settings.frame,
        titleBarStyle: json.settings.titlebarstyle,
        backgroundColor: '#000000',
        show: false
    });

    window.loadURL('file://' + path.join(__dirname, '..', '..') + '/index.html#v' + app.getVersion());
    
    window.once('ready-to-show', () => {
        window.show()
    })

    window.on('closed', function () {
        window = null;
    });
    
    return window;
}
app.on('ready', function()  {
  autoUpdater.checkForUpdates();
});
autoUpdater.on('checking-for-update', () => {
  sendStatusToWindow('Checking for update...');
})
autoUpdater.on('update-available', (info) => {
  sendStatusToWindow('Update available.');
})
autoUpdater.on('update-not-available', (info) => {
  sendStatusToWindow('Update not available.');
})
autoUpdater.on('error', (err) => {
  sendStatusToWindow('Error in auto-updater. ' + err);
})
autoUpdater.on('download-progress', (progressObj) => {
  let log_message = "Download speed: " + progressObj.bytesPerSecond;
  log_message = log_message + ' - Downloaded ' + progressObj.percent + '%';
  log_message = log_message + ' (' + progressObj.transferred + "/" + progressObj.total + ')';
  sendStatusToWindow(log_message);
})
autoUpdater.on('update-downloaded', (info) => {
  sendStatusToWindow('Update downloaded');
});

app.on('ready', function () {
    mainWindow();
});
app.on('window-all-closed', () => {
  app.quit();
});
```

Log:
```
[2017-11-30 09:38:00:0536] [info] App starting...
[2017-11-30 09:38:00:0607] [info] Checking for update
[2017-11-30 09:38:00:0607] [info] Checking for update...
[2017-11-30 09:38:01:0926] [info] Generated new staging user ID: 
[2017-11-30 09:38:03:0907] [info] Found version 0.1.1 (url: Wired-Setup-0.1.1.exe)
[2017-11-30 09:38:03:0907] [info] Update available.
[2017-11-30 09:38:03:0908] [info] Downloading update from Wired-Setup-0.1.1.exe
[2017-11-30 09:38:03:0912] [error] Error: TypeError: Cannot read property 'url' of undefined
    at updateInfo.files.map.it (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\PrivateGitHubProvider.ts:101:63)
    at Array.map (native)
    at PrivateGitHubProvider.resolveFiles (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\PrivateGitHubProvider.ts:98:29)
    at C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:19:53
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:133:11)
    at C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:304:25
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.downloadUpdate (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:355:11)
    at C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:280:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:326:11)
    at C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:280:11)
    at NsisUpdater.checkForUpdates (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:177:35)
    at App.<anonymous> (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\javascripts\main\index.js:45:15)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
[2017-11-30 09:38:03:0912] [info] Error in auto-updater. TypeError: Cannot read property 'url' of undefined
```

**Comment by thealexbaron** [comment]
Getting a similar error: 

```
[2017-12-01 16:08:43.290] [info] Checking for update
[2017-12-01 16:08:46.392] [info] Found version 0.0.2 (url: )
[2017-12-01 16:08:46.393] [info] Downloading update from
[2017-12-01 16:08:46.396] [error] Error: TypeError: Cannot read property 'map' of undefined
    at PrivateGitHubProvider.resolveFiles (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-updater\src\PrivateGitHubProvider.ts:98:23)
    at C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:19:53
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:133:11)
    at C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:304:25
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.downloadUpdate (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:355:11)
    at C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:280:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:326:11)
    at C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:280:11)
    at NsisUpdater.checkForUpdates (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:177:35)
    at NsisUpdater.checkForUpdatesAndNotify (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:197:17)
    at Object.<anonymous> (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\src\index.js:77:30)
    at Object.<anonymous> (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\src\index.js:215:3)
    at Module._compile (module.js:571:32)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-compile\src\require-hook.js:65:14)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at Object.init (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\node_modules\electron-compile\src\config-parser.js:102:16)
    at Object.<anonymous> (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\__shim.js:3:29)
    at Object.<anonymous> (C:\Users\inlineofire\AppData\Local\Programs\webship-scale-reader\resources\app.asar\__shim.js:5:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

**Comment by develar** [comment]
electron-updater 2.16.3 released.

**Comment by andrewo0** [comment]
I'm still getting the same error after updating electron-updater to 2.16.3 and releasing my app
Update is being found but it's not able to download.

Log:
```
[2017-12-02 10:24:59:0790] [info] App starting...
[2017-12-02 10:24:59:0841] [info] Checking for update
[2017-12-02 10:24:59:0841] [info] Checking for update...
[2017-12-02 10:25:01:0101] [info] Generated new staging user ID: 
[2017-12-02 10:25:03:0602] [info] Found version 0.1.1 (url: Wired-Setup-0.1.1.exe)
[2017-12-02 10:25:03:0602] [info] Update available.
[2017-12-02 10:25:03:0606] [info] Downloading update from Wired-Setup-0.1.1.exe
[2017-12-02 10:25:03:0616] [error] Error: TypeError: Cannot read property 'url' of undefined
    at updateInfo.files.map.it (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\PrivateGitHubProvider.ts:101:63)
    at Array.map (native)
    at PrivateGitHubProvider.resolveFiles (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\PrivateGitHubProvider.ts:98:29)
    at C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:19:53
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:133:11)
    at C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:304:25
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.downloadUpdate (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:355:11)
    at C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:280:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:326:11)
    at C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:280:11)
    at NsisUpdater.checkForUpdates (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:177:35)
    at App.<anonymous> (C:\Users\Andrew\AppData\Local\Programs\Wired\resources\app.asar\javascripts\main\index.js:84:15)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
[2017-12-02 10:25:03:0617] [info] Error in auto-updater. TypeError: Cannot read property 'url' of undefined
```

**Comment by thealexbaron** [comment]
I'm also getting the same error after updating to `2.16.3`. I appreciate your attention to this issue!

**Comment by develar** [comment]
@andrewo0 @thealexbaron Please try 2.17.0 (it is pre-release version, to upgrade, please set explicitly to `^2.17.0`).

**Comment by AdrianCuartas** [comment]
I'm getting a similar error.

log:
`
"err": {
    "message": "Cannot read property 'sha512' of undefined",
    "name": "TypeError",
    "stack": "TypeError: Cannot read property 'sha512' of undefined\n    at C:\\Users\\c-sol\\AppData\\Local\\Programs\\proxima\\resources\\app.asar\\node_modules\\electron-updater\\src\\NsisUpdater.ts:28:15\n    at Generator.next (<anonymous>)\n    at runCallback (timers.js:781:20)\n    at tryOnImmediate (timers.js:743:5)\n    at processImmediate [as _immediateCallback] (timers.js:714:5)\nFrom previous event:\n    at NsisUpdater.doDownloadUpdate (C:\\Users\\c-sol\\AppData\\Local\\Programs\\proxima\\resources\\app.asar\\node_modules\\electron-updater\\src\\NsisUpdater.ts:20:96)\n    at C:\\Users\\c-sol\\AppData\\Local\\Programs\\proxima\\resources\\app.asar\\node_modules\\electron-updater\\src\\AppUpdater.ts:361:25\n    at Generator.next (<anonymous>)\nFrom previous event:\n    at NsisUpdater.downloadUpdate (C:\\Users\\c-sol\\AppData\\Local\\Programs\\proxima\\resources\\app.asar\\node_modules\\electron-updater\\src\\AppUpdater.ts:350:86)\n    at Function.<anonymous> (C:\\Users\\c-sol\\AppData\\Local\\Programs\\proxima\\resources\\app.asar\\dist\\electron\\main.js:1:64226)"
  }
`

My 'latest.yml' file is uploaded correctly and looks good:

version: 0.7.0
files:
  - url: proxima Setup 0.7.0.exe
    sha512: -----------
    size: 52174845
path: proxima Setup 0.7.0.exe
sha512: -----------
sha2: -------------
releaseDate: '2018-06-29T11:39:08.277Z'

I'm using "electron-updater": "^2.22.1"

I'm lost. I'll appreciate any help

**Comment by develar** [comment]
@AdrianCuartas Do you use latest electron-builder?

**Comment by AdrianCuartas** [comment]
Yes, I do. 
 "electron-builder": "^20.18.0"

**Comment by tglanz** [comment]
It might be looking for url under author at the package.json..?
Try adding this to the package.json of the app
```
"author": {
    "name": "some-name",
    "email": "some-mail@gmail.com",
    "url": "http://some-site.org/"
}
```

**Comment by AdrianCuartas** [comment]
I tried almost everything. And still getting this error:
![image](https://user-images.githubusercontent.com/3962288/42762563-f3d5b57a-8910-11e8-8583-216d793d2a84.png)

This  is my package.json

`{
  "name": "proxima",
  "productName": "Proxima",
  "version": "0.7.25",
  "author": "",
  "description": "",
  "license": "",
  "main": "./dist/electron/main.js",
  "scripts": {
    "build": "node .electron-vue/build.js",
    "build:darwin": "cross-env BUILD_TARGET=darwin node .electron-vue/build.js",
    "build:linux": "cross-env BUILD_TARGET=linux node .electron-vue/build.js",
    "build:mas": "cross-env BUILD_TARGET=mas node .electron-vue/build.js",
    "build:win32": "cross-env BUILD_TARGET=win32 node .electron-vue/build.js",
    "build:clean": "cross-env BUILD_TARGET=clean node .electron-vue/build.js",
    "build:web": "cross-env BUILD_TARGET=web node .electron-vue/build.js",
    "dev": "node .electron-vue/dev-runner.js",
    "dist": "./node_modules/.bin/electron-builder --prepackaged ./build/Proxima-win32-x64",
    "publish": "node .electron-vue/build.js && build --publish always",
    "lint": "eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter src",
    "lint:fix": "eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src",
    "pack": "npm run pack:main && npm run pack:renderer",
    "pack:main": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.main.config.js",
    "pack:renderer": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.renderer.config.js",
    "postinstall": "npm run lint:fix"
  },
  "build": {
    "productName": "proxima",
    "appId": "com.proxima.novastock",
    "directories": {
      "output": "build"
    },
    "icon": "build/icons",
    "asar": true,
    "files": [
      "dist/electron/**/*"
    ],
    "nsis": {
      "artifactName": "${productName}Setup${version}.${ext}"
    },
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64"
          ]
        }
      ],
      "publish": {
        "provider": "s3",
        "bucket": "updates-proxima"
      }
    }
  },
  "dependencies": {
    "bunyan": "^1.8.12",
    "bunyan-loggly": "^1.3.5",
    "electron-updater": "^2.23.3",
    "font-awesome": "^4.7.0",
    "fs-extra": "^5.0.0",
    "javascript-state-machine": "^3.1.0",
    "knex": "^0.14.6",
    "koa": "^2.5.2",
    "koa-bodyparser": "^4.2.1",
    "koa-router": "^7.4.0",
    "moment": "^2.22.2",
    "node-grok": "^2.0.3",
    "odbc": "^1.4.2",
    "sqlite3": "^3.1.13",
    "typeface-roboto": "0.0.54",
    "vue": "^2.5.16",
    "vue-electron": "^1.0.6",
    "vue-router": "^3.0.1",
    "vuetify": "^1.1.4",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.24.1",
    "babili-webpack-plugin": "^0.1.2",
    "cfonts": "^1.2.0",
    "chalk": "^2.4.1",
    "copy-webpack-plugin": "^4.5.2",
    "cross-env": "^5.2.0",
    "css-loader": "^0.28.11",
    "del": "^3.0.0",
    "devtron": "^1.4.0",
    "electron": "^1.8.7",
    "electron-builder": "^20.22.0",
    "electron-debug": "^1.4.0",
    "electron-devtools-installer": "^2.2.4",
    "electron-log": "^2.2.16",
    "electron-packager": "^10.1.2",
    "electron-publisher-s3": "^20.17.2",
    "electron-rebuild": "^1.8.1",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "html-webpack-plugin": "^2.30.1",
    "multispinner": "^0.2.1",
    "node-loader": "^0.6.0",
    "style-loader": "^0.18.2",
    "url-loader": "^0.5.9",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^13.7.2",
    "vue-style-loader": "^3.1.2",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.12.0",
    "webpack-dev-server": "^2.11.2",
    "webpack-hot-middleware": "^2.22.2"
  }
}
`
