### ISSUE TITLE
ENOENT appimagetool for armv7l

### ISSUE THREAD

**Issue by ikonduktor** [electron-userland/electron-builder#2348]
I'm using electron-builder v 19.47.1

Build for target armv7l linux and x64 linux.
For x64 everything is ok, builded on Ubuntu
But for armv7l there is a problem with appimagetool
Tryed on Ubuntu 16 and raspbery pi 3

Error stack:
```
 nodecm-agent@0.1.0 dist /home/pi/Downloads/agent
> build -l --armv7l
 
electron-builder 19.47.1
No native production dependencies
Packaging for linux armv7l using electron 1.7.9 to dist/linux-armv7l-unpacked
Building AppImage for arch armv7l
⚠️  Application category is not set for Linux (linux.category).
Please see https://electron.build/configuration/configuration#LinuxBuildOptions-category
Error: Exit code: ENOENT. spawn /home/pi/.cache/electron-builder/appimage/appimage-9.0.3/linux-arm/appimagetool ENOENT
    at /home/pi/Downloads/agent/node_modules/builder-util/src/util.ts:109:16
    at exithandler (child_process.js:278:5)
    at ChildProcess.errorhandler (child_process.js:290:5)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```
When i looks to this path, there is no appimagetool.

Also Error stack for ubuntu, when try build armv7l:
```

> nodecm-agent@0.1.0 dist /home/rootuser/proj/work/agent_dump
> build -l --armv7l

electron-builder 19.47.1
No native production dependencies
Packaging for linux armv7l using electron 1.6.15 to dist/linux-armv7l-unpacked
Building AppImage for arch armv7l
⚠️  Application category is not set for Linux (linux.category).
Please see https://electron.build/configuration/configuration#LinuxBuildOptions-category
Error: Exit code: 1. Command failed: /home/rootuser/.cache/electron-builder/appimage/appimage-9.0.3/linux-x64/appimagetool --runtime-file /home/rootuser/.cache/electron-builder/appimage/appimage-9.0.3/runtime-armv7l --no-appstream /home/rootuser/proj/work/agent_dump/dist/__appImage-armv7l /home/rootuser/proj/work/agent_dump/dist/nodecm-agent-0.1.0-armv7l.AppImage
Using architecture ARM
Deleting pre-existing .DirIcon
Creating .DirIcon symlink based on information from desktop file
Generating squashfs...
Unable to load provided runtime file

```

**Comment by develar** [comment]
Not supported yet, help-wanted, moved to backlog.

**Comment by ffalcinelli** [comment]
It seems that there's still a mismatch between the architectures names. On a debian armv7l docker machine:

```
# uname -a
Linux dec97180d82e 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 armv7l GNU/Linux
```
I had to make a symbolic link to a folder where I recompiled the AppImageKit

```
# ls -lrt ~/.cache/electron-builder/appimage/appimage-9.0.5/
total 468
drwxr-xr-x 4 root root   4096 Oct  1 15:25 lib
-rw-r--r-- 1 root root  92908 Nov 22 12:59 runtime-i686
-rw-r--r-- 1 root root 100024 Nov 22 12:59 runtime-x86_64
drwxr-xr-x 2 root root   4096 Nov 22 13:01 linux-x64
drwxr-xr-x 2 root root   4096 Nov 22 13:03 darwin
drwxr-xr-x 2 root root   4096 Nov 22 13:25 linux-ia32
-rwxr-xr-x 1 root root 106660 Jan  6 09:54 runtime-armv7
-rwxr-xr-x 1 root root 148368 Jan 19 07:50 runtime-arm64
drwxr-xr-x 2 root root   4096 Jan 19 07:50 linux-arm64
lrwxrwxrwx 1 root root     28 Jan 25 15:08 linux-arm -> /root/AppImageKit/build/out/
```
That's because for some reason it is searching for `linux-arm` directory that is not provided in the 9.0.5 version. Then also, once compiled and uploaded, you will find a `latest-linux-armv7l.yml` near the AppImage bundle and to make `electron-updater` work you have to rename it in `latest-linux-arm.yml`

In this way I'm able to publish and autoupdate on `armv7l`.

I'm trying to figure it out in the `electron-builder` project, but I still have some difficulties to make the all thing build, sorry :confused:

**Comment by InspireTheLostBoys** [comment]
I am experiencing the same issue as @ffalcinelli.
When trying to run the electron-builder for armv7l 32 bit architecture, the AppImage downloaded does not contain a folder linux-arm.

I have not tried on a 64 bit architecture yet as the requirement is for a 32 bit.

Any pointers would be greatly appreciated.
