### ISSUE TITLE
Error when building Windows AppX build

### ISSUE THREAD

**Issue by holgersindbaek** [electron-userland/electron-builder#2354]
I'm trying to create a build for Windows AppX. I've created the self signed certificate, as the terminal guided me to, but if I run `electron-builder` I get the following error:

```
C:\Users\holgersindbaek\Desktop\SolitaireGameCenter>npm run electron:dist

> Solitaire@1.0.8 electron:dist C:\Users\holgersindbaek\Desktop\SolitaireGameCenter
> electron-builder

electron-builder 19.31.3
electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from
 devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "
electron-builder install-app-deps" to your `package.json`
Rebuilding native production dependencies for win32:x64
Packaging for win32 x64 using electron 1.7.9 to dist\win-unpacked
CSC_KEY_PASSWORD is not defined, empty password will be used
Signing Solitaire-1.0.8.appx (certificate file: "src/electron/holgersindbaek.pfx")
Error: Exit code: ENOENT. spawn prlctl ENOENT
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\builder-util\src\util.ts:91:16
    at exithandler (child_process.js:282:5)
    at ChildProcess.errorhandler (child_process.js:294:5)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at exec (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\builder-util\src\util.ts:63:3
)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\parallels.ts:4
:23
    at Generator.next (<anonymous>)
From previous event:
    at parseVmList (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\out\p
arallels.js:42:21)
    at Lazy.<anonymous> (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\
src\winPackager.ts:68:27)
    at Generator.next (<anonymous>)
    at Lazy.get value [as value] (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\lazy-val
\src\main.ts:18:23)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\windowsCodeSig
n.ts:93:36
    at Generator.next (<anonymous>)
    at doSign (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\out\window
sCodeSign.js:77:22)
    at defaultExecutor (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\s
rc\windowsCodeSign.ts:70:12)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\windowsCodeSig
n.ts:77:11
From previous event:
    at Lazy.get value [as value] (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\lazy-val
\src\main.ts:18:23)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\windowsCodeSig
n.ts:93:36
    at Generator.next (<anonymous>)
    at doSign (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\out\window
sCodeSign.js:77:22)
    at defaultExecutor (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\s
rc\windowsCodeSign.ts:70:12)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\windowsCodeSig
n.ts:77:11
    at Generator.next (<anonymous>)
    at sign (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\out\windowsC
odeSign.js:45:21)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\winPackager.ts
:272:15
From previous event:
    at doSign (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\out\window
sCodeSign.js:77:22)
    at defaultExecutor (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\s
rc\windowsCodeSign.ts:70:12)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\windowsCodeSig
n.ts:77:11
    at Generator.next (<anonymous>)
From previous event:
    at sign (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\out\windowsC
odeSign.js:45:21)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\winPackager.ts
:272:15
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.doSign (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builde
r\out\winPackager.js:401:11)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\winPackager.ts
:257:16
From previous event:
    at WinPackager.sign (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\
out\winPackager.js:381:11)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\targets\appx.t
s:116:20
    at Generator.next (<anonymous>)
From previous event:
    at AppXTarget.build (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\
out\targets\appx.js:179:11)
    at taskManager.addTask.default.map.it (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules
\electron-builder\src\platformPackager.ts:110:85)
From previous event:
    at AppXTarget.build (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\
out\targets\appx.js:179:11)
    at taskManager.addTask.default.map.it (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules
\electron-builder\src\platformPackager.ts:110:85)
From previous event:
    at WinPackager.packageInDistributableFormat (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_m
odules\electron-builder\src\platformPackager.ts:110:41)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\platformPackag
er.ts:106:10
From previous event:
    at WinPackager.pack (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\
out\platformPackager.js:175:11)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\packager.ts:26
0:24
From previous event:
    at Packager.doBuild (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\
out\packager.js:344:11)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\packager.ts:18
6:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\ou
t\packager.js:263:11)
    at C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\builder.ts:286
:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\out\builder
.js:69:21)
    at loadEnv.then (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder\src\
cli\cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-
builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builder
\node_modules\yargs\lib\command.js:226:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\e
lectron-builder\node_modules\yargs\yargs.js:998:24)
    at Object.get [as argv] (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-buil
der\node_modules\yargs\yargs.js:912:21)
    at Object.<anonymous> (C:\Users\holgersindbaek\Desktop\SolitaireGameCenter\node_modules\electron-builde
r\src\cli\cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! Solitaire@1.0.8 electron:dist: `electron-builder`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the Solitaire@1.0.8 electron:dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\holgersindbaek\AppData\Roaming\npm-cache\_logs\2017-12-03T17_53_57_751Z-debug.log
```

These are my build configs:

```
  "build": {
    "appId": "com.betaunltd.solitaire-game-center",
    "productName": "Solitaire",
    "buildVersion": "1.0.12",
    "win": {
      "target": "appx",
      "certificateFile" : "src/electron/holgersindbaek.pfx",
      "icon": "src/electron/assets/store.ico",
      "publisherName": "holgersindbaek"
    },
    "files": [
      "src/electron.js",
      "src/electron/**/*",
      "package.json"
    ],
    "directories": {
      "buildResources": "src/electron/assets"
    }
  }
```

Any guesses as to what I'm doing wrong here?

**Comment by rjb8682** [comment]
Bumping this issue.

Currently running into the same error trying to build the windows version of our app on a Mac. We recently added in a USB token-based EV cert into the mix and we're trying to get this to build/sign using that EV cert.

Not sure if the issue is related to attempting to add that cert.

**Comment by IGassmann** [comment]
Encountering the same error when trying to sign a Windows app on Travis using the provided docker image.

**Comment by develar** [comment]
You cannot build AppX on macOS without Parallels Desktop Pro. It is Windows limitation — AppX works only on Windows.

**Comment by tbushman** [comment]
@develar Thank you. The Parallels build works. You're awesome.

**Comment by develar** [comment]
> The Parallels build works

Great.

The main problem to setup windows build agent for now not a money (well, I can always require users to pay 10$ per year for builds), but fact that windows and macOS doesn't support docker and so, not easy to add windows/macOS worker agent to cluster pool. Anyway, I think it will be done this year.
