### ISSUE TITLE
electron-builder causes graceful-fs to fail on Electron 1.7.0+

### ISSUE THREAD

**Issue by Zamiell** [electron-userland/electron-builder#2369]
**Which version of electron-builder are you using?**
19.48.2

**What target are you building for?**
Windows

**What is the issue?**

Hello again develar. = )

* I've made a **very tiny** example application based on the `electron-quick-start` repository to demonstrate this problem.
* All that the app does is read a file into a variable
  * The new code added is in `renderer.js`: : https://github.com/Zamiell/electron-quick-start1/blob/master/renderer.js
  * The `main.js` file is unchanged except to uncomment the `mainWindow.webContents.openDevTools()` line.
* After running `npm run dist` (which causes `electron-builder` to package up the repository), the resulting application works just fine on Electron 1.6.11. However, when on Electron 1.7.0+, it fails, causing the following error:

```
Uncaught TypeError: Bad arguments
    at fs.readFile (ELECTRON_ASAR.js:468:15)
    at go$readFile (C:\Users\james\AppData\Local\Programs\electron-quick-start\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:73:14)
    at Object.readFile (C:\Users\james\AppData\Local\Programs\electron-quick-start\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:70:12)
    at Object.readFile (C:\Users\james\AppData\Local\Programs\electron-quick-start\resources\app.asar\node_modules\universalify\index.js:5:67)
    at Object.<anonymous> (C:\Users\james\AppData\Local\Programs\electron-quick-start\resources\app.asar\renderer.js:10:4)
    at Object.<anonymous> (C:\Users\james\AppData\Local\Programs\electron-quick-start\resources\app.asar\renderer.js:19:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

Repository 1, using Electron 1.6.11: https://github.com/Zamiell/electron-quick-start1
Repository 2, using Electron 1.8.1: https://github.com/Zamiell/electron-quick-start2
(both of these repositories are identical except for the package.json file)

I assume the issue has something to do with the file being inside of an Asar archive. But is the problem Electron? Or is it a problem with electron-builder? Or is it a problem with graceful-fs? It is very confusing. But it only happens after using `electron-builder`, and never in development.

**Comment by marcusjwhelan** [comment]
What is the path you are feeding it? I did also have an issue with readfile when upgrading as well but I had made my own method on top of readfile to get past this issue. But I did switch both electron-builder version and from nodejs fs to graceful-fs at the same time. So there is no telling where the error is originating.

**Comment by Zamiell** [comment]
@marcusjwhelan See: https://github.com/Zamiell/electron-quick-start2/blob/master/renderer.js#L9

**Comment by nmanske** [comment]
I experienced the same issue with graceful-fs as @Zamiell on Electron v1.7.10. I am building for both Linux and Windows and am receiving a TypeError on a valid readFile() method. The code works fine in dev but fails after being packaged by electron-builder. As a  temporary fix I am using the default fs package for the readFile() method and fs-extra/graceful-fs for everything else.

**Comment by Zamiell** [comment]
I refactored all of my code to not use graceful-fs anymore.
