### ISSUE TITLE
Differential download fails on GitHub Releases. (Content-Type "multipart/byteranges" is expected, but got "application/octet-stream")

### ISSUE THREAD

**Issue by mateullull** [electron-userland/electron-builder#2376]
* **Version**: 19.48.3

* **Electron-updater**: 2.17.3

* **Target**: Linux x64

When I try to auto-update from **GitHub Releases** from a TravisCI-generated binary, I get this error:

```
File has 455 changed blocks
Full: 55,823.95 KB, To download: 5,234.26 KB (9%)
Cannot download differentially, fallback to full download: Error: Content-Type "multipart/byteranges" is expected, but got "application/octet-stream"
    at ClientRequest.request.httpExecutor.doRequest.response (/tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/src/differentialDownloader/DifferentialDownloader.ts:219:16)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/tmp/.mount_la-bib8Yqgk3/app/resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
From previous event:
    at /tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/src/differentialDownloader/DifferentialDownloader.ts:91:5
    at Generator.next (<anonymous>)
    at /tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at AppImageDifferentialDownloader.downloadFile (/tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/out/differentialDownloader/DifferentialDownloader.js:165:11)
    at AppImageDifferentialDownloader.doDownload (/tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/src/differentialDownloader/DifferentialDownloader.ts:82:17)
    at /tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/src/differentialDownloader/AppImageDifferentialDownloader.ts:11:16
From previous event:
    at AppImageDifferentialDownloader.download (/tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/out/differentialDownloader/AppImageDifferentialDownloader.js:31:11)
    at /tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:68:12
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at /tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:143:33
    at /tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:46:13
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at AppImageUpdater.executeDownload (/tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:98:11)
    at /tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:51:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater.doDownloadUpdate (/tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:150:11)
    at /tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:331:25
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.downloadUpdate (/tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:366:11)
    at Function.<anonymous> (/tmp/.mount_la-bib8Yqgk3/app/resources/app.asar/dist/electron/main.js:1:4062)
```

When fallback to full-download, the file is created in `/temp/<random>` folder correctly, but it never downloads. The download size remains with 0 bytes.

**Comment by mateullull** [comment]
Solved in Linux with **electron-updater 2.17.4**
