### ISSUE TITLE
Latest release breaks NSIS installer builds

### ISSUE THREAD

**Issue by bayssmekanique** [electron-userland/electron-builder#2386]
* **Version**: 19.49.0 & 19.49.2

* **Updater Version**: 2.17.6

* **Target**: Windows x64 & ia32

Starting at release `19.49.0`, the build fails with an async error and then the script exits with an `Exit status 1`.

Error details:
```
...
Downloading nsis-resources-3.3.0, please wait
Error: The specified module could not be found.
\\?\C:\projects\keiser-mseries-challenge\node_modules\rabin-bindings\build\Release\rabin-bindings.node
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at bindings (C:\projects\keiser-mseries-challenge\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\projects\keiser-mseries-challenge\node_modules\rabin-bindings\index.js:1:43)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at _load_rabinBindings (C:\projects\keiser-mseries-challenge\node_modules\app-package-builder\out\ContentDefinedChunker.js:23:29)
...
```

I've tested on 3 different PCs (though all were Windows 10 x64 PCs) plus AppVeyor, using both npm and yarn, and I've seen the exact same issue on all 4 instances.  The module it's saying doesn't exist is there (in that exact location) and there are no weird permission set on the file.  Also, the issue is for sure with the NSIS installer portion.  Running `electron-builder --dir` works fine.

**Comment by bayssmekanique** [comment]
Upon further digging, this seems to be a problem with the differential package additions.  The documentation makes it sound like the `nsis.differentialPackage` will default to `false`, but looking at the `isBuildDifferentialAware()` it checks for `this.options.differentialPackage !== false`, this would only evaluate to false if it's explicitly set to `false` (which it does not appear to be).

Adding `"nsis": {"differentialPackage": false}` resolves the build issues.

Given that this is a minor release, shouldn't the default be set to `false` to preserve existing functionality?

**Comment by develar** [comment]
> shouldn't the default be set to false to preserve existing functionality?

New behaviour doesn't break existing functionality. Ok — I will get rid of NodeJS and will use Golang to implement this solution, indeed, NodeJS is not suitable for this task. Sorry for inconvenience.

**Comment by develar** [comment]
Reopened — early release of unfinished functionality was a main intention to see, if solution on NodeJS is suitable for Windows users or not.
