### ISSUE TITLE
AppImageUpdater.quitAndInstall throws exception

### ISSUE THREAD

**Issue by logidelic** [electron-userland/electron-builder#2391]
* **Version**: 19.49.2

* **electron-updater**: 2.17.6

* **Target**: Linux AppImage

I'm trying to get auto-update working for my linux/appimage target. Update downloads correctly, but when I call `quitAndInstall`, i.e.:

```
     autoUpdater.signals.updateDownloaded((ev, info) => {
         autoUpdater.quitAndInstall();
     });
```

I get the following log & exception:

```
Install on explicit quitAndInstall
Install: isSilent: false, isRunAfter: true

Error: Error: EIO: i/o error, write
    at Object.fs.writeSync (fs.js:745:20)
    at SyncWriteStream._write (internal/fs.js:75:6)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SyncWriteStream.Writable.write (_stream_writable.js:241:11)
    at execFileSync (child_process.js:511:20)
    at module.(anonymous function) (ELECTRON_ASAR.js:173:20)
    at AppImageUpdater.doInstall (/tmp/.mount_myappk39cLy/app/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:107:5)
    at AppImageUpdater.install (/tmp/.mount_myappk39cLy/app/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:80:19)
    at AppImageUpdater.quitAndInstall (/tmp/.mount_myappk39cLy/app/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:21:14)
    at AppImageUpdater.autoUpdater.signals.updateDownloaded (/tmp/.mount_myappk39cLy/app/resources/app.asar/main.js:462:21)
    at emitOne (events.js:96:13)
    at AppImageUpdater.emit (events.js:191:7)
    at /tmp/.mount_myappk39cLy/app/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:85:10
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/tmp/.mount_myappk39cLy/app/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
```

FWIW, the new version was correctly downloaded and the old version was deleted, but `quitAndInstall` does not quit the old version or run the new...

**Comment by logidelic** [comment]
After beginning to debug, I can no longer repro. Not sure what has changed, but it was consistent before. I will re-open if I can figure it out.
