### ISSUE TITLE
electron-updater getting ERR_CONNECTION_REFUSED on checkForUpdates

### ISSUE THREAD

**Issue by naheller** [electron-userland/electron-builder#2405]
* **Version**: 
electron-builder: 19.45.5
electron-updater: 2.16.1

I'm currently publishing to S3, and had no issues up until some recent code changes. Before I get into the actual code, I was hoping someone could help me interpret the following error log. Your help is appreciated!

```
[2017-12-20 17:01:02.128] [info] CHECKING FOR UPDATE
[2017-12-20 17:01:02.236] [error] Error: Error: net::ERR_CONNECTION_REFUSED
    at CancellationToken.createPromise (/Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:69:30)
    at ElectronHttpExecutor.request (/Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:61:17)
    at /Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GenericProvider.ts:18:53
    at Generator.next (<anonymous>)
From previous event:
    at GenericProvider.getLatestVersion (/Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GenericProvider.js:58:11)
    at /Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:251:37
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at MacUpdater.checkForUpdates (/Applications/Training Tracker.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at Timeout.setInterval [as _onTimeout] (/Applications/Training Tracker.app/Contents/Resources/app.asar/main.js:80:21)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by develar** [comment]
It means that updater cannot connect to remote host. Please check updates URL.
