### ISSUE TITLE
ERROR: Desktop file contains errors. Please fix them.

### ISSUE THREAD

**Issue by schickling** [electron-userland/electron-builder#2412]
* **Version**: 

19.48.3, 19.49.0, ..., 19.49.3

* **Target**:  -lmw

```
...
Downloading wine-2.0.1-mac-10.12, please wait
Building nsis installer (x64)
Downloading nsis-3.0.1.13, please wait
Error: Exit code: 1. Command failed: /Users/travis/Library/Caches/electron-builder/appimage/appimage-9.0.3/darwin/appimagetool --runtime-file /Users/travis/Library/Caches/electron-builder/appimage/appimage-9.0.3/runtime-x86_64 --no-appstream /Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/build-electron/__appImage-x64 /Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/build-electron/graphql-playground-1.3.13-x86_64.AppImage
ERROR: Desktop file contains errors. Please fix them. Please see
       https://standards.freedesktop.org/desktop-entry-spec/latest/
       for more information.
WARNING: zsyncmake is missing, please install it if you want to use binary delta updates
/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/build-electron/__appImage-x64/graphql-playground.desktop: error: value "DeveloperTools;" for key "Categories" in group "Desktop Entry" contains an unregistered value "DeveloperTools"; values extending the format should start with "X-"
/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/build-electron/__appImage-x64/graphql-playground.desktop: hint: value "DeveloperTools;" for key "Categories" in group "Desktop Entry" does not contain a registered main category; application might only show up in a "catch-all" section of the application menu
ERROR: Desktop file contains errors. Please fix them. Please see
       https://standards.freedesktop.org/desktop-entry-spec/latest/
       for more information.
    at /Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/builder-util/src/util.ts:109:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at exec (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/builder-util/src/util.ts:77:3)
    at /Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:109:5
    at Generator.next (<anonymous>)
    at /Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at AppImageTarget.build (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:191:11)
    at taskManager.addTask.default.map.it (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/src/platformPackager.ts:120:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/src/platformPackager.ts:120:41)
    at /Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/src/platformPackager.ts:116:10
From previous event:
    at LinuxPackager.pack (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/out/platformPackager.js:195:11)
    at /Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/src/packager.ts:345:24
From previous event:
    at Packager.doBuild (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/out/packager.js:407:11)
    at /Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/src/packager.ts:289:52
From previous event:
    at Packager._build (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/out/packager.js:351:11)
    at /Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/src/packager.ts:259:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder-lib/out/packager.js:311:11)
    at /Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder/src/builder.ts:287:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder/out/builder.js:61:21)
    at build (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder/src/builder.ts:257:10)
    at then (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn release" failed and exited with 1 during .
Your build has been stopped.
```

Build link: https://travis-ci.org/graphcool/graphql-playground/builds/321198946#L406
Code link: https://github.com/graphcool/graphql-playground/blob/master/packages/graphql-playground-electron/package.json

**Comment by develar** [comment]
Please fix

/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/build-electron/__appImage-x64/graphql-playground.desktop: error: value "DeveloperTools;" for key "Categories" in group "Desktop Entry" contains an unregistered value "DeveloperTools"; values extending the format should start with "X-"
/Users/travis/build/graphcool/graphql-playground/packages/graphql-playground-electron/build-electron/__appImage-x64/graphql-playground.desktop: hint: value "DeveloperTools;" for key "Categories" in group "Desktop Entry" does not contain a registered main category; application might only show up in a "catch-all" section of the application menu
