### ISSUE TITLE
PACKAGING -Mac issue.

### ISSUE THREAD

**Issue by pikvik** [electron-userland/electron-builder#2419]
yarn run v1.3.2
$ npm run build && build -m

> asystguard@2.1.0 build /Users/deepakumari/Desktop/Asystguard-Mac
> concurrently "npm run build-main" "npm run build-renderer"

[0]
[0] > asystguard@2.1.0 build-main /Users/deepakumari/Desktop/Asystguard-Mac
[0] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors
[0]
[1]
[1] > asystguard@2.1.0 build-renderer /Users/deepakumari/Desktop/Asystguard-Mac
[1] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
[1]
[1] (node:4626) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
[1]     at /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/extract-text-webpack-plugin/index.js:271:25
[1]     at /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/async/dist/async.js:3096:16
[1]     at eachOfArrayLike (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/async/dist/async.js:1055:9)
[1]     at eachOf (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/async/dist/async.js:1103:5)
[1]     at Object.eachLimit (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/async/dist/async.js:3158:5)
[1]     at ExtractTextPlugin.<anonymous> (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/extract-text-webpack-plugin/index.js:268:10)
[1]     at Compilation.applyPluginsAsyncSeries (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:206:13)
[1]     at Compilation.seal (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:605:8)
[1]     at applyPluginsParallel.err (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compiler.js:504:17)
[1]     at /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:289:11
[1]     at _addModuleChain (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:507:11)
[1]     at processModuleDependencies.err (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:477:14)
at _combinedTickCallback (internal/process/next_tick.js:131:7)
[1]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0] /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
[0]         throw new Error(
[0]         ^
[0]
[0] Error: original.line and original.column are not numbers -- you probably meant to omit the originalmapping entirely and only map the generated position. If so, pass null for the original mapping insteadof an object with empty or null values.
[0]     at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
[0]     at SourceMapGenerator_addMapping [as addMapping] (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
[0]     at /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
[0]     at Array.forEach (<anonymous>)
[0]     at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
[0]     at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
[0]     at SourceMapSource.node (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
[0]     at SourceMapSource.proto.sourceAndMap (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
[0]     at getTaskForFile (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
[0]     at chunk.files.forEach.file (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
[0]     at Array.forEach (<anonymous>)
[0]     at /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/SourceMapDevToolPlugin.js:89:18
[0]     at Array.forEach (<anonymous>)
[0]     at Compilation.<anonymous> (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:12)
[0]     at Compilation.applyPlugins1 (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:75:14)
[0]     at self.applyPluginsAsync.err (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:670:11)
[0]     at next (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:202:11)
[0]     at Compilation.<anonymous> (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/babili-webpack-plugin/lib/index.js:106:11)
[0]     at Compilation.applyPluginsAsyncSeries (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:206:13)
[0]     at self.applyPluginsAsync.err (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:666:10)
[0]     at Compilation.applyPluginsAsyncSeries (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:195:46)
    at sealPart2 (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:662:9)
[0]     at Compilation.applyPluginsAsyncSeries (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:195:46)
[0]     at Compilation.seal (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:605:8)
[0]     at applyPluginsParallel.err (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compiler.js:504:17)
[0]     at /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:289:11
[0]     at _addModuleChain (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:507:11)
[0]     at processModuleDependencies.err (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:477:14)
[0]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[0] npm ERR! asystguard@2.1.0 build-main: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the asystguard@2.1.0 build-main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /Users/deepakumari/.npm/_logs/2017-12-28T12_07_54_262Z-debug.log
[0] npm run build-main exited with code 1
[1] /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
[1]         throw new Error(
[1]         ^
[1]
[1] Error: original.line and original.column are not numbers -- you probably meant to omit the originalmapping entirely and only map the generated position. If so, pass null for the original mapping insteadof an object with empty or null values.
[1]     at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
[1]     at SourceMapGenerator_addMapping [as addMapping] (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
[1]     at /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
[1]     at Array.forEach (<anonymous>)
[1]     at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
[1]     at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
[1]     at SourceMapSource.node (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
[1]     at SourceMapSource.proto.sourceAndMap (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
[1]     at getTaskForFile (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
[1]     at chunk.files.forEach.file (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
[1]     at Array.forEach (<anonymous>)
[1]     at /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/SourceMapDevToolPlugin.js:89:18
    at Array.forEach (<anonymous>)
[1]     at Compilation.<anonymous> (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:12)
[1]     at Compilation.applyPlugins1 (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:75:14)
[1]     at self.applyPluginsAsync.err (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:670:11)
[1]     at next (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:202:11)
[1]     at Compilation.<anonymous> (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/babili-webpack-plugin/lib/index.js:106:11)
[1]     at Compilation.applyPluginsAsyncSeries (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:206:13)
[1]     at self.applyPluginsAsync.err (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:666:10)
[1]     at next (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:202:11)
[1]     at ExtractTextPlugin.<anonymous> (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/extract-text-webpack-plugin/index.js:345:4)
[1]     at Compilation.applyPluginsAsyncSeries (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:206:13)
[1]     at sealPart2 (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.js:662:9)
[1]     at next (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:202:11)
[1]     at ExtractTextPlugin.<anonymous> (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/extract-text-webpack-plugin/index.js:317:5)
[1]     at /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/async/dist/async.js:473:16
[1]     at iteratorCallback (/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/async/dist/async.js:1050:13)
[1]     at /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/async/dist/async.js:958:16
[1]     at /Users/deepakumari/Desktop/Asystguard-Mac/node_modules/extract-text-webpack-plugin/index.js:301:6
[1] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[1] npm ERR! asystguard@2.1.0 build-renderer: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors`
[1] npm ERR! Exit status 1
[1] npm ERR!
npm ERR! Failed at the asystguard@2.1.0 build-renderer script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /Users/deepakumari/.npm/_logs/2017-12-28T12_08_47_597Z-debug.log
[1] npm run build-renderer exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! asystguard@2.1.0 build: `concurrently "npm run build-main" "npm run build-renderer" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the asystguard@2.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deepakumari/.npm/_logs/2017-12-28T12_08_47_645Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

COMPLETE LOG :

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle asystguard@2.1.0~prebuild: asystguard@2.1.0
6 info lifecycle asystguard@2.1.0~build: asystguard@2.1.0
7 verbose lifecycle asystguard@2.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle asystguard@2.1.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/.bin:/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/Users/deepakumari/Desktop/Asystguard-Mac/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/bin/node_modules/npm/bin/node-gyp-bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin
9 verbose lifecycle asystguard@2.1.0~build: CWD: /Users/deepakumari/Desktop/Asystguard-Mac
10 silly lifecycle asystguard@2.1.0~build: Args: [ '-c',
10 silly lifecycle   'concurrently "npm run build-main" "npm run build-renderer" ' ]
11 silly lifecycle asystguard@2.1.0~build: Returned: code: 1  signal: null
12 info lifecycle asystguard@2.1.0~build: Failed to exec build script
13 verbose stack Error: asystguard@2.1.0 build: `concurrently "npm run build-main" "npm run build-renderer" `
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid asystguard@2.1.0
15 verbose cwd /Users/deepakumari/Desktop/Asystguard-Mac
16 verbose Darwin 17.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error asystguard@2.1.0 build: `concurrently "npm run build-main" "npm run build-renderer" `
22 error Exit status 1
23 error Failed at the asystguard@2.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by develar** [comment]
Error is not related to electron-builder. It is webpack issue. Please update webpack and other your build tools versions.
