### ISSUE TITLE
Error running yarn dist "original.line and original.column are not numbers"

### ISSUE THREAD

**Issue by thealexbaron** [electron-userland/electron-builder#2428]
* **Version**: 19.50.0

* **Target**: Windows

I get this error whenever I run `yarn dist`

```
inlineofire@rsis-desktop MINGW64 ~/Desktop/new-electron-webpack-project (master)
$ yarn dist
yarn run v1.3.2
$ cross-env NODE_ENV=development yarn compile && electron-builder
$ electron-webpack
 51% [0] chunk asset optimization
C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:276
        throw new Error(
              ^
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:110:12)
    at C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:72:17
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack-sources\node_modules\source-map\lib\source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:48:24)
    at SourceMapSource.node (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack-sources\lib\SourceMapSource.js:32:35)
    at C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack-sources\lib\ConcatSource.js:59:50
    at Array.map (<anonymous>)
    at ConcatSource.node (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack-sources\lib\ConcatSource.js:58:63)
    at ConcatSource.proto.sourceAndMap (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack-sources\lib\SourceAndMapMixin.js:30:18)
    at getTaskForFile (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack\lib\SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack\lib\SourceMapDevToolPlugin.js:91:21)
    at Array.forEach (<anonymous>)
    at C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack\lib\SourceMapDevToolPlugin.js:89:18
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack\lib\SourceMapDevToolPlugin.js:88:12)
    at Compilation.applyPlugins1 (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\tapable\lib\Tapable.js:75:14)
    at self.applyPluginsAsync.err (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack\lib\Compilation.js:670:11)
    at next (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack\lib\ProgressPlugin.js:119:6)
    at next (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\tapable\lib\Tapable.js:204:14)
    at Compilation.compilation.plugin (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack\lib\BannerPlugin.js:67:5)
    at next (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\tapable\lib\Tapable.js:204:14)
    at Compilation.<anonymous> (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\babel-minify-webpack-plugin\dist\index.js:119:11)
    at Compilation.applyPluginsAsyncSeries (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\tapable\lib\Tapable.js:206:13)
    at self.applyPluginsAsync.err (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack\lib\Compilation.js:666:10)
    at next (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\webpack\lib\ProgressPlugin.js:115:6)
    at Compilation.applyPluginsAsyncSeries (C:\Users\inlineofire\Desktop\new-electron-webpack-project\node_modules\tapable\lib\Tapable.js:206:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I can share the whole repo if necessary but there isn't much to it. Is there something obvious I'm missing?

**Comment by Dorkside** [comment]
I've got the exact same problem, any news ?

**Comment by the-darc** [comment]
I got the same problem here. There is a workaround in [electron-userland/electron-webpack-quick-start #14](https://github.com/electron-userland/electron-webpack-quick-start/issues/14).

**Comment by thealexbaron** [comment]
Yep, @the-darc is right. That is the work around that I used as well. I added the following to my `package.json`:

```
  "resolutions": {
    "webpack-sources": "1.0.1"
  },
  "dependencies": {
    "webpack-sources": "1.0.1"
  }
```

I'm keeping an eye on these tickets to update once the actual fix is in of course.
