### ISSUE TITLE
TypeError: _this.logBuilding is not a function ... node_modules\electron-builder-squirrel-windows\src\SquirrelWindowsTarget.ts:30:10

### ISSUE THREAD

**Issue by nandodutra** [electron-userland/electron-builder#2429]
* **Version**: 19.50.0

* **Target**: win

Hi, i've the following output on the building process:

```
electron-builder 19.50.0
No native production dependencies
Packaging for win32 x64 using electron 1.7.10 to dist\win-unpacked
TypeError: _this.logBuilding is not a function
    at C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-squirrel-windows\src\SquirrelWindowsTarget.ts:30:10
    at next (native)
From previous event:
    at SquirrelWindowsTarget.build (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-squirrel-windows\out\SquirrelWindowsTarget.js:83:11)
    at taskManager.addTask.default.map.it (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-lib\src\platformPackager.ts:120:85)
From previous event:
    at WinPackager.packageInDistributableFormat (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-lib\src\platformPackager.ts:120:41)
    at C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-lib\src\platformPackager.ts:116:10
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at WinPackager.pack (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-lib\out\platformPackager.js:195:11)
    at C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-lib\src\packager.ts:345:24
    at next (native)
    at xfs.stat (C:\Users\Fernando\siafplus_pdv\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\Fernando\siafplus_pdv\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager.doBuild (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-lib\out\packager.js:407:11)
    at C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-lib\src\packager.ts:289:52
From previous event:
    at Packager._build (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-lib\out\packager.js:351:11)
    at C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-lib\src\packager.ts:259:23
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder-lib\out\packager.js:311:11)
    at C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder\src\builder.ts:287:40
    at next (native)
From previous event:
    at _build (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder\out\builder.js:61:21)
    at build (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder\src\builder.ts:257:10)
    at then (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\Users\Fernando\siafplus_pdv\node_modules\yargs\lib\command.js:228:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\Fernando\siafplus_pdv\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (C:\Users\Fernando\siafplus_pdv\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\Fernando\siafplus_pdv\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

Any one know how fix this issue? Thanks!

**Comment by develar** [comment]
It seems you have updated `electron-builder-squirrel-windows` to 19.51.0, but electron-builder 19.51.0 was not updated. I have marked 19.51.0 as latest, please update.

**Comment by develar** [comment]
BTW, consider to use default NSIS target.
