### ISSUE TITLE
Missing library after packaging mac app (libzmq)

### ISSUE THREAD

**Issue by lzkelley** [electron-userland/electron-builder#2434]
* **Version**:     "electron-builder": "^19.52.1",

* **Target**: electron 1.8.1

I'm able to get my application to work in development by running `npm install` and then rebuilding `zmq` and `zerorpc` to match the electron version (e.g. `npm rebuild zmq --runtime=electron --target=1.8.1`).  This process seems to be very temperamental, but in general works.  When I run the packaged application (i.e. double-clicking the `dist/mac/app`) after using my build script (`npm run dist`), however, it fails to find a required library (error below).  I have no idea what I'm doing (totally electron and node noobie); but could the error be that `zmq` isn't being rebuilt in the packaged version?  Any suggestions would be greatly appreciated!

**package.json**

```
{
  [...METADATA...]
  "main": "./app/main.js",
  "scripts": {
    "postinstall": "electron-builder install-app-deps",
    "start": "electron .",
    "pack": "build --dir",
    "dist": "build"
  },
  "build": {
    "appId": "cosmo",
    "dmg": {
      "contents": [
        {
          "x": 110,
          "y": 150
        },
        {
          "x": 240,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "linux": {
      "target": [
        "AppImage",
        "deb"
      ]
    }
  },
  "devDependencies": {
    "electron": "^1.8.1",
    "electron-builder": "^19.52.1",
    "electron-rebuild": "^1.6.0"
  },
  "dependencies": {
    "electron-debug": "^1.5.0",
    "sprintf-js": "^1.1.1",
    "zerorpc": "^0.9.7",
    "zmq": "^2.15.3"
  }
}

```

**Error Message (via console):**

```
/Users/lzkelley/Programs/cosmo/dist/mac/cosmo.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:83 Uncaught Error: dlopen(/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/.cosmo.vhDgTh, 1): Library not loaded: @rpath/libzmq.5.1.2.dylib
  Referenced from: /var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/.cosmo.vhDgTh
  Reason: image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/Users/lzkelley/Programs/cosmo/dist/mac/cosmo.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/lzkelley/Programs/cosmo/dist/mac/cosmo.app/Contents/Resources/app.asar/node_modules/zmq/lib/index.js:6:30)
plot.js:509 DATA_FILE_PATH =  /Users/lzkelley/Programs/cosmo/dist/mac/cosmo.app/Contents/Resources/app.asar/app/data/cosmo_grid.csv

```

**Comment by lzkelley** [comment]
This was not an issue with electron-builder.  The problem was that the library was installed using a particular version of python (python2 in this case), while I built the package using a different python (python3).  Using the same python to install the modules and to package the app solved the problem.
