### ISSUE TITLE
build in windows breaks after upgrade to 19.53.3

### ISSUE THREAD

**Issue by zxdong262** [electron-userland/electron-builder#2458]
* **Version**:  19.53.3

* **Target**:   windows target: ["tar.gz"]

after upgrade from 19.45.5 to 19.53.3, windows build breaks(while linux and mac build still ok), logs at https://ci.appveyor.com/project/zxdong262/electerm/build/1.0.47,
```bash
downloading     path=C:\Users\appveyor\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.3.0-x64 url=https://github.com/develar/app-builder/releases/download/v0.3.0/app-builder-v0.3.0-win-x64.7z
SyntaxError: Unexpected token p in JSON at position 19
SyntaxError: Unexpected token p in JSON at position 19
    at JSON.parse (<anonymous>)
    at C:\projects\electerm\node_modules\electron-builder-lib\src\platformPackager.ts:593:25
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\projects\electerm\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\projects\electerm\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (C:\projects\electerm\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (C:\projects\electerm\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\projects\electerm\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\projects\electerm\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\projects\electerm\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\projects\electerm\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.resolveIcon (C:\projects\electerm\node_modules\electron-builder-lib\out\platformPackager.js:631:11)
    at C:\projects\electerm\node_modules\electron-builder-lib\src\platformPackager.ts:576:25
    at Generator.next (<anonymous>)
    at WinPackager.getOrConvertIcon (C:\projects\electerm\node_modules\electron-builder-lib\out\platformPackager.js:612:11)
    at Lazy.WinPackager._iconPath.Lazy (C:\projects\electerm\node_modules\electron-builder-lib\src\winPackager.ts:60:43)
    at Lazy.get value [as value] (C:\projects\electerm\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (C:\projects\electerm\node_modules\electron-builder-lib\src\winPackager.ts:200:27)
    at C:\projects\electerm\node_modules\electron-builder-lib\src\winPackager.ts:297:33
    at Generator.next (<anonymous>)
    at WinPackager.signAndEditResources (C:\projects\electerm\node_modules\electron-builder-lib\out\winPackager.js:414:11)
    at C:\projects\electerm\node_modules\electron-builder-lib\src\winPackager.ts:348:18
From previous event:
    at WinPackager.getOrConvertIcon (C:\projects\electerm\node_modules\electron-builder-lib\out\platformPackager.js:612:11)
    at Lazy.WinPackager._iconPath.Lazy (C:\projects\electerm\node_modules\electron-builder-lib\src\winPackager.ts:60:43)
    at Lazy.get value [as value] (C:\projects\electerm\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (C:\projects\electerm\node_modules\electron-builder-lib\src\winPackager.ts:200:27)
    at C:\projects\electerm\node_modules\electron-builder-lib\src\winPackager.ts:297:33
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signAndEditResources (C:\projects\electerm\node_modules\electron-builder-lib\out\winPackager.js:414:11)
    at C:\projects\electerm\node_modules\electron-builder-lib\src\winPackager.ts:348:18
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (C:\projects\electerm\node_modules\electron-builder-lib\out\winPackager.js:432:11)
    at C:\projects\electerm\node_modules\electron-builder-lib\src\platformPackager.ts:217:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (C:\projects\electerm\node_modules\electron-builder-lib\out\platformPackager.js:289:11)
    at C:\projects\electerm\node_modules\electron-builder-lib\src\platformPackager.ts:117:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\projects\electerm\node_modules\electron-builder-lib\out\platformPackager.js:207:11)
    at C:\projects\electerm\node_modules\electron-builder-lib\src\packager.ts:361:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\projects\electerm\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\projects\electerm\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (C:\projects\electerm\node_modules\electron-builder-lib\out\packager.js:423:11)
    at C:\projects\electerm\node_modules\electron-builder-lib\src\packager.ts:305:52
From previous event:
    at Packager._build (C:\projects\electerm\node_modules\electron-builder-lib\out\packager.js:367:11)
    at C:\projects\electerm\node_modules\electron-builder-lib\src\packager.ts:267:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (C:\projects\electerm\node_modules\electron-builder-lib\out\packager.js:323:11)
    at C:\projects\electerm\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\projects\electerm\node_modules\electron-builder\out\builder.js:61:21)
    at build (C:\projects\electerm\node_modules\electron-builder\src\builder.ts:280:10)
    at then (C:\projects\electerm\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\projects\electerm\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\projects\electerm\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\projects\electerm\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (C:\projects\electerm\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\projects\electerm\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electerm@0.13.0 output: `electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electerm@0.13.0 output script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2018-01-09T10_03_29_689Z-debug.lo
```

 I doubt it is related to the icon part.
```js
//my electron-builder.json
  "win": {
    "target": ["tar.gz"],
    "icon": "node_modules/electerm-resource/build/icons.ico"
  },
```

and `19.53.1` works

**Comment by develar** [comment]
Thanks for using pre-release version, will be fixed and investigated in 2 days.

**Comment by frankLife** [comment]
I have come cross the same problem. What version can we use instead now?

**Comment by develar** [comment]
Latest stable release is `19.52.1`.
