### ISSUE TITLE
MacUpdater error

### ISSUE THREAD

**Issue by bstegman** [electron-userland/electron-builder#2459]
electron-builder 19.52.1
electron-updater 2.18.2
targets: zip, dmg

On mac when I release a new version I get the update-downloaded event like expected but then I get a popup with the following error.

Uncaught Exception:
TypeError: (_electron || _load_electron(...)).Notification is not a constructor
    at MacUpdater.signals.updateDownloaded.it (Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:219:7)
    at emitOne (events.js:101:20)
    at MacUpdater.emit (events.js:188:7)
    at AutoUpdater.MacUpdater.nativeUpdater.on (Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:21:12)
    at emitMany (events.js:127:13)
    at AutoUpdater.emit (events.js:201:7)

**Comment by develar** [comment]
Electron version?

**Comment by bstegman** [comment]
Version 1.6.15

**Comment by develar** [comment]
Please try to use latest 1.7.10

**Comment by bstegman** [comment]
Okay .. will do

**Comment by bstegman** [comment]
that fixed it.. thanks
