### ISSUE TITLE
image must be at least 256x256

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#2462]
* **Version**: 19.53.4

* **Target**: NSIS Web Win x64 and ia32

Building my app now always results in the following error:

```
image C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\build\icon.ico must be at least 256x256
```

The `.ico` file is 256x256, I tried also using the 1024x1024 png version of my icon in the build folder but then it applies an icon that has horribly jagged edges.

I tried downgrading (used to work with **19.53.3**), but since today there is some unlocked dependency that is not compatible with **19.53.3** which causes a bunch of errors when I try to build with the downgraded version:

ERRORS RELATED TO **19.53.3** AS OF TODAY

```
• electron-builder version=19.53.3
• loaded configuration file=C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\electron-builder.yml
• writing effective config file=dist\electron-builder.yaml
• skipped app dependencies rebuild reason=npmRebuild is set to false
• packaging       platform=win32 arch=x64 electron=1.8.2-beta.3 appOutDir=dist\win-unpacked

SyntaxError: Unexpected token U in JSON at position 19
SyntaxError: Unexpected token U in JSON at position 19
  at JSON.parse (<anonymous>)
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\src\platformPackager.ts:593:25
  at Generator.next (<anonymous>)
  at Generator.tryCatcher (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\bluebird\js\release\util.js:16:23)
  at PromiseSpawn._promiseFulfilled (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\bluebird\js\release\generators.js:97:49)
  at Promise._settlePromise (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\bluebird\js\release\promise.js:574:26)
  at Promise._settlePromise0 (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\bluebird\js\release\promise.js:614:10)
  at Promise._settlePromises (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\bluebird\js\release\promise.js:693:18)
  at Async._drainQueue (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\bluebird\js\release\async.js:133:16)
  at Async._drainQueues (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\bluebird\js\release\async.js:143:10)
  at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\bluebird\js\release\async.js:17:14)
  at runCallback (timers.js:773:18)
  at tryOnImmediate (timers.js:734:5)
  at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
  at WinPackager.resolveIcon (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\out\platformPackager.js:631:11)
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\src\platformPackager.ts:583:27
  at Generator.next (<anonymous>)
  at go$readdir$cb (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\graceful-fs\graceful-fs.js:149:14)
  at FSReqWrap.oncomplete (fs.js:149:20)
From previous event:
  at WinPackager.getOrConvertIcon (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\out\platformPackager.js:612:11)
  at Lazy.WinPackager._iconPath.Lazy (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:60:43)
  at Lazy.get value [as value] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\lazy-val\src\main.ts:18:23)
  at WinPackager.getIconPath (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:200:27)
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:297:33
  at Generator.next (<anonymous>)
From previous event:
  at WinPackager.signAndEditResources (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\out\winPackager.js:414:11)
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:348:18
  at Generator.next (<anonymous>)
From previous event:
  at WinPackager.signApp (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\out\winPackager.js:432:11)
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\src\platformPackager.ts:217:16
  at Generator.next (<anonymous>)
  at runCallback (timers.js:773:18)
  at tryOnImmediate (timers.js:734:5)
  at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
  at WinPackager.doPack (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\out\platformPackager.js:289:11)
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\src\platformPackager.ts:117:16
  at Generator.next (<anonymous>)
From previous event:
  at WinPackager.pack (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\out\platformPackager.js:207:11)
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:361:24
  at Generator.next (<anonymous>)
  at xfs.mkdir.er (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
From previous event:
  at Packager.doBuild (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\out\packager.js:423:11)
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:305:52
  at Generator.next (<anonymous>)
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\graceful-fs\graceful-fs.js:99:16
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\graceful-fs\graceful-fs.js:43:10
  at FSReqWrap.oncomplete (fs.js:149:20)
From previous event:
  at Packager._build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\out\packager.js:367:11)
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:267:23
  at Generator.next (<anonymous>)
  at runCallback (timers.js:773:18)
  at tryOnImmediate (timers.js:734:5)
  at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
  at Packager.build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\node_modules\electron-builder-lib\out\packager.js:323:11)
  at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\builder.ts:310:40
  at Generator.next (<anonymous>)
From previous event:
  at _build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\builder.js:61:21)
  at build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\builder.ts:280:10)
  at then (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:49:4)
  at runCallback (timers.js:773:18)
  at tryOnImmediate (timers.js:734:5)
  at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
  at Object.args [as handler] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:49:4)
  at Object.runCommand (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\lib\command.js:235:44)
  at Object.parseArgs [as _parseArgs] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\yargs.js:1041:24)
  at Object.get [as argv] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\yargs.js:957:21)
  at Object.<anonymous> (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:43:15)
  at Module._compile (module.js:660:30)
  at Object.Module._extensions..js (module.js:671:10)
  at Module.load (module.js:573:32)
  at tryModuleLoad (module.js:513:12)
  at Function.Module._load (module.js:505:3)
  at Function.Module.runMain (module.js:701:10)
  at startup (bootstrap_node.js:194:16)
  at bootstrap_node.js:618:3
```

**Comment by develar** [comment]
Please attach your icon.

**Comment by HitomiTenshi** [comment]
[icon.zip](https://github.com/electron-userland/electron-builder/files/1622413/icon.zip)

**Comment by HitomiTenshi** [comment]
Version **19.53.2** seems to work as expected.

**Comment by d-schloss-mvg** [comment]
I confirm for **19.53.4**

Working: **19.52.1**

**Comment by scottnonnenberg** [comment]
I'm reproducing this on `19.53.4` with an `.ico` a that has a full complement of sizes: 16px all the way to 256px, verified by extracting components via imagemagick. I do note that windows explorer's 'details' tab shows the file as 128x128, but the file has all sizes.

**Comment by develar** [comment]
If you have this bug for 19.53.5 — please attach icon.

**Comment by HitomiTenshi** [comment]
@develar Problem fixed on my side with **19.53.5**, thanks!

**Comment by deoxyseia** [comment]
I have the same problem building for Mac. I'm using electron-builder 20.36.2.

**Comment by flaschbier** [comment]
Same on MacOS using electron builder `21.2.0`.
Any hints?

**Comment by Blightysoft** [comment]
Same on Linux for an .ico file when packaging for AppImage using electron-builder version 21.2.0.

**Comment by astroame** [comment]
I found a solution here:

https://github.com/maximegris/angular-electron/issues/150#issuecomment-549155703

**Comment by Slapbox** [comment]
The 256x256 icons look _awful_ in the installer on Windows 11. Windows 11 seems to have a really awful downscaling algorithm compared to older versions of Windows and they appear horribly jagged. Is there any workaround for this?

We had the same issues with our Electron tray icon until we reduced the icon size, but trying to reduce the icon size here throws an error.

**Comment by aaronklinker-st** [comment]
Ran into this on v24.4.0. I first generated my ICO using a 512x512px PNG using https://cloudconvert.com/png-to-ico, but that resulted in this error.

Then I used https://redketchup.io/icon-editor with the same PNG, and it worked! 

I don't know much about the ICO file format, but I imagine one of the sizes is set as the default, and different tools default to different sizes? Not sure.

**Comment by colorpickerfromimage-ux** [comment]
I also faced the same issue and then i resolved it by using the https://colorpickerfromimage.net/
