### ISSUE TITLE
Error building on OSX High Sierra

### ISSUE THREAD

**Issue by madebynoam** [electron-userland/electron-builder#2467]
* **Version**:  19.53.4 (also tried 19.53.1)

* **Target**: DMG

I upgraded to High Sierra, and then upgraded electron-builder as well as switched to yarn. 

When I run build I run in to this error, any help would be greatly appreciated. 

• electron-builder version=19.53.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=1.7.10 appOutDir=dist/mac

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1260:5)
    at AppFileWalker.handleSymlink (/Users/MadeByNoam/Documents/VRBloq WebVR Studio/webvr-studio-beta/node_modules/electron-builder-lib/src/util/NodeModuleCopyHelper.ts:34:23)
    at /Users/MadeByNoam/Documents/VRBloq WebVR Studio/webvr-studio-beta/node_modules/electron-builder-lib/src/util/NodeModuleCopyHelper.ts:61:24
    at Generator.next (<anonymous>)
From previous event:
    at AppFileWalker.collectNodeModules (/Users/MadeByNoam/Documents/VRBloq WebVR Studio/webvr-studio-beta/node_modules/electron-builder-lib/out/util/NodeModuleCopyHelper.js:160:11)
    at then.it (/Users/MadeByNoam/Documents/VRBloq WebVR Studio/webvr-studio-beta/node_modules/electron-builder-lib/src/util/AppFileWalker.ts:54:21)
    at runCallback (timers.js:756:18)
...

**Comment by eranimo** [comment]
Also getting this same problem. Why was this closed? What is the solution?

**Comment by beliefgp** [comment]
Also getting this same problem.
