### ISSUE TITLE
TypeError: Invalid data, chunk must be a string or buffer, not object while building electron app

### ISSUE THREAD

**Issue by imolorhe** [electron-userland/electron-builder#2469]
* **Version**: ^19.52.1

* **Target**:  linux

Getting this error in Travis CI logs when building electron app for linux:

```
 • TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:654:11)
    at Socket.stream.write (/home/travis/build/imolorhe/altair/node_modules/single-line-log/index.js:12:16)
    at Logger._doLog (/home/travis/build/imolorhe/altair/node_modules/builder-util/src/log.ts:68:17)
    at Logger.doLog (/home/travis/build/imolorhe/altair/node_modules/builder-util/src/log.ts:57:12)
    at Logger.warn (/home/travis/build/imolorhe/altair/node_modules/builder-util/src/log.ts:46:10)
    at then.catch.e (/home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/src/fileTransformer.ts:34:25)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
From previous event:
    at file (/home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/src/fileTransformer.ts:34:10)
    at /home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/src/util/AppFileCopierHelper.ts:64:32
From previous event:
    at /home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/src/util/AppFileCopierHelper.ts:58:27
From previous event:
    at computeFileSets (/home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/out/util/AppFileCopierHelper.js:82:21)
    at _computeFileSets (/home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/src/platformPackager.ts:236:14)
    at LinuxPackager.copyAppFiles (/home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/src/platformPackager.ts:249:27)
    at /home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/src/platformPackager.ts:192:10
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at LinuxPackager.doPack (/home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/out/platformPackager.js:276:11)
    at /home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/src/platformPackager.ts:115:16
    at next (native)
From previous event:
    at LinuxPackager.pack (/home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/out/platformPackager.js:195:11)
    at /home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/src/packager.ts:355:24
    at next (native)
    at xfs.mkdir.er (/home/travis/build/imolorhe/altair/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager.doBuild (/home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/out/packager.js:419:11)
    at /home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/src/packager.ts:299:52
From previous event:
    at Packager._build (/home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/out/packager.js:363:11)
    at /home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/src/packager.ts:261:23
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/home/travis/build/imolorhe/altair/node_modules/electron-builder-lib/out/packager.js:319:11)
    at /home/travis/build/imolorhe/altair/node_modules/electron-builder/src/builder.ts:310:40
    at next (native)
From previous event:
    at _build (/home/travis/build/imolorhe/altair/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/travis/build/imolorhe/altair/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/home/travis/build/imolorhe/altair/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (/home/travis/build/imolorhe/altair/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/home/travis/build/imolorhe/altair/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/travis/build/imolorhe/altair/node_modules/electron-builder/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/travis/build/imolorhe/altair/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/travis/build/imolorhe/altair/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

Tracing the error, it appears it fails at this line: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-lib/src/fileTransformer.ts#L3:26

This looks like it isn't getting a package.json file content from an installed package, or something like that.

**Note:** The build executes succesfully for windows on appveyor CI.

**Comment by develar** [comment]
@imolorhe 19.53.5

**Comment by imolorhe** [comment]
@develar Thanks!

**Comment by imolorhe** [comment]
@develar I'm still getting the same error with the new version.

**Comment by imolorhe** [comment]
@develar Here's the travis build with the error: https://travis-ci.org/imolorhe/altair/jobs/328491249

**Comment by imolorhe** [comment]
It turns out there is an error in one of the package.json files in one of the installed packages, but the log library is failing to display it due to a bug in it. The actual error: `SyntaxError: Unexpected token < in JSON at position 609`
