### ISSUE TITLE
Windows ENOENT error on app-builder.exe

### ISSUE THREAD

**Issue by giokara** [electron-userland/electron-builder#2477]
* **Version**: 19.53.6

* **Target**: Windows 10 

* **Shell**: x64 Native Tools Command Prompt for VS 2017

Running electron-builder with following command: `tsc && electron-builder`

The build property of package.json:

```
  "build": {
    "productName": "Demo",
    "appId": "mycompany.Demo",
    "asar": true,
    "win": {
      "target": "nsis"
    },
    "nsis": {
      "oneClick": false,
      "allowElevation": false
    },
    "linux": {
      "target": "AppImage",
      "category": "Development"
    },
    "mac": {
      "target": "dmg"
    },
    "icon": "build/icon",
    "directories": {
      "buildResources": "/build",
      "output": "./dist"
    },
    "files": [
      "**/*.js",
      "**/*.html",
      "**/*.ts",
      "node_modules",
      "assets",
      "app"
    ],
    "extraResources": [
      {
        "from": "./build/some_api",
        "to": "some_api"
      },
      {
        "from": "./build/some_other_api",
        "to": "some_other_api"
      },
      {
        "from": "./build/some_file_path",
        "to": "some_file_path"
      },
      {
        "from": "./some_other_file_path",
        "to": "some_other_file_path"
      }
    ]
  }
```

Confirm that the above procedure works on Mac (on Linux other errors occur related to other issues already reported).

The following error occurs on running on Windows:

```
Error: Exit code: ENOENT. spawn C:\Users\Giorgos\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.4.0-x64\app-builder.exe ENOENT
    at c:\my\project\path\node_modules\builder-util\src\util.ts:122:16
    at exithandler (child_process.js:211:5)
    at ChildProcess.errorhandler (child_process.js:223:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at exec (c:\my\project\path\node_modules\builder-util\src\util.ts:85:3)
    at c:\my\project\path\node_modules\electron-builder-lib\src\platformPackager.ts:596:23
    at next (native)
    at xfs.mkdir.er (c:\my\project\path\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at WinPackager.resolveIcon (c:\my\project\path\node_modules\electron-builder-lib\out\platformPackager.js:635:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\platformPackager.ts:575:25
    at next (native)
    at WinPackager.getOrConvertIcon (c:\my\project\path\node_modules\electron-builder-lib\out\platformPackager.js:610:11)
    at Lazy.WinPackager._iconPath.Lazy (c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:60:43)
    at Lazy.get value [as value] (c:\my\project\path\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:200:17)
    at c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:297:33
    at next (native)
    at WinPackager.signAndEditResources (c:\my\project\path\node_modules\electron-builder-lib\out\winPackager.js:414:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:348:18
From previous event:
    at WinPackager.getOrConvertIcon (c:\my\project\path\node_modules\electron-builder-lib\out\platformPackager.js:610:11)
    at Lazy.WinPackager._iconPath.Lazy (c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:60:43)
    at Lazy.get value [as value] (c:\my\project\path\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:200:17)
    at c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:297:33
    at next (native)
From previous event:
    at WinPackager.signAndEditResources (c:\my\project\path\node_modules\electron-builder-lib\out\winPackager.js:414:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:348:18
    at next (native)
From previous event:
    at WinPackager.signApp (c:\my\project\path\node_modules\electron-builder-lib\out\winPackager.js:432:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\platformPackager.ts:216:16
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at WinPackager.doPack (c:\my\project\path\node_modules\electron-builder-lib\out\platformPackager.js:283:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\platformPackager.ts:116:16
    at next (native)
From previous event:
    at WinPackager.pack (c:\my\project\path\node_modules\electron-builder-lib\out\platformPackager.js:201:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\packager.ts:361:24
    at next (native)
    at xfs.stat (c:\my\project\path\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at c:\my\project\path\node_modules\graceful-fs\polyfills.js:287:18
From previous event:
    at Packager.doBuild (c:\my\project\path\node_modules\electron-builder-lib\out\packager.js:423:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\packager.ts:305:52
    at next (native)
    at c:\my\project\path\node_modules\graceful-fs\graceful-fs.js:99:16
    at c:\my\project\path\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager._build (c:\my\project\path\node_modules\electron-builder-lib\out\packager.js:367:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\packager.ts:267:23
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (c:\my\project\path\node_modules\electron-builder-lib\out\packager.js:323:11)
    at c:\my\project\path\node_modules\electron-builder\src\builder.ts:310:40
    at next (native)
From previous event:
    at _build (c:\my\project\path\node_modules\electron-builder\out\builder.js:61:21)
    at build (c:\my\project\path\node_modules\electron-builder\src\builder.ts:280:10)
    at then (c:\my\project\path\node_modules\electron-builder\src\cli\cli.ts:49:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (c:\my\project\path\node_modules\electron-builder\src\cli\cli.ts:49:33)
    at Object.runCommand (c:\my\project\path\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (c:\my\project\path\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (c:\my\project\path\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (c:\my\project\path\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

**Comment by andycreeth** [comment]
I am also having this issue.  I did a little investigation and it seems that `19.53.3` is the first version with this issue.  Let me know if I can help debug.

**Comment by mykter** [comment]
I'm getting this issue on Mac and Windows. Not Linux.
Also found it works on 19.53.2 and not 19.53.3

**Comment by develar** [comment]
Works for me. Both on CI and local Windows 10 VM. Is file `Caches/electron-builder/app-builder/app-builder-v0.4.0-x64/app-builder` exists?

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder`.

**Comment by develar** [comment]
Maybe it will be fixed in 19.53.7

**Comment by giokara** [comment]
Checked, app-builder.exe exists in the mentioned directory.

Below the output with` DEBUG=electron-builder` flag.
```

  • electron-builder version=19.53.6
  • loaded configuration file=package.json ("build" field)
  • effective config config=
                       directories:
                         output: ./dist
                         buildResources: /build
                       productName: Demo
                       appId: mycompany.Demo
                       asar: true
                       win:
                         target: nsis
                       nsis:
                         oneClick: false
                         allowElevation: false
                       linux:
                         target: AppImage
                         category: Development
                       mac:
                         target: dmg
                       icon: build/icon
                       files:
                         - '**/*.js'
                         - '**/*.html'
                         - '**/*.ts'
                         - node_modules
                         - assets
                         - app
                       extraResources:
                         - from: ./build/some_api
                           to: some_api
                         - from: ./build/some_other_api
                           to: some_other_api
                         - from: ./build/some_file_path
                           to: some_file_path
                         - from: ./some_other_file_path
                           to: some_other_file_path

  • writing effective config file=dist\electron-builder.yaml
  • Unresolved dependencies after first round unresolved=fsevents
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.7.10 appOutDir=dist\win-unpacked
  • spawning        command=c:\my\project\path\node_modules\7zip-bin-win\x64\7za.exe args=x -bd C:\Users\Giorgos\AppData\Local\electron\Cache\electron-v1.7.10-win32-x64.zip -aoa -oc:\my\project\path\dist\win-unpacked

7-Zip (a) 17.01 beta (x64) : Copyright (c) 1999-2017 Igor Pavlov : 2017-08-28

Scanning the drive for archives:
1 file, 53893268 bytes (52 MiB)

Extracting archive: C:\Users\Giorgos\AppData\Local\electron\Cache\electron-v1.7.10-win32-x64.zip
--
Path = C:\Users\Giorgos\AppData\Local\electron\Cache\electron-v1.7.10-win32-x64.zip
Type = zip
Physical Size = 53893268

Everything is Ok

Files: 117
Size:       138386651
Compressed: 53893268
  • exited          command=7za.exe code=0 pid=10420
  • copying files using pattern matcher=from: c:\my\project\path\build\robot-parts, to: c:\my\project\path\dist\win-unpacked\resources\robot-parts, patterns: **/*
  • copying         src=c:\my\project\path\build\robot-parts destination=c:\my\project\path\dist\win-unpacked\resources\robot-parts
  • copying files using pattern matcher=from: c:\my\project\path\precomputedfiles, to: c:\my\project\path\dist\win-unpacked\resources\precomputedfiles, patterns: **/*
  • copying         src=c:\my\project\path\precomputedfiles destination=c:\my\project\path\dist\win-unpacked\resources\precomputedfiles
  • getPublishConfigsForUpdateInfo: no publishConfigs, detect using repository info
  • found existing  path=C:\Users\Giorgos\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.4.0-x64
  • executing       file=C:\Users\Giorgos\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.4.0-x64\app-builder.exe args=icon --input build/icon --format ico --root c:\build --root c:\my\project\path cwd=c:\build env=
                      {
                        "DEBUG": "true",
                        "TMPDIR": "C:\\Users\\Giorgos\\AppData\\Local\\Temp\\temp-dir-fDHNbw\\icons-0"
                      }
Error: Exit code: ENOENT. spawn C:\Users\Giorgos\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.4.0-x64\app-builder.exe ENOENT
    at c:\my\project\path\node_modules\builder-util\src\util.ts:122:16
    at exithandler (child_process.js:211:5)
    at ChildProcess.errorhandler (child_process.js:223:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at exec (c:\my\project\path\node_modules\builder-util\src\util.ts:85:3)
    at c:\my\project\path\node_modules\electron-builder-lib\src\platformPackager.ts:596:23
    at next (native)
    at xfs.mkdir.er (c:\my\project\path\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at WinPackager.resolveIcon (c:\my\project\path\node_modules\electron-builder-lib\out\platformPackager.js:635:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\platformPackager.ts:575:25
    at next (native)
    at WinPackager.getOrConvertIcon (c:\my\project\path\node_modules\electron-builder-lib\out\platformPackager.js:610:11)
    at Lazy.WinPackager._iconPath.Lazy (c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:60:43)
    at Lazy.get value [as value] (c:\my\project\path\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:200:17)
    at c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:297:33
    at next (native)
    at WinPackager.signAndEditResources (c:\my\project\path\node_modules\electron-builder-lib\out\winPackager.js:414:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:348:18
From previous event:
    at WinPackager.getOrConvertIcon (c:\my\project\path\node_modules\electron-builder-lib\out\platformPackager.js:610:11)
    at Lazy.WinPackager._iconPath.Lazy (c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:60:43)
    at Lazy.get value [as value] (c:\my\project\path\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:200:17)
    at c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:297:33
    at next (native)
From previous event:
    at WinPackager.signAndEditResources (c:\my\project\path\node_modules\electron-builder-lib\out\winPackager.js:414:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\winPackager.ts:348:18
    at next (native)
From previous event:
    at WinPackager.signApp (c:\my\project\path\node_modules\electron-builder-lib\out\winPackager.js:432:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\platformPackager.ts:216:16
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at WinPackager.doPack (c:\my\project\path\node_modules\electron-builder-lib\out\platformPackager.js:283:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\platformPackager.ts:116:16
    at next (native)
From previous event:
    at WinPackager.pack (c:\my\project\path\node_modules\electron-builder-lib\out\platformPackager.js:201:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\packager.ts:361:24
    at next (native)
    at xfs.stat (c:\my\project\path\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at c:\my\project\path\node_modules\graceful-fs\polyfills.js:287:18
From previous event:
    at Packager.doBuild (c:\my\project\path\node_modules\electron-builder-lib\out\packager.js:423:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\packager.ts:305:52
    at next (native)
    at c:\my\project\path\node_modules\graceful-fs\graceful-fs.js:99:16
    at c:\my\project\path\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager._build (c:\my\project\path\node_modules\electron-builder-lib\out\packager.js:367:11)
    at c:\my\project\path\node_modules\electron-builder-lib\src\packager.ts:267:23
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (c:\my\project\path\node_modules\electron-builder-lib\out\packager.js:323:11)
    at c:\my\project\path\node_modules\electron-builder\src\builder.ts:310:40
    at next (native)
From previous event:
    at _build (c:\my\project\path\node_modules\electron-builder\out\builder.js:61:21)
    at build (c:\my\project\path\node_modules\electron-builder\src\builder.ts:280:10)
    at then (c:\my\project\path\node_modules\electron-builder\src\cli\cli.ts:49:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (c:\my\project\path\node_modules\electron-builder\src\cli\cli.ts:49:33)
    at Object.runCommand (c:\my\project\path\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (c:\my\project\path\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (c:\my\project\path\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (c:\my\project\path\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

**Comment by develar** [comment]
@giokara Please try to execute `C:\Users\Giorgos\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.4.0-x64\app-builder.exe` in terminal.

**Comment by giokara** [comment]
Terminal output:

```
usage: app-builder [<flags>] <command> [<args> ...]

app-builder

Flags:
  --help     Show context-sensitive help (also try --help-long and --help-man).
  --version  Show application version.

Commands:
  help [<command>...]
    Show help.

  icns-to-png --input=INPUT
    convert ICNS to PNG

  icon --input=INPUT --format=FORMAT [<flags>]
    create ICNS or ICO from PNG files

  collect-icons --source=SOURCE
    collect icons in a dir

  blockmap --input=INPUT [<flags>]
    Generates file block map for differential update using content defined
    chunking (that is robust to insertions, deletions, and changes to input
    file)

  asar --output=OUTPUT
```

**Comment by coopernyc** [comment]
same issue
> ROME@3.3.0 pack C:\_projects\CoreElectron
> electron-builder -w --x64 --project build --dir

  • electron-builder version=19.53.7
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist\electron-builder.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.7.10 appOutDir=dist\win-unpacked
  • downloading     path=C:\Users\akuprikov\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.5.0-x64 url=https://github.com/develar/app-builder/releases/download/v0.5.0/app-builder-v0.5.0-win-x64.7z
Error: Exit code: ENOENT. spawn C:\Users\akuprikov\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.5.0-x64\app-builder.exe ENOENT
    at C:\_projects\CoreElectron\node_modules\builder-util\src\util.ts:122:16
    at exithandler (child_process.js:282:5)
    at ChildProcess.errorhandler (child_process.js:294:5)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at exec (C:\_projects\CoreElectron\node_modules\builder-util\src\util.ts:85:3)
    at C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\platformPackager.ts:596:23
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (C:\_projects\CoreElectron\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at WinPackager.resolveIcon (C:\_projects\CoreElectron\node_modules\electron-builder-lib\out\platformPackager.js:635:11)
    at C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\platformPackager.ts:575:25
    at Generator.next (<anonymous>)
    at WinPackager.getOrConvertIcon (C:\_projects\CoreElectron\node_modules\electron-builder-lib\out\platformPackager.js:610:11)
    at Lazy.WinPackager._iconPath.Lazy (C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\winPackager.ts:60:43)
    at Lazy.get value [as value] (C:\_projects\CoreElectron\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\winPackager.ts:200:27)
    at C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\winPackager.ts:297:33
    at Generator.next (<anonymous>)
    at WinPackager.signAndEditResources (C:\_projects\CoreElectron\node_modules\electron-builder-lib\out\winPackager.js:414:11)
    at C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\winPackager.ts:348:18
From previous event:
    at WinPackager.getOrConvertIcon (C:\_projects\CoreElectron\node_modules\electron-builder-lib\out\platformPackager.js:610:11)
    at Lazy.WinPackager._iconPath.Lazy (C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\winPackager.ts:60:43)
    at Lazy.get value [as value] (C:\_projects\CoreElectron\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\winPackager.ts:200:27)
    at C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\winPackager.ts:297:33
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signAndEditResources (C:\_projects\CoreElectron\node_modules\electron-builder-lib\out\winPackager.js:414:11)
    at C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\winPackager.ts:348:18
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (C:\_projects\CoreElectron\node_modules\electron-builder-lib\out\winPackager.js:432:11)
    at C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\platformPackager.ts:216:16
From previous event:
    at WinPackager.doPack (C:\_projects\CoreElectron\node_modules\electron-builder-lib\out\platformPackager.js:283:11)
    at C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\platformPackager.ts:116:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\_projects\CoreElectron\node_modules\electron-builder-lib\out\platformPackager.js:201:11)
    at C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\packager.ts:361:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.doBuild (C:\_projects\CoreElectron\node_modules\electron-builder-lib\out\packager.js:423:11)
    at C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\packager.ts:305:52
    at Generator.next (<anonymous>)
    at C:\_projects\CoreElectron\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\_projects\CoreElectron\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\_projects\CoreElectron\node_modules\electron-builder-lib\out\packager.js:367:11)
    at C:\_projects\CoreElectron\node_modules\electron-builder-lib\src\packager.ts:267:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (C:\_projects\CoreElectron\node_modules\electron-builder-lib\out\packager.js:323:11)
    at C:\_projects\CoreElectron\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\_projects\CoreElectron\node_modules\electron-builder\out\builder.js:61:21)
    at build (C:\_projects\CoreElectron\node_modules\electron-builder\src\builder.ts:280:10)
    at then (C:\_projects\CoreElectron\node_modules\electron-builder\src\cli\cli.ts:49:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\_projects\CoreElectron\node_modules\electron-builder\src\cli\cli.ts:49:33)
    at Object.runCommand (C:\_projects\CoreElectron\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\_projects\CoreElectron\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (C:\_projects\CoreElectron\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\_projects\CoreElectron\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by develar** [comment]
NodeJS version?

**Comment by giokara** [comment]
I'm behind on that one, v6.11.0

**Comment by coopernyc** [comment]
node -v
v8.9.2

**Comment by coopernyc** [comment]
it runs fine on builder 19.49.4
C:\_projects\CoreElectron>npm run pack

> ROME@3.3.0 pack C:\_projects\CoreElectron
> electron-builder -w --x64 --project build --dir

electron-builder 19.49.4
Installing app dependencies for win32:x64 to C:\_projects\CoreElectron\build
Packaging for win32 x64 using electron 1.7.10 to ..\dist\win-unpacked

C:\_projects\CoreElectron>

**Comment by willove** [comment]
C:\Users\Giorgos\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.4.0-x64\app-builder.exe
no such FILE? 
I suggest you should get the 'app-builder' file from github link and copy the file to your local path.

**Comment by sundowatch** [comment]
`yarn add electron-builder` or `npm install electron-builder` solved my problem.

**Comment by physics515** [comment]
For me this was Windows Security believing "\node_modules\dmg-builder\node_modules\app-builder-bin\win\ia32\app-builder.exe" was a trojan and removing it. `yarn add electron-builder` helped but windows kept removing it.
