### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by gucong3000** [electron-userland/electron-builder#2479]
* **Version**:  --version 19.52.1

* **Target**: Windows x64

Can not build my app when use proxy

`C:\Users\cdyf\AppData\.npmrc`:
```ini
proxy=http://localhost:8001
https-proxy=http://localhost:8001
strict-ssl=false
```

When set `strict-ssl` to `false`, **Expect to be able to skip certificate validation**
 
Error details:
```shell
  • downloading     path=C:\Users\cdyf\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13 url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.1.13/nsis-3.0.1.13.7z
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1036:34)
    at TLSSocket.emit (events.js:159:13)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
From previous event:
    at CancellationToken.createPromise (E:\work\safetree\node_modules\builder-util-runtime\src\CancellationToken.ts:51:5)
    at E:\work\safetree\node_modules\builder-util\src\nodeHttpExecutor.ts:23:44
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at NodeHttpExecutor.download (E:\work\safetree\node_modules\builder-util\src\nodeHttpExecutor.ts:36:4)
    at Timeout._onTimeout (E:\work\safetree\node_modules\builder-util\src\binDownload.ts:83:14)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
```

**Comment by syshu** [comment]
@gucong3000 have you ever solved this? I've been facing the same problem right now, seeking for solution.

**Comment by gucong3000** [comment]
> have you ever solved this?
No.
