### ISSUE TITLE
"installOrRebuild" is no longer available

### ISSUE THREAD

**Issue by demid5111** [electron-userland/electron-builder#2494]
* **Version**: 19.55.0

* **Target**: maOS Sierra 10.12.6

I try to use the **installOrRebuild** function, however it is not available in the latest version. Could you please help to solve this issue?
```
node ./config/install-app-deps


module.js:472
    throw err;
    ^

Error: Cannot find module 'electron-builder/out/util/yarn'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (my path)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

In ```install-app-deps``` I just try to require the function:

```
require('electron-builder/out/util/yarn').installOrRebuild;
```

**Comment by develar** [comment]
Please use command `electron-builder install-app-deps`
