### ISSUE TITLE
Error: Cannot cleanup when publishing (TypeError: Path must be a string)

### ISSUE THREAD

**Issue by kwent** [electron-userland/electron-builder#2495]
Edit: Fixed by upgrading **electron-publisher-s3** to last version.

* **Version**:
electron-builder: **19.54.0**
electron-updater: **2.19.1**
electron-publisher-s3: **17.6.0**
* **Target**: macOS, win32

Seeing the following error when attempting to publish (publish fail). Same for Windows and possibly Linux (untested)

OSX backtrace:
```
...
  • building        target=macOS zip arch=x64 file=release/myproject-0.4.9-mac.zip
  • building        target=DMG arch=x64 file=release/myproject-0.4.9.dmg
  • building block map blockMapFile=release/myproject-0.4.9.dmg.blockmap
  • publishing      publisher=S3 (bucket: myproject-releases)
Error: Cannot cleanup:

Error #1 --------------------------------------------------------------------------------
TypeError: Path must be a string. Received { file: '/Users/username/Projects/myproject/release/myproject-0.4.9.dmg.blockmap',
  safeArtifactName: 'null.blockmap',
  target:
   DmgTarget {
     name: 'dmg',
     isAsyncSupported: true,
     packager:
      MacPackager {
        info: [Object],
        _resourceList: [Object],
        platformSpecificBuildOptions: [Object],
        appInfo: [Object],
        _iconPath: [Object],
        codeSigningInfo: [Object] },
     outDir: '/Users/username/Projects/myproject/release',
     options: { contents: [Array] } },
  arch: null,
  packager:
   MacPackager {
     info:
      Packager {
        cancellationToken: [Object],
        isTwoPackageJsonProjectLayoutUsed: true,
        eventEmitter: [Object],
        tempDirManager: [Object],
        _repositoryInfo: [Object],
        afterPackHandlers: [Array],
        afterSignHandlers: [],
        debugLogger: [Object],
        _productionDeps: [Object],
        _electronDownloader: null,
        electronDownloader: [Function],
        stageDirPathCustomizer: [Function],
        projectDir: '/Users/username/Projects/myproject',
        _appDir: '/Users/username/Projects/myproject/app',
        options: [Object],
        _devMetadata: [Object],
        _metadata: [Object],
        _configuration: [Object],
        appInfo: [Object],
        _buildResourcesDir: '/Users/username/Projects/myproject/resources' },
     _resourceList: Lazy { creator: null, _value: [Object] },
     platformSpecificBuildOptions: { category: 'public.app-category.developer-tools' },
     appInfo:
      AppInfo {
        info: [Object],
        description: 'Collaborative SQL editor to write, run, and share queries instantly',
        version: '0.4.9',
        buildNumber: undefined,
        buildVersion: '0.4.9',
        productName: 'myproject',
        productFilename: 'myproject' },
     _iconPath: Lazy { creator: null, _value: [Object] },
     codeSigningInfo:
      Promise {
        _bitField: 33554432,
        _fulfillmentHandler0: undefined,
        _rejectionHandler0: [Object],
        _promise0: undefined,
        _receiver0: undefined,
        _trace: [Object] } },
  updateInfo:
   { size: 69964212,
     sha512: 'yMdn94LykhmEzBCJDmCqqo67vbWbUpY6QXost0pDixz0CkPOkL8nzcyQEgNPeDDQyaz0As6uZ4K/cpe5VQP+iQ==' } }
    at assertPath (path.js:28:11)
    at basename (path.js:1383:5)
    at /Users/username/Projects/myproject/node_modules/electron-publisher-s3/src/s3Publisher.ts:38:22
    at Generator.next (<anonymous>)
From previous event:
    at S3Publisher.upload (/Users/username/Projects/myproject/node_modules/electron-publisher-s3/out/s3Publisher.js:109:11)
    at PublishManager.scheduleUpload (/Users/username/Projects/myproject/node_modules/electron-builder-lib/src/publish/PublishManager.ts:122:40)
    at /Users/username/Projects/myproject/node_modules/electron-builder-lib/src/publish/PublishManager.ts:149:14
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

Error #2 --------------------------------------------------------------------------------
TypeError: Path must be a string. Received { file: '/Users/username/Projects/myproject/release/myproject-0.4.9.dmg',
  safeArtifactName: null,
  target:
   DmgTarget {
     name: 'dmg',
     isAsyncSupported: true,
     packager:
      MacPackager {
        info: [Object],
        _resourceList: [Object],
        platformSpecificBuildOptions: [Object],
        appInfo: [Object],
        _iconPath: [Object],
        codeSigningInfo: [Object] },
     outDir: '/Users/username/Projects/myproject/release',
     options: { contents: [Array] } },
  arch: 1,
  packager:
   MacPackager {
     info:
      Packager {
        cancellationToken: [Object],
        isTwoPackageJsonProjectLayoutUsed: true,
        eventEmitter: [Object],
        tempDirManager: [Object],
        _repositoryInfo: [Object],
        afterPackHandlers: [Array],
        afterSignHandlers: [],
        debugLogger: [Object],
        _productionDeps: [Object],
        _electronDownloader: null,
        electronDownloader: [Function],
        stageDirPathCustomizer: [Function],
        projectDir: '/Users/username/Projects/myproject',
        _appDir: '/Users/username/Projects/myproject/app',
        options: [Object],
        _devMetadata: [Object],
        _metadata: [Object],
        _configuration: [Object],
        appInfo: [Object],
        _buildResourcesDir: '/Users/username/Projects/myproject/resources' },
     _resourceList: Lazy { creator: null, _value: [Object] },
     platformSpecificBuildOptions: { category: 'public.app-category.developer-tools' },
     appInfo:
      AppInfo {
        info: [Object],
        description: 'Collaborative SQL editor to write, run, and share queries instantly',
        version: '0.4.9',
        buildNumber: undefined,
        buildVersion: '0.4.9',
        productName: 'myproject',
        productFilename: 'myproject' },
     _iconPath: Lazy { creator: null, _value: [Object] },
     codeSigningInfo:
      Promise {
        _bitField: 33554432,
        _fulfillmentHandler0: undefined,
        _rejectionHandler0: [Object],
        _promise0: undefined,
        _receiver0: undefined,
        _trace: [Object] } },
  isWriteUpdateInfo: true,
  updateInfo:
   { size: 69964212,
     sha512: 'yMdn94LykhmEzBCJDmCqqo67vbWbUpY6QXost0pDixz0CkPOkL8nzcyQEgNPeDDQyaz0As6uZ4K/cpe5VQP+iQ==' } }
    at assertPath (path.js:28:11)
    at basename (path.js:1383:5)
    at /Users/username/Projects/myproject/node_modules/electron-publisher-s3/src/s3Publisher.ts:38:22
    at Generator.next (<anonymous>)
From previous event:
    at S3Publisher.upload (/Users/username/Projects/myproject/node_modules/electron-publisher-s3/out/s3Publisher.js:109:11)
    at PublishManager.scheduleUpload (/Users/username/Projects/myproject/node_modules/electron-builder-lib/src/publish/PublishManager.ts:122:40)
    at /Users/username/Projects/myproject/node_modules/electron-builder-lib/src/publish/PublishManager.ts:149:14
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
    at assertPath (path.js:28:11)
    at basename (path.js:1383:5)
    at /Users/username/Projects/myproject/node_modules/electron-publisher-s3/src/s3Publisher.ts:38:22
    at Generator.next (<anonymous>)
    at S3Publisher.upload (/Users/username/Projects/myproject/node_modules/electron-publisher-s3/out/s3Publisher.js:109:11)
    at PublishManager.scheduleUpload (/Users/username/Projects/myproject/node_modules/electron-builder-lib/src/publish/PublishManager.ts:122:40)
    at /Users/username/Projects/myproject/node_modules/electron-builder-lib/src/publish/PublishManager.ts:149:14
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
    at assertPath (path.js:28:11)
    at basename (path.js:1383:5)
    at /Users/username/Projects/myproject/node_modules/electron-publisher-s3/src/s3Publisher.ts:38:22
    at Generator.next (<anonymous>)
    at S3Publisher.upload (/Users/username/Projects/myproject/node_modules/electron-publisher-s3/out/s3Publisher.js:109:11)
    at PublishManager.scheduleUpload (/Users/username/Projects/myproject/node_modules/electron-builder-lib/src/publish/PublishManager.ts:122:40)
    at /Users/username/Projects/myproject/node_modules/electron-builder-lib/src/publish/PublishManager.ts:149:14
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
    at throwError (/Users/username/Projects/myproject/node_modules/builder-util/src/asyncTaskManager.ts:91:11)
    at checkErrors (/Users/username/Projects/myproject/node_modules/builder-util/src/asyncTaskManager.ts:54:9)
    at /Users/username/Projects/myproject/node_modules/builder-util/src/asyncTaskManager.ts:59:5
    at Generator.next (<anonymous>)
From previous event:
    at AsyncTaskManager.awaitTasks (/Users/username/Projects/myproject/node_modules/builder-util/out/asyncTaskManager.js:103:11)
    at /Users/username/Projects/myproject/node_modules/electron-builder-lib/src/publish/PublishManager.ts:178:28
    at Generator.next (<anonymous>)
From previous event:
    at PublishManager.awaitTasks (/Users/username/Projects/myproject/node_modules/electron-builder-lib/out/publish/PublishManager.js:443:11)
    at /Users/username/Projects/myproject/node_modules/electron-builder/src/builder.ts:317:32
    at /Users/username/Projects/myproject/node_modules/builder-util/src/promise.ts:26:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at executeFinally (/Users/username/Projects/myproject/node_modules/builder-util/out/promise.js:37:21)
    at /Users/username/Projects/myproject/node_modules/electron-builder/src/builder.ts:310:10
    at Generator.next (<anonymous>)
From previous event:
    at _build (/Users/username/Projects/myproject/node_modules/electron-builder/out/builder.js:61:21)
    at build (/Users/username/Projects/myproject/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/Users/username/Projects/myproject/node_modules/electron-builder/src/cli/cli.ts:49:33)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.args [as handler] (/Users/username/Projects/myproject/node_modules/electron-builder/out/cli/cli.js:127:117)
    at Object.runCommand (/Users/username/Projects/myproject/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/username/Projects/myproject/node_modules/electron-builder/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/username/Projects/myproject/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/username/Projects/myproject/node_modules/electron-builder/out/cli/cli.js:123:439)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

Any ideas ?
Also is there anyway to disabled differential update ?

Regards

**Comment by kwent** [comment]
Fixed by upgrading electron-publisher-s3 to last version.
