### ISSUE TITLE
Error: Cannot find module 'http2' when building for linux

### ISSUE THREAD

**Issue by usamaejaz** [electron-userland/electron-builder#2500]
* **Version**: 19.54.0

* **Target**: Windows, Linux (ia32, x64)

I am on windows x64. Building installer for windows works fine (ia32, x64). But when building installer for linux (`electron-builder -l --ia32 --x64`, this error shows.

```shell
Error: Cannot find module 'http2'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at _load_http (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\out\remoteBuilder\RemoteBuilder.js:84:20)
    at C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:121:18
    at Generator.next (<anonymous>)
From previous event:
    at findBuildAgent (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\out\remoteBuilder\RemoteBuilder.js:69:21)
    at C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:68:30
    at Generator.next (<anonymous>)
From previous event:
    at RemoteBuilder._build (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\out\remoteBuilder\RemoteBuilder.js:187:11)
    at default.mapSeries.arch (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:54:19)
From previous event:
    at RemoteBuilder.build (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:53:28)
    at C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\src\linuxPackager.ts:110:30
From previous event:
    at RemoteTarget.finishBuild (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\out\linuxPackager.js:151:11)
    at C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\src\packager.ts:369:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.doBuild (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\out\packager.js:423:11)
    at C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\src\packager.ts:305:52
    at Generator.next (<anonymous>)
    at C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\out\packager.js:367:11)
    at C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\src\packager.ts:267:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder-lib\out\packager.js:323:11)
    at C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder\out\builder.js:61:21)
    at build (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder\src\builder.ts:280:10)
    at then (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder\src\cli\cli.ts:49:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.args [as handler] (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder\out\cli\cli.js:127:117)
    at Object.runCommand (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\dell\CodeHell\prayertimes-desktop\node_modules\electron-builder\out\cli\cli.js:123:439)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prayertimes@2.0.0 dist-linux: `electron-builder -l --x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prayertimes@2.0.0 dist-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2018-01-20T15_29_23_922Z-debug.log
```

**Comment by develar** [comment]
PLease use node 9 or latest 8.

**Comment by usamaejaz** [comment]
So `http2` is only in new version of Node that is why it didn't work for me. Thank you for the quick response 🤗
