### ISSUE TITLE
Cannot build for Windows using Mac -- wine refusing to create a configuration directory

### ISSUE THREAD

**Issue by qualisign** [electron-userland/electron-builder#2510]
* **Version**: 19.52.1

MacOS

I cannot successfully build for Windows.  I first received error messages indicating that Wine must be installed.  After installing Wine via brew, I tried building again, and received this lengthy error message:
```

  • electron-builder version=19.52.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build/electron-builder.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • packaging       platform=linux arch=x64 electron=1.7.10 appOutDir=build/linux-unpacked
  • building        target=AppImage arch=x64 file=build/my-project-0.0.0-x86_64.AppImage
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category
  • rebuilding native production dependencies platform=win32 arch=x64
  • building embedded block map file=build/my-project-0.0.0-x86_64.AppImage
  • packaging       platform=win32 arch=x64 electron=1.7.10 appOutDir=build/win-unpacked
Error: Exit code: 1. Command failed: wine /Users/josephadmin/Library/Caches/electron-builder/winCodeSign/winCodeSign-1.9.0/rcedit.exe /Users/josephadmin/projects/my-project/build/win-unpacked/my-project.exe --set-version-string FileDescription my-project --set-version-string ProductName my-project --set-version-string LegalCopyright Copyright © 2018 my-project --set-file-version 0.0.0 --set-product-version 0.0.0.0 --set-version-string InternalName my-project --set-version-string OriginalFilename  --set-icon /Users/josephadmin/projects/my-project/build/icons/icon.ico
wine: '/Users/josephadmin' is not owned by you, refusing to create a configuration directory there

wine: '/Users/josephadmin' is not owned by you, refusing to create a configuration directory there

    at /Users/josephadmin/projects/my-project/node_modules/builder-util/src/util.ts:122:16
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
From previous event:
    at exec (/Users/josephadmin/projects/my-project/node_modules/builder-util/src/util.ts:85:3)
    at wineExecutable.value.then.wine (/Users/josephadmin/projects/my-project/node_modules/builder-util/src/wine.ts:72:16)
From previous event:
    at execWine (/Users/josephadmin/projects/my-project/node_modules/builder-util/src/wine.ts:64:8)
    at /Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/src/winPackager.ts:346:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at WinPackager.signAndEditResources (/Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/out/winPackager.js:456:11)
    at /Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/src/winPackager.ts:363:18
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/out/winPackager.js:474:11)
    at /Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/src/platformPackager.ts:215:16
From previous event:
    at WinPackager.doPack (/Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/out/platformPackager.js:276:11)
    at /Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/src/platformPackager.ts:115:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/out/platformPackager.js:195:11)
    at /Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/src/packager.ts:355:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.doBuild (/Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/out/packager.js:419:11)
    at /Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/src/packager.ts:299:52
    at Generator.next (<anonymous>)
    at /Users/josephadmin/projects/my-project/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/josephadmin/projects/my-project/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at Packager._build (/Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/out/packager.js:363:11)
    at /Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/src/packager.ts:261:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/Users/josephadmin/projects/my-project/node_modules/electron-builder-lib/out/packager.js:319:11)
    at /Users/josephadmin/projects/my-project/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/Users/josephadmin/projects/my-project/node_modules/electron-builder/out/builder.js:61:21)
    at build (/Users/josephadmin/projects/my-project/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/Users/josephadmin/projects/my-project/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (/Users/josephadmin/projects/my-project/node_modules/electron-builder/out/cli/cli.js:127:117)
    at Object.runCommand (/Users/josephadmin/projects/my-project/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/josephadmin/projects/my-project/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/josephadmin/projects/my-project/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/josephadmin/projects/my-project/node_modules/electron-builder/out/cli/cli.js:123:441)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3


```
Does anyone know what could be causing this?  Thanks.

**Comment by TuckerDowns** [comment]
Similarly today I had an issue with directory ownership while running electron-build with gitlab-ci

```wine: /Users/revdev/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/wine-home is not owned by you```

The build was run as user gitlab-user, when run as su then it works fine. Not really sure about the right course of action right now but my build did finish, so... weird. 

Happy to provide more specific info if this gets more traction.

**Comment by SupremacyAI** [comment]
Anyone looking for a solution - this is causing our project to sit still. 
Samme type of error.

**Comment by seckinbostanci** [comment]
Anyone find a solution?

**Comment by hn3000** [comment]
It looks like you were running the build with different users at different times.

The folder 
```/Users/<user>/Library/Caches/electron-builder/wine/wine-<version>/wine-home``` is used as WINEPREFIX and needs to be writable for the current user.

**Comment by jorbascrumps** [comment]
Currently experiencing this with Github Actions. Has anyone solved this? Not sure su is an option for me with Actions..

(Sorry for the necropost)

**Comment by 354574876** [comment]
Anyone who solved this problem ?

**Comment by neutrinog** [comment]
Ditto with Github Actions. I've been successfully using wine in docker image on concourse for about a year. I'm attempting to migrate to Github Actions using the same docker image as the container. Everything works fine until I need to run wine.

**Comment by kshychko** [comment]
For anyone who is having troubles with publishing using GitHub actions, preserving $HOME value did help me:
https://github.com/actions/runner/issues/863#issuecomment-2335135444
