### ISSUE TITLE
compress.sh exec flag  is not set

### ISSUE THREAD

**Issue by niklauslee** [electron-userland/electron-builder#2523]
I'm try to build .deb package in Ubuntu 16.04. However it failed with following error messages:

```bsh
parallels@ubuntu:~/git/staruml3$ sudo npm run dist

> @ dist /home/parallels/git/staruml3
> build

  • electron-builder version=19.55.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=1.7.11 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/StarUML-3.0.0-alpha.1-x86_64.AppImage
  • building embedded block map file=dist/StarUML-3.0.0-alpha.1-x86_64.AppImage
  • building        target=deb arch=x64 file=dist/StarUML_3.0.0-alpha.1_amd64.deb
Error: Exit code: 1. Command failed: /home/parallels/.cache/electron-builder/fpm/fpm-1.9.2-2.3.1-linux-x86_64/fpm -s dir -t deb --architecture amd64 --name StarUML --force --after-install /tmp/temp-dir-JOAcQh/1-after-install --after-remove /tmp/temp-dir-JOAcQh/0-after-remove --description 
 A sophisticated software modeler --version 3.0.0-alpha.1 --package /home/parallels/git/staruml3/dist/StarUML_3.0.0-alpha.1_amd64.deb --maintainer niklauslee <support@staruml.io> --url https://staruml.io --vendor niklauslee <support@staruml.io> --deb-compression xz --depends gconf2 --depends gconf-service --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --depends libxss1 /home/parallels/git/staruml3/dist/linux-unpacked/=/opt/StarUML /home/parallels/git/staruml3/build/icons/16x16.png=/usr/share/icons/hicolor/16x16/apps/staruml.png /home/parallels/git/staruml3/build/icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/staruml.png /home/parallels/git/staruml3/build/icons/48x48.png=/usr/share/icons/hicolor/48x48/apps/staruml.png /home/parallels/git/staruml3/build/icons/128x128.png=/usr/share/icons/hicolor/128x128/apps/staruml.png /home/parallels/git/staruml3/build/icons/256x256.png=/usr/share/icons/hicolor/256x256/apps/staruml.png /home/parallels/git/staruml3/build/icons/512x512.png=/usr/share/icons/hicolor/512x512/apps/staruml.png /tmp/temp-dir-JOAcQh/2-StarUML.desktop=/usr/share/applications/staruml.desktop

{:timestamp=>"2018-01-25T17:51:48.370603+0900", :message=>"Debian tools (dpkg/apt) don't do well with packages that use capital letters in the name. In some cases it will automatically downcase them, in others it will not. It is confusing. Best to not use any capital letters at all. I have downcased the package name for you just to be safe.", :oldname=>"StarUML", :fixedname=>"staruml", :level=>:warn}
{:timestamp=>"2018-01-25T17:51:48.382137+0900", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2018-01-25T17:51:48.895591+0900", :message=>"Process failed: tar failed (exit code 13). Full command was:[\"tar\", \"-C\", \"/tmp/package-dir-staging-a9c15a55e6031f73e09ab6c06daf98c28b3ae264a5c8c100b569c89b3c4c\", \"-I'/home/parallels/git/staruml3/node_modules/7zip-bin/compress.sh'\", \"--numeric-owner\", \"--owner\", \"0\", \"--numeric-owner\", \"--group\", \"0\", \"-cf\", \"/tmp/package-deb-build-0b71cf161a5aad2c7fbdbdd91b2972ee40d7fdb16de51d2c4d1a963ca11a/data.tar.xz\", \".\"]", :level=>:error}

    at /home/parallels/git/staruml3/node_modules/builder-util/src/util.ts:122:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at exec (/home/parallels/git/staruml3/node_modules/builder-util/src/util.ts:85:3)
    at /home/parallels/git/staruml3/node_modules/electron-builder-lib/src/targets/fpm.ts:230:11
    at Generator.next (<anonymous>)
From previous event:
    at FpmTarget.build (/home/parallels/git/staruml3/node_modules/electron-builder-lib/out/targets/fpm.js:278:11)
    at default.each.it (/home/parallels/git/staruml3/node_modules/electron-builder-lib/src/platformPackager.ts:121:89)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at taskManager.addTask.default.map.then (/home/parallels/git/staruml3/node_modules/electron-builder-lib/src/platformPackager.ts:121:37)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/parallels/git/staruml3/node_modules/electron-builder-lib/src/platformPackager.ts:121:10)
    at /home/parallels/git/staruml3/node_modules/electron-builder-lib/src/platformPackager.ts:115:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at LinuxPackager.pack (/home/parallels/git/staruml3/node_modules/electron-builder-lib/out/platformPackager.js:202:11)
    at /home/parallels/git/staruml3/node_modules/electron-builder-lib/src/packager.ts:364:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/parallels/git/staruml3/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/parallels/git/staruml3/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/parallels/git/staruml3/node_modules/electron-builder-lib/out/packager.js:432:11)
    at /home/parallels/git/staruml3/node_modules/electron-builder-lib/src/packager.ts:308:52
    at Generator.next (<anonymous>)
    at /home/parallels/git/staruml3/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/parallels/git/staruml3/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/parallels/git/staruml3/node_modules/electron-builder-lib/out/packager.js:376:11)
    at /home/parallels/git/staruml3/node_modules/electron-builder-lib/src/packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/home/parallels/git/staruml3/node_modules/electron-builder-lib/out/packager.js:332:11)
    at /home/parallels/git/staruml3/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/home/parallels/git/staruml3/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/parallels/git/staruml3/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/home/parallels/git/staruml3/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/home/parallels/git/staruml3/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/home/parallels/git/staruml3/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/parallels/git/staruml3/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/parallels/git/staruml3/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/parallels/git/staruml3/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

And, following is script and build config in `package.json`:

```json
  "scripts": {
    "dist": "build"
  },
  "build": {
    "linux": {
      "target": [
        "AppImage",
        "deb"
      ],
      "category": "Development"
    },
    "deb": {},
  }
```

I've also checked require packages:

```
parallels@ubuntu:~/git/staruml3$ fpm --version
1.9.3
parallels@ubuntu:~/git/staruml3$ xz --version
xz (XZ Utils) 5.1.0alpha
liblzma 5.1.0alpha
```

Version of electron-builder is `19.55.2`

Thanks in advance.

**Comment by develar** [comment]
Please try `chmod +x /home/parallels/git/staruml3/node_modules/7zip-bin/compress.sh`

**Comment by niklauslee** [comment]
It works! Thank you.

**Comment by develar** [comment]
Bloody yarn / npm.... We need to write this wrapper in go as part of our app-builder.
