### ISSUE TITLE
Error: Unresolved node modules: jquery, popper.js     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\util\packageDependencies.ts:110:19 

### ISSUE THREAD

**Issue by 819460357** [electron-userland/electron-builder#2529]
Error: Unresolved node modules: jquery, popper.js
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\util\packageDependencies.ts:110:19
From previous event:
    at Collector.resolveUnresolvedHoisted (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\out\util\packageDependencies.js:206:11)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\util\packageDependencies.ts:86:18
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Collector.collect (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\out\util\packageDependencies.js:154:11)
    at computeDependencies (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\util\packageDependencies.ts:51:26)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\util\packageDependencies.ts:46:28
    at Generator.next (<anonymous>)
From previous event:
    at getProductionDependencies (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\out\util\packageDependencies.js:29:21)
    at Lazy (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\util\packageDependencies.ts:40:25)
    at Lazy.get value [as value] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\lazy-val\src\main.ts:18:23)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\util\yarn.ts:120:81
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\out\util\yarn.js:93:22)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at installOrRebuild (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:442:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\out\packager.js:496:11)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:356:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\out\packager.js:432:11)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:308:52
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\out\packager.js:376:11)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\out\packager.js:332:11)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\out\builder.js:61:21)
    at build (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:280:10)
    at then (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by deed02392** [comment]
I am pretty sure this is an issue with your project.

Those unresolved modules are from your project, not builder. So, try something like:

```
npm install popper.js --save
npm install jquery --save
```

then rebuild.

**Comment by mnewmedia** [comment]
Seems like these are deps of bootstrap 4.

**Comment by theCrius** [comment]
If you're using something like ngbootstrap for Angular, you should use https://www.npmjs.com/package/bootstrap-css-only instead of the regular bootstrap.

**Comment by 526142399** [comment]
i also has this issues. the reason is you use the  tool that installs dependencies. I think you can use 'yarn' for your dependencies.

**Comment by theCrius** [comment]
Switching over an entire different module manager over a simple issue with the library not being meant for doing what it was expected seems quite an overkill. Let's just keep the "promote my favourite package manager" out of this.

**Comment by maple3142** [comment]
I encountered this error today too, but using `bootstrap-css-only` instead of `bootstrap` doesn't help.
My imports:
![image](https://user-images.githubusercontent.com/9370547/46247163-e8a35b80-c439-11e8-89ee-0f63ffc7d36b.png)

I still have to `yarn add -D jquery popper.js` to get `electron-builder` works.

**Comment by theCrius** [comment]
You definitely don't need to do that. If you still have that problem it's either your code or some other library.

I see you're using BootstrapVue there as well, I was using angular 5.x. We can't really help you there.
Try opening a stackoverflow question.

**Comment by aliahsan07** [comment]
Hi I'm facing this issue but only getting unresolved node modules: jquery
Is there any other way except installing jquery? I don't even remember using jquery anywhere in the project.

**Comment by Wurielle** [comment]
Make sure to include your dependencies in the correct fields inside your package.json.

```
{
  ...
  "dependencies": {
    // Here goes anything required on runtime, e.g: auto-launch, anything-node,... 
    "auto-launch": "^5.0.5",
    "electron-dl": "^1.12.0",
    "electron-is-dev": "^1.0.1",
    "electron-log": "^2.2.17",
    "electron-updater": "^4.0.6",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    // Here goes anything compiled, e.g: jquery, lodash,...
  }
}
```
Could fix some of your "Unresolved node modules" problems.

**Comment by Flygenring** [comment]
This is caused by a dependency (`bootstrap` through `bootstrap-vue` in this case) having declared `peerDependencies` that are not met in the project.

As `bootstrap-vue` has removed the `bootstrap` dependency for `jquery` and `popper` you know that these are not needed and you can put them in an `optionalDependencies` section, which tells the rest of the build to not fail if they're missing, e.g.:
```
{
  ...
  "dependencies": {
    "bootstrap-vue": "^2.0",
    "vue": "^2.6",
  },
  "optionalDependencies": {
    "jquery": "1.9.1 - 3",
    "popper.js": "^1.14.7"
  }
}
```

**Comment by yangbo** [comment]
> This is caused by a dependency (`bootstrap` through `bootstrap-vue` in this case) having declared `peerDependencies` that are not met in the project.
> 
> As `bootstrap-vue` has removed the `bootstrap` dependency for `jquery` and `popper` you know that these are not needed and you can put them in an `optionalDependencies` section, which tells the rest of the build to not fail if they're missing, e.g.:
> 
> ```
> {
>   ...
>   "dependencies": {
>     "bootstrap-vue": "^2.0",
>     "vue": "^2.6",
>   },
>   "optionalDependencies": {
>     "jquery": "1.9.1 - 3",
>     "popper.js": "^1.14.7"
>   }
> }
> ```

Added the optionalDependencies, but still build fail with the same error, any idea?

I use the bootstrap-vue module, when I manually delete the peerDependencies from the bootstrap package.json, the build can succeed, but how to solve this issue by config?

**Comment by o1dnik** [comment]
> npm i -D popper.js jquery

Solved the problem temporarily. Unfortunately it is indeed a dependency, but you can install as `devDependencies`

**Comment by Dzhokhar** [comment]
Error: Unresolved node modules: material-ui

**Comment by catman85** [comment]
I had the same problem, with bootstrap-vue and electron-vue.
I ran the following commands and everything works fine...
(As @theCrius suggested):
```javascript
npm uninstall bootstrap
npm install bootstrap-vue bootstrap-css-only
```
(As @Flygenring  suggested):
I added to package.json
```javascript
  "optionalDependencies": {
    "jquery": "1.9.1 - 3"
  },
```
And builds work just fine... 👌
```javascript
sudo npm run build
```
You can have a look at my project [here.](https://github.com/catman85/Bias-2-Importer-Exporter)

**Comment by AndrazPustotnik** [comment]
Just import bootstrap as:
```
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
```
in "<head>" of "index.ejs" if you are using SimulatedGREG's boilerplate.

credit: 
@[Breci](https://github.com/Breci)
