### ISSUE TITLE
MacOS Auto-Updater Stopped Working with Github releases (public) returns 400 

### ISSUE THREAD

**Issue by Nederby** [electron-userland/electron-builder#2540]
* electron-builder version: **19.55.2**

* electron-updater: **2.20.1**

*  Target: **Mac**

**The auto-updater works fine on Windows (nsis)** - but on mac I start getting `status 400: Bad Request` in the log file. When i push out a new version. I thought it was a temporary Github issue - but it has been broken for little month.   

My update script
``` javascript
import { autoUpdater } from "electron-updater"

autoUpdater.checkForUpdatesAndNotify() 

```
If I do a normal `GET` request to https://api.github.com/repos/dixahq/dixa-desktop-app-release/releases/assets/6032765 everything looks fine. 

```
[2018-01-31 09:34:20.668] [info] Checking for update...
[2018-01-31 09:34:21.394] [info] Found version 2.0.6 (url: dixa-2.0.6-mac.zip, dixa-2.0.6.dmg)
[2018-01-31 09:34:21.396] [info] Update available.
[2018-01-31 09:34:21.396] [info] 2.0.6
[2018-01-31 09:34:21.397] [info] Downloading update from dixa-2.0.6-mac.zip, dixa-2.0.6.dmg
[2018-01-31 09:34:21.409] [info] / requested
[2018-01-31 09:34:21.412] [info] /app.zip requested
[2018-01-31 09:34:21.853] [warn] Error: Update download failed. The server sent an invalid response. Try again later.

[2018-01-31 09:34:21.853] [error] Error: Error: Update download failed. The server sent an invalid response. Try again later.
[2018-01-31 09:34:21.853] [info] Error in auto-updater.
[2018-01-31 09:34:21.853] [info] Error: Update download failed. The server sent an invalid response. Try again later.

[2018-01-31 09:34:21.854] [error] Error: Error: Cannot download "https://api.github.com/repos/dixahq/dixa-desktop-app-release/releases/assets/6032765": Error: Cannot download "https://api.github.com/repos/dixahq/dixa-desktop-app-release/releases/assets/6032765", status 400: Bad Request
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:74:22
    at ClientRequest.downloadRequest.httpExecutor.doRequest.downloadResponse (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:101:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/Applications/Dixa.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
From previous event:
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:44:12
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:127:11)
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:331:25
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.downloadUpdate (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:366:11)
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:307:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:337:11)
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:255:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:291:11)
    at MacUpdater.checkForUpdates (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:204:35)
    at MacUpdater.checkForUpdatesAndNotify (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:224:17)
    at AutoUpdater.checkForUpdate (/Applications/Dixa.app/Contents/Resources/app.asar/app/webpack:/src/autoUpdate/AutoUpdate.js:31:17)
    at click (/Applications/Dixa.app/Contents/Resources/app.asar/app/webpack:/src/background.js:77:26)
    at MenuItem.click (/Applications/Dixa.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Applications/Dixa.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)
[2018-01-31 09:34:21.855] [info] Error in auto-updater.
[2018-01-31 09:34:21.855] [info] Error: Cannot download "https://api.github.com/repos/dixahq/dixa-desktop-app-release/releases/assets/6032765": Error: Cannot download "https://api.github.com/repos/dixahq/dixa-desktop-app-release/releases/assets/6032765", status 400: Bad Request
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:74:22
    at ClientRequest.downloadRequest.httpExecutor.doRequest.downloadResponse (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:101:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/Applications/Dixa.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
From previous event:
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:44:12
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:127:11)
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:331:25
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.downloadUpdate (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:366:11)
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:307:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:337:11)
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:255:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:291:11)
    at MacUpdater.checkForUpdates (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:204:35)
    at MacUpdater.checkForUpdatesAndNotify (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:224:17)
    at AutoUpdater.checkForUpdate (/Applications/Dixa.app/Contents/Resources/app.asar/app/webpack:/src/autoUpdate/AutoUpdate.js:31:17)
    at click (/Applications/Dixa.app/Contents/Resources/app.asar/app/webpack:/src/background.js:77:26)
    at MenuItem.click (/Applications/Dixa.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Applications/Dixa.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)

[2018-01-31 09:34:34.187] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://api.github.com/repos/dixahq/dixa-desktop-app-release/releases/assets/6032765)
```

Thanks - any help would be appreciated.

**Comment by nbcnc** [comment]
I reported a similar problem [here](https://github.com/electron-userland/electron-builder/issues/2508) but I thought it was confined to private repos only.

**Comment by Nederby** [comment]
[There is something wrong client request](https://developer.github.com/v3/#client-errors). Maybe the logs should include the full response on a `400` response from the Github API, so we could see what is wrong with the request.

**Comment by marceloromaomultilaser** [comment]
Same... i've change mey repo to public and the problem persist

**Comment by develar** [comment]
@Nederby Please provide your publisher config (via private message in Slack if you want privacy).

**Comment by Stereoscape** [comment]
@develar we have the same issue that @Nederby is having. In Windows it works fine. But Mac version is not working. It has been like this at least for over a month. It would be great if you could look into it. 

Electron-builder **20.22.0**:
electron-updater **3.0.3**:
Target **MAC**:

Below is the publish config and the error log. 
{
  "name": "electronupdater",
  "version": "0.0.17",
  "main": "main.js",
  "description": "electron-updater example project",
  "author": "Matt Haggard",
  "scripts": {
    "publish": "build -p always"
  },
  "devDependencies": {
    "electron": "^1.8.7",
    "electron-builder": "^20.22.0"
  },
  "dependencies": {
    "electron-log": "^1.3.0",
    "electron-updater": "^3.0.3",
    "shell-env": "^2.0.1"
  },
  "build": {
    "publish": [
      {
        "provider": "github",
        "owner": "Stereoscape",
        "repo": "electronupdater",
        "private": true,
        "token": "*************************"
      }
    ],
    "appId": "com.github.stereoscape.electronupdater",
    "mac": {
      "category": "your.app.category.type",
      "target": [
        "zip",
        "dmg"
      ]
    }
  }
}





[2018-07-18 18:16:28:0991] [info] Checking for update
[2018-07-18 18:16:28:0991] [info] Checking for update...
[2018-07-18 18:16:30:0880] [info] Found version 0.0.17 (url: electronupdater-0.0.17-mac.zip, electronupdater-0.0.17.dmg)
[2018-07-18 18:16:30:0880] [info] Update available.
[2018-07-18 18:16:30:0881] [info] Downloading update from electronupdater-0.0.17-mac.zip, electronupdater-0.0.17.dmg
[2018-07-18 18:16:30:0928] [info] / requested
[2018-07-18 18:16:30:0932] [info] /app.zip requested
[2018-07-18 18:16:31:0423] [warn] Request to https://api.github.com/repos/Stereoscape/electronupdater/releases/assets/7921483 failed, status code: 400
[2018-07-18 18:16:31:0428] [warn] Error: Update download failed. The server sent an invalid response. Try again later.

[2018-07-18 18:16:31:0428] [error] Error: Error: Update download failed. The server sent an invalid response. Try again later.
[2018-07-18 18:16:31:0429] [info] Error in auto-updater. Error: Update download failed. The server sent an invalid response. Try again later.
[2018-07-18 18:16:31:0430] [error] Error: Error: Cannot download "https://api.github.com/repos/Stereoscape/electronupdater/releases/assets/7921483": Error: Cannot download "https://api.github.com/repos/Stereoscape/electronupdater/releases/assets/7921483", status 400: Bad Request
    at _this.doProxyUpdateFile.error (/Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:77:22)
    at ClientRequest.downloadRequest.httpExecutor.doRequest.downloadResponse (/Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:107:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at URLRequest.ClientRequest.urlRequest.on (/Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/electron.asar/browser/api/net.js:209:12)
    at emitOne (events.js:115:13)
    at URLRequest.emit (events.js:210:7)
From previous event:
    at MacUpdater.doDownloadUpdate (/Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:25:80)
    at /Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:393:25
From previous event:
    at MacUpdater.downloadUpdate (/Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:382:86)
    at /Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:369:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at MacUpdater._checkForUpdates (/Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at MacUpdater.checkForUpdates (/Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at MacUpdater.checkForUpdatesAndNotify (/Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:235:41)
    at App.<anonymous> (/Users/ferhatsen/Downloads/electron-updater-example-master/dist/electronupdater 9.app/Contents/Resources/app.asar/main.js:120:15)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
[2018-07-18 18:16:31:0430] [info] Error in auto-updater. Error: Cannot download "https://api.github.com/repos/Stereoscape/electronupdater/releases/assets/7921483": Error: Cannot download "https://api.github.com/repos/Stereoscape/electronupdater/releases/assets/7921483", status 400: Bad Request
[2018-07-18 18:16:36:0431] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://api.github.com/repos/Stereoscape/electronupdater/releases/assets/7921483)

**Comment by develar** [comment]
@Stereoscape Well, do you set token if you set private GitHub? Ok.. it seems you set it since NSIS works. Well, as stated, private GitHub repo for special cases and so it is often broken ;) I will check.

**Comment by Stereoscape** [comment]
@develar yes, it is set. process.env.GH_TOKEN is set in main.js and environment variable is also set. 

I made some debug logging of version in privategithubprovider. In MAC, it seems it also authenticates and reads the latest but maybe not able to get the download URL correctly?

`[2018-07-18 17:49:17:0526] [info] Checking for update
[2018-07-18 17:49:17:0526] [info] Checking for update...
[2018-07-18 17:49:17:0686] [info] Url private github provider baseURL /repos/Stereoscape/electronupdater/releases)
[2018-07-18 17:49:17:0686] [info] Url private github provider calculated baseURL https://api.github.com/repos/Stereoscape/electronupdater/releases/latest)
[2018-07-18 17:49:17:0686] [info] Url private github provider calculated baseURL https://api.github.com/repos/Stereoscape/electronupdater/releases/latest)
[2018-07-18 17:49:18:0773] [info] version calculated over json parse in private gitgub provider: {"url":"https://api.github.com/repos/Stereoscape/electronupdater/releases/11988444","assets_url":"https://api.github.com/repos/Stereoscape/electronupdater/releases/11988444/assets","upload_url":"https://uploads.github.com/repos/Stereoscape/electronupdater/releases/11988444/assets{?name,label}","html_url":"https://github.com/Stereoscape/electronupdater/releases/tag/v0.0.13","id":11988444,"node_id":"MDc6UmVsZWFzZTExOTg4NDQ0","tag_name":"v0.0.13","target_commitish":"master","name":"0.0.13","draft":false,"author":{"login":"Stereoscape","id":39617542,"node_id":"MDQ6VXNlcjM5NjE3NTQy","avatar_url":"https://avatars1.githubusercontent.com/u/39617542?v=4","gravatar_id":"","url":"https://api.github.com/users/Stereoscape","html_url":"https://github.com/Stereoscape","followers_url":"https://api.github.com/users/Stereoscape/followers","following_url":"https://api.github.com/users/Stereoscape/following{/other_user}","gists_url":"https://api.github.com/users/Stereoscape/gists{/gist_id}","starred_url":"https://api.github.com/users/Stereoscape/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Stereoscape/subscriptions","organizations_url":"https://api.github.com/users/Stereoscape/orgs","repos_url":"https://api.github.com/users/Stereoscape/repos","events_url":"https://api.github.com/users/Stereoscape/events{/privacy}","received_events_url":"https://api.github.com/users/Stereoscape/received_events","type":"User","site_admin":false},"prerelease":false,"created_at":"2018-07-18T08:58:49Z","published_at":"2018-07-18T14:48:56Z","assets":[{"url":"https://api.github.com/repos/Stereoscape/electronupdater/releases/assets/7920989","id":7920989,"node_id":"MDEyOlJlbGVhc2VBc3NldDc5MjA5ODk=","name":"electronupdater-0.0.13-mac.zip","label":"","uploader":{"login":"Stereoscape","id":39617542,"node_id":"MDQ6VXNlcjM5NjE3NTQy","avatar_url":"https://avatars1.githubusercontent.com/u/39617542?v=4","gravatar_id":"","url":"https://api.github.com/users/Stereoscape","html_url":"https://github.com/Stereoscape","followers_url":"https://api.github.com/users/Stereoscape/followers","following_url":"https://api.github.com/users/Stereoscape/following{/other_user}","gists_url":"https://api.github.com/users/Stereoscape/gists{/gist_id}","starred_url":"https://api.github.com/users/Stereoscape/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Stereoscape/subscriptions","organizations_url":"https://api.github.com/users/Stereoscape/orgs","repos_url":"https://api.github.com/users/Stereoscape/repos","events_url":"https://api.github.com/users/Stereoscape/events{/privacy}","received_events_url":"https://api.github.com/users/Stereoscape/received_events","type":"User","site_admin":false},"content_type":"application/zip","state":"uploaded","size":48200351,"download_count":0,"created_at":"2018-07-18T14:45:12Z","updated_at":"2018-07-18T14:47:37Z","browser_download_url":"https://github.com/Stereoscape/electronupdater/releases/download/v0.0.13/electronupdater-0.0.13-mac.zip"},{"url":"https://api.github.com/repos/Stereoscape/electronupdater/releases/assets/7920984","id":7920984,"node_id":"MDEyOlJlbGVhc2VBc3NldDc5MjA5ODQ=","name":"electronupdater-0.0.13.dmg","label":"","uploader":{"login":"Stereoscape","id":39617542,"node_id":"MDQ6VXNlcjM5NjE3NTQy","avatar_url":"https://avatars1.githubusercontent.com/u/39617542?v=4","gravatar_id":"","url":"https://api.github.com/users/Stereoscape","html_url":"https://github.com/Stereoscape","followers_url":"https://api.github.com/users/Stereoscape/followers","following_url":"https://api.github.com/users/Stereoscape/following{/other_user}","gists_url":"https://api.github.com/users/Stereoscape/gists{/gist_id}","starred_url":"https://api.github.com/users/Stereoscape/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Stereoscape/subscriptions","organizations_url":"https://api.github.com/users/Stereoscape/orgs","repos_url":"https://api.github.com/users/Stereoscape/repos","events_url":"https://api.github.com/users/Stereoscape/events{/privacy}","received_events_url":"https://api.github.com/users/Stereoscape/received_events","type":"User","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":49758934,"download_count":0,"created_at":"2018-07-18T14:45:05Z","updated_at":"2018-07-18T14:48:15Z","browser_download_url":"https://github.com/Stereoscape/electronupdater/releases/download/v0.0.13/electronupdater-0.0.13.dmg"},{"url":"https://api.github.com/repos/Stereoscape/electronupdater/releases/assets/7920983","id":7920983,"node_id":"MDEyOlJlbGVhc2VBc3NldDc5MjA5ODM=","name":"electronupdater-0.0.13.dmg.blockmap","label":"","uploader":{"login":"Stereoscape","id":39617542,"node_id":"MDQ6VXNlcjM5NjE3NTQy","avatar_url":"https://avatars1.githubusercontent.com/u/39617542?v=4","gravatar_id":"","url":"https://api.github.com/users/Stereoscape","html_url":"https://github.com/Stereoscape","followers_url":"https://api.github.com/users/Stereoscape/followers","following_url":"https://api.github.com/users/Stereoscape/following{/other_user}","gists_url":"https://api.github.com/users/Stereoscape/gists{/gist_id}","starred_url":"https://api.github.com/users/Stereoscape/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Stereoscape/subscriptions","organizations_url":"https://api.github.com/users/Stereoscape/orgs","repos_url":"https://api.github.com/users/Stereoscape/repos","events_url":"https://api.github.com/users/Stereoscape/events{/privacy}","received_events_url":"https://api.github.com/users/Stereoscape/received_events","type":"User","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":53501,"download_count":0,"created_at":"2018-07-18T14:45:05Z","updated_at":"2018-07-18T14:45:06Z","browser_download_url":"https://github.com/Stereoscape/electronupdater/releases/download/v0.0.13/electronupdater-0.0.13.dmg.blockmap"},{"url":"https://api.github.com/repos/Stereoscape/electronupdater/releases/assets/7920990","id":7920990,"node_id":"MDEyOlJlbGVhc2VBc3NldDc5MjA5OTA=","name":"latest-mac.json","label":"","uploader":{"login":"Stereoscape","id":39617542,"node_id":"MDQ6VXNlcjM5NjE3NTQy","avatar_url":"https://avatars1.githubusercontent.com/u/39617542?v=4","gravatar_id":"","url":"https://api.github.com/users/Stereoscape","html_url":"https://github.com/Stereoscape","followers_url":"https://api.github.com/users/Stereoscape/followers","following_url":"https://api.github.com/users/Stereoscape/following{/other_user}","gists_url":"https://api.github.com/users/Stereoscape/gists{/gist_id}","starred_url":"https://api.github.com/users/Stereoscape/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Stereoscape/subscriptions","organizations_url":"https://api.github.com/users/Stereoscape/orgs","repos_url":"https://api.github.com/users/Stereoscape/repos","events_url":"https://api.github.com/users/Stereoscape/events{/privacy}","received_events_url":"https://api.github.com/users/Stereoscape/received_events","type":"User","site_admin":false},"content_type":"application/json","state":"uploaded","size":187,"download_count":0,"created_at":"2018-07-18T14:45:12Z","updated_at":"2018-07-18T14:45:12Z","browser_download_url":"https://github.com/Stereoscape/electronupdater/releases/download/v0.0.13/latest-mac.json"},{"url":"https://api.github.com/repos/Stereoscape/electronupdater/releases/assets/7921028","id":7921028,"node_id":"MDEyOlJlbGVhc2VBc3NldDc5MjEwMjg=","name":"latest-mac.yml","label":"","uploader":{"login":"Stereoscape","id":39617542,"node_id":"MDQ6VXNlcjM5NjE3NTQy","avatar_url":"https://avatars1.githubusercontent.com/u/39617542?v=4","gravatar_id":"","url":"https://api.github.com/users/Stereoscape","html_url":"https://github.com/Stereoscape","followers_url":"https://api.github.com/users/Stereoscape/followers","following_url":"https://api.github.com/users/Stereoscape/following{/other_user}","gists_url":"https://api.github.com/users/Stereoscape/gists{/gist_id}","starred_url":"https://api.github.com/users/Stereoscape/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Stereoscape/subscriptions","organizations_url":"https://api.github.com/users/Stereoscape/orgs","repos_url":"https://api.github.com/users/Stereoscape/repos","events_url":"https://api.github.com/users/Stereoscape/events{/privacy}","received_events_url":"https://api.github.com/users/Stereoscape/received_events","type":"User","site_admin":false},"content_type":"text/yaml","state":"uploaded","size":494,"download_count":0,"created_at":"2018-07-18T14:48:16Z","updated_at":"2018-07-18T14:48:16Z","browser_download_url":"https://github.com/Stereoscape/electronupdater/releases/download/v0.0.13/latest-mac.yml"}],"tarball_url":"https://api.github.com/repos/Stereoscape/electronupdater/tarball/v0.0.13","zipball_url":"https://api.github.com/repos/Stereoscape/electronupdater/zipball/v0.0.13","body":""})`

**Comment by develar** [comment]
electron-updater 3.4.0

**Comment by RobertLowe** [comment]
This is was resolved for me after publishing another release *after* I made my repo public. So just make sure your repo is public, then publish, and things should be okay or at least that's how it was for me, you cant use a release that was published while the repo was private (that makes sense).
