### ISSUE TITLE
Cannot find module 'electron-download-tf'

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#2550]
* **Version**: 20.0.0

* **Target**: Windows NSIS Web (x64 & ia32)

Build crashes with the following error:

```
> media-presenter@1.0.11 dist:n C:\Users\johann.rekowski\Documents\Apps\Media-Presenter
> build --x64 --ia32

  • electron-builder version=20.0.0
  • loaded configuration file=C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\electron-builder.yml
  • writing effective config file=dist\electron-builder.yaml
  • skipped app dependencies rebuild reason=npmRebuild is set to false
  • packaging       platform=win32 arch=x64 electron=1.8.2-beta.5 appOutDir=dist\win-unpacked
Error: Cannot find module 'electron-download-tf'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Packager.packager.electronDownloader (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\src\index.ts:41:54)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\src\packager\dirPackager.ts:53:21
    at Generator.next (<anonymous>)
From previous event:
    at unpack (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\out\packager\dirPackager.js:55:21)
    at unpackElectron (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\src\packager\dirPackager.ts:27:10)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\src\platformPackager.ts:167:27
    at Generator.next (<anonymous>)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at WinPackager.doPack (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\out\platformPackager.js:274:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\src\platformPackager.ts:116:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\out\platformPackager.js:194:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\src\packager.ts:363:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
From previous event:
    at Packager.doBuild (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\out\packager.js:426:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\src\packager.ts:307:52
    at Generator.next (<anonymous>)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:149:20)
From previous event:
    at Packager._build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\out\packager.js:370:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\src\packager.ts:269:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Packager.build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\out\packager.js:326:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\src\index.ts:62:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-lib\out\index.js:61:21)
    at build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\builder.ts:217:10)
    at then (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Object.args [as handler] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\yargs.js:1042:24)
    at Object.get [as argv] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

I did a fresh `npm install`, I even deleted my `package-lock.json` beforehand to make sure it pulls the latest dependencies.

**Comment by develar** [comment]
Thanks for using pre-release version. Could you please try yarn instead of buggy npm?

**Comment by HitomiTenshi** [comment]
@develar Unfortunately no, our project uses some dependencies that do stuff with node-gyp.

I tried using yarn before and it didn't execute the node-gyp compilation stuff from those dependencies because of security reasons. I need my stuff to compile, even if yarn considers it unsafe.

I'd like to keep using npm.

**Comment by develar** [comment]
Ok, since you have to use npm, have you tried to `rm -rf node_modules` (and of course, because of bugs, `package-lock.json` must be also be removed, as you have already tried)?

**Comment by HitomiTenshi** [comment]
@develar Yes, I removed `node_modules` and `package-lock.json` before running `npm install`.

The previous electron-builder version (19.56.2) works fine.

**Comment by HitomiTenshi** [comment]
My OS is Windows 10 Pro x64, using the latest updates. Just saying, in case it only happens on Windows. I'll test on linux real quick to see if it's a Windows only issue.

**Comment by HitomiTenshi** [comment]
@develar Exactly the same error happens on Linux. I don't have a build target set for Linux, but it seems like electron-builder crashes before realizing that.

**Comment by HitomiTenshi** [comment]
Version 20.0.1 fixed the error for me 👍

**Comment by develar** [comment]
In the 20 release we will get rid of electron-download in favour of our new 8-4x faster downloader implemented in Go.

**Comment by HitomiTenshi** [comment]
Holy hell, I'm all for it! 👍
