### ISSUE TITLE
"Error: ditto" when auto-updating on mac

### ISSUE THREAD

**Issue by thealexbaron** [electron-userland/electron-builder#2563]
* **Electron Builder Version**: 19.56.1

* **Electron Updater**: 2.20.1

* **Target**: Mac

```
Error: ditto: /Users/SomeUser/Library/Caches/com.electron.webship-scale-reader.ShipIt/update.S98onKL/webship-scale-reader.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib: No such file or directory
    at /Applications/webship-scale-reader.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:44:12
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/webship-scale-reader.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:127:11)
    at /Applications/webship-scale-reader.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:25
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.downloadUpdate (/Applications/webship-scale-reader.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:382:11)
    at /Applications/webship-scale-reader.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:316:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/webship-scale-reader.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /Applications/webship-scale-reader.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/webship-scale-reader.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at MacUpdater.checkForUpdates (/Applications/webship-scale-reader.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Timeout._onTimeout (/Applications/webship-scale-reader.app/Contents/Resources/app.asar/webpack:/src/main/index.js:105:10)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by arantes555** [comment]
Seeing this too

**Comment by darshan-jain-29** [comment]
Got any solution for this?
