### ISSUE TITLE
Unable to build distributable releases for Windows under OS X

### ISSUE THREAD

**Issue by hzeroo** [electron-userland/electron-builder#258]
Distributable releases works fine for OS X, but i'm having trouble with the windows release. As the docs says, I've installed Caskroom/cask/xquartz, wine and mono with brew, but when i try to run it fails:

        Packaging app for platform win32 x64 using electron v0.37.2
        Error: Failed with exit code: 1
        Output:
        Intentando compilar el paquete desde 'xxxxxx.nuspec'. 
        ManifestMetadata is required.
        ManifestMetadata is required.
            at ChildProcess.<anonymous> (/usr/local/lib/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/spawn-promise.js:59:16)
            at emitTwo (events.js:100:13)
            at ChildProcess.emit (events.js:185:7)
            at maybeClose (internal/child_process.js:821:16)
            at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
        From previous event:
            at processImmediate [as _immediateCallback] (timers.js:383:17)
        From previous event:
            at Object.createWindowsInstaller (/usr/local/lib/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/index.js:207:16)
            at WinPackager.<anonymous> (/usr/local/lib/node_modules/electron-builder/src/winPackager.ts:123:50)
            at [object Generator].next (native)
        From previous event:
            at tsAwaiter (/usr/local/lib/node_modules/electron-builder/src/awaiter.ts:10:51)
            at Object.build (/usr/local/lib/node_modules/electron-builder/src/builder.ts:30:55)
            at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/src/build-cli.ts:41:2)
            at Module._compile (module.js:413:34)
            at Object.Module._extensions..js (module.js:422:10)
            at Module.load (module.js:357:32)
            at Function.Module._load (module.js:314:12)
            at Function.Module.runMain (module.js:447:10)
            at startup (node.js:139:18)
            at node.js:999:3

Packaging works fine, is the installer creation what fails.

**Comment by develar** [comment]
Please ask about it in the [windows-installer](https://github.com/electronjs/windows-installer/issues)

**Comment by havenchyk** [comment]
@hzeroo please create a ticket against `electron-winstaller` mention this issue there, so we can track it.

**Comment by develar** [comment]
Please try [3.0.0](https://github.com/electron-userland/electron-builder/releases/tag/v3.0.0) (`next` version). Please be aware of breaking changes (see release notes).

**Comment by hzeroo** [comment]
With 3.0.0:

        Packaging app for platform win32 x64 using electron v0.37.2
        Error: Failed with exit code: 255
        Output:
        System.InvalidOperationException: The input package file /Users/zero/Desktop/popcorn-electron/dist/win/popcorn.0.9.8.nupkg targets no platform and cannot be transformed into a release package.
        at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2 releaseNotesProcessor, System.Action`1 contentsPostProcessHook) [0x00000] in <filename unknown>:0 
        at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, Boolean generateMsi) [0x00000] in <filename unknown>:0 
        at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00000] in <filename unknown>:0 
        at Squirrel.Update.Program.main (System.String[] args) [0x00000] in <filename unknown>:0 

        at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2 releaseNotesProcessor, System.Action`1 contentsPostProcessHook) [0x00000] in <filename unknown>:0 
        at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, Boolean generateMsi) [0x00000] in <filename unknown>:0 
        at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00000] in <filename unknown>:0 
        at Squirrel.Update.Program.main (System.String[] args) [0x00000] in <filename unknown>:0 
            at ChildProcess.<anonymous> (/Users/zero/Desktop/popcorn-electron/node_modules/electron-winstaller-fixed/lib/spawn-promise.js:59:16)
            at emitTwo (events.js:100:13)
            at ChildProcess.emit (events.js:185:7)
            at maybeClose (internal/child_process.js:821:16)
            at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
        From previous event:
            at processImmediate [as _immediateCallback] (timers.js:383:17)
        From previous event:
            at Object.createWindowsInstaller (/Users/zero/Desktop/popcorn-electron/node_modules/electron-winstaller-fixed/lib/index.js:204:16)
            at WinPackager.<anonymous> (/Users/zero/Desktop/popcorn-electron/node_modules/electron-builder/src/winPackager.ts:123:50)
            at [object Generator].next (native)
        From previous event:
            at tsAwaiter (/Users/zero/Desktop/popcorn-electron/node_modules/electron-builder/src/awaiter.ts:10:51)
            at Object.build (/Users/zero/Desktop/popcorn-electron/node_modules/electron-builder/src/builder.ts:30:55)
            at Object.<anonymous> (/Users/zero/Desktop/popcorn-electron/node_modules/electron-builder/src/build-cli.ts:41:2)
            at Module._compile (module.js:413:34)
            at Object.Module._extensions..js (module.js:422:10)
            at Module.load (module.js:357:32)
            at Function.Module._load (module.js:314:12)
            at Function.Module.runMain (module.js:447:10)
            at startup (node.js:139:18)
            at node.js:999:3

**Comment by hzeroo** [comment]
With DEBUG:

    electron-windows-installer:main Created NuSpec file:
    <?xml version="1.0" encoding="utf-8"?>
    <package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>xxxxx</id>
        <title>xxxxx</title>
        <version>0.9.8</version>
        <authors>xxxxx xxxxx</authors>
        <owners>xxxxx xxxxx</owners>
        <iconUrl>https://raw.githubusercontent.com/atom/electron/master/atom/browser/resources/win/atom.ico</iconUrl>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>xxxxx</description>
        <copyright>Copyright © 2016 xxxxx xxxxx</copyright>
    </metadata>
    <files>
        <file src="locales/**" target="lib/net45/locales" />
        <file src="resources/**" target="lib/net45/resources" />
        <file src="*.bin" target="lib/net45" />
        <file src="*.dll" target="lib/net45" />
        <file src="*.pak" target="lib/net45" />
        <file src="Update.exe" target="lib/net45/squirrel.exe" />
        <file src="icudtl.dat" target="lib/net45/icudtl.dat" />
        <file src="LICENSE" target="lib/net45/LICENSE" />
        <file src="xxxxx.exe" target="lib/net45/xxxxx.exe" />
    </files>
    </package>
    +14ms
    electron-windows-installer:spawn Spawning /usr/bin/mono /Users/zero/Desktop/xxxxx-electron/node_modules/electron-builder/node_modules/electron-winstaller-fixed/vendor/nuget.exe pack /var/folders/mw/pk6fyxz91_g1_p6gprvplhsh0000gn/T/si-116223-10943-1nf7yqf/xxxxx.nuspec -BasePath /Users/zero/Desktop/xxxxx-electron/dist/xxxxx-win32-ia32 -OutputDirectory /var/folders/mw/pk6fyxz91_g1_p6gprvplhsh0000gn/T/si-116223-10943-1nf7yqf -NoDefaultExcludes +3ms
    electron-windows-installer:main Intentando compilar el paquete desde 'xxxxx.nuspec'. 
    Paquete '/var/folders/mw/pk6fyxz91_g1_p6gprvplhsh0000gn/T/si-116223-10943-1nf7yqf/xxxxx.0.9.8.nupkg' creado correctamente.
    +23s
    electron-windows-installer:spawn Spawning /usr/bin/mono /Users/zero/Desktop/xxxxx-electron/node_modules/electron-builder/node_modules/electron-winstaller-fixed/vendor/Update-Mono.exe --releasify /var/folders/mw/pk6fyxz91_g1_p6gprvplhsh0000gn/T/si-116223-10943-1nf7yqf/xxxxx.0.9.8.nupkg --releaseDir /Users/zero/Desktop/xxxxx-electron/dist/win --loadingGif /Users/zero/Desktop/xxxxx-electron/node_modules/electron-builder/node_modules/electron-winstaller-fixed/resources/install-spinner.gif --setupIcon /Users/zero/Desktop/xxxxx-electron/build/icon.ico --no-msi +0ms
    Error: Failed with exit code: 255
    Output:
    System.InvalidOperationException: Operation is not valid due to the current state of the object
    at System.Xml.XmlNodeListChildren+Enumerator.get_Current () [0x00000] in <filename unknown>:0 
    at System.Linq.Enumerable+<CreateOfTypeIterator>c__Iterator21`1[System.Xml.XmlElement].MoveNext () [0x00000] in <filename unknown>:0 
    at Squirrel.ContentType.Clean (System.Xml.XmlDocument doc) [0x00000] in <filename unknown>:0 
    at Squirrel.ReleasePackage.addDeltaFilesToContentTypes (System.String rootDirectory) [0x00000] in <filename unknown>:0 
    at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2 releaseNotesProcessor, System.Action`1 contentsPostProcessHook) [0x00000] in <filename unknown>:0 
    at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, Boolean generateMsi) [0x00000] in <filename unknown>:0 
    at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00000] in <filename unknown>:0 
    at Squirrel.Update.Program.main (System.String[] args) [0x00000] in <filename unknown>:0 

    at System.Xml.XmlNodeListChildren+Enumerator.get_Current () [0x00000] in <filename unknown>:0 
    at System.Linq.Enumerable+<CreateOfTypeIterator>c__Iterator21`1[System.Xml.XmlElement].MoveNext () [0x00000] in <filename unknown>:0 
    at Squirrel.ContentType.Clean (System.Xml.XmlDocument doc) [0x00000] in <filename unknown>:0 
    at Squirrel.ReleasePackage.addDeltaFilesToContentTypes (System.String rootDirectory) [0x00000] in <filename unknown>:0 
    at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2 releaseNotesProcessor, System.Action`1 contentsPostProcessHook) [0x00000] in <filename unknown>:0 
    at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, Boolean generateMsi) [0x00000] in <filename unknown>:0 
    at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00000] in <filename unknown>:0 
    at Squirrel.Update.Program.main (System.String[] args) [0x00000] in <filename unknown>:0 
        at ChildProcess.<anonymous> (/Users/zero/Desktop/xxxxx-electron/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/spawn-promise.js:59:16)
        at emitTwo (events.js:100:13)
        at ChildProcess.emit (events.js:185:7)
        at maybeClose (internal/child_process.js:821:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    From previous event:
        at processImmediate [as _immediateCallback] (timers.js:383:17)
    From previous event:
        at Object.createWindowsInstaller (/Users/zero/Desktop/xxxxx-electron/node_modules/electron-builder/node_modules/electron-winstaller-fixed/lib/index.js:210:16)
        at WinPackager.<anonymous> (/Users/zero/Desktop/xxxxx-electron/node_modules/electron-builder/src/winPackager.ts:111:72)
        at [object Generator].next (native)
    From previous event:
        at tsAwaiter (/Users/zero/Desktop/xxxxx-electron/node_modules/electron-builder/src/awaiter.ts:10:51)
        at Object.build (/Users/zero/Desktop/xxxxx-electron/node_modules/electron-builder/src/builder.ts:30:55)
        at Object.<anonymous> (/Users/zero/Desktop/xxxxx-electron/node_modules/electron-builder/src/build-cli.ts:41:2)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Function.Module.runMain (module.js:447:10)
        at startup (node.js:139:18)
        at node.js:999:3

**Comment by develar** [comment]
@hzeroo Thanks for debug log. I still don't understand, because I also use OS X. And it seems you install all required packages (wine and mono).

@hzeroo Could you please provide your `build` configuration?

Try to build only x64: `npm run dist -- --platform win32 --arch x64`

**Comment by develar** [comment]
@hzeroo Just to be sure, please `mono --version` and `wine --version`.

**Comment by hzeroo** [comment]
Ok, solved. All was caused due to a very old version of mono previously installed without brew, and when mono was launched the old version spawned. Removing the old version and checking that mono 4.2.X is used solved the issue, all is working perfectly right now.

Really thanks for you time @develar

**Comment by develar** [comment]
Na endlich. Thanks, so, we can tag 3.0 as `latest`.
