### ISSUE TITLE
Error: Application entry file "electron-app.js" does not exist. Seems like a wrong configuration.

### ISSUE THREAD

**Issue by slavkomae** [electron-userland/electron-builder#2585]
* **Version**: 20.0.4

* **Target**: Windows 10 x64

Stack trace:
```
Error: Application entry file "electron-app.js" does not exist. Seems like a wrong configuration.        
    at C:\Repos\Wallet.Client\node_modules\electron-builder-lib\src\platformPackager.ts:349:15           
From previous event:                                                                                     
    at WinPackager.checkFileInPackage (C:\Repos\Wallet.Client\node_modules\electron-builder-lib\out\platf
ormPackager.js:403:11)                                                                                   
    at C:\Repos\Wallet.Client\node_modules\electron-builder-lib\src\platformPackager.ts:373:16           
    at Generator.next (<anonymous>)                                                                      
    at C:\Repos\Wallet.Client\node_modules\graceful-fs\polyfills.js:287:18                               
    at FSReqWrap.oncomplete (fs.js:153:5)                                                                
From previous event:                                                                                     
    at WinPackager.sanityCheckPackage (C:\Repos\Wallet.Client\node_modules\electron-builder-lib\out\platf
ormPackager.js:421:11)                                                                                   
    at C:\Repos\Wallet.Client\node_modules\electron-builder-lib\src\platformPackager.ts:211:16           
    at Generator.next (<anonymous>)                                                                      
    at runCallback (timers.js:789:20)                                                                    
    at tryOnImmediate (timers.js:751:5)                                                                  
    at processImmediate [as _immediateCallback] (timers.js:722:5)                                        
From previous event:                                                                                     
    at WinPackager.doPack (C:\Repos\Wallet.Client\node_modules\electron-builder-lib\out\platformPackager.
js:274:11)                                                                                               
    at C:\Repos\Wallet.Client\node_modules\electron-builder-lib\src\platformPackager.ts:116:16           
    at Generator.next (<anonymous>)                                                                      
From previous event:                                                                                     
    at WinPackager.pack (C:\Repos\Wallet.Client\node_modules\electron-builder-lib\out\platformPackager.js
:194:11)                                                                                                 
    at C:\Repos\Wallet.Client\node_modules\electron-builder-lib\src\packager.ts:372:24                   
    at Generator.next (<anonymous>)                                                                      
    at xfs.stat (C:\Repos\Wallet.Client\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.j
s:56:16)                                                                                                 
    at C:\Repos\Wallet.Client\node_modules\graceful-fs\polyfills.js:287:18                               
    at FSReqWrap.oncomplete (fs.js:153:5)                                                                
From previous event:                                                                                     
    at Packager.doBuild (C:\Repos\Wallet.Client\node_modules\electron-builder-lib\out\packager.js:441:11)
    at C:\Repos\Wallet.Client\node_modules\electron-builder-lib\src\packager.ts:316:52                   
    at Generator.next (<anonymous>)                                                                      
    at C:\Repos\Wallet.Client\node_modules\graceful-fs\graceful-fs.js:99:16                              
    at C:\Repos\Wallet.Client\node_modules\graceful-fs\graceful-fs.js:43:10                              
    at FSReqWrap.oncomplete (fs.js:135:15)                                                               
From previous event:                                                                                     
    at Packager._build (C:\Repos\Wallet.Client\node_modules\electron-builder-lib\out\packager.js:385:11) 
    at C:\Repos\Wallet.Client\node_modules\electron-builder-lib\src\packager.ts:278:23                   
    at Generator.next (<anonymous>)                                                                      
    at runCallback (timers.js:789:20)                                                                    
    at tryOnImmediate (timers.js:751:5)                                                                  
    at processImmediate [as _immediateCallback] (timers.js:722:5)                                        
From previous event:                                                                                     
    at Packager.build (C:\Repos\Wallet.Client\node_modules\electron-builder-lib\out\packager.js:341:11)  
    at C:\Repos\Wallet.Client\node_modules\electron-builder-lib\src\index.ts:50:40                       
    at Generator.next (<anonymous>)                                                                      
From previous event:                                                                                     
    at build (C:\Repos\Wallet.Client\node_modules\electron-builder-lib\out\index.js:47:21)               
    at build (C:\Repos\Wallet.Client\node_modules\electron-builder\src\builder.ts:228:10)                
    at then (C:\Repos\Wallet.Client\node_modules\electron-builder\src\cli\cli.ts:48:33)                  
    at runCallback (timers.js:789:20)                                                                    
    at tryOnImmediate (timers.js:751:5)                                                                  
    at processImmediate [as _immediateCallback] (timers.js:722:5)                                        
From previous event:                                                                                     
    at Object.args [as handler] (C:\Repos\Wallet.Client\node_modules\electron-builder\src\cli\cli.ts:48:3
3)                                                                                                       
    at Object.runCommand (C:\Repos\Wallet.Client\node_modules\electron-builder\node_modules\yargs\lib\com
mand.js:235:44)                                                                                          
    at Object.parseArgs [as _parseArgs] (C:\Repos\Wallet.Client\node_modules\electron-builder\node_module
s\yargs\yargs.js:1014:30)                                                                                
    at Object.get [as argv] (C:\Repos\Wallet.Client\node_modules\electron-builder\node_modules\yargs\yarg
s.js:957:21)                                                                                             
    at Object.<anonymous> (C:\Repos\Wallet.Client\node_modules\electron-builder\src\cli\cli.ts:42:15)    
    at Module._compile (module.js:643:30)                                                                
    at Object.Module._extensions..js (module.js:654:10)                                                  
    at Module.load (module.js:556:32)                                                                    
    at tryModuleLoad (module.js:499:12)                                                                  
    at Function.Module._load (module.js:491:3)                                                           
    at Function.Module.runMain (module.js:684:10)                                                        
    at startup (bootstrap_node.js:187:16)                                                                
    at bootstrap_node.js:608:3                                                                           
```

Package.json:
```json
{
  "name": "Integra-Wallet-Client",
    "description": "Client application for accessing Integra Ledger infrastructure",
    "author": "Integra Ledger",
  "version": "0.0.0",
  "license": "MIT",
  "main": "electron-app.js",
  "scripts": {
    "ng": "ng",
    "start": "npm run build.ng && npm run build.tasks && npm run build.electron && npm run start.electron",
    "start.watch": "npm run build.ng.watch",
    "start.electron": "electron dist/electron-app.js",
    "watch": "npm run build.tasks && npm run build.electron && npm run build.watch && npm run start.electron",
    "build": "ng build --base-href . && npm run build.electron",
    "build.prod": "ng build --prod --base-href . && npm run build.electron",
    "build.ng": "ng build --base-href .",
    "build.ng.watch": "ng build --base-href . --watch",
    "build.electron": "gulp build.electron",
    "build.tasks": "gulp build.tasks",
    "build.watch": "gulp build.default",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "bundle.clean": "gulp bundle.clean",
    "bundle.prepare": "npm run bundle.prepare.npm && npm run bundle.clean",
    "bundle.prepare.npm": "gulp build.npm.copy",
    "bundle.mac": "npm run bundle.prepare && electron-packager dist/ demo --platform=darwin --arch=x64 --overwrite --out=bundles",
    "bundle.windows": "npm run bundle.prepare && electron-packager dist/ demo --platform=win32 --overwrite --out=bundles",
    "bundle.linux": "npm run bundle.prepare && electron-packager dist/ demo --platform=linux --overwrite --out=bundles",
    "electron-packager": "electron-packager"
  },
    "build": {
        "appId": "integra.wallet",
        "asar": true,
        "productName": "Integra-Wallet",
        "extends": null
    },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "body-parser": "^1.18.2",
    "bootstrap": "^4.0.0",
    "cookie-parser": "^1.4.3",
    "core-js": "^2.4.1",
    "electron-connect": "^0.4.8",
    "electron-log": "^2.2.14",
    "electron-request-response": "^1.0.3",
    "express": "^4.16.2",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "morgan": "^1.9.0",
    "popper.js": "^1.12.9",
    "rxjs": "^5.1.0",
    "serve-favicon": "^2.4.5",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.8",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.99",
    "codelyzer": "~2.0.0",
      "electron": "^1.8.2",
    "electron-builder": "^20.0.4",
    "electron-debug": "^1.0.0",
    "electron-packager": "^8.7.2",
    "electron-prebuilt": "^1.4.13",
    "gulp": "^3.9.1",
    "gulp-debug": "^3.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^0.6.1",
    "gulp-run": "^1.7.1",
    "gulp-shell": "^0.6.3",
    "gulp-tsc": "^1.3.2",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "load-gulp-tasks": "^0.1.0",
    "node-sass": "^4.5.3",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0",
    "yargs": "^8.0.1"
  }
}
```

In my case, app.asar is being generated.

I also have electron-app.js right under `\dist`.

The app is buildable and runnable with `npm run start`.

As you can see above, I tried the "extends": null workaround -- no dice.

Thanks in advance.

**Comment by develar** [comment]
> "main": "electron-app.js"

So, it will not work when it will be packed. Or it works?

**Comment by davincif** [comment]
Did u manage to solve this? I'm having a similar ```⨯ Application entry file "/home/../build/linux-unpacked/resources/app/dist/index.js" does not exist. Seems like a wrong configuration.  stackTrace=```

```json
{
  "name": "index",
  "version": "0.0.0",
  "scripts": {
    "serve": "ng serve",
    "start": "npm run build && electron ./dist/index.js",
    "start:electron": "electron ./dist/index.js",
    "pack": "npm run build && npm run pack-only",
    "build": "npm run build:angular && npm run build:electron",
    "build:angular": "ng build --aot --prod --base-href=./",
    "build:electron": "tsc --project ./electron/ && mv ./dist/main.js ./dist/index.js",
    "pack-only": "electron-builder build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "axios": "^0.19.0",
    "dotenv": "^8.2.0",
    "getmac": "^1.4.6",
    "hashids": "^1.2.2",
    "image-size": "^0.7.4",
    "jimp": "^0.6.4",
    "nw": "^0.42.5",
    "querystring": "^0.2.0",
    "quicksorter": "^1.0.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.19",
    "@angular/cli": "~8.3.19",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "electron": "^7.1.2",
    "electron-builder": "^21.2.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  },
  "build": {
    "appId": "alltiming-index",
    "asar": false,
    "electronUpdaterCompatibility": true,
    "directories": {
      "buildResources": "./dist",
      "output": "./build"
    },
    "linux": {
      "target": [
        {
          "target": "AppImage",
          "arch": [
            "x64"
          ]
        }
      ]
    }
  }
}
```
