### ISSUE TITLE
Travis CI Linux build hangs on downloading app-builder

### ISSUE THREAD

**Issue by meltedspark** [electron-userland/electron-builder#2594]
* **Version**:  19.56.2

* **Target**: Linux

When building to linux in Travis CI the build hangs on "downloading app-builder" step. It's pretty small file I believe the size is not a problem here. I've also tried to set timeout 20 mins, still getting the same result.

>   • electron-builder version=19.56.2
>   • publishing will be skipped reason=current build is a part of pull request solution=
>                                  set env PUBLISH_FOR_PULL_REQUEST to true to force code signing
>                                  There are serious security concerns with PUBLISH_FOR_PULL_REQUEST=true (see the  CircleCI documentation (https://circleci.com/docs/1.0/fork-pr-builds/) for details)
>                                  If you have SSH keys, sensitive env vars or AWS credentials stored in your project settings and untrusted forks can make pull requests against your repo, then this option isn't for you.
>   • loaded configuration file=/home/travis/build/meltedspark/electron-angular-native/electron-builder.yaml
>   • description is missed in the package.json appPackageFile=/home/travis/build/meltedspark/electron-angular-native/dist/package.json
>   • author is missed in the package.json appPackageFile=/home/travis/build/meltedspark/electron-angular-native/dist/package.json
>   • executing node-gyp rebuild arch=x64
>   • installing production dependencies platform=linux arch=x64 appDir=/home/travis/build/meltedspark/electron-angular-native/dist
>   • asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available
>   • packaging       platform=linux arch=x64 electron=1.8.2 appOutDir=build-artifacts/linux-unpacked
>   • building        target=AppImage arch=x64 file=build-artifacts/ElectronAngularNativeApp-1.0.0-x86_64.AppImage
>   • downloading     path=/home/travis/.cache/electron-builder/app-builder/app-builder-v0.6.1-x64 url=https://github.com/develar/app-builder/releases/download/v0.6.1/app-builder-v0.6.1-linux-x64.7z
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

Repository: https://github.com/meltedspark/electron-angular-native

[electron-builder configuration](https://github.com/meltedspark/electron-angular-native/blob/e2e-testing-support/electron-builder.yaml)
[Travis CI configuration](https://github.com/meltedspark/electron-angular-native/blob/e2e-testing-support/.travis.yml)

When I build locally for Windows it builds OK.

**Comment by meltedspark** [comment]
**UPDATE:**
Just have run it on local linux machine. It seems to hang on building AppImage step:

>   • electron-builder version=19.56.2
>   • loaded configuration file=/home/genomics/dev/playground/electron-angular-native/electron-builder.yaml
>   • description is missed in the package.json appPackageFile=/home/genomics/dev/playground/electron-angular-native/dist/package.json
>   • author is missed in the package.json appPackageFile=/home/genomics/dev/playground/electron-angular-native/dist/package.json
>   • writing effective config file=build-artifacts/electron-builder.yaml
>   • executing node-gyp rebuild arch=x64
>   • installing production dependencies platform=linux arch=x64 appDir=/home/genomics/dev/playground/electron-angular-native/dist
>   • asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available
>   • packaging       platform=linux arch=x64 electron=1.8.2 appOutDir=build-artifacts/linux-unpacked
>   • building        target=AppImage arch=x64 file=build-artifacts/ElectronAngularNativeApp-1.0.0-x86_64.AppImage

**Comment by meltedspark** [comment]
**UPDATE 2:**
It seems that there is an error eventually, but the task wouldn't finish until I press `Ctrl+C`.
After I forcibly finish it, the following stack trace appears:
```
Error: Exit code: null. Command failed: /home/meltedspark/.cache/electron-builder/app-builder/app-builder-v0.6.1-x64/app-builder icon --format set --root /home/meltedspark/dev/playground/electron-angular-native/build-resources --root /home/meltedspark/dev/playground/electron-angular-native --input icons --input /home/meltedspark/dev/playground/electron-angular-native/src/favicon.icns --input /home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/templates/linux/electron-icons

    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/builder-util/src/util.ts:122:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
    at exec (/home/meltedspark/dev/playground/electron-angular-native/node_modules/builder-util/src/util.ts:85:3)
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/platformPackager.ts:586:23
    at Generator.next (<anonymous>)
    at LOOP (fs.js:1745:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at LinuxPackager.resolveIcon (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/out/platformPackager.js:623:11)
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:35:35
    at Generator.next (<anonymous>)
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:68:11)
    at Lazy.LinuxTargetHelper.iconPromise.Lazy (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:13:54)
    at Lazy.get value [as value] (/home/meltedspark/dev/playground/electron-angular-native/node_modules/lazy-val/src/main.ts:18:23)
    at LinuxTargetHelper.get icons [as icons] (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:21:29)
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:137:61
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/home/meltedspark/dev/playground/electron-angular-native/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at AppImageTarget.copyIcons (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:220:11)
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:53:37
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:186:11)
    at taskManager.addTask.default.map.it (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/platformPackager.ts:119:67)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/platformPackager.ts:119:23)
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at LinuxPackager.pack (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/out/platformPackager.js:196:11)
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/packager.ts:364:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/meltedspark/dev/playground/electron-angular-native/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/out/packager.js:432:11)
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/packager.ts:308:52
    at Generator.next (<anonymous>)
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/out/packager.js:376:11)
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/src/packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder-lib/out/packager.js:332:11)
    at /home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder/node_modules/yargs/yargs.js:1014:30)
    at Object.get [as argv] (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/meltedspark/dev/playground/electron-angular-native/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at findNodeScript.then.existing (/usr/lib/node_modules/npm/node_modules/libnpx/index.js:266:14)
    at <anonymous>

**Comment by develar** [comment]
Please use 20.0.6.
