### ISSUE TITLE
create-self-signed-cert throws with Error: spawn EACCES

### ISSUE THREAD

**Issue by dwalintukan** [electron-userland/electron-builder#2605]
* **Version**: 20.0.5
* **Target**: NSIS, x64 and ia32

After trying to create a self-signed cert for windows:
```
./node_modules/.bin/electron-builder create-self-signed-cert --publisher "Bodhi"
```

Getting this error:
```
Error: spawn EACCES
    at _errnoException (util.js:999:13)
    at ChildProcess.spawn (internal/child_process.js:340:11)
    at exports.spawn (child_process.js:499:9)
    at exports.execFile (child_process.js:209:15)
    at Promise (/Users/deric/coding/bodhi-graphql/node_modules/builder-util/src/util.ts:88:5)
    at new Promise (<anonymous>)
    at exec (/Users/deric/coding/bodhi-graphql/node_modules/builder-util/src/util.ts:87:3)
    at /Users/deric/coding/bodhi-graphql/node_modules/electron-builder/src/cli/create-self-signed-cert.ts:22:11
    at Generator.next (<anonymous>)
From previous event:
    at createSelfSignedCert (/Users/deric/coding/bodhi-graphql/node_modules/electron-builder/out/cli/create-self-signed-cert.js:40:21)
    at __dirname.default.command.command.command.command.argv (/Users/deric/coding/bodhi-graphql/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at then (/Users/deric/coding/bodhi-graphql/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at Object.args [as handler] (/Users/deric/coding/bodhi-graphql/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/Users/deric/coding/bodhi-graphql/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/deric/coding/bodhi-graphql/node_modules/yargs/yargs.js:1014:30)
    at Object.get [as argv] (/Users/deric/coding/bodhi-graphql/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/deric/coding/bodhi-graphql/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

Looks like a permissions issue, but I checked the binary file that is being executed by `spawn` and it has all read and execute permissions. How do I fix this?

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.

**Comment by dwalintukan** [comment]
@develar Should this be done in my `.bash_profile`?

**Comment by develar** [comment]
Ouch, this command works only on Windows 10. Not on Linux/macOS. Please use Keychain Access -> Keychain Access App menu -> Certificate Assistant
![screen shot 2018-02-19 at 16 27 02](https://user-images.githubusercontent.com/350686/36385065-c1807e0e-1591-11e8-8c51-3c3f07d96a15.png)
.

**Comment by dwalintukan** [comment]
@develar Ah I see. Will do. Do self-signed certificates solve the antivirus flagging as malicious issue? Or will I need to get a trusted cert?

**Comment by develar** [comment]
On macOS you in any case need to buy an Apple developer cert. On Windows  you can simply wait several weeks or days until your download location will be not considered trusted (it depends), but yes — for commercial app better to buy cert.

> Do self-signed certificates solve

No, only makes situation worse :)
