### ISSUE TITLE
Error publishing to github when building on travis 

### ISSUE THREAD

**Issue by jbleuzen** [electron-userland/electron-builder#261]
Hi, 
I have error on my Travis instance when building my app :  GitHub Personal Access Token is not specified. The fact is I don't want to publish to github so I want to disable this publish thing.

I've added this in my package.json (the developper one) : 

```json
"build": {
"publish": "never"
...
}
```

But when I read the docs, I see "But please consider to use automatic rules and don't specify publish explicitly". So, is the "publish" attribute used or not ???

**Comment by develar** [comment]
Please provide full stack trace of error. Must be no error if you use don't use script named `release`.

**Comment by jbleuzen** [comment]
I don't use `npm release` but `npm run dist`, here is the output i have as "raw log" in Travis : 

```
Tag v0.1.0 is defined, so artifacts will be published
Installing app dependencies for arch x64 to /Users/travis/build/Product/web-app-desktop/app
Packaging app for platform darwin x64 using electron v0.36.8
App is not signed: CSC_LINK or CSC_NAME are not specified
Creating DMG
Creating ZIP for Squirrel.Mac
Unhandled rejection Error: GitHub Personal Access Token is not specified
    at new GitHubPublisher (/Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/gitHubPublisher.ts:36:13)
    at /Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/builder.ts:23:12
    at [object Generator].next (native)
From previous event:
    at tsAwaiter (/Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/awaiter.ts:10:51)
    at createPublisher (/Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/builder.ts:12:146)
    at EventEmitter.<anonymous> (/Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/builder.ts:81:49)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at MacPackager.dispatchArtifactCreated (/Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/platformPackager.ts:84:28)
    at /Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/macPackager.ts:89:49
From previous event:
    at MacPackager.packageInDistributableFormat (/Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/macPackager.ts:89:10)
    at Packager.<anonymous> (/Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/packager.ts:79:33)
    at [object Generator].next (native)
    at processImmediate [as _immediateCallback] (timers.js:516:17)
From previous event:
    at tsAwaiter (/Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/awaiter.ts:10:51)
    at Object.build (/Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/builder.ts:30:55)
    at Object.<anonymous> (/Users/travis/build/Product/web-app-desktop/node_modules/electron-builder/src/build-cli.ts:41:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by jbleuzen** [comment]
I forgot to mention that even when I set the argument 'publish' to 'never' with `
npm run dist -p never`, I also get the error...

**Comment by jbleuzen** [comment]
It looks like no body have input to give me for this... 
I looked the source and don't see a reason why the github publisher is running.

Maybe someone can help me reproduce the Travis setup so that I can edit code on my machine to fix this ?

**Comment by develar** [comment]
@jbleuzen I was returned from vacation and there were another issues to fix (remember, I work on project in my spare time by morning :)). Now I am going to investigate it. You can expect fix/solution today.

**Comment by jbleuzen** [comment]
@develar didn't mean to be too pressing. Sorry about that and I hoped your vacation were fun :p

I was also offering help if I can replicate travis env so I can make some printf debug :smile:  
I looked at the code and don't understand why I get that message on travis only.

**Comment by jbleuzen** [comment]
Thanks @develar it's working !
