### ISSUE TITLE
app-builder Linux images 'panic: send on closed channel'

### ISSUE THREAD

**Issue by mykter** [electron-userland/electron-builder#2621]
* **Version**: 20.0.8

* **Target**: snap

```
  • building        target=AppImage arch=x64 file=dist/TagTime-desktop-0.7.1-x86_64.AppImage
panic: send on closed channel
goroutine 6 [running]:
github.com/develar/app-builder/pkg/util.mapAsync.func1(0xc4200322a0, 0xc420032230, 0xc42002a420, 0xc42002a3c0, 0xc420142930)
	/Users/develar/go/src/github.com/develar/app-builder/pkg/util/async.go:56 +0xc9
created by github.com/develar/app-builder/pkg/util.mapAsync
	/Users/develar/go/src/github.com/develar/app-builder/pkg/util/async.go:40 +0x181
Error: /home/travis/build/mykter/TagTime-desktop/node_modules/app-builder-bin-linux/x64/app-builder exited with code 2
    at ChildProcess.childProcess.once.code (/home/travis/build/mykter/TagTime-desktop/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at LinuxPackager.resolveIcon (/home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/out/platformPackager.js:610:11)
    at /home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:41:35
    at Generator.next (<anonymous>)
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:72:11)
    at Lazy.LinuxTargetHelper.iconPromise.Lazy (/home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:13:54)
    at Lazy.get value [as value] (/home/travis/build/mykter/TagTime-desktop/node_modules/lazy-val/src/main.ts:18:23)
    at LinuxTargetHelper.get icons [as icons] (/home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:21:29)
    at /home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/src/targets/snap.ts:132:23
    at Generator.next (<anonymous>)
```

You can see it 'live' here: https://travis-ci.org/mykter/TagTime-desktop/jobs/344539730

Curiously this only seems to be happening on travis ubuntu 14.04 but not my local 16.04 machine. Perhaps a different version of snapcraft - 2.35 locally vs 2.39 on travis? But then it seems to be about icons rather than the snap, so probably not.

Travis is running openjpeg-tools amd64 1.3+dfsg-4.7ubuntu1

(A `DEBUG=electron-builder` build is running here: https://travis-ci.org/mykter/TagTime-desktop/jobs/344551889 - hopefully it will provide more info when done)

**Comment by mykter** [comment]
Thanks for the quick fixes on previous issues, I really appreciate the options electron-builder enables me to offer users!

**Comment by kspearrin** [comment]
I don't think snapcraft works on 14.04

**Comment by mykter** [comment]
OK here's the debug output. It isn't snapcraft related.

```
• spawning        command=/home/travis/build/mykter/TagTime-desktop/node_modules/app-builder-bin-linux/x64/app-builder clear-exec-stack --input /home/travis/build/mykter/TagTime-desktop/dist/linux-unpacked/tagtime-desktop
  • exited          command=app-builder code=0 pid=28980
  • building        target=snap arch=x64 file=dist/tagtime-desktop_0.7.1_amd64.snap
  • building        target=AppImage arch=x64 file=dist/TagTime-desktop-0.7.1-x86_64.AppImage
  • spawning        command=/home/travis/build/mykter/TagTime-desktop/node_modules/app-builder-bin-linux/x64/app-builder icon --format set --root /home/travis/build/mykter/TagTime-desktop/build --root /home/travis/build/mykter/TagTime-desktop --out /home/travis/build/mykter/TagTime-desktop/dist/.icon-set --input icons --input resources/icon.icns --input /home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/templates/linux/electron-icons
  • path doesn't exist        path=/home/travis/build/mykter/TagTime-desktop/build/icons
  • path doesn't exist        path=/home/travis/build/mykter/TagTime-desktop/icons
  • path doesn't exist        path=/home/travis/build/mykter/TagTime-desktop/build/icon.png
  • path doesn't exist        path=/home/travis/build/mykter/TagTime-desktop/icon.png
  • path doesn't exist        path=/home/travis/build/mykter/TagTime-desktop/build/resources/icon.icns
  • path resolved             outputFormat=set path=/home/travis/build/mykter/TagTime-desktop/resources/icon.icns
  • skip unsupported icns sub image format file=/home/travis/build/mykter/TagTime-desktop/resources/icon.icns type=s8mk
  • skip unsupported icns sub image format file=/home/travis/build/mykter/TagTime-desktop/resources/icon.icns type=il32
  • skip unsupported icns sub image format file=/home/travis/build/mykter/TagTime-desktop/resources/icon.icns type=h8mk
  • skip unsupported icns sub image format file=/home/travis/build/mykter/TagTime-desktop/resources/icon.icns type=it32
  • skip unsupported icns sub image format file=/home/travis/build/mykter/TagTime-desktop/resources/icon.icns type=is32
  • skip unsupported icns sub image format file=/home/travis/build/mykter/TagTime-desktop/resources/icon.icns type=ih32
  • skip unsupported icns sub image format file=/home/travis/build/mykter/TagTime-desktop/resources/icon.icns type=t8mk
  • skip unsupported icns sub image format file=/home/travis/build/mykter/TagTime-desktop/resources/icon.icns type=l8mk
  • map async                 taskCount=2
  • execute command           args=[opj_decompress -quiet -i /home/travis/build/mykter/TagTime-desktop/dist/.icon-set/icon_ic09.jp2 -o /home/travis/build/mykter/TagTime-desktop/dist/.icon-set/icon_512.png] path=opj_decompress
  • open /home/travis/build/mykter/TagTime-desktop/dist/.icon-set/icon_512.png: no such file or directory
github.com/develar/app-builder/pkg/icons.LoadImage
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/image-util.go:27
github.com/develar/app-builder/pkg/icons.multiResizeImage
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icns-to-png.go:125
github.com/develar/app-builder/pkg/icons.ConvertIcnsToPng
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icns-to-png.go:61
github.com/develar/app-builder/pkg/icons.ConvertIcon
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:148
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:26
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:59
runtime.main
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361
  ⨯ open /home/travis/build/mykter/TagTime-desktop/dist/.icon-set/icon_512.png: no such file or directory
github.com/develar/app-builder/pkg/icons.LoadImage
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/image-util.go:27
github.com/develar/app-builder/pkg/icons.multiResizeImage
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icns-to-png.go:125
github.com/develar/app-builder/pkg/icons.ConvertIcnsToPng
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icns-to-png.go:61
github.com/develar/app-builder/pkg/icons.ConvertIcon
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:148
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:26
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:59
runtime.main
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361
  • exited          command=app-builder code=1 pid=28984
  • async task error error=/home/travis/build/mykter/TagTime-desktop/node_modules/app-builder-bin-linux/x64/app-builder exited with code 1
Error: /home/travis/build/mykter/TagTime-desktop/node_modules/app-builder-bin-linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/travis/build/mykter/TagTime-desktop/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at LinuxPackager.resolveIcon (/home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/out/platformPackager.js:610:11)
    at /home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:41:35
    at Generator.next (<anonymous>)
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:72:11)
    at Lazy.LinuxTargetHelper.iconPromise.Lazy (/home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:13:54)
    at Lazy.get value [as value] (/home/travis/build/mykter/TagTime-desktop/node_modules/lazy-val/src/main.ts:18:23)
    at LinuxTargetHelper.get icons [as icons] (/home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:21:29)
    at /home/travis/build/mykter/TagTime-desktop/node_modules/electron-builder-lib/src/targets/snap.ts:132:23
    at Generator.next (<anonymous>)
```
