### ISSUE TITLE
Error: No such command "pack".

### ISSUE THREAD

**Issue by vladimiry** [electron-userland/electron-builder#2625]
"electron-builder": "20.0.8",

--linux snap --x64

```
Error: No such command "pack".
Error: /project/node_modules/app-builder-bin-linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/project/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at SnapTarget.build (/project/node_modules/electron-builder-lib/out/targets/snap.js:174:11)
    at taskManager.addTask.default.map.it (/project/node_modules/electron-builder-lib/src/platformPackager.ts:121:67)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/project/node_modules/electron-builder-lib/src/platformPackager.ts:121:23)
    at /project/node_modules/electron-builder-lib/src/platformPackager.ts:116:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at LinuxPackager.pack (/project/node_modules/electron-builder-lib/out/platformPackager.js:188:11)
    at /project/node_modules/electron-builder-lib/src/packager.ts:372:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/project/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:136:15)
From previous event:
    at Packager.doBuild (/project/node_modules/electron-builder-lib/out/packager.js:441:11)
    at /project/node_modules/electron-builder-lib/src/packager.ts:316:52
From previous event:
    at Packager._build (/project/node_modules/electron-builder-lib/out/packager.js:385:11)
    at /project/node_modules/electron-builder-lib/src/packager.ts:278:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Packager.build (/project/node_modules/electron-builder-lib/out/packager.js:341:11)
    at /project/node_modules/electron-builder-lib/src/index.ts:50:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/project/node_modules/electron-builder-lib/out/index.js:47:21)
    at build (/project/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/project/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Object.args [as handler] (/project/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/project/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/project/node_modules/yargs/yargs.js:1024:28)
    at Object.get [as argv] (/project/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/project/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

- Console output log https://travis-ci.org/vladimiry/protonmail-desktop-app/jobs/344737146
- electron-builder.yml https://github.com/vladimiry/protonmail-desktop-app/blob/c5a8f9ae8c689eb352d1ac947fed87f9fada5bdf/electron-builder.yml
- package.json https://github.com/vladimiry/protonmail-desktop-app/blob/c5a8f9ae8c689eb352d1ac947fed87f9fada5bdf/package.json
- .travis.yml https://github.com/vladimiry/protonmail-desktop-app/blob/c5a8f9ae8c689eb352d1ac947fed87f9fada5bdf/.travis.yml
- docker image `electronuserland/builder:8`

**Comment by ExtendLord** [comment]
```
 ⨯ exit status 2
output: Usage: snapcraft [OPTIONS] COMMAND [ARGS]...

Error: No such command "pack".


Error: /home/lol/Desktop/DeezLoader-Reborn/node_modules/app-builder-bin-linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/lol/Desktop/DeezLoader-Reborn/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (events.js:255:19)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
From previous event:
    at SnapTarget.build (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/out/targets/snap.js:174:11)
    at taskManager.addTask.default.map.it (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/src/platformPackager.ts:121:67)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/src/platformPackager.ts:121:23)
    at /home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/src/platformPackager.ts:116:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at LinuxPackager.pack (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/out/platformPackager.js:188:11)
    at /home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/src/packager.ts:372:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/lol/Desktop/DeezLoader-Reborn/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/lol/Desktop/DeezLoader-Reborn/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:167:5)
From previous event:
    at Packager.doBuild (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/out/packager.js:441:11)
    at /home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/src/packager.ts:316:52
    at Generator.next (<anonymous>)
    at /home/lol/Desktop/DeezLoader-Reborn/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/lol/Desktop/DeezLoader-Reborn/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:149:20)
From previous event:
    at Packager._build (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/out/packager.js:385:11)
    at /home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/src/packager.ts:278:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Packager.build (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/out/packager.js:341:11)
    at /home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/src/index.ts:50:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder-lib/out/index.js:47:21)
    at build (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Object.args [as handler] (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/home/lol/Desktop/DeezLoader-Reborn/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/lol/Desktop/DeezLoader-Reborn/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/home/lol/Desktop/DeezLoader-Reborn/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/lol/Desktop/DeezLoader-Reborn/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dist: `electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lol/.npm/_logs/2018-02-22T14_33_38_706Z-debug.log
```
[2018-02-22T14_33_38_706Z-debug.log](https://github.com/electron-userland/electron-builder/files/1748266/2018-02-22T14_33_38_706Z-debug.log)

**Comment by develar** [comment]
`snapcraft --version`?

**Comment by vladimiry** [comment]
snapcraft version is 2.34, the one comes with `electronuserland/builder:8`, see links in the first message

**Comment by vladimiry** [comment]
If I use `electronuserland/builder` / `electronuserland/builder:9` docker image, build fails with `exec: "snapcraft": executable file not found in $PATH` error

- travis output https://travis-ci.org/vladimiry/protonmail-desktop-app/jobs/344997375.
- travis config https://github.com/vladimiry/protonmail-desktop-app/blob/aa9d4ecf97de48f06154f3f9efe401f54cc2bc8b/.travis.yml

**Comment by vladimiry** [comment]
If I do `PATH=/snap/bin:$PATH` explicitly before running electron-builder, then `exec: "snapcraft": executable file not found in $PATH` error is gone, running with `electronuserland/builder` image https://github.com/vladimiry/protonmail-desktop-app/blob/60988931b28efc4dfd8474a311b076dc9cb26a7d/.travis.yml#L63 So issue is solved for me.

**Comment by michaldev** [comment]
I have the same problem
