### ISSUE TITLE
node-gyp permissions error

### ISSUE THREAD

**Issue by dzt** [electron-userland/electron-builder#2637]
* **19.56.2**: 

* **macOS**: 

When running `npm run dist:mac` (`electron-builder --mac`) I get a permissions error with node-gyp

```
Error: npm exited with code 1
Error output:
sh: build_log.txt: Permission denied
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-electron-v1.8-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and electron@1.8.2 (electron-v1.8 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /Users/peter/Desktop/shopify-electron/node_modules/fsevents
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/peter/Desktop/shopify-electron/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 17.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/peter/Desktop/shopify-electron/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/peter/Desktop/shopify-electron/node_modules/fsevents
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fsevents@1.1.3 install: `node install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peter/.npm/_logs/2018-02-25T00_22_16_633Z-debug.log

    at ChildProcess.childProcess.once.code (/Users/peter/.config/yarn/global/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
    at rebuild (/Users/peter/.config/yarn/global/node_modules/electron-builder-lib/out/util/yarn.js:93:22)
    at /Users/peter/.config/yarn/global/node_modules/electron-builder-lib/src/util/yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at installOrRebuild (/Users/peter/.config/yarn/global/node_modules/electron-builder-lib/out/util/yarn.js:31:21)
    at /Users/peter/.config/yarn/global/node_modules/electron-builder-lib/src/packager.ts:450:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/Users/peter/.config/yarn/global/node_modules/electron-builder-lib/out/packager.js:505:11)
    at /Users/peter/.config/yarn/global/node_modules/electron-builder-lib/src/packager.ts:364:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/Users/peter/.config/yarn/global/node_modules/electron-builder-lib/out/packager.js:441:11)
    at /Users/peter/.config/yarn/global/node_modules/electron-builder-lib/src/packager.ts:316:52
    at Generator.next (<anonymous>)
    at /Users/peter/.config/yarn/global/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/peter/.config/yarn/global/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/peter/.config/yarn/global/node_modules/electron-builder-lib/out/packager.js:385:11)
    at /Users/peter/.config/yarn/global/node_modules/electron-builder-lib/src/packager.ts:278:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/Users/peter/.config/yarn/global/node_modules/electron-builder-lib/out/packager.js:341:11)
    at /Users/peter/.config/yarn/global/node_modules/electron-builder-lib/src/index.ts:50:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/peter/.config/yarn/global/node_modules/electron-builder-lib/out/index.js:47:21)
    at build (/Users/peter/.config/yarn/global/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/peter/.config/yarn/global/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/Users/peter/.config/yarn/global/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/Users/peter/.config/yarn/global/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/peter/.config/yarn/global/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/Users/peter/.config/yarn/global/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/peter/.config/yarn/global/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

If you could kindly help that would be a charm, thank you so much. Have a great one.

**Comment by dzt** [comment]
For anybody else having this issue I fixed it using this command.

```
sudo chown -R $(whoami) ~/
```
