### ISSUE TITLE
Error: Unable to find a valid app

### ISSUE THREAD

**Issue by aarnaud** [electron-userland/electron-builder#264]
## My `dist` directory:

````
dist/
├── electron.js
├── icon.icns
├── lxd-logo.png
├── package.json
└── www
    ├── assets
    │   ├── js
    │   │   └── term.js
    │   └── templates
    │       ├── app.component.html
    │       ├── container-detail.component.html
    │       └── containers.component.html
    ├── index.html
    ├── main.9fe52e361e8ef1a7762c.bundle.js
    ├── main.9fe52e361e8ef1a7762c.bundle.js.gz
    ├── polyfills.3459c5709858e9448dde.bundle.js
    ├── polyfills.3459c5709858e9448dde.bundle.js.gz
    ├── vendor.471a79fad63c15127dbb.bundle.js
    └── vendor.471a79fad63c15127dbb.bundle.js.gz
````

## The `package.json`:
````
{
  "name": "LXD-WebUI",
  "main": "electron.js",
  "description": "LXD web ui client",
  "author": {
    "name": "Anthony ARNAUD",
    "email": "lxd-webui@anthony-arnaud.fr"
  }
}
````

## With electron-packager (OK):
````
./node_modules/.bin/electron-packager dist/ --platform=linux --arch=x64
````
it's works, the result folder is:

````
LXD-WebUI-linux-x64/
├── content_shell.pak
├── icudtl.dat
├── libffmpeg.so
├── libnode.so
├── LICENSE
├── LICENSES.chromium.html
├── locales
│   ├── am.pak
│   ├── ar.pak
│   ├── bg.pak
│   ├── bn.pak
│   ├── ca.pak
│   ├── cs.pak
│   ├── da.pak
│   ├── de.pak
│   ├── el.pak
│   ├── en-GB.pak
│   ├── en-US.pak
│   ├── es-419.pak
│   ├── es.pak
│   ├── et.pak
│   ├── fake-bidi.pak
│   ├── fa.pak
│   ├── fil.pak
│   ├── fi.pak
│   ├── fr.pak
│   ├── gu.pak
│   ├── he.pak
│   ├── hi.pak
│   ├── hr.pak
│   ├── hu.pak
│   ├── id.pak
│   ├── it.pak
│   ├── ja.pak
│   ├── kn.pak
│   ├── ko.pak
│   ├── lt.pak
│   ├── lv.pak
│   ├── ml.pak
│   ├── mr.pak
│   ├── ms.pak
│   ├── nb.pak
│   ├── nl.pak
│   ├── pl.pak
│   ├── pt-BR.pak
│   ├── pt-PT.pak
│   ├── ro.pak
│   ├── ru.pak
│   ├── sk.pak
│   ├── sl.pak
│   ├── sr.pak
│   ├── sv.pak
│   ├── sw.pak
│   ├── ta.pak
│   ├── te.pak
│   ├── th.pak
│   ├── tr.pak
│   ├── uk.pak
│   ├── vi.pak
│   ├── zh-CN.pak
│   └── zh-TW.pak
├── LXD-WebUI
├── natives_blob.bin
├── resources
│   ├── app
│   │   ├── electron.js
│   │   ├── icon.icns
│   │   ├── lxd-logo.png
│   │   ├── package.json
│   │   └── www
│   │       ├── assets
│   │       │   ├── js
│   │       │   │   └── term.js
│   │       │   └── templates
│   │       │       ├── app.component.html
│   │       │       ├── container-detail.component.html
│   │       │       └── containers.component.html
│   │       ├── index.html
│   │       ├── main.9fe52e361e8ef1a7762c.bundle.js
│   │       ├── main.9fe52e361e8ef1a7762c.bundle.js.gz
│   │       ├── polyfills.3459c5709858e9448dde.bundle.js
│   │       ├── polyfills.3459c5709858e9448dde.bundle.js.gz
│   │       ├── vendor.471a79fad63c15127dbb.bundle.js
│   │       └── vendor.471a79fad63c15127dbb.bundle.js.gz
│   └── atom.asar
├── snapshot_blob.bin
└── version
````

## With electron-builder 3.0.0 and 2.11.0 (Failed)
````
./node_modules/.bin/build --appDir ./dist/ --arch x64
````

The build is success, but on start:

````
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/home/anthony/Devs/lxd-webui/dist/LXD-WebUI-linux-x64/resources/atom.asar/browser/init.js:111:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:151:18)
    at node.js:1007:3
````

The build result is:
````
LXD-WebUI-linux-x64/
├── content_shell.pak
├── icudtl.dat
├── libffmpeg.so
├── libnode.so
├── LICENSE
├── LICENSES.chromium.html
├── locales
│   ├── am.pak
│   ├── ar.pak
│   ├── bg.pak
│   ├── bn.pak
│   ├── ca.pak
│   ├── cs.pak
│   ├── da.pak
│   ├── de.pak
│   ├── el.pak
│   ├── en-GB.pak
│   ├── en-US.pak
│   ├── es-419.pak
│   ├── es.pak
│   ├── et.pak
│   ├── fake-bidi.pak
│   ├── fa.pak
│   ├── fil.pak
│   ├── fi.pak
│   ├── fr.pak
│   ├── gu.pak
│   ├── he.pak
│   ├── hi.pak
│   ├── hr.pak
│   ├── hu.pak
│   ├── id.pak
│   ├── it.pak
│   ├── ja.pak
│   ├── kn.pak
│   ├── ko.pak
│   ├── lt.pak
│   ├── lv.pak
│   ├── ml.pak
│   ├── mr.pak
│   ├── ms.pak
│   ├── nb.pak
│   ├── nl.pak
│   ├── pl.pak
│   ├── pt-BR.pak
│   ├── pt-PT.pak
│   ├── ro.pak
│   ├── ru.pak
│   ├── sk.pak
│   ├── sl.pak
│   ├── sr.pak
│   ├── sv.pak
│   ├── sw.pak
│   ├── ta.pak
│   ├── te.pak
│   ├── th.pak
│   ├── tr.pak
│   ├── uk.pak
│   ├── vi.pak
│   ├── zh-CN.pak
│   └── zh-TW.pak
├── LXD-WebUI
├── natives_blob.bin
├── resources
│   ├── app.asar
│   └── atom.asar
├── snapshot_blob.bin
└── version
````

## Conclusion

The resources haven't app directory, i don't known why.

My code is on github: https://github.com/aarnaud/lxd-webui

Thanks,

**Comment by develar** [comment]
`appDir` required if you use two-package.json structure and want to use custom dir instead of `app` (default value).

See https://github.com/electron-userland/electron-builder#in-short

Another problem —we use `dist` folder as output directory and currently no configuration option to change it.

**Comment by jbleuzen** [comment]
I had the same sort of error with electron-builder > 3.x.x.
Rollbacked to 2.11.0 and my app get build correctly... 

@aarnaud have you try adding the option "asar": false into your dev package.json in build item ?

**Comment by develar** [comment]
@jbleuzen Please create new issue and provide details.

**Comment by aarnaud** [comment]
Thanks, @develar 

My change for solve it : https://github.com/aarnaud/lxd-webui/commit/2b343d1f008855bc041c75f5fe3a33467251ec49

**Comment by develar** [comment]
@aarnaud Cool. Please note — your feedback is welcome and anything can be changed to make configuration simple and comfortable. Cool that you decided to follow convention instead of creating configuration hell.
