### ISSUE TITLE
spawn: Error ENOENT, but only in packed app

### ISSUE THREAD

**Issue by drcmda** [electron-userland/electron-builder#2651]
* **Version**: 5.6.0

* **Target**: mac x64

I am packing an .exe file in an electron app, which is spawned like so:

    let ccProcess = spawn("wine", [
        "/Users/drcmda/dev/triangles/packed/mac/triangles.app/Contents/Resources/app/node_modules/@awv/bin/instance.exe", 
        "-port:9491", 
        "-ccwss", 
        "-binary", 
        "-console", 
        "-debug", 
        "-id:82b81664-0fac-cf9b-ab56-e2bcc02e8913"
    ])

I have wine installed, and it works if i simply let electron run it, even calling the command from the commandline works. But within a packed .dmg the call throws:

    'Error: spawn wine ENOENT\n    at exports._errnoException (util.js:1024:11)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)\n    at onErrorNT (internal/child_process.js:374:16)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n    at Function.Module.runMain (module.js:607:11)\n    at startup (bootstrap_node.js:167:16)\n    at bootstrap_node.js:589:3'

I can't figure out why this happens or how electron could even affect spawning at all. Could anyone point me in the right direction - i've googled for a while and nothing seemed to help it.

**Comment by drcmda** [comment]
Finally found something that fixes it, and it's not related to electron: https://github.com/sindresorhus/fix-path
