### ISSUE TITLE
SyntaxError: Unexpected token ﻿ in JSON at position 0

### ISSUE THREAD

**Issue by zhanqunqin** [electron-userland/electron-builder#2660]
* **Version**: "electron-builder": "19.19.0",

* **Target**: windows 10

SyntaxError: Unexpected token ﻿ in JSON at position 0
SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at then.it (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\util\packageDependencies.ts:65:22)
    at tryCatcher (C:\Users\Administrator\Documents\ssc_tool\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Documents\ssc_tool\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Administrator\Documents\ssc_tool\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Documents\ssc_tool\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Administrator\Documents\ssc_tool\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\Administrator\Documents\ssc_tool\node_modules\bluebird\js\release\promise.js:638:18)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\bluebird\js\release\nodeback.js:42:21
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
From previous event:
    at readJson (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\util\packageDependencies.ts:65:6)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\util\packageDependencies.ts:145:59
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:171:5)
From previous event:
    at readChildPackage (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\out\util\packageDependencies.js:124:22)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\util\packageDependencies.ts:112:62
From previous event:
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\util\packageDependencies.ts:112:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at _readInstalled (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\out\util\packageDependencies.js:89:22)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\util\packageDependencies.ts:58:9
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
From previous event:
    at computeDependencies (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\out\util\packageDependencies.js:43:22)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\util\packageDependencies.ts:51:28
    at Generator.next (<anonymous>)
From previous event:
    at getProductionDependencies (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\out\util\packageDependencies.js:29:21)
    at Lazy (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\util\packageDependencies.ts:45:25)
    at Lazy.get value [as value] (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder-http\src\httpExecutor.ts:307:23)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\util\yarn.ts:120:81
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\out\util\yarn.js:96:22)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at installOrRebuild (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\out\util\yarn.js:34:21)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\packager.ts:322:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\out\packager.js:381:11)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\packager.ts:218:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\out\packager.js:317:11)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\packager.ts:175:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at Packager.build (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\out\packager.js:236:11)
    at C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\builder.ts:266:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\out\builder.js:69:21)
    at Object.args [as handler] (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\cli\cli.ts:46:4)
    at Object.self.runCommand (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\node_modules\yargs\yargs.js:1018:24)
    at Object.get [as argv] (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\node_modules\yargs\yargs.js:927:19)
    at Object.<anonymous> (C:\Users\Administrator\Documents\ssc_tool\node_modules\electron-builder\src\cli\cli.ts:41:15)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3
error An unexpected error occurred: "Command failed.
Exit code: 4294967295

**Comment by zhanqunqin** [comment]
electron-builder works fine in MacOS, but not in windows. I really have no idea what the problem it is...  and it took me over several days

**Comment by zhanqunqin** [comment]
And the same problem in the MacOS. is it a bug?

**Comment by zhanqunqin** [comment]
"build": {
    "productName": "gtool",
    "appId": "org.simulatedgreg.electron-vue",
    "directories": {
      "output": "build"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
    "mac": {
      "icon": "build/icons/icon.icns"
    },
    "win": {
      "icon": "build/icons/icon.ico"
    },
    "linux": {
      "icon": "build/icons"
    }
  },
  "jest": {
    "coverageDirectory": "coverage/",
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "transformIgnorePatterns": [
      "<rootDir>/node_modules/(?!@foo)"
    ],
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  },
  "dependencies": {
    "axios": "^0.17.1",
    "casperjs": "^1.1.4",
    "element-ui": "^2.0.11",
    "is": "^3.2.1",
    "koa": "^2.4.1",
    "koa-bodyparser": "^4.2.0",
    "koa-convert": "^1.2.0",
    "koa-json": "^2.0.2",
    "koa-logger": "^3.1.0",
    "koa-multer": "^1.0.2",
    "koa-onerror": "^4.0.0",
    "koa-router": "^7.3.0",
    "koa-session": "^5.8.1",
    "koa-static": "^4.0.2",
    "koa-views": "^6.1.3",
    "lodash": "^4.17.4",
    "log4js": "^2.5.2",
    "moment": "^2.20.1",
    "nedb-promise": "^2.0.1",
    "nodemailer": "^4.4.2",
    "queue": "^4.4.2",
    "rxjs": "^5.5.6",
    "underscore": "^1.8.3",
    "vue": "^2.5.13",
    "vue-electron": "^1.0.6",
    "vue-router": "3.0.1",
    "vuex": "3.0.1"
  },
  "devDependencies": {
    "@types/jest": "^22.1.0",
    "@types/node": "^9.3.0",
    "@types/webpack": "^3.8.3",
    "babili-webpack-plugin": "^0.1.2",
    "cfonts": "^1.1.3",
    "chalk": "^2.1.0",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^5.0.5",
    "css-loader": "^0.28.4",
    "del": "^3.0.0",
    "devtron": "^1.4.0",
    "electron": "^1.7.5",
    "electron-builder": "^19.19.1",
    "electron-debug": "^1.4.0",
    "electron-devtools-installer": "^2.2.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "html-webpack-plugin": "^2.30.1",
    "jest": "^22.1.4",
    "jsdoc": "^3.5.5",
    "jsdom": "^11.6.1",
    "jsdom-global": "^3.0.2",
    "multispinner": "^0.2.1",
    "node-loader": "^0.6.0",
    "randexp": "^0.4.6",
    "require-dir": "^0.3.0",
    "source-map-support": "^0.5.2",
    "spectron": "^3.7.1",
    "style-loader": "^0.18.2",
    "ts-es5-istanbul-coverage": "^1.0.1",
    "ts-jest": "^22.0.1",
    "ts-loader": "^3.3.1",
    "ts-node": "^4.1.0",
    "tsconfig-paths": "^3.1.1",
    "typescript": "^2.6.2",
    "url-loader": "^0.5.9",
    "vue-class-component": "^6.1.2",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^13.7.0",
    "vue-property-decorator": "^6.0.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.13",
    "webpack": "^3.5.2",
    "webpack-dev-server": "^2.7.1",
    "webpack-hot-middleware": "^2.18.2"
  }

**Comment by develar** [comment]
Please try latest 20.3.0

**Comment by nosferatu500** [comment]
Version 20.28.1
I get this error in random time for same builds.

For example: I build project with webpack & electron-updater. Build it 7 times. And I get this error 4 times. How I can solve it?

**Comment by jamjar919** [comment]
I fixed this error by updating my nodejs version fyi
