### ISSUE TITLE
Problem creating AppImage

### ISSUE THREAD

**Issue by CoDanny** [electron-userland/electron-builder#2664]
Version :20.2.1

Platform details: platform=linux arch=x64 electron=1.8.2

I get the following issue when trying to build an AppImage: 

```
output: /home/osboxes/.cache/electron-builder/appimage/appimage-9.1.0/linux-x64/mksquashfs: invalid option
```

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.

**Comment by CoDanny** [comment]
```

osboxes@osboxes:~/astroprint-repos/AstroPrint-App$ echo ${DEBUG}
electron-builder
osboxes@osboxes:~/astroprint-repos/AstroPrint-App$ sudo npm run package-app

> astroprint@0.1.13 package-app /home/osboxes/astroprint-repos/AstroPrint-App
> build

  • electron-builder version=20.2.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build/dist/electron-builder.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=1.8.2 appOutDir=build/dist/linux-unpacked
  • building        target=AppImage arch=x64 file=build/dist/astroprint-0.1.13-x86_64.AppImage
  ⨯ exit status 1
output: /home/osboxes/.cache/electron-builder/appimage/appimage-9.1.0/linux-x64/mksquashfs: invalid option

SYNTAX:/home/osboxes/.cache/electron-builder/appimage/appimage-9.1.0/linux-x64/mksquashfs source1 source2 ...  dest [options] [-e list of exclude
dirs/files]

Filesystem build options:
-comp <comp>		select <comp> compression
			Compressors available:
				gzip (default)
				xz
-b <block_size>		set data block to <block_size>.  Default 128 Kbytes
			Optionally a suffix of K or M can be given to specify
			Kbytes or Mbytes respectively
-no-exports		don't make the filesystem exportable via NFS
-no-sparse		don't detect sparse files
-no-xattrs		don't store extended attributes
-xattrs			store extended attributes (default)
-noI			do not compress inode table
-noD			do not compress data blocks
-noF			do not compress fragment blocks
-noX			do not compress extended attributes
-no-fragments		do not use fragments
-always-use-fragments	use fragment blocks for files larger than block size
-no-duplicates		do not perform duplicate checking
-all-root		make all files owned by root
-force-uid uid		set all file uids to uid
-force-gid gid		set all file gids to gid
-nopad			do not pad filesystem to a multiple of 4K
-keep-as-directory	if one source directory is specified, create a root
			directory containing that directory, rather than the
			contents of the directory

Filesystem filter options:
-p <pseudo-definition>	Add pseudo file definition
-pf <pseudo-file>	Add list of pseudo file definitions
			Pseudo definitions should be of the format
				filename d mode uid gid
				filename m mode uid gid
				filename b mode uid gid major minor
				filename c mode uid gid major minor
				filename f mode uid gid command
				filename s mode uid gid symlink
-sort <sort_file>	sort files according to priorities in <sort_file>.  One
			file or dir with priority per line.  Priority -32768 to
			32767, default priority 0
-ef <exclude_file>	list of exclude dirs/files.  One per line
-wildcards		Allow extended shell wildcards (globbing) to be used in
			exclude dirs/files
-regex			Allow POSIX regular expressions to be used in exclude
			dirs/files

Filesystem append options:
-noappend		do not append to existing filesystem
-root-becomes <name>	when appending source files/directories, make the
			original root become a subdirectory in the new root
			called <name>, rather than adding the new source items
			to the original root

Mksquashfs runtime options:
-version		print version, licence and copyright message
-exit-on-error		treat normally ignored errors as fatal
-recover <name>		recover filesystem data using recovery file <name>
-no-recovery		don't generate a recovery file
-quiet			no verbose output
-info			print files written to filesystem
-no-progress		don't display the progress bar
-progress		display progress bar when using the -info option
-processors <number>	Use <number> processors.  By default will use number of
			processors available
-mem <size>		Use <size> physical memory.  Currently set to 1971M
			Optionally a suffix of K, M or G can be given to specify
			Kbytes, Mbytes or Gbytes respectively

Miscellaneous options:
-root-owned		alternative name for -all-root
-o <offset>		Skip <offset> bytes at the beginning of the file.
			Default 0 bytes
-noInodeCompression	alternative name for -noI
-noDataCompression	alternative name for -noD
-noFragmentCompression	alternative name for -noF
-noXattrCompression	alternative name for -noX

-Xhelp			print compressor options for selected compressor

Compressors available and compressor specific options:
	gzip (default)
	  -Xcompression-level <compression-level>
		<compression-level> should be 1 .. 9 (default 9)
	  -Xwindow-size <window-size>
		<window-size> should be 8 .. 15 (default 15)
	  -Xstrategy strategy1,strategy2,...,strategyN
		Compress using strategy1,strategy2,...,strategyN in turn
		and choose the best compression.
		Available strategies: default, filtered, huffman_only,
		run_length_encoded and fixed
	xz
	  -Xbcj filter1,filter2,...,filterN
		Compress using filter1,filter2,...,filterN in turn
		(in addition to no filter), and choose the best compression.
		Available filters: x86, arm, armthumb, powerpc, sparc, ia64
	  -Xdict-size <dict-size>
		Use <dict-size> as the XZ dictionary size.  The dictionary size
		can be specified as a percentage of the block size, or as an
		absolute value.  The dictionary size must be less than or equal
		to the block size and 8192 bytes or larger.  It must also be
		storable in the xz header as either 2^n or as 2^n+2^(n+1).
		Example dict-sizes are 75%, 50%, 37.5%, 25%, or 32K, 16K, 8K
		etc.


Error: /home/osboxes/astroprint-repos/AstroPrint-App/node_modules/app-builder-bin-linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/builder-util/src/util.ts:252:14)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
From previous event:
    at /home/osboxes/astroprint-repos/AstroPrint-App/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/osboxes/astroprint-repos/AstroPrint-App/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at AppImageTarget.build (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:150:11)
    at taskManager.addTask.default.map.it (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/src/platformPackager.ts:122:67)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/src/platformPackager.ts:122:23)
    at /home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/src/platformPackager.ts:117:10
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at LinuxPackager.pack (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/out/platformPackager.js:189:11)
    at /home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/src/packager.ts:372:24
    at next (native)
    at xfs.stat (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/osboxes/astroprint-repos/AstroPrint-App/node_modules/graceful-fs/polyfills.js:287:18
From previous event:
    at Packager.doBuild (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/out/packager.js:441:11)
    at /home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/src/packager.ts:316:52
    at next (native)
    at /home/osboxes/astroprint-repos/AstroPrint-App/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/osboxes/astroprint-repos/AstroPrint-App/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager._build (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/out/packager.js:385:11)
    at /home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/src/packager.ts:278:23
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/out/packager.js:341:11)
    at /home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/src/index.ts:50:40
    at next (native)
From previous event:
    at build (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder-lib/out/index.js:47:21)
    at build (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/osboxes/astroprint-repos/AstroPrint-App/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3

npm ERR! Linux 4.4.0-116-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "package-app"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! astroprint@0.1.13 package-app: `build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the astroprint@0.1.13 package-app script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the astroprint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs astroprint
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls astroprint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/osboxes/astroprint-repos/AstroPrint-App/npm-debug.log
osboxes@osboxes:~/astroprint-repos/AstroPrint-App$ 
```

**Comment by CoDanny** [comment]
Also with 19.56.2 it works

**Comment by develar** [comment]
Strange, but your output doesn't contain debug information.

`DEBUG=electron-builder npm run package-app`

**Comment by CoDanny** [comment]
Ok, I updated the log output above

**Comment by CoDanny** [comment]
I have updated the log output above

**Comment by vladimiry** [comment]
I've run into the same issue, travis build output is [here](https://travis-ci.org/vladimiry/protonmail-desktop-app/jobs/349471954), downgrading 20.2.1 => 20.2.0 [helps](https://travis-ci.org/vladimiry/protonmail-desktop-app/jobs/349490718).
