### ISSUE TITLE
Go binary error proxyconnect tcp

### ISSUE THREAD

**Issue by gryzzly** [electron-userland/electron-builder#2665]
* **Version**: 20.2.1
* electron-updater: 2.20.1
* **Target**: nsis

We started getting the following go error after changing the way we supply configuration (from package.json to separate file) and updated to latest versions.
```
building block map blockMapFile=electron-releases/IDAGIO-0.0.35-snapshot-911107b.dmg.blockmap
downloading               path=/Users/misha/Library/Caches/electron-builder/nsis/nsis-resources-3.3.0 url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.3.0/nsis-resources-3.3.0.7z
  ⨯ Get https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.3.0/nsis-resources-3.3.0.7z: proxyconnect tcp: dial tcp :0: connect: can't assign requested address
github.com/develar/app-builder/pkg/download.follow.func2
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:135
github.com/develar/app-builder/pkg/download.follow
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:176
github.com/develar/app-builder/pkg/download.Download
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:61
github.com/develar/app-builder/pkg/download.DownloadArtifact
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/artifactDownloader.go:80
github.com/develar/app-builder/pkg/download.ConfigureArtifactCommand.func1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/artifactDownloader.go:25
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:59
runtime.main
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361
```

**Comment by develar** [comment]
Proxy defined in the `.npmrc` or env?

**Comment by gryzzly** [comment]
@develar thanks for prompt reply. No proxies defined anywhere, we don’t use any. 

```
┌ [16:11:22] ~/Source/idagio-web (staging-desktop-app *)
└ cat ~/.npmrc
proxy=false
```

**Comment by develar** [comment]
Please try to run with env `NO_PROXY=*`. Please provide `env | grep -i proxy`

**Comment by gryzzly** [comment]
@develar 

Unfortunately still the same result:

```
┌ [16:46:01] ~/Source/idagio-web (staging-desktop-app *)
└ NO_PROXY=* npm run electron:package:staging

> idagio-web@12.12.1 electron:package:staging /Users/misha/Source/idagio-web
> `npm bin`/electron-builder --mac --win --x64 --ia32 --publish never --config electron-builder-staging.json

  • electron-builder version=20.2.1
  • loaded configuration file=/Users/misha/Source/idagio-web/electron-builder-staging.json
  • writing effective config file=electron-releases/electron-builder.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=1.8.2 appOutDir=electron-releases/mac
  • signing         file=electron-releases/mac/IDAGIO.app identityName=Developer ID Application: idagio GmbH (KJWX8Z7M3H) identityHash=89C3FDA6930514C567EC8F38AC8BF3867E8B4843
(node:2745) Warning: a promise was created in a handler at Users/misha/Source/idagio-web/node_modules/electron-builder-lib/src/macPackager.ts:95:26 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.map (/Users/misha/Source/idagio-web/node_modules/bluebird/js/release/map.js:164:12)
  • building        target=macOS zip arch=x64 file=electron-releases/IDAGIO-0.0.35-snapshot-911107b-mac.zip
  • building        target=DMG arch=x64 file=electron-releases/IDAGIO-0.0.35-snapshot-911107b.dmg
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.8.2 appOutDir=electron-releases/win-unpacked
  • no native production dependencies
  • packaging       platform=win32 arch=ia32 electron=1.8.2 appOutDir=electron-releases/win-ia32-unpacked
  • building        target=nsis file=electron-releases/IDAGIO Setup 0.0.35-snapshot-911107b.exe archs=x64, ia32 oneClick=true
  • building block map blockMapFile=electron-releases/IDAGIO-0.0.35-snapshot-911107b.dmg.blockmap
  • downloading               path=/Users/misha/Library/Caches/electron-builder/nsis/nsis-resources-3.3.0 url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.3.0/nsis-resources-3.3.0.7z
  ⨯ Get https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.3.0/nsis-resources-3.3.0.7z: proxyconnect tcp: dial tcp :0: connect: can't assign requested address
github.com/develar/app-builder/pkg/download.follow.func2
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:135
github.com/develar/app-builder/pkg/download.follow
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:176
github.com/develar/app-builder/pkg/download.Download
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:61
github.com/develar/app-builder/pkg/download.DownloadArtifact
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/artifactDownloader.go:80
github.com/develar/app-builder/pkg/download.ConfigureArtifactCommand.func1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/artifactDownloader.go:25
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:59
runtime.main
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361
```

**Comment by gryzzly** [comment]
@develar <3 thanks
