### ISSUE TITLE
Fails on module canvas

### ISSUE THREAD

**Issue by pSatishC** [electron-userland/electron-builder#2678]
* **Version**: electron-builder@20.4.0, electron-updater@2.18.2

* **Target**: Windows ia32 on x64

Building with `electron@1.7.1` on `node v8.9.4` and `npm 5.6.0`
The build fails on `canvas@1.3.16` module as below
```
Running "exec:dist" (exec) task

> @ dist D:\Git\MyApp
> build --win --ia32 --publish always

  • electron-builder version=20.4.0
  • loaded configuration file=package.json ("build" field)
  • effective config config=
                       directories:
                         output: dist
                         buildResources: build
                       appId: com.myorg.myapp
                       asar: true
                       productName: MyApp
                       publish:
                         provider: generic
                         url: 'http://127.0.0.1:8080/MyApp/'
                       win:
                         target: nsis
                         icon: ./build/icon.ico
                         fileAssociations:
                           ext: bac
                           name: BAC File
                       nsis:
                         perMachine: 'true'
                       
  • two package.json structure is used devPackageFile=D:\Git\MyApp\package.json appPackageFile=D:\Git\MyApp\app\package.json
  • Unresolved dependencies after first round unresolved=contextify
  • rebuilding native production dependencies platform=win32 arch=ia32
  • spawning        command=D:\work\a\nodejs\node.exe D:\work\a\nodejs\node_modules\npm\bin\npm-cli.js rebuild canvas@1.3.16 cwd=D:\Git\MyApp\app
>> npm
>> WARN invalid config access=undefined
>> npm WARN invalid config also=undefined
>> npm
>> WARN invalid config https-proxy=undefined
>> npm WARN invalid config Must be a full url with 'http://'
>> npm
>> WARN invalid config init-author-url=undefined
>> npm WARN invalid config Must be a full url with 'http://'
>> npm WARN invalid config only=undefined
>> npm WARN
>> invalid config otp=undefined
>> npm WARN invalid config
>> Must be a numeric value
>> npm WARN invalid config proxy=undefined
>> npm
>> WARN invalid config Must be a full url with 'http://'
>> npm WARN
>> onload-script failed to require onload script undefined
>> npm WARN
>> onload-script Error: Cannot find module 'undefined'
>> npm WARN onload-script     at Function.Module._resolveFilename (module.js:538:15)
>> npm WARN onload-script
>> at Function.Module._load (module.js:468:25)
>> npm WARN onload-script     at Module.require (module.js:587:17)
>> npm
>> WARN onload-script     at require (internal/module.js:11:18)
>> npm WARN
>> onload-script     at cb (D:\work\a\nodejs\node_modules\npm\lib\npm.js:234:11)
>> npm WARN onload-script     at D:\work\a\nodejs\node_modules\npm\lib\npm.js:365:16
>> npm
>> WARN onload-script     at D:\work\a\nodejs\node_modules\npm\lib\config\core.js:81:7
>> npm
>> WARN onload-script     at Array.forEach (<anonymous>)
>> npm WARN onload-script
>> at D:\work\a\nodejs\node_modules\npm\lib\config\core.js:80:13
>> npm WARN onload-script     at f (D:\work\a\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
>> npm
>> WARN onload-script     at finalize (D:\work\a\nodejs\node_modules\npm\lib\config\core.js:198:5)
>> npm WARN
>> onload-script     at Conf.afterCARead (D:\work\a\nodejs\node_modules\npm\lib\config\load-cafile.js:13:40)
>> npm WARN onload-script
>> at ReadFileContext.callback (D:\work\a\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
>> npm WARN onload-script     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
>> npm
>> WARN onload-script  { Error: Cannot find module 'undefined'
>> npm WARN
>> onload-script     at Function.Module._resolveFilename (module.js:538:15)
>> npm WARN onload-script     at Function.Module._load (module.js:468:25)
>> npm
>> WARN onload-script     at Module.require (module.js:587:17)
>> npm WARN
>> onload-script     at require (internal/module.js:11:18)
>> npm WARN onload-script
>> at cb (D:\work\a\nodejs\node_modules\npm\lib\npm.js:234:11)
>> npm WARN onload-script     at D:\work\a\nodejs\node_modules\npm\lib\npm.js:365:16
>> npm WARN onload-script     at D:\work\a\nodejs\node_modules\npm\lib\config\core.js:81:7
>> npm
>> WARN onload-script     at Array.forEach (<anonymous>)
>> npm WARN
>> onload-script     at D:\work\a\nodejs\node_modules\npm\lib\config\core.js:80:13
>> npm WARN onload-script     at f (D:\work\a\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
>> npm WARN onload-script
>> at finalize (D:\work\a\nodejs\node_modules\npm\lib\config\core.js:198:5)
>> npm WARN onload-script     at Conf.afterCARead (D:\work\a\nodejs\node_modules\npm\lib\config\load-cafile.js:13:40)
>> npm WARN
>> onload-script     at ReadFileContext.callback (D:\work\a\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
>> npm WARN onload-script     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
>> npm WARN onload-script   stack: 'Error: Cannot find module \'undefined\'\n    at Function.Module._resolveFilename (module.js:538:15)\n    at Function.Module._load (module.js:468:25)\n    at Module.require (module.js:587:17)\n    at require (internal/module.js:11:18)\n    at cb (D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\npm.js:234:11)\n    at D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\npm.js:365:16\n    at D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\config\\core.js:81:7\n    at Array.forEach (<anonymous>)\n    at D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\config\\core.js:80:13\n    at f (D:\\udu\\a\\nodejs\\node_modules\\npm\\node_modules\\once\\once.js:25:25)\n    at finalize (D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\config\\core.js:198:5)\n    at Conf.afterCARead (D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\config\\load-cafile.js:13:40)\n    at ReadFileContext.callback (D:\\udu\\a\\nodejs\\node_modules\\npm\\node_modules\\graceful-fs\\graceful-fs.js:78:16)\n    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)',
>> npm
>> WARN onload-script   code: 'MODULE_NOT_FOUND' }

> canvas@1.3.16 install D:\Git\MyApp\app\node_modules\canvas
> node-gyp rebuild

>> npm ERR!
>> file undefined
>> npm ERR! path undefined
>> npm ERR! code ELIFECYCLE
>> npm ERR! errno ENOENT
>> npm
>> ERR! syscall spawn undefined
>> npm ERR! canvas@1.3.16 install: `node-gyp rebuild`
>> npm ERR! spawn undefined ENOENT
>> npm ERR! 
>> npm
>> ERR! Failed at the canvas@1.3.16 install script.
>> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>> 
>> npm ERR! A complete log of this run can be found in:
>> npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2018-03-09T10_14_07_883Z-debug.log
  • exited          command=node.exe code=1 pid=12416
>> Error: D:\work\a\nodejs\node.exe exited with code 1
>>     at ChildProcess.childProcess.once.code (D:\Git\MyApp\node_modules\builder-util\src\util.ts:252:14)
>>     at Object.onceWrapper (events.js:317:30)
>>     at emitTwo (events.js:126:13)
>>     at ChildProcess.emit (events.js:214:7)
>>     at maybeClose (internal/child_process.js:925:16)
>>     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
>> From previous event:
>>     at rebuild (D:\Git\MyApp\node_modules\electron-builder-lib\out\util\yarn.js:93:22)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
>>     at Generator.next (<anonymous>)
>>     at runCallback (timers.js:789:20)
>>     at tryOnImmediate (timers.js:751:5)
>>     at processImmediate [as _immediateCallback] (timers.js:722:5)
>> From previous event:
>>     at installOrRebuild (D:\Git\MyApp\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\packager.ts:446:7
>>     at Generator.next (<anonymous>)
>> From previous event:
>>     at Packager.installAppDependencies (D:\Git\MyApp\node_modules\electron-builder-lib\out\packager.js:502:11)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\packager.ts:360:20
>>     at Generator.next (<anonymous>)
>> From previous event:
>>     at Packager.doBuild (D:\Git\MyApp\node_modules\electron-builder-lib\out\packager.js:438:11)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\packager.ts:312:52
>> From previous event:
>>     at Packager._build (D:\Git\MyApp\node_modules\electron-builder-lib\out\packager.js:382:11)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\packager.ts:274:23
>>     at Generator.next (<anonymous>)
>>     at runCallback (timers.js:789:20)
>>     at tryOnImmediate (timers.js:751:5)
>>     at processImmediate [as _immediateCallback] (timers.js:722:5)
>> From previous event:
>>     at Packager.build (D:\Git\MyApp\node_modules\electron-builder-lib\out\packager.js:338:11)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\index.ts:50:40
>>     at Generator.next (<anonymous>)
>> From previous event:
>>     at build (D:\Git\MyApp\node_modules\electron-builder-lib\out\index.js:47:21)
>>     at build (D:\Git\MyApp\node_modules\electron-builder\src\builder.ts:229:10)
>>     at then (D:\Git\MyApp\node_modules\electron-builder\src\cli\cli.ts:48:33)
>>     at runCallback (timers.js:789:20)
>>     at tryOnImmediate (timers.js:751:5)
>>     at processImmediate [as _immediateCallback] (timers.js:722:5)
>> From previous event:
>>     at Object.args [as handler] (D:\Git\MyApp\node_modules\electron-builder\src\cli\cli.ts:48:33)
>>     at Object.runCommand (D:\Git\MyApp\node_modules\yargs\lib\command.js:235:44)
>>     at Object.parseArgs [as _parseArgs] (D:\Git\MyApp\node_modules\yargs\yargs.js:1042:24)
>>     at Object.get [as argv] (D:\Git\MyApp\node_modules\yargs\yargs.js:957:21)
>>     at Object.<anonymous> (D:\Git\MyApp\node_modules\electron-builder\src\cli\cli.ts:42:15)
>>     at Module._compile (module.js:643:30)
>>     at Object.Module._extensions..js (module.js:654:10)
>>     at Module.load (module.js:556:32)
>>     at tryModuleLoad (module.js:499:12)
>>     at Function.Module._load (module.js:491:3)
>>     at Function.Module.runMain (module.js:684:10)
>>     at startup (bootstrap_node.js:187:16)
>>     at bootstrap_node.js:608:3
>> npm
>> ERR! code ELIFECYCLE
>> npm ERR! errno
>> 1
>> npm
>> ERR! @ dist: `build --win --ia32 --publish always`
>> npm ERR!
>> Exit status 1
>> npm ERR!
>> npm
>> ERR! Failed at the @ dist script.
>> npm ERR!
>> This is probably not a problem with npm. There is likely additional logging output above.
>> 
>> npm ERR! A complete log of this run can be found in:
>> npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2018-03-09T10_14_07_945Z-debug.log
>> Exited with code: 1.
>> Error executing child process: Error: Command failed: npm run dist
>> npm WARN invalid config access=undefined
>> npm WARN invalid config also=undefined
>> npm WARN invalid config https-proxy=undefined
>> npm WARN invalid config Must be a full url with 'http://'
>> npm WARN invalid config init-author-url=undefined
>> npm WARN invalid config Must be a full url with 'http://'
>> npm WARN invalid config only=undefined
>> npm WARN invalid config otp=undefined
>> npm WARN invalid config Must be a numeric value
>> npm WARN invalid config proxy=undefined
>> npm WARN invalid config Must be a full url with 'http://'
>> npm WARN onload-script failed to require onload script undefined
>> npm WARN onload-script Error: Cannot find module 'undefined'
>> npm WARN onload-script     at Function.Module._resolveFilename (module.js:538:15)
>> npm WARN onload-script     at Function.Module._load (module.js:468:25)
>> npm WARN onload-script     at Module.require (module.js:587:17)
>> npm WARN onload-script     at require (internal/module.js:11:18)
>> npm WARN onload-script     at cb (D:\work\a\nodejs\node_modules\npm\lib\npm.js:234:11)
>> npm WARN onload-script     at D:\work\a\nodejs\node_modules\npm\lib\npm.js:365:16
>> npm WARN onload-script     at D:\work\a\nodejs\node_modules\npm\lib\config\core.js:81:7
>> npm WARN onload-script     at Array.forEach (<anonymous>)
>> npm WARN onload-script     at D:\work\a\nodejs\node_modules\npm\lib\config\core.js:80:13
>> npm WARN onload-script     at f (D:\work\a\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
>> npm WARN onload-script     at finalize (D:\work\a\nodejs\node_modules\npm\lib\config\core.js:198:5)
>> npm WARN onload-script     at Conf.afterCARead (D:\work\a\nodejs\node_modules\npm\lib\config\load-cafile.js:13:40)
>> npm WARN onload-script     at ReadFileContext.callback (D:\work\a\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
>> npm WARN onload-script     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
>> npm WARN onload-script  { Error: Cannot find module 'undefined'
>> npm WARN onload-script     at Function.Module._resolveFilename (module.js:538:15)
>> npm WARN onload-script     at Function.Module._load (module.js:468:25)
>> npm WARN onload-script     at Module.require (module.js:587:17)
>> npm WARN onload-script     at require (internal/module.js:11:18)
>> npm WARN onload-script     at cb (D:\work\a\nodejs\node_modules\npm\lib\npm.js:234:11)
>> npm WARN onload-script     at D:\work\a\nodejs\node_modules\npm\lib\npm.js:365:16
>> npm WARN onload-script     at D:\work\a\nodejs\node_modules\npm\lib\config\core.js:81:7
>> npm WARN onload-script     at Array.forEach (<anonymous>)
>> npm WARN onload-script     at D:\work\a\nodejs\node_modules\npm\lib\config\core.js:80:13
>> npm WARN onload-script     at f (D:\work\a\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
>> npm WARN onload-script     at finalize (D:\work\a\nodejs\node_modules\npm\lib\config\core.js:198:5)
>> npm WARN onload-script     at Conf.afterCARead (D:\work\a\nodejs\node_modules\npm\lib\config\load-cafile.js:13:40)
>> npm WARN onload-script     at ReadFileContext.callback (D:\work\a\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
>> npm WARN onload-script     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
>> npm WARN onload-script   stack: 'Error: Cannot find module \'undefined\'\n    at Function.Module._resolveFilename (module.js:538:15)\n    at Function.Module._load (module.js:468:25)\n    at Module.require (module.js:587:17)\n    at require (internal/module.js:11:18)\n    at cb (D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\npm.js:234:11)\n    at D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\npm.js:365:16\n    at D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\config\\core.js:81:7\n    at Array.forEach (<anonymous>)\n    at D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\config\\core.js:80:13\n    at f (D:\\udu\\a\\nodejs\\node_modules\\npm\\node_modules\\once\\once.js:25:25)\n    at finalize (D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\config\\core.js:198:5)\n    at Conf.afterCARead (D:\\udu\\a\\nodejs\\node_modules\\npm\\lib\\config\\load-cafile.js:13:40)\n    at ReadFileContext.callback (D:\\udu\\a\\nodejs\\node_modules\\npm\\node_modules\\graceful-fs\\graceful-fs.js:78:16)\n    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)',
>> npm WARN onload-script   code: 'MODULE_NOT_FOUND' }
>> npm ERR! file undefined
>> npm ERR! path undefined
>> npm ERR! code ELIFECYCLE
>> npm ERR! errno ENOENT
>> npm ERR! syscall spawn undefined
>> npm ERR! canvas@1.3.16 install: `node-gyp rebuild`
>> npm ERR! spawn undefined ENOENT
>> npm ERR! 
>> npm ERR! Failed at the canvas@1.3.16 install script.
>> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>> 
>> npm ERR! A complete log of this run can be found in:
>> npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2018-03-09T10_14_07_883Z-debug.log
>> Error: D:\work\a\nodejs\node.exe exited with code 1
>>     at ChildProcess.childProcess.once.code (D:\Git\MyApp\node_modules\builder-util\src\util.ts:252:14)
>>     at Object.onceWrapper (events.js:317:30)
>>     at emitTwo (events.js:126:13)
>>     at ChildProcess.emit (events.js:214:7)
>>     at maybeClose (internal/child_process.js:925:16)
>>     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
>> From previous event:
>>     at rebuild (D:\Git\MyApp\node_modules\electron-builder-lib\out\util\yarn.js:93:22)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
>>     at Generator.next (<anonymous>)
>>     at runCallback (timers.js:789:20)
>>     at tryOnImmediate (timers.js:751:5)
>>     at processImmediate [as _immediateCallback] (timers.js:722:5)
>> From previous event:
>>     at installOrRebuild (D:\Git\MyApp\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\packager.ts:446:7
>>     at Generator.next (<anonymous>)
>> From previous event:
>>     at Packager.installAppDependencies (D:\Git\MyApp\node_modules\electron-builder-lib\out\packager.js:502:11)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\packager.ts:360:20
>>     at Generator.next (<anonymous>)
>> From previous event:
>>     at Packager.doBuild (D:\Git\MyApp\node_modules\electron-builder-lib\out\packager.js:438:11)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\packager.ts:312:52
>> From previous event:
>>     at Packager._build (D:\Git\MyApp\node_modules\electron-builder-lib\out\packager.js:382:11)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\packager.ts:274:23
>>     at Generator.next (<anonymous>)
>>     at runCallback (timers.js:789:20)
>>     at tryOnImmediate (timers.js:751:5)
>>     at processImmediate [as _immediateCallback] (timers.js:722:5)
>> From previous event:
>>     at Packager.build (D:\Git\MyApp\node_modules\electron-builder-lib\out\packager.js:338:11)
>>     at D:\Git\MyApp\node_modules\electron-builder-lib\src\index.ts:50:40
>>     at Generator.next (<anonymous>)
>> From previous event:
>>     at build (D:\Git\MyApp\node_modules\electron-builder-lib\out\index.js:47:21)
>>     at build (D:\Git\MyApp\node_modules\electron-builder\src\builder.ts:229:10)
>>     at then (D:\Git\MyApp\node_modules\electron-builder\src\cli\cli.ts:48:33)
>>     at runCallback (timers.js:789:20)
>>     at tryOnImmediate (timers.js:751:5)
>>     at processImmediate [as _immediateCallback] (timers.js:722:5)
>> From previous event:
>>     at Object.args [as handler] (D:\Git\MyApp\node_modules\electron-builder\src\cli\cli.ts:48:33)
>>     at Object.runCommand (D:\Git\MyApp\node_modules\yargs\lib\command.js:235:44)
>>     at Object.parseArgs [as _parseArgs] (D:\Git\MyApp\node_modules\yargs\yargs.js:1042:24)
>>     at Object.get [as argv] (D:\Git\MyApp\node_modules\yargs\yargs.js:957:21)
>>     at Object.<anonymous> (D:\Git\MyApp\node_modules\electron-builder\src\cli\cli.ts:42:15)
>>     at Module._compile (module.js:643:30)
>>     at Object.Module._extensions..js (module.js:654:10)
>>     at Module.load (module.js:556:32)
>>     at tryModuleLoad (module.js:499:12)
>>     at Function.Module._load (module.js:491:3)
>>     at Function.Module.runMain (module.js:684:10)
>>     at startup (bootstrap_node.js:187:16)
>>     at bootstrap_node.js:608:3
>> npm ERR! code ELIFECYCLE
>> npm ERR! errno 1
>> npm ERR! @ dist: `build --win --ia32 --publish always`
>> npm ERR! Exit status 1
>> npm ERR! 
>> npm ERR! Failed at the @ dist script.
>> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>> 
>> npm ERR! A complete log of this run can be found in:
>> npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2018-03-09T10_14_07_945Z-debug.log
Warning: Task "exec:dist" failed. Use --force to continue.

Aborted due to warnings.
```
However if I cd into the canvas dir and run `node-gyp rebuild`, it succeeds
```
D:\Git\MyApp\app\node_modules\canvas>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | win32 | x64
gyp info spawn C:\Users\user1\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'D:\\work\\g\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Git\\MyApp\\app\\node_modules\\canvas\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\work\\g\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user1\\.node-gyp\\8.9.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\user1\\.node-gyp\\8.9.4',
gyp info spawn args   '-Dnode_gyp_dir=D:\\work\\g\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\user1\\.node-gyp\\8.9.4\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Git\\MyApp\\app\\node_modules\\canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Git\\MyApp\\app\\node_modules\\canvas\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
  win_delay_load_hook.cc
..\src\Image.cc(375): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\Git\MyApp\app\node_modules\canvas\build\canvas.vcxproj]
  D:\Git\MyApp\app\node_modules\nan\nan.h(1568): note: see declaration of 'Nan::
  Callback::Call'
..\src\Image.cc(388): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\Git\MyApp\app\node_modules\canvas\build\canvas.vcxproj]
  D:\Git\MyApp\app\node_modules\nan\nan.h(1568): note: see declaration of 'Nan::
  Callback::Call'
..\src\Canvas.cc(144): warning C4457: declaration of 'data' hides function parameter [D:\Git\MyApp\app\node_modules\canvas\build\canvas.vcxproj]
  ..\src\Canvas.cc(140): note: see declaration of 'data'
..\src\Canvas.cc(211): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\Git\MyApp\app\node_modules\canvas\build\canvas.vcxproj]
  D:\Git\MyApp\app\node_modules\nan\nan.h(1568): note: see declaration of 'Nan::
  Callback::Call'
..\src\Canvas.cc(216): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\Git\MyApp\app\node_modules\canvas\build\canvas.vcxproj]
  D:\Git\MyApp\app\node_modules\nan\nan.h(1568): note: see declaration of 'Nan::
  Callback::Call'
..\src\CanvasRenderingContext2d.cc(790): warning C4996: 'v8::Function::NewInstance': was declared de precated [D:\Git\MyApp\app\node_modules\canvas\build\canvas.vcxproj]
  C:\Users\user1\.node-gyp\8.9.4\include\node\v8.h(3832): note: see declaration of 'v8::Function:
  :NewInstance'
     Creating library D:\Git\MyApp\app\node_modules\canvas\build\Release\canvas.
  lib and object D:\Git\MyApp\app\node_modules\canvas\build\Release\canvas.exp
  Generating code
  Finished generating code
  canvas.vcxproj -> D:\Git\MyApp\app\node_modules\canvas\build\Release\\canvas.n
  ode
  canvas.vcxproj -> D:\Git\MyApp\app\node_modules\canvas\build\Release\canvas.pd
  b (Full PDB)
  Copying C:/GTK/bin/libcairo-2.dll to D:\Git\MyApp\app\node_modules\canvas\buil
  d\Release\\libcairo-2.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libfontconfig-1.dll to D:\Git\MyApp\app\node_modules\canvas
  \build\Release\\libfontconfig-1.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libexpat-1.dll to D:\Git\MyApp\app\node_modules\canvas\buil
  d\Release\\libexpat-1.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libfreetype-6.dll to D:\Git\MyApp\app\node_modules\canvas\b
  uild\Release\\libfreetype-6.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libpng14-14.dll to D:\Git\MyApp\app\node_modules\canvas\bui
  ld\Release\\libpng14-14.dll
          1 file(s) copied.
  Copying C:/GTK/bin/zlib1.dll to D:\Git\MyApp\app\node_modules\canvas\build\Rel
  ease\\zlib1.dll
          1 file(s) copied.
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  canvas-postbuild.vcxproj -> D:\Git\MyApp\app\node_modules\canvas\build\Release
  \\canvas-postbuild.node
  canvas-postbuild.vcxproj -> D:\Git\MyApp\app\node_modules\canvas\build\Release
  \canvas-postbuild.pdb (Full PDB)
gyp info ok
```

Any ideas why the canvas's install script fails when electron-builder runs it?

**Comment by pSatishC** [comment]
It appears that the absence of some libraries in PATH caused this. ConEmu shell did not give out any useful info except what is shown above. However running this in cmd showed that msbuild was failing due to a corrupt `iojs` library. 
Deleting `.electron-gyp` from `%USERPROFILE%` resolved the corrupt iojs lib issue but spit out multiple linker errors as shown below
```
Canvas.obj : error LNK2001: unresolved external symbol _png_destroy_write_struct [D:\Git\MyApp\app\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol _png_set_bKGD [D:\Git\MyApp\app\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol _png_set_write_user_transform_fn [D:\Git\MyApp\app\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp__cairo_surface_destroy [D:\Git\MyApp\app\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol _png_set_longjmp_fn...
(truncated)
```
Someone suggested missing libraries and adding `C:\GTK\bin` to `%PATH%` resolved them and finally the build got through. Closing this issue as this concerns configuration.

**Comment by antonymarion** [comment]
For those using last e- version: https://github.com/antonymarion/canvas-prebuilt/releases

you will find canvas-v2.5.0-electron-v4.2-win32-unknown-x64.tar.gz
