### ISSUE TITLE
Debian package (.deb) build failure

### ISSUE THREAD

**Issue by niklauslee** [electron-userland/electron-builder#2707]
I'm try to build .deb package in Ubuntu 16.04 (64 bit). But it fails as follow:

```
> build

  • electron-builder version=20.5.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=1.7.11 appOutDir=dist/linux-unpacked
  • building        target=deb arch=x64 file=dist/StarUML_3.0.0-alpha.0_amd64.deb
Error: Exit code: 1. Command failed: /home/parallels/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir -t deb --architecture amd64 --name StarUML --force --after-install /tmp/temp-dir-2MCNUi/1-after-install --after-remove /tmp/temp-dir-2MCNUi/0-after-remove --description 
 A sophisticated software modeler --version 3.0.0-alpha.0 --package /home/parallels/git/staruml3/dist/StarUML_3.0.0-alpha.0_amd64.deb --maintainer niklauslee <support@staruml.io> --url https://staruml.io --vendor niklauslee <support@staruml.io> --deb-compression xz --depends gconf2 --depends gconf-service --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --depends libxss1 /home/parallels/git/staruml3/dist/linux-unpacked/=/opt/StarUML /home/parallels/git/staruml3/build/icons/16x16.png=/usr/share/icons/hicolor/16x16/apps/staruml.png /home/parallels/git/staruml3/build/icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/staruml.png /home/parallels/git/staruml3/build/icons/48x48.png=/usr/share/icons/hicolor/48x48/apps/staruml.png /home/parallels/git/staruml3/build/icons/128x128.png=/usr/share/icons/hicolor/128x128/apps/staruml.png /home/parallels/git/staruml3/build/icons/256x256.png=/usr/share/icons/hicolor/256x256/apps/staruml.png /home/parallels/git/staruml3/build/icons/512x512.png=/usr/share/icons/hicolor/512x512/apps/staruml.png /tmp/temp-dir-2MCNUi/2-StarUML.desktop=/usr/share/applications/staruml.desktop

{:timestamp=>"2018-03-17T18:09:33.540192+0900", :message=>"Debian tools (dpkg/apt) don't do well with packages that use capital letters in the name. In some cases it will automatically downcase them, in others it will not. It is confusing. Best to not use any capital letters at all. I have downcased the package name for you just to be safe.", :oldname=>"StarUML", :fixedname=>"staruml", :level=>:warn}
{:timestamp=>"2018-03-17T18:09:33.546913+0900", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2018-03-17T18:09:34.025590+0900", :message=>"Process failed: tar failed (exit code 13). Full command was:[\"tar\", \"-C\", \"/tmp/package-dir-staging-158c51aa1854f961ca9ee1ac770cbb55b21bad205e7e8eb699ddd1785138\", \"-I'/home/parallels/git/staruml3/node_modules/app-builder-bin-linux/x64/app-builder'\", \"--numeric-owner\", \"--owner\", \"0\", \"--numeric-owner\", \"--group\", \"0\", \"-cf\", \"/tmp/package-deb-build-9b2f6290c946d5b1ed9d3dd2a3d452760bd8629529b9bf7d39719ddf4c1c/data.tar.xz\", \".\"]", :level=>:error}

    at /home/parallels/git/staruml3/node_modules/builder-util/src/util.ts:124:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at FpmTarget.build (/home/parallels/git/staruml3/node_modules/electron-builder-lib/out/targets/fpm.js:286:11)
    at default.each.it (/home/parallels/git/staruml3/node_modules/electron-builder-lib/src/platformPackager.ts:123:89)
From previous event:
    at taskManager.addTask.default.map.then (/home/parallels/git/staruml3/node_modules/electron-builder-lib/src/platformPackager.ts:123:37)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/parallels/git/staruml3/node_modules/electron-builder-lib/src/platformPackager.ts:123:10)
    at /home/parallels/git/staruml3/node_modules/electron-builder-lib/src/platformPackager.ts:117:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at LinuxPackager.pack (/home/parallels/git/staruml3/node_modules/electron-builder-lib/out/platformPackager.js:189:11)
    at /home/parallels/git/staruml3/node_modules/electron-builder-lib/src/packager.ts:368:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/parallels/git/staruml3/node_modules/electron-builder-lib/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/parallels/git/staruml3/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/parallels/git/staruml3/node_modules/electron-builder-lib/out/packager.js:438:11)
    at /home/parallels/git/staruml3/node_modules/electron-builder-lib/src/packager.ts:312:52
    at Generator.next (<anonymous>)
    at /home/parallels/git/staruml3/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/parallels/git/staruml3/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/parallels/git/staruml3/node_modules/electron-builder-lib/out/packager.js:382:11)
    at /home/parallels/git/staruml3/node_modules/electron-builder-lib/src/packager.ts:274:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (/home/parallels/git/staruml3/node_modules/electron-builder-lib/out/packager.js:338:11)
    at /home/parallels/git/staruml3/node_modules/electron-builder-lib/src/index.ts:50:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/parallels/git/staruml3/node_modules/electron-builder-lib/out/index.js:47:21)
    at build (/home/parallels/git/staruml3/node_modules/electron-builder/src/builder.ts:229:10)
    at then (/home/parallels/git/staruml3/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Object.args [as handler] (/home/parallels/git/staruml3/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/home/parallels/git/staruml3/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/parallels/git/staruml3/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/home/parallels/git/staruml3/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/parallels/git/staruml3/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

My configuration is:

```json
    "linux": {
      "target": [
        "AppImage",
        "deb"
      ],
      "category": "Development"
    },
```

AppImage was built successfully, but deb always failed.

Thank you in advance.

**Comment by appler1009** [comment]
I had the same issue but fixed it with installing `xz`. Please take a look at #309.

**Comment by niklauslee** [comment]
@appler1009 I've already installed `xz`

```sh
$ xz --version
xz (XZ Utils) 5.1.0alpha
liblzma 5.1.0alpha
```

**Comment by niklauslee** [comment]
Now .deb package build successfully. It's so strange, nothing changed. Anyway, this issue could be closed.

**Comment by mj-mehdizadeh** [comment]
i try to build .deb on windows 10 and got this error

this is my config
``` json
    "linux": {
      "target": [
        {
          "target": "deb",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ],
      "asar": true,
      "icon": "favicon.png"
    },
```
Error:
```
Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: connect ECONNREFUSED 51.38.69.239:443)
    at ClientHttp2Session.destroy (internal/http2/core.js:1219:20)
    at TLSSocket.socketOnError (internal/http2/core.js:2605:13)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at D:\Project\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:122:10
    at Generator.next (<anonymous>)
From previous event:
    at findBuildAgent (D:\Project\node_modules\electron-builder-lib\out\remoteBuilder\RemoteBuilder.js:69:21)
    at D:\Project\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:68:30
    at Generator.next (<anonymous>)
From previous event:
    at RemoteBuilder._build (D:\Project\node_modules\electron-builder-lib\out\remoteBuilder\RemoteBuilder.js:187:11)
    at default.mapSeries.arch (D:\Project\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:54:19)
From previous event:
    at RemoteBuilder.build (D:\Projects\iGap\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:53:28)
    at D:\Projects\iGap\node_modules\electron-builder-lib\src\linuxPackager.ts:106:30
From previous event:
    at RemoteTarget.finishBuild (D:\Projects\iGap\node_modules\electron-builder-lib\out\linuxPackager.js:148:11)
    at D:\Projects\iGap\node_modules\electron-builder-lib\src\packager.ts:372:36
From previous event:
    at Packager.doBuild (D:\Projects\iGap\node_modules\electron-builder-lib\out\packager.js:432:11)
    at D:\Projects\iGap\node_modules\electron-builder-lib\src\packager.ts:308:52
From previous event:
    at Packager._build (D:\Projects\iGap\node_modules\electron-builder-lib\out\packager.js:376:11)
    at D:\Projects\iGap\node_modules\electron-builder-lib\src\packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (D:\Projects\iGap\node_modules\electron-builder-lib\out\packager.js:332:11)
    at D:\Projects\iGap\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (D:\Projects\iGap\node_modules\electron-builder\out\builder.js:61:21)
    at build (D:\Projects\iGap\node_modules\electron-builder\src\builder.ts:280:10)
    at then (D:\Projects\iGap\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Object.args [as handler] (D:\Projects\iGap\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (D:\Projects\iGap\node_modules\electron-builder\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (D:\Projects\iGap\node_modules\electron-builder\node_modules\yargs\yargs.js:1074:24)
    at Object.get [as argv] (D:\Projects\iGap\node_modules\electron-builder\node_modules\yargs\yargs.js:989:21)
    at Object.<anonymous> (D:\Projects\iGap\node_modules\electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

```
