### ISSUE TITLE
Codesigning fails due to unsealed contents in Squirrel.framework

### ISSUE THREAD

**Issue by Wolvan** [electron-userland/electron-builder#2731]
* **Version**: 20.6.2

* **Target**:  macOS DMG/ZIP

Attempting to build a signed DMG fails on MacOS 10.11.6 with the following error:
```
electron-builder
  • electron-builder version=20.6.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=1.8.4 appOutDir=dist/mac
  • Mac Developer is used to sign app — it is only for development and testing, not for production
  • signing         file=dist/mac/ITMSPTransporter Helfer.app identityName=Mac Developer: office@kdg-mediascope.at (M3872WM4M6) identityHash=7075FE053B95D28FC5101FE3B9ABE5E3CE5767E7
Error: Command failed: codesign --sign 7075FE053B95D28FC5101FE3B9ABE5E3CE5767E7 --force /Volumes/FlowRage1/Vorlagen/06 Tools/Skripts/ITMSPTransporterHelper/dist/mac/ITMSPTransporter Helfer.app/Contents/Frameworks/Squirrel.framework
/Volumes/FlowRage1/Vorlagen/06 Tools/Skripts/ITMSPTransporterHelper/dist/mac/ITMSPTransporter Helfer.app/Contents/Frameworks/Squirrel.framework: replacing existing signature
/Volumes/FlowRage1/Vorlagen/06 Tools/Skripts/ITMSPTransporterHelper/dist/mac/ITMSPTransporter Helfer.app/Contents/Frameworks/Squirrel.framework: unsealed contents present in the root directory of an embedded framework

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
From previous event:
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Object.args [as handler] (/usr/local/lib/node_modules/electron-builder/src/cli/cli.ts:48:50)
    at Object.runCommand (/usr/local/lib/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/electron-builder/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/usr/local/lib/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/out/cli/cli.js:148:373)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

**Comment by timsuchanek** [comment]
Having the exact same error when building in Circle! Used `19.55.3` before, there it was fine.

**Comment by Wolvan** [comment]
Turns out that the problem was that the project files were on another server that has been mounted. Building from my local drive signs without problems
