### ISSUE TITLE
Failed if using release: build at appveyor

### ISSUE THREAD

**Issue by idnesdotlink** [electron-userland/electron-builder#2735]
* **Version**:  20.6.2

* **Target**: x86

Hi, my build error in **appveyor** if i try to use yarn release

this is my package.json :
```
"release": "build",
"build": "node --max_old_space_size=2048 .electron-vue/build.js && electron-builder"
```

this is my log :
```
$ node --max_old_space_size=2048 ./node_modules/.bin/electron-builder
C:\projects\vuehis\node_modules\.bin\electron-builder:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\windows\\system32\\cmd.exe
Arguments: /d /s /c node --max_old_space_size=2048 ./node_modules/.bin/electron-builder

```
tell me if you need more info ...
or if it is my false

**Comment by mwroffo** [comment]
Also experiencing this problem:

```
λ yarn dist
yarn run v1.17.3
$ node node_modules\.bin\electron-builder
C:\Users\mroffo\zowe\pantabot\node_modules\.bin\electron-builder:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by laclance** [comment]
+1

**Comment by jaygraygray** [comment]
I'm experiencing the same problem. My Mac builds work fine, but when trying to run the same scripts on Windows, they bomb out.
