### ISSUE TITLE
Invalid content length: -1 when building Windows

### ISSUE THREAD

**Issue by mobitar** [electron-userland/electron-builder#2737]
Hello, I [recently upgraded](https://github.com/standardnotes/desktop/commit/271417dd0728c93d88ae51bc90eb1c7b41ba1a35) from electron-builder 19.55.2 -> 20.5.1, and I'm getting this issue when I run `electron-builder -w --x64 --ia32`:

```
  • electron-builder version=20.5.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=1.8.4 appOutDir=dist/win-unpacked
  • server doesn't support ranges
  ⨯ Invalid content length: -1
github.com/develar/app-builder/pkg/download.Download
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:67
github.com/develar/app-builder/pkg/download.ConfigureCommand.func1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:36
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:58
runtime.main
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361
github.com/develar/app-builder/pkg/download.ConfigureCommand.func1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:36
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:58
runtime.main
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361

Error: /Users/mo/Desktop/sn/desktop/node_modules/app-builder-bin-mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/mo/Desktop/sn/desktop/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (events.js:326:30)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
From previous event:
    at LOOP (fs.js:1772:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at downloadCertificate (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/out/codeSign.js:97:22)
    at Lazy.WinPackager.cscInfo.Lazy (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/winPackager.ts:50:5)
    at Lazy.get value [as value] (/Users/mo/Desktop/sn/desktop/node_modules/lazy-val/src/main.ts:18:23)
    at Lazy.<anonymous> (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/winPackager.ts:87:40)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (/Users/mo/Desktop/sn/desktop/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/publish/PublishManager.ts:202:69
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at getAppUpdatePublishConfiguration (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/out/publish/PublishManager.js:40:22)
    at /Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/publish/PublishManager.ts:87:35
    at Generator.next (<anonymous>)
From previous event:
    at PublishManager.packager.addAfterPackHandler (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/out/publish/PublishManager.js:355:29)
    at default.each.it (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/packager.ts:462:49)
From previous event:
    at Packager.afterPack (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/packager.ts:462:28)
    at /Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/platformPackager.ts:215:21
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at WinPackager.doPack (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/out/platformPackager.js:274:11)
    at /Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/platformPackager.ts:116:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/out/platformPackager.js:189:11)
    at /Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/packager.ts:368:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/mo/Desktop/sn/desktop/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/mo/Desktop/sn/desktop/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:167:5)
From previous event:
    at Packager.doBuild (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/out/packager.js:438:11)
    at /Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/packager.ts:312:52
    at Generator.next (<anonymous>)
    at /Users/mo/Desktop/sn/desktop/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/mo/Desktop/sn/desktop/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:149:15)
From previous event:
    at Packager._build (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/out/packager.js:382:11)
    at /Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/packager.ts:274:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/out/packager.js:338:11)
    at /Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/src/index.ts:50:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder-lib/out/index.js:47:21)
    at build (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder/src/builder.ts:229:10)
    at then (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.args [as handler] (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/Users/mo/Desktop/sn/desktop/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/mo/Desktop/sn/desktop/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/Users/mo/Desktop/sn/desktop/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/mo/Desktop/sn/desktop/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

I am able to build Mac and Linux successfully, just not Windows.

**Comment by mobitar** [comment]
Update: if I downgrade back to 19.55.2, it builds successfully. If I upgrade back to 20.5.1, building fails with the error above. I am performing the build on a Mac machine, for Windows.

**Comment by JsseL** [comment]
We had/have this same problem. Seemed to be related to code signing since skipping the signing got the build succeeding. Also serving the signing cert from local filesystem seemed to work, but serving the cert from external server seemed to reintroduce the problem.

**Comment by develar** [comment]
Please try 20.9.1

**Comment by Lange** [comment]
I believe the issue is that Dropbox now issues a 302 redirect when attempting to download a file from one of the generated "Share" links. The downloader in `electron-builder` is currently saving that 302 response, rather than following it and saving the resulting file.
