### ISSUE TITLE
Error: spawn fpm ENOENT

### ISSUE THREAD

**Issue by Luncher** [electron-userland/electron-builder#274]
Packaging app for platform linux x64 using electron v0.37.2
Error: spawn fpm ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
From previous event:
    at Object.exec (/data/LocalHolaStudio/release/node_modules/electron-builder/src/util.ts:68:10)
    at LinuxPackager.<anonymous> (/data/LocalHolaStudio/release/node_modules/electron-builder/src/linuxPackager.ts:175:15)
    at [object Generator].next (native)
From previous event:
    at tsAwaiter (/data/LocalHolaStudio/release/node_modules/electron-builder/src/awaiter.ts:10:51)
    at Object.build (/data/LocalHolaStudio/release/node_modules/electron-builder/src/builder.ts:30:55)
    at Object.<anonymous> (/data/LocalHolaStudio/release/node_modules/electron-builder/src/build-cli.ts:41:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

--- 

[luncher@localhost release]$ uname -a
Linux localhost.localdomain 3.17.4-301.fc21.x86_64 #1 SMP Thu Nov 27 19:09:10 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[luncher@localhost release]$

**Comment by develar** [comment]
See https://github.com/electron-userland/electron-builder/blob/master/docs/multi-platform-build.md#linux

**Comment by develar** [comment]
Hmm... yes, `fpm` is not documented for Linux. See https://github.com/jordansissel/fpm#system-packages

**Comment by thangngoc89** [comment]
For anyone who is looking for the above link. It was moved to wiki: https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build
