### ISSUE TITLE
The request timed out.

### ISSUE THREAD

**Issue by Matho** [electron-userland/electron-builder#2740]
* **Electron builder version**: 20.7.1
* **Electron updater version**: 2.21.3

* **Target**: MacOs High Sierra

Hi. I have problem with error 'The request timed out.' when i'm downloading new release in my electron app. I try to download 240MB file over 3Mbit/s wifi network, with low intesity signal (50%). I don't know if the issue is due to packet loss, or if there is some internal time, in which the download must succeed. The logged message is:

`The request timed out.","stack":"Error: The request timed out.\n    at MacUpdater.doDownloadUpdate (/Applications/Rocket Monkeys Recorder.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:44:12)\n    at <anonymous>","code":-1001,"domain":"NSURLErrorDomain","__stackCleaned__":true`

Thanks

**Comment by khalil1608** [comment]
I have the same problem with a good connection and with a good intesity signal
Any one ?

**Comment by develar** [comment]
electron-updater 3.4.0

**Comment by SupremeTechnopriest** [comment]
This bug is back in version `4.0.6`.  The logs are coming in really sloppy as well... Probably because things are happening in parallel.

```
    [                    ] 0% 0.0s | qmk-configurator-0.1.0-beta-x86_64.AppImage to GitHub  • building embedded block map file=dist/QMK Configurator-0.1.0-beta-mac.zip
    [                    ] 1% 272.0s | qmk-configurator-0.1.0-beta-x86_64.AppImage to GitHub  • uploading       file=qmk-configurator-0.1.0-beta-mac.zip provider=GitHub
    [                    ] 2% 246.1s | qmk-configurator-0.1.0-beta-x86_64.AppImage to GitHub  • rebuilding native dependency name=node-zopfli-es
    [                    ] 1% 2318.3s | qmk-configurator-0.1.0-beta-mac.zip to GitHub  • packaging       platform=win32 arch=x64 electron=3.0.13 appOutDir=dist/win-unpacked
    [=                   ] 3% 978.0s | qmk-configurator-0.1.0-beta-mac.zip to GitHub  • uploading       file=qmk-configurator-0.1.0-beta.zip provider=GitHub
    [=                   ] 3% 796.5s | qmk-configurator-0.1.0-beta-mac.zip to GitHub  • building        target=zip arch=x64 file=dist/QMK Configurator-0.1.0-beta-win.zip
  • building        target=nsis file=dist/QMK Configurator Setup 0.1.0-beta.exe archs=x64 oneClick=false perMachine=false
    [=                   ] 4% 658.7s | qmk-configurator-0.1.0-beta.zip to GitHub  • uploading       file=qmk-configurator-0.1.0-beta-win.zip provider=GitHub

    [                    ] 0% 0.0s | qmk-configurator-0.1.0-beta-win.zip to GitHub  • building block map blockMapFile=dist/QMK Configurator Setup 0.1.0-beta.exe.blockmap
    [====================] 100% 0.0s | qmk-configurator-0.1.0-beta-mac.zip to GitHubError: Cannot cleanup:
    [====================] 100% 0.0s | qmk-configurator-0.1.0-beta.zip to GitHub
Error #1 --------------------------------------------------------------------------------
Error: Request timed out=] 100% 0.0s | qmk-configurator-setup-0.1.0-beta.exe to GitHub
    at TLSSocket.socket.setTimeout (/Users/rl/Sites/libraries/qmk/node_modules/builder-util/node_modules/builder-util-runtime/src/httpExecutor.ts:285:18)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.Socket._onTimeout (net.js:453:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at GitHubPublisher.doUpload (/Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/gitHubPublisher.ts:163:160)
    at /Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/publisher.ts:86:16
    at Generator.next (<anonymous>)
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at GitHubPublisher.upload (/Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/publisher.ts:75:32)
    at PublishManager.scheduleUpload (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:152:40)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:179:14
From previous event:
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:155:83)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:110:39)
    at EventEmitter.emit (events.js:187:15)
    at Packager.dispatchArtifactCreated (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:276:23)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:280:10
    at Generator.next (<anonymous>)
From previous event:
    at Packager.callArtifactBuildCompleted (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:279:58)
    at /Users/rl/Sites/libraries/qmk/node_modules/dmg-builder/src/dmg.ts:71:25
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Users/rl/Sites/libraries/qmk/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at nonMasPromise.then.then (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/macPackager.ts:90:26)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/rl/Sites/libraries/qmk/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/rl/Sites/libraries/qmk/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/rl/Sites/libraries/qmk/node_modules/electron-builder/src/cli/cli.ts:46:19)

Error #2 --------------------------------------------------------------------------------
Error: Request timed out
    at TLSSocket.socket.setTimeout (/Users/rl/Sites/libraries/qmk/node_modules/builder-util/node_modules/builder-util-runtime/src/httpExecutor.ts:285:18)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.Socket._onTimeout (net.js:453:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at GitHubPublisher.doUpload (/Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/gitHubPublisher.ts:163:160)
    at /Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/publisher.ts:86:16
    at Generator.next (<anonymous>)
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at GitHubPublisher.upload (/Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/publisher.ts:75:32)
    at PublishManager.scheduleUpload (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:152:40)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:179:14
From previous event:
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:155:83)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:110:39)
    at EventEmitter.emit (events.js:187:15)
    at Packager.dispatchArtifactCreated (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:276:23)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:280:10
    at Generator.next (<anonymous>)
From previous event:
    at Packager.callArtifactBuildCompleted (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:279:58)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:83:25
From previous event:
    at AppImageTarget.build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:28:44)
    at Function.buildAsyncTargets (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at LinuxPackager.packageInDistributableFormat (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:114:10
From previous event:
    at LinuxPackager.pack (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.doBuild (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/rl/Sites/libraries/qmk/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/rl/Sites/libraries/qmk/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at TLSSocket.socket.setTimeout (/Users/rl/Sites/libraries/qmk/node_modules/builder-util/node_modules/builder-util-runtime/src/httpExecutor.ts:285:18)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.Socket._onTimeout (net.js:453:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at GitHubPublisher.doUpload (/Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/gitHubPublisher.ts:163:160)
    at /Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/publisher.ts:86:16
    at Generator.next (<anonymous>)
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
    at GitHubPublisher.upload (/Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/publisher.ts:75:32)
    at PublishManager.scheduleUpload (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:152:40)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:179:14
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:155:83)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:110:39)
    at EventEmitter.emit (events.js:187:15)
    at Packager.dispatchArtifactCreated (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:276:23)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:280:10
    at Generator.next (<anonymous>)
    at Packager.callArtifactBuildCompleted (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:279:58)
    at /Users/rl/Sites/libraries/qmk/node_modules/dmg-builder/src/dmg.ts:71:25
    at Generator.next (<anonymous>)
    at DmgTarget.build (/Users/rl/Sites/libraries/qmk/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at nonMasPromise.then.then (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/macPackager.ts:90:26)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
    at MacPackager.pack (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/rl/Sites/libraries/qmk/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
    at Packager.doBuild (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
    at Packager._build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at Packager.build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/rl/Sites/libraries/qmk/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/rl/Sites/libraries/qmk/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at TLSSocket.socket.setTimeout (/Users/rl/Sites/libraries/qmk/node_modules/builder-util/node_modules/builder-util-runtime/src/httpExecutor.ts:285:18)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.Socket._onTimeout (net.js:453:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at GitHubPublisher.doUpload (/Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/gitHubPublisher.ts:163:160)
    at /Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/publisher.ts:86:16
    at Generator.next (<anonymous>)
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
    at GitHubPublisher.upload (/Users/rl/Sites/libraries/qmk/node_modules/electron-publish/src/publisher.ts:75:32)
    at PublishManager.scheduleUpload (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:152:40)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:179:14
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:155:83)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:110:39)
    at EventEmitter.emit (events.js:187:15)
    at Packager.dispatchArtifactCreated (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:276:23)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:280:10
    at Generator.next (<anonymous>)
    at Packager.callArtifactBuildCompleted (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:279:58)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:83:25
    at AppImageTarget.build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:28:44)
    at Function.buildAsyncTargets (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at LinuxPackager.packageInDistributableFormat (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at LinuxPackager.pack (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at Packager.doBuild (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/rl/Sites/libraries/qmk/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
    at Packager._build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at Packager.build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/rl/Sites/libraries/qmk/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/rl/Sites/libraries/qmk/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at throwError (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/node_modules/builder-util/src/asyncTaskManager.ts:90:11)
    at checkErrors (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/node_modules/builder-util/src/asyncTaskManager.ts:53:9)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/node_modules/builder-util/src/asyncTaskManager.ts:67:7
From previous event:
    at AsyncTaskManager.awaitTasks (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/node_modules/builder-util/src/asyncTaskManager.ts:44:19)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:209:28
    at Generator.next (<anonymous>)
From previous event:
    at PublishManager.awaitTasks (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/publish/PublishManager.ts:208:19)
    at isErrorOccurred (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/index.ts:93:32)
    at /Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/node_modules/builder-util/src/promise.ts:25:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at _executeFinally (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/node_modules/builder-util/out/promise.js:63:26)
    at executeFinally (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/node_modules/builder-util/out/promise.js:41:26)
    at build (/Users/rl/Sites/libraries/qmk/node_modules/app-builder-lib/src/index.ts:86:10)
    at build (/Users/rl/Sites/libraries/qmk/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/rl/Sites/libraries/qmk/node_modules/electron-builder/src/cli/cli.ts:46:19)
error Command failed with exit code 1.
```

**Comment by fer-fullstackdev** [comment]
Hello, @Matho , @develar, @khalil1608 , @GuoXiaoyang 
Did you solve this issue? What is the solution? 
Thanks.

**Comment by caloloc2** [comment]
Hello, anybody had a solution for this error?

**Comment by wslp12** [comment]
same too 
~  autoupdate   ~
request time out

**Comment by wslp12** [comment]
@caloloc2 
I solved the problem. Not a good way Still looking for the answer

Modify file 
path - 'node_modules/builder-util-runtime/out/httpExecutor.js'

line 322
setTimeout () modify ms
