### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#2753]
> electron-builder : v20.8.0
electron-updater: v2.21.4
node: v6.9.4
OS - macOS High Sierra 

Build error - 
```sh
npm install

> testapp@1.9.0 postinstall /testapp
> electron-builder install-app-deps

/path/node_modules/electron-builder/out/cli/cli.js:184
async function rebuildAppNativeCode(args) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by develar** [comment]
Please try 20.8.1

**Comment by akashnimare** [comment]
Fixed. This works as expected now using `v20.8.1` 😄
