### ISSUE TITLE
Error: connect ECONNREFUSED 94.237.40.251:443 when trying to use remote build for Linux appImage

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-builder#2767]
* **Version**: 20.8.1

* **Target**: 1.8.4
```
  • packaging       platform=linux arch=x64 electron=1.8.4 appOutDir=release\linux-unpacked
Downloading tmp-10996-0-electron-v1.8.4-linux-x64.zip
[============================================>] 100.0% of 47.19 MB (6.09 MB/s)
  • scheduling remote build target=appImage arch=x64
(node:10996) ExperimentalWarning: The http2 module is an experimental API.
Error: connect ECONNREFUSED 94.237.40.251:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
From previous event:
    at C:\Projects\Recollectr\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:122:10
    at Generator.next (<anonymous>)
From previous event:
    at findBuildAgent (C:\Projects\Recollectr\node_modules\electron-builder-lib\out\remoteBuilder\RemoteBuilder.js:1                                                                     32:17)
    at C:\Projects\Recollectr\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:66:48
    at Generator.next (<anonymous>)
From previous event:
    at RemoteBuilder._build (C:\Projects\Recollectr\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilde                                                                     r.ts:104:5)
    at _bluebirdLst.default.mapSeries.arch (C:\Projects\Recollectr\node_modules\electron-builder-lib\out\remoteBuild                                                                     er\RemoteBuilder.js:172:19)
From previous event:
    at RemoteBuilder.build (C:\Projects\Recollectr\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder                                                                     .ts:49:6)
    at C:\Projects\Recollectr\node_modules\electron-builder-lib\src\linuxPackager.ts:104:30
From previous event:
    at RemoteTarget.finishBuild (C:\Projects\Recollectr\node_modules\electron-builder-lib\out\linuxPackager.js:207:7                                                                     )
    at C:\Projects\Recollectr\node_modules\electron-builder-lib\src\packager.ts:380:36
From previous event:
    at Packager.doBuild (C:\Projects\Recollectr\node_modules\electron-builder-lib\out\packager.js:605:7)
    at C:\Projects\Recollectr\node_modules\electron-builder-lib\src\packager.ts:316:52
From previous event:
    at Packager._build (C:\Projects\Recollectr\node_modules\electron-builder-lib\out\packager.js:532:7)
    at C:\Projects\Recollectr\node_modules\electron-builder-lib\src\packager.ts:289:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (C:\Projects\Recollectr\node_modules\electron-builder-lib\out\packager.js:491:7)
    at C:\Projects\Recollectr\node_modules\electron-builder-lib\src\index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Projects\Recollectr\node_modules\electron-builder-lib\out\index.js:220:17)
    at build (C:\Projects\Recollectr\node_modules\electron-builder\src\builder.ts:229:10)
    at then (C:\Projects\Recollectr\node_modules\electron-builder\src\cli\cli.ts:43:10)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\Projects\Recollectr\node_modules\electron-builder\src\cli\cli.ts:43:10)
    at Object.runCommand (C:\Projects\Recollectr\node_modules\electron-builder\node_modules\yargs\lib\command.js:235                                                                     :44)
    at Object.parseArgs [as _parseArgs] (C:\Projects\Recollectr\node_modules\electron-builder\node_modules\yargs\yar                                                                     gs.js:1042:24)
    at Object.get [as argv] (C:\Projects\Recollectr\node_modules\electron-builder\node_modules\yargs\yargs.js:957:21                                                                     )
    at Object.<anonymous> (C:\Projects\Recollectr\node_modules\electron-builder\src\cli\cli.ts:28:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
```

I've ruled out firewall issues on my side, so I'm not sure what else I can look at from my end.

**Comment by kiviev** [comment]
The same thing happened to me.

> • packaging       platform=win32 arch=x64 electron=1.8.3 appOutDir=D:\workspaces\web\electron_dist\...\win-unpacked
  • building        target=nsis file=D:\workspaces\web\electron_dist\...\ Setup 0.0.1.exe archs=x64 oneClick=true
Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: connect ECONNREFUSED 94.237.40.251:443)
    at ClientHttp2Session.destroy (internal/http2/core.js:1131:20)
    at TLSSocket.socketOnError (internal/http2/core.js:2452:13)

**Comment by Slapbox** [comment]
I wonder if the issue is HTTP2. On a working build log I have, HTTP2 was not mentioned.

**Comment by krzysdz** [comment]
Visiting https://94.237.40.251:443 and http://94.237.40.251:443 in browsers (Chrome, Edge, Firefox) also shows ERR_CONNECTION_REFUSED

**Comment by Slapbox** [comment]
@develar, do you know what the issue may be here? I feel bad that I'm letting down potential Linux users currently, and previously this remote build system has worked superbly. Thanks for any thoughts, I know you're very busy.

**Comment by OualidYousfi** [comment]
I also get this error. My command is yarn dist --linux ((short for yarn compile && electron-builder --linux)).

**Comment by develar** [comment]
Great, that service is really used :) Fixed.

**Comment by Slapbox** [comment]
@develar saves the day again! Many thanks!

**Comment by jonathontoon** [comment]
@develar thanks a lot!

**Comment by redplane** [comment]
I'm having this issue.

**Comment by develar** [comment]
@redplane https://github.com/electron-userland/electron-builder/issues/3030#issuecomment-401533109

**Comment by rightdroid** [comment]
Have the same issue.
