### ISSUE TITLE
`Yarn set-versions` gives error on windows

### ISSUE THREAD

**Issue by shaluyadav13** [electron-userland/electron-builder#2789]
on executing `Yarn set-versions` on windows I am getting an error. Below is the stack trace:
```
yarn run v1.5.1
$ node test/out/helpers/setVersions.js
Error: Exit code: ENOENT. spawn yarn ENOENT
    at C:\Users\syadav\Documents\projects\electron-builder\packages\builder-util\src\util.ts:124:16
    at exithandler (child_process.js:282:5)
    at ChildProcess.errorhandler (child_process.js:294:5)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at getLatestVersions (C:\Users\syadav\Documents\projects\electron-builder\test\src\helpers\setVersions.ts:34:26)
    at setPackageVersions (C:\Users\syadav\Documents\projects\electron-builder\test\src\helpers\setVersions.ts:54:26)
    at main (C:\Users\syadav\Documents\projects\electron-builder\test\src\helpers\setVersions.ts:28:11)
    at <anonymous>
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c node test/out/helpers/setVersions.js
Directory: C:\\Users\\syadav\\Documents\\projects\\electron-builder
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\syadav\\Documents\\projects\\electron-builder\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
But on Mac it works as expected without any error. 
Can Anyone help me with this?

**Comment by shaluyadav13** [comment]
The issue is resolved by replacing 
`exec( 'yarn', ["info", "--json", packageInfo.name, "dist-tags"])`
to
`exec(/^win/.test(process.platform) ? 'yarn.cmd' : 'yarn', ["info", "--json", packageInfo.name, "dist-tags"])`
