### ISSUE TITLE
electron-builder fails for sqlite3 (win 10 x64)

### ISSUE THREAD

**Issue by DonTomato** [electron-userland/electron-builder#2792]
* **Version**: 20.8.2

* **Target**: sqlite3 for electron

```
> install-app-deps

  • please use as subcommand: electron-builder install-app-deps
  • electron-builder version=20.8.2
  • rebuilding native production dependencies platform=win32 arch=x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Error output:
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.8-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@4.0.0 and electron@1.8.4 (electron-v1.8 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\npm-lifecycle\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\Bitbucket\\mvb\\mvb\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\Bitbucket\\mvb\\mvb\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd D:\Bitbucket\mvb\mvb\node_modules\sqlite3
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Bitbucket\mvb\mvb\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\Bitbucket\mvb\mvb\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64 --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Bitbucket\mvb\mvb\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Bitbucket\\mvb\\mvb\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Bitbucket\mvb\mvb\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Michael\AppData\Roaming\npm-cache\_logs\2018-04-13T16_22_22_360Z-debug.log

    at ChildProcess.childProcess.once.code (D:\Bitbucket\mvb\mvb\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
From previous event:
    at rebuild (D:\Bitbucket\mvb\mvb\node_modules\electron-builder-lib\out\util\yarn.js:233:18)
    at D:\Bitbucket\mvb\mvb\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at installOrRebuild (D:\Bitbucket\mvb\mvb\node_modules\electron-builder-lib\out\util\yarn.js:68:17)
    at D:\Bitbucket\mvb\mvb\node_modules\electron-builder\src\cli\install-app-deps.ts:57:5
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at installAppDeps (D:\Bitbucket\mvb\mvb\node_modules\electron-builder\out\cli\install-app-deps.js:174:17)
    at main (D:\Bitbucket\mvb\mvb\node_modules\electron-builder\src\cli\install-app-deps.ts:66:2)
    at Object.<anonymous> (D:\Bitbucket\mvb\mvb\node_modules\electron-builder\src\cli\install-app-deps.ts:72:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mvb@0.0.0 postinstall: `install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mvb@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Michael\AppData\Roaming\npm-cache\_logs\2018-04-13T16_22_22_440Z-debug.log
```

**Comment by tbonz** [comment]
@DonTomato for what it's worth I was having the same issue trying to run install-app-deps from my Cmder window.  Then, I tried executing directly from windows command prompt and it completed without error ¯\_(ツ)_/¯

**Comment by Wuzi** [comment]
I was having a similar problem and fixed by using `npm install --global --production windows-build-tools`.

**Comment by develar** [comment]
I am sorry, that electron-builder cannot help you here, but it is global problem for NodeJS and not related to not only electron-builder, but even to electron. 

Things are simple, — if author of module doesn't provide prebuilt node module, then it will be built on __your__ machine. So, you need to install build tools. The most simple way for Windows — https://www.npmjs.com/package/windows-build-tools

That's it. No magic here. The only problem is that Windows is not normal and usable OS, so, quite a lot of problems arise. Well, `windows-build-tools` addresses this problem as much as possible.

Don't want to fight against Windows? Well, you can use free build service https://www.appveyor.com/ as stated in the docs — https://www.electron.build/multi-platform-build  (see [Sample appveyor.yml to Build Electron App for Windows](https://www.electron.build/multi-platform-build#sample-appveyoryml-to-build-electron-app-for-windows))
