### ISSUE TITLE
Error in electron-updater "string is missing the terminator"

### ISSUE THREAD

**Issue by Syed-Umair** [electron-userland/electron-builder#2796]
* **Version**: 19.55.3 -builder , 2.20.1 -updater

* **Target**: windows 10, electron - v1.8.3

Error after Update Download : :

```Command failed: powershell.exe -NoProfile -NonInteractive -Command Get-AuthenticodeSignature 'C:\Users\ERICA'~1\AppData\Local\Temp\up-Az4XU0\Update-win-7.5.0.exe' | ConvertTo-Json -Compress
The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at verifySignature (C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\src\windowsExecutableCodeSignatureVerifier.ts:11:3)
    at C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:88:18
From previous event:
    at NsisUpdater.verifySignature (C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:148:11)
    at C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:43:54
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:118:33
    at C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:46:13
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at NsisUpdater.executeDownload (C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:98:11)
    at C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:37:16
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:125:11)
    at C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:340:25
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.downloadUpdate (C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:382:11)
    at C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:316:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:353:11)
    at C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:307:11)
    at NsisUpdater.checkForUpdates (C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:213:35)
    at Object.setApplicationModeAndCheckUpdates (C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\archive\background.js:1561:25)
    at Object.controlledCheckForUpdates (C:\Users\Erica's PC\AppData\Local\Programs\update\resources\app.asar\archive\background.js:1597:26)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'powershell.exe -NoProfile -NonInteractive -Command Get-AuthenticodeSignature \'C:\\Users\\ERICA\'~1\\AppData\\Local\\Temp\\up-Az4XU0\\Update-win-7.5.0.exe\' | ConvertTo-Json -Compress'

**Comment by Syed-Umair** [comment]
Please advise

**Comment by Syed-Umair** [comment]
Any update on this issue ?

**Comment by mastergberry** [comment]
I am having this same exact issue @develar and as a result some users cannot use the software properly at all.

After months I finally got logs from a user today about this.

**Comment by develar** [comment]
Please use latest electron-updater (2.23.3). Any internal error during verification doesn't prevent update now.

**Comment by develar** [comment]
@mastergberry I don't see anything wrong in our command. MS PS sucks, and has a lot of pitfalls (hi, it is MS, WTF...) Humans cannot write proper PS command. Since only "1/200 people" are affected, I will close issue until some God will not explain whats' wrong or MS will get rid of PS and will use bash.

As I said, electron-updater now conforms to fact that MS cannot implement any thing correctly and ignore any internal error during verification.
