### ISSUE TITLE
Plugin not found, cannot call StdUtils

### ISSUE THREAD

**Issue by fhoe49** [electron-userland/electron-builder#2797]
* **Version**: 
"electron": "1.8.4",
"electron-builder": "20.8.1",
"electron-updater": "^2.21.4",

* **Target**: 
"nsis":
	"oneClick": true,
	"perMachine": false,
	"allowElevation": true,
	"allowToChangeInstallationDirectory": false,
[...]			

Cannot build setup.exe from Application with current Version, makensis exit with error:

Plugin not found, cannot call StdUtils::TestParameter
Error in macro _StdUtils_TestParameter on macroline 2
Error in macro _isUpdated on macroline 1
Error in macro _If on macroline 9
Error in macro CHECK_APP_RUNNING on macroline 3
!include: error in script: "uninstaller.nsh" on line 10
Error in script "<stdin>" on line 151 -- aborting creation process
   exited          command=makensis.exe code=1 pid=1756
   async task error error=
                       Error: ...AppData\Local\electron-builder\cache\nsis\nsis-3.0.3.0\Bin\makensis.exe exited with code 1
                           at ChildProcess.childProcess.once.code (D:\java-ide\workspace\exec_app\build\Electron\www\node_modules\electron-builder-lib\node_modules\builder-util\out\util.js:542:14)
                           at Object.onceWrapper (events.js:318:30)
                           at emitTwo (events.js:125:13)
                           at ChildProcess.emit (events.js:213:7)
                           at maybeClose (internal/child_process.js:897:16)
                           at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
Error: ...\AppData\Local\electron-builder\cache\nsis\nsis-3.0.3.0\Bin\makensis.exe exited with code 1
    at ChildProcess.childProcess.once.code (D:\java-ide\workspace\exec_app\build\Electron\www\node_modules\electron-builder-lib\node_modules\builder-util\out\util.js:542:14)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)

Allready try to clean caches.

**Comment by fhoe49** [comment]
Dont use German umlauts in path for cache!
