### ISSUE TITLE
NSIS: build fails because winCodeSign-2.0.0 cannot be downloaded

### ISSUE THREAD

**Issue by clusterberries** [electron-userland/electron-builder#2814]
* **Version**: 20.8.1

* **Target**: nsis

Build fails due to error
`Get https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.0.0/winCodeSign-2.0.0.7z: x509: certificate signed by unknown authority`

There was no error with earlier versions of electron-builder (e.g. 20.5.1 works fine). Also I cannot reproduce it on other machines with similar environments. Please advice what is the cause of the issue. Thanks!

Full console output:
```
  â€¢ electron-builder version=20.8.1
  â€¢ artifacts will be published if draft release exists reason=CI detected
  â€¢ loaded configuration file=package.json ("build" field)
  â€¢ rebuilding native production dependencies platform=win32 arch=x64
  â€¢ packaging       platform=win32 arch=x64 electron=1.8.4 appOutDir=dist\win-unpacked
[34m  â€¢[0m downloading               [34mpath[0m=C:\Users\grmf4qf2\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-2.0.0 [34murl[0m=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.0.0/winCodeSign-2.0.0.7z
[31m  â¨¯[0m Get https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.0.0/winCodeSign-2.0.0.7z: x509: certificate signed by unknown authority
github.com/develar/app-builder/pkg/download.follow.func2
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:133
github.com/develar/app-builder/pkg/download.follow
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:174
github.com/develar/app-builder/pkg/download.Download
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:50
github.com/develar/app-builder/pkg/download.DownloadArtifact
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/artifactDownloader.go:100
github.com/develar/app-builder/pkg/download.ConfigureArtifactCommand.func1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/artifactDownloader.go:26
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:54
runtime.main
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361

Error: C:\...\electron\node_modules\app-builder-bin-win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (C:\...\electron\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at WinPackager.signAndEditResources (C:\...\electron\node_modules\electron-builder-lib\src\winPackager.ts:338:5)
    at C:\...\electron\node_modules\electron-builder-lib\src\winPackager.ts:344:11
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (C:\...\electron\node_modules\electron-builder-lib\src\winPackager.ts:345:5)
    at C:\...\electron\node_modules\electron-builder-lib\src\platformPackager.ts:211:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at WinPackager.doPack (C:\...\electron\node_modules\electron-builder-lib\out\platformPackager.js:374:7)
    at C:\...\electron\node_modules\electron-builder-lib\src\platformPackager.ts:116:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\...\electron\node_modules\electron-builder-lib\out\platformPackager.js:265:7)
    at C:\...\electron\node_modules\electron-builder-lib\src\packager.ts:372:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (C:\...\electron\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager.doBuild (C:\...\electron\node_modules\electron-builder-lib\out\packager.js:605:7)
    at C:\...\electron\node_modules\electron-builder-lib\src\packager.ts:316:52
From previous event:
    at Packager._build (C:\...\electron\node_modules\electron-builder-lib\out\packager.js:532:7)
    at C:\...\electron\node_modules\electron-builder-lib\src\packager.ts:289:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (C:\...\electron\node_modules\electron-builder-lib\out\packager.js:491:7)
    at C:\...\electron\node_modules\electron-builder-lib\src\index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\...\electron\node_modules\electron-builder-lib\out\index.js:220:17)
    at build (C:\...\electron\node_modules\electron-builder\src\builder.ts:229:10)
    at then (C:\...\electron\node_modules\electron-builder\src\cli\cli.ts:43:10)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Object.args [as handler] (C:\...\electron\node_modules\electron-builder\src\cli\cli.ts:43:10)
    at Object.runCommand (C:\...\electron\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\...\electron\node_modules\yargs\yargs.js:1042:24)
    at Object.get [as argv] (C:\...\electron\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\...\electron\node_modules\electron-builder\src\cli\cli.ts:28:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by clusterberries** [comment]
@iunfire I found out that I have issues with certificates on the machine. When I simply open github.com in the browser, it shows an error. That's why it doesn't seem to be an issue with electron-builder.
I'm going to close this issue if you don't have any additional information.

**Comment by opiepj** [comment]
I have this issue as well
