### ISSUE TITLE
electron-builder example for linux

### ISSUE THREAD

**Issue by DevidCIC** [electron-userland/electron-builder#2824]
I am trying to configure the electron-builder for Linux, but I get a error. For windows it is working.
This is my package.json:

```
{
  "name": "cic-nt",
  "productName": "CICone NT",
  "displayName": "CICone NT",
  "version": "0.25.3-develop-build.0",
  "description": "This is the base project for the CIC.Bas.Web project also called CIC One - New Technologies",
  "author": "C.I.C Software GmbH",
  "main": "main.electron.js",
  "copyright": "CICone NT © ${author} 2018",
  "build": {
    "appId": "electron-builder.%npm_package_name%",
    "directories": {
      "output": "../electron-build"
    },
    "win": {
      "asar": false,
      "icon": "../src/assets/icon/nt-white.ico",
      "publish": [
        {
          "provider": "generic",
          "url": "https://se-dnexec.cic-software.de/ElectronUpdate/${os}/${channel}"
        }
      ]
    },
    "linux": {
      "icon": "../src/assets/icon/nt-white.ico",
      "target": [
        "deb"
      ],
      "publish": [
        {
          "provider": "generic",
          "url": "https://se-dnexec.cic-software.de/ElectronUpdate/${os}/${channel}"
        }
      ]
    }
  },
  "dependencies": {
    "electron-updater": "^2.21.8"
  }
}
```

And this is how I run it:
```
    "package:electron:linux": "electron-builder --project=electron --linux deb --publish=always",
```

So what am I missing here ?

```
Error: Cannot cleanup:

Error #1 --------------------------------------------------------------------------------
Error: Please specify project homepage, see https://electron.build/configuration/configuration#Metadata-homepage

Please specify author 'email' in the application package.json

See https://docs.npmjs.com/files/package.json#people-fields-author-contributors

It is required to set Linux .deb package maintainer. Or you can set maintainer in the custom linux options.
(see https://www.electron.build/configuration/linux).
```

**Comment by develar** [comment]
Set `homepage` option (near `name`).

**Comment by DevidCIC** [comment]
Now I get the error:

```
Error: Cannot find module 'http2'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at _http (C:\Development\cic.nt\node_modules\electron-builder-lib\out\remoteBuilder\RemoteBuilder.js:29:16)
    at C:\Development\cic.nt\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:121:18
    at Generator.next (<anonymous>)
```

**Comment by develar** [comment]
If you build for Linux on Windows, you need nodejs 8.

**Comment by DevidCIC** [comment]
Thanks for the help. I already have Node v8.3.0. Is that not enough, do I need to install the version v8.11.1 ?

**Comment by develar** [comment]
Yes, you need latest because to build linux on windows https://github.com/electron-userland/electron-build-service is used (HTTP 2 is required).
