### ISSUE TITLE
electron-updater NOT WORK!! 

### ISSUE THREAD

**Issue by trueflywood** [electron-userland/electron-builder#2845]
* **Version**: 20.8.1

electron-updater@2.21.8

* **Target**:  windows x64 NSIS

code:

```
let auto_updater2 = require('electron-updater').autoUpdater;

```

electron-updater error:

```

polyfills.1bb34ef….bundle.js:1 Unhandled Promise rejection: Cannot read property 'isReady' of undefined ; Zone: <root> ; Task: null ; Value: TypeError: Cannot read property 'isReady' of undefined
    at AppUpdater.untilAppReady.resolve (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:162:18)
    at new e (file:///C:/Users/a.kompanec/AppData/Local/Programs/angular-electron/resources/app.asar/dist/polyfills.1bb34ef449a430001fb0.bundle.js:1:30334)
    at AppUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:161:12)
    at BaseUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:12:5)
    at NsisUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:16:5)
    at _load_autoUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\main.ts:21:20)
    at Object.get [as autoUpdater] (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\main.ts:35:28)
    at <anonymous>:1:48 TypeError: Cannot read property 'isReady' of undefined
    at AppUpdater.untilAppReady.resolve (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:162:18)
    at new e (file:///C:/Users/a.kompanec/AppData/Local/Programs/angular-electron/resources/app.asar/dist/polyfills.1bb34ef449a430001fb0.bundle.js:1:30334)
    at AppUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:161:12)
    at BaseUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:12:5)
    at NsisUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:16:5)
    at _load_autoUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\main.ts:21:20)
    at Object.get [as autoUpdater] (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\main.ts:35:28)
    at <anonymous>:1:48
console.(anonymous function) @ polyfills.1bb34ef….bundle.js:1
n.onUnhandledError @ polyfills.1bb34ef….bundle.js:1
f @ polyfills.1bb34ef….bundle.js:1
e @ polyfills.1bb34ef….bundle.js:1
n.microtaskDrainDone @ polyfills.1bb34ef….bundle.js:1
v @ polyfills.1bb34ef….bundle.js:1
C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electro…:240 Uncaught TypeError: Cannot read property 'getPath' of undefined
    at AppUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:171:67)
    at BaseUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:12:5)
    at NsisUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:16:5)
    at _load_autoUpdater (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\main.ts:21:20)
    at Object.get [as autoUpdater] (C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electron-updater\src\main.ts:35:28)
    at <anonymous>:1:48
AppUpdater @ C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electro…:240
BaseUpdater @ C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electro…:64
NsisUpdater @ C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electro…:116
_load_autoUpdater @ C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electro…:85
get @ C:\Users\a.kompanec\AppData\Local\Programs\angular-electron\resources\app.asar\node_modules\electro…:98
(anonymous) @ VM212:1

```

**Comment by gmantri** [comment]
Please see this: https://github.com/electron-userland/electron-builder/issues/1387.

**Comment by develar** [comment]
Duplicates  #1387
