### ISSUE TITLE
Version 20.13.0 incorrectly published?

### ISSUE THREAD

**Issue by nikku** [electron-userland/electron-builder#2863]
* **Version**: 20.13.0

* **Target**: Linux

In an attempt to try out https://github.com/electron-userland/electron-builder/issues/2860 I've run into trouble:

```
> npm install electron-builder@20.13.0
...
> npm run build
/project/boilerplate/node_modules/electron-builder/src/builder.ts:316                                                             
      choices: getArchCliNames().concat("all", undefined as any),
               ^
TypeError: (0 , _builderUtil(...).getArchCliNames) is not a function
    at Object.configureBuildCommand [as builder] (/project/boilerplate/node_modules/electron-builder/src/builder.ts:316:16)       
    at Object.runCommand (/project/boilerplate/node_modules/yargs/lib/command.js:183:35)                                          
    at Object.parseArgs [as _parseArgs] (/project/boilerplate/node_modules/yargs/yargs.js:1042:24)                                
    at Object.get [as argv] (/project/boilerplate/node_modules/yargs/yargs.js:957:21)                                             
    at Object.<anonymous> (/project/boilerplate/node_modules/electron-builder/src/cli/cli.ts:28:22)                               
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Is this related to the latest release? `v20.11.x` installs without issues.

**Comment by develar** [comment]
20.13.1 published.
