### ISSUE TITLE
Exit code: null while building windows target on the macOS

### ISSUE THREAD

**Issue by ToniaDemchuk** [electron-userland/electron-builder#2864]
* **Version**: 20.11.1

* **Target**: Windows
* **OS**: MacOS 10.12

I'm getting an error while trying to build `win` target on the macOS:

command: `electron-builder --win`

```
Error: Exit code: null. Command failed: /Users/rstad/electronCache/wine/wine-2.0.1-mac-10.12/bin/wine /Users/rstad/electronCache/winCodeSign/winCodeSign-2.0.0/rcedit-ia32.exe /Users/rstad/FeedbackApp/desktop/dist/win-unpacked/electron-quick-start.exe --set-version-string FileDescription electron-quick-start --set-version-string ProductName electron-quick-start --set-version-string LegalCopyright Copyright © 2018 akolkev --set-file-version 1.0.0 --set-product-version 1.0.0.0 --set-version-string InternalName electron-quick-start --set-version-string OriginalFilename  --set-version-string CompanyName akolkev
```

The full log:
```
  • electron-builder version=20.11.1
  • loaded configuration file=package.json ("build" field)
  • effective config config=
                       directories:
                         output: dist
                         buildResources: build
                       appId: tid.feedback.id
                       mac:
                         category: public.app-category.business
                       files:
                         - dist/**/*
                         - node_modules/**/*
                         - package.json
                       
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.0 appOutDir=dist/win-unpacked
  • executing       file=unzip args=-oqq -d /Users/rstad/FeedbackApp/desktop/dist/win-unpacked /Users/rstad/Library/Caches/electron/electron-v2.0.0-win32-x64.zip
  • executed        file=unzip
  • getPublishConfigsForUpdateInfo: no publishConfigs, detect using repository info
  • spawning        command=/Users/rstad/FeedbackApp/desktop/node_modules/app-builder-bin-mac/app-builder icon --format ico --root /Users/rstad/FeedbackApp/desktop/build --root /Users/rstad/FeedbackApp/desktop --out /Users/rstad/FeedbackApp/desktop/dist/.icon-ico --input icon.ico --input icon.png --input icons --input icon.icns
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/build/icon.ico
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/icon.ico
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/build/icon.ico.ico
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/icon.ico.ico
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/build/icon.png
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/icon.png
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/build/icon.png.ico
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/icon.png.ico
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/build/icons
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/icons
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/build/icons.ico
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/icons.ico
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/build/icon.icns
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/icon.icns
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/build/icon.icns.ico
  • path doesn't exist        path=/Users/rstad/FeedbackApp/desktop/icon.icns.ico
  • exited          command=app-builder code=0 pid=8722 out={"icons":null}
  • default Electron icon is used reason=application icon is not set
  • spawning        command=/Users/rstad/FeedbackApp/desktop/node_modules/app-builder-bin-mac/app-builder download-artifact --url https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.0.0/winCodeSign-2.0.0.7z --name winCodeSign-2.0.0 --sha512 QT51iAVlWZlKeip3FPc8FHG/HKhCdWR/Wg+cevhrKHQ1d/oHl49EqXgeztO//DrdyN1X+GCvglaHifXnWR5VXQ==
  • found existing            path=/Users/rstad/electronCache/winCodeSign/winCodeSign-2.0.0
  • exited          command=app-builder code=0 pid=8723 out=/Users/rstad/electronCache/winCodeSign/winCodeSign-2.0.0
  • macOS version   version=10.12.6
  • spawning        command=/Users/rstad/FeedbackApp/desktop/node_modules/app-builder-bin-mac/app-builder download-artifact --url https://github.com/electron-userland/electron-builder-binaries/releases/download/wine-2.0.1-mac-10.12/wine-2.0.1-mac-10.12.7z --name wine-2.0.1-mac-10.12 --sha512 IvKwDml/Ob0vKfYVxcu92wxUzHu8lTQSjjb8OlCTQ6bdNpVkqw17OM14TPpzGMIgSxfVIrQZhZdCwpkxLyG3mg==
  • found existing            path=/Users/rstad/electronCache/wine/wine-2.0.1-mac-10.12
  • exited          command=app-builder code=0 pid=8724 out=/Users/rstad/electronCache/wine/wine-2.0.1-mac-10.12
  • executing       file=/Users/rstad/electronCache/wine/wine-2.0.1-mac-10.12/bin/wine args=/Users/rstad/electronCache/winCodeSign/winCodeSign-2.0.0/rcedit-ia32.exe /Users/rstad/FeedbackApp/desktop/dist/win-unpacked/electron-quick-start.exe --set-version-string FileDescription electron-quick-start --set-version-string ProductName electron-quick-start --set-version-string LegalCopyright Copyright © 2018 akolkev --set-file-version 1.0.0 --set-product-version 1.0.0.0 --set-version-string InternalName electron-quick-start --set-version-string OriginalFilename  --set-version-string CompanyName akolkev env=
                      {
                        "WINEDEBUG": "-all,err+all",
                        "WINEDLLOVERRIDES": "winemenubuilder.exe=d",
                        "WINEPREFIX": "/Users/rstad/electronCache/wine/wine-2.0.1-mac-10.12/wine-home",
                        "DYLD_FALLBACK_LIBRARY_PATH": "/Users/rstad/electronCache/wine/wine-2.0.1-mac-10.12/lib"
                      }
Error: Exit code: null. Command failed: /Users/rstad/electronCache/wine/wine-2.0.1-mac-10.12/bin/wine /Users/rstad/electronCache/winCodeSign/winCodeSign-2.0.0/rcedit-ia32.exe /Users/rstad/FeedbackApp/desktop/dist/win-unpacked/electron-quick-start.exe --set-version-string FileDescription electron-quick-start --set-version-string ProductName electron-quick-start --set-version-string LegalCopyright Copyright © 2018 akolkev --set-file-version 1.0.0 --set-product-version 1.0.0.0 --set-version-string InternalName electron-quick-start --set-version-string OriginalFilename  --set-version-string CompanyName akolkev

    at /Users/rstad/FeedbackApp/desktop/node_modules/builder-util/src/util.ts:124:16
    at ChildProcess.exithandler (child_process.js:205:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
From previous event:
    at execWine (/Users/rstad/FeedbackApp/desktop/node_modules/builder-util/src/wine.ts:64:8)
    at /Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/out/winPackager.js:531:41
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at WinPackager.signAndEditResources (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/src/winPackager.ts:338:5)
    at /Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/src/winPackager.ts:344:11
    at next (native)
From previous event:
    at WinPackager.signApp (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/src/winPackager.ts:345:5)
    at /Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/src/platformPackager.ts:233:16
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at WinPackager.doPack (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/out/platformPackager.js:410:7)
    at /Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/src/platformPackager.ts:117:16
    at next (native)
From previous event:
    at WinPackager.pack (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/out/platformPackager.js:275:7)
    at /Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/src/packager.ts:373:24
    at next (native)
    at xfs.stat (/Users/rstad/FeedbackApp/desktop/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/rstad/FeedbackApp/desktop/node_modules/graceful-fs/polyfills.js:287:18
From previous event:
    at Packager.doBuild (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/out/packager.js:615:7)
    at /Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/src/packager.ts:317:52
    at next (native)
    at /Users/rstad/FeedbackApp/desktop/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/rstad/FeedbackApp/desktop/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager._build (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/out/packager.js:542:7)
    at /Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/src/packager.ts:290:23
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/out/packager.js:501:7)
    at /Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/src/index.ts:51:40
    at next (native)
From previous event:
    at build (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder/src/builder.ts:229:10)
    at then (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder/src/cli/cli.ts:43:10)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder/src/cli/cli.ts:43:10)
    at Object.runCommand (/Users/rstad/FeedbackApp/desktop/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/rstad/FeedbackApp/desktop/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/Users/rstad/FeedbackApp/desktop/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/rstad/FeedbackApp/desktop/node_modules/electron-builder/src/cli/cli.ts:28:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 dist: `npm run build && electron-builder --win`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rstad/.npm/_logs/2018-05-03T09_48_54_128Z-debug.log
```

**Comment by moudicat** [comment]
same problem..

**Comment by ghadaghada** [comment]
@ToniaDemchuk, have you found a solution ? Thank you

**Comment by moudicat** [comment]
@ghadaghada Update macOS to latest version, and remove `/Users/<your username>/electronCache`, it works for me.

**Comment by junebug12851** [comment]
I can't figure this out either, tried deleting cache, mac already up-to-date, will have to investigate other options and whatnot until this is fixed.
