### ISSUE TITLE
Failure to build proton-native hellworld example.

### ISSUE THREAD

**Issue by IceMimosa** [electron-userland/electron-builder#2899]
I created a helloworld example project by [create-proton-app](https://github.com/albe-rosado/create-proton-app) and got error when i run `npm run dist`. Can anyone help me？Thanks.

```shell
> npm run dist

> proton-app-test@0.0.1 dist /Users/icemimosa/Documents/github/AskMisa/proton-app-test
> electron-builder

  • electron-builder version=20.13.2
  • loaded configuration file=package.json ("build" field)
  • description is missed in the package.json appPackageFile=/Users/icemimosa/Documents/github/AskMisa/proton-app-test/package.json
  • author is missed in the package.json appPackageFile=/Users/icemimosa/Documents/github/AskMisa/proton-app-test/package.json
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 proton=8.3.0 appOutDir=dist/mac
TypeError: (0 , _fsExtraP(...).copyFile) is not a function
    at /Users/icemimosa/Documents/github/AskMisa/proton-app-test/node_modules/electron-builder-lib/src/ProtonFramework.ts:61:33
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at ProtonFramework.prepareMacosApplicationStageDirectory (/Users/icemimosa/Documents/github/AskMisa/proton-app-test/node_modules/electron-builder-lib/out/ProtonFramework.js:170:7)
    at /Users/icemimosa/Documents/github/AskMisa/proton-app-test/node_modules/electron-builder-lib/src/ProtonFramework.ts:90:11
    at Generator.next (<anonymous>)
    at deleteItem (/Users/icemimosa/Documents/github/AskMisa/proton-app-test/node_modules/fs-extra/lib/empty/index.js:20:25)
............
```

**Comment by develar** [comment]
Cool that we have first proton-native user here :)

What is your NodeJS version?

**Comment by develar** [comment]
Please upgrade to 8.11.1
