### ISSUE TITLE
The auto-updater seems broken on mac with github - response returns 400

### ISSUE THREAD

**Issue by Nederby** [electron-userland/electron-builder#2910]
* Electron-builder **20.11.0**: 

* electron-updater **2.20.1**:

* Target **MAC**: 

I can still reproduce the issue #2540 - so I am creating a new issue.

**The auto-updater works fine on Windows (nsis).** But on mac I start getting status 400: Bad Request in the log file. When i push out a new version. The Github repo is public.

My update script
```javascript 
import { autoUpdater } from "electron-updater"

autoUpdater.checkForUpdatesAndNotify() 

```

I can not see the response header from Github in the electron-logs.

Here is the log with the error.:

```
[2018-05-15 11:22:50.176] [info] Found version 2.0.12 (url: dixa-2.0.12-mac.zip, dixa-2.0.12.dmg)
[2018-05-15 11:22:50.177] [info] Downloading update from dixa-2.0.12-mac.zip, dixa-2.0.12.dmg
[2018-05-15 11:22:50.238] [info] / requested
[2018-05-15 11:22:50.248] [info] /app.zip requested
[2018-05-15 11:22:50.731] [warn] Error: Update download failed. The server sent an invalid response. Try again later.

[2018-05-15 11:22:50.731] [error] Error: Error: Update download failed. The server sent an invalid response. Try again later.
[2018-05-15 11:22:50.732] [error] Error: Error: Cannot download "https://api.github.com/repos/dixahq/dixa-desktop-app-release/releases/assets/7021122": Error: Cannot download "https://api.github.com/repos/dixahq/dixa-desktop-app-release/releases/assets/7021122", status 400: Bad Request
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:74:22
    at ClientRequest.downloadRequest.httpExecutor.doRequest.downloadResponse (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:101:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at URLRequest.ClientRequest.urlRequest.on (/Applications/Dixa.app/Contents/Resources/electron.asar/browser/api/net.js:209:12)
    at emitOne (events.js:115:13)
    at URLRequest.emit (events.js:210:7)
From previous event:
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:44:12
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:127:11)
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:25
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.downloadUpdate (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:382:11)
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:316:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at MacUpdater.checkForUpdates (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at MacUpdater.checkForUpdatesAndNotify (/Applications/Dixa.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:233:17)
    at new AutoUpdater (/Applications/Dixa.app/Contents/Resources/app.asar/app/webpack:/src/autoUpdate/AutoUpdate.js:26:17)
    at createWin (/Applications/Dixa.app/Contents/Resources/app.asar/app/webpack:/src/background.js:201:16)
    at App._electron.app.on (/Applications/Dixa.app/Contents/Resources/app.asar/app/webpack:/src/background.js:429:5)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
```

When doing a request to the same endpoint with `curl` it returns `200 OK`

`curl -v https://api.github.com/repos/dixahq/dixa-desktop-app-release/releases/assets/7021122`

```
*   Trying 192.30.253.117...
* TCP_NODELAY set
* Connected to api.github.com (192.30.253.117) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.com
*  start date: Jan 18 00:00:00 2017 GMT
*  expire date: Apr 17 12:00:00 2020 GMT
*  subjectAltName: host "api.github.com" matched cert's "*.github.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
> GET /repos/dixahq/dixa-desktop-app-release/releases/assets/7021122 HTTP/1.1
> Host: api.github.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: GitHub.com
< Date: Tue, 15 May 2018 09:29:36 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 1458
< Status: 200 OK
< X-RateLimit-Limit: 60
< X-RateLimit-Remaining: 50
< X-RateLimit-Reset: 1526377923
< Cache-Control: public, max-age=60, s-maxage=60
< Vary: Accept
< ETag: "f937f9a00facdeb3b05ce5b5b65ac96a"
< Last-Modified: Mon, 30 Apr 2018 10:36:14 GMT
< X-GitHub-Media-Type: github.v3; format=json
< Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
< Access-Control-Allow-Origin: *
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: deny
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< Content-Security-Policy: default-src 'none'
< X-Runtime-rack: 0.029736
< X-GitHub-Request-Id: D24B:419B:B76759:15FFF4E:5AFAA87F
<
{
  "url": "https://api.github.com/repos/dixahq/dixa-desktop-app-release/releases/assets/7021122",
  "id": 7021122,
  "name": "dixa-2.0.12-mac.zip",
  "label": "",
  "uploader": {
    "login": "Nederby",
    "id": 6588469,
    "avatar_url": "https://avatars2.githubusercontent.com/u/6588469?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Nederby",
    "html_url": "https://github.com/Nederby",
    "followers_url": "https://api.github.com/users/Nederby/followers",
    "following_url": "https://api.github.com/users/Nederby/following{/other_user}",
    "gists_url": "https://api.github.com/users/Nederby/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Nederby/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Nederby/subscriptions",
    "organizations_url": "https://api.github.com/users/Nederby/orgs",
    "repos_url": "https://api.github.com/users/Nederby/repos",
    "events_url": "https://api.github.com/users/Nederby/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Nederby/received_events",
    "type": "User",
    "site_admin": false
  },
  "content_type": "application/zip",
  "state": "uploaded",
  "size": 68573513,
  "download_count": 676,
  "created_at": "2018-04-30T10:35:25Z",
  "updated_at": "2018-04-30T10:36:14Z",
  "browser_download_url": "https://github.com/dixahq/dixa-desktop-app-release/releases/download/v2.0.12/dixa-2.0.12-mac.zip"
}
```

**Comment by ismet** [comment]
We are experiencing exactly the same error! 

@develar  any plans to fix this bug?

**Comment by develar** [comment]
Duplicates #2540

**Comment by develar** [comment]
In the future please do not file a new issue but ask to reopen old. If no answer after several pings, please ping via Slack direct message.
