### ISSUE TITLE
Electron Builder CLI fails but exit code is 0.

### ISSUE THREAD

**Issue by qtphan734** [electron-userland/electron-builder#2940]
* **Version**: 20.13.4

 N/A

* **Target**:  Windows/OSX/Linux

I am not sure if this is by design or not, but I have seen several instances of electron-builder failing but exit code is still 0.  For example, when GH_TOKEN is not set, electron-builder CLI will print out the error in red but the exit code itself is 0.  Digging into the code (cli.ts), I see that the wrap() function catches the error, and sets the process.exitCode = 1.  However, it seems to get overridden somewhere (maybe an issue in yargs?).   We are trying integrate electron-builder into CI and this is causing issues.

**Comment by qtphan734** [comment]
Inside our package.json we defined a script "publish": "build -p always" and we are just executing that: "npm run publish"

**Comment by qtphan734** [comment]
Any updates on this? I have a workaround: Set a flag whenever an error occurred in wrap() function and add a process.on("exit") listener.

`//Set process.exitCode on exit event
process.on("exit", () => {
    if (errorOccurred) {
        process.exitCode = 1
    }
})`

**Comment by omeryagmurlu** [comment]
Any updates?

**Comment by radreamer** [comment]
Looks like I have a similar issue during codesign execution on macOS:
```
25-Jun-2018 16:56:28 | • signing         file=dist/mac/<APP_NAME>.app identityName=Developer ID Application: <TEAM> (<TEAM_ID>) identityHash=<IDENTITY_HASH> provisioningProfile=none
-- | --
25-Jun-2018 16:56:29 | • executing       file=security args=delete-keychain /private/var/folders/yw/t8ff2ms53tzbwkgrh_hjmncm0000gp/T/temp-dir-9enHGh/1.keychain
25-Jun-2018 16:56:29 | • executed        file=security
25-Jun-2018 16:56:29 | Error: Command failed: codesign --sign <IDENTITY_HASH> --force --keychain /private/var/folders/yw/t8ff2ms53tzbwkgrh_hjmncm0000gp/T/temp-dir-9enHGh/1.keychain /Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/dist/mac/<APP_NAME>.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
25-Jun-2018 16:56:29 | error: The specified item could not be found in the keychain.
25-Jun-2018 16:56:29 |  
25-Jun-2018 16:56:29 | at ChildProcess.exithandler (child_process.js:275:12)
25-Jun-2018 16:56:29 | at emitTwo (events.js:126:13)
25-Jun-2018 16:56:29 | at ChildProcess.emit (events.js:214:7)
25-Jun-2018 16:56:29 | at maybeClose (internal/child_process.js:925:16)
25-Jun-2018 16:56:29 | at Socket.stream.socket.on (internal/child_process.js:346:11)
25-Jun-2018 16:56:29 | at emitOne (events.js:116:13)
25-Jun-2018 16:56:29 | at Socket.emit (events.js:211:7)
25-Jun-2018 16:56:29 | at Pipe._handle.close [as _onclose] (net.js:557:12)
25-Jun-2018 16:56:29 | From previous event:
25-Jun-2018 16:56:29 | at MacPackager.sign (/Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/src/macPackager.ts:120:97)
25-Jun-2018 16:56:29 | at nonMasPromise.then (/Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/src/macPackager.ts:88:26)
25-Jun-2018 16:56:29 | at runCallback (timers.js:810:20)
25-Jun-2018 16:56:29 | at tryOnImmediate (timers.js:768:5)
25-Jun-2018 16:56:29 | at processImmediate [as _immediateCallback] (timers.js:745:5)
25-Jun-2018 16:56:29 | From previous event:
25-Jun-2018 16:56:29 | at /Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/src/macPackager.ts:88:10
25-Jun-2018 16:56:29 | at Generator.next (<anonymous>)
25-Jun-2018 16:56:29 | From previous event:
25-Jun-2018 16:56:29 | at MacPackager.pack (/Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/src/macPackager.ts:79:95)
25-Jun-2018 16:56:29 | at /Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/src/packager.ts:373:24
25-Jun-2018 16:56:29 | at Generator.next (<anonymous>)
25-Jun-2018 16:56:29 | at xfs.mkdir.er (/Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
25-Jun-2018 16:56:29 | at FSReqWrap.oncomplete (fs.js:135:15)
25-Jun-2018 16:56:29 | From previous event:
25-Jun-2018 16:56:29 | at Packager.doBuild (/Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/src/packager.ts:341:39)
25-Jun-2018 16:56:29 | at /Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/src/packager.ts:317:52
25-Jun-2018 16:56:29 | From previous event:
25-Jun-2018 16:56:29 | at Packager._build (/Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/src/packager.ts:294:133)
25-Jun-2018 16:56:29 | at /Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/src/packager.ts:290:23
25-Jun-2018 16:56:29 | at Generator.next (<anonymous>)
25-Jun-2018 16:56:29 | at runCallback (timers.js:810:20)
25-Jun-2018 16:56:29 | at tryOnImmediate (timers.js:768:5)
25-Jun-2018 16:56:29 | at processImmediate [as _immediateCallback] (timers.js:745:5)
25-Jun-2018 16:56:29 | From previous event:
25-Jun-2018 16:56:29 | at Packager.build (/Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/src/packager.ts:248:14)
25-Jun-2018 16:56:29 | at /Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/src/index.ts:51:40
25-Jun-2018 16:56:29 | at Generator.next (<anonymous>)
25-Jun-2018 16:56:29 | From previous event:
25-Jun-2018 16:56:29 | at build (/Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder-lib/out/index.js:220:17)
25-Jun-2018 16:56:29 | at build (/Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder/src/builder.ts:234:10)
25-Jun-2018 16:56:29 | at then (/Users/maytech/bamboo-agent-home/xml-data/build-dir/QX-QE-GP/node_modules/electron-builder/src/cli/cli.ts:46:19)
25-Jun-2018 16:56:29 | at <anonymous>
25-Jun-2018 16:56:29 | Finished task 'Build macOS sources' with result: Success```

**Comment by qtphan734** [comment]
The way I got around this is to do this programmatically.  In my gulpfile, I have a task that did something like this:

```
// Get electron builder configuration from electron-builder.json
const builderConfig = JSON.parse(fs.readFileSync('electron-builder.json'));
//Execute
builder.build({
	config: builderConfig,
}).then(() => {
	done();
}).catch((error) => {
	done(error);
});
```
