### ISSUE TITLE
Windows: Broken auto-updates for nsis

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#2949]
Okay, so I'm getting a different kind of errors on different electron-builder's version. 

a) **electron-builder: `v19.53.6` and `v20.8.1`**

Error - 

```
Getting the same error on `v19.53.6`.

[2018-05-25 02:42:00:0697] [error] Error: Error: Command failed: powershell.exe Get-AuthenticodeSignature 'C:\Users\username\AppData\Local\Temp\up-UN2ofR\test-web-setup-2.3.1.exe' | ConvertTo-Json -Compress

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at verifySignature (C:\Program Files\test\resources\app.asar\node_modules\electron-updater\src\windowsExecutableCodeSignatureVerifier.ts:11:3)
    at C:\Program Files\test\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:88:18
From previous event:
    at NsisUpdater.verifySignature (C:\Program Files\test\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:148:11)
    at C:\Program Files\test\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:43:54
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at C:\Program Files\test\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:118:33
    at C:\Program Files\test\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:46:13
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at NsisUpdater.executeDownload (C:\Program Files\test\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:98:11)
    at C:\Program Files\test\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:37:16
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Program Files\test\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:125:11)
    at C:\Program Files\test\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:331:25
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.downloadUpdate (C:\Program Files\test\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:366:11)
    at C:\Program Files\test\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:307:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files\test\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:337:11)
    at C:\Program Files\test\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:255:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Program Files\test\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:291:11)
    at NsisUpdater.checkForUpdates (C:\Program Files\test\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:204:35)
    at appUpdater (C:\Program Files\test\resources\app.asar\main\autoupdater.js:54:14)
    at WebContents.page.once (C:\Program Files\test\resources\app.asar\main\index.js:164:3)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
 
```
It's same as - https://github.com/electron-userland/electron-builder/issues/2589

**b) electron-builder: `v20.11.1`**

Error - 

```
[2018-05-25 03:07:28.020] [info] Checking for update
[2018-05-25 03:07:38.703] [info] Found version 2.3.1 (url: testapp-web-setup-2.3.1.exe)
[2018-05-25 03:07:38.719] [info] Downloading update from testapp-web-setup-2.3.1.exe
[2018-05-25 03:07:38.734] [info] No cached update available
[2018-05-25 03:07:56.314] [error] Cannot download differentially, fallback to full download: Error: EPERM: operation not permitted, open 'C:\Program Files\testapp\package.7z'
    at C:\Program Files\testapp\resources\app.asar\node_modules\builder-util-runtime\src\blockMapApi.ts:22:20
    at Generator.next (<anonymous>)
From previous event:
    at readEmbeddedBlockMapData (C:\Program Files\testapp\resources\app.asar\node_modules\builder-util-runtime\out\blockMapApi.js:55:17)
    at C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\FileWithEmbeddedBlockMapDifferentialDownloader.ts:11:44
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at FileWithEmbeddedBlockMapDifferentialDownloader.download (C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\out\differentialDownloader\FileWithEmbeddedBlockMapDifferentialDownloader.js:49:7)
    at C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:182:10
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.differentialDownloadWebPackage (C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:311:7)
    at Object.<anonymous> (C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:50:26)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:177:25)
    at C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:83:25
    at Generator.throw (<anonymous>)
From previous event:
    at NsisUpdater.executeDownload (C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:164:7)
    at C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:31:23
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:181:7)
    at C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:361:25
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.downloadUpdate (C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:539:7)
    at C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:337:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:502:7)
    at C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:279:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:433:7)
    at NsisUpdater.checkForUpdates (C:\Program Files\testapp\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:217:35)
    at appUpdater (C:\Program Files\testapp\resources\app.asar\main\autoupdater.js:54:14)
    at WebContents.page.once (C:\Program Files\testapp\resources\app.asar\main\index.js:164:3)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
[2018-05-25 03:08:55.571] [info] New version 2.3.1 has been downloaded to C:\Users\username\AppData\Roaming\testapp\installer-2.3.1.exe
[2018-05-25 03:09:01.524] [info] Install on explicit quitAndInstall
[2018-05-25 03:09:01.524] [info] Install: isSilent: false, isRunAfter: true
[2018-05-25 03:09:01.961] [info] Access denied or UNKNOWN error code on spawn, will be executed again using elevate
[2018-05-25 03:09:02.086] [info] Update installer has already been triggered. Quitting application.
[2018-05-25 03:09:20.875] [info] Checking for update
[2018-05-25 03:09:32.748] [info] Update for version 2.3.1 is not available (latest version: 2.3.1, downgrade is disallowed).
```

The app does able to auto-update in this case but the differential update doesn't work.

**c) electron-builder: `v20.8.1` -**

> When I accept the Update dialog the old version gets uninstalled then everything stops. The launching icon says the exe is missing and I should delete the shortcut.

Error 

```
[2018-03-24 09:04:46:0609] [info] Checking for update
[2018-03-24 09:04:48:0177] [info] Generated new staging user ID: 9dbb8cb7-9c76-5f5a-b0c0-2b2669b7a167
[2018-03-24 09:04:51:0503] [info] Found version 1.9.0 (url: testapp-web-setup-1.9.0.exe)
[2018-03-24 09:04:51:0506] [info] Downloading update from testapp-web-setup-1.9.0.exe
[2018-03-24 09:04:56:0153] [info] File has 1568 changed blocks
[2018-03-24 09:04:56:0162] [info] Full: 39,491.76 KB, To download: 32,143.6 KB (81%)
[2018-03-24 09:04:56:0176] [info] Differential download: https://github.com/testapp/testapp-electron/releases/download/v1.9.0/testapp-1.9.0-x64.nsis.7z
[2018-03-24 09:04:56:0352] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/60656871/5d3bcabc-2ed6-11e8-820c-173cd59753f0
[2018-03-24 09:05:01:0547] [info] New version 1.9.0 has been downloaded to C:\Users\username\AppData\Local\Temp\2\up-iW4iWZ\testapp-web-setup-1.9.0.exe
[2018-03-24 09:05:04:0727] [info] Install on explicit quitAndInstall
[2018-03-24 09:05:04:0729] [info] Install: isSilent: false, isRunAfter: true
[2018-03-24 09:05:20:0262] [info] Checking for update
[2018-03-24 09:05:25:0037] [info] Update for version 1.9.0 is not available (latest version: 1.9.0, downgrade is disallowed.
[2018-03-26 13:30:06:0278] [info] Checking for update
[2018-03-26 13:30:11:0611] [info] Update for version 1.9.0 is not available (latest version: 1.9.0, downgrade is disallowed.
[2018-03-31 16:05:27:0485] [info] Checking for update
[2018-03-31 16:05:32:0387] [info] Update for version 1.9.0 is not available (latest version: 1.9.0, downgrade is disallowed.
[2018-05-10 10:18:38:0322] [info] Checking for update
[2018-05-10 10:18:43:0995] [info] Found version 2.0.0 (url: testapp-web-setup-2.0.0.exe)
[2018-05-10 10:18:44:0000] [info] Downloading update from testapp-web-setup-2.0.0.exe
[2018-05-10 10:18:48:0886] [info] File has 1175 changed blocks
[2018-05-10 10:18:48:0987] [info] Full: 39,607.86 KB, To download: 23,668.18 KB (60%)
[2018-05-10 10:18:49:0178] [info] Differential download: https://github.com/testapp/testapp-electron/releases/download/v2.0.0/testapp-2.0.0-x64.nsis.7z
[2018-05-10 10:18:49:0370] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/60656871/762512b6-43fa-11e8-9392-edf59d0f465a
[2018-05-10 10:18:55:0311] [info] New version 2.0.0 has been downloaded to C:\Users\username\AppData\Local\Temp\17\up-eV01Sf\testapp-web-setup-2.0.0.exe
[2018-05-10 10:19:40:0538] [info] Install on explicit quitAndInstall
[2018-05-10 10:19:40:0539] [info] Install: isSilent: false, isRunAfter: true
[2018-05-10 10:19:57:0461] [info] Checking for update
[2018-05-10 10:20:03:0624] [info] Update for version 2.0.0 is not available (latest version: 2.0.0, downgrade is disallowed.
[2018-05-10 17:58:09:0531] [info] Checking for update
[2018-05-10 17:58:15:0320] [info] Update for version 2.0.0 is not available (latest version: 2.0.0, downgrade is disallowed.
[2018-05-24 18:10:23:0307] [info] Checking for update
[2018-05-24 18:10:31:0229] [info] Found version 2.3.1 (url: testapp-web-setup-2.3.1.exe)
[2018-05-24 18:10:31:0230] [info] Downloading update from testapp-web-setup-2.3.1.exe
[2018-05-24 18:10:31:0271] [info] No cached update available
[2018-05-24 18:10:39:0614] [info] File has 1859 changed blocks
[2018-05-24 18:10:39:0687] [info] Full: 40,015.95 KB, To download: 37,915.67 KB (95%)
[2018-05-24 18:10:39:0695] [info] Differential download: https://github.com/testapp/testapp-electron/releases/download/v2.3.1/testapp-2.3.1-x64.nsis.7z
[2018-05-24 18:10:39:0936] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/60656871/17ba1204-5ee8-11e8-9cdd-8ecc145cad9c
[2018-05-24 18:10:48:0697] [info] New version 2.3.1 has been downloaded to C:\Users\username\AppData\Roaming\testapp\installer-2.3.1.exe
[2018-05-24 18:12:14:0620] [info] Install on explicit quitAndInstall
[2018-05-24 18:12:14:0620] [info] Install: isSilent: false, isRunAfter: true
[2018-05-24 18:12:15:0087] [info] Update installer has already been triggered. Quitting application.
[2018-05-24 18:15:22:0396] [info] Checking for update
[2018-05-24 18:15:28:0342] [info] Found version 2.3.1 (url: testapp-web-setup-2.3.1.exe)
[2018-05-24 18:15:28:0343] [info] Downloading update from testapp-web-setup-2.3.1.exe
[2018-05-24 18:15:28:0395] [info] Update has already been downloaded C:\Users\username\AppData\Roaming\testapp\installer-2.3.1.exe).
[2018-05-24 18:15:47:0119] [info] Install on explicit quitAndInstall
[2018-05-24 18:15:47:0120] [info] Install: isSilent: false, isRunAfter: true
[2018-05-24 18:15:47:0159] [info] Update installer has already been triggered. Quitting application.
```

**Comment by akashnimare** [comment]
I think the error a)

```
[2018-03-02 16:57:14:0957] [warn] Cannot execute Get-AuthenticodeSignature: Error: Command failed: powershell.exe Get-AuthenticodeSignature 'D:\Users\username\AppData\Local\Temp\up-cx7rgd\testapp-web-setup-1.8.2.exe' | ConvertTo-Json -Compress
The term 'ConvertTo-Json' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
At line:1 char:116
+ Get-AuthenticodeSignature 'D:\Users\username\AppData\Local\Temp\up-cx7rgd\testapp
-web-setup-1.8.2.exe' | ConvertTo-Json <<<<  -Compress
    + CategoryInfo          : ObjectNotFound: (ConvertTo-Json:String) [], Comm 
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
. Ignoring signature validation due to unsupported powershell version. Please upgrade to powershell 3 or higher.
```
is happeing due to the powershell I think.

**Comment by rickling** [comment]
We're also experiencing c). It doesn't actually clear the whole folder but just the main .exe for us.

**Comment by tzarebczan** [comment]
We've also experienced this intermittently on the same electron builder version. Running a 2nd time works. Could it be related to the installer downloaded?

**Comment by develar** [comment]
>  Error: Error: Command failed: powershell.exe

I see that the only acceptable implementation of `verifySignature` must be rejection only in case of failed validation on our side. Currently, error is ignored for `isOldWin6`. But Windows is Windows and we cannot simply reject update if something is broken and we got unclear error. It is out of electron-updater scope to verify system — if system is corrupted somehow — it is not electron-updater business to protect user.

Level will be changed to `warn`.

**Comment by develar** [comment]
> EPERM: operation not permitted, open 'C:\Program Files\testapp\package.7z'

What? Flag `r` is used correctly, why windows blocks access...

**Comment by develar** [comment]
> c) electron-builder: v20.8.1 -

Should be fixed now. Some fixes (thanks to PR) were applied recently.
