### ISSUE TITLE
Error with pack on Windows 

### ISSUE THREAD

**Issue by klinkov** [electron-userland/electron-builder#2950]
Hi
Got this error when try to pack on Windows 10
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli
'C:\\Users\\shade\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli 'run',
1 verbose cli 'pack' ]
2 info using npm@ 6 . 0 . 1
3 info using node@ v8.11.2
4 verbose run-script [ 'prepack', 'pack', 'postpack' ]
5 info lifecycle lookinglass@ 1 . 0 . 0 ~prepack : lookinglass@ 1 . 0 . 0
6 info lifecycle lookinglass@ 1 . 0 . 0 ~pack : lookinglass@ 1 . 0 . 0
7 verbose lifecycle lookinglass@ 1 . 0 . 0 ~pack : unsafe-perm in lifecycle true
8 verbose lifecycle lookinglass@ 1 . 0 . 0 ~pack : PATH:
C:\Users\shade\AppData\Roaming\npm\node_modules\npm\node_modules\npm-
lifecycle\node-gyp-bin;C:\Work\Archive\node_modules\.bin;C:\Program
Files\Docker\Docker\Resources\bin;C:\Python27\;C:\Python27\Scripts;C:\ProgramData
\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbe
m;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA
Corporation\PhysX\Common;C:\WINDOWS\system32\confg\systemprofle\.dnx\bin;C:\
Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows
Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL
Server\130\Tools\Binn\;C:\Program
Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C
:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Pr
ogram Files\Calibre2\;C:\Program Files
(x86)\Yarn\bin;C:\nodejs\;C:\WINDOWS\System32\OpenSSH\;C:\Users\shade\AppData
\Local\Microsoft\WindowsApps;C:\Android\SDK\tools;C:\Android\SDK\platform-
tools;C:\Users\shade\AppData\Local\Yarn\bin;;C:\Program Files\Microsoft VS
Code\bin;C:\Users\shade\AppData\Roaming\npm
9 verbose lifecycle lookinglass@ 1 . 0 . 0 ~pack : CWD: C:\Work\Archive
10 silly lifecycle lookinglass@ 1 . 0 . 0 ~pack : Args: [ '/d /s /c', 'electron-builder --dir' ]
11 silly lifecycle lookinglass@ 1 . 0 . 0 ~pack : Returned: code: 1 signal:
12 info lifecycle lookinglass@ 1 . 0 . 0 ~pack : Failed to exec pack script
13 verbose stack Error: lookinglass@ 1 . 0 . 0 pack: `electron-builder --dir`
13 verbose stack Exit status 1
13 verbose stack at EventEmitter.<anonymous>
(C:\Users\shade\AppData\Roaming\npm\node_modules\npm\node_modules\npm-
lifecycle\index.js:283:16)
13 verbose stack at emitTwo (events.js:126:13)
13 verbose stack at EventEmitter.emit (events.js:214:7)
13 verbose stack at ChildProcess.<anonymous>
(C:\Users\shade\AppData\Roaming\npm\node_modules\npm\node_modules\npm-
lifecycle\lib\spawn.js:55:14)
13 verbose stack at emitTwo (events.js:126:13)
13 verbose stack at ChildProcess.emit (events.js:214:7)
13 verbose stack at maybeClose (internal/child_process.js:925:16)
13 verbose stack at Process.ChildProcess._handle.onexit
(internal/child_process.js:209:5)
14 verbose pkgid lookinglass@ 1 . 0 . 0
15 verbose cwd C:\Work\Archive
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\nodejs\\node.exe"
"C:\\Users\\shade\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js"
"run" "pack"
18 verbose node v8.11.2
19 verbose npm v6.0.1
20 error code ELIFECYCLE
21 error errno 1
22 error lookinglass@ 1 . 0 . 0 pack: `electron-builder --dir`
22 error Exit status 1
23 error Failed at the lookinglass@ 1 . 0 . 0 pack script.
23 error This is probably not a problem with npm. There is likely additional logging
output above.
24 verbose exit [ 1, true ]
```

my package.json
```
  "devDependencies": {
    "cross-env": "^5.1.6",
    "electron": "2.0.0",
    "electron-builder": "20.11.1",
    "electron-packager": "12.0.2",
    "electron-prebuilt-compile": "2.0.0",
    "electron-rebuild": "^1.7.3"
  },
  "dependencies": {
    "crypto-js": "^3.1.9-1",
    "electron-store": "^1.3.0",
    "fs": "0.0.1-security",
    "jquery": "3.3.1",
    "moment": "2.22.1",
    "password-generator": "^2.2.0",
    "path": "^0.12.7",
    "zxcvbn": "^4.4.2"
  },
```

**Comment by develar** [comment]
Please try to execute using yarn. Or `npx electron-builder --dir`

**Comment by klinkov** [comment]
Fixed by remove ES6 code from main.js.
