### ISSUE TITLE
Native module compilation fails - runs twice?

### ISSUE THREAD

**Issue by mischnic** [electron-userland/electron-builder#2954]
* **Version**: 20.15.1 (Node 10.2.1, npm 6.1.0, yarn 1.7.0)

* **Target**:  macOS

Why is everything logged twice?

```
$ yarn build
yarn run v1.7.0
$ electron-builder --dir
  • electron-builder version=20.15.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
  • rebuilding native dependency name=serialport
  • rebuilding native dependency name=usb
Error: /usr/local/Cellar/node/10.2.1/bin/node exited with code 1
Error output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.2.1 | darwin | x64
node-pre-gyp http GET https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-electron-v2.0-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-electron-v2.0-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-electron-v2.0-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for usb@1.3.1 and electron@2.0.2 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-electron-v2.0-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-electron-v2.0-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for usb@1.3.1 and electron@2.0.2 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
gypgyp info  it worked if it ends with ok
info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.2.1 | darwin | x64
gyp info using node-gyp@3.6.2
gyp info using node@10.2.1 | darwin | x64
gypgyp  info infook
 ok
gyp info it worked if it ends with ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.2.1 | darwin | x64
gyp info using node-gyp@3.6.2
gyp info using node@10.2.1 | darwin | x64
gyp http GETgyp https://atom.io/download/electron/v2.0.2/iojs-v2.0.2.tar.gz
 http GET https://atom.io/download/electron/v2.0.2/iojs-v2.0.2.tar.gz
gyp http 200 https://atom.io/download/electron/v2.0.2/iojs-v2.0.2.tar.gz
gyp http 200 https://atom.io/download/electron/v2.0.2/iojs-v2.0.2.tar.gz
gyp http GET https://atom.io/download/electron/v2.0.2/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v2.0.2/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/usb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/niklas/.electron-gyp/iojs-2.0.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/niklas/.electron-gyp/iojs-2.0.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/niklas/.electron-gyp/iojs-2.0.2/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/usb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp http GET https://atom.io/download/electron/v2.0.2/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v2.0.2/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/usb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/niklas/.electron-gyp/iojs-2.0.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/niklas/.electron-gyp/iojs-2.0.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/niklas/.electron-gyp/iojs-2.0.2/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/usb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info ok
gypgyp  info it worked if it ends withinfo ok
 it worked if it ends with ok
gyp info usinggyp node-gyp@3.6.2
 gyp infoinfo  using node@10.2.1 | darwin | x64
using node-gyp@3.6.2
gyp info using node@10.2.1 | darwin | x64
gyp gypinfo  spawninfo make
 spawn make
gyp gypinfo  infospawn args  [ 'BUILDTYPE=Release', '-C', 'build' ]
spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
../libusb/libusb/core.c:2241:35: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
../libusb/libusb/core.c:2241:35: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
        if (header_len < 0 || header_len >= sizeof(buf)) {
                              ~~~~~~~~~~ ^  ~~~~~~~~~~~
        if (header_len < 0 || header_len >= sizeof(buf)) {
                              ~~~~~~~~~~ ^  ~~~~~~~~~~~
../libusb/libusb/core.c../libusb/libusb/core.c::22502250::4444::  warningwarning: : comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]

        if (text_len < 0 || text_len + header_len >= sizeof(buf)) {
                            ~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~        if (text_len < 0 || text_len + header_len >= sizeof(buf)) {

                            ~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~
2 warnings generated.
2 warnings generated.
rm: ./Release/.deps/Release/obj.target/libusb/libusb/libusb/core.o.d.raw: No such file or directory
make: *** [libusb.target.mk:147: Release/obj.target/libusb/libusb/libusb/core.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/10.2.1/bin/node" "/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/usb/src/binding"
gyp ERR! cwd /Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/usb
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.2.1/bin/node" "/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/usb
node-pre-gyp ERR! node -v v10.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
error Command failed with exit code 1.
../libusb/libusb/os/darwin_usb.c:344:3: warning: 'objc_registerThreadWithCollector' is deprecated: it does nothing. Define OBJC_SILENCE_GC_DEPRECATIONS=1 to temporarily silence this diagnostic. [-Wdeprecated-declarations]
  objc_registerThreadWithCollector();
  ^
/usr/include/objc/objc-auto.h:244:1: note: 'objc_registerThreadWithCollector' has been explicitly marked deprecated here
OBJC_GC_DEPRECATED("it does nothing")
^
/usr/include/objc/objc-auto.h:47:55: note: expanded from macro 'OBJC_GC_DEPRECATED'
#   define OBJC_GC_DEPRECATED(message) __attribute__((deprecated(message ". Define OBJC_SILENCE_GC_DEPRECATIONS=1 to temporarily silence this diagnostic.")))
                                                      ^
../libusb/libusb/os/darwin_usb.c:1281:27: warning: expression which evaluates to zero treated as a null pointer constant of type 'IOUSBInterfaceInterface550 **' (aka 'struct IOUSBInterfaceStruct550 **') [-Wnon-literal-null-conversion]
  cInterface->interface = IO_OBJECT_NULL;
                          ^~~~~~~~~~~~~~
/System/Library/Frameworks/IOKit.framework/Headers/IOTypes.h:164:24: note: expanded from macro 'IO_OBJECT_NULL'
#define IO_OBJECT_NULL  ((io_object_t) 0)
                        ^~~~~~~~~~~~~~~~~
2 warnings generated.
../src/node_usb.cc:150:7: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        Nan::MakeCallback(Nan::New(hotplugThis), "emit", 2, argv);
             ^
../../nan/nan.h:971:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning generated.
../src/device.cc:237:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
                        Nan::MakeCallback(device, Nan::New(baton->callback), 1, argv);
                             ^
../../nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning generated.
../src/transfer.cc:126:8: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
                Nan::MakeCallback(self->handle(), Nan::New(self->v8callback), 3, argv);
                     ^
../../nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning generated.
gyp info ok

    at ChildProcess.childProcess.once.code (/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
From previous event:
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at /Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/src/util/yarn.ts:150:27
From previous event:
    at rebuild (/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/out/util/yarn.js:234:18)
    at /Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/src/util/yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at installOrRebuild (/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/out/util/yarn.js:68:17)
    at /Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/src/packager.ts:451:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/src/packager.ts:415:70)
    at /Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/src/packager.ts:365:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/src/packager.ts:341:39)
    at /Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/src/packager.ts:317:52
    at Generator.next (<anonymous>)
    at /Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:169:20)
From previous event:
    at Packager._build (/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/src/packager.ts:294:133)
    at /Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/src/packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/src/packager.ts:248:14)
    at /Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/Users/niklas/Documents/_dev/_git/Watering/WateringGUI/node_modules/electron-builder/src/cli/cli.ts:46:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```json
{
	"main": "src/main.js",
	"scripts": {
		"start": "electron .",
		"rebuild": "electron-rebuild",
		"build": "electron-builder --dir",
		"package": "electron-builder",
		"postinstall": "electron-builder install-app-deps"
	},
	"build": {
		"files": [
			"src/**/*",
			"node_modules/**/*",
			"package.json"
		],
		"mac": {
			"category": "public.app-category.developer-tools",
			"identity": null
		},
	},
	"devDependencies": {
		"electron": "^2.0.0",
		"electron-builder": "^20.13.4"
	},
	"dependencies": {
		"electron-settings": "^3.1.4",
		"font-awesome": "^4.7.0",
		"jquery": "^3.2.1",
		"serialport": "^6.0.4",
		"tree-kill": "^1.2.0",
		"usbtinyisp": "mischnic/usbtinyisp"
	}
}
```

**Comment by mischnic** [comment]
Works fine with Node 8.11.2 and npm 5.6.0. (Homebrew: `export PATH="/usr/local/opt/node@8/bin:$PATH"`)

**Comment by mischnic** [comment]
Actual issue: https://github.com/tessel/node-usb/issues/244

**Comment by pumano** [comment]
I got the same scenario. I have `usb` and `serialport`. Building from source via `electron-builder` got race condition for file access. It starts after upgrading from node 10.1 to 10.6. Currently as workaround I downgrade `nodejs` to 10.1 and it compile successfully. 

stacktrace:
```
 win_delay_load_hook.cc
C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc : fatal error C
1083: Cannot open include file: C:\Repository\MyApp\node_modules\usb\build\Release\ob
j\libusb\win_delay_load_hook.obj: Permission denied [C:\Repository\MyApp\node_modules\usb\build\libusb.vc
xproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

**Comment by mischnic** [comment]
`usb` updated their `node-pre-gyp` dependency. It works for me now (macOS). Try upgrading usb to 1.3.2.

**Comment by aabuziad** [comment]
Uninstalling Yarn worked for me, Because i have all the dependencies on npm but not having them on Yarn.

So electron-builder will find missing dependencies using Yarn.
