### ISSUE TITLE
Error: Application entry file "main.js" in the ".../Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.

### ISSUE THREAD

**Issue by nkint** [electron-userland/electron-builder#2955]
* **Version**: 
    "electron": "^2.0.2",
    "electron-builder": "^20.15.1",
    "electron-webpack": "^2.1.2"

    node v10.0.0
    yarn 1.6.0
    mac sierra 10.13.4

* **Target**: 
mac

I'm following this gist:
https://gist.github.com/matthewjberger/6f42452cb1a2253667942d333ff53404

Everything is ok, development is ok, but on `yarn dist`
I get this error:
```
Error: Application entry file "main.js" in the ".../Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
```

I found somewhere a workaround as add `"extends": null` in `build` in package.json but I get a compiled file (.app) that open a white page.
If I start the electron app created that shows only a white page with the inspector opened I see `app.js not found error`

My package.json build right now is:
```
"build": {
      "appId": "com.electron.electron-with-create-react-app",
      "win": {
          "icon": "https://cdn2.iconfinder.com/data/icons/designer-skills/128/react-256.png"
      },
      "directories": {
          "buildResources": "public"
      }
  },
```

I've tried to copy my `src/electron-starter.js` into `main.js` (into main project directory) and in `src/main.js` and into `public/main.js` as a workaround but the error is still there.

Do you have any hint?
Do I have to post something more about my actual project?

**Comment by alice-em** [comment]
I'm getting a similar issue also.

```
> wonder-reader@1.0.0-a electron-pack /home/alice-mod/Documents/git/wonder-reader
> electron-builder -c.extraMetadata.main = build / electron.js

  • electron-builder version=20.15.1
  • loaded configuration file=package.json ("build" field)
  • loaded parent configuration preset=react-cra
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • packaging       platform=linux arch=x64 electron=2.0.2 appOutDir=dist/linux-unpacked
Error: Application entry file "=" in the "/home/alice-mod/Documents/git/wonder-reader/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/asar/asarFileChecker.ts:33:11
    at Generator.next (<anonymous>)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at checkFileInArchive (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/out/asar/asarFileChecker.js:78:17)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/platformPackager.ts:356:13
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.checkFileInPackage (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/platformPackager.ts:353:110)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/platformPackager.ts:405:16
    at Generator.next (<anonymous>)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at LinuxPackager.sanityCheckPackage (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/platformPackager.ts:392:70)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/platformPackager.ts:232:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at LinuxPackager.doPack (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/platformPackager.ts:162:151)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/platformPackager.ts:117:16
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.pack (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/platformPackager.ts:115:95)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/packager.ts:373:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/alice-mod/Documents/git/wonder-reader/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/packager.ts:341:39)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/packager.ts:317:52
    at Generator.next (<anonymous>)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/packager.ts:294:133)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/packager.ts:248:14)
    at /home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/home/alice-mod/Documents/git/wonder-reader/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wonder-reader@1.0.0-a electron-pack: `electron-builder -c.extraMetadata.main = build / electron.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wonder-reader@1.0.0-a electron-pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alice-mod/.npm/_logs/2018-05-29T06_33_44_694Z-debug.log
```

My code is (here)[https://github.com/alice-em/wonder-reader/tree/snapcraft].  I don't fully understand how to go about debugging this particular error message.

**Comment by pcicho** [comment]
Try this

```
 "files": [
      "**/*",
      "dist/*"
    ],
```

**Comment by mikew** [comment]
I'm seeing this as well. It's only happening in CI, on both Windows and macOS.

It works in development in both environments, as well as when run manually in the CI environments. But when running it through Gitlab CI, I'm seeing this error.

Even better, with the exact same setup, just in a different branch name, it works fine.

**Comment by vishakhag6** [comment]
Hi, 

If I follow this, I am getting the same error for ubuntu. 

Error: Application entry file "main.js" in the "/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.

Is there any solution?

main.js contains:
`const { app, BrowserWindow } = require('electron');
let win;
function createWindow() {

  // Create the browser window.
  win = new BrowserWindow({ width: 800, height: 600 });

  // If you want to give full screen
  // win = new BrowserWindow({ fullscreen: true })

  // and load the index.html of the app. 
  win.loadFile('../dist/app/index.html');

  // Open the DevTools.
  win.webContents.openDevTools();

  // Emitted when the window is closed.
  win.on('closed', () => {
    win = null
  })
};

// This method will be called when Electron has finished   
// initialization and is ready to create browser windows.   
// Some APIs can only be used after this event occurs.   
app.on('ready', createWindow);

// Quit when all windows are closed.
app.on('window-all-closed', () => {

  // On macOS it is common for applications and their menu bar     
  // to stay active until the user quits explicitly with Cmd + Q     
  if (process.platform !== 'darwin') { app.quit() }
});

app.on('activate', () => {
  // On macOS it's common to re-create a window in the app when the     
  // dock icon is clicked and there are no other windows open.
  if (win === null) { createWindow() }
});  `

**Comment by vishakhag6** [comment]
How did you solve your issue?

**Comment by seksitha** [comment]
I'm trying this and it works. electron-builder need build folder in the package.
i have `src/main.js` and no build machanicm for my app to generate build like `react-script`.

so what work is to let the EB to know what directory is use as build folder by using files key in package.json.
```
"files": [
            "node_modules/**/*",
            {
                "from":"src",
                "to":"build",
                "filter":"**/*"
            }	
],
```
p.s I'm new to EB too I don't know if it work for everyone.

**Comment by Suroor-Ahmmad** [comment]
Refer this #1482 
If your output directory name as `build` this will throw error

**Comment by danielehrhardt** [comment]
This is really wried on Windows it does work to Build windows but on Mac it does not work.
