### ISSUE TITLE
Error on build for Windows portable or nsis on Windows...

### ISSUE THREAD

**Issue by jonatasfreitasv** [electron-userland/electron-builder#2973]
Build for Linux and OSX run ok, on Debian...

* **Version**: 
"electron": "^2.0.2",
"electron-builder": "^20.15.1",

* **Target**: 
```
"build": {
    "productName": "HouseOps",
    "appId": "org.house.ops",
    "files": [
      "dist/",
      "node_modules/",
      "resources/",
      "app.html",
      "loading.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json"
    ],
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "target": [
        "portable"
      ]
    },
    "linux": {
      "target": [
        "deb"
      ],
      "category": "Development"
    },
    "directories": {
      "buildResources": "resources",
      "output": "release"
    }
  },
```

* **Stacktrace**:
```
Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:780:25)
    at Socket._write (net.js:799:8)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:717:40)
    at Socket.Writable.end (_stream_writable.js:563:10)
    at Socket.end (net.js:509:31)
    at Promise (C:\Users\Anon\Projects\HouseOps\node_modules\builder-util\src\util.ts:201:24)
    at new Promise (<anonymous>)
    at spawnAndWrite (C:\Users\Anon\Projects\HouseOps\node_modules\builder-util\src\util.ts:184:10)
    at C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:466:11
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.executeMakensis (C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:434:76)
    at C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:230:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at NsisTarget.buildInstaller (C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:123:31)
    at C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:107:18
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:105:20)
    at C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\packager.ts:381:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.doBuild (C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\packager.ts:341:39)
    at C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\packager.ts:317:52
    at Generator.next (<anonymous>)
    at C:\Users\Anon\Projects\HouseOps\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\Anon\Projects\HouseOps\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\packager.ts:294:133)
    at C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\packager.ts:248:14)
    at C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\src\index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder-lib\out\index.js:220:17)
    at build (C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder\src\builder.ts:234:10)
    at then (C:\Users\Anon\Projects\HouseOps\node_modules\electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
```

**Comment by ishansharma2912** [comment]
@jonatasfreitasv I'm also getting the same error from last 2 days and looking for the solution. Have you resolved this or applied any solution to get this resolve?
