### ISSUE TITLE
Unhandled promise rejection when downloading update fails

### ISSUE THREAD

**Issue by jasonoverland** [electron-userland/electron-builder#2978]
* **Version**:  20.14.7

2.21.10

* **Target**: NSIS(Windows), Dmg (Mac), AppImage (Linux)

Hi. We are developing a new electron application and are still getting familiar with JS tooling, promises, etc. We are using electron-updater. For context here is our workflow: We call checkForUpdates after electron is ready(), then we offer the user the choice to quitAndInstall().

We also have decided to install global handlers for all uncaught exceptions and unhandled rejections which display a "something bad happened; please restart" message to the user while also sending us feedback.

This has all been working for us however we recently changed our application name, which resulted in a state where we had a 404 error when trying to download the .exe. This resulted in an unhandled promise rejection. Our desire is that a failure to find an update is silent to the user (if latest.yml is not found, it is silent). Our thought was that this rename failure should not happen, but maybe something like it could happen in production (connectivity issues, etc).

It looks like there is already a .catch inside checkForUpdates(), but somebody further inside is not bubbling the error. I'm trying to track through the electron-updater code to see where I might add a .catch() but there is a lot of layers and I'm not quite sure where to poke yet.

Where in the call chain might a .catch() go?

[2018-06-01 15:20:49.345] [info] Checking for update
[2018-06-01 15:20:51.722] [info] Found version 0.5.5042 (url: Thunderstruck Setup 0.5.5042.exe)
[2018-06-01 15:20:51.723] [info] Downloading update from Thunderstruck Setup 0.5.5042.exe
[2018-06-01 15:20:51.734] [info] No cached update available
[2018-06-01 15:20:51.755] [error] Error: Error: Cannot download "http://localhost/thunderstruck/Thunderstruck%20Setup%200.5.5042.exe", status 404: Not Found
    at ClientRequest.request.doRequest.response (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:216:18)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at URLRequest.ClientRequest.urlRequest.on (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\electron.asar\browser\api\net.js:207:12)
    at emitOne (events.js:116:13)
    at URLRequest.emit (events.js:211:7)
From previous event:
    at CancellationToken.createPromise (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\builder-util-runtime\out\CancellationToken.js:75:12)
    at C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\electronHttpExecutor.js:66:46
    at Generator.next (<anonymous>)
From previous event:
    at ElectronHttpExecutor.download (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\electronHttpExecutor.js:79:7)
    at Object.<anonymous> (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:142:40)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:177:25)
    at C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:148:27
    at Generator.throw (<anonymous>)
From previous event:
    at NsisUpdater.executeDownload (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:164:7)
    at C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:134:26
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:181:7)
    at C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:533:29
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.downloadUpdate (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:539:7)
    at C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:500:55
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:502:7)
    at C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:427:29
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:433:7)
    at NsisUpdater.checkForUpdates (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:349:35)
    at App.app.on (C:\Users\joverland\AppData\Local\Programs\thunderstruck\resources\app.asar\src\electron-starter.js:446:18)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)

**Comment by jasonoverland** [comment]
This patch seems to do the trick for me.

[electron-updater+2.21.10.patch.txt](https://github.com/electron-userland/electron-builder/files/2070408/electron-updater.2.21.10.patch.txt)

**Comment by jasonoverland** [comment]
I had to re-apply this tiny patch on my tree. I could make a PR if needed? It was only a try/catch/rethrow wrapper which I'm not sure if is the best solution. Thanks.

**Comment by andersekdahl** [comment]
I'm seeing this as well. I'm using `electron-unhandled`. My code:

```
autoUpdater.on('error', e => {
  log.error('Failed to check for updates');
  log.error(e);
});

autoUpdater.checkForUpdates().catch(e => {
  log.error('Failed to check for updates');
  log.error(e);
});
```

I'm catching everything I can, but it's still reported as unhandled. I would assume that it's a rejected promise that doesn't propagate. I would have thought that the downloading failed that would be propagated so the promise that `autoUpdater.checkForUpdates()` would be the rejected promise for the download.

electron: 6.0.8
electron-updater: 4.1.2
electron-unhandled: 3.0.0

**Comment by teremyx** [comment]
I know this has been closed, but I think this is unexpected behaviour. The _error_-event lets me "catch" the error, but I'd rather use the promise's catch-function. It helps me structure my code better, because I know the error belongs to the promise. There are many different reasons that could lead to the error-event, so it's harder to give good feedback to the user in terms of what actually caused the error.

**Comment by tukanFrozen** [comment]
Same here, any fix?

**Comment by skident** [comment]
I observe the same issue for a long time.
