### ISSUE TITLE
Error: Command failed: codesign

### ISSUE THREAD

**Issue by Dotnaught** [electron-userland/electron-builder#2990]
electron-builder 20.15.1
targeting Mac dmg
on macOS 10.13.5

I recently added electron-builder to an Electron app I've successfully packaged previously for non-store distribution using electron-packager. But electron-builder throws an error.

The error notes that provisioningProfile=none, which I take to mean that I haven't properly configured code signing (though packager was fine without this).

I was under the impression electron-builder would pick up the provisioning profile from Keychain. But perhaps I need to supply a path?

Update: export CSC_IDENTITY_AUTO_DISCOVERY=false makes the build work correctly.

Is some extra step necessary to get provisioningProfile to register the installed profile?

Update: Also noticed this after setting DEBUG=electron-builder:

not packed into asar archive file=release-builds/vulture-feeds-darwin-x64/vulture-feeds.app/Contents/Resources/app/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib reason=contains executable code

Not sure if this is related to codesign failure.

> build

  • electron-builder version=20.15.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=2.0.2 appOutDir=dist/mac
  • signing         file=dist/mac/vulture-feeds.app identityName=Developer ID Application: XXXXXXXXXXX (XXXXXXXXXX) identityHash=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX provisioningProfile=none
**Error: Command failed: codesign --sign XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --force /Users/tk/Code/Git/vulture-feeds/dist/mac/vulture-feeds.app/Contents/Resources/app.asar.unpacked/release-builds/vulture-feeds-darwin-x64/vulture-feeds.app/Contents/Resources/app/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework
/Users/tk/Code/Git/vulture-feeds/dist/mac/vulture-feeds.app/Contents/Resources/app.asar.unpacked/release-builds/vulture-feeds-darwin-x64/vulture-feeds.app/Contents/Resources/app/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework: bundle format unrecognized, invalid, or unsuitable**

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at MacPackager.sign (/Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/src/macPackager.ts:120:97)
    at nonMasPromise.then (/Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/src/macPackager.ts:88:26)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at /Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/src/macPackager.ts:88:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/src/macPackager.ts:79:95)
    at /Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/src/packager.ts:373:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/tk/Code/Git/vulture-feeds/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/tk/Code/Git/vulture-feeds/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/src/packager.ts:341:39)
    at /Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/src/packager.ts:317:52
    at Generator.next (<anonymous>)
    at /Users/tk/Code/Git/vulture-feeds/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/tk/Code/Git/vulture-feeds/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/src/packager.ts:294:133)
    at /Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/src/packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/src/packager.ts:248:14)
    at /Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/Users/tk/Code/Git/vulture-feeds/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vulture-feeds@1.0.0 dist: `build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vulture-feeds@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tk/.npm/_logs/2018-06-06T15_32_05_980Z-debug.log

DEBUG LOG
0 info it worked if it ends with ok
1 verbose cli [ '/Users/tk/.nvm/versions/node/v8.11.2/bin/node',
1 verbose cli   '/Users/tk/.nvm/versions/node/v8.11.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dist' ]
2 info using npm@6.1.0
3 info using node@v8.11.2
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle vulture-feeds@1.0.0~predist: vulture-feeds@1.0.0
6 info lifecycle vulture-feeds@1.0.0~dist: vulture-feeds@1.0.0
7 verbose lifecycle vulture-feeds@1.0.0~dist: unsafe-perm in lifecycle true
8 verbose lifecycle vulture-feeds@1.0.0~dist: PATH: /Users/tk/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/tk/Code/Git/vulture-feeds/node_modules/.bin:/Users/tk/.pyenv/shims:/Users/tk/.pyenv/bin:/Users/tk/.nvm/versions/node/v8.11.2/bin:/Users/tk/google-cloud-sdk/bin:/Users/tk/Code/git/flutter/bin:/usr/local/sbin:/usr/local/heroku/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/mongodb/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
9 verbose lifecycle vulture-feeds@1.0.0~dist: CWD: /Users/tk/Code/Git/vulture-feeds
10 silly lifecycle vulture-feeds@1.0.0~dist: Args: [ '-c', 'build' ]
11 silly lifecycle vulture-feeds@1.0.0~dist: Returned: code: 1  signal: null
12 info lifecycle vulture-feeds@1.0.0~dist: Failed to exec dist script
13 verbose stack Error: vulture-feeds@1.0.0 dist: `build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/tk/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/tk/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid vulture-feeds@1.0.0
15 verbose cwd /Users/tk/Code/Git/vulture-feeds
16 verbose Darwin 17.6.0
17 verbose argv "/Users/tk/.nvm/versions/node/v8.11.2/bin/node" "/Users/tk/.nvm/versions/node/v8.11.2/bin/npm" "run" "dist"
18 verbose node v8.11.2
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error vulture-feeds@1.0.0 dist: `build`
22 error Exit status 1
23 error Failed at the vulture-feeds@1.0.0 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Dotnaught** [comment]
Issue resolved: Removed /release-builds/ folder, which included artifacts from electron-packager. Must've had modules that interfered.
