### ISSUE TITLE
File "" not under the source directory "C:\projects\identity-wallet\node_modules"

### ISSUE THREAD

**Issue by rodrigopavezi** [electron-userland/electron-builder#3001]
* **Version**: 20.15.3

* **Target**: Windows x64

I get this following error when building my application on appveyor.

`File "" not under the source directory "C:\projects\identity-wallet\node_modules"`

See debug logs below.

```
Downloading tmp-4364-1-SHASUMS256.txt-2.0.2
[============================================>] 100.0% of 5.33 kB (5.33 kB/s)
  • spawning        command=C:\projects\identity-wallet\node_modules\7zip-bin\win\x64\7za.exe x -bd C:\Users\appveyor\AppData\Local\electron\Cache\electron-v2.0.2-win32-x64.zip -aoa -oC:\projects\identity-wallet\dist\win-unpacked
7-Zip (a) 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28
Scanning the drive for archives:
1 file, 50660794 bytes (49 MiB)
Extracting archive: C:\Users\appveyor\AppData\Local\electron\Cache\electron-v2.0.2-win32-x64.zip
--
Path = C:\Users\appveyor\AppData\Local\electron\Cache\electron-v2.0.2-win32-x64.zip
Type = zip
Physical Size = 50660794
Everything is Ok
Files: 117
Size:       121188647
Compressed: 50660794
  • exited          command=7za.exe code=0 pid=5048
  • skipped copying directory=C:\projects\identity-wallet\dist\renderer-dll reason=doesn't exist
  • spawning        command=C:\projects\identity-wallet\node_modules\app-builder-bin\win\x64\app-builder.exe node-dep-tree --dir C:\projects\identity-wallet
  • exited          command=app-builder.exe code=0 pid=4712 out={"C:\\projects\\identity-wallet\\node_modules":["@sindresorhus/is","@uirouter/angularjs","@uirouter/core","abstract-leveldown","accepts","aggregate-error","ajv","amdefine","angular","angular-animate","angular-aria","angular-local-storage","angular-localforage","angular-material","angular-messages","angular-qrcode","angular-sanitize","angular-zxcvbn","ansi-regex","ansi-styles","any-promise","aproba","are-we-there-yet","arr-diff","arr-flatten","arr-union","array-each","array-flatten","array-unique","asn1","asn1.js","assert-plus","assign-symbols","async","async-eventemitter","async-limiter","asynckit","atob","aws-sign2","aws4","babel-code-frame","babel-core","babel-generator","babel-helper-builder-binary-assignment-operator-visitor","babel-helper-call-delegate","babel-helper-define-map","babel-helper-explode-assignable-expression","babel-helper-function-name","babel-helper-get-function-arity","babel-helper-hoist-variables","babel-helper-optimise-call-expression","babel-helper-regex","babel-helper-remap-async-to-generator","babel-helper-replace-supers","babel-helpers","babel-messages","babel-plugin-check-es2015-constants","babel-plugin-syntax-async-functions","babel-plugin-syntax-exponentiation-operator","babel-plugin-syntax-trailing-function-commas","babel-plugin-transform-async-to-generator","babel-plugin-transform-es2015-arrow-functions","babel-plugin-transform-es2015-block-scoped-functions","babel-plugin-transform-es2015-block-scoping","babel-plugin-transform-es2015-classes","babel-plugin-transform-es2015-computed-properties","babel-plugin-transform-es2015-destructuring","babel-plugin-transform-es2015-duplicate-keys","babel-plugin-transform-es2015-for-of","babel-plugin-transform-es2015-function-name","babel-plugin-transform-es2015-literals","babel-plugin-transform-es2015-modules-amd","babel-plugin-transform-es2015-modules-commonjs","babel-plugin-transform-es2015-modules-systemjs","babel-plugin-transform-es2015-modules-umd","babel-plugin-transform-es2015-object-super","babel-plugin-transform-es2015-parameters","babel-plugin-transform-es2015-shorthand-properties","babel-plugin-transform-es2015-spread","babel-plugin-transform-es2015-sticky-regex","babel-plugin-transform-es2015-template-literals","babel-plugin-transform-es2015-typeof-symbol","babel-plugin-transform-es2015-unicode-regex","babel-plugin-transform-exponentiation-operator","babel-plugin-transform-regenerator","babel-plugin-transform-strict-mode","babel-preset-env","babel-register","babel-runtime","babel-template","babel-traverse","babel-types","babelify","babylon","backoff","base","base62","base64-js","bcrypt-pbkdf","bignumber.js","bindings","bip66","bl","block-stream","bluebird","bn.js","body-parser","brace-expansion","braces","brorand","browserify-aes","browserify-cipher","browserify-des","browserify-rsa","browserify-sha3","browserify-sign","buffer-alloc","buffer-alloc-unsafe","buffer-crc32","buffer-fill","buffer-from","buffer-to-arraybuffer","buffer-xor","builtin-modules","bytes","cache-base","cacheable-request","camelcase","caniuse-lite","capture-stack-trace","caseless","chalk","checkpoint-store","chownr","cipher-base","class-utils","clean-stack","cliui","clone","clone-response","co","code-point-at","collection-visit","color-convert","color-name","combined-stream","commander","component-emitter","concat-map","concat-stream","console-control-strings","content-disposition","content-type","convert-source-map","cookie","cookie-signature","copy-descriptor","core-js","core-util-is","cors","create-ecdh","create-error-class","create-hash","create-hmac","cross-fetch","crypto","crypto-browserify","dashdash","debug","decamelize","decode-uri-component","decompress","decompress-response","decompress-tar","decompress-tarbz2","decompress-targz","decompress-unzip","deep-equal","deep-extend","deferred-leveldown","define-properties","define-property","defined","delayed-stream","delegates","depd","des.js","destroy","detect-file","detect-indent","detect-libc","diffie-hellman","dns-packet","dns-socket","dom-walk","drbg.js","duplexer3","ecc-jsbn","ee-first","electron-to-chromium","elliptic","encodeurl","encoding","end-of-stream","errno","error-ex","es-abstract","es-to-primitive","es3ify","escape-html","escape-string-regexp","esmangle-evaluator","esprima-fb","esutils","etag","eth-block-tracker","eth-json-rpc-infura","eth-json-rpc-middleware","eth-lib","eth-query","eth-sig-util","eth-tx-summary","ethereum-common","ethereumjs-abi","ethereumjs-account","ethereumjs-block","ethereumjs-tx","ethereumjs-util","ethereumjs-vm","ethjs-unit","ethjs-util","eventemitter3","evp_bytestokey","expand-brackets","expand-template","expand-tilde","express","extend","extend-shallow","extglob","extsprintf","fake-merkle-patricia-tree","falafel","fast-deep-equal","fast-json-stable-stringify","fetch-ponyfill","fibers","file-type","fill-range","finalhandler","findup-sync","fined","flagged-respawn","for-each","for-in","for-own","foreach","forever-agent","form-data","forwarded","fragment-cache","fresh","from2","fs-constants","fs-extra","fs-promise","fs.realpath","fstream","function-bind","functional-red-black-tree","gauge","get-caller-file","get-stream","get-value","getpass","github-from-package","glob","global","global-modules","global-prefix","google-charts","got","graceful-fs","graceful-readlink","har-schema","har-validator","has","has-ansi","has-flag","has-symbol-support-x","has-to-string-tag-x","has-unicode","has-value","has-values","hash-base","hash.js","hmac-drbg","home-or-tmp","homedir-polyfill","hosted-git-info","http-cache-semantics","http-errors","http-https","http-signature","iconv-lite","ieee754","immediate","inflight","inherits","ini","inline-process-browser","interpret","into-stream","invariant","invert-kv","ip","ip-regex","ipaddr.js","is-absolute","is-accessor-descriptor","is-arrayish","is-buffer","is-builtin-module","is-callable","is-data-descriptor","is-date-object","is-descriptor","is-extendable","is-finite","is-fn","is-fullwidth-code-point","is-function","is-hex-prefixed","is-ip","is-natural-number","is-number","is-object","is-odd","is-online","is-plain-obj","is-plain-object","is-redirect","is-regex","is-relative","is-retry-allowed","is-stream","is-symbol","is-typedarray","is-unc-path","is-utf8","is-windows","isarray","isexe","isobject","isstream","isurl","js-sha3","js-tokens","jsbn","json-buffer","json-rpc-engine","json-rpc-error","json-rpc-random-id","json-schema","json-schema-traverse","json-stable-stringify","json-stringify-safe","json5","jsonfile","jsonify","jsprim","jstransform","keccak","keccakjs","keythereum","keyv","kind-of","klaw","knex","lcid","ledger-wallet-provider","ledgerco","level-codec","level-errors","level-iterator-stream","level-ws","levelup","lie","liftoff","load-json-file","localforage","lodash","lodash.assign","loose-envify","lowercase-keys","ltgt","make-dir","make-iterator","map-cache","map-visit","md5.js","media-typer","memdown","memorystream","merge-descriptors","merkle-patricia-tree","methods","micromatch","miller-rabin","mime-db","mime-types","mimic-response","min-document","minimalistic-assert","minimalistic-crypto-utils","minimatch","minimist","mixin-deep","mkdirp","mkdirp-promise","mock-fs","mout","ms","mv","mz","nan","nano-json-stream-parser","nanomatch","ncp","negotiator","node-abi","node-fetch","node-hid","noop-logger","normalize-package-data","npmlog","number-is-nan","number-to-bn","oauth-sign","object-assign","object-copy","object-inspect","object-keys","object-visit","object.defaults","object.map","object.pick","oboe","on-finished","once","os-homedir","os-locale","os-tmpdir","p-any","p-cancelable","p-finally","p-is-promise","p-some","p-timeout","parse-asn1","parse-filepath","parse-headers","parse-json","parse-passwd","parseurl","pascalcase","path-is-absolute","path-parse","path-root","path-root-regex","path-to-regexp","pbkdf2","pend","performance-now","pg-connection-string","pify","pinkie","pinkie-promise","posix-character-classes","prebuild-install","precond","prepend-http","private","process-nextick-args","promise-timeout","promise-to-callback","proxy-addr","prr","public-encrypt","public-ip","pump","punycode","qrcode-generator","qs","query-string","randombytes","randomfill","randomhex","range-parser","raw-body","rc","read-pkg","read-pkg-up","readable-stream","rechoir","regenerate","regenerator-runtime","regex-not","regjsgen","regjsparser","repeat-element","repeat-string","repeating","request","require-directory","require-from-string","require-main-filename","resolve","resolve-dir","resolve-url","responselike","resumer","ret","rimraf","ripemd160","rlp","rustbn.js","safe-buffer","safe-regex","safer-buffer","scrypt","scrypt.js","scryptsy","secp256k1","seek-bzip","semaphore","semver","send","serve-static","servify","set-blocking","set-immediate-shim","set-value","setimmediate","setprototypeof","sha.js","sha3","signal-exit","simple-concat","simple-get","sjcl","slash","snapdragon","snapdragon-node","snapdragon-util","solc","source-list-map","source-map","source-map-resolve","source-map-support","source-map-url","spdx-correct","spdx-exceptions","spdx-expression-parse","spdx-license-ids","split-string","sqlite3","sshpk","static-extend","statuses","strict-uri-encode","string-width","string.prototype.trim","string_decoder","strip-ansi","strip-bom","strip-dirs","strip-hex-prefix","strip-json-comments","supports-color","swarm-js","tape","tar","tar-fs","tar-stream","tar.gz","tarn","thenify","thenify-all","through","through2","tildify","timed-out","to-buffer","to-object-path","to-regex","to-regex-range","tough-cookie","treeify","trim","trim-right","tunnel-agent","tweetnacl","type-is","typedarray","typedarray-to-buffer","u2f-api","ultron","unbzip2-stream","unc-path-regex","underscore","union-value","universalify","unpipe","unreachable-branch-transform","unset-value","unzip-response","urix","url-parse-lax","url-set-query","url-to-options","use","utf8","util-deprecate","utils-merge","uuid","validate-npm-package-license","vary","verror","web3","web3-bzz","web3-core","web3-core-helpers","web3-core-method","web3-core-promievent","web3-core-requestmanager","web3-core-subscriptions","web3-eth","web3-eth-abi","web3-eth-accounts","web3-eth-contract","web3-eth-iban","web3-eth-personal","web3-net","web3-provider-engine","web3-providers-http","web3-providers-ipc","web3-providers-ws","web3-shh","web3-utils","webpack-sources","websocket","whatwg-fetch","which","which-module","which-pm-runs","wide-align","window-size","wrap-ansi","wrappy","ws","xhr","xhr-request","xhr-request-promise","xhr2","xtend","y18n","yaeti","zxcvbn"],"C:\\projects\\identity-wallet\\node_modules\\aggregate-error\\node_modules":["indent-string"],"C:\\projects\\identity-wallet\\node_modules\\babel-code-frame\\node_modules":["ansi-styles","chalk","supports-color"],"C:\\projects\\identity-wallet\\node_modules\\babel-generator\\node_modules":["jsesc"],"C:\\projects\\identity-wallet\\node_modules\\babel-plugin-transform-es2015-unicode-regex\\node_modules":["regexpu-core"],"C:\\projects\\identity-wallet\\node_modules\\babel-plugin-transform-regenerator\\node_modules":["regenerator-transform"],"C:\\projects\\identity-wallet\\node_modules\\babel-preset-env\\node_modules":["browserslist"],"C:\\projects\\identity-wallet\\node_modules\\babel-register\\node_modules":["source-map-support"],"C:\\projects\\identity-wallet\\node_modules\\babel-traverse\\node_modules":["globals"],"C:\\projects\\identity-wallet\\node_modules\\babel-types\\node_modules":["to-fast-properties"],"C:\\projects\\identity-wallet\\node_modules\\base\\node_modules":["define-property"],"C:\\projects\\identity-wallet\\node_modules\\brace-expansion\\node_modules":["balanced-match"],"C:\\projects\\identity-wallet\\node_modules\\cacheable-request\\node_modules":["lowercase-keys","normalize-url","prepend-http","sort-keys"],"C:\\projects\\identity-wallet\\node_modules\\cliui\\node_modules":["is-fullwidth-code-point","string-width"],"C:\\projects\\identity-wallet\\node_modules\\decompress-tarbz2\\node_modules":["file-type"],"C:\\projects\\identity-wallet\\node_modules\\decompress-unzip\\node_modules":["fd-slicer","file-type","get-stream","yauzl"],"C:\\projects\\identity-wallet\\node_modules\\deferred-leveldown\\node_modules":["abstract-leveldown"],"C:\\projects\\identity-wallet\\node_modules\\define-property\\node_modules":["is-accessor-descriptor","is-data-descriptor","is-descriptor","kind-of"],"C:\\projects\\identity-wallet\\node_modules\\eth-tx-summary\\node_modules":["eth-block-tracker","ethereumjs-vm","web3-provider-engine"],"C:\\projects\\identity-wallet\\node_modules\\ethereumjs-tx\\node_modules":["ethereum-common"],"C:\\projects\\identity-wallet\\node_modules\\ethjs-unit\\node_modules":["bn.js"],"C:\\projects\\identity-wallet\\node_modules\\express\\node_modules":["body-parser","iconv-lite","qs","raw-body","safe-buffer"],"C:\\projects\\identity-wallet\\node_modules\\extglob\\node_modules":["define-property"],"C:\\projects\\identity-wallet\\node_modules\\falafel\\node_modules":["acorn","isarray"],"C:\\projects\\identity-wallet\\node_modules\\fetch-ponyfill\\node_modules":["node-fetch"],"C:\\projects\\identity-wallet\\node_modules\\findup-sync\\node_modules":["is-extglob","is-glob"],"C:\\projects\\identity-wallet\\node_modules\\fs-promise\\node_modules":["fs-extra","jsonfile"],"C:\\projects\\identity-wallet\\node_modules\\gauge\\node_modules":["is-fullwidth-code-point","string-width"],"C:\\projects\\identity-wallet\\node_modules\\global\\node_modules":["process"],"C:\\projects\\identity-wallet\\node_modules\\has-values\\node_modules":["kind-of"],"C:\\projects\\identity-wallet\\node_modules\\http-errors\\node_modules":["statuses"],"C:\\projects\\identity-wallet\\node_modules\\inline-process-browser\\node_modules":["isarray","readable-stream","through2"],"C:\\projects\\identity-wallet\\node_modules\\is-accessor-descriptor\\node_modules":["kind-of"],"C:\\projects\\identity-wallet\\node_modules\\is-data-descriptor\\node_modules":["kind-of"],"C:\\projects\\identity-wallet\\node_modules\\is-descriptor\\node_modules":["kind-of"],"C:\\projects\\identity-wallet\\node_modules\\is-odd\\node_modules":["is-number"],"C:\\projects\\identity-wallet\\node_modules\\is-online\\node_modules":["got"],"C:\\projects\\identity-wallet\\node_modules\\jstransform\\node_modules":["source-map"],"C:\\projects\\identity-wallet\\node_modules\\keythereum\\node_modules":["sjcl","uuid"],"C:\\projects\\identity-wallet\\node_modules\\knex\\node_modules":["debug","v8flags"],"C:\\projects\\identity-wallet\\node_modules\\ledger-wallet-provider\\node_modules":["async-eventemitter","eth-block-tracker","web3-provider-engine"],"C:\\projects\\identity-wallet\\node_modules\\level-iterator-stream\\node_modules":["isarray","level-errors","readable-stream"],"C:\\projects\\identity-wallet\\node_modules\\level-ws\\node_modules":["isarray","object-keys","readable-stream","xtend"],"C:\\projects\\identity-wallet\\node_modules\\levelup\\node_modules":["semver"],"C:\\projects\\identity-wallet\\node_modules\\lie\\node_modules":["immediate"],"C:\\projects\\identity-wallet\\node_modules\\make-dir\\node_modules":["pify"],"C:\\projects\\identity-wallet\\node_modules\\make-iterator\\node_modules":["kind-of"],"C:\\projects\\identity-wallet\\node_modules\\merkle-patricia-tree\\node_modules":["async"],"C:\\projects\\identity-wallet\\node_modules\\micromatch\\node_modules":["define-property","extend-shallow","is-extendable","kind-of"],"C:\\projects\\identity-wallet\\node_modules\\mixin-deep\\node_modules":["is-extendable"],"C:\\projects\\identity-wallet\\node_modules\\mkdirp\\node_modules":["minimist"],"C:\\projects\\identity-wallet\\node_modules\\mv\\node_modules":["glob","rimraf"],"C:\\projects\\identity-wallet\\node_modules\\nanomatch\\node_modules":["define-property","extend-shallow","is-extendable","kind-of"],"C:\\projects\\identity-wallet\\node_modules\\number-to-bn\\node_modules":["bn.js"],"C:\\projects\\identity-wallet\\node_modules\\object.defaults\\node_modules":["array-slice"],"C:\\projects\\identity-wallet\\node_modules\\public-ip\\node_modules":["got","p-cancelable","p-timeout","pify","prepend-http","url-parse-lax"],"C:\\projects\\identity-wallet\\node_modules\\read-pkg\\node_modules":["path-type"],"C:\\projects\\identity-wallet\\node_modules\\read-pkg-up\\node_modules":["find-up","path-exists"],"C:\\projects\\identity-wallet\\node_modules\\readable-stream\\node_modules":["string_decoder"],"C:\\projects\\identity-wallet\\node_modules\\regex-not\\node_modules":["extend-shallow","is-extendable"],"C:\\projects\\identity-wallet\\node_modules\\regjsparser\\node_modules":["jsesc"],"C:\\projects\\identity-wallet\\node_modules\\seek-bzip\\node_modules":["commander"],"C:\\projects\\identity-wallet\\node_modules\\send\\node_modules":["mime"],"C:\\projects\\identity-wallet\\node_modules\\snapdragon-node\\node_modules":["define-property"],"C:\\projects\\identity-wallet\\node_modules\\solc\\node_modules":["fs-extra","is-fullwidth-code-point","jsonfile","string-width","yargs","yargs-parser"],"C:\\projects\\identity-wallet\\node_modules\\source-map-support\\node_modules":["source-map"],"C:\\projects\\identity-wallet\\node_modules\\split-string\\node_modules":["extend-shallow","is-extendable"],"C:\\projects\\identity-wallet\\node_modules\\sqlite3\\node_modules":["abbrev","ansi-regex","aproba","are-we-there-yet","balanced-match","brace-expansion","chownr","code-point-at","concat-map","console-control-strings","core-util-is","debug","deep-extend","delegates","detect-libc","fs-minipass","fs.realpath","gauge","glob","has-unicode","iconv-lite","ignore-walk","inflight","inherits","ini","is-fullwidth-code-point","isarray","minimatch","minimist","minipass","minizlib","mkdirp","ms","nan","needle","node-pre-gyp","nopt","npm-bundled","npm-packlist","npmlog","number-is-nan","object-assign","once","os-homedir","os-tmpdir","osenv","path-is-absolute","process-nextick-args","rc","readable-stream","rimraf","safe-buffer","sax","semver","set-blocking","signal-exit","string-width","string_decoder","strip-ansi","strip-json-comments","tar","util-deprecate","wide-align","wrappy","yallist"],"C:\\projects\\identity-wallet\\node_modules\\string-width\\node_modules":["ansi-regex","strip-ansi"],"C:\\projects\\identity-wallet\\node_modules\\swarm-js\\node_modules":["buffer","fs-extra","jsonfile"],"C:\\projects\\identity-wallet\\node_modules\\tape\\node_modules":["resolve"],"C:\\projects\\identity-wallet\\node_modules\\tar-fs\\node_modules":["pump"],"C:\\projects\\identity-wallet\\node_modules\\tar.gz\\node_modules":["bluebird"],"C:\\projects\\identity-wallet\\node_modules\\to-regex\\node_modules":["define-property","extend-shallow","is-extendable"],"C:\\projects\\identity-wallet\\node_modules\\unbzip2-stream\\node_modules":["base64-js","buffer"],"C:\\projects\\identity-wallet\\node_modules\\union-value\\node_modules":["set-value"],"C:\\projects\\identity-wallet\\node_modules\\unreachable-branch-transform\\node_modules":["ast-types","esprima-fb","isarray","readable-stream","recast","through2"],"C:\\projects\\identity-wallet\\node_modules\\unset-value\\node_modules":["has-value","has-values"],"C:\\projects\\identity-wallet\\node_modules\\use\\node_modules":["kind-of"],"C:\\projects\\identity-wallet\\node_modules\\verror\\node_modules":["extsprintf"],"C:\\projects\\identity-wallet\\node_modules\\web3-eth-abi\\node_modules":["bn.js"],"C:\\projects\\identity-wallet\\node_modules\\web3-eth-accounts\\node_modules":["eth-lib","uuid"],"C:\\projects\\identity-wallet\\node_modules\\web3-eth-iban\\node_modules":["bn.js"],"C:\\projects\\identity-wallet\\node_modules\\web3-provider-engine\\node_modules":["ws"],"C:\\projects\\identity-wallet\\node_modules\\web3-utils\\node_modules":["bn.js"],"C:\\projects\\identity-wallet\\node_modules\\webpack-sources\\node_modules":["source-map"],"C:\\projects\\identity-wallet\\node_modules\\wrap-ansi\\node_modules":["is-fullwidth-code-point","string-width"],"C:\\projects\\identity-wallet\\node_modules\\define-property\\node_modules\\is-accessor-descriptor\\node_modules":["kind-of"],"C:\\projects\\identity-wallet\\node_modules\\define-property\\node_modules\\is-data-descriptor\\node_modules":["kind-of"],"C:\\projects\\identity-wallet\\node_modules\\eth-tx-summary\\node_modules\\eth-block-tracker\\node_modules":["async-eventemitter"],"C:\\projects\\identity-wallet\\node_modules\\eth-tx-summary\\node_modules\\web3-provider-engine\\node_modules":["ethereumjs-vm"],"C:\\projects\\identity-wallet\\node_modules\\express\\node_modules\\raw-body\\node_modules":["depd","http-errors","setprototypeof","statuses"],"C:\\projects\\identity-wallet\\node_modules\\sqlite3\\node_modules\\rc\\node_modules":["minimist"],"C:\\projects\\identity-wallet\\node_modules\\unset-value\\node_modules\\has-value\\node_modules":["isobject"]}
  • async task error error=File "" not under the source directory "C:\projects\identity-wallet\node_modules"
Error: File "" not under the source directory "C:\projects\identity-wallet\node_modules"
    at getDestinationPath (C:\projects\identity-wallet\node_modules\electron-builder-lib\src\util\appFileCopier.ts:26:15)
    at C:\projects\identity-wallet\node_modules\electron-builder-lib\src\asar\unpackDetector.ts:71:79
    at Generator.next (<anonymous>)
From previous event:
    at detectUnpackedDirs (C:\projects\identity-wallet\node_modules\electron-builder-lib\out\asar\unpackDetector.js:195:17)
    at C:\projects\identity-wallet\node_modules\electron-builder-lib\src\asar\asarUtil.ts:47:13
    at Generator.next (<anonymous>)
From previous event:
    at AsarPackager.createPackageFromFiles (C:\projects\identity-wallet\node_modules\electron-builder-lib\src\asar\asarUtil.ts:39:84)
    at C:\projects\identity-wallet\node_modules\electron-builder-lib\src\asar\asarUtil.ts:34:52
    at Generator.next (<anonymous>)
From previous event:
    at AsarPackager.pack (C:\projects\identity-wallet\node_modules\electron-builder-lib\src\asar\asarUtil.ts:26:79)
    at taskManager.addTask._computeFileSets.then.fileSets (C:\projects\identity-wallet\node_modules\electron-builder-lib\src\platformPackager.ts:281:136)
From previous event:
    at WinPackager.copyAppFiles (C:\projects\identity-wallet\node_modules\electron-builder-lib\src\platformPackager.ts:281:10)
    at C:\projects\identity-wallet\node_modules\electron-builder-lib\src\platformPackager.ts:214:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at WinPackager.doPack (C:\projects\identity-wallet\node_modules\electron-builder-lib\src\platformPackager.ts:162:151)
    at C:\projects\identity-wallet\node_modules\electron-builder-lib\src\platformPackager.ts:117:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\projects\identity-wallet\node_modules\electron-builder-lib\src\platformPackager.ts:115:95)
    at C:\projects\identity-wallet\node_modules\electron-builder-lib\src\packager.ts:373:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\projects\identity-wallet\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\projects\identity-wallet\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:171:5)
From previous event:
    at Packager.doBuild (C:\projects\identity-wallet\node_modules\electron-builder-lib\src\packager.ts:341:39)
    at C:\projects\identity-wallet\node_modules\electron-builder-lib\src\packager.ts:317:52
From previous event:
    at Packager._build (C:\projects\identity-wallet\node_modules\electron-builder-lib\src\packager.ts:294:133)
    at C:\projects\identity-wallet\node_modules\electron-builder-lib\src\packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at Packager.build (C:\projects\identity-wallet\node_modules\electron-builder-lib\src\packager.ts:248:14)
    at C:\projects\identity-wallet\node_modules\electron-builder-lib\src\index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\projects\identity-wallet\node_modules\electron-builder-lib\out\index.js:220:17)
    at build (C:\projects\identity-wallet\node_modules\electron-builder\src\builder.ts:234:10)
    at then (C:\projects\identity-wallet\node_modules\electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by ymmuse** [comment]
@rodrigopavezi See #3002

**Comment by rodrigopavezi** [comment]
@ymmuse awesome. cheers
