### ISSUE TITLE
Error: Offset is out of bounds

### ISSUE THREAD

**Issue by skotturi** [electron-userland/electron-builder#302]
Received the following when trying to build dist:

```
activity-frontend $ npm run dist

> activity-frontend@1.1.1 dist /Users/santekotturi/Developer/digitalocean/test-env/activity-frontend
> build

Skipping app dependencies installation because dev and app dependencies are not separated
Packaging app for platform darwin x64 using electron v0.37.5
Signing app
Creating DMG
Creating ZIP for Squirrel.Mac
Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:582:11)
    at /Users/santekotturi/Developer/digitalocean/test-env/activity-frontend/node_modules/appdmg/node_modules/image-size/lib/index.js:45:8
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node4-lts/4.4.2/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! activity-frontend@1.1.1 dist: `build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the activity-frontend@1.1.1 dist script 'build'.
```

requested issue info:

dev-level package.json
```
{
    "name": "activity-frontend",
    "version": "1.1.1",
    "author": "Sante Kotturi",
    "description": "activity-frontend: An Ionic project",
    "dependencies": {
        "gulp": "^3.5.6",
        "gulp-concat": "^2.2.0",
        "gulp-minify-css": "^0.3.0",
        "gulp-rename": "^1.2.0",
        "gulp-sass": "^2.0.4"
    },
    "devDependencies": {
        "bower": "^1.3.3",
        "electron-builder": "^3.5.0",
        "electron-prebuilt": "^0.37.5",
        "gulp-util": "^2.2.14",
        "shelljs": "^0.3.0"
    },
    "scripts": {
        "electron": "electron www",
        "postinstall": "install-app-deps",
        "pack": "build",
        "dist": "build"
    },
    "build": {
        "osx": {
            "contents": [
                {
                    "x": 410,
                    "y": 220,
                    "type": "link",
                    "path": "/Applications"
                },
                {
                    "x": 130,
                    "y": 220,
                    "type": "file"
                }
            ]
        }
    }
}
```

app level package.json:
```
{
  "name"    : "activity-uploader",
  "version" : "0.0.1",
  "main"    : "main.js"
}
```

no config.json (not using ts).

node = 4.4.2
npm = 3.8.6

thanks in advance!

**Comment by develar** [comment]
Do you have `build/background.png` and `build/icon.icns`?

**Comment by skotturi** [comment]
I did but my icns was corrupt/broken I think. I remade it and reran build dist, its working now. Thanks for the lead!
