### ISSUE TITLE
Yarn Workspaces Error: Cannot find parent config file: electron-webpack/electron-builder.yml

### ISSUE THREAD

**Issue by amaurymartiny** [electron-userland/electron-builder#3029]
* **Version**: 20.15.1

* **Target**: macos

Using yarn workspaces, I cannot build binaries with electron-builder.

```
> crale-electron@0.1.0 package /Users/amaurymartiny/Workspace/cra-lerna-electron/packages/crale-electron
> electron-builder

  • electron-builder version=20.15.1
  • loaded configuration file=/Users/amaurymartiny/Workspace/cra-lerna-electron/packages/crale-electron/electron-builder.json
Error: Cannot find parent config file: electron-webpack/electron-builder.yml
    at loadParentConfig (/Users/amaurymartiny/Workspace/cra-lerna-electron/node_modules/read-config-file/src/main.ts:104:11)
From previous event:
    at getConfig (/Users/amaurymartiny/Workspace/cra-lerna-electron/node_modules/electron-builder-lib/out/util/config.js:182:17)
    at /Users/amaurymartiny/Workspace/cra-lerna-electron/node_modules/electron-builder-lib/src/packager.ts:266:33
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (/Users/amaurymartiny/Workspace/cra-lerna-electron/node_modules/electron-builder-lib/src/packager.ts:248:14)
    at /Users/amaurymartiny/Workspace/cra-lerna-electron/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/amaurymartiny/Workspace/cra-lerna-electron/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Users/amaurymartiny/Workspace/cra-lerna-electron/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/Users/amaurymartiny/Workspace/cra-lerna-electron/node_modules/electron-builder/src/cli/cli.ts:46:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crale-electron@0.1.0 package: `electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the crale-electron@0.1.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/amaurymartiny/.npm/_logs/2018-06-22T14_44_41_123Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here is the yarn workspaces config in my root package.json

```json
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/electron-webpack",
      "**/electron-webpack/**"
    ]
  },
```

Note: if I add nohoist ` "**/electron-builder"` and ` "**/electron-builder/**"`, then the above error disappears. But the modules are then not copied into the asar.

#### Sample project

Clone https://github.com/amaurymartiny/cra-lerna-electron, and run `yarn package`.

#### Note

I need to add `electron-webpack` to nohoist because of https://github.com/electron-userland/electron-webpack/issues/56.

#### Hack fix

Installing another copy of `electron-webpack` makes things work: `yarn add electron-webpack --dev -W` inside the root folder, but then there are two copies of electron-wepback.

**Comment by amaurymartiny** [comment]
`rm yarn.lock && yarn install` made it work.
