### ISSUE TITLE
Cannot build for deb in Windows Environment

### ISSUE THREAD

**Issue by MD-AZMAL** [electron-userland/electron-builder#3030]
* **Version**:  20.15.1

* **Target**:  Linux

F:\SDK's and IDE's\my program\native\Sharp-Tune>build --linux -p never
  • electron-builder version=20.15.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist\electron-builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=2.0.2 appOutDir=dist\linux-unpacked
  • scheduling remote build target=deb arch=x64
(node:4800) ExperimentalWarning: The http2 module is an experimental API.
  • compressing and uploading to remote builder
  • uploaded to remote builder time=0s 17ms
Error: spawn C:\Users\HP\AppData\Local\electron-builder\cache\zstd\zstd-1.3.4-linux-x64\zstd.exe ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at RemoteBuildManager.doBuild (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuildManager.ts:96:12)
    at C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuildManager.ts:72:12
From previous event:
    at RemoteBuildManager.build (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuildManager.ts:57:12)
    at C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:73:37
    at Generator.next (<anonymous>)
From previous event:
    at RemoteBuilder._build (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:59:83)
    at _bluebirdLst.default.mapSeries.arch (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:54:19)
From previous event:
    at RemoteBuilder.build (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:53:28)
    at C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\linuxPackager.ts:99:30
From previous event:
    at RemoteTarget.finishBuild (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\linuxPackager.ts:97:20)
    at C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:381:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.doBuild (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:341:39)
    at C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:317:52
    at Generator.next (<anonymous>)
    at C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:294:133)
    at C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.ts:248:14)
    at C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\src\index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\node_modules\electron-builder-lib\out\index.js:220:17)
    at build (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:234:10)
    at then (C:\Users\HP\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
WARNING: The system cannot find the path specified.
C:\Users\HP\AppData\Local\Temp\temp-dir-PCddbE\remote-build-metadata-2\info.json

**Comment by MD-AZMAL** [comment]
I dont get what this means

Error: spawn C:\Users\HP\AppData\Local\electron-builder\cache\zstd\zstd-1.3.4-linux-x64\zstd.exe ENOENT

**Comment by MD-AZMAL** [comment]
what shame they call this an opensource community and nobody there to help

**Comment by ReadingCommando** [comment]
help

**Comment by ReadingCommando** [comment]
you fix it ?

**Comment by ReadingCommando** [comment]
i have the same error

**Comment by GammaGames** [comment]
It was only open for a day, why did you close it? I'm having the same issue

**Comment by redplane** [comment]
Same to me.

**Comment by redplane** [comment]
Seems like there is a temporary solution for this issue.
I went to [zstd site](https://github.com/facebook/zstd/releases) and downloaded **zstd-v1.3.4-win64.zip** (because my windows is 64 bit)

After having downloaded the file, I extracted it and copy its content to  `%AppData%\Local\electron-builder\cache\zstd\zstd-1.3.4-linux-x64`

When I ran `build` command again, it worked. 

Hope this helps.

**Comment by redplane** [comment]
I think it can't be closed. IMO, `electron-builder` has to download and  cache the zstd automatically.

**Comment by develar** [comment]
@redplane It is fixed, see my commits :) Will be released in minutes.

**Comment by develar** [comment]
Please try 20.19.1

**Comment by develar** [comment]
Service not working for now, will be fixed in 8 hours.

**Comment by develar** [comment]
Service active now.

**Comment by GammaGames** [comment]
This issue is fixed, but now I have the problem of it being uploaded to the remote builder (from windows) and that is all:

![image](https://user-images.githubusercontent.com/7832163/42172068-2c142578-7dd8-11e8-9f4e-a8b833376973.png)

It's been stuck like this for ~15 minutes
