### ISSUE TITLE
Build fails with Error: EEXIST: file already exists (20.16.0)

### ISSUE THREAD

**Issue by adlk** [electron-userland/electron-builder#3039]
* **Version**: 20.16.0

* **Target**: dmg, nsis (32 & 64bit)

Since 20.15.2 builds are failing with the following issue:
```
  • electron-builder version=20.16.0
  • publishing will be skipped reason=current build is a part of pull request solution=
                                 set env PUBLISH_FOR_PULL_REQUEST to true to force code signing
                                 There are serious security concerns with PUBLISH_FOR_PULL_REQUEST=true (see the  CircleCI documentation (https://circleci.com/docs/1.0/fork-pr-builds/) for details)
                                 If you have SSH keys, sensitive env vars or AWS credentials stored in your project settings and untrusted forks can make pull requests against your repo, then this option isn't for you.
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=1.7.15 appOutDir=release/win-unpacked
  • asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available
Error: EEXIST: file already exists, link '/Users/distiller/wp-desktop/node_modules/acorn-globals/node_modules/acorn/AUTHORS' -> '/Users/distiller/wp-desktop/release/win-unpacked/resources/app/node_modules/acorn/AUTHORS'
    at copyOrLinkFile (/Users/distiller/wp-desktop/node_modules/builder-util/src/fs.ts:175:12)
    at /Users/distiller/wp-desktop/node_modules/builder-util/src/fs.ts:243:11
    at Generator.next (<anonymous>)
From previous event:
    at FileCopier.copy (/Users/distiller/wp-desktop/node_modules/builder-util/src/fs.ts:228:64)
    at copyFileOrData (/Users/distiller/wp-desktop/node_modules/electron-builder-lib/src/util/appFileCopier.ts:92:23)
    at taskManager.addTask.transformContentIfNeed.then.it (/Users/distiller/wp-desktop/node_modules/electron-builder-lib/src/util/appFileCopier.ts:76:74)
```

Please just let me know if you need more infos.

**Comment by develar** [comment]
Is it possible to provide project?

**Comment by adlk** [comment]
@develar sure, https://github.com/Automattic/wp-desktop
the PR in question is `feature/spell-checker` currently rolled back to 20.8.2

**Comment by adlk** [comment]
Works like a charm. Thank you so much! 👍
