### ISSUE TITLE
Error: Cannot find module 'stream-json/utils/Stream JsonObject' at Function.Module._resolveFilename electron builder while packaging for linux

### ISSUE THREAD

**Issue by sruthivarghese15** [electron-userland/electron-builder#3042]
Version: 20.16.0

Target: deb 

The error shows:

`Error: Cannot find module 'stream-json/utils/StreamJsonObjects'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at RemoteBuildManager.doBuild (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuildManager.ts:95:31)
    at E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuildManager.ts:72:12
    at RemoteBuildManager.build (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuildManager.ts:57:12)
    at E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:73:37
    at Generator.next (<anonymous>)
From previous event:
    at RemoteBuilder._build (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:59:83)
    at _bluebirdLst.default.mapSeries.arch (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:54:19)
From previous event:
    at RemoteBuilder.build (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\remoteBuilder\RemoteBuilder.ts:53:28)
    at E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\linuxPackager.ts:99:30
From previous event:
    at RemoteTarget.finishBuild (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\linuxPackager.ts:97:20)
    at E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\packager.ts:387:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.doBuild (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\packager.ts:347:39)
    at E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\packager.ts:323:52
    at Generator.next (<anonymous>)
    at E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\graceful-fs\graceful-fs.js:99:16
    at E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\packager.ts:300:133)
    at E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\packager.ts:296:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\packager.ts:254:14)
    at E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\src\index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder-lib\out\index.js:220:17)
    at build (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder\src\builder.ts:234:10)
    at then (E:\Ankom-AE\Ankom_AE\Technical\Sources\Software\ANKOM-AE-HMI\node_modules\electron-builder\src\cli\cli.ts:46:19)`

My package.json
`{
  "name": "ankom-ae-hmi",
  "version": "0.0.0",
  "license": "MIT",
  "main": "main.js",
  "homepage": ".",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "electron": "electron .",
    "electron-build": "ng build --prod && electron .",
    "pkg:linux": "electron-packager . project_name --platform=linux --arch=x64 --overwrite --asar=true --out=dist --ignore=dist",
    "pkg:win": "electron-packager . \"project_name\" --platform=win32 --arch=x64 --overwrite --asar=true --out=dist --version-string.CompanyName=\"client\" --version-string.ProductName=\"project_name\" --version-string.FileDescription=\"project_name\" --version-string.OriginalFilename=\"project_name\" --ignore=dist",
    "builder:linux": "electron-builder dist/project_name-linux-x64 --platform=linux --x64 --config=config.json",
    "dist": "build --linux --x64 --config=config.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.1",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@types/gsap": "^1.19.2",
    "@types/hammerjs": "^2.0.35",
    "angular2-carousel": "^1.0.14",
    "bootstrap": "4.0.0-beta.2",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "ng2-dragula": "^1.5.0",
    "ngx-bootstrap": "^3.0.0",
    "popper.js": "^1.14.3",
    "roboto-fontface": "^0.9.0",
    "rxjs": "^5.5.6",
    "stream-json": "^1.0.2",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.7",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "electron": "^2.0.1",
    "electron-builder": "^20.16.0",
    "electron-packager": "^12.0.2",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
`

config.json:

`{
    "linux" : {
      "target" : "deb",
      "description" : "description",
      "executableName" : "project_name",
      "maintainer": "Developer <developer@gmail.com>"
    }
  }`

**Comment by sruthivarghese15** [comment]
It's fixed?

**Comment by develar** [comment]
@sruthivarghese15 Please try 20.17.0

**Comment by GammaGames** [comment]
Thank you, I don't have the issue anymore in 20.17.2! Now I have #3042 instead ¯\\\_(ツ)_/¯
