### ISSUE TITLE
Error: Unresolved node modules: webpack when building.

### ISSUE THREAD

**Issue by Glinkis** [electron-userland/electron-builder#3048]
Version:
* **20.16.4**: 

Target:
* **dmg**: 

When running `electron-builder --dir` I get this error.

[Project repo for reproducing](https://github.com/Glinkis/reverse-image-finder) (check failed build for details)

```
Error: Unresolved node modules: webpack
    at /Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/util/packageDependencies.ts:112:21
From previous event:
    at Collector.resolveUnresolvedHoisted (/Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/util/packageDependencies.ts:88:81)
    at /Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/util/packageDependencies.ts:83:18
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Collector.collect (/Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/util/packageDependencies.ts:76:28)
    at /Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/util/packageDependencies.ts:47:44
    at Generator.next (<anonymous>)
From previous event:
    at getProductionDependencies (/Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/out/util/packageDependencies.js:130:17)
    at Lazy.<anonymous> (/Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/packager.ts:115:24)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (/Projects/Webb/reverse-image-finder/node_modules/lazy-val/src/main.ts:18:23)
    at /Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/util/yarn.ts:121:81
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (/Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/out/util/yarn.js:234:18)
    at /Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/util/yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at installOrRebuild (/Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/out/util/yarn.js:68:17)
    at /Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/packager.ts:460:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/packager.ts:421:70)
    at /Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/packager.ts:371:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/packager.ts:347:39)
    at /Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/packager.ts:323:52
    at Generator.next (<anonymous>)
    at /Projects/Webb/reverse-image-finder/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Projects/Webb/reverse-image-finder/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/packager.ts:300:133)
    at /Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/packager.ts:296:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/packager.ts:254:14)
    at /Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Projects/Webb/reverse-image-finder/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Projects/Webb/reverse-image-finder/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/Projects/Webb/reverse-image-finder/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
```

**Comment by 526142399** [comment]
Do you have a solution for it?

**Comment by Glinkis** [comment]
Unfortunately, no.

**Comment by theshekhawat** [comment]
I am still getting the same issue. Electron version that I am using is 

        "electron": "^8.1.1",
        "electron-builder": "^20.44.4",
        "electron-rebuild": "^1.11.0",

Anyone got resolution to this issue ?
