### ISSUE TITLE
Step "compiling using electron-compile" fails after upgrading from 20.15 to 20.16 and up

### ISSUE THREAD

**Issue by rvanmil** [electron-userland/electron-builder#3050]
* **Version**: 20.17.0

* **Target**: all

The build was working correctly, but after upgrading electron-builder to 20.16 or 20.17 the build fails with the details below. Nothing else has changed.

```
  compiling using electron-compile
  ⨯ nodeModules.Dependency.Dependencies: ReadMapCB: expect { or n, but found [, error found in #10 byte of ...|ncies" : [],
	"repos|..., bigger context ...|://www.josscrowcroft.com)"
	],
	"dependencies" : [],
	"repository" : {"type": "git", "url": "git://g|...
github.com/develar/app-builder/pkg/nodeModules.readPackageJson
	/Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:302
github.com/develar/app-builder/pkg/nodeModules.(*Collector).resolveDependency
	/Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:226
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
	/Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:177
github.com/develar/app-builder/pkg/nodeModules.ConfigureCommand.func1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:30
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:60
runtime.main
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Error: /Users/rvanmil/myelectronapp/node_modules/app-builder-bin/mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/rvanmil/myelectronapp/node_modules/builder-util/src/util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at copyNodeModules (/Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/out/util/AppFileCopierHelper.js:342:18)
    at /Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/platformPackager.ts:261:42
    at Generator.next (<anonymous>)
From previous event:
    at then (/Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/platformPackager.ts:257:14)
From previous event:
    at _computeFileSets (/Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/platformPackager.ts:258:10)
    at MacPackager.copyAppFiles (/Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/platformPackager.ts:280:27)
    at /Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/platformPackager.ts:214:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at MacPackager.doPack (/Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/platformPackager.ts:162:151)
    at /Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/macPackager.ts:87:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/macPackager.ts:79:95)
    at /Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/packager.ts:379:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/rvanmil/myelectronapp/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/rvanmil/myelectronapp/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/packager.ts:347:39)
    at /Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/packager.ts:323:52
    at Generator.next (<anonymous>)
    at /Users/rvanmil/myelectronapp/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/rvanmil/myelectronapp/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/packager.ts:300:133)
    at /Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/packager.ts:296:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (/Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/packager.ts:254:14)
    at /Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/rvanmil/myelectronapp/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Users/rvanmil/myelectronapp/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/Users/rvanmil/myelectronapp/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
error Command failed with exit code 1.
```

**Comment by rvanmil** [comment]
I found the source of the problem. My project contains a dependency to a module (https://www.npmjs.com/package/accounting) which specifies `"dependencies" : [],` in its package.json. Which is invalid because dependencies must be an object, not an array.
I'll contact the module author to fix this.

**Comment by sintloer** [comment]
@rvanmil, thanks for explanation! :)

**Comment by xct24** [comment]
@rvanmil may i ask how did you locate the module that was having the issue? i met the same issue but i didn't include that dependency. Thx

**Comment by rvanmil** [comment]
> @rvanmil may i ask how did you locate the module that was having the issue? i met the same issue but i didn't include that dependency. Thx

The error mentioned the very specific `www.josscrowcroft.com` string, so I searched for that inside the node_modules directory.

**Comment by xct24** [comment]
> > @rvanmil may i ask how did you locate the module that was having the issue? i met the same issue but i didn't include that dependency. Thx
> 
> The error mentioned the very specific `www.josscrowcroft.com` string, so I searched for that inside the node_modules directory.

Thank you very much! I found the package that was bothering me too.

**Comment by SearchingSoul** [comment]
With electron-builder version: "20.38.3"
I see a similar error as OP on electron 4.0.0 & 3.0.13 both with yarn 1.12.3. Works fine with npm 😕

The dependency(call it depX) that seems to cause this does not  have `"dependencies" : []`, it has `"dependencies" : {}` in its package.json. None of the dependencies of depX have empty dependency arrays. If I remove depX the problem disappears.

```
 ⨯ node_modules.Dependency.Dependencies: ReadMapCB: expect { or n, but found [, error found in #10 byte of ...|cies"  : [],
  "repo|..., bigger context ...|g>",
  "contributors"  : [],
  "dependencies"  : [],
  "repository"    : {"type": "git", "url": "git|...

```

**Comment by rizkyario** [comment]
Had the same problem with yarn.

Works fine with npm.

**Comment by SheenOh** [comment]
I also install module accounting. I get same problem and npm build fails yet；
npm version 5.1.0

**Comment by gandrewstone** [comment]
I had no good string, but found the problem with the following search:

..../node_modules$ find . -name "package.json" -print | xargs grep --with-filename -n "encies\"  \: \[\],"

**Comment by haoma2514** [comment]
thanks for explanation!

> I found the source of the problem. My project contains a dependency to a module (https://www.npmjs.com/package/accounting) which specifies `"dependencies" : [],` in its package.json. Which is invalid because dependencies must be an object, not an array. I'll contact the module author to fix this.
