### ISSUE TITLE
mac os update problem

### ISSUE THREAD

**Issue by staifan** [electron-userland/electron-builder#3051]
* **Version**: 20.17.0

* **Target**: dmg,zip

electron version : 2.0.3
electron-updater version : 2.22.1

Hello, excuse me for my english but I am french ... (besides, if you are interested, I can send you the assistedMessage.yml file with the french translation)

as for my problem, when I use your system for windows update everything works perfectly but for the update mac os I get the following error :

> error:[2018-06-27 15:21:06.972] [info] App starting...
[2018-06-27 15:21:12.968] [info] Checking for update
[2018-06-27 15:21:12.969] [info] Checking for update... 
[2018-06-27 15:21:13.532] [info] Found version 1.0.0 (url: OrthoDoc-1.0.0-mac.zip, OrthoDoc-1.0.0.dmg)
[2018-06-27 15:21:13.532] [info] update-available undefined
[2018-06-27 15:21:13.546] [warn] checkForUpdatesAndNotify called, but downloadPromise is null
[2018-06-27 15:21:16.271] [info] Downloading update from OrthoDoc-1.0.0-mac.zip, OrthoDoc-1.0.0.dmg
[2018-06-27 15:21:16.372] [warn] Error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/OrthoDoc.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:25:96)
    at /Applications/OrthoDoc.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:361:25
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.downloadUpdate (/Applications/OrthoDoc.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:350:86)
    at EventEmitter.ipc.on (/Applications/OrthoDoc.app/Contents/Resources/app.asar/modules/window/index.js:574:41)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (/Applications/OrthoDoc.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)!--

and my corresponding package.json file:

> {
  "name": "builder-orthoDoc",
  "version": "1.0.0",
  "scripts": {
         "updateElectron": "npm i -g -D electron@latest",
         "postinstall": "electron-builder install-app-deps",
         "start": "electron ./app --enable-logging",
         "dev": "NODE_ENV='development' npm run start",
         "creatDist": "build CSC_KEYCHAIN=RUAUD STEPHANE EI"
  },
  "author": "",
  "license": "SEE LICENSE IN license.txt",
  "devDependencies": {
    "electron-builder": "^20.17.0"
  },
  "build": {
    "appId": "fr.webinsoft.orthoDoc",
    "asar": true,
    "electronVersion": "2.0.3",
    "directories": {
      "app": "../app",
      "output": "../dist/${platform}/${channel}/${version}"
    },
    "mac": {
      "target": [
        {
          "target": "dmg"
        },
        {
          "target": "zip"
        }
      ],
      "category": "public.app-category.medical",
      "minimumSystemVersion": "10.9.0",
      "electronUpdaterCompatibility": "2.21.8",
      "publish": [
        {
          "provider": "generic",
          "url": "https://webinsoft.fr/softInstaller/${name}/${platform}/${channel}/"
        }
      ]
    },
    "dmg": {
      "icon": "build/icon.icns"
    },
    "extraResources": [
      "../resourcesMac/**"
    ]
  },
  "main": "index.js",
  "dependencies": {},
  "description": ""
}

thanks in advance
 If you want, you can donate to increase issue priority (https://www.electron.build/donate) -->

**Comment by develar** [comment]
It seems since electron 2 electron updater proxy is not valid. I will check.

**Comment by staifan** [comment]
Indeed, I recompiled my application with electron 1.8.7 and the mac os update works perfectly.
Thank you for this information. Do you think that a solution is possible for electron version 2 or should I stay on 1.8.7 ?
In any case, thank you for your responsiveness and congratulations for your work ...

I enclose the file assistedMessage.yml for the build nsis with the french translation.
[assistedMessages.zip](https://github.com/electron-userland/electron-builder/files/2149414/assistedMessages.zip)

**Comment by staifan** [comment]
@develar said : 

> It seems since electron 2 electron updater proxy is not valid. I will check.

Problem solved.

electron version : 2.0.4
electron-builder version : 20.20.4
electron-updater version : 2.23.3

Everything is OK

**Comment by develar** [comment]
Thanks for confirmation. In any case soon I will recheck compatibility with electron 2.x to ensure stability.

**Comment by adammeyer** [comment]
I'm seeing this same issue with electron 3.  How do I update the proxy?

**Comment by aguynamedben** [comment]
I'm also seeing this sometimes with Electron 3.0.6, electron-builder 20.28.4, and electron-updater 3.1.2

![image](https://user-images.githubusercontent.com/107841/49333890-01380b00-f57c-11e8-93e1-f630eaffa38e.png)

Any ideas?

**Comment by aguynamedben** [comment]
Nevermind, I think this was addressed in https://github.com/electron-userland/electron-builder/issues/3377
