### ISSUE TITLE
Multi platform build problem

### ISSUE THREAD

**Issue by Meemaw** [electron-userland/electron-builder#3084]
* **Version**: electron-builder version=20.19.1

* **Target**: windows

Im trying to build windows target with electron-builder locally on OSx. Im following documentation on [multi-platform-build](https://www.electron.build/multi-platform-build).

Command im running:
```
docker run --rm -ti \
  --env ELECTRON_CACHE="/root/.cache/electron" \
  --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
  -v ${PWD}:/project \
  -v ~/.cache/electron:/root/.cache/electron \
  -v ~/.cache/electron-builder:/root/.cache/electron-builder \
  electronuserland/builder:wine \
  /bin/bash -c "yarn electron-dist-windows"
```

```
"electron-dist-windows": "electron-builder -c.extraMetadata.main=build_prod/electron.js -w",
```

However im getting the following error:

```
Error: Exit code: 1. Command failed: wine /root/.cache/electron-builder/winCodeSign/winCodeSign-2.0.0/rcedit-ia32.exe /project/dist/win-unpacked/MosaicHub.exe --set-version-string FileDescription MosaicHub --set-version-string ProductName MosaicHub --set-version-string LegalCopyright Copyright © year ${author} --set-file-version 0.1.0 --set-product-version 0.1.0.0 --set-version-string InternalName MosaicHub --set-version-string OriginalFilename  --set-version-string CompanyName Matej Šnuderl --set-icon /project/assets/icon.ico
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
0026:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0026:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0026:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0026:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0026:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0022:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0022:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0022:err:mshtml:check_version Could not open VERSION file
002c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
002c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0022:err:mshtml:check_version Could not open VERSION file
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.wine' has been updated.
Fatal error: Unable to set icon

0026:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0026:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0026:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0026:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0026:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0022:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0022:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0022:err:mshtml:check_version Could not open VERSION file
002c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
002c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0022:err:mshtml:check_version Could not open VERSION file
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.wine' has been updated.
Fatal error: Unable to set icon

    at /project/node_modules/builder-util/src/util.ts:125:16
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:595:12)
```

**Comment by develar** [comment]
On macOS you don't need to use Docker. You can build windows targets without any issues. (wine installation also not required).

**Comment by Meemaw** [comment]
It seems issue was my icon.ico icon which was somehow corrupted.
