### ISSUE TITLE
今天编译突然出现错误，使用的electrion版本是0.24.0

### ISSUE THREAD

**Issue by chenyidong** [electron-userland/electron-builder#3090]
错误如下
```
⨯ resolve request failed with status code 404
github.com/develar/app-builder/pkg/download.Downloader.follow
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:187
github.com/develar/app-builder/pkg/download.Downloader.Download
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:75
github.com/develar/app-builder/pkg/download.ConfigureCommand.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:41
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:62
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Error: E:\Workspace\Linux\rongcheng\fs-queryMachine-rc\dapaidang-zhanhui\node_modules\_app-builder-bin@1.10.3@app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (E:\Workspace\Linux\rongcheng\fs-queryMachine-rc\dapaidang-zhanhui\node_modules\_builder-util@5.13.2@builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (E:\Workspace\Linux\rongcheng\fs-queryMachine-rc\dapaidang-zhanhui\node_modules\_bluebird@3.5.1@bluebird\js\release\debuggability.js:400:19)
    at new PromiseSpawn (E:\Workspace\Linux\rongcheng\fs-queryMachine-rc\dapaidang-zhanhui\node_modules\_bluebird@3.5.1@bluebird\js\release\generators.js:43:17)
    at E:\Workspace\Linux\rongcheng\fs-queryMachine-rc\dapaidang-zhanhui\node_modules\_bluebird@3.5.1@bluebird\js\release\generators.js:197:21
    at build (E:\Workspace\Linux\rongcheng\fs-queryMachine-rc\dapaidang-zhanhui\node_modules\_electron-builder-lib@20.19.2@electron-builder-lib\out\index.js:220:17)
    at build (E:\Workspace\Linux\rongcheng\fs-queryMachine-rc\dapaidang-zhanhui\node_modules\_electron-builder@20.19.2@electron-builder\src\builder.ts:224:10)
    at then (E:\Workspace\Linux\rongcheng\fs-queryMachine-rc\dapaidang-zhanhui\node_modules\_electron-builder@20.19.2@electron-builder\src\cli\cli.ts:46:19)
error Command failed with exit code 1.
```

**Comment by 277800076** [comment]
问题解决了吗？

**Comment by develar** [comment]
Ребята, о чем вы?

**Comment by develar** [comment]
At least we need to include URL into error message.

**Comment by chenyidong** [comment]
没有解决，貌似库中没有这个包了

**Comment by pansila** [comment]
新的版本log加入了出错时请求的URL信息，建议使用新版本重新提供log，或者关闭bug。
