### ISSUE TITLE
Windows Build Crashing

### ISSUE THREAD

**Issue by daveywc** [electron-userland/electron-builder#3099]
Electron Builder: 20.19.2 (19.56.2)

Electron Updater: 2.23.3 (2.20.1)

Target: Windows: 

Have not built on Windows for about 3 months.  Before trying I updated electron-builder, electron-updater and electron to latest versions.  The build crashes out mid-way thru (see attached screen shot of debug output).  By crashing out I mean that the command prompt window is closed.  To try to capture the debug log I resorted to piping output to a file - unfortunately that file is deleted when the build crashes, hence the best I can do is to capture a screenshot of the end of the debug out put prior to the file being deleted.  I tried resorting back to the versions of the npm packages that I had previously (versions shown in brackets above), however I get the same (or similar) crash.  Sometimes my package.json file is deleted after the crash.  Any suggestions on what is causing the crash?
![npmrundistwin](https://user-images.githubusercontent.com/923942/42503080-0baca374-847b-11e8-9efa-9378204f5b44.jpg)

**Comment by develar** [comment]
Do you use requestExecutionLevel?

**Comment by daveywc** [comment]
Have tried 20.4.0 and 20.19.1 and both still crash out completely at the same point.  Any other suggestions?

**Comment by daveywc** [comment]
Also I have just tried building on Mac (again first time for a few months) and it is failing there as well now.  I've included the output in case it is somehow related to the other problem on Windows.

• electron-builder version=20.19.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=2.0.4 appOutDir=dist/mac
Error: ENOENT: no such file or directory, stat '/Users/david/Library/Developer/Xcode/DerivedData/DocsOnTapV2-egbeodqzvxrofwdtcnkokxhqekej/Build/Intermediates.noindex/ArchiveIntermediates/DocsOnTapV2/InstallationBuildProductsLocation/Applications/DocsOnTapV2.app'
    at AppFileWalker.handleSymlink (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/util/AppFileWalker.ts:39:14)
    at then.linkTarget (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/util/AppFileWalker.ts:30:21)
    at FSReqWrap.oncomplete (fs.js:136:15)
From previous event:
    at AppFileWalker.handleFile (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/util/AppFileWalker.ts:28:8)
    at AppFileWalker.consume (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/util/AppFileWalker.ts:97:17)
    at then.stat (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/builder-util/src/fs.ts:87:69)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at _bluebirdLst.default.map.name (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/builder-util/src/fs.ts:82:10)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/builder-util/src/fs.ts:75:51
    at Generator.next (<anonymous>)
    at go$readdir$cb (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:136:15)
From previous event:
    at walk (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/builder-util/out/fs.js:206:18)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/util/appFileCopier.ts:148:25
    at Generator.next (<anonymous>)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at computeFileSets (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/out/util/appFileCopier.js:355:18)
    at _computeFileSets (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/platformPackager.ts:261:14)
    at MacPackager.copyAppFiles (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/platformPackager.ts:298:27)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/platformPackager.ts:210:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at MacPackager.doPack (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/platformPackager.ts:158:165)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/macPackager.ts:80:95)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/packager.ts:369:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Packager.doBuild (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/packager.ts:337:39)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/packager.ts:313:52
    at Generator.next (<anonymous>)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:136:15)
From previous event:
    at Packager._build (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/packager.ts:290:133)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/packager.ts:286:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Packager.build (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/packager.ts:243:14)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/src/index.ts:52:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder/src/builder.ts:224:10)
    at then (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! au.com.harboursoftware.docsontap.v2@1.5.3 distmac: `ionic-app-scripts build --prod && set DEBUG=electron-builder && build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the au.com.harboursoftware.docsontap.v2@1.5.3 distmac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by develar** [comment]
Could you please set env `DEBUG=electron-builder` (https://www.electron.build/#debug) and attach log of the terminal output.

I didn't understand issue properly, now I see that not your final app failed, but build. BTW, on Windows I suggest to use [`windows-build-tools`](https://github.com/felixrieseberg/windows-build-tools) to install build tools for building native node modules on Windows.

**Comment by daveywc** [comment]
In my original post you will see that I had problems capturing the log using the debug option.  I've done my best to capture what I could in the screen shot that I provided then.

**Comment by daveywc** [comment]
OK - I installed windows-build-tools.  That seems to have resolved the problem building on Windows.  Thank you!

What about the second problem building on Mac?

**Comment by develar** [comment]
> electron-builder version=20.19.2

Could you please try latest version?

**Comment by daveywc** [comment]
@develar Just tried with latest version - still not building - see below:

Error: ENOENT: no such file or directory, stat '/Users/david/Library/Developer/Xcode/DerivedData/DocsOnTapV2-egbeodqzvxrofwdtcnkokxhqekej/Build/Intermediates.noindex/ArchiveIntermediates/DocsOnTapV2/InstallationBuildProductsLocation/Applications/DocsOnTapV2.app'
    at AppFileWalker.handleSymlink (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/util/AppFileWalker.ts:39:14)
    at then.linkTarget (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/util/AppFileWalker.ts:30:21)
    at FSReqWrap.oncomplete (fs.js:136:15)
From previous event:
    at AppFileWalker.handleFile (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/util/AppFileWalker.ts:28:8)
    at AppFileWalker.consume (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/util/AppFileWalker.ts:97:17)
    at then.stat (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/builder-util/src/fs.ts:87:69)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at _bluebirdLst.default.map.name (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/builder-util/src/fs.ts:82:10)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/builder-util/src/fs.ts:75:51
    at Generator.next (<anonymous>)
    at go$readdir$cb (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:136:15)
From previous event:
    at walk (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/builder-util/out/fs.js:206:18)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/util/appFileCopier.ts:145:7
    at Generator.next (<anonymous>)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at computeFileSets (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/out/util/appFileCopier.js:353:18)
    at _computeFileSets (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/platformPackager.ts:264:14)
    at MacPackager.copyAppFiles (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/platformPackager.ts:301:27)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/platformPackager.ts:209:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at MacPackager.doPack (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/platformPackager.ts:157:165)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Packager.doBuild (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:136:15)
From previous event:
    at Packager._build (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Packager.build (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Volumes/HD2CaseSensitive/Development/Projects/docsontapv2/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! au.com.harboursoftware.docsontap.v2@1.5.4 distmac: `ionic-app-scripts build --prod && build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the au.com.harboursoftware.docsontap.v2@1.5.4 distmac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by lagivan** [comment]
I've got exactly the same issue on Mac. I've checked the "ArchiveIntermediates" directory is missing. Does anyone know how it's supposed to be generated?
