### ISSUE TITLE
electron-updater fails to get checksum from github

### ISSUE THREAD

**Issue by openbuilds-engineer** [electron-userland/electron-builder#3105]
* **Version**: 
electron@1.8.7

electron-updater@2.23.3

* **Target**: 
win64

I have an app that I build an publish to github releases
Autoupdater runs and checks: Find the update, but when it has to download it:
```
Checking for update
Found version 1.1.0 (url: )
Downloading update from
Error: Error: Update info doesn't contain nor sha256 neither sha512 checksum: {
  "url": "OpenBuildsMachineDriver-Setup-1.1.0.exe"
}
    at newError (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\builder-util-runtime\src\index.ts:29:17)
    at files.map.fileInfo (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\Provider.ts:113:13)
    at Array.map (native)
    at resolveFiles (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\Provider.ts:111:55)
    at GitHubProvider.resolveFiles (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\GitHubProvider.ts:124:12)
    at C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\NsisUpdater.ts:24:40
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\NsisUpdater.ts:22:80)
    at C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:365:25
From previous event:
    at NsisUpdater.downloadUpdate (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:354:86)
    at C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:341:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:311:34)
    at C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:283:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:278:33)
    at NsisUpdater.checkForUpdates (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:217:35)
    at App.<anonymous> (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\index.js:89:15)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
Unhandled rejection Error: Update info doesn't contain nor sha256 neither sha512 checksum: {
  "url": "OpenBuildsMachineDriver-Setup-1.1.0.exe"
}
    at newError (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\builder-util-runtime\src\index.ts:29:17)
    at files.map.fileInfo (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\Provider.ts:113:13)
    at Array.map (native)
    at resolveFiles (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\Provider.ts:111:55)
    at GitHubProvider.resolveFiles (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\GitHubProvider.ts:124:12)
    at C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\NsisUpdater.ts:24:40
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\NsisUpdater.ts:22:80)
    at C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:365:25
From previous event:
    at NsisUpdater.downloadUpdate (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:354:86)
    at C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:341:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:311:34)
    at C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:283:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:278:33)
    at NsisUpdater.checkForUpdates (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\AppUpdater.ts:217:35)
    at App.<anonymous> (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\index.js:89:15)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)

```

Here's the latest.yml from git
```
version: 1.1.0
path: OpenBuildsMachineDriver-Setup-1.1.0.exe
sha2: 4887fc56080aa8bdb0a74ee01fa76636af9782cae70a033f5fb8e15bbf255873

```

**Comment by openbuilds-engineer** [comment]
Github release https://github.com/OpenBuilds/SW-Machine-Drivers/releases/tag/v1.1.0

**Comment by openbuilds-engineer** [comment]
https://github.com/electron-userland/electron-builder/issues/2874 seems similar

**Comment by openbuilds-engineer** [comment]
https://translate.google.co.za/translate?hl=en&sl=zh-TW&u=https://hk.saowen.com/a/a1d06fe4642bb2be45f27a5d63b2c9b92fc770c13fd6f11748ffec1652120eb4&prev=search says:
![translated](https://user-images.githubusercontent.com/31449271/42590574-7edecb46-8544-11e8-81e0-b2852158cee9.PNG)

**Comment by openbuilds-engineer** [comment]
Okay I am digging in a little.

In Provider.js under the resolveFiles Function I added some logging

```
function resolveFiles(updateInfo, baseUrl, pathTransformer = p => p) {
  const files = getFileList(updateInfo);
  const result = files.map(fileInfo => {
    if (fileInfo.sha2 == null && fileInfo.sha512 == null) {
		console.log(`Logging out Updateinfo ${(0, _builderUtilRuntime().safeStringifyJson)(updateInfo)} ` )
      throw (0, _builderUtilRuntime().newError)(`Update info doesn't contain nor sha256 neither sha512 checksum: ${(0, _builderUtilRuntime().safeStringifyJson)(fileInfo)}`, "ERR_UPDATER_NO_CHECKSUM");
    }

    return {
      url: (0, _main().newUrlFromBase)(pathTransformer(fileInfo.url), baseUrl),
      info: fileInfo
    };
  });
  const packages = updateInfo.packages;
  const packageInfo = packages == null ? null : packages[process.arch] || packages.ia32;

  if (packageInfo != null) {
    result[0].packageInfo = Object.assign({}, packageInfo, {
      path: (0, _main().newUrlFromBase)(pathTransformer(packageInfo.path), baseUrl).href
    });
  }

  return result;
}
```

Now that I log out the updateInfo: I can confirm, yip it is reading my latest.yml

```
Checking for update
Found version 1.1.0 (url: )
Downloading update from
Logging out Updateinfo {
  "version": "1.1.0",
  "path": "OpenBuildsMachineDriver-Setup-1.1.0.exe",
  "sha2": "4887fc56080aa8bdb0a74ee01fa76636af9782cae70a033f5fb8e15bbf255873",
  "releaseName": "1.1.0",
  "releaseNotes": ""
}
Error: Error: Update info doesn't contain nor sha256 neither sha512 checksum: {
  "url": "OpenBuildsMachineDriver-Setup-1.1.0.exe"
}
    at newError (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\builder-util-runtime\src\index.ts:29:17)
    at files.map.fileInfo (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\Provider.ts:114:6)
    at Array.map (native)
    at resolveFiles (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\Provider.ts:111:55)
    at GitHubProvider.resolveFiles (C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\GitHubProvider.ts:124:12)
    at C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers\node_modules\electron-updater\src\NsisUpdater.ts:24:40
```

**Comment by openbuilds-engineer** [comment]
If i comment out throw, it continues and works.

```
function resolveFiles(updateInfo, baseUrl, pathTransformer = p => p) {
  const files = getFileList(updateInfo);
  const result = files.map(fileInfo => {
    if (fileInfo.sha2 == null && fileInfo.sha512 == null) {
      //throw (0, _builderUtilRuntime().newError)(`Update info doesn't contain nor sha256 neither sha512 checksum: ${(0, _builderUtilRuntime().safeStringifyJson)(fileInfo)}`, "ERR_UPDATER_NO_CHECKSUM");
    }

    return {
      url: (0, _main().newUrlFromBase)(pathTransformer(fileInfo.url), baseUrl),
      info: fileInfo
    };
  });
  const packages = updateInfo.packages;
  const packageInfo = packages == null ? null : packages[process.arch] || packages.ia32;

  if (packageInfo != null) {
    result[0].packageInfo = Object.assign({}, packageInfo, {
      path: (0, _main().newUrlFromBase)(pathTransformer(packageInfo.path), baseUrl).href
    });
  }

  return result;
}
```

But this wont work well, as we deploy with Appveyor, and it downloads a clean copy of electron-updater - also not good practice to just edit node modules. This does look like a bug on your end though

**Comment by openbuilds-engineer** [comment]
@develar any chance you can look at this?  Our Deployments are totally stuck until this is fixed.  Its not an implementation issue, it is a bug.  as demonstrated in https://github.com/electron-userland/electron-builder/issues/3105#issuecomment-404260679 (: 

Sorry to tag again, but boss is on my case (:

**Comment by develar** [comment]
@openbuilds-engineer electron-builder version?

**Comment by openbuilds-engineer** [comment]
Thanks for looking into this develar (: 
```
$ npm list electron-builder
OpenBuildsMachineDriver@1.0.23 C:\OPENBUILDS-ENGINEER\SW-Machine-Drivers
`-- electron-builder@14.5.3
```

**Comment by openbuilds-engineer** [comment]
Wait! That looks too old right!  
Let me update first and then let you know if issue persists!

**Comment by openbuilds-engineer** [comment]
Yip! Time for me to self-confess that I was a retard! (: 
v20.22.0 works a treat! Deployments is back online!
