### ISSUE TITLE
Cannot find module 'builder-util/out/license'

### ISSUE THREAD

**Issue by tschellenbach** [electron-userland/electron-builder#3107]
Electron 2.04 + Electron Builder 20.19.2 fails to build Winds (http://github.com/getstream/winds) with the error below. 

```
Error: Cannot find module 'builder-util/out/license'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at _license (/Users/thierry/workspace/Winds/app/node_modules/dmg-builder/src/dmgLicense.ts:3:1)
    at /Users/thierry/workspace/Winds/app/node_modules/dmg-builder/src/dmgLicense.ts:13:30
    at Generator.next (<anonymous>)
From previous event:
    at addLicenseToDmg (/Users/thierry/workspace/Winds/app/node_modules/dmg-builder/out/dmgLicense.js:142:17)
    at /Users/thierry/workspace/Winds/app/node_modules/dmg-builder/src/dmg.ts:58:31
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Users/thierry/workspace/Winds/app/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Users/thierry/workspace/Winds/app/node_modules/electron-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Users/thierry/workspace/Winds/app/node_modules/electron-builder-lib/src/platformPackager.ts:119:24)
    at nonMasPromise.then.then (/Users/thierry/workspace/Winds/app/node_modules/electron-builder-lib/src/macPackager.ts:90:26)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

**Comment by develar** [comment]
Please try 20.20.4

**Comment by tschellenbach** [comment]
Works like a charm, thank you!
