### ISSUE TITLE
some dependencies in node_modules seem not to be executable

### ISSUE THREAD

**Issue by agualabs** [electron-userland/electron-builder#3123]
* **Version**:  20.22.1

Node Version: v8.11.3
Yarn Version: 1.6.0

* **Target**:  Mac x64

Hi there,

I am using yarn workspaces. 

Everything works as expected, but if I  introduce the option 
```
"build": {
..., 
"asarUnpack": [ "node_modules" ]
}
```
electron build doesn't seem to respect the workspace structure. `node_modules` just for demonstration.

I end up with an output
```
yarn run v1.6.0
$ electron-builder -m --x64 --publish=always
  • electron-builder version=20.22.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=1.8.4 appOutDir=build/mac
Error: /Users/palm/projects/tl/node_modules/7zip/index.js must be under /Users/palm/projects/tl/packages/electro/
    at AsarPackager.unpackPattern (/Users/palm/projects/tl/node_modules/electron-builder-lib/src/util/filter.ts:37:13)
    at /Users/palm/projects/tl/node_modules/electron-builder-lib/src/asar/asarUtil.ts:116:82
From previous event:
    at AsarPackager.createPackageFromFiles (/Users/palm/projects/tl/node_modules/electron-builder-lib/src/asar/asarUtil.ts:40:84)
    at /Users/palm/projects/tl/node_modules/electron-builder-lib/src/asar/asarUtil.ts:35:52
From previous event:
    at AsarPackager.pack (/Users/palm/projects/tl/node_modules/electron-builder-lib/src/asar/asarUtil.ts:27:79)
    at /Users/palm/projects/tl/node_modules/electron-builder-lib/src/platformPackager.ts:308:14
    at Generator.next (<anonymous>)
From previous event:
    at taskManager.addTask._computeFileSets.then (/Users/palm/projects/tl/node_modules/electron-builder-lib/src/platformPackager.ts:301:27)
From previous event:
    at MacPackager.copyAppFiles (/Users/palm/projects/tl/node_modules/electron-builder-lib/src/platformPackager.ts:302:10)
    at /Users/palm/projects/tl/node_modules/electron-builder-lib/src/platformPackager.ts:209:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at MacPackager.doPack (/Users/palm/projects/tl/node_modules/electron-builder-lib/src/platformPackager.ts:157:165)
    at /Users/palm/projects/tl/node_modules/electron-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/palm/projects/tl/node_modules/electron-builder-lib/src/macPackager.ts:80:95)
    at /Users/palm/projects/tl/node_modules/electron-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/palm/projects/tl/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/palm/projects/tl/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/palm/projects/tl/node_modules/electron-builder-lib/src/packager.ts:344:39)
    at /Users/palm/projects/tl/node_modules/electron-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /Users/palm/projects/tl/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/palm/projects/tl/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/palm/projects/tl/node_modules/electron-builder-lib/src/packager.ts:285:133)
    at /Users/palm/projects/tl/node_modules/electron-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/Users/palm/projects/tl/node_modules/electron-builder-lib/src/packager.ts:238:14)
    at build (/Users/palm/projects/tl/node_modules/electron-builder-lib/src/index.ts:46:28)
    at build (/Users/palm/projects/tl/node_modules/electron-builder/src/builder.ts:224:10)
    at then (/Users/palm/projects/tl/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at <anonymous>
error Command failed with exit code 1.
```

**Comment by develar** [comment]
All required node_modules (native and so on) will be unpacked automatically, no need to specify.

**Comment by agualabs** [comment]
Ok, maybe I have a misunderstanding then. One of my npm dependencies comes with a chromium app. Devmode works perfectly. When I unpack the asar package, the chromium app is not marked as executable. If I change it to executable via `chown +x ...`, the unpackaged app works again.

How can I influence, whether dependencies are executable in the packaged asar archive.

**Comment by develar** [comment]
I suggest you to get rid of chromium since it leads to a huge app size and sounds strange (since Electron itself is chrome).

As solution disable asar: `asar: false`

**Comment by agualabs** [comment]
Thanks, but `asar: false` is not an option because I will need to code sign later. I also need two chromium version because the one of electron is different from the one the dependency is using.

Ok, so it is not possible to mark specific file or directory in node_modules as executable in the packaged electron app.

**Comment by develar** [comment]
>  so it is not possible to mark specific file or directory in node_modules as executable in the packaged electron app.

No, it should be possible, but for now not clear for me why. Please specify name of your dep with chromium and maybe I will find time to investigate why it is not unpacked correctly.

**Comment by agualabs** [comment]
The packages is puppeteer at version 1.6.0. I will try to produce a minimal working example. Thanks for your any help.

**Comment by agualabs** [comment]
Here is a minimal working example:

https://github.com/agualabs/electron-puppeteer-quick-start

Works on mac only, sorry!
