### ISSUE TITLE
Cannot find module 'ncp'

### ISSUE THREAD

**Issue by djpereira** [electron-userland/electron-builder#313]
I'm using the latest version of electron-build and it fails in OSX.

"electron-builder": "3.5.1"
"electron-prebuilt": "0.37.5"

I manually ran `npm install ncp` and fixed the issue, but I think this shouldn't be the case.

I believe the problem could be with the electron-packager or one of its dependencies, but this brings another question: is there specific reason why electron-builder uses a beta version of the electron-packager instead of the production (more stable) version?

```
Packaging app for platform darwin x64 using electron v0.37.5
Error: Cannot find module 'ncp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/daniel/myproject.desktop/node_modules/electron-builder/node_modules/electron-packager-tf/mac.js:3:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/daniel/myproject.desktop/node_modules/electron-builder/node_modules/electron-packager-tf/index.js:137:13
    at end (/Users/daniel/myproject.desktop/node_modules/electron-builder/node_modules/electron-packager-tf/node_modules/run-series/index.js:8:15)
    at done (/Users/daniel/myproject.desktop/node_modules/electron-builder/node_modules/electron-packager-tf/node_modules/run-series/index.js:11:10)
    at each (/Users/daniel/myproject.desktop/node_modules/electron-builder/node_modules/electron-packager-tf/node_modules/run-series/index.js:16:43)
    at ZipFile.<anonymous> (/Users/daniel/myproject.desktop/node_modules/electron-builder/node_modules/electron-packager-tf/node_modules/extract-zip/index.js:29:11)
```

**Comment by develar** [comment]
I suppose `electron-packager-tf` is not updated. Because our CI tests passed.

> is there specific reason why electron-builder uses a beta version of the electron-packager instead of the production (more stable) version?

Using fs-extra copy instead of unreliable ncp (this PR is accepted).

**Comment by develar** [comment]
Please try 3.5.2
