### ISSUE TITLE
Windows Portable Build Failing

### ISSUE THREAD

**Issue by RockGuitarist1** [electron-userland/electron-builder#3135]
* **Version**:  Tested in 20.22.0 - 20.26.0

* **Target**: Windows. Electron v.2.0.5

Debug Log:

```
> electron-builder --windows

  • electron-builder version=20.26.0
  • loaded configuration file=C:\app\electron-builder.json
  • effective config config=
                       directories:
                         output: app-builds
                         buildResources: build
                       productName: MyApp
                       files:
                         - '**/*'
                         - '!*.ts'
                         - '!package.json'
                         - '!package-lock.json'
                         - '!src/'
                         - '!e2e/'
                         - '!.angular-cli.json'
                         - '!karma.conf.js'
                         - '!tsconfig.json'
                         - '!tslint.json'
                         - '!protractor.conf.js'
                       win:
                         icon: dist
                         target:
                           - portable
                       mac:
                         icon: src/assets/images/logo_icon.ico
                         target:
                           - dmg
                       linux:
                         icon: src/assets/images/logo_icon.ico
                         target:
                           - AppImage

  • writing effective config file=app-builds\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.5 appOutDir=app-builds\win-unpacked
  • spawning        command=C:\app\node_modules\7zip-bin\win\x64\7za.exe x -bd C:\Users\me\AppData\Local\electron\Cache\electron-v2.0.5-win32-x64.zip -aoa -oC:\app\app-builds\win-unpacked

7-Zip (a) 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28

Scanning the drive for archives:
1 file, 50698842 bytes (49 MiB)

Extracting archive: C:\Users\me\AppData\Local\electron\Cache\electron-v2.0.5-win32-x64.zip
--
Path = C:\Users\me\AppData\Local\electron\Cache\electron-v2.0.5-win32-x64.zip
Type = zip
Physical Size = 50698842

Everything is Ok

Files: 117
Size:       121273683
Compressed: 50698842
  • exited          command=7za.exe code=0 pid=7744
  • spawning        command=C:\app\node_modules\app-builder-bin\win\x64\app-builder.exe node-dep-tree --dir C:\app
  • exited          command=app-builder.exe code=0 pid=1096 out=[{"dir":"C:\\app\\node_modules","deps":["@fortawesome/fontawesome-free","chart.js","chartjs-color","chartjs-color-string","color-name","moment","openseadragon","primeicons","primeng"]},{"dir":"C:\\app\\node_modules\\chartjs-color\\node_modules","deps":["color-convert"]}]
  • spawning        command=C:\app\node_modules\app-builder-bin\win\x64\app-builder.exe icon --format ico --root C:\app\build --root C:\app --out C:\app\app-builds\.icon-ico --input dist --input icon.ico --input icon.png --input icons --input icon.icns
←[37m  •←[0m path doesn't exist        ←[37mpath←[0m=C:\app\build\dist
←[37m  •←[0m path resolved             ←[37moutputFormat←[0m=ico ←[37mpath←[0m=C:\app\dist
←[31m  ⨯←[0m icon directory C:\app\dist doesn't contain icons
github.com/develar/app-builder/pkg/icons.CollectIcons
        /Users/develar/go/src/github.com/develar/app-builder/pkg/icons/collect-icons.go:72
github.com/develar/app-builder/pkg/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:124
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:27
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:64
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361
github.com/develar/app-builder/pkg/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:126
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:27
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:64
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

  • exited          command=app-builder.exe code=1 pid=10640
Error: C:\app\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (C:\app\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at WinPackager.resolveIcon (C:\app\node_modules\electron-builder-lib\src\platformPackager.ts:565:69)
    at C:\app\node_modules\electron-builder-lib\src\platformPackager.ts:549:31
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.getOrConvertIcon (C:\app\node_modules\electron-builder-lib\src\platformPackager.ts:537:54)
    at Lazy.WinPackager._iconPath (C:\app\node_modules\electron-builder-lib\src\winPackager.ts:63:9)
    at Lazy.get value [as value] (C:\app\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (C:\app\node_modules\electron-builder-lib\src\winPackager.ts:199:4)
    at C:\app\node_modules\electron-builder-lib\out\winPackager.js:519:37
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signAndEditResources (C:\app\node_modules\electron-builder-lib\src\winPackager.ts:338:5)
    at _bluebirdLst.default.map.file (C:\app\node_modules\electron-builder-lib\out\winPackager.js:599:25)
    at go$readdir$cb (C:\app\node_modules\graceful-fs\graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at C:\app\node_modules\electron-builder-lib\src\winPackager.ts:366:7
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (C:\app\node_modules\electron-builder-lib\src\winPackager.ts:389:9)
    at C:\app\node_modules\electron-builder-lib\src\platformPackager.ts:232:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (C:\app\node_modules\electron-builder-lib\src\platformPackager.ts:157:165)
    at C:\app\node_modules\electron-builder-lib\src\platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\app\node_modules\electron-builder-lib\src\platformPackager.ts:110:95)
    at C:\app\node_modules\electron-builder-lib\src\packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\app\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\app\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (C:\app\node_modules\electron-builder-lib\src\packager.ts:344:39)
    at C:\app\node_modules\electron-builder-lib\src\packager.ts:314:57
    at Generator.next (<anonymous>)
    at C:\app\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\app\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\app\node_modules\electron-builder-lib\src\packager.ts:285:133)
    at C:\app\node_modules\electron-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (C:\app\node_modules\electron-builder-lib\src\packager.ts:238:14)
    at build (C:\app\node_modules\electron-builder-lib\src\index.ts:46:28)
    at build (C:\app\node_modules\electron-builder\src\builder.ts:224:10)
    at then (C:\app\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
```

**Comment by RockGuitarist1** [comment]
Problem resolved by using build configuration in package.json. Previous was using script.

**Comment by YolandaXQY** [comment]
hello, I used the NPM, I also got this bug, and then I downloaded the yarn again, it's ok to use the `yarn pack`, according to your answer, you modified the package.json using `build` instead of `script`? How is your code represented? hope you answer me!

**Comment by YolandaXQY** [comment]
it's my `build`
```
{
  "productName": "COA",
  "directories": {
    "output": "release/"
  },
    "files": [
        "**/*",
        "!*.ts",
        "!*.code-workspace",
        "!LICENSE.md",
        "!package.json",
        "!package-lock.json",
        "!src/",
        "!e2e/",
        "!hooks/",
        "!.angular-cli.json",
        "!_config.yml",
        "!karma.conf.js",
        "!tsconfig.json",
        "!tslint.json"
    ],
  "win": {
    "icon": "dist",
    "target": [
      "portable"
    ]
  },
  "mac": {
    "icon": "dist",
    "target": [
      "dmg"
    ]
  },
  "linux": {
    "icon": "dist",
    "target": [
      "AppImage"
    ]
  }
}

```

**Comment by RockGuitarist1** [comment]
@YolandaXQY Your "build" property in your package.json looks fine to me. In order to execute this, just create a script for it. For example:

```
"scripts": {
    "package-app": "build-electron-app && electron-builder"
}
```
