### ISSUE TITLE
Error: Cannot cleanup:  Error: Request timed out when uploading to github

### ISSUE THREAD

**Issue by andreborud** [electron-userland/electron-builder#3140]
* **Version**: 20.22.0 (also happened with 20.19.x) 

Node 8.11.3

* **Target**: --win --mac

This error just started happening suddenly. Didn't change any settings regarding electron-builder or anything on github where I'm trying to publish the built files. 

I have cleared the ~/Library/Caches/electron-builder folder. 
Updated from version 20.19.x to 20.22.0. 

This is the error I keep getting, which happens almost every time just after this line:
• uploading       file=App-Setup-0.1.8.exe provider=GitHub

```
Error: Cannot cleanup:

Error #1 --------------------------------------------------------------------------------
Error: Request timed out
    at TLSSocket.socket.setTimeout (../app/node_modules/builder-util/node_modules/builder-util-runtime/src/httpExecutor.ts:217:18)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket.Socket._onTimeout (net.js:410:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
From previous event:
    at CancellationToken.createPromise (../app/node_modules/electron-builder-lib/node_modules/builder-util-runtime/src/CancellationToken.ts:51:12)
    at NodeHttpExecutor.doApiRequest (../app/node_modules/builder-util/node_modules/builder-util-runtime/src/httpExecutor.ts:84:30)
    at NodeHttpExecutor.request (../app/node_modules/builder-util/node_modules/builder-util-runtime/src/httpExecutor.ts:74:17)
    at GitHubPublisher.githubRequest (../app/node_modules/electron-publish/src/gitHubPublisher.ts:245:35)
    at ../app/node_modules/electron-publish/src/gitHubPublisher.ts:91:33
    at Generator.next (<anonymous>)
From previous event:
    at GitHubPublisher.getOrCreateRelease (../app/node_modules/electron-publish/src/gitHubPublisher.ts:84:35)
    at Lazy.GitHubPublisher._release (../app/node_modules/electron-publish/src/gitHubPublisher.ts:30:102)
    at Lazy.get value [as value] (../app/node_modules/lazy-val/src/main.ts:18:23)
    at ../app/node_modules/electron-publish/src/gitHubPublisher.ts:164:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubPublisher.doUpload (../app/node_modules/electron-publish/src/gitHubPublisher.ts:163:160)
    at ../app/node_modules/electron-publish/src/publisher.ts:86:16
    at Generator.next (<anonymous>)
    at ../app/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at GitHubPublisher.upload (../app/node_modules/electron-publish/src/publisher.ts:75:32)
    at PublishManager.scheduleUpload (../app/node_modules/electron-builder-lib/src/publish/PublishManager.ts:134:7)
    at ../app/node_modules/electron-builder-lib/src/publish/PublishManager.ts:161:11
From previous event:
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (../app/node_modules/electron-builder-lib/src/publish/PublishManager.ts:168:5)
    at EventEmitter.PublishManager.packager.artifactCreated.event (../app/node_modules/electron-builder-lib/src/publish/PublishManager.ts:97:36)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at Packager.dispatchArtifactCreated (../app/node_modules/electron-builder-lib/src/packager.ts:235:23)
    at ../app/node_modules/electron-builder-lib/src/targets/differentialUpdateInfoBuilder.ts:73:17
From previous event:
    at createBlockmap (../app/node_modules/electron-builder-lib/out/targets/differentialUpdateInfoBuilder.js:125:18)
    at ../app/node_modules/dmg-builder/out/dmg.js:322:84
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (../app/node_modules/dmg-builder/src/dmg.ts:73:7)
    at Function.buildAsyncTargets (../app/node_modules/electron-builder-lib/src/platformPackager.ts:139:36)
    at MacPackager.packageInDistributableFormat (../app/node_modules/electron-builder-lib/src/platformPackager.ts:118:24)
    at nonMasPromise.then.then (../app/node_modules/electron-builder-lib/src/macPackager.ts:90:26)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at ../app/node_modules/electron-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (../app/node_modules/electron-builder-lib/src/macPackager.ts:80:95)
    at ../app/node_modules/electron-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (../app/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at ../app/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (../app/node_modules/electron-builder-lib/src/packager.ts:344:39)
    at ../app/node_modules/electron-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at ../app/node_modules/graceful-fs/graceful-fs.js:99:16
    at ../app/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (../app/node_modules/electron-builder-lib/src/packager.ts:285:133)
    at ../app/node_modules/electron-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (../app/node_modules/electron-builder-lib/src/packager.ts:238:14)
    at build (../app/node_modules/electron-builder-lib/src/index.ts:46:28)
    at build (../app/node_modules/electron-builder/src/builder.ts:224:10)
    at then (../app/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at <anonymous>
```

**Comment by andreborud** [comment]
Seems to have been a server problem if you tried to connect from Spain. I used a VPN and connected from the US instead and all worked fine.
