### ISSUE TITLE
20.24.1 - unknown option "draft"

### ISSUE THREAD

**Issue by peterdanis** [electron-userland/electron-builder#3145]
* **Version**:  20.24.1

* **Target**: all

Build exits with code 1 and error `unknown option "draft"` on all platforms. On 20.23.1 no issues.

![image](https://user-images.githubusercontent.com/26599181/43002889-b7c3f8ea-8c2a-11e8-945a-2fa594d92ce9.png)

Btw the reported version is out of sync (see red squares in picture above). The same is for 20.23.1, where yarn tells me that I have 20.23.1, build process tell me 20.22.0 and package.json in node_modules (even after fresh installing) also 20.22.0.

**Comment by mrgodhani** [comment]
I am getting this as well

**Comment by damianobarbati** [comment]
+1

**Comment by develar** [comment]
Sorry, 20.24.2

**Comment by damianobarbati** [comment]
@develar, is there a known combo of latest stable versions to proceed without the following error?

```
$ cat package.json  | grep '"electron-'
        "electron-log": "^2.2.15",
        "electron-updater": "^2.23.3",
        "electron-builder": "^20.21.2",
        "electron-debug": "^2.0.0",
        "electron-reload": "^1.2.3",

$ yarn pack:dev
  • electron-builder version=20.24.2
  • loaded configuration file=package.json ("build" field)
Error: At least electron-updater 3.0.3 is recommended by current electron-builder version. Please set electron-updater version to "^3.0.3"
    at checkMetadata (/Users/damiano/Desktop/tav-client/node_modules/app-builder-lib/src/util/packageMetadata.ts:80:11)
    at /Users/damiano/Desktop/tav-client/node_modules/app-builder-lib/src/packager.ts:279:5
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (/Users/damiano/Desktop/tav-client/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/Users/damiano/Desktop/tav-client/node_modules/app-builder-lib/src/index.ts:54:28)
    at build (/Users/damiano/Desktop/tav-client/node_modules/electron-builder/src/builder.ts:224:10)
    at then (/Users/damiano/Desktop/tav-client/node_modules/electron-builder/src/cli/cli.ts:42:48)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by develar** [comment]
```
        "electron-log": "^2.2.15",
        "electron-updater": "^3.0.3",
        "electron-builder": "^20.24.2",
        "electron-debug": "^2.0.0",
        "electron-reload": "^1.2.3",
```

**Comment by develar** [comment]
@damianobarbati `Cannot download differentially` it is not a critical error, full download after it will be performed and app will be updated.

**Comment by damianobarbati** [comment]
I rolled back to these versions I found in https://github.com/develar/onshape-desktop-shell/blob/master/yarn.lock and now that error is gone.
```
"electron-log": "^2.2.15",
"electron-updater": "2.23.3",
"electron": "2.0.5",
"electron-builder": "20.21.2",
"electron-debug": "^2.0.0",
```

I know it's totally OT, but... do you have any idea why the `electron-updater` kills the app after during differential download like this? 
Logging with `logger.transports.file.level = 'silly';` doesn't log anything else.
I'm desperate 😔

```
C:\Users\damiano\AppData\Roaming>type TAV\log.log
...
...
[2018-07-20 15:31:44.749] [info] Found version 6.3.0-beta.8 (url: TAV.exe)
[2018-07-20 15:31:44.750] [info] Downloading update from TAV.exe
[2018-07-20 15:31:44.771] [info] No cached update info available
[2018-07-20 15:31:44.775] [info] Download block maps (old: "https://github.com/translated/tav-releases/releases/download/6.3.0-beta.5/TAV.exe.blockmap", new: https://github.com/translated/tav-releases/releases/download/6.3.0-beta.8/TAV.exe.blockmap)
[2018-07-20 15:31:46.268] [info] File has 890 changed blocks
[2018-07-20 15:31:46.268] [debug] [
  {
    "kind": 1,
    "start": 0,
    "end": 15450
  },
  ...
  ...
  ...
  {
    "kind": 1,
    "start": 81955803,
    "end": 82212992
  }
]
[2018-07-20 15:31:46.274] [info] Full: 80,286.13 KB, To download: 18,453.65 KB (23%)
[2018-07-20 15:31:46.277] [info] Differential download: https://github.com/translated/tav-releases/releases/download/6.3.0-beta.8/TAV.exe
[2018-07-20 15:31:46.277] [debug] effective url: original, range: bytes=0-15449
[2018-07-20 15:31:46.474] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/137188552/5c4da848-8c1c-11e8-8a4c-14acfe98d6fc
[2018-07-20 15:31:46.713] [debug] effective url: https://github-production-release-asset-2e65be.s3.amazonaws.com/137188552/5c4da848-8c1c-11e8-8a4c-14acfe98d6fc, range: bytes=23693-51345
[2018-07-20 15:31:46.914] [debug] effective url: https://github-production-release-asset-2e65be.s3.amazonaws.com/137188552/5c4da848-8c1c-11e8-8a4c-14acfe98d6fc, range: bytes=222575-279688
[2018-07-20 15:31:47.176] [debug] effective url: https://github-production-release-asset-2e65be.s3.amazonaws.com/137188552/5c4da848-8c1c-11e8-8a4c-14acfe98d6fc, range: bytes=427036-454400
[2018-07-20 15:31:47.345] [debug] effective url: https://github-production-release-asset-2e65be.s3.amazonaws.com/137188552/5c4da848-8c1c-11e8-8a4c-14acfe98d6fc, range: bytes=6627392-7967750
[2018-07-20 15:31:48.771] [debug] effective url: https://github-production-release-asset-2e65be.s3.amazonaws.com/137188552/5c4da848-8c1c-11e8-8a4c-14acfe98d6fc, range: bytes=7976626-8615613

C:\Users\damiano\AppData\Roaming>
```
