### ISSUE TITLE
Build Failing for Mac & Windows

### ISSUE THREAD

**Issue by smithalan92** [electron-userland/electron-builder#3155]
20.24.5 ( electron-builder-squirrel-windows 20.24.2 )

MacOS x64 , Windows x86

Builds are failing for both platforms using the latest versions of the electron builder packages.

```
 electron-builder version=20.24.5
Error: Unknown option "project"
    at checkBuildRequestOptions (/Users/vagrant/git/node_modules/app-builder-lib/src/index.ts:42:13)
    at build (/Users/vagrant/git/node_modules/app-builder-lib/src/index.ts:48:3)
    at build (/Users/vagrant/git/node_modules/electron-builder/src/builder.ts:226:10)
    at then (/Users/vagrant/git/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at <anonymous>
{ Error: Command failed: "./node_modules/.bin/build" -m --x64 --project ./client
    at checkExecSyncError (child_process.js:592:13)
    at execSync (child_process.js:632:13)
    at build (/Users/vagrant/git/build/desktop/build-app.js:40:3)
    at buildApp (/Users/vagrant/git/build/desktop/build-app.js:81:3)
    at <anonymous>
```

**Comment by migmacdev** [comment]
Which configuration code are you using for the build property?

**Comment by smithalan92** [comment]
Using a package.json file for config options, and triggering the build this command from the root directory of the project.

```
./node_modules/.bin/electron-builder build -m --x64 --project ./app
```

From what I can tell from the docs, that should be correct

**Comment by felix307253927** [comment]
you can use 20.22.0

**Comment by kmdrGroch** [comment]
@smithalan92 you should be able to use versions till 20.24.x - there is provided "validation" which breaks a lot of things right now.

**Comment by kmdrGroch** [comment]
@develar it should be repaired by adding "project" in "expected options" in  packages/app-builder-lib/src/index.ts
