### ISSUE TITLE
SignTool Error: An unexpected internal error has occurred. Error: Store::ImportCertObject() failed.

### ISSUE THREAD

**Issue by pumano** [electron-userland/electron-builder#3160]
* **Version**: 
 electron: 2.0.3 / 2.0.4
 node: 8/10
 npm: 5/6
 windows: 10
 electron-builder: 20.17.0 / 20.24.5

* **Target**: 
`--win --ia32` (nsis)

* **Details**:
When I try to build app via `electron-builder` with `pfx` certificate with existed password, sometimes (can repeat up to 10 times) I got error at signing stage (check below). After removing password from pfx certificate, signing stage works perfectly.

```• rebuilding native production dependencies platform=win32 arch=ia32
  • packaging       platform=win32 arch=ia32 electron=2.0.3 appOutDir=dist\win-ia32-unpacked
  • signing         file=dist\win-ia32-unpacked\My App.exe certificateFile=./cert.pfx
  • building        target=nsis file=dist\My App Setup 6.5.0.exe archs=ia32 oneClick=false
  • signing         file=dist\win-ia32-unpacked\resources\elevate.exe certificateFile=./cert.pfx
Error: Exit code: 1. Command failed: C:\Users\myuser\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-2.0.0\windows-10\x64\signtool.exe sign /tr http://timestamp.comodoca.com/rfc3161 /f ./cert.pfx /fd sha256 /td sha256 /d My App /as /p 6c5b2e31922010079bda9ca27de9da622c53cd6fe9d8974354af36667f033643 (sha256 hash) /debug C:\Users\myuser\runner\builds\e16c7471\0\developers\myapp\dist\win-ia32-unpacked\resources\elevate.exe
SignTool Error: An unexpected internal error has occurred.

Error information: "Error: Store::ImportCertObject() failed." (-2146893792/0x80090020)

SignTool Error: An unexpected internal error has occurred.

    at C:\Users\myuser\runner\builds\e16c7471\0\developers\myapp\node_modules\electron-builder\node_modules\builder-util\src\util.ts:125:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at doSign (C:\Users\myuser\runner\builds\e16c7471\0\developers\myapp\node_modules\electron-builder\node_modules\electron-builder-lib\out\windowsCodeSign.js:160:18)
    at defaultExecutor (C:\Users\myuser\runner\builds\e16c7471\0\developers\myapp\node_modules\electron-builder\node_modules\electron-builder-lib\src\windowsCodeSign.ts:61:12)
    at C:\Users\myuser\runner\builds\e16c7471\0\developers\myapp\node_modules\electron-builder\node_modules\electron-builder-lib\src\windowsCodeSign.ts:68:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at sign (C:\Users\myuser\runner\builds\e16c7471\0\developers\myapp\node_modules\electron-builder\node_modules\electron-builder-lib\out\windowsCodeSign.js:268:17)
    at C:\Users\myuser\runner\builds\e16c7471\0\developers\myapp\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:256:15
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.doSign (C:\Users\myuser\runner\builds\e16c7471\0\developers\myapp\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:253:51)
    at C:\Users\myuser\runner\builds\e16c7471\0\developers\myapp\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:244:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at WinPackager.sign (C:\Users\myuser\runner\builds\e16c7471\0\developers\myapp\node_modules\electron-builder\node_modules\electron-builder-lib\src\winPackager.ts:204:53)
    at promise.then (C:\Users\myuser\runner\builds\e16c7471\0\developers\myapp\node_modules\electron-builder\node_modules\electron-builder-lib\src\targets\nsis\nsisUtil.ts:86:53)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp@6.5.0 build-app: `webpack && build --win --ia32 --publish=never`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myapp@6.5.0 build-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2018-07-19T07_38_10_832Z-debug.log
ERROR: Job failed: exit status 1
```

**Comment by UzEE** [comment]
After some more investigation, I may have narrowed down the problem to this particular line in the project:

https://github.com/electron-userland/electron-builder/blob/c35b3150536be66a9e1c2aae75f7e8f7f610699d/packages/app-builder-lib/src/winPackager.ts#L89

Since we're making an `exec` call to PowerShell, and reading the response from STDOUT, it is not properly encoded to UTF-8 (default encoding in PowerShell is not UTF-8 for legacy reasons from what I understand) so any non-ASCII characters and read incorrectly.
