### ISSUE TITLE
Unsupported arch arm

### ISSUE THREAD

**Issue by osinglee** [electron-userland/electron-builder#3162]
version "electron-builder": "^19.19.1",
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

Error: Unsupported arch arm
    at archFromString (/home/pi/Desktop/electron-dlw-master/node_modules/electron-builder-lib/node_modules/builder-util/src/arch.ts:39:13)
    at computeArchToTargetNamesMap (/home/pi/Desktop/electron-dlw-master/node_modules/electron-builder-lib/src/targets/targetFactory.ts:36:18)
    at /home/pi/Desktop/electron-dlw-master/node_modules/electron-builder-lib/src/packager.ts:351:41
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/home/pi/Desktop/electron-dlw-master/node_modules/electron-builder-lib/out/packager.js:432:11)
    at /home/pi/Desktop/electron-dlw-master/node_modules/electron-builder-lib/src/packager.ts:308:52
    at Generator.next (<anonymous>)

**Comment by deathblade89** [comment]
Hi there,

I see this comment was made a while ago, do you have any inclination on answering?

I have the same issue and would like to understand what the deprecations might be, workarounds or solutions to this
