### ISSUE TITLE
Electron-builder fails on peer dependencies

### ISSUE THREAD

**Issue by pronebird** [electron-userland/electron-builder#3166]
* **Version**: 20.25.0

* **Target**: macOS

`electron-builder install-app-deps` fails due to missing peer dependencies:

>Error: Unresolved node modules: react-native, react-native-windows
    at /Users/user/app/desktop/node_modules/app-builder-lib/src/util/packageDependencies.ts:108:17

These peer deps are required by `reactxp`, however are not used when building for web platform, therefore the question, why `electron-builder` fails on missing peer dependencies and how to disable that?

__Update__

Digging through the code I found that setting `ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES` environment variable to `true` allows to circumvent the error.

**Comment by pronebird** [comment]
This issue has been around for over a year, that's the log:

```
$ yarn install
yarn install v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > reactxp@1.5.0" has unmet peer dependency "react-native@^0.55.0".
warning " > reactxp@1.5.0" has unmet peer dependency "react-native-windows@^0.55.0-rc.0".
[4/4] 🔨  Building fresh packages...
$ DEBUG=electron-builder electron-builder install-app-deps
  • electron-builder version=20.28.2
  • loaded configuration file=~/app/electron-builder.yml
  • unresolved dependencies after first round unresolved=react-native, react-native-windows
Error: Unresolved node modules: react-native, react-native-windows
    at ~/app/node_modules/app-builder-lib/src/util/packageDependencies.ts:108:17
From previous event:
    at Collector.resolveUnresolvedHoisted (~/app/node_modules/app-builder-lib/src/util/packageDependencies.ts:164:10)
    at ~/app/node_modules/app-builder-lib/src/util/packageDependencies.ts:82:28
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Collector.collect (~/app/node_modules/app-builder-lib/src/util/packageDependencies.ts:84:6)
    at ~/app/node_modules/app-builder-lib/out/util/packageDependencies.js:123:47
    at Generator.next (<anonymous>)
From previous event:
    at getProductionDependencies (~/app/node_modules/app-builder-lib/out/util/packageDependencies.js:128:17)
    at Lazy.<anonymous> (~/app/node_modules/app-builder-lib/src/util/packageDependencies.ts:31:35)
    at Lazy.get value [as value] (~/app/node_modules/lazy-val/src/main.ts:18:23)
    at ~/app/node_modules/app-builder-lib/src/util/yarn.ts:128:81
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (~/app/node_modules/app-builder-lib/out/util/yarn.js:239:18)
    at ~/app/node_modules/app-builder-lib/src/util/yarn.ts:20:11
From previous event:
    at installOrRebuild (~/app/node_modules/app-builder-lib/out/util/yarn.js:68:17)
    at ~/app/node_modules/electron-builder/src/cli/install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (~/app/node_modules/electron-builder/out/cli/install-app-deps.js:174:17)
    at then (~/app/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at processImmediate (timers.js:632:19)
From previous event:
    at Object.args [as handler] (~/app/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (~/app/node_modules/electron-builder/node_modules/yargs/lib/command.js:237:44)
    at Object.parseArgs [as _parseArgs] (~/app/node_modules/electron-builder/node_modules/yargs/yargs.js:1059:30)
    at Object.get [as argv] (~/app/node_modules/electron-builder/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (~/app/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
error Command failed with exit code 1.

```
