### ISSUE TITLE
APPIMAGE env is not defined

### ISSUE THREAD

**Issue by mprandot** [electron-userland/electron-builder#3167]
* **Version**: "electron-builder": "^19.56.2",

* **Target**: Linux - AppImage

Hello! 
I'm using linux and when i try to auto-update my app he gives me a error;
I know that is just define a APPIMAGE variable, but, what path i need to define?

┏ Electron -------------------
  Checking for update
┗ ----------------------------
┏ Electron -------------------
  Found version 0.0.2 (url: numerama-frente-0.0.2-x86_64.AppImage)
┗ ----------------------------
┏ Electron -------------------
  Downloading update from numerama-frente-0.0.2-x86_64.AppImage
┗ ----------------------------
┏ Electron -------------------
  No cached update info available
┗ ----------------------------

┏ Electron -------------------
  Error: Error: APPIMAGE env is not defined
      at newError (/home/marcio/Desktop/frente/node_modules/builder-util-runtime/src/index.ts:29:17)
      at Object.<anonymous> (/home/marcio/Desktop/frente/node_modules/electron-updater/src/AppImageUpdater.ts:56:17)
      at Generator.next (<anonymous>)
  From previous event:
      at Object.task (/home/marcio/Desktop/frente/node_modules/electron-updater/src/AppImageUpdater.ts:53:7)
      at /home/marcio/Desktop/frente/node_modules/electron-updater/src/BaseUpdater.ts:104:25
      at Generator.throw (<anonymous>)
  From previous event:
      at AppImageUpdater.executeDownload (/home/marcio/Desktop/frente/node_modules/electron-updater/src/BaseUpdater.ts:29:68)
      at /home/marcio/Desktop/frente/node_modules/electron-updater/src/AppImageUpdater.ts:48:23
  From previous event:
      at AppImageUpdater.doDownloadUpdate (/home/marcio/Desktop/frente/node_modules/electron-updater/src/AppImageUpdater.ts:37:80)
      at /home/marcio/Desktop/frente/node_modules/electron-updater/src/AppUpdater.ts:393:25
  From previous event:
      at AppImageUpdater.downloadUpdate (/home/marcio/Desktop/frente/node_modules/electron-updater/src/AppUpdater.ts:382:86)
      at /home/marcio/Desktop/frente/node_modules/electron-updater/src/AppUpdater.ts:369:49
  From previous event:
      at AppImageUpdater.doCheckForUpdates (/home/marcio/Desktop/frente/node_modules/electron-updater/src/AppUpdater.ts:348:34)
      at /home/marcio/Desktop/frente/node_modules/electron-updater/src/AppUpdater.ts:287:25
      at Generator.next (<anonymous>)
      at runCallback (timers.js:781:20)
      at tryOnImmediate (timers.js:743:5)
      at processImmediate [as _immediateCallback] (timers.js:714:5)
  From previous event:
      at AppImageUpdater._checkForUpdates (/home/marcio/Desktop/frente/node_modules/electron-updater/src/AppUpdater.ts:282:33)
      at AppImageUpdater.checkForUpdates (/home/marcio/Desktop/frente/node_modules/electron-updater/src/AppUpdater.ts:221:35)
      at App.<anonymous> (/home/marcio/Desktop/frente/dist/electron/main.js:2375:67)
      at emitTwo (events.js:130:20)
      at App.emit (events.js:213:7)
┗ ----------------------------

**Comment by mprandot** [comment]
there's nobody to help in this issue?

**Comment by riteshzefo** [comment]
Did you find a solution to this?

**Comment by mprandot** [comment]
@riteshzefo in parts, this occurred because i'm trying to run auto-update on development mode, in production works normally

**Comment by hn6pot** [comment]
Hi, i have got the same issue on electron 4.0.1 using last electron-builder version : 20.38.5
I don't know why but i can't user auto update :s

**Comment by BloodShura** [comment]
Same problem happening here. Using a packaged AppImage (in production mode).

**Comment by jianwang-beijing** [comment]
@BloodShura Hi, I meet the same issue. Do you know where and when to set `APPIMAGE` value?

**Comment by okdistribute** [comment]
Also ran into this, not clear when to set APPIMAGE variable.

**Comment by okdistribute** [comment]
Was able to get it working with the following in index.js before the windows open

```
process.env.APPIMAGE = path.join(__dirname, 'dist', `Installar_Mapeo_${app.getVersion()}_linux.AppImage`)
```

**Comment by Hronom** [comment]
Hey just got in trouble with this, can we re-open this and fix it?

**Comment by Hronom** [comment]
I created PR to reflect this in docs https://github.com/electron-userland/electron-builder/pull/9039 to save other's time.
