### ISSUE TITLE
Error building an application 32 bit in a machine with 64 bit

### ISSUE THREAD

**Issue by maxcnunes** [electron-userland/electron-builder#317]
I got two problems building the application on Linux 64 for Windows 32 (I guess these problems would occur for building for Linux as well).

Ubuntu: `14.04` 64bit

#### `/usr/bin/ld: cannot find crti.o: No such file or directory`

```bash
root@892bdfc6b634:/usr/src/app# npm run --unsafe-perm dist:win

> @ dist:win /usr/src/app
> build --platform win32 --arch all

Installing app dependencies for arch ia32 to /usr/src/app/app

> fsevents@1.0.11 install /usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

make: Entering directory `/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/build'
make: Warning: File `.target.mk' has modification time 2.2e+03 s in the future
  SOLINK_MODULE(target) Release/obj.target/.node
/usr/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/.node] Error 1
make: Leaving directory `/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.3.6-coreos
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64/fse.node" "--module_name=fse" "--module_path=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64"
gyp ERR! cwd /usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64/fse.node --module_name=fse --module_path=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.3.6-coreos
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v4.4.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64/fse.node --module_name=fse --module_path=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64' (1)

npm ERR! Linux 4.3.6-coreos
npm ERR! argv "/usr/bin/nodejs" "/usr/lib/node_modules/npm/bin/npm-cli.js" "rebuild" "--production"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@1.0.11 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/app/npm-debug.log
Error: /usr/bin/nodejs exited with code 1
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/electron-builder/src/util.ts:95:69)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at spawn (/usr/src/app/node_modules/electron-builder/src/util.ts:93:10)
    at Object.installDependencies (/usr/src/app/node_modules/electron-builder/src/util.ts:45:9)
    at Packager.installAppDependencies (/usr/src/app/node_modules/electron-builder/src/packager.ts:171:33)
    at Packager.<anonymous> (/usr/src/app/node_modules/electron-builder/src/packager.ts:73:20)
    at [object Generator].next (native)
From previous event:
    at tsAwaiter (/usr/src/app/node_modules/electron-builder/src/awaiter.ts:10:51)
    at Object.build (/usr/src/app/node_modules/electron-builder/src/builder.ts:30:59)
    at Object.<anonymous> (/usr/src/app/node_modules/electron-builder/src/build-cli.ts:41:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Linux 4.3.6-coreos
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "--unsafe-perm" "dist:win"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! @ dist:win: `build --platform win32 --arch all`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the @ dist:win script 'build --platform win32 --arch all'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --platform win32 --arch all
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
root@892bdfc6b634:/usr/src/app# apt-get install gcc-multili^C
```

####  `/usr/bin/ld: cannot find -lstdc++`

```bash
root@892bdfc6b634:/usr/src/app# npm run --unsafe-perm dist:win

> @ dist:win /usr/src/app
> build --platform win32 --arch all

Installing app dependencies for arch ia32 to /usr/src/app/app

> fsevents@1.0.11 install /usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

make: Entering directory `/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/build'
make: Warning: File `.target.mk' has modification time 2.2e+03 s in the future
  SOLINK_MODULE(target) Release/obj.target/.node
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/.node] Error 1
make: Leaving directory `/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.3.6-coreos
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64/fse.node" "--module_name=fse" "--module_path=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64"
gyp ERR! cwd /usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64/fse.node --module_name=fse --module_path=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.3.6-coreos
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v4.4.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64/fse.node --module_name=fse --module_path=/usr/src/app/app/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/electron-v0.37-linux-x64' (1)

npm ERR! Linux 4.3.6-coreos
npm ERR! argv "/usr/bin/nodejs" "/usr/lib/node_modules/npm/bin/npm-cli.js" "rebuild" "--production"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@1.0.11 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/app/npm-debug.log
Error: /usr/bin/nodejs exited with code 1
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/electron-builder/src/util.ts:95:69)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at spawn (/usr/src/app/node_modules/electron-builder/src/util.ts:93:10)
    at Object.installDependencies (/usr/src/app/node_modules/electron-builder/src/util.ts:45:9)
    at Packager.installAppDependencies (/usr/src/app/node_modules/electron-builder/src/packager.ts:171:33)
    at Packager.<anonymous> (/usr/src/app/node_modules/electron-builder/src/packager.ts:73:20)
    at [object Generator].next (native)
From previous event:
    at tsAwaiter (/usr/src/app/node_modules/electron-builder/src/awaiter.ts:10:51)
    at Object.build (/usr/src/app/node_modules/electron-builder/src/builder.ts:30:59)
    at Object.<anonymous> (/usr/src/app/node_modules/electron-builder/src/build-cli.ts:41:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Linux 4.3.6-coreos
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "--unsafe-perm" "dist:win"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! @ dist:win: `build --platform win32 --arch all`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the @ dist:win script 'build --platform win32 --arch all'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --platform win32 --arch all
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

### Solution
First problem solved with `apt-get install -y gcc-multilib`.
Second problem solved with `apt-get install -y g++-multilib`

Maybe would be good include these instructions in the docs.

**Comment by havenchyk** [comment]
@maxcnunes PR is welcome. In general I'd recommend to use windows to create windows build.
