### ISSUE TITLE
App-builder exits with code 1

### ISSUE THREAD

**Issue by KacyLuzz** [electron-userland/electron-builder#3174]
**Version**: 20.25.0
* **Target**: Windows (NSIS)

When building for windows, app-builder.exe exits with code 1.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` (https://www.electron.build/#debug) and attach log of the terminal output.

**Comment by KacyLuzz** [comment]
**Command**: DEBUG=electron-builder electron-builder -lw --x64 --ia32
**Log :**
`> integrate@1.0.0 dist D:\Integrate\Launcher
> electron-builder -wl --x64 --ia32

  • electron-builder version=20.25.0
  • loaded configuration file=package.json ("build" field)
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=2.0.5 appOutDir=dist\linux-unpacked
  • scheduling remote build target=snap arch=x64
  • scheduling remote build target=appImage arch=x64
  • no native production dependencies
  • packaging       platform=linux arch=ia32 electron=2.0.5 appOutDir=dist\linux-ia32-unpacked
  • scheduling remote build target=snap arch=ia32
  • scheduling remote build target=appImage arch=ia32
  ⨯ unknown long flag '--build-resource-dir'

  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.5 appOutDir=dist\win-unpacked
  • no native production dependencies
  • packaging       platform=win32 arch=ia32 electron=2.0.5 appOutDir=dist\win-ia32-unpacked
  • building        target=nsis file=dist\Integrate Setup 1.0.0.exe archs=x64, ia32 oneClick=false
Error: D:\Integrate\Launcher\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (D:\Integrate\Launcher\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:254:19)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:568:12)
From previous event:
    at RemoteBuilder._build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:56:83)
    at _bluebirdLst.default.mapSeries.arch (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:51:19)
From previous event:
    at RemoteBuilder.build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:50:28)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\linuxPackager.ts:99:30
From previous event:
    at RemoteTarget.finishBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\linuxPackager.ts:97:20)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:384:36
From previous event:
    at Packager.doBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:314:57
From previous event:
    at Packager._build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at Packager.build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\Integrate\Launcher\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\Integrate\Launcher\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
  • signing         file=dist\win-ia32-unpacked\resources\elevate.exe subject=CN=Integrate thumbprint=0C6CACC72C26A0036F3A19D8AAFF719D454363D2 store=My user=current user
  • signing         file=dist\win-unpacked\resources\elevate.exe subject=CN=Integrate thumbprint=0C6CACC72C26A0036F3A19D8AAFF719D454363D2 store=My user=current user
  •   Signing NSIS uninstaller file=dist\.__uninstaller-nsis-integrate.exe subject=CN=Integrate thumbprint=0C6CACC72C26A0036F3A19D8AAFF719D454363D2 store=My user=current user
  • signing         file=dist\Integrate Setup 1.0.0.exe subject=CN=Integrate thumbprint=0C6CACC72C26A0036F3A19D8AAFF719D454363D2 store=My user=current user
  • building block map blockMapFile=dist\Integrate Setup 1.0.0.exe.blockmap
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integrate@1.0.0 dist: `electron-builder -wl --x64 --ia32`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integrate@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kacym\AppData\Roaming\npm-cache\_logs\2018-07-26T15_51_02_563Z-debug.log
`

**Comment by develar** [comment]
Please try pre-release 20.26.0

**Comment by KacyLuzz** [comment]
Fixed in 20.26.0

**Comment by gormrgryn** [comment]
`electron-builder`
I have the same problem on 20.44.4
