### ISSUE TITLE
Electron-Updater 3.0.3 - Error when building

### ISSUE THREAD

**Issue by popod** [electron-userland/electron-builder#3175]
Hi @develar 

I've the following error (see the electron-builder debug trace and my package.json config below) when trying to build my app for windows (and for mac too).

I'm on
* **Electron-Builder**: 20.25.0
* **Electron-Updater**: 3.0.3

I've tried with and this works fine
* **Electron-Builder**: 20.20.4
* **Electron-Updater**: 2.23.3

Do you have an idea of what is the problem ? Thanks

```
mbpr-userName:electron-vue userName$ DEBUG=electron-builder:* npm run build:win

> projectName@1.0.6 build:win /Users/userName/Documents/Documents/Projets/projectName/electron-vue
> npm run pack && build -w


> projectName@1.0.6 pack /Users/userName/Documents/Documents/Projets/projectName/electron-vue
> npm run pack:main && npm run pack:renderer


> projectName@1.0.6 pack:main /Users/userName/Documents/Documents/Projets/projectName/electron-vue
> cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.main.config.js

Hash: 1e071bfbe31e8cfc53e9                                                            
Version: webpack 4.16.2
Time: 1899ms
Built at: 2018-07-26 19:53:54
  Asset     Size  Chunks             Chunk Names
main.js  117 KiB       0  [emitted]  main
Entrypoint main = main.js
 [0] external "electron" 42 bytes {0} [built]
 [1] external "electron-is-dev" 42 bytes {0} [built]
 [3] ./app/src/renderer/utils/translator.js 2.7 KiB {0} [built]
 [9] ./app/src/main/electronLog.js 583 bytes {0} [built]
[12] ./app/src/renderer/lang/app-de.json 59.1 KiB {0} [built]
[22] ./app/src/main/index.js 4.33 KiB {0} [built]
[23] external "electron-window-state" 42 bytes {0} [built]
[24] ./app/src/main/autoUpdate.js 1.36 KiB {0} [built]
[33] ./app/src/main/linuxUpdater.js 1.67 KiB {0} [built]
[34] external "https" 42 bytes {0} [built]
[35] ./app/src/main/menu.js 4.06 KiB {0} [built]
[36] external "electron-localshortcut" 42 bytes {0} [built]
[37] ./app/src/renderer/utils/crashReporter.js 1.05 KiB {0} [built]
[38] ./app/src/renderer/storage/userData.js 870 bytes {0} [built]
[82] ./app/src/main/analytics.js 1.06 KiB {0} [built]
    + 69 hidden modules

> projectName@1.0.6 pack:renderer /Users/userName/Documents/Documents/Projets/projectName/electron-vue
> cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.renderer.config.js

Hash: e57231ba474639db2846                                                              
Version: webpack 4.16.2
Time: 13829ms
Built at: 2018-07-26 19:54:11
      Asset      Size  Chunks             Chunk Names
 styles.css  18.3 KiB       0  [emitted]  renderer
renderer.js   789 KiB       0  [emitted]  renderer
 index.html  3.58 KiB          [emitted]  
Entrypoint renderer = styles.css renderer.js
  [0] ./app/src/renderer/utils/translator.js 2.2 KiB {0} [built]
  [1] ./app/src/renderer/utils/logger.js 1.09 KiB {0} [built]
 [12] external "moment" 42 bytes {0} [built]
 [13] ./app/src/renderer/utils/history.js 463 bytes {0} [built]
 [22] external "vue" 42 bytes {0} [built]
 [24] ./app/src/renderer/utils/auth.js + 1 modules 12 KiB {0} [built]
      | ./app/src/renderer/utils/auth.js 10.2 KiB [built]
      | ./app/src/renderer/utils/licence.js 1.76 KiB [built]
 [38] external "vee-validate" 42 bytes {0} [built]
 [42] ./app/src/renderer/utils/migration.js 7.57 KiB {0} [built]
[116] external "vue-router" 42 bytes {0} [built]
[145] external "vue-electron" 42 bytes {0} [built]
[146] external "vue-resource" 42 bytes {0} [built]
[160] external "vue-moment" 42 bytes {0} [built]
[315] ./app/src/renderer/utils/validators.js 1.21 KiB {0} [built]
[317] ./app/src/renderer/main.js + 16 modules 19.4 KiB {0} [built]
      | ./app/src/renderer/App.vue?vue&type=template&id=13ba44bf& 207 bytes [built]
      | ./app/src/renderer/main.js 2.17 KiB [built]
      | ./app/src/renderer/plugins/notify.js 447 bytes [built]
      | ./app/src/renderer/routes.js 4.49 KiB [built]
      | ./app/src/renderer/App.vue 612 bytes [built]
      | ./app/src/renderer/App.vue?vue&type=script&lang=js& 356 bytes [built]
      | ./app/src/renderer/utils/crashReporter.js 690 bytes [built]
      | ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./app/src/renderer/App.vue?vue&type=script&lang=js& 2 KiB [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./app/src/renderer/App.vue?vue&type=template&id=13ba44bf& 1.81 KiB [built]
      | ./app/src/renderer/vuex/store.js 318 bytes [built]
      | ./app/src/renderer/vuex/actions.js 30 bytes [built]
      | ./app/src/renderer/vuex/getters.js 30 bytes [built]
      |     + 5 hidden modules
[327] ./app/src/renderer/components/InfosPageView.vue + 4 modules 4.6 KiB {0} [built]
      |    5 modules
    + 316 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./app/index.ejs 4.22 KiB {0} [built]
    [2] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!app/node_modules/vue-multiselect/dist/vue-multiselect.min.css?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/App.vue?vue&type=style&index=1&lang=css&:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/vue-loader/lib??vue-loader-options!./app/src/renderer/App.vue?vue&type=style&index=1&lang=css& 1.92 KiB {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Consultation/ConsultationAnamneseFormPageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Consultation/ConsultationDetailPageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Consultation/ConsultationFormPageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Consultation/ConsultationPageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Global/MySelect.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Invoices/InvoiceDetailsPageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Invoices/InvoicePageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/LoginPageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Modal/ConsultationPaid.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Modal/InvoicePaid.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Modal/Modal.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Modal/Representative.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Modal/ResetAppDatas.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/NavPageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Patient/Add/Base.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Patient/PatientDetailPageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Patient/PatientImportPageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Patient/PatientPageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/RegisterPageView.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/vue-loader/lib/index.js??vue-loader-options!app/src/renderer/components/Settings/Defaults.vue?vue&type=style&index=0&lang=css&:
    Entrypoint mini-css-extract-plugin = *
       2 modules
  • electron-builder version=20.25.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=2.0.5 appOutDir=dist/win-unpacked
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=babel-runtime
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=dot-prop, write-file-atomic
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=electron-is-dev
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=bluebird
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=bluebird-lst, fs-extra-p, sax
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=bluebird-lst, fs-extra-p, 
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=ms
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=bluebird-lst
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=graceful-fs, universalify
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=graceful-fs
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=graceful-fs
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=bluebird-lst
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=bluebird-lst
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=jsonfile, universalify, graceful-fs
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=graceful-fs
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=graceful-fs
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=deep-equal, extend
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=quill
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=deep-equal, extend
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=deep-equal, extend
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=lodash, bluebird
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=safe-buffer
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=moment
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=detect-libc, github-from-package, node-abi, noop-logger, os-homedir, which-pm-runs, expand-template, rc, tar-fs, simple-get, tunnel-agent, mkdirp, npmlog, pump
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=semver
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=deep-extend, ini, strip-json-comments
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=chownr, mkdirp, tar-stream
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=, mkdirp, 
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=end-of-stream, once
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=once
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=end-of-stream, readable-stream
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=readable-stream, safe-buffer
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=wrappy
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=core-util-is, inherits, string_decoder
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=once
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=safe-buffer
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=readable-stream
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=object-assign, console-control-strings
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=strip-ansi
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=string-width
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=end-of-stream, once
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=moment
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=deep-equal, mkdirp
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=deep-equal, mkdirp
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=graceful-fs
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=graceful-fs
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=graceful-fs
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=graceful-fs
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=graceful-fs, jsonfile, universalify
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=mkdirp
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=underscore
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=es6-promise, lie, pako
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=, lie, 
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=inherits, isarray, util-deprecate, core-util-is
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=inherits, isarray, util-deprecate, core-util-is
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=jquery
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=mimic-response, pify, decompress-response, safe-buffer
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=normalize-url, responselike, clone-response, get-stream, http-cache-semantics, keyv
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=, , , get-stream, , 
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=prepend-http, sort-keys
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=prepend-http, 
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/node_modules round=0 unresolved=decode-uri-component, object-assign, strict-uri-encode
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=1 unresolved=, object-assign, strict-uri-encode
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=lowercase-keys
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=mimic-response
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=inherits, readable-stream
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=signal-exit, graceful-fs
  • unresolved deps           nodeModuleDir=/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules round=0 unresolved=ms
Error: /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/ansi-regex/index.js must be under /Users/userName/Documents/Documents/Projets/projectName/electron-vue/app/
    at AsarPackager.unpackPattern (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/util/filter.ts:37:13)
    at /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/asar/asarUtil.ts:116:82
From previous event:
    at AsarPackager.createPackageFromFiles (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/asar/asarUtil.ts:40:84)
    at /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/asar/asarUtil.ts:35:52
From previous event:
    at AsarPackager.pack (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/asar/asarUtil.ts:27:79)
    at /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/platformPackager.ts:308:14
    at Generator.next (<anonymous>)
From previous event:
    at taskManager.addTask._computeFileSets.then (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/platformPackager.ts:301:27)
From previous event:
    at WinPackager.copyAppFiles (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/platformPackager.ts:302:10)
    at /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/platformPackager.ts:209:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at WinPackager.doPack (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/platformPackager.ts:157:165)
    at /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:159:5)
From previous event:
    at Packager.doBuild (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/userName/Documents/Documents/Projets/projectName/electron-vue/node_modules/electron-builder/src/cli/cli.ts:42:48)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! projectName@1.0.6 build:win: `npm run pack && build -w`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the projectName@1.0.6 build:win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/userName/.npm/_logs/2018-07-26T17_54_31_338Z-debug.log
```

```
"build": {
    "productName": "productName",
    "asarUnpack": [
      "**/dist/assets/fonts/Verdana.woff2",
      "**/dist/assets/fonts/VerdanaBold.woff2"
    ],
    "appId": "com.productname.app",
    "dmg": {
      "icon": "app/icons/dmg.icns",
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
    "files": [
      "dist/",
      "node_modules/",
      "package.json"
    ],
    "mac": {
      "category": "public.app-category.utility",
      "icon": "app/icons/icon.icns",
      "bundleVersion": ""
    },
    "win": {
      "icon": "app/icons/icon.ico",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]
    },
    "linux": {
      "category": "Utility",
      "target": [
        "deb"
      ]
    }
```

**Comment by popod** [comment]
Thanks for answer, but this will juste hide the unresolved deps and not fix the error which is juste below. Correct ?

**Comment by KacyLuzz** [comment]
You must also update to 20.26.0, some bugs were fixed.

**Comment by sindresorhus** [comment]
I'm seeing this too with the latest version of `electron-builder` (v20.26.1).

Failed build: https://travis-ci.com/atomiclabs/hyperdex/builds/80773438
package.json: https://github.com/atomiclabs/hyperdex/blob/bf9ecc4154dbf02b393d3a2058950c1ab29410ea/package.json

It might be a useful feature, but it's very hard to figure out what's causing the problem:

```
Error: /Users/travis/build/atomiclabs/hyperdex/node_modules/argparse/LICENSE must be under /Users/travis/build/atomiclabs/hyperdex/app/
```

Ok, so `argparse` cannot be in the root `node_modules` directory, but according to `yarn why argparse` (run in root):

```
info Reasons this module exists
   - "js-yaml" depends on it
   - Hoisted from "js-yaml#argparse"
   - Hoisted from "xo#eslint#js-yaml#argparse"
   - Hoisted from "stylelint#cosmiconfig#js-yaml#argparse"
```

So it has to be in the root `node_modules` too. It looks like the error is incorrect.

**Comment by popod** [comment]
I do not have this error anymore with `electron-builder 20.28.4`. Have you fix this issue @develar (if yes, I will close it. Thanks !) ? Or is this error related to something else ?

**Comment by popod** [comment]
@sindresorhus do you still have this issue or can I close It ?

**Comment by sindresorhus** [comment]
I'm not having the problem anymore, but the error definitely should be improved.
