### ISSUE TITLE
Error 416 when building AppImage

### ISSUE THREAD

**Issue by KacyLuzz** [electron-userland/electron-builder#3176]
* **Version**: 20.26.0 
* **Target**: AppImage

``` • downloading               parts=8 size=58 PB url=integrate-1.0.0-x86_64.AppImage
  ⨯ part download request failed with status code 416
github.com/develar/app-builder/pkg/download.(*Part).doRequest
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/Part.go:127
github.com/develar/app-builder/pkg/download.(*Part).download
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/Part.go:46
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadResolved.func1.1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:98
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func3
        /Users/develar/go/src/github.com/develar/app-builder/pkg/util/async.go:60
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Error: D:\Integrate\Launcher\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (D:\Integrate\Launcher\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:254:19)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
From previous event:
    at RemoteBuilder._build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:56:83)
    at _bluebirdLst.default.mapSeries.arch (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:51:19)
From previous event:
    at RemoteBuilder.build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:50:28)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\linuxPackager.ts:99:30
From previous event:
    at RemoteTarget.finishBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\linuxPackager.ts:97:20)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:384:36
From previous event:
    at Packager.doBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:314:57
From previous event:
    at Packager._build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at Packager.build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\Integrate\Launcher\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\Integrate\Launcher\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integrate@1.0.0 dist: `electron-builder -wl --x64 --ia32`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integrate@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kacym\AppData\Roaming\npm-cache\_logs\2018-07-26T16_18_00_062Z-debug.log```

**Comment by KacyLuzz** [comment]
@develar When looking for what the 416 code means i found "REQUESTED RANGE NOT SATISFIABLE"
It's maybe an problem when download files that are too heavy.

**Comment by develar** [comment]
Duplicates #3115

Yeach... so #3115 is not yet fixed.

**Comment by develar** [comment]
It works for me, but it seems some remote server error. Need to investigate.
