### ISSUE TITLE
Error when signing

### ISSUE THREAD

**Issue by KacyLuzz** [electron-userland/electron-builder#3177]
* **Version**: 20.26.0
* **Target**: Windows (NSIS)

Error: Cannot cleanup:

Error #1 --------------------------------------------------------------------------------
Error: Exit code: 1. Command failed: C:\Users\kacym\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-2.2.0\windows-10\x64\signtool.exe sign /tr http://timestamp.comodoca.com/rfc3161 /sha1 0C6CACC72C26A0036F3A19D8AAFF719D454363D2 /s My /fd sha256 /td sha256 /d Integrate /du https://integrateclient.net /as /debug D:\Integrate\Launcher\dist\Integrate Setup 1.0.0.exe
SignTool Error: The file is being used by another process.
SignTool Error: An error occurred while attempting to sign: D:\Integrate\Launcher\dist\Integrate Setup 1.0.0.exe

The following certificates were considered:
    Issued to: afd7267df43bb217
    Issued by: Token Signing Public Key
    Expires:   Mon Jan 01 14:16:52 2018
    SHA1 hash: 930A90724D84C3EB817A8129B55F22F3F7C851F6

    Issued to: Integrate
    Issued by: Integrate
    Expires:   Sun Jan 01 01:59:59 2040
    SHA1 hash: 0C6CACC72C26A0036F3A19D8AAFF719D454363D2

After EKU filter, 1 certs were left.
After expiry filter, 1 certs were left.
After Hash filter, 1 certs were left.
After Private Key filter, 1 certs were left.
The following certificate was selected:
    Issued to: Integrate
    Issued by: Integrate
    Expires:   Sun Jan 01 01:59:59 2040
    SHA1 hash: 0C6CACC72C26A0036F3A19D8AAFF719D454363D2

Done Adding Additional Store

Number of files successfully Signed: 0
Number of warnings: 0
Number of errors: 1

SignTool Error: The file is being used by another process.
SignTool Error: An error occurred while attempting to sign: D:\Integrate\Launcher\dist\Integrate Setup 1.0.0.exe

    at D:\Integrate\Launcher\node_modules\builder-util\src\util.ts:125:16
    at ChildProcess.exithandler (child_process.js:279:5)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
From previous event:
    at doSign (D:\Integrate\Launcher\node_modules\app-builder-lib\out\windowsCodeSign.js:160:18)
    at defaultExecutor (D:\Integrate\Launcher\node_modules\app-builder-lib\src\windowsCodeSign.ts:57:4)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\windowsCodeSign.ts:66:72
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at sign (D:\Integrate\Launcher\node_modules\app-builder-lib\out\windowsCodeSign.js:266:17)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\winPackager.ts:254:51
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.doSign (D:\Integrate\Launcher\node_modules\app-builder-lib\src\winPackager.ts:267:9)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\winPackager.ts:242:10
From previous event:
    at WinPackager.sign (D:\Integrate\Launcher\node_modules\app-builder-lib\src\winPackager.ts:247:7)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:252:32
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at NsisTarget.buildInstaller (D:\Integrate\Launcher\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:273:7)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\out\targets\nsis\NsisTarget.js:318:22
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:110:6)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:384:36
From previous event:
    at Packager.doBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:314:57
From previous event:
    at Packager._build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at Packager.build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\Integrate\Launcher\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\Integrate\Launcher\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>

Error #2 --------------------------------------------------------------------------------
Error: D:\Integrate\Launcher\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (D:\Integrate\Launcher\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:254:19)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
From previous event:
    at RemoteBuilder._build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:56:83)
    at _bluebirdLst.default.mapSeries.arch (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:51:19)
From previous event:
    at RemoteBuilder.build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:50:28)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\linuxPackager.ts:99:30
From previous event:
    at RemoteTarget.finishBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\linuxPackager.ts:97:20)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:384:36
From previous event:
    at Packager.doBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:314:57
From previous event:
    at Packager._build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at Packager.build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\Integrate\Launcher\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\Integrate\Launcher\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
    at D:\Integrate\Launcher\node_modules\builder-util\src\util.ts:125:16
    at ChildProcess.exithandler (child_process.js:279:5)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
    at doSign (D:\Integrate\Launcher\node_modules\app-builder-lib\out\windowsCodeSign.js:160:18)
    at defaultExecutor (D:\Integrate\Launcher\node_modules\app-builder-lib\src\windowsCodeSign.ts:57:4)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\windowsCodeSign.ts:66:72
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
    at sign (D:\Integrate\Launcher\node_modules\app-builder-lib\out\windowsCodeSign.js:266:17)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\winPackager.ts:254:51
    at Generator.next (<anonymous>)
    at WinPackager.doSign (D:\Integrate\Launcher\node_modules\app-builder-lib\src\winPackager.ts:267:9)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\winPackager.ts:242:10
    at WinPackager.sign (D:\Integrate\Launcher\node_modules\app-builder-lib\src\winPackager.ts:247:7)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:252:32
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
    at NsisTarget.buildInstaller (D:\Integrate\Launcher\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:273:7)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\out\targets\nsis\NsisTarget.js:318:22
    at Generator.next (<anonymous>)
    at NsisTarget.finishBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:110:6)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:384:36
    at Packager.doBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:314:57
    at Packager._build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
    at Packager.build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\Integrate\Launcher\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\Integrate\Launcher\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
    at ChildProcess.childProcess.once.code (D:\Integrate\Launcher\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:254:19)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
    at RemoteBuilder._build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:56:83)
    at _bluebirdLst.default.mapSeries.arch (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:51:19)
    at RemoteBuilder.build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:50:28)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\linuxPackager.ts:99:30
    at RemoteTarget.finishBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\linuxPackager.ts:97:20)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:384:36
    at Packager.doBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:314:57
    at Packager._build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
    at Packager.build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\Integrate\Launcher\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\Integrate\Launcher\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
    at throwError (D:\Integrate\Launcher\node_modules\builder-util\src\asyncTaskManager.ts:90:11)
    at checkErrors (D:\Integrate\Launcher\node_modules\builder-util\src\asyncTaskManager.ts:53:9)
    at D:\Integrate\Launcher\node_modules\builder-util\src\asyncTaskManager.ts:67:7
From previous event:
    at AsyncTaskManager.awaitTasks (D:\Integrate\Launcher\node_modules\builder-util\src\asyncTaskManager.ts:44:19)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:388:23
From previous event:
    at Packager.doBuild (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:314:57
From previous event:
    at Packager._build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at Packager.build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\Integrate\Launcher\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\Integrate\Launcher\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\Integrate\Launcher\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integrate@1.0.0 dist: `electron-builder -wl --x64 --ia32`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integrate@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kacym\AppData\Roaming\npm-cache\_logs\2018-07-26T16_57_35_841Z-debug.log

**Comment by KacyLuzz** [comment]
Addition:
It happens directly after 416 error, so maybe it's linked.

**Comment by develar** [comment]
Duplicates #3112
