### ISSUE TITLE
Build failing with EEXIST: file already exists

### ISSUE THREAD

**Issue by smithalan92** [electron-userland/electron-builder#3179]
20.26.0 ( latest )

MacOS - DMG , Windows - Squirrel ( Windows build passes, MacOS build fails)

I'm having the same issue as was brought up here https://github.com/electron-userland/electron-builder/issues/3039 , The MacOS build fails with EEXIST: file already exists, below is a sample of the error, there are more similar errors in the error log. This only happens on the CI (Bitrise) , if I run the build on a local machine it works perfectly, this also only seems to affect MacOS, Windows local & CI builds work perfectly. 

```
 electron-builder version=20.26.0
  • artifacts will be published reason=tag is defined tag=0.33.0-pre3
  • loaded configuration file=package.json ("build" field)
  • skipped app dependencies rebuild reason=npmRebuild is set to false
  • packaging       platform=darwin arch=x64 electron=2.0.5 appOutDir=dist/mac
  • downloading               parts=4 size=49 MB url=https://github.com/electron/electron/releases/download/v2.0.5/electron-v2.0.5-darwin-x64.zip
  • downloading               parts=1 size=5.3 kB url=https://github.com/electron/electron/releases/download/v2.0.5/SHASUMS256.txt
  • asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available
Error: Cannot cleanup: 
Error #1 --------------------------------------------------------------------------------
Error: EEXIST: file already exists, link '/Users/vagrant/git/node_modules/electron-remote/node_modules/debug/LICENSE' -> '/Users/vagrant/git/client/dist/mac/Electron.app/Contents/Resources/app/node_modules/debug/LICENSE'
    at copyOrLinkFile (/Users/vagrant/git/node_modules/builder-util/src/fs.ts:182:12)
    at /Users/vagrant/git/node_modules/builder-util/src/fs.ts:257:11
    at Generator.next (<anonymous>)
From previous event:
    at FileCopier.copy (/Users/vagrant/git/node_modules/builder-util/src/fs.ts:235:64)
    at /Users/vagrant/git/node_modules/app-builder-lib/src/util/appFileCopier.ts:70:13
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/vagrant/git/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/vagrant/git/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at copyAppFiles (/Users/vagrant/git/node_modules/app-builder-lib/out/util/appFileCopier.js:260:17)
    at taskManager.addTask._bluebirdLst.default.each.it (/Users/vagrant/git/node_modules/app-builder-lib/src/platformPackager.ts:292:86)
From previous event:
    at MacPackager.copyAppFiles (/Users/vagrant/git/node_modules/app-builder-lib/src/platformPackager.ts:292:43)
    at /Users/vagrant/git/node_modules/app-builder-lib/src/platformPackager.ts:209:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at MacPackager.doPack (/Users/vagrant/git/node_modules/app-builder-lib/src/platformPackager.ts:157:165)
    at /Users/vagrant/git/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/vagrant/git/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/vagrant/git/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/Users/vagrant/git/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:136:15)
From previous event:
    at Packager.doBuild (/Users/vagrant/git/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /Users/vagrant/git/node_modules/app-builder-lib/src/packager.ts:314:57
From previous event:
    at Packager._build (/Users/vagrant/git/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /Users/vagrant/git/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Packager.build (/Users/vagrant/git/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/Users/vagrant/git/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/Users/vagrant/git/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/vagrant/git/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at <anonymous>
```

**Comment by develar** [comment]
Set env `USE_HARD_LINKS=false` as workaround.

**Comment by develar** [comment]
Is it possible to provide project or sample to reproduce (locally you can reproduce using env `USE_HARD_LINKS=true`)?

**Comment by smithalan92** [comment]
Thanks for the reply @develar , Setting the env variable works 👍

I can't provide the project, its on a private repo, but I've made a quick sample app using the same dependencies as the app that has the problem

https://github.com/smithalan92/electron-builder-sample-error-app

`npm i` in the root and in `./src` and then `npm run build` and the error will happen

**Comment by snene** [comment]
@smithalan92 Where do you set the USE_HARD_LINKS env variable?

**Comment by smithalan92** [comment]
@snene For Windows it needs to be set in [System Environment Variables](https://www.computerhope.com/issues/ch000549.htm), for MacOS it needs to go in your ~/.bashrc or ~/.bash_profile file ( see [here](https://medium.com/@himanshuagarwal1395/setting-up-environment-variables-in-macos-sierra-f5978369b255)

**Comment by snene** [comment]
Thanks a bunch for the prompt reply @smithalan92

**Comment by vraravam** [comment]
> Set env `USE_HARD_LINKS=false` as workaround.

Finally, this seems to have fixed the problem.  I'm recording my comment here in case it helps others in newer builds of `electron-builder` - v`22.10.5`. Builds on both xenial (ubuntu) and osx (xcode 12.4) were failing till I set this env variable.

**Comment by MikeJerred** [comment]
Just ran into this issue on v22.13.1. `USE_HARD_LINKS=false` fixes it

**Comment by nwittwer** [comment]
> Just ran into this issue on v22.13.1. `USE_HARD_LINKS=false` fixes it

`USE_HARD_LINKS=false` fixes the issue in v22.14.13 as well. Using Github Actions as CI.

Is there a long-term fix for this planned?

**Comment by ggreco** [comment]
Also happens (electron-builder 22.14.13) using a CUSTOM github actions runner, while I can build without errors on the same machine if I run electron-builder not through the github runner.

I can confirm that adding `USE_HARD_LINKS: false` to the environment of the step that package the application solves the issue.

I tested this in an environment where the output was an universal binary DMG.

**Comment by itsPG** [comment]
I ran into this issue while I was building code on a macOS jenkins node.

Currently the source code of builder-util/src/fs.ts is `const _isUseHardLink = process.platform !== "win32" && process.env.USE_HARD_LINKS !== "false" && (isCI || process.env.USE_HARD_LINKS === "true")` 

thus electron-builder will enable _isUseHardLink on jenkins automatically, whereas it didn't work on my macOS jenkins node.
