### ISSUE TITLE
"rebuild" is not found when using yarn workspaces

### ISSUE THREAD

**Issue by pronebird** [electron-userland/electron-builder#3181]
* **Version**: 20.26

* **Target**: macOS

Yarn is not able to complete the post install step when adding a dependency into yarn workspace. It seems that it's missing `rebuild` command when running `electron-builder install-app-deps`.

```
yarn workspace @org/desktop-app add leftpad
yarn workspace v1.7.0
yarn add v1.7.0
[1/4] 🔍  Resolving packages...
warning leftpad@0.0.1: Use the built-in String.padStart function instead
[2/4] 🚚  Fetching packages...
info windows-security@0.0.5: The platform "darwin" is incompatible with this module.
info "windows-security@0.0.5" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-325d5a70-4dfb-41e2-b0fc-33809dee3497 > @org/components@1.0.0" has unmet peer dependency "react@^16.0.0".
warning "workspace-aggregator-325d5a70-4dfb-41e2-b0fc-33809dee3497 > @org/components@1.0.0" has unmet peer dependency "react-dom@^16.0.0".
warning "workspace-aggregator-325d5a70-4dfb-41e2-b0fc-33809dee3497 > @org/components@1.0.0" has unmet peer dependency "reactxp@^1.3.2".
warning "workspace-aggregator-325d5a70-4dfb-41e2-b0fc-33809dee3497 > @org/desktop-app > reactxp@1.3.2" has unmet peer dependency "react-native@^0.55.0".
warning "workspace-aggregator-325d5a70-4dfb-41e2-b0fc-33809dee3497 > @org/desktop-app > reactxp@1.3.2" has unmet peer dependency "react-native-windows@^0.54.0".
warning "workspace-aggregator-325d5a70-4dfb-41e2-b0fc-33809dee3497 > @org/mobile-app > react-native@0.53.3" has incorrect peer dependency "react@16.2.0".
warning "workspace-aggregator-325d5a70-4dfb-41e2-b0fc-33809dee3497 > @org/mobile-app > react-native-windows@0.51.0" has incorrect peer dependency "react@16.0.0".
warning "workspace-aggregator-325d5a70-4dfb-41e2-b0fc-33809dee3497 > @org/mobile-app > react-native-windows@0.51.0" has incorrect peer dependency "react-native@~0.51.0".
warning "nseventmonitor@0.0.9" is missing a bundled dependency "node-pre-gyp". This should be reported to the package maintainer.
[4/4] 📃  Building fresh packages...
[6/6] ⠈ @org/desktop-app
[-/6] ⠈ waiting...
[-/6] ⠈ waiting...
[-/6] ⠈ waiting...
error /Users/pronebird/org/project-root/app/node_modules/@org/desktop-app: Command failed.
Exit code: 1
Command: electron-builder install-app-deps
Arguments: 
Directory: /Users/pronebird/org/project-root/app/node_modules/@org/desktop-app
Output:
• electron-builder version=20.26.0
  • loaded configuration file=/Users/pronebird/org/project-root/app/packages/desktop/electron-builder.yml
  • rebuilding native production dependencies platform=darwin arch=x64
Error: /usr/local/Cellar/node@8/8.11.2/bin/node exited with code 1
Output:
yarn run v1.7.0
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Error output:
error Command "rebuild" not found.

    at ChildProcess.childProcess.once.code (/Users/pronebird/org/project-root/app/node_modules/builder-util/src/util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
From previous event:
    at rebuild (/Users/pronebird/org/project-root/app/node_modules/app-builder-lib/out/util/yarn.js:238:18)
    at /Users/pronebird/org/project-root/app/node_modules/app-builder-lib/src/util/yarn.ts:20:11
From previous event:
    at installOrRebuild (/Users/pronebird/org/project-root/app/node_modules/app-builder-lib/out/util/yarn.js:68:17)
    at /Users/pronebird/org/project-root/app/node_modules/electron-builder/src/cli/install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:




error Command failed.
Exit code: 1
Command: /usr/local/Cellar/node@8/8.11.2/bin/node
Arguments: /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js add leftpad
Directory: /Users/pronebird/org/project-root/app/packages/desktop
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

**Comment by pronebird** [comment]
It seems that the reason is why that happens is because yarn is not being properly detected when used with workspaces.

I just verified that `isYarn = false` in `packages/app-builder-lib/src/util/yarn.ts`

Running without workspaces:

```
isYarn = true, execPath = /usr/local/Cellar/yarn/1.7.0/libexec/bin/yarn.js name=MRFOCK
```

Running with workspaces:

```
isYarn = false, execPath = /usr/local/Cellar/node@8/8.11.2/bin/node name=MRFOCK
```
