### ISSUE TITLE
Error on remove temp update file: Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by spiral2k** [electron-userland/electron-builder#3189]
**Version:** 20.26.1

**'electron-updater' version:** 3.1.1

**Target:** windows

running on windows 7 - 64

when downloading the new update i`m getting this error:

```
[2018-07-30 01:25:32.335] [warn] checking-for-update
[2018-07-30 01:25:33.662] [info] Found version 0.0.4 (url: nedio-setup-0.0.4.exe)
[2018-07-30 01:25:33.662] [warn] update-available
[2018-07-30 01:25:33.663] [info] Downloading update from nedio-setup-0.0.4.exe
[2018-07-30 01:25:33.675] [info] No cached update info available
[2018-07-30 01:25:33.677] [warn] Error on remove temp update file: Error: EPERM: operation not permitted, unlink 'C:\Users\Meni\AppData\Roaming\nedio\__update__\temp-update.exe'
[2018-07-30 01:25:33.679] [warn] Error on remove temp update file: Error: EPERM: operation not permitted, unlink 'C:\Users\Meni\AppData\Roaming\nedio\__update__\temp-0-update.exe'
[2018-07-30 01:25:33.681] [info] Download block maps (old: "https://api.github.com/repos/spiral2k/Nedio/releases/assets/8052786.blockmap", new: https://api.github.com/repos/spiral2k/Nedio/releases/assets/8052786.blockmap)
[2018-07-30 01:25:34.341] [error] Cannot download differentially, fallback to full download: Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:355:17)
From previous event:
    at CancellationToken.createPromise (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:157:46
    at Generator.next (<anonymous>)
From previous event:
    at downloadBlockMap (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:154:13)
    at C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:170:34
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.differentialDownloadInstaller (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:148:210)
    at Object.<anonymous> (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:40:42)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:37:7)
    at C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:104:25
    at Generator.throw (<anonymous>)
From previous event:
    at NsisUpdater.executeDownload (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:29:68)
    at C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:32:23
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:22:80)
    at C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:393:25
From previous event:
    at NsisUpdater.downloadUpdate (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:382:86)
    at C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:369:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:348:34)
    at C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:282:33)
    at NsisUpdater.checkForUpdates (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:221:35)
    at Timeout.setInterval [as _onTimeout] (C:\Users\Meni\AppData\Local\Programs\nedio\resources\app.asar\update.js:19:15)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

i think its permission issue, any help guys?

**Comment by spiral2k** [comment]
fixed it by running "npm cache clean --force"
