### ISSUE TITLE
Infinite loop issue

### ISSUE THREAD

**Issue by kmdrGroch** [electron-userland/electron-builder#3191]
* **Version**: 
20.23.1 / 20.26.0

3.0.3

* **Target**: 
Win -> Win

Some issue appeared with "infinite loop". I even tried fixing it by getting previous versions of my app (i could build then, but now even they can't be built).

  • electron-builder version=20.26.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.5 appOutDir=build\win-unpacked
  ⨯ Infinite loop: C:\node_modules
github.com/develar/app-builder/pkg/nodeModules.(*Collector).processDependencies
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:268
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:178
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:194
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:194
github.com/develar/app-builder/pkg/nodeModules.ConfigureCommand.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:32
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:64
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:196
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:194
github.com/develar/app-builder/pkg/nodeModules.ConfigureCommand.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:32
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:64
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Error: C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (C:\Users\b.leoniak\Desktop\a\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at computeNodeModuleFileSets (C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\out\util\appFileCopier.js:429:18)
    at C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\platformPackager.ts:268:42
    at Generator.next (<anonymous>)
From previous event:
    at then (C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\platformPackager.ts:264:14)
From previous event:
    at _computeFileSets (C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\platformPackager.ts:265:10)
    at WinPackager.copyAppFiles (C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\platformPackager.ts:301:27)
    at C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\platformPackager.ts:209:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at WinPackager.doPack (C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\platformPackager.ts:157:165)    at C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\platformPackager.ts:110:95)
    at C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Users\b.leoniak\Desktop\a\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\b.leoniak\Desktop\a\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\packager.ts:344:39)
    at C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\packager.ts:314:57
    at Generator.next (<anonymous>)
    at C:\Users\b.leoniak\Desktop\a\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\b.leoniak\Desktop\a\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\packager.ts:285:133)
    at C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (C:\Users\b.leoniak\Desktop\a\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (C:\Users\b.leoniak\Desktop\a\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\Users\b.leoniak\Desktop\a\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>

**Comment by kmdrGroch** [comment]
I think i solved it. Removing all node files from C:/ , temp, and appdata allowed it to be built.
