### ISSUE TITLE
Pushing release doesn't work

### ISSUE THREAD

**Issue by iahmedani** [electron-userland/electron-builder#3195]
* **Version**: 
"electron-builder": "^20.26.0",

* **Target**: 
Windows

* **Details**:
Previously it was working fine but all of sudden from last evening facing following issue:

> Error: Request timed out
    at TLSSocket.socket.setTimeout (E:\acf_mis_local_v1\node_modules\builder-util-runtime\src\httpExecutor.ts:217:18)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.Socket._onTimeout (net.js:448:8)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
From previous event:
    at CancellationToken.createPromise (E:\acf_mis_local_v1\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at NodeHttpExecutor.doApiRequest (E:\acf_mis_local_v1\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at E:\acf_mis_local_v1\node_modules\electron-publish\src\gitHubPublisher.ts:174:35
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at GitHubPublisher.doUpload (E:\acf_mis_local_v1\node_modules\electron-publish\src\gitHubPublisher.ts:163:160)
    at E:\acf_mis_local_v1\node_modules\electron-publish\src\publisher.ts:86:16
    at Generator.next (<anonymous>)
    at E:\acf_mis_local_v1\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:159:5)
From previous event:
    at GitHubPublisher.upload (E:\acf_mis_local_v1\node_modules\electron-publish\src\publisher.ts:75:32)
    at PublishManager.scheduleUpload (E:\acf_mis_local_v1\node_modules\app-builder-lib\src\publish\PublishManager.ts:148:7)
    at E:\acf_mis_local_v1\node_modules\app-builder-lib\src\publish\PublishManager.ts:175:11
From previous event:
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (E:\acf_mis_local_v1\node_modules\app-builder-lib\src\publish\PublishManager.ts:182:5)
    at EventEmitter.PublishManager.packager.artifactCreated.event (E:\acf_mis_local_v1\node_modules\app-builder-lib\src\publish\PublishManager.ts:107:36)
    at EventEmitter.emit (events.js:187:15)
    at Packager.dispatchArtifactCreated (E:\acf_mis_local_v1\node_modules\app-builder-lib\src\packager.ts:235:23)
    at E:\acf_mis_local_v1\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:264:7
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at NsisTarget.buildInstaller (E:\acf_mis_local_v1\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:273:7)
    at E:\acf_mis_local_v1\node_modules\app-builder-lib\out\targets\nsis\NsisTarget.js:318:22
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (E:\acf_mis_local_v1\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:110:6)
    at E:\acf_mis_local_v1\node_modules\app-builder-lib\src\packager.ts:384:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.doBuild (E:\acf_mis_local_v1\node_modules\app-builder-lib\src\packager.ts:344:39)
    at E:\acf_mis_local_v1\node_modules\app-builder-lib\src\packager.ts:314:57
    at Generator.next (<anonymous>)
    at E:\acf_mis_local_v1\node_modules\graceful-fs\graceful-fs.js:99:16
    at E:\acf_mis_local_v1\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (E:\acf_mis_local_v1\node_modules\app-builder-lib\src\packager.ts:285:133)
    at E:\acf_mis_local_v1\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (E:\acf_mis_local_v1\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (E:\acf_mis_local_v1\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (E:\acf_mis_local_v1\node_modules\electron-builder\src\builder.ts:227:10)
    at then (E:\acf_mis_local_v1\node_modules\electron-builder\src\cli\cli.ts:42:48)
<

**Comment by iahmedani** [comment]
Issue resolved, seems my network admin blocked the port
