### ISSUE TITLE
Error: Cannot find module 'app-builder-lib/out/binDownload'

### ISSUE THREAD

**Issue by BarryCarlyon** [electron-userland/electron-builder#3205]
* Version:
```
  "dependencies": {
    "electron": "^2.0.6",
    "electron-builder": "^20.26.1",
    "electron-builder-lib": "^20.23.1",
    "electron-builder-squirrel-windows": "^20.27.0"
  }
```

* **Target**: Windows.Squirrel

```
Error: Cannot find module 'app-builder-lib/out/binDownload'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at _binDownload (<SNIPPEDPATH>node_modules/electron-builder-squirrel-windows/src/SquirrelWindowsTarget.ts:2:1)
    at <SNIPPEDPATH>node_modules/electron-builder-squirrel-windows/src/SquirrelWindowsTarget.ts:85:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
From previous event:
    at SquirrelWindowsTarget.computeEffectiveDistOptions (<SNIPPEDPATH>node_modules/electron-builder-squirrel-windows/src/SquirrelWindowsTarget.ts:54:36)
    at <SNIPPEDPATH>node_modules/electron-builder-squirrel-windows/src/SquirrelWindowsTarget.ts:35:36
    at Generator.next (<anonymous>)
From previous event:
    at SquirrelWindowsTarget.build (<SNIPPEDPATH>node_modules/electron-builder-squirrel-windows/src/SquirrelWindowsTarget.ts:17:44)
    at Function.buildAsyncTargets (<SNIPPEDPATH>node_modules/app-builder-lib/src/platformPackager.ts:139:36)
    at WinPackager.packageInDistributableFormat (<SNIPPEDPATH>node_modules/app-builder-lib/src/platformPackager.ts:118:24)
    at <SNIPPEDPATH>node_modules/app-builder-lib/src/platformPackager.ts:113:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at WinPackager.pack (<SNIPPEDPATH>node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at <SNIPPEDPATH>node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (<SNIPPEDPATH>node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at <SNIPPEDPATH>node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (<SNIPPEDPATH>node_modules/app-builder-lib/src/packager.ts:344:39)
    at <SNIPPEDPATH>node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at <SNIPPEDPATH>node_modules/graceful-fs/graceful-fs.js:99:16
    at <SNIPPEDPATH>node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (<SNIPPEDPATH>node_modules/app-builder-lib/src/packager.ts:285:133)
    at <SNIPPEDPATH>node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (<SNIPPEDPATH>node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (<SNIPPEDPATH>node_modules/app-builder-lib/src/index.ts:58:28)
    at build (<SNIPPEDPATH>node_modules/electron-builder/src/builder.ts:227:10)
    at then (<SNIPPEDPATH>node_modules/electron-builder/src/cli/cli.ts:42:48)
```

**Comment by framerate** [comment]
Yep, got this too

**Comment by develar** [comment]
Please use electron-builder 20.27.0 Will be marked as latest, sorry.
