### ISSUE TITLE
Snap build doesn't work on Ubuntu 18 - gtk-update-icon-cache-3.0: not found

### ISSUE THREAD

**Issue by kspearrin** [electron-userland/electron-builder#3211]
* **Version**: `^20.25.0`

* **Target**: snap

```
    "snap": {
      "confinement": "strict",
      "plugs": [
        "default",
        "password-manager-service"
      ],
      "stagePackages": [
        "default",
        "libsecret-1-0"
      ]
    }
```

Trying to build snap on Ubuntu 18 results in the following error. I can successfully run the same build on Ubuntu 16.

```
  • electron-builder version=20.25.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • installing production dependencies platform=linux arch=x64 appDir=/home/bitwarden/Projects/bitwarden/desktop/build
  • packaging       platform=linux arch=x64 electron=2.0.5 appOutDir=dist/linux-unpacked
  • building        target=snap arch=x64 file=dist/bitwarden_1.5.0_amd64.snap
Setting target machine to 'amd64'
Preparing to pull desktop-gtk3 
Hit http://us.archive.ubuntu.com/ubuntu bionic InRelease                                                  
Hit https://deb.nodesource.com/node_10.x bionic InRelease                                                 
Get:1 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                              
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]                               
Get:3 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                            
Hit https://download.docker.com/linux/ubuntu bionic InRelease                                             
Fetched 247 kB in 0s (0 B/s)                                                                              
Pulling desktop-gtk3 
Cloning into '/home/bitwarden/Projects/bitwarden/desktop/dist/__snap-x64/parts/desktop-gtk3/src'...
remote: Counting objects: 1180, done.
remote: Total 1180 (delta 0), reused 0 (delta 0), pack-reused 1179
Receiving objects: 100% (1180/1180), 200.52 KiB | 1.11 MiB/s, done.
Resolving deltas: 100% (615/615), done.
'app' has prerequisites that need to be staged: desktop-gtk3
Preparing to build desktop-gtk3 
Building desktop-gtk3 
+ snapcraftctl build
make FLAVOR=gtk3 -j1
gcc -Wall -O2 -o bindtextdomain.so -fPIC -shared ./../src/bindtextdomain.c -ldl
make FLAVOR=gtk3 install DESTDIR=/home/bitwarden/Projects/bitwarden/desktop/dist/__snap-x64/parts/desktop-gtk3/install
install -D -m755 desktop-launch /home/bitwarden/Projects/bitwarden/desktop/dist/__snap-x64/parts/desktop-gtk3/install/bin/desktop-launch
install -D -m644 flavor-select /home/bitwarden/Projects/bitwarden/desktop/dist/__snap-x64/parts/desktop-gtk3/install/
install -D -m644 bindtextdomain.so /home/bitwarden/Projects/bitwarden/desktop/dist/__snap-x64/parts/desktop-gtk3/install/lib/bindtextdomain.so
+ export XDG_DATA_DIRS=/home/bitwarden/Projects/bitwarden/desktop/dist/__snap-x64/parts/desktop-gtk3/install/usr/share
+ update-mime-database /home/bitwarden/Projects/bitwarden/desktop/dist/__snap-x64/parts/desktop-gtk3/install/usr/share/mime
+ [ -f /home/bitwarden/Projects/bitwarden/desktop/dist/__snap-x64/parts/desktop-gtk3/install/usr/share/icons/Adwaita//index.theme ]
+ 
+ gtk-update-icon-cache-3.0 -q /home/bitwarden/Projects/bitwarden/desktop/dist/__snap-x64/parts/desktop-gtk3/install/usr/share/icons/Adwaita/
/bin/sh: 36: gtk-update-icon-cache-3.0: not found
+ which gtk-update-icon-cache-3.0
Failed to run 'override-build': Exit code was 127.
  ⨯ exit status 2
github.com/develar/app-builder/pkg/util.ExecuteWithInheritedStdOutAndStdErr
	/Users/develar/go/src/github.com/develar/app-builder/pkg/util/util.go:54
github.com/develar/app-builder/pkg/snap.buildWithoutDockerAndWithoutTemplate
	/Users/develar/go/src/github.com/develar/app-builder/pkg/snap/snap.go:313
github.com/develar/app-builder/pkg/snap.Snap
	/Users/develar/go/src/github.com/develar/app-builder/pkg/snap/snap.go:222
github.com/develar/app-builder/pkg/snap.ConfigureCommand.func1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/snap/snap.go:102
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:64
runtime.main
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Error: /home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/bitwarden/Projects/bitwarden/desktop/node_modules/builder-util/src/util.ts:251:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
From previous event:
    at SnapTarget.build (/home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/targets/snap.ts:143:44)
    at Function.buildAsyncTargets (/home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
    at LinuxPackager.packageInDistributableFormat (/home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
    at /home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/platformPackager.ts:113:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
From previous event:
    at LinuxPackager.pack (/home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/bitwarden/Projects/bitwarden/desktop/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/bitwarden/Projects/bitwarden/desktop/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /home/bitwarden/Projects/bitwarden/desktop/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/bitwarden/Projects/bitwarden/desktop/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:139:20)
From previous event:
    at Packager._build (/home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
From previous event:
    at Packager.build (/home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/home/bitwarden/Projects/bitwarden/desktop/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/home/bitwarden/Projects/bitwarden/desktop/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/bitwarden/Projects/bitwarden/desktop/node_modules/electron-builder/src/cli/cli.ts:42:48)
```

`gtk-update-icon-cache` is installed on the machine.

**Comment by jookyboi** [comment]
Same here.

**Comment by develar** [comment]
20.30.0 will include `libsecret-1-0` by default.

**Comment by Jmlevick** [comment]
Same problem here, Ubuntu 18.04, gtk-update-icon-cache is installed on the machine (3.22.30-1ubuntu2)

**Comment by ndabAP** [comment]
Did anyone find a solution for this?
