### ISSUE TITLE
Snap build failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by marcoancona** [electron-userland/electron-builder#3215]
* **Version**: 20.27.1

Which version of electron-updater are you using (if applicable)?  
3.1.1

* **Target**: Linux (snap)

I cannot build a snap with the latest electron-builder. I cannot figure out what the problem is:

```
E:Failed to fetch http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1504/x86_64/Release  No Hash entry in Release file /home/anconam/.cache/snapcraft/stage-packages/apt/fd73f6a6da9e8583bf29dedd8998c444b7c4e7b42f8255b9d006bf625008f29a741a04010f1371c2234c6ab4e0119a43/var/lib/apt/lists/partial/developer.download.nvidia.com_compute_cuda_repos_ubuntu1504_x86%5f64_Release which is considered strong enough for security purposes
E:Failed to fetch http://ppa.launchpad.net/pinta-maintainers/pinta-stable/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E:Failed to fetch http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E:Failed to fetch http://ppa.launchpad.net/colingille/freshlight/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E:Some index files failed to download. They have been ignored
or old ones used instead.

Check that the sources on your host are configured correctly.
  ⨯ exit status 2
github.com/develar/app-builder/pkg/util.ExecuteWithInheritedStdOutAndStdErr
        /Users/develar/go/src/github.com/develar/app-builder/pkg/util/util.go:55
github.com/develar/app-builder/pkg/snap.buildWithoutDockerAndWithoutTemplate
        /Users/develar/go/src/github.com/develar/app-builder/pkg/snap/snap.go:313
github.com/develar/app-builder/pkg/snap.Snap
        /Users/develar/go/src/github.com/develar/app-builder/pkg/snap/snap.go:222
github.com/develar/app-builder/pkg/snap.ConfigureCommand.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/snap/snap.go:102
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:72
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Error: /home/anconam/projects/ElectronCal/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/anconam/projects/ElectronCal/node_modules/builder-util/src/util.ts:254:14)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at SnapTarget.build (/home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/targets/snap.ts:143:44)
    at Function.buildAsyncTargets (/home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
    at LinuxPackager.packageInDistributableFormat (/home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
    at /home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/platformPackager.ts:113:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at LinuxPackager.pack (/home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/anconam/projects/ElectronCal/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/anconam/projects/ElectronCal/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /home/anconam/projects/ElectronCal/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/anconam/projects/ElectronCal/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Packager.build (/home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/home/anconam/projects/ElectronCal/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/home/anconam/projects/ElectronCal/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/anconam/projects/ElectronCal/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at <anonymous>
```

**Comment by marcoancona** [comment]
Maybe related to https://github.com/electron-userland/electron-builder/issues/3211 ?

**Comment by develar** [comment]
Duplicates #3211
