### ISSUE TITLE
only the first time can be builded successfully

### ISSUE THREAD

**Issue by hooray** [electron-userland/electron-builder#3221]
OS: Windows 10
build again and reported the error:
```
electron-builder 19.45.4
No native production dependencies
Packaging for win32 x64 using electron 2.0.7 to dist\win-unpacked
Error: Exit code: 1. Command failed: C:\Users\hoora\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.9.0\rcedit.exe C:\Users\hoora\Desktop\electron-quick-start-master\dist\win-unpacked\electron-quick-start.exe --set-version-string FileDescription electron-quick-start --set-version-string ProductName electron-quick-start --set-version-string LegalCopyright Copyright © 2018 GitHub --set-file-version 1.0.0 --set-product-version 1.0.0.0 --set-version-string InternalName electron-quick-start --set-version-string OriginalFilename  --set-version-string CompanyName GitHub --set-icon C:\Users\hoora\Desktop\electron-quick-start-master\build\icon.ico
Fatal error: Unable to commit changes

Fatal error: Unable to commit changes

    at C:\Users\hoora\AppData\Roaming\npm\node_modules\electron-builder\node_modules\_builder-util@3.2.2@builder-util\src\util.ts:108:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\hoora\AppData\Roaming\npm\node_modules\electron-builder\node_modules\_bluebird@3.5.1@bluebird\js\release\debuggability.js:400:19)
    at Promise._then (C:\Users\hoora\AppData\Roaming\npm\node_modules\electron-builder\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:232:17)
    at Promise.then (C:\Users\hoora\AppData\Roaming\npm\node_modules\electron-builder\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:125:17)
    at Object.args [as handler] (C:\Users\hoora\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\Users\hoora\AppData\Roaming\npm\node_modules\electron-builder\node_modules\_yargs@10.0.3@yargs\lib\command.js:228:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\hoora\AppData\Roaming\npm\node_modules\electron-builder\node_modules\_yargs@10.0.3@yargs\yargs.js:1041:24)
    at Object.get [as argv] (C:\Users\hoora\AppData\Roaming\npm\node_modules\electron-builder\node_modules\_yargs@10.0.3@yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\hoora\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by hooray** [comment]
and I upgrade the electron-builder, the version still on 19.45.6
```
yarn upgrade electron-builder@latest
```
