### ISSUE TITLE
Error in app-builder-lib filter util with yarn workspace

### ISSUE THREAD

**Issue by PastaJ36** [electron-userland/electron-builder#3223]
* **Version: 20.27.1**: 

* **Target: win**: 

I have a project setup where an electron project is part of a yarn workspace. When I build an error is thrown by [util filter](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/util/filter.ts#L37). At that moment the variables are:
it = C:\<project_folder>\node_modules\ansi-regex\index.js
srcWithEndSlash = C:\<project_folder>\<package_folder>\

I tried putting the modules in the package folder with no-hoist, but then it still throws the error. Only after I completely remove the package from the project_folder does it continue. But then the same error happens with other node_modules, so this doesn't seem a viable solution. 

```
yarn workspace v1.9.4
yarn run v1.9.4
$ electron-builder
  • electron-builder version=20.27.1
  • loaded configuration file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config file=dist\builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • rebuilding native dependency name=node-hid
  • packaging       platform=win32 arch=x64 electron=2.0.7 appOutDir=dist\win-unpacked
Error: C:\<snip>\node_modules\ansi-regex\index.js must be under C:\<snip>\<package_name>\
    at AsarPackager.unpackPattern (C:\<snip>\node_modules\app-builder-lib\out\util\filter.js:48:13)
    at C:\<snip>\node_modules\app-builder-lib\src\asar\asarUtil.ts:116:82
From previous event:
    at AsarPackager.createPackageFromFiles (C:\<snip>\node_modules\app-builder-lib\src\asar\asarUtil.ts:40:84)
    at C:\<snip>\node_modules\app-builder-lib\src\asar\asarUtil.ts:35:52
From previous event:
    at AsarPackager.pack (C:\<snip>\node_modules\app-builder-lib\src\asar\asarUtil.ts:27:79)
    at C:\<snip>\node_modules\app-builder-lib\src\platformPackager.ts:308:14
    at Generator.next (<anonymous>)
From previous event:
    at taskManager.addTask._computeFileSets.then (C:\<snip>\node_modules\app-builder-lib\src\platformPackager.ts:301:27)
From previous event:
    at WinPackager.copyAppFiles (C:\<snip>\node_modules\app-builder-lib\src\platformPackager.ts:302:10)
    at C:\<snip>\node_modules\app-builder-lib\src\platformPackager.ts:209:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at WinPackager.doPack (C:\<snip>\node_modules\app-builder-lib\src\platformPackager.ts:157:165)
    at C:\<snip>\node_modules\app-builder-lib\src\platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\<snip>\node_modules\app-builder-lib\src\platformPackager.ts:110:95)
    at C:\<snip>\node_modules\app-builder-lib\src\packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\<snip>\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\<snip>\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (C:\<snip>\node_modules\app-builder-lib\src\packager.ts:344:39)
    at C:\<snip>\node_modules\app-builder-lib\src\packager.ts:314:57
    at Generator.next (<anonymous>)
    at C:\<snip>\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\<snip>\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\<snip>\node_modules\app-builder-lib\src\packager.ts:285:133)
    at C:\<snip>\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (C:\<snip>\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (C:\<snip>\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (C:\<snip>\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\<snip>\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
```

**Comment by develar** [comment]
Please try 20.28.2

**Comment by PastaJ36** [comment]
Awesome, thanks a lot!
