### ISSUE TITLE
Can't code sign Windows app on OSX using DigiCert certificate with latest version 20.27.1

### ISSUE THREAD

**Issue by payitforwardnow** [electron-userland/electron-builder#3226]
* **Version**: 20.27.1

* **Target**: Windows

This is my first posted issue in electron-userland. I hope it is received in the way it is intended. It is very possible I'm doing something wrong. I've checked and rechecked the documentation and I could have missed something. The last known version of electron-builder to work is 20.8.1. I have verified build works with only a simple change to electron-builder version and then rebuilding. 

I created a sample from a clone of electron-quick-start. I modified the package.json file and added some resources. When using the same certificate, etc. it works when the builder is 20.8.1 but NOT when I change it to the latest and greatest 20.27.1. 

Assuming you have a DigiCert certificate, all you have to do is add your certificate in p12 format to certs/MyCert.p12. When building the app you will get a prompt for your password.

Project is here https://github.com/payitforwardnow/electron-win-code-signing-issue

Note that when the code signing failed there is a reference to verisign timestamp

```
-t http://timestamp.verisign.com/scripts/timstamp.dll 
```
even though I specifically put the following in the package.json file

```
 "rfc3161TimeStampServer": "http://timestamp.digicert.com"
``` 

First let me show you what I see when using electron-builder version 20.8.1. This is the output when it works. 

```
Mickey-2:electron-win-code-signing-issue popeye$ npm run build

> electron-win-code-signing-issue@1.0.0 build /Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue
> export WIN_CSC_LINK=./certs/MyCert.p12; read -s -p "Certificate Password: " certPassword; export WIN_CSC_KEY_PASSWORD="$certPassword"; npm run build:win64

Certificate Password:
> electron-win-code-signing-issue@1.0.0 build:win64 /Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue
> electron-builder --win --x64

  • electron-builder version=20.8.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.7 appOutDir=dist/win-unpacked

... and 1 more
  • default Electron icon is used reason=application icon is not set
  • signing         file=dist/win-unpacked/electron-win-code-signing-issue.exe certificateFile=/Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/certs/MyCert.p12
  • building        target=nsis file=dist/electron-win-code-signing-issue Setup 1.0.0.exe archs=x64 oneClick=false
  •   Signing NSIS uninstaller file=dist/.__uninstaller-nsis-electron-win-code-signing-issue.exe certificateFile=/Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/certs/MyCert.p12
  • signing         file=dist/electron-win-code-signing-issue Setup 1.0.0.exe certificateFile=/Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/certs/MyCert.p12
  • building block map blockMapFile=dist/electron-win-code-signing-issue Setup 1.0.0.exe.blockmap
Mickey-2:electron-win-code-signing-issue popeye$
```

Below is what I get when all I use electron-builder version 20.27.1
```
Mickey-2:electron-win-code-signing-issue popeye$ npm run build

> electron-win-code-signing-issue@1.0.0 build /Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue
> export WIN_CSC_LINK=./certs/MyCert.p12; read -s -p "Certificate Password: " certPassword; export WIN_CSC_KEY_PASSWORD="$certPassword"; npm run build:win64

Certificate Password:
> electron-win-code-signing-issue@1.0.0 build:win64 /Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue
> electron-builder --win --x64

  • electron-builder version=20.27.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.7 appOutDir=dist/win-unpacked
  • default Electron icon is used reason=application icon is not set
  • building        target=nsis file=dist/electron-win-code-signing-issue Setup 1.0.0.exe archs=x64 oneClick=false
  • signing         file=dist/win-unpacked/resources/elevate.exe certificateFile=/Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/certs/MyCert.p12
Error: Exit code: null. Command failed: /Users/popeye/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.2.0/darwin/osslsigncode -in /Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/dist/win-unpacked/resources/elevate.exe -out /Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/dist/win-unpacked/resources/elevate-signed-sha1.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -pkcs12 /Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/certs/MyCert.p12 -h sha1 -n electron-win-code-signing-issue -i https://github.com/payitforwardnow/electron-win-code-signing-issue#readme -pass 4e3d7dc556d3ea9838fc10d5684a562f002971ee.... (sha256 hash)
    at /Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/node_modules/builder-util/src/util.ts:128:16
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
From previous event:
    at doSign (/Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/node_modules/app-builder-lib/out/windowsCodeSign.js:160:18)
    at defaultExecutor (/Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/node_modules/app-builder-lib/src/windowsCodeSign.ts:57:4)
    at /Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/node_modules/app-builder-lib/src/windowsCodeSign.ts:66:72
    at Generator.next (<anonymous>)
From previous event:
    at sign (/Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/node_modules/app-builder-lib/out/windowsCodeSign.js:266:17)
    at /Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/node_modules/app-builder-lib/src/winPackager.ts:255:51
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.doSign (/Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/node_modules/app-builder-lib/src/winPackager.ts:268:9)
    at /Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/node_modules/app-builder-lib/src/winPackager.ts:243:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at WinPackager.sign (/Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/node_modules/app-builder-lib/src/winPackager.ts:248:7)
    at promise.then (/Users/popeye/Data/MyProjects/git/pifn002/electron-win-code-signing-issue/node_modules/app-builder-lib/src/targets/nsis/nsisUtil.ts:92:53)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-win-code-signing-issue@1.0.0 build:win64: `electron-builder --win --x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-win-code-signing-issue@1.0.0 build:win64 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/popeye/.npm/_logs/2018-08-11T18_43_17_354Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-win-code-signing-issue@1.0.0 build: `export WIN_CSC_LINK=./certs/MyCert.p12;read -s -p "Certificate Password: " certPassword; export WIN_CSC_KEY_PASSWORD="$certPassword";npm run build:win64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-win-code-signing-issue@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/popeye/.npm/_logs/2018-08-11T18_43_17_408Z-debug.log
Mickey-2:electron-win-code-signing-issue popeye$
```
Again, if I change the builder version to 20.8.1 it works. 

Don't forget to install after changing the version number.
```
npm install
npm run build
```

Thank you in advance for your time and consideration.

**Comment by payitforwardnow** [comment]
Sorry for the long output in the post. I wasn't sure what was important so I copy and pasted everything.

**Comment by payitforwardnow** [comment]
Shouldn't the -t parameter be http://timestamp.digicert.com????? Does the latest version ignore the rfc3161TimeStampServer property in the build/win section? Here is the actual package.json file so you don't have to clone the git repo to look at it
```
{
  "name": "electron-win-code-signing-issue",
  "version": "1.0.0",
  "description": "Testing Win Code Signing Issue",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build:win64": "electron-builder --win --x64",
    "build": "export WIN_CSC_LINK=./certs/MyCert.p12; read -s -p \"Certificate Password: \" certPassword; export WIN_CSC_KEY_PASSWORD=\"$certPassword\"; npm run build:win64"
  },
  "repository": "https://github.com/payitforwardnow/electron-win-code-signing-issue.git",
  "build": {
    "asar": true,
    "appId": "com.securediscovery.issue02",
    "win": {
      "target": "nsis",
      "rfc3161TimeStampServer": "http://timestamp.digicert.com"
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowElevation": true,
      "installerHeaderIcon": "./build/installerHeaderIcon.ico",
      "deleteAppDataOnUninstall": true,
      "runAfterFinish": false,
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true,
      "menuCategory": true
    }
  },
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "2.0.7",
    "electron-builder": "20.27.1"
  }
}
``` 

Again, all I have to do is change the version of electron-builder to 20.8.1 and it works.

**Comment by payitforwardnow** [comment]
6 moths later and not a single response :(
