### ISSUE TITLE
Cannot find listfile

### ISSUE THREAD

**Issue by pksunkara** [electron-userland/electron-builder#3230]
* **Version**: 20.27.1

* **Target**: mac

```
Building app with electron-builder:

  • electron-builder version=20.27.1
  • description is missed in the package.json appPackageFile=/Users/pksunkara/Coding/pksunkara/dotsync/packages/@dotsync/app/package.json
  • writing effective config file=dist_electron/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=2.1.0-unsupported.20180809 appOutDir=dist_electron/mac
  • default Electron icon is used reason=application icon is not set
  • skipped macOS application code signing reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
  • building        target=macOS zip arch=x64 file=dist_electron/@dotsyncapp-0.1.1-mac.zip
  • building        target=DMG arch=x64 file=dist_electron/@dotsyncapp-0.1.1.dmg
  • building block map blockMapFile=dist_electron/@dotsyncapp-0.1.1.dmg.blockmap
Unhandled rejection Error: Exit code: 7. Command failed: /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/7zip-bin/mac/7za a -bd -mx=7 -mtc=off -mm=Deflate -mcu /Users/pksunkara/Coding/pksunkara/dotsync/packages/@dotsync/app/dist_electron/@dotsyncapp-0.1.1-mac.zip @dotsyncapp.app


Command Line Error:
Cannot find listfile
dotsyncapp.app


7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)




Command Line Error:
Cannot find listfile
dotsyncapp.app

    at /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/builder-util/src/util.ts:128:16
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe._handle.close (net.js:598:12)
From previous event:
    at archive (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/out/targets/archive.js:226:18)
    at /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/targets/ArchiveTarget.ts:37:13
    at Generator.next (<anonymous>)
From previous event:
    at ArchiveTarget.build (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/targets/ArchiveTarget.ts:14:44)
    at Function.buildAsyncTargets (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
    at MacPackager.packageInDistributableFormat (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
    at nonMasPromise.then.then (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/macPackager.ts:90:26)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:159:5)
From previous event:
    at Packager.doBuild (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Packager.build (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/app-builder-lib/src/index.ts:58:28)
    at Object.build (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/electron-builder/src/builder.ts:227:10)
    at bundle.run (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/vue-cli-plugin-electron-builder/index.js:164:12)
    at finalCallback (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/webpack/lib/Compiler.js:210:39)
    at hooks.done.callAsync.err (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/webpack/lib/Compiler.js:259:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/tapable/lib/Hook.js:35:21)
    at emitRecords.err (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/webpack/lib/Compiler.js:257:22)
    at Compiler.emitRecords (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/webpack/lib/Compiler.js:372:39)
    at emitAssets.err (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/webpack/lib/Compiler.js:251:10)
    at hooks.afterEmit.callAsync.err (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/webpack/lib/Compiler.js:358:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/tapable/lib/Hook.js:35:21)
    at asyncLib.forEach.err (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/webpack/lib/Compiler.js:355:27)
    at done (/Users/pksunkara/Coding/pksunkara/dotsync/node_modules/neo-async/async.js:2854:11)
    at /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/neo-async/async.js:2805:7
    at /Users/pksunkara/Coding/pksunkara/dotsync/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:145:20)

✨  Done in 33.29s.
```

**Comment by pksunkara** [comment]
Does the scoped package names have an issue? I don't understand why I am unable to build.

**Comment by pksunkara** [comment]
My app's package.json was named `@dotsync/app` in which the `@` was the issue. I configured the `productName` to `Dotsync` and it fixed the issue.
