### ISSUE TITLE
Building snap fails with error "FileNotFoundError: [Errno 2] No such file or directory: 'sudo'"

### ISSUE THREAD

**Issue by ghost** [electron-userland/electron-builder#3231]
* **Version**: 20.27.1

* **Target**: linux (snap)

The host OS is macOS High Sierra.

I am trying to build a snap.

Running the command `electron-builder -l` fails with following error
```
  • electron-builder version=20.27.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release/builder-effective-config.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • rebuilding native dependency name=grpc
  • rebuilding native dependency name=realm
  • packaging       platform=linux arch=x64 electron=1.8.7 appOutDir=release/linux-unpacked
  • building        target=snap arch=x64 file=release/app_0.0.1_amd64.snap
Setting target machine to 'amd64'
Installing build dependencies: gir1.2-gtk-2.0 libgtk2.0-dev libxml2-utils
Downloading parts list
Sorry, Snapcraft ran into an error when trying to running through its
lifecycle that generated the following traceback:
Traceback (most recent call last):
  File "/snap/snapcraft/current/bin/snapcraft", line 11, in <module>
    load_entry_point('snapcraft==2.42.1', 'console_scripts', 'snapcraft')()
  File "/snap/snapcraft/current/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/snapcraft/current/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/snapcraft/current/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/snapcraft/current/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/snapcraft/current/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/snapcraft/current/lib/python3.5/site-packages/snapcraft/cli/lifecycle.py", line 113, in prime
    _execute(steps.PRIME, parts, **kwargs)
  File "/snap/snapcraft/current/lib/python3.5/site-packages/snapcraft/cli/lifecycle.py", line 33, in _execute
    lifecycle.execute(step, project_config, parts)
  File "/snap/snapcraft/current/lib/python3.5/site-packages/snapcraft/internal/lifecycle/_runner.py", line 69, in execute
    installed_packages = repo.Repo.install_build_packages(project_config.build_tools)
  File "/snap/snapcraft/current/lib/python3.5/site-packages/snapcraft/internal/repo/_deb.py", line 272, in install_build_packages
    cls._install_new_build_packages([package[0] for package in new_packages])
  File "/snap/snapcraft/current/lib/python3.5/site-packages/snapcraft/internal/repo/_deb.py", line 331, in _install_new_build_packages
    subprocess.check_call(apt_command + package_names, env=env)
  File "/snap/snapcraft/current/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/snap/snapcraft/current/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/snap/snapcraft/current/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/snap/snapcraft/current/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo'
  ⨯ exit status 1
github.com/develar/app-builder/pkg/util.ExecuteWithInheritedStdOutAndStdErr
        /Users/develar/go/src/github.com/develar/app-builder/pkg/util/util.go:55
github.com/develar/app-builder/pkg/snap.buildUsingDocker
        /Users/develar/go/src/github.com/develar/app-builder/pkg/snap/snap.go:364
github.com/develar/app-builder/pkg/snap.Snap
        /Users/develar/go/src/github.com/develar/app-builder/pkg/snap/snap.go:220
github.com/develar/app-builder/pkg/snap.ConfigureCommand.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/snap/snap.go:102
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:72
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Error: /Users/user/directory/node_modules/app-builder-bin/mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/user/directory/node_modules/builder-util/src/util.ts:254:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at SnapTarget.build (/Users/user/directory/node_modules/app-builder-lib/src/targets/snap.ts:143:44)
    at Function.buildAsyncTargets (/Users/user/directory/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
    at LinuxPackager.packageInDistributableFormat (/Users/user/directory/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
    at /Users/user/directory/node_modules/app-builder-lib/src/platformPackager.ts:113:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at LinuxPackager.pack (/Users/user/directory/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /Users/user/directory/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/user/directory/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/user/directory/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/user/directory/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /Users/user/directory/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /Users/user/directory/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/user/directory/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/user/directory/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /Users/user/directory/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/Users/user/directory/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/Users/user/directory/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/Users/user/directory/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/user/directory/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at <anonymous>
error An unexpected error occurred: "Command failed.
Exit code: 1
```

Relevant part of `package.json`
```javascript
  "build": {
    "linux": {
      "target": [
        "snap"
      ]
    },
  }
```

**Comment by hackjutsu** [comment]
I'm running into the exact same issue with version `20.28.2` when trying to build a snap package. My relevant part of `package.json` is 
```
"build": {
    "linux": {
      "category": "Development",
      "target": [
        "AppImage",
        "snap"
      ]
    }
}
```

**Comment by stephen-goveia** [comment]
Yes running into this issue as well. Same setup as @iaaflaafc.

**Comment by spiral2k** [comment]
have the same problem, somebody have an idea to fix this?
