### ISSUE TITLE
Error: Cannot cleanup http error:401 unauthorized

### ISSUE THREAD

**Issue by serverLua** [electron-userland/electron-builder#3237]
* **Version**: 20.27.1

* **Target**: windows

HttpError: 401 Unauthorized
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
Headers: {
  "server": "GitHub.com",
  "date": "Mon, 13 Aug 2018 20:24:41 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "83",
  "connection": "close",
  "status": "401 Unauthorized",
  "x-github-media-type": "github.v3; format=json",
  "x-ratelimit-limit": "60",
  "x-ratelimit-remaining": "58",
  "x-ratelimit-reset": "1534194215",
  "access-control-expose-headers": "ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval",
  "access-control-allow-origin": "*",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "content-security-policy": "default-src 'none'",
  "x-runtime-rack": "0.017764",
  "x-github-request-id": "0420:604D:9579A:135CBD:5B71E909"
}
    at createHttpError (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:32:10)
    at IncomingMessage.stream.on (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:171:18)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at CancellationToken.createPromise (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at NodeHttpExecutor.doApiRequest (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at NodeHttpExecutor.request (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at GitHubPublisher.githubRequest (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:245:35)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:91:33
    at Generator.next (<anonymous>)
From previous event:
    at GitHubPublisher.getOrCreateRelease (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:84:35)
    at Lazy.GitHubPublisher._release (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:30:102)
    at Lazy.get value [as value] (C:\projects\soda-markdown\node_modules\lazy-val\src\main.ts:18:23)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:164:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubPublisher.doUpload (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:163:160)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\publisher.ts:86:16
    at Generator.next (<anonymous>)
    at C:\projects\soda-markdown\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at GitHubPublisher.upload (C:\projects\soda-markdown\node_modules\electron-publish\src\publisher.ts:75:32)
    at PublishManager.scheduleUpload (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:148:7)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:175:11
From previous event:
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:182:5)
    at EventEmitter.PublishManager.packager.artifactCreated.event (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:107:36)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at Packager.dispatchArtifactCreated (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:235:23)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\differentialUpdateInfoBuilder.ts:73:17
From previous event:
    at createBlockmap (C:\projects\soda-markdown\node_modules\app-builder-lib\out\targets\differentialUpdateInfoBuilder.js:125:18)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:261:30
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at NsisTarget.buildInstaller (C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:274:7)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\out\targets\nsis\NsisTarget.js:328:22
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:111:6)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:384:36
From previous event:
    at Packager.doBuild (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:344:39)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:314:57
From previous event:
    at Packager._build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:285:133)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (C:\projects\soda-markdown\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\projects\soda-markdown\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>

and error 2
HttpError: 401 Unauthorized
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
Headers: {
  "server": "GitHub.com",
  "date": "Mon, 13 Aug 2018 20:24:41 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "83",
  "connection": "close",
  "status": "401 Unauthorized",
  "x-github-media-type": "github.v3; format=json",
  "x-ratelimit-limit": "60",
  "x-ratelimit-remaining": "58",
  "x-ratelimit-reset": "1534194215",
  "access-control-expose-headers": "ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval",
  "access-control-allow-origin": "*",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "content-security-policy": "default-src 'none'",
  "x-runtime-rack": "0.017764",
  "x-github-request-id": "0420:604D:9579A:135CBD:5B71E909"
}
    at createHttpError (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:32:10)
    at IncomingMessage.stream.on (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:171:18)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at CancellationToken.createPromise (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at NodeHttpExecutor.doApiRequest (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at NodeHttpExecutor.request (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at GitHubPublisher.githubRequest (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:245:35)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:91:33
    at Generator.next (<anonymous>)
From previous event:
    at GitHubPublisher.getOrCreateRelease (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:84:35)
    at Lazy.GitHubPublisher._release (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:30:102)
    at Lazy.get value [as value] (C:\projects\soda-markdown\node_modules\lazy-val\src\main.ts:18:23)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:164:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubPublisher.doUpload (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:163:160)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\publisher.ts:86:16
    at Generator.next (<anonymous>)
    at C:\projects\soda-markdown\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at GitHubPublisher.upload (C:\projects\soda-markdown\node_modules\electron-publish\src\publisher.ts:75:32)
    at PublishManager.scheduleUpload (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:148:7)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:175:11
From previous event:
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:182:5)
    at EventEmitter.PublishManager.packager.artifactCreated.event (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:107:36)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at Packager.dispatchArtifactCreated (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:235:23)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\differentialUpdateInfoBuilder.ts:73:17
From previous event:
    at createBlockmap (C:\projects\soda-markdown\node_modules\app-builder-lib\out\targets\differentialUpdateInfoBuilder.js:125:18)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:261:30
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at NsisTarget.buildInstaller (C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:274:7)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\out\targets\nsis\NsisTarget.js:328:22
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:111:6)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:384:36
From previous event:
    at Packager.doBuild (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:344:39)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:314:57
From previous event:
    at Packager._build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:285:133)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (C:\projects\soda-markdown\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\projects\soda-markdown\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
    at createHttpError (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:32:10)
    at IncomingMessage.stream.on (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:171:18)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at CancellationToken.createPromise (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at NodeHttpExecutor.doApiRequest (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at NodeHttpExecutor.request (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at GitHubPublisher.githubRequest (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:245:35)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:91:33
    at Generator.next (<anonymous>)
    at GitHubPublisher.getOrCreateRelease (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:84:35)
    at Lazy.GitHubPublisher._release (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:30:102)
    at Lazy.get value [as value] (C:\projects\soda-markdown\node_modules\lazy-val\src\main.ts:18:23)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:164:41
    at Generator.next (<anonymous>)
    at GitHubPublisher.doUpload (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:163:160)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\publisher.ts:86:16
    at Generator.next (<anonymous>)
    at C:\projects\soda-markdown\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
    at GitHubPublisher.upload (C:\projects\soda-markdown\node_modules\electron-publish\src\publisher.ts:75:32)
    at PublishManager.scheduleUpload (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:148:7)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:175:11
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:182:5)
    at EventEmitter.PublishManager.packager.artifactCreated.event (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:107:36)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at Packager.dispatchArtifactCreated (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:235:23)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\differentialUpdateInfoBuilder.ts:73:17
    at createBlockmap (C:\projects\soda-markdown\node_modules\app-builder-lib\out\targets\differentialUpdateInfoBuilder.js:125:18)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:261:30
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at NsisTarget.buildInstaller (C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:274:7)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\out\targets\nsis\NsisTarget.js:328:22
    at Generator.next (<anonymous>)
    at NsisTarget.finishBuild (C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:111:6)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:384:36
    at Packager.doBuild (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:344:39)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:314:57
    at Packager._build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:285:133)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at Packager.build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (C:\projects\soda-markdown\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\projects\soda-markdown\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
    at createHttpError (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:32:10)
    at IncomingMessage.stream.on (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:171:18)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at CancellationToken.createPromise (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at NodeHttpExecutor.doApiRequest (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at NodeHttpExecutor.request (C:\projects\soda-markdown\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at GitHubPublisher.githubRequest (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:245:35)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:91:33
    at Generator.next (<anonymous>)
    at GitHubPublisher.getOrCreateRelease (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:84:35)
    at Lazy.GitHubPublisher._release (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:30:102)
    at Lazy.get value [as value] (C:\projects\soda-markdown\node_modules\lazy-val\src\main.ts:18:23)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:164:41
    at Generator.next (<anonymous>)
    at GitHubPublisher.doUpload (C:\projects\soda-markdown\node_modules\electron-publish\src\gitHubPublisher.ts:163:160)
    at C:\projects\soda-markdown\node_modules\electron-publish\src\publisher.ts:86:16
    at Generator.next (<anonymous>)
    at C:\projects\soda-markdown\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
    at GitHubPublisher.upload (C:\projects\soda-markdown\node_modules\electron-publish\src\publisher.ts:75:32)
    at PublishManager.scheduleUpload (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:148:7)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:175:11
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:182:5)
    at EventEmitter.PublishManager.packager.artifactCreated.event (C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:107:36)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at Packager.dispatchArtifactCreated (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:235:23)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\differentialUpdateInfoBuilder.ts:73:17
    at createBlockmap (C:\projects\soda-markdown\node_modules\app-builder-lib\out\targets\differentialUpdateInfoBuilder.js:125:18)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:261:30
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at NsisTarget.buildInstaller (C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:274:7)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\out\targets\nsis\NsisTarget.js:328:22
    at Generator.next (<anonymous>)
    at NsisTarget.finishBuild (C:\projects\soda-markdown\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:111:6)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:384:36
    at Packager.doBuild (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:344:39)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:314:57
    at Packager._build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:285:133)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at Packager.build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (C:\projects\soda-markdown\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\projects\soda-markdown\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
    at throwError (C:\projects\soda-markdown\node_modules\builder-util\src\asyncTaskManager.ts:90:11)
    at checkErrors (C:\projects\soda-markdown\node_modules\builder-util\src\asyncTaskManager.ts:53:9)
    at C:\projects\soda-markdown\node_modules\builder-util\src\asyncTaskManager.ts:67:7
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at AsyncTaskManager.awaitTasks (C:\projects\soda-markdown\node_modules\builder-util\src\asyncTaskManager.ts:44:19)
    at C:\projects\soda-markdown\node_modules\app-builder-lib\src\publish\PublishManager.ts:207:19
    at Generator.next (<anonymous>)
From previous event:
    at PublishManager.awaitTasks (C:\projects\soda-markdown\node_modules\app-builder-lib\out\publish\PublishManager.js:558:7)
    at isErrorOccurred (C:\projects\soda-markdown\node_modules\app-builder-lib\src\index.ts:92:32)
    at C:\projects\soda-markdown\node_modules\builder-util\src\promise.ts:25:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at executeFinally (C:\projects\soda-markdown\node_modules\builder-util\out\promise.js:60:17)
    at build (C:\projects\soda-markdown\node_modules\app-builder-lib\src\index.ts:85:10)
    at build (C:\projects\soda-markdown\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\projects\soda-markdown\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>

**Comment by serverLua** [comment]
this is a appveyor build log

**Comment by joehehir** [comment]
@serverLua The "Personal access token" for repository access may be invalid, try generating a new one and replacing it in your `electron-builder.yml` or wherever you keep it.

**Comment by HuaRongSAO** [comment]
How did you solve this problem？ t-t

**Comment by joehehir** [comment]
@HuaRongSAO The properties `HttpError: 401 Unauthorized` and `server: "GitHub.com"` indicate that we’re attempting to access or perform an action on GitHub that requires authentication. electron-builder uses a "Personal access token" to gain authorization to perform actions like creating releases. A little further down the error log we can see “GitHubPublisher.getOrCreateRelease…” which is an action that requires authorization. I hope this helps :+1:

**Comment by JDPCraddock** [comment]
@serverLua Any chance you could elaborate on this? I'm having this issue as well.

**Comment by KsRyY** [comment]
@JDPCraddock If you are using travis or appveyor, just check out if you had encrypted your token but forgot to enable decrypt feature on your build site

**Comment by edelCustodio** [comment]
Hi, @KsRyY how to do this? any file example? also, how I can set the GitHub token? as a local environment variable? or set a password on GitHub global credentials

**Comment by ustc-mjc** [comment]
> I have already solve this problem, it's beacuse of I froget to open the encrypt/decrypt

can you tell me how to do that? Thanks!

**Comment by ianchanning** [comment]
I'm adding this here as it's the first hit I get when I Google `electron builder publish github token 401 "Bad credentials"`

I got this error:

```
GH_TOKEN=ghp_xxxxx npm run publish:win
> my-app/desktop@1.0.4 publish:win
> electron-builder --win --publish always

  • electron-builder  version=23.6.0 os=6.2.6-76060206-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=24.1.3 appOutDir=dist/win-unpacked
  • building        target=nsis file=dist/myapp_1.0.4.exe archs=x64 oneClick=true perMachine=false
  • building block map  blockMapFile=dist/myapp_1.0.4.exe.blockmap
  • publishing      publisher=Github (owner: my.org, project: kiosk-app, version: 1.0.4)
  • uploading       file=myapp_1.0.4.exe.blockmap provider=github
  • uploading       file=myapp_1.0.4.exe provider=github
  ⨯ Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
HttpError: 401 Unauthorized
"method: GET url: https://api.github.com/repos/my.org/my-app/releases

          Data:
          {\"message\":\"Bad credentials\",\"documentation_url\":\"https://docs.github.com/rest\"}
          "
```

My `GH_TOKEN` was ok but it showed that it hadn't been used.

I eventually tracked it down to a subtle problem with the `owner` config.

```json
    "publish": [
      {
        "provider": "github",
        "repo": "my-app",
        "owner": "my.org",
        "private": true,
        "releaseType": "release"
      }
    ],
```

I had the `owner` as the company domain name `my.org`, where as it needs to be the URL path to your organisation in Github `https://github.com/my-org`

So my publish was trying to release to `https://api.github.com/repos/my.org/my-app/releases` instead of `https://api.github.com/repos/my-org/my-app/releases` just a one character diff.
