### ISSUE TITLE
Error: node_modules license file must be in build root dir

### ISSUE THREAD

**Issue by tangb** [electron-userland/electron-builder#3238]
* **Version**: 
electron-builder@20.22.1
electron@2.0.7

* **Target**: 
win10 pro + linux64

I can't build my app because of supposed sentry file at wrong place (I guess):
```
  • electron-builder version=20.22.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build/cleepdesktop_tree/dist/builder-effective-config.yaml
  • installing production dependencies platform=linux arch=x64 appDir=/home/osboxes/CleepDesktop/build/cleepdesktop_tree
  • packaging       platform=linux arch=x64 electron=2.0.7 appOutDir=build/cleepdesktop_tree/dist/linux-unpacked
Error: /home/osboxes/CleepDesktop/node_modules/@sentry/core/LICENSE must be under /home/osboxes/CleepDesktop/build/cleepdesktop_tree/
    at AsarPackager.unpackPattern (/home/osboxes/CleepDesktop/node_modules/electron-builder-lib/src/util/filter.ts:37:13)
    at /home/osboxes/CleepDesktop/node_modules/electron-builder-lib/src/asar/asarUtil.ts:116:82
```
I supposed it was a problem on sentry package but it seems specified file exists.
In fact i found this problem jumping from 20.10.0 to 20.27.1. So I tryed all version until it works and the problem appears migrating from 20.22.0 to 20.22.1.

But changes between those versions seem not related to my problem :
```
do not remove GitHub's releaseType attribute from the publish configuration (7f529ff), closes #2971 #2994
```

Can you give me some clue for investigation ?

Thank you very much

**Comment by VelGenov** [comment]
I'm experiencing a similar problem. I'm building all my targets on a OSX, and this started happening when I added Sentry.io to my project. The problem is very specific to building the Windows MSI target, and it's not fixed in the patch linked above. My exact configuration is below.

OSX: 10.14.3
electron-builder version: 20.38.5
sentry/cli version: 1.39.0
sentry/electron version: 0.15.0
sentry/webpack-plugin version: 1.6.2

This is the error I get:

`error output:Z:\Users\Vel\Documents\Projects\electron-desktop\release\__msi-ia32\project.wxs(154) : error LGHT0103 : The system cannot find the file 'Z:\Users\Vel\Documents\Projects\electron-desktop\release\win-ia32-unpacked\resources\app.asar.unpacked\node_modules\@sentry\cli\LICENSE'.`
