### ISSUE TITLE
Import UpdateInfo & CancellationToken

### ISSUE THREAD

**Issue by sqwk** [electron-userland/electron-builder#3251]
I am just updated to the following versions:

        "electron": "2.0.7",
        "electron-builder": "20.28.1",
        "electron-builder-squirrel-windows": "20.28.0",
        "electron-updater": "2.1.1",

from these previous versions:

        "electron": "2.0.2",
        "electron-builder": "20.15.1",
        "electron-builder-squirrel-windows": "20.15.0",
        "electron-updater": "2.21.10",

UpdateInfo and CancellationToken can no longer be imported like so: 

        import { UpdateInfo, CancellationToken } from 'electron-updater';

Where should they be imported from now?

**Comment by leonardochaia** [comment]
I think I may be experiencing a similar issue:

```typescript
import { CancellationToken } from 'electron-updater';
// also, vsCode auto import suggests the below which produces the same error.
// import { CancellationToken } from 'builder-util-runtime';

const cancellationToken = new CancellationToken();
this.autoUpdater.downloadUpdate(cancellationToken);
```

```
C:\timoneer\node_modules\electron\dist\resources\electron.asar\common\api\callbacks-registry.js:47 Cannot download differentially, fallback to full download: TypeError: cancellationToken.createPromise is not a function
    at ElectronHttpExecutor.doApiRequest (C:\timoneer\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (C:\timoneer\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at C:\timoneer\node_modules\electron-updater\src\NsisUpdater.ts:149:46
    at Generator.next (<anonymous>)
From previous event:
    at downloadBlockMap (C:\timoneer\node_modules\electron-updater\src\NsisUpdater.ts:146:13)
    at C:\timoneer\node_modules\electron-updater\src\NsisUpdater.ts:162:34
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.differentialDownloadInstaller (C:\timoneer\node_modules\electron-updater\src\NsisUpdater.ts:140:210)
    at Object.<anonymous> (C:\timoneer\node_modules\electron-updater\src\NsisUpdater.ts:32:42)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (C:\timoneer\node_modules\electron-updater\src\NsisUpdater.ts:29:7)
    at C:\timoneer\node_modules\electron-updater\src\AppUpdater.ts:570:25
    at Generator.throw (<anonymous>)
From previous event:
    at NsisUpdater.executeDownload (C:\timoneer\node_modules\electron-updater\src\AppUpdater.ts:487:68)
    at NsisUpdater.executeDownload (C:\timoneer\node_modules\electron-updater\src\BaseUpdater.ts:28:18)
    at C:\timoneer\node_modules\electron-updater\src\NsisUpdater.ts:25:23
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\timoneer\node_modules\electron-updater\src\NsisUpdater.ts:22:80)
    at C:\timoneer\node_modules\electron-updater\src\AppUpdater.ts:393:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at NsisUpdater.downloadUpdate (C:\timoneer\node_modules\electron-updater\src\AppUpdater.ts:382:86)
    at callFunction (C:\timoneer\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:249:18)
    at EventEmitter.<anonymous> (C:\timoneer\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\timoneer\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
```

```json
    "electron-updater": "^3.1.1"
    "electron": "^2.0.7",
    "electron-builder": "^20.27.1",
```

**Comment by sqwk** [comment]
This seems to work:

    import { CancellationToken } from 'electron-builder-http/out/CancellationToken';
    import { UpdateInfo } from 'builder-util-runtime';

Doesn't seem very intuitive, though.
