### ISSUE TITLE
7za.exe exited with code 2: Can not open the file as archive

### ISSUE THREAD

**Issue by momocow** [electron-userland/electron-builder#3255]
Cannot figure out what caused this problem 😞 
I tried to execute the command manually and no error happened.

BTW, I am using Win10 along with Node v10.5.0 to build executable.

Need some helps, thank you.

* **Version**: 20.28.1

* **Target**: win

```
Exit code: 2. Command failed: Z:\<project_root>\node_modules\7zip-bin\win\x64\7za.exe a -bd -mx=9 -mtc=off -mtm=off -mta=off Z:\<project_root>\dist\tukiyomi-v0.0.0-local.7z .
ERROR: Z:\<project_root>\dist\tukiyomi-v0.0.0-local.7z
Can not open the file as archive



System ERROR:
�{�ǵL�k�s���ɮסA�]���ɮץ��ѥt�@�ӵ{�ǨϥΡC


7-Zip (a) 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28

Open archive: Z:\<project_root>\dist\tukiyomi-v0.0.0-local.7z

ERROR: Z:\<project_root>\dist\tukiyomi-v0.0.0-local.7z
Can not open the file as archive



System ERROR:
�{�ǵL�k�s���ɮסA�]���ɮץ��ѥt�@�ӵ{�ǨϥΡC

    at Z:\<project_root>\node_modules\builder-util\src\util.ts:128:16
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:460:23)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
From previous event:
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at archive (Z:\<project_root>\node_modules\app-builder-lib\out\targets\archive.js:226:18)
    at Z:\<project_root>\node_modules\app-builder-lib\src\targets\ArchiveTarget.ts:53:13
    at Generator.next (<anonymous>)
From previous event:
    at ArchiveTarget.build (Z:\<project_root>\node_modules\app-builder-lib\src\targets\ArchiveTarget.ts:15:44)
    at Function.buildAsyncTargets (Z:\<project_root>\node_modules\app-builder-lib\src\platformPackager.ts:139:36)
    at WinPackager.packageInDistributableFormat (Z:\<project_root>\node_modules\app-builder-lib\src\platformPackager.ts:118:24)
    at Z:\<project_root>\node_modules\app-builder-lib\src\platformPackager.ts:113:10
From previous event:
    at WinPackager.pack (Z:\<project_root>\node_modules\app-builder-lib\src\platformPackager.ts:110:95)
    at Z:\<project_root>\node_modules\app-builder-lib\src\packager.ts:376:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Packager.doBuild (Z:\<project_root>\node_modules\app-builder-lib\src\packager.ts:344:39)
    at Z:\<project_root>\node_modules\app-builder-lib\src\packager.ts:314:57
    at Generator.next (<anonymous>)
    at Z:\<project_root>\node_modules\graceful-fs\graceful-fs.js:99:16
    at Z:\<project_root>\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (Z:\<project_root>\node_modules\app-builder-lib\src\packager.ts:285:133)
    at Z:\<project_root>\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Packager.build (Z:\<project_root>\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (Z:\<project_root>\node_modules\app-builder-lib\src\index.ts:58:28)
    at Object.build (Z:\<project_root>\node_modules\electron-builder\src\builder.ts:227:10)
    at module.exports (Z:\<project_root>\build\scripts\build.js:7:18)
    at configBuild (Z:\<project_root>\gulpfile.js:86:10)
    at taskWrapper (Z:\<project_root>\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at asyncRunner (Z:\<project_root>\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by momocow** [comment]
I change my artifact name from `${productName}-v${version}.${ext}` to `${productName}-v${version}-${os}-${arch}.${ext}` and the problem is solved!

It was the race condition on `<project-name>-v0.0.0.7z` since both builds for Windows ia32 and Windows x64 were trying to write to `<project-name>-v0.0.0.7z`.

Now, there are `<project-name>-v0.0.0-win.7z` and `<project-name>-v0.0.0-ia32-win.7z`.
Therefore, no more race conditions.

😄
