### ISSUE TITLE
Publish succeeds but still throws error

### ISSUE THREAD

**Issue by teken** [electron-userland/electron-builder#3266]
* **Version**: 20.26.0

* **Target**: linux

Here is the output, I'm not sure what error is supposed to be throwing as it is publishing fine.
```
yarn run release
yarn run v1.9.2
$ electron-builder --publish always
  • electron-builder version=20.26.0
  • loaded configuration file=package.json ("build" field)
  • loaded parent configuration preset=react-cra
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=1.8.7 appOutDir=dist/linux-unpacked
[34m  •[0m downloading               [34mparts[0m=8 [34msize[0m=47 MB [34murl[0m=https://github.com/electron/electron/releases/download/v1.8.7/electron-v1.8.7-linux-x64.zip
[34m  •[0m downloading               [34mparts[0m=1 [34msize[0m=5.7 kB [34murl[0m=https://github.com/electron/electron/releases/download/v1.8.7/SHASUMS256.txt
  • building        target=snap arch=x64 file=dist/programname_0.1.4_amd64.snap
  • building        target=AppImage arch=x64 file=dist/programname-0.1.4-x86_64.AppImage
[34m  •[0m downloading               [34mpath[0m=/root/.cache/electron-builder/appimage/appimage-9.1.0 [34murl[0m=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-9.1.0/appimage-9.1.0.7z
[31m  ⨯[0m snapcraft is not installed, please: sudo snap install snapcraft --classic
[34m  •[0m downloading               [34mparts[0m=1 [34msize[0m=1.5 MB [34murl[0m=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-9.1.0/appimage-9.1.0.7z
  • publishing      publisher=S3 (bucket: programname)
  • uploading       file=programname-0.1.4-x86_64.AppImage provider=S3
Error: /tmp/cirrus-ci-build/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/tmp/cirrus-ci-build/node_modules/app-builder-lib/node_modules/builder-util/src/util.ts:251:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
From previous event:
    at SnapTarget.build (/tmp/cirrus-ci-build/node_modules/app-builder-lib/src/targets/snap.ts:143:44)
    at Function.buildAsyncTargets (/tmp/cirrus-ci-build/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
    at LinuxPackager.packageInDistributableFormat (/tmp/cirrus-ci-build/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
    at /tmp/cirrus-ci-build/node_modules/app-builder-lib/src/platformPackager.ts:113:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
From previous event:
    at LinuxPackager.pack (/tmp/cirrus-ci-build/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /tmp/cirrus-ci-build/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/tmp/cirrus-ci-build/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:139:20)
From previous event:
    at Packager.doBuild (/tmp/cirrus-ci-build/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /tmp/cirrus-ci-build/node_modules/app-builder-lib/src/packager.ts:314:57
From previous event:
    at Packager._build (/tmp/cirrus-ci-build/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /tmp/cirrus-ci-build/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
From previous event:
    at Packager.build (/tmp/cirrus-ci-build/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/tmp/cirrus-ci-build/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/tmp/cirrus-ci-build/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/tmp/cirrus-ci-build/node_modules/electron-builder/src/cli/cli.ts:42:48)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by benjamincburns** [comment]
I'm seeing this issue as well. My build log is available here (includes debug output): https://ci.appveyor.com/project/trufflesuite/ganache/build/29

All build files were added to my draft release successfully. Relevant output is copied below - build process terminated after this, so this was the last of the output from the build process.

```
  ΓÇó uploading       file=ganache-setup-1.2.2.exe.blockmap provider=GitHub
  ΓÇó uploading       file=ganache-setup-1.2.2.exe provider=GitHub
2018-08-22T20:39:40.018Z electron-builder Request: {
  "hostname": "uploads.github.com",
  "path": "/repos/trufflesuite/ganache/releases/12510955/assets?name=ganache-setup-1.2.2.exe.blockmap",
  "method": "POST",
  "headers": {
    "Accept": "application/vnd.github.v3+json",
    "Content-Type": "application/octet-stream",
    "Content-Length": 62993,
    "authorization": "<stripped sensitive data>",
    "User-Agent": "electron-builder",
    "Cache-Control": "no-cache"
  }
}
2018-08-22T20:39:40.020Z electron-builder Request: {
  "hostname": "uploads.github.com",
  "path": "/repos/trufflesuite/ganache/releases/12510955/assets?name=ganache-setup-1.2.2.exe",
  "method": "POST",
  "headers": {
    "Accept": "application/vnd.github.v3+json",
    "Content-Type": "application/octet-stream",
    "Content-Length": 58966320,
    "authorization": "<stripped sensitive data>",
    "User-Agent": "electron-builder",
    "Cache-Control": "no-cache"
  }
}
2018-08-22T20:39:40.342Z electron-builder Response: 201 Created, request options: {
  "hostname": "uploads.github.com",
  "path": "/repos/trufflesuite/ganache/releases/12510955/assets?name=ganache-setup-1.2.2.exe.blockmap",
  "method": "POST",
  "headers": {
    "Accept": "application/vnd.github.v3+json",
    "Content-Type": "application/octet-stream",
    "Content-Length": 62993,
    "authorization": "<stripped sensitive data>",
    "User-Agent": "electron-builder",
    "Cache-Control": "no-cache"
  }
}
2018-08-22T20:40:01.139Z electron-builder Response: 201 Created, request options: {
  "hostname": "uploads.github.com",
  "path": "/repos/trufflesuite/ganache/releases/12510955/assets?name=Ganache-1.2.2.appx",
  "method": "POST",
  "headers": {
    "Accept": "application/vnd.github.v3+json",
    "Content-Type": "application/octet-stream",
    "Content-Length": 91104519,
    "authorization": "<stripped sensitive data>",
    "User-Agent": "electron-builder",
    "Cache-Control": "no-cache"
  }
}
2018-08-22T20:40:16.141Z electron-builder Response: 201 Created, request options: {
  "hostname": "uploads.github.com",
  "path": "/repos/trufflesuite/ganache/releases/12510955/assets?name=ganache-setup-1.2.2.exe",
  "method": "POST",
  "headers": {
    "Accept": "application/vnd.github.v3+json",
    "Content-Type": "application/octet-stream",
    "Content-Length": 58966320,
    "authorization": "<stripped sensitive data>",
    "User-Agent": "electron-builder",
    "Cache-Control": "no-cache"
  }
}
2018-08-22T20:40:16.274Z electron-builder Request: {
  "hostname": "uploads.github.com",
  "path": "/repos/trufflesuite/ganache/releases/12510955/assets?name=latest.yml",
  "method": "POST",
  "headers": {
    "Accept": "application/vnd.github.v3+json",
    "Content-Type": "text/yaml",
    "Content-Length": 413,
    "authorization": "<stripped sensitive data>",
    "User-Agent": "electron-builder",
    "Cache-Control": "no-cache"
  }
}
2018-08-22T20:40:16.831Z electron-builder Response: 201 Created, request options: {
  "hostname": "uploads.github.com",
  "path": "/repos/trufflesuite/ganache/releases/12510955/assets?name=latest.yml",
  "method": "POST",
  "headers": {
    "Accept": "application/vnd.github.v3+json",
    "Content-Type": "text/yaml",
    "Content-Length": 413,
    "authorization": "<stripped sensitive data>",
    "User-Agent": "electron-builder",
    "Cache-Control": "no-cache"
  }
}
Command executed with exception: 2018-08-22T20:40:16.831Z electron-builder Response: 201 Created, request options: {
  "hostname": "uploads.github.com",
  "path": "/repos/trufflesuite/ganache/releases/12510955/assets?name=latest.yml",
  "method": "POST",
  "headers": {
    "Accept": "application/vnd.github.v3+json",
    "Content-Type": "text/yaml",
    "Content-Length": 413,
    "authorization": "<stripped sensitive data>",
    "User-Agent": "electron-builder",
    "Cache-Control": "no-cache"
  }
}
```

**Comment by benjamincburns** [comment]
Same result after updating to 20.28.2.

https://ci.appveyor.com/project/trufflesuite/ganache/build/33
