### ISSUE TITLE
Error: No update available, can't quit and install

### ISSUE THREAD

**Issue by K-Wen** [electron-userland/electron-builder#3269]
* **Version**: 
"electron-builder": "^20.28.2"

"electron-updater": "^3.1.1"

* **Target**: 
Mac

Recently I updated electron-builder from ^19.19.1 to the lastest version, ^19.19.1  worked very well but the lastest version failed.
I see the log show follows:
`

2018-08-22 17:10:01:838 info:Update has already been downloaded to /Users/mymac/Library/Application Support/MyApp/__update__/myapp-2.1.0.zip).
2018-08-22 17:10:01:848 warn:Error: **No update available, can't quit and install**
`
I saw the updates has been downloaded, but it can not be installed.
Look forward to your favourable reply.

**Comment by TomRomanowski** [comment]
Glad to see I'm not the only one having this same exact issue

**Comment by ozooner** [comment]
Same issue here:
electron-updater: 3.1.2
electron-builder: 20.28.3
```
[09-01-2018 17:56:06.054] (info) Download speed: 4881006 - Downloaded 9.59166761240812% (4885887/50938869)
[09-01-2018 17:56:07.055] (info) Download speed: 5427587 - Downloaded 21.331508165208774% (10866029/50938869)
[09-01-2018 17:56:08.056] (info) Download speed: 5609793 - Downloaded 33.07141939095664% (16846207/50938869)
[09-01-2018 17:56:09.057] (info) Download speed: 5700886 - Downloaded 44.81125994375729% (22826349/50938869)
[09-01-2018 17:56:10.059] (info) Download speed: 5754400 - Downloaded 56.55117116950515% (28806527/50938869)
[09-01-2018 17:56:11.061] (info) Download speed: 5790058 - Downloaded 68.29101172230581% (34786669/50938869)
[09-01-2018 17:56:12.062] (info) Download speed: 5816357 - Downloaded 80.03092294805367% (40766847/50938869)
[09-01-2018 17:56:13.063] (info) Download speed: 5836079 - Downloaded 91.77076350085433% (46746989/50938869)
[09-01-2018 17:56:13.763] (info) Download speed: 5848320 - Downloaded 100% (50938869/50938869)
[09-01-2018 17:56:13.779] (info) New version 1.11.2 has been downloaded to /Users/myelectron/Library/Application Support/myelectron/__update__/myelectron-1.11.2-mac.zip
[09-01-2018 17:56:13.783] (info) Update downloaded, exiting application to install update...
[09-01-2018 17:56:13.956] (warn) Error: No update available, can't quit and install

[09-01-2018 17:56:13.957] (error) Error: Error: No update available, can't quit and install
[09-01-2018 17:56:13.957] (error) Error during updating
[09-01-2018 17:56:13.958] (error) Error: No update available, can't quit and install

[09-01-2018 17:56:13.961] (info) Window closed
[09-01-2018 17:56:13.970] (error) Error: Error: No update available, can't quit and install
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Object.done (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:46:11)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:530:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at done (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:523:15)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:584:18
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at MacUpdater.executeDownload (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:487:68)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:39:23
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:22:80)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:393:25
From previous event:
    at MacUpdater.downloadUpdate (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:382:86)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:369:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at MacUpdater.checkForUpdates (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at EventEmitter.<anonymous> (/Applications/myelectron.app/Contents/Resources/app.asar/main.js:224:15)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at WebContents.<anonymous> (/Applications/myelectron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
[09-01-2018 17:56:13.971] (error) Error during updating
[09-01-2018 17:56:13.971] (error) Error: No update available, can't quit and install
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Object.done (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:46:11)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:530:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at done (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:523:15)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:584:18
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at MacUpdater.executeDownload (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:487:68)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:39:23
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:22:80)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:393:25
From previous event:
    at MacUpdater.downloadUpdate (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:382:86)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:369:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at MacUpdater.checkForUpdates (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at EventEmitter.<anonymous> (/Applications/myelectron.app/Contents/Resources/app.asar/main.js:224:15)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at WebContents.<anonymous> (/Applications/myelectron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

[09-01-2018 17:56:14.029] (error) Error: No update available, can't quit and install
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Object.done (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:46:11)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:530:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at done (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:523:15)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:584:18
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at MacUpdater.executeDownload (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:487:68)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:39:23
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:22:80)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:393:25
From previous event:
    at MacUpdater.downloadUpdate (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:382:86)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:369:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at MacUpdater.checkForUpdates (/Applications/myelectron.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at EventEmitter.<anonymous> (/Applications/myelectron.app/Contents/Resources/app.asar/main.js:224:15)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at WebContents.<anonymous> (/Applications/myelectron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

[09-01-2018 17:56:14.061] (info) / requested
[09-01-2018 17:56:14.074] (info) /app.zip requested
[09-01-2018 17:56:14.074] (info) app.zip requested by Squirrel.Mac, pipe /Users/myelectron/Library/Application Support/myelectron/__update__/myelectron-1.11.2-mac.zip
[09-01-2018 17:56:19.329] (info) Proxy server for native Squirrel.Mac is closed (was started to download https://releaseint.myelectron.com/download/1.11.2/osx_64/myelectron-1.11.2-mac.zip)
[09-01-2018 17:57:00.179] (info) Lastpong - lastPing = 0
[09-01-2018 17:57:00.183] (error) Error: Object has been destroyed
    at Timeout._onTimeout (/Applications/myelectron.app/Contents/Resources/app.asar/main.js:195:20)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by ozooner** [comment]
Update: With electron-updater version 3.0.3 OSX updates work (May work with more recent releases as well, didn't test)

**Comment by kraenhansen** [comment]
I experience the same with
- electron 2.0.7.
- electron-updater 3.1.2
- electron-builder 20.27.1

Here is my stacktrace:

```
Checking for update
Found version 2.8.0 (url: Realm Studio-2.8.0-mac.zip, Realm Studio-2.8.0.dmg)
Downloading update from Realm Studio-2.8.0-mac.zip, Realm Studio-2.8.0.dmg
No cached update info available
New version 2.8.0 has been downloaded to /Users/kraenhansen/Library/Application Support/Realm Studio/__update__/Realm Studio-2.8.0-mac.zip
Error: No update available, can't quit and install
    at MacUpdater.quitAndInstall (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:149:24)
    at xe.detail [as onUpdateAvailable] (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/build/webpack:/src/main/Updater.ts:204:7)
    at MacUpdater.autoUpdater (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/build/webpack:/src/main/Updater.ts:105:5)
    at emitOne (events.js:116:13)
    at MacUpdater.emit (events.js:211:7)
    at /Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:529:12
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
Error: Error: No update available, can't quit and install
    at MacUpdater.quitAndInstall (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:149:24)
    at xe.detail [as onUpdateAvailable] (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/build/webpack:/src/main/Updater.ts:204:7)
    at MacUpdater.autoUpdater (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/build/webpack:/src/main/Updater.ts:105:5)
    at emitOne (events.js:116:13)
    at MacUpdater.emit (events.js:211:7)
    at /Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:529:12
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/kraenhansen/Repositories/realm-studio/dist/mac/Realm Studio.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
/ requested
/app.zip requested
app.zip requested by Squirrel.Mac, pipe /Users/kraenhansen/Library/Application Support/Realm Studio/__update__/Realm Studio-2.8.0-mac.zip
2018-09-04 17:34:15.979 Realm Studio[17373:13770778] Download completed to: file:///Users/kraenhansen/Library/Caches/io.realm.realm-studio.ShipIt/update.SpaEtbU/app.zip
Proxy server for native Squirrel.Mac is closed (was started to download https://s3.amazonaws.com/static.realm.io/downloads/realm-studio/Realm%20Studio-2.8.0-mac.zip)
```

I invoke the `quitAndInstall` from the callback of the `update-downloaded` event like so:

```
  autoUpdater.on('update-downloaded', info => {
    const appName = electron.app.getName();
    const currentVersion = electron.app.getVersion();
    const lastestVersion = info.version;

    // Show a dialog synchronously
    const response = electron.dialog.showMessageBox({
      type: 'info',
      message: `A new version of ${appName} is available!`,
      detail: `${appName} ${lastestVersion} is available – you have ${currentVersion}. Would you like to update it now?`,
      buttons: ['Yes', 'No'],
      defaultId: 0,
      cancelId: 1,
    });

    // Quit and install
    if (response === 0) {
      autoUpdater.quitAndInstall();
    }
  });
```

**Comment by parkerdan** [comment]
Yep...issue with the `3.1.x` package(s).  `3.0.3` works great.

**Comment by arantes555** [comment]
I'm not extremely familiar with the code, but at first glance it seems the problem comes from https://github.com/electron-userland/electron-builder/commit/86d64c24eb480d92131d5691798cdff9d7926c3c#diff-2b9b61e9eb8d7c70588122422cd9b0e9R530

In this commit, the `update-downloaded` event is now emitted before setting up the server (which is done with calling `taskOptions.done`)

**Comment by reneklacan** [comment]
> I'm not extremely familiar with the code, but at first glance it seems the problem comes from 86d64c2#diff-2b9b61e9eb8d7c70588122422cd9b0e9R530

That does indeed seem like a potential source of this issue.

@develar What do you think?

**Comment by gseregni** [comment]
The same here... seems we can't update mac users,... soooooo baaaaaaad

**Comment by destegabry** [comment]
As a workaround I'm setting `autoUpdater.autoInstallOnAppQuit = true` and asking the user to quit the app in a dialog... any updates on this?

**Comment by nbcnc** [comment]
Similar problem here.  Still works on a Windows PC, though.

```
[2018-10-04 08:27:31.208] [info] / requested
[2018-10-04 08:27:51.058] [info] Checking for update
[2018-10-04 08:27:51.357] [info] Found version 1.3.0 (url: App-Installer.zip, App-Installer.dmg)
[2018-10-04 08:27:52.804] [info] Downloading update from App-Installer.zip, App-Installer.dmg
[2018-10-04 08:27:52.825] [info] No cached update info available
[2018-10-04 08:28:02.668] [info] New version 1.3.0 has been downloaded to /Users/nbcnc/Library/Application Support/App/__update__/App-Installer.zip
[2018-10-04 08:28:02.688] [warn] Error: No update available, can't quit and install
[2018-10-04 08:28:02.689] [error] Error: Error: No update available, can't quit and install
[2018-10-04 08:28:02.713] [error] Error: Error: No update available, can't quit and install
    at /Applications/App.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Object.done (/Applications/App.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:46:11)
    at /Applications/App.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:530:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at done (/Applications/App.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:523:15)
    at /Applications/App.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:584:18
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at MacUpdater.executeDownload (/Applications/App.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:487:68)
    at /Applications/App.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:39:23
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/App.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:22:80)
    at /Applications/App.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:393:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater.downloadUpdate (/Applications/App.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:382:86)
    at EventEmitter.ipcMain.on (/Applications/App.app/Contents/Resources/app.asar/main.js:395:13)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at WebContents.<anonymous> (/Applications/App.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
```

**Comment by VSchlattinger** [comment]
> Yep...issue with the `3.1.x` package(s). `3.0.3` works great.

Same for me. `3.0.4` works fine, but `3.1.x` throws the described error.

However, if I wait a few seconds after the download has finished, the following message appears in my console:

`
Proxy server for native Squirrel.Mac is closed (was started to download <url to new version>)
`

If I wait with the call to `autoUpdater.quitAndInstall();` until after that message appears, everything works fine. So, theoretically, I could try to delay that function call for a few seconds, but that doesn't seem like a good or stable solution. (You never know how long it takes on someone else's machine.)

For now I'm sticking with `3.0.4`. That seems better to me than trying to find some workaround. I hope this can get fixed soon, so I can upgrade back to the latest version.

**Comment by kevinkir** [comment]
@develar is there any way to remedy the situation if a user has a version with this bug?

**Comment by Lakshman1996** [comment]
I got it working on  electron-updater - 4.0.6 and   electron-builder - 20.36.2.
This is what i was doing before
```
autoUpdater.downloadUpdate().then(() => {
    autoUpdater.quitAndInstall(true, true);
}).catch(downloadError => {
    console.error(downloadError);
});
```

Because of some timing issue,  i had to wait for update-downloaded to be fired and the call quitAndInstall and then i changed it to below code
```
autoUpdater.on('update-downloaded', (ev, info) => {
    autoUpdater.quitAndInstall(true, true);
});


autoUpdater.downloadUpdate().then(() => {
    console.log('wait for post download operation');
}).catch(downloadError => {
    console.error(downloadError);
});
```

**Comment by mqliutie** [comment]
> I got it working on electron-updater - 4.0.6 and electron-builder - 20.36.2. This is what i was doing before
> 
> ```
> autoUpdater.downloadUpdate().then(() => {
>     autoUpdater.quitAndInstall(true, true);
> }).catch(downloadError => {
>     console.error(downloadError);
> });
> ```
> 
> Because of some timing issue, i had to wait for update-downloaded to be fired and the call quitAndInstall and then i changed it to below code
> 
> ```
> autoUpdater.on('update-downloaded', (ev, info) => {
>     autoUpdater.quitAndInstall(true, true);
> });
> 
> 
> autoUpdater.downloadUpdate().then(() => {
>     console.log('wait for post download operation');
> }).catch(downloadError => {
>     console.error(downloadError);
> });
> ```

What different between `autoUpdater.downloadUpdate()` with `autoUpdater.on('update-downloaded',()=>{})` event?

**Comment by mqliutie** [comment]
After much effort, I finally found a solution

First, import  `autoUpdater` from `electron` and `electron-update`;

```
import { autoUpdater as nativeUpdater  } from 'electron';
import { autoUpdater } from 'electron-updater';
```
When we check for updates, we call the autoUpdater method, and we use the autoUpdater event listener.
```
// This autpUpdate from electron-updater
autoUpdater.checkForUpdates()

autoUpdater.on('error', () => {
  // To tell user the error occurred
});

autoUpdater.on('update-available', async () => {
  // To tell user the update is available
});
autoUpdater.on('update-not-available', () => {
  // To tell user the update is not available
});
autoUpdater.on('download-progress', () => {
  // Show the progress to user
});
autoUpdater.on('update-downloaded', async () => {
  // Show dialog request quitAndInstall
});
```

The next key is that when the user clicks to confirm the install immediately, we do the following


```
const nativeUpdateDownloadedCallback = () => {
  nativeUpdater.removeListener('update-downloaded', nativeUpdateDownloadedCallback);
  // important call the nativeUpdate quitAndInstall
  nativeUpdater.quitAndInstall();
};
// do this when user agree install immediately
const handleConfirmUser = () => {
  setImmediate(() => {
    // remove all window close listener
    ensureSafeQuitAndInstall();
    // important!!!  call nativeUpdater checkForUpdates
    nativeUpdater.checkForUpdates();
    // important!!!  listen nativeUpdate 'update-downloaded' event
    nativeUpdater.on('update-downloaded', nativeUpdateDownloadedCallback);
  });
};
```

**Comment by tuugy** [comment]
Finally found the solution. Set autoDownload false

autoUpdater.autoDownload = false;
In my case downloading 2 times after app run.
