### ISSUE TITLE
autoUpdater.checkForUpdatesAndNotify() is not a function

### ISSUE THREAD

**Issue by bacvothanh** [electron-userland/electron-builder#3274]
electron 2.0.8

electron-updater 3.1.1

* **Target**: 
win 10/7 64 bit

I already ran the command  : **yarn add electron-updater**
and package.json : 
`
...
"build": {
    "appId": "winup.client",
    "productName": "Winup",
    "win": {
      "target": "portable",
      "icon": "./img/icons/256.png",
      "legalTrademarks": "",
      "publisherName": "winup"
    },
    "portable": {
      "artifactName": "${productName}Portable.${version}.${ext}"
    },
    "buildVersion": "1.0.0",
    "publish": [
      {
        "provider": "github",
        "owner": "bacvothanh",
        "repo": "winup",
        "protocol": "https",
        "token": "332f51e5266fe0f61731e5fd179a7a960f048a13"
      }
    ]
  },
  "devDependencies": {
    "electron": "^1.7.9",
    "electron-builder": "^20.8.2",
     "electron-updater": "^3.1.1",
     "electron-log": "^1.3.0"
  },
  "dependencies": {
    "electron-log": "^1.3.0",
    "electron-updater": "^3.1.1"
  }
`

and main.js : 
`
// This is free and unencumbered software released into the public domain.
// See LICENSE for details

const { app, BrowserWindow, Menu, protocol, ipcMain } = require('electron');
const log = require('electron-log');
const { autoUpdater } = require("electron-updater");

//-------------------------------------------------------------------
// Logging
//
// THIS SECTION IS NOT REQUIRED
//
// This logging setup is not required for auto-updates to work,
// but it sure makes debugging easier :)
//-------------------------------------------------------------------
autoUpdater.logger = log;
autoUpdater.logger.transports.file.level = 'info';
log.info('App starting...');
//-------------------------------------------------------------------
// Define the menu
//
// THIS SECTION IS NOT REQUIRED
//-------------------------------------------------------------------
let template = []
if (process.platform === 'darwin') {
    // OS X
    const name = app.getName();
    template.unshift({
        label: name,
        submenu: [
            {
                label: 'About ' + name,
                role: 'about'
            },
            {
                label: 'Quit',
                accelerator: 'Command+Q',
                click() { app.quit(); }
            },
        ]
    })
}

//-------------------------------------------------------------------
// Open a window that displays the version
//
// THIS SECTION IS NOT REQUIRED
//
// This isn't required for auto-updates to work, but it's easier
// for the app to show a window than to have to click "About" to see
// that updates are working.
//-------------------------------------------------------------------
let win;

function sendStatusToWindow(text) {
    log.info(text);
    win.webContents.send('message', text);
}
function createDefaultWindow() {
    win = new BrowserWindow({
        webPreferences: {
            allowRunningInsecureContent: true,
            webSecurity: false
        }
    });
    win.webContents.openDevTools();
    win.on('closed', () => {
        win = null;
    });
    win.loadURL(`file://${__dirname}/index.html`);
    return win;
}
autoUpdater.on('checking-for-update', () => {
    sendStatusToWindow('Checking for update...');
})
autoUpdater.on('update-available', (info) => {
    sendStatusToWindow('Update available.');
})
autoUpdater.on('update-not-available', (info) => {
    sendStatusToWindow('Update not available.');
})
autoUpdater.on('error', (err) => {
    sendStatusToWindow('Error in auto-updater. ' + err);
})
autoUpdater.on('download-progress', (progressObj) => {
    let log_message = "Download speed: " + progressObj.bytesPerSecond;
    log_message = log_message + ' - Downloaded ' + progressObj.percent + '%';
    log_message = log_message + ' (' + progressObj.transferred + "/" + progressObj.total + ')';
    sendStatusToWindow(log_message);
})
autoUpdater.on('update-downloaded', (info) => {
    sendStatusToWindow('Update downloaded');
});
app.on('ready', function () {
    // Create the Menu
    const menu = Menu.buildFromTemplate(template);
    Menu.setApplicationMenu(menu);
    autoUpdater.
    createDefaultWindow();
});
app.on('window-all-closed', () => {
    app.quit();
});

//
// CHOOSE one of the following options for Auto updates
//

//-------------------------------------------------------------------
// Auto updates - Option 1 - Simplest version
//
// This will immediately download an update, then install when the
// app quits.
//-------------------------------------------------------------------
app.on('ready', function () {
    autoUpdater.checkForUpdatesAndNotify();
    sendStatusToWindow('ready');
    
});

`
But when run script : npm start
always the exception :
`
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: autoUpdater.createDefaultWindow is not a function
    at App.<anonymous> (D:\Projects\TradingBot\Web\Client\main.js:100:5)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)

[OK]
`

Please help me how to resolve this!

**Comment by EddieOne** [comment]
Why did you close it?

**Comment by EddieOne** [comment]
I guess this doesn't work.

const autoUpdater = require("electron-updater");

but this does

const {autoUpdater} = require("electron-updater");
