### ISSUE TITLE
node-hid

### ISSUE THREAD

**Issue by Wolrab1** [electron-userland/electron-builder#3298]
* **Version**:  ^20.19.2
* **Target**:  Windows 10

When adding the package node-hid I get the following error which doesn't say what went wrong:

```
Error: F:\electron\node_test-1\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (F:\electron\node_test-1\node_modules\builder-util\src\util.ts:254:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at computeNodeModuleFileSets (F:\electron\node_test-1\node_modules\app-builder-lib\out\util\appFileCopier.js:429:18)
    at F:\electron\node_test-1\node_modules\app-builder-lib\src\platformPackager.ts:272:42
    at Generator.next (<anonymous>)
From previous event:
    at then (F:\electron\node_test-1\node_modules\app-builder-lib\src\platformPackager.ts:268:14)
From previous event:
    at _computeFileSets (F:\electron\node_test-1\node_modules\app-builder-lib\src\platformPackager.ts:269:10)
    at WinPackager.copyAppFiles (F:\electron\node_test-1\node_modules\app-builder-lib\src\platformPackager.ts:306:27)
    at F:\electron\node_test-1\node_modules\app-builder-lib\src\platformPackager.ts:213:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at WinPackager.doPack (F:\electron\node_test-1\node_modules\app-builder-lib\src\platformPackager.ts:166:165)
    at F:\electron\node_test-1\node_modules\app-builder-lib\src\platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (F:\electron\node_test-1\node_modules\app-builder-lib\src\platformPackager.ts:110:95)
    at F:\electron\node_test-1\node_modules\app-builder-lib\src\packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (F:\electron\node_test-1\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at F:\electron\node_test-1\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (F:\electron\node_test-1\node_modules\app-builder-lib\src\packager.ts:344:39)
    at F:\electron\node_test-1\node_modules\app-builder-lib\src\packager.ts:314:57
    at Generator.next (<anonymous>)
    at F:\electron\node_test-1\node_modules\graceful-fs\graceful-fs.js:99:16
    at F:\electron\node_test-1\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (F:\electron\node_test-1\node_modules\app-builder-lib\src\packager.ts:285:133)
    at F:\electron\node_test-1\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (F:\electron\node_test-1\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (F:\electron\node_test-1\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (F:\electron\node_test-1\node_modules\electron-builder\src\builder.ts:227:10)
    at then (F:\electron\node_test-1\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Object.args [as handler] (F:\electron\node_test-1\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at Object.runCommand (F:\electron\node_test-1\node_modules\yargs\lib\command.js:237:44)
    at Object.parseArgs [as _parseArgs] (F:\electron\node_test-1\node_modules\yargs\yargs.js:1085:24)
    at Object.get [as argv] (F:\electron\node_test-1\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (F:\electron\node_test-1\node_modules\electron-builder\src\cli\cli.ts:25:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node_test-1@0.0.1 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
```

**Comment by DeekshithShetty** [comment]
Have you put `"postinstall": "electron-builder install-app-deps"` npm script in your package.json?

**Comment by FlipOneDev** [comment]
I got pretty much the same build error trace as @Wolrab1, using electron-builder 20.28.4, electron 2.0.9, webpack 4.18.0, @babel/core 7.0.0.

Hours spent without any progress - would be nice if @develar has any ideas on this.

**Comment by FlipOneDev** [comment]
@develar, here's the Error Trace I got:

To ensure your native dependencies are always matched electron version, simply a
dd script `"postinstall": "electron-builder install-app-deps" to your `package.j
son`
   writing effective config file=dist\builder-effective-config.yaml
   rebuilding native production dependencies platform=win32 arch=x64
   packaging       platform=win32 arch=x64 electron=2.0.9 appOutDir=dist\win-unp
acked
?[31m  ??[0m Infinite loop: C:\node_modules
github.com/develar/app-builder/pkg/nodeModules.(*Collector).processDependencies
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tre
e.go:268
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tre
e.go:178
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tre
e.go:194
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tre
e.go:194
github.com/develar/app-builder/pkg/nodeModules.ConfigureCommand.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tre
e.go:32
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixi
n).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/a
lecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Applicatio
n).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/a
lecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Applicatio
n).execute
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/a
lecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Applicatio
n).Parse
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/a
lecthomas/kingpin/app.go:222
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:74
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tre
e.go:196
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tre
e.go:194
github.com/develar/app-builder/pkg/nodeModules.ConfigureCommand.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tre
e.go:32
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixi
n).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/a
lecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Applicatio
n).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/a
lecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Applicatio
n).execute
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/a
lecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Applicatio
n).Parse
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/a
lecthomas/kingpin/app.go:222
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:74
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Error: C:\Projects\Electron\adrenalin-sounds\node_modules\app-builder-bin\win\x6
4\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (C:\Projects\Electron\adrenalin-sound
s\node_modules\builder-util\src\util.ts:254:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at computeNodeModuleFileSets (C:\Projects\Electron\adrenalin-sounds\node_mod
ules\app-builder-lib\out\util\appFileCopier.js:429:18)
    at C:\Projects\Electron\adrenalin-sounds\node_modules\app-builder-lib\src\pl
atformPackager.ts:272:42
    at Generator.next (<anonymous>)
From previous event:
    at then (C:\Projects\Electron\adrenalin-sounds\node_modules\app-builder-lib\
src\platformPackager.ts:268:14)
From previous event:
    at _computeFileSets (C:\Projects\Electron\adrenalin-sounds\node_modules\app-
builder-lib\src\platformPackager.ts:269:10)
    at WinPackager.copyAppFiles (C:\Projects\Electron\adrenalin-sounds\node_modu
les\app-builder-lib\src\platformPackager.ts:306:27)
    at C:\Projects\Electron\adrenalin-sounds\node_modules\app-builder-lib\src\pl
atformPackager.ts:213:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (C:\Projects\Electron\adrenalin-sounds\node_modules\ap
p-builder-lib\src\platformPackager.ts:166:165)
    at C:\Projects\Electron\adrenalin-sounds\node_modules\app-builder-lib\src\pl
atformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Projects\Electron\adrenalin-sounds\node_modules\app-
builder-lib\src\platformPackager.ts:110:95)
    at C:\Projects\Electron\adrenalin-sounds\node_modules\app-builder-lib\src\pa
ckager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Projects\Electron\adrenalin-sounds\node_modules\fs-extra-p\n
ode_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Projects\Electron\adrenalin-sounds\node_modules\graceful-fs\polyfills.
js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (C:\Projects\Electron\adrenalin-sounds\node_modules\app-
builder-lib\src\packager.ts:344:39)
    at C:\Projects\Electron\adrenalin-sounds\node_modules\app-builder-lib\src\pa
ckager.ts:314:57
    at Generator.next (<anonymous>)
    at C:\Projects\Electron\adrenalin-sounds\node_modules\graceful-fs\graceful-f
s.js:99:16
    at C:\Projects\Electron\adrenalin-sounds\node_modules\graceful-fs\graceful-f
s.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Projects\Electron\adrenalin-sounds\node_modules\app-b
uilder-lib\src\packager.ts:285:133)
    at C:\Projects\Electron\adrenalin-sounds\node_modules\app-builder-lib\src\pa
ckager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (C:\Projects\Electron\adrenalin-sounds\node_modules\app-bu
ilder-lib\src\packager.ts:238:14)
    at build (C:\Projects\Electron\adrenalin-sounds\node_modules\app-builder-lib
\src\index.ts:58:28)
    at build (C:\Projects\Electron\adrenalin-sounds\node_modules\electron-builde
r\src\builder.ts:227:10)
    at then (C:\Projects\Electron\adrenalin-sounds\node_modules\electron-builder
\src\cli\cli.ts:42:48)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\Projects\Electron\adrenalin-sounds\node_modu
les\electron-builder\src\cli\cli.ts:42:48)
    at Object.runCommand (C:\Projects\Electron\adrenalin-sounds\node_modules\yar
gs\lib\command.js:237:44)
    at Object.parseArgs [as _parseArgs] (C:\Projects\Electron\adrenalin-sounds\n
ode_modules\yargs\yargs.js:1085:24)
    at Object.get [as argv] (C:\Projects\Electron\adrenalin-sounds\node_modules\
yargs\yargs.js:1000:21)
    at Object.<anonymous> (C:\Projects\Electron\adrenalin-sounds\node_modules\el
ectron-builder\src\cli\cli.ts:25:28)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! AdrenalinSounds@2.0.1 release: `webpack --config=webpack.app.config.js
--env=production && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the AdrenalinSounds@2.0.1 release script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by pansila** [comment]
I got a similar error as well.

electron-builder 20.28.4, electron 2.0.11, webpack 4.15.1, @babel/core 6.26.3

  ⨯ Get https://github.com/electron/electron/releases/download/v2.0.11/electron-v2.0.11-win32-x64.zip: proxyconnect tcp: dial tcp :0: connectex: The requested address is not valid in its context.
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:167
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:200
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:75
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
        /Users/develar/go/src/github.com/develar/app-builder/pkg/electron/electronDownloader.go:191
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
        /Users/develar/go/src/github.com/develar/app-builder/pkg/electron/electronDownloader.go:171
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/electron/electronDownloader.go:71
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Users/develar/go/src/github.com/develar/app-builder/pkg/util/async.go:67
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Error: d:\work\electron-test\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (d:\work\electron-test\node_modules\builder-util\src\util.ts:254:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
...

**Comment by YolandaXQY** [comment]
how do you resolve this at the end? I got a similar error as well.
