### ISSUE TITLE
Cannot find module 'electron-builder/out/util/nodeHttpExecutor' when building Squirrel installer on Linux

### ISSUE THREAD

**Issue by jakubzitny** [electron-userland/electron-builder#3317]
* **Version**: 20.28.4
* **Target**: Windows/Squirrel on a Linux machine
* **Node**: v8.11.3
* **Yarn**: 1.7.0
* **Electron**: 1.8.7

We're building a Squirrel installer on a Linux machine and everything worked with old electron-builder v12. Recently, we've updated to latest version and everything still works except the squirrel build for Windows. It's after fresh yarn install, with no cache.

We're getting the following error:
```
Error: Cannot find module 'electron-builder/out/util/nodeHttpExecutor'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at HttpExecutorHolder.get httpExecutor [as httpExecutor] (/project/node_modules/electron-builder-http/src/httpExecutor.ts:37:33)
    at download (/project/node_modules/electron-builder-http/src/httpExecutor.ts:50:25)
    at /project/node_modules/electron-builder-util/src/binDownload.ts:49:3
    at Generator.next (<anonymous>)
    at /project/node_modules/electron-builder-util/node_modules/fs-extra/lib/mkdirs/mkdirs.js:35:14
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at doGetBin (/project/node_modules/electron-builder-util/out/binDownload.js:54:21)
    at getBin (/project/node_modules/electron-builder-util/src/binDownload.ts:23:38)
    at getBinFromBintray (/project/node_modules/electron-builder-util/src/binDownload.ts:13:10)
    at /project/avode/node_modules/electron-builder-squirrel-windows/src/squirrelWindows.ts:79:25
From previous event:
    at SquirrelWindowsTarget.computeEffectiveDistOptions (/project/node_modules/electron-builder-squirrel-windows/out/squirrelWindows.js:126:11)
    at /project/node_modules/electron-builder-squirrel-windows/src/squirrelWindows.ts:35:36
    at Generator.next (<anonymous>)
From previous event:
    at SquirrelWindowsTarget.build (/project/node_modules/electron-builder-squirrel-windows/out/squirrelWindows.js:74:11)
    at Function.buildAsyncTargets (/project/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
    at WinPackager.packageInDistributableFormat (/project/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
    at /project/node_modules/app-builder-lib/src/platformPackager.ts:113:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

After these steps during build:
```
# ./node_modules/.bin/build -w 
  • electron-builder version=20.28.4
  • loaded configuration file=/project/electron-builder.yml
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config file=release/builder-effective-config.yaml
  • skipped app dependencies rebuild reason=npmRebuild is set to false
  • packaging       platform=win32 arch=x64 electron=1.8.7 appOutDir=release/win-unpacked
Building Squirrel.Windows for arch x64
```

*I know building Windows on Linux is not recommended, and also that Squirrel is deprecated.*

**Comment by jakubzitny** [comment]
When I manually copy the `electron-builder/out/util` directory from v12, it seems to be working correctly, so the issue here is only where did it get lost. I'll be happy to send a PR if you point me in the right direction 🙂
