### ISSUE TITLE
Problem with the remote build for target OS Linux

### ISSUE THREAD

**Issue by Gentser** [electron-userland/electron-builder#3328]
* **Electron-builder version**: 20.28.4  
* **Electron version**: 2.0.9  
* **npm version**: 6.2.0  
* **node version**: 8.9.3  

* **Building platform**: Windows 10 x64  
* **Target platform**:  Linux  

Hi, everybody. There is a problem with the remote build for Linux target OS using electron-bulder. Previously, the application was normally building into .AppImage file, but one day (in late august) it crashed this way:  

```
$ npm run build:linux

> react_electron_app@0.1.0 build:linux D:\myProject1\src
> build --platform linux

  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
  • description is missed in the package.json appPackageFile=D:\myProject1\src\package.json
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=2.0.9 appOutDir=dist\linux-unpacked
  • scheduling remote build target=appImage arch=x64
  • compressing and uploading to remote builder
  • uploaded to remote builder duration=1m36.102s
  • remote building           status=build in progress...
  • remote building           status=build in progress...
  • remote building           status=build in progress...
  • remote building           status=build in progress...
  ...
```

Well, respectively it endlessly displays a string  
`* remote building status=build in progress...`  
until the runtime error hapens. The build under Windows runs normally as before.  

Maybe anyone knows what the problem is? I would be grateful for any help.
[package_json.zip](https://github.com/electron-userland/electron-builder/files/2389018/package_json.zip)

**Comment by ShadyThGod** [comment]
I am having the exact same problem. I tried changing the linux configuration a few times but it keeps doing this. I tried reading through the error to try and find out something but I couldn't.

Here is the error: 
```
Error: C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\builder-util\src\util.ts:254:14)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at RemoteBuilder._build (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:56:83)
    at _bluebirdLst.default.mapSeries.arch (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:51:19)
From previous event:
    at RemoteBuilder.build (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:50:28)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\linuxPackager.ts:99:30
From previous event:
    at RemoteTarget.finishBuild (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\linuxPackager.ts:97:20)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\packager.ts:384:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Packager.doBuild (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\packager.ts:344:39)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\packager.ts:314:57
    at Generator.next (<anonymous>)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at Packager._build (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\packager.ts:285:133)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Object.args [as handler] (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at Object.runCommand (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\yargs\yargs.js:1085:24)
    at Object.get [as argv] (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-builder\src\cli\cli.ts:25:28)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

Here is what my package file looks like: [package.json](https://gist.github.com/ShadyThGod/de84a31eb87375ce6beb2f83ff621fb1)

**Comment by ShadyThGod** [comment]
It seems like there might be some problem with building from Windows because I tried building from a Linux VM and it worked properly.

**Comment by Gentser** [comment]
Yes, that was ment under the state of problem. Remote building is not working, so maybe there are some problems with remote-building server.
