### ISSUE TITLE
App crashes and gets deleted after updating with oneClick=true, perMachine=false

### ISSUE THREAD

**Issue by odiseo42** [electron-userland/electron-builder#3338]
* **electron-builder**: 20.19.2
* **electron-updater**: 2.23.3
* **Target**: nsis-web

I've been seeing that when my app is built with `oneClick=true` and `perMachine=false` after the update is downloaded and `autoUpdater.quitAndInstall();` is called, the app closes but the installer crashes and the app gets deleted from `C:\<user>\AppData\Local\Programs\`. This is super strange, as simply setting `perMachine=true` will work (but this will require elevation).

To isolate the problem and make it reproducible, I've made just a slight change to `electron-boilerplate` to add auto updates. You can:

1. Clone https://github.com/odiseo42/electron-boilerplate.git
2. Run `yarn install`
3. Make a build with `yarn run release`
4. I used `SimpleHTTPServer` (`python -m SimpleHTTPServer 8000`) as a local update server. I'm serving it from `electron-boilerplate/dist`, so probably you'd like to do the same and change `build.win.publish.url` in `package.json` for your local IP.

This naturally requires at least two incremental builds.

GIF screen capture: 

![](http://g.recordit.co/QkvXMfDPjc.gif)

The log file using `electron-log` is:

```
[2018-09-20 15:37:26.462] [info] App starting...
[2018-09-20 15:37:26.666] [info] Checking for update
[2018-09-20 15:37:27.900] [info] Generated new staging user ID: e68a65da-143f-5d6e-8d62-f7c177723c1e
[2018-09-20 15:37:27.994] [info] Found version 2.0.0 (url: Electron Boilerplate_2.0.0.exe)
[2018-09-20 15:37:27.994] [info] Downloading update from Electron Boilerplate_2.0.0.exe
[2018-09-20 15:37:28.025] [info] No cached update info available
[2018-09-20 15:37:28.103] [error] Cannot download differentially, fallback to full download: Error: Server doesn't support Accept-Ranges (response code 200)
    at checkIsRangesSupported (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\multipleRangeDownloader.ts:111:14)
    at ClientRequest.request.httpExecutor.doRequest.response (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:210:14)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at URLRequest.ClientRequest.urlRequest.on (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\electron.asar\browser\api\net.js:207:12)
    at emitOne (events.js:116:13)
    at URLRequest.emit (events.js:211:7)
From previous event:
    at FileWithEmbeddedBlockMapDifferentialDownloader.readRemoteBytes (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:195:70)
    at C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\FileWithEmbeddedBlockMapDifferentialDownloader.ts:9:42
    at Generator.next (<anonymous>)
From previous event:
    at FileWithEmbeddedBlockMapDifferentialDownloader.download (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\FileWithEmbeddedBlockMapDifferentialDownloader.ts:5:17)
    at C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:204:10
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.differentialDownloadWebPackage (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:190:122)
    at Object.<anonymous> (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:52:26)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:37:7)
    at C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:104:25
    at Generator.throw (<anonymous>)
From previous event:
    at NsisUpdater.executeDownload (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:29:68)
    at C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:32:23
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:22:80)
    at C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:393:25
From previous event:
    at NsisUpdater.downloadUpdate (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:382:86)
    at C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:369:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:348:34)
    at C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:282:33)
    at NsisUpdater.checkForUpdates (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:221:35)
    at NsisUpdater.checkForUpdatesAndNotify (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:235:41)
    at App.showMessageBox (C:\Users\IEUser\AppData\Local\Programs\electron-boilerplate\resources\app.asar\app\webpack:\src\background.js:64:12)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
[2018-09-20 15:37:30.443] [info] New version 2.0.0 has been downloaded to C:\Users\IEUser\AppData\Roaming\Electron Boilerplate\__update__\Electron Boilerplate_2.0.0.exe
[2018-09-20 15:38:34.693] [info] Install on explicit quitAndInstall
[2018-09-20 15:38:34.693] [info] Install: isSilent: false, isRunAfter: true
[2018-09-20 15:38:34.712] [info] Update installer has already been triggered. Quitting application.
```

I wouldn't worry too much about the error on incremental updates, as this also shows up when i run it as an admin with `perMachine=true`, yet in that scenario the update is applied correctly.

I think this is a pretty serious bug, as **it renders `electron-updater` useless for per user installation**. I'm going to try to debug the issue by using a local copy of `electron-packager` and setting logs in `electron-updater`, but any help/question/suggestion to debug/solution will be greatly appreciated.

**Comment by odiseo42** [comment]
Actually i just found out that this only happens with `nsis-web` as target. `nsis` seems to work completely fine.
