### ISSUE TITLE
Error Trying to build for windows on linux: __uninstaller-nsis-filename.exe

### ISSUE THREAD

**Issue by rodobodolfo** [electron-userland/electron-builder#3343]
* **Electron Builder Version**:  20.28.4

* **Electron Updater Version**:  3.1.2

* **Target**:  windows (nsis)
* **Host**: Ubuntu Linux 18.04.1

Hi! 
I cant build to windows (NSIS) anymore, I'm pretty sure it started failing after I did some unrelated wine changes (tried playonlinux and kxstudios wine versions, did some uninstalling/reinstalling)

It seems to build just fine, but after then it fails on the uninstaller part:

```
 electron-builder --win
  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.8.8 appOutDir=dist/win-unpacked
  • default Electron icon is used reason=application icon is not set
  • building        target=nsis file=dist/speechr Setup 1.0.12.exe archs=x64 oneClick=true
Error: /home/baj/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis exited with code 1
Output:
Command line defined: "APP_ID=com.pointbleepstudios.speechr"
Command line defined: "APP_GUID=35bbb4cb-0f34-5ecf-a80b-639ffb84be3c"
Command line defined: "UNINSTALL_APP_KEY=35bbb4cb-0f34-5ecf-a80b-639ffb84be3c"
Command line defined: "PRODUCT_NAME=speechr"
Command line defined: "PRODUCT_FILENAME=speechr"
Command line defined: "APP_FILENAME=speechr"
Command line defined: "APP_DESCRIPTION=All in one game content organization tool"
Command line defined: "VERSION=1.0.12"
Command line defined: "PROJECT_DIR=/home/baj/dev/speecherjs-v2"
Command line defined: "BUILD_RESOURCES_DIR=/home/baj/dev/speecherjs-v2/build"
Command line defined: "APP_64=/home/baj/dev/speecherjs-v2/dist/speechr-1.0.12-x64.nsis.7z"
Command line defined: "APP_64_NAME=speechr-1.0.12-x64.nsis.7z"
Command line defined: "APP_64_HASH=1D8F0D47BA2BC74CDD1838AA7FBD382C74D1281E82BAB21AC8BCE4F368A99425652B616CC08E9914004FA573B507BE6BE345FB13CF152574429A1E7EDC54D7BD"
Command line defined: "COMPANY_NAME=rodobodolfo"
Command line defined: "APP_INSTALLER_STORE_FILE=speechr\__installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "SHORTCUT_NAME=speechr"
Command line defined: "UNINSTALL_DISPLAY_NAME=speechr v1.0.12"
Command line defined: "ESTIMATED_SIZE=420898"
Command line defined: "COMPRESS=auto"
Command line defined: "UNINSTALLER_OUT_FILE=/home/baj/dev/speecherjs-v2/dist/.__uninstaller-nsis-speechr.exe"
Processing script file: "<stdin>" (UTF8)

Error output:
File: "/home/baj/dev/speecherjs-v2/dist/.__uninstaller-nsis-speechr.exe" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in macro installApplicationFiles on macroline 85
!include: error in script: "installSection.nsh" on line 60
Error in script "<stdin>" on line 147 -- aborting creation process

    at ChildProcess.childProcess.once.code (/home/baj/dev/speecherjs-v2/node_modules/builder-util/src/util.ts:254:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
error Command failed with exit code 1.

```

**Comment by sixtyseven** [comment]
worked for me before,
then after a few minutes when I come back to the same script, doing the same thing for me here

**Comment by rodobodolfo** [comment]
> Guess what? After mannually empty the disk, it is back to work again. Took me a good half day to solve it. Hoo~

Lucky! For me the issue was resolved after upgrading Kde neon, which had some broken wine dependencies.
