### ISSUE TITLE
Autoupdate using DigitalOcean returns 403 AccessDenied error. Request does not use environment variables.

### ISSUE THREAD

**Issue by paulsutherland** [electron-userland/electron-builder#3357]
* **Version**: 20.28.4

* **Target**: macOS

I am using DigitalOcean as my autoupdate provider.  I can publish successfully to a private space using the DO_KEY_ID and the DO_SECRET_KEY environment variables.

However, when I check for updates I receive a 403 Forbidden error.

Package json:

```
...
  "build": {
    "publish": [
      {
        "provider": "spaces",
        "channel": "latest",
        "name": "abv2",
        "region": "ams3",
        "path": "latest",
        "acl": "private"
      }
    ]
  },
...
```
dev-app-update.yml:

```
provider: "spaces"
channel: "latest"
name: "abv2"
region: "ams3"
path: "latest"
acl: "private"
```

I have followed the stack trace to check the request headers and I don't see anything relating to digital ocean authorisation credentials. I don't think the key and secret are being used in the request to the spaces bucket.
```
[10:37:43.123] [info] Checking for update
[10:37:43.520] [error] Error: HttpError: 403 Forbidden
"<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AccessDenied</Code><BucketName>abv2</BucketName><RequestId>tx000000000000012b8fb86-005bb33c67-b0fade-ams3a</RequestId><HostId>b0fade-ams3a-ams3</HostId></Error>"
Headers: {
  "accept-ranges": [
    "bytes"
  ],
  "content-length": [
    "211"
  ],
  "content-type": [
    "application/xml"
  ],
  "date": [
    "Tue, 02 Oct 2018 09:37:43 GMT"
  ],
  "strict-transport-security": [
    "max-age=15552000; includeSubDomains; preload"
  ],
  "x-amz-request-id": [
    "tx000000000000012b8fb86-005bb33c67-b0fade-ams3a"
  ]
}
    at createHttpError (/Users/paul/Spikes/electron-updating/node_modules/builder-util-runtime/src/httpExecutor.ts:32:10)
    at IncomingMessage.stream.on (/Users/paul/Spikes/electron-updating/node_modules/builder-util-runtime/src/httpExecutor.ts:171:18)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at CancellationToken.createPromise (/Users/paul/Spikes/electron-updating/node_modules/builder-util-runtime/src/CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (/Users/paul/Spikes/electron-updating/node_modules/builder-util-runtime/src/httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (/Users/paul/Spikes/electron-updating/node_modules/builder-util-runtime/src/httpExecutor.ts:74:17)
    at GenericProvider.httpRequest (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/providers/Provider.ts:29:26)
    at /Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/providers/GenericProvider.ts:24:45
    at Generator.next (<anonymous>)
From previous event:
    at GenericProvider.getLatestVersion (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/providers/GenericProvider.ts:18:25)
    at /Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:345:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater.getUpdateInfo (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:335:32)
    at /Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:349:35
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater._checkForUpdates (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at MacUpdater.checkForUpdates (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at EventEmitter.<anonymous> (/Users/paul/Spikes/electron-updating/main.js:66:15)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at WebContents.<anonymous> (/Users/paul/Spikes/electron-updating/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
{ HttpError: 403 Forbidden
"<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AccessDenied</Code><BucketName>abv2</BucketName><RequestId>tx000000000000012b8fb86-005bb33c67-b0fade-ams3a</RequestId><HostId>b0fade-ams3a-ams3</HostId></Error>"
Headers: {
  "accept-ranges": [
    "bytes"
  ],
  "content-length": [
    "211"
  ],
  "content-type": [
    "application/xml"
  ],
  "date": [
    "Tue, 02 Oct 2018 09:37:43 GMT"
  ],
  "strict-transport-security": [
    "max-age=15552000; includeSubDomains; preload"
  ],
  "x-amz-request-id": [
    "tx000000000000012b8fb86-005bb33c67-b0fade-ams3a"
  ]
}
    at createHttpError (/Users/paul/Spikes/electron-updating/node_modules/builder-util-runtime/src/httpExecutor.ts:32:10)
    at IncomingMessage.stream.on (/Users/paul/Spikes/electron-updating/node_modules/builder-util-runtime/src/httpExecutor.ts:171:18)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at CancellationToken.createPromise (/Users/paul/Spikes/electron-updating/node_modules/builder-util-runtime/src/CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (/Users/paul/Spikes/electron-updating/node_modules/builder-util-runtime/src/httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (/Users/paul/Spikes/electron-updating/node_modules/builder-util-runtime/src/httpExecutor.ts:74:17)
    at GenericProvider.httpRequest (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/providers/Provider.ts:29:26)
    at /Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/providers/GenericProvider.ts:24:45
    at Generator.next (<anonymous>)
From previous event:
    at GenericProvider.getLatestVersion (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/providers/GenericProvider.ts:18:25)
    at /Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:345:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater.getUpdateInfo (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:335:32)
    at /Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:349:35
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater._checkForUpdates (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at MacUpdater.checkForUpdates (/Users/paul/Spikes/electron-updating/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at EventEmitter.<anonymous> (/Users/paul/Spikes/electron-updating/main.js:66:15)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at WebContents.<anonymous> (/Users/paul/Spikes/electron-updating/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
  statusCode: 403,
  description: '<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><BucketName>abv2</BucketName><RequestId>tx000000000000012b8fb86-005bb33c67-b0fade-ams3a</RequestId><HostId>b0fade-ams3a-ams3</HostId></Error>',
  name: 'HttpError' }
```

**Comment by bharathj1674** [comment]
i also have the same issues. did you get any resolution to above ?

**Comment by paulsutherland** [comment]
No. I ended up using a generic https server.  I used Azure blob storage, which works fine.

**Comment by jcolemn3** [comment]
@paulsutherland I'm trying to get azure blog storage to work with auto-updating. Any advice to get it up and going? I keep getting 401 but I can go directly to an incognito browser and download the .yml update file.

**Comment by paulsutherland** [comment]
@jcolemn3 

Hi,

I use a node api app to handle the updates.  You have two options with Azure Blob Storage containers:  either access is publicly available or you secure it with a secure access signature token (SAS).

I call the api end point and pass in and validate the user's JWT session token.  Once I have validated the user I use the [azure-storage](https://github.com/Azure/azure-storage-node) package to call out to Azure to create a 5min SAS token restricted to downloads from the container.  I create a url with this sas token and pass it back to the electron app.

This url will allow the electron app, [using electron-updater](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater), to call azure blob storage direct and check for updates.

You can use the [azure blob storage explorer app](https://azure.microsoft.com/en-gb/features/storage-explorer/) for uploading new app releases to Azure Blob Storage.  Or generate a script that can push directly into Azure Blob Storage, it is a the same as the downloading example above, only you generate a SAS token allowing uploads only.

I hope that helps.

Cheers...

Paul

**Comment by jcolemn3** [comment]
@paulsutherland Thanks so much for your response. This definitely points me in the right direction. Have you found any drawbacks with calling the SetFeedUrl? (electron-builder suggests not to set this url). Do you construct your package.json config in the suggested approach now that you also set the feedUrl pro-grammatically?

**Comment by paulsutherland** [comment]
@jcolemn3 

In short - no issues.

I want to check that a user is authorised before issuing an update url and I want to be able to switch out the storage back end if required, so I settled on setting the SetFeedUrl programmatically.  I call out to the api app via a dance between the main and renderer process using ipc.

If you look at the source, the SetFeedUrl function happily takes a string and I have had no issues doing that.

I purposely make sure not to set the url in package.json so there is no conflict.

```
  ipcMain.on('update', (event, data) => {
    if (process.env.NODE_ENV === 'development') {
      console.log('Skipping update check as we are in development mode')
      return
    } else {
      autoUpdater.setFeedURL({
        'provider': 'generic',
        'url': data.url
      })
      return autoUpdater.checkForUpdates()
    }
  })
```

**Comment by jcolemn3** [comment]
@paulsutherland Thanks again for all your help. I am at the point where it's using the SAS token to detect the lastest.yml file in the private blob correctly. However, after setting the feedUrl with the {url}{sas token}, the autoupdater is now looking for the resource in the {appdata}\{appName}\pending\{artifact}{sas token} which does not exist. In other words its appending the token to the end of the blob resource. Have you seen this before?

**Comment by paulsutherland** [comment]
@jcolemn3

I am not 100% clear on what is happening there, but it is possible for you to generate a SAS token for either an individual file or the entire container:

For a file:

```
function generateDownloadSas (container, filename) {
  return new Promise((resolve, reject) => {
    let startDate = new Date()
    let expiryDate = new Date(startDate)
    expiryDate.setMinutes(startDate.getMinutes() + 5)
    startDate.setMinutes(startDate.getMinutes() - 5)

    const sharedAccessPolicy = {
      AccessPolicy: {
        Permissions: [azure.BlobUtilities.SharedAccessPermissions.READ],
        Start: startDate,
        Expiry: expiryDate
      }
    }
    try {
      const token = blobService.generateSharedAccessSignature(container, filename, sharedAccessPolicy)
      const sas = blobService.getUrl(container, filename, token)
      resolve(sas)
    } catch (err) {
      reject(new Error(err))
    }
  })
}

```
Or a container:

```
function generateContainerSas (container) {
  return new Promise((resolve, reject) => {
    const startDate = new Date()
    const expiryDate = new Date(startDate)
    expiryDate.setMinutes(startDate.getMinutes() + 5)
    startDate.setMinutes(startDate.getMinutes() - 5)

    const sharedAccessPolicy = {
      AccessPolicy: {
        Permissions: [azure.BlobUtilities.SharedAccessPermissions.READ],
        Start: startDate,
        Expiry: expiryDate
      }
    }
    try {
      const token = blobService.generateSharedAccessSignature(container, null, sharedAccessPolicy)
      // Or return the URL
      // let url = blobService.getUrl(container, null, token)
      resolve(token)
    } catch (err) {
      reject(new Error(err))
    }
  })
}
```

Does that help?

**Comment by jcolemn3** [comment]
@paulsutherland 
This does help. Getting the token was relatively easy using your example. 
![image](https://user-images.githubusercontent.com/42102900/51793701-92012080-2192-11e9-9b72-fadb5adf3575.png)

(see the screenshot)
First, it goes to **check-for-update** which retrieves the file successfully from the BLOB using the sas token url.
Second, it attempts to download the package but fails because the electron-updater is appending the token to the end of the file name for the package pulled from the BLOB.
This is where the auto-updater fails.

**AutoUpdater module**

```
const { autoUpdater } = require('electron-updater');
const logger = require('electron-log');
const azure = require('azure-storage');
const CONFIG = require('../../config');

let autoUpdateTimer = null;
let BrowserWindow = null;
const blobService = azure.createBlobService(CONFIG.PROD.AZ_BLOB_CONN);
autoUpdater.logger = logger;

const generateContainerSas = () => {
    return new Promise((resolve, reject) => {
        const startDate = new Date();
        const expiryDate = new Date(startDate);
        expiryDate.setMinutes(startDate.getMinutes() + 5);
        startDate.setMinutes(startDate.getMinutes() - 5);

        const sharedAccessPolicy = {
            AccessPolicy: {
                Permissions: [azure.BlobUtilities.SharedAccessPermissions.READ],
                Start: startDate,
                Expiry: expiryDate
            }
        };

        try {
            const token = blobService.generateSharedAccessSignature(CONFIG.PROD.AZ_CONTAINER, null, sharedAccessPolicy);
            const url = new URL(blobService.getUrl(CONFIG.PROD.AZ_CONTAINER, null, token));
            url.pathname = `${url.pathname}/Updates`; // Add folder to url
            resolve(url.href);
        } catch (err) {
            reject(err);
        }
    })
}

/**
 * Starts check for auto updater. Runs on a random time period between 6-8 hours
 * **Note:** This interval is calculate dynamically
 * @param {Electron.BrowserWindow} mainWindow 
 */
const initAutoUpdateCheck = (mainWindow) => {
    BrowserWindow = mainWindow;
    // if autoupdating has already started, do not attempt to start it again
    if (autoUpdateTimer !== null) return;

    const max = Math.floor(30000); //Math.floor(28800000);
    const min = Math.ceil(20000); //Math.ceil(21600000);
    const defaultFrequency = Math.floor(Math.random() * (max - min + 1)) + min;
    autoUpdateTimer = setInterval(() => {
        generateContainerSas()
            .then(response => {
                autoUpdater.setFeedURL({ provider: 'generic', url: response });
                autoUpdater.checkForUpdates();
            })
            .catch(error => {
                sendMessage('error', error);
            });
    }, defaultFrequency);
}

/**
 * Stops check for auto updater
 */
const stopAutoUpdateCheck = () => {
    clearInterval(autoUpdateTimer);
    autoUpdateTimer = null;
}

/**
 * Restarts the app and installs the update after it has been downloaded.
 * It should only be called after `update-downloaded` has been emitted.
 *
 * **Note:** `autoUpdater.quitAndInstall()` will close all application windows first and only emit `before-quit` event on `app` after that.
 * This is different from the normal quit event sequence.
 */
const installUpdate = () => {
    setTimeout(() => {
        // Give the UI enough time for UI treatment
        autoUpdater.quitAndInstall();
    }, 5000);
}

/**
 * Send an asynchronous message to renderer process via channel, you can also send
 * arbitrary arguments. Arguments will be serialized in JSON internally and hence
 * no functions or prototype chain will be included. The renderer process can
 * handle the message by listening to channel with the ipcRenderer module. An
 * example of sending messages from the main process to the renderer process:
 * @param {string} channel 
 * @param {any} message 
 */
const sendMessage = (channel, message) => {
    BrowserWindow.webContents.send(channel, message);
};

autoUpdater.on('checking-for-update', () => {
    sendMessage('checking-for-update', autoUpdater);
});

autoUpdater.on('update-available', (updateInfo) => {
    sendMessage('update-available', updateInfo);
});

autoUpdater.on('update-not-available', (updateInfo) => {
    sendMessage('update-not-available', updateInfo);
});

autoUpdater.on('error', (error) => {
    sendMessage('error', error);
});

autoUpdater.on('download-progress', (progressObj) => {
    sendMessage('download-progress', progressObj);
})

autoUpdater.on('update-downloaded', (updateInfo) => {
    sendMessage('update-downloaded', updateInfo);
    stopAutoUpdateCheck();
});

/**
 * Module handles starting and stopping MTA's auto updating feature in main process.
 * Also handles the download and installation of updates when updates
 * available
 */
const AutoUpdateHelper = {
    installUpdate,
    initAutoUpdateCheck,
    stopAutoUpdateCheck
};

module.exports = AutoUpdateHelper;
```
InitAutoUpdateCheck is where the code is initialized. I then call the method to return the URL with SAS from the Azure Blob Service.

**package.json**
 ```
 "build": {
    "appId": "com.myapp.MyApp.AppName",
    "directories": {
      "output": "packages"
    },
    "publish": [
      {
        "useMultipleRangeRequest": false,
        "provider": "generic",
        "url": ""
      }
    ],
    "mac": {
      "category": "com.ge.category.type",
      "target": [
        "zip",
        "dmg"
      ]
    },
    "win": {
      "icon": "app/assets/images/logo-white.da28284a.png",
      "target": [
        {
          "target": "nsis-web",
          "arch": [
            "ia32",
            "x64"
          ]
        }
      ]
    },
    "nsisWeb": {
      "artifactName": "${productName}-Setup-${version}.exe",
      "allowElevation": true,
      "createDesktopShortcut": false,
      "oneClick": true,
      "perMachine": true,
      "differentialPackage": true
    }
  },
```
This is what I was trying to (horribly I might add) explain. I can access the latest.yml file with the SAS token without issue but the Electron-updater is also appending the SAS token to the end of the file name that it creates while downloading the artifact. Is there a certain way I should be formatting the url that we set in the setFeedURL? Or is there another subsequent place that I should be removing the SAS from the feed URL? Thanks for all of your help

**Comment by paulsutherland** [comment]
@jcolemn3 

Sorry I missed your reply.

I can't see why that does not work for you.  Have you tried removing:

```
   "publish": [
     {
       "useMultipleRangeRequest": false,
       "provider": "generic",
       "url": ""
     }
   ],

```
from your package.json?

Also what versions of Electron, Electron builder and Electron Updater are you using?

Finally, try the following as your target for win in package.json:

```
    "target": [
      "portable",
      "zip",
      "nsis"
    ]
```

**Comment by linuxjuggler** [comment]
@paulsutherland can you open your app content and check the content for the `app-update.yml` file?

I suspect that the issue you are facing with DO spaces is related to the fact that the `acl` is `private`.

remember that when you build your app the environment variables `DO_KEY_ID` and  `DO_SECRET_KEY` will not be part of the `app-update.yml` file and since the update files `acl` is `private` there is no way for the app to access them.

**Comment by paulsutherland** [comment]
@linuxjuggler 

Thanks for the reply.  I tried both public and public-read, but I still get a 403.

Thank you,

Paul

**Comment by natearmagost** [comment]
It seems that auto-updating from DigitalOcean is completely broken. I'm having the same issue with 403s.

For some reason the updater is appending a '/' to my space (bucket) and the URL `result` in the link below ends up something like this:

```
URL {
  href:
   'https://space.nyc3.digitaloceanspaces.com/MyApp-1.0.2-mac.zip/',
  origin: 'https://space.nyc3.digitaloceanspaces.com',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'space.nyc3.digitaloceanspaces.com',
  hostname: 'space.nyc3.digitaloceanspaces.com',
  port: '',
  pathname: '/MyApp-1.0.2-mac.zip/',
```
space.nyc3.digitaloceanspaces.com/MyApp-1.0.2-mac.zip/ <----

https://github.com/electron-userland/electron-builder/blob/f0bf67c7d87e7af4e31b24f45172cf4ba3c2ca72/packages/electron-updater/src/main.ts#L127

The trailing slash attempt to load a directory and will give the AccessDenied / 403 Forbidden. Maybe the slash is an S3 deal? Maybe my setup? I don't know. If I dig into node_modules and actually remove that trailing slash, I can publish fine to a private space. I can get past that part.

But that doesn't really matter. Auto-updating is still broken because the only place the `DO_KEY_ID` and `DO_SECRET_KEY` seem to be used are in files related to publishing.
