### ISSUE TITLE
Error: Can not access a closed Stream. (appveyor)

### ISSUE THREAD

**Issue by maxcnunes** [electron-userland/electron-builder#336]
Does the example project build the app correctly on appveyor? I have found out that is not working for me. Because is not including the app `node_modules` in the release. Then I figured out it is occurring  because is using [`npm update`](https://github.com/develar/onshape-desktop-shell/blob/master/appveyor.yml#L24) instead of `npm install`. Which does not execute the [`postinstall`]
(https://github.com/develar/onshape-desktop-shell/blob/master/package.json#L5).

I have changed by `appveyor` to use `npm install` instead of `npm update`. But once there is the `app/node_modules` the build crashes:

```bash
Removing C:\projects\sqlectron-gui\dist\win-x64
Packaging app for platform win32 x64 using electron v0.36.12
Can not access a closed Stream.
Error: C:\projects\sqlectron-gui\node_modules\electron-winstaller-fixed\vendor\nuget.exe failed with exit code: 1
    at ChildProcess.<anonymous> (C:\projects\sqlectron-gui\node_modules\electron-winstaller-fixed\lib\spawn-promise.js:33:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at tsAwaiter (C:\projects\sqlectron-gui\node_modules\electron-builder\src\awaiter.ts:10:51)
    at Object.build (C:\projects\sqlectron-gui\node_modules\electron-builder\src\builder.ts:30:59)
    at Object.<anonymous> (C:\projects\sqlectron-gui\node_modules\electron-builder\src\build-cli.ts:41:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
Unhandled rejection Error: EBUSY: resource busy or locked, unlink 'C:\Users\appveyor\AppData\Local\Temp\1\si-116318-2600-ed85ne\Sqlectron.1.6.2.nupkg'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:980:18)
    at rimrafSync (C:\projects\sqlectron-gui\node_modules\temp\node_modules\rimraf\rimraf.js:211:13)
    at C:\projects\sqlectron-gui\node_modules\temp\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (native)
    at rmkidsSync (C:\projects\sqlectron-gui\node_modules\temp\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (C:\projects\sqlectron-gui\node_modules\temp\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\projects\sqlectron-gui\node_modules\temp\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\projects\sqlectron-gui\node_modules\temp\node_modules\rimraf\rimraf.js:216:26)
    at cleanupDirsSync (C:\projects\sqlectron-gui\node_modules\temp\lib\temp.js:143:5)
    at process.cleanupSync (C:\projects\sqlectron-gui\node_modules\temp\lib\temp.js:196:19)
    at emitOne (events.js:95:20)
    at process.emit (events.js:182:7)
    at process.emit (C:\projects\sqlectron-gui\node_modules\electron-builder\node_modules\source-map-support\source-map-support.js:415:21)
    at process.exit (internal/process.js:79:15)
    at printErrorAndExit (C:\projects\sqlectron-gui\node_modules\electron-builder\src\promise.ts:8:11)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Object.<anonymous> (C:\projects\sqlectron-gui\node_modules\electron-builder\src\build-cli.ts:41:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
 
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\appveyor\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! @1.6.2 dist: `npm run compile && build --arch all`
npm ERR! Exit status 4294967295
npm ERR! 
npm ERR! Failed at the @1.6.2 dist script 'npm run compile && build --arch all'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile && build --arch all
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\sqlectron-gui\npm-debug.log
Command exited with code 1
```
Full log: https://ci.appveyor.com/project/maxcnunes/sqlectron-gui/build/1.0.50

Any idea why this is happening? It does not occur building the app in a local Windows.
There is this error message below, but I have no idea why.
> Unhandled rejection Error: EBUSY: resource busy or locked, unlink 'C:\Users\appveyor\AppData\Local\Temp\1\si-116318-2600-ed85ne\Sqlectron.1.6.2.nupkg'

**Comment by maxcnunes** [comment]
Actually looking the logs of the build with `npm update` looks like the script tries to install the app dependencies, because there this message:
> Installing app dependencies for arch x64 to C:\projects\sqlectron-gui\app - https://ci.appveyor.com/project/maxcnunes/sqlectron-gui/build/1.0.46#L1038

But after that does not print the installed modules. So I guess is not really installing anything. I have even printed the `app/node_modules` after the build and there is nothing there.

**Comment by develar** [comment]
Please try to use `next` version of electron-builder.

Well, it seems I can try to test using your project, but for now may be `next` will be a solution.

**Comment by develar** [comment]
Relates to: #338

**Comment by maxcnunes** [comment]
@develar using the next version + `npm install` it worked.
Thank you very much! 👏

**Comment by jigz** [comment]
For future reference, msix and appx makers can fail from leftover outputs
```json
"scripts": {
  "clean": "rimraf out-web out-electron",
}
```
