### ISSUE TITLE
I can't build Snap on Ubuntu 18.10

### ISSUE THREAD

**Issue by grigio** [electron-userland/electron-builder#3361]
* **^20.28.4**: 

electron --version
v3.0.2

* **Snap**: 

I can build the AppImage but not the Snap version

```
node_modules/.bin/build --linux Snap
  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)

  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=3.0.2 appOutDir=dist/linux-unpacked


  • building        target=snap arch=x64 file=dist/borderless-camera_0.0.4_amd64.snap
  • downloading               path=/home/grigio/.cache/electron-builder/snap/snap-template-electron-2.3 url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-2.3/snap-template-electron-2.3.tar.7z
  • downloading               parts=8 size=46 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-2.3/snap-template-electron-2.3.tar.7z
  • retrying (1)             
  • retrying (2)             
  • retrying (1)             
  • retrying (3)             
  ⨯ part download request failed with status code 403
github.com/develar/app-builder/pkg/download.(*Part).doRequest
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/Part.go:127
github.com/develar/app-builder/pkg/download.(*Part).download
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/Part.go:66
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadResolved.func1.1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:110
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
	/Users/develar/go/src/github.com/develar/app-builder/pkg/util/async.go:67
runtime.goexit
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361
github.com/develar/app-builder/pkg/download.(*Part).download
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/Part.go:72
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadResolved.func1.1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:110
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
	/Users/develar/go/src/github.com/develar/app-builder/pkg/util/async.go:67
runtime.goexit
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Error: /home/grigio/Code/borderless-camera/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/grigio/Code/borderless-camera/node_modules/builder-util/src/util.ts:254:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
From previous event:
    at SnapTarget.build (/home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/targets/snap.ts:146:44)
    at Function.buildAsyncTargets (/home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
    at LinuxPackager.packageInDistributableFormat (/home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
    at /home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/platformPackager.ts:113:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at LinuxPackager.pack (/home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/grigio/Code/borderless-camera/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/grigio/Code/borderless-camera/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /home/grigio/Code/borderless-camera/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/grigio/Code/borderless-camera/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/home/grigio/Code/borderless-camera/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/home/grigio/Code/borderless-camera/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/grigio/Code/borderless-camera/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Object.args [as handler] (/home/grigio/Code/borderless-camera/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (/home/grigio/Code/borderless-camera/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/home/grigio/Code/borderless-camera/node_modules/yargs/yargs.js:1085:24)
    at Object.get [as argv] (/home/grigio/Code/borderless-camera/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/home/grigio/Code/borderless-camera/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)

```

**Comment by MohamedLamineAllal** [comment]
Why this is absolete ?

**Comment by hosseinsalemi** [comment]
same problem.

**Comment by touring** [comment]
same problem.

**Comment by BeliefRC** [comment]
same problem.

**Comment by karan-karnad** [comment]
@develar Facing the same issue

(⨯ part download request failed with status code 403
github.com/develar/app-builder/pkg/download.(*Part).doRequest
        /Volumes/data/Documents/app-builder/pkg/download/Part.go:126
github.com/develar/app-builder/pkg/download.(*Part).download
        /Volumes/data/Documents/app-builder/pkg/download/Part.go:67
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadResolved.func1.1
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:107
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/asm_amd64.s:1337  
  ⨯ /Users/karankarnad/BMS/DIY/nemesis/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                            Error: /Users/karankarnad/BMS/DIY/nemesis/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                at ChildProcess.<anonymous> (/Users/karankarnad/BMS/DIY/nemesis/node_modules/builder-util/src/util.ts:239:14)
                                                                                                                                                at Object.onceWrapper (events.js:291:20)
                                                                                                                                                at ChildProcess.emit (events.js:203:13)
                                                                                                                                                at maybeClose (internal/child_process.js:1021:16)
                                                                                                                                                at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)))
