### ISSUE TITLE
EACCES when using quitAndInstall electron 3

### ISSUE THREAD

**Issue by timotheeguerin** [electron-userland/electron-builder#3367]
* **Version**: 
  - Builder: 20.28.4
  - Updater: 3.1.2

* **Target**: 
Windows

```
C:\Users\tiguerin\AppData\Roaming\BatchExplorer\__update__\BatchExplorer Setup 0.18.3-stable.99.exe EACCES
        at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
        at onErrorNT (internal/child_process.js:406:16)
```

I believe the issue is that the `spawn` command doesn't actually throw an error that is catchable here https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/NsisUpdater.ts#L115

After testing locally I think the `try catch` needs to be changed to `on("error"` might have been a change to node 10 vs 8

This mock code for example works fine when using `.on("error"`
```ts
const { spawn } = require("child_process");

const installerPath = "C:\\Users\\tiguerin\\AppData\\Roaming\\BatchExplorer\\__update__\\BatchExplorer Setup 0.18.3-stable.99.exe";
const args = [];
const spawnOptions = {
    detached: true,
    stdio: "ignore",
};

const elevatePath = "C:\\Program Files\\BatchExplorer\\resources\\elevate.exe";

spawn(installerPath, args, spawnOptions).on("error", (e) => {
    // yes, such errors dispatched not as error event
    // https://github.com/electron-userland/electron-builder/issues/1129
    if ((e).code === "UNKNOWN" || (e).code === "EACCES") { // Node 8 sends errors: https://nodejs.org/dist/latest-v8.x/docs/api/errors.html#errors_common_system_errors
        console.log("Access denied or UNKNOWN error code on spawn, will be executed again using elevate")

        try {
            spawn(elevatePath, [installerPath].concat(args), spawnOptions).unref()
        } catch (e) {
            console.error("Elevate failed too", e);
        }
    } else {
        console.error("Error here", e);
    }
})
```

**Comment by dscalzi** [comment]
I have the same issue with the assisted installer for NSIS. Been an issue with my app since electron 3.x was released.

![image](https://user-images.githubusercontent.com/9703873/46566577-3c58ed80-c8ef-11e8-9e5c-e50013037d6c.png)

@develar Fix would be appreciated when you can, stuck on 2.x for now.

**Comment by dscalzi** [comment]
Do you know of any possible workaround for election 3? Looks like this won't be handled for a while.

**Comment by timotheeguerin** [comment]
not that I know of, I'll probably push the compiled js to another branch of my fork if this doesn't get merged and reference it in my package.json

**Comment by AhadCove** [comment]
I actually just started receiving the same error after updating to Electron 3.0.3 from 2.x.
:(

**Comment by Pagebakers** [comment]
Thanks @dscalzi That works

If you rename the package back to electron-updater you can just run
```
npm install electron-updater@https://github.com/WesterosCraftCode/electron-updater-bin
```
Without needing to change anything in the code.

**Comment by Franco8888** [comment]
I got mine working by including the node_modules's bin folders. I use to have

`"!**/node_modules/.bin" `
in the _files_ parameter in the _build_ param in **package.json.**

I removed this so no it includes the bin of each of the node modules.

I also include electron-updater and all of it's dependencies in thje files parameter.
