### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by mhomam** [electron-userland/electron-builder#3368]
* ** 20.28.4**: 

electron-builder: 20.28.4 & electron-updater: 3.1.2

* **Both  macOS & Windows**: 

I am using autoUpdater from electron-builder. But the app is not updating. I am getting the below errors.

Unhandled rejection TypeError: options.cancellationToken.createPromise is not a function
    at /Users/homam/Development/Electron/HompathElectron/node_modules/electron-updater/src/electronHttpExecutor.ts:19:44
    at Generator.next (<anonymous>)
From previous event:
    at ElectronHttpExecutor.download (/Users/homam/Development/Electron/HompathElectron/node_modules/electron-updater/src/electronHttpExecutor.ts:14:76)
    at Object.task (/Users/homam/Development/Electron/HompathElectron/node_modules/electron-updater/src/MacUpdater.ts:44:34)
    at /Users/homam/Development/Electron/HompathElectron/node_modules/electron-updater/src/AppUpdater.ts:570:25
    at Generator.throw (<anonymous>)
From previous event:
    at MacUpdater.executeDownload (/Users/homam/Development/Electron/HompathElectron/node_modules/electron-updater/src/AppUpdater.ts:487:68)
    at /Users/homam/Development/Electron/HompathElectron/node_modules/electron-updater/src/MacUpdater.ts:39:23
From previous event:
    at MacUpdater.doDownloadUpdate (/Users/homam/Development/Electron/HompathElectron/node_modules/electron-updater/src/MacUpdater.ts:22:80)
    at /Users/homam/Development/Electron/HompathElectron/node_modules/electron-updater/src/AppUpdater.ts:393:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater.downloadUpdate (/Users/homam/Development/Electron/HompathElectron/node_modules/electron-updater/src/AppUpdater.ts:382:86)
    at EventEmitter.ipcMain.on (/Users/homam/Development/Electron/HompathElectron/index.js:430:15)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at WebContents.<anonymous> (/Users/homam/Development/Electron/HompathElectron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

**Comment by framerate** [comment]
could be related to #3377
