### ISSUE TITLE
Error: Unsupported provider: undefined

### ISSUE THREAD

**Issue by pureZjr** [electron-userland/electron-builder#3369]
my build in package.json

```
 "publish": [
            {
                "provider": "generic",
                "url": "http://127.0.0.1:8082"
            }
        ],
```

error msg

```
[2018-10-08 14:32:51.278] [error] Error: Error: Unsupported provider: undefined
    at newError (/Users/pure/Desktop/test/test/node_modules/builder-util-runtime/src/index.ts:29:17)
    at createClient (/Users/pure/Desktop/test/test/node_modules/electron-updater/src/providerFactory.ts:47:13)
    at _this4.clientPromise._this4.configOnDisk.value.then.it (/Users/pure/Desktop/test/test/node_modules/electron-updater/src/AppUpdater.ts:339:63)
From previous event:
    at /Users/pure/Desktop/test/test/node_modules/electron-updater/src/AppUpdater.ts:339:52
    at next (<anonymous>)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at MacUpdater.getUpdateInfo (/Users/pure/Desktop/test/test/node_modules/electron-updater/src/AppUpdater.ts:335:32)
    at /Users/pure/Desktop/test/test/node_modules/electron-updater/src/AppUpdater.ts:349:35
    at next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Users/pure/Desktop/test/test/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /Users/pure/Desktop/test/test/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at next (<anonymous>)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at MacUpdater._checkForUpdates (/Users/pure/Desktop/test/test/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at MacUpdater.checkForUpdates (/Users/pure/Desktop/test/test/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at AutoUpdater.checkUpdate (/Users/pure/Desktop/test/test/main/appUpdater.ts:47:21)
    at EventEmitter.ipcMain.on (/Users/pure/Desktop/test/test/main/main.ts:24:29)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by mpeguero** [comment]
sometimes this issue come from this line:
autoUpdater.setFeedURL(feed); 
I tried to pass a object and it gave me this error
