### ISSUE TITLE
Mac build fails against electron v4.0.0-beta.3

### ISSUE THREAD

**Issue by npezza93** [electron-userland/electron-builder#3385]
* **Version**: 20.28.4
* **Target**: mac

When builder against electron v4.0.0-beta.3 I get the following error:
```
  • packaging       platform=darwin arch=x64 electron=4.0.0-beta.3 appOutDir=dist/mac
[xmldom error]  invalid doc source
@#[line:0,col:undefined]
TypeError: Cannot read property 'documentElement' of undefined
    at parse (/Users/nick/Documents/archipelago/node_modules/plist/lib/parse.js:68:9)
    at /Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/electron/electronMac.ts:51:25
From previous event:
    at createMacApp (/Users/nick/Documents/archipelago/node_modules/app-builder-lib/out/electron/electronMac.js:245:17)
    at /Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:75:11
    at Generator.next (<anonymous>)
From previous event:
    at beforeCopyExtraFiles (/Users/nick/Documents/archipelago/node_modules/app-builder-lib/out/electron/ElectronFramework.js:147:17)
    at beforeCopyExtraFiles (/Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:150:14)
    at /Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/platformPackager.ts:222:13
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at MacPackager.doPack (/Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/platformPackager.ts:166:165)
    at /Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/nick/Documents/archipelago/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/nick/Documents/archipelago/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /Users/nick/Documents/archipelago/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/nick/Documents/archipelago/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/Users/nick/Documents/archipelago/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/Users/nick/Documents/archipelago/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/nick/Documents/archipelago/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Object.args [as handler] (/Users/nick/Documents/archipelago/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (/Users/nick/Documents/archipelago/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/nick/Documents/archipelago/node_modules/yargs/yargs.js:1085:24)
    at Object.get [as argv] (/Users/nick/Documents/archipelago/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/Users/nick/Documents/archipelago/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)```

**Comment by christophpre** [comment]
Just tried this with the other 4.0.X betas. This seems to be an issue with all electron 4.0.X versions.

**Comment by alessandroliveri** [comment]
Hello!Any update?

**Comment by setpixel** [comment]
Yes - I have this problem too. I would love to know if it's a problem with electron 4.0+ or electron builder...

**Comment by audionerd** [comment]
Seeing this issue on a build with `electron v4.0.0-beta.5`.

**Comment by audionerd** [comment]
Possibly related to https://github.com/electron/electron/commit/e8782f2c2d6d7848db15cf7a3a7263e90016aeb0

**Comment by caesar** [comment]
@audionerd You're right. The error is being thrown here where the helper app plist is read:
https://github.com/electron-userland/electron-builder/blob/c35b3150536be66a9e1c2aae75f7e8f7f610699d/packages/app-builder-lib/src/electron/electronMac.ts#L51

**Comment by hn6pot** [comment]
Got the same issues on 4.0.1 using electronuserland/builder to build my app.

Any update ?

**Comment by dingchaoyan1983** [comment]
I have the same errors, any updates for this?

**Comment by hn6pot** [comment]
You should use electron builder 20.31.3, it works perfectly with electron 4.0.1 !

**Comment by develar** [comment]
Ok, I will recheck.

**Comment by npezza93** [comment]
Everything seems to be working for me on the latest 4.0.x release. Thanks for the fix! Feel free to reopen if there are still issues.
