### ISSUE TITLE
Building DMG hangs on OSX High Sierra 10.13.4（but 10.13.2 can）

### ISSUE THREAD

**Issue by luckybai** [electron-userland/electron-builder#3391]
**v19.5.1** && Mac high Sierra 10.13.4 (but Mac high Sierra 10.13.2 can build  dmg)

Version: 
**v19.21.0** (so i try this new version)

**none**

Target: 
**Mac DMG**

```
> build "--config" "./build/fd/assets/electron-builder.json"

electron-builder 19.21.0
Using build/fd/assets/electron-builder.json configuration file
Skip app dependencies rebuild because npmRebuild is set to false
Warning: Packaging using asar archive is disabled — it is strongly not recommended.
Please enable asar and use asarUnpack to unpack files that must be externally available.
Packaging for darwin x64 using electron 1.7.13 to dist/mac
Error: Application entry file "dist/main.js" does not exist. Seems like a wrong configuration.
    at /Users/lucky/Documents/project/ide/blacktea/node_modules/_electron-builder@19.21.0@electron-builder/src/platformPackager.ts:32
5:15
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/async.js:147:5)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/debuggability.js:411:19)
    at Promise._then (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/promise.js:232:17)
    at Promise.then (/Users/lucky/Documents/project/ide/blacktea/node_modules/_bluebird@3.5.2@bluebird/js/release/promise.js:125:17)
    at Object.args [as handler] (/Users/lucky/Documents/project/ide/blacktea/node_modules/_electron-builder@19.21.0@electron-builder/src/cli/cli.ts:49:4)
    at Object.self.runCommand (/Users/lucky/Documents/project/ide/blacktea/node_modules/_yargs@8.0.2@yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/lucky/Documents/project/ide/blacktea/node_modules/_yargs@8.0.2@yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/lucky/Documents/project/ide/blacktea/node_modules/_yargs@8.0.2@yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/lucky/Documents/project/ide/blacktea/node_modules/_electron-builder@19.21.0@electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! ide-ts@0.0.1 build:electron: `build "--config" "./build/fd/assets/electron-builder.json"`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the ide-ts@0.0.1 build:electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lucky/.npm/_logs/2018-10-15T07_21_57_661Z-debug.log
pack failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ide-ts@0.0.1 pack: `node build/pack.js "fd"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ide-ts@0.0.1 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lucky/.npm/_logs/2018-10-15T07_21_57_705Z-debug.log
```

**Comment by luckybai** [comment]
@Vladimir Krivosheev  can u help me? please
thx

**Comment by luckybai** [comment]
@develar can u help me? please
thx
