### ISSUE TITLE
"Incompatible library version" when running on different mac

### ISSUE THREAD

**Issue by awbacker** [electron-userland/electron-builder#3395]
* **Version**:  `electron-builder@20.14.7`
* **Target**:  `mac:dmg`

I am building an app for internal distribution, and most of us use macs (the Win10 builds are ok). When any of my coworkers runs the app they get an "Incompatible Library Version" when loading one of the `.dylib`s.  Which dylib is reported seems to change, but they all have similar messages:

* Using `sharp` (has all the fancy .dylib files)
* Using `canvas`
* Sharp & Canvas appear to be unpacked in Resources/app.asar.unpacked/
* I use macports, so I have most of the dylibs in /opt/local/lib/ for other purposes

It appears to be linking to my local version (or storing that version # somewhere), but including a different version in the .dmg file somehow.  I _think_ it tries to load the dylib, finds it in the .app/, but notices its the wrong version #.  So it appears to package right (?), but

Any idea what I should to do fix this issue?  I'm at a loss here, and tons of googling hasn't brought any help.  I'm sure there are some special keywords that'll turn up a blog post somewhere, but so far... no luck :D 

```
Uncaught Exception
    Error: dlopen(/var/folders/2g/{random string}/.org.mycompany.product.AB2CBj,1):
        Library not loaded: /opt/local/lib/ligpangocairo-1.0.0.dylib
            Referenced from: /var/folders/2g/{random string}/.org.mycompany.product.AB2CBj
            Reason: Incompatible library version:
                .org.mycompany.product.AB2CBj requires version 4201.0.0 or later, but
                libpangocairo-1.0.0.dylib provides version 4001

at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
at Object.module._extnesions..node (module.js:598:18)
at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
at Moduel.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Fucntion.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at Object.<anonymous>(...app.asar/node_modules/canvas/lib/bindings.js:3:18)
at Object.<anonymous>(...app.asar/nodel_modules/canva/lis/bindings.js:5:3)
```

```
$ otool -L /opt/local/lib/libpangocairo-1.0.0.dylib
/opt/local/lib/libpangocairo-1.0.0.dylib:
	/opt/local/lib/libpangocairo-1.0.0.dylib (compatibility version 4201.0.0, current version 4201.4.0)
```

In the app-build folder:
```
$ cd /app-builds/mac/product.app/Contents/Resources
$ otool -L ./app.asar.unpacked/node_modules/sharp/vendor/lib/libpangocairo-1.0.0.dylib
./app.asar.unpacked/node_modules/sharp/vendor/lib/libpangocairo-1.0.0.dylib:
	@rpath/libpangocairo-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.14.0)
```

Extracting from the app.asar (it seems to be here too, not just in "unpacked" as expected).
```
$ cd /app-builds/mac/product.app/Contents/Resources
$ asar extract app.asar .
$ otool -L ./node_modules/sharp/vendor/lib/libpangocairo-1.0.0.dylib
./node_modules/sharp/vendor/lib/libpangocairo-1.0.0.dylib:
	@rpath/libpangocairo-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.14.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1445.12.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 50.0.0)
	@rpath/libpango-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.14.0)
	@rpath/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.10.0)
	@rpath/libpangoft2-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.14.0)
        ....
```

**Comment by awbacker** [comment]
Found it...  There are 2 variables that are set in the .profile for macports, but they aren't `export`ed, which means they don't show up in `printenv`.  

Added this to my build/package/upload script and the lib errors went away:
```
unset LIBRARY_PATH
unset CPLUS_INCLUDE_PATH
```

**Comment by awbacker** [comment]
Doesn't appear to be an issue with electron-builder linking the libs, as I thought at first.

The issue was with `canvas` requiring shared libs, at least by default, and not with `sharp`.  Solved by removing canvas since our users will never have the libs installed!  If there is some way to get those in the .asar[.unpacked] and make canvas work without system shared libs, then I'd be interested to know, but I can't imagine that is the electron-builder's responsibility :D
