### ISSUE TITLE
Error: EEXIST: file already exists 

### ISSUE THREAD

**Issue by jacklovepdf** [electron-userland/electron-builder#3397]
electron-builder version=20.28.4

* **Version**: 20.28.4

* **Target**: dmg

    mgenerate result.json success
  • electron-builder version=20.28.4
  • artifacts will be published if draft release exists reason=CI detected
  • loaded configuration file=/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/builder-config/result.json
  • rebuilding native production dependencies platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=2.0.10 appOutDir=build/mac
  • asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available
Error: Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
Error: EEXIST: file already exists, link '/Users/smallnb/node_modules/dashdash/node_modules/assert-plus/AUTHORS' -> '/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/build/mac/Electron.app/Contents/Resources/app/node_modules/assert-plus/AUTHORS'
    at copyOrLinkFile (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/builder-util/src/fs.ts:186:12)
    at /Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/builder-util/src/fs.ts:261:11
    at Generator.next (<anonymous>)
From previous event:
    at FileCopier.copy (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/builder-util/src/fs.ts:239:64)
    at /Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/util/appFileCopier.ts:70:13
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at copyAppFiles (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/out/util/appFileCopier.js:260:17)
    at taskManager.addTask._bluebirdLst.default.each.it (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/platformPackager.ts:296:86)
From previous event:
    at MacPackager.copyAppFiles (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/platformPackager.ts:296:43)
    at /Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/platformPackager.ts:213:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at MacPackager.doPack (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/platformPackager.ts:166:165)
    at /Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Packager.doBuild (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/packager.ts:314:57
From previous event:
    at Packager._build (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.args [as handler] (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/electron-builder/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/electron-builder/node_modules/yargs/yargs.js:1085:24)
    at Object.get [as argv] (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/electron-builder/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/Users/smallnb/jenkins2/workspace/tt_micro_devtools_build/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3

**Comment by jacklovepdf** [comment]
this issue may similar with 
https://github.com/electron-userland/electron-builder/issues/3039;
but my electron-builder version is  latest;

**Comment by jacklovepdf** [comment]
sorry to close this issue that i have solve the  problem!

**Comment by angvp** [comment]
@jacklovepdf how did you solve it? :) for me it works randomly sometimes it packages well, sometimes it doesn't and this unreliability is driving us crazy :(

**Comment by julian-alarcon** [comment]
Same issue here on  https://github.com/IsmaelMartinez/teams-for-linux

**Comment by alex-dow** [comment]
I have the same issue. @jacklovepdf please explain your solution

**Comment by whysthatso** [comment]
@jacklovepdf some hint on how you fixed it would be really appreciated.
