### ISSUE TITLE
Build Error: TypeError: Cannot read property 'publisherName' of null

### ISSUE THREAD

**Issue by Nino9614** [electron-userland/electron-builder#3401]
Version: latest

Which version of electron-updater are you using : not using electron-updater

What target are you building for?: windows x64 x86

I currently have following problem: When running the dist command to generate a .exe Build of my application i get following error: 

`TypeError: Cannot read property 'publisherName' of null
    at D:\svn\IconFinderApp\node_modules\app-builder-lib\out\publish\PublishManager.js:575:73
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at getAppUpdatePublishConfiguration (D:\svn\IconFinderApp\node_modules\app-builder-lib\out\publish\PublishManager.js:593:18)
    at D:\svn\IconFinderApp\node_modules\app-builder-lib\src\publish\PublishManager.ts:97:9
    at next (native)
From previous event:
    at PublishManager.packager.addAfterPackHandler (D:\svn\IconFinderApp\node_modules\app-builder-lib\src\publish\PublishManager.ts:84:5)
    at _bluebirdLst.default.each.it (D:\svn\IconFinderApp\node_modules\app-builder-lib\src\packager.ts:473:49)
From previous event:
    at Packager.afterPack (D:\svn\IconFinderApp\node_modules\app-builder-lib\src\packager.ts:473:28)
    at D:\svn\IconFinderApp\node_modules\app-builder-lib\src\platformPackager.ts:233:21
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at WinPackager.doPack (D:\svn\IconFinderApp\node_modules\app-builder-lib\src\platformPackager.ts:166:165)
    at D:\svn\IconFinderApp\node_modules\app-builder-lib\src\platformPackager.ts:112:16
    at next (native)
From previous event:
    at WinPackager.pack (D:\svn\IconFinderApp\node_modules\app-builder-lib\src\platformPackager.ts:110:95)
    at D:\svn\IconFinderApp\node_modules\app-builder-lib\src\packager.ts:376:24
    at next (native)
    at xfs.stat (D:\svn\IconFinderApp\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at D:\svn\IconFinderApp\node_modules\graceful-fs\polyfills.js:287:18
From previous event:
    at Packager.doBuild (D:\svn\IconFinderApp\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\svn\IconFinderApp\node_modules\app-builder-lib\src\packager.ts:314:57
    at next (native)
    at D:\svn\IconFinderApp\node_modules\graceful-fs\graceful-fs.js:99:16
    at D:\svn\IconFinderApp\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager._build (D:\svn\IconFinderApp\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\svn\IconFinderApp\node_modules\app-builder-lib\src\packager.ts:281:23
    at next (native)
From previous event:
    at Packager.build (D:\svn\IconFinderApp\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\svn\IconFinderApp\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\svn\IconFinderApp\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\svn\IconFinderApp\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (D:\svn\IconFinderApp\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at Object.runCommand (D:\svn\IconFinderApp\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (D:\svn\IconFinderApp\node_modules\yargs\yargs.js:1085:24)
    at Object.get [as argv] (D:\svn\IconFinderApp\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (D:\svn\IconFinderApp\node_modules\electron-builder\src\cli\cli.ts:25:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3`

I cant find any thing about this field in the docs.  In my build before i never experienced this kind of error before. Is this something new thing?

**Comment by AhadCove** [comment]
Add a publisherName under your electron windows configuration
https://www.electron.build/configuration/win
