### ISSUE TITLE
electronDist - error building with custom electron build

### ISSUE THREAD

**Issue by rr326** [electron-userland/electron-builder#3407]
* **Version**: 20.28.4

NA

* **Target**:  mas

I am creating a custom electron build with [electron's documentation](https://electronjs.org/docs/development/build-instructions-gn). I can properly open the resulting Electron.app (eg: `electron-gn/src/out/Release/Electron.app`).

In my build config I set: `electronDist: path.resolve(__dirname, 'electron/electron-gn/src/out/Release')`
Then I get a long string of errors. (I think the error starts after the copying is complete.)

Do I need some special parameters in my electron build, or am I doing something else wrong?

     • copying Electron source=/Users/johndoe/dev/filing/electron/electron-gn/src/out/Debug/Electron.app destination=/Users/johndoe/dev/filing/dist_masdev/mas-dev/Electron.app
    [xmldom error]  invalid doc source
    @#[line:0,col:undefined]
    TypeError: Cannot read property 'documentElement' of undefined
        at parse (/Users/johndoe/dev/filing/node_modules/plist/lib/parse.js:68:9)
        at /Users/johndoe/dev/filing/node_modules/app-builder-lib/src/electron/electronMac.ts:51:25
    From previous event:
        at createMacApp (/Users/johndoe/dev/filing/node_modules/app-builder-lib/out/electron/electronMac.js:245:17)
        at /Users/johndoe/dev/filing/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:75:11
        at Generator.next (<anonymous>)
    From previous event:
        at beforeCopyExtraFiles (/Users/johndoe/dev/filing/node_modules/app-builder-lib/out/electron/ElectronFramework.js:147:17)
        at beforeCopyExtraFiles (/Users/johndoe/dev/filing/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:150:14)
        at /Users/johndoe/dev/filing/node_modules/app-builder-lib/src/platformPackager.ts:222:13
        at Generator.next (<anonymous>)
        at runCallback (timers.js:810:20)
        at tryOnImmediate (timers.js:768:5)
        at processImmediate [as _immediateCallback] (timers.js:745:5)
    From previous event:
        at MacPackager.doPack (/Users/johndoe/dev/filing/node_modules/app-builder-lib/src/platformPackager.ts:166:165)
        at /Users/johndoe/dev/filing/node_modules/app-builder-lib/src/macPackager.ts:108:20
        at Generator.next (<anonymous>)
    From previous event:
        at MacPackager.pack (/Users/johndoe/dev/filing/node_modules/app-builder-lib/src/macPackager.ts:80:95)
        at /Users/johndoe/dev/filing/node_modules/app-builder-lib/src/packager.ts:376:24
        at Generator.next (<anonymous>)
        at runCallback (timers.js:810:20)
        at tryOnImmediate (timers.js:768:5)
        at processImmediate [as _immediateCallback] (timers.js:745:5)
    From previous event:
        at Packager.doBuild (/Users/johndoe/dev/filing/node_modules/app-builder-lib/src/packager.ts:344:39)
        at /Users/johndoe/dev/filing/node_modules/app-builder-lib/src/packager.ts:314:57
        at Generator.next (<anonymous>)
        at /Users/johndoe/dev/filing/node_modules/graceful-fs/graceful-fs.js:99:16
        at /Users/johndoe/dev/filing/node_modules/graceful-fs/graceful-fs.js:43:10
        at FSReqWrap.oncomplete (fs.js:135:15)
    From previous event:
        at Packager._build (/Users/johndoe/dev/filing/node_modules/app-builder-lib/src/packager.ts:285:133)
        at /Users/johndoe/dev/filing/node_modules/app-builder-lib/src/packager.ts:281:23
        at Generator.next (<anonymous>)
    From previous event:
        at Packager.build (/Users/johndoe/dev/filing/node_modules/app-builder-lib/src/packager.ts:238:14)
        at build (/Users/johndoe/dev/filing/node_modules/app-builder-lib/src/index.ts:58:28)
        at build (/Users/johndoe/dev/filing/node_modules/electron-builder/src/builder.ts:227:10)
        at then (/Users/johndoe/dev/filing/node_modules/electron-builder/src/cli/cli.ts:42:48)
        at runCallback (timers.js:810:20)
        at tryOnImmediate (timers.js:768:5)
        at processImmediate [as _immediateCallback] (timers.js:745:5)
    From previous event:
        at Object.args [as handler] (/Users/johndoe/dev/filing/node_modules/electron-builder/src/cli/cli.ts:42:48)
        at Object.runCommand (/Users/johndoe/dev/filing/node_modules/yargs/lib/command.js:238:44)
        at Object.parseArgs [as _parseArgs] (/Users/johndoe/dev/filing/node_modules/yargs/yargs.js:1085:24)
        at Object.get [as argv] (/Users/johndoe/dev/filing/node_modules/yargs/yargs.js:1000:21)
        at Object.<anonymous> (/Users/johndoe/dev/filing/node_modules/electron-builder/src/cli/cli.ts:25:28)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Function.Module.runMain (module.js:693:10)
        at startup (bootstrap_node.js:191:16)
        at bootstrap_node.js:612:3

**Comment by christophpre** [comment]
From to output this looks related to #3385

**Comment by rr326** [comment]
No - this is electron 3.0.5 (and 3.0.4)

**Comment by develar** [comment]
Please try 20.31.2
