### ISSUE TITLE
electron-builder crashes when building a Linux AppImage build on Windows

### ISSUE THREAD

**Issue by serge1peshcoff** [electron-userland/electron-builder#3413]
* **Version**: electron-builder@20.28.4
* **Node version**: v10.2.1
* **npm version**: 5.6.0
* **Target**: Linux
* **Host**: Windows

When I try to build electron app for Linux on Windows, the build script crashes. If I do the same on Mac, it will work flawlessly. Building Windows build on Windows also works fine. Tested it on 2 machines and got the same result, so it shouldn't be the environment.
Here's the log:

```sh
D:\builds\Archive>npm run dist:linux

> neuroAd@1.0.38 dist:linux D:\builds\Archive
> electron-builder --linux

  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=3.0.5 appOutDir=dist\linux-unpacked
←[34m  •←[0m downloading               ←[34mparts←[0m=8 ←[34msize←[0m=52 MB ←[34murl←[0m=https://github.com/electron/electron/releases/download/v3.0.5/electron-v3.0.5-linux-x64.zip
←[34m  •←[0m downloaded                ←[34mduration←[0m=17.87s ←[34murl←[0m=https://github.com/electron/electron/releases/download/v3.0.5/electron-v3.0.5-linux-x64.zip
  • scheduling remote build target=snap arch=x64
  • scheduling remote build target=appImage arch=x64
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x988628]

goroutine 1 [running]:
github.com/develar/app-builder/pkg/remoteBuild.getBuildAgentEndpoint(0xc04223eb70, 0xc042017040, 0x40, 0x0, 0x0, 0x0, 0x0)
        /Users/develar/go/src/github.com/develar/app-builder/pkg/remoteBuild/buildAgentEndpoint.go:53 +0x88
github.com/develar/app-builder/pkg/remoteBuild.findBuildAgent(0xc042240870, 0x0, 0xf3b940, 0x280, 0xb0000)
        /Users/develar/go/src/github.com/develar/app-builder/pkg/remoteBuild/buildAgentEndpoint.go:34 +0x35a
github.com/develar/app-builder/pkg/remoteBuild.(*RemoteBuilder).build(0xc042239500, 0xc0422440b0, 0xa4, 0xc042238920, 0x2, 0x2, 0xc04201ae40, 0x16, 0xc04201af00, 0x17, ...)
        /Users/develar/go/src/github.com/develar/app-builder/pkg/remoteBuild/RemoteBuilder.go:62 +0x56
github.com/develar/app-builder/pkg/remoteBuild.ConfigureBuildCommand.func1(0xc042208a20, 0x40e6ca, 0xa49c40)
        /Users/develar/go/src/github.com/develar/app-builder/pkg/remoteBuild/RemoteBuilder.go:36 +0x15f
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions(0xc0420b6498, 0xc042208a20, 0x0, 0x0)
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28 +0x74
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions(0xc0420b8690, 0xc042208a20, 0x0, 0x0)
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557 +0xe5
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute(0xc0420b8690, 0xc042208a20, 0xc0421b4770, 0x1, 0x1, 0x0, 0x0, 0x7b0209, 0xa32a40)
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390 +0x96
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse(0xc0420b8690, 0xc042082010, 0xb, 0xf, 0xc04201c3b8, 0x0, 0x2, 0x2)
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222 +0x1f9
main.main()
        /Users/develar/go/src/github.com/develar/app-builder/main.go:74 +0x1a4
Error: D:\builds\Archive\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 2
    at ChildProcess.childProcess.once.code (D:\builds\Archive\node_modules\builder-util\src\util.ts:254:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at RemoteBuilder._build (D:\builds\Archive\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:56:83)
    at _bluebirdLst.default.mapSeries.arch (D:\builds\Archive\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:51:19)
From previous event:
    at RemoteBuilder.build (D:\builds\Archive\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:50:28)
    at D:\builds\Archive\node_modules\app-builder-lib\src\linuxPackager.ts:99:30
From previous event:
    at RemoteTarget.finishBuild (D:\builds\Archive\node_modules\app-builder-lib\src\linuxPackager.ts:97:20)
    at D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:384:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.doBuild (D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:314:57
    at Generator.next (<anonymous>)
    at D:\builds\Archive\node_modules\graceful-fs\graceful-fs.js:99:16
    at D:\builds\Archive\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\builds\Archive\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\builds\Archive\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\builds\Archive\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Object.args [as handler] (D:\builds\Archive\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at Object.runCommand (D:\builds\Archive\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (D:\builds\Archive\node_modules\yargs\yargs.js:1085:24)
    at Object.get [as argv] (D:\builds\Archive\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (D:\builds\Archive\node_modules\electron-builder\src\cli\cli.ts:25:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! neuroAd@1.0.38 dist:linux: `electron-builder --linux`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the neuroAd@1.0.38 dist:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\goe\AppData\Roaming\npm-cache\_logs\2018-10-24T11_27_26_798Z-debug.log

```

And the `package.json` (I've removed all of the company data since it's under NDA):

```js
{
  "name": "test",
  "version": "1.0.38",
  "description": "Description",
  "main": "index.js",
  "scripts": {
    "start": "electron .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "pack": "electron-builder --dir",
    "dist": "electron-builder --linux --win",
    "dist:linux": "electron-builder --linux",
    "dist:win": "electron-builder --win",
    "publish:linux": "publish config.json linux",
    "publish:win": "publish config.json win32",
    "buildall": "npm run build && npm run publish:linux && npm run publish:win"
  },
  "author": "test",
  "license": "ISC",
  "devDependencies": {
    "electron": "^3.0.5",
    "electron-builder": "^20.28.4",
    "electron-packager": "^12.2.0",
    "electron-simple-publisher": "^0.4.12",
    "node-gyp": "^3.8.0"
  },
  "dependencies": {
    "electron-builder-squirrel-windows": "^20.28.3",
    "electron-dl": "^1.12.0",
    "electron-simple-updater": "^1.2.4",
    "fs": "0.0.1-security",
    "fs-sync": "^1.0.6",
    "http": "0.0.0",
    "ip": "^1.1.5",
    "md5-file": "^4.0.0",
    "mime-types": "^2.1.21",
    "moment": "^2.22.2",
    "node-fetch": "^2.2.0",
    "path": "^0.12.7",
    "url": "^0.11.0"
  },
  "build": {
    "appImage": {
      "systemIntegration": "doNotAsk"
    },
    "win": {
      "target": "squirrel"
    }
  }
}
```

**Comment by serge1peshcoff** [comment]
I think I've found the reason: this file: https://github.com/develar/app-builder/blob/master/pkg/remoteBuild/buildAgentEndpoint.go, function `getBuildAgentEndpoint`, line 53. When the request is failing for some reason, before checking for error, the this function tries to access `response.Body`, which I suppose can be nil, hence the panic.

Can someone move the `if err != nil` before the `if response.Body != nil` part? That should fix it.

**Comment by serge1peshcoff** [comment]
I've created a PR that should fix it: https://github.com/develar/app-builder/pull/6, can someone merge it, re-submit to npm and bump the version here?

**Comment by serge1peshcoff** [comment]
Fixed, thanks to @develar.

**Comment by zhangxing406** [comment]
I pack electron app on windows for linux, but some problem happend,[33mwaitTime?[0m=6
?[31m  ⨯?[0m Get https://service.electron.build/find-build-agent?no-cache=1edq2i5: dial tcp 51.38.69.239:443: connectex: No connection could be made because the target machine actively refused it.
have you met?

**Comment by ThummalaJanardhanReddy** [comment]
Hi Team,
I'm getting below error while trying to build for Linux.

 cannot get, wait  error=Get https://service.electron.build/find-build-agent?no-cache=1f42ij9: dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=0
                      waitTime=2
  • cannot get, wait  error=Get https://service.electron.build/find-build-agent?no-cache=1f42ij9: dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=1
                      waitTime=4
  • cannot get, wait  error=Get https://service.electron.build/find-build-agent?no-cache=1f42ij9: dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=2
                      waitTime=6
  ⨯ Get https://service.electron.build/find-build-agent?no-cache=1f42ij9: dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.

**Comment by frankjoke** [comment]
Same problem packing linux app on windows machine.

**Comment by miyanoyuriko** [comment]
> Same problem packing linux app on windows machine.

HI,did you solve this problem?How did you build app for linux at last?

**Comment by frankjoke** [comment]
No, did not solve it and was not able to build app, also not on newer version of electron.

**Comment by miyanoshiyo** [comment]
> No, did not solve it and was not able to build app, also not on newer version of electron.

You can build it on Linux, it is can be successful.
If you want to build a package for Linux, it is hard to success on Windows
