### ISSUE TITLE
https://service.electron.build uses invalid SSL certificate, causing app-builder to crash when scheduling remote build

### ISSUE THREAD

**Issue by serge1peshcoff** [electron-userland/electron-builder#3419]
(Not sure if it's this repo or develap/app-builder that is more suitable for this issue)

When I try to build Linux Electron app on Windows using electron-builder, it tries to schedule remote build. When app-builder tries to access `https://service.electron.build/find-build-agent`, it results in an error because of the invalid SSL certificate, and it causes app-builder to crash and build process to fail (see https://github.com/electron-userland/electron-builder/issues/3413 and https://github.com/develar/app-builder/pull/6). I've fixed the app crashing problem in this PR: https://github.com/develar/app-builder/pull/6, but fetching this addres is still not working because of SSL certificate.

I can reproduce it in browser as well:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/1060257/47531036-10f56d00-d8b5-11e8-9b5f-31d9aeae3893.png">

Can something be done about it?

**Comment by serge1peshcoff** [comment]
okay, so I've tried to build my own app-builder without any SSL validity checks, as described here: https://stackoverflow.com/questions/12122159/how-to-do-a-https-request-with-bad-certificate, and now it fails because of the timeout after 30 minutes, but it's fetching the address at least.

For those who stumbled upon it, here's how I resolved it: in this file https://github.com/develar/app-builder/blob/master/pkg/remoteBuild/RemoteBuilder.go in the `newRemoteBuilder` function change  transport declaration:

```
TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
```

and add crypto/tls to imports.

**Comment by develar** [comment]
@serge1peshcoff There are some issues with build service, I will fix it in several days.

**Comment by serge1peshcoff** [comment]
I still see the invalid certificate message on service.electron.build :(

**Comment by develar** [comment]
@serge1peshcoff Remote build works for me. Or do you mean in browser?

**Comment by serge1peshcoff** [comment]
@develar I didn't try remote builds yet, but for me the last time it was failing because of the issues with SSL certificate, if I won't use the custom build with all of the SSL checks disabled (like in this comment: https://github.com/electron-userland/electron-builder/issues/3419#issuecomment-433333462). So there was 2 issues, 1 is invalid SSL certificate (which is still the issue, I suppose) and other is remote builds not working (I didn't check this yet, will check in an hour, but probably fixed, as you've described).

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-build-service#privacy about 

> Custom certificate authority is used and required by client (electron-builder), it means that even if someone will take control over domain, build will be rejected due to incorrect certificate (build agent certificate must be issued only by expected certificate authority).

Custom CA cert is hidden and not available in internet. Valid for 1 year.

For each build agent by this CA issued certificate that valid only for 3 months, to ensure that if agent machine will be compomised, cert will be not used long.

**Comment by serge1peshcoff** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/1060257/47634669-62c31f00-db63-11e8-8532-dabd2d2c765f.png">

@develar what do you think can be the issue with this certificate? Can you check if it's working for you in a browser and in application?

**Comment by develar** [comment]
Спасибо вам, а то бы я так и забыл, так как фокус пока что не на проекте.

**Comment by serge1peshcoff** [comment]
@develar да не за что ;)

Сейчас попробовал запустить, свою версию, версию из репозитория, версию из NPM, SSL подключение работает на всех, но билд все равно не собирается. Вот логи мои:

```sh
$ npm run dist:linux

> neuroAd@1.0.38 dist:linux D:\builds\Archive
> electron-builder --linux

  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=3.0.5 appOutDir=dist\linux-unpacked
  • scheduling remote build target=snap arch=x64
  • scheduling remote build target=appImage arch=x64
  • compressing and uploading to remote builder
  • uploaded to remote builder duration=33.128s
  • remote building           status=job started (queue time: 0s)
  • remote building           status=build in progress...
  • remote building           status=build in progress...
  • remote building           status=build in progress...
  • remote building           status=build in progress...
  • remote building           status=  • electron-builder version=20.29.1
  • building        target=snap arch=x64 file=out/neuroAd_1.0.38_amd64.snap
  • building        target=AppImage arch=x64 file=out/neuroAd-1.0.38-x86_64.AppImage
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category
  • downloading               parts=8 size=81 PB url=neuroAd-1.0.38-x86_64.AppImage
  ⨯ part download request failed with status code 416
github.com/develar/app-builder/pkg/download.(*Part).doRequest
        C:/Users/goe/go/src/github.com/develar/app-builder/pkg/download/Part.go:127
github.com/develar/app-builder/pkg/download.(*Part).download
        C:/Users/goe/go/src/github.com/develar/app-builder/pkg/download/Part.go:46
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadResolved.func1.1
        C:/Users/goe/go/src/github.com/develar/app-builder/pkg/download/downloader.go:110
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        C:/Users/goe/go/src/github.com/develar/app-builder/pkg/util/async.go:67
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:1333

Error: D:\builds\Archive\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (D:\builds\Archive\node_modules\builder-util\src\util.ts:254:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at RemoteBuilder._build (D:\builds\Archive\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:56:83)
    at _bluebirdLst.default.mapSeries.arch (D:\builds\Archive\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:51:19)
From previous event:
    at RemoteBuilder.build (D:\builds\Archive\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:50:28)
    at D:\builds\Archive\node_modules\app-builder-lib\src\linuxPackager.ts:99:30
From previous event:
    at RemoteTarget.finishBuild (D:\builds\Archive\node_modules\app-builder-lib\src\linuxPackager.ts:97:20)
    at D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:384:36
From previous event:
    at Packager.doBuild (D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:314:57
From previous event:
    at Packager._build (D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\builds\Archive\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\builds\Archive\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\builds\Archive\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Object.args [as handler] (D:\builds\Archive\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at Object.runCommand (D:\builds\Archive\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (D:\builds\Archive\node_modules\yargs\yargs.js:1085:24)
    at Object.get [as argv] (D:\builds\Archive\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (D:\builds\Archive\node_modules\electron-builder\src\cli\cli.ts:25:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! neuroAd@1.0.38 dist:linux: `electron-builder --linux`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the neuroAd@1.0.38 dist:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\goe\AppData\Roaming\npm-cache\_logs\2018-10-29T07_31_48_456Z-debug.log
```

Есть идеи, из-за чего может быть?

**Comment by develar** [comment]
Could you please try 20.29.1?

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` (https://www.electron.build/#debug) and attach log of the terminal output.

**Comment by serge1peshcoff** [comment]
@develar here you go:

```sh
$ DEBUG=electron-builder npm run dist:linux

> neuroAd@1.0.38 dist:linux D:\builds\Archive
> electron-builder --linux

  • electron-builder version=20.29.1
  • loaded configuration file=package.json ("build" field)
  • effective config config=
                       directories:
                         output: dist
                         buildResources: build
                       appImage:
                         systemIntegration: doNotAsk
                       win:
                         target: squirrel

  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=3.0.5 appOutDir=dist\linux-unpacked
  • spawning        command=D:\builds\Archive\node_modules\app-builder-lib\node_modules\app-builder-bin\win\x64\app-builder.exe unpack-electron --configuration [{"platform":"linux","arch":"x64","version":"3.0.5"}] --output D:\builds\Archive\dist\linux-unpacked --distMacOsAppName Electron.app
  • map async                 taskCount=2
  • map async                 taskCount=1
  • map async                 taskCount=70
  • exited          command=app-builder.exe code=0 pid=6640
  • spawning        command=D:\builds\Archive\node_modules\app-builder-lib\node_modules\app-builder-bin\win\x64\app-builder.exe node-dep-tree --dir D:\builds\Archive
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=async-exit-hook, electron-publish, minimatch, plist, fs-extra-p, is-ci, js-yaml, sanitize-filename, 7zip-bin, chromium-pickle-js, ejs, isbinaryfile, lazy-val, normalize-package-data, semver, temp-file, bluebird-lst, hosted-git-info, read-config-file
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=bluebird-lst, debug, fs-extra-p, sax
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=ms
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules\app-builder-lib\node_modules round=0 unresolved=bluebird, compare-version, isbinaryfile, minimist, plist
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=1 unresolved=bluebird, compare-version, isbinaryfile, , plist
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=js-yaml, lazy-val, source-map-support, stat-mode, bluebird-lst, semver, app-builder-bin, chalk, is-ci, 7zip-bin, builder-util-runtime, debug, fs-extra-p, temp-file
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=bluebird-lst, fs-extra-p, sax
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=ms
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=chalk, fs-extra-p, lazy-val, mime, bluebird-lst
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=bluebird-lst, fs-extra-p, sax
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=ms
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=builder-util-runtime, chalk, fs-extra-p, lazy-val, stat-mode, 7zip-bin, is-ci, semver, bluebird-lst, debug, js-yaml, source-map-support, temp-file
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=xmldom
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=bluebird-lst
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=graceful-fs, jsonfile, universalify
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=dotenv-expand, fs-extra-p, bluebird-lst, dotenv, js-yaml, json5, lazy-val, ajv-keywords
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=uri-js, fast-json-stable-stringify
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=js-yaml, source-map-support, lazy-val, 7zip-bin, bluebird-lst, builder-util-runtime, chalk, is-ci, semver, app-builder-bin, stat-mode, temp-file, fs-extra-p
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=ms
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=buffer-crc32, crc32-stream, readable-stream
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=remove-trailing-separator
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=base64-js, ieee754
  • unresolved deps           nodeModuleDir=D:\builds\Archive\node_modules round=0 unresolved=buffer-alloc, end-of-stream, fs-constants, readable-stream, to-buffer, bl
  • exited          command=app-builder.exe code=0 pid=7684 out=[{"dir":"D:\\builds\\Archive\\node_modules","deps":["7zip-bin","ajv-keywords","ansi-styles","app-builder-bin","app-builder-lib","archiver","archiver-utils","argparse","async","async-exit-hook","balanced-match","base64-js","bl","bluebird","bluebird-lst","brace-expansion","buffer-alloc","buffer-alloc-unsafe","buffer-crc32","buffer-fill","buffer-from","builder-util","builder-util-runtime","builtin-modules","chalk","chromium-pickle-js","ci-info","color-convert","color-name","compare-version","compress-commons","concat-map","core-util-is","crc","crc32-stream","debug","dotenv","dotenv-expand","ejs","electron-builder-squirrel-windows","electron-dl","electron-publish","electron-simple-updater","end-of-stream","escape-string-regexp","esprima","ext-list","ext-name","fast-json-stable-stringify","fs","fs-constants","fs-extra-p","fs-sync","fs.realpath","glob","graceful-fs","grep","has-flag","hosted-git-info","http","httpreq","iconv-lite","ieee754","inflight","inherits","ip","is-builtin-module","is-ci","is-plain-obj","isarray","isbinaryfile","js-yaml","json5","jsonfile","lazy-val","lazystream","lodash","lodash.assign","lodash.defaults","lodash.difference","lodash.flatten","lodash.isplainobject","lodash.toarray","lodash.union","md5-file","mime","mime-db","mime-types","minimatch","minimist","mkdirp","modify-filename","moment","ms","node-fetch","normalize-package-data","normalize-path","once","path","path-exists","path-is-absolute","plist","process","process-nextick-args","punycode","pupa","querystring","read-config-file","readable-stream","remove-trailing-separator","rimraf","safe-buffer","safer-buffer","sanitize-filename","sax","semver","sort-keys","sort-keys-length","source-map","source-map-support","spdx-correct","spdx-exceptions","spdx-expression-parse","spdx-license-ids","sprintf-js","stat-mode","string_decoder","supports-color","tar-stream","temp-file","to-buffer","truncate-utf8-bytes","universalify","unused-filename","uri-js","url","utf8-byte-length","util","util-deprecate","validate-npm-package-license","wrappy","xmldom","zip-stream"]},{"dir":"D:\\builds\\Archive\\node_modules\\app-builder-lib\\node_modules","deps":["app-builder-bin","builder-util","builder-util-runtime","debug","electron-osx-sign","minimist"]},{"dir":"D:\\builds\\Archive\\node_modules\\builder-util\\node_modules","deps":["debug"]},{"dir":"D:\\builds\\Archive\\node_modules\\builder-util-runtime\\node_modules","deps":["debug"]},{"dir":"D:\\builds\\Archive\\node_modules\\compress-commons\\node_modules","deps":["normalize-path"]},{"dir":"D:\\builds\\Archive\\node_modules\\crc\\node_modules","deps":["buffer"]},{"dir":"D:\\builds\\Archive\\node_modules\\electron-publish\\node_modules","deps":["app-builder-bin","builder-util","builder-util-runtime","debug"]},{"dir":"D:\\builds\\Archive\\node_modules\\fs-extra-p\\node_modules","deps":["fs-extra"]},{"dir":"D:\\builds\\Archive\\node_modules\\json5\\node_modules","deps":["minimist"]},{"dir":"D:\\builds\\Archive\\node_modules\\mime-types\\node_modules","deps":["mime-db"]},{"dir":"D:\\builds\\Archive\\node_modules\\plist\\node_modules","deps":["base64-js","xmlbuilder"]},{"dir":"D:\\builds\\Archive\\node_modules\\read-config-file\\node_modules","deps":["ajv","fast-deep-equal","json-schema-traverse"]},{"dir":"D:\\builds\\Archive\\node_modules\\tar-stream\\node_modules","deps":["xtend"]},{"dir":"D:\\builds\\Archive\\node_modules\\uri-js\\node_modules","deps":["punycode"]},{"dir":"D:\\builds\\Archive\\node_modules\\app-builder-lib\\node_modules\\electron-osx-sign\\node_modules","deps":["debug","ms"]}]
  • not packed into asar archive file=node_modules\7zip-bin\mac\7za reason=contains executable code
  • not packed into asar archive file=node_modules\app-builder-bin\mac\app-builder reason=contains executable code
  • not packed into asar archive file=node_modules\app-builder-lib\node_modules\app-builder-bin\mac\app-builder reason=contains executable code
  • not packed into asar archive file=node_modules\electron-publish\node_modules\app-builder-bin\mac\app-builder reason=contains executable code
  • scheduling remote build target=snap arch=x64
  • scheduling remote build target=appImage arch=x64
  • remote building remoteTargets=
                      [
                        {
                          "name": "snap",
                          "arch": "x64",
                          "unpackedDirectory": "D:\\builds\\Archive\\dist\\linux-unpacked",
                          "outDir": "D:\\builds\\Archive\\dist"
                        },
                        {
                          "name": "appImage",
                          "arch": "x64",
                          "unpackedDirectory": "D:\\builds\\Archive\\dist\\linux-unpacked",
                          "outDir": "D:\\builds\\Archive\\dist"
                        }
                      ]
  • spawning        command=D:\builds\Archive\node_modules\app-builder-lib\node_modules\app-builder-bin\win\x64\app-builder.exe remote-build --request eyJ0YXJnZXRzIjpbeyJuYW1lIjoic25hcCIsImFyY2giOiJ4NjQiLCJ1bnBhY2tlZERpck5hbWUiOiJsaW51eC11bnBhY2tlZCJ9LHsibmFtZSI6ImFwcEltYWdlIiwiYXJjaCI6Ing2NCIsInVucGFja2VkRGlyTmFtZSI6ImxpbnV4LXVucGFja2VkIn1dLCJwbGF0Zm9ybSI6ImxpbnV4In0= --output D:\builds\Archive\dist --file D:\builds\Archive\dist\linux-unpacked --file C:\Users\goe\AppData\Local\Temp\temp-dir-5snDoX\remote-build-metadata-0\info.json --build-resource-dir D:\builds\Archive\build
  • found existing            path=C:\Users\goe\AppData\Local\electron-builder\Cache\zstd\zstd-1.3.5-win-x64
  • compressing and uploading to remote builder
  • uploaded to remote builder duration=30.546s
  • remote builder event      event={"status":"job started (queue time: 1ms)"}
  • remote building           status=job started (queue time: 1ms)
  • remote builder event      event={"status":"build in progress..."}
  • remote building           status=build in progress...
  • remote builder event      event={"status":"build in progress..."}
  • remote building           status=build in progress...
  • remote builder event      event={"status":"build in progress..."}
  • remote building           status=build in progress...
  • remote builder event      event={"status":"build in progress..."}
  • remote building           status=build in progress...
  • remote builder event      event={"status":"build in progress..."}
  • remote building           status=build in progress...
  • remote builder event      event={"status":"build in progress..."}
  • remote building           status=build in progress...
  • remote builder event      event={"status":"build in progress..."}
  • remote building           status=build in progress...
  • remote builder event      event={"status":"build in progress..."}
  • remote building           status=build in progress...
  • remote builder event      event={"status":"build in progress..."}
  • remote building           status=build in progress...
  • remote builder event      event={"status":"build in progress..."}
  • remote building           status=build in progress...
  • remote builder event      event={"status":"build in progress..."}
  • remote building           status=build in progress...
  • remote builder event      event={"status":"  \u001b[34m•\u001b[39m electron-builder \u001b[34mversion\u001b[39m=20.29.1\n  \u001b[34m•\u001b[39m building        \u001b[34mtarget\u001b[39m=snap \u001b[34march\u001b[39m=x64 \u001b[34mfile\u001b[39m=out/neuroAd_1.0.38_amd64.snap\n  \u001b[34m•\u001b[39m building        \u001b[34mtarget\u001b[39m=AppImage \u001b[34march\u001b[39m=x64 \u001b[34mfile\u001b[39m=out/neuroAd-1.0.38-x86_64.AppImage\n  \u001b[33m•\u001b[39m application Linux category is set to default \"Utility\" \u001b[33mreason\u001b[39m=linux.category is not set and cannot map from macOS \u001b[33mdocs\u001b[39m=https://electron.build/configuration/configuration#LinuxBuildOptions-category\n  \u001b[33m•\u001b[39m application Linux category is set to default \"Utility\" \u001b[33mreason\u001b[39m=linux.category is not set and cannot map from macOS \u001b[33mdocs\u001b[39m=https://electron.build/configuration/configuration#LinuxBuildOptions-category\n"}
  • remote building           status=  • electron-builder version=20.29.1
  • building        target=snap arch=x64 file=out/neuroAd_1.0.38_amd64.snap
  • building        target=AppImage arch=x64 file=out/neuroAd-1.0.38-x86_64.AppImage
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category
  • remote builder event      event={"baseUrl":"/v2/download/1CF5iHJkOAaPa5acpAow4ue3zDn","files":[{"file":"neuroAd-1.0.38-x86_64.AppImage","target":"appImage","arch":1,"safeArtifactName":null,"isWriteUpdateInfo":true,"updateInfo":{"size":82271991,"sha512":"+vBSLVMk0vEIkqF4FzRdv+5KsrVSw0ztQeK0bZIRvWA73vJh6UEnGybUuG3SR2YpgdbOH385mSX5BdPpfefb5g==","blockMapSize":88123}},{"file":"neuroAd_1.0.38_amd64.snap","target":"snap","arch":1,"safeArtifactName":null,"isWriteUpdateInfo":false}],"fileSizes":[82271991131985408]}
  • downloading               parts=8 size=82 PB url=neuroAd-1.0.38-x86_64.AppImage
  • map async                 taskCount=8
  • download part             index=4 range=bytes=41135995565992704-51419994457490879
  • download part             index=0 range=bytes=0-10283998891498175
  • download part             index=1 range=bytes=10283998891498176-20567997782996351
  • download part             index=3 range=bytes=30851996674494528-41135995565992703
  • download part             index=2 range=bytes=20567997782996352-30851996674494527
  • download part             index=7 range=bytes=71987992240487232-82271991131985407
  • download part             index=5 range=bytes=51419994457490880-61703993348989055
  • download part             index=6 range=bytes=61703993348989056-71987992240487231
  • part download error       error=part download request failed with status code 416 id=1
  • part download error       error=part download request failed with status code 416 id=6
  • part download error       error=part download request failed with status code 416 id=2
  • part download error       error=part download request failed with status code 416 id=4
  • part download error       error=part download request failed with status code 416 id=5
  • part download error       error=part download request failed with status code 416 id=3
  • part download error       error=part download request failed with status code 416 id=7
  ⨯ part download request failed with status code 416
github.com/develar/app-builder/pkg/download.(*Part).doRequest
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/Part.go:127
github.com/develar/app-builder/pkg/download.(*Part).download
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/Part.go:46
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadResolved.func1.1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/download/downloader.go:110
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Users/develar/go/src/github.com/develar/app-builder/pkg/util/async.go:67
runtime.goexit
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333

  • exited          command=app-builder.exe code=1 pid=7708
  • async task error error=D:\builds\Archive\node_modules\app-builder-lib\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
Error: D:\builds\Archive\node_modules\app-builder-lib\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (D:\builds\Archive\node_modules\app-builder-lib\node_modules\builder-util\src\util.ts:254:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at RemoteBuilder._build (D:\builds\Archive\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:56:83)
    at _bluebirdLst.default.mapSeries.arch (D:\builds\Archive\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:51:19)
From previous event:
    at RemoteBuilder.build (D:\builds\Archive\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:50:28)
    at D:\builds\Archive\node_modules\app-builder-lib\src\linuxPackager.ts:99:30
From previous event:
    at RemoteTarget.finishBuild (D:\builds\Archive\node_modules\app-builder-lib\src\linuxPackager.ts:97:20)
    at D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:383:36
From previous event:
    at Packager.doBuild (D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:343:39)
    at D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:313:57
From previous event:
    at Packager._build (D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:284:133)
    at D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:280:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (D:\builds\Archive\node_modules\app-builder-lib\src\packager.ts:237:14)
    at build (D:\builds\Archive\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\builds\Archive\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\builds\Archive\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Object.args [as handler] (D:\builds\Archive\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at Object.runCommand (D:\builds\Archive\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (D:\builds\Archive\node_modules\yargs\yargs.js:1085:24)
    at Object.get [as argv] (D:\builds\Archive\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (D:\builds\Archive\node_modules\electron-builder\src\cli\cli.ts:25:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! neuroAd@1.0.38 dist:linux: `electron-builder --linux`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the neuroAd@1.0.38 dist:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\goe\AppData\Roaming\npm-cache\_logs\2018-10-29T08_48_20_290Z-debug.log
```

I wonder why it tries to build snap image when I only need AppImage though.

**Comment by develar** [comment]
@serge1peshcoff Nice. Fixed, build agents will be rolled out in a few minutes.

**Comment by serge1peshcoff** [comment]
@develar checked on 2 machines, everything is working so far.
Thanks for all of your help!
I'll close my another issue related to this then.
