### ISSUE TITLE
Typescript Error when running npm install

### ISSUE THREAD

**Issue by AhadCove** [electron-userland/electron-builder#3423]
### Versions
* Electron-builder: 20.28.4
* Electron-Updater: 3.1.2
* Target: Mac

### Issue
I started receiving this typescript error when running npm install. I’m not even using Typescript btw.

```
Error: Unresolved node modules: typescript
    at /Users/me/Electron/MyApp/node_modules/app-builder-lib/src/util/packageDependencies.ts:108:17
From previous event:
    at Collector.resolveUnresolvedHoisted (/Users/me/Electron/MyApp/node_modules/app-builder-lib/src/util/packageDependencies.ts:164:10)
    at /Users/me/Electron/MyApp/node_modules/app-builder-lib/src/util/packageDependencies.ts:82:28
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Collector.collect (/Users/me/Electron/MyApp/node_modules/app-builder-lib/src/util/packageDependencies.ts:84:6)
    at /Users/me/Electron/MyApp/node_modules/app-builder-lib/out/util/packageDependencies.js:123:47
    at Generator.next (<anonymous>)
From previous event:
    at getProductionDependencies (/Users/me/Electron/MyApp/node_modules/app-builder-lib/out/util/packageDependencies.js:128:17)
    at Lazy.<anonymous> (/Users/me/Electron/MyApp/node_modules/app-builder-lib/src/util/packageDependencies.ts:31:35)
    at Lazy.get value [as value] (/Users/me/Electron/MyApp/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/me/Electron/MyApp/node_modules/app-builder-lib/src/util/yarn.ts:128:81
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (/Users/me/Electron/MyApp/node_modules/app-builder-lib/out/util/yarn.js:239:18)
    at /Users/me/Electron/MyApp/node_modules/app-builder-lib/src/util/yarn.ts:20:11
From previous event:
    at installOrRebuild (/Users/me/Electron/MyApp/node_modules/app-builder-lib/out/util/yarn.js:68:17)
    at /Users/me/Electron/MyApp/node_modules/electron-builder/src/cli/install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (/Users/me/Electron/MyApp/node_modules/electron-builder/out/cli/install-app-deps.js:174:17)
    at then (/Users/me/Electron/MyApp/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Object.args [as handler] (/Users/me/Electron/MyApp/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (/Users/me/Electron/MyApp/node_modules/electron-builder/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/me/Electron/MyApp/node_modules/electron-builder/node_modules/yargs/yargs.js:1059:30)
    at Object.get [as argv] (/Users/me/Electron/MyApp/node_modules/electron-builder/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/Users/me/Electron/MyApp/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
```

**Comment by AhadCove** [comment]
I had to install typescript to my dev dependencies

**Comment by dannyharding10** [comment]
I am having this same issue. If I am not using typescript I should not need it as a dev dependency. Is there any way around this?

**Comment by jackieli123723** [comment]
yarn add typescript --save-dev
