### ISSUE TITLE
Windows packaging fails on binaries with EPERM: operation not permitted, copyfile ...

### ISSUE THREAD

**Issue by zeevl** [electron-userland/electron-builder#3438]
* **Version**: 20.31.0
* **Electron Updater Version**: 3.1.2
* **Target**: Windows
* **Electron**: 3.0.5
* **Node**: 10.13.0
* **Yarn**: 1.12.1

This has been driving me nuts for days.   A previously working project suddenly stopped working, and I'm having a hell of a time trying to figure out why.  

`electron-builder publish` is failing with: 
```
  electron-builder version=20.31.0
  loaded configuration file=package.json ("build" field)
  rebuilding native production dependencies platform=win32 arch=x64
  packaging       platform=win32 arch=x64 electron=3.0.5 appOutDir=release\win-unpacked
Error: EPERM: operation not permitted, copyfile 'C:\jenkins\workspace\scribeware build - windows\node_modules\7zip\.bin\7z' -> 'C:\jenkins\workspace\scribeware build - windows\release\win-unpacked\resources\app.asar.unpacked\node_modules\7zip\.bin\7z'
    at doCopyFile (C:\jenkins\workspace\scribeware build - windows\node_modules\builder-util\src\fs.ts:218:19)
    at copyOrLinkFile (C:\jenkins\workspace\scribeware build - windows\node_modules\builder-util\src\fs.ts:200:10)
    at C:\jenkins\workspace\scribeware build - windows\node_modules\builder-util\src\fs.ts:261:11
    at Generator.next (<anonymous>)
From previous event:
    at FileCopier.copy (C:\jenkins\workspace\scribeware build - windows\node_modules\builder-util\src\fs.ts:239:64)
    at copyFileOrData (C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\asar\asarUtil.ts:262:23)
    at C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\asar\asarUtil.ts:125:29
From previous event:
    at AsarPackager.createPackageFromFiles (C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\asar\asarUtil.ts:40:84)
    at C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\asar\asarUtil.ts:35:52
From previous event:
    at AsarPackager.pack (C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\asar\asarUtil.ts:27:79)
    at C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\platformPackager.ts:313:14
    at Generator.next (<anonymous>)
From previous event:
    at taskManager.addTask._computeFileSets.then (C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\platformPackager.ts:306:27)
From previous event:
    at WinPackager.copyAppFiles (C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\platformPackager.ts:307:10)
    at C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\platformPackager.ts:213:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.doPack (C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\platformPackager.ts:166:165)
    at C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\platformPackager.ts:110:95)
    at C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\jenkins\workspace\scribeware build - windows\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\jenkins\workspace\scribeware build - windows\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\packager.ts:344:39)
    at C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\packager.ts:314:57
From previous event:
    at Packager._build (C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\packager.ts:285:133)
    at C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (C:\jenkins\workspace\scribeware build - windows\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (C:\jenkins\workspace\scribeware build - windows\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\jenkins\workspace\scribeware build - windows\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Object.args [as handler] (C:\jenkins\workspace\scribeware build - windows\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at Object.runCommand (C:\jenkins\workspace\scribeware build - windows\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\jenkins\workspace\scribeware build - windows\node_modules\yargs\yargs.js:1085:24)
    at Object.get [as argv] (C:\jenkins\workspace\scribeware build - windows\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (C:\jenkins\workspace\scribeware build - windows\node_modules\electron-builder\src\cli\cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at findNodeScript.then.existing 
```

The binary doesn't matter -- if I remove the 7z dependency it just fails on the next one.  

The copyfile is referencing a junction in windows, that does exist:
```
C:\jenkins\workspace\scribeware build - windows>dir "C:\jenkins\workspace\scribeware build - windows\node_modules\7zip\.
bin\"
 Volume in drive C has no label.
 Volume Serial Number is E057-D3B1

 Directory of C:\jenkins\workspace\scribeware build - windows\node_modules\7zip\.bin

10/31/2018  06:26 PM    <DIR>          .
10/31/2018  06:26 PM    <DIR>          ..
10/31/2018  06:26 PM    <JUNCTION>     7z [C:\Users\steve\AppData\Local\Yarn\Cache\v3\npm-7zip-0.0.6-9cafb171af823294903
53b4816f03347aa150a30\node_modules\7zip\7zip-lite\7z.exe]
```

Any ideas??

**Comment by zeevl** [comment]
Yarn issue.   Ugh. 
https://github.com/yarnpkg/yarn/issues/6585
