### ISSUE TITLE
quitAndInstall throw error on temp update file

### ISSUE THREAD

**Issue by clem91** [electron-userland/electron-builder#3456]
Latest

* **Target**:  Linux AppImage

Hi,
I have a some problem with the installation of my updates. I trigger quitAndInstall() on update-downloaded but an error is thrown and prevent from quiting.

`Unhandled rejection Error: ENOENT: no such file or directory, chmod '/home/user/.config/MyProject/__update__/temp-filenameNewVersion.AppImage'`

The appImage file is modified and updated during this process and when I restart I have my app updated. 

Here is my code

` javascript
autoUpdater.autoInstallOnAppQuit = false;
    autoUpdater.on('checking-for-update', () => {
      const opts = {
        method: 'GET',
        region: 'eu-west-3',
        service: 's3',
        host: `${s3_bucket}.s3.amazonaws.com`,
        path: latest_yml_path
      };
      aws4.sign(opts, aws_access);
      autoUpdater.requestHeaders = opts.headers;
    });

    autoUpdater.on('error', err => {
      log.error(err);
    });

    autoUpdater.on('update-available', info => {
      const update_path = `${release_path}${info.path}`;
      const opts = {
        method: 'GET',
        region: 'eu-west-3',
        service: 's3',
        host: `${s3_bucket}.s3.amazonaws.com`,
        path: update_path
      };
      aws4.sign(opts, aws_access);
      autoUpdater.requestHeaders = opts.headers;
      try {
        autoUpdater.downloadUpdate();
      } catch (err) {
        if (this.isNetworkError(err)) {
          log.info('Network Error');
        } else {
          log.info('Unknown Error');
          log.info(err == null ? 'unknown' : (err.stack || err).toString());
        }
      }
    });

    autoUpdater.on('update-downloaded', () => {
      try {
        autoUpdater.quitAndInstall();
      } catch (err) {
        if (this.isNetworkError(err)) {
          log.info('Network Error');
        } else {
          log.info('Unknown Error');
          log.info(err == null ? 'unknown' : (err.stack || err).toString());
        }
      }
    });
    autoUpdater.checkForUpdates();
`

**Comment by clem91** [comment]
Hi @develar . Unfortunately the last version does not fix the problem. Here is the complete stack trace:
```javascript
Unhandled rejection Error: ENOENT: no such file or directory, chmod '/home/user/.config/myproject/__update__/temp-myproject-0.6.8-x86_64.AppImage'
    at Object.<anonymous> (/tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:72:15)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (/tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:44:11)
    at /tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:595:25
    at Generator.throw (<anonymous>)
From previous event:
    at AppImageUpdater.executeDownload (/tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:511:68)
    at AppImageUpdater.executeDownload (/tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:28:18)
    at AppImageUpdater.doDownloadUpdate (/tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:40:17)
    at AppImageUpdater.downloadUpdate (/tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:411:19)
    at /tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:374:49
From previous event:
    at AppImageUpdater.doCheckForUpdates (/tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:353:34)
    at /tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:289:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:284:33)
    at AppImageUpdater.checkForUpdates (/tmp/.mount_/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:223:35)
    at Timeout.setTimeout (/tmp/.mount_/resources/app.asar/app/webpack:/app/main.dev.js:102:14)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

**Comment by clem91** [comment]
The problem was me. After I noticed some double entry in the log I rechecked the docs and saw this option
    autoUpdater.autoDownload = false;
The updater tried to download concurently two files and when the first one end it clean the folder that's why the second download can't find his file once finished. 
Everything works now with the 3.x version of electron updater

**Comment by shivarkarimi** [comment]
I still have this issue happening intermittently
   "electron-builder": "22.8.1",
   "electron": "9.1.2",
   "electron-updater": "4.3.5",
 running the app the second time it works

`[2020-11-03 14:46:54.279] [info] New version 6.4.1-dev has been downloaded to /Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip
[2020-11-03 14:46:54.285] [error] Error: Error: ENOENT: no such file or directory, rename '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip' -> '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip'
[2020-11-03 14:46:54.286] [error] Auto-updater Manager: {"errno":-2,"code":"ENOENT","syscall":"rename","path":"/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip","dest":"/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip"}. Error message: Error: ENOENT: no such file or directory, rename '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip' -> '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip'
[2020-11-03 14:46:54.288] [error] Error: Error: ENOENT: no such file or directory, rename '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip' -> '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip'
[2020-11-03 14:46:54.288] [error] Auto-updater Manager: {"errno":-2,"code":"ENOENT","syscall":"rename","path":"/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip","dest":"/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip"}. Error message: Error: ENOENT: no such file or directory, rename '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/temp-myapp-6.4.1-dev-mac.zip' -> '/Users/xxxxx/Library/Application Support/Caches/myapp/pending/myapp-6.4.1-dev-mac.zip'`
