### ISSUE TITLE
Windows: cannot download differentially for NPM scoped package app

### ISSUE THREAD

**Issue by artemv** [electron-userland/electron-builder#3464]
electron-builder: 20.30.0
electron-updater: 3.1.2
target: nsis-web

I'm using electron-updater and "differential downloads" are not working for my app. The error is:
```
[2018-11-09 17:30:51.417] [info] Found version 0.17.33 (url: MyDesktopApp Web Setup 0.17.33.exe)
[2018-11-09 17:30:51.418] [info] Update available. { version: '0.17.33',
  files: 
   [ { url: 'MyDesktopApp Web Setup 0.17.33.exe',
       sha512: '8D+LTx0yzAYRT5hS7VpKzrwaE+DrkImglOMX7OKDvmFeUAlmxVbbTAbUSqw+HfBE8DFaKNTp7oPUHbttS/hdnw==' } ],
  path: 'MyDesktopApp Web Setup 0.17.33.exe',
  sha512: '8D+LTx0yzAYRT5hS7VpKzrwaE+DrkImglOMX7OKDvmFeUAlmxVbbTAbUSqw+HfBE8DFaKNTp7oPUHbttS/hdnw==',
  packages: 
   { ia32: 
      { size: 31889626,
        sha512: 'y6p62ZqTCX0E6HQXCFuxOzPPjpFaS5JdUzod1d9g3lCsIzHL3xTt1P75j96BaLmYCQUj7ZxOGZSXpT9oxUgpeA==',
        blockMapSize: 33864,
        path: '@myscopemy-desktop-app-0.17.33-ia32.nsis.7z',
        file: '@myscopemy-desktop-app-0.17.33-ia32.nsis.7z' },
     x64: 
      { size: 37721797,
        sha512: 'CNnGalI3LP7Vey1JI0RmG3F73RaKhWC1r5hz9lNjCYPsOxXDR8OXvP5WBTGoMkUG44PuqoYyquNM6ZQ0wsCtCg==',
        blockMapSize: 40341,
        path: '@myscopemy-desktop-app-0.17.33-x64.nsis.7z',
        file: '@myscopemy-desktop-app-0.17.33-x64.nsis.7z' } },
  releaseDate: '2018-11-09T17:20:02.285Z' }
[2018-11-09 17:30:51.420] [info] Downloading update from MyDesktopApp Web Setup 0.17.33.exe
[2018-11-09 17:30:51.461] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: hjwYZvVXGvFeu9fF5Gzb2pVMCRXH4I4PhBikN7Mv+ZBwHfPxhoB1R2eaeGs9fdAsjN1vqouJiGFLOFpNgID9Yw==, expected: 8D+LTx0yzAYRT5hS7VpKzrwaE+DrkImglOMX7OKDvmFeUAlmxVbbTAbUSqw+HfBE8DFaKNTp7oPUHbttS/hdnw==. Directory for cached update will be cleaned
[2018-11-09 17:30:52.733] [info] Download speed: 136779 - Downloaded 19.157613976772396% (142934/746095)
[2018-11-09 17:30:53.710] [info] Download speed: 368989 - Downloaded 100% (746095/746095)
[2018-11-09 17:30:54.358] [error] Cannot download differentially, fallback to full download: Error: ENOENT: no such file or directory, open 'C:\Users\user\AppData\Roaming\@myscope\my-desktop-app\__package.7z'
    at C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\src\blockMapApi.ts:20:20
    at Generator.next (<anonymous>)
From previous event:
    at readEmbeddedBlockMapData (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\blockMapApi.js:52:17)
    at C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\FileWithEmbeddedBlockMapDifferentialDownloader.ts:11:44
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at FileWithEmbeddedBlockMapDifferentialDownloader.download (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\FileWithEmbeddedBlockMapDifferentialDownloader.ts:5:17)
    at C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:196:10
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.differentialDownloadWebPackage (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:182:122)
    at Object.<anonymous> (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:44:26)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:29:11)
    at C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:570:25
    at Generator.throw (<anonymous>)
From previous event:
    at NsisUpdater.executeDownload (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:487:68)
    at NsisUpdater.executeDownload (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:28:18)
    at C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:25:23
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:22:80)
    at C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:393:25
From previous event:
    at NsisUpdater.downloadUpdate (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:382:86)
    at C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:369:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:348:34)
    at C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:282:33)
    at NsisUpdater.checkForUpdates (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:221:35)
    at runAutoUpdate (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\main-process\setup-auto-update.ts:39:17)
    at App.<anonymous> (C:\Users\user\AppData\Local\Programs\@myscopemy-desktop-app\resources\app.asar\main-process\setup-auto-update.ts:51:5)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
[2018-11-09 17:31:09.122] [info] New version 0.17.33 has been downloaded to C:\Users\user\AppData\Roaming\@myscope\my-desktop-app\__update__\MyDesktopApp Web Setup 0.17.33.exe
[2018-11-09 17:31:09.138] [info] Update downloaded
```

The C:\Users\user\AppData\Roaming\@myscope\my-desktop-app\__package.7z is missing indeed. Instead there's C:\Users\user\AppData\Roaming\MyDesktopApp\__package.7z. In package.json `name` is "@myscope/my-desktop-app" and in electron-builder.json `productName` is "MyDesktopApp".

It does successfully download the full version for update, but obviously the delta update would be better.

This reproduces both for first and subsequential updates.
For `nsis` target it doesn't work similarly. Meanwhile for `AppImage` target of the same app differential updates work fine.
I also tried to use "@myscope/my-desktop-app" as `productName` - no luck.

Thanks for advice.

**Comment by develar** [comment]
Duplicates #3451

You can expect fix today. Thanks for clear error report.
