### ISSUE TITLE
Publish failing on version error

### ISSUE THREAD

**Issue by factorone** [electron-userland/electron-builder#3475]
* **Version**: 20.31.0 -> 20.35.0

* **Version**: 3.2 -> 4.0

* **Target**: x64: NSIS, Zip, DMG

Started receiving errors on the publish command today after having had successful publishing requests for the last week and a half.

Stack trace:
```
TypeError: Invalid Version: 4.0
    at new SemVer (C:\Users\bmworf\AppData\Local\Yarn\Data\global\node_modules\semver\semver.js:312:11)
    at Range.test (C:\Users\bmworf\AppData\Local\Yarn\Data\global\node_modules\semver\semver.js:1137:15)
    at Object.satisfies (C:\Users\bmworf\AppData\Local\Yarn\Data\global\node_modules\semver\semver.js:1189:16)
    at checkDependencies (C:\Users\bmworf\AppData\Local\Yarn\Data\global\node_modules\app-builder-lib\src\util\packageMetadata.ts:96:41)
    at checkMetadata (C:\Users\bmworf\AppData\Local\Yarn\Data\global\node_modules\app-builder-lib\src\util\packageMetadata.ts:66:5)
    at C:\Users\bmworf\AppData\Local\Yarn\Data\global\node_modules\app-builder-lib\src\packager.ts:278:5
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (C:\Users\bmworf\AppData\Local\Yarn\Data\global\node_modules\app-builder-lib\src\packager.ts:237:14)
    at build (C:\Users\bmworf\AppData\Local\Yarn\Data\global\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Users\bmworf\AppData\Local\Yarn\Data\global\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\Users\bmworf\AppData\Local\Yarn\Data\global\node_modules\electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
```

Previously, it started giving me errors about Electron Updater needing to be version 4.0 or greater. So I upgraded it, and now start getting this on the `electron-builder --publish=always` command.

**Comment by factorone** [comment]
I was able to rectify this by moving my versions back:
**Builder:** 20.32.0
**Updater:** 3.2.3

So this is likely a bug in at least 20.33.0 or later.
