### ISSUE TITLE
proton: macOS default icon missing?

### ISSUE THREAD

**Issue by mischnic** [electron-userland/electron-builder#3481]
* **Version**: 20.36.0

* **Target**:  macOS

```json
  "build": {
    "framework": "proton",
    "mac": {
      "identity": null
    }
  }
```

It seems like the proton-native default app icon is missing for macOS

```
$ electron-builder --dir
  • electron-builder version=20.36.0
  • loaded configuration file=package.json ("build" field)
  • description is missed in the package.json appPackageFile=.../new-test/package.json
  • author is missed in the package.json appPackageFile=.../new-test/package.json
  • writing effective config file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 proton=11.1.0 appOutDir=dist/mac
  • downloading               parts=2 size=11 MB url=https://nodejs.org/dist/v11.1.0/node-v11.1.0-darwin-x64.tar.xz
  • downloaded                duration=3.691s url=https://nodejs.org/dist/v11.1.0/node-v11.1.0-darwin-x64.tar.xz
Error: ENOENT: no such file or directory, copyfile '.../new-test/node_modules/app-builder-lib/templates/icons/proton-native/proton-native.icns' -> '.../new-test/dist/mac/new-test.app/Contents/Resources/new-test.icns'
    at doCopyFile (.../new-test/node_modules/builder-util/src/fs.ts:218:19)
    at copyOrLinkFile (.../new-test/node_modules/builder-util/src/fs.ts:200:10)
    at then (.../new-test/node_modules/builder-util/src/fs.ts:144:17)
    at xfs.stat (.../new-test/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at .../new-test/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:162:5)
From previous event:
    at copyFile (.../new-test/node_modules/builder-util/src/fs.ts:144:6)
    at .../new-test/node_modules/app-builder-lib/src/macPackager.ts:279:13
From previous event:
    at MacPackager.applyCommonInfo (.../new-test/node_modules/app-builder-lib/src/macPackager.ts:263:60)
    at .../new-test/node_modules/app-builder-lib/src/frameworks/LibUiFramework.ts:64:20
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at ProtonFramework.prepareMacosApplicationStageDirectory (.../new-test/node_modules/app-builder-lib/src/frameworks/LibUiFramework.ts:54:126)
    at .../new-test/node_modules/app-builder-lib/src/frameworks/LibUiFramework.ts:47:18
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (.../new-test/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqCallback.oncomplete (fs.js:148:20)
From previous event:
    at ProtonFramework.prepareApplicationStageDirectory (.../new-test/node_modules/app-builder-lib/src/frameworks/LibUiFramework.ts:27:90)
    at .../new-test/node_modules/app-builder-lib/src/platformPackager.ts:180:21
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.doPack (.../new-test/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at .../new-test/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (.../new-test/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at .../new-test/node_modules/app-builder-lib/src/packager.ts:406:24
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.doBuild (.../new-test/node_modules/app-builder-lib/src/packager.ts:372:24)
    at .../new-test/node_modules/app-builder-lib/src/packager.ts:342:57
    at Generator.next (<anonymous>)
    at .../new-test/node_modules/graceful-fs/graceful-fs.js:111:16
    at .../new-test/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:148:20)
From previous event:
    at Packager._build (.../new-test/node_modules/app-builder-lib/src/packager.ts:311:133)
    at .../new-test/node_modules/app-builder-lib/src/packager.ts:307:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (.../new-test/node_modules/app-builder-lib/src/packager.ts:264:14)
    at build (.../new-test/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (.../new-test/node_modules/electron-builder/src/builder.ts:227:10)
    at then (.../new-test/node_modules/electron-builder/src/cli/cli.ts:46:19)
```

**Comment by develar** [comment]
protonTest added to travis test suite to avoid such regression in the future.

**Comment by develar** [comment]
20.36.1 released.
