### ISSUE TITLE
Electron updater 4.x problem with quitAndInstall 

### ISSUE THREAD

**Issue by clem91** [electron-userland/electron-builder#3482]
electron-updater 4.0.3

* **Target**:  AppImage on Ubuntu 18.04

Hi I tried the new 4.X electron updater version and I had an issue with the quitAndInstall procedure. The update is working and the app is rebooted into his new version but there is an unhandled exception. Here is the error stack trace:

```javascript
Unhandled rejection TypeError: A value true was yielded that could not be treated as a promise

    See http://goo.gl/MqrFmX

From coroutine:
    at Promise.coroutine (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/bluebird/js/release/generators.js:194:17)
    at AppImageUpdater.quitAndInstall (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:13:83)
    at AppImageUpdater.h.autoUpdater.on (/tmp/.mount_Hnixu3/resources/app.asar/app/webpack:/app/appUpdater.js:56:1)
    at AppImageUpdater.emit (events.js:182:13)
    at AppImageUpdater.dispatchUpdateDownloaded (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:431:10)
    at Object.<anonymous> (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:30:14)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/bluebird/js/release/generators.js:97:49)
    at AppImageUpdater.quitAndInstall (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:13:83)
    at AppImageUpdater.h.autoUpdater.on (/tmp/.mount_Hnixu3/resources/app.asar/app/webpack:/app/appUpdater.js:56:1)
    at AppImageUpdater.emit (events.js:182:13)
    at AppImageUpdater.dispatchUpdateDownloaded (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:431:10)
    at Object.<anonymous> (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:30:14)
    at Generator.next (<anonymous>)
From previous event:
    at Object.done (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:29:11)
    at /tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:575:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at done (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:573:15)
    at /tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:616:18
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:169:20)
From previous event:
    at AppImageUpdater.executeDownload (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:537:68)
    at AppImageUpdater.executeDownload (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/BaseUpdater.ts:27:18)
    at AppImageUpdater.doDownloadUpdate (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:40:17)
    at AppImageUpdater.downloadUpdate (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:412:19)
    at AppImageUpdater.h.autoUpdater.on.e (/tmp/.mount_Hnixu3/resources/app.asar/app/webpack:/app/appUpdater.js:47:7)
    at AppImageUpdater.emit (events.js:182:13)
    at AppImageUpdater.onUpdateAvailable (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:381:10)
    at /tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:367:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:352:34)
    at AppImageUpdater.checkForUpdates (/tmp/.mount_Hnixu3/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at Object.checkForUpdates (/tmp/.mount_Hnixu3/resources/app.asar/app/webpack:/app/appUpdater.js:56:1)
    at EventEmitter.rotate (/tmp/.mount_Hnixu3/resources/app.asar/app/webpack:/app/main.dev.js:146:1)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/tmp/.mount_Hnixu3/resources/electron.asar/browser/api/web-contents.js:284:13)
    at WebContents.emit (events.js:182:13)
```

And here is the portion of code I use to update the app:

```javascript
export default class AppUpdater {
  constructor() {
    log.transports.file.level = 'info';
    autoUpdater.logger = log;
    autoUpdater.autoDownload = false;
    autoUpdater.autoInstallOnAppQuit = false;
    autoUpdater.on('checking-for-update', () => {
      const opts = {
        method: 'GET',
        region: 'eu-west-3',
        service: 's3',
        host: `${s3_bucket}.s3.amazonaws.com`,
        path: latest_yml_path
      };
      aws4.sign(opts, aws_access);
      autoUpdater.requestHeaders = opts.headers;
    });

    autoUpdater.on('error', err => {
      log.error(err);
    });

    autoUpdater.on('update-available', info => {
      const update_path = `${release_path}${info.path}`;
      const opts = {
        method: 'GET',
        region: 'eu-west-3',
        service: 's3',
        host: `${s3_bucket}.s3.amazonaws.com`,
        path: update_path
      };
      aws4.sign(opts, aws_access);
      autoUpdater.requestHeaders = opts.headers;
      autoUpdater.downloadUpdate();
    });

    autoUpdater.on('update-downloaded', () => {
        console.log('downloaded');
        autoUpdater.quitAndInstall()
    });
  }

  checkForUpdates() {
    autoUpdater.checkForUpdates();
  }
}
```
```javascript
updater.checkForUpdates();
```

**Comment by clem91** [comment]
Thank you @develar  it works!
