### ISSUE TITLE
404 downloading lzma-native

### ISSUE THREAD

**Issue by chiefsmurph** [electron-userland/electron-builder#3483]
* **Version**: 20.36.2

* **Target**: darwin x64

when I run `./node_modules/.bin/electron-builder`

I get this error...

```
  • electron-builder version=20.36.2
  • loaded configuration file=package.json ("build" field)
  • description is missed in the package.json appPackageFile=/Users/chiefsmurph/code/music-friends/package.json
  • writing effective config file=dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
Error: npm exited with code 1
Output:

> lzma-native@3.0.8 install /Users/chiefsmurph/code/music-friends/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build

Failed to execute '/usr/local/Cellar/node/10.11.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/chiefsmurph/code/music-friends/node_modules/lzma-native/binding-v3.0.8-electron-v3.0-darwin-x64/lzma_native.node --module_name=lzma_native --module_path=/Users/chiefsmurph/code/music-friends/node_modules/lzma-native/binding-v3.0.8-electron-v3.0-darwin-x64' (1)

Error output:
node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-electron-v3.0-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.8 and electron@3.0.9 (electron-v3.0 ABI, unknown) (falling back to source compile with node-gyp) 
...
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
```

**Comment by develar** [comment]
It means that this module doesn't provide prebuilds for your electron version.

**Comment by chiefsmurph** [comment]
@develar How would I fix this?  I am not doing any special config with lmza-native.

**Comment by develar** [comment]
Without prebuild version npm tries to compile from sources. It means that you need to install XCode and cammand line tools. And, probably, some deps, although on lzma native readme nothing listed.

**Comment by chiefsmurph** [comment]
does everybody who uses electron-builder need to compile from sources?  I am not trying to do anything fancy with lzma-native as far as I know.

**Comment by chiefsmurph** [comment]
I was able to build for darwin x64 successfully just yesterday.  I was using an old version of electron-builder (19.22.1), but when I just tried with that version and now getting the same error.

**Comment by towfiqi** [comment]
Having the same error. @chiefsmurph were you able to find a fix for this?

**Comment by chiefsmurph** [comment]
I searched far and wide and could not figure it out.

**Comment by towfiqi** [comment]
I actually found a solution and posted in on stackoverflow: 
https://stackoverflow.com/questions/53678786/could-not-find-com-android-toolscommon25-2-3/53684681#53684681
