### ISSUE TITLE
Error: buffer is not ico

### ISSUE THREAD

**Issue by daviseford** [electron-userland/electron-builder#349]
Hey there, when I try to build the win32 version of my app, I receive this error

Error: buffer is not ico
    at parseIco (/Users/loaner/opat-presentation/native/node_modules/electron-builder/src/winPackager.ts:202:11)
    at /Users/loaner/opat-presentation/native/node_modules/electron-builder/src/winPackager.ts:185:25
    at [object Generator].next (native)
    at /Users/loaner/opat-presentation/native/node_modules/electron-builder/node_modules/fs-extra-p/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/loaner/opat-presentation/native/node_modules/electron-builder/node_modules/read-package-json/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
From previous event:
    at tsAwaiter (/Users/loaner/opat-presentation/native/node_modules/electron-builder/src/awaiter.ts:10:51)
    at Object.build (/Users/loaner/opat-presentation/native/node_modules/electron-builder/src/builder.ts:30:59)
    at Object.<anonymous> (/Users/loaner/opat-presentation/native/node_modules/electron-builder/src/build-cli.ts:41:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

The Mac and Linux versions of my project build just fine. At first I thought this error might be related to my "iconUrl", but haven't had any luck switching it. Has anyone else run into this issue?

**Comment by develar** [comment]
Please check that your `build/icon.ico` is valid ICO file.

**Comment by daviseford** [comment]
D'oh! Thanks!

**Comment by develar** [comment]
Reopened — the error message is unclear and must be fixed.

**Comment by develar** [comment]
@daviseford Please clarify — ico file was invalid (why?) or didn't exist?

**Comment by daviseford** [comment]
I copied the /build directory from https://github.com/develar/onshape-desktop-shell/. Apparently the .ico files in that directory were not valid. The file did exist, but even my Mac couldn't open them - files must have been corrupted or something. After I replaced icon.ico with a new, valid icon, the build worked.

**Comment by develar** [comment]
@daviseford onshape-desktop-shell uses GIT LFS to store binary files. If you clone repo without installed GIT LFS, you get just text pointers. Thanks for clarification.

**Comment by demetris-manikas** [comment]
@develar 
This https://www.npmjs.com/package/icojs could be used to check ico . 
and this https://www.npmjs.com/package/image-type could be used to check the rest of the image files

**Comment by develar** [comment]
@demetris-manikas We already check `ico` — https://github.com/electron-userland/electron-builder/blob/master/src/winPackager.ts#L225 (yes, I saw icojs but `ico` is very easy to check/read).
