### ISSUE TITLE
Differential update fails when assets change (nsis & nsis-web)

### ISSUE THREAD

**Issue by Vaggal** [electron-userland/electron-builder#3490]
* **Version**: 20.34.0
* **Electron-Updater**: 3.2.3
* **Target**: Windows 10 x64
* **Node**: v11.2.0
* **NPM**: v6.4.1

I have tried with the 20.36.2 version of electron-builder and the 4.0.4 version of electron-updater but I have a different kind of error there for which I will open another issue.

For the versions I am using right now, I am aware of [#3451](https://github.com/electron-userland/electron-builder/issues/3451) but the new versions of electron-updater require Electron 3 and we cannot upgrade for now.
I have used the fix suggested in [#3451#issuecomment-436213442](https://github.com/electron-userland/electron-builder/issues/3451#issuecomment-436213442)

I am testing differential updates using a local server. This is the config I am using:
```
"win": {
	"target": "nsis",
	"icon": "build/icon.ico"
},
"nsis": {
	"artifactName": "Shop Setup ${version}.${ext}",
	"shortcutName": "Shop",
	"differentialPackage": true,
	"runAfterFinish": false,
	"deleteAppDataOnUninstall": true
},
"publish": [
	{
		"provider": "generic",
		"url": "http://releases.local"
	}
]
```
When only code is changed everything works fine, but whenever some assets(images, audio, etc) are changed, the updater falls back to full download.

The updater logs are these:
```
[2018-11-21 12:55:34.931] [info] Checking for update
[2018-11-21 12:55:37.195] [info] Found version 1.1.10 (url: Shop Setup 1.1.10.exe)
[2018-11-21 12:55:37.205] [info] Update available.
[2018-11-21 12:55:37.205] [info] Downloading update from Shop Setup 1.1.10.exe
[2018-11-21 12:55:37.226] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: Z6GRE4XxWqPzL7eDXvlyQD/VMhgFQUWKJuzJbENgmItO3Y7KuI60iSgnMyxcyw99JSA4ADz/qZ4KlKwkn/dAIw==, expected: db38PZpKQLdT5dNEA8EY73YhNb6kBZNcfzrEEALl1ZrYJIlPQ/IX2eYmx4i4d5t4abGAcUUYOdx90roeFT0yOA==. Directory for cached update will be cleaned
[2018-11-21 12:55:37.238] [info] Download block maps (old: "http://releases.local/Shop%20Setup%201.1.9.exe.blockmap", new: http://releases.local/Shop%20Setup%201.1.10.exe.blockmap)
[2018-11-21 12:55:37.431] [info] File has 4955 changed blocks
[2018-11-21 12:55:37.453] [info] Full: 328,257.12 KB, To download: 102,562.43 KB (31%)
[2018-11-21 12:55:37.501] [error] Cannot download differentially, fallback to full download: Error: Content-Type "multipart/byteranges" is expected, but got "application/x-msdownload"
    at ClientRequest.differentialDownloader.httpExecutor.createRequest.response (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\multipleRangeDownloader.ts:89:14)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at URLRequest.ClientRequest.urlRequest.on (C:\Users\user\AppData\Local\Programs\shop-client\resources\electron.asar\browser\api\net.js:209:12)
    at emitOne (events.js:115:13)
    at URLRequest.emit (events.js:210:7)
From previous event:
    at C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at GenericDifferentialDownloader.doDownloadFile (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:116:82)
    at GenericDifferentialDownloader.downloadFile (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:90:17)
    at GenericDifferentialDownloader.doDownload (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:76:17)
    at GenericDifferentialDownloader.download (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\GenericDifferentialDownloader.ts:6:17)
    at C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:192:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater.differentialDownloadInstaller (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:159:210)
    at Object.<anonymous> (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:34:42)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:31:11)
    at C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:595:25
    at Generator.throw (<anonymous>)
From previous event:
    at NsisUpdater.executeDownload (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:511:68)
    at NsisUpdater.executeDownload (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:28:18)
    at NsisUpdater.doDownloadUpdate (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:27:17)
    at NsisUpdater.downloadUpdate (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:411:19)
    at C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:374:49
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:353:34)
    at C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:289:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:284:33)
    at NsisUpdater.checkForUpdates (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:223:35)
    at NsisUpdater.checkForUpdatesAndNotify (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:237:41)
    at BrowserWindow.primaryWindow.once (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\src\index.js:56:21)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at BrowserWindow.emit (events.js:210:7)
[2018-11-21 12:55:40.775] [info] Download speed: 4502820 - Downloaded 4.341596840441212% (14593639/336135287)
[2018-11-21 12:55:41.834] [info] Download speed: 3633914 - Downloaded 4.6486731992526575% (15625831/336135287)
[2018-11-21 12:55:42.835] [info] Download speed: 4823792 - Downloaded 7.60732954526134% (25570919/336135287)
[2018-11-21 12:55:43.835] [info] Download speed: 5756177 - Downloaded 10.790200375481554% (36269671/336135287)
[2018-11-21 12:55:44.836] [info] Download speed: 6326811 - Downloaded 13.743982493572595% (46198375/336135287)
[2018-11-21 12:55:45.836] [info] Download speed: 6849477 - Downloaded 16.917104867957526% (56864359/336135287)
[2018-11-21 12:55:46.837] [info] Download speed: 7203967 - Downloaded 19.937955219798155% (67018503/336135287)
[2018-11-21 12:55:47.837] [info] Download speed: 9075176 - Downloaded 27.816640089917126% (93501543/336135287)
[2018-11-21 12:55:48.837] [info] Download speed: 11081442 - Downloaded 37.26283667444888% (125253543/336135287)
[2018-11-21 12:55:49.837] [info] Download speed: 12755762 - Downloaded 46.687792109133724% (156934144/336135287)
[2018-11-21 12:55:50.837] [info] Download speed: 14710561 - Downloaded 58.21899680529524% (195694592/336135287)
[2018-11-21 12:55:51.837] [info] Download speed: 16636825 - Downloaded 70.79188683930111% (237956512/336135287)
[2018-11-21 12:55:52.837] [info] Download speed: 19172916 - Downloaded 87.28721659026533% (293403136/336135287)
[2018-11-21 12:55:53.392] [info] Download speed: 21196575 - Downloaded 100% (336135287/336135287)
[2018-11-21 12:55:53.397] [info] New version 1.1.10 has been downloaded to C:\Users\user\AppData\Roaming\shop-client\__update__\Shop Setup 1.1.10.exe
[2018-11-21 12:55:53.401] [info] Update downloaded
[2018-11-21 12:55:53.402] [info] {
    "version": "1.1.10",
    "files": [
        {
            "url": "Shop Setup 1.1.10.exe",
            "sha512": "db38PZpKQLdT5dNEA8EY73YhNb6kBZNcfzrEEALl1ZrYJIlPQ/IX2eYmx4i4d5t4abGAcUUYOdx90roeFT0yOA==",
            "size": 336135287
        }
    ],
    "path": "Shop Setup 1.1.10.exe",
    "sha512": "db38PZpKQLdT5dNEA8EY73YhNb6kBZNcfzrEEALl1ZrYJIlPQ/IX2eYmx4i4d5t4abGAcUUYOdx90roeFT0yOA==",
    "releaseDate": "2018-11-21T10:55:12.583Z",
    "downloadedFile": "C:\\Users\\user\\AppData\\Roaming\\shop-client\\__update__\\Shop Setup 1.1.10.exe"
}
[2018-11-21 12:55:53.403] [info] Install on explicit quitAndInstall
[2018-11-21 12:55:53.404] [info] Install: isSilent: false, isRunAfter: true
[2018-11-21 12:55:53.957] [info] Update installer has already been triggered. Quitting application.
```
I have tried nsis-web also and the same thing happens only the error there is:
```
Content-Type "multipart/byteranges" is expected, but got "application/x-7z-compressed"
```
In addition, even if only one image with size 200KB is changed then before falling back to full download, the updater says:
```
[...]
File has 13937 changed blocks
Full: 332,128.14 KB, To download: 284,408.94 KB (86%)
[...]
```
How is this possible?

**Comment by mariouzae** [comment]
electron-builder: 20.34.0
electron-updater: 4.0.0

I'm with the same error, both for Windows 7 and 10 x64. 

Even not setting "productName" on package.json, it creates two folders, one in "AppData/Local" and other in "AppData/Roaming". 

When I call "autoUpdater.downloadUpdate()" the log show:

[2018-11-28 10:46:28.996] [error] Cannot download differentially, fallback to full download: Error: ENOENT: no such file or directory, open 'C:\Users\mariouzae\AppData\Local\Nuacom-Softphone\installer.exe'
    at C:\Users\mariouzae\AppData\Local\Programs\Nuacom-Softphone\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:116:29
    at Generator.next (<anonymous>)

**Comment by tbillington** [comment]
Getting the same on Win10 using `nsis-web`

```
Full: 111,990.59 KB, To download: 1,524.95 KB (1%)
Cannot download differentially, fallback to full download: Error: Content-Type "multipart/byteranges" is expected, but got "application/x-7z-compressed"
```

**Comment by Vaggal** [comment]
I have tested also with Content-Type "multipart/byteranges" but the error changes to:
```
Content-Type "multipart/byteranges" is expected, but got "multipart/byteranges"
```

**Comment by jiangbo2015** [comment]
+1

**Comment by peererror** [comment]
+1

**Comment by weiweian90** [comment]
i have the same error on win10 with autoUpdater.downloadUpdate()
Cannot download differentially, fallback to full download, Error: Content-Type "multipart/byteranges" is expected, but got "application/x-msdownload"

**Comment by alfredayibonte** [comment]
Set  `useMultipleRangeRequest: false` in `setFeedURL`
