### ISSUE TITLE
Differential update fails (nsis & nsis-web)

### ISSUE THREAD

**Issue by Vaggal** [electron-userland/electron-builder#3491]
* **Version**: 20.36.2
* **Electron-Updater**: 4.0.4
* **Target**: Windows 10 x64
* **Node**: v11.2.0
* **NPM**: v6.4.1

I am testing differential updates using a local server. This is the config I am using:
```
"win": {
	"target": "nsis",
	"icon": "build/icon.ico"
},
"nsis": {
	"artifactName": "Shop Setup ${version}.${ext}",
	"shortcutName": "Shop",
	"differentialPackage": true,
	"runAfterFinish": false,
	"deleteAppDataOnUninstall": true
},
"publish": [
	{
		"provider": "generic",
		"url": "http://releases.local"
	}
]
```

The updater always displays the error even if I try with nsis-web.

The updater logs are these:
```
[2018-11-21 14:45:36.131] [info] Checking for update
[2018-11-21 14:45:36.891] [info] Found version 1.1.7 (url: Shop Setup 1.1.7.exe)
[2018-11-21 14:45:36.891] [info] Update available.
[2018-11-21 14:45:36.891] [info] Downloading update from Shop Setup 1.1.7.exe
[2018-11-21 14:45:36.914] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: rovoYvsMFav5USPlBki4yiH2fR3ovvshG+1RfY05c/5dvn6fcHIZAdnAWho10yULFRlj1RR5Eo26WJOuB0y1CA==, expected: +7encdEf1n5LxEd+uV7xGSVI1t2jAKiyIRaLzqRDUNDNovOU6XM3g+Ru2/V4aJjiHD/Cw/yDkVBnkDSv7wBG7g==. Directory for cached update will be cleaned
[2018-11-21 14:45:36.956] [info] Download speed: 33932700 - Downloaded 100% (678654/678654)
[2018-11-21 14:45:37.137] [error] Cannot download differentially, fallback to full download: Error: operation (block index: 14904, checksum: HR5Cqia856PVff4zoBEpo2yw, kind: COPY) overlaps previous operation (checksum: HR5Cqia856PVff4zoBEpo2yw):
abs: 305846554 until 310168041 and 309969710 until 309983639
rel: 0 until 4321487 and 4123156 until 4137085
    at validateAndAdd (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\downloadPlanBuilder.ts:99:13)
    at computeOperations (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\downloadPlanBuilder.ts:83:9)
    at FileWithEmbeddedBlockMapDifferentialDownloader.doDownload (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:52:24)
    at C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\FileWithEmbeddedBlockMapDifferentialDownloader.ts:14:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
From previous event:
    at FileWithEmbeddedBlockMapDifferentialDownloader.download (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\differentialDownloader\FileWithEmbeddedBlockMapDifferentialDownloader.ts:8:17)
    at C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:199:10
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.differentialDownloadWebPackage (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:185:122)
    at Object.<anonymous> (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:47:26)
From previous event:
    at Object.task (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:32:11)
    at C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:610:25
From previous event:
    at NsisUpdater.executeDownload (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:545:68)
    at NsisUpdater.executeDownload (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:27:18)
    at NsisUpdater.doDownloadUpdate (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:28:17)
    at NsisUpdater.downloadUpdate (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:420:19)
    at C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:383:49
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at NsisUpdater.checkForUpdatesAndNotify (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:249:41)
    at BrowserWindow.primaryWindow.once (C:\Users\user\AppData\Local\Programs\shop-client\resources\app.asar\src\index.js:56:21)
    at Object.onceWrapper (events.js:273:13)
    at BrowserWindow.emit (events.js:182:13)
[2018-11-21 14:45:42.898] [info] New version 1.1.7 has been downloaded to C:\Users\user\AppData\Local\shop-client-updater\pending\Shop Setup 1.1.7.exe
[2018-11-21 14:45:42.901] [info] Update downloaded
[2018-11-21 14:45:42.901] [info] {
    "version": "1.1.7",
    "files": [
        {
            "url": "Shop Setup 1.1.7.exe",
            "sha512": "+7encdEf1n5LxEd+uV7xGSVI1t2jAKiyIRaLzqRDUNDNovOU6XM3g+Ru2/V4aJjiHD/Cw/yDkVBnkDSv7wBG7g=="
        }
    ],
    "path": "Shop Setup 1.1.7.exe",
    "sha512": "+7encdEf1n5LxEd+uV7xGSVI1t2jAKiyIRaLzqRDUNDNovOU6XM3g+Ru2/V4aJjiHD/Cw/yDkVBnkDSv7wBG7g==",
    "packages": {
        "x64": {
            "size": 342725638,
            "sha512": "DUxiqxhjgml2JsjboTL8Rd6PLxrQvjI1Dy0GGM4qK6a/6Io9aidnPWqnDIS3rOCqHik+mcBVWHv1zluBj8X4hA==",
            "blockMapSize": 359318,
            "path": "shop-client-1.1.7-x64.nsis.7z",
            "file": "shop-client-1.1.7-x64.nsis.7z"
        }
    },
    "releaseDate": "2018-11-21T12:45:21.533Z",
    "downloadedFile": "C:\\Users\\user\\AppData\\Local\\shop-client-updater\\pending\\Shop Setup 1.1.7.exe"
}
[2018-11-21 14:45:42.901] [info] Install on explicit quitAndInstall
[2018-11-21 14:45:42.901] [info] Install: isSilent: false, isForceRunAfter: true
[2018-11-21 14:45:44.107] [info] Update installer has already been triggered. Quitting application.
```

**Comment by zhaoterryy** [comment]
Duplicates #3485
