### ISSUE TITLE
Build fails for target pacman when not using a sh-compatible shell

### ISSUE THREAD

**Issue by emkay443** [electron-userland/electron-builder#3494]
* **Version**: 20.36.2

* **Target**: pacman

electron-builder fails to build for target pacman when using a shell that's not sh-compatible (like fish).
It works fine on bash and zsh, though.

* **Workaround**: Run electron-builder with `env SHELL=bash`.

* **Output**:
```
  • electron-builder version=20.36.2
  • loaded configuration file=package.json ("build" field)
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=2.0.14 appOutDir=dist/linux-unpacked
  • building        target=pacman arch=x64 file=dist/myproject-0.0.10.pacman
  • default Electron icon is used reason=application icon is not set
Error: Exit code: 1. Command failed: /home/johndoe/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir -t pacman --architecture amd64 --name myproject --force --after-install /tmp/t-01Sk3v/0-postinstall.sh --after-remove /tmp/t-01Sk3v/1-postremove.sh --description 
 My Project app --version 0.0.10 --package /home/johndoe/git/myproject/dist/myproject-0.0.10.pacman --maintainer John Doe <john@example.org> --url https://example.org --vendor John Doe <john@example.org> --depends libappindicator3 --depends gconf --depends libnotify --depends libxtst --depends nss --license GPL-2.0-or-later /home/johndoe/git/myproject/dist/linux-unpacked/=/opt/myproject /home/johndoe/git/myproject/includes/icons/linux/16x16.png=/usr/share/icons/hicolor/16x16/apps/myproject.png /home/johndoe/git/myproject/includes/icons/linux/32x32.png=/usr/share/icons/hicolor/32x32/apps/myproject.png /home/johndoe/git/myproject/includes/icons/linux/64x64.png=/usr/share/icons/hicolor/64x64/apps/myproject.png /home/johndoe/git/myproject/includes/icons/linux/128x128.png=/usr/share/icons/hicolor/128x128/apps/myproject.png /home/johndoe/git/myproject/includes/icons/linux/256x256.png=/usr/share/icons/hicolor/256x256/apps/myproject.png /home/johndoe/git/myproject/includes/icons/linux/512x512.png=/usr/share/icons/hicolor/512x512/apps/myproject.png /home/johndoe/git/myproject/includes/icons/linux/1024x1024.png=/usr/share/icons/hicolor/1024x1024/apps/myproject.png /tmp/t-01Sk3v/2-AStA Copyclient.desktop=/usr/share/applications/myproject.desktop

{:timestamp=>"2018-11-25T15:55:36.666954+0100", :message=>"Process failed: /usr/bin/fish failed (exit code 127). Full command was:[\"/usr/bin/fish\", \"-c\", \"LANG=C bsdtar -czf .MTREE --format=mtree --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' .INSTALL .PKGINFO usr opt\"]", :level=>:error}

    at /home/johndoe/git/myproject/node_modules/builder-util/src/util.ts:126:16
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:616:12)
From previous event:
    at FpmTarget.build (/home/johndoe/git/myproject/node_modules/app-builder-lib/src/targets/fpm.ts:92:44)
    at /home/johndoe/git/myproject/node_modules/app-builder-lib/src/platformPackager.ts:131:24
From previous event:
    at AsyncTaskManager.add (/home/johndoe/git/myproject/node_modules/builder-util/src/asyncTaskManager.ts:14:20)
    at LinuxPackager.packageInDistributableFormat (/home/johndoe/git/myproject/node_modules/app-builder-lib/src/platformPackager.ts:123:17)
    at /home/johndoe/git/myproject/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at LinuxPackager.pack (/home/johndoe/git/myproject/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/johndoe/git/myproject/node_modules/app-builder-lib/src/packager.ts:406:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/johndoe/git/myproject/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/johndoe/git/myproject/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:162:5)
From previous event:
    at Packager.doBuild (/home/johndoe/git/myproject/node_modules/app-builder-lib/src/packager.ts:372:24)
    at /home/johndoe/git/myproject/node_modules/app-builder-lib/src/packager.ts:342:57
From previous event:
    at Packager._build (/home/johndoe/git/myproject/node_modules/app-builder-lib/src/packager.ts:311:133)
    at /home/johndoe/git/myproject/node_modules/app-builder-lib/src/packager.ts:307:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/home/johndoe/git/myproject/node_modules/app-builder-lib/src/packager.ts:264:14)
    at build (/home/johndoe/git/myproject/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/johndoe/git/myproject/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/johndoe/git/myproject/node_modules/electron-builder/src/cli/cli.ts:46:19)
```

**Comment by junebug12851** [comment]
I'm using zsh and it's same issue, i'll try your suggestion. Searched Google for like 30 minutes and zilch support anywhere on anything I could remotely find

**Comment by junebug12851** [comment]
For me it didn't work, I dropped into `/bin/bash` and it errored out

```
  • building        target=pacman arch=x64 file=build/###### ### Setup linux.pacman
  • building        target=pacman arch=ia32 file=build/###### ### Setup linux i686.pacman
Error: Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
Error: Exit code: 1. Command failed: /home/junebug12851/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir -t pacman --architecture amd64 --name ######### --force --after-install /tmp/t-HA136w/5-after-install --after-remove /tmp/t-HA136w/1-after-remove --description ############ ###
 ############ ### --version 1.2.0 --package /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/build/###### ### Setup linux.pacman --maintainer June <###> --url https://github.com/junebug12851/##########readme --vendor June <###> --category Applications/###s --depends c-ares --depends ffmpeg --depends gtk3 --depends http-parser --depends libevent --depends libvpx --depends libxslt --depends libxss --depends minizip --depends nss --depends re2 --depends snappy --depends libnotify --depends libappindicator-gtk2 --depends libappindicator-gtk3 --depends libappindicator-sharp --license Apache-2.0 /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/build/linux-unpacked/=/opt/###### ### /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/16x16.png=/usr/share/icons/hicolor/16x16/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/24x24.png=/usr/share/icons/hicolor/24x24/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/48x48.png=/usr/share/icons/hicolor/48x48/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/64x64.png=/usr/share/icons/hicolor/64x64/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/96x96.png=/usr/share/icons/hicolor/96x96/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/128x128.png=/usr/share/icons/hicolor/128x128/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/256x256.png=/usr/share/icons/hicolor/256x256/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/512x512.png=/usr/share/icons/hicolor/512x512/apps/#########.png /tmp/t-HA136w/b-###### ###.desktop=/usr/share/applications/#########.desktop

{:timestamp=>"2018-11-26T23:58:46.935702-0500", :message=>"Process failed: /bin/zsh failed (exit code 127). Full command was:[\"/bin/zsh\", \"-c\", \"LANG=C bsdtar -czf .MTREE --format=mtree --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' opt usr .PKGINFO .INSTALL\"]", :level=>:error}

    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/util.ts:126:16
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
From previous event:
    at FpmTarget.build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/targets/fpm.ts:92:44)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:131:24
From previous event:
    at AsyncTaskManager.add (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/asyncTaskManager.ts:14:20)
    at LinuxPackager.packageInDistributableFormat (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:123:17)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at LinuxPackager.pack (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:406:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:162:5)
From previous event:
    at Packager.doBuild (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:372:24)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:342:57
    at Generator.next (<anonymous>)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:148:20)
From previous event:
    at Packager._build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:311:133)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:307:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:264:14)
    at build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/electron-builder/src/cli/cli.ts:46:19)

Error #2 --------------------------------------------------------------------------------
Error: Exit code: 1. Command failed: /home/junebug12851/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir -t pacman --architecture i686 --name ######### --force --after-install /tmp/t-HA136w/5-after-install --after-remove /tmp/t-HA136w/1-after-remove --description ############ ###
 ############ ### --version 1.2.0 --package /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/build/###### ### Setup linux i686.pacman --maintainer June <###> --url https://github.com/junebug12851/##########readme --vendor June <###> --category Applications/###s --depends c-ares --depends ffmpeg --depends gtk3 --depends http-parser --depends libevent --depends libvpx --depends libxslt --depends libxss --depends minizip --depends nss --depends re2 --depends snappy --depends libnotify --depends libappindicator-gtk2 --depends libappindicator-gtk3 --depends libappindicator-sharp --license Apache-2.0 /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/build/linux-ia32-unpacked/=/opt/###### ### /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/16x16.png=/usr/share/icons/hicolor/16x16/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/24x24.png=/usr/share/icons/hicolor/24x24/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/48x48.png=/usr/share/icons/hicolor/48x48/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/64x64.png=/usr/share/icons/hicolor/64x64/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/96x96.png=/usr/share/icons/hicolor/96x96/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/128x128.png=/usr/share/icons/hicolor/128x128/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/256x256.png=/usr/share/icons/hicolor/256x256/apps/#########.png /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/dist/#########/assets/icons/512x512.png=/usr/share/icons/hicolor/512x512/apps/#########.png /tmp/t-HA136w/c-###### ###.desktop=/usr/share/applications/#########.desktop

{:timestamp=>"2018-11-26T23:59:06.543607-0500", :message=>"Process failed: /bin/zsh failed (exit code 127). Full command was:[\"/bin/zsh\", \"-c\", \"LANG=C bsdtar -czf .MTREE --format=mtree --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' opt usr .PKGINFO .INSTALL\"]", :level=>:error}

    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/util.ts:126:16
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
From previous event:
    at FpmTarget.build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/targets/fpm.ts:92:44)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:131:24
From previous event:
    at AsyncTaskManager.add (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/asyncTaskManager.ts:14:20)
    at LinuxPackager.packageInDistributableFormat (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:123:17)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:114:10
From previous event:
    at LinuxPackager.pack (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:406:24
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.doBuild (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:372:24)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:342:57
    at Generator.next (<anonymous>)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:148:20)
From previous event:
    at Packager._build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:311:133)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:307:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:264:14)
    at build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/util.ts:126:16
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
    at FpmTarget.build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/targets/fpm.ts:92:44)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:131:24
    at AsyncTaskManager.add (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/asyncTaskManager.ts:14:20)
    at LinuxPackager.packageInDistributableFormat (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:123:17)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
    at LinuxPackager.pack (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:406:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:162:5)
    at Packager.doBuild (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:372:24)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:342:57
    at Generator.next (<anonymous>)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:148:20)
    at Packager._build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:311:133)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:307:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
    at Packager.build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:264:14)
    at build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/util.ts:126:16
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
    at FpmTarget.build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/targets/fpm.ts:92:44)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:131:24
    at AsyncTaskManager.add (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/asyncTaskManager.ts:14:20)
    at LinuxPackager.packageInDistributableFormat (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:123:17)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at LinuxPackager.pack (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:406:24
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
    at Packager.doBuild (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:372:24)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:342:57
    at Generator.next (<anonymous>)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:148:20)
    at Packager._build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:311:133)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:307:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
    at Packager.build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:264:14)
    at build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at throwError (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/asyncTaskManager.ts:90:11)
    at checkErrors (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/asyncTaskManager.ts:53:9)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/asyncTaskManager.ts:67:7
From previous event:
    at AsyncTaskManager.awaitTasks (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/builder-util/src/asyncTaskManager.ts:44:19)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:418:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.doBuild (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:372:24)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:342:57
    at Generator.next (<anonymous>)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:148:20)
From previous event:
    at Packager._build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:311:133)
    at /home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:307:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/packager.ts:264:14)
    at build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/junebug12851/Documents/Projects/Programming/Sandbox/angular2/#########/node_modules/electron-builder/src/cli/cli.ts:46:19)
npm ERR! code ELIFECYCLE
```

**Comment by emkay443** [comment]
Weird. Using zsh, it works in my case. Though I haven't configured zsh yet, it's pretty much vanilla. No "oh-my-zsh" or something like that.

```
johndoe@myhost ~/git/myproject $ env SHELL=zsh ./node_modules/.bin/electron-builder --linux --ia32 --x64
  • electron-builder version=20.36.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=2.0.14 appOutDir=dist/linux-unpacked
  • building        target=pacman arch=x64 file=dist/myproject-0.0.10.pacman
  • default Electron icon is used reason=application icon is not set
  • no native production dependencies
  • packaging       platform=linux arch=ia32 electron=2.0.14 appOutDir=dist/linux-ia32-unpacked
  • building        target=pacman arch=ia32 file=dist/myproject-0.0.10-i686.pacman
johndoe@myhost ~/git/myproject $
```

**Comment by junebug12851** [comment]
I already make AppImage as well, just wanted to provide native pacman format for users who preferred it but in favor of sanity I temporarily dropped pacman given AppImage is still provided as an alternative so that I can proceed with development.

**Comment by junebug12851** [comment]
Basically awaiting news on how to fix this if it's on my end or a fix to be made if it's not on my end until then users will just have to make do with AppImage which from my understanding is pretty universal and easy to use so shouldn't be much of a problem.

**Comment by emkay443** [comment]
Yeah, or just build with `env SHELL=bash`, as it seems to fix this problem. ;)

**Comment by emkay443** [comment]
AppImage sure is a solution, but I need some `afterInstall` and `afterRemove` scripts, and I don't know whether AppImage allows that.

**Comment by develar** [comment]
```
  /**
   * The function (or path to file or module id) to be run on artifact build start.
   */
  readonly artifactBuildStarted?: ((context: ArtifactBuildStarted) => Promise<any> | any) | string | null
  /**
   * The function (or path to file or module id) to be run on artifact build completed.
   */
  readonly artifactBuildCompleted?: ((context: ArtifactCreated) => Promise<any> | any) | string | null
```

added to configuration.

Hook `artifactBuildCompleted` only for main artifacts, so, it is not equivalent of existing artifactCreated event.

**Comment by 183amir** [comment]
Could we please re-open this issue?
