### ISSUE TITLE
How to auto update the electron application using the electron-updater?

### ISSUE THREAD

**Issue by applecool** [electron-userland/electron-builder#3500]
* **Version**: Electron-builder - `20.36.2`
Electron-updater - `4.0.4`

* **Target**:  Mac OSX

I have an angular app which has been converted into a desktop app using the electron-builder. Now, I am trying to implement the auto-updates features into it. I don't want electron-builder to publish the changes to the github repository. (Note: The whole app is on a private github repo.) I want to manually upload the necessary `.dmg, .zip, .yml` files to the release tag and I want that to be picked up by the auto updater. How can I achieve this? 

Currently, I have the source `.zip` and `.tar.gz` as part of my release tag. And whenever I try to invoke the `autoUpdater.checkForUpdates()` when the app is ready, I get the following error saying:
```
Error: ENOENT, dev-app-update.yml not found in /Users/userX/project-web/build/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar
at notFoundError (ELECTRON_ASAR.js:108:19)
    at fs.readFile (ELECTRON_ASAR.js:536:16)
    at go$readFile (/Users/userX/project-web/build/node_modules/graceful-fs/graceful-fs.js:85:14)
    at readFile (/Users/userX/project-web/build/node_modules/graceful-fs/graceful-fs.js:82:12)
    at readFile (/Users/userX/project-web/build/node_modules/universalify/index.js:5:67)
From previous event:
    at /Users/userX/project-web/build/node_modules/electron-updater/src/AppUpdater.ts:460:27
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.loadUpdateConfig (/Users/userX/project-web/build/node_modules/electron-updater/src/AppUpdater.ts:456:33)
    at Lazy.AppUpdater.configOnDisk (/Users/userX/project-web/build/node_modules/electron-updater/src/AppUpdater.ts:142:43)
    at Lazy.get value [as value] (/Users/userX/project-web/build/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/userX/project-web/build/node_modules/electron-updater/src/AppUpdater.ts:340:46
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at MacUpdater.getUpdateInfoAndProvider (/Users/userX/project-web/build/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /Users/userX/project-web/build/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Users/userX/project-web/build/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at MacUpdater.checkForUpdates (/Users/userX/project-web/build/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at Timeout.check [as _onTimeout] (/Users/userX/project-web/desktop/src/updater.ts:15:17)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

Here's my code:

`updater.ts`
```
import { autoUpdater } from 'electron-updater';
import { dialog, BrowserWindow, ipcMain } from 'electron';

const log = require('electron-log');
let downloadProgress: number;
log.transports.file.level = "debug";
autoUpdater.logger = log;

autoUpdater.autoDownload = false;

export function check() {
    autoUpdater.checkForUpdates();

    autoUpdater.on('checking-for-update', () => {
        dialog.showMessageBox({
            type: 'info',
            title: 'Update Available',
            message: 'A new version of app is available. Do you want to update now?',
            buttons: ['Update', 'No']
        }, (index) => {
            if (index) {
                return;
            } else {
                autoUpdater.downloadUpdate();

                let proWin = new BrowserWindow({
                    width: 350,
                    height: 35,
                    useContentSize: true,
                    autoHideMenuBar: true,
                    maximizable: false,
                    fullscreen: false,
                    fullscreenable: false,
                    resizable: false,
                    title: 'Downloading Update'
                });
                proWin.loadURL(`file://$(__dirname)/progress`);

                proWin.on('closed', () => {
                    proWin = null;
                });

                ipcMain.on('download-progress-request', (e) => {
                    e.returnValue = downloadProgress;
                });

                autoUpdater.on('download-progress', (d) => {
                    downloadProgress = d.percent;
                    autoUpdater.logger.info(downloadProgress);
                });

                autoUpdater.on('update-downloaded', () => {
                    if (progressWindow) progressWindow.close();

                    dialog.showMessageBox({
                        type: 'info',
                        title: 'Update Ready',
                        message: 'A new version of app is ready. Quit and Install now?',
                        buttons: ['Yes', 'Later']
                    }, (index) => {
                        if (!index) {
                            autoUpdater.quitAndInstall();
                        }
                    });
                });
            }
        });
    });
}
```
The `check()` method in the `updater.ts` is invoked from the `main.ts` when the app is ready as follows:
```
app.on('ready', async () => {
   mainWinProcess() // handles all the browser window ops.
   createTray();
   setTimeout(updater.check, 2000); 
});
```
`package.json` as follows:

```
{
    "name": "project-web",
    "productName": "Project Web X",
    "version": "1.0.0",
    "author": "applecool",
    "description": "A func app",
    "main": "./main.js",
    "dependencies": {
        "electron-log": "2.2.17",
        "electron-updater": "4.0.4",
        "path": "0.12.7",
        "url": "0.11.0",
        "fs-extra": "7.0.1",
        "decompress-zip": "0.3.1"
    },
    "scripts": {
        "mac": "NODE_ENV=production ./node_modules/gulp/bin/gulp.js --gulpfile ./ops/gulpfile.js mac",
        "mac-dev": "NODE_ENV=development ./node_modules/gulp/bin/gulp.js --gulpfile ./ops/gulpfile.js mac-dev",
        "start": "NODE_ENV=development ./node_modules/.bin/electron index.js --debug --enable-logging",
        "start-mac-setup-dev": "build --mac --config electron-builder-dev.yml",
        "start-mac-setup": "build --mac"
    },
    "devDependencies": {
        "@types/node": "^10.12.9",
        "electron": "3.0.10",
        "electron-builder": "20.36.2",
        "electron-is-dev": "1.0.1",
        "electron-reload": "1.3.0",
        "gulp": "4.0.0",
        "icon-gen": "2.0.0",
        "jimp": "0.5.6",
        "os": "0.1.1",
        "zip-folder": "1.0.0",
        "devtron": "1.4.0"
    },
    "build": {
        "appId": "com.projectweb.x"
    }
}
```

Could anyone please point me in a right direction. I am trying to do this in the dev environment.

Thank you.

**Comment by kontrollanten** [comment]
I guess you can find docs on https://www.electron.build/auto-update.html

> Note that in order to develop/test UI/UX of updating without packaging the application you need to have a file named dev-app-update.yml in the root of your project, which matches your publish setting from electron-builder config (but in yaml format). But it is not recommended, better to test auto-update for installed application (especially on Windows). Minio is recommended as a local server for testing updates.
