### ISSUE TITLE
Error not a file on windows build

### ISSUE THREAD

**Issue by mayur5478** [electron-userland/electron-builder#3502]
20.36.2

* **Version**: 

4.0.4

* **Target**: 
Windows

While building it is giving this error:-

Error: B:\recorder-to-test-720p not a file
    at B:\recorder-to-test-720p\node_modules\app-builder-lib\src\codeSign\macCodeSign.ts:128:11
    at Generator.next (<anonymous>)
    at B:\recorder-to-test-720p\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at _downloadCertificate (B:\recorder-to-test-720p\node_modules\app-builder-lib\out\codeSign\macCodeSign.js:268:31)
    at downloadCertificate (B:\recorder-to-test-720p\node_modules\app-builder-lib\out\codeSign\macCodeSign.js:219:31)
    at Lazy.WinPackager.cscInfo (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\winPackager.ts:61:12)
    at Lazy.get value [as value] (B:\recorder-to-test-720p\node_modules\lazy-val\src\main.ts:18:23)
    at Lazy.<anonymous> (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\winPackager.ts:88:40)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (B:\recorder-to-test-720p\node_modules\lazy-val\src\main.ts:18:23)
    at B:\recorder-to-test-720p\node_modules\app-builder-lib\src\publish\PublishManager.ts:234:112
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at _getAppUpdatePublishConfiguration (B:\recorder-to-test-720p\node_modules\app-builder-lib\out\publish\PublishManager.js:442:44)
    at getAppUpdatePublishConfiguration (B:\recorder-to-test-720p\node_modules\app-builder-lib\out\publish\PublishManager.js:416:44)
    at B:\recorder-to-test-720p\node_modules\app-builder-lib\src\publish\PublishManager.ts:101:35
    at Generator.next (<anonymous>)
From previous event:
    at B:\recorder-to-test-720p\node_modules\app-builder-lib\src\publish\PublishManager.ts:84:5
    at _bluebirdLst.default.each.it (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\packager.ts:503:49)
From previous event:
    at Packager.afterPack (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\packager.ts:503:28)
    at B:\recorder-to-test-720p\node_modules\app-builder-lib\src\platformPackager.ts:242:21
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.doPack (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at B:\recorder-to-test-720p\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at B:\recorder-to-test-720p\node_modules\app-builder-lib\src\packager.ts:406:24
    at Generator.next (<anonymous>)
    at xfs.stat (B:\recorder-to-test-720p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at B:\recorder-to-test-720p\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\packager.ts:372:24)
    at B:\recorder-to-test-720p\node_modules\app-builder-lib\src\packager.ts:342:57
    at Generator.next (<anonymous>)
    at B:\recorder-to-test-720p\node_modules\graceful-fs\graceful-fs.js:111:16
    at B:\recorder-to-test-720p\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\packager.ts:311:133)
    at B:\recorder-to-test-720p\node_modules\app-builder-lib\src\packager.ts:307:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\packager.ts:264:14)
    at build (B:\recorder-to-test-720p\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (B:\recorder-to-test-720p\node_modules\electron-builder\src\builder.ts:227:10)
    at then (B:\recorder-to-test-720p\node_modules\electron-builder\src\cli\cli.ts:46:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Hifi_recorder@1.0.7 dist: `build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Hifi_recorder@1.0.7 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mayur\AppData\Roaming\npm-cache\_logs\2018-11-27T06_07_29_687Z-debug.log

**Comment by develar** [comment]
env `WIN_CSC_LINK` doesn't point to correct p12 file for code sign.
