### ISSUE TITLE
Error: Cannot extract publisher name from code signing certificate, please file issue. As workaround, set win.publisherName

### ISSUE THREAD

**Issue by mayur5478** [electron-userland/electron-builder#3507]
20.38.0

* **Version**: 

* **Target**: Windows

Error: Cannot extract publisher name from code signing certificate, please file issue. As workaround, set win.publisherName

: Error: B:\recorder-27-11\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (B:\recorder-27-11\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at _getCertInfo (B:\recorder-27-11\node_modules\app-builder-lib\out\codeSign\windowsCodeSign.js:184:23)
    at getCertInfo (B:\recorder-27-11\node_modules\app-builder-lib\out\codeSign\windowsCodeSign.js:164:23)
    at Lazy.<anonymous> (B:\recorder-27-11\node_modules\app-builder-lib\src\winPackager.ts:114:18)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Lazy.get value [as value] (B:\recorder-27-11\node_modules\lazy-val\src\main.ts:18:23)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\publish\PublishManager.ts:234:112
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at _getAppUpdatePublishConfiguration (B:\recorder-27-11\node_modules\app-builder-lib\out\publish\PublishManager.js:442:44)
    at getAppUpdatePublishConfiguration (B:\recorder-27-11\node_modules\app-builder-lib\out\publish\PublishManager.js:416:44)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\publish\PublishManager.ts:101:35
    at Generator.next (<anonymous>)
From previous event:
    at B:\recorder-27-11\node_modules\app-builder-lib\src\publish\PublishManager.ts:84:5
    at _bluebirdLst.default.each.it (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:527:49)
From previous event:
    at Packager.afterPack (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:527:28)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:242:21
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at WinPackager.doPack (B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (B:\recorder-27-11\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at B:\recorder-27-11\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:396:24)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at B:\recorder-27-11\node_modules\graceful-fs\graceful-fs.js:111:16
    at B:\recorder-27-11\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:335:133)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (B:\recorder-27-11\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (B:\recorder-27-11\node_modules\electron-builder\src\builder.ts:227:10)
    at then (B:\recorder-27-11\node_modules\electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
    at ChildProcess.childProcess.once.code (B:\recorder-27-11\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
    at _getCertInfo (B:\recorder-27-11\node_modules\app-builder-lib\out\codeSign\windowsCodeSign.js:184:23)
    at getCertInfo (B:\recorder-27-11\node_modules\app-builder-lib\out\codeSign\windowsCodeSign.js:164:23)
    at Lazy.<anonymous> (B:\recorder-27-11\node_modules\app-builder-lib\src\winPackager.ts:114:18)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at Lazy.get value [as value] (B:\recorder-27-11\node_modules\lazy-val\src\main.ts:18:23)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\publish\PublishManager.ts:234:112
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at _getAppUpdatePublishConfiguration (B:\recorder-27-11\node_modules\app-builder-lib\out\publish\PublishManager.js:442:44)
    at getAppUpdatePublishConfiguration (B:\recorder-27-11\node_modules\app-builder-lib\out\publish\PublishManager.js:416:44)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\publish\PublishManager.ts:101:35
    at Generator.next (<anonymous>)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\publish\PublishManager.ts:84:5
    at _bluebirdLst.default.each.it (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:527:49)
    at Packager.afterPack (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:527:28)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:242:21
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at WinPackager.doPack (B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
    at WinPackager.pack (B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (B:\recorder-27-11\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at B:\recorder-27-11\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
    at Packager.doBuild (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:396:24)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at B:\recorder-27-11\node_modules\graceful-fs\graceful-fs.js:111:16
    at B:\recorder-27-11\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
    at Packager._build (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:335:133)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at Packager.build (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (B:\recorder-27-11\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (B:\recorder-27-11\node_modules\electron-builder\src\builder.ts:227:10)
    at then (B:\recorder-27-11\node_modules\electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
    at B:\recorder-27-11\node_modules\app-builder-lib\src\codeSign\windowsCodeSign.ts:88:11
    at Generator.throw (<anonymous>)
From previous event:
    at _getCertInfo (B:\recorder-27-11\node_modules\app-builder-lib\out\codeSign\windowsCodeSign.js:184:23)
    at getCertInfo (B:\recorder-27-11\node_modules\app-builder-lib\out\codeSign\windowsCodeSign.js:164:23)
    at Lazy.<anonymous> (B:\recorder-27-11\node_modules\app-builder-lib\src\winPackager.ts:114:18)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Lazy.get value [as value] (B:\recorder-27-11\node_modules\lazy-val\src\main.ts:18:23)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\publish\PublishManager.ts:234:112
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at _getAppUpdatePublishConfiguration (B:\recorder-27-11\node_modules\app-builder-lib\out\publish\PublishManager.js:442:44)
    at getAppUpdatePublishConfiguration (B:\recorder-27-11\node_modules\app-builder-lib\out\publish\PublishManager.js:416:44)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\publish\PublishManager.ts:101:35
    at Generator.next (<anonymous>)
From previous event:
    at B:\recorder-27-11\node_modules\app-builder-lib\src\publish\PublishManager.ts:84:5
    at _bluebirdLst.default.each.it (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:527:49)
From previous event:
    at Packager.afterPack (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:527:28)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:242:21
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at WinPackager.doPack (B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (B:\recorder-27-11\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (B:\recorder-27-11\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at B:\recorder-27-11\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:396:24)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at B:\recorder-27-11\node_modules\graceful-fs\graceful-fs.js:111:16
    at B:\recorder-27-11\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:335:133)
    at B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (B:\recorder-27-11\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (B:\recorder-27-11\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (B:\recorder-27-11\node_modules\electron-builder\src\builder.ts:227:10)
    at then (B:\recorder-27-11\node_modules\electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! HTS_Recorder@1.0.7 dist: `electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the HTS_Recorder@1.0.7 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mayur\AppData\Roaming\npm-cache\_logs\2018-11-28T07_36_42_211Z-debug.log

Can I set codeSign to false in windows ? If so , how ? Also can code signing work on sef signed certificate in windows 10?

**Comment by shawnsang** [comment]
I used win.publisherName in package.json, still not work. My electron-builder version is 20.38.1.
