### ISSUE TITLE
20.38.2: electron-builder install-app-deps - Unresolved node modules: rollup

### ISSUE THREAD

**Issue by JohnRSim** [electron-userland/electron-builder#3518]
* **Version**: 
20.38.2

* **Target**: 
Windows 10

Error Error: Unresolved node modules: rollup on installing electron-builder

```
>npm install

> jse-desktop@0.5.9 postinstall C:\work\jsecoin\github\platform
> electron-builder install-app-deps

  • electron-builder version=20.38.2
  • loaded configuration file=package.json ("build" field)
Error: Unresolved node modules: rollup
    at C:\work\jsecoin\github\platform\node_modules\app-builder-lib\src\util\packageDependencies.ts:112:21
From previous event:
    at Collector.resolveUnresolvedHoisted (C:\work\jsecoin\github\platform\node_modules\app-builder-lib\src\util\packageDependencies.ts:88:81)
    at C:\work\jsecoin\github\platform\node_modules\app-builder-lib\src\util\packageDependencies.ts:83:18
From previous event:
    at Collector.collect (C:\work\jsecoin\github\platform\node_modules\app-builder-lib\src\util\packageDependencies.ts:76:28)
    at C:\work\jsecoin\github\platform\node_modules\app-builder-lib\src\util\packageDependencies.ts:47:44
    at Generator.next (<anonymous>)
From previous event:
    at _getProductionDependencies (C:\work\jsecoin\github\platform\node_modules\app-builder-lib\out\util\packageDependencies.js:92:37)
    at getProductionDependencies (C:\work\jsecoin\github\platform\node_modules\app-builder-lib\out\util\packageDependencies.js:83:37)
    at Lazy.<anonymous> (C:\work\jsecoin\github\platform\node_modules\app-builder-lib\src\util\packageDependencies.ts:41:25)
    at Lazy.get value [as value] (C:\work\jsecoin\github\platform\node_modules\lazy-val\src\main.ts:18:23)
    at C:\work\jsecoin\github\platform\node_modules\app-builder-lib\out\util\yarn.js:166:90
    at Generator.next (<anonymous>)
From previous event:
    at _rebuild (C:\work\jsecoin\github\platform\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (C:\work\jsecoin\github\platform\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at C:\work\jsecoin\github\platform\node_modules\app-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at _installOrRebuild (C:\work\jsecoin\github\platform\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\work\jsecoin\github\platform\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\work\jsecoin\github\platform\node_modules\electron-builder\src\cli\install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jse-desktop@0.5.9 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jse-desktop@0.5.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by JohnRSim** [comment]
just installed the rollup as dev and fixed issue for now - will take a look later.
