### ISSUE TITLE
cannot find moudle 'electron-builder-squirrel-windows'

### ISSUE THREAD

**Issue by BigSteel** [electron-userland/electron-builder#3519]
electron-builder:20.28.2
electron-builder-squirrel-windows:20.38.2
os :win10 x64 

details:
Module electron-builder-squirrel-windows must be installed in addition to build Squirrel.Windows: Error: Cannot find module 'electron-builder-squirrel-windows'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at targetClass (C:\Users\xxx\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\src\winPackager.ts:167:24)

**Comment by sandeep1995** [comment]
If you set windows target as `squirrel` then this package `electron-builder-squirrel-windows` is required. 
Squirrel target is deprecated. If possible, try to use `nsis`
