### ISSUE TITLE
Error: spawn wine ENOENT

### ISSUE THREAD

**Issue by jechazelle** [electron-userland/electron-builder#352]
I have an error when I execute the build electron to create mac application with this command :

`sudo npm run-script dist`

```
Error: spawn wine ENOENT
        at exports._errnoException (util.js:890:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
        at onErrorNT (internal/child_process.js:348:16)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)
When I launch my app with `npm start` it works !
```
 and after

```
npm ERR! Darwin 15.0.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist:win32"
    npm ERR! node v5.10.0
    npm ERR! npm  v3.8.3
    npm ERR! code ELIFECYCLE
    npm ERR! releaseChecker@ dist:win32: `build --platform win32 --arch ia32`
    npm ERR! Exit status 255
```

**output**

```
    > releaseChecker@ dist /Users/chazellejeremie/Sites/release-checker-app
    > npm run dist:osx && npm run dist:win32 && npm run dist:win64


    > releaseChecker@ dist:osx /Users/chazellejeremie/Sites/release-checker-app
    > build --platform darwin

    license in the development package.json is deprecated, please move to the application package.json
    Rebuilding app dependencies for arch x64 to /Users/chazellejeremie/Sites/release-checker-app/app
    electron-squirrel-startup@0.1.4 /Users/chazellejeremie/Sites/release-checker-app/app/node_modules/electron-squirrel-startup
    debug@2.2.0 /Users/chazellejeremie/Sites/release-checker-app/app/node_modules/debug
    ms@0.7.1 /Users/chazellejeremie/Sites/release-checker-app/app/node_modules/ms
    Packaging app for platform darwin x64 using electron v0.37.6
    App is not signed: CSC_LINK or CSC_NAME are not specified
    Creating DMG
    Creating ZIP for Squirrel.Mac

    > releaseChecker@ dist:win32 /Users/chazellejeremie/Sites/release-checker-app
    > build --platform win32 --arch ia32

    license in the development package.json is deprecated, please move to the application package.json
    Rebuilding app dependencies for arch ia32 to /Users/chazellejeremie/Sites/release-checker-app/app
    electron-squirrel-startup@0.1.4 /Users/chazellejeremie/Sites/release-checker-app/app/node_modules/electron-squirrel-startup
    debug@2.2.0 /Users/chazellejeremie/Sites/release-checker-app/app/node_modules/debug
    ms@0.7.1 /Users/chazellejeremie/Sites/release-checker-app/app/node_modules/ms
    Removing /Users/chazellejeremie/Sites/release-checker-app/dist/win
    Packaging app for platform win32 ia32 using electron v0.37.6
    Error: spawn wine ENOENT
        at exports._errnoException (util.js:890:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
        at onErrorNT (internal/child_process.js:348:16)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)
    From previous event:
        at WinPackager.<anonymous> (/Users/chazellejeremie/Sites/release-checker-app/node_modules/electron-builder/src/platformPackager.ts:143:15)
        at [object Generator].next (native)
    From previous event:
        at tsAwaiter (/Users/chazellejeremie/Sites/release-checker-app/node_modules/electron-builder/src/awaiter.ts:10:51)
        at Object.build (/Users/chazellejeremie/Sites/release-checker-app/node_modules/electron-builder/src/builder.ts:30:59)
        at Object.<anonymous> (/Users/chazellejeremie/Sites/release-checker-app/node_modules/electron-builder/src/build-cli.ts:47:2)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Function.Module.runMain (module.js:447:10)
        at startup (node.js:146:18)
        at node.js:404:3

    npm ERR! Darwin 15.0.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist:win32"
    npm ERR! node v5.10.0
    npm ERR! npm  v3.8.3
    npm ERR! code ELIFECYCLE
    npm ERR! releaseChecker@ dist:win32: `build --platform win32 --arch ia32`
    npm ERR! Exit status 255
    npm ERR! 
    npm ERR! Failed at the releaseChecker@ dist:win32 script 'build --platform win32 --arch ia32'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the releaseChecker package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     build --platform win32 --arch ia32
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs releaseChecker
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls releaseChecker
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/chazellejeremie/Sites/release-checker-app/npm-debug.log

    npm ERR! Darwin 15.0.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "dist"
    npm ERR! node v5.10.0
    npm ERR! npm  v3.8.3
    npm ERR! code ELIFECYCLE
    npm ERR! releaseChecker@ dist: `npm run dist:osx && npm run dist:win32 && npm run dist:win64`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the releaseChecker@ dist script 'npm run dist:osx && npm run dist:win32 && npm run dist:win64'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the releaseChecker package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run dist:osx && npm run dist:win32 && npm run dist:win64
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs releaseChecker
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls releaseChecker
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/chazellejeremie/Sites/release-checker-app/npm-debug.log

```

**my package.json**

```
{
      "name": "releaseChecker",
      "description": "Release CHecker application built with Electron.",
      "scripts": {
        "start": "electron ./app --enable-logging",
        "dev": "NODE_ENV='development' npm run start",
        "dist": "npm run dist:osx && npm run dist:win32 && npm run dist:win64",
        "dist:osx": "build --platform darwin",
        "dist:win32": "build --platform win32 --arch ia32",
        "dist:win64": "build --platform win32 --arch x64"
      },
      "author": "",
      "license": "MIT",
      "devDependencies": {
        "electron-builder": "^3.9.0",
        "electron-prebuilt": "^0.37.6"
      },
      "build": {
        "app-bundle-id": "releasechecker",
        "app-category-type": "public.app-category.productivity",
        "iconUrl": "http://releasechecker.s3.amazonaws.com/icon.ico",
        "osx": {
          "title": "Release Checker",
          "background": "build/background.png",
          "icon": "build/app-icon.icns",
          "icon-size": 128,
          "contents": [
            {
              "x": 355,
              "y": 125,
              "type": "link",
              "path": "/Applications"
            },
            {
              "x": 155,
              "y": 125,
              "type": "file"
            }
          ]
        }
      }
    }

```

I use node v5.10.0 and npm 3.8.3

**Comment by develar** [comment]
See https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#os-x

> npm run dist:osx && npm run dist:win32 && npm run dist:win64

See http://electron.rocks/electron-builder-explained/#comment-2607281511

**Comment by jechazelle** [comment]
hi develar,
thx for your answer !

I use El Capitan to make my application

**Comment by MontassarHammouda** [comment]
install wine

**Comment by MontassarHammouda** [comment]
install wine
