### ISSUE TITLE
Auto updater fails on mac

### ISSUE THREAD

**Issue by gryzzly** [electron-userland/electron-builder#3525]
* **Version**: 
Builder 20.36.2 
Updater 4.0.4

* **Target**: 
Default "mac"

After recent updates we have troubles with auto-updates on Mac. Some users are getting the following error that I wasn’t able to reproduce on any of our development machines.

The error happens at the time of checking for updates, for us that means on application launch and when user manually clicks "check for updates" in application menu.

Any advice greatly appreciated!

<details>
  <summary>The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.</summary>

  ```
  Unhandled Promise Rejection

  Error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

  at Object.done (/Applications/IDAGIO.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:56:11)

  at /Applications/IDAGIO.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:583:25

  at Generator.next (<anonymous>)

  From previous event:

  at done (/Applications/IDAGIO.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:581:15)

  at /Applications/IDAGIO.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:624:18

  at Generator.next (<anonymous>)

  From previous event:

  at MacUpdater.executeDownload (/Applications/IDAGIO.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:545:68)

  at MacUpdater.doDownloadUpdate (/Applications/IDAGIO.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:49:17)

  at MacUpdater.downloadUpdate (/Applications/IDAGIO.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:420:19)

  at /Applications/IDAGIO.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:383:49

  at Generator.next (<anonymous>)

  From previous event:

  at MacUpdater.doCheckForUpdates (/Applications/IDAGIO.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)

  at MacUpdater.checkForUpdates (/Applications/IDAGIO.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)

  at MacUpdater.checkForUpdatesAndNotify (/Applications/IDAGIO.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:249:41)

  at Object.<anonymous> (/Applications/IDAGIO.app/Contents/Resources/app.asar/electron.js:61:30)

  at Object.<anonymous> (/Applications/IDAGIO.app/Contents/Resources/app.asar/electron.js:298:3)
  ```
</details>

**Comment by aguynamedben** [comment]
We that App Transport Security policy error too sometimes. And sometimes, intermittently, users (including me testing prod build updates) see the download from S3 failing even when I know my computer has internet connectivity and the file is on S3.

```
[2018-12-08 16:33:50.115] [info] /1544315630078-7713.zip requested
[2018-12-08 16:33:50.116] [info] /1544315630078-7713.zip requested by Squirrel.Mac, pipe /Users/ben/Library/Application Support/Caches/tesla-updater/pending/Command E-1.2.20-mac.zip
[2018-12-08 16:33:55.277] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://commande-releases.s3.amazonaws.com/Command%20E-1.2.20-mac.zip)
[2018-12-08 16:33:55.282] [warn] Error: The network connection was lost.

[2018-12-08 16:33:55.283] [error] Error: Error: The network connection was lost.
```

![image](https://user-images.githubusercontent.com/107841/49692148-28588480-fb08-11e8-828b-26fdacc4622a.png)

electron-builder@20.38.2
electron-updater@4.0.5

@gryzzly Do you see that Squirrel.Mac error? I think you have to tweak the logger a bit...
```js
    // Production - Run autoUpdater
    autoUpdater.logger = log; // log from electron-log
    autoUpdater.logger.transports.file.level = 'info';
```

**Comment by gryzzly** [comment]
@aguynamedben we have these lines already in the source

I did get the output like yours at some point, when testing our releases on my own machine.
```
[2018-12-08 16:33:55.282] [warn] Error: The network connection was lost.
[2018-12-08 16:33:55.283] [error] Error: Error: The network connection was lost.

**Comment by aguynamedben** [comment]
We're also seeing the reported App Transport Security idea with only some users:
![image](https://user-images.githubusercontent.com/107841/49768588-a1cfae80-fc91-11e8-8b6d-21d1283ac381.png)

It's a very painful error because a certain subset of our users are just "stuck" on an old version of our app. They can't upgrade past a specific version. We'd have to ask them to download and install the new version manually.

Any ideas @develar? I'm happy to spend some time investigating, I just don't know where to start given the intermittent behavior.

@gryzzly Did you find any workaround? i.e. using an old version or doing auto-updates a different way?

**Comment by aguynamedben** [comment]
Related issues:
https://github.com/electron-userland/electron-builder/issues/3377
https://github.com/electron-userland/electron-builder/issues/3051

**Comment by aguynamedben** [comment]
Donated toward this issue 🙏 https://www.electron.build/donate

**Comment by aguynamedben** [comment]
We don't have a ton of users, but the user this is happening to is on macOS 10.11.6 (El Capitan, which is pretty old now). I noticed [here](https://github.com/develar/electron-builder/blob/76fdd42336c41c35bedb56624e6947f339df653b/packages/app-builder-lib/src/wine.ts#L19) that there are checks for 10.12.x and 10.13.x. Is El Capitan supported?

@gryzzly Are you able to determine what the macOS version is for users seeing this with your app?

Auto-update were previously working for this El Capitan user, so I think it's unlikely to be the cause, but would like to rule out this theory if possible.

**Comment by aguynamedben** [comment]
I'm reviewing the Apple ATS guidelines and noticed that macOS 10.12 and before have slightly different behavior for ATS.

![image](https://user-images.githubusercontent.com/107841/49771249-1bb96500-fc9d-11e8-84a3-6c2e33646f6f.png)
[Source](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW68)

I'm reviewing the [recent changes](https://github.com/develar/electron-builder/commit/76fdd42336c41c35bedb56624e6947f339df653b) to ATS usage (this user also [pointed it out](https://github.com/electron-userland/electron-builder/issues/3377#issuecomment-444050998)) to understand if electron-updates sets `"NSAllowsArbitraryLoads": true`. It should be setting that to support macOS 10.12 and before.

**Comment by develar** [comment]
Duplicates #3377
