### ISSUE TITLE
Build error on ubuntu 16.04

### ISSUE THREAD

**Issue by betterRunner** [electron-userland/electron-builder#3529]
* **Version**: 20.38.2

* **Target**: Linux

I am buidling a vue-electron based project on my Ubuntu 16.04 with below errors:
the version of node is: 10.6.0
the version of npm is: 6.4.1
Thanks in advance.

```
Error: Cannot cleanup:

Error #1 --------------------------------------------------------------------------------
Error: /home/kjim/code/projects/my-electron/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/kjim/code/projects/my-electron/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:598:12)
From previous event:
    at AppImageTarget.build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:28:44)
    at Function.buildAsyncTargets (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at LinuxPackager.packageInDistributableFormat (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at LinuxPackager.pack (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/kjim/code/projects/my-electron/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:159:5)
From previous event:
    at Packager.doBuild (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/kjim/code/projects/my-electron/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/kjim/code/projects/my-electron/node_modules/electron-builder/src/cli/cli.ts:46:19)

Error #2 --------------------------------------------------------------------------------
Error: /home/kjim/code/projects/my-electron/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/kjim/code/projects/my-electron/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:598:12)
From previous event:
    at SnapTarget.build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/targets/snap.ts:148:44)
    at Function.buildAsyncTargets (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at LinuxPackager.packageInDistributableFormat (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at LinuxPackager.pack (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/kjim/code/projects/my-electron/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:159:5)
From previous event:
    at Packager.doBuild (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/kjim/code/projects/my-electron/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/kjim/code/projects/my-electron/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at ChildProcess.childProcess.once.code (/home/kjim/code/projects/my-electron/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:598:12)
    at AppImageTarget.build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:28:44)
    at Function.buildAsyncTargets (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at LinuxPackager.packageInDistributableFormat (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at LinuxPackager.pack (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/kjim/code/projects/my-electron/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:159:5)
    at Packager.doBuild (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:145:20)
    at Packager._build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at Packager.build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/kjim/code/projects/my-electron/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/kjim/code/projects/my-electron/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at ChildProcess.childProcess.once.code (/home/kjim/code/projects/my-electron/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:598:12)
    at SnapTarget.build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/targets/snap.ts:148:44)
    at Function.buildAsyncTargets (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at LinuxPackager.packageInDistributableFormat (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at LinuxPackager.pack (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/kjim/code/projects/my-electron/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:159:5)
    at Packager.doBuild (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:145:20)
    at Packager._build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at Packager.build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/kjim/code/projects/my-electron/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/kjim/code/projects/my-electron/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at throwError (/home/kjim/code/projects/my-electron/node_modules/builder-util/src/asyncTaskManager.ts:90:11)
    at checkErrors (/home/kjim/code/projects/my-electron/node_modules/builder-util/src/asyncTaskManager.ts:53:9)
    at /home/kjim/code/projects/my-electron/node_modules/builder-util/src/asyncTaskManager.ts:67:7
From previous event:
    at AsyncTaskManager.awaitTasks (/home/kjim/code/projects/my-electron/node_modules/builder-util/src/asyncTaskManager.ts:44:19)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:442:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.doBuild (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/kjim/code/projects/my-electron/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/kjim/code/projects/my-electron/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/kjim/code/projects/my-electron/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/kjim/code/projects/my-electron/node_modules/electron-builder/src/cli/cli.ts:46:19)
```

**Comment by betterRunner** [comment]
Sorry to pull the issue without reviewing the error info, I fix my problem now.

It is because of the network problem:
` ⨯ Get https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-2.4/snap-template-electron-2.4.tar.7z: proxyconnect tcp: dial tcp :0: connect: connection refused`
And I use the proxy to make it work, thanks.

**Comment by rburmeister** [comment]
How did you fix this issue? Running into the same problem

**Comment by darkphenyx2021** [comment]
I'm also running into this error. How did you go about fixing it?

**Comment by shrinidhi111** [comment]
In my case, I got the error since "multipass" was not installed. I fixed it by running 

>> sudo snap install multipass --classic --beta

But of course to find the actual in your case go through the error stack once again.
