### ISSUE TITLE
Build failing just by including `react-no-render` in `package.json`

### ISSUE THREAD

**Issue by fabiospampinato** [electron-userland/electron-builder#3530]
* **Version**: v20.38.2

Just be including `react-no-render` in `package.json`, without even requiring it, I get this error:

```
Error: Unresolved node modules: render
    at /Users/fabio/Desktop/foo/node_modules/app-builder-lib/src/util/packageDependencies.ts:112:21
From previous event:
    at Collector.resolveUnresolvedHoisted (/Users/fabio/Desktop/foo/node_modules/app-builder-lib/src/util/packageDependencies.ts:88:81)
    at /Users/fabio/Desktop/foo/node_modules/app-builder-lib/src/util/packageDependencies.ts:83:18
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Collector.collect (/Users/fabio/Desktop/foo/node_modules/app-builder-lib/src/util/packageDependencies.ts:76:28)
    at /Users/fabio/Desktop/foo/node_modules/app-builder-lib/src/util/packageDependencies.ts:47:44
    at Generator.next (<anonymous>)
    at _getProductionDependencies (/Users/fabio/Desktop/foo/node_modules/app-builder-lib/out/util/packageDependencies.js:92:37)
    at getProductionDependencies (/Users/fabio/Desktop/foo/node_modules/app-builder-lib/out/util/packageDependencies.js:83:37)
    at Lazy.<anonymous> (/Users/fabio/Desktop/foo/node_modules/app-builder-lib/src/packager.ts:138:24)
    at Generator.next (<anonymous>)
    at Lazy.get value [as value] (/Users/fabio/Desktop/foo/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/fabio/Desktop/foo/node_modules/app-builder-lib/out/util/yarn.js:166:89
From previous event:
...and so on...
```

My guess is that for some reason the `-no-render` portion of `react-no-render` is considered as a directive to not bundle the `render` package.

I just wasted multiple hours on this 😞

**Comment by fabiospampinato** [comment]
I've renamed the package to `react-component-renderless` and I'm still seeing the problem 😨Just removing it from `package.json`, without even removing it from `node_modules`, makes the error disappear.

**Comment by fabiospampinato** [comment]
There was a typo in that package.
