### ISSUE TITLE
NsisUpdater crash (a value true was yielded that could not be treated as a promise)

### ISSUE THREAD

**Issue by yovanoc** [electron-userland/electron-builder#3546]
* **Version**: 20.36.1

electron updater : 4.0.1

I have a lot of sentry reports since I upgrade to electron 3. Thanks
https://sentry.io/share/issue/61fef9ef60014ce99a32b40be7a10c2b/

**Comment by Kelin2025** [comment]
Have this problem too:
```
TypeError: A value true was yielded that could not be treated as a promise

    See http://goo.gl/MqrFmX

From coroutine:
    at Promise.coroutine (C:\Users\Philipp\AppData\Local\Programs\frameninja\resources\app.asar\node_modules\bluebird\js\release\generators.js:194:17)
    at NsisUpdater.quitAndInstall (C:\Users\Philipp\AppData\Local\Programs\frameninja\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:13:83)
    at NsisUpdater.quitAndInstall (C:\Users\Philipp\AppData\Local\Programs\frameninja\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:13:83)
```

**Comment by develar** [comment]
Please use latest electron-updater (see https://github.com/electron-userland/electron-builder/issues/4018).
