### ISSUE TITLE
at least snapcraft 2.40.0 ... unable to build snap

### ISSUE THREAD

**Issue by PhieF** [electron-userland/electron-builder#3549]
* **Version**: 20.38.3
* **Target**: snap
Hi,

When trying to build a snap package come the error
```
⨯ at least snapcraft 2.40.0 is required, please: sudo snap install snapcraft --classic
```

of course snapcraft is installed and in version > 3.0

here is the complete log 
Hope you can find the source of the error, perhaps it comes from me but it appeared suddenly and I can't find why
I was thinking of a mistake in the version comparison when upgrading to > 3.0

```

• building        target=snap arch=x64 file=dist/Carnet_0.10.2_amd64.snap
  ⨯ at least snapcraft 2.40.0 is required, please: sudo snap install snapcraft --classic
Error: /home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at SnapTarget.build (/home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/targets/snap.ts:148:44)
    at Function.buildAsyncTargets (/home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at LinuxPackager.packageInDistributableFormat (/home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/platformPackager.ts:114:10
From previous event:
    at LinuxPackager.pack (/home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.doBuild (/home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/phie/Dev/GitBis/QuickDoc/CarnetNextcloud/templates/CarnetElectron/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
```

Thanks !

**Comment by shiftkey** [comment]
@PhieF I think you'll need to wait for a release containing this fix to appear: fb63683b7d133ced2a39b265680cddf1a0f50d50

**Comment by PhieF** [comment]
Seems to work, now... Perhaps when I've updated to electron v3

**Comment by Cyntaax** [comment]
I am still experiencing this issue on version 20.38.4. I'm not sure exactly what snapcraft is doing for the  default build process? Is it required to produce packaged for Linux? Is there a way around it? Literally same situation as the OP.

**Comment by tenfromfive** [comment]
@Cyntaax, I am having the same issue.  Do we have a way around this, or a way to easily revert snapcraft to 2.40.0 to see if that is the problem?

**Comment by shiftkey** [comment]
Please read over #3600 as I think there's been a packaging issue with the latest version of `electron-builder` that affects this bug.

**Comment by jmsv** [comment]
No longer getting this error after adding `-c.snap.publish=github` to my `electron-builder` command
