### ISSUE TITLE
Electron builder failing during packages on windows

### ISSUE THREAD

**Issue by flabbyThoroughbred** [electron-userland/electron-builder#3566]
Hello,
I'm having this issue on a windows 10 machine. This machine has built successfully multiple times. I'm not sure if it's been updated or not as I do not manage updates on it.
I should mention that this still works on my windows 7 machine. I don't think it's anything to do with my nsis configuration or the code itself.
Any thoughts?

Using:
electron 1.8.5
electron-builder 20.29.0
electron-updater 3.1.3
NSIS

Thanks!

```
> dashboard@1.0.7 dist c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client
> electron-builder

  • electron-builder version=20.29.0
  • artifacts will be published if draft release exists reason=CI detected
  • loaded configuration file=package.json ("build" field)
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.8.5 appOutDir=dist\win-unpacked
  • downloading               parts=6 size=50 MB url=https://github.com/electron/electron/releases/download/v1.8.5/electron-v1.8.5-win32-x64.zip
  • downloaded                duration=5.803s url=https://github.com/electron/electron/releases/download/v1.8.5/electron-v1.8.5-win32-x64.zip
Error: Exit code: ENOENT. spawn C:\WINDOWS\TEMP\electron-builder-cache\winCodeSign\winCodeSign-2.3.1\rcedit-x64.exe ENOENT
    at c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\builder-util\src\util.ts:128:16
    at exithandler (child_process.js:296:5)
    at ChildProcess.errorhandler (child_process.js:308:5)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.signAndEditResources (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\winPackager.ts:339:5)
    at _bluebirdLst.default.map.file (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\out\winPackager.js:609:25)
    at go$readdir$cb (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\graceful-fs\graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\winPackager.ts:367:7
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\winPackager.ts:390:9)
    at c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\platformPackager.ts:236:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.doPack (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\platformPackager.ts:166:165)
    at c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\platformPackager.ts:110:95)
    at c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\packager.ts:375:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager.doBuild (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\packager.ts:343:39)
    at c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\packager.ts:313:57
From previous event:
    at Packager._build (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\packager.ts:284:133)
    at c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\packager.ts:280:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\packager.ts:237:14)
    at build (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\electron-builder\src\builder.ts:227:10)
    at then (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Object.args [as handler] (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at Object.runCommand (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\yargs\yargs.js:1085:24)
    at Object.get [as argv] (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (c:\Gitlab-Runner\builds\38b5f22f\0\development\dashboard-client\node_modules\electron-builder\src\cli\cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dashboard@1.0.7 dist: `electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dashboard@1.0.7 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by flabbyThoroughbred** [comment]
I reset windows 10 and reinstalled gitlab. It all seems to work now.
Perhaps an automatic update created a conflict.
I created a snapshot of the vm it is on in case it occurs again.
Thanks!
