### ISSUE TITLE
The documentation on iconUrl config is unintuitive

### ISSUE THREAD

**Issue by serge1peshcoff** [electron-userland/electron-builder#3568]
* **Version**: 20.38.2

* **Target**: Windows

When I try to build an application and I don't set the `build.iconUrl` attribute, the building fails on Windows, saying (also it refers to non-existant HTML anchor):

```
• electron-builder version=20.38.2
  • loaded configuration file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=3.0.10 appOutDir=dist\win-unpacked
  • building        target=Squirrel.Windows arch=x64 file=dist\squirrel-windows\faceRecognition-0.0.1-x64.exe
iconUrl is not specified, please see https://electron.build/configuration/configuration#WinBuildOptions-iconUrl
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! face-recognition@0.0.1 dist:win: `electron-builder --win`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the face-recognition@0.0.1 dist:win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pc144\AppData\Roaming\npm-cache\_logs\2018-12-24T11_27_27_581Z-debug.log

Process finished with exit code 1
```

When I add the `build.iconUrl` attribute, it fails with this error:

```
Error: Configuration is invalid.
 - configuration has an unknown property 'iconUrl'. These properties are valid:
   object { afterAllArtifactBuild?, afterPack?, afterSign?, apk?, appId?, appImage?, appx?, artifactBuildCompleted?, artifactBuildStarted?, artifactName?, asar?, asarUnpack?, beforeBuild?, buildDependenciesFromSource?, buildVersion?, compression?, copyright?, cscKeyPassword?, cscLink?, deb?, detectUpdateChannel?, directories?, dmg?, electronCompile?, electronDist?, electronDownload?, electronUpdaterCompatibility?, electronVersion?, extends?, extraFiles?, extraMetadata?, extraResources?, fileAssociations?, files?, forceCodeSigning?, framework?, freebsd?, generateUpdatesFilesForAllChannels?, icon?, includePdb?, launchUiVersion?, linux?, mac?, mas?, msi?, muonVersion?, nodeGypRebuild?, nodeVersion?, npmArgs?, npmRebuild?, npmSkipBuildFromSource?, nsis?, nsisWeb?, onNodeModuleFile?, p5p?, pacman?, pkg?, portable?, productName?, protocols?, protonNodeVersion?, publish?, readonly?, releaseInfo?, remoteBuild?, removePackageScripts?, rpm?, snap?, squirrelWindows?, target?, win? }
   Configuration Options


How to fix:
1. Open https://electron.build/configuration/configuration
2. Search the option name on the page.
  * Not found? The option was deprecated or not exists (check spelling).
  * Found? Check that the option in the appropriate place. e.g. "title" only in the "dmg", not in the root.

    at validateConfig (D:\electron\face-recognition\node_modules\read-config-file\src\main.ts:133:19)
From previous event:
    at _validateConfig2 (D:\electron\face-recognition\node_modules\app-builder-lib\out\util\config.js:339:27)
    at validateConfig (D:\electron\face-recognition\node_modules\app-builder-lib\out\util\config.js:302:27)
    at D:\electron\face-recognition\node_modules\app-builder-lib\src\packager.ts:336:11
    at Generator.next (<anonymous>)
From previous event:
    at Packager._build (D:\electron\face-recognition\node_modules\app-builder-lib\src\packager.ts:335:133)
    at D:\electron\face-recognition\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (D:\electron\face-recognition\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (D:\electron\face-recognition\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (D:\electron\face-recognition\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\electron\face-recognition\node_modules\electron-builder\src\cli\cli.ts:46:19)
```

The only thing that worked for me was setting `squirrelWindows.iconUrl`, like in this case (not providing full package.json because NDA):

```
{
  "build": {
    "artifactName": "${productName}-${version}-${arch}.${ext}",
    "appImage": {
      "systemIntegration": "doNotAsk"
    },
    "squirrelWindows": {
      "iconUrl": "https://path/to/valid/image.png"
    },
    "linux": {
      "target": "AppImage"
    },
    "win": {
      "target": "squirrel"
    }
  }
}
```

I've spent 1 hour figuring this out. For me it's okay, but can you make it more obvious for other people? And also update the documentation so it won't mislead others.

Thanks for the response!

**Comment by AddoSolutions** [comment]
I am having the exact same issue.  Interestingly, I built it once, without iconUrl specified at all and it worked fine. Then I added `build.win.iconUrl`, it whined about being invalid, but when I removed it I could not get it to build again and spent an hour until I found this article as well.  This smells like a bug.
