### ISSUE TITLE
Failing in build for windows from mac with puppeteer dependency

### ISSUE THREAD

**Issue by CQBinh** [electron-userland/electron-builder#3592]
* **Version**: ^20.38.4

* **electron-updater**: ^4.0.6

* **Target**: windows

I use the `puppeteer` package. In dev mode, it works like charm, but when packaging for windows, I meet the error: 
```
error output:wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
Z:\Users\binh\Documents\Development\electron\Fx\release\__msi-x64\project.wxs(462) : error LGHT0103 : The system cannot find the file 'Z:\Users\binh\Documents\Development\electron\Fx\release\win-unpacked/resources/app.asar.unpacked/node_modules/puppeteer/.local-chromium/mac-609904/chrome-mac/Chromium.app/Contents/Versions/72.0.3617.0/Chromium Framework.framework/Helpers'.

github.com/develar/app-builder/pkg/util.Execute
	/Volumes/data/Documents/app-builder/pkg/util/util.go:75
github.com/develar/app-builder/pkg/wine.execWine
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:75
github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:43
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:78
runtime.main
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/proc.go:201
runtime.goexit
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:1333

  • building block map blockMapFile=release/ElectronReact Setup 0.17.1.exe.blockmap
Error: /Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-bin/mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/binh/Documents/Development/electron/Fx/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at MsiTarget.light (/Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/targets/MsiTarget.ts:105:142)
    at /Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/targets/MsiTarget.ts:89:16
From previous event:
    at MsiTarget.build (/Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/targets/MsiTarget.ts:43:44)
    at Function.buildAsyncTargets (/Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at WinPackager.packageInDistributableFormat (/Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at WinPackager.pack (/Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/binh/Documents/Development/electron/Fx/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/binh/Documents/Development/electron/Fx/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/binh/Documents/Development/electron/Fx/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/binh/Documents/Development/electron/Fx/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/binh/Documents/Development/electron/Fx/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/binh/Documents/Development/electron/Fx/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/binh/Documents/Development/electron/Fx/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
error Command failed with exit code 1.
```
When I remove `puppeteer`, the build process work, but my application can't using `puppeteer` anymore.
My environment:
```
- Host: Mac OS 10.14
- node: v8.12.0
- puppeteer: ^1.11.0
- electron-builder: ^20.38.4
```

* Packaging for mac os is ok.
* Packaging from windows is ok too.

**Comment by twigs67** [comment]
@CQBinh did you ever get this working?

**Comment by diephil** [comment]
@CQBinh I would be interested in the solution of this too!
