### ISSUE TITLE
open /Volumes/My App/.VolumeIcon.icns: no space left on device

### ISSUE THREAD

**Issue by VikramTiwari** [electron-userland/electron-builder#3595]
* **Version**: ^20.26.0

* **Target**: OSX

I am getting the `no space left on device` error while trying to package my app for OSX. It was packaging just fine beforehand. The changes to code are unrelated as they were purely CSS changes in the app code.

```
  • building        target=DMG arch=x64 file=release/MYAPP-0.0.1.dmg
  ⨯ open /Volumes/MYAPP 0.0.1/.VolumeIcon.icns: no space left on device
github.com/develar/go-fs-util.open
	/Volumes/data/go/pkg/mod/github.com/develar/go-fs-util@v2.0.1-0.20181113101504-f6630ccc0e93+incompatible/fs.go:22
github.com/develar/go-fs-util.WriteFile
	/Volumes/data/go/pkg/mod/github.com/develar/go-fs-util@v2.0.1-0.20181113101504-f6630ccc0e93+incompatible/fs.go:50
github.com/develar/go-fs-util.CopyFile
	/Volumes/data/go/pkg/mod/github.com/develar/go-fs-util@v2.0.1-0.20181113101504-f6630ccc0e93+incompatible/fs.go:45
github.com/develar/app-builder/pkg/fs.(*FileCopier).CopyFile
	/Volumes/data/Documents/app-builder/pkg/fs/copier.go:128
github.com/develar/app-builder/pkg/fs.(*FileCopier).copyDirOrFile
	/Volumes/data/Documents/app-builder/pkg/fs/copier.go:102
github.com/develar/app-builder/pkg/fs.(*FileCopier).CopyDirOrFile
	/Volumes/data/Documents/app-builder/pkg/fs/copier.go:60
github.com/develar/app-builder/pkg/fs.CopyDirOrFile
	/Volumes/data/Documents/app-builder/pkg/fs/copier.go:46
github.com/develar/app-builder/pkg/package-format/dmg.BuildDmg
	/Volumes/data/Documents/app-builder/pkg/package-format/dmg/dmg.go:41
github.com/develar/app-builder/pkg/package-format/dmg.ConfigureCommand.func1
	/Volumes/data/Documents/app-builder/pkg/package-format/dmg/dmg.go:28
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:78
runtime.main
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/proc.go:201
runtime.goexit
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:1333

  • building embedded block map file=release/MYAPP-0.0.1-mac.zip
Error: /Users/vikram/Documents/code/my-app/node_modules/app-builder-bin/mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/vikram/Documents/code/my-app/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
From previous event:
    at _customizeDmg (/Users/vikram/Documents/code/my-app/node_modules/dmg-builder/out/dmg.js:455:24)
    at customizeDmg (/Users/vikram/Documents/code/my-app/node_modules/dmg-builder/out/dmg.js:399:24)
    at /Users/vikram/Documents/code/my-app/node_modules/dmg-builder/src/dmg.ts:48:54
    at /Users/vikram/Documents/code/my-app/node_modules/dmg-builder/src/dmgUtil.ts:37:31
From previous event:
    at _attachAndExecute (/Users/vikram/Documents/code/my-app/node_modules/dmg-builder/out/dmgUtil.js:120:28)
    at attachAndExecute (/Users/vikram/Documents/code/my-app/node_modules/dmg-builder/out/dmgUtil.js:97:28)
    at /Users/vikram/Documents/code/my-app/node_modules/dmg-builder/src/dmg.ts:48:16
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Users/vikram/Documents/code/my-app/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at nonMasPromise.then.then (/Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/macPackager.ts:90:26)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at /Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/vikram/Documents/code/my-app/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/vikram/Documents/code/my-app/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/vikram/Documents/code/my-app/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/vikram/Documents/code/my-app/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/vikram/Documents/code/my-app/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/vikram/Documents/code/my-app/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/vikram/Documents/code/my-app/node_modules/electron-builder/src/cli/cli.ts:46:19)
error Command failed with exit code 1.
```

**Comment by VikramTiwari** [comment]
Confirming that package is latest. Excerpt from `yarn.lock`

```
electron-builder@^20.26.0:
  version "20.38.4"
  resolved "https://registry.yarnpkg.com/electron-builder/-/electron-builder-20.38.4.tgz#67727529ffb87e7fdd78b3a84ea0d6c22bf04ec2"
  integrity sha512-WHOr3Rz2wktxV5TqmRL6woO9/wrIZeRfJPSEXOhgfgLskE5Sp2Aer0zAF7lHNqXuG6JhU+0I9IYFAxa73MTs9w==
  dependencies:
    app-builder-lib "20.38.4"
    bluebird-lst "^1.0.6"
    builder-util "9.6.1"
    builder-util-runtime "8.1.0"
    chalk "^2.4.1"
    dmg-builder "6.5.3"
    fs-extra-p "^7.0.0"
    is-ci "^2.0.0"
    lazy-val "^1.0.3"
    read-config-file "3.2.0"
    sanitize-filename "^1.6.1"
    update-notifier "^2.5.0"
    yargs "^12.0.5"

```

**Comment by VikramTiwari** [comment]
Similar to https://github.com/electron-userland/electron-builder/issues/821 and https://github.com/electron-userland/electron-builder/issues/3301. Also, confirming that I don't have a `icon` field in my `package.json`.
