### ISSUE TITLE
Cannot build app with 3.6.2+

### ISSUE THREAD

**Issue by Vj3k0** [electron-userland/electron-builder#360]
When I try to create app for Mac, it fails on 7zip. Here is the relevant part:

```
Signing app
Creating DMG
Creating ZIP for Squirrel.Mac

WARNING: No more files
myapp.app

Error: /Users/vjeko/dev/myapp/node_modules/7zip-bin-osx/7za exited with code 1
    at ChildProcess.<anonymous> (/Users/vjeko/dev/myapp/node_modules/electron-builder/src/util.ts:95:69)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at Object.spawn (/Users/vjeko/dev/myapp/node_modules/electron-builder/src/util.ts:93:10)
    at MacPackager.zipMacApp (/Users/vjeko/dev/myapp/node_modules/electron-builder/src/macPackager.ts:118:17)
    at MacPackager.packageInDistributableFormat (/Users/vjeko/dev/myapp/node_modules/electron-builder/src/macPackager.ts:101:12)
    at Packager.<anonymous> (/Users/vjeko/dev/myapp/node_modules/electron-builder/src/packager.ts:79:33)
From previous event:
    at tsAwaiter (/Users/vjeko/dev/myapp/node_modules/electron-builder/src/awaiter.ts:10:51)
    at Object.build (/Users/vjeko/dev/myapp/node_modules/electron-builder/src/builder.ts:30:59)
    at Object.<anonymous> (/Users/vjeko/dev/myapp/node_modules/electron-builder/src/build-cli.ts:41:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
[17:24:43] 'dist:osx' errored after 8.52 s
[17:24:43] Error: Command `node_modules/.bin/build  --appDir out -d --platform darwin` failed with exit code 255
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

And here is package.json part:

```
"build": {
    "name": "myapp",
    "productName": "MyApp",
    "app-bundle-id": "hr.creaticon.myapp",
    "app-category-type": "public.app-category.productivity",
    "iconUrl": "http://update.creaticon.com.s3.amazonaws.com/myapp/installer/icon.ico",
    "osx": {
      "title": "myapp",
      "background": "build/background.png",
      "icon": "build/icon.icns",
      "icon-size": 128,
      "contents": [
        {
          "x": 355,
          "y": 125,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 155,
          "y": 125,
          "type": "file"
        }
      ]
    },
    "win": {
    }
  }
```

On 3.6.1 or versions before that I don't have this issue and can build it normally.

Any ideas?

**Comment by develar** [comment]
I will add debug log to investigate.

**Comment by develar** [comment]
Please try 3.13.0. Set `DEBUG=electron-buider` env to get debug logs.

**Comment by Vj3k0** [comment]
Hey Vladimir, thanks for your effort.

I defined productName as "MyApp" and name was "myapp". This caused to create myapp.app file, but electron-builder sent to appdmg path as "..../MyApp.app" in contents property.

In the end, I've fixed this by having same productName and name props, but is this a bug?

**Comment by develar** [comment]
>  is this a bug?
Yes. Will be fixed. Thanks for explanation.
