### ISSUE TITLE
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-electron-v4.0-win32-x64.tar.gz 

### ISSUE THREAD

**Issue by hugetiny** [electron-userland/electron-builder#3618]
I try to publish win on Mac 10.13.6 but got failed
* **Version**: 
node:10.15.0
electron:4.0.1
electron-builder=latest

* **Target**: 
win

```
Error: npm exited with code 1
Output:

> fsevents@1.2.7 install /Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents
> node install

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
Failed to execute '/Users/zhangzhechong/.nvm/versions/node/v10.15.0/bin/node /Users/zhangzhechong/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents/lib/binding/Release/electron-v4.0-win32-x64/fse.node --module_name=fse --module_path=/Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents/lib/binding/Release/electron-v4.0-win32-x64 --napi_version=3 --node_abi_napi=napi' (1)
  COPY /Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents/lib/binding/Release/electron-v4.0-win32-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-electron-v4.0-win32-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and electron@4.0.1 (electron-v4.0 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and electron@4.0.1 (electron-v4.0 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/zhangzhechong/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/zhangzhechong/.nvm/versions/node/v10.15.0/bin/node" "/Users/zhangzhechong/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents/lib/binding/Release/electron-v4.0-win32-x64/fse.node" "--module_name=fse" "--module_path=/Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents/lib/binding/Release/electron-v4.0-win32-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/zhangzhechong/.nvm/versions/node/v10.15.0/bin/node /Users/zhangzhechong/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents/lib/binding/Release/electron-v4.0-win32-x64/fse.node --module_name=fse --module_path=/Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents/lib/binding/Release/electron-v4.0-win32-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/zhangzhechong/.nvm/versions/node/v10.15.0/bin/node" "/Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/zhangzhechong/WebstormProjects/webox/node_modules/fsevents
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fsevents@1.2.7 install: `node install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.2.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/CoreServices are out of sync. Falling back to library file for linking.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangzhechong/.npm/_logs/2019-01-20T15_08_51_254Z-debug.log
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.

    at ChildProcess.childProcess.once.code (/Users/zhangzhechong/WebstormProjects/webox/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
From previous event:
    at _rebuild (/Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/src/util/yarn.ts:179:5)
    at rebuild (/Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/out/util/yarn.js:163:19)
    at /Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/src/util/yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at _installOrRebuild (/Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/out/util/yarn.js:71:28)
    at installOrRebuild (/Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/out/util/yarn.js:55:28)
    at /Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/src/packager.ts:511:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/src/packager.ts:472:70)
    at /Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/src/packager.ts:420:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/zhangzhechong/WebstormProjects/webox/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/zhangzhechong/WebstormProjects/webox/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/zhangzhechong/WebstormProjects/webox/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/zhangzhechong/WebstormProjects/webox/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/zhangzhechong/WebstormProjects/webox/node_modules/electron-builder/src/cli/cli.ts:46:19)

```

**Comment by hugetiny** [comment]
I checked the download address.It's not available.
The available binary should be:
https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-**node-vxx**-win32-x64.tar.gz

**Comment by Technickster** [comment]
I have the same issue. I cant find where it is setting electron as the platform instead of node to try fix it

**Comment by andrenoberto** [comment]
This is also happening with me.

**Comment by nwittwer** [comment]
Getting this issue as well, specifically through the `electron-builder install-app-deps` script.

Node: 10.15.0
Electron: ^4.0.3
Electron-builder: ^20.38.5

**Comment by patrickmichalina** [comment]
Same issue here trying to fetch `https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-electron-v4.0-darwin-x64.tar.gz`

**Comment by pihyper** [comment]
As mentioned here, https://github.com/electron-userland/electron-builder/issues/3671#issuecomment-466137111

running 

`npm i --save-dev node@8.15.0`

and then building, got me through without errors. It worked for me anyways, without being have to switch to yarn.

**Comment by nickensoul** [comment]
Any news about this?

**Comment by artdiniz** [comment]
I stumbled upon this error when running `electron-builder` after updating node from 8 to 12.

Removing `node_modules` and re-executing `npm install` got everything up and running again 👍

**Comment by wendellpereira** [comment]
Looks like there is some version with the wrong or outdated url for the fsevents binaries:

`Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-electron-v4.0-win32-x64.tar.gz`

For me worked simply deleting package-lock-old.json and run `npm install`.

**Comment by develar** [comment]
Please try 21.0.5.

**Comment by dijs** [comment]
I just tried v21.0.5. Still seeing the same exact error.

**Comment by cemretok** [comment]
Just try to delete package-lock.json then try it again.

**Comment by EmadAdly** [comment]
Remove existing node_modules/

```rm -r node_modules```

Remove the existing `package-json.lock`

```rm package-json.lock```

And then reinstalling

```npm install```

**Comment by JerryCjr** [comment]
> Looks like there is some version with the wrong or outdated url for the fsevents binaries:
> 
> `Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-electron-v4.0-win32-x64.tar.gz`
> 
> For me worked simply deleting package-lock-old.json and run `npm install`. Or in case it's yarn, `yarn remove` and `yarn add` for packages that uses fsevents.

it worker for me
