### ISSUE TITLE
Broken auto-updates on macOS

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#3657]
* **Version**: 
"electron-builder": "20.28.3",
"electron-updater": "3.1.2"

* **Target**: 
macOS

```sh
[2019-01-31 19:28:45.716] [info] Checking for update
[2019-01-31 19:28:45.838] [info] Generated new staging user ID: 79aa6fb2-2931-515a-9878-ab67ad5a5d2d
[2019-01-31 19:28:48.914] [info] Found version 2.4.0 (url: Zulipelectron-2.4.0.zip, Zulipelectron-2.4.0.dmg)
[2019-01-31 19:28:48.915] [info] Downloading update from Zulipelectron-2.4.0.zip, Zulipelectron-2.4.0.dmg
[2019-01-31 19:28:48.932] [info] No cached update info available
[2019-01-31 19:30:42.387] [info] New version 2.4.0 has been downloaded to /Users/akka/Library/Application Support/Zulipelectron/__update__/Zulipelectron-2.4.0.zip
[2019-01-31 19:30:47.884] [info] / requested
[2019-01-31 19:30:47.894] [info] /app.zip requested
[2019-01-31 19:30:47.895] [info] app.zip requested by Squirrel.Mac, pipe /Users/akka/Library/Application Support/Zulipelectron/__update__/Zulipelectron-2.4.0.zip
[2019-01-31 19:30:48.925] [warn] Error: No update available, can't quit and install
    at Timeout.setTimeout (/Applications/Zulipelectron.app/Contents/Resources/app.asar/main/autoupdater.js:101:10)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

[2019-01-31 19:30:48.926] [error] Error: Error: No update available, can't quit and install
    at Timeout.setTimeout (/Applications/Zulipelectron.app/Contents/Resources/app.asar/main/autoupdater.js:101:10)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

Reproduce using -
* Download - https://github.com/akashnimare/zulip-electron-test/releases/download/v2.3.82/Zulipelectron-2.3.82.dmg
* Install and run the app
* After some time the update dialog will pop up
* If you select **install now** then the app will quit and the updates will not be applied
* If you select the **install later** and quit the app the updates do get installed

**Comment by tzarebczan** [comment]
@akashnimare does it update on close? I'm seeing something similar on Windows, and it does work on close.

**Comment by popod** [comment]
@akashnimare Have you resolve this problem ?
