### ISSUE TITLE
Build fails after specifying stagePackages for snap

### ISSUE THREAD

**Issue by johannesjo** [electron-userland/electron-builder#3677]
* **Version**: 20.38.5
* **Target**: linux snap

As soon as I specify a custom dependency for snap the build fails with a non helpful error message. Have a look here for a full build log: https://travis-ci.org/johannesjo/super-productivity/jobs/491217854
```
// this works
"stagePackages": [
        "default"
]
// this doesn't no matter what else i put in
"stagePackages": [
        "default",
        "xprintidle"
]
```

The error message is this:
```
Error: /project/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/project/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:276:13)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
From previous event:
    at processImmediate (timers.js:632:19)
From previous event:
    at SnapTarget.build (/project/node_modules/app-builder-lib/src/targets/snap.ts:148:44)
    at Function.buildAsyncTargets (/project/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at /project/node_modules/app-builder-lib/src/platformPackager.ts:126:24
    at Generator.next (<anonymous>)
From previous event:
    at AsyncTaskManager.add (/project/node_modules/builder-util/src/asyncTaskManager.ts:14:20)
    at LinuxPackager.packageInDistributableFormat (/project/node_modules/app-builder-lib/src/platformPackager.ts:123:17)
    at /project/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at LinuxPackager.pack (/project/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /project/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/project/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqCallback.args [as oncomplete] (fs.js:147:20)
From previous event:
    at Packager.doBuild (/project/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /project/node_modules/app-builder-lib/src/packager.ts:366:57
From previous event:
    at Packager._build (/project/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /project/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/project/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/project/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/project/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/project/node_modules/electron-builder/src/cli/cli.ts:46:19)
```

Probably some missconfiguration on my end. But having a more helpful error message would be great!

**Comment by develar** [comment]
20.434.0 supports [multipass](https://github.com/CanonicalLtd/multipass).
