### ISSUE TITLE
EPERM error on windows during update process

### ISSUE THREAD

**Issue by scottnonnenberg-signal** [electron-userland/electron-builder#3681]
* **Version**: 
  electron-builder v20.38.5
  electron-updater v4.0.6
  https://github.com/signalapp/Signal-Desktop/blob/development/package.json#L116

* **Target**: 
macOS

We've had quite a few of our users run into this, a new issue appearing with a recent upgrade of Electron Builder/Updater. Maybe the file isn't fully downloaded and closed before we try to do something with it?

It seems to happen before the prompt is shown asking the user to update - you can see our update code here:

- Checking for new version: https://github.com/signalapp/Signal-Desktop/blob/84bb9be6a9c8bcd520301cc0220f4b7109cb0923/app/auto_update.js#L21-L27
- Listening for 'update-downloaded' event: https://github.com/signalapp/Signal-Desktop/blob/84bb9be6a9c8bcd520301cc0220f4b7109cb0923/app/auto_update.js#L77-L79
- Kicking off the upgrade with the downloaded file: https://github.com/signalapp/Signal-Desktop/blob/84bb9be6a9c8bcd520301cc0220f4b7109cb0923/app/auto_update.js#L49-L58

The callstack looks like this: 

```
Unhandled Promise Rejection
Error: EPERM: operation not permitted, open 'C:\Users\XXX\AppData\Local\signal-desktop-beta-updater\pending\temp-signal-desktop-beta-win-1.21.0-beta.4.exe'
    at ElectronHttpExecutor.download (C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\node_modules\electron-updater\src\electronHttpExecutor.ts:23:73)
    at Object.<anonymous> (C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:35:35)
From previous event:
    at Object.task (C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:31:11)
    at C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:610:25
From previous event:
    at NsisUpdater.executeDownload (C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:545:68)
    at NsisUpdater.executeDownload (C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:27:18)
    at NsisUpdater.doDownloadUpdate (C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:27:17)
    at NsisUpdater.downloadUpdate (C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:420:19)
    at C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:383:49
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at Timeout.checkForUpdates [as _onTimeout] (C:\Users\XXX\AppData\Local\Programs\signal-desktop-beta\resources\app.asar\app\auto_update.js:22:15)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

Original bug: https://github.com/signalapp/Signal-Desktop/issues/3106

**Comment by liayn** [comment]
Signal bug mentioned above also happened on Windows for me.

**Comment by gimdongwoo** [comment]
Any updates?

**Comment by gimdongwoo** [comment]
It needs to set `autoDownload = false`, when using `downloadUpdate`.

**Comment by thomasnordquist** [comment]
Ran into the same issue for Mac auto updates.

**Comment by ShawnKuan** [comment]
I still have this issue, "[2021-02-19 10:39:17.858] [warn] auto updater error -- real Error: EPERM: operation not permitted,"
does anyone have a solution?

**Comment by anserwaseem** [comment]
> I still have this issue, when I cancelled my current update, and re-update again, I got "[2021-02-19 10:39:17.858] [warn] auto updater error -- real Error: EPERM: operation not permitted," does anyone have a solution?
> 
> Update: during 2 days, i found the solution. thanks to @StaZhu, I forked the repo and use his changes. It works!
> 
> It seems like electron-builder team has no longer maintain the framework anymore

kindly share the solution so others can take benefit, thanks.

**Comment by dingshaohua-com** [comment]
same to your err in mas,but i is nomal in dmg
<img width="899" alt="img_v3_02i3_c3ca05cc-025c-4a0a-9efe-0e111b22836g" src="https://github.com/user-attachments/assets/c5662e4b-8f2d-433e-a6cf-111c5aa903f3" />

**Comment by EkkoCrystal** [comment]
I still have this issue
