### ISSUE TITLE
NSPOSIXErrorDomain 13. Could not create temporary directory: Permission denied

### ISSUE THREAD

**Issue by ccorcos** [electron-userland/electron-builder#3686]
* **Version**: 3.2.3

- Cant upgrade because we're still running electron 2.0.5

* **Target**: Mac

I'm seeing a lot of these errors:

```
error:
code:13
domain:NSPOSIXErrorDomain
message:Could not create temporary directory: Permission denied
name:Error
stack:Error: Could not create temporary directory: Permission denied
    at Object.done (/Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:191:25)
    at /Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:724:29
    at Generator.next (<anonymous>)
From previous event:
    at done (/Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:729:23)
    at /Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:738:22
From previous event:
    at MacUpdater.executeDownload (/Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:788:7)
    at /Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:110:26
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:195:7)
    at /Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:575:29
From previous event:
    at MacUpdater.downloadUpdate (/Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:585:7)
    at /Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:542:55
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:544:7)
    at /Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:437:29
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:443:7)
    at MacUpdater.checkForUpdates (/Applications/Notion.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:355:35)
    at /Applications/Notion.app/Contents/src/desktop/main/autoUpdater.ts:105:23
    at step (/Applications/Notion.app/Contents/Resources/app.asar/main/autoUpdater.js:32:23)
    at Object.next (/Applications/Notion.app/Contents/Resources/app.asar/main/autoUpdater.js:13:53)
    at fulfilled (/Applications/Notion.app/Contents/Resources/app.asar/main/autoUpdater.js:4:58)
    at <anonymous>
```

**Comment by ccorcos** [comment]
Its that reject statement here which isnt too useful:

```
            server.listen(0, "127.0.0.1", () => {
              _this.nativeUpdater.setFeedURL({
                url: getServerUrl(),
                headers: {
                  "Cache-Control": "no-cache"
                }
              });

              _this.nativeUpdater.once("error", reject);

              _this.nativeUpdater.checkForUpdates();
            });
```
