### ISSUE TITLE
Can't include shared libraries.

### ISSUE THREAD

**Issue by thegergo02** [electron-userland/electron-builder#3693]
* **Version**: 20.38.5 

* **Target**: Linux x64 AppImage

Some of my users are experiencing this error: 
```
Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-10275/resources/app.asar/node_modules/keytar/lib/keytar.js:1:169)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-10275/resources/app.asar/node_modules/keytar/lib/keytar.js:61:3)
```
How can I include shared libraries?

* **Host**: Linux Mint Tara 19 x64
* **Node version**: v8.10.0
* **NPM version**: 3.5.2
* **package.json**: 
```
{
  "name": "gkreta",
  "version": "0.7.0",
  "description": "It's an application for displaying your informations from the KRÉTA systems. (Written in Electron)",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "postinstall": "electron-rebuild",
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "dist:linux": "electron-builder --linux appimage",
    "dist:win": "electron-builder --win"
  },
  "author": "thegergo02",
  "license": "GPL-3.0",
  "dependencies": {
    "keytar": "^4.4.0"
  },
  "devDependencies": {
    "electron": "^4.0.4",
    "electron-builder": "^20.38.5",
    "electron-rebuild": "^1.8.4"
  },
  "build": {
    "appId": "thegergo02.gkreta",
    "productName": "gKreta",
    "artifactName": "${productName}.${ext}",
    "copyright": "Copyright © 2019 Gergő Vári",
    "directories": {
      "buildResources": "build",
      "output": "dist"
    },
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": "x64"
        }
      ]
    },
    "nsis": {
      "oneClick": false,
      "perMachine": false,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true
    },
    "mac": {
      "target": "dmg",
      "category": "public.app-category.education"
    },
    "linux": {
      "target": "AppImage",
      "maintainer": "thegergo02",
      "vendor": "gKreta",
      "synopsis": "Based on Electron, a replacement for KRÉTA's web interface.",
      "description": "Based on Electron, this is a replacement for KRÉTA's web interface.",
      "category": "Education"
    },
    "deb": {
      "compression": "xz",
      "packageCategory": "Education",
      "priority": "optional"
    },
    "compression": "maximum",
    "files": [
      "!{dist,.gitignore,.github,.conf,dist}"
    ],
    "extraResources": [
      "libraries"
    ],
    "asar": true
  }
}
```

**Comment by probonopd** [comment]
Maybe related to https://github.com/electron-userland/electron-builder/issues/2732

**Comment by probonopd** [comment]
Not doing anything is never a good reason to close tickets in my humble opinion. So I don't know what good this bot is supposed to be doing.

**Comment by probonopd** [comment]
Not doing anything is never a good reason to close tickets in my humble opinion. So I don't know what good this bot is supposed to be doing.
