### ISSUE TITLE
Windows 10 update isn't working due to new version  is not signed by the application owner

### ISSUE THREAD

**Issue by mttv** [electron-userland/electron-builder#3714]
* **Version**: 20.27.1

NSIS

* **Target**: NSIS

Hello! Recently, people who use my application on Windows 10 have their auto update stopped working, for a couple of days I could not figure out what could be the problem until the update logs had an error that there was no signature certificate. There are no problems with updating on windows 7 and there were no problems with windows 10 until this couple of days.

**Build conf**:

`"gh-publish": "yarn electron-builder --ia32 --win -p always && node_modules/.bin/build"`

`"build": {
    "publish": [
      {
        "provider": "github",
        "owner": "mttv",
        "repo": "mttv-app"
      }
    ],
    "win": {
      "target": [
        "nsis"
      ],
      "icon": "build/icon.ico",
      "publisherName": "webifua"
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "deleteAppDataOnUninstall": true,
      "createDesktopShortcut": true,
      "installerIcon": "build/icon.ico",
      "uninstallerIcon": "build/icon.ico",
      "uninstallDisplayName": "Uninstall MTTV"
    },
    "productName": "MTTV",
    "appId": "com.mttv.app",
    "extends": null,
    "electronVersion": "3.0.0",
    "buildVersion": "0.2.7",
    "copyright": "webifua 2019",
    "files": [
      "build/**/*",
      "electron/**/*"
    ]
  }`

**Log:**
[2019-02-25 21:51:59.464] [info] App starting...
[2019-02-25 21:52:05.544] [info] Checking for update
[2019-02-25 21:52:05.616] [info] Checking for update...
[2019-02-25 21:52:05.769] [info] Generated new staging user ID: a488db7d-724c-53fa-9c43-b811a945aa9f
[2019-02-25 21:52:07.857] [info] Found version 0.2.7 (url: mttv-setup-0.2.7.exe)
[2019-02-25 21:52:10.886] [info] Downloading update from mttv-setup-0.2.7.exe
[2019-02-25 21:52:10.915] [info] No cached update info available
[2019-02-25 21:52:10.919] [info] Download block maps (old: "https://github.com/mttv/mttv-app/releases/download/v0.2.5/mttv-setup-0.2.5.exe.blockmap", new: https://github.com/mttv/mttv-app/releases/download/v0.2.7/mttv-setup-0.2.7.exe.blockmap)
[2019-02-25 21:52:11.881] [info] File has 1493 changed blocks
[2019-02-25 21:52:11.886] [info] Full: 62,513.36 KB, To download: 30,412.29 KB (49%)
[2019-02-25 21:52:11.893] [info] Differential download: https://github.com/mttv/mttv-app/releases/download/v0.2.7/mttv-setup-0.2.7.exe
[2019-02-25 21:52:12.109] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/168543775/f86c9080-3942-11e9-9b2f-242515d08d36
[2019-02-25 22:16:52.989] [info] App starting...
[2019-02-25 22:16:57.638] [info] Checking for update
[2019-02-25 22:16:57.716] [info] Checking for update...
[2019-02-25 22:17:00.451] [info] Found version 0.2.7 (url: mttv-setup-0.2.7.exe)
[2019-02-25 22:17:02.723] [info] Downloading update from mttv-setup-0.2.7.exe
[2019-02-25 22:17:02.752] [info] No cached update info available
[2019-02-25 22:17:02.758] [info] Download block maps (old: "https://github.com/mttv/mttv-app/releases/download/v0.2.5/mttv-setup-0.2.5.exe.blockmap", new: https://github.com/mttv/mttv-app/releases/download/v0.2.7/mttv-setup-0.2.7.exe.blockmap)
[2019-02-25 22:17:03.725] [info] File has 1493 changed blocks
[2019-02-25 22:17:03.730] [info] Full: 62,513.36 KB, To download: 30,412.29 KB (49%)
[2019-02-25 22:17:03.754] [info] Differential download: https://github.com/mttv/mttv-app/releases/download/v0.2.7/mttv-setup-0.2.7.exe
[2019-02-25 22:17:03.971] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/168543775/f86c9080-3942-11e9-9b2f-242515d08d36
[2019-02-25 22:17:41.781] [warn] Sign verification failed, installer signed with incorrect certificate: publisherNames: webifua, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\Admin\\AppData\\Local\\mttv-updater\\pending\\temp-mttv-setup-0.2.7.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
[2019-02-25 22:17:41.801] [error] Error: Error: New version 0.2.7 is not signed by the application owner: publisherNames: webifua, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\Admin\\AppData\\Local\\mttv-updater\\pending\\temp-mttv-setup-0.2.7.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
    at newError (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\builder-util-runtime\src\index.ts:29:17)
    at Object.<anonymous> (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:42:17)
From previous event:
    at Object.task (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:31:11)
    at C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:610:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at NsisUpdater.executeDownload (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:545:68)
    at NsisUpdater.executeDownload (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:27:18)
    at NsisUpdater.doDownloadUpdate (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:27:17)
    at NsisUpdater.downloadUpdate (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:420:19)
    at BrowserWindow.appUpdateWin.on (C:\Program Files (x86)\MTTV\resources\app.asar\electron\main.js:600:25)
    at BrowserWindow.emit (events.js:182:13)
[2019-02-25 22:17:41.802] [info] Error in auto-updater. Error: New version 0.2.7 is not signed by the application owner: publisherNames: webifua, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\Admin\\AppData\\Local\\mttv-updater\\pending\\temp-mttv-setup-0.2.7.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}

**Comment by mttv** [comment]
I've managed somehow to make app update, but it still doesnt show download progress.

**Windows 10 log:**
[2019-02-26 15:18:29.802] [info] App starting...
[2019-02-26 15:18:36.041] [info] Checking for update
[2019-02-26 15:18:36.114] [info] Checking for update...
[2019-02-26 15:18:36.260] [info] Generated new staging user ID: 586f30fb-dd63-5cff-8359-25c6a892ff9b
[2019-02-26 15:18:38.324] [info] Found version 0.2.9 (url: mttv-setup-0.2.9.exe)
[2019-02-26 15:18:39.408] [info] Downloading update from mttv-setup-0.2.9.exe
[2019-02-26 15:18:39.444] [info] No cached update info available
[2019-02-26 15:18:39.448] [info] Download block maps (old: "https://github.com/mttv/mttv-app/releases/download/v0.2.8/mttv-setup-0.2.8.exe.blockmap", new: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe.blockmap)
[2019-02-26 15:18:40.188] [info] Downloading update from mttv-setup-0.2.9.exe
[2019-02-26 15:18:40.197] [info] No cached update info available
[2019-02-26 15:18:40.201] [info] Download block maps (old: "https://github.com/mttv/mttv-app/releases/download/v0.2.8/mttv-setup-0.2.8.exe.blockmap", new: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe.blockmap)
[2019-02-26 15:18:40.533] [info] File has 162 changed blocks
[2019-02-26 15:18:40.537] [info] Full: 62,513.62 KB, To download: 3,365.21 KB (5%)
[2019-02-26 15:18:40.545] [info] Differential download: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe
[2019-02-26 15:18:40.808] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/168543775/c9542e80-39d7-11e9-83eb-b15a493706f3
[2019-02-26 15:18:40.922] [info] File has 162 changed blocks
[2019-02-26 15:18:40.923] [info] Full: 62,513.62 KB, To download: 3,365.21 KB (5%)
[2019-02-26 15:18:40.925] [info] Differential download: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe
[2019-02-26 15:18:41.217] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/168543775/c9542e80-39d7-11e9-83eb-b15a493706f3
[2019-02-26 15:18:53.861] [warn] Sign verification failed, installer signed with incorrect certificate: publisherNames: webifua, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\Admin\\AppData\\Local\\mttv-updater\\pending\\temp-mttv-setup-0.2.9.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
[2019-02-26 15:18:53.866] [warn] Sign verification failed, installer signed with incorrect certificate: publisherNames: webifua, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\Admin\\AppData\\Local\\mttv-updater\\pending\\temp-mttv-setup-0.2.9.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
[2019-02-26 15:18:53.884] [error] Error: Error: New version 0.2.9 is not signed by the application owner: publisherNames: webifua, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\Admin\\AppData\\Local\\mttv-updater\\pending\\temp-mttv-setup-0.2.9.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
    at newError (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\builder-util-runtime\src\index.ts:29:17)
    at Object.<anonymous> (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:42:17)
From previous event:
    at Object.task (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:31:11)
    at C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:610:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at NsisUpdater.executeDownload (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:545:68)
    at NsisUpdater.executeDownload (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:27:18)
    at NsisUpdater.doDownloadUpdate (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:27:17)
    at NsisUpdater.downloadUpdate (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:420:19)
    at Object.exports.downloadUpdate (C:\Program Files (x86)\MTTV\resources\app.asar\electron\main.js:649:21)
    at callFunction (C:\Program Files (x86)\MTTV\resources\electron.asar\browser\rpc-server.js:250:18)
    at EventEmitter.<anonymous> (C:\Program Files (x86)\MTTV\resources\electron.asar\browser\rpc-server.js:360:5)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Program Files (x86)\MTTV\resources\electron.asar\browser\api\web-contents.js:293:13)
    at WebContents.emit (events.js:182:13)
[2019-02-26 15:18:53.884] [info] Error in auto-updater. Error: New version 0.2.9 is not signed by the application owner: publisherNames: webifua, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\Admin\\AppData\\Local\\mttv-updater\\pending\\temp-mttv-setup-0.2.9.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
[2019-02-26 15:18:53.885] [error] Error: Error: New version 0.2.9 is not signed by the application owner: publisherNames: webifua, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\Admin\\AppData\\Local\\mttv-updater\\pending\\temp-mttv-setup-0.2.9.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
    at newError (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\builder-util-runtime\src\index.ts:29:17)
    at Object.<anonymous> (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:42:17)
From previous event:
    at Object.task (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:31:11)
    at C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:610:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at NsisUpdater.executeDownload (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:545:68)
    at NsisUpdater.executeDownload (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\BaseUpdater.ts:27:18)
    at NsisUpdater.doDownloadUpdate (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:27:17)
    at NsisUpdater.downloadUpdate (C:\Program Files (x86)\MTTV\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:420:19)
    at BrowserWindow.appUpdateWin.on (C:\Program Files (x86)\MTTV\resources\app.asar\electron\main.js:601:25)
    at BrowserWindow.emit (events.js:182:13)
[2019-02-26 15:18:53.887] [info] Error in auto-updater. Error: New version 0.2.9 is not signed by the application owner: publisherNames: webifua, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\Admin\\AppData\\Local\\mttv-updater\\pending\\temp-mttv-setup-0.2.9.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
[2019-02-26 15:21:05.972] [info] App starting...
[2019-02-26 15:21:10.390] [info] Checking for update
[2019-02-26 15:21:10.463] [info] Checking for update...
[2019-02-26 15:21:12.505] [info] Found version 0.2.9 (url: mttv-setup-0.2.9.exe)
[2019-02-26 15:21:13.308] [info] Downloading update from mttv-setup-0.2.9.exe
[2019-02-26 15:21:13.343] [info] No cached update info available
[2019-02-26 15:21:13.347] [info] Download block maps (old: "https://github.com/mttv/mttv-app/releases/download/v0.2.8/mttv-setup-0.2.8.exe.blockmap", new: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe.blockmap)
[2019-02-26 15:21:13.589] [info] Downloading update from mttv-setup-0.2.9.exe
[2019-02-26 15:21:13.599] [info] No cached update info available
[2019-02-26 15:21:13.602] [info] Download block maps (old: "https://github.com/mttv/mttv-app/releases/download/v0.2.8/mttv-setup-0.2.8.exe.blockmap", new: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe.blockmap)
[2019-02-26 15:21:14.488] [info] File has 162 changed blocks
[2019-02-26 15:21:14.492] [info] Full: 62,513.62 KB, To download: 3,365.21 KB (5%)
[2019-02-26 15:21:14.505] [info] Differential download: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe
[2019-02-26 15:21:14.729] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/168543775/c9542e80-39d7-11e9-83eb-b15a493706f3
[2019-02-26 15:21:14.822] [info] File has 162 changed blocks
[2019-02-26 15:21:14.823] [info] Full: 62,513.62 KB, To download: 3,365.21 KB (5%)
[2019-02-26 15:21:14.825] [info] Differential download: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe
[2019-02-26 15:21:15.018] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/168543775/c9542e80-39d7-11e9-83eb-b15a493706f3
[2019-02-26 15:21:26.181] [warn] Cannot execute Get-AuthenticodeSignature: Error: Command failed: powershell.exe -NoProfile -NonInteractive -InputFormat None -Command Get-AuthenticodeSignature 'C:\Users\Admin\AppData\Local\mttv-updater\pending\temp-mttv-setup-0.2.9.exe' | ConvertTo-Json -Compress
Get-AuthenticodeSignature : The process cannot access the file 'C:\Users\Admin\AppData\Local\mttv-updater\pending\temp-
mttv-setup-0.2.9.exe' because it is being used by another process.
At line:1 char:1
+ Get-AuthenticodeSignature 'C:\Users\Admin\AppData\Local\mttv-updater\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AuthenticodeSignature], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.GetAuthenticodeSignatureCommand
 
. Ignoring signature validation due to unknown error.
[2019-02-26 15:21:26.184] [info] New version 0.2.9 has been downloaded to C:\Users\Admin\AppData\Local\mttv-updater\pending\mttv-setup-0.2.9.exe
[2019-02-26 15:21:26.188] [info] Update downloaded
[2019-02-26 15:21:26.188] [info] Install on explicit quitAndInstall
[2019-02-26 15:21:26.188] [info] Install: isSilent: false, isForceRunAfter: true
[2019-02-26 15:21:26.357] [info] Update installer has already been triggered. Quitting application.
[2019-02-26 15:21:26.357] [info] Cannot run installer: error code: EACCES, error message: "spawn C:\Users\Admin\AppData\Local\mttv-updater\pending\mttv-setup-0.2.9.exe EACCES", will be executed again using elevate if EACCES"
[2019-02-26 15:21:38.800] [info] App starting...
[2019-02-26 15:21:42.995] [info] Checking for update
[2019-02-26 15:21:43.069] [info] Checking for update...
[2019-02-26 15:21:45.195] [info] Update for version 0.2.9 is not available (latest version: 0.2.9, downgrade is disallowed).
[2019-02-26 15:21:45.196] [info] Update not available.

**Windows 7 log:**
[2019-02-26 15:29:30.018] [info] App starting...
[2019-02-26 15:29:33.723] [info] Checking for update
[2019-02-26 15:29:33.791] [info] Checking for update...
[2019-02-26 15:29:33.912] [info] Generated new staging user ID: 3620a96d-bb80-583c-b3be-312dcf8c9ed1
[2019-02-26 15:29:35.833] [info] Found version 0.2.9 (url: mttv-setup-0.2.9.exe)
[2019-02-26 15:29:36.617] [info] Downloading update from mttv-setup-0.2.9.exe
[2019-02-26 15:29:36.648] [info] No cached update info available
[2019-02-26 15:29:36.652] [info] Download block maps (old: "https://github.com/mttv/mttv-app/releases/download/v0.2.8/mttv-setup-0.2.8.exe.blockmap", new: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe.blockmap)
[2019-02-26 15:29:36.978] [info] Downloading update from mttv-setup-0.2.9.exe
[2019-02-26 15:29:36.986] [info] No cached update info available
[2019-02-26 15:29:36.989] [info] Download block maps (old: "https://github.com/mttv/mttv-app/releases/download/v0.2.8/mttv-setup-0.2.8.exe.blockmap", new: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe.blockmap)
[2019-02-26 15:29:37.615] [info] File has 162 changed blocks
[2019-02-26 15:29:37.619] [info] Full: 62,513.62 KB, To download: 3,365.21 KB (5%)
[2019-02-26 15:29:37.630] [info] Differential download: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe
[2019-02-26 15:29:37.842] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/168543775/c9542e80-39d7-11e9-83eb-b15a493706f3
[2019-02-26 15:29:37.984] [info] File has 162 changed blocks
[2019-02-26 15:29:37.985] [info] Full: 62,513.62 KB, To download: 3,365.21 KB (5%)
[2019-02-26 15:29:37.995] [info] Differential download: https://github.com/mttv/mttv-app/releases/download/v0.2.9/mttv-setup-0.2.9.exe
[2019-02-26 15:29:38.222] [info] Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/168543775/c9542e80-39d7-11e9-83eb-b15a493706f3
[2019-02-26 15:29:45.234] [warn] Cannot execute Get-AuthenticodeSignature: Error: Command failed: powershell.exe -NoProfile -NonInteractive -InputFormat None -Command Get-AuthenticodeSignature 'C:\Users\User\AppData\Local\mttv-updater\pending\temp-mttv-setup-0.2.9.exe' | ConvertTo-Json -Compress
��� "ConvertTo-Json" �� �ᯮ����� ��� ��� ���������, �㭪樨, 䠩�� �ਯ� �
�� �믮��塞�� �ணࠬ��. �஢���� �ࠢ��쭮��� ����ᠭ�� �����, � ⠪�� �����
�� � �ࠢ��쭮��� ���, ��᫥ 祣� ������ ������.
��ப�:1 ����:120
+ Get-AuthenticodeSignature 'C:\Users\User\AppData\Local\mttv-updater\pending\t
emp-mttv-setup-0.2.9.exe' | ConvertTo-Json <<<<  -Compress
    + CategoryInfo          : ObjectNotFound: (ConvertTo-Json:String) [], Comm 
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
. Ignoring signature validation due to unsupported powershell version. Please upgrade to powershell 3 or higher.
[2019-02-26 15:29:45.235] [info] New version 0.2.9 has been downloaded to C:\Users\User\AppData\Local\mttv-updater\pending\mttv-setup-0.2.9.exe
[2019-02-26 15:29:45.237] [info] Update downloaded
[2019-02-26 15:29:45.237] [info] Install on explicit quitAndInstall
[2019-02-26 15:29:45.237] [info] Install: isSilent: false, isForceRunAfter: true
[2019-02-26 15:29:45.553] [info] Update installer has already been triggered. Quitting application.
[2019-02-26 15:29:45.556] [warn] Cannot execute Get-AuthenticodeSignature: Error: Command failed: powershell.exe -NoProfile -NonInteractive -InputFormat None -Command Get-AuthenticodeSignature 'C:\Users\User\AppData\Local\mttv-updater\pending\temp-mttv-setup-0.2.9.exe' | ConvertTo-Json -Compress
��� "ConvertTo-Json" �� �ᯮ����� ��� ��� ���������, �㭪樨, 䠩�� �ਯ� �
�� �믮��塞�� �ணࠬ��. �஢���� �ࠢ��쭮��� ����ᠭ�� �����, � ⠪�� �����
�� � �ࠢ��쭮��� ���, ��᫥ 祣� ������ ������.
��ப�:1 ����:120
+ Get-AuthenticodeSignature 'C:\Users\User\AppData\Local\mttv-updater\pending\t
emp-mttv-setup-0.2.9.exe' | ConvertTo-Json <<<<  -Compress
    + CategoryInfo          : ObjectNotFound: (ConvertTo-Json:String) [], Comm 
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
. Ignoring signature validation due to unsupported powershell version. Please upgrade to powershell 3 or higher.
[2019-02-26 15:29:53.583] [info] App starting...
[2019-02-26 15:29:57.299] [info] Checking for update
[2019-02-26 15:29:57.363] [info] Checking for update...
[2019-02-26 15:30:00.028] [info] Update for version 0.2.9 is not available (latest version: 0.2.9, downgrade is disallowed).
[2019-02-26 15:30:00.028] [info] Update not available.

**Comment by mttv** [comment]
If I update non-published version to github then everything works fine.

**Comment by meekaah** [comment]
pretty sure this is related to https://github.com/electron-userland/electron-builder/issues/3526 no?

**Comment by mttv** [comment]
@meekaah Not quite, but I managed to solve auto-update problem with `"verifyUpdateCodeSignature": false`, but download progress is still very buggy it sometimes works and sometimes it doesnt.

**Comment by meekaah** [comment]
indeed i've stopped relying on it myself aswell most of the time it just goes 0%....100% 👎

**Comment by mttv** [comment]
@meekaah no I mean it doesnt even start

**Comment by meekaah** [comment]
ah ok nevermind then its not the same issue i was facing.
from looking at the code it could be that since its downloading a diffferential update and the following code https://github.com/electron-userland/electron-builder/blob/59aac664a7ea9c595fe3e11c38eb972b29d74bf1/packages/builder-util-runtime/src/ProgressCallbackTransform.ts#L33 it just skips and doesnt send out the download-progress event as it downloads each segment in under a second?

**Comment by mttv** [comment]
@meekaah Yep, its just skips download-progress event

**Comment by meekaah** [comment]
from the code above it seems like its "intended" behavior...  even though it seems buggy I would agree

**Comment by mttv** [comment]
Closing due to no response!

**Comment by mallamsripooja** [comment]
Can someone please help with a solution? Autoupdater is able to identify and download the latest app release but the shortcut and menu icon are not pointing to the latest app version after update.

Auto update is working as intended on Ubuntu but the issue seems to be happening on Windows system. I am using a Windows 10 system on which the shortcut and menu item are not getting updated.
