### ISSUE TITLE
App-builder exits with code 2

### ISSUE THREAD

**Issue by AlekEagleYT** [electron-userland/electron-builder#3758]
* **Version**: v20.39.0

* **Target**: Windows x64 NSIS

* **My Platform**: Linux Ubuntu 18.10 (Cosmic Cuttlefish)

Debug information with `DEBUG=electron-builder` set:

```
alekeagle@this-is-an-uwubuwutuwu-computer:~/Documents/newelectronproject$ electron-builder build -w --x64
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=package.json ("build" field)
  • effective config config=
                       directories:
                         output: dist
                         buildResources: build
                       dmg:
                         contents:
                           - x: 110
                             'y': 150
                           - x: 240
                             'y': 150
                             type: link
                             path: /Applications
                       linux:
                         target:
                           - AppImage
                           - deb
                         maintainer: AlekEagle
                         category: Utility
                         icon: icons/
                       win:
                         target: NSIS
                         icon: icons/
                       
  • writing effective config file=dist/builder-effective-config.yaml
  • unresolved dependencies after first round unresolved=register-scheme
  • Unresolved node modules: register-scheme
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=4.1.0 appOutDir=dist/win-unpacked
  • spawning        command=/usr/lib/node_modules/electron-builder/node_modules/app-builder-bin/linux/x64/app-builder unpack-electron --configuration [{"platform":"win32","arch":"x64","version":"4.1.0"}] --output /home/alekeagle/Documents/newelectronproject/dist/win-unpacked --distMacOsAppName Electron.app
  • map async                 taskCount=2
  • map async                 taskCount=1
  • map async                 taskCount=79
  • exited          command=app-builder code=0 pid=21602
  • spawning        command=/usr/lib/node_modules/electron-builder/node_modules/app-builder-bin/linux/x64/app-builder node-dep-tree --dir /home/alekeagle/Documents/newelectronproject
  • unresolved deps           nodeModuleDir=/home/alekeagle/Documents/newelectronproject/node_modules round=0 unresolved=psl
  • exited          command=app-builder code=0 pid=21619 out=[{"dir":"/home/alekeagle/Documents/newelectronproject/node_modules","deps":["@sentry/browser","@sentry/core","@sentry/electron","@sentry/hub","@sentry/minimal","@sentry/node","@sentry/types","@sentry/utils","@types/stack-trace","agent-base","ajv","ansi-styles","applescript","asn1","assert-plus","async-limiter","asynckit","auto-launch","aws-sign2","aws4","bcrypt-pbkdf","caseless","chalk","color-convert","color-name","combined-stream","conf","cookie","core-util-is","dashdash","debug","define-properties","delayed-stream","discord-rpc","dot-prop","ecc-jsbn","electron-fetch","electron-store","encoding","env-paths","es-abstract","es-to-primitive","es6-promise","es6-promisify","escape-string-regexp","extend","extsprintf","fast-deep-equal","fast-json-stable-stringify","find-up","forever-agent","form-data","function-bind","getpass","graceful-fs","har-schema","har-validator","has","has-flag","has-symbols","http-signature","https-proxy-agent","iconv-lite","imurmurhash","is-callable","is-date-object","is-obj","is-regex","is-symbol","is-typedarray","isstream","jsbn","json-schema","json-schema-traverse","json-stringify-safe","jsprim","locate-path","lru_map","lsmod","make-dir","mime-db","mime-types","minimist","mkdirp","ms","node-fetch","oauth-sign","object-keys","object.getownpropertydescriptors","p-limit","p-locate","p-try","path-exists","path-is-absolute","performance-now","pify","pkg-up","psl","punycode","qs","request","safe-buffer","safer-buffer","signal-exit","sshpk","stack-trace","supports-color","tough-cookie","tslib","tunnel-agent","tweetnacl","untildify","uri-js","util.promisify","uuid","verror","winreg","write-file-atomic","ws"]},{"dir":"/home/alekeagle/Documents/newelectronproject/node_modules/tough-cookie/node_modules","deps":["punycode"]}]
  • getPublishConfigsForUpdateInfo: no publishConfigs, detect using repository info
  • calling getInfo reason=owner or project is not specified explicitly provider=github owner=undefined project=undefined
  • spawning        command=/usr/lib/node_modules/electron-builder/node_modules/app-builder-bin/linux/x64/app-builder icon --format ico --root /home/alekeagle/Documents/newelectronproject/build --root /home/alekeagle/Documents/newelectronproject --out /home/alekeagle/Documents/newelectronproject/dist/.icon-ico --input icons/
  • path doesn't exist        path=/home/alekeagle/Documents/newelectronproject/build/icons/.ico
  • path doesn't exist        path=/home/alekeagle/Documents/newelectronproject/icons/.ico
  • path doesn't exist        path=/home/alekeagle/Documents/newelectronproject/build/icons
  • path resolved             outputFormat=ico path=/home/alekeagle/Documents/newelectronproject/icons
  • icon directory doesn't contain icons ([0-9]+.png), but icon.png exists iconDir=/home/alekeagle/Documents/newelectronproject/icons
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/develar/app-builder/pkg/icons.doConvertIcon(0xc00011e380, 0x8, 0x8, 0xc0001ec660, 0x2, 0x2, 0x7fff2bcab149, 0x3, 0x7fff2bcab1c1, 0x3b, ...)
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:223 +0xf19
github.com/develar/app-builder/pkg/icons.ConvertIcon(0xc0000c5300, 0x0, 0x0, 0x0)
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56 +0xd6
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1(0xc0001a9170, 0x409c03, 0xb1f720)
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33 +0x6e
github.com/alecthomas/kingpin.(*actionMixin).applyActions(0xc000092cd8, 0xc0001a9170, 0x0, 0x0)
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28 +0x6d
github.com/alecthomas/kingpin.(*Application).applyActions(0xc0000da690, 0xc0001a9170, 0x0, 0x0)
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557 +0xdc
github.com/alecthomas/kingpin.(*Application).execute(0xc0000da690, 0xc0001a9170, 0xc0001c2a20, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390 +0x8f
github.com/alecthomas/kingpin.(*Application).Parse(0xc0000da690, 0xc000092010, 0xb, 0xb, 0xc0000da690, 0xc0001e7f88, 0x4059ef, 0xc00002c118)
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222 +0x203
main.main()
        /Volumes/data/Documents/app-builder/main.go:78 +0x350
  • exited          command=app-builder code=2 pid=21641
Error: /usr/lib/node_modules/electron-builder/node_modules/app-builder-bin/linux/x64/app-builder exited with code 2
    at ChildProcess.childProcess.once.code (/usr/lib/node_modules/electron-builder/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:285:20)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:988:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
From previous event:
    at WinPackager.resolveIcon (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:594:101)
    at /usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:573:31
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.getOrConvertIcon (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:572:54)
    at Lazy.WinPackager._iconPath (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/winPackager.ts:79:43)
    at Lazy.get value [as value] (/usr/lib/node_modules/electron-builder/node_modules/lazy-val/src/main.ts:18:25)
    at WinPackager.getIconPath (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/winPackager.ts:190:27)
    at /usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/winPackager.ts:287:33
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signAndEditResources (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/winPackager.ts:363:21)
    at go$readdir$cb (/usr/lib/node_modules/electron-builder/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at /usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/winPackager.ts:355:73)
    at /usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:250:16
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:638:19)
From previous event:
    at WinPackager.doPack (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/usr/lib/node_modules/electron-builder/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /usr/lib/node_modules/electron-builder/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:159:5)
From previous event:
    at Packager.doBuild (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/electron-builder/node_modules/graceful-fs/graceful-fs.js:111:16
    at /usr/lib/node_modules/electron-builder/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at Packager._build (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:638:19)
From previous event:
    at Packager.build (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/usr/lib/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/usr/lib/node_modules/electron-builder/src/cli/cli.ts:46:19)
```

**Comment by AlekEagleYT** [comment]
I fixed it, I had to point to the `icon.ico` file in the win target.
