### ISSUE TITLE
Auto-Updater: Periodically check for updates

### ISSUE THREAD

**Issue by vkolova** [electron-userland/electron-builder#3769]
* **Version**: 20.39.0

* **electron-updater version**: 4.0.6

* **Target**: windows

Hello! I'm trying to set our application to periodically check for updates and not just on application start. Since I didn't find anything like this in the documents or examples, I tried with:
```
autoUpdater.checkForUpdatesAndNotify();
setInterval(autoUpdater.checkForUpdatesAndNotify, 1000 * 60 * 15);
```
And the first line works perfectly. Update is downloaded and installed as it should. Great. But when called a second time, from the interval, I get this error:

```
error: uncaughtException: this.isUpdaterActive is not a function
TypeError: this.isUpdaterActive is not a function
    at Timeout.checkForUpdatesAndNotify [as _onTimeout] (...\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:245:15)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10) 
```
So I tried with `autoUpdater.checkForUpdates` instead. Then I started getting
```
error: uncaughtException: Cannot read property 'info' of undefined
TypeError: Cannot read property 'info' of undefined
    at Timeout.checkForUpdates [as _onTimeout] (...\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:219:18)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
```

Am I missing something from the documentation? Am I doing something wrong? Auto updates when they are published is a very important thing for our application.

**Comment by popod** [comment]
@vkolova Have you found a solution ? I'me interested by this tool.

**Comment by vkolova** [comment]
@popod  Yes, changing it to
```javascript
setInterval(() => {
    autoUpdater.checkForUpdatesAndNotify();
}, 1000 * 60 * 15);
```
worked.

**Comment by yusuf-zafar** [comment]
Hey, thanks this is exactly something I was looking for!
