### ISSUE TITLE
Need to use electron dependencies on production environment

### ISSUE THREAD

**Issue by kentng201** [electron-userland/electron-builder#3773]
* **Version**: 19.19.1

* **Electron Updater Version**: 2.21.10

* **Target**: nsis on Windows 10
* **Node**: 8.11.3
* **NPM:** 6.4.1

I need help for add 'electron' as dependencies but not devDependencies due to use some electron module like ipcRenderer and ipcMain, how to adding them and build successfully?

* **Build log:** Error: Package "electron" is only allowed in "devDependencies". Please remove it from the "dependencies" section in your package.json.
    at checkMetadata (D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder-lib\src\util\packageMetadata.ts:77:11)
    at D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder-lib\src\packager.ts:268:5
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder-lib\out\packager.js:332:11)
    at D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder\out\builder.js:61:21)
    at build (D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder\src\builder.ts:280:10)
    at then (D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Object.args [as handler] (D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder\node_modules\yargs\yargs.js:1074:24)
    at Object.get [as argv] (D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder\node_modules\yargs\yargs.js:989:21)
    at Object.<anonymous> (D:\projects\electron\feedme-restaurant-desktop\node_modules\electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

* **package.json:** "scripts": {
    "build": "node .electron-vue/build.js && electron-builder",
    ...
    "dev": "node .electron-vue/dev-runner.js",
    "lint": "eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter src test",
    "lint:fix": "eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src test",
    ...
    "postinstall": "npm run lint:fix && electron-builder install-app-deps"
  },
  "build": {
    ...
    "buildDependenciesFromSource": true,
    "npmRebuild": false,
    "generateUpdatesFilesForAllChannels": true,
    "directories": {
      "output": "build"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "dmg": {
      "contents": [
        ...
      ]
    },
    ...
    "win": {
      "target": [
        "nsis"
      ],
      "verifyUpdateCodeSignature": false,
      "icon": "build/icons/icon.ico"
    },
    ...
  },
  "dependencies": {
    ...
    "electron": "^4.1.0",
    "electron-dl": "^1.12.0",
    "electron-store": "^2.0.0",
    "electron-updater": "^2.21.10",
    ...
  },
  "devDependencies": {
    ...
    "electron-builder": "^19.19.1",
    "electron-debug": "^1.4.0",
    "electron-devtools-installer": "^2.2.0",
    ...
    "webpack": "^3.5.2",
    "webpack-dev-server": "^2.7.1",
    "webpack-hot-middleware": "^2.18.2",
    "webpack-merge": "^4.1.0"
  }

**Comment by meekaah** [comment]
you dont need to add electron as a production dependency to be able to use ipcrenderer or ipcmain they are available in either case

**Comment by kentng201** [comment]
Sure, thanks!
