### ISSUE TITLE
GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"

### ISSUE THREAD

**Issue by JohannBlake** [electron-userland/electron-builder#3792]
Up until yesterday I was able to publish my app to Github but after upgrading to Electron 4.1.3 I get the following error:

> GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"

This token does in fact exist in the environment variable GH_TOKEN on my Mac. I tried rebooting the machine but that didn't help. I can also run the environment command "env" and the token is listed. Here is the full error. The log contents follow this:

```
> build -p always

Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=4.1.3 appOutDir=dist/mac
  • signing         file=dist/mac/skutti.app identityName=Developer ID Application: Johann Blake (xxx) identityHash=xxx
 provisioningProfile=none
  • building        target=DMG arch=x64 file=dist/skutti-1.0.3.dmg
  • building block map blockMapFile=dist/skutti-1.0.3.dmg.blockmap
Error: Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
    at new GitHubPublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-publish/src/gitHubPublisher.ts:47:15)
    at createPublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:272:14)
    at PublishManager.getOrCreatePublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:195:19)
    at PublishManager.scheduleUpload (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:136:28)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:179:14
From previous event:
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:155:83)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:110:39)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at Packager.dispatchArtifactCreated (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:276:23)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:280:10
    at Generator.next (<anonymous>)
From previous event:
    at Packager.callArtifactBuildCompleted (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:279:58)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/targets/differentialUpdateInfoBuilder.ts:72:56
From previous event:
    at _createBlockmap (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/targets/differentialUpdateInfoBuilder.ts:74:3)
    at createBlockmap (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/out/targets/differentialUpdateInfoBuilder.js:116:26)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/dmg-builder/src/dmg.ts:70:30
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at nonMasPromise.then.then (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:90:26)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>

Error #2 --------------------------------------------------------------------------------
Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
    at new GitHubPublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-publish/src/gitHubPublisher.ts:47:15)
    at createPublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:272:14)
    at PublishManager.getOrCreatePublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:195:19)
    at PublishManager.scheduleUpload (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:136:28)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:179:14
From previous event:
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:155:83)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:110:39)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at Packager.dispatchArtifactCreated (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:276:23)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:280:10
    at Generator.next (<anonymous>)
From previous event:
    at Packager.callArtifactBuildCompleted (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:279:58)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/dmg-builder/src/dmg.ts:71:25
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at nonMasPromise.then.then (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:90:26)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
    at new GitHubPublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-publish/src/gitHubPublisher.ts:47:15)
    at createPublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:272:14)
    at PublishManager.getOrCreatePublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:195:19)
    at PublishManager.scheduleUpload (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:136:28)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:179:14
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:155:83)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:110:39)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at Packager.dispatchArtifactCreated (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:276:23)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:280:10
    at Generator.next (<anonymous>)
    at Packager.callArtifactBuildCompleted (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:279:58)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/targets/differentialUpdateInfoBuilder.ts:72:56
    at _createBlockmap (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/targets/differentialUpdateInfoBuilder.ts:74:3)
    at createBlockmap (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/out/targets/differentialUpdateInfoBuilder.js:116:26)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/dmg-builder/src/dmg.ts:70:30
    at Generator.next (<anonymous>)
    at DmgTarget.build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at nonMasPromise.then.then (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:90:26)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
    at MacPackager.pack (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
    at Packager.doBuild (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
    at Packager._build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at Packager.build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
    at new GitHubPublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-publish/src/gitHubPublisher.ts:47:15)
    at createPublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:272:14)
    at PublishManager.getOrCreatePublisher (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:195:19)
    at PublishManager.scheduleUpload (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:136:28)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:179:14
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:155:83)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:110:39)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at Packager.dispatchArtifactCreated (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:276:23)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:280:10
    at Generator.next (<anonymous>)
    at Packager.callArtifactBuildCompleted (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:279:58)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/dmg-builder/src/dmg.ts:71:25
    at Generator.next (<anonymous>)
    at DmgTarget.build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at nonMasPromise.then.then (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:90:26)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
    at MacPackager.pack (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
    at Packager.doBuild (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
    at Packager._build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at Packager.build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
    at throwError (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/builder-util/src/asyncTaskManager.ts:90:11)
    at checkErrors (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/builder-util/src/asyncTaskManager.ts:53:9)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/builder-util/src/asyncTaskManager.ts:58:5
    at Generator.next (<anonymous>)
From previous event:
    at AsyncTaskManager.awaitTasks (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/builder-util/src/asyncTaskManager.ts:44:19)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:209:28
    at Generator.next (<anonymous>)
From previous event:
    at PublishManager.awaitTasks (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/publish/PublishManager.ts:208:19)
    at isErrorOccurred (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/index.ts:93:32)
    at /Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/builder-util/src/promise.ts:25:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at _executeFinally (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/builder-util/out/promise.js:63:26)
    at executeFinally (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/builder-util/out/promise.js:41:26)
    at build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/app-builder-lib/src/index.ts:86:10)
    at build (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skutti@1.0.3 shipMac: `build -p always`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the skutti@1.0.3 shipMac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johann/.npm/_logs/2019-04-01T10_19_15_657Z-debug.log
```

Log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'shipMac' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'preshipMac', 'shipMac', 'postshipMac' ]
5 info lifecycle skutti@1.2.0~preshipMac: skutti@1.2.0
6 info lifecycle skutti@1.2.0~shipMac: skutti@1.2.0
7 verbose lifecycle skutti@1.2.0~shipMac: unsafe-perm in lifecycle true
8 verbose lifecycle skutti@1.2.0~shipMac: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/.bin:/Users/johann/.yarn/bin:/Users/johann/.config/yarn/global/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/bin/:/Users/johann/SDKs/Android/platform-tools/:/Users/johann/SDKs/appengine-java-sdk-1.9.64/bin/:/Users/johann/SDKs/google-cloud-sdk/bin/:/Users/johann/SDKs/gradle-4.5/bin/:/Users/johann/SDKs/kotlinc/bin/:/Users/johann/SDKs/apache-maven-3.5.2/bin/:/Library/Frameworks/Mono.framework/
9 verbose lifecycle skutti@1.2.0~shipMac: CWD: /Users/johann/Work/Dev/Web/Projects/ServetusClient
10 silly lifecycle skutti@1.2.0~shipMac: Args: [ '-c', 'build -p always' ]
11 silly lifecycle skutti@1.2.0~shipMac: Returned: code: 1  signal: null
12 info lifecycle skutti@1.2.0~shipMac: Failed to exec shipMac script
13 verbose stack Error: skutti@1.2.0 shipMac: `build -p always`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid skutti@1.2.0
15 verbose cwd /Users/johann/Work/Dev/Web/Projects/ServetusClient
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "shipMac"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error skutti@1.2.0 shipMac: `build -p always`
22 error Exit status 1
23 error Failed at the skutti@1.2.0 shipMac script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by JohannBlake** [comment]
It appears that Macs have diverse ways of setting the environment variable. Apple changes these methods every once in a while and what may work on an older version of macOS may not work on a newer version. I am currently using macOS 10.13.6 High Sierra. Regardless what method I chose to set the environment variable, it never succeeded. I figured out a solution however that does work. In your package.json file under the script key, set GH_TOKEN as follows:

```
  "scripts": {
    "publishMac": "GH_TOKEN=your_access_token build -p always"
  }
```

Then just run your script:

> npm run publishMac

Even though you are including your token in the package.json file within the scripts section, electron builder does not include the token in the published build. However, if you were to place the token under the build key as follows, it will get included in the published build (which is something you should never do):

```
  "build": {
    "publish": [
      {
        "provider": "github",
        "owner": "your_github_name",
        "repo": "your_github_repo",
        "token": "your_access_token"
      }
    ]
```

**Comment by proccedure-caze** [comment]
This helped me to get rid of the error: https://github.com/electron-userland/electron-builder/issues/1693#issuecomment-1296113080
