### ISSUE TITLE
Error: CURL failure: Failure when receiving data from the peer...

### ISSUE THREAD

**Issue by busticated** [electron-userland/electron-builder#3806]
* **OS**: macOS `v10.13.6`
* **Version**: `electron-builder@20.39.0`
* **Target**: windows "portable"

hey there :wave:

i've been able to build just fine up until today - as of this morning, i'm hitting:

```
Failure when receiving data from the peer
authenticode timestamping failed
CURL failure: Failure when receiving data from the peer
authenticode timestamping failed
```

it occurs when building and signing the windows portable `.exe`

my config:

```
  "build": {
    "productName": "Test App",
    "artifactName": "TestApp.${ext}",
    "appId": "io.myapptest.test",
    "files": [
      "./src/**/*",
      "./build/**/*"
    ],
    "directories": {
      "app": "./",
      "output": "./dist",
      "buildResources": "./build"
    },
    "appImage": {
      "systemIntegration": "doNotAsk"
    },
    "mac": {
      "target": "zip",
      "category": "public.app-category.developer-tools",
      "icon": "./src/assets/app.icns",
      "minimumSystemVersion": "10.12.0"
    },
    "win": {
      "target": "portable",
      "icon": "./src/assets/app.ico"
    },
    "linux": {
      "target": "AppImage",
      "category": "Utility"
    }
  }
```

<details>
<summary>Full Error Log</summary>
<p>

```
Error: Exit code: 255. Command failed: /Users/me/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.4.0/darwin/10.12/osslsigncode -in /Users/me/code/test-app/dist/win-unpacked/Test App.exe -out /Users/me/code/test-app/dist/win-unpacked/Test App-signed-sha1.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -pkcs12 /Users/me/code/test-app/src/my-cert.p12 -h sha1 -n Test App -pass <omitted> (sha256 hash) failure: Failure when receiving data from the peer
authenticode timestamping failed
Failed
CURL failure: Failure when receiving data from the peer
authenticode timestamping failed
Failed
    at /Users/me/code/test-app/node_modules/builder-util/src/util.ts:126:16
    at ChildProcess.exithandler (child_process.js:288:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
From previous event:
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at _doSign (/Users/me/code/test-app/node_modules/app-builder-lib/out/codeSign/windowsCodeSign.js:288:18)
    at doSign (/Users/me/code/test-app/node_modules/app-builder-lib/out/codeSign/windowsCodeSign.js:236:18)
    at defaultExecutor (/Users/me/code/test-app/node_modules/app-builder-lib/src/codeSign/windowsCodeSign.ts:59:12)
    at /Users/me/code/test-app/node_modules/app-builder-lib/src/codeSign/windowsCodeSign.ts:66:11
    at Generator.next (<anonymous>)
From previous event:
    at _sign (/Users/me/code/test-app/node_modules/app-builder-lib/out/codeSign/windowsCodeSign.js:160:16)
    at sign (/Users/me/code/test-app/node_modules/app-builder-lib/out/codeSign/windowsCodeSign.js:121:16)
    at /Users/me/code/test-app/node_modules/app-builder-lib/src/winPackager.ts:245:15
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.doSign (/Users/me/code/test-app/node_modules/app-builder-lib/src/winPackager.ts:242:51)
    at /Users/me/code/test-app/node_modules/app-builder-lib/src/winPackager.ts:233:16
From previous event:
    at WinPackager.sign (/Users/me/code/test-app/node_modules/app-builder-lib/src/winPackager.ts:193:53)
    at /Users/me/code/test-app/node_modules/app-builder-lib/src/winPackager.ts:327:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at WinPackager.signAndEditResources (/Users/me/code/test-app/node_modules/app-builder-lib/src/winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (/Users/me/code/test-app/node_modules/app-builder-lib/src/winPackager.ts:363:21)
    at go$readdir$cb (/Users/me/code/test-app/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at /Users/me/code/test-app/node_modules/app-builder-lib/src/winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/Users/me/code/test-app/node_modules/app-builder-lib/src/winPackager.ts:355:73)
    at /Users/me/code/test-app/node_modules/app-builder-lib/src/platformPackager.ts:250:16
From previous event:
    at WinPackager.doPack (/Users/me/code/test-app/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /Users/me/code/test-app/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/me/code/test-app/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /Users/me/code/test-app/node_modules/app-builder-lib/src/packager.ts:430:24
From previous event:
    at Packager.doBuild (/Users/me/code/test-app/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/me/code/test-app/node_modules/app-builder-lib/src/packager.ts:366:57
From previous event:
    at Packager._build (/Users/me/code/test-app/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/me/code/test-app/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/Users/me/code/test-app/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/me/code/test-app/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/me/code/test-app/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/me/code/test-app/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
  • building embedded block map file=dist/TestApp.zip
```

</p>
</details>

fwiw, when i try:

```
curl http://timestamp.verisign.com/scripts/timstamp.dll
```

i get `curl: (56) Recv failure: Connection reset by peer` but 🤷‍♂️

**Comment by korob93** [comment]
Same issue on my side. Any workaround for this?

**Comment by vladseverin** [comment]
Same issue on my side too. How it resolve?

**Comment by vladseverin** [comment]
Im found right solution for me [here](https://github.com/electron-userland/electron-builder/issues/291#issuecomment-206533486)

**Comment by stevenrombauts** [comment]
@busticated Did you find a solution? I'm having the same problem since a couple of days. Signing seems to work for a bunch of files until it suddenly stops with the same error as you had.

**Comment by tobiasmuecksch** [comment]
Same issue here, in my case the certificate file is located in the build machine.

**Comment by busticated** [comment]
@stevenrombauts shortly after posting, the issue resolved itself - i chalked it up to an unreliable 3rd party. i just tried again and it seems the `http://timestamp.verisign.com/scripts/timstamp.dll` endpoint is down again

**Comment by Tev-work** [comment]
This occurred during our build today as well, retrying 2 hours later worked.

**Comment by roman9869** [comment]
We have same problem last day

**Comment by stevenrombauts** [comment]
@busticated The problem seems to be the default timestamp server. I'm guessing the default server is limiting the amount of requests you are allowed to do, so it tends to fail if you're signing all your files consecutively.

I solved this by setting the `timeStampServer` to `http://timestamp.globalsign.com/scripts/timstamp.dll`.

**Comment by busticated** [comment]
if a more reliable time server would be helpful, perhaps this is worth a look:

https://blog.cloudflare.com/secure-time/

**Comment by develar** [comment]
Fixed in 21.
