### ISSUE TITLE
7zip error on macOS

### ISSUE THREAD

**Issue by ccnokes** [electron-userland/electron-builder#3812]
* **Version**: 20.31.3

* **Target**: macOS

I just upgraded from v20.4.1 to v20.31.3. When running my build, the 7zip step is throwing an error. The hdiutil is also throwing but that may just be a result of 7zip. Weirdly, this happens only on my CI Jenkins machine (macOS v10.12.6), not my local macOS (v10.14.3). Any ideas? Let me know if any other info is helpful. Thanks!

```
13:07:42 > build --mac
13:07:42 
13:07:42   • electron-builder version=20.31.3
13:07:42   • artifacts will be published if draft release exists reason=CI detected
13:07:42   • loaded configuration file=package.json ("build" field)
13:07:42   • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies
13:07:42 
13:07:42 To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
13:07:48   • rebuilding native production dependencies platform=darwin arch=x64
13:08:01   • packaging       platform=darwin arch=x64 electron=4.1.2 appOutDir=dist/mac
13:08:30   • signing         file=dist/mac/Buzz.app identityName=Developer ID Application: Domo, Inc. (UT) (WU68TQFWSR) identityHash=060B0FB98CFCC29D3CBE24EF5966C441F22DE687 provisioningProfile=none
13:09:15   • building        target=macOS zip arch=x64 file=dist/Buzz-2.0.0-mac.zip
13:09:15   • building        target=DMG arch=x64 file=dist/Buzz-2.0.0.dmg
13:10:43 Error: Cannot cleanup: 
13:10:43 
13:10:43 Error #1 --------------------------------------------------------------------------------
13:10:43 Error: Exit code: 2. Command failed: /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/node_modules/7zip-bin/mac/7za a -bd -mx=7 -mtc=off -mm=Deflate -mcu /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/dist/Buzz-2.0.0-mac.zip Buzz.app
13:10:43 
13:10:43 
13:10:43 System ERROR:
13:10:43 E_FAIL
13:10:43 
13:10:43 
13:10:43 7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
13:10:43 p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)
13:10:43 
13:10:43 Scanning the drive:
13:10:43 143 folders, 179 files, 1514135871 bytes (1444 MiB)
13:10:43 
13:10:43 Creating archive: /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/dist/Buzz-2.0.0-mac.zip
13:10:43 
13:10:43 Items to compress: 322
13:10:43 
13:10:43 
13:10:43 
13:10:43 
13:10:43 System ERROR:
13:10:43 E_FAIL
13:10:43 
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/node_modules/builder-util/src/util.ts:127:16
13:10:43     at ChildProcess.exithandler (child_process.js:298:5)
13:10:43     at ChildProcess.emit (events.js:182:13)
13:10:43     at maybeClose (internal/child_process.js:961:16)
13:10:43     at Socket.stream.socket.on (internal/child_process.js:380:11)
13:10:43     at Socket.emit (events.js:182:13)
13:10:43     at Pipe._handle.close (net.js:598:12)
13:10:43 From previous event:
13:10:43     at _archive (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/out/targets/archive.js:226:19)
13:10:43     at archive (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/out/targets/archive.js:198:19)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/targets/ArchiveTarget.ts:58:13
13:10:43     at Generator.next (<anonymous>)
13:10:43 From previous event:
13:10:43     at ArchiveTarget.build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/targets/ArchiveTarget.ts:16:44)
13:10:43     at Function.buildAsyncTargets (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
13:10:43     at MacPackager.packageInDistributableFormat (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
13:10:43     at nonMasPromise.then.then (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/macPackager.ts:90:26)
13:10:43     at runCallback (timers.js:696:18)
13:10:43     at tryOnImmediate (timers.js:667:5)
13:10:43     at processImmediate (timers.js:649:5)
13:10:43 From previous event:
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/macPackager.ts:90:10
13:10:43     at Generator.next (<anonymous>)
13:10:43 From previous event:
13:10:43     at MacPackager.pack (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/macPackager.ts:80:95)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:375:24
13:10:43     at Generator.next (<anonymous>)
13:10:43     at xfs.stat (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/graceful-fs/polyfills.js:285:20
13:10:43     at FSReqWrap.oncomplete (fs.js:159:5)
13:10:43 From previous event:
13:10:43     at Packager.doBuild (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:343:39)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:313:57
13:10:43 From previous event:
13:10:43     at Packager._build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:284:133)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:280:23
13:10:43     at Generator.next (<anonymous>)
13:10:43     at runCallback (timers.js:696:18)
13:10:43     at tryOnImmediate (timers.js:667:5)
13:10:43     at processImmediate (timers.js:649:5)
13:10:43 From previous event:
13:10:43     at Packager.build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:237:14)
13:10:43     at build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/index.ts:58:28)
13:10:43     at build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/electron-builder/src/builder.ts:227:10)
13:10:43     at then (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/electron-builder/src/cli/cli.ts:46:19)
13:10:43 
13:10:43 Error #2 --------------------------------------------------------------------------------
13:10:43 Error: hdiutil exited with code 1
13:10:43     at ChildProcess.childProcess.once.code (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/dmg-builder/node_modules/builder-util/src/util.ts:253:14)
13:10:43     at Object.onceWrapper (events.js:273:13)
13:10:43     at ChildProcess.emit (events.js:182:13)
13:10:43     at maybeClose (internal/child_process.js:961:16)
13:10:43     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
13:10:43 From previous event:
13:10:43     at DmgTarget.build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/dmg-builder/src/dmg.ts:21:42)
13:10:43     at Function.buildAsyncTargets (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
13:10:43     at MacPackager.packageInDistributableFormat (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
13:10:43     at nonMasPromise.then.then (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/macPackager.ts:90:26)
13:10:43     at runCallback (timers.js:696:18)
13:10:43     at tryOnImmediate (timers.js:667:5)
13:10:43     at processImmediate (timers.js:649:5)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/node_modules/builder-util/src/util.ts:127:16
13:10:43     at ChildProcess.exithandler (child_process.js:298:5)
13:10:43     at ChildProcess.emit (events.js:182:13)
13:10:43     at maybeClose (internal/child_process.js:961:16)
13:10:43     at Socket.stream.socket.on (internal/child_process.js:380:11)
13:10:43     at Socket.emit (events.js:182:13)
13:10:43     at Pipe._handle.close (net.js:598:12)
13:10:43     at _archive (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/out/targets/archive.js:226:19)
13:10:43     at archive (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/out/targets/archive.js:198:19)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/targets/ArchiveTarget.ts:58:13
13:10:43     at Generator.next (<anonymous>)
13:10:43     at ArchiveTarget.build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/targets/ArchiveTarget.ts:16:44)
13:10:43     at Function.buildAsyncTargets (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
13:10:43     at MacPackager.packageInDistributableFormat (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
13:10:43     at nonMasPromise.then.then (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/macPackager.ts:90:26)
13:10:43     at runCallback (timers.js:696:18)
13:10:43     at tryOnImmediate (timers.js:667:5)
13:10:43     at processImmediate (timers.js:649:5)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/macPackager.ts:90:10
13:10:43     at Generator.next (<anonymous>)
13:10:43     at MacPackager.pack (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/macPackager.ts:80:95)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:375:24
13:10:43     at Generator.next (<anonymous>)
13:10:43     at xfs.stat (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/graceful-fs/polyfills.js:285:20
13:10:43     at FSReqWrap.oncomplete (fs.js:159:5)
13:10:43     at Packager.doBuild (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:343:39)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:313:57
13:10:43     at Packager._build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:284:133)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:280:23
13:10:43     at Generator.next (<anonymous>)
13:10:43     at runCallback (timers.js:696:18)
13:10:43     at tryOnImmediate (timers.js:667:5)
13:10:43     at processImmediate (timers.js:649:5)
13:10:43     at Packager.build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:237:14)
13:10:43     at build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/index.ts:58:28)
13:10:43     at build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/electron-builder/src/builder.ts:227:10)
13:10:43     at then (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/electron-builder/src/cli/cli.ts:46:19)
13:10:43     at ChildProcess.childProcess.once.code (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/dmg-builder/node_modules/builder-util/src/util.ts:253:14)
13:10:43     at Object.onceWrapper (events.js:273:13)
13:10:43     at ChildProcess.emit (events.js:182:13)
13:10:43     at maybeClose (internal/child_process.js:961:16)
13:10:43     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
13:10:43     at DmgTarget.build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/dmg-builder/src/dmg.ts:21:42)
13:10:43     at Function.buildAsyncTargets (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
13:10:43     at MacPackager.packageInDistributableFormat (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
13:10:43     at nonMasPromise.then.then (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/macPackager.ts:90:26)
13:10:43     at runCallback (timers.js:696:18)
13:10:43     at tryOnImmediate (timers.js:667:5)
13:10:43     at processImmediate (timers.js:649:5)
13:10:43     at throwError (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/node_modules/builder-util/src/asyncTaskManager.ts:90:11)
13:10:43     at checkErrors (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/node_modules/builder-util/src/asyncTaskManager.ts:53:9)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/node_modules/builder-util/src/asyncTaskManager.ts:67:7
13:10:43 From previous event:
13:10:43     at AsyncTaskManager.awaitTasks (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/node_modules/builder-util/src/asyncTaskManager.ts:44:19)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:387:23
13:10:43 From previous event:
13:10:43     at Packager.doBuild (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:343:39)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:313:57
13:10:43 From previous event:
13:10:43     at Packager._build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:284:133)
13:10:43     at /Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:280:23
13:10:43     at Generator.next (<anonymous>)
13:10:43     at runCallback (timers.js:696:18)
13:10:43     at tryOnImmediate (timers.js:667:5)
13:10:43     at processImmediate (timers.js:649:5)
13:10:43 From previous event:
13:10:43     at Packager.build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/packager.ts:237:14)
13:10:43     at build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/app-builder-lib/src/index.ts:58:28)
13:10:43     at build (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/electron-builder/src/builder.ts:227:10)
13:10:43     at then (/Users/jenkins/node/workspace/one-off-builds/BuzzDesktop/BuzzMac/node_modules/electron-builder/src/cli/cli.ts:46:19)
```

**Comment by develar** [comment]
Please try version 20.40.2

**Comment by ccnokes** [comment]
@develar I just tried it and got the same error 😢. Let me know if you need any more info. I'm going to work on updating the OS version just in case that is causing it. I'll add that the node.js version is 10.6.0.

**Comment by ccnokes** [comment]
Is there a way to not use 7zip? Just wondering if using plain zip or tar would work.

**Comment by emile-f** [comment]
Version: 20.39.0
Target: macOS
I don't know if this helpfull but i was able to build my electron app with the CLI command without getting the error message but when i run it with the JS api it fails with the same error message.

CLI-command: electron-builder --mac
Api config:
`      builder.build({
        targets: Platform.MAC.createTarget(),
        config: {
          appId: 'com..' + _.camelCase(projectName),
          artifactName: _.kebabCase(projectName) + '.dmg',
          productName: _.kebabCase(projectName),
          mac: {
            icon: 'app/build/icon.icns'
          },
          directories: {
            buildResources: 'app/',
            output: 'dist/mac'
          }
        }
      })`

**Comment by ccnokes** [comment]
I downgraded to 20.31.3 and it works now. Strange 🤷‍♂️. @emile-f thanks, I've actually always been running it via the CLI.

**Comment by pgupt** [comment]
Getting the same issue. I tried electron-builder 20.44 and 20.31.3 as one comment suggested. but no luck.

**Comment by emile-f** [comment]
A solution that worked for me is not setting the artifactName. When I removed the name the build finishes correctly.

**Comment by pgupt** [comment]
@emile-f I have not mentioned artifactName in package.json. 

Thanks for taking time to reply. appreciate it.
