### ISSUE TITLE
Build crashes for macOS

### ISSUE THREAD

**Issue by GunterJameda** [electron-userland/electron-builder#3835]
* **Version**: 20.39.0

* **Target**: MacOs

 I tried to build my application for macOs and it threw an error whose output I'll paste here right away. I don't know if this is relevant, but it still produced some output files.

As I'm a newbie at electron, I'd appreciate your help. :)

Output:
```
Error: /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-bin/mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
From previous event:
    at MacPackager.resolveIcon (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/platformPackager.ts:594:101)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/platformPackager.ts:573:31
    at Generator.next (<anonymous>)
    at MacPackager.getOrConvertIcon (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/platformPackager.ts:572:54)
    at Lazy.MacPackager._iconPath (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/macPackager.ts:35:43)
    at Lazy.get value [as value] (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/lazy-val/src/main.ts:18:25)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/macPackager.ts:50:27
    at Generator.next (<anonymous>)
    at MacPackager.getIconPath (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/macPackager.ts:49:20)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/macPackager.ts:271:29
From previous event:
    at MacPackager.getOrConvertIcon (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/platformPackager.ts:572:54)
    at Lazy.MacPackager._iconPath (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/macPackager.ts:35:43)
    at Lazy.get value [as value] (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/lazy-val/src/main.ts:18:25)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/macPackager.ts:50:27
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.getIconPath (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/macPackager.ts:49:20)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/macPackager.ts:271:29
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.applyCommonInfo (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/macPackager.ts:264:60)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/electron/electronMac.ts:77:18
From previous event:
    at _createMacApp (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/out/electron/electronMac.js:262:24)
    at createMacApp (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/out/electron/electronMac.js:120:24)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:77:11
    at Generator.next (<anonymous>)
From previous event:
    at _beforeCopyExtraFiles (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/out/electron/ElectronFramework.js:172:32)
    at beforeCopyExtraFiles (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/out/electron/ElectronFramework.js:121:32)
    at ElectronFramework.beforeCopyExtraFiles (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:129:12)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/platformPackager.ts:222:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at MacPackager.doPack (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Packager.doBuild (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at Packager._build (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/pedrobarbosa/development/albumteller-desktop-app/node_modules/electron-builder/src/cli/cli.ts:46:19)
```

**Comment by GunterJameda** [comment]
I solved it.

Some icons were missing in the location I provided in the electron-builder.json

Thanks anyway!
