### ISSUE TITLE
Building for Linux (Snap or AppImage) on Windows fails

### ISSUE THREAD

**Issue by cdietschrun** [electron-userland/electron-builder#3843]
* **Version**: 
20.36.2, will retry with 20.39.0, electron 4.0.0 (via electron-prebuilt-compile)

* **Target**: 
Linux Snap or AppImage

Builds fine for Windows NSIS, but switching package.json to 
`"linux": { "target": [ "snap" (or appImage ] }`

this takes a while and then fails. It basically is creating an infinite loop of dist/linux-unpacked/dist/linux-unpacked/dist....etc until it fails:

inux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\linux-unpacked\dist\win-unpacked\dist\win-unpacked\.env'
    at _bluebirdLst.default.map.name (C:\Users\chdietsc\source\repos\mason-ui\node_modules\builder-util\src\fs.ts:81:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\builder-util\src\fs.ts:75:51
    at Generator.next (<anonymous>)
    at go$readdir$cb (C:\Users\chdietsc\source\repos\mason-ui\node_modules\graceful-fs\graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at walk (C:\Users\chdietsc\source\repos\mason-ui\node_modules\builder-util\out\fs.js:123:16)
    at copyDir (C:\Users\chdietsc\source\repos\mason-ui\node_modules\builder-util\src\fs.ts:297:10)
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\fileMatcher.ts:332:18
    at Generator.next (<anonymous>)
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\fileMatcher.ts:310:10
From previous event:
    at copyFiles (C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\fileMatcher.ts:310:26)
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\platformPackager.ts:236:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at LinuxPackager.doPack (C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.pack (C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Users\chdietsc\source\repos\mason-ui\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\Users\chdietsc\source\repos\mason-ui\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Users\chdietsc\source\repos\mason-ui\node_modules\electron-builder\src\builder.ts:227:10)
    at then (C:\Users\chdietsc\source\repos\mason-ui\node_modules\electron-builder\src\cli\cli.ts:46:19)

**Comment by cdietschrun** [comment]
Problem repeats on 20.39.0, latest as of now

**Comment by cdietschrun** [comment]
I notice that trace seems to end in .env, and I have this in my package.json:

`    "extraFiles": [
      "**/.env"
    ],
    "files": {
      "filter": [
        "out-tsc/**",
        "html/**",
        "css/**",
        "fonts/**",
        "**/.env"
      ]
    },`

Which I'm using to include a .env file in my installer. Is something wrong there that I shouldn't do?

**Comment by cdietschrun** [comment]
This seems to create a snap for me using my Azure DevOps builds on linux machines, so this is probably a non-issue. It was my understanding that snaps or AppImages could be created on Windows, maybe not.
