### ISSUE TITLE
app-update.yml is missing in pacman builds

### ISSUE THREAD

**Issue by hzeroo** [electron-userland/electron-builder#3844]
Version:
    electron-builder: 20.39.0
    electron-updater: 4.0.6

    Target:
    pacman

```bash
23:18:31.480 › App starting...
23:18:31.645 › Checking for update
23:18:31.883 › Checking for updates
23:18:32.216 › Error: Error: ENOENT: no such file or directory, open '/opt/Twitch Desktop/resources/app-update.yml'
at /opt/Twitch Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:460:27
at Generator.next (<anonymous>)
From previous event:
at AppImageUpdater.loadUpdateConfig (/opt/Twitch Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:456:33)
at Lazy.AppUpdater.configOnDisk (/opt/Twitch Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:142:43)
at Lazy.get value [as value] (/opt/Twitch Desktop/resources/app.asar/node_modules/lazy-val/src/main.ts:18:25)
at /opt/Twitch Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:46
at Generator.next (<anonymous>)
at runCallback (timers.js:694:18)
at tryOnImmediate (timers.js:665:5)
at processImmediate (timers.js:647:5)
From previous event:
at AppImageUpdater.getUpdateInfoAndProvider (/opt/Twitch Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
at /opt/Twitch Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
at Generator.next (<anonymous>)
From previous event:
at AppImageUpdater.doCheckForUpdates (/opt/Twitch Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
at AppImageUpdater.checkForUpdates (/opt/Twitch Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
at App.<anonymous> (/opt/Twitch Desktop/resources/app.asar/main.ts:60:19)
at App.emit (events.js:187:15)
23:18:32.218 › Error in auto-updater. Error: ENOENT: no such file or directory, open '/opt/Twitch Desktop/resources/app-update.yml'
```

Appimage target update works without problems.

**Comment by hzeroo** [comment]
Maybe related to https://github.com/electron-userland/electron-builder/issues/2667

**Comment by develar** [comment]
By intention auto-update is supported only for some formats (on Linux — AppImage). To update pacman/deb/snap/etc please use platform native solutions (package manager).
