### ISSUE TITLE
TypeError: Cannot read property 'from' of null

### ISSUE THREAD

**Issue by posidron** [electron-userland/electron-builder#3849]
* **Version**: 20.39.0, 20.40.2

* **Target**: MacOS, Linux, Windows x64

Hey, I am struggling for this now since some time and can't exactly figure out what's wrong here. Which leads to me to think this may a bug. I switched to the JS API cause I got the warning about `yargs`.

```
win64: Platform.WINDOWS.createTarget(['zip'], Arch.x64),
linux64: Platform.LINUX.createTarget(['AppImage'], Arch.x64),
macos: Platform.MAC.createTarget(['dmg'], Arch.x64)

[...]

const config = {
  // [...]
  files: [
    'dist/main/main.js', 
    'dist/renderer/production', 
    'build', 
    '!**/*.map'
  ],
  directories: {
    output: 'releases/${os}/${arch}',
    buildResources: 'build'
  },
  compression: 'normal',
  nsis: {
    oneClick: false,
    perMachine: true,
    allowToChangeInstallationDirectory: true,
    createDesktopShortcut: 'always'
  },
  win: {},
  mac: {
    category: 'public.app-category.foo'
  },
  linux: {
    category: 'foo'
  }
}

const Build = async () => {
  console.log(`Building on platform ${process.platform} in ${process.env.NODE_ENV} mode.`)
  for (let target of targets) {
    await builder
      .build({ targets: target, config: config })
      .then(files => {
        console.log('🙌   Build is OK!')
        files.map(file => console.log(`• ${file}`))
      })
      .catch(error => {
        console.log(`🔥   Build is toast!\n${error}`)
      })
  }
}

Build()
```

I am running Build() for my "macos" and "linux" targets. They both work individually but not consecutively within the loop.

```
TypeError: Cannot read property 'from' of null
    at normalizeFiles (node_modules/app-builder-lib/src/util/config.ts:130:14)
    at doMergeConfigs (node_modules/app-builder-lib/src/util/config.ts:178:3)
    at node_modules/app-builder-lib/src/util/config.ts:83:10
From previous event:
    at getConfig (node_modules/app-builder-lib/out/util/config.js:111:22)
    at node_modules/app-builder-lib/src/packager.ts:307:33
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:443:21)
From previous event:
    at Packager.build (node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (node_modules/app-builder-lib/src/index.ts:59:28)
    at Object.build (node_modules/electron-builder/src/builder.ts:228:10)
    at Build (build.js:63:19)
```

**Comment by posidron** [comment]
Okay, as usual you write stuff down and then a solution pop's up.

It works with:
```
files: ['dist/main/main.js', { from: 'dist/renderer/production' }, { from: 'build' }, '!**/*.map'],
```

But could you please explain why this is the case? Why does the above work individually for each target but if I call `builder.build` consecutively with different targets it doesn't?

**Comment by dertieran** [comment]
Just for anyone having the same issue in the future. The problem is that the `config` object is
mutated when running `build`. So using the same `config` object again might produces an invalid
`config` object the second time.

I didn't look into what objects are mutated and just deep cloned the `config` object before each
call to `build`.

So something like:
```js
for (const target of targets) {
    const cloned = JSON.parse(JSON.stringify(config));
    await build({ targets: target, config: cloned });
}
```

**Comment by sukolenvo** [comment]
I had same issue. Here is `files.from` is unset:
https://github.com/electron-userland/electron-builder/blob/39faac55ff669a0db2c4cae7e954b1252ed9c404/packages/app-builder-lib/src/util/config.ts#L134
