### ISSUE TITLE
Can't build windows bigger application

### ISSUE THREAD

**Issue by ecourdoisy** [electron-userland/electron-builder#3916]
Hello, I'm on mac and i'm using electron builder to build mac and windows. Mac is ok. On Windows, when application is small (I remove videos) I can build it and it's working fine. But now I need to Build with video (3Go) and I've an error when I make build.

My config is : 
```
"win": {
      "target": "portable",
      "icon": "build/icon.ico"
    }
```

├─ electron-builder@20.40.2
└─ electron@4.2.2

and error is : 

```
Error: /xxx/Library/Caches/electron-builder/nsis/nsis-3.0.3.2/mac/makensis exited with code 1
Output:
Command line defined: "APP_ID=xxx"
Command line defined: "APP_GUID=cf852852-f50d-58a7-b7be-0df6f7c04ea3"
Command line defined: "UNINSTALL_APP_KEY=cf852852-f50d-58a7-b7be-0df6f7c04ea3"
Command line defined: "PRODUCT_NAME=xx"
Command line defined: "PRODUCT_FILENAME=xx"
Command line defined: "APP_FILENAME=xxx"
Command line defined: "APP_DESCRIPTION=xxx"
Command line defined: "VERSION=1.0.0"
Command line defined: "PROJECT_DIR=/xxx"
Command line defined: "BUILD_RESOURCES_DIR=/xxx/build"
Command line defined: "APP_PACKAGE_NAME=xxx"
Command line defined: "APP_64=/xxx/dist/xxx-1.0.0-x64.nsis.7z"
Command line defined: "APP_64_NAME=xxx-1.0.0-x64.nsis.7z"
Command line defined: "APP_64_HASH=689AEA0A5E130DA33F3A631A546BEE8DD24C50A98BCC2EB4102F21BD2311D39B654D1756114CD68B031F799E7C25346CC432207CD408F9F5EB15EE28DCEE17DA"
Command line defined: "COMPANY_NAME=xxx"
Command line defined: "APP_PRODUCT_FILENAME=xx"
Command line defined: "APP_INSTALLER_STORE_FILE=xxx-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "REQUEST_EXECUTION_LEVEL=user"
Command line defined: "ESTIMATED_SIZE=3300006"
Command line defined: "COMPRESS=auto"
Processing script file: "<stdin>" (UTF8)

Error output:
File: failed creating mmap of "xxx/xxx-x64.nsis.7z"
Error in macro x64_app_files on macroline 1
Error in macro extractEmbeddedAppPackage on macroline 17
Error in script "<stdin>" on line 108 -- aborting creation process

    at ChildProcess.childProcess.once.code (xxx/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:285:13)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
error Command failed with exit code 1.

```

I already clean caches

Thanks a lot !

**Comment by markjongkind** [comment]
I have the exact same problem: building without video-files is OK, but building with the video files included results in this error. Total size of my videos is 3.7GB (largest single file is 278MB).

I guess it has to do with a file size limit on Windows (2 GB). If I use nsis-web as a target, I get no errors.

**Comment by ninhhoang0207** [comment]
You can separate your app into 2 parts( app to run and your videos or files). using "nsis zip plugin" to zip your videos and your files. After you finish installing your app, you just need to install the zip.

**Comment by Usnul** [comment]
Same issue here, pretty significant impact.
