### ISSUE TITLE
Building on Windows fails with Update.com Error Code

### ISSUE THREAD

**Issue by framerate** [electron-userland/electron-builder#392]
Running `npm run dist` on windows exists with the following error:

`\node_modules\electron-winstaller-fixed\vendor\Update.com failed with exit code: 4294967295`

`npm run pack` works just fine. I'm trying to create an MSI and work towards windows autoupdating.

Running the latest Windows Technical Preview, in case that matters. Tried both `@latest` and @3.11.0 suggested in #366

**Comment by develar** [comment]
Please attach `node_modules/electron-winstaller-fixed/vendor/SquirrelSetup.log`.

**Comment by framerate** [comment]
Assuming this is the relevant part:

```
2016-05-10 19:33:06> Unhandled exception: System.ComponentModel.DataAnnotations.ValidationException: Description is required.
   at NuGet.Manifest.Validate(Manifest manifest)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleasePackage.get_SuggestedReleaseFileName()
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

**Comment by develar** [comment]
Weird, but it is Windows :( Reopened — must be checked on our side, not on *** Windows *** tool.

**Comment by framerate** [comment]
Gotcha. Let me know how I can help!

**Comment by marcopiraccini** [comment]
We have the  same issue, the strange thing is that all worked until yesterday...
@framerate what does it means "EDIT: Found it, http icons only for windows. Weird"?
I'm using https:// for the icon URL. is this the problem?

**Comment by develar** [comment]
@marcopiraccini The same error in the `node_modules/electron-winstaller-fixed/vendor/SquirrelSetup.log`?

**Comment by marcopiraccini** [comment]
Here, on Windows 7 32 bit. Yesterday it worked!

2016-05-13 04:23:04> Program: Starting Squirrel Updater: --releasify C:\app\dist\win\TestApp-0.1.6-full.nupkg --releaseDir C:\app\dist\win --loadingGif C:\app\build\loading-splash.png --no-msi
2016-05-13 04:23:06> Program: Bootstrapper EXE found at:C:\app\node_modules\electron-builder\node_modules\electron-winstaller-fixed\vendor\Setup.exe
2016-05-13 04:23:09> Unhandled exception: System.IO.FileNotFoundException: Could not find file 'C:\app\dist\win\TestApp-0.1.6-full.nupkg'.
File name: 'C:\app\dist\win\TestApp-0.1.6-full.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.ReleaseEntry.GenerateFromFile(String path, String baseUrl)
   at Squirrel.Update.Program.<>c__DisplayClass10_0.<ReleasifyElectron>b__0(String packageFilename)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String bootstrapperExe, String backgroundGif, String baseUrl, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

**Comment by marcopiraccini** [comment]
(Indeedm the file ` 'C:\app\dist\win\TestApp-0.1.6-full.nupkg'` does not exists...)

**Comment by develar** [comment]
@marcopiraccini As a workaround, set electron-buidler version to `3.20.0`. Does it help?

> (Indeedm the file 'C:\app\dist\win\TestApp-0.1.6-full.nupkg' does not exists...)
What exists? Please list files.

**Comment by marcopiraccini** [comment]
Under "win"? Nothing.
In the xxx-win32-ia32 there is all the working application

**Comment by marcopiraccini** [comment]
Is `electron-builder` nos supporting ia32 anymore? https://github.com/electron-userland/electron-builder/commit/079989acee340512d9834e5a210b98561289fcb9#diff-6456376d7ed2e6f2d66ffc860e13af6eR55

**Comment by develar** [comment]
@marcopiraccini Fully supported, it is just a warning. Try to set version to 3.20.0 until I your issue is not fixed.

**Comment by marcopiraccini** [comment]
The same. Also with 3.17.0 (which used to work 3 days ago!)
It seems something broke on a recursive dependency.

**Comment by develar** [comment]
@marcopiraccini Reproduced. Fix will be soon. Our test suite didn't check ia32 and error was not catched during CI run.

**Comment by marcopiraccini** [comment]
Tnx very much :)

**Comment by develar** [comment]
@marcopiraccini BTW, may be you can just migrate to x64 ;)?

**Comment by marcopiraccini** [comment]
I cannot, ia32 it's a requirement :(

**Comment by marcopiraccini** [comment]
Just curiosity: what's the cause? It's a transitive dependency that changed?

**Comment by marcopiraccini** [comment]
@develar Tested with v3.22.1, but I have the same problem :(

**Comment by marcopiraccini** [comment]
Summarizing, Windows 7 ia32, using (main `package.json`, not the app one): 
```
    "electron-builder": "^3.22.1",
    "electron-prebuilt": "^0.37"
```
`build --platform=win32 --arch=ia32`       -> Creates the xxx-win32-ia32 folder. Ok
`build --platform=win32 --arch=ia32  -d`  -> Ceates the folder in the image:
 
![builder_1](https://cloud.githubusercontent.com/assets/668050/15257311/000a870e-1946-11e6-8757-cd4bec04731c.png)

...with `win-ia32` empty, and `win-ia32-unpacked` with this content:
 
![builder_2](https://cloud.githubusercontent.com/assets/668050/15257367/4d608968-1946-11e6-878f-84f892dbce0e.png)

**Comment by marcopiraccini** [comment]
(why this is not labelled as "bug"? )

**Comment by develar** [comment]
@marcopiraccini Because this issue about "Apparently a blank package.json description shits the bed. " Please try version `3.26.0` and open new issue in case of error (and please attach Squirrel log file and output).

**Comment by L3V147H4N** [comment]
Still doesn't work on 3.26.3
