### ISSUE TITLE
Timeout errors building Windows on Travis OS X image - context deadline exceeded on steps with Wine

### ISSUE THREAD

**Issue by florisporro** [electron-userland/electron-builder#3928]
### What?

Consistently failing builds with timeout errors when building Windows on a Travis OS X image.

Mac builds seem to succeed, failures are usually just after the Mac builds. In some cases, electron-builder stops producing output.

Builds are succeeding on my Mac (Mojave, OS X v10.14.2, xCode v10.1, Node v8.12.0). I'm running into this issue setting up Travis for the first time to build a pre-existing project.

### The errors I've received:

* error: context deadline exceeded
* No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
* error: signal: killed

### Targets

* OS X
* Windows

Building on Travis Mac image.

### Things I've tried

* Upgrading electron-builder from 20.38.5 to 20.41.0
* Manually clearing cache
* Restarting the build a few times
* Waiting overnight to rule out temporary outages
* Switching NodeJS version from v10 to v8 (in line with my local version)
* Switching Travis image from xcode9.4 to xcode10.1 (again, in line with my local version)

### Travis config

```yml
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      language: node_js
      node_js: "8"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - yarn

script:
  - npm run build:webpack
  - DEBUG=electron-builder npm run build:electron:distributable

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
```

### Relevant log output

```bash
$ electron-builder -mw
  • electron-builder version=20.41.0
  • artifacts will be published if draft release exists reason=CI detected
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=darwin arch=x64
  • rebuilding native dependency name=fsevents
  • packaging       platform=darwin arch=x64 electron=4.0.1 appOutDir=/Users/travis/build/florisporro/Distributions/mac
  • asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available
  • signing         file=/Users/travis/build/florisporro/Distributions/mac/Holographics.app identityName=Developer ID Application: Floris Porro (97J6P3WCEN) identityHash=CDEB49228B1C08357637FF5916A6EC354BF89E7F provisioningProfile=none
  • building        target=macOS zip arch=x64 file=/Users/travis/build/florisporro/Distributions/Holographics-1.2.3-mac.zip
  • building        target=DMG arch=x64 file=/Users/travis/build/florisporro/Distributions/Holographics-1.2.3.dmg
  • rebuilding native production dependencies platform=win32 arch=x64
  • rebuilding native dependency name=fsevents
  • packaging       platform=win32 arch=x64 electron=4.0.1 appOutDir=/Users/travis/build/florisporro/Distributions/win-unpacked
  • asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available
  • downloading               parts=4 size=26 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/wine-2.0.3-mac-10.13/wine-2.0.3-mac-10.13.7z
  • downloaded                duration=3.764s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/wine-2.0.3-mac-10.13/wine-2.0.3-mac-10.13.7z
  • building embedded block map file=/Users/travis/build/florisporro/Distributions/Holographics-1.2.3-mac.zip
  • publishing      publisher=S3 (bucket: holographics-distribution)
  • not published to S3 file=/Users/travis/build/florisporro/Distributions/Holographics-1.2.3-mac.zip reason=current build is not for a git tag publishPolicy=onTagOrDraft
  ⨯ error: context deadline exceeded
path: /Users/travis/.cache/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine
args: /Users/travis/.cache/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine /Users/travis/.cache/electron-builder/winCodeSign/winCodeSign-2.4.0/rcedit-ia32.exe /Users/travis/build/florisporro/Distributions/win-unpacked/Holographics.exe --set-version-string FileDescription Holographics --set-version-string ProductName Holographics --set-version-string LegalCopyright Copyright © 2019 Stream My Event --set-file-version 1.2.3.8 --set-product-version 1.2.3.8 --set-version-string InternalName Holographics --set-version-string OriginalFilename  --set-version-string CompanyName Stream My Event --set-icon /Users/travis/build/florisporro/holographics/build/icon.ico
output: 
error output:
github.com/develar/app-builder/pkg/util.Execute
	/Volumes/data/Documents/app-builder/pkg/util/util.go:75
github.com/develar/app-builder/pkg/wine.execWine
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:92
github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:43
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:80
runtime.main
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337
Error: /Users/travis/build/florisporro/holographics/node_modules/app-builder-bin/mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/travis/build/florisporro/holographics/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.signAndEditResources (/Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (/Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/winPackager.ts:363:21)
    at go$readdir$cb (/Users/travis/build/florisporro/holographics/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at /Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/winPackager.ts:355:73)
    at /Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/platformPackager.ts:250:16
From previous event:
    at WinPackager.doPack (/Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/packager.ts:430:24
From previous event:
    at Packager.doBuild (/Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/packager.ts:366:57
From previous event:
    at Packager._build (/Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/travis/build/florisporro/holographics/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/travis/build/florisporro/holographics/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/travis/build/florisporro/holographics/node_modules/electron-builder/src/cli/cli.ts:49:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn run build:electron:distributable" exited with 1.
```

### Full log in debug mode

[buildlog.txt](https://github.com/electron-userland/electron-builder/files/3227304/buildlog.txt)

**Comment by artemv** [comment]
I've encountered this too on CI, reproducing on some builds - apparently depends on how busy the machine is atm.
What helped me is changing from 
`yarn electron-builder -mw`
to doing that one by one:
```
yarn electron-builder -m
yarn electron-builder -w
```

**Comment by artemv** [comment]
> asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available

This was likely the reason - at least in my case the error went away in `yarn electron-builder -mwl` after I made it `asar: true`.
