### ISSUE TITLE
Can't build for Windows from linux

### ISSUE THREAD

**Issue by michibat01** [electron-userland/electron-builder#3949]
* **Version**: 20.43.0

* **Target**: win 64bit

I suppose it stopped working after I added:
` "build": {
    "appId": "com.xxx.xxx",
    "extraResources": [
      "**/*.mp4"
    ]
  }`
to the package.json

gives me this error:

Processing script file: "\<stdin\>" (UTF8)
  • exited          command=makensis code=null pid=31987
  • async task error error=
                       Error: /home/michelangelo/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis exited with code null
                           at ChildProcess.childProcess.once.code (/home/michelangelo/xxx/xxx/node_modules/builder-util/src/util.ts:244:14)
                           at Object.onceWrapper (events.js:277:13)
                           at ChildProcess.emit (events.js:189:13)
                           at maybeClose (internal/child_process.js:970:16)
                           at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Error: /home/michelangelo/.cache/electron-builder/nsis/nsis-3.0.3.2/linux/makensis exited with code null
    at ChildProcess.childProcess.once.code (/home/michelangelo/xxx/xxx/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

**Comment by sharunspi** [comment]
is there any solution for this
