### ISSUE TITLE
Cannot upload prerelease version

### ISSUE THREAD

**Issue by mbrainiac** [electron-userland/electron-builder#395]
```
Packaging app for platform win32 x64 using electron v0.37.8
Release v3.0.0-beta.2 doesn't exists, creating one
Error: ENOENT: no such file or directory, stat 'C:\projects\app\dist\win-x64\App-3.0.0-beta.2-full.nupkg'
    at Error (native)
From previous event:
    at GitHubPublisher.<anonymous> (C:\projects\app\node_modules\electron-builder\src\gitHubPublisher.ts:77:32)
    at [object Generator].next (native)
From previous event:
    at tsAwaiter (C:\projects\app\node_modules\electron-builder\src\awaiter.ts:10:47)
    at GitHubPublisher.upload (C:\projects\app\node_modules\electron-builder\src\gitHubPublisher.ts:69:51)
    at C:\projects\app\node_modules\electron-builder\src\builder.ts:80:72
From previous event:
    at EventEmitter.<anonymous> (C:\projects\app\node_modules\electron-builder\src\builder.ts:80:16)
    at emitOne (events.js:90:13)
    at EventEmitter.emit (events.js:182:7)
    at WinPackager.dispatchArtifactCreated (C:\projects\app\node_modules\electron-builder\src\platformPackager.ts:101:28)
    at WinPackager.<anonymous> (C:\projects\app\node_modules\electron-builder\src\winPackager.ts:178:12)
    at [object Generator].next (native)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at tsAwaiter (C:\projects\app\node_modules\electron-builder\src\awaiter.ts:10:47)
    at Object.build (C:\projects\app\node_modules\electron-builder\src\builder.ts:30:59)
    at Object.<anonymous> (C:\projects\app\node_modules\electron-builder\src\build-cli.ts:47:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

The output file is App-3.0.0-beta2-full.nupkg, (no dot at `beta`), but the builder trying to upload file App-3.0.0-beta.2-full.nupkg.

**Comment by develar** [comment]
electron-builder version?

**Comment by mbrainiac** [comment]
3.20.0

**Comment by develar** [comment]
How version is specified in your package.json?

**Comment by mbrainiac** [comment]
My version is ```3.0.0-beta.2```, 
I think the problem is winstaller-fixed removed the dot before creating nupkg, and git uploader use the file with version string from package.json.

**Comment by develar** [comment]
It is a regression in the last release, fix in progress.

**Comment by develar** [comment]
Does it work before?

**Comment by develar** [comment]
```
   public string SuggestedReleaseFileName {
            get {
                var zp = new ZipPackage(InputPackageFile);
                return String.Format("{0}-{1}-full.nupkg", zp.Id, zp.Version);
            }
        }
```

installer-fixed behaviour correct according to *** Squirrel.Windows *** nuget *** transformation.
