### ISSUE TITLE
总是构建不成

### ISSUE THREAD

**Issue by mutour123** [electron-userland/electron-builder#3957]
take it away `electron-builder`

  • electron-builder version=20.43.0
Error: Invalid version: "、"
    at Object.fixVersionField (E:\ynelectron\my-project\node_modules\normalize-package-data\lib\fixer.js:191:13)
    at E:\ynelectron\my-project\node_modules\normalize-package-data\lib\normalize.js:32:38
    at Array.forEach (<anonymous>)
    at normalize (E:\ynelectron\my-project\node_modules\normalize-package-data\lib\normalize.js:31:15)
    at E:\ynelectron\my-project\node_modules\app-builder-lib\src\util\packageMetadata.ts:13:3
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
From previous event:
    at _readPackageJson (E:\ynelectron\my-project\node_modules\app-builder-lib\out\util\packageMetadata.js:71:27)
    at readPackageJson (E:\ynelectron\my-project\node_modules\app-builder-lib\out\util\packageMetadata.js:58:27)
    at E:\ynelectron\my-project\node_modules\app-builder-lib\src\packager.ts:304:52
    at Generator.next (<anonymous>)

**Comment by wangjue666** [comment]
版本号没填写正确
