### ISSUE TITLE
Error: Application entry file "dist\electron\main.js"  错误

### ISSUE THREAD

**Issue by xiatiantiantian** [electron-userland/electron-builder#3969]
I try build this project  https://github.com/WhiteMinds/LiveAutoRecord  
Can't build .  (WIN10 64  1903)

PS D:\electron-builder\LiveAutoRecord\LiveAutoRecord> yarn dist
yarn run v1.16.0
warning ....\package.json: No license field
$ electron-builder
• electron-builder version=20.43.0
• loaded configuration file=package.json ("build" field)
• electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script "postinstall": "electron-builder install-app-deps" to your package.json`
• writing effective config file=build\builder-effective-config.yaml
• rebuilding native production dependencies platform=win32 arch=x64
• rebuilding native dependency name=sqlite3
• packaging platform=win32 arch=x64 electron=5.0.1 appOutDir=build\win-unpacked
Error: Application entry file "dist\electron\main.js" in the "D:\electron-builder\LiveAutoRecord\LiveAutoRecord\build\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
at error (D:\electron-builder\node_modules\app-builder-lib\out\asar\asarFileChecker.js:44:14)
at D:\electron-builder\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:30:4
at Generator.next ()
at D:\electron-builder\node_modules\graceful-fs\polyfills.js:285:20
at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
at _checkFileInArchive (D:\electron-builder\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:36:17)
at checkFileInArchive (D:\electron-builder\node_modules\app-builder-lib\out\asar\asarFileChecker.js:40:30)
at D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:409:13
at Generator.next ()
From previous event:
at WinPackager.checkFileInPackage (D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:406:110)
at D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:460:16
at Generator.next ()
at D:\electron-builder\node_modules\graceful-fs\polyfills.js:285:20
at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
at WinPackager.sanityCheckPackage (D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:446:92)
at D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:249:16
at Generator.next ()
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
From previous event:
at WinPackager.doPack (D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
at D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:113:16
at Generator.next ()
From previous event:
at WinPackager.pack (D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
at D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:430:24
at Generator.next ()
at xfs.stat (D:\electron-builder\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
at D:\electron-builder\node_modules\graceful-fs\polyfills.js:285:20
at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
at Packager.doBuild (D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:396:24)
at D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:366:57
at Generator.next ()
at D:\electron-builder\node_modules\graceful-fs\graceful-fs.js:111:16
at D:\electron-builder\node_modules\graceful-fs\graceful-fs.js:45:10
at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
at Packager._build (D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:335:133)
at D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:331:23
at Generator.next ()
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
From previous event:
at Packager.build (D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:288:14)
at build (D:\electron-builder\node_modules\app-builder-lib\src\index.ts:59:28)
at build (D:\electron-builder\node_modules\electron-builder\src\builder.ts:228:10)
at then (D:\electron-builder\node_modules\electron-builder\src\cli\cli.ts:49:19)
error Command failed with exit code 1.

**Comment by xiatiantiantian** [comment]
ReferenceError: __static is not defined
    at App.r (D:\electron-builder\LiveAutoRecord\LiveAutoRecord\build\win-unpacked\resources\app.asar\dist\electron\main.js:1:22899)
    at App.emit (events.js:199:15)

**Comment by huwanlong** [comment]
why?
