### ISSUE TITLE
`Error: spawn EPERM` when build Windows natively

### ISSUE THREAD

**Issue by nixklai** [electron-userland/electron-builder#3985]
* **Version**: 20.43.0

* **Electron version**: 5.0.4 (also failed on Electron 4.2.4)

* **Target**: Windows

* **Operation system**: Windows 10

* **Node.js version**: 12.0.0 (also failed on 10.16.0 and 12.4.0)

After ```electron-builder --win --ia32 --x64``` is executed, electron-builder seems to be blocked at the _building_ step and the following error is shown:
```
Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:535:9)
    at execFile (child_process.js:217:17)
    at C:\Code\myproject\node_modules\builder-util\src\util.ts:90:5
    at new Promise (<anonymous>)
    at exec (C:\Code\myproject\node_modules\builder-util\src\util.ts:89:10)
    at execWine (C:\Code\myproject\node_modules\app-builder-lib\src\wine.ts:11:12)
    at C:\Code\myproject\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:324:11
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.computeScriptAndSignUninstaller (C:\Code\myproject\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:307:121)
    at C:\Code\myproject\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:264:114
From previous event:
    at NsisTarget.buildInstaller (C:\Code\myproject\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:125:31)
    at C:\Code\myproject\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:109:18
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (C:\Code\myproject\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:107:20)
    at C:\Code\myproject\node_modules\app-builder-lib\src\packager.ts:438:36
From previous event:
    at Packager.doBuild (C:\Code\myproject\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Code\myproject\node_modules\app-builder-lib\src\packager.ts:366:57
From previous event:
    at Packager._build (C:\Code\myproject\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Code\myproject\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Packager.build (C:\Code\myproject\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\Code\myproject\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Code\myproject\node_modules\electron-builder\src\builder.ts:228:10)
    at C:\Code\myproject\node_modules\electron-builder\src\cli\cli.ts:49:19
```

The full debug output can be found [here](https://github.com/electron-userland/electron-builder/files/3302730/debug.log).

## Attempted solution
- Remove the whole `node_modules` folder and re-run `yarn`
- Updated `electron` to `4.2.4` and `5.0.4`
- Remove `build` folder, including the icons
- Remove the `cache` folder in `%userprofile%AppData\Local\electron-builder\Cache`

**Comment by nixklai** [comment]
I figured it out. The anti-virus terminated the `makensis.exe` without any warning. I later excluded the project root and everything now works as intended.
