### ISSUE TITLE
Travis CI: 7za No such file or directory

### ISSUE THREAD

**Issue by mbrainiac** [electron-userland/electron-builder#399]
electron-builder@3.21.0
node 5.10.0
npm 3.9.0

travis.yml copy from https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml

```
CI detected, so artifacts will be published if draft release exists
Rebuilding app dependencies for arch x64 to /home/travis/build/mbrainiac/pencil/app
  [36;1melectron-builder [0mSpawning /home/travis/.nvm/versions/node/v5.10.0/bin/node /home/travis/.nvm/versions/node/v5.10.0/lib/node_modules/npm/bin/npm-cli.js rebuild --production[36m +0ms[0m
  [36;1melectron-builder [0mDownload fpm from https://github.com/develar/fpm-self-contained/releases/download/v1.5.0-2.3.1/fpm-1.5.0-2.3.1-linux-x86_64.7z to /home/travis/.cache/fpm/4812-0-1463114555804.7z[36m +29ms[0m
  [36;1melectron-builder [0mSpawning /home/travis/build/mbrainiac/pencil/node_modules/7zip-bin-linux/7za x /home/travis/.cache/fpm/4812-0-1463114555804.7z -o4812-0-1463114555804 -bd -bb3[36m +2s[0m
[31mUnhandled rejection Error: spawn /home/travis/build/mbrainiac/pencil/node_modules/7zip-bin-linux/7za ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Object.spawn (/home/travis/build/mbrainiac/pencil/node_modules/electron-builder/src/util.ts:101:9)
    at /home/travis/build/mbrainiac/pencil/node_modules/electron-builder/src/fpmDownload.ts:63:14
    at [object Generator].next (native)
    at WriteStream.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at WriteStream.emit (events.js:179:7)
    at fs.js:1851:14
    at /home/travis/build/mbrainiac/pencil/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
From previous event:
    at tsAwaiter (/home/travis/build/mbrainiac/pencil/node_modules/electron-builder/src/awaiter.ts:10:47)
    at Object.build (/home/travis/build/mbrainiac/pencil/node_modules/electron-builder/src/builder.ts:30:59)
    at Object.<anonymous> (/home/travis/build/mbrainiac/pencil/node_modules/electron-builder/src/build-cli.ts:47:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3[0m
```

```
$ ls -al $TRAVIS_BUILD_DIR/node_modules/7zip-bin-linux
total 1608
drwxrwxr-x   2 travis travis    4096 May 13 07:54 .
drwxrwxr-x 254 travis travis   12288 May 13 08:50 ..
-rwxrwxr-x   1 travis travis 1620784 Mar 23 19:33 7za
-rw-rw-r--   1 travis travis      70 Apr  8 05:44 index.js
-rw-rw-r--   1 travis travis    1910 May 13 07:54 package.json

$ $TRAVIS_BUILD_DIR/node_modules/7zip-bin-linux/7za
home/travis/build.sh: line 45: /home/travis/build/mbrainiac/pencil/node_modules/7zip-bin-linux/7za: No such file or directory
```

It seems like electron-builder use 32bit version of 7za.

**Comment by develar** [comment]
Set env `USE_SYSTEM_FPM=true` as a workaround (so, ruby & fpm should be installed as before).

**Comment by mbrainiac** [comment]
@develar 
Why not use system 7za, install p7z easier than ruby and fpm.

**Comment by mitchhentges** [comment]
I'm not seeing the `7za` binary in `7zip-bin-linux@1.0.1`:

```
mitch@SCRATCH-DESKTOP ~/d/j/n/7zip-bin-linux (electron-builder)> pwd
/home/mitch/dev/james/node_modules/7zip-bin-linux
mitch@SCRATCH-DESKTOP ~/d/j/n/7zip-bin-linux (electron-builder)> ls -al
total 48
drwxr-xr-x   2 mitch mitch  4096 May 13 13:36 ./
drwxr-xr-x 779 mitch mitch 32768 May 13 13:36 ../
-rw-r--r--   1 mitch mitch    84 May 13 12:15 index.js
-rw-r--r--   1 mitch mitch  1827 May 13 13:36 package.json

**Comment by develar** [comment]
Problem not in the binary. Something strange on Travis — i.e. our tests passed on one CI server, app correctly builds in the docker container, desktop linux machine, but my app on Travis failed. ENOENT doesn't mean that 7za not found, it also means that some argument is invalid.

**Comment by mitchhentges** [comment]
It's building again for me, thanks!

**Comment by develar** [comment]
@mitchhentges Wait, `USE_SYSTEM_7ZA` helps you?

**Comment by mitchhentges** [comment]
Oh, sorry, no, the update to `7zip-bin-linux` did. As of `1.0.2`, the `7za` binary is available

**Comment by develar** [comment]
Error: 7za out dir is not created by 7za, we must create it.

Why error was not catched by CI tests?

Our CI tests download fpm concurrently -> one process creates 7za fpm out dir -> second process use it -> leader wins -> no 7za error

Docker build uses mapped fpm cache on host machine -> no fpm download -> no error.

Why I publish release if my Travis build was failed as well — because Travis was currently down and it was not clear :(

**Comment by notblank00** [comment]
Same problem in a GitLab runner

**Comment by aak1247** [comment]
> Same problem in a GitLab runner

Same in gitlab runner (docker executer).
