### ISSUE TITLE
 Unexpected token < in JSON

### ISSUE THREAD

**Issue by xxyyzz2050** [electron-userland/electron-builder#3991]
when I compile my app whith electron-build, I face an error: Unresolved module @angular/http
so I temporary set ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true as a workarround, but it gave me another error:

```
SyntaxError: Unexpected token < in JSON at position 602
    at JSON.parse (<anonymous>)
    at then.it (node_modules\app-builder-lib\src\fileTransformer.ts:39:45)
    at tryCatcher (node_modules\bluebird-lst\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules\bluebird-lst\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (node_modules\bluebird-lst\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (node_modules\bluebird-lst\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (node_modules\bluebird-lst\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (node_modules\bluebird-lst\node_modules\bluebird\js\release\promise.js:643:18)
    at node_modules\bluebird-lst\node_modules\bluebird\js\release\nodeback.js:42:21
    at node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
From previous event:
    at file (node_modules\app-builder-lib\src\fileTransformer.ts:39:10)
    at _bluebirdLst.default.filter (node_modules\app-builder-lib\src\util\appFileCopier.ts:117:30)
From previous event:
    at node_modules\app-builder-lib\src\util\appFileCopier.ts:111:25
    at Generator.next (<anonymous>)
From previous event:
    at transformFiles (node_modules\app-builder-lib\out\util\appFileCopier.js:221:26)
    at node_modules\app-builder-lib\src\platformPackager.ts:323:19
    at Generator.next (<anonymous>)
From previous event:
    at node_modules\app-builder-lib\src\platformPackager.ts:320:27
From previous event:
    at WinPackager.copyAppFiles (node_modules\app-builder-lib\src\platformPackager.ts:321:10)
    at node_modules\app-builder-lib\src\platformPackager.ts:214:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.doPack (node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Packager.doBuild (node_modules\app-builder-lib\src\packager.ts:396:24)
    at node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at node_modules\graceful-fs\graceful-fs.js:111:16
    at node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at Packager._build (node_modules\app-builder-lib\src\packager.ts:335:133)
    at node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (node_modules\app-builder-lib\src\index.ts:59:28)
    at build (node_modules\electron-builder\src\builder.ts:228:10)
    at then (node_modules\electron-builder\src\cli\cli.ts:49:19)
```

repo: https://github.com/xxyyzz2050/eldeebCMS

package.json:
```
{
  "name": "eldeeb-cms",
  "version": "0.0.1",
  "scripts": {
    "start": "npm run build  && npm run serve:firebase",
    "start-dev": "npm run build-dev  && npm run serve:firebase",
    "build": "npm run build:browser && npm run build:server && npm run webpack:server && npm run build:firebase",
    "build-dev": "npm run build:browser-dev && npm run build:server-dev && npm run webpack:server && npm run build:firebase-dev ",
    "start:electron": "npm run build:electron && npx electron projects/electron",
    "build:browser": "ng build --prod",
    "build:browser-dev": "ng build --prod=false",
    "build:server": "ng run eldeebCMS:server:production",
    "build:server-dev": "ng run eldeebCMS:server",
    "build:firebase": "npm --prefix ./firebase run build --prod",
    "build:firebase-dev": "npm --prefix ./firebase run build",
    "build:electron": "tsc --p projects/electron ",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:server": "nodemon dist/server --inspaect --open --watch",
    "serve:browser": "ng serve --open --watch",
    "serve:firebase": "npx firebase serve --token 1/-cuYL8hksXU161i1XHw2bsyx0jckZ5PTFCBMCt-ZVUY",
    "webpack": "npm run webpack:server",
    "serve": "npm run serve:server",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "doc": "npx compodoc -p package.json",
    "android": "tns run android --bundle",
    "ios": "tns run ios --bundle",
    "mobile": "tns run --bundle",
    "preview": "tns preview --bundle",
    "deploy:github": "ng build --prod --output-path docs --base-href /eldeebCMS/",
    "deploy:firebase": "npx firebase deploy  --token 1/-cuYL8hksXU161i1XHw2bsyx0jckZ5PTFCBMCt-ZVUY",
    "all": "npm run start && npm run deploy:firebase && npm run deploy:github && mobile && npm run build:electron && npm run compile:electron",
    "check": "npx npm-check -u",
    "compile:electron": "set ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true && electron-builder"
  },
  "private": false,
  "dependencies": {
    "@angular/animations": "~8.1.0-next.1",
    "@angular/cdk": "~8.0.0",
    "@angular/common": "~8.1.0-next.1",
    "@angular/compiler": "~8.1.0-next.1",
    "@angular/core": "~8.1.0-next.1",
    "@angular/fire": "^5.2.1",
    "@angular/forms": "~8.1.0-next.1",
    "@angular/material": "^8.0.0",
    "@angular/material-moment-adapter": "^8.0.0",
    "@angular/platform-browser": "~8.1.0-next.1",
    "@angular/platform-browser-dynamic": "~8.1.0-next.1",
    "@angular/platform-server": "~8.1.0-next.1",
    "@angular/router": "~8.1.0-next.1",
    "@compodoc/compodoc": "^1.1.9",
    "@nativescript/schematics": "^0.6.0",
    "@nguniversal/express-engine": "^7.1.1",
    "@nguniversal/module-map-ngfactory-loader": "0.0.0",
    "@ngx-formly/core": "^5.1.1",
    "@ngx-formly/material": "^5.1.1",
    "core-js": "^2.5.4",
    "cors": "^2.8.5",
    "devextreme": "latest",
    "devextreme-angular": "latest",
    "devextreme-schematics": "^1.0.7",
    "express": "^4.15.2",
    "firebase": "^6.1.1",
    "firebase-admin": "^8.1.0",
    "firebase-functions": "^3.0.1",
    "firebase-tools": "^7.0.0",
    "hammerjs": "^2.0.8",
    "moment": "^2.24.0",
    "mongoose": "^5.5.11",
    "nativescript-angular": "~7.2.0",
    "nativescript-theme-core": "~1.0.4",
    "ng-katex": "^1.2.1",
    "npm-check": "^5.9.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.2",
    "shortid": "^2.2.14",
    "tns-core-modules": "~5.2.0",
    "tslib": "^1.10.0",
    "xmlhttprequest": "^1.8.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular-devkit/build-ng-packagr": "~0.800.0",
    "@angular/cli": "~8.0.0",
    "@angular/compiler-cli": "~8.1.0-next.1",
    "@angular/language-service": "~8.1.0-next.1",
    "@nativescript/schematics": "~0.4.0",
    "@types/electron": "^1.6.10",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/mongodb": "^3.1.26",
    "@types/mongoose": "^5.3.27",
    "@types/node": "^12.0.0",
    "@types/shortid": "0.0.29",
    "bufferutil": "^4.0.1",
    "codelyzer": "^5.0.1",
    "devextreme-cli": "latest",
    "electron": "^5.0.5",
    "electron-builder": "^20.44.4",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "nativescript-dev-webpack": "^0.20.0",
    "ng-packagr": "^5.1.0",
    "nodemon": "^1.19.0",
    "protractor": "~5.4.0",
    "ts-loader": "^5.2.0",
    "ts-node": "~7.0.0",
    "tsconfig-paths-webpack-plugin": "^3.2.0",
    "tsickle": "^0.35.0",
    "tslint": "~5.11.0",
    "typescript": "~3.4.5",
    "utf-8-validate": "^5.0.2",
    "webpack-cli": "^3.1.0",
    "ws": "^7.0.0",
    "xhr2": "^0.2.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/xxyyzz2050/eldeebCMS"
  },
  "author": "eldeeb<facebook.com/eng.dibo>",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/xxyyzz2050/eldeebCMS"
  },
  "homepage": "https://github.com/xxyyzz2050/eldeebCMS#readme",
  "browser": {
    "fs": false,
    "path": false,
    "os": false
  },
  "compodoc": {
    "output": "dist/docs",
    "tsconfig": "tsconfig.json",
    "open": true,
    "port": 4200,
    "watch": true,
    "exportFormat": "html",
    "language": "en-US",
    "theme": "material",
    "hideGenerator": true,
    "gaID": ""
  },
  "nativescript": {
    "id": "org.nativescript.ngsample"
  },
  "build": {
    "appId": "com.eldeebcms",
    "asar": true,
    "copyright": "eldeebCMS ©2019.",
    "directories": {
      "buildResources": "resources",
      "output": "dist/electron/app"
    },
    "files": [
      "dist/electron"
    ],
    "dmg": {
      "contents": [
        {
          "x": 110,
          "y": 150
        },
        {
          "x": 240,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "linux": {
      "target": [
        "AppImage",
        "deb"
      ]
    },
    "win": {
      "target": "NSIS",
      "icon": "build/icon.ico"
    },
    "mac": {
      "category": "public.app-category.productivity",
      "artifactName": "${productName}-${version}-${arch}.${ext}"
    }
  }
}
```

**Comment by RiasJairoudieh** [comment]
This might be related to the @schematics/angular version (fx required within @angular/pwa).
On older versions of schematics some template files where suffixed with .json which made electron-builder trying to parse them and treat them like valid JSON.

While actually it was not valid JSON. Since @schematics/angular >= 7.3.0 they suffixed these files with .template and the error is gone.

See https://github.com/angular/angular-cli/commit/36eba0c9fcf17305a7ef99096c860ad271c5aaf7#diff-84ab480b30e45c756807451b0b4411e1
