### ISSUE TITLE
Really confused on how to make electron-builder work

### ISSUE THREAD

**Issue by yalomdd** [electron-userland/electron-builder#3993]
I've been screwing around with trying to make https://github.com/tensorflow/tfjs-models/tree/master/posenet work all morning through npm. In my long chain of errors I am left with:

2019-06-24 10:33:40.111931: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
internal/modules/cjs/loader.js:805
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/Users/desmondyalom/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/desmondyalom/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

which means I'm pretty sure I need to use electron-builder but I am sooo lost at how to make it work for this case. Can someone please give me step by step instructions on how to use this  project for this?

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/3660#issuecomment-504892977 Try `buildDependenciesFromSource` workaround.
