### ISSUE TITLE
 at GenericProvider.getLatestVersion  Unhandled rejection Error: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by evilArsh** [electron-userland/electron-builder#4032]
┏ Electron -------------------

  http://192.168.17.111:5000/api/resources/

┗ ----------------------------

┏ Electron -------------------

  Checking for update

┗ ----------------------------

┏ Electron -------------------

  

┏ Electron -------------------

  [_this.channel1] latest
  [_this.updater.isAddNoCacheQuery] true
  [channelFile] latest.yml
  [channelUrl] URL {
    href:
     'http://192.168.17.111:5000/api/resources/latest.yml?noCache=1dfbflqsc',
    origin: 'http://192.168.17.111:5000',
    protocol: 'http:',
    username: '',
    password: '',
    host: '192.168.17.111:5000',
    hostname: '192.168.17.111',
    port: '5000',
    pathname: '/api/resources/latest.yml',
    search: '?noCache=1dfbflqsc',
    searchParams: URLSearchParams { 'noCache' => '1dfbflqsc' },
    hash: '' }

┗ ----------------------------

┏ Electron -------------------

  [e] Error: net::ERR_CONNECTION_REFUSED
      at GenericProvider.getLatestVersion (E:\money\digital\node_modules\electron-updater\out\providers\GenericProvider.js:98:7)
      at E:\money\digital\node_modules\electron-updater\src\AppUpdater.ts:346:26
      at Generator.next (<anonymous>)
      at processImmediate (internal/timers.js:443:21)
  From previous event:
      at NsisUpdater.getUpdateInfoAndProvider (E:\money\digital\node_modules\electron-updater\src\AppUpdater.ts:335:43)
      at E:\money\digital\node_modules\electron-updater\src\AppUpdater.ts:362:31
      at Generator.next (<anonymous>)
  From previous event:
      at NsisUpdater.doCheckForUpdates (E:\money\digital\node_modules\electron-updater\src\AppUpdater.ts:359:34)
      at NsisUpdater.checkForUpdates (E:\money\digital\node_modules\electron-updater\src\AppUpdater.ts:220:35)
      at checkForUpdates (webpack:///./src/main/index.js?:129:15)
      at EventEmitter.eval (webpack:///./src/main/index.js?:87:3)
      at EventEmitter.emit (events.js:194:13)
      at WebContents.<anonymous> (E:\money\digital\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:390:13)
      at WebContents.emit (events.js:194:13)

┗ ----------------------------

┏ Electron -------------------

  Unhandled rejection Error: net::ERR_CONNECTION_REFUSED
      at GenericProvider.getLatestVersion (E:\money\digital\node_modules\electron-updater\out\providers\GenericProvider.js:98:7)
      at E:\money\digital\node_modules\electron-updater\src\AppUpdater.ts:346:26
      at Generator.next (<anonymous>)
      at processImmediate (internal/timers.js:443:21)
  From previous event:
      at NsisUpdater.getUpdateInfoAndProvider (E:\money\digital\node_modules\electron-updater\src\AppUpdater.ts:335:43)
      at E:\money\digital\node_modules\electron-updater\src\AppUpdater.ts:362:31
      at Generator.next (<anonymous>)
  From previous event:
      at NsisUpdater.doCheckForUpdates (E:\money\digital\node_modules\electron-updater\src\AppUpdater.ts:359:34)
      at NsisUpdater.checkForUpdates (E:\money\digital\node_modules\electron-updater\src\AppUpdater.ts:220:35)
      at checkForUpdates (webpack:///./src/main/index.js?:129:15)
      at EventEmitter.eval (webpack:///./src/main/index.js?:87:3)
      at EventEmitter.emit (events.js:194:13)
      at WebContents.<anonymous> (E:\money\digital\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:390:13)
      at WebContents.emit (events.js:194:13)

I open the URL http://192.168.17.111:5000/api/resources/ in my Chrome
![image](https://user-images.githubusercontent.com/20971355/60895481-56b56280-a297-11e9-90a5-32034aef939f.png)

And i open 
![image](https://user-images.githubusercontent.com/20971355/60895596-819fb680-a297-11e9-9ca9-679ad643d480.png)
![image](https://user-images.githubusercontent.com/20971355/60896102-536ea680-a298-11e9-9f05-a4d42da2c813.png)

I just put the newest package to another computer in the local network。why it shows the error:net::ERR_CONNECTION_REFUSED

this is my code 
![image](https://user-images.githubusercontent.com/20971355/60895927-0985c080-a298-11e9-9455-d6de47c1c98b.png)
![image](https://user-images.githubusercontent.com/20971355/60896007-24f0cb80-a298-11e9-82fa-7d7adf8d4e22.png)

![image](https://user-images.githubusercontent.com/20971355/60896271-a5afc780-a298-11e9-8291-40c54abe180a.png)

But if i put the newest package to my own local http server in my own computer,it will work and will download the newest package to install 。when put the newest package to another computerin the local network ,it can not autoupdate and raise  
Error: net::ERR_CONNECTION_REFUSED
but i open the url with my chrome browser ,i can access the resources.
i am confused with the problem,please help me .my English is not good,i hope that you can help me fix the problem,thank you!

**Comment by evilArsh** [comment]
may be it is due to the mimetype of the .yml file?
but how should i set the correct mimetype for the .yml.text/plain or application/json or what？
and the strange is my axios cannot request any url,so i have to use the nodejs' http.request method.I donot know whether it caused by the Flask web server (werkzeug) or not,or the options or the BrowserWindow,such as "Websecurity:false".and my Flask allows cross-origin
