### ISSUE TITLE
Builder not working on ubuntu 14.04 vm

### ISSUE THREAD

**Issue by aletocar** [electron-userland/electron-builder#406]
**Description**: Trying to build an electron app for linux using electron builder and an ubuntu 14.04 64 bit vm on Mac Os Parallels. The same project builds fine for mac, and also builds in travis, but could not make it build locally, which I need since our users use a modified ubuntu 32 bit environment, and can't build that on travis.
However, when i ran ```npm run dist```, the following was logged.

```bash
Rebuilding app dependencies for arch x64 to /home/parallels/Projects/memoriaylegado/app
Packaging app for platform linux x64 using electron v1.0.2
Error: spawn /home/parallels/Projects/memoriaylegado/node_modules/7zip-bin-linux/7za ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Object.spawn (/home/parallels/Projects/memoriaylegado/node_modules/electron-builder/src/util.ts:101:9)
    at /home/parallels/Projects/memoriaylegado/node_modules/electron-builder/src/fpmDownload.ts:63:14
    at undefined.next (native)
    at WriteStream.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at WriteStream.emit (events.js:185:7)
    at fs.js:1766:14
    at /home/parallels/Projects/memoriaylegado/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:117:15)
From previous event:
    at tsAwaiter (/home/parallels/Projects/memoriaylegado/node_modules/electron-builder/src/awaiter.ts:10:47)
    at Object.build (/home/parallels/Projects/memoriaylegado/node_modules/electron-builder/src/builder.ts:30:59)
    at Object.<anonymous> (/home/parallels/Projects/memoriaylegado/node_modules/electron-builder/src/build-cli.ts:47:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
```

**Node version**: 6.1.0
**npm version**: 3.8.9

I fixed this by changing the dependency in the electron-builder 
```"7zip-bin": "^1.0.0"```, which was set to ^0.3.0.

**Comment by develar** [comment]
Do you use electron-builder 3.23.0?

**Comment by aletocar** [comment]
Was using 3.20. Now I see this was fixed in newer versions. Sorry!
