### ISSUE TITLE
Maximum allowed size is 5 MB

### ISSUE THREAD

**Issue by brkrtp** [electron-userland/electron-builder#4187]
"electron": "^4.0.6",
"electron-builder": "^21.2.0",
 "electron-updater": "^4.0.4",

 Windows Apps

```
 18:21:01.452 > Checking for update
18:21:04.986 > Found version 0.0.1 (url: RestoKasa-Setup-0.0.1.exe)
18:21:04.996 > Downloading update from RestoKasa-Setup-0.0.1.exe
18:21:05.007 > updater cache dir: C:\Users\Seyda\AppData\Local\restokasa-updater
18:21:05.031 > Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: lp2zgG7QI/Oifi8OqhPAHYplgXCZ2fpdrNyii86gFK9JAm4B6wnFiKyww+KLfuGlkpSwuk2IreFaqfvSoiE1kQ==, expected: yMS0+ZPC1V2bI14cQK7lLI5D+NzG3UKTkzsQTHcFBDpde0QgudE0Eb3LkvAvCMvpTq7IvKOgNYZ1EzebijNTvQ==. Directory for cached update will be cleaned
18:21:05.047 > Download block maps (old: "https://api.github.com/repos/brkrtp/electron/releases/assets/14594487.blockmap", new: https://api.github.com/repos/brkrtp/electron/releases/assets/14594487.blockmap)
18:21:05.540 > Cannot download differentially, fallback to full download: Error: Maximum allowed size is 5 MB
    at Object.responseHandler (C:\Users\Seyda\Desktop\electron\dist\win-unpacked\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:238:26)
    at ClientRequest.request.createRequest.response (C:\Users\Seyda\Desktop\electron\dist\win-unpacked\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:297:17)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (C:\Users\Seyda\Desktop\electron\dist\win-unpacked\resources\electron.asar\browser\api\net.js:207:12)
    at URLRequest.emit (events.js:182:13)
```

**Comment by toddmyphoto** [comment]
Seems like this issues has been asked about many times in the past, but all issues are closed. This is the only open issue of this I've found, but seems to still be an issue for many of us. Hoping we get a response / solution / update, soon.
