### ISSUE TITLE
AppImage auto-updater 404 when publish generic provider url has port

### ISSUE THREAD

**Issue by mazinsw** [electron-userland/electron-builder#4188]
* **Version**: 4.1.2

* **Target**: AppImage

This configuration

```json
"publish": [
    {
      "provider": "generic",
      "url": "http://127.0.0.1:8007/downloads"
    }
  ],
```
Results in

```bash
16:37:52.992 › Cannot download differentially, fallback to full download: HttpError: 404 Not Found
Headers: {
  "cache-control": [
    "max-age=0, private, must-revalidate",
    "no-cache, private"
  ],
  "connection": [
    "keep-alive"
  ],
  "content-type": [
    "text/html; charset=UTF-8"
  ],
  "date": [
    "Tue, 27 Aug 2019 19:37:52 GMT"
  ],
  "server": [
    "nginx/1.17.1"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "x-powered-by": [
    "PHP/7.1.14"
  ]
}
    at createHttpError (/tmp/.mount_Nota VlrDAch/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at checkIsRangesSupported (/tmp/.mount_Nota VlrDAch/resources/app.asar/node_modules/electron-updater/src/differentialDownloader/multipleRangeDownloader.ts:104:12)
    at ClientRequest.request.httpExecutor.createRequest.response (/tmp/.mount_Nota VlrDAch/resources/app.asar/node_modules/electron-updater/src/differentialDownloader/DifferentialDownloader.ts:250:14)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (/tmp/.mount_Nota VlrDAch/resources/electron.asar/browser/api/net.js:207:12)
    at URLRequest.emit (events.js:182:13)
16:37:53.095 › Error: Error: Cannot download "http://127.0.0.1/downloads/Nota%20Varejo-1.0.1.AppImage", status 404: Not Found
    at ClientRequest.request.createRequest.response (/tmp/.mount_Nota VlrDAch/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:247:26)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (/tmp/.mount_Nota VlrDAch/resources/electron.asar/browser/api/net.js:207:12)
    at URLRequest.emit (events.js:182:13)
(node:19118) UnhandledPromiseRejectionWarning: Error: Cannot download "http://127.0.0.1/downloads/Nota%20Varejo-1.0.1.AppImage", status 404: Not Found
    at ClientRequest.request.createRequest.response (/tmp/.mount_Nota VlrDAch/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:247:26)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (/tmp/.mount_Nota VlrDAch/resources/electron.asar/browser/api/net.js:207:12)
    at URLRequest.emit (events.js:182:13)
```
Notes on `http://127.0.0.1/downloads` without por number

**Comment by misteraries** [comment]
> This problem occurs when remote file does not exists, only the log is affected

I met the same problem, can you tell me your solution?Thank you!

**Comment by mazinsw** [comment]
> > This problem occurs when remote file does not exists, only the log is affected
> 
> I met the same problem, can you tell me your solution?Thank you!

The solution is quiet simple, just put the latest.yml and binaries files together.

**Comment by misteraries** [comment]
> > > This problem occurs when remote file does not exists, only the log is affected
> > 
> > 
> > I met the same problem, can you tell me your solution?Thank you!
> 
> The solution is quiet simple, just put the latest.yml and binaries files together.
My latest.yml is with binaries, but I still get this error and I don't know how to fix it

**Comment by misteraries** [comment]
> > > This problem occurs when remote file does not exists, only the log is affected
> > 
> > 
> > I met the same problem, can you tell me your solution?Thank you!
> 
> The solution is quiet simple, just put the latest.yml and binaries files together into the folder provided by url.

This is my error message:
Download block maps (old: "http://localhost:5002/download/ISSUE-Preview.0.2-Setup-0.0.1.exe.blockmap", new: http://localhost:5002/download/ISSUE-Preview.0.2-Setup-0.0.2.exe.blockmap)
(electron) 'setResizable function' is deprecated and will be removed. Please use 'resizable property' instead.
Cannot download differentially, fallback to full download: Error: Cannot download "http://localhost/download/ISSUE-Preview.0.2-Setup-0.0.2.exe.blockmap", status 404: Not Found    at ClientRequest.<anonymous> (E:\IssueHub\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:278:26)
    at ClientRequest.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2527:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
Error: Error: Cannot download "http://localhost/download/ISSUE-Preview.0.2-Setup-0.0.2.exe", status 404: Not Found
    at ClientRequest.<anonymous> (E:\IssueHub\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:278:26)
    at ClientRequest.emit (events.js:203:13)

**Comment by mazinsw** [comment]
Try downloading this file http://localhost:5002/download/ISSUE-Preview.0.2-Setup-0.0.2.exe from browser, if it not work, check file naming or the server options, server must serve static files to work

**Comment by terminatorheart** [comment]
i have the same problem. have set something like
url: http://xxxx.xxx:8090/
and log shows that it have find blockmap file, but download file from http://xxxx.xxx/ other than http://xxxx.xxx:8090/, so strange. hope help

**Comment by mazinsw** [comment]
> i have the same problem. have set something like
> url: http://xxxx.xxx:8090/
> and log shows that it have find blockmap file, but download file from http://xxxx.xxx/ other than http://xxxx.xxx:8090/, so strange. hope help

Try download from browser, if it fail, there is a problem with your static file server or probably wrong file name
