### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by mydansun** [electron-userland/electron-builder#427]
```
Rebuilding app dependencies for arch x64 to E:\UserDocument\Desktop\PROJECT\Electron\whatever\app
Packaging app for platform win32 x64 using electron v1.1.0
Error: Application entry file index.js could not be found in package. Seems like a wrong configuration.
    at WinPackager.<anonymous> (C:\Users\mydan\AppData\Roaming\npm\node_modules\electron-builder\src\platformPackager.ts:271:13)
    at undefined.next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at tsAwaiter (C:\Users\mydan\AppData\Roaming\npm\node_modules\electron-builder\src\awaiter.ts:10:47)
    at Object.build (C:\Users\mydan\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:30:59)
    at Object.<anonymous> (C:\Users\mydan\AppData\Roaming\npm\node_modules\electron-builder\src\build-cli.ts:47:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
```

windows 10
```
{
"electron-builder": "^3.25.0",
"electron-packager": "^7.0.1",
"electron-prebuilt": "^1.1.0",
"electron-rebuild": "^1.1.4"
}
```

How to solve?

**Comment by gamestailer94** [comment]
allready in work.
Temp workaround is to set `releaseName` and `name` in app `package.json` to same value
- see https://github.com/electron-userland/electron-builder/issues/371#issuecomment-220775971

**Comment by develar** [comment]
Duplicate #360
