### ISSUE TITLE
unable to build on raspberry pi 4: Unsupported arch arm

### ISSUE THREAD

**Issue by sbarex** [electron-userland/electron-builder#4279]
electron-builder version 21.2.0

target: linux on raspberry pi 4 arm board

When building the process halt with this error:

⨯ Unsupported arch arm  stackTrace=
Error: Unsupported arch arm
at archFromString (/home/pi/electron/node_modules/builder-util/src/arch.ts:43:13)
at computeArchToTargetNamesMap (/home/pi/electron/node_modules/app-builder-lib/src/targets/targetFactory.ts:43:20)
at Packager.doBuild (/home/pi/electron/node_modules/app-builder-lib/src/packager.ts:422:41)
at Packager._build (/home/pi/electron/node_modules/app-builder-lib/src/packager.ts:366:57)
at Packager.build (/home/pi/electron/node_modules/app-builder-lib/src/packager.ts:330:12)
at executeFinally (/home/pi/electron/node_modules/builder-util/src/promise.ts:12:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! video_player@1.0.0 dist: `electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the video_player@1.0.0 dist script.

But, I have edited the function `archFromString` on `node_modules/builder-util/out/arch.js` (compiled version of arch.ts) so it's return `armv7l` also for arch name `arm` and the app is builded correctly.

**Comment by sbarex** [comment]
for me it is still relevant but obviously not for others

**Comment by kuntalakrishna** [comment]
It's relevant to me as well. Is there any solution to this problem?

**Comment by ptkdev** [comment]
+1

**Comment by ptkdev** [comment]
Work for me:
`electron-builder --dir --armv7l --linux deb`
