### ISSUE TITLE
Multiple errors when building on mac

### ISSUE THREAD

**Issue by jarrodek** [electron-userland/electron-builder#4288]
* **Version**: 21.2.0
* **electron-updater**: 4.1.2
* **Target**:  wlm

Last time when I run my build script it was all working just fine, but it was few months ago. I was always able to build my application from mac. Now I am experiencing problems when building the app.

Note, the app does not use native dependencies.

The command I am executing:

```sh
node_modules/.bin/electron-builder --win --mac --linux --publish always
```

And the output is:

```
  • electron-builder  version=21.2.0 os=17.7.0
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=6.0.11 appOutDir=dist/mac
  • signing         file=dist/mac/AdvancedRestClient.app identityName=Developer ID Application: Pawel Psztyc (28GF7N4NRS) identityHash=0479A05327FF289DAE94560A2635B952400AD423 provisioningProfile=none
  • building        target=DMG arch=x64 file=dist/arc-14.0.0-alpha.5.dmg
  • building        target=macOS zip arch=x64 file=dist/arc-14.0.0-alpha.5.zip
  • packaging       platform=linux arch=x64 electron=6.0.11 appOutDir=dist/linux-unpacked
  • building        target=tar.gz arch=x64 file=dist/arc-linux-14.0.0-alpha.5-x64.tar.gz
  • building        target=AppImage arch=x64 file=dist/arc-linux-14.0.0-alpha.5-x86_64.AppImage
  • packaging       platform=linux arch=ia32 electron=6.0.11 appOutDir=dist/linux-ia32-unpacked
  • building        target=tar.gz arch=ia32 file=dist/arc-linux-14.0.0-alpha.5-ia32.tar.gz
  • building        target=AppImage arch=ia32 file=dist/arc-linux-14.0.0-alpha.5-i386.AppImage
  • packaging       platform=win32 arch=x64 electron=6.0.11 appOutDir=dist/win-unpacked
  • publishing      publisher=Github (owner: advanced-rest-client, project: arc-electron, version: 14.0.0-alpha.5)
  • uploading       file=arc-linux-14.0.0-alpha.5-x86_64.AppImage provider=GitHub
  • overwrite published file  file=arc-linux-14.0.0-alpha.5-x86_64.AppImage reason=already exists on GitHub
  ⨯ cannot execute  cause=fork/exec /Users/ppsztyc/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine: no such file or directory
                    command=/Users/ppsztyc/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine /Users/ppsztyc/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.5.0/rcedit-ia32.exe /Users/ppsztyc/workspace/arc/arc-electron/dist/win-unpacked/AdvancedRestClient.exe --set-version-string FileDescription AdvancedRestClient --set-version-string ProductName AdvancedRestClient --set-version-string LegalCopyright 'Copyright © 2018 Mulesoft' --set-file-version 14.0.0-alpha.5 --set-product-version 14.0.0.0 --set-version-string InternalName AdvancedRestClient --set-version-string OriginalFilename '' --set-version-string CompanyName 'Pawel Psztyc' --set-icon /Users/ppsztyc/workspace/arc/arc-electron/build/icon.ico
                   workingDir=
  • publishing      publisher=Github (owner: advanced-rest-client, project: arc-electron, version: 14.0.0-alpha.5)
  • uploading       file=arc-linux-14.0.0-alpha.5-i386.AppImage provider=GitHub
  • building embedded block map  file=dist/arc-14.0.0-alpha.5.zip
  • uploading       file=arc-14.0.0-alpha.5.zip provider=GitHub
  • building        target=deb arch=ia32 file=dist/arc-linux-14.0.0-alpha.5-i386.deb
  • uploading       file=arc-linux-14.0.0-alpha.5-ia32.tar.gz provider=GitHub
  ⨯ cannot execute  cause=exit status 1
                    out={:timestamp=>"2019-10-02T09:08:47.576843-0700", :message=>"No such file (for after_install): \"/private/var/folders/r3/4_y_0s_d30sdfpnmb56sbnwj0cjbs8/T/t-zasufT/1-after-install\"", :level=>:error}
    
                    errorOut=/Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/lib/fpm/command.rb:444:in `read': No such file or directory @ rb_sysopen - /private/var/folders/r3/4_y_0s_d30sdfpnmb56sbnwj0cjbs8/T/t-zasufT/1-after-install (Errno::ENOENT)
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/lib/fpm/command.rb:444:in `block in execute'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/lib/fpm/command.rb:448:in `call'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/lib/fpm/command.rb:448:in `execute'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/vendor/ruby/2.2.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/lib/fpm/command.rb:574:in `run'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/vendor/ruby/2.2.0/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/bin/fpm:7:in `<main>'
    
                    command=/Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/fpm -s dir --force -t deb -d libgtk-3-0 -d libnotify4 -d libnss3 -d libxss1 -d libxtst6 -d xdg-utils -d libatspi2.0-0 -d libuuid1 -d libappindicator3-1 -d libsecret-1-0 --deb-compression xz --architecture i386 --name advanced-rest-client --after-install /private/var/folders/r3/4_y_0s_d30sdfpnmb56sbnwj0cjbs8/T/t-zasufT/1-after-install --after-remove /private/var/folders/r3/4_y_0s_d30sdfpnmb56sbnwj0cjbs8/T/t-zasufT/2-after-remove --description 'A developer tool to test HTTP requests
     The Advanced REST Client desktop application.' --version 14.0.0-alpha.5 --package /Users/ppsztyc/workspace/arc/arc-electron/dist/arc-linux-14.0.0-alpha.5-i386.deb --maintainer 'Pawel Psztyc <arc@mulesoft.com>' --url https://advancedrestclient.com --vendor Mulesoft --license Apache-2.0 /Users/ppsztyc/workspace/arc/arc-electron/dist/linux-ia32-unpacked/=/opt/AdvancedRestClient /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/icon_16x16.png=/usr/share/icons/hicolor/16x16/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/icon_32x32.png=/usr/share/icons/hicolor/32x32/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/icon_48x48.png=/usr/share/icons/hicolor/48x48/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/icon_64x64.png=/usr/share/icons/hicolor/64x64/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/icon_128x128.png=/usr/share/icons/hicolor/128x128/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/result.iconset/icon_256x256.png=/usr/share/icons/hicolor/256x256/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/result.iconset/icon_512x512.png=/usr/share/icons/hicolor/512x512/apps/advanced-rest-client.png /private/var/folders/r3/4_y_0s_d30sdfpnmb56sbnwj0cjbs8/T/t-GxYEAy/7-AdvancedRestClient.desktop=/usr/share/applications/advanced-rest-client.desktop
                    workingDir=
  • building        target=deb arch=x64 file=dist/arc-linux-14.0.0-alpha.5-amd64.deb
  • uploading       file=arc-linux-14.0.0-alpha.5-x64.tar.gz provider=GitHub
  ⨯ cannot execute  cause=exit status 1
                    out={:timestamp=>"2019-10-02T09:08:49.733422-0700", :message=>"No such file (for after_install): \"/private/var/folders/r3/4_y_0s_d30sdfpnmb56sbnwj0cjbs8/T/t-zasufT/1-after-install\"", :level=>:error}
    
                    errorOut=/Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/lib/fpm/command.rb:444:in `read': No such file or directory @ rb_sysopen - /private/var/folders/r3/4_y_0s_d30sdfpnmb56sbnwj0cjbs8/T/t-zasufT/1-after-install (Errno::ENOENT)
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/lib/fpm/command.rb:444:in `block in execute'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/lib/fpm/command.rb:448:in `call'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/lib/fpm/command.rb:448:in `execute'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/vendor/ruby/2.2.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/lib/fpm/command.rb:574:in `run'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/vendor/ruby/2.2.0/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
    	from /Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/lib/app/bin/fpm:7:in `<main>'
    
                    command=/Users/ppsztyc/Library/Caches/electron-builder/fpm/fpm-1.9.3-20150715-2.2.2-mac/fpm -s dir --force -t deb -d libgtk-3-0 -d libnotify4 -d libnss3 -d libxss1 -d libxtst6 -d xdg-utils -d libatspi2.0-0 -d libuuid1 -d libappindicator3-1 -d libsecret-1-0 --deb-compression xz --architecture amd64 --name advanced-rest-client --after-install /private/var/folders/r3/4_y_0s_d30sdfpnmb56sbnwj0cjbs8/T/t-zasufT/1-after-install --after-remove /private/var/folders/r3/4_y_0s_d30sdfpnmb56sbnwj0cjbs8/T/t-zasufT/2-after-remove --description 'A developer tool to test HTTP requests
     The Advanced REST Client desktop application.' --version 14.0.0-alpha.5 --package /Users/ppsztyc/workspace/arc/arc-electron/dist/arc-linux-14.0.0-alpha.5-amd64.deb --maintainer 'Pawel Psztyc <arc@mulesoft.com>' --url https://advancedrestclient.com --vendor Mulesoft --license Apache-2.0 /Users/ppsztyc/workspace/arc/arc-electron/dist/linux-unpacked/=/opt/AdvancedRestClient /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/icon_16x16.png=/usr/share/icons/hicolor/16x16/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/icon_32x32.png=/usr/share/icons/hicolor/32x32/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/icon_48x48.png=/usr/share/icons/hicolor/48x48/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/icon_64x64.png=/usr/share/icons/hicolor/64x64/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/icon_128x128.png=/usr/share/icons/hicolor/128x128/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/result.iconset/icon_256x256.png=/usr/share/icons/hicolor/256x256/apps/advanced-rest-client.png /Users/ppsztyc/workspace/arc/arc-electron/dist/.icon-set/result.iconset/icon_512x512.png=/usr/share/icons/hicolor/512x512/apps/advanced-rest-client.png /private/var/folders/r3/4_y_0s_d30sdfpnmb56sbnwj0cjbs8/T/t-GxYEAy/8-AdvancedRestClient.desktop=/usr/share/applications/advanced-rest-client.desktop
                    workingDir=
```

I am using CLI command as multi build instructions never work for me.
Is there anything I am doing wrong here?

**Comment by jarrodek** [comment]
I may have a solution for this. After removing `/Users/ppsztyc/Library/Caches/electron-builder/` and project's node_modules folders, reinstalling the dependencies, and running build again this errors disappeared. I have other errors but I believe it is an issue with my company's pre-installed anti-virus blocking windows signing process. 
Feel free to close this ticket.
