### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by xsudiptaster** [electron-userland/electron-builder#4294]
* **Version**: 

Mac: 

Uncaught Exception:
Error: Cannot find module 'electron-is-dev'
Require stack:
- /Users/skarmakar/Documents/WorkSpace/PermissionHandler/NewApp/dist/mac/newapp.app/Contents/Resources/app.asar/build/electron.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/Users/skarmakar/Documents/WorkSpace/PermissionHandler/NewApp/dist/mac/newapp.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/skarmakar/Documents/WorkSpace/PermissionHandler/NewApp/dist/mac/newapp.app/Contents/Resources/app.asar/build/electron.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)

**Comment by 13banda** [comment]
Module is missing please install it
`npm i electron-is-dev
`
