### ISSUE TITLE
Electron-builder fails to build for Windows on Travis CI when using docker

### ISSUE THREAD

**Issue by AdrianoFerrari** [electron-userland/electron-builder#4304]
* **Version**: 21.2.0

* **Target**: Windows, macOS, and Linux.
`.travis.yml` file here: https://github.com/gingko/client/blob/master/.travis.yml
Tried and failed with node versions 10 and 12.

The travis build fails with npm error:
```
npm ERR! makeDirectory homeless?

npm ERR! path /home/travis
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall stat
npm ERR! enoent ENOENT: no such file or directory, stat '/home/travis'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-10-09T16_53_17_609Z-debug.log
```
You can see [this broken build here](https://travis-ci.org/gingko/client/builds/595717432).

[Last working build](https://travis-ci.org/gingko/client/builds/594378200) was a few commits ago, but I changed nothing on .travis.yml or build scripts since then.

My current suspicion is docker isn't able to access `/home/travis` for some reason

Possibly related past (closed) issue: #692

**Comment by AdrianoFerrari** [comment]
**Update** : I tried building without `npm install` before the `npm release` part of the script ([new config here](https://travis-ci.org/AdrianoFerrari/gingko-client-trytravis/jobs/595737554/config), and [old one for comparison](https://travis-ci.org/gingko/client/jobs/595717434/config)), and get the same error, but with additional information.

Here's [the failing build](https://travis-ci.org/AdrianoFerrari/gingko-client-trytravis/jobs/595737554), and below is the log:

```
> DEBUG=electron-builder && electron-builder "--linux" "--win"
  • electron-builder  version=21.2.0 os=4.15.0-1028-gcp
  • artifacts will be published if draft release exists  reason=CI detected
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=linux arch=x64 appDir=/project/app
  ⨯ /usr/local/bin/node exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Error output:
Error output:
npm ERR! makeDirectory homeless?
npm ERR! path /home/travis
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall stat
npm ERR! enoent ENOENT: no such file or directory, stat '/home/travis'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-10-09T17_44_45_468Z-debug.log
  stackTrace=
Error: /usr/local/bin/node exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Error output:

Error output:
npm ERR! makeDirectory homeless?
npm ERR! path /home/travis
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall stat
npm ERR! enoent ENOENT: no such file or directory, stat '/home/travis'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-10-09T17_44_45_468Z-debug.log

at ChildProcess.childProcess.once.code (/project/node_modules/builder-util/src/util.ts:239:14)
at Object.onceWrapper (events.js:285:13)
at ChildProcess.emit (events.js:197:13)
at maybeClose (internal/child_process.js:984:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by AdrianoFerrari** [comment]
**Update**: It does seem to be a docker issue. I removed the docker section, and _installed wine directly_ and now the build completes. Working config [can be seen here](https://travis-ci.org/AdrianoFerrari/gingko-client-trytravis/jobs/595751322/config), relevant sections are these:

```
before_install:
  - |
    sudo apt-get update && sudo apt-get install -y --no-install-recommends software-properties-common && sudo dpkg --add-architecture i386 && curl -L https://dl.winehq.org/wine-builds/winehq.key > winehq.key && sudo apt-key add winehq.key && sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu && \
    sudo apt-get update && \
    sudo apt-get -y purge software-properties-common libdbus-glib-1-2 python3-dbus python3-gi python3-pycurl python3-software-properties && \
    sudo apt-get install -y --no-install-recommends winehq-stable && \
    # clean
    sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* && sudo unlink winehq.key
```

```
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run release -- -- --linux --win
    else
      npm run release
    fi
```

Any issue with doing things this way?

**Comment by AdrianoFerrari** [comment]
Yet another Update (hope these actually help):

Turns out that building like this with manual wine install instead of docker, doesn't work. Native dependencies don't seem to work this way, whereas building the app manually on a Windows machine produces a working build.

**Comment by AdrianoFerrari** [comment]
Yes! After diving into docker to understand this better, was able to get it to work. I suspect the error was on my end, in the way I was calling my build commands.

Working build, for reference: https://travis-ci.org/gingko/client/jobs/597540757/config
