### ISSUE TITLE
Fails to publish snap

### ISSUE THREAD

**Issue by jookyboi** [electron-userland/electron-builder#4316]
* **Version**: 21.2.0

* **Target**: 

As of this morning the `electron-builder --publish always` command fails with this error on my Teamcity build.

```
[Step 2/2] > cacher@2.21.2 dist /home/ubuntu/agent/work/ddd3bd3957705c66
[09:37:04]	[Step 2/2] > electron-builder --publish always
[09:37:04]	[Step 2/2] 
[09:37:04]	[Step 2/2]   • electron-builder  version=21.2.0 os=4.4.0-1072-aws
[09:37:05]	[Step 2/2]   • loaded configuration  file=package.json ("build" field)
[09:37:05]	[Step 2/2]   • packaging       platform=linux arch=x64 electron=5.0.10 appOutDir=dist/linux-unpacked
[09:37:10]	[Step 2/2]   • building        target=AppImage arch=x64 file=dist/Cacher-2.21.2.AppImage
[09:37:10]	[Step 2/2]   • building        target=snap arch=x64 file=dist/cacher_2.21.2_amd64.snap
[09:38:05]	[Step 2/2]   • publishing      publisher=Snap Store
[09:38:05]	[Step 2/2]   • uploading       file=cacher_2.21.2_amd64.snap provider=snapStore
[09:38:05]	[Step 2/2]   • building        target=deb arch=x64 file=dist/cacher_2.21.2_amd64.deb
[09:38:08]	[Step 2/2] Preparing to push 'cacher_2.21.2_amd64.snap'.
[09:38:08]	[Step 2/2] After pushing, an attempt will be made to release to 'edge'
[09:38:09]	[Step 2/2] Received 401: '{"error_list": [{"code": "macaroon-authorization-required", "extra": {"realm": "Devportal"}, "message": "The request is missing an Authorization header field containing a valid macaroon"}]}'
[09:38:09]	[Step 2/2]   ⨯ exit status 2
[09:38:09]	[Step 2/2] github.com/develar/app-builder/pkg/util.ExecuteAndPipeStdOutAndStdErr
[09:38:09]	[Step 2/2] 	/Volumes/data/Documents/app-builder/pkg/util/exec.go:23
[09:38:09]	[Step 2/2] github.com/develar/app-builder/pkg/package-format/snap.publishToStore
[09:38:09]	[Step 2/2] 	/Volumes/data/Documents/app-builder/pkg/package-format/snap/snapStore.go:35
[09:38:09]	[Step 2/2] github.com/develar/app-builder/pkg/package-format/snap.ConfigurePublishCommand.func1
[09:38:09]	[Step 2/2] 	/Volumes/data/Documents/app-builder/pkg/package-format/snap/snapStore.go:18
[09:38:09]	[Step 2/2] github.com/alecthomas/kingpin.(*actionMixin).applyActions
[09:38:09]	[Step 2/2] 	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
[09:38:09]	[Step 2/2] github.com/alecthomas/kingpin.(*Application).applyActions
[09:38:09]	[Step 2/2] 	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
[09:38:09]	[Step 2/2] github.com/alecthomas/kingpin.(*Application).execute
[09:38:09]	[Step 2/2] 	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
[09:38:09]	[Step 2/2] github.com/alecthomas/kingpin.(*Application).Parse
[09:38:09]	[Step 2/2] 	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
[09:38:09]	[Step 2/2] main.main
[09:38:09]	[Step 2/2] 	/Volumes/data/Documents/app-builder/main.go:90
[09:38:09]	[Step 2/2] runtime.main
[09:38:09]	[Step 2/2] 	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/proc.go:200
[09:38:09]	[Step 2/2] runtime.goexit
[09:38:09]	[Step 2/2] 	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/asm_amd64.s:1337  
[09:39:46]	[Step 2/2]   • building        target=rpm arch=x64 file=dist/cacher-2.21.2.x86_64.rpm
[09:42:35]	[Step 2/2]   ⨯ /home/ubuntu/agent/work/ddd3bd3957705c66/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
[09:42:35]	[Step 2/2] Error: /home/ubuntu/agent/work/ddd3bd3957705c66/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
[09:42:35]	[Step 2/2] at ChildProcess.childProcess.once.code (/home/ubuntu/agent/work/ddd3bd3957705c66/node_modules/builder-util/src/util.ts:239:14)
[09:42:35]	[Step 2/2] at Object.onceWrapper (events.js:273:13)
[09:42:35]	[Step 2/2] at ChildProcess.emit (events.js:182:13)
[09:42:35]	[Step 2/2] at maybeClose (internal/child_process.js:962:16)
[09:42:35]	[Step 2/2] at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Comment by jookyboi** [comment]
My fault. `snapcraft` was not logged in.
