### ISSUE TITLE
Unable to sign the framework library

### ISSUE THREAD

**Issue by joeyer** [electron-userland/electron-builder#4347]
electron-builder：20.38.1

A framework library has been imported into the project. error：

Error: Command failed: codesign --sign FBA30565226FE4A49187A491855036EE98E6F4FD --force --keychain /private/var/folders/l8/gwgxg6fx40l7dcszmzfv2gc00000gn/T/t-NAXDA3/1.keychain /Users/lzj/Desktop/linkus_pc/release/mac/Linkus.app/Contents/Frameworks/copy.framework/copy
/Users/lzj/Desktop/linkus_pc/release/mac/Linkus.app/Contents/Frameworks/copy.framework/copy: bundle format unrecognized, invalid, or unsuitable

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
From previous event:
    at MacPackager.sign (/Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/macPackager.ts:121:97)
    at nonMasPromise.then (/Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/macPackager.ts:89:26)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at /Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/macPackager.ts:89:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at callback (/Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Packager.build (/Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/lzj/.nvm/versions/node/v10.11.0/lib/node_modules/electron-builder/src/cli/cli.ts:46:19)

**Comment by joeyer** [comment]
If the framework dynamic library is packaged in the asar file, it will appear  “no suitable image found” the error will occur.
