### ISSUE TITLE
Unable to create DMG - fails with "DmgTarget is not a constructor" error

### ISSUE THREAD

**Issue by gmantri** [electron-userland/electron-builder#4354]
* **Version**: 21.2.0

* **Electron Updater Version**: 4.1.2

* **Target**: DMG (macOS)

I recently updated electron builder from version 20.10.0 to 21.2.0. Since then I am unable to create DMG file. Here's the code snippet I have been using to build:

```
const builder = require("electron-builder");

  const osxConfig = {
    category: 'public.app-category.developer-tools',
    icon: 'resources/osx/icon.icns',
    artifactName: 'MyApplicationName.${ext}',
  };
  const osxBuildConfig = Object.assign({}, commonConfig);
  osxBuildConfig.mac = osxConfig;
  builder.build({
    targets: builder.Platform.MAC.createTarget(),
    config: osxBuildConfig
  })
  .then(() => {
    console.log('Done building installer for OSX!!!');
  })
  .catch((error) => {
    console.log('Error building Mac installer....');
    console.log(error);
  });

```
With the code above, I am getting the following error message:

```
TypeError: DmgTarget is not a constructor
    at outDir (/Users/<my-user-name>/Projects/<my-app-name>/node_modules/app-builder-lib/src/macPackager.ts:72:34)
    at mapper (/Users/<my-user-name>/Projects/<my-app-name>/node_modules/app-builder-lib/src/targets/targetFactory.ts:57:16)
    at MacPackager.createTargets (/Users/<my-user-name>/Projects/<my-app-name>/node_modules/app-builder-lib/src/macPackager.ts:72:11)
    at createTargets (/Users/<my-user-name>/Projects/<my-app-name>/node_modules/app-builder-lib/src/targets/targetFactory.ts:64:12)
    at Packager.doBuild (/Users/<my-user-name>/Projects/<my-app-name>/node_modules/app-builder-lib/src/packager.ts:435:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

If I try to create either a `pkg` or a `zip` artifact, that works.

What am I doing wrong? Any help would be highly appreciated.

**Comment by gmantri** [comment]
I updated the electron-builder to version `22.1.0` (latest at this time) and the problem went away.
