### ISSUE TITLE
help!Exit code: ENOENT. spawn prlctl ENOENT

### ISSUE THREAD

**Issue by goo4it** [electron-userland/electron-builder#4477]
hi! my os is mac, and that version is  10.15.1 (19B88).
I will build project, but has error.
`Exit code: ENOENT. spawn prlctl ENOENT  stackTrace=
                                                        Error: Exit code: ENOENT. spawn prlctl ENOENT
                                                            at /Users/yanglinghui/git_tonkor/cnyb-ele/node_modules/app-builder-lib/node_modules/builder-util/src/util.ts:125:16
                                                            at exithandler (child_process.js:301:5)
                                                            at ChildProcess.errorhandler (child_process.js:313:5)
                                                            at ChildProcess.emit (events.js:189:13)
                                                            at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
                                                            at onErrorNT (internal/child_process.js:421:16)
                                                            at process.internalTickCallback (internal/process/next_tick.js:72:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by lk321** [comment]
Just update the pkg to 22.2.0:

`$ yarn add electron-builder@latests -D`
