### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by laclance** [electron-userland/electron-builder#4493]
* **Version**: 21.2.0
* **Target**: windows 10

I have used capacitor to create an electron app, which runs fine. I installed electron-builder and ran `node ./node_modules/.bin/electron-builder` and get the following output: 
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by laclance** [comment]
The error was from running `node node_modules\.bin\electron-builder`. Adding electron-builder to an npm script worked.
