### ISSUE TITLE
Can't use npm pre-release versions on windows

### ISSUE THREAD

**Issue by limoragni** [electron-userland/electron-builder#451]
I'm trying to use npm pre-releases like `2.0.1-2` and it fails on windows (appVeyor). Its working just fine on Osx.
It says the version is not a valid string. Is this expected behaviour? 
 
```
Packaging app for platform win32 ia32 using electron v0.35.6
System.ArgumentException: '2.4.32-0' is not a valid version string.
Parameter name: version
   at NuGet.SemanticVersion.Parse(String version)
   at NuGet.ManifestMetadata.NuGet.IPackageName.get_Version()
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
Error: C:\projects\footmapp\node_modules\electron-builder\node_modules\electron-winstaller-fixed\vendor\Update.com failed with exit code: 4294967295
    at ChildProcess.<anonymous> (C:\projects\footmapp\node_modules\electron-builder\node_modules\electron-winstaller-fixed\lib\spawn-promise.js:33:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at spawn (C:\projects\footmapp\node_modules\electron-builder\node_modules\electron-winstaller-fixed\lib\spawn-promise.js:22:10)
    at releasify (C:\projects\footmapp\node_modules\electron-builder\node_modules\electron-winstaller-fixed\lib\index.js:272:37)
    at Object.<anonymous> (C:\projects\footmapp\node_modules\electron-builder\node_modules\electron-winstaller-fixed\lib\index.js:126:11)
    at [object Generator].next (native)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at Object.createWindowsInstaller (C:\projects\footmapp\node_modules\electron-builder\node_modules\electron-winstaller-fixed\lib\index.js:146:16)
    at WinPackager.<anonymous> (C:\projects\footmapp\node_modules\electron-builder\src\winPackager.ts:175:44)
    at [object Generator].next (native)
From previous event:
    at tsAwaiter (C:\projects\footmapp\node_modules\electron-builder\src\awaiter.ts:10:47)
    at Object.build (C:\projects\footmapp\node_modules\electron-builder\src\builder.ts:30:59)
    at Object.<anonymous> (C:\projects\footmapp\node_modules\electron-builder\src\build-cli.ts:47:2)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

electron-builder version is 3.25.0

**Comment by develar** [comment]
Nuget supports only `1.0.0-beta.1` — instead of `2.0.1-2` please use `2.0.1-beta.2`
