### ISSUE TITLE
Auto updater downloads the update but fail to install it

### ISSUE THREAD

**Issue by iJosephY** [electron-userland/electron-builder#4526]
Versions : 
Electron-builder : i tried both v22.20 and v22.1.0
Electron-updater :  v4.2.0
Electron : v7.1.4

Error i'm having : 

`[2019-12-11 10:49:07.004] [info] Checking for update
[2019-12-11 10:49:07.185] [info] Generated new staging user ID: ef86f7bb-c82a-5220-aabc-7355cfe52688
[2019-12-11 10:49:10.537] [info] Found version 0.3.3 (url: plazamoddingtoolkit-setup-0.3.3.exe)
[2019-12-11 10:49:10.544] [info] Downloading update from plazamoddingtoolkit-setup-0.3.3.exe
[2019-12-11 10:49:10.553] [debug] updater cache dir: C:\Users\Administrator\AppData\Local\plazamoddingtoolkit-updater
[2019-12-11 10:49:10.564] [info] No cached update info available
[2019-12-11 10:49:10.572] [info] Download block maps (old: "https://github.com/TheModdingPlaza/ModdingToolkit/releases/download/v0.3.2/plazamoddingtoolkit-setup-0.3.2.exe.blockmap", new: https://github.com/TheModdingPlaza/ModdingToolkit/releases/download/v0.3.3/plazamoddingtoolkit-setup-0.3.3.exe.blockmap)
[2019-12-11 10:49:10.826] [error] Cannot download differentially, fallback to full download: Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2561:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
[2019-12-11 10:49:11.091] [error] Error: Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2561:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
`

My Code :
![image](https://user-images.githubusercontent.com/42868470/70650715-e351bb80-1c4f-11ea-8786-dfb6acbad1fc.png)

Well, i don't know what to do .. can someone help?

**Comment by cocochepeau** [comment]
Same case here with:

* electron 6
* electron-builder 21.2.0
* electron-updater 4.2.0

Exception is the following one:

```
Error: Redirect was cancelled
  File "electron/js2c/browser_init.js", line 2558, col 23, in SimpleURLLoaderWrapper.<anonymous>
  File "events.js", line 203, col 13, in SimpleURLLoaderWrapper.emit
  File "domain.js", line 476, col 20, in SimpleURLLoaderWrapper.EventEmitter.emit
  File "domain.js", line 131, col 23, in SimpleURLLoaderWrapper.topLevelDomainCallback
```

![image](https://user-images.githubusercontent.com/2019778/70725745-37ff4000-1cfd-11ea-8051-b35fb4ac19c8.png)

**Comment by fguitton** [comment]
I also have the problem, it prevents the application from being updated all together.

It shows up for me too with the following:
- electron: "7.1.4"
- electron-builder: "22.2.0"
- electron-updater: "4.2.0"

It is working with the combo:
- electron: "6.0.12"
- electron-builder: "21.2.0"
- electron-updater: "4.2.0"

**Comment by iJosephY** [comment]
@fguitton 
you are saying that it's workings with the combo
electron: "6.0.12"
electron-builder: "21.2.0"
electron-updater: "4.2.0"

but @cocochepeau saying otherwise.

interesting ... i will give the combo a try, if it works then i would have no choice but to downgrade to v6 .. thanks you for the info

**Comment by fguitton** [comment]
@iJosephY Yes, it is strange, there might be other things interfering. Possibly during dependency resolution. I have been able to see that it works also for electron 6.1.6. But as soon as I pass to electron 7, it breaks.

**Comment by sentialx** [comment]
The same with:
- electron: 7.1.5
- electron-builder: 22.2.0
- electron-updater: 4.2.0

Last working electron-builder version: 22.1.0

**Comment by transparentech** [comment]
I had the same problem with Electron: 7.1 and electron-builder: 21.2.

I created a fork of electron-builder 21.2 and reverted commit 39e6783 and then the auto-update worked again. So for me, something in that particular commit was problematic. Unfortunately I don't know enough about Windows/NSIS to say what exactly.

**Comment by sidneys** [comment]
Is this related to https://github.com/electron-userland/electron-builder/issues/4505 ?

**Comment by iJosephY** [comment]
@sidneys i guess it is
only difference is that my target is windows ..

**Comment by sidneys** [comment]
@develar 

This Issue should be merged with https://github.com/electron-userland/electron-builder/issues/4505

**Comment by sentialx** [comment]
Any update on this? Is there any maintainer alive? Currently, there seems to be no workaround for developers who need to be on the newest Electron version.

**Comment by agata** [comment]
I don't upgrade Electron from 6.1 to 7.1 yet. I am waiting to solved this problem.

**Comment by borsTiHD** [comment]
Same here. Update not working. :)

-     "electron": "^7.1.2"
-     "electron-builder": "^21.2.0"
-     "electron-updater": "^4.2.0"

**Comment by dodododooo** [comment]
Same here. Update not working on windows 7, but windows 10 ok,
"electron": "^6.0.7"
"electron-builder": "^21.2.0"
"electron-updater": "^4.2.0"
I do this and it works ok both on 7 and 10,

add code like this in node_modules\electron-updater\out\NsisUpdater.js(row: 212)
````
    callUsingElevation();
    return true;
````

**Comment by borsTiHD** [comment]
I haven't tried it, but is it a good idea to 'return' and skip the rest?
For what exaclty is this 'elevate.exe'?

Another question... where can I find the logs, created with 'this._logger.info()'?
