### ISSUE TITLE
Can't use CSC_LINK as base64 string

### ISSUE THREAD

**Issue by cawa-93** [electron-userland/electron-builder#4540]
* **Version**: 21.2.0

* **Target**: dmg

I created a * .p12 certificate.
Converted it to base64 string  (as recommended in your documentation) and saved it to GitHub Secrets.

In GitHub action I set two env:
- `CSC_LINK` — base64 string
- `CSC_KEY_PASSWORD`

However, I get an error when running an action:
```
  env:
    GH_TOKEN: ***
    CSC_LINK: ***
    CSC_KEY_PASSWORD: ***

...


Building app with electron-builder:
  • electron-builder  version=21.2.0 os=19.0.0
  • packaging       platform=darwin arch=x64 electron=8.0.0-beta.4 appOutDir=dist_electron/mac
  • downloading     url=https://github.com/electron/electron/releases/download/v8.0.0-beta.4/electron-v8.0.0-beta.4-darwin-x64.zip size=65 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v8.0.0-beta.4/electron-v8.0.0-beta.4-darwin-x64.zip duration=1.284s
  • default Electron icon is used  reason=application icon is not set
 ERROR  Error: /Users/runner/runners/2.162.0/work/play-shikimori-online/play-shikimori-online/*** doesn't exist
Error: /Users/runner/runners/2.162.0/work/play-shikimori-online/play-shikimori-online/*** doesn't exist
    at downloadCertificate (/Users/runner/runners/2.162.0/work/play-shikimori-online/play-shikimori-online/node_modules/app-builder-lib/src/codeSign/codesign.ts:43:11)
From previous event:
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)
From previous event:
    at createKeychain (/Users/runner/runners/2.162.0/work/play-shikimori-online/play-shikimori-online/node_modules/app-builder-lib/src/codeSign/macCodeSign.ts:179:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at MacPackager.sign (/Users/runner/runners/2.162.0/work/play-shikimori-online/play-shikimori-online/node_modules/app-builder-lib/src/macPackager.ts:148:27)
```

I'm assuming the electron-builder is trying to use CSC_LINK as the filename and logically doesn't find it.

**Comment by cawa-93** [comment]
yes

**Comment by cawa-93** [comment]
Yes

**Comment by morisuke** [comment]
@cawa-93 
It can be read from the following implementation that the end must end with "=" when using BASE64.
Also, from my experience, BASE64 containing line feed code will cause an error.

https://github.com/electron-userland/electron-builder/blob/4e454f8b4390a4bcc38a30f065e0ed1eba2acee9/packages/app-builder-lib/src/codeSign/codesign.ts#L25
