### ISSUE TITLE
Auto update not working with NSIS

### ISSUE THREAD

**Issue by Omar-ABDELNABY** [electron-userland/electron-builder#4544]
* **Version**:  21.2.0

electron-update version: 4.2.0

* **Target**:  NSIS

I get below message when auto updating:

Download block maps (old: "https://api.github.com/repos/Omar-ABDELNABY/esignaturDesktopApp-release/releases/assets/16872434.blockmap", new: https://api.github.com/repos/Omar-ABDELNABY/esignaturDesktopApp-release/releases/assets/16872434.blockmap)

first: the old and new urls are the SAME!
second: this is not the url of the blockmap file, but rather JSON info of the .exe installer

then I get the below error:
[error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Program Files\esignatur_Desktop\esignatur_Desktop\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:239:26)
    at ClientRequest.<anonymous> (C:\Program Files\esignatur_Desktop\esignatur_Desktop\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:298:17)
    at ClientRequest.emit (events.js:203:13)
    at URLRequest.<anonymous> (electron/js2c/browser_init.js:2402:12)
    at URLRequest.emit (events.js:203:13)

It seems that updater tried to download the ".exe" itself instead of the blockmap, and got this error due to the buffer size limitation

@develar Please support

**Comment by Omar-ABDELNABY** [comment]
I tried in "NsisUpdater" to replace these two lines (246, 247) 

// const newBlockMapUrl = (0, _main().newUrlFromBase)(`${fileInfo.url.pathname}.blockmap`, fileInfo.url);
// const oldBlockMapUrl = (0, _main().newUrlFromBase)(`${fileInfo.url.pathname.replace(new RegExp(downloadUpdateOptions.updateInfoAndProvider.info.version, "g"), this.currentVersion.version)}.blockmap`, fileInfo.url);

with these: 

const newBlockMapUrlString = downloadUpdateOptions.updateInfoAndProvider.info.assets.filter(asset => asset.name.endsWith(".blockmap"))[0].browser_download_url;
      const newBlockMapUrl = new URL(newBlockMapUrlString);
      const oldBlockMapUrl = new URL(newBlockMapUrlString.replace(new RegExp(downloadUpdateOptions.updateInfoAndProvider.info.version, "g"), this.currentVersion.version));

to get the right blockmaps URL but I got a new error related to checksum mismatch (despite I did run the release i downloaded from github after uploading it !!!)

[2019-12-19 10:35:30.368] [info] Download block maps (old: "https://github.com/Omar-ABDELNABY/esignaturDesktopApp-release/releases/download/v7.0.40/esignatur_Desktop.exe.blockmap", new: https://github.com/Omar-ABDELNABY/esignaturDesktopApp-release/releases/download/v7.0.41/esignatur_Desktop.exe.blockmap)
[2019-12-19 10:35:35.421] [info] File has 367 changed blocks
[2019-12-19 10:35:35.449] [info] Full: 113,665.86 KB, To download: 7,785.66 KB (7%)
[2019-12-19 10:35:36.591] [info] Differential download: https://api.github.com/repos/Omar-ABDELNABY/esignaturDesktopApp-release/releases/assets/16895372
[2019-12-19 10:35:42.234] [error] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected pchBdqP+PQ38zjnzjmInqiRQ6dVvELthKRw65fmqAtt5Ks3nTIlEoUER+rIrxXHykGYuPfzfDVD6BINahLNwmQ==, got DpgVnBprmlz9dPSjhJNSZWcVHPA7HdNwspHLzce6R38zJjDipJf6xIYLJuQ++j0ZLABha6ZxnS7e8lhVnb5A6Q==
    at newError (C:\Program Files\esignatur_Desktop\esignatur_Desktop\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\index.js:212:17)
    at DigestTransform.validate (C:\Program Files\esignatur_Desktop\esignatur_Desktop\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:403:35)
    at WriteStream.<anonymous> (C:\Program Files\esignatur_Desktop\esignatur_Desktop\resources\app.asar\node_modules\electron-updater\out\differentialDownloader\DifferentialDownloader.js:186:29)
    at WriteStream.emit (events.js:203:13)
    at internal/fs/streams.js:224:14
    at C:\Program Files\esignatur_Desktop\esignatur_Desktop\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:153:23)

**Comment by Omar-ABDELNABY** [comment]
@develar  a little help please

**Comment by MD-AZMAL** [comment]
Having the same issue for these versions in public github repository as well
