### ISSUE TITLE
Publish fails with `EEXIST: file already exists, symlink`

### ISSUE THREAD

**Issue by vladh** [electron-userland/electron-builder#4559]
* **Version**:  21.2.0

* **Target**: 4.2.0

When running, `npm run publish`, I get the following output:

```
vladh sundae my-app:release $ npm run publish

> myapp@1.1.28 publish /mypath
> electron-builder -p always

  • electron-builder  version=21.2.0 os=19.2.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@serialport/bindings@2.0.2, sharp@0.22.1, sqlite3@4.0.4 platform=darwin arch=x64
  • install prebuilt binary  name=sharp version=0.22.1 platform=darwin arch=x64
  • install prebuilt binary  name=@serialport/bindings version=2.0.2 platform=darwin arch=x64
  • build native dependency from sources  name=@serialport/bindings
                                          version=2.0.2
                                          platform=darwin
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.2.2
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ /Users/vladh/.npm/_prebuilds/ff3637-bindings-v2.0.2-electron-v57-darwin-x64.tar.gz
    prebuild-install http request GET https://github.com/node-serialport/node-serialport/releases/download/v2.0.2/bindings-v2.0.2-electron-v57-darwin-x64.tar.gz
    prebuild-install http 404 https://github.com/node-serialport/node-serialport/releases/download/v2.0.2/bindings-v2.0.2-electron-v57-darwin-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=2.0.13 runtime=electron arch=x64 platform=darwin)

  • packaging       platform=darwin arch=x64 electron=2.0.13 appOutDir=dist/mac
  ⨯ EEXIST: file already exists, symlink '../he/bin/he' -> '/mypath/dist/mac/myapp.app/Contents/Resources/data/my-git-submodule/node_modules/mocha/node_modules/.bin/he'  stackTrace=
    Error: EEXIST: file already exists, symlink '../he/bin/he' -> '/mypath/dist/mac/myapp.app/Contents/Resources/data/my-git-submodule/node_modules/mocha/node_modules/.bin/he'
        at processImmediate (internal/timers.js:439:21)
    From previous event:
        at /mypath/node_modules/builder-util/src/fs.ts:306:33
```

If I try to set the environment variable `USE_HARD_LINKS=true`, I then get:

```
> myapp@1.1.28 publish /mypath
> electron-builder -p always

  • electron-builder  version=21.2.0 os=19.2.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@serialport/bindings@2.0.2, sharp@0.22.1, sqlite3@4.0.4 platform=darwin arch=x64
  • install prebuilt binary  name=sharp version=0.22.1 platform=darwin arch=x64
  • install prebuilt binary  name=@serialport/bindings version=2.0.2 platform=darwin arch=x64
  • build native dependency from sources  name=@serialport/bindings
                                          version=2.0.2
                                          platform=darwin
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.2.2
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ /Users/vladh/.npm/_prebuilds/ff3637-bindings-v2.0.2-electron-v57-darwin-x64.tar.gz
    prebuild-install http request GET https://github.com/node-serialport/node-serialport/releases/download/v2.0.2/bindings-v2.0.2-electron-v57-darwin-x64.tar.gz
    prebuild-install http 404 https://github.com/node-serialport/node-serialport/releases/download/v2.0.2/bindings-v2.0.2-electron-v57-darwin-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=2.0.13 runtime=electron arch=x64 platform=darwin)

  • packaging       platform=darwin arch=x64 electron=2.0.13 appOutDir=dist/mac
  ⨯ EEXIST: file already exists, link '/mypath/data/my_data_file.dat' -> '/mypath/dist/mac/myapp.app/Contents/Resources/data/my_data_file.dat'  stackTrace=
    Error: EEXIST: file already exists, link '/mypath/data/my_data_file.dat' -> '/mypath/dist/mac/myapp.app/Contents/Resources/data/my_data_file.dat'
        at processImmediate (internal/timers.js:439:21)
    From previous event:
        at walk (/mypath/node_modules/builder-util/src/fs.ts:75:51)
        at /mypath/node_modules/app-builder-lib/src/fileMatcher.ts:332:12
```

#3179 and #3397 also report this issue but have been closed. If you could point me in the right direction so I could release the latest version of our software, I would be very grateful! :)

**Comment by vladh** [comment]
I seem to have identified the issue. `node_modules/.bin` is excluded from the build by default, but I also had the following directories:

* `node_modules/mocha/node_modules/.bin`
* `my-submodule/node_modules/.bin`
* `my-submodule/node_modules/mocha/node_modules/.bin`

These files presumably do not match the default exclusion patterns, and were not excluded from the build. The `.bin` symlinks could for some reason not be copied, resulting in the error.

My proposed resolution is to change the default pattern from the (presumably) current `/node_modules/.bin` to `node_modules/.bin`.
