### ISSUE TITLE
Docker image is broken

### ISSUE THREAD

**Issue by Aviortheking** [electron-userland/electron-builder#4573]
* **Version**: 21.0.11

* **Target**: pacman, windows-portable

when trying to run the image as the doc says, it throws errors
```
❯ docker run --rm -ti  --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_')  --env ELECTRON_CACHE="/root/.cache/electron"  --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder"  -v ${PWD}:/project  -v ${PWD##*/}-node-modules:/project/node_modules  -v ~/.cache/electron:/root/.cache/electron  -v ~/.cache/electron-builder:/root/.cache/electron-builder  electronuserland/builder:wine /bin/bash -c "yarn && yarn dist"
/usr/bin/yarn: 2: /usr/bin/yarn: sed: not found
/usr/bin/yarn: 3: /usr/bin/yarn: readlink: not found
/usr/bin/yarn: 5: /usr/bin/yarn: uname: not found
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module '/project/yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by belvederef** [comment]
I am facing the same problem.
