### ISSUE TITLE
icudtl.dat: file changed as we read it

### ISSUE THREAD

**Issue by wesleywesley** [electron-userland/electron-builder#460]
This happened only after I added linux section in package.json: 

```
    "linux": {
      "target": ["deb", "rpm", "tar.gz"]
    }

```
```

/usr/local/opt/gnu-tar/libexec/gnubin/tar: /Users/me/Desktop/xyz/app/dist/linux/icudtl.dat: file changed as we read it
Unhandled rejection Error: /usr/local/opt/gnu-tar/libexec/gnubin/tar exited with code 1
    at ChildProcess.childProcess.on.code (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/util.ts:118:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at Object.spawn (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/util.ts:103:9)
    at LinuxPackager.<anonymous> (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/platformPackager.ts:326:18)
    at undefined.next (native)
From previous event:
    at tsAwaiter (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/awaiter.ts:10:47)
    at Object.build (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/builder.ts:171:52)
    at Object.<anonymous> (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/build-cli.ts:8:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

Error: /usr/local/opt/gnu-tar/libexec/gnubin/tar exited with code 1
    at ChildProcess.childProcess.on.code (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/util.ts:118:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at Object.spawn (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/util.ts:103:9)
    at LinuxPackager.<anonymous> (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/platformPackager.ts:326:18)
    at undefined.next (native)
From previous event:
    at tsAwaiter (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/awaiter.ts:10:47)
    at Object.build (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/builder.ts:171:52)
    at Object.<anonymous> (/Users/me/Desktop/xyz/app/node_modules/electron-builder/src/build-cli.ts:8:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

```

**Comment by wesleywesley** [comment]
I'm using 4.2.0 FYI.

**Comment by mzmousa** [comment]
+1
Getting this exact same error

**Comment by develar** [comment]
We cannot use FPM in parallel, it is known issue to investigate. But we cannot even run tar if fpm working — for now disable parallel building for FPM.

**Comment by jtbandes** [comment]
It's been years since this was patched but I am seeing this issue again: `tar: ./opt/Foxglove Studio/resources/app/renderer/main.js: file changed as we read it`. I found this by adding `"fpm": ["--verbose", "--debug"]` to my deb config.

The code that was originally fixed no longer seems to be present in linuxPackager.ts or fpm.ts. Was another fix made? Or any idea why it was removed?
