### ISSUE TITLE
macos build fails with "struct.error" on zipping

### ISSUE THREAD

**Issue by b-zurg** [electron-userland/electron-builder#4607]
* **electron-builder Version**: "^21.2.0"

* **electron-updater version**: "^4.1.2"

* **Target**: macos

Running the following build script:
`electron-builder --config electron-builder.json`

It runs mostly fine until a certain point.  Here is the output:
```
yarn run v1.21.1
$ electron-builder --config configs/electron-builder.json
  • electron-builder  version=21.2.0 os=19.2.0
  • loaded configuration  file=/Users/xxx/Documents/GIT/desktop-app/configs/electron-builder.json
  • loaded parent configuration  file=/Users/xxx/Documents/GIT/desktop-app/node_modules/electron-webpack/out/electron-builder.js
  • packaging       platform=darwin arch=x64 electron=7.1.9 appOutDir=build/packaged/mac
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                                   0 identities found
                                              
                                                Valid identities only
                                                   0 valid identities found
  • building        target=macOS zip arch=x64 file=build/packaged/app-0.0.1-alpha-mac.zip
  • building        target=DMG arch=x64 file=build/packaged/app-0.0.1-alpha.dmg
  • building embedded block map  file=build/packaged/app-0.0.1-alpha-mac.zip
  ⨯ Exit code: 1. Command failed: /usr/bin/python /Users/xxx/Documents/GIT/desktop-app/node_modules/dmg-builder/vendor/dmgbuild/core.py
Traceback (most recent call last):
  File "/Users/xxx/Documents/GIT/desktop-app/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 282, in <module>
    build_dmg()
  File "/Users/xxx/Documents/GIT/desktop-app/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 253, in build_dmg
    icvp['backgroundImageAlias'] = biplist.Data(alias.to_bytes())
  File "/Users/xxx/Documents/GIT/desktop-app/node_modules/dmg-builder/vendor/mac_alias/alias.py", line 589, in to_bytes
    self._to_fd(b)
  File "/Users/xxx/Documents/GIT/desktop-app/node_modules/dmg-builder/vendor/mac_alias/alias.py", line 476, in _to_fd
    *self.target.cnid_path)
struct.error: 'I' format requires 0 <= number <= 4294967295

Traceback (most recent call last):
  File "/Users/xxx/Documents/GIT/desktop-app/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 282, in <module>
    build_dmg()
  File "/Users/xxx/Documents/GIT/desktop-app/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 253, in build_dmg
    icvp['backgroundImageAlias'] = biplist.Data(alias.to_bytes())
  File "/Users/xxx/Documents/GIT/desktop-app/node_modules/dmg-builder/vendor/mac_alias/alias.py", line 589, in to_bytes
    self._to_fd(b)
  File "/Users/xxx/Documents/GIT/desktop-app/node_modules/dmg-builder/vendor/mac_alias/alias.py", line 476, in _to_fd
    *self.target.cnid_path)
struct.error: 'I' format requires 0 <= number <= 4294967295
  stackTrace=
````

The last logged error seems to indicate a known bug in certain versions of python (see: https://stackoverflow.com/questions/6911777/python-error-when-zipping-files-l-format-requires-0-number-4294967295 )

I tried to eliminate the possibility of this bug affecting it by installing python3 with brew and making the following aliases in my .zshrc file
```
alias python=/usr/local/bin/python3
alias /usr/bin/python=/usr/local/bin/python3
```

And this has take effect but doesn't seem to change anything. 

Do you guys have any ideas?  I think it has to do with the size of the package that's being zipped (I'm including some rather large but necessary dependencies in the packaging) but this has no issue on my windows build.

**Comment by catmans1** [comment]
I've a same thing.
Any solution or suggestion for that?
