### ISSUE TITLE
AppImage build failing when file association extension is an array

### ISSUE THREAD

**Issue by ollm** [electron-userland/electron-builder#4612]
* **Version**: 22.3.1

* **Target**: AppImage

There is currently an error building for AppImage when the file association extension is an array, this error is only present in AppImage, in other formats it works correctly.

This is the error you are currently giving:

```
⨯ appimage.AppImageConfiguration.FileAssociations: []appimage.FileAssociation: appimage.FileAssociation.Ext: ReadString: expects " or n, but found [, error found in #10 byte of ...|G","ext":["jpg","jpe|..., bigger context ...|eAssociations":[{"description":"Image JPG","ext":["jpg","jpeg","jif","jfi","jfif","jfif-tbnl","jpe"]|...  
⨯ /my-app-dir/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
           Error: /my-app-dir/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
               at ChildProcess.<anonymous> (/my-app-dir/node_modules/builder-util/src/util.ts:239:14)
               at Object.onceWrapper (events.js:313:26)
               at ChildProcess.emit (events.js:223:5)
               at maybeClose (internal/child_process.js:1021:16)
               at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

For example, this works
```
"fileAssociations": [
	{
		"description": "Image JPG",
		"ext": "jpg",
		"role": "Viewer"
	}
]
```
But this gives error
```
"fileAssociations": [
	{
		"description": "Image JPG",
		"ext": [
			"jpg",
			"jpeg",
			"jif",
			"jfi",
			"jfif",
			"jfif-tbnl",
			"jpe"
		],
		"role": "Viewer"
	}
]
```

**Comment by ollm** [comment]
This issue is the same bug https://github.com/electron-userland/electron-builder/issues/3204
