### ISSUE TITLE
Build win ia32 exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

### ISSUE THREAD

**Issue by zlab** [electron-userland/electron-builder#4629]
"electron": "^7.1.11",
 "electron-builder": "^22.3.2"

* **Version**: 

"electron-updater": "^4.2.0"

* **Target**: 
Mac 10.13.6 
electron-builder --win --ia32 
target: nsis

## which was built for Mac OS X 10.15 ??
```
Error output:
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/zhanqi/Library/Caches/electron-builder/nsis/nsis-3.0.4.1/mac/makensis
 (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/zhanqi/Library/Caches/electron-builder/nsis/nsis-3.0.4.1/mac/makensis 
(which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

  stackTrace=
```

![image](https://user-images.githubusercontent.com/2288630/73587346-a5f20780-44f5-11ea-9125-8c9ab7fef891.png)

**Comment by anubhav04** [comment]
Instead of darwin use squirrel by 'yarn add electron-builder-squirrel-windows' or 'npm install electron-builder-squirrel-windows'. Then run the build command. Hope it will work for you, it worked for me.

**Comment by GitNomster** [comment]
I have same problem when building win x32 and x64 on mac. Only helps downgrading builder to v. 21.2.0

**Comment by sentialx** [comment]
Even building on a Windows machine throws the same error `ERR_ELECTRON_BUILDER_CANNOT_EXECUTE`. Downgrading to 21.2.0 also helps.

**Comment by Agent77326** [comment]
I ran into the same problem:
```
electron-builder --publish never -mwl
  • electron-builder  version=22.4.1 os=17.4.0
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=fsevents@1.2.11 platform=darwin arch=x64
  • rebuilding native dependency  name=fsevents version=1.2.11
  • packaging       platform=darwin arch=x64 electron=8.1.1 appOutDir=dist/mac
  • downloading     url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-darwin-x64.zip size=66 MB parts=4
  • downloaded      url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-darwin-x64.zip duration=2.556s
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                                   0 identities found
                                              
                                                Valid identities only
                                                   0 valid identities found
  • building        target=DMG arch=x64 file=dist/Software-Challenge-GUI-mac-20.3.4.dmg
  • rebuilding native dependencies  dependencies=fsevents@1.2.11 platform=linux arch=x64
  • rebuilding native dependency  name=fsevents version=1.2.11
  • packaging       platform=linux arch=x64 electron=8.1.1 appOutDir=dist/linux-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-linux-x64.zip size=71 MB parts=4
  • downloaded      url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-linux-x64.zip duration=1.48s
  • building        target=AppImage arch=x64 file=dist/Software-Challenge-GUI-linux-20.3.4.AppImage
  • rebuilding native dependencies  dependencies=fsevents@1.2.11 platform=win32 arch=x64
  • rebuilding native dependency  name=fsevents version=1.2.11
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=825ms
  • packaging       platform=win32 arch=x64 electron=8.1.1 appOutDir=dist/win-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-win32-x64.zip size=71 MB parts=4
  • downloaded      url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-win32-x64.zip duration=2.008s
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=851ms
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/wine-2.0.3-mac-10.13/wine-2.0.3-mac-10.13.7z size=26 MB parts=4
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/wine-2.0.3-mac-10.13/wine-2.0.3-mac-10.13.7z duration=1.28s
  • rebuilding native dependencies  dependencies=fsevents@1.2.11 platform=win32 arch=ia32
  • rebuilding native dependency  name=fsevents version=1.2.11
  • building block map  blockMapFile=dist/Software-Challenge-GUI-mac-20.3.4.dmg.blockmap
  • packaging       platform=win32 arch=ia32 electron=8.1.1 appOutDir=dist/win-ia32-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-win32-ia32.zip size=68 MB parts=4
  • downloaded      url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-win32-ia32.zip duration=1.994s
  • building        target=nsis file=dist/Software-Challenge-GUI-win-20.3.4.exe archs=x64, ia32 oneClick=false perMachine=false
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.2/nsis-3.0.4.2.7z size=1.4 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.2/nsis-3.0.4.2.7z duration=775ms
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z size=731 kB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z duration=656ms
  ⨯ /Users/travis/caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Error output:
Error output:
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/travis/caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/travis/caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
  stackTrace=

Error: /Users/travis/caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Error output:


Error output:

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin

Referenced from: /Users/travis/caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis (which was built for Mac OS X 10.15)

Expected in: /usr/lib/libSystem.B.dylib


dyld: Symbol not found: ____chkstk_darwin

Referenced from: /Users/travis/caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis (which was built for Mac OS X 10.15)

Expected in: /usr/lib/libSystem.B.dylib

at ChildProcess.<anonymous> (/Users/travis/build/CAU-Kiel-Tech-Inf/socha-gui/node_modules/builder-util/src/util.ts:239:14)
at Object.onceWrapper (events.js:418:26)
at ChildProcess.emit (events.js:311:20)
at maybeClose (internal/child_process.js:1021:16)
at Socket.<anonymous> (internal/child_process.js:443:11)
at Socket.emit (events.js:311:20)
at Pipe.<anonymous> (net.js:668:12)
error Command failed with exit code 1.
```
Downgrading was so far (as of today) the only workaround.

**Comment by Agent77326** [comment]
Could it be that currently ia32 is not supported for OSX < 10.15 (aka Catalina)?

**Comment by jontonsoup** [comment]
I have this issue using the wine linux docker. 

```
yarn run v1.22.0

$ yarn run build && electron-builder --ia32 --publish always

$ yarn run copy-template && tsc

$ copyfiles -u 1 ./src/**/*.html ./dist && copyfiles -u 1 ./src/**/*.css ./dist

  • electron-builder  version=22.5.1 os=4.15.0-1052-aws

  • loaded configuration  file=package.json ("build" field)

  • packaging       platform=linux arch=ia32 electron=8.2.1 appOutDir=dist/linux-ia32-unpacked

  • downloading     url=https://github.com/electron/electron/releases/download/v8.2.1/electron-v8.2.1-linux-ia32.zip size=72 MB parts=8

  • downloaded      url=https://github.com/electron/electron/releases/download/v8.2.1/electron-v8.2.1-linux-ia32.zip duration=657ms

  • building        target=snap arch=ia32 file=dist/live-data-entry_1.0.15_i386.snap

  • building        target=AppImage arch=ia32 file=dist/Live Data Entry-1.0.15-i386.AppImage

  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux

  • default Electron icon is used  reason=application icon is not set

  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux

  ⨯ snapcraft is not installed, please: sudo snap install snapcraft --classic  

  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1

  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=120ms

  ⨯ /root/project/desktop/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=

                                                                                                                                     Error: /root/project/desktop/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

                                                                                                                                         at ChildProcess.<anonymous> (/root/project/desktop/node_modules/builder-util/src/util.ts:243:14)

                                                                                                                                         at Object.onceWrapper (events.js:418:26)

                                                                                                                                         at ChildProcess.emit (events.js:311:20)

                                                                                                                                         at maybeClose (internal/child_process.js:1021:16)

                                                                                                                                         at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

  • publishing      publisher=S3 (bucket: live-data-entry-client)

  • uploading       file=Live Data Entry-1.0.15-i386.AppImage provider=S3

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by jflorindezr** [comment]
This is still happening. I had to downgrade to 21.2.0 to make it work.

**Comment by vivekcheerla** [comment]
even after downgrading the issue still happening.

**Comment by miyanoshiyo** [comment]
@jontonsoup  Same problem, how did you solve it?

**Comment by jontonsoup** [comment]
Forced my users to get off 32 bit windows

**Comment by realrecordzLab** [comment]
Same problem when try build with vue cli ui. Also my `vue.config.js` is ignored and I'm unable to create portable release of my app.

**Comment by engina** [comment]
Problem persists. Downgrading to 21.2.0 works for me as well.

**Comment by realrecordzLab** [comment]
How do you do the downgrade procedure?If I try to do it, vue ui will always
use the last version of electron builder.

Il giorno ven 15 gen 2021 alle ore 19:37 Engin A <notifications@github.com>
ha scritto:

**Comment by Kupstas** [comment]
Same error at `22.10.5`

**Comment by redplane** [comment]
So frustrating.
I have the same issue with electron-buider version `22.10.5` on raspberry pi 4

**Comment by ufukomer** [comment]
+1 

electron-builder: 22.10.5
electrion: 12.0.2

**Comment by ufukomer** [comment]
@neviko I was getting same error while trying to build on Mac and the solution was to agreeing the Xcode agreement or something like that using this command:

`
sudo xcodebuild -license
`
