### ISSUE TITLE
Error installing electron-builder with yarn

### ISSUE THREAD

**Issue by xAgustin93** [electron-userland/electron-builder#4668]
* **Yarn Version**: 1.22.0
When I run the electron-builder installation generates the following error, I use version 1.22.0 of Yarn.

![Captura de pantalla 2020-02-12 a las 0 09 40](https://user-images.githubusercontent.com/25793726/74288665-45509f00-4d2d-11ea-98a9-392ab8271fce.png)

`
yarn add electron-builder --dev
yarn add v1.22.0

[1/4] 🔍  Resolving packages...
error Couldn't find package "7zip-bin@~5.0.3" required by "builder-util@22.3.2" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "7zip-bin@~5.0.3" required by "app-builder-lib@22.3.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
Error: Couldn't find package "7zip-bin@~5.0.3" required by "app-builder-lib@~22.3.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
Error: Couldn't find package "7zip-bin@~5.0.3" required by "builder-util@~22.3.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
`

**Comment by EricGeigerQ** [comment]
Also having this issue. Looks like the 7zip-bin npm registry is empty. Also, I don't see any releases in the GitHub repo for that project.

**Comment by xAgustin93** [comment]
The problem is that your package exceeds 7zip-bin then if yours fails too.

**Comment by hugozap** [comment]
I'm having this issue too after trying to install dependencies with yarn. Not sure what's going on with the 7zip-bin dep.

**Comment by hugozap** [comment]
It looks like an npm registry issue with packages that start with a digit.
It was updated but could take a few hours to be available.
 More info here https://github.com/yarnpkg/yarn/issues/7902

**Comment by netstratum-labs** [comment]
Not working even after 10 hours. Any other fixes?

**Comment by EricGeigerQ** [comment]
Still broken for me, as well.

**Comment by hugozap** [comment]
Npm incident status: https://status.npmjs.org/incidents/lvgmcrfvrvsh?u=wvmhttll6lh5

**Comment by lmcbout** [comment]
Broken for me as well

**Comment by timfish** [comment]
@xAgustin93 can this be closed now?

**Comment by xAgustin93** [comment]
Yes, the problem is already solved.
