### ISSUE TITLE
electron-builder install-app-deps fails

### ISSUE THREAD

**Issue by heikkimu** [electron-userland/electron-builder#4694]
* **Version**: 22.3.2

* **Target**: 

Hello,

I've a postinstall issue. I'm currently using ubuntu-shell at Windows WSL.

This os tegularly failing at postinstall.

I've tried to install grpc and other stuff from sources, but couln’t resolve the issue. Any pointers where to head next?

```bash
xxxx@me:/mnt/c/dev/testproject$ $(npm bin)/electron-builder install-app-deps
  • electron-builder  version=22.3.2
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  • rebuilding native dependencies  dependencies=grpc@1.23.3 platform=linux arch=x64
  ⨯ cannot execute  cause=exit status 1
                    out=
    > grpc@1.23.3 install /mnt/c/dev/testproject/node_modules/grpc
    > node-pre-gyp install --fallback-to-build --library=static_library

    Failed to execute '/home/xxxx/.nvm/versions/node/v12.16.1/bin/node /home/xxxx/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/mnt/c/dev/testproject/node_modules/grpc/src/node/extension_binary/electron-v8.0-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/mnt/c/dev/testproject/node_modules/grpc/src/node/extension_binary/electron-v8.0-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v8.0' (1)

                    errorOut=node-pre-gyp WARN Using request for node-pre-gyp https download
    (node:2150) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
    node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/electron-v8.0-linux-x64-glibc.tar.gz
    node-pre-gyp WARN Pre-built binaries not found for grpc@1.23.3 and electron@8.0.1 (electron-v8.0 ABI, glibc) (falling back to source compile with node-gyp)
    (node:2173) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
    gyp WARN install got an error, rolling back install
    gyp ERR! configure error
    gyp ERR! stack Error: write EPROTO 140325374920576:error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 49
    gyp ERR! stack
    gyp ERR! stack     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
    gyp ERR! System Linux 4.4.0-18362-Microsoft
    gyp ERR! command "/home/xxxx/.nvm/versions/node/v12.16.1/bin/node" "/home/xxxx/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/mnt/c/dev/testproject/node_modules/grpc/src/node/extension_binary/electron-v8.0-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/mnt/c/dev/testproject/node_modules/grpc/src/node/extension_binary/electron-v8.0-linux-x64-glibc" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v8.0"
    gyp ERR! cwd /mnt/c/dev/testproject/node_modules/grpc
    gyp ERR! node -v v12.16.1
    gyp ERR! node-gyp -v v5.0.5
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute '/home/xxxx/.nvm/versions/node/v12.16.1/bin/node /home/xxxx/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/mnt/c/dev/testproject/node_modules/grpc/src/node/extension_binary/electron-v8.0-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/mnt/c/dev/testproject/node_modules/grpc/src/node/extension_binary/electron-v8.0-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v8.0' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mnt/c/dev/testproject/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    node-pre-gyp ERR! System Linux 4.4.0-18362-Microsoft
    node-pre-gyp ERR! command "/home/xxxx/.nvm/versions/node/v12.16.1/bin/node" "/mnt/c/dev/testproject/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
    node-pre-gyp ERR! cwd /mnt/c/dev/testproject/node_modules/grpc
    node-pre-gyp ERR! node -v v12.16.1
    node-pre-gyp ERR! node-pre-gyp -v v0.13.0
    node-pre-gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the grpc@1.23.3 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/xxxx/.npm/_logs/2020-02-21T15_49_19_846Z-debug.log

                    command=npm rebuild grpc@1.23.3
                    workingDir=
```

**Comment by heikkimu** [comment]
I also tried this at fresh Linux mint image with headers and developer tools installed. The postinstall failed with npm and was working with yarn.
