### ISSUE TITLE
I have a question Mac os build windows 64 error "dist/__uninstaller-nsis-app.exe" -> no files found."

### ISSUE THREAD

**Issue by wq155** [electron-userland/electron-builder#4724]
• electron-builder  version=21.2.0 os=19.2.0

Error output:

Error output:
File: "/Users/admin/work/app/dist/__uninstaller-nsis-app.exe" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in macro installApplicationFiles on macroline 78
!include: error in script: "installSection.nsh" on line 60
Error in script "<stdin>" on line 161 -- aborting creation process

    at ChildProcess.<anonymous> (/Users/admin/work/app/node_modules/_builder-util@21.2.0@builder-util/src/util.ts:239:14)
    at Object.onceWrapper (events.js:300:26)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by mozhengFly** [comment]
@wq155 can you tell me how to slove the problem?

**Comment by rnowak8** [comment]
@wq155 I have the same issue, did you resolve that?
