### ISSUE TITLE
Signing application on Windows fails since electron-builder 22.3

### ISSUE THREAD

**Issue by wartab** [electron-userland/electron-builder#4729]
* **Version**: 22.3.5
* **Target**: nsis-web

It's been a few weeks, since we had to stop upgrading our electron-builder dependency to electron-builder@22.3, because of the following issue:
```
  • electron-builder  version=22.3.5 os=10.0.17763
  • loaded configuration  file=package.json ("build" field)
  • description is missed in the package.json  appPackageFile=C:\Users\Vincent\app-mobile\build\electron\app\package.json
  • packaging       platform=win32 arch=x64 electron=8.0.3 appOutDir=dist\win-unpacked
  ⨯ Cannot find certificate <redacted>, all certs: {"Subject":"CN=<redacted>, O=<redacted>, STREET=<redacted>, L=<redacted>, S=<redacted>, PostalCode=<redacted>, C=<redacted>, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.3=<redacted>, SERIALNUMBER=<redacted>","PSParentPath":"Microsoft.PowerShell.Security\\Certificate::CurrentUser\\My","Thumbprint":"FD1BC95083AB5158DC1D43C3EDA4F799C660712D"}
  stackTrace=
        Error: Cannot find certificate <redacted>, all certs: {"Subject":"CN=<redacted>, O=<redacted>, STREET=<redacted>, L=<redacted>, S=<redacted>, PostalCode=<redacted>, C=<redacted>, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.3=<redacted>, SERIALNUMBER=<redacted>","PSParentPath":"Microsoft.PowerShell.Security\\Certificate::CurrentUser\\My","Thumbprint":"FD1BC95083AB5158DC1D43C3EDA4F799C660712D"}

            at getCertificateFromStoreInfo (C:\Users\Vincent\app-mobile\build\electron\node_modules\app-builder-lib\src\codeSign\windowsCodeSign.ts:138:9)
            at processTicksAndRejections (internal/process/task_queues.js:89:5)
            at WinPackager.signAndEditResources (C:\Users\Vincent\app-mobile\build\electron\node_modules\app-builder-lib\src\winPackager.ts:292:106)
        From previous event:
            at processImmediate (internal/timers.js:439:21)
        From previous event:
            at WinPackager.signApp (C:\Users\Vincent\app-mobile\build\electron\node_modules\app-builder-lib\src\winPackager.ts:357:27)
            at WinPackager.doPack (C:\Users\Vincent\app-mobile\build\electron\node_modules\app-builder-lib\src\platformPackager.ts:243:16)
            at WinPackager.pack (C:\Users\Vincent\app-mobile\build\electron\node_modules\app-builder-lib\src\platformPackager.ts:114:5)
            at Packager.doBuild (C:\Users\Vincent\app-mobile\build\electron\node_modules\app-builder-lib\src\packager.ts:444:9)
            at executeFinally (C:\Users\Vincent\app-mobile\build\electron\node_modules\builder-util\src\promise.ts:12:14)
            at Packager._build (C:\Users\Vincent\app-mobile\build\electron\node_modules\app-builder-lib\src\packager.ts:373:31)
            at Packager.build (C:\Users\Vincent\app-mobile\build\electron\node_modules\app-builder-lib\src\packager.ts:337:12)
            at executeFinally (C:\Users\Vincent\app-mobile\build\electron\node_modules\builder-util\src\promise.ts:12:14)
child process exited with code 1
```

It works in 22.2 and we are clueless about what this issue is caused by.

**Comment by wartab** [comment]
To clarify: the certificate name that cannot be found is actually listed in the all certs object.

**Comment by kzimny** [comment]
Check if it works in v.22.3.6

**Comment by wartab** [comment]
No, that does not work, not surprising given I talked about Windows and that update is Mac related.

That said, I tried the 22.4.0 version and that seems to work.
