### ISSUE TITLE
Windows build failed on MacOS High Sierra

### ISSUE THREAD

**Issue by GitNomster** [electron-userland/electron-builder#4760]
* **Version**: 22.4.0
* **Target**: Win x32
Trying to build Win x32 on macOS v. 10.13.3, but its failed.
```
• building target=nsis file=dist/electron-webpack-quick-start Setup 0.0.0.exe archs=ia32 oneClick=true perMachine=false
  ⨯ /Users/test014/Library/Caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Error output:

Error output:
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/test014/Library/Caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/test014/Library/Caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

  stackTrace=
    Error: /Users/test014/Library/Caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    Error output:

    Error output:
    dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
    Referenced from: /Users/test014/Library/Caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis (which was built for Mac OS X 10.15)
    Expected in: /usr/lib/libSystem.B.dylib

    dyld: Symbol not found: ____chkstk_darwin
    Referenced from: /Users/test014/Library/Caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis (which was built for Mac OS X 10.15)
    Expected in: /usr/lib/libSystem.B.dylib

        at ChildProcess.<anonymous> (/Users/test014/testing/electron-webpack-quick-start/node_modules/builder-util/src/util.ts:239:14)
        at Object.onceWrapper (events.js:423:26)
        at ChildProcess.emit (events.js:316:20)
        at maybeClose (internal/child_process.js:1026:16)
        at Socket.<anonymous> (internal/child_process.js:441:11)
        at Socket.emit (events.js:316:20)
        at Pipe.<anonymous> (net.js:672:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-webpack-quick-start@0.0.0 dist: `npm run compile && electron-builder --win --ia32`
npm ERR! Exit status 1
```
All is ok with electron-builder v. 21.2.0.

**Comment by Agent77326** [comment]
Duplicate #4629

**Comment by wolfiex** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
> 
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

Which generally occurs from a lack of an answer?

**Comment by fromcouch** [comment]
I have the same problem. 
 Mac Os X High Sierra here 10.13.6 with electron 10.0.7 and electron-builder 23.6.0 and i have same error when building for windows.

What's the solution finally?

**Comment by Yasamato** [comment]
@fromcouch, in #4629 the solution was to either not compile for ia32 (win 32bit) or downgrade your version of electron-builder to `21.2.x`
