### ISSUE TITLE
javaScript error occurred in the main process

### ISSUE THREAD

**Issue by ajmetal** [electron-userland/electron-builder#4770]
Version 21.2.0

* **Target**: Windows x64

My Electron app runs fine using electron from the command line, but after I've built it from an executable and try to run it I get: 

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: The specified module could not be found.
\\?\C:\Users\username\AppData\Local\Temp\808c0bf6-a0f1-4211-a312-7c0cce29173a.tmp.node
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)

[OK]
```

I don't know how to reproduce the error yet. Does anyone know why the app is attempting to load a module from AppData\Local? What module is this? How do I debug this problem?

**Comment by aabuhijleh** [comment]
Your app is trying to run a `.node` file from the `%temp%` directory. The reason behind this issue is that Windows cannot run `node|dll|exeutable` files from the `asar` package.

To fix this, add this to your `electron-builder` configuration

```json
"asarUnpack": ["**/*.node"]
```

**Comment by CircleOnCircles** [comment]
I have a similar error.
```
electron/js2c/asar.js:138 Uncaught (in promise) Error: The specified module could not be found.
\\?\C:\Users\User\AppData\Local\Temp\b3ccaeda-cfb0-43e5-868c-cab1254fdf7d.tmp.node
    at process.func (electron/js2c/asar.js:138)
    at process.func [as dlopen] (electron/js2c/asar.js:138)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828)
    at Object.func (electron/js2c/asar.js:138)
    at Object.func [as .node] (electron/js2c/asar.js:147)
    at Module.load (internal/modules/cjs/loader.js:645)
    at Function.Module._load (internal/modules/cjs/loader.js:560)
    at Module.require (internal/modules/cjs/loader.js:685)
    at require (internal/modules/cjs/helpers.js:16)
    at Object.<anonymous> (C:\Users\User\AppData\Local\Programs\Labmate\resources\app.asar\node_modules\opencv4nodejs\lib\cv.js:58)
    at Object.<anonymous> (C:\Users\User\AppData\Local\Programs\Labmate\resources\app.asar\node_modules\opencv4nodejs\lib\cv.js:69)
    at Module._compile (internal/modules/cjs/loader.js:786)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798)
    at Module.load (internal/modules/cjs/loader.js:645)
    at Function.Module._load (internal/modules/cjs/loader.js:560)
    at Module.require (internal/modules/cjs/loader.js:685)
```
https://github.com/justadudewhohacks/opencv4nodejs/issues/707

but the 
```
"asarUnpack": ["**/*.node"]
```
doesn't help.

**Comment by CircleOnCircles** [comment]
tried https://github.com/justadudewhohacks/opencv4nodejs/issues/493


by adding

```
"win": {
      "target": [
        "nsis",
        "msi"
      ],
      "extraResources": [
        {
          "from": "app/dist/redistributable/",
          "to": "../",
          "filter": "*"
        }
      ],
      "files": [
        "!node_modules/opencv-build/opencv/opencv/",
        "!node_modules/opencv-build/opencv/opencv_contrib/",
        "!node_modules/opencv-build/opencv/build/3rdparty/",
        "!node_modules/opencv-build/opencv/build/CMakeFiles/",
        "!node_modules/opencv-build/opencv/build/data/",
        "!node_modules/opencv-build/opencv/build/doc/",
        "!node_modules/opencv-build/opencv/build/downloads/",
        "!node_modules/opencv-build/opencv/build/etc/",
        "!node_modules/opencv-build/opencv/build/include/",
        "!node_modules/opencv-build/opencv/build/junk/",
        "!node_modules/opencv-build/opencv/build/lib/",
        "!node_modules/opencv-build/opencv/build/modules/",
        "!node_modules/opencv-build/opencv/build/opencv2/",
        "!node_modules/opencv-build/opencv/build/testdata/",
        "!node_modules/opencv-build/opencv/build/win-install/",
        "!node_modules/opencv-build/opencv/build/x64/",
        "!node_modules/opencv-build/opencv/build/bin/Debug/"
      ]
    },
```

without turn off `asar`

**Comment by CircleOnCircles** [comment]
After observe the `.node` file, I wondered why there is no .node for `opencv4node` in the dist folder
![image](https://user-images.githubusercontent.com/8089231/78969574-7254de80-7b31-11ea-8eea-9e6f355b7048.png)

**Comment by CircleOnCircles** [comment]
> After observe the `.node` file, I wondered why there is no .node for `opencv4node` in the dist folder
> ![image](https://user-images.githubusercontent.com/8089231/78969574-7254de80-7b31-11ea-8eea-9e6f355b7048.png)

after added an `opencv4nodejs.node`, i still not work

**Comment by CircleOnCircles** [comment]
There is a file named `ea8c35a5-7f2c-445f-b22c-1ff45cfa290d.tmp.node` in the `C:\Users\ben\AppData\Local\Temp`

It seems some libs give the path wrong. ref error msg `\\?\C:\Users\User\AppData\Local\Temp\b3ccaeda-cfb0-43e5-868c-cab1254fdf7d.tmp.node` instead of `C:\Users\User\AppData\Local\Temp\b3ccaeda-cfb0-43e5-868c-cab1254fdf7d.tmp.node`

**Comment by CircleOnCircles** [comment]
> Your app is trying to run a `.node` file from the `%temp%` directory. The reason behind this issue is that Windows cannot run `node|dll|exeutable` files from the `asar` package => so it copies them to `%temp%` and tries to execute them there.
> 
> To fix this, add this to your `electron-builder` configuration
> 
> ```json
> "asarUnpack": ["**/*.node"]
> ```

I did it wrong bt appending that it outside the `build`

Still, I got a new error message.
```
Uncaught (in promise) Error: The specified module could not be found.
\\?\C:\Users\ben\AppData\Local\Programs\Labmate\resources\app.asar.unpacked\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\ben\AppData\Local\Programs\Labmate\resources\app.asar\node_modules\opencv4nodejs\lib\cv.js:58:8)
    at Object.<anonymous> (C:\Users\ben\AppData\Local\Programs\Labmate\resources\app.asar\node_modules\opencv4nodejs\lib\cv.js:69:3)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
```

**Comment by ajmetal** [comment]
I eventually discovered this issue is caused by a custom native node module I had created. If a native module fails to load for a myriad of reasons it will present with: `Error: The specified module could not be found.` 

In my case there was a missing dependency the native node module required.

**Comment by Alfredoatem** [comment]
> Finalmente descubrí que este problema es causado por un módulo de nodo nativo personalizado que había creado. Si un módulo nativo no se carga por una miríada de razones, se presentará con:`Error: The specified module could not be found.`
> 
> En mi caso, faltaba una dependencia que requería el módulo de nodo nativo.

como lo solucionaste amigo? soy nuevo en esto

**Comment by CircleOnCircles** [comment]
I did solve this my not using the native lib.

**Comment by haha861924** [comment]
I have the same error 
`A JavaScript error occurred in the main process Uncaught Exception: Error: Cannot find module '/media/sf_linux-desktop/vue-electron-linux-x64/resources/app/background.js' at Module._resolveFilename (internal/modules/cjs/loader.js:972:15) at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921) at Object. (electron/js2c/browser_init.js:185:3470) at Object../lib/browser/init.ts (electron/js2c/browser_init.js:185:3714) at webpack_require (electron/js2c/browser_init.js:1:128) at electron/js2c/browser_init.js:1:1200 at electron/js2c/browser_init.js:1:1267 at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:277:7) at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:10) at loadNativeModule (internal/modules/cjs/helpers.js:24:9)`

**Comment by clementlize** [comment]
Same error here. Except that I don't use the missing module anywhere. And when I add it to my dependencies, same result.
Same error on Ubuntu and Windows10.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@babel/runtime/helpers/asyncToGenerator'
Require stack:
- /usr/lib/myapp/resources/app/.webpack/main/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /usr/lib/rekordtools/resources/app/.webpack/main/index.js:1:710
    at /usr/lib/rekordtools/resources/app/.webpack/main/index.js:1:3484
    at Object.<anonymous> (/usr/lib/rekordtools/resources/app/.webpack/main/index.js:1:3505)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

![image](https://user-images.githubusercontent.com/48858570/150598949-9343262d-80cb-43c1-aabe-1dc86a981c20.png)

**Comment by ScaredTheDEV** [comment]
Any fixes?

**Comment by clementlize** [comment]
> Any fixes?

I fixed it yes, it was a configuration mistake. When I tried to build for windows I had an error coming from missing modules. When googling the error I found a solution which was to put `externals: [nodeExternals()],` into my webpack configuration, which I did.

So this just told webpack to ignore the modules and to bundle the app without them. And that's why I had this missing module error.

At the end, I removed this line and went digging into the original problem, which I finally solved after a few days.
I don't know if this can help you, good luck anyway.

**Comment by grctest** [comment]
Thanks for the tip, sorted my problem out @clementlize 👍

**Comment by LordFugi** [comment]
I have no idea what the problem is I keep saying that it has to do with win 11 again and again, why not that didn't exist before either
-------------------------------------------------------------------------------------------------------------------------------------------
A JavaScript error occurred in the main process

Uncaught Exception:

Error: The specified module was not found.

\\?\E:\steam\steamapps\common\War And Peace\resources\app.asar.unpacked\node_modules\ste...\steamworksjs.win32-x64-msvc.node

at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812) at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)

at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039) at Module.load (internal/modules/cjs/loader.js:992:32) at Module._load (internal/modules/cjs/loader.js:885:14) at Function.f._load (electron/js2c/asar_bundle.js:5:12633) at Module.require (internal/modules/cjs/loader.js:1032:19) at require (internal/modules/cjs/helpers.js:72:18)

at Object.<anonymous> (E:\steam\steamapps\common\War And Peace\resources\app.asar\node_modules\steamworks.js\index.js:8:21) at Module._compile (internal/modules/cjs/loader.js:1152:30)

**Comment by beshoymikhail** [comment]
I have the same issue when generate exe for windows from electron.net project i tried many things but nothing work ?

**Comment by aadilmallick** [comment]
this is probably the worst error I've ever seen in my life. It's not even a logic problem - it's just a random arcane build issue with no direction on how to fix it.

**Comment by beshoymikhail** [comment]
add {
        "from": "./node_modules/@socket.io/component-emitter",
        "to": "node_modules/@socket.io/component-emitter",
        "filter": [ "**/*" ]
      }
to electron.manifest.json
