### ISSUE TITLE
Cannot download differentially, fallback to full download: Error

### ISSUE THREAD

**Issue by wslp12** [electron-userland/electron-builder#4776]
* **Version**: 22.4.0

updater:r4.2.2

* **Target**:  nsis

> [2020-03-13 15:14:39.845] [info] App starting...
[2020-03-13 15:14:46.049] [info] Checking for update
[2020-03-13 15:14:47.320] [info] Found version 0.1.4 (url: /download/flavor/default/0.1.4/windows_32/wetv_view_type_0.1.4.exe)
[2020-03-13 15:14:47.326] [info] Downloading update from /download/flavor/default/0.1.4/windows_32/wetv_view_type_0.1.4.exe
[2020-03-13 15:14:47.336] [info] No cached update info available
[2020-03-13 15:14:47.342] [info] Download block maps (old: "http://localhost/download/flavor/default/0.1.3/windows_32/wetv_view_type_0.1.3.exe.blockmap", new: http://localhost/download/flavor/default/0.1.4/windows_32/wetv_view_type_0.1.4.exe.blockmap)
[2020-03-13 15:14:47.589] [info] blockAwareFileInfo: [object Object]
[2020-03-13 15:14:47.614] [info] File has 76 changed blocks
[2020-03-13 15:14:47.648] [info] Full: 107,573.16 KB, To download: 1,641.9 KB (2%)
[2020-03-13 15:14:48.599] [info] Differential download: http://localhost/download/flavor/default/0.1.4/windows_32/wetv_view_type_0.1.4.exe
[2020-03-13 15:21:47.569] [error] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected beac2c54154a47c1c5ad8da745a86a3912464a3f24a2be83a23fdd3fae2648b4, got mBoGT51ekdWQYqK75l2ZWoTADM2PKk6Pckhk7z88tgbGhTnh1rjuR+IxIKF1rkFe/roW9Q9MzuVpIX4hvWkiwA==
    at newError (C:\Users\yunji\AppData\Local\Programs\wetv-view-type\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\index.js:212:17)
    at DigestTransform.validate (C:\Users\yunji\AppData\Local\Programs\wetv-view-type\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:407:35)
    at WriteStream.<anonymous> (C:\Users\yunji\AppData\Local\Programs\wetv-view-type\resources\app.asar\node_modules\electron-updater\out\differentialDownloader\DifferentialDownloader.js:188:29)
    at WriteStream.emit (events.js:210:5)
    at internal/fs/streams.js:218:14
    at C:\Users\yunji\AppData\Local\Programs\wetv-view-type\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:146:23)

this error only appears "defferentially download"

**Comment by ouyang-yuxuan** [comment]
I had the same problem

**Comment by frssistemas** [comment]
Estou com o mesmo problema de fallback, sendo que não uso repositório privado

**Comment by snow-sprite** [comment]
> I had the same problem

me too...

**Comment by RiggedToBlow** [comment]
what config do use to make the update differential mine is always downloading full updates 😅

**Comment by caezarz** [comment]
This error seems to be only appear when you are in "electron ." mode, running the actual application(the installed app) works just fine.

**Comment by jjhbw** [comment]
AFAIU this is related to #4676
