### ISSUE TITLE
Github publisher error

### ISSUE THREAD

**Issue by ifzm** [electron-userland/electron-builder#4781]
* **Version**: 21.2.0
* **Target**: win64

I got an exception while using the auto update feature, hoping for help ...

---

Building app with electron-builder:
  • electron-builder  version=21.2.0 os=10.0.18363
  • description is missed in the package.json  appPackageFile=E:\Personal\Workspace\VSCode\electron-vue\dist_electron\bundled\package.json
  • author is missed in the package.json  appPackageFile=E:\Personal\Workspace\VSCode\electron-vue\dist_electron\bundled\package.json     
  • writing effective config  file=dist_electron\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=6.1.9 appOutDir=dist_electron\win-unpacked
  • building        target=nsis file=dist_electron\electron-vue_Setup_0.1.0.exe archs=x64 oneClick=true perMachine=false
  • building block map  blockMapFile=dist_electron\electron-vue_Setup_0.1.0.exe.blockmap
  • publishing      publisher=Github (owner: ifzm, project: electron-vue-example, version: 0.1.0)
  • uploading       file=electron-vue_Setup_0.1.0.exe.blockmap provider=GitHub
  • uploading       file=electron-vue_Setup_0.1.0.exe provider=GitHub
 ERROR  Error: Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)

Error #2 --------------------------------------------------------------------------------
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
Error: Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)

Error #2 --------------------------------------------------------------------------------
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
    at throwError (E:\Personal\Workspace\VSCode\electron-vue\node_modules\builder-util\src\asyncTaskManager.ts:90:11)
    at checkErrors (E:\Personal\Workspace\VSCode\electron-vue\node_modules\builder-util\src\asyncTaskManager.ts:53:9)
    at AsyncTaskManager.awaitTasks (E:\Personal\Workspace\VSCode\electron-vue\node_modules\builder-util\src\asyncTaskManager.ts:67:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at PublishManager.awaitTasks (E:\Personal\Workspace\VSCode\electron-vue\node_modules\app-builder-lib\src\publish\PublishManager.ts:210:5)
    at executeFinally (E:\Personal\Workspace\VSCode\electron-vue\node_modules\builder-util\src\promise.ts:25:3)
error Command failed with exit code 1.

**Comment by ifzm** [comment]
Seems to be a network problem
