### ISSUE TITLE
Problem packaging native module (opencv4nodejs) into electron apps

### ISSUE THREAD

**Issue by champ8644** [electron-userland/electron-builder#4782]
electron-builder 20.28.4

* **Version**: 

4.0.6

* **Target**: 
"nsis" for x86 windows

Hi, I'm currently doing an electron react webpack project that use `opencv4nodejs` (native node module). In the dev environment, everything is doing good as I rebuild `opencv4nodejs` by `electron-rebuilder`. But after I finished everything and tried to package it up to executable apps - there was an errror:
```
TypeError: Cannot read property 'default' of undefined
{"componentStack":"\n    in UnconnectedReactImportedComponent (created by Context.Consumer)\n    in ReactImportedComponent (created by Imported)\n    in Imported (created by Context.Consumer)\n    in Route (created by j)\n    in Switch\n    in j\n    in div\n    in div\n    in X (created by ForwardRef)\n    in ForwardRef (created by UnconnectedReactImportedComponent)\n    in UnconnectedReactImportedComponent (created by Context.Consumer)\n    in ReactImportedComponent (created by Imported)\n    in Imported (created by Context.Consumer)\n    in Route\n    in Switch\n    in Router (created by HashRouter)\n    in HashRouter\n    in Unknown\n    in Pe (created by ForwardRef)\n    in ForwardRef (created by Connect(Component))\n    in Connect(Component)\n    in v\n    in h\n    in div\n    in Ut (created by ForwardRef)\n    in ForwardRef (created by Connect(Component))\n    in Connect(Component) (created by n)\n    in n\n    in Router (created by ConnectedRouter)\n    in ConnectedRouter\n    in Provider\n    in Ft\n    in AppContainer"}Error Stack:
"TypeError: Cannot read property 'default' of undefined\n    at Object.es6import [as exportPicker] (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-imported-component\\dist\\Component.js:230:17)\n    at UnconnectedReactImportedComponent.pickPrecached (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-imported-component\\dist\\Component.js:133:38)\n    at new UnconnectedReactImportedComponent (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-imported-component\\dist\\Component.js:101:25)\n    at constructClassInstance (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:12902:18)\n    at updateClassComponent (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:17124:5)\n    at beginWork (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:18653:16)\n    at HTMLUnknownElement.callCallback (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:188:14)\n    at Object.invokeGuardedCallbackDev (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:237:16)\n    at invokeGuardedCallback (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:292:31)\n    at beginWork$1 (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:23234:7)\n    at performUnitOfWork (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:22188:12)\n    at workLoopSync (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:22161:22)\n    at performSyncWorkOnRoot (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:21787:9)\n    at C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:11111:24\n    at unstable_runWithPriority (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\scheduler\\cjs\\scheduler.development.js:653:12)\n    at runWithPriority$1 (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:11061:10)"

Error boundary log capture:
TypeError: Cannot read property 'default' of undefined
{"componentStack":"\n    in UnconnectedReactImportedComponent (created by Context.Consumer)\n    in ReactImportedComponent (created by Imported)\n    in Imported (created by Context.Consumer)\n    in Route (created by j)\n    in Switch\n    in j\n    in div\n    in div\n    in X (created by ForwardRef)\n    in ForwardRef (created by UnconnectedReactImportedComponent)\n    in UnconnectedReactImportedComponent (created by Context.Consumer)\n    in ReactImportedComponent (created by Imported)\n    in Imported (created by Context.Consumer)\n    in Route\n    in Switch\n    in Router (created by HashRouter)\n    in HashRouter\n    in Unknown\n    in Pe (created by ForwardRef)\n    in ForwardRef (created by Connect(Component))\n    in Connect(Component)\n    in v\n    in h\n    in div\n    in Ut (created by ForwardRef)\n    in ForwardRef (created by Connect(Component))\n    in Connect(Component) (created by n)\n    in n\n    in Router (created by ConnectedRouter)\n    in ConnectedRouter\n    in Provider\n    in Ft\n    in AppContainer"}Error Stack:
"TypeError: Cannot read property 'default' of undefined\n    at Object.es6import [as exportPicker] (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-imported-component\\dist\\Component.js:230:17)\n    at UnconnectedReactImportedComponent.pickPrecached (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-imported-component\\dist\\Component.js:133:38)\n    at new UnconnectedReactImportedComponent (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-imported-component\\dist\\Component.js:101:25)\n    at constructClassInstance (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:12902:18)\n    at updateClassComponent (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:17124:5)\n    at beginWork (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:18653:16)\n    at HTMLUnknownElement.callCallback (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:188:14)\n    at Object.invokeGuardedCallbackDev (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:237:16)\n    at invokeGuardedCallback (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:292:31)\n    at beginWork$1 (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:23234:7)\n    at performUnitOfWork (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:22188:12)\n    at workLoopSync (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:22161:22)\n    at performSyncWorkOnRoot (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:21787:9)\n    at C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:11111:24\n    at unstable_runWithPriority (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\scheduler\\cjs\\scheduler.development.js:653:12)\n    at runWithPriority$1 (C:\\Users\\Champ\\AppData\\Local\\Programs\\myApp\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:11061:10)"
```
this is some part of my package.json
```
{
  "scripts": {
    "build": "yarn lint && concurrently \"yarn build-main\" \"yarn build-renderer\"",
    "build-dll": "cross-env NODE_ENV=development node --trace-warnings -r @babel/register ./node_modules/webpack/bin/webpack --config ./webpack/config.renderer.dev.dll.babel.js --colors",
    "build-main": "cross-env NODE_ENV=production node --trace-warnings -r @babel/register ./node_modules/webpack/bin/webpack --config ./webpack/config.main.prod.babel.js --colors",
    "build-renderer": "cross-env NODE_ENV=production node --trace-warnings -r @babel/register ./node_modules/webpack/bin/webpack --config ./webpack/config.renderer.prod.babel.js --colors  --display-chunks --display-modules",
    "dev": "cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev",
    "package": "yarn build && electron-builder build --publish never",
    "package-all": "yarn build && build -mwl --publish never",
    "package-mac": "yarn build && build --mac --publish never",
    "package-linux": "yarn build && build --linux --publish never",
    "package-win": "yarn build && build --win --x64 --publish never",
    "publish": "yarn build && electron-builder build --publish always",
    "prestart": "yarn build",
    "start": "cross-env NODE_ENV=production run-electron ./app/main.prod.js",
    "start-main-dev": "cross-env HOT=1 NODE_ENV=development run-electron -r @babel/register ./app/main.dev.js",
    "start-renderer-dev": "cross-env NODE_ENV=development webpack-dev-server --config webpack/config.renderer.dev.babel.js",
    "publish-mac": "yarn build && build --mac --publish always",
    "publish-linux": "yarn build && build --linux --publish always",
    "publish-win": "yarn build && build --win --x64 --publish always",
    "lint": "cross-env NODE_ENV=development eslint --cache --format=pretty --ext .js --ext .jsx .",
    "lint-styles": "stylelint --ignore-path .eslintignore '**/*.*(css|scss)' --syntax scss",
    "lint-fix": "yarn --silent lint --fix; exit 0",
    "lint-styles-fix": "yarn --silent lint-styles --fix; exit 0",
    "postlint-fix": "prettier --ignore-path .eslintignore --single-quote --write '**/*.*{js,jsx,json}'",
    "postlint-styles-fix": "prettier --ignore-path .eslintignore --single-quote --write '**/*.{css,scss}'",
    "precommit": "lint-staged",
    "preinstall": "node ./internals/scripts/CheckYarn.js",
    "postinstall": "yarn build-dll && electron-builder install-app-deps",
    "electron-rebuild": "electron-rebuild -w opencv4nodejs"
  },
  "opencv4nodejs": {
    "disableAutoBuild": 1,
    "opencvIncludeDir": "C:\\tools\\opencv\\build\\include",
    "opencvLibDir": "C:\\tools\\opencv\\build\\x64\\vc15\\lib",
    "opencvBinDir": "C:\\tools\\opencv\\build\\x64\\vc15\\bin"
  },
  "main": "./app/main.prod.js",
  "build": {
    "forceCodeSigning": false,
    "readonly": true,
    "files": [
      "app/dist/",
      "app/app.html",
      "app/worker.html",
      "app/main.prod.js",
      "app/main.prod.js.map",
      "package.json"
    ],
    "extraFiles": [
      {
        "from": "build/mac/bin",
        "to": "Resources/bin",
        "filter": [
          "**/*"
        ]
      }
    ],
    "win": {
      "target": [
        "nsis"
      ],
      "extraResources": [
        {
          "from": "app/dist/redistributable/",
          "to": "../",
          "filter": "*"
        }
      ]
    },
  },
  "devDependencies": {
    "electron": "4.0.1",
    "electron-builder": "^22.4.1",
    "electron-rebuild": "^1.8.8",
  },
  "dependencies": {
    "node-loader": "^0.6.0",
    "opencv-build": "^0.1.9",
    "opencv4nodejs": "^5.5.0",
    "react": "^16.4.1",
    "redux": "^4.0.4",
  },
  "devEngines": {
    "node": ">=8.x",
    "npm": ">=4.x",
    "yarn": ">=0.21.3"
  }
}
```
I have extensively search for the answer but no clues. maybe this is some rookie question but please help!!

**Comment by aperkaz** [comment]
Hi @champ8644 any luck with this issue? I am attempting to do something similar myself :slightly_smiling_face:

**Comment by champ8644** [comment]
As I has recalled correctly - I was deleted all of node_modules folder and reinstall+rebuild opencv4nodejs again with adding `asar: false` in the electron-builder property thanks to #2738 .
Btw I have updated my depedencies too, this is my final `package.json`:
`
"scripts": {
    "build": "yarn lint && concurrently \"yarn build-main\" \"yarn build-renderer\"",
    "build-dll": "cross-env NODE_ENV=development node --trace-warnings -r @babel/register ./node_modules/webpack/bin/webpack --config ./webpack/config.renderer.dev.dll.babel.js --colors",
    "build-main": "cross-env NODE_ENV=production node --trace-warnings -r @babel/register ./node_modules/webpack/bin/webpack --config ./webpack/config.main.prod.babel.js --colors",
    "build-renderer": "cross-env NODE_ENV=production node --trace-warnings -r @babel/register ./node_modules/webpack/bin/webpack --config ./webpack/config.renderer.prod.babel.js --colors  --display-chunks --display-modules",
    "deploy": "yarn build && electron-builder build --publish always",
    "package": "yarn build && electron-builder build --publish never",
    "package-all": "yarn build && build -mwl --publish never",
    "package-mac": "yarn build && build --mac --publish never",
    "package-linux": "yarn build && build --linux --publish never",
    "package-win": "yarn build && build --win --x64 --publish never",
    "prestart": "yarn build",
    "start": "cross-env NODE_ENV=production run-electron ./app/main.prod.js",
    "start-main-dev": "cross-env HOT=1 NODE_ENV=development run-electron -r @babel/register ./app/main.dev.js",
    "start-renderer-dev": "cross-env NODE_ENV=development webpack-dev-server --mode development --hot --config webpack/config.renderer.dev.babel.js",
    "lint": "cross-env NODE_ENV=development eslint --cache --format=pretty --ext .js --ext .jsx .",
    "lint-styles": "stylelint --ignore-path .eslintignore '**/*.*(css|scss)' --syntax scss",
    "lint-fix": "yarn --silent lint --fix; exit 0",
    "lint-styles-fix": "yarn --silent lint-styles --fix; exit 0",
    "postlint-fix": "prettier --ignore-path .eslintignore --single-quote --write '**/*.*{js,jsx,json}'",
    "postlint-styles-fix": "prettier --ignore-path .eslintignore --single-quote --write '**/*.{css,scss}'",
    "precommit": "lint-staged",
    "preinstall": "node ./internals/scripts/CheckYarn.js",
    "postinstall": "yarn build-dll && electron-builder install-app-deps package.json",
    "electron-rebuild": "electron-rebuild -w opencv4nodejs",
    ...
  },
  "devDependencies": {
    "electron": "7.1.8",
    "electron-builder": "^22.2.0",
    "electron-rebuild": "^1.8.8",
    ...
  },
  "dependencies": {
    "node-loader": "^0.6.0",
    "opencv4nodejs": "^5.5.0",
    "react": "^16.4.1",
    ...
  }
`
