### ISSUE TITLE
Error when building on MacOS

### ISSUE THREAD

**Issue by Splode** [electron-userland/electron-builder#4846]
* **Version**: 22.4.1

* **Electron Version**: 8.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: dmg

Fails to build on MacOS with the following output:

```bash
  • electron-builder  version=22.4.1 os=18.2.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=build/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=8.2.0 appOutDir=build/mac
SIGILL: illegal instruction
PC=0x1065880 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc00022ddf8 sp=0xc00022ddf0 pc=0x1065880
math/rand.seedrand(...)
	/usr/local/Cellar/go/1.14/libexec/src/math/rand/rng.go:198
math/rand.(*rngSource).Seed(0xc0001a3500, 0x16027a9e151b3d20)
	/usr/local/Cellar/go/1.14/libexec/src/math/rand/rng.go:218 +0xad fp=0xc00022de00 sp=0xc00022ddf8 pc=0x1126e6d
math/rand.NewSource(0x16027a9e151b3d20, 0x8b455b, 0x1faa6e0)
	/usr/local/Cellar/go/1.14/libexec/src/math/rand/rand.go:46 +0x4a fp=0xc00022de28 sp=0xc00022de00 pc=0x1125aca
github.com/aws/aws-sdk-go/internal/sdkrand.init()
	/Volumes/data/go/pkg/mod/github.com/aws/aws-sdk-go@v1.29.15/internal/sdkrand/locked_source.go:29 +0x39 fp=0xc00022de68 sp=0xc00022de28 pc=0x15cd359
runtime.doInit(0x1f5ece0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc00022de98 sp=0xc00022de68 pc=0x104330a
runtime.doInit(0x1f62a00)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00022dec8 sp=0xc00022de98 pc=0x10432d7
runtime.doInit(0x1f63000)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00022def8 sp=0xc00022dec8 pc=0x10432d7
runtime.doInit(0x1f664e0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00022df28 sp=0xc00022def8 pc=0x10432d7
runtime.doInit(0x1f64440)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00022df58 sp=0xc00022df28 pc=0x10432d7
runtime.doInit(0x1f66f80)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00022df88 sp=0xc00022df58 pc=0x10432d7
runtime.main()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc00022dfe0 sp=0xc00022df88 pc=0x103686e
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00022dfe8 sp=0xc00022dfe0 pc=0x1064011

rax    0x225
rbx    0x8c9994ea
rcx    0xc0001a3500
rdx    0xc9994eb
rdi    0x952a1c529cf7b4be
rsi    0x12b6
rbp    0xc00022de18
rsp    0xc00022ddf0
r8     0x60b5293800000
r9     0x1
r10    0xc0001a3500
r11    0x1
r12    0xffffffffffffffff
r13    0x2
r14    0x1
r15    0x3
rip    0x1065880
rflags 0x10216
cs     0x2b
fs     0x0
gs     0x0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pomotroid@0.7.1 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pomotroid@0.7.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christopher/.npm/_logs/2020-04-04T01_47_18_203Z-debug.log
Christophers-iMac:pomotroid christopher$ cat /Users/christopher/.npm/_logs/2020-04-04T01_47_18_203Z-debug.log
```

Contents of npm debug log:

```log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node@12/12.14.0/bin/node',
1 verbose cli   '/usr/local/opt/node@12/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle pomotroid@0.7.1~prebuild: pomotroid@0.7.1
6 info lifecycle pomotroid@0.7.1~build: pomotroid@0.7.1
7 verbose lifecycle pomotroid@0.7.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle pomotroid@0.7.1~build: PATH: /usr/local/Cellar/node@12/12.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/christopher/code/pomotroid/node_modules/.bin:/usr/local/opt/node@12/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle pomotroid@0.7.1~build: CWD: /Users/christopher/code/pomotroid
10 silly lifecycle pomotroid@0.7.1~build: Args: [ '-c', 'node .electron-vue/build.js && electron-builder' ]
11 silly lifecycle pomotroid@0.7.1~build: Returned: code: 1  signal: null
12 info lifecycle pomotroid@0.7.1~build: Failed to exec build script
13 verbose stack Error: pomotroid@0.7.1 build: `node .electron-vue/build.js && electron-builder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node@12/12.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@12/12.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid pomotroid@0.7.1
15 verbose cwd /Users/christopher/code/pomotroid
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/Cellar/node@12/12.14.0/bin/node" "/usr/local/opt/node@12/bin/npm" "run" "build"
18 verbose node v12.14.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error pomotroid@0.7.1 build: `node .electron-vue/build.js && electron-builder`
22 error Exit status 1
23 error Failed at the pomotroid@0.7.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I'm a bit lost here. Does `electron-builder` use Go?

**Comment by shrinidhi111** [comment]
I struggled with the same issue for a while.. (macOS 10.14.5) Apparently it uses to manage the modules and this go version has a known issue with mac.

So I basically fixed it by deleting node_modules, and downgraded electron to 7 and electron-builder to 21. That fixed the problem.

Interestingly, this is not an issue in macInCloud server running 10.15.3 (19D76).

**Comment by Splode** [comment]
Thanks for all the info. I think in my case, the best solution is to upgrade my version of macOS.

**Comment by guy032** [comment]
Occurred to me also with Electron 7.1.13 and electron-builder 22.3.6.
Node.js version: 12.16.3
MAC version: 10.15.3

**Comment by phloose** [comment]
Though closed i think this issue is related to the go version used (1.14): https://github.com/golang/go/issues/37459
