### ISSUE TITLE
Maximum download limit 50mb in public repo

### ISSUE THREAD

**Issue by aman-pandia** [electron-userland/electron-builder#4872]
* **Version**:  22.4.1

* **Electron Version**: 8.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Windows NSIS

I am having the maximum download size error. It cannot download files over 50mb. On checking other similar issues i found that private repo have this issue but my repo is public.
I have attached the terminal output below.

My github repo link : https://github.com/aman-pandia/Medico

Terminal output : 
```bash
Found version 1.0.2 (url: medico-Setup-1.0.2.exe)
Downloading update from medico-Setup-1.0.2.exe
updater cache dir: C:\Users\hp\AppData\Local\medico-updater
No cached update info available
Download block maps (old: "https://api.github.com/repos/aman-pandia/Medico/releases/assets/19672069.blockmap", new: https://api.github.com/repos/aman-pandia/Medico/releases/assets/19672069.blockmap)
Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Users\hp\Desktop\New folder (2)\Medico\node_modules\builder-util-runtime\out\httpExecutor.js:240:26)
    at ClientRequest.<anonymous> (C:\Users\hp\Desktop\New folder (2)\Medico\node_modules\builder-util-runtime\out\httpExecutor.js:302:17)
    at ClientRequest.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2510:12)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
```

**Comment by razvanstatescu** [comment]
I got this issue too on electron 8.2.2 with electron-builder 22.5.1 and electron-updater 4.3.1. My repo is also public

**Comment by ethanbonin** [comment]
Does anybody have any pointers on how to fix this?

`"electron-updater": "^4.3.1",`
`"electron-builder": "^22.7.0",`

I'm also using the electron-boilerplate-react template

```
[2020-06-16 18:14:16.856] [error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Users\ethan\AppData\Local\Programs\A3\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:210:26)
    at ClientRequest.<anonymous> (C:\Users\ethan\AppData\Local\Programs\A3\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:274:17)
    at ClientRequest.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2536:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)```
