### ISSUE TITLE
Windows 10: node_modules\app-builder-bin\win\ia32\app-builder.exe ENOENT

### ISSUE THREAD

**Issue by chenc17** [electron-userland/electron-builder#4901]
* **Version**: 22.4.1
* **Electron Version**: 8.2.2
* **Target**: Windows 10

I'm running `electron-builder build --win --x64 -c.extraMetadata.main=electron/main.js --publish never` and encountering the following error:

```
 • electron-builder  version=22.5.1 os=10.0.17763
  • loaded configuration  file=package.json ("build" field)
  • public/electron.js not found. Please see https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3
  • loaded parent configuration  preset=react-cra
  • description is missed in the package.json  appPackageFile=C:\Users\user_name\Desktop\repos\repo_name\package.json
  • author is missed in the package.json  appPackageFile=C:\Users\user_name\Desktop\repos\repo_name\package.json
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script "postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=dist\builder-effective-config.yaml
  ⨯ spawn C:\Users\user_name\Desktop\repos\repo_name\node_modules\app-builder-bin\win\ia32\app-builder.exe ENOENT  stackTrace=
Error: spawn C:\Users\user_name\Desktop\repos\repo_name\node_modules\app-builder-bin\win\ia32\app-builder.exe ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
at onErrorNT (internal/child_process.js:469:16)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Anyone have any ideas on what's going on? I find it really strange that electron-builder is trying to access app-builder-bin\win\ia32 when I'm building from an x64 device and also specifically targeting a Windows 10 x64 device. I've already tried deleting node_modules and package-lock.json and re-running `npm install`. 

Any thoughts/ideas would be much appreciated! Thank you!

**Comment by Niquolas** [comment]
Check your antivirus isn't blocking it, there is an issue where it's being  [falsely detected](https://github.com/electron-userland/electron-builder/issues/4886#issuecomment-616085789)

**Comment by chenc17** [comment]
Thanks, that's exactly what's going on.
