### ISSUE TITLE
No update-info.json file in update cache folder 😶

### ISSUE THREAD

**Issue by b-zurg** [electron-userland/electron-builder#4928]
* **electron-builder**: "22.5.1"
* **Electron Version**: 8.2.2
* **Electron Type**: current
* **electron-updater**: "4.2.5"
* **Target**: windows

I'm seeing this error after uploading a new version to an S3 bucket.

The upload went fine and all of the artifacts are there as far as I can tell.

Here is the log of the local application (output to AppData log.log from `electron-log` logger)

```log
[2020-05-05 22:41:04.824] [info] Checking for update
[2020-05-05 22:41:05.017] [info] Generated new staging user ID: 586a9abf-80b7-5cb4-a8db-9af47cc1d5a7
[2020-05-05 22:41:06.100] [info] Found version 0.0.2-beta (url: MyApp Setup 0.0.2-beta.exe)
[2020-05-05 22:41:06.252] [info] Downloading update from MyApp Setup 0.0.2-beta.exe
[2020-05-05 22:41:06.273] [debug] updater cache dir: C:\Users\zurg\AppData\Local\app.com.org-updater
[2020-05-05 22:41:07.510] [error] Error: TypeError: Cannot read property 'fileName' of undefined
    at t.DownloadedUpdateHelper.cachedUpdateFile [as getValidCachedUpdateFile] (C:\Users\zurg\AppData\Local\Programs\app.com.org\resources\app.asar\.webpack\main\webpack:\node_modules\electron-updater\out\DownloadedUpdateHelper.js:149:20)
    at t.DownloadedUpdateHelper.cachedUpdateFile [as validateDownloadedPath] (C:\Users\zurg\AppData\Local\Programs\app.com.org\resources\app.asar\.webpack\main\webpack:\node_modules\electron-updater\out\DownloadedUpdateHelper.js:88:11)
    at b.executeDownload (C:\Users\zurg\AppData\Local\Programs\app.com.org\resources\app.asar\.webpack\main\webpack:\node_modules\electron-updater\out\AppUpdater.js:726:11)
[2020-05-05 22:41:07.522] [info] Updating **with** synchronization
[2020-05-05 22:41:07.832] [error] TYPE should be object
```

After looking at the source code the only place the `fileName` property is accessed is here:
```ts
    if (cachedInfo.fileName == null) {
      logger.warn(`Cached update info is corrupted: no fileName, directory for cached update will be cleaned`)
      await this.cleanCacheDirForPendingUpdate()
      return null
    }
```

I think this actually means that for some reason the `update-info.json` file that the cachedInfo object is supposed to draw from does not exist.  Indeed I checked my directory and there is nothing.

## Are there more logging steps that can be done?

**Comment by b-zurg** [comment]
It seems that this file is supposed to be created normally in the update download process. I am unsure why it was not created in my case but I have a fix in the linked PR which will ensure that the update cache folder is cleared and recreated if the file does not exist. 

I tested this locally and this fix does work and the cache folder created correctly.  

Could anyone review my PR ?

**Comment by spcBackToLife** [comment]
i meet the same problem with no update-info.json file . and the error is same: 
![image](https://user-images.githubusercontent.com/20703494/86569949-c55bf780-bfa1-11ea-8ff3-b612cd8c9bf9.png)

electron: 8.3.2
electron-builder: 22.7.0

**Comment by spcBackToLife** [comment]
> It seems that this file is supposed to be created normally in the update download process. I am unsure why it was not created in my case but I have a fix in the linked PR which will ensure that the update cache folder is cleared and recreated if the file does not exist.
> 
> I tested this locally and this fix does work and the cache folder created correctly.
> 
> ### Update
> The root cause of this is fs-extra's `readJson` is not throwing as expected but rather succeeding and returning `undefined`. I think this could be because of a recent version or patch of node. Anyhow it seems unreliable to depend on an exception for an important code execution path. This clearing of the updater cache needs to happen on every initial installation's check for an update and is kind of critical.
> 
> This is the code in question
> https://github.com/electron-userland/electron-builder/blob/2e49f0bb1bd8448e1c2ccc4e2eb9def77b1a04df/packages/electron-updater/src/DownloadedUpdateHelper.ts#L93-L114
> 
> The optional chaining and nullish coalescing changes I added before should fix things but I'm going to add an early return as well for clarity.

the problem is same:

**Comment by b-zurg** [comment]
Yeah my fix was incomplete.  My project was actually having issues with fs-extra in other dependencies as well, and I think the suspect is my webpack configuration.  I'm not really sure what was happening.  I might give electron-builder another go soon and see if that was it, because according to the spec provided by fs-extra I think the code in electron-builder should be working.
