### ISSUE TITLE
erro while packaging for linux

### ISSUE THREAD

**Issue by saw-jan** [electron-userland/electron-builder#4938]
electron-builder: 22.6.0;
electron: 8.0.0
target-build: Linux (deb)

while running "electron-builder --linux" gives:

```
building        target=deb arch=x64 file=dist/the_bible_setup_v1.0.0.deb
  ⨯ unknown output format set
github.com/develar/app-builder/pkg/icons.convertSingleFile
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:305
github.com/develar/app-builder/pkg/icons.doConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:247
github.com/develar/app-builder/pkg/icons.ConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:90
runtime.main
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373  
  ⨯ /home/kinsae/CODE/thebible/app/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  
stackTrace=
Error: /home/kinsae/CODE/thebible/app/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE 
at ChildProcess.<anonymous> (/home/kinsae/CODE/thebible/app/node_modules/builder-util/src/util.ts:243:14) 
at ject.onceWrapper (events.js:417:26) at ChildProcess.emit (events.js:310:20) 
at maybeClose(internal/child_process.js:1021:16) 
at Process.ChildProcess._handle.onexit(internal/child_process.js:286:5)
```

**Comment by saw-jan** [comment]
Hopefully i found the solution here: 
#3591

The problem was with _icon.ico_ format, using _icon.png_ is the solution for linux.
Here is the solution in short:
```
build: {
	…
    "linux": {
      "icon": "build/256x256.png",
      "target": [
        "deb"
      ]
    },
}
```

**Comment by bksubhuti** [comment]
that did not work for me.. I created 256x256 png but still get the error.

**Comment by mikemanders** [comment]
@bksubhuti Make sure you include the icon in your assets (in angular.json) so it also ends up in your dist directory.

![image](https://user-images.githubusercontent.com/36154936/152973105-745db1ef-827b-42a2-bb26-ed227abba021.png)
