### ISSUE TITLE
Electron Updater fails with Unexpected Token on three dots

### ISSUE THREAD

**Issue by eladmeidar** [electron-userland/electron-builder#4949]
* **Version**: 
4.2.5
* **Electron Version**:
8.2.5
* **Electron Type (current, beta, nightly)**:
current
|* **electron-updater version**:
4.2.5
* **Target**: 
mac, win

After upgrading from electron 6.0.1 we started encountering the following error when trying to build:
```
SyntaxError: unknown: Unexpected token (2084:65)
    2082 |       }
    2083 |     } else {
  > 2084 |       result.headers = headers == null ? this.requestHeaders : { ...this.requestHeaders,
         |                                                                  ^
    2085 |         ...headers
    2086 |       };
    2087 |     }
      at Parser.pp$5.raise (/Users/lordmeidar/projects/electron/node_modules/babylon/lib/index.js:4454:13)
      at Parser.pp.unexpected (/Users/lordmeidar/projects/electron/node_modules/babylon/lib/index.js:1761:8)
      at Parser.pp$3.parseIdentifier (/Users/lordmeidar/projects/electron/node_modules/babylon/lib/index.js:4332:10)
      at Parser.pp$3.parsePropertyName (/Users/lordmeidar/projects/electron/node_modules/babylon/lib/index.js:4156:96)
```
We've tried adding `babel-plugin-transform-object-rest-spread` (6.2.6.0) but also nothing changed much.

**Comment by anatolzak** [comment]
I have the same problem. 

Does anyone know how to fix this error?
