### ISSUE TITLE
Changing ELECTRON_BUILDER_CACHE between builds causes error

### ISSUE THREAD

**Issue by adam-lynch** [electron-userland/electron-builder#4955]
* **Version**: 22.6.0

* **Electron Version**: 8.x
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows NSIS and MSI

In trying to workaround #1850: 
1. Before a build, I set `ELECTRON_BUILDER_CACHE` to a newly created directory with a randomly generated name.
2. After the build, delete the directory.

If I run two builds right after each other, I get the following error:

```shell
Error: Exit code: ENOENT. spawn MY_CACHE_DIRECTORY\winCodeSign\winCodeSign-2.6.0\windows-10\x64\signtool.exe ENOENT
    at MY_PROJECT_DIRECTORY\node_modules\builder-util\src\util.ts:129:16
    at exithandler (child_process.js:302:5)
    at ChildProcess.errorhandler (child_process.js:314:5)
    at ChildProcess.emit (events.js:203:13)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
From previous event:
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:131:23)
From previous event:
    at WinPackager.signApp (MY_PROJECT_DIRECTORY\node_modules\app-builder-lib\src\winPackager.ts:357:27)
    at WinPackager.doPack (MY_PROJECT_DIRECTORY\node_modules\app-builder-lib\src\platformPackager.ts:244:16)
    at WinPackager.pack (MY_PROJECT_DIRECTORY\node_modules\app-builder-lib\src\platformPackager.ts:115:5)
    at Packager.doBuild (MY_PROJECT_DIRECTORY\node_modules\app-builder-lib\src\packager.ts:444:9)
    at executeFinally (MY_PROJECT_DIRECTORY\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (MY_PROJECT_DIRECTORY\node_modules\app-builder-lib\src\packager.ts:373:31)
    at Packager.build (MY_PROJECT_DIRECTORY\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.build [as default] (MY_PROJECT_DIRECTORY\built\server\build.js:164:29)
    at Object.receiveAppData [as default] (MY_PROJECT_DIRECTORY\built\server\receiveAppData.js:30:27)
    at Worker.queue [as fn] (MY_PROJECT_DIRECTORY\built\server\index.js:136:36)
```

I think what's happening is that binDownload.ts' [promise cache](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/binDownload.ts#L3) is never broken/invalidated.

I imagine the fix would be to check if the environment variable has changed and reset the map before [it's used here](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/binDownload.ts#L39). I can make a pull-request.

**Comment by adam-lynch** [comment]
Thanks

**Comment by greenimpala** [comment]
Not sure its related but I had codesign failing issues when upgrading electron-builder + electron versions.

Deleted the cache inside AppData and working again :)
