### ISSUE TITLE
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by laszukdawid** [electron-userland/electron-builder#4968]
* **Version**: 22.3.6

* **Electron Version**: 7.1.13
* **Electron Type (current, beta, nightly)**: current

* **Target**: any (linux)

I'm not sure what's the problem and what is causing it, so I guess I'm asking more for a help. This is happening when triggered by an action [action-electron-builder](https://github.com/samuelmeuli/action-electron-builder). I've raised there a [similar question](https://github.com/samuelmeuli/action-electron-builder/issues/26) and was referred here.

[Pollytron](https://github.com/laszukdawid/pollytron) is an app based on [electron-react-boilerplate](https://electron-react-boilerplate.js.org/). I'm trying to add your action but I'm ending up with `ER_UNESCAPED_CHARACTERS`. It's not clear to me what is the url that's not escaped as I'm not setting any (explicitly). Would you mind helping me to debug the problem?

Here are logs from the actions build:
https://github.com/laszukdawid/pollytron/runs/660183766?check_suite_focus=true

The error stack trace comes up 3 times, just after `unloading` step:

```log
 Error #1 --------------------------------------------------------------------------------
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:116:13)
    at request (https.js:289:10)
    at NodeHttpExecutor.createRequest (/home/runner/work/pollytron/pollytron/node_modules/builder-util/src/nodeHttpExecutor.ts:9:12)
    at cancellationToken.createPromise (/home/runner/work/pollytron/pollytron/node_modules/builder-util-runtime/src/httpExecutor.ts:84:28)
    at Promise (/home/runner/work/pollytron/pollytron/node_modules/builder-util-runtime/src/CancellationToken.ts:84:7)
    at new Promise (<anonymous>)
    at CancellationToken.createPromise (/home/runner/work/pollytron/pollytron/node_modules/builder-util-runtime/src/CancellationToken.ts:62:12)
    at NodeHttpExecutor.doApiRequest (/home/runner/work/pollytron/pollytron/node_modules/builder-util-runtime/src/httpExecutor.ts:83:30)
    at NodeHttpExecutor.request (/home/runner/work/pollytron/pollytron/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at GitHubPublisher.githubRequest (/home/runner/work/pollytron/pollytron/node_modules/electron-publish/src/gitHubPublisher.ts:253:35)
    at GitHubPublisher.getOrCreateRelease (/home/runner/work/pollytron/pollytron/node_modules/electron-publish/src/gitHubPublisher.ts:91:33)
    at Lazy.GitHubPublisher._release (/home/runner/work/pollytron/pollytron/node_modules/electron-publish/src/gitHubPublisher.ts:30:102)
    at Lazy.get value [as value] (/home/runner/work/pollytron/pollytron/node_modules/lazy-val/src/main.ts:18:25)
    at GitHubPublisher.doUpload (/home/runner/work/pollytron/pollytron/node_modules/electron-publish/src/gitHubPublisher.ts:163:41)
    at GitHubPublisher.upload (/home/runner/work/pollytron/pollytron/node_modules/electron-publish/src/publisher.ts:86:16)
```

**Comment by laszukdawid** [comment]
The problem was that the `owner` had a space char inside. Didn't realise that the owner is the github owner.

**Comment by b-zurg** [comment]
This was helpful.  I had the same issue and it was resolved by removing all spaces and special characters in the `artifactName` in my builder config.  Funny enough that wasn't a problem for the s3 publisher, but it was for Github.  Perhaps there's some dependency downstream that needs to be updated...

regardless, it works now!

**Comment by Maus3rSR** [comment]
Encounter same issue! Your post saved me a lot of time! Thank you 😄
