### ISSUE TITLE
leveldown 

### ISSUE THREAD

**Issue by camhart** [electron-userland/electron-builder#5030]
* **Version**: 22.7.0
* **Electron Version**: 9.0.2
* **Electron Type (current, beta, nightly)**: current
* **Target**:  Windows 10, 64 bit

If I try to use a package that contains leveldown as a dependency (v5.6.0), I get the following runtime error:
```
Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=80 uv=1 libc=glibc
    at Function.load.path (webpack:///./node_modules/node-gyp-build/index.js?:56:9)
    at load (webpack:///./node_modules/node-gyp-build/index.js?:20:30)
    at eval (webpack:///./node_modules/leveldown/binding.js?:1:101)
    at Object../node_modules/leveldown/binding.js (C:\Users\Cam\projects\codename-desktop\myapp\dist_electron\index.js:16181:1)
    at __webpack_require__ (C:\Users\Cam\projects\codename-desktop\myapp\dist_electron\index.js:20:30)
    at eval (webpack:///./node_modules/leveldown/leveldown.js?:3:17)
    at Object../node_modules/leveldown/leveldown.js (C:\Users\Cam\projects\codename-desktop\myapp\dist_electron\index.js:16214:1)
    at __webpack_require__ (C:\Users\Cam\projects\codename-desktop\myapp\dist_electron\index.js:20:30)
    at eval (webpack:///./node_modules/@virgilsecurity/e3kit-node/dist/node.es.js?:36:67)
    at Module../node_modules/@virgilsecurity/e3kit-node/dist/node.es.js (C:\Users\Cam\projects\codename-desktop\myapp\dist_electron\index.js:1495:1) {
  name: 'UnhandledRejection Error'
}
```

Workaround:
```
yarn add leveldown --save --build-from-source
```
Seems to solve the problem.

It's worth mentioning, when I do `yarn install` it **does** indicate that leveldown was rebuilt.

**Comment by camhart** [comment]
Adjusting the webpack config appears to have fixed the issue.

```
    node: {
      __dirname: true
    }
```

**Comment by killpowa** [comment]
I am encountering the same issue but that's not fixing it for me. Would you be so kind to share your project, or at least your webpack configuration? @camhart
