### ISSUE TITLE
Error: Content-Type "multipart/byteranges" is expected, but got "application/x-msdos-program"

### ISSUE THREAD

**Issue by vitozyf** [electron-userland/electron-builder#5036]
"electron-builder": "^22.3.6",

* **Version**: 

"electron": "7.1.13",

* **Electron Version**: "7.1.13",
* **Electron Type (current, beta, nightly)**:

"electron-updater": "^4.2.0",

* **Target**: "nsis"

An error occurred while trying to automate updates

The error log is as follows:

```
[2020-06-05 17:00:37.509] [info] Checking for update
[2020-06-05 17:00:37.816] [info] Found version 1.1.5 (url: ZnlLinkAll Setup 1.1.5.exe)
[2020-06-05 17:00:37.823] [info] Downloading update from ZnlLinkAll Setup 1.1.5.exe
[2020-06-05 17:00:37.835] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: Ps3EiFiy08wx308gIQ0DE4WaTxHm1YlkMkhz2BCvx7hwVDDS66/HvVeSeRwtUJ7eaHEX5J/dgPHyfTjrSqSFsg==, expected: Ksa59IHeo1vnGOKs2Zl88Z+QrHDyv1QMCk6RL564dNlOGBD9mPGE0D9O91j8YCkBw7W356ZPfqprgb2JwqioIQ==. Directory for cached update will be cleaned
[2020-06-05 17:00:37.849] [info] Download block maps (old: "http://127.0.0.1:7001/public/ZnlLinkAll%20Setup%201.1.4.exe.blockmap", new: http://127.0.0.1:7001/public/ZnlLinkAll%20Setup%201.1.5.exe.blockmap)
[2020-06-05 17:00:37.910] [info] File has 74 changed blocks
[2020-06-05 17:00:37.928] [info] Full: 45,337.02 KB, To download: 1,570.47 KB (3%)
[2020-06-05 17:00:38.925] [error] Cannot download differentially, fallback to full download: Error: Content-Type "multipart/byteranges" is expected, but got "application/x-msdos-program"
    at ClientRequest.<anonymous> (D:\Program Files\ReactEle\ZnlLinkAll\resources\app.asar\main.prod.js:2:137144)
    at ClientRequest.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2536:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
[2020-06-05 17:00:40.380] [info] New version 1.1.5 has been downloaded to C:\Users\Dell\AppData\Local\electron-react-boilerplate-updater\pending\ZnlLinkAll Setup 1.1.5.exe

```

Package configuration is as follows

```
"build": {
    "compression": "maximum",
    "asar": true,
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true,
      "menuCategory": true,
      "allowElevation": false
    },
   "publish": {
      "provider": "generic",
      "url": "http://127.0.0.1:7001/public/",
      "channel": "latest"
    }
}
```

**Comment by harshitsilly** [comment]
@vitozyf  Hi, try this module electron-differential-updater.. it is built on top of electron-builder and help u with the fix.
It also has differential update for mac also.

**Comment by M956588010** [comment]
hey,bro,do you resolve this problem? @vitozyf

**Comment by harshitsilly** [comment]
@M956588010  you can try this module [electron-differential-updater](https://imjselectron.github.io/electron-differential-updater/#/) it has the fix and the other features..
