### ISSUE TITLE
Unable to find latest version on GitHub, please ensure a production release exists: HttpError: 401 Unauthorized

### ISSUE THREAD

**Issue by brennomarques** [electron-userland/electron-builder#5037]
* **Version 1.0.0: 

* **Electron Version: 5.0.0:
* **Electron Type (current, beta, nightly)**:

* Target: 1.0.1: 

I'm using electron-updade, I can generate the builds using localhost and update normal, but when I use Github I can't see the versions, what I did ..... I perform a comimit for my project master, I made a tag v1.0.0 for Releases. remember that I generated a token, according to the documentation you have to put in "autoUpdater.setFeedURL", all that was done. but the log presents that message.

* **.logs**

```
[2020-06-04 17:51:15.962] [info] Checking for update
[2020-06-04 17:51:17.423] [error] Error: Error: Unable to find latest version on GitHub (https://api.github.com/repos/brennomarques/skeleton-vue-electron/releases/latest), please ensure a production release exists: HttpError: 401 Unauthorized
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
Headers: {
  "access-control-allow-origin": [
    "*"
  ],
  "access-control-expose-headers": [
    "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset"
  ],
  "content-length": [
    "83"
  ],
  "content-security-policy": [
    "default-src 'none'"
  ],
  "content-type": [
    "application/json; charset=utf-8"
  ],
  "date": [
    "Thu, 04 Jun 2020 20:51:17 GMT"
  ],
  "referrer-policy": [
    "origin-when-cross-origin, strict-origin-when-cross-origin"
  ],
  "server": [
    "GitHub.com"
  ],
  "status": [
    "401 Unauthorized"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "vary": [
    "Accept-Encoding, Accept, X-Requested-With"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-media-type": [
    "github.v3; format=json"
  ],
  "x-github-request-id": [
    "FA67:7FC4:DF791:137467:5ED95EC5"
  ],
  "x-ratelimit-limit": [
    "60"
  ],
  "x-ratelimit-remaining": [
    "54"
  ],
  "x-ratelimit-reset": [
    "1591305212"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at f (C:\Users\brenno\AppData\Local\Programs\skeleton-vue-electron\resources\app.asar\background.js:1:127371)
    at IncomingMessage.<anonymous> (C:\Users\brenno\AppData\Local\Programs\skeleton-vue-electron\resources\app.asar\background.js:1:129703)
    at IncomingMessage.emit (events.js:194:13)
    at endReadableNT (_stream_readable.js:1141:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at t.newError (C:\Users\brenno\AppData\Local\Programs\skeleton-vue-electron\resources\app.asar\background.js:1:5792)
    at l.getLatestVersionInfo (C:\Users\brenno\AppData\Local\Programs\skeleton-vue-electron\resources\app.asar\background.js:2:231695)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

```

* **Main.js**

```
if (process.env.NODE_ENV !== 'development') {
    autoUpdater.setFeedURL({
      provider: 'github',
      repo: 'skeleton-vue-electron',
      owner: 'brennomarques',
      private: true,
      token: '1a377b5b689077c0ec7fe24f230e10ba6b921b38'
    });
    autoUpdater.checkForUpdates();
  }
```
* **.json**

```
"build": {
    "appId": "com.friasoftit.electron-auto-update",
    "productName": "Electron Auto Update",
    "win": {
      "publish": [
        "github"
      ],
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]
    }
  },
```

I don't know what else to do, another detail that when I perform the git push for my git, the Token disappears to git. https://github.com/brennomarques/skeleton-vue-electron

**Comment by Cosen95** [comment]
@brennomarques I encountered the same problem, have you solved it now?

- "electron": "^10.1.5",
-  "electron-builder": "^22.9.1",

**Comment by brennomarques** [comment]
Solved, but I created a local WEB server with a valid domain on the web.

In git you can't put it to work, localhost and Web production all ok

to work on the web I didn't even make a change.
