### ISSUE TITLE
Cannot update from private github repository linux

### ISSUE THREAD

**Issue by agnoam** [electron-userland/electron-builder#5058]
* **Version**: 22.6.0

* **Electron Version**: 8.2.5

* **electron-updater version**: 4.3.1

* **Target**:  Linux

This is my *app-update.yml:*
```
owner: agnoam
repo: my_repo
provider: github
private: true
token: xxxxxxxxxxxxxxxxxxxGH_TOKENxxxxxxxxxxxxxxxxxx
updaterCacheDirName: electron-updater-private-updater
```
For checking the Updates I'm using: `autoUpdater.checkForUpdates();`

On Windows everything works fine. But on Linux it throws an exception:
```
[2020-06-09 15:00:03.968] [info] Checking for update
[2020-06-09 15:00:07.250] [error] Error: HttpError: 404 Not Found
"method: GET url: https://github.com/agnoam/my_repo/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "date": "Tue, 09 Jun 2020 14:00:07 GMT",
  "content-type": "text/plain; charset=utf-8",
  "server": "GitHub.com",
  "status": "404 Not Found",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=_gh_sess_code; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.604450108.1591711206; Path=/; Domain=github.com; Expires=Wed, 09 Jun 2021 14:00:06 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Wed, 09 Jun 2021 14:00:06 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "9FEC:ED05:67D8BBF:9596948:5EDF95E6"
}
    at createHttpError (/tmp/.mount_df_vieZrsJrd/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_df_vieZrsJrd/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:169:14)
    at ClientRequest.<anonymous> (/tmp/.mount_df_vieZrsJrd/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2510:12)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)

```

**Comment by tozeka** [comment]
I am experiencing this error since yesterday on Windows. What it could be?
 "electron-updater": "^4.3.9"
"electron-builder": "^22.11.7"
