### ISSUE TITLE
how to build form Programmatic usage

### ISSUE THREAD

**Issue by phevose** [electron-userland/electron-builder#508]
beacuse i won't use "two package.json" method,so i build myApp(win32) use Programmatic,but below error appear:

```
> node ./electronPackage.js

Warning: license in the development package.json is deprecated, please move to the application package.json
Error: Build for OS X is supported only on OS X, please see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build
    at Packager.<anonymous> (D:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\electron-builder\5.3.0\electron-builder\src\packager.ts:81:15)
    at undefined.next (native)
From previous event:
    at tsAwaiter (D:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\electron-builder\5.3.0\electron-builder\src\awaiter.ts:10:47)
    at Object.build (D:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\electron-builder\5.3.0\electron-builder\src\builder.ts:182:52)
    at D:\work\nodejs\angular\angular2-electron\electronPackage.js:9:13
    at next (D:\work\nodejs\angular\angular2-electron\node_modules\rimraf\rimraf.js:74:7)
    at CB (D:\work\nodejs\angular\angular2-electron\node_modules\rimraf\rimraf.js:110:9)
    at D:\work\nodejs\angular\angular2-electron\node_modules\rimraf\rimraf.js:136:14
    at FSReqWrap.oncomplete (fs.js:117:15)
```

*****************electronPackage.js*********************
```
"use strict"
const path = require('path');
const rimraf = require('rimraf');
const builder = require("electron-builder")
const Platform = builder.Platform

builder.build({
        targets: Platform.OSX.createTarget(),
        devMetadata: {
            "build": {
                "productName": "mysoft",
                "description": "only test",
                "win": {
                    "iconUrl": "icon.ico",
                    "loadingGif": "loading.gif",
                    "msi": true
                }
            },
            "directories":{
                "app": "./output/electron/build",
                "output": "./output/electron/dist"
            },
            "arch": "x64",
            "platform": "win32"
        }
    }).then(() => {
        // handle result
    }).catch((error) => {
        // handle error
        return console.error( error);
    });
```

**Comment by develar** [comment]
> targets: Platform.OSX.createTarget(),

This line wins. Remote `arch` and `platform`. 
Replace `Platform.OSX.createTarget(),` to `Platform.WINDOWS.createTarget(null, builder.Arch.ia32),`

**Comment by phevose** [comment]
Thank @develar  for responding, i have found the problem,but how to set icon(local ico) & other electron-packager options?
```
"use strict"
const path = require('path');
const rimraf = require('rimraf');
const builder = require("electron-builder");
const Platform = builder.Platform;
const resourcePath = path.resolve(__dirname,"./src/electron");
const buildPath = "./output/electron/build";
const distPath = "./output/electron/dist";

builder.build({
        targets: Platform.WINDOWS.createTarget(null, builder.Arch.x64),
        devMetadata: {
            "build": {
                "productName": "myapp",
                "description": "only test",
                "win": {
                    "loadingGif": path.join(buildPath,"loading.gif"),
                    "msi": true
                }
            },
            "directories":{
                "buildResources":buildPath,
                "app": buildPath,
                "output": distPath
            }
        }
    }).then(() => {
        // handle result
    }).catch((error) => {
        // handle error
        return console.error( error);
    });
```

**Comment by develar** [comment]
See https://github.com/electron-userland/electron-builder#in-short

In general, follow conventions instead of specifying tons of options. Anyway, any option in the `devMetadata.build` will be passed to electron-packager. But please follow conventions. Some options are prohibited or deprecated — you will get error or warning in this case.

**Comment by phevose** [comment]
@develar Your reply so quickly! i set "icon" in "build" as below:
```
           "build": {
                "productName": "myapp",
                "description": "only test",
                "icon":"logo.ico",
                "win": {
                    "loadingGif": path.join(buildPath,"loading.gif"),
                    "msi": true
                }
            }
```
but electron-builder still to find icon.ico under buildPath, not "logo.ico".
