### ISSUE TITLE
Failed to build DMG, blockmap for Mac but uploads / builds properly for Windows

### ISSUE THREAD

**Issue by jjason685** [electron-userland/electron-builder#5122]
* **Version**: v22.4.1

* **Electron Version**: v6.1.10
* **Electron Type (current, beta, nightly)**: current

* **Target**: Mac and Windows

⨯ hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace= |   |  
-- | -- | --
  | Error: hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE |   |  
  | at ChildProcess.<anonymous> (/Users/Shared/Jenkins/Home/workspace/Wrath v3/node_modules/builder-util/src/util.ts:239:14) |   |  
  | at Object.onceWrapper (events.js:300:26) |   |  
  | at ChildProcess.emit (events.js:210:5) |   |  
  | at maybeClose (internal/child_process.js:1021:16) |   |  
  | at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

It builds & uploads properly for Windows (packaging off of a Mac) but fails to build the DMG for Mac.

**Comment by jjason685** [comment]
Fixed with a build machine restart.
