### ISSUE TITLE
Cannot download differentially, fallback to full download: Error: invalid block type

### ISSUE THREAD

**Issue by DataScientist1** [electron-userland/electron-builder#5131]
"electron-builder": "22.7.0"
"electron": "8.3.2"
"electron-updater": "4.3.1"
"target": "nsis-web"

 Cannot download differentially, fallback to full download: Error: invalid block type
    at Zlib.zlibOnError [as onerror] (zlib.js:170:17)
    at processChunkSync (zlib.js:416:12)
    at zlibBufferSync (zlib.js:156:12)
    at syncBufferWrapper (zlib.js:755:14)
    at readBlockMap (../../src/differentialDownloader/FileWithEmbeddedBlockMapDifferentialDownloader.ts:18:21)
    at FileWithEmbeddedBlockMapDifferentialDownloader.download (../../src/differentialDownloader/FileWithEmbeddedBlockMapDifferentialDownloader.ts:12:25)

any help regarding this issue will be appreciated, thank you

**Comment by harshitsilly** [comment]
@DataScientist1  Hi, try this module electron-differential-updater.. it is built on top of electron-builder and help u with the fix.
It also has differential update for mac also.
