### ISSUE TITLE
Using absolute path for devMetadata.directories.app option leads to error

### ISSUE THREAD

**Issue by alchapone** [electron-userland/electron-builder#514]
Getting  `Application directory doesn't exist` error when passing absolute path to electron-builder as app dir:
``` javascript
builder.build({
  targets: builder.Platform[platform.toUpperCase()].createTarget(),
  devMetadata: {
    directories: {
      app: app_path,
      buildResources: 'resources',
      output: 'packages'
    }
  }
})
// app_path => /Users/ac/OSS/gistgram/builds/production
```

but this is not true:

```
Unhandled rejection Error: Application directory /Users/ac/OSS/gistgram/builds/production doesn't exists
    at Object.<anonymous> (/Users/ac/OSS/bozon/node_modules/electron-builder/src/util.ts:187:13)
    at undefined.next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at tsAwaiter (/Users/ac/OSS/bozon/node_modules/electron-builder/src/awaiter.ts:10:47)
    at Object.build (/Users/ac/OSS/bozon/node_modules/electron-builder/src/builder.ts:182:52)
    at Packager.productionBuild (/Users/ac/OSS/bozon/lib/packaging/packager.js:40:20)
    at Packager.build (/Users/ac/OSS/bozon/lib/packaging/packager.js:14:19)
    at Object.bozon.package (/Users/ac/OSS/bozon/lib/bozon.js:61:21)
    at Object.runner.package (/Users/ac/OSS/bozon/lib/runner.js:26:18)
    at Command.<anonymous> (/Users/ac/OSS/bozon/lib/cli.js:40:19)
    at Command.listener (/Users/ac/OSS/bozon/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/ac/OSS/bozon/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/ac/OSS/bozon/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/ac/OSS/bozon/lib/cli.js:43:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

ac$ ls /Users/ac/OSS/gistgram/builds/production
index.html	javascripts	node_modules	package.json	stylesheets
```

**Comment by develar** [comment]
Thanks for #515.
