### ISSUE TITLE
Electron updater throwing error that can't be handled

### ISSUE THREAD

**Issue by linonetwo** [electron-userland/electron-builder#5151]
* **Version**:   "electron-builder": "22.7.0",

* **Electron Version**: "electron": "9.1.0"
* **Electron Type (current, beta, nightly)**: current

"electron-updater": "4.3.3"

* **Target**: Mac

It throwing following error when I use lled to see main thread's log:

```
Error: Error: No published versions on GitHub
    at newError (/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/dist/mac/Singlebox.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/index.js:212:17)
    at XElement.element (/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/dist/mac/Singlebox.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/xml.js:70:35)
    at GitHubProvider.getLatestVersion (/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/dist/mac/Singlebox.app/Contents/Resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:101:30)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async MacUpdater.getUpdateInfoAndProvider (/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/dist/mac/Singlebox.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:500:13)
    at async MacUpdater.doCheckForUpdates (/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/dist/mac/Singlebox.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:516:20)
(node:90173) UnhandledPromiseRejectionWarning: Error: No published versions on GitHub
    at newError (/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/dist/mac/Singlebox.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/index.js:212:17)
    at XElement.element (/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/dist/mac/Singlebox.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/xml.js:70:35)
    at GitHubProvider.getLatestVersion (/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/dist/mac/Singlebox.app/Contents/Resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:101:30)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async MacUpdater.getUpdateInfoAndProvider (/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/dist/mac/Singlebox.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:500:13)
    at async MacUpdater.doCheckForUpdates (/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/dist/mac/Singlebox.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:516:20)
(node:90173) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

I can't find who is throwing this error, adding try catch to some of call to `autoUpdater` can't stop this.

**Comment by momakes** [comment]
Just for resolving your own issue, from the error appears if you add one release to the repository, this will be gone.
