### ISSUE TITLE
 Error: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by StitchC** [electron-userland/electron-builder#5164]
* **Version: 20.38.5**: 

* **Electron Version: 4.1.4**:
* **Electron Type (current, beta, nightly)none**:

* **using built-in autoUpdater**

* **Target: win**: 

auto-update throw error when download resource finish, see below:

----------------------------------------------------------------------------------------------------------------------------------------
{ Error: EBUSY: resource busy or locked, rename 'C:\Users\admin\AppData\Local\vipthink-test-online-updater\pending\temp-vipthink-test-online_win_2.2.1.exe' -> 'C:\Users\admin\AppData\Local\vipthink-test-online-updater\pending\vipthink-test-online_win_2.2.1.exe'
      at O.M [as _captureStackTrace] (D:\工具\VIPThink-test-online\resources\app.asar\dist\main.js:1:1481962)
      at new h (D:\工具\VIPThink-test-online\resources\app.asar\dist\main.js:1:1505292)
      at D:\工具\VIPThink-test-online\resources\app.asar\dist\main.js:1:1508398
      at t.NsisUpdater.executeDownload (D:\工具\VIPThink-test-online\resources\app.asar\dist\main.js:1:352973)
      at t.NsisUpdater.executeDownload (D:\工具\VIPThink-test-online\resources\app.asar\dist\main.js:1:694666)
      at t.NsisUpdater.doDownloadUpdate (D:\工具\VIPThink-test-online\resources\app.asar\dist\main.js:1:1804655)
      at t.NsisUpdater.downloadUpdate (D:\工具\VIPThink-test-online\resources\app.asar\dist\main.js:1:349413)
      at EventEmitter.value (D:\工具\VIPThink-test-online\resources\app.asar\dist\main.js:1:21375)
      at EventEmitter.emit (events.js:182:13)
      at WebContents.<anonymous> (D:\工具\VIPThink-test-online\resources\electron.asar\browser\api\web-contents.js:346:13)
      at WebContents.emit (events.js:182:13)
    cause:
     { Error: EBUSY: resource busy or locked, rename 'C:\Users\admin\AppData\Local\vipthink-test-online-updater\pending\temp-vipthink-test-online_win_2.2.1.exe' -> 'C:\Users\admin\AppData\Local\vipthink-test-online-updater\pending\vipthink-test-online_win_2.2.1.exe'
       errno: -4082,
       code: 'EBUSY',
       syscall: 'rename',
       path:
        'C:\\Users\\admin\\AppData\\Local\\vipthink-test-online-updater\\pending\\temp-vipthink-test-online_win_2.2.1.exe',
       dest:
        'C:\\Users\\admin\\AppData\\Local\\vipthink-test-online-updater\\pending\\vipthink-test-online_win_2.2.1.exe' },
    isOperational: true,
    errno: -4082,
    code: 'EBUSY',
    syscall: 'rename',
    path:
     'C:\\Users\\admin\\AppData\\Local\\vipthink-test-online-updater\\pending\\temp-vipthink-test-online_win_2.2.1.exe',
    dest:
     'C:\\Users\\admin\\AppData\\Local\\vipthink-test-online-updater\\pending\\vipthink-test-online_win_2.2.1.exe' }

----------------------------------------------------------------------------------------------------------------------------------------
how i can solve this error, did i make some mistake on my config ?

**Comment by StitchC** [comment]
any answer can provide ?
