### ISSUE TITLE
Cannot download differentially, fallback to full download

### ISSUE THREAD

**Issue by TonyLiuYan** [electron-userland/electron-builder#5182]
* **Version**: 
"electron-builder": "^22.7.0"

* **Electron Version**:
"electron": "^8.2.5"

* **Electron Type (current, beta, nightly)**:
"electron-updater": "^4.3.1"

* **Target**: 
nsis

const { autoUpdater, CancellationToken } = require('electron-updater');
autoUpdater.checkForUpdates();

```15:40:59.666 > Checking for update
15:40:59.861 > Found version 2.0.0 (url: myelectron-2.0.0.exe)
15:41:02.140 > 0
15:41:02.141 > Downloading update from myelectron-2.0.0.exe
15:41:02.236 > No cached update info available
15:41:02.239 > Download block maps (old: "http://62.234.153.20/electron/myelectron-1.0.0.exe.blockmap", new: http://62.234.153.20/electron/myelectron-2.0.0.exe.blockmap)
15:41:02.370 > File has 46 changed blocks
15:41:02.371 > [
  {
    "kind": 0,
    "start": 0,
    "end": 44218
  },
  {
    "kind": 1,
    "start": 44218,
    "end": 99842
  },
  {
    "kind": 0,
    "start": 99847,
    "end": 146333
  },
  {
    "kind": 1,
    "start": 146328,
    "end": 179096
  },
  {
    "kind": 0,
    "start": 179101,
    "end": 9126837
  },
  {
    "kind": 1,
    "start": 9126832,
    "end": 9739610
  },
  {
    "kind": 0,
    "start": 9739694,
    "end": 62164597
  },
  {
    "kind": 1,
    "start": 62164513,
    "end": 62284466
  },
  {
    "kind": 0,
    "start": 62284600,
    "end": 81203762
  },
  {
    "kind": 1,
    "start": 81203628,
    "end": 81230228
  },
  {
    "kind": 0,
    "start": 81230362,
    "end": 81461794
  },
  {
    "kind": 1,
    "start": 81461660,
    "end": 81473024
  },
  {
    "kind": 0,
    "start": 81473158,
    "end": 81490681
  },
  {
    "kind": 1,
    "start": 81490547,
    "end": 81600973
  }
]
15:41:02.405 > Full: 79,688.45 KB, To download: 946.79 KB (1%)
15:41:02.413 > Cannot download differentially, fallback to full download: Error: ENOENT: no such file or directory, open 'C:\Users\xxxx\AppData\Roaming\myelectron\__installer.exe'
    at D:\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:119:29
    at Generator.next (<anonymous>)
From previous event:
    at GenericDifferentialDownloader.doDownloadFile (D:\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:118:82)
    at GenericDifferentialDownloader.downloadFile (D:\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:92:17)
    at GenericDifferentialDownloader.doDownload (D:\node_modules\electron-updater\src\differentialDownloader\DifferentialDownloader.ts:79:17)
    at D:\node_modules\electron-updater\src\differentialDownloader\GenericDifferentialDownloader.ts:6:16
    at Generator.next (<anonymous>)
From previous event:
    at GenericDifferentialDownloader.download (D:\node_modules\electron-updater\src\differentialDownloader\GenericDifferentialDownloader.ts:5:62)
    at D:\node_modules\electron-updater\src\NsisUpdater.ts:190:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at NsisUpdater.differentialDownloadInstaller (D:\node_modules\electron-updater\src\NsisUpdater.ts:158:210)
    at Object.<anonymous> (D:\node_modules\electron-updater\src\NsisUpdater.ts:32:42)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (D:\node_modules\electron-updater\src\NsisUpdater.ts:29:11)
    at D:\node_modules\electron-updater\src\AppUpdater.ts:569:25
    at Generator.throw (<anonymous>)
From previous event:
    at NsisUpdater.executeDownload (D:\node_modules\electron-updater\src\AppUpdater.ts:487:68)
    at NsisUpdater.executeDownload (D:\node_modules\electron-updater\src\BaseUpdater.ts:29:18)
    at D:\node_modules\electron-updater\src\NsisUpdater.ts:25:23
From previous event:
    at NsisUpdater.doDownloadUpdate (D:\node_modules\electron-updater\src\NsisUpdater.ts:22:80)
    at D:\node_modules\electron-updater\src\AppUpdater.ts:393:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at NsisUpdater.downloadUpdate (D:\node_modules\electron-updater\src\AppUpdater.ts:382:86)
    at Function.<anonymous> (D:\PrivateProject\electron\electron-quick-start\main.js:91:29)
aborted... 6.400163880398828
15:41:10.623 > Cancelled
15:41:10.630 > Error: Error: Cancelled
    at CancellationToken.cancelHandler (D:\node_modules\electron-updater\node_modules\builder-util-runtime\src\CancellationToken.ts:62:18)
    at Object.onceWrapper (events.js:273:13)
    at CancellationToken.emit (events.js:182:13)
    at CancellationToken.cancel (D:\node_modules\electron-updater\node_modules\builder-util-runtime\src\CancellationToken.ts:33:10)
    at Function.<anonymous> (D:\PrivateProject\electron\electron-quick-start\main.js:110:43)
    at _callbacks.(anonymous function)._callbacks.(anonymous function).forEach.cb (D:\PrivateProject\electron\electron-quick-start\node_modules\_electron-progressbar@1.2.0@electron-progressbar\source\index.js:196:7)
    at Array.forEach (<anonymous>)
    at ProgressBar._fire (D:\PrivateProject\electron\electron-quick-start\node_modules\_electron-progressbar@1.2.0@electron-progressbar\source\index.js:195:52)
    at BrowserWindow._window.on (D:\PrivateProject\electron\electron-quick-start\node_modules\_electron-progressbar@1.2.0@electron-progressbar\source\index.js:259:10)
    at BrowserWindow.emit (events.js:182:13)
From previous event:
    at CancellationToken.createPromise (D:\node_modules\electron-updater\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at D:\node_modules\electron-updater\src\electronHttpExecutor.ts:19:44
    at Generator.next (<anonymous>)
From previous event:
    at ElectronHttpExecutor.download (D:\node_modules\electron-updater\src\electronHttpExecutor.ts:14:76)
    at Object.<anonymous> (D:\node_modules\electron-updater\src\NsisUpdater.ts:33:35)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (D:\node_modules\electron-updater\src\NsisUpdater.ts:29:11)
    at D:\node_modules\electron-updater\src\AppUpdater.ts:569:25
    at Generator.throw (<anonymous>)
From previous event:
    at NsisUpdater.executeDownload (D:\node_modules\electron-updater\src\AppUpdater.ts:487:68)
    at NsisUpdater.executeDownload (D:\node_modules\electron-updater\src\BaseUpdater.ts:29:18)
    at D:\node_modules\electron-updater\src\NsisUpdater.ts:25:23
From previous event:
    at NsisUpdater.doDownloadUpdate (D:\node_modules\electron-updater\src\NsisUpdater.ts:22:80)
    at D:\node_modules\electron-updater\src\AppUpdater.ts:393:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at NsisUpdater.downloadUpdate (D:\node_modules\electron-updater\src\AppUpdater.ts:382:86)
    at Function.<anonymous> (D:\PrivateProject\electron\electron-quick-start\main.js:91:29)
鏇存柊鍑洪敊
Unhandled rejection Error: Cancelled
    at CancellationToken.cancelHandler (D:\node_modules\electron-updater\node_modules\builder-util-runtime\src\CancellationToken.ts:62:18)
    at Object.onceWrapper (events.js:273:13)
    at CancellationToken.emit (events.js:182:13)
    at CancellationToken.cancel (D:\node_modules\electron-updater\node_modules\builder-util-runtime\src\CancellationToken.ts:33:10)
    at Function.<anonymous> (D:\PrivateProject\electron\electron-quick-start\main.js:110:43)
    at _callbacks.(anonymous function)._callbacks.(anonymous function).forEach.cb (D:\PrivateProject\electron\electron-quick-start\node_modules\_electron-progressbar@1.2.0@electron-progressbar\source\index.js:196:7)
    at Array.forEach (<anonymous>)
    at ProgressBar._fire (D:\PrivateProject\electron\electron-quick-start\node_modules\_electron-progressbar@1.2.0@electron-progressbar\source\index.js:195:52)
    at BrowserWindow._window.on (D:\PrivateProject\electron\electron-quick-start\node_modules\_electron-progressbar@1.2.0@electron-progressbar\source\index.js:259:10)
    at BrowserWindow.emit (events.js:182:13)
From previous event:
    at CancellationToken.createPromise (D:\node_modules\electron-updater\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at D:\node_modules\electron-updater\src\electronHttpExecutor.ts:19:44
    at Generator.next (<anonymous>)
From previous event:
    at ElectronHttpExecutor.download (D:\node_modules\electron-updater\src\electronHttpExecutor.ts:14:76)
    at Object.<anonymous> (D:\node_modules\electron-updater\src\NsisUpdater.ts:33:35)
    at Generator.next (<anonymous>)
From previous event:
    at Object.task (D:\node_modules\electron-updater\src\NsisUpdater.ts:29:11)
    at D:\node_modules\electron-updater\src\AppUpdater.ts:569:25
    at Generator.throw (<anonymous>)
From previous event:
    at NsisUpdater.executeDownload (D:\node_modules\electron-updater\src\AppUpdater.ts:487:68)
    at NsisUpdater.executeDownload (D:\node_modules\electron-updater\src\BaseUpdater.ts:29:18)
    at D:\node_modules\electron-updater\src\NsisUpdater.ts:25:23
    at Object.task (D:\node_modules\electron-updater\src\NsisUpdater.ts:29:11)
    at D:\node_modules\electron-updater\src\AppUpdater.ts:569:25
    at Generator.throw (<anonymous>)
From previous event:
    at NsisUpdater.executeDownload (D:\node_modules\electron-updater\src\AppUpdater.ts:487:68)
    at NsisUpdater.executeDownload (D:\node_modules\electron-updater\src\BaseUpdater.ts:29:18)
    at D:\node_modules\electron-updater\src\NsisUpdater.ts:25:23
From previous event:
    at NsisUpdater.doDownloadUpdate (D:\node_modules\electron-updater\src\NsisUpdater.ts:22:80)
    at D:\node_modules\electron-updater\src\AppUpdater.ts:393:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at NsisUpdater.downloadUpdate (D:\node_modules\electron-updater\src\AppUpdater.ts:382:86)
    at Function.<anonymous> (D:\PrivateProject\electron\electron-quick-start\main.js:91:29)
Done in 14.35s.```

**Comment by jjhbw** [comment]
May be fixed by https://github.com/electron-userland/electron-builder/pull/5025

Can you check with the latest version of `electron-updater` and `electron-builder`?

**Comment by jane-rose** [comment]
still not working.

**Comment by Sirbuland** [comment]
Still having this issue:

**Electron Builder Version:**
"electron-builder": "^22.9.1"

**Electron Version:**
"electron": "^11.3.0"

**Electron Updater:**
"electron-updater": "^4.3.5"

**Comment by cazetto** [comment]
Same for me:

"electron-builder": "^22.11.7",
"electron": "^13.2.2",
"electron-updater": "^4.3.9",

**Comment by n3g2** [comment]
Same for me:

"electron-builder": "^24.6.3",
"electron": "^26.0.0",
"electron-updater": "^6.1.1",

**Comment by fatihhidiroglu** [comment]
I have that same problem. json has the following versions. How can I solve this problem?
dependencies: {
    "electron-updater": "^6.1.4",
}
devDependencies: {
   "electron": "^26.2.1",
   "electron-builder": "^24.9.1",
}
