### ISSUE TITLE
Passing dir option to builder.build() throws "Unknown option" error

### ISSUE THREAD

**Issue by zposten** [electron-userland/electron-builder#5207]
* **Version**:  22.8.0

* **Electron Version**: 9.1.2
* **Electron Type (current, beta, nightly)**:  current

* **Target**:  Windows

Passing the `dir` option to `builder.build()`:

```js
const builder = require('electron-builder')
const Platform = builder.Platform

builder.build({
  targets: Platform.WINDOWS.createTarget(),
  dir: true,
})
```

throws an error:

```
  • electron-builder  version=22.8.0 os=10.0.18362
(node:13872) UnhandledPromiseRejectionWarning: Error: Unknown option "dir"
    at checkBuildRequestOptions (C:\dev\carlo\pbi-tips\business-ops\node_modules\app-builder-lib\src\index.ts:44:13)
    at build (C:\dev\carlo\pbi-tips\business-ops\node_modules\app-builder-lib\src\index.ts:50:3)
    at Object.build (C:\dev\carlo\pbi-tips\business-ops\node_modules\electron-builder\src\builder.ts:218:10)
    at createExe (C:\dev\carlo\pbi-tips\business-ops\bld\build-exe.js:12:31)
```

even though according to the typescript types this should be valid:

```ts
export interface CliOptions extends PackagerOptions, PublishOptions {
    x64?: boolean;
    ia32?: boolean;
    armv7l?: boolean;
    arm64?: boolean;
    dir?: boolean;
}

export declare function build(rawOptions?: CliOptions): Promise<Array<string>>;
```

I couldn't find documentation around the`dir` flag on [JavaScript API](https://www.electron.build/api/electron-builder) (although it is present in [the CLI documentation](https://www.electron.build/cli)).

**Comment by zposten** [comment]
As a workaround, this seems to work:

```js
builder.build({
  targets: Platform.WINDOWS.createTarget(builder.DIR_TARGET),
})
```

**Comment by zposten** [comment]
Yes this is still relevant.  I think that to move forward, someone with more thorough knowledge of electron-builder needs to diagnose the issue.

**Comment by zposten** [comment]
Yes this is still relevant. I think that to move forward, someone with more thorough knowledge of electron-builder needs to diagnose the issue.

**Comment by baparham** [comment]
Seems to be gated in `app-builder-lib/src/index.ts:39` ([link](https://github.com/electron-userland/electron-builder/blob/ff242ab865f65987da4d95183a99c6fbaa7d3b78/packages/app-builder-lib/src/index.ts#L39)) but simply adding `'dir'` to the list still doesn't make this work, so it's likely that the underlying implementation needs to be added/fixed as well.

It makes the error go away, but the app is still built. Perhaps there is still just one more link that needs to be fixed to get the `dir` option all the way to where it's used like the `--dir` option on the cli.

**Comment by jiakuan** [comment]
I got a similar issue with the latest prerelease version `22.10.4`:

```
  • electron-builder  version=22.10.4 os=20.2.0
(node:38196) UnhandledPromiseRejectionWarning: Error: Unknown option "arm64"
    at checkBuildRequestOptions (/Users/jake/pi/desktop_fe_app/node_modules/app-builder-lib/src/index.ts:44:13)
    at build (/Users/jake/pi/desktop_fe_app/node_modules/app-builder-lib/src/index.ts:50:3)
    at Object.build (/Users/jake/pi/desktop_fe_app/node_modules/electron-builder/src/builder.ts:219:10)
    at build (/Users/jake/pi/desktop_fe_app/packaging/builder.js:191:21)
    at Object.<anonymous> (/Users/jake/pi/desktop_fe_app/packaging/builder.js:202:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:38196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zposten** [comment]
Yes this is still relevant. Others have added some diagnosis and additional examples.
