### ISSUE TITLE
build mac on ubuntu16

### ISSUE THREAD

**Issue by msi008** [electron-userland/electron-builder#5209]
* **Version**: 22.7.0

* **Electron Version**: 8.3.4
* **Electron Type (current, beta, nightly)**:

* **Target**: mac dmg

It always fails to build MAC installation package in Ubuntu environment,

I want to generate the DMG installation package and command electron-builder -m

The error information is as follows：

⨯ Cannot cleanup:

Error #1 --------------------------------------------------------------------------------
Error: Exit code: ENOENT. spawn productbuild ENOENT
    at /imclass-pc/node_modules/builder-util/src/util.ts:129:16
    at exithandler (child_process.js:296:5)
    at ChildProcess.errorhandler (child_process.js:308:5)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Error #2 --------------------------------------------------------------------------------
Error: spawn hdiutil ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)  stackTrace=

How can I solve it gracefully

**Comment by baruchvlz** [comment]
As far as I know, Mac builds can be built in Mac.

**Comment by b-zurg** [comment]
lol yeah the solution is to have a mac man.  Or get a sketchy vm setup.   If you configure things through trial and error you should be able to get a build running on github actions as it has actual mac runners available.  Although then how do you test the install....
