### ISSUE TITLE
Fails to upload mac.zip to github

### ISSUE THREAD

**Issue by krazyjakee** [electron-userland/electron-builder#5224]
* **Version**: 22.8.0

* **Electron Version**: 8
* **Electron Type (current, beta, nightly)**: current

* **Target**: Mac/Windows x64

The process throws ERR_ELECTRON_BUILDER_CANNOT_EXECUTE with no useful stack trace.

```
  • electron-builder  version=22.8.0 os=19.6.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=release/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=8.4.1 appOutDir=release/mac
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                                   0 identities found
                                              
                                                Valid identities only
                                                   0 valid identities found
  • building        target=macOS zip arch=x64 file=release/MystaliaManager-0.0.1-mac.zip
  • building        target=DMG arch=x64 file=release/MystaliaManager-0.0.1.dmg
  • packaging       platform=win32 arch=x64 electron=8.4.1 appOutDir=release/win-unpacked
  • building        target=MSI arch=x64 file=release/MystaliaManager 0.0.1.msi
  • building        target=nsis file=release/MystaliaManager Setup 0.0.1.exe archs=x64 oneClick=true perMachine=false
  ⨯ macOS Catalina doesn't support 32-bit executables and as result Wine cannot run Windows 32-bit applications too  
  • building block map  blockMapFile=release/MystaliaManager Setup 0.0.1.exe.blockmap
  • publishing      publisher=Github (owner: krazyjakee, project: mystalia-manager, version: 0.0.1)
  • uploading       file=MystaliaManager-Setup-0.0.1.exe.blockmap provider=GitHub
  • uploading       file=MystaliaManager-Setup-0.0.1.exe provider=GitHub
    [                    ] 0% 0.0s | MystaliaManager-Setup-0.0.1.exe to GitHub  • building block map  blockMapFile=release/MystaliaManager-0.0.1.dmg.blockmap
  • uploading       file=MystaliaManager-0.0.1.dmg.blockmap provider=GitHub
  • uploading       file=MystaliaManager-0.0.1.dmg provider=GitHub

    [                    ] 0% 0.0s | MystaliaManager-0.0.1.dmg to GitHub  • overwrite published file  file=MystaliaManager-Setup-0.0.1.exe.blockmap reason=already exists on GitHub
  • overwrite published file  file=MystaliaManager-0.0.1.dmg.blockmap reason=already exists on GitHub
    [=======             ] 37% 31.0s | MystaliaManager-Setup-0.0.1.exe to GitHub  • building embedded block map  file=release/MystaliaManager-0.0.1-mac.zip
    [=======             ] 36% 31.1s | MystaliaManager-0.0.1.dmg to GitHub  • uploading       file=MystaliaManager-0.0.1-mac.zip provider=GitHub

    [                    ] 0% 0.0s | MystaliaManager-0.0.1-mac.zip to GitHub  ⨯ /Users/jake/.nvm/versions/node/v14.4.0/lib/node_modules/electron-builder/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                                                  Error: /Users/jake/.nvm/versions/node/v14.4.0/lib/node_modules/electron-builder/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                                      at ChildProcess.<anonymous> (/Users/jake/.nvm/versions/node/v14.4.0/lib/node_modules/electron-builder/node_modules/builder-util/src/util.ts:243:14)
                                                                                                                                                                                      at Object.onceWrapper (events.js:422:26)
                                                                                                                                                                                      at ChildProcess.emit (events.js:315:20)
                                                                                                                                                                                      at maybeClose (internal/child_process.js:1051:16)
```

**Comment by krazyjakee** [comment]
I gave up and set the repo to public. Then it wouldn't upload mac-latest.yml.
I replaced the "dmg" section of the package.json with
```
"mac": {
   "target": ["dmg", "zip"]
 },
```

Now it works.
