### ISSUE TITLE
Build Failure: cannot find background.tiff  

### ISSUE THREAD

**Issue by James-Hudson3010** [electron-userland/electron-builder#5232]
electron-builder  version=22.8.0 os=19.5.0

version "9.2.0"
current

macOS DMG

I am getting the following build error:

```
No such file or directory: '/path/to/.background/background.tiff'
```

when building the macOS dmg.

According to the documentation:

```
background String - The path to background image (default: build/background.tiff or build/background.png if exists). The resolution of this file determines the resolution of the installer window. If background is not specified, use window.size. Default locations expected background size to be 540x380. See: DMG with Retina background support.
```

I do not specify the background anywhere, but electron builder still wants to try to use the default image.  Do I have to specify and supply a background image? Any explanation as to why this is happening? A bug?

**Comment by James-Hudson3010** [comment]
more error output:

```
build	17-Aug-2020 09:57:53	 INFO  Building app with electron-builder:
build	17-Aug-2020 09:57:53	  � electron-builder  version=22.8.0 os=19.5.0
build	17-Aug-2020 09:57:53	  � artifacts will be published if draft release exists  reason=CI detected
build	17-Aug-2020 09:57:53	  � packaging       platform=darwin arch=x64 electron=9.2.0 appOutDir=dist_electron/mac
build	17-Aug-2020 09:57:55	  � skipped macOS code signing  reason=identity explicitly is set to null
build	17-Aug-2020 09:57:55	  � building        target=DMG arch=x64 file=dist_electron/MyAmm.dmg
build	17-Aug-2020 09:57:55	  � packaging       platform=linux arch=x64 electron=9.2.0 appOutDir=dist_electron/linux-unpacked
build	17-Aug-2020 09:57:57	  � building        target=deb arch=x64 file=dist_electron/MyAmm.deb
build	17-Aug-2020 09:57:58	  � packaging       platform=win32 arch=x64 electron=9.2.0 appOutDir=dist_electron/win-unpacked
build	17-Aug-2020 09:58:00	  � building        target=nsis file=dist_electron/MyAmm.exe archs=x64 oneClick=true perMachine=false
build	17-Aug-2020 09:58:34	  � building block map  blockMapFile=dist_electron/MyAmm.exe.blockmap
error	17-Aug-2020 09:59:25	(node:92987) UnhandledPromiseRejectionWarning: Error: Compound error: 
error	17-Aug-2020 09:59:25	
error	17-Aug-2020 09:59:25	Error #1 --------------------------------------------------------------------------------
error	17-Aug-2020 09:59:25	Error: Exit code: 1. Command failed: /usr/bin/python /Users/bamboosa/bamboo-agent-2/xml-data/build-dir/JIG-JPUM-JOB1/node_modules/dmg-builder/vendor/dmgbuild/core.py
error	17-Aug-2020 09:59:25	Traceback (most recent call last):
error	17-Aug-2020 09:59:25	  File "/Users/bamboosa/bamboo-agent-2/xml-data/build-dir/JIG-JPUM-JOB1/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 282, in <module>
error	17-Aug-2020 09:59:25	    build_dmg()
error	17-Aug-2020 09:59:25	  File "/Users/bamboosa/bamboo-agent-2/xml-data/build-dir/JIG-JPUM-JOB1/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 249, in build_dmg
error	17-Aug-2020 09:59:25	    alias = Alias.for_file(background_file)
error	17-Aug-2020 09:59:25	  File "/Users/bamboosa/bamboo-agent-2/xml-data/build-dir/JIG-JPUM-JOB1/node_modules/dmg-builder/vendor/mac_alias/alias.py", line 348, in for_file
error	17-Aug-2020 09:59:25	    st = osx.statfs(path)
error	17-Aug-2020 09:59:25	  File "/Users/bamboosa/bamboo-agent-2/xml-data/build-dir/JIG-JPUM-JOB1/node_modules/dmg-builder/vendor/mac_alias/osx.py", line 816, in statfs
error	17-Aug-2020 09:59:25	    raise OSError(err, os.strerror(err), path)
error	17-Aug-2020 09:59:25	OSError: [Errno 2] No such file or directory: '/Volumes/MyAmm 0.0.1/.background/background.png'
```

**Comment by James-Hudson3010** [comment]
For the additional error output, I did create a background.png in the default "build" folder...but I still get a similar error message.

Looking into this issue more, it would seem that electron builder should be copying a background image to the .background folder of the DMG it is creating and that is not happening for some reason.

**Comment by James-Hudson3010** [comment]
I have also noted that this is not consistent behavior...sometimes it works...sometimes it doesn't. I think it works most of the time.

**Comment by James-Hudson3010** [comment]
What appears to resolve the build issue I am seeing is the following workaround script:

```
#!/bin/bash

verify_file_exists() {
    filePath=$1
    
    for i in {1..3}
    do
        if [ -f "$filePath" ];
        then
            echo "    $filePath EXISTS"
            sleep 10
            return 0
        fi
        
        sleep 10
    done
    
    echo "    $filePath DOES NOT EXIST"
    return 42
}

yarn_build() {
    platform=$1
    builtArtifact=$2
    
    echo "yarn build for $platform"
    
    for i in {1..3}
    do
        yarn --verbose electron:build -$platform
        error=$?
        
        if [ "$error" -eq "0" ]; 
        then
            verify_file_exists $builtArtifact
            error=$?
            
            if [ "$error" -eq "0" ]; 
            then
                echo "    yarn build SUCCESS for $platform"
                sleep 10
                return 0                   
            fi
        fi   
        
        sleep 10   
                
    done
    
    echo "    yarn build FAILED for $platform"
    exit 42    
}

export PATH="/opt/local/bin:$PATH"
yarn_build m "./dist_electron/MyAmm.dmg"
yarn_build w "./dist_electron/MyAmm.exe"
yarn_build l "./dist_electron/MyAmm.deb"
```

The basic problem is that the yarn build process when building DMGs can fail in a myriad of ways. The yarn code written to do this does not properly propagate up and return error codes indicating that something went wrong. Right after the build, I check to see if the expected artifact exists. If it does not, I try again. The second attempt always seems to work.

**Comment by James-Hudson3010** [comment]
Here is some more output after turning using 

```
build	18-Aug-2020 07:53:25	   exited          command=app-builder code=0 pid=55891 out={"backgroundWidth":600,"backgroundHeight":600,"backgroundFile":"/Volumes/MyAmm/.background/bkgnd_a.png"}
build	18-Aug-2020 07:53:25	   executing       file=ln args=-s /Applications /Volumes/MyAmm/Applications
build	18-Aug-2020 07:53:25	   executed        file=ln
build	18-Aug-2020 07:53:25	   executing       file=/usr/bin/python args=/Users/bamboosa/bamboo-agent-2/xml-data/build-dir/JIG-JPUM-JOB1/node_modules/dmg-builder/vendor/dmgbuild/core.py cwd=/Users/bamboosa/bamboo-agent-2/xml-data/build-dir/JIG-JPUM-JOB1/node_modules/dmg-builder/vendor env=
build	18-Aug-2020 07:53:25	                      {
build	18-Aug-2020 07:53:25	                        "volumePath": "/Volumes/MyAmm",
build	18-Aug-2020 07:53:25	                        "appFileName": "MyAmm.app",
build	18-Aug-2020 07:53:25	                        "iconSize": 80,
build	18-Aug-2020 07:53:25	                        "iconTextSize": 12,
build	18-Aug-2020 07:53:25	                        "PYTHONIOENCODING": "utf8",
build	18-Aug-2020 07:53:25	                        "windowWidth": "600",
build	18-Aug-2020 07:53:25	                        "windowHeight": "600",
build	18-Aug-2020 07:53:25	                        "windowX": 400,
build	18-Aug-2020 07:53:25	                        "windowY": "420",
build	18-Aug-2020 07:53:25	                        "backgroundWidth": 600,
build	18-Aug-2020 07:53:25	                        "backgroundHeight": 600,
build	18-Aug-2020 07:53:25	                        "backgroundFile": "/Volumes/MyAmm/.background/bkgnd_a.png",
build	18-Aug-2020 07:53:25	                        "iconLocations": "'MyAmm.app': (300, 166),\n'Applications': (300, 410)"
build	18-Aug-2020 07:53:25	                      }
build	18-Aug-2020 07:53:38	   executed        file=/usr/bin/python
build	18-Aug-2020 07:53:38	   executing       file=hdiutil args=detach -quiet /dev/disk2
build	18-Aug-2020 07:53:39	   executing       file=hdiutil args=detach -force /dev/disk2
build	18-Aug-2020 07:53:40	   async task error  error=
build	18-Aug-2020 07:53:40	                        Exit code: 1. Command failed: hdiutil detach -force /dev/disk2
build	18-Aug-2020 07:53:40	                        hdiutil: detach failed - No such file or directory
build	18-Aug-2020 07:53:40	                        
build	18-Aug-2020 07:53:40	                        hdiutil: detach failed - No such file or directory
build	18-Aug-2020 07:53:40	                        
error	18-Aug-2020 07:53:40	(node:55035) UnhandledPromiseRejectionWarning: Error: Exit code: 1. Command failed: hdiutil detach -force /dev/disk2
error	18-Aug-2020 07:53:40	hdiutil: detach failed - No such file or directory
error	18-Aug-2020 07:53:40	
error	18-Aug-2020 07:53:40	hdiutil: detach failed - No such file or directory
error	18-Aug-2020 07:53:40	
error	18-Aug-2020 07:53:40	    at /Users/bamboosa/bamboo-agent-2/xml-data/build-dir/JIG-JPUM-JOB1/node_modules/builder-util/src/util.ts:129:16
error	18-Aug-2020 07:53:40	    at ChildProcess.exithandler (child_process.js:315:5)
error	18-Aug-2020 07:53:40	    at ChildProcess.emit (events.js:314:20)
error	18-Aug-2020 07:53:40	    at maybeClose (internal/child_process.js:1051:16)
error	18-Aug-2020 07:53:40	    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
error	18-Aug-2020 07:53:40	(Use `node --trace-warnings ...` to show where the warning was created)
error	18-Aug-2020 07:53:40	(node:55035) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
error	18-Aug-2020 07:53:40	(node:55035) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
build	18-Aug-2020 07:53:40	Done in 66.26s.
```

I do not know why the disk appears to disappear before the hdiutil tries to detach it. 

One problem is that this error is not propagated up, allowing the build processs to exit with a non-zero error code.

**Comment by martpie** [comment]
@James-Hudson3010 I'm encountering a similar issue, have you found a solution?

**Comment by Rabbitzzc** [comment]
me too. Is there a solution to this problem?

**Comment by roryabraham** [comment]
I just ran into this problem too

**Comment by MangoSwirl** [comment]
@James-Hudson3010 Were you able to solve this? I'm having the same problem.

**Comment by Samuel-luo** [comment]
I have same issue with "electron-builder": "^25.1.8"
