### ISSUE TITLE
quitAndInstall failed with error spawn ... EACCES on some Windows machine

### ISSUE THREAD

**Issue by jackple** [electron-userland/electron-builder#5269]
My code:
`autoUpdater.quitAndInstall(true, true)`

Error: spawn C:\Users\xxxx\AppData\Local\yim-updater\pending\xxx-ia32-1.12.2.exe EACCES {}
Error: spawn C:\Program Files (x86)\yim\resources\elevate.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by maple-leaf** [comment]
![image](https://user-images.githubusercontent.com/3980995/95651671-8c8e6a00-0b1e-11eb-9e33-15f92b549584.png)
we had a similar problem here, the electron-updater throws spawn error when verifying the code signature.
