### ISSUE TITLE
Error running electron-builder :"Error: spawn EPERM"

### ISSUE THREAD

**Issue by stefancova** [electron-userland/electron-builder#5289]
* **Version**: 22.8.0
* **Electron Version**: 10.1.1
* **Electron Type (current, beta, nightly)**: current
* **Target**: windows portable executable x64
* **Operating system**: Windows 10

When running "npm run electron-builder" the process start, a7z file is created and then it failed with this error : 

`⨯ Cannot spawn C:\Users\username\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe: Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:548:9)
    at doSpawn (C:\Users\username\Documents\sites\maem\node_modules\builder-util\src\util.ts:170:12)
    at spawnAndWrite (C:\Users\username\Documents\sites\maem\node_modules\builder-util\src\util.ts:178:24)
    at NsisTarget.executeMakensis (C:\Users\username\Documents\sites\maem\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:552:11)
    at NsisTarget.buildInstaller (C:\Users\username\Documents\sites\maem\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:282:5)
    at NsisTarget.finishBuild (C:\Users\username\Documents\sites\maem\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:109:7)
    at async Promise.all (index 1)
    at AsyncTaskManager.awaitTasks (C:\Users\username\Documents\sites\maem\node_modules\builder-util\src\asyncTaskManager.ts:65:25)
    at Packager.doBuild (C:\Users\username\Documents\sites\maem\node_modules\app-builder-lib\src\packager.ts:456:5)
    at executeFinally (C:\Users\username\Documents\sites\maem\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\Users\username\Documents\sites\maem\node_modules\app-builder-lib\src\packager.ts:373:31)
    at Packager.build (C:\Users\username\Documents\sites\maem\node_modules\app-builder-lib\src\packager.ts:337:12)
    at executeFinally (C:\Users\username\Documents\sites\maem\node_modules\builder-util\src\promise.ts:12:14)`

**Comment by Ayzrian** [comment]
Try to run your command under the Admin user.

**Comment by yuwiggin** [comment]
Same issue when building Windows version on MacOS. 

Version: 22.9.1
Electron Version: 9.3.4
Electron Type (current, beta, nightly): current
Target: windows portable executable x64
Operating system: MacOS 10.12.6

The error message:

```
 
  ⨯ Cannot spawn /Users/username/Library/Caches/electron-builder/nsis/nsis-3.0.4.1/mac/makensis: Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:553:9)
    at doSpawn (/Users/username/webProjs/xxxx/node_modules/builder-util/src/util.ts:170:12)
    at spawnAndWrite (/Users/username/webProjs/xxxx/node_modules/builder-util/src/util.ts:178:24)
    at NsisTarget.executeMakensis (/Users/username/webProjs/xxxx/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:560:11)
    at NsisTarget.computeScriptAndSignUninstaller (/Users/username/webProjs/xxxx/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:340:5)
    at NsisTarget.buildInstaller (/Users/username/webProjs/xxxx/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:278:103)
    at NsisTarget.finishBuild (/Users/username/webProjs/xxxx/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:110:7)
    at async Promise.all (index 2)
    at AsyncTaskManager.awaitTasks (/Users/username/webProjs/xxxx/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at Packager.doBuild (/Users/username/webProjs/xxxx/node_modules/app-builder-lib/src/packager.ts:456:5)
    at executeFinally (/Users/username/webProjs/xxxx/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/username/webProjs/xxxx/node_modules/app-builder-lib/src/packager.ts:373:31)
    at Packager.build (/Users/username/webProjs/xxxx/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/Users/username/webProjs/xxxx/node_modules/builder-util/src/promise.ts:12:14)  stackTrace=

```

**Comment by Vadi** [comment]
Did you tried using 22.5.1. Make sure you provide fixed version in package.json file.

**Comment by yuwiggin** [comment]
I tried but didn't work
