### ISSUE TITLE
npm run build on macOS , i get this error,what i should do , i search some information on internet, but i can't resolve it. Can  you help me?

### ISSUE THREAD

**Issue by kaermomo** [electron-userland/electron-builder#5315]
Error: hdiutil exited with code 1
    at ChildProcess.<anonymous> (/Library/fileCombine/fileCombineElectron/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
From previous event:
    at _createStageDmg (/Library/fileCombine/fileCombineElectron/node_modules/dmg-builder/out/dmg.js:363:26)
    at createStageDmg (/Library/fileCombine/fileCombineElectron/node_modules/dmg-builder/out/dmg.js:351:26)
    at /Library/fileCombine/fileCombineElectron/node_modules/dmg-builder/src/dmg.ts:35:27
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Library/fileCombine/fileCombineElectron/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/macPackager.ts:91:26
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at /Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/macPackager.ts:91:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/macPackager.ts:82:95)
    at /Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at /Library/fileCombine/fileCombineElectron/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
    at callback (/Library/fileCombine/fileCombineElectron/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:177:5)
From previous event:
    at Packager.doBuild (/Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Library/fileCombine/fileCombineElectron/node_modules/graceful-fs/graceful-fs.js:144:16
    at /Library/fileCombine/fileCombineElectron/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:164:23)
From previous event:
    at Packager._build (/Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Packager.build (/Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Library/fileCombine/fileCombineElectron/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Library/fileCombine/fileCombineElectron/node_modules/electron-builder/src/builder.ts:228:10)
    at /Library/fileCombine/fileCombineElectron/node_modules/electron-builder/src/cli/cli.ts:49:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecombine@0.0.1 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecombine@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

-------------Delimiter-----------------
this is package.json:
{
  "name": "projectName",
  "version": "0.0.1",
  "author": "XXX",
  "description": "An electron-vue project",
  "license": "MIT",
  "main": "./dist/electron/main.js",
  "scripts": {
    "build": "node .electron-vue/build.js && electron-builder",
    "build:dir": "node .electron-vue/build.js && electron-builder --dir",
    "build:clean": "cross-env BUILD_TARGET=clean node .electron-vue/build.js",
    "build:web": "cross-env BUILD_TARGET=web node .electron-vue/build.js",
    "package": "electron-packager ./ --all",
    "packageall": "electron-packager ./ filecombine --all --out ./OutApp --electron-version 2.0.18 --electron-zip-dir=C:/Users/myName/AppData/Local/electron/Cache --overwrite",
    "packagewin": "electron-packager ./ filecombine --platform=win32 --arch=x64 --out=./OutApp --asar --app-version=2.0.1 --electron-version=2.0.18 --electron-zip-dir=C:/Users/myName/AppData/Local/electron/Cache --overwrite",
    "dev": "node .electron-vue/dev-runner.js",
    "lint": "eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter src",
    "lint:fix": "eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src",
    "pack": "npm run pack:main && npm run pack:renderer",
    "pack:main": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.main.config.js",
    "pack:renderer": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.renderer.config.js",
    "postinstall": "npm run lint:fix",
    "build-python-officetopdf": "pyinstaller -F ./python/OfficeToPdf.py --clean --distpath ./pydist",
    "build-python-pdf2image": "pyinstaller -F ./python/Pdf2Image.py --add-data ./python/poppler/*;./python/poppler --noupx --clean --distpath ./pydist"
  },
  "build": {
    "productName": "filecombine",
    "appId": "com.example.yourapp",
    "asar": true,
    "extraResources": [
      {
        "from": "./pydistwind/",
        "to": "../pydistwind/"
      },
      {
        "from": "./pydistlinux/",
        "to": "../pydistlinux/"
      },
      {
        "from": "./pydistmac/",
        "to": "pydistmac"
      },
      {
        "from": "./dll/",
        "to": "../dll/"
      }
    ],
    "directories": {
      "output": "build"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
    "mac": {
      "icon": "build/icons/icon.icns",
      "artifactName": "${productName}_setup_${version}.${ext}",
      "category": "your.app.category.type"
    },
    "win": {
      "icon": "filecombine.ico",
      "artifactName": "${productName}_setup_${version}.${ext}",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64"
          ]
        }
      ]
    },
    "linux": {
      "icon": "build/icons",
      "artifactName": "${productName}_setup_${version}.${ext}",
      "depends":
      [
        "gconf2", 
        "gconf-service", 
        "libnotify4", 
        "libappindicator1", 
        "libxtst6", 
        "libnss3"
      ]
    },
    "nsis": {
      "oneClick": false,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "installerIcon": "filecombine.ico",
      "uninstallerIcon": "filecombine.ico",
      "installerHeaderIcon": "filecombine.ico",
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true,
      "runAfterFinish": true,
      "guid": "FILECOMBINE",
      "include": "installer.nsh"
    }
  },
  "dependencies": {
    "axios": "^0.18.0",
    "element-ui": "^2.13.1",
    "ffi": "^2.3.0",
    "font-list": "^1.2.11",
    "nedb": "^1.8.0",
    "node-gyp": "^7.0.0",
    "python-shell": "^2.0.1",
    "rebuild": "^0.1.2",
    "ref": "^1.3.5",
    "ref-array": "^1.2.0",
    "sortable": "^2.0.0",
    "vue": "^2.5.16",
    "vue-electron": "^1.0.6",
    "vue-loading-overlay": "^3.3.2",
    "vue-radial-progress": "^0.3.1",
    "vue-router": "^3.0.1",
    "vuedraggable": "^2.23.2",
    "vuescroll": "^4.15.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "ajv": "^6.5.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "babel-minify-webpack-plugin": "^0.3.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
    "cfonts": "^2.1.2",
    "chalk": "^2.4.1",
    "copy-webpack-plugin": "^4.5.1",
    "cross-env": "^5.1.6",
    "css-loader": "^0.28.11",
    "del": "^3.0.0",
    "devtron": "^1.4.0",
    "electron": "^2.0.18",
    "electron-builder": "^20.19.2",
    "electron-debug": "^1.5.0",
    "electron-devtools-installer": "^2.2.4",
    "electron-packager": "^15.0.0",
    "electron-rebuild": "^1.11.0",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^4.0.3",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "0.4.0",
    "multispinner": "^0.2.1",
    "node-loader": "^0.6.0",
    "style-loader": "^0.21.0",
    "url-loader": "^1.0.1",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^15.2.4",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.15.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.3"
  }
}
----------------end-----------------------
please~ thank u

**Comment by kaermomo** [comment]
我认为我最后解决了这个问题，非常愚蠢的是，竟是因为磁盘空间不足了。
