### ISSUE TITLE
Installation Has Failed - Seems to be an issue with the RELEASES file

### ISSUE THREAD

**Issue by bsharper** [electron-userland/electron-builder#534]
This might be an upstream issue, but I figured I'd start here because I'm not familiar enough with the modules electron-builder uses to know which would be causing the error.

When I generate a Windows installer from OS X and then try to install the file I get a dialog box that says

```

[Window Title]
Setup.exe

[Main Instruction]
Installation has failed

[Content]
There was an error while installing the application. Check the setup log for more information and contact the author.
```

When I check the SquirrelSetup.txt log, the issue seems to be this:

```
2016-06-22 21:30:06> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Invalid release entry: Found new TLS offset at 240
   at Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Squirrel.ReleaseEntry.ParseReleaseFile(String fileContents)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Invalid release entry: Found new TLS offset at 240
   at Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Squirrel.ReleaseEntry.ParseReleaseFile(String fileContents)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```
(I can include the full output if needed)

When I extract the RELEASES files from the executable, the contents are simply "Found new TLS offset at 240" and not the expected `sha1 filename filesize` format. It almost seems like something is printing more lines than expected, and (for example) the first line is all that gets included in RELEASES. But this is just a guess.

I'm building this the same way I have in the past, I'm not sure what would have changed since the last time I built an installer.

If I copy the unpacked directory over, everything works as expected.

I'm using electron-builder@3.27.0.

**Comment by develar** [comment]
Please try latest release 5.x

**Comment by bsharper** [comment]
Hi @develar, I'm seeing the same error with electron-builder@5.6.2. I removed both the build `node_modules` and everything in the `dist` directories and did a fresh install and build to make sure I hadn't inadvertently changed something.

Output from the setup log from a W10 machine, installer built on OS X. I'm going to try this again on a different work computer shortly, I'll post something if I get a different result.

```
2016-06-23 08:59:31> Program: Starting Squirrel Updater: --install .
2016-06-23 08:59:31> Program: Starting install, writing to C:\Users\User\AppData\Local\SquirrelTemp
2016-06-23 08:59:31> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Invalid release entry: Found new TLS offset at 240
   at Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Squirrel.ReleaseEntry.ParseReleaseFile(String fileContents)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Invalid release entry: Found new TLS offset at 240
   at Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Squirrel.ReleaseEntry.ParseReleaseFile(String fileContents)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

```

**Comment by develar** [comment]
@bsharper Please send me your nupkg file and RELEASES.

**Comment by develar** [comment]
I guess error was caused by wine 1.8.3 update. Now we use more robust out parser.

**Comment by develar** [comment]
Please try 5.6.3

**Comment by bsharper** [comment]
@develar Thanks, it's working again!
