### ISSUE TITLE
Deb Fails

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#537]
```
Error: Command failed: /Users/admin/.cache/fpm/fpm-1.5.1-20150715-2.2.2-osx/fpm -s dir -t deb --architecture amd64 --name App --force --after-install /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/after-install --after-remove /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/after-remove --description 
 App Client GUI --maintainer App Foundation <info@app.com> --vendor App Foundation <info@app.com> --version 0.1.1.1-b --package /Users/admin/Desktop/App/dist/App-0.1.1.1-b.deb --url https://www.app.com/ --deb-compression xz --depends libappindicator1 --depends libnotify-bin /Users/admin/Desktop/App/dist/linux/=/opt/App Client /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/icon_16x16x32.png=/usr/share/icons/hicolor/16x16/apps/App.png /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/icon_24x24x32.png=/usr/share/icons/hicolor/24x24/apps/App.png /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/icon_32x32x32.png=/usr/share/icons/hicolor/32x32/apps/App.png /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/icon_48x48x32.png=/usr/share/icons/hicolor/48x48/apps/App.png /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/icon_64x64x32.png=/usr/share/icons/hicolor/64x64/apps/App.png /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/icon_96x96x32.png=/usr/share/icons/hicolor/96x96/apps/App.png /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/icon_128x128x32.png=/usr/share/icons/hicolor/128x128/apps/App.png /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/icon_256x256x32.png=/usr/share/icons/hicolor/256x256/apps/App.png /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/icon_512x512x32.png=/usr/share/icons/hicolor/512x512/apps/App.png /var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/electron-builder-linux-1j1-ipu02bl8-0/App Client.desktop=/usr/share/applications/App Client.desktop

{:timestamp=>"2016-06-24T19:16:50.380668+0200", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2016-06-24T19:16:50.920488+0200", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2016-06-24T19:17:58.731400+0200", :message=>"Process failed: ar failed (exit code 69). Full command was:[\"ar\", \"-qc\", \"/Users/admin/Desktop/App/dist/App-0.1.1.1-b.deb\", \"debian-binary\", \"control.tar.gz\", \"/var/folders/3n/4vf0scp56svf_945s1c3__gr0000gn/T/package-deb-build20160624-1999-pjm5xp/data.tar.xz\"]", :level=>:error}

    at /Users/admin/Desktop/App/node_modules/electron-builder/src/util/util.ts:86:16
    at ChildProcess.exithandler (child_process.js:214:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
From previous event:
    at Object.exec (/Users/admin/Desktop/App/node_modules/electron-builder/src/util/util.ts:72:9)
    at FpmTarget.<anonymous> (/Users/admin/Desktop/App/node_modules/electron-builder/src/targets/fpm.ts:173:15)
    at undefined.next (native)
    at tsAwaiter (/Users/admin/Desktop/App/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at FpmTarget.build (/Users/admin/Desktop/App/node_modules/electron-builder/src/targets/fpm.ts:103:81)
    at LinuxPackager.<anonymous> (/Users/admin/Desktop/App/node_modules/electron-builder/src/linuxPackager.ts:64:22)
From previous event:
    at tsAwaiter (/Users/admin/Desktop/App/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/Users/admin/Desktop/App/node_modules/electron-builder/src/builder.ts:190:52)
    at Object.<anonymous> (/Users/admin/Desktop/App/node_modules/electron-builder/src/build-cli.ts:25:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "distlin"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! @ distlin: `build --linux --x64 --ia32`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the @ distlin script 'build --linux --x64 --ia32'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --linux --x64 --ia32
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/Desktop/App/npm-debug.log

```

**Comment by kunkinkan** [comment]
Never mind, works in latest version.

**Comment by develar** [comment]
I think it is a sporadic error.

**Comment by sidneys** [comment]
@develar 
This keeps on popping up event in the latest versions and breaks Travis builds, without any clear reason for the error. Is there any new knowledge on this?

**Comment by chzhm159** [comment]
electron-builder: 20.10.0
tar : 1.26
node: V8.11.1
npm: 5.6.0
yarn: 1.6.0
xz: 5.2.2
centos7
this error was happened in my project
