### ISSUE TITLE
Build failing when productName contains a slash

### ISSUE THREAD

**Issue by n6g7** [electron-userland/electron-builder#539]
Environment:
> OS X 10.11.5
> Node v6.2.2
> npm v2.15.5
> electron-builder 5.7.0

I'm trying to build it for every platforms with `build -mwl`.

When the application package.json's `productName` contains a slash (eg. "A/B test") the build fails:
```sh
Rebuilding app dependencies for arch x64 to /Users/n6g7/dev/abtest/app

Packaging for platform darwin x64 using electron 1.2.5 to dist/mac

Error: ENOENT: no such file or directory, rename '/Users/n6g7/dev/abtest/dist/mac/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper' -> '/Users/n6g7/dev/abtest/dist/mac/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/A/B test Helper'
    at Error (native)
From previous event:
    at Object.rename (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/fs-extra-p/index.js:8:10)
    at rename (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/mac.js:11:13)
    at /Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/mac.js:17:12
From previous event:
    at moveHelpers (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/mac.js:15:18)
    at Promise.all.then.then (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/mac.js:160:19)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Object.createApp (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/mac.js:160:8)
    at promisifiedFs.emptyDir.then.then (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/index.js:155:61)
    at ZipFile.<anonymous> (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/node_modules/extract-zip/index.js:29:11)
    at emitNone (events.js:86:13)
    at ZipFile.emit (events.js:185:7)
    at FdSlicer.<anonymous> (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/node_modules/extract-zip/node_modules/yauzl/index.js:182:10)
    at FdSlicer.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at FdSlicer.emit (events.js:185:7)
    at onCloseDone (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/node_modules/extract-zip/node_modules/yauzl/node_modules/fd-slicer/index.js:74:12)
    at /Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/appdmg/node_modules/cp-file/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/graceful-fs.js:43:10
From previous event:
    at then.then.then.then (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/index.js:155:12)
    at /Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/node_modules/electron-download/index.js:44:14
    at /Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/node_modules/electron-download/node_modules/path-exists/index.js:8:3
    at FSReqWrap.oncomplete (fs.js:117:15)
From previous event:
    at Promise.mapSeries (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/index.js:141:8)
From previous event:
    at createPromise (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/index.js:99:18)
    at getNameAndVersion.catch.then (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/index.js:186:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Function.pack (/Users/n6g7/dev/abtest/node_modules/electron-builder/node_modules/electron-packager-tf/index.js:177:6)
    at MacPackager.<anonymous> (/Users/n6g7/dev/abtest/node_modules/electron-builder/src/platformPackager.ts:208:164)
    at undefined.next (native)
From previous event:
    at tsAwaiter (/Users/n6g7/dev/abtest/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/Users/n6g7/dev/abtest/node_modules/electron-builder/src/builder.ts:190:52)
    at Object.<anonymous> (/Users/n6g7/dev/abtest/node_modules/electron-builder/src/build-cli.ts:25:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.2.2
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! abtest@0.0.1 build: `rm -r dist && build -mwl`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the abtest@0.0.1 build script 'rm -r dist && build -mwl'.
npm ERR! This is most likely a problem with the abtest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -r dist && build -mwl
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs abtest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls abtest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/n6g7/dev/abtest/npm-debug.log
```

It looks like it's mistaking `A` for a directory. Is there a way to automatically replace slashes (and other reserved characters) during the build?

**Comment by develar** [comment]
Fixed, `A/B` [will be replaced](https://www.npmjs.com/package/sanitize-filename) to `AB`.

**Comment by develar** [comment]
MSI is not fixed, will be addressed later (I doubt that it is required for you).

**Comment by n6g7** [comment]
@develar Awesome, thanks for the quick fix!
