### ISSUE TITLE
Auto-update broken, cannot download differentially from github private repo.

### ISSUE THREAD

**Issue by AshwinDeTaeye** [electron-userland/electron-builder#5440]
Version: 22.9.1
    Electron Version: 9.3.1
    Electron-updater Version: 4.3.5
    Target:  "AppImage"

I'm trying to get the auto updater working with a private github repo.

My log (electron-log) : 
 
 ```
 $ cat ~/.config/App/logs/main.log
 
 [2020-11-27 12:06:05.474] [info] Checking for update
 [2020-11-27 12:06:06.473] [info] Found version 1.0.27 (url: App.AppImage)
 [2020-11-27 12:06:06.475] [info] Downloading update from App-1.0.27.AppImage
 [2020-11-27 12:06:06.479] [debug] updater cache dir: /home/user/.cache/App-updater
 [2020-11-27 12:06:06.686] [error] Cannot download differentially, fallback to full download: Error: Server doesn't support Accept-Ranges (response code 200)
     at o (/tmp/.mount_CAME-pD0DArx/resources/app.asar/main.prod.js:2:193042)
     at ClientRequest.<anonymous> (/tmp/.mount_App-pD0DArx/resources/app.asar/main.prod.js:2:188325)
     at ClientRequest.emit (events.js:223:5)
     at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6152)
     at SimpleURLLoaderWrapper.emit (events.js:223:5)
 ```
 
 The error in the log: 
 ```
 [error] Cannot download differentially, fallback to full download: Error: Server doesn't support Accept-Ranges (response code 200)
 ```

I have tried older versions of electron-builder and electron updater without success.

**Comment by lilian131** [comment]
Look my answer in stackoverflow: https://stackoverflow.com/questions/59837408/electron-updater-notify-for-new-release-but-do-not-update-or-download-new-releas/66940788#66940788
