### ISSUE TITLE
Error signing installer when building NSIS

### ISSUE THREAD

**Issue by bontibon** [electron-userland/electron-builder#547]
* **Version**: 5.10.1

* **Target**: Windows NSIS

```text
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for platform win32 ia32 using electron 1.2.4 to dist\win-ia32-unpacked

"ignore is specified as function, may be new "files" option will be suit your needs? Please see https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-files
Signing App.exe (certificate file "C:\Users\app\AppData\Local\Temp\3y4-ipy8b13p-0.p12")
Creating NSIS ia32 package

Building NSIS installer

Signing Setup 0.1.0.exe (certificate file "C:\Users\user\AppData\Local\Temp\3y4-ipy8b13p-0.p12")
{ Error: Signing failed with 1. SignTool Error: The file is being used by another process.
SignTool Error: An error occurred while attempting to sign: C:\Users\user\Desktop\app\dist\Setup 0.1.0.exe

    at Error (native)
    at ChildProcess.<anonymous> (C:\Users\user\Desktop\app\node_modules\signcode-tf\index.js:155:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at WinPackager.<anonymous> (C:\Users\user\Desktop\app\node_modules\electron-builder\src\winPackager.ts:132:43)
    at undefined.next (native)
From previous event:
    at tsAwaiter (C:\Users\user\Desktop\app\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at Object.build (C:\Users\user\Desktop\app\node_modules\electron-builder\src\builder.ts:190:52)
    at jetpack.readAsync.then (C:\Users\user\Desktop\app\pkg.js:81:24)
    at _fulfilled (C:\Users\user\Desktop\app\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\user\Desktop\app\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\user\Desktop\app\node_modules\q\q.js:796:13)
    at C:\Users\user\Desktop\app\node_modules\q\q.js:604:44
    at runSingle (C:\Users\user\Desktop\app\node_modules\q\q.js:137:13)
    at flush (C:\Users\user\Desktop\app\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  cause:
   Error: Signing failed with 1. SignTool Error: The file is being used by another process.
   SignTool Error: An error occurred while attempting to sign: C:\Users\user\Desktop\app\dist\Setup 0.1.0.exe

       at Error (native)
       at ChildProcess.<anonymous> (C:\Users\user\Desktop\app\node_modules\signcode-tf\index.js:155:16)
       at emitTwo (events.js:106:13)
       at ChildProcess.emit (events.js:191:7)
       at maybeClose (internal/child_process.js:850:16)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5),
  isOperational: true }
Error: Signing failed with 1. SignTool Error: The file is being used by another process.
SignTool Error: An error occurred while attempting to sign: C:\Users\user\Desktop\app\dist\Setup 0.1.0.exe

    at Error (native)
    at ChildProcess.<anonymous> (C:\Users\user\Desktop\app\node_modules\signcode-tf\index.js:155:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at WinPackager.<anonymous> (C:\Users\user\Desktop\app\node_modules\electron-builder\src\winPackager.ts:132:43)
    at undefined.next (native)
From previous event:
    at tsAwaiter (C:\Users\user\Desktop\app\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at Object.build (C:\Users\user\Desktop\app\node_modules\electron-builder\src\builder.ts:190:52)
    at jetpack.readAsync.then (C:\Users\user\Desktop\app\pkg.js:81:24)
    at _fulfilled (C:\Users\user\Desktop\app\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\user\Desktop\app\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\user\Desktop\app\node_modules\q\q.js:796:13)
    at C:\Users\user\Desktop\app\node_modules\q\q.js:604:44
    at runSingle (C:\Users\user\Desktop\app\node_modules\q\q.js:137:13)
    at flush (C:\Users\user\Desktop\app\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by develar** [comment]
Could you please attach full build log?

**Comment by develar** [comment]
Do you build only i32 or both arches?

**Comment by bontibon** [comment]
@develar Edited original comment to include full log. I build ia32 only.

**Comment by bontibon** [comment]
Just tried running it again without error.

**Comment by develar** [comment]
I suppose installer was running. Well, we cannot fix it — only suggest to use MacOS.
