### ISSUE TITLE
Auto update version issue 2.02.21

### ISSUE THREAD

**Issue by sarathak** [electron-userland/electron-builder#5472]
* **Version**: 22.7.0

* **Electron Version**:9.1.0
* **Electron Type (current, beta, nightly)**:current

* **Target**: windows

A JavaScript error occurred in the main process

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
```
Error: App version is not a valid semver version: "2.02.21"
    at newError (C:\Users\nano01\AppData\Local\Programs\yededoy\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\index.js:212:17)
    at new AppUpdater (C:\Users\nano01\AppData\Local\Programs\yededoy\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:236:48)
    at new BaseUpdater (C:\Users\nano01\AppData\Local\Programs\yededoy\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:20:5)
    at new NsisUpdater (C:\Users\nano01\AppData\Local\Programs\yededoy\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:126:5)
    at doLoadAutoUpdater (C:\Users\nano01\AppData\Local\Programs\yededoy\resources\app.asar\node_modules\electron-updater\out\main.js:129:20)
    at Object.get [as autoUpdater] (C:\Users\nano01\AppData\Local\Programs\yededoy\resources\app.asar\node_modules\electron-updater\out\main.js:142:28)
    at Object.<anonymous> (C:\Users\nano01\AppData\Local\Programs\yededoy\resources\app.asar\index.js:2:9)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

![](https://snipboard.io/zcu1Q3.jpg)

**Comment by sandeep1995** [comment]
@sarathak Please correct your app version. It should be `2.2.21`. 

`2.02.21` is not a valid semver.

**Comment by sarathak** [comment]
electron support it. I think builder must support it also .
