### ISSUE TITLE
can't build application

### ISSUE THREAD

**Issue by vamsee9** [electron-userland/electron-builder#5491]
* **Version**:  22.9.1

* **Electron Version**: 11.1.0
* **Electron Type (current, beta, nightly)**: latest

* **Target**:  windows

```
$ npx run electron-builder --win
npx: installed 5 in 1.764s
Watching D:\Electron-Projekt\mcpu and all sub-directories not excluded by your .gitignore. Will not monitor dotfiles.
Found & ignored ./node_modules ; is listed in .gitignore
Found & ignored ./out\Resource Monitor-win32-x64\resources\app\node_modules ; is listed in .gitignore
Found & ignored ./out\Resource Monitor-win32-x64\resources\app\src\index.css ; has ignored extension
Found & ignored ./src\index.css ; has ignored extension

Starting: electron-builder --win
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'D:\Electron-Projekt\mcpu\electron-builder'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by vamsee9** [comment]
By reinstalling Node Js it worked
