### ISSUE TITLE
electron not included

### ISSUE THREAD

**Issue by calidion** [electron-userland/electron-builder#5510]
* **Version**:   22.9.1

* **Electron Version**:  v11.0.3
* **Electron Type (current, beta, nightly)**:  current

* **Target**:   Linux

```
./trojan-desktop-0.1.0.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/tmp/.mount_trojanEbgd1n/resources/app.asar/node_modules/electron'
Require stack:
- /tmp/.mount_trojanEbgd1n/resources/app.asar/dist/desktop/src/option.js
- /tmp/.mount_trojanEbgd1n/resources/app.asar/dist/desktop/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/.mount_trojanEbgd1n/resources/app.asar/dist/desktop/src/option.js:15:17)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
```

**Comment by Bloeckchengrafik** [comment]
@calidion Can you please provide how you solved the issue?

**Comment by mmaietta** [comment]
electron isn't supposed to be included. It's a dev dependency. electron-quickstart example: https://github.com/electron/electron-quick-start/blob/master/package.json#L20
