### ISSUE TITLE
Installer crashes on Windows with System.IO.PathTooLongException when Asar is false

### ISSUE THREAD

**Issue by epezhman** [electron-userland/electron-builder#552]
* **Version**: 5.10.2

* **Target**:  Win32

Hi, when I don't specify `asar` in `.build ` of` package.json` it builds fine and I can install the `.exe` without any problem but when set the` "asar": false`, (which I need for my app), it builds fine but at installation it gives me `System.IO.PathTooLongException` error and it fails, Any idea or workroud? thanks, 
here is the log from SquirrelTemp:

```
2016-06-30 05:03:11> Program: Starting Squirrel Updater: --install .
2016-06-30 05:03:11> Program: Starting install, writing to C:\Users\epezhman\AppData\Local\SquirrelTemp
2016-06-30 05:03:11> Program: About to install to: C:\Users\epezhman\AppData\Local\tumdmdesktop
2016-06-30 05:03:11> Program: Install path C:\Users\epezhman\AppData\Local\tumdmdesktop already exists, burning it to the ground
2016-06-30 05:03:15> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\epezhman\AppData\Local\tumdmdesktop\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2016-06-30 05:03:15> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\epezhman\AppData\Local\tumdmdesktop\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-06-30 05:03:15> CheckForUpdateImpl: Reading RELEASES file from C:\Users\epezhman\AppData\Local\SquirrelTemp
2016-06-30 05:03:15> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-06-30 05:03:15> ApplyReleasesImpl: Writing files to app directory: C:\Users\epezhman\AppData\Local\tumdmdesktop\app-0.1.17
2016-06-30 05:03:34> IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Squirrel.ReleasePackage.ExtractZipDecoded(String zipFilePath, String outFolder, String directoryFilter)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-06-30 05:03:34> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Squirrel.ReleasePackage.ExtractZipDecoded(String zipFilePath, String outFolder, String directoryFilter)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Squirrel.ReleasePackage.ExtractZipDecoded(String zipFilePath, String outFolder, String directoryFilter)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---


```

**Comment by develar** [comment]
Please do not disable asar, windows io is very bad. Consider using `extraResources`/`extraFiles` (https://github.com/electron-userland/electron-builder/wiki/Options#BuildMetadata-extraResources).

**Comment by epezhman** [comment]
@develar Thanks for the reply, but I don't see how it can help me. For example I tried to move my `node_modules` directory with `extraResources`, now it's both in `resources `and also inside my `app.asar` . is there any equivalent to `--unpack-dir` in `asar`?

**Comment by develar** [comment]
Set `asar` to object of asar options:
```
"asar: {
  "unpackDir": "..."
}
```

> Now it's both in resourcesand also inside my app.asar
Because you don't use two-package structure ;) In any case `unpackDir ` should works.

**Comment by epezhman** [comment]
@develar Thanks again,  I set the `"unpackDir": "node_modules"` and it unpacks properly, but they are still in both places, (`resources\app.asar.unpacked` and `app.asar` ). thanks for  mentioning two-package structure, but I use it, am I doing something wrong? here is my project structure:

![project](https://cloud.githubusercontent.com/assets/3763134/16491560/c0d680ce-3ede-11e6-8ba5-fa00b4d2c0a7.PNG)

my` app/package.json`
```
{
  "name": "tumdmdesktop",
  "productName": "TUM Demand Manager",
  "description": "TUM Demand Manager for Computers.",
  "version": "0.1.17",
  "author": {
    "name": "TUM, Institute of Informatics",
    "email": "",
    "url": ""
  },
  "main": "./main.js",
  "license": "MIT",
  "homepage": "",
  "dependencies": {
    "application-config": "^0.2.2",
    "auto-launch": "^2.0.1",
    "electron-json-storage": "^2.0.0",
    "electron-positioner": "^3.0.0",
    "electron-squirrel-startup": "^1.0.0",
    "firebase": "^3.0.0",
    "jquery": "^3.0.0",
    "node-notifier": "^4.6.0",
    "node-uuid": "^1.4.7",
    "q": "^1.4.1",
    "request": "^2.72.0"
  }
}

```

my root/package.json
```
{
  "name": "tumdmdesktop",
  "productName": "TUM Demand Manager",
  "description": "TUM Demand Manager for Computers.",
  "author": {
    "name": "TUM, Institute of Informatics",
    "email": "",
    "url": ""
  },
  "scripts": {
    "postinstall": "install-app-deps",
    "start": "electron ./app --remote-debugging-port=9222",
    "dev": "set NODE_ENV=development&& npm start",
    "reload": "live-reload app --port 35729"
  },
  "devDependencies": {
    "async": "^2.0.0-rc.6",
    "aws-sdk": "^2.4.0",
    "del": "^2.2.0",
    "electron-builder": "^5.10.2",
    "electron-prebuilt": "^1.2.2",
    "gulp": "^3.9.1",
    "gulp-if": "^2.0.1",
    "gulp-jscs": "^4.0.0",
    "gulp-jshint": "^2.0.1",
    "gulp-load-plugins": "^1.2.4",
    "gulp-print": "^2.0.1",
    "gulp-sass": "^2.3.2",
    "gulp-task-listing": "^1.0.1",
    "gulp-util": "^3.0.7",
    "jshint": "^2.9.2",
    "jshint-stylish": "^2.2.0",
    "live-reload": "^1.1.0",
    "mkdirp": "^0.5.1",
    "mv": "^2.1.1",
    "q": "^1.4.1",
    "rimraf": "^2.5.2",
    "yargs": "^4.7.1"
  },
  "build": {
    "appId": "de.tum.tumdmdesktop",
    "app-category-type": "public.app-category.utilities",
    "iconUrl": "https://s3.eu-central-1.amazonaws.com/demand-manager-resources/icons/icon.ico",
    "files": [
      "**/*",
      "!assets/stylesheets/sass"
    ],
    "asar": {
      "unpackDir": "node_modules"
    },
    "dmg": {
      "title": "TUM Demand Manager",
      "icon-size": 128,
      "contents": [
        {
          "x": 355,
          "y": 125,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 155,
          "y": 125,
          "type": "file"
        }
      ]
    }
  }
}

```

and I build programmatically using gulp 

```
 return Q.fcall(()=> {
            utils.log('Building for Windows 64-bit')
            return builder.build({
                targets: Platform.WINDOWS.createTarget(null, Arch.x64)
            })
        })
```

**Comment by develar** [comment]
Thanks for detailed description. `extraResources` is to copy files outside of your app dir, so, these files are duplicated in your case. Yes — for your case you should use only `unpackDir` — #554.

**Comment by luisa123456** [comment]
Long Path tool can resolve error messages like: path too long, cannot delete file, too long path, destination path is too long, etc.

**Comment by frankLife** [comment]
LogHost: Rigging execution stub for %E8%BD%BB%E8%88%9F%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7_ExecutionStub.exe to C:\Users\shangpo.zw\AppData\Local\boat-ide\%E8%BD%BB%E8%88%9F%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7.exe
2018-01-09 19:53:56> IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: 指定的路径或文件名太长，或者两者都太长。完全限定文件名必须少于 260 个字符，并且目录名必须少于 248 个字符
