### ISSUE TITLE
Squirrel Updater error: System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'.

### ISSUE THREAD

**Issue by fredericlefeurmou** [electron-userland/electron-builder#553]
- **Version**: 5.10.2
- **Target**: Win

After my app is packaged, the squirrel updater is failing.
Here are the logs.

```
Building Squirrel.Windows installer

2016-06-30 07:20:39> Program: Starting Squirrel Updater: --releasify C:\Users\IEUser\project\dist\win\project-0.16.2-alpha-full.nupkg --releaseDir C:\Users\IEUser\project\dist\win

Error: 2016-06-30 07:20:39> Unhandled exception: System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 9, position 51.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 9, position 51.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)

Error: Command failed: C:\Users\IEUser\project\node_modules\electron-winstaller-fixed\vendor\Update.com --releasify C:\Users\IEUser\project\dist\win\project-0.16.2-alpha-full.nupkg --releaseDir C:\Users\IEUser\project\dist\win
2016-06-30 07:20:39> Unhandled exception: System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 9, position 51.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 9, position 51.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
    at C:\Users\IEUser\project\node_modules\electron-winstaller-fixed\lib\spawn-promise.js:56:18
    at ChildProcess.exithandler (child_process.js:214:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at tsAwaiter (C:\Users\IEUser\project\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at Object.build (C:\Users\IEUser\project\node_modules\electron-builder\src\builder.ts:190:52)
    at Object.<anonymous> (C:\Users\IEUser\project\node_modules\electron-builder\src\build-cli.ts:25:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IEUser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE
npm ERR! project@0.16.2-alpha dist: `build`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the project@0.16.2-alpha dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IEUser\project\npm-debug.log

IEUser@MSEDGEWIN10 MINGW64 ~/project (my-branch)
$ node -v
v6.2.2

IEUser@MSEDGEWIN10 MINGW64 ~/project (my-branch)
$ npm -v
3.10.2
```

**Comment by develar** [comment]
Please set env `DEBUG=electron-windows-installer` and attach log here. What is your app name?

**Comment by fredericlefeurmou** [comment]
Ok, here are the new logs:
```
Building Squirrel.Windows installer

Thu, 30 Jun 2016 18:28:26 GMT electron-windows-installer Created NuSpec file:
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>my-project</id>
    <version>0.16.2-alpha</version>
    <title>my-project</title>
    <authors>Company</authors>
    <owners>Company</owners>
    <iconUrl>https://images.google.fr/url?sa=t&rct=j&q=&source=imgres&cd=1&cad=rja&uact=8&ved=0ahUKEwich_2Hk83NAhXJtRoKHUztBxsQ5hMIBTAA&url=http%3A%2F%2Fwww.iconarchive.com%2Fdownload%2Fi27117%2Fph03nyx%2Fsuper-mario%2FMushroom-1UP.ico&usg=AFQjCNEAOvkn53xahhdCZKeBFdvuagVRmQ&sig2=AQ0ponG4KFg-0x16J_eBXQ</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>My App</description>
    <copyright>Copyright © 2016 Company</copyright>
    <projectUrl>http://www.company.com/</projectUrl>
  </metadata>
</package>
Thu, 30 Jun 2016 18:29:16 GMT electron-windows-installer Executing C:\Users\IEUser\company\my-project\node_modules\electron-winstaller-fixed\vendor\Update.com --releasify C:\Users\IEUser\company\my-project\dist\win\my-project-0.16.2-alpha-full.nupkg --releaseDir C:\Users\IEUser\company\my-project\dist\win
2016-06-30 11:29:16> Program: Starting Squirrel Updater: --releasify C:\Users\IEUser\company\my-project\dist\win\my-project-0.16.2-alpha-full.nupkg --releaseDir C:\Users\IEUser\company\my-project\dist\win

Error: 2016-06-30 11:29:16> Unhandled exception: System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 9, position 51.
```

And my build options:
```
  "build": {
    "appId": "com.company.myproject",
    "app-category-type": "public.app-category.productivity",
    "win": {
      "iconUrl": "https://images.google.fr/url?sa=t&rct=j&q=&source=imgres&cd=1&cad=rja&uact=8&ved=0ahUKEwich_2Hk83NAhXJtRoKHUztBxsQ5hMIBTAA&url=http%3A%2F%2Fwww.iconarchive.com%2Fdownload%2Fi27117%2Fph03nyx%2Fsuper-mario%2FMushroom-1UP.ico&usg=AFQjCNEAOvkn53xahhdCZKeBFdvuagVRmQ&sig2=AQ0ponG4KFg-0x16J_eBXQ"
    }
  },
```

I can't disclose the real app name for the moment.

Thanks

**Comment by develar** [comment]
> I can't disclose the real app name for the moment.

Yeah, logs means nothing without real data, but I understand. Ok. Does your app name (or description) contains `=` or other special chars?

**Comment by develar** [comment]
Please try to encode your icon url, e.g. using https://goo.gl (so, url will be like `http://goo.gl/V1J59T`)

**Comment by fredericlefeurmou** [comment]
You're right, the problem was coming from the icon url. Thanks a lot for your help on this one :)

**Comment by develar** [comment]
*** Squirrel.Windows, *** nuget, *** Windows :(

**Comment by develar** [comment]
Once #529 will be fixed, we will use NSIS as default target instead of buggy Squirrel.Windows.
