### ISSUE TITLE
Failed to verify application bundle. See details in debug log. (electron-osx-sign:error)

### ISSUE THREAD

**Issue by p3140** [electron-userland/electron-builder#559]
* **Version**: 5.10.3

* **Target**: mac

When signing app it throws the following error: 

`Failed to verify application bundle. See details in debug log. (electron-osx-sign:error)`

but nothing in debug log. some help please ?

**Comment by develar** [comment]
Please see https://www.npmjs.com/package/electron-osx-sign#debug

Set env `DEBUG=electron-osx-sign*` and build again to get debug log.

**Comment by p3140** [comment]
Thanks, its show the following:
```
electron-osx-sign:error Error: Command failed: codesign --verify --deep --verbose=2 /Applications/AMPPS/www/app/app/dist/mac/app.app
/Applications/AMPPS/www/app/app/dist/mac/app.app: nested code is modified or invalid
```

**Comment by develar** [comment]
cc @sethlu Could you please advice?

**Comment by develar** [comment]
@p3140 Could you please attach full build log?

**Comment by p3140** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/laboratorio/.nvm/versions/node/v6.2.2/bin/node',
1 verbose cli   '/Users/laboratorio/.nvm/versions/node/v6.2.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dist:osx' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'predist:osx', 'dist:osx', 'postdist:osx' ]
5 info lifecycle lsoft@1.0.1~predist:osx: lsoft@1.0.1
6 silly lifecycle lsoft@1.0.1~predist:osx: no script for predist:osx, continuing
7 info lifecycle lsoft@1.0.1~dist:osx: lsoft@1.0.1
8 verbose lifecycle lsoft@1.0.1~dist:osx: unsafe-perm in lifecycle true
9 verbose lifecycle lsoft@1.0.1~dist:osx: PATH: /Users/laboratorio/.nvm/versions/node/v6.2.2/lib/node_modules/npm/bin/node-gyp-bin:/Applications/AMPPS/www/lsoft-collahuasi/app/node_modules/.bin:/Users/laboratorio/.nvm/versions/node/v6.2.2/bin:/Users/laboratorio/.nvm/versions/node/v6.2.2/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/ruby193/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Applications/AMPPS/www/aliciamorgan/lib/Cake/Console/
10 verbose lifecycle lsoft@1.0.1~dist:osx: CWD: /Applications/AMPPS/www/lsoft-collahuasi/app
11 silly lifecycle lsoft@1.0.1~dist:osx: Args: [ '-c', 'build --platform darwin' ]
12 silly lifecycle lsoft@1.0.1~dist:osx: Returned: code: 255  signal: null
13 info lifecycle lsoft@1.0.1~dist:osx: Failed to exec dist:osx script
14 verbose stack Error: lsoft@1.0.1 dist:osx: `build --platform darwin`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (/Users/laboratorio/.nvm/versions/node/v6.2.2/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/laboratorio/.nvm/versions/node/v6.2.2/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid lsoft@1.0.1
16 verbose cwd /Applications/AMPPS/www/lsoft-collahuasi/app
17 error Darwin 13.3.0
18 error argv "/Users/laboratorio/.nvm/versions/node/v6.2.2/bin/node" "/Users/laboratorio/.nvm/versions/node/v6.2.2/bin/npm" "run" "dist:osx"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error lsoft@1.0.1 dist:osx: `build --platform darwin`
22 error Exit status 255
23 error Failed at the lsoft@1.0.1 dist:osx script 'build --platform darwin'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the lsoft package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     build --platform darwin
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs lsoft
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls lsoft
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by develar** [comment]
Thanks, but I mean console output (I want to see line `Signing ...`)

**Comment by p3140** [comment]
```
pib0x:app laboratorio$ NODE_ENV='development' DEBUG=electron-osx-sign:error npm run dist:osx

> lsoft@1.0.1 dist:osx /Applications/AMPPS/www/lsoft-collahuasi/app
> build --platform darwin

Rebuilding app dependencies for arch x64 to /Applications/AMPPS/www/lsoft-collahuasi/app/app

electron-squirrel-startup@1.0.0 /Applications/AMPPS/www/lsoft-collahuasi/app/app/node_modules/electron-squirrel-startup
debug@2.2.0 /Applications/AMPPS/www/lsoft-collahuasi/app/app/node_modules/debug
ms@0.7.1 /Applications/AMPPS/www/lsoft-collahuasi/app/app/node_modules/ms
jquery@3.0.0 /Applications/AMPPS/www/lsoft-collahuasi/app/app/node_modules/jquery
Packaging for platform mac x64 using electron 1.2.5 to dist/mac

Signing app (identity: Developer ID Application: José María Sanhueza Solovera (535AL6XDH5))

  electron-osx-sign:error Error: Command failed: codesign --verify --deep --verbose=2 /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app
/Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app: nested code is modified or invalid

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12) +0ms
(node:41551) Warning: a promise was rejected with a non-error: [object String]
(node:41551) Warning: a promise was rejected with a non-error: [object String]
(node:41551) Warning: a promise was rejected with a non-error: [object String]
(node:41551) Warning: a promise was rejected with a non-error: [object String]
(node:41551) Warning: a promise was rejected with a non-error: [object String]
(node:41551) Warning: a promise was rejected with a non-error: [object String]
(node:41551) Warning: a promise was rejected with a non-error: [object String]
Failed to verify application bundle. See details in debug log. (electron-osx-sign:error)

npm ERR! Darwin 13.3.0
npm ERR! argv "/Users/laboratorio/.nvm/versions/node/v6.2.2/bin/node" "/Users/laboratorio/.nvm/versions/node/v6.2.2/bin/npm" "run" "dist:osx"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! lsoft@1.0.1 dist:osx: `build --platform darwin`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the lsoft@1.0.1 dist:osx script 'build --platform darwin'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lsoft package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --platform darwin
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lsoft
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lsoft
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/AMPPS/www/lsoft-collahuasi/app/npm-debug.log
pib0x:app laboratorio$
```

**Comment by sethlu** [comment]
Hi @p3140, would you mind building again with the following command so we could get a full log of code-signing? We can't really find much clue currently with only the error thrown.

```sh
$ NODE_ENV='development' DEBUG=electron-osx-sign* npm run dist:osx
```

**Comment by p3140** [comment]
Hi @sethlu, here is the output

```
pib0x:app laboratorio$ NODE_ENV='development' DEBUG=electron-osx-sign* npm run dist:osx

> lsoft@1.0.3 dist:osx /Applications/AMPPS/www/lsoft-collahuasi/app
> build --platform darwin

Rebuilding app dependencies for arch x64 to /Applications/AMPPS/www/lsoft-collahuasi/app/app

electron-squirrel-startup@1.0.0 /Applications/AMPPS/www/lsoft-collahuasi/app/app/node_modules/electron-squirrel-startup
debug@2.2.0 /Applications/AMPPS/www/lsoft-collahuasi/app/app/node_modules/debug
ms@0.7.1 /Applications/AMPPS/www/lsoft-collahuasi/app/app/node_modules/ms
jquery@3.0.0 /Applications/AMPPS/www/lsoft-collahuasi/app/app/node_modules/jquery
Packaging for platform mac x64 using electron 1.2.5 to dist/mac

Signing app (identity: Developer ID Application: José María Sanhueza Solovera (535AL6XDH5))

  electron-osx-sign:warn No `entitlements` passed in arguments, will not sign with entitlements. +0ms
  electron-osx-sign Signing application... +89ms
  electron-osx-sign > application         /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app +1ms
  electron-osx-sign > platform            darwin +1ms
  electron-osx-sign > entitlements        undefined +0ms
  electron-osx-sign > child-entitlements  undefined +0ms
  electron-osx-sign > additional-binaries undefined +0ms
  electron-osx-sign > identity            Developer ID Application: José María Sanhueza Solovera (535AL6XDH5) +0ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +45ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib +8s
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib +748ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/crashpad_handler +2s
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/Electron Framework.framework +641ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle +6s
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/Mantle.framework +519ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa +553ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/ReactiveCocoa.framework +560ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/Squirrel.framework/Versions/A/Resources/ShipIt +522ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel +591ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/Squirrel.framework +647ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/lsoftcollahuasi Helper EH.app/Contents/MacOS/lsoftcollahuasi Helper EH +692ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/lsoftcollahuasi Helper EH.app +681ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/lsoftcollahuasi Helper NP.app/Contents/MacOS/lsoftcollahuasi Helper NP +607ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/lsoftcollahuasi Helper NP.app +615ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/lsoftcollahuasi Helper.app/Contents/MacOS/lsoftcollahuasi Helper +608ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/Frameworks/lsoftcollahuasi Helper.app +655ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app/Contents/MacOS/lsoftcollahuasi +601ms
  electron-osx-sign Signing... /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app +609ms
  electron-osx-sign Verifying code sign... +594ms
  electron-osx-sign:error Error: Command failed: codesign --verify --deep --verbose=2 /Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app
/Applications/AMPPS/www/lsoft-collahuasi/app/dist/mac/lsoftcollahuasi.app: nested code is modified or invalid

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12) +558ms
(node:1409) Warning: a promise was rejected with a non-error: [object String]
(node:1409) Warning: a promise was rejected with a non-error: [object String]
(node:1409) Warning: a promise was rejected with a non-error: [object String]
(node:1409) Warning: a promise was rejected with a non-error: [object String]
(node:1409) Warning: a promise was rejected with a non-error: [object String]
(node:1409) Warning: a promise was rejected with a non-error: [object String]
(node:1409) Warning: a promise was rejected with a non-error: [object String]
Failed to verify application bundle. See details in debug log. (electron-osx-sign:error)

npm ERR! Darwin 13.3.0
npm ERR! argv "/Users/laboratorio/.nvm/versions/node/v6.2.2/bin/node" "/Users/laboratorio/.nvm/versions/node/v6.2.2/bin/npm" "run" "dist:osx"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! lsoft@1.0.3 dist:osx: `build --platform darwin`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the lsoft@1.0.3 dist:osx script 'build --platform darwin'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lsoft package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --platform darwin
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lsoft
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lsoft
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/AMPPS/www/lsoft-collahuasi/app/npm-debug.log
pib0x:app laboratorio$ 
```

**Comment by sethlu** [comment]
Hi @p3140, I'm not sure where went wrong during your codesign phase. If there being no additional nested code left unsigned from your Electron app, would you try downloading "SignatureCheck" from https://developer.apple.com/download/more/, and checking your app bundle (though it failing the verification currently)?

> The signature check application ("check-signature") checks OS X application bundles and installer packages to determine if they are correctly signed for distribution and will pass the default Gatekeeper assessment.

I think it may tell us more about the missing components during the codesigning process. 😸

**Comment by p3140** [comment]
pib0x:mac laboratorio$ /Volumes/Signature\ Check/check-signature lsoftcollahuasi.app
(c) 2014 Apple Inc.  All rights reserved.
lsoftcollahuasi.app: nested code is modified or invalid
NO
pib0x:mac laboratorio$

**Comment by sethlu** [comment]
@p3140 Sorry that didn't seem very helpful. 😞 I'll have a think about the issue and get back with something soon.

**Comment by develar** [comment]
@p3140 Please try to check using https://itunes.apple.com/us/app/rb-app-checker-lite/id519421117?mt=12

**Comment by p3140** [comment]
@develar with the app checker everything looks fine but there is an error 
` Requirements and resources didn't pass static validation.`

if i expand details
```
Error details: “-67050: code failed to satisfy specified code requirement(s)” {
	Error in architecture: “x86_64”
}
```

if i click info of this error
`The bundle's code signature may be obsolete, or its contents may have been modified AFTER codesigning, either by a misplaced build step or deliberate hacking.`

**Comment by sethlu** [comment]
@p3140 may I ask which Xcode version you are using with codesign?

**Comment by p3140** [comment]
@sethlu Thanks man, i was using an old version of Xcode (6.x). After reading your comment i did update and now all works fine !. Thanks to all and sorry for de noob question :D

**Comment by sethlu** [comment]
@p3140 No worries; glad to know the issue's resolved. 🎊 Sometimes Xcode versions get slightly tricky...
