### ISSUE TITLE
build zeromq zerorpc error

### ISSUE THREAD

**Issue by blogwy** [electron-userland/electron-builder#5602]
```
electron-builder install-app-deps
  • electron-builder  version=22.9.1
  • rebuilding native dependencies  dependencies=zeromq@5.2.0, zeromq@4.6.0 platform=darwin arch=x64
  • install prebuilt binary  name=zeromq version=4.6.0 platform=darwin arch=x64
  • install prebuilt binary  name=zeromq version=5.2.0 platform=darwin arch=x64
  • build native dependency from sources  name=zeromq
                                          version=5.2.0
                                          platform=darwin
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.6
    prebuild-install info looking for cached prebuild @ /Users/wangyu/.npm/_prebuilds/9d2f15-zeromq-v5.2.0-electron-v80-darwin-x64.tar.gz
    prebuild-install http request GET https://github.com/zeromq/zeromq.js/releases/download/v5.2.0/zeromq-v5.2.0-electron-v80-darwin-x64.tar.gz
    prebuild-install http 404 https://github.com/zeromq/zeromq.js/releases/download/v5.2.0/zeromq-v5.2.0-electron-v80-darwin-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=9.4.2 runtime=electron arch=x64 libc= platform=darwin)
    
  • build native dependency from sources  name=zeromq
                                          version=4.6.0
                                          platform=darwin
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 2.5.3
    prebuild-install info looking for local prebuild @ prebuilds/zeromq-v4.6.0-electron-v80-darwin-x64.tar.gz
    prebuild-install info looking for cached prebuild @ /Users/wangyu/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.6.0-zeromq-v4.6.0-electron-v80-darwin-x64.tar.gz
    prebuild-install http request GET https://github.com/zeromq/zeromq.js/releases/download/v4.6.0/zeromq-v4.6.0-electron-v80-darwin-x64.tar.gz
    prebuild-install http 404 https://github.com/zeromq/zeromq.js/releases/download/v4.6.0/zeromq-v4.6.0-electron-v80-darwin-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=9.4.2 runtime=electron arch=x64 platform=darwin)
    
  • rebuilding native dependency  name=zeromq version=4.6.0
  • rebuilding native dependency  name=zeromq version=5.2.0
  ⨯ cannot execute  cause=exit status 1
                    out=yarn run v1.17.3
    $ node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
    
    prebuild-install WARN install No prebuilt binaries found (target=9.4.2 runtime=electron arch=x64 platform=darwin)
    
    Libzmq found, skipping rebuild.
      CXX(target) Release/obj.target/zmq/binding.o
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    
                    errorOut=gyp info it worked if it ends with ok
    gyp info using node-gyp@5.0.5
    gyp info using node@12.14.1 | darwin | x64
    gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
    gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
    gyp info spawn args [
    gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/wangyu/Desktop/workspace/aiot-electron-aisle/aiot-electron-aisle-next/node_modules/zerorpc/node_modules/zeromq/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/wangyu/.electron-gyp/9.4.2/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/Users/wangyu/.electron-gyp/9.4.2',
    gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/Users/wangyu/.electron-gyp/9.4.2/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/Users/wangyu/Desktop/workspace/aiot-electron-aisle/aiot-electron-aisle-next/node_modules/zerorpc/node_modules/zeromq',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    ../binding.cc:394:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
             ^
    ../../../../nan/nan.h:1026:3: note: 'MakeCallback' has been explicitly marked deprecated here
      NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      ^
    ../../../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../binding.cc:402:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
             ^
    ../../../../nan/nan.h:1026:3: note: 'MakeCallback' has been explicitly marked deprecated here
      NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      ^
    ../../../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../binding.cc:453:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 4, argv);
             ^
    ../../../../nan/nan.h:1026:3: note: 'MakeCallback' has been explicitly marked deprecated here
      NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      ^
    ../../../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../binding.cc:468:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 1, argv);
             ^
    ../../../../nan/nan.h:1026:3: note: 'MakeCallback' has been explicitly marked deprecated here
      NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      ^
    ../../../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../binding.cc:809:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
             ^
    ../../../../nan/nan.h:1026:3: note: 'MakeCallback' has been explicitly marked deprecated here
      NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      ^
    ../../../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../binding.cc:888:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
             ^
    ../../../../nan/nan.h:1026:3: note: 'MakeCallback' has been explicitly marked deprecated here
      NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      ^
    ../../../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../binding.cc:1295:34: error: no matching member function for call to 'Get'
          Local<Object> buf = batch->Get(i).As<Object>();
                              ~~~~~~~^~~
    /Users/wangyu/.electron-gyp/9.4.2/include/node/v8.h:3711:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
      V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                              ^
    /Users/wangyu/.electron-gyp/9.4.2/include/node/v8.h:3714:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
      V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                              ^
    ../binding.cc:1296:39: error: no matching member function for call to 'Get'
          Local<Number> flagsObj = batch->Get(i + 1).As<Number>();
                                   ~~~~~~~^~~
    /Users/wangyu/.electron-gyp/9.4.2/include/node/v8.h:3711:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
      V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                              ^
    /Users/wangyu/.electron-gyp/9.4.2/include/node/v8.h:3714:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
      V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                              ^
    6 warnings and 2 errors generated.
    make: *** [Release/obj.target/zmq/binding.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    gyp ERR! System Darwin 20.1.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/wangyu/Desktop/workspace/aiot-electron-aisle/aiot-electron-aisle-next/node_modules/zerorpc/node_modules/zeromq
    gyp ERR! node -v v12.14.1
    gyp ERR! node-gyp -v v5.0.5
    gyp ERR! not ok 
    error Command failed with exit code 1.
    
                    command=/usr/local/bin/node /usr/local/Cellar/yarn/1.17.3/libexec/bin/yarn.js run install
                    workingDir=/Users/wangyu/Desktop/workspace/aiot-electron-aisle/aiot-electron-aisle-next/node_modules/zerorpc/node_modules/zeromq
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

macOS 11.0.1(MBP2018)
electron v9.4.2
electron-builder v22.9.1
nodejs v12.14.1

run `yarn` in cmd，got this error.

I am not good at native packages, the following are my guesses

Since github does not have a corresponding platform binary package, the system starts to compile by itself, and then compile errors due to some problem（ps: electron v2.x is work）

thanks！！！

**Comment by blogwy** [comment]
😮‍💨

**Comment by blogwy** [comment]
The problem has not been solved, forget it. The project has been abandoned by the company
