### ISSUE TITLE
Auto updater throws error on checkForUpdatesAndNotify()

### ISSUE THREAD

**Issue by Chrisbright10** [electron-userland/electron-builder#5620]
* **Builder Version**: 22.9.1
* **Electron Version**: 11.2.3
* **Electron Type (current, beta, nightly)**: current
* **Electron Updater**: 4.3.5 (also tried 4.2.5 just in case)
* **Target**: win: nsis
* **Auto Updating Repo Type**: Github Private Repo

Logging reveals that the auto updater is throwing this issue when i attempt to check for updates

[2021-02-06 02:28:37.117] [error] Error: HttpError: 400 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>token 6e25a026e05393b88bc0292adeaa00d6867f4539</ArgumentValue><RequestId>9C17C52FC4BCEB5A</RequestId><HostId>/vD0Pp4bZNLrbTtoydiy8Junq8LixDno7OcdkDpq7nZz64e6o7gnp1RCaBBnCrWy7Q3LtisU9ro=</HostId></Error>"
Headers: {
  "x-amz-request-id": "9C17C52FC4BCEB5A",
  "x-amz-id-2": "/vD0Pp4bZNLrbTtoydiy8Junq8LixDno7OcdkDpq7nZz64e6o7gnp1RCaBBnCrWy7Q3LtisU9ro=",
  "content-type": "application/xml",
  "server": "AmazonS3",
  "accept-ranges": "bytes",
  "via": "1.1 varnish, 1.1 varnish",
  "date": "Sat, 06 Feb 2021 09:28:38 GMT",
  "x-served-by": "cache-dca17773-DCA, cache-pao17474-PAO",
  "x-cache": "MISS, MISS",
  "x-cache-hits": "0, 0",
  "strict-transport-security": "max-age=31536000",
  "x-fastly-request-id": "ac2272965423dbe4a5668aa875bb88258d70f499"
}
    at createHttpError (C:\Users\chris\AppData\Local\Programs\electron-test-app\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:84:10)
    at IncomingMessage.<anonymous> (C:\Users\chris\AppData\Local\Programs\electron-test-app\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:200:18)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

I created a test rig independent from my codebase from a tutorial and I still get this issue. I am not sure how to overcome it, it is blocking productions deployments.

** Note ** - I am using a private github repo to do the auto updating and I am not able to get the auto updating to work.

**Comment by Chrisbright10** [comment]
#5595
