### ISSUE TITLE
Apple Silicon can’t auto-update with Universal target

### ISSUE THREAD

**Issue by EtienneLem** [electron-userland/electron-builder#5639]
* **Version**: 22.10.4

* **Electron Version**: 11.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: Universal (macOS)

Getting a `Error: No files provided` error when trying to auto-update. A current workaround is to launch the app with Rosetta enabled, auto-update, disable Rosetta.

```
[2021-02-15 14:03:01.269] [info] Checking for update
[2021-02-15 14:03:02.638] [info] Found version 9.50.1 (url: App-9.50.1-mac.zip, App-9.50.1.dmg)
[2021-02-15 14:03:02.639] [info] Downloading update from App-9.50.1-mac.zip, App-9.50.1.dmg
[2021-02-15 14:03:02.640] [error] Error: Error: No files provided
    at newError (App.app/Contents/Resources/app-arm64.asar/node_modules/builder-util-runtime/out/index.js:212:17)
    at findFile (App.app/Contents/Resources/app-arm64.asar/node_modules/electron-updater/out/providers/Provider.js:111:46)
    at MacUpdater.doDownloadUpdate (App.app/Contents/Resources/app-arm64.asar/node_modules/electron-updater/out/MacUpdater.js:80:50)
    at MacUpdater.downloadUpdate (App.app/Contents/Resources/app-arm64.asar/node_modules/electron-updater/out/AppUpdater.js:577:19)
    at MacUpdater.doCheckForUpdates (App.app/Contents/Resources/app-arm64.asar/node_modules/electron-updater/out/AppUpdater.js:537:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

/cc @lutzroeder in case you have an idea since you implemented #5481

**Comment by lutzroeder** [comment]
Duplicate of #5495

**Comment by EtienneLem** [comment]
> Duplicate of #5495

Oh, is it? I did rename the artifacts as the workaround suggests in that issue. Had no problem migrating from Intel build to Universal.

Good to know if that's the same issue, it felt like a different one.

**Comment by lutzroeder** [comment]
The underlying issue is that `electron-updater` is hardcoded to probe for a file with a known name that has no architecture-specific (default) extension. There are many different ways to go about this. The #5495 change is to specify that the universal targets use the default extension (instead of `x64`).

**Comment by EtienneLem** [comment]
Understood! We’ll wait for the next preview release. Thanks 🤘🏼

**Comment by maoryadin** [comment]
Same issue, any way to make it work?
