### ISSUE TITLE
"no suitable image found" error under Apple Silicon when building a DMG with a license

### ISSUE THREAD

**Issue by ezzatron** [electron-userland/electron-builder#5677]
* **Version**: 22.10.5

* **Electron Version**: 12.0.0
* **Electron Type (current, beta, nightly)**: current

* **electron-updater Version**: 4.3.8

* **Target**: macOS / universal / DMG

When attempting to run a build on an Apple Silicon Mac, I currently get this error once the build reaches the `building embedded block map` step:

```
  • building embedded block map  file=path/to/Installer.zip
Error: dlopen(/path/to/node_modules/iconv-corefoundation/lib/native.node, 1): no suitable image found.  Did find:
  /path/to/node_modules/iconv-corefoundation/lib/native.node: mach-o, but wrong architecture
  /path/to/node_modules/iconv-corefoundation/lib/native.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/path/to/node_modules/iconv-corefoundation/lib/native.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/path/to/node_modules/iconv-corefoundation/lib/index.js:6:18)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
```

I've already opened [an issue](https://github.com/argv-minus-one/iconv-corefoundation/issues/2) on the `iconv-corefoundation` repo, but I thought you might also want to know that this is currently broken.

The dependency on `iconv-corefoundation` comes via `electron-builder` > `dmg-builder` > `dmg-license` > `iconv-corefoundation`, so I would assume that this only occurs when you are using a DMG license.

The issue persists regardless of whether I run `electron-builder` under Rosetta or not. I can't think of any other relevant details at the moment, but please let me know if you need more information about the machine etc.

**Comment by mmaietta** [comment]
@ezzatron opened PR for them to provide a universal `native.node` binary. We'll just have to pick it up once fixed upstream
https://github.com/argv-minus-one/iconv-corefoundation/pull/3

For the interim, you can use this patch to disable dmg-builder to unblock yourself (if you're not using a license file). I didn't test the impact, only just commented it out in case you wanted to give it a try.
`dmg-builder+22.10.5.patch`
```
diff --git a/node_modules/dmg-builder/out/dmgLicense.js b/node_modules/dmg-builder/out/dmgLicense.js
index fa922c6..76f16f5 100644
--- a/node_modules/dmg-builder/out/dmgLicense.js
+++ b/node_modules/dmg-builder/out/dmgLicense.js
@@ -25,16 +25,6 @@ function _jsYaml() {
   return data;
 }
 
-function _license() {
-  const data = require("app-builder-lib/out/util/license");
-
-  _license = function () {
-    return data;
-  };
-
-  return data;
-}
-
 function _fsExtra() {
   const data = require("fs-extra");
 
@@ -65,8 +55,9 @@ function _dmgLicense() {
   return data;
 }
 
+// import { getLicenseFiles } from "app-builder-lib/out/util/license"
 async function addLicenseToDmg(packager, dmgPath) {
-  const licenseFiles = await (0, _license().getLicenseFiles)(packager);
+  const licenseFiles = []; //await getLicenseFiles(packager)
 
   if (licenseFiles.length === 0) {
     return null;

```

**Comment by ezzatron** [comment]
@mmaietta Thank you! I'll have to give this a try on Monday if the upstream repo hasn't already merged by then 👍

**Comment by ezzatron** [comment]
Sorry, I guess I forgot to try that patch in the end. But the upstream repo has fixed the issue on their end, and I'm now able to successfully build a DMG under Apple Silicon 🎉
