### ISSUE TITLE
Error: The command is disabled and cannot be executed on quitAndInstall()

### ISSUE THREAD

**Issue by AdrianMrn** [electron-userland/electron-builder#5717]
* **Version**: 4.3.8
* **Electron Version**: 11.3.0
* **Electron Type (current, beta, nightly)**: current
* **Target**: Mac

I'm seeing this issue https://github.com/electron/electron/issues/7792, I've checked to make sure I'm not checking for updates multiple times. This issue popped up, seemingly out of nowhere. Nothing about our build process has changed in a while, and earlier versions worked fine.

The download works fine, and the update file itself is also fine. I'm not getting this issue on Windows or Linux for the same update.

I get this error in my console (manually running the app from the terminal) after running `autoUpdater.quitAndInstall();` (which I run in the callback of `autoUpdater.on('update-downloaded', …`).

```
09:48:41.981 › Error: The command is disabled and cannot be executed
    at u.quitAndInstall (/Users/…/app.asar/dist/main.js:113:133615)
    at /Users/…/app.asar/dist/main.js:367:24549
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

`autoUpdater.autoInstallOnAppQuit` is `true`, but the app also won't install on quit (without any error message, as far as I can see).

**Comment by AdrianMrn** [comment]
I managed to fix this, I think the issue was caused either by calling `event.preventDefault()` in `window.close()`, or by having `autoUpdater.autoInstallOnAppQuit = true;` when calling `autoUpdater.quitAndInstall();`.

So now, I run this when updating:
```js
autoUpdater.autoInstallOnAppQuit = false;
autoUpdater.quitAndInstall();
```

and changed my `mainWindow.on('close', …)` listener to this:
```js
mainWindow.on('close', (event) => {
    if (!autoUpdater.autoInstallOnAppQuit) {
        return;
    }

    event.preventDefault();
});
```

**Comment by AliasT** [comment]
https://github.com/electron/electron/issues/7792

**Comment by Kirezi** [comment]
@AdrianMrn I am facing the same issue,  do you mind sharing your autoUpdater.on('update-downloaded'). I have tried lots of suggestions and nothing seems to be working

**Comment by AdrianMrn** [comment]
@Kirezi 

```js
autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => {
    const dialogOpts = {
        type: 'info',
        buttons: ['Restart', 'Later'],
        title: 'Application Update',
        message: process.platform === 'win32' ? releaseNotes : releaseName,
        detail: `A new version (${event.version}) has been downloaded. Restart the app to apply the updates.`,
    };

    dialog.showMessageBox(dialogOpts).then((returnValue) => {
        if (returnValue.response === 0) {
            autoUpdater.autoInstallOnAppQuit = false;
            autoUpdater.quitAndInstall();
        }
    });
});
```

**Comment by vineet1984** [comment]
@AdrianMrn I tried your suggestion but still seeing this error on Mac with autoUpdater.checkForUpdates() in main.js.

"electron": "^21.2.0"
System configuration: MacOS Ventura 13.1
Node version: 18.13.0

Here's my main.js code:-

```
const { app, BrowserWindow, ipcMain, dialog, screen, Tray ,session, autoUpdater } = require('electron')
const os = require('node:os');
const log = require('electron-log');

log.info('Log from the main process');

autoUpdater.logger = log
autoUpdater.logger.transports.file.level = 'debug'

if (require('electron-squirrel-startup')) app.quit()

const macUrl = `${server}/update/osx_${os.arch()}/${app.getVersion()}`

autoUpdater.setFeedURL({
  url: macUrl
});

  let tray = null;
  mainWindow.on('minimize', function (event) {
    event.preventDefault();
    mainWindow.hide();
    tray = createTray();
  });

  mainWindow.on('restore', function (event) {
    mainWindow.maximize();
    mainWindow.show();
    tray?.destroy();  
  });

  mainWindow.on('close', (event) => {
    if (!autoUpdater.autoInstallOnAppQuit) {
        return;
    }

    event.preventDefault();
  });

app.whenReady().then(() => {
  createWindow()
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
  setInterval(() => {
    log.info('Checking for update: ' + macUrl);
    autoUpdater.checkForUpdates()
  }, 30000)
})

autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => {
  log.info('Update downloaded');
  const dialogOpts = {
    type: 'info',
    buttons: ['Restart', 'Later'],
    title: 'Application Update',
    detail:
      'A new version has been downloaded. Restart the application to apply the updates.',
  }

  dialog.showMessageBox(dialogOpts).then((returnValue) => {
    if (returnValue.response === 0) { 
      autoUpdater.autoInstallOnAppQuit = false;
      autoUpdater.quitAndInstall();
    }
  })
})
```

Any help would be appreciated.
