### ISSUE TITLE
Windows MSI target fails if icon not specified

### ISSUE THREAD

**Issue by rpatrick00** [electron-userland/electron-builder#5744]
* **Version**: 22.10.5

* **Electron Version**: 12.0.2
* **Electron Type (current, beta, nightly)**: release

* **Target**: windows msi

I have a simple electron-builder.yaml file to configure my installer builds:

```yaml
appId: com.oracle.weblogic.wkt-ui
productName: WebLogic Kubernetes Toolkit UI
copyright: Copyright (c) 2021, Oracle and/or its affiliates
extraFiles:
  - from: ../tools
    to: tools
directories:
  output: ../dist
win:
  target: msi
```

When I try to run the build, I get the error shown below.  Adding `icon: Placeholder.ico` to point to an ico file fixes the issue.  This behavior is different that other platforms where the Electron icon is found and used by default.

```
PS C:\Users\rpatrick\Projects\wktui\electron> npm run build:installer

> wktui@1.0.0 build:installer
> electron-builder --config electron-builder.yaml -w

  • electron-builder  version=22.10.5 os=6.3.9600
  • loaded configuration  file=C:\Users\rpatrick\Projects\wktui\electron\electron-builder.yaml
  • writing effective config  file=C:\Users\rpatrick\Projects\wktui\dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=12.0.2 appOutDir=C:\Users\rpatrick\Projects\wktui\dist\win-unpacked

  • Unpacking electron zip  zipPath=undefined
  • default Electron icon is used  reason=application icon is not set
  • building        target=MSI arch=x64 file=C:\Users\rpatrick\Projects\wktui\dist\WebLogic Kubernetes Toolkit UI 1.0.0.
msi
  ⨯ Exit code: 94. Command failed: C:\Users\rpatrick\AppData\Local\electron-builder\Cache\wix\wix-4.0.0.5512.2\light.exe
 -out C:\Users\rpatrick\Projects\wktui\dist\WebLogic Kubernetes Toolkit UI 1.0.0.msi -v -spdb -sw1076 -dappDir=C:\Users\
rpatrick\Projects\wktui\dist\win-unpacked -pedantic -wx project.wixobj
C:\Users\rpatrick\Projects\wktui\dist\__msi-x64\project.wxs(101) : error LGHT0094 : The identifier 'Icon:icon.ico' could
 not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linke
r.

WiX Toolset Linker version 4.0.0.5512
Copyright (c) .NET Foundation and contributors. All rights reserved.


C:\Users\rpatrick\Projects\wktui\dist\__msi-x64\project.wxs(101) : error LGHT0094 : The identifier 'Icon:icon.ico' could
 not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linke
r.
  stackTrace=
                                              Error: Exit code: 94. Command failed: C:\Users\rpatrick\AppData\Local\elec
tron-builder\Cache\wix\wix-4.0.0.5512.2\light.exe -out C:\Users\rpatrick\Projects\wktui\dist\WebLogic Kubernetes Toolkit
 UI 1.0.0.msi -v -spdb -sw1076 -dappDir=C:\Users\rpatrick\Projects\wktui\dist\win-unpacked -pedantic -wx project.wixobj

                                              C:\Users\rpatrick\Projects\wktui\dist\__msi-x64\project.wxs(101) : error L
GHT0094 : The identifier 'Icon:icon.ico' could not be found. Ensure you have typed the reference correctly and that all
the necessary inputs are provided to the linker.

                                              WiX Toolset Linker version 4.0.0.5512
                                              Copyright (c) .NET Foundation and contributors. All rights reserved.
                                              C:\Users\rpatrick\Projects\wktui\dist\__msi-x64\project.wxs(101) : error L
GHT0094 : The identifier 'Icon:icon.ico' could not be found. Ensure you have typed the reference correctly and that all
the necessary inputs are provided to the linker.

                                                  at C:\Users\rpatrick\Projects\wktui\electron\node_modules\builder-util
\src\util.ts:129:16
                                                  at ChildProcess.exithandler (child_process.js:315:5)
                                                  at ChildProcess.emit (events.js:315:20)
                                                  at maybeClose (internal/child_process.js:1048:16)
                                                  at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
PS C:\Users\rpatrick\Projects\wktui\electron>
```

**Comment by xcenai** [comment]
Having this same issue trying to build a windows msi on a linux platform.

**Comment by kburns2kb** [comment]
This is affecting my build as well. Help would be awesome on this

**Comment by sushan-shrestha** [comment]
Has anyone found any solution here I'm facing this issue too

**Comment by lonelyteapot** [comment]
I'm facing the same issue. This should not be closed

**Comment by pinko42** [comment]
I soved this issue by adding an icon key to the build object in packege.json file:

`
"build": {
    ...
    "icon": "mccoy.png",
    ...
}
`

**Comment by robatwilliams** [comment]
This is easily worked around by a developer, and they'll need to add an icon eventually anyway. But it's a bit unfriendly to throw this shortly after printing the message "default Electron icon is used  reason=application icon is not set".

The bot closed this as "completed" because nobody responded within a 7 day window a couple of years ago, but it's still a valid issue.
