### ISSUE TITLE
Electron builder failing on dmg

### ISSUE THREAD

**Issue by CaiIsProgrammer** [electron-userland/electron-builder#5771]
* **Version**: ^20.38.5

* **Electron Version**:^4.0.6
* **Electron Type (current, beta, nightly)**:current

^4.3.5

* **Target**: dmg

I was told to try and ask here but ive been at a loss and keep getting this error with no hope of fixing it. 
There is  
`Error: Exit code: 2. Command failed: /usr/bin/perl /private/tmp/t-fuQapm/1-dmgProperties.pl
Can't locate Mac/Finder/DSStore.pm in @INC (you may need to install the Mac::Finder::DSStore module) (@INC contains: /Library/Perl/5.28/darwin-thread-multi-2level /Library/Perl/5.28 /Network/Library/Perl/5.28/darwin-thread-multi-2level /Network/Library/Perl/5.28 /Library/Perl/Updates/5.28.2 /System/Library/Perl/5.28/darwin-thread-multi-2level /System/Library/Perl/5.28 /System/Library/Perl/Extras/5.28/darwin-thread-multi-2level /System/Library/Perl/Extras/5.28) at /private/tmp/t-fuQapm/1-dmgProperties.pl line 3.
BEGIN failed--compilation aborted at /private/tmp/t-fuQapm/1-dmgProperties.pl line 3.
 
Can't locate Mac/Finder/DSStore.pm in @INC (you may need to install the Mac::Finder::DSStore module) (@INC contains: /Library/Perl/5.28/darwin-thread-multi-2level /Library/Perl/5.28 /Network/Library/Perl/5.28/darwin-thread-multi-2level /Network/Library/Perl/5.28 /Library/Perl/Updates/5.28.2 /System/Library/Perl/5.28/darwin-thread-multi-2level /System/Library/Perl/5.28 /System/Library/Perl/Extras/5.28/darwin-thread-multi-2level /System/Library/Perl/Extras/5.28) at /private/tmp/t-fuQapm/1-dmgProperties.pl line 3.
BEGIN failed--compilation aborted at /private/tmp/t-fuQapm/1-dmgProperties.pl line 3.
 
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/builder-util/src/util.ts:126:16
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
From previous event:
    at _applyProperties (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/dmg-builder/out/dmgUtil.js:179:27)
    at applyProperties (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/dmg-builder/out/dmgUtil.js:166:27)
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/dmg-builder/src/dmg.ts:307:9
From previous event:
    at _customizeDmg (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/dmg-builder/out/dmg.js:458:24)
    at customizeDmg (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/dmg-builder/out/dmg.js:402:24)
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/dmg-builder/src/dmg.ts:48:54
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/dmg-builder/src/dmgUtil.ts:37:31
From previous event:
    at _attachAndExecute (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/dmg-builder/out/dmgUtil.js:120:28)
    at attachAndExecute (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/dmg-builder/out/dmgUtil.js:97:28)
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/dmg-builder/src/dmg.ts:48:16
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/macPackager.ts:91:26
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/macPackager.ts:91:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/macPackager.ts:82:95)
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
    at callback (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:184:5)
From previous event:
    at Packager.doBuild (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/graceful-fs/graceful-fs.js:144:16
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:171:23)
From previous event:
    at Packager._build (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Packager.build (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/electron-builder/src/builder.ts:228:10)
    at /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/electron-builder/src/cli/cli.ts:49:19`

**Comment by mmaietta** [comment]
Can you please try latest electron-builder 22.10.5?
Please report back if/what error message appears and also with what node version are you using.

**Comment by CaiIsProgrammer** [comment]
alright im on the latest version now and running node v14.16.0. now im just getting this error 
`$ /Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/.bin/electron-builder
  • electron-builder  version=22.10.5 os=20.3.0
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  • writing effective config  file=out/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=fsevents@1.2.13 platform=darwin arch=x64
  • rebuilding native dependency  name=fsevents version=1.2.13
  • packaging       platform=darwin arch=x64 electron=4.2.12 appOutDir=out/mac
  • Unpacking electron zip  zipPath=undefined
  • signing         file=out/mac/SYQEL-RADIO.app identityName=Developer ID Application: SYQEL LLC (6D929A586A) identityHash=F77E059EF6A24A79935603ECB6DF0CE55FDBCA57 provisioningProfile=none
  • building        target=macOS zip arch=x64 file=out/SYQEL-RADIO-2.4.0-mac.zip
  • building        target=DMG arch=x64 file=out/SYQEL-RADIO-2.4.0.dmg
  • Above command failed, retrying 5 more times
  • Above command failed, retrying 4 more times
  • Above command failed, retrying 3 more times
  • Above command failed, retrying 2 more times
  • Above command failed, retrying 1 more times
  • Above command failed, retrying 0 more times
  • building embedded block map  file=out/SYQEL-RADIO-2.4.0-mac.zip
  ⨯ hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                    Error: hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                        at ChildProcess.<anonymous> (/Users/caimartin/Desktop/Syqel/radio-desktop/node_modules/builder-util/src/util.ts:243:14)
                                                                        at Object.onceWrapper (events.js:422:26)
                                                                        at ChildProcess.emit (events.js:315:20)
                                                                        at maybeClose (internal/child_process.js:1048:16)
                                                                        at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)`

**Comment by mmaietta** [comment]
Hmmm, are you compiling DMG on M1 hardware?

**Comment by CaiIsProgrammer** [comment]
yes

**Comment by mmaietta** [comment]
Yeeeeup. That'll be fixed in the upcoming version
https://github.com/electron-userland/electron-builder/pull/5724

@develar can you please run a pre-release cut?

**Comment by CaiIsProgrammer** [comment]
@mmaietta when will this version release?

**Comment by develar** [comment]
@CaiIsProgrammer In 2 days.

**Comment by CaiIsProgrammer** [comment]
@develar Hey i dont see the new update yet on github is it updated on npm?

**Comment by yoavshalev** [comment]
Hi @mmaietta - curious if you had an updated ETA on this?
