### ISSUE TITLE
Cannot build with docker and electronuserland/builder:wine-mono image

### ISSUE THREAD

**Issue by Bartiff** [electron-userland/electron-builder#5783]
* **Version**: `22.10.5`
* **Electron Version**: `11.4.1`
* **Electron Type (current, beta, nightly)**: `current`
* **Target**: `squirrel`

Hi,

I am trying to build an .exe and a .nupkg for Windows on Linux. So I need Squirrel target and Mono.
I have a VM with [Homestead](https://laravel.com/docs/8.x/homestead) (with Ubuntu 18.04) on which I have installed **node** (v12.22.1), **wine** (wine-3.0 Ubuntu 3.0-1ubuntu1) and **mono** (6.12.0.122). And it works !

```
⠙  Bundling main process...

 DONE  Compiled successfully in 1286ms                                                                                         1:00:44 PM

  File                                   Size                                           Gzipped

  dist_electron/bundled/background.js    213.88 KiB                                     65.92 KiB

  Images and other types of assets omitted.

 INFO  Building app with electron-builder:
  • electron-builder  version=22.10.5 os=4.15.0-140-generic
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=11.4.1 appOutDir=dist_electron/win-unpacked
  • Unpacking electron zip  zipPath=undefined
  • building        target=Squirrel.Windows arch=x64 file=dist_electron/squirrel-windows/My APP 1.0.2.exe
  • building        target=nsis file=dist_electron/My APP 1.0.2.exe archs=x64 oneClick=true perMachine=false
  • building block map  blockMapFile=dist_electron/My APP 1.0.2.exe.blockmap
 DONE  Build complete!
 ```

Now I'm trying to build with docker (and docker-machine) and the electronuserland/builder:wine-mono image following the [documentation](https://www.electron.build/multi-platform-build#build-electron-app-using-docker-on-a-local-machine). 

I run my docker container like this :
```
docker run --rm -ti \
 --env ELECTRON_CACHE="/root/.cache/electron" \
 --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
 -v ${PWD}:/project \
 -v ~/.cache/electron:/root/.cache/electron \
 -v ~/.cache/electron-builder:/root/.cache/electron-builder \
 electronuserland/builder:wine-mono
```

But it doesn't work :(

```
⠙  Bundling main process...

 DONE  Compiled successfully in 1328ms                                                                                                                              2:16:56 PM

  File                                   Size                                                             Gzipped

  dist_electron/bundled/background.js    213.88 KiB                                                       65.92 KiB

  Images and other types of assets omitted.

 INFO  Building app with electron-builder:
  • electron-builder  version=22.10.5 os=4.19.130-boot2docker
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=11.4.1 appOutDir=dist_electron/win-unpacked
  • Unpacking electron zip  zipPath=undefined
  ⨯ cannot execute  cause=exit status 1
                    errorOut=000d:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
    000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
    0021:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    0021:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    0025:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    0025:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    0025:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
    0025:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
    0025:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
    000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    002b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
    002b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
    Could not find Wine Gecko. HTML rendering will be disabled.
    wine: configuration in L"/root/.wine" has been updated.
    0009:err:virtual:virtual_map_section mapping 0x710000 785a000 000000000 failed
    Fatal error: Unable to commit changes
    
                    command=wine /root/.cache/electron-builder/winCodeSign/winCodeSign-2.6.0/rcedit-ia32.exe '/project/dist_electron/win-unpacked/My APP.exe' --set-version-string FileDescription 'My APP' --set-version-string ProductName 'My APP' --set-version-string LegalCopyright 'Copyright © 2021 Company' --set-file-version 1.0.2 --set-product-version 1.0.2.0 --set-version-string InternalName 'My APP' --set-version-string OriginalFilename '' --set-version-string CompanyName Company --set-icon /project/public/icon_app_win.ico
                    workingDir=
  • Above command failed, retrying 3 more times
  ⨯ cannot execute  cause=exit status 1
                    errorOut=000d:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
    000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
    0009:err:virtual:virtual_map_section mapping 0x710000 785a000 000000000 failed
    Fatal error: Unable to commit changes
    
                    command=wine /root/.cache/electron-builder/winCodeSign/winCodeSign-2.6.0/rcedit-ia32.exe '/project/dist_electron/win-unpacked/My APP.exe' --set-version-string FileDescription 'My APP' --set-version-string ProductName 'My APP' --set-version-string LegalCopyright 'Copyright © 2021 Company' --set-file-version 1.0.2 --set-product-version 1.0.2.0 --set-version-string InternalName 'My APP' --set-version-string OriginalFilename '' --set-version-string CompanyName Company --set-icon /project/public/icon_app_win.ico
                    workingDir=
  • Above command failed, retrying 2 more times
  ⨯ cannot execute  cause=exit status 1
                    errorOut=000d:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
    000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
    0009:err:virtual:virtual_map_section mapping 0x710000 785a000 000000000 failed
    Fatal error: Unable to commit changes
    
                    command=wine /root/.cache/electron-builder/winCodeSign/winCodeSign-2.6.0/rcedit-ia32.exe '/project/dist_electron/win-unpacked/My APP.exe' --set-version-string FileDescription 'My APP' --set-version-string ProductName 'My APP' --set-version-string LegalCopyright 'Copyright © 2021 Company' --set-file-version 1.0.2 --set-product-version 1.0.2.0 --set-version-string InternalName 'My APP' --set-version-string OriginalFilename '' --set-version-string CompanyName Company --set-icon /project/public/icon_app_win.ico
                    workingDir=
  • Above command failed, retrying 1 more times
  ⨯ cannot execute  cause=exit status 1
                    errorOut=000d:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
    000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
    0009:err:virtual:virtual_map_section mapping 0x710000 785a000 000000000 failed
    Fatal error: Unable to commit changes
    
                    command=wine /root/.cache/electron-builder/winCodeSign/winCodeSign-2.6.0/rcedit-ia32.exe '/project/dist_electron/win-unpacked/My APP.exe' --set-version-string FileDescription 'My APP' --set-version-string ProductName 'My APP' --set-version-string LegalCopyright 'Copyright © 2021 Company' --set-file-version 1.0.2 --set-product-version 1.0.2.0 --set-version-string InternalName 'My APP' --set-version-string OriginalFilename '' --set-version-string CompanyName Company --set-icon /project/public/icon_app_win.ico
                    workingDir=
  • Above command failed, retrying 0 more times
ExecError: /project/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/project/node_modules/builder-util/src/util.ts:243:14)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
From previous event:
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at WinPackager.signApp (/project/node_modules/app-builder-lib/src/winPackager.ts:357:27)
    at WinPackager.doSignAfterPack (/project/node_modules/app-builder-lib/src/platformPackager.ts:270:16)
    at WinPackager.doPack (/project/node_modules/app-builder-lib/src/platformPackager.ts:255:7)
    at WinPackager.pack (/project/node_modules/app-builder-lib/src/platformPackager.ts:115:5)
    at Packager.doBuild (/project/node_modules/app-builder-lib/src/packager.ts:434:9)
    at executeFinally (/project/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/project/node_modules/app-builder-lib/src/packager.ts:369:31)
    at Packager.build (/project/node_modules/app-builder-lib/src/packager.ts:333:12)
    at executeFinally (/project/node_modules/builder-util/src/promise.ts:12:14) {
  exitCode: 2,
  alreadyLogged: true,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@1.0.2 electron:buildwin: `vue-cli-service electron:build --windows`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app@1.0.2 electron:buildwin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-09T14_17_26_578Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@1.0.2 electron:buildall: `sh ./bin/build.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app@1.0.2 electron:buildall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/company/.npm/_logs/2021-04-09T14_17_26_725Z-debug.log
```

I'd be interested to hear our ideas. ;)

**Comment by mmaietta** [comment]
I wonder if that'll be fixed by this PR? https://github.com/electron-userland/electron-builder/pull/5722

**Comment by Bartiff** [comment]
Ok that would be good! 
Do you think it will be released soon?

**Comment by mmaietta** [comment]
I certainly hope so 😅 

I don't have access to those controls. Or if I do, I have no idea where that "button" is.
