### ISSUE TITLE
Error on Apple Silicon

### ISSUE THREAD

**Issue by vitalyster** [electron-userland/electron-builder#5816]
> electron-builder  version=22.10.5
> Cannot spawn /node_modules/app-builder-bin/mac/app-builder: Error: spawn Unknown system error -86

**Comment by mmaietta** [comment]
Can you please run with `DEBUG=electron-builder` set so that we can have more logs here?

**Comment by LinusU** [comment]
@mmaietta 

```sh
$ DEBUG=electron-builder electron-builder install-app-deps
  • electron-builder  version=22.10.5
  • loaded configuration  file=package.json ("build" field)
  • spawning        command=/Users/linus/coding/dbgate/app/node_modules/app-builder-bin/mac/app-builder node-dep-tree --dir /Users/linus/coding/dbgate/app
  ⨯ Cannot spawn /Users/linus/coding/dbgate/app/node_modules/app-builder-bin/mac/app-builder: Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at spawn (node:child_process:609:9)
    at doSpawn (/Users/linus/coding/dbgate/app/node_modules/builder-util/src/util.ts:170:12)
    at /Users/linus/coding/dbgate/app/node_modules/builder-util/src/util.ts:359:28
    at new Promise (<anonymous>)
    at runCommand (/Users/linus/coding/dbgate/app/node_modules/builder-util/src/util.ts:358:12)
    at executeAppBuilder (/Users/linus/coding/dbgate/app/node_modules/builder-util/src/util.ts:377:12)
    at executeAppBuilderAsJson (/Users/linus/coding/dbgate/app/node_modules/app-builder-lib/src/util/appBuilder.ts:5:10)
    at Lazy.creator (/Users/linus/coding/dbgate/app/node_modules/app-builder-lib/src/util/packageDependencies.ts:12:12)
    at Lazy.get value [as value] (/Users/linus/coding/dbgate/app/node_modules/lazy-val/src/main.ts:18:25)
```

My guess is that `node_modules/app-builder-bin/mac/app-builder` is an Intel only binary, investigating further now...

**Comment by LinusU** [comment]
That was indeed the issue, filed an upstream issue report here: https://github.com/develar/app-builder/issues/56

**Comment by LinusU** [comment]
This is still relevant...

The upstream issue haven't gotten any feedback though: https://github.com/develar/app-builder/issues/56

**Comment by mmaietta** [comment]
Hmmm, I just tested this on my M1 and it seems to have worked correctly. Maybe this is an env issue, such as requiring Rosetta installed? I'm quite puzzled on the error here ¯\_(ツ)_/¯. Can you create a minimum reproducible gist or repo and I can test it locally and maybe provide a workaround for you.
```
<dir>/node_modules/.bin/electron-builder install-app-deps --arch arm64
  • electron-builder  version=22.10.5
  • loaded configuration  file=<dir>/electron-builder.js
  • rebuilding native dependencies  dependencies=electron-deeplink@1.0.6, node-mac-permissions@2.2.0 platform=darwin arch=arm64
  • rebuilding native dependency  name=electron-deeplink version=1.0.6
  • rebuilding native dependency  name=node-mac-permissions version=2.2.0
✨  Done in 20.20s.
```
```
<dir>/node_modules/.bin/electron-builder install-app-deps --arch x64
  • electron-builder  version=22.10.5
  • loaded configuration  file=<dir>/electron-builder.js
  • rebuilding native dependencies  dependencies=electron-deeplink@1.0.6, node-mac-permissions@2.2.0 platform=darwin arch=x64
  • rebuilding native dependency  name=electron-deeplink version=1.0.6
  • rebuilding native dependency  name=node-mac-permissions version=2.2.0
✨  Done in 6.73s.
```

**Comment by LinusU** [comment]
> such as requiring Rosetta installed

Sorry, should probably have specified that earlier. I do not have Rosetta available (and thus cannot run Intel binaries) and my goal is to have this working without Rosetta.

The issue is blocked on app-builder only shipping Intel binaries. It's written in Go so it _should_ be quite straight forward to compile it for arm64 as well, I just haven't had time to work on it...

**Comment by vitalyster** [comment]
Still relevant. please reopen

**Comment by kuncevic** [comment]
Caught that here https://github.com/FreeTubeApp/FreeTube/issues/2054
