### ISSUE TITLE
 Cannot download differentially, fallback to full download: Error: invalid block type

### ISSUE THREAD

**Issue by geolffreym** [electron-userland/electron-builder#5820]
Hi guys, same problem here using Ubuntu Linux distro. Which version can i use that it working? This is an issue related to zlib?
```
 Cannot download differentially, fallback to full download: Error: invalid block type
    at Zlib.zlibOnError [as onerror] (zlib.js:181:17)
    at processChunkSync (zlib.js:430:12)
    at zlibBufferSync (zlib.js:169:12)
    at syncBufferWrapper (zlib.js:764:14)
    at readBlockMap (/tmp/.mount_watchiuK0hmD/resources/app.asar/node_modules/electron-updater/out/differentialDownloader/FileWithEmbeddedBlockMapDifferentialDownloader.js:53:48)
    at FileWithEmbeddedBlockMapDifferentialDownloader.download (/tmp/.mount_watchiuK0hmD/resources/app.asar/node_modules/electron-updater/out/differentialDownloader/FileWithEmbeddedBlockMapDifferentialDownloader.js:44:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.task (/tmp/.mount_watchiuK0hmD/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:138:11)
    at async AppImageUpdater.executeDownload (/tmp/.mount_watchiuK0hmD/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:754:7)
    at async AppImageUpdater.<anonymous> (/tmp/.mount_watchiuK0hmD/resources/app.asar/src/main/index.js:167:5)
```

_Originally posted by @geolffreym in https://github.com/electron-userland/electron-builder/issues/5755#issuecomment-815978567_

**Comment by geolffreym** [comment]
@develar would somebody help me with this?
