### ISSUE TITLE
NoSuchLanguageError: No known languages found for specification English.

### ISSUE THREAD

**Issue by meydominic** [electron-userland/electron-builder#5834]
* **Version**: 22.10.5

* **Electron Version**: 8.5.5
* **Electron Type (current, beta, nightly)**:

* **Target**: macOS

If I try to build our application with electron-builder it fails with the following exception:
```
  ⨯ No known languages found for specification English.  stackTrace=
                                                           NoSuchLanguageError: No known languages found for specification English.
                                                               at Function.bySpec (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/Language.js:35:19)
                                                               at Object.indexByLanguage (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/Language.js:81:41)
                                                               at labelCache (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/assembleLicenses.js:92:35)
                                                               at Object.assembleLicenses [as default] (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/assembleLicenses.js:117:23)
                                                               at dmgLicensePlist (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/index.js:27:78)
                                                               at dmgLicense (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/index.js:21:62)
                                                               at dmgLicenseFromJSON (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/index.js:37:18)
                                                               at addLicenseToDmg (/Users/dmey/workspace/drive/node_modules/dmg-builder/src/dmgLicense.ts:57:9)
```

The exact same configuration is working on a workmates device.

We have a `license_de.rtf`, `license_en.rtf`, `licenseButtons_de.json` and a `licenseButtons_en.json` in our build directory.

Thanks for your help,
best regards,
Dominic

**Comment by meydominic** [comment]
?

**Comment by mmaietta** [comment]
Just to confirm. Does your workmate have the same electron-builder configuration with the same files?
Can you share a minimum reproducing repro/gist for me to help debug this further?

**Comment by mmaietta** [comment]
I'm honestly not familiar with the dependency we use, dmg-license, but just a random shot in the dark. Can you try only adding the license file language `en` and skip `de`? Another test I'd recommend is trying to use an empty `txt` file instead of `rtf`. I'm just thinking of edge cases where the file read could be failing as I feel like I've seen this error message in the past, I think when fixing some tests

**Comment by meydominic** [comment]
Interesting, I removed the en files and then got this error:
```
  ⨯ No known languages found for specification Deutsch.  stackTrace=
                                                           NoSuchLanguageError: No known languages found for specification Deutsch.
                                                               at Function.bySpec (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/Language.js:35:19)
                                                               at Object.indexByLanguage (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/Language.js:81:41)
                                                               at labelCache (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/assembleLicenses.js:92:35)
                                                               at Object.assembleLicenses [as default] (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/assembleLicenses.js:117:23)
                                                               at dmgLicensePlist (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/index.js:27:78)
                                                               at dmgLicense (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/index.js:21:62)
                                                               at dmgLicenseFromJSON (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/index.js:37:18)
                                                               at addLicenseToDmg (/Users/dmey/workspace/drive/node_modules/dmg-builder/src/dmgLicense.ts:57:9)
```

Then I renamed license_de.rtf to .txt but I got the same error.

This is nearly the complete output:

```
dmey@DominicysNeuMBP drive % npm run electron:mac

> plentydevtool@1.2.1 electron:mac /Users/dmey/workspace/drive
> npm run build:prod && electron-builder build --mac


> plentydevtool@1.2.1 build:prod /Users/dmey/workspace/drive
> npm run build -- -c production


> plentydevtool@1.2.1 build /Users/dmey/workspace/drive
> npm run postinstall:electron && npm run electron:serve-tsc && ng build "-c" "production"


> plentydevtool@1.2.1 postinstall:electron /Users/dmey/workspace/drive
> node postinstall


> plentydevtool@1.2.1 electron:serve-tsc /Users/dmey/workspace/drive
> tsc -p tsconfig-serve.json


chunk {0} runtime.7d9d4678f9511567f211.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.21f0f1821facaee65217.js (main) 570 kB [initial] [rendered]
chunk {2} polyfills.9e5f02ddbbe9b6461c4d.js (polyfills) 49.2 kB [initial] [rendered]
chunk {3} polyfills-es5.eb63c25cb41d86c8c54e.js (polyfills-es5) 132 kB [initial] [rendered]
chunk {4} styles.8305ff6fc08b218356e9.css (styles) 168 kB [initial] [rendered]
Date: 2021-05-09T17:24:03.996Z - Hash: 1397b09476e601b40528 - Time: 19674ms
  • electron-builder  version=22.10.5 os=20.4.0
  • loaded configuration  file=/Users/dmey/workspace/drive/electron-builder.json
  • writing effective config  file=release/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=8.5.5 appOutDir=release/mac
  • Unpacking electron zip  zipPath=undefined
  • signing         xxxxxx
  • building        target=DMG arch=x64 file=release/PlentyDevTool-1.2.1.dmg
  • building        target=macOS zip arch=x64 file=release/PlentyDevTool-1.2.1-mac.zip
  • building embedded block map  file=release/PlentyDevTool-1.2.1-mac.zip
  ⨯ No known languages found for specification Deutsch.  stackTrace=
                                                           NoSuchLanguageError: No known languages found for specification Deutsch.
                                                               at Function.bySpec (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/Language.js:35:19)
                                                               at Object.indexByLanguage (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/Language.js:81:41)
                                                               at labelCache (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/assembleLicenses.js:92:35)
                                                               at Object.assembleLicenses [as default] (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/assembleLicenses.js:117:23)
                                                               at dmgLicensePlist (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/index.js:27:78)
                                                               at dmgLicense (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/index.js:21:62)
                                                               at dmgLicenseFromJSON (/Users/dmey/workspace/drive/node_modules/dmg-license/lib/index.js:37:18)
                                                               at addLicenseToDmg (/Users/dmey/workspace/drive/node_modules/dmg-builder/src/dmgLicense.ts:57:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plentydevtool@1.2.1 electron:mac: `npm run build:prod && electron-builder build --mac`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the plentydevtool@1.2.1 electron:mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dmey/.npm/_logs/2021-05-09T17_25_05_733Z-debug.log

```

Output of the log:
```
dmey@DominicysNeuMBP drive % cat /Users/dmey/.npm/_logs/2021-05-09T17_25_05_733Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/Users/dmey/.nvm/versions/node/v10.24.1/bin/node',
1 verbose cli   '/Users/dmey/.nvm/versions/node/v10.24.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'electron:mac' ]
2 info using npm@6.14.12
3 info using node@v10.24.1
4 verbose run-script [ 'preelectron:mac', 'electron:mac', 'postelectron:mac' ]
5 info lifecycle plentydevtool@1.2.1~preelectron:mac: plentydevtool@1.2.1
6 info lifecycle plentydevtool@1.2.1~electron:mac: plentydevtool@1.2.1
7 verbose lifecycle plentydevtool@1.2.1~electron:mac: unsafe-perm in lifecycle true
8 verbose lifecycle plentydevtool@1.2.1~electron:mac: PATH: /Users/dmey/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dmey/workspace/drive/node_modules/.bin:/Users/dmey/.nvm/versions/node/v10.24.1/bin:/usr/local/opt/ruby/bin:/Users/dmey/.gem/ruby/2.6.0/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/dmey/workspace/flutter/bin:/Users/dmey/.jenv/shims:/Users/dmey/Downloads/gwt-2.7.0:/Users/dmey/.jenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Users/dmey/Library/Android/sdk/platform-tools:/Users/dmey/Library/Android/sdk/tools
9 verbose lifecycle plentydevtool@1.2.1~electron:mac: CWD: /Users/dmey/workspace/drive
10 silly lifecycle plentydevtool@1.2.1~electron:mac: Args: [ '-c', 'npm run build:prod && electron-builder build --mac' ]
11 silly lifecycle plentydevtool@1.2.1~electron:mac: Returned: code: 1  signal: null
12 info lifecycle plentydevtool@1.2.1~electron:mac: Failed to exec electron:mac script
13 verbose stack Error: plentydevtool@1.2.1 electron:mac: `npm run build:prod && electron-builder build --mac`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/dmey/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/dmey/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid plentydevtool@1.2.1
15 verbose cwd /Users/dmey/workspace/drive
16 verbose Darwin 20.4.0
17 verbose argv "/Users/dmey/.nvm/versions/node/v10.24.1/bin/node" "/Users/dmey/.nvm/versions/node/v10.24.1/bin/npm" "run" "electron:mac"
18 verbose node v10.24.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error plentydevtool@1.2.1 electron:mac: `npm run build:prod && electron-builder build --mac`
22 error Exit status 1
23 error Failed at the plentydevtool@1.2.1 electron:mac script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by meydominic** [comment]
One thing I can test, my workmates device is set to english, mine to german. Because the error message is saying 'Deutsch' in the last error. I'll switch to english and test again.

**Comment by meydominic** [comment]
It looks like that your documentation is not valid anymore?
https://www.electron.build/configuration/dmg

**Comment by argv-minus-one** [comment]
`dmg-license` only recognizes [a limited set of language tags](https://github.com/argv-minus-one/dmg-license/blob/master/docs/Supported%20Language%20Tags.md), because those exact language tags correspond to the Classic Mac OS numeric language codes supported by Apple's `dmg` license format. Trying to use any other language tag, such as `en` or `de`, will result in the error above.

So, try naming your license file something like `license_de-de.rtf` (for German in RTF format) or `license_en-us.txt` (for US English in plain text format).

I notice that that the `electron-builder` documentation links to [this list of language tags](https://github.com/meikidd/iso-639-1/blob/master/src/data.js). Again, `dmg-license` won't recognize most of those. The `electron-builder` documentation should probably link to [the list of language tags supported by `dmg-license`](https://github.com/argv-minus-one/dmg-license/blob/master/docs/Supported%20Language%20Tags.md) instead.

**Comment by argv-minus-one** [comment]
@meydominic That's strange. I notice the error says `English` rather than `en-us`, so `electron-builder` must be feeding `dmg-license` the string `English` instead of a language tag. No idea why that's happening. I looked at [the code responsible](https://github.com/electron-userland/electron-builder/blob/79940292bdd1a5de45b33453be492ea67529434b/packages/dmg-builder/src/dmgLicense.ts#L17) and it appears to correctly pass a language tag like `en-us`, not a language name like `English`.

---

According to the stack trace, `dmg-license` is rejecting the supplied language tag for the `licenseButtons` files. [The language tag for a `licenseButtons` file is inferred from the file name](https://github.com/electron-userland/electron-builder/blob/79940292bdd1a5de45b33453be492ea67529434b/packages/dmg-builder/src/dmgLicense.ts#L51), but it looks like you can override it in JSON.

Try adding `"lang": "de-de"` to the root object in `licenseButtons_de-de.json` and `"lang": "en-us"` to `licenseButtons_en-us.json`.

However, this probably won't work. The language tags for `license_de-de.rtf` and `license_en-us.rtf` are inferred from the file name the same way as for the `licenseButtons` files, and unlike the `licenseButtons` files, there's no way to override the language tag for the license text files. I expect you'll just get the same error message with a slightly different stack trace.

---

You say the exact same configuration works on a different device. In that case, I wonder what's different between the two devices. Is an old version of some JavaScript module being loaded instead of the correct one?

I take it you installed `electron-builder` using `npm install -g`? What if you try reinstalling it with `npm uninstall -g electron-builder && rm -rf /Users/dmey/.nvm/versions/node/v12.22.1/lib/node_modules/electron-builder && npm install -g electron-builder@22.10.5`—does that fix it?

What if you clone a fresh copy of your project and build that? Does that work?

If that doesn't work, maybe also try completely deleting and reinstalling Node. That *probably* won't help, but you may as well try.

---

I'm going to see if I can get ahold of a Mac (I don't have one right now) and reproduce your problem, but if it works on your workmate's Mac then I'm not hopeful; it'll probably work on my Mac too.

I know it's hard to prepare a minimal working example of the bug you're experiencing, but if the above suggestions don't work for you, then that may be our only hope of figuring it out.

**Comment by meydominic** [comment]
I'll try your suggestions and report back, thanks.

We had a meeting about this problem and we found out, that we have some difference. So it's my fault. I didn't say anything about the new information.

My workmate is using macOS Catalina with an older version of electron-builder, which is not using dmg-license.

**Comment by meydominic** [comment]
> Try adding `"lang": "de-de"` to the root object in `licenseButtons_de-de.json` and `"lang": "en-us"` to `licenseButtons_en-us.json`.

Result:
```
  ⨯ No known languages found for specification en-us-EN-US.  failedTask=build stackTrace=NoSuchLanguageError: No known languages found for specification en-us-EN-US.
    at Function.bySpec (/Users/dmey/.nvm/versions/node/v12.22.1/lib/node_modules/electron-builder/node_modules/dmg-license/lib/Language.js:35:19)
    at Object.indexByLanguage (/Users/dmey/.nvm/versions/node/v12.22.1/lib/node_modules/electron-builder/node_modules/dmg-license/lib/Language.js:81:41)
    at Object.assembleLicenses [as default] (/Users/dmey/.nvm/versions/node/v12.22.1/lib/node_modules/electron-builder/node_modules/dmg-license/lib/assembleLicenses.js:118:31)
    at dmgLicensePlist (/Users/dmey/.nvm/versions/node/v12.22.1/lib/node_modules/electron-builder/node_modules/dmg-license/lib/index.js:27:78)
    at dmgLicense (/Users/dmey/.nvm/versions/node/v12.22.1/lib/node_modules/electron-builder/node_modules/dmg-license/lib/index.js:21:62)
    at Object.dmgLicenseFromJSON (/Users/dmey/.nvm/versions/node/v12.22.1/lib/node_modules/electron-builder/node_modules/dmg-license/lib/index.js:37:18)
    at Object.addLicenseToDmg (/Users/dmey/.nvm/versions/node/v12.22.1/lib/node_modules/electron-builder/node_modules/dmg-builder/src/dmgLicense.ts:59:9)
    at DmgTarget.build (/Users/dmey/.nvm/versions/node/v12.22.1/lib/node_modules/electron-builder/node_modules/dmg-builder/src/dmg.ts:73:25)
```

Then I removed "lang" from both json because I thought it'll concatenate them but the result is exactly the same stacktrace.

**Comment by argv-minus-one** [comment]
I borrowed a Mac and successfully reproduced your problem.

## Problems

There are two things going on here:

1. The `licenseButtons` property `lang` is supposed to be a language *tag* (like `en-us`), but the documentation says to put a language *name* (like `English`) there. Doing this results in the error message you originally reported: `No known languages found for specification English.` I've opened issue #5887 about that.
2. The code that parses the language tag out of your file name doesn't work correctly if you put a dash in it (as in `languageButtons_en-us.json`). `electron-builder` expects an *underscore* between the language and country (as in `languageButtons_en_us.json`), presumably for backward compatibility reasons. Putting a dash there results in the error message you reported just now: `No known languages found for specification en-us-EN-US.`

## Solutions

* Remove the `lang` property from all `licenseButtons` files. It's not needed with `electron-builder` and can only cause confusion.
* Rename all license files such that the language tag contains only underscores, not dashes: `license_en_us.rtf`, `licenseButtons_en_us.json`, `license_de_de.rtf`, `licenseButtons_de_de.json`.

## Giving a Language Name

You *can* give a language *name* in the `licenseButtons` file (though it's optional, except for languages marked "requires `languageName`" in [the list](https://github.com/argv-minus-one/dmg-license/blob/master/docs/Supported%20Language%20Tags.md)). It goes in the `languageName` property, not `lang`. Example:

```json
{
  "languageName": "English, do you speak it",
  "agree": "Agree",
  "disagree": "Disagree",
  "print": "Print",
  "save": "Save",
  "description": "Here is my own description"
}
```

However, I don't think current macOS actually displays the language name anywhere. It still expects a language name to appear in the DMG metadata, but there probably isn't any benefit in providing a `languageName` unless it's required.

## `licenseButtons` Are Optional

For several languages, including both US English and German, you don't actually have to provide a `licenseButtons` file at all. For any language marked as having "predefined labels" in [the list](https://github.com/argv-minus-one/dmg-license/blob/master/docs/Supported%20Language%20Tags.md), those predefined labels will be used if you don't provide your own.

**Comment by meydominic** [comment]
Wow... What a response... Thank you so much.

Will try it tomorrow and report back.

Thanks and best regards,
Dominic

**Comment by meydominic** [comment]
Many thanks @argv-minus-one ,
your solution works fine :)
