### ISSUE TITLE
Signing (signcode-tf) failed on Windows 7 when SHA256 hash algorithm is used

### ISSUE THREAD

**Issue by djpereira** [electron-userland/electron-builder#584]
When I try to run build -w under Windows 7, the signcode-tf library fails as you can see below, when you try to sign using SHA256 **only**.

@develar this is similar to #581, however it fails with a different error with a single hash algorithm, if that algorithm happens to be SHA256. It works well with SHA1 under Windows 7 with both the Signtool.exe under the windows-6 folder and the one under the windows-10 folder.

electron-builder v5.12.1
target: Windows.

```
Signing My App.exe (certificate file "build/win.p12")
spawning C:\myfolder\node_modules\electron-builder\node_modules\signcode-tf\vendor\windows-6\sig
ntool.exe sign /tr http://timestamp.comodoca.com/rfc3161 /f build/win.p12 /fd sha256 /td sha256 /d My App /du http
s://www.myurl.com/ /p PASSWORD C:\myfolder\dist\win-unpacked\My App.exe
Error: Signing failed with 3221225477
    at Error (native)
    at ChildProcess.<anonymous> (C:\myfolder\node_modules\electron-builder\node_modules\signcode
-tf\index.js:155:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at WinPackager.<anonymous> (C:\myfolder\node_modules\electron-builder\src\winPackager.ts:132
:43)
    at next (native)
From previous event:
    at tsAwaiter (C:\myfolder\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at Object.build (C:\myfolder\node_modules\electron-builder\src\builder.ts:192:52)
    at Object.<anonymous> (C:\myfolder\node_modules\electron-builder\src\build-cli.ts:27:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by djpereira** [comment]
@develar please check https://github.com/develar/signcode/pull/3 for a fix.
