### ISSUE TITLE
Linux, Bug, Docs. executableName does not produce result according to docs

### ISSUE THREAD

**Issue by kroko** [electron-userland/electron-builder#5848]
* **Version**: 22.10.5

* **Electron Version**: 12.0.5
* **Electron Type (current, beta, nightly)**: Current

* **Target**: linux, AppImage

The [docs state](https://www.electron.build/configuration/linux) that 
> `executableName` String - The executable name. Defaults to `productName`. Cannot be specified per target, allowed only in the `linux`.

However, the produced executable has name of package.json `name`, not `productName`

Thus

_package.json_

```json
{
  "name": "bwleee-app-electron",
  "productName": "BeautifulName"
}
```

will produce executable `bwleee-app-electron`.

Meanwhile, explicitly setting executableName works.

_.electron-builder.config.js_

```js
const pkg = require(path.resolve(__dirname, 'package.json'));
// ...

  linux: {
    // https://github.com/electron/electron/issues/28956
    executableName: pkg.productName,
   // ...
  }
```

Related

https://github.com/electron-userland/electron-builder/pull/5409

Sideffects

https://github.com/electron/electron/issues/28956  
Most DEs for apps that use Tray produces tooltips. Assume that tooltip is not programmatically overridden in app - in that case tooltip text would be the same as executable name. Having cryptic executable name (package.json `name` is more likely to be cryptic and has to follow strict rules, `productName` is more likely to be something human readable) results in an sideffect.

Actually IMHO having it to default to `productName` would open other sideffects, the observed behaviour where it uses `name` is OK, docs just need correction.

> `executableName` String - The executable name. Defaults to `name`. Cannot be specified per target, allowed only in the `linux`.

**Comment by mmaietta** [comment]
Thanks for calling that out. Would you be willing to open a PR to update those docs?
It's located on the `docs` branch
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#documentation

**Comment by kroko** [comment]
@mmaietta well, given that i have spent two months each day working on an app i can say - docs are full of bugs / non updated stuff. one has to read source. or knowingly create invalid configuration so the builder will throw and report the correct schema is an option.

now I see why - to contribute one must pip3, manualy copy mkdocs.yml, edit it, mkdocs build. i'm not bashing, just yeah.. it produces things like below.

fails as mkdocs throws.

```
╭─reinis@warp-node-03.warp ~/Downloads/electron-builder
╰─➤  pip3 list
Package                    Version
-------------------------- --------
click                      7.1.2
future                     0.18.2
Jinja2                     2.11.3
joblib                     1.0.1
livereload                 2.6.3
lunr                       0.5.8
Markdown                   3.3.4
markdown-include           0.6.0
MarkupSafe                 1.1.1
mkdocs                     1.1.2
mkdocs-material            7.1.3
mkdocs-material-extensions 1.0.1
nltk                       3.6.2
pip                        21.0.1
Pygments                   2.9.0
pymdown-extensions         8.1.1
PyYAML                     5.4.1
regex                      2021.4.4
setuptools                 54.1.2
six                        1.15.0
TBB                        0.1
tornado                    6.1
tqdm                       4.60.0
wheel                      0.36.2
```

```
╭─reinis@warp-node-03.warp ~/Downloads/electron-builder
╰─➤  mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /Users/reinis/Downloads/electron-builder/site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - generated/DebOptions.md
  - generated/LinuxTargetSpecificOptions.md
  - generated/Metadata.md
  - generated/NsisOptions.md
  - generated/PlatformSpecificBuildOptions.md
  - generated/TargetSpecificOptions.md
  - generated/appimage-options.md
  - generated/s3-options.md
  - generated/snap-store-options.md
  - generated/spaces-options.md
  - includes/hooks.md
  - includes/platform-specific-configuration-note.md
  - tutorials/test-update-on-s3-locally.md
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 285, in build
    _build_theme_template(template, env, files, config, nav)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 108, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 87, in _build_template
    output = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/material/404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "/usr/local/lib/python3.9/site-packages/material/main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python3.9/site-packages/material/base.html", line 118, in top-level template code
    {% block header %}
  File "/usr/local/lib/python3.9/site-packages/material/base.html", line 119, in block "header"
    {% include "partials/header.html" %}
  File "/usr/local/lib/python3.9/site-packages/material/partials/header.html", line 7, in top-level template code
    {% include "partials/logo.html" %}
  File "/usr/local/lib/python3.9/site-packages/material/partials/logo.html", line 5, in top-level template code
    <img src="{{ config.theme.logo | url }}" alt="logo">
  File "/usr/local/lib/python3.9/site-packages/mkdocs/utils/filters.py", line 14, in url_filter
    return normalize_url(value, page=context['page'], base=context['base_url'])
  File "/usr/local/lib/python3.9/site-packages/mkdocs/utils/__init__.py", line 262, in normalize_url
    path = path_to_url(path or '.')
  File "/usr/local/lib/python3.9/site-packages/mkdocs/utils/__init__.py", line 290, in path_to_url
    return '/'.join(path.split('\\'))
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by mmaietta** [comment]
Oh lordy.

Yeah, I joined recently, and yeah the docs definitely are out of date.
Happy to also accept suggestions on ways we can improve documentation so that it doesn't exist explicitly in a separate branch, or is as difficult to track.
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#documentation
For instance, why are we avoiding google indexing to require the `docs` branch?

**Comment by mmaietta** [comment]
@kroko I'm looking to find a better way of automating doc generation, particularly by consolidating it back into the release process / in master branch.
Do you have pro tips on improving to achieve that for this project?
