### ISSUE TITLE
Build fails with TimeOut exception: proxy

### ISSUE THREAD

**Issue by meltedspark** [electron-userland/electron-builder#585]
* **^5.12.1**: 

* **Windows**: 

Trying to build installer for my package but it fails with the following exception:

> Unhandled rejection Error: connect ETIMEDOUT 108.168.243.150:443
>     at Object.exports._errnoException (util.js:1008:11)
>     at exports._exceptionWithHostPort (util.js:1031:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
> From previous event:
>     at C:\git\adt_tools\electron\playground\node_modules\electron-builder\src\util\binDownload.ts:52:17
>     at next (native)
>     at C:\git\adt_tools\electron\playground\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:35:14
>     at FSReqWrap.oncomplete (fs.js:123:15)
> From previous event:
>     at tsAwaiter (C:\git\adt_tools\electron\playground\node_modules\electron-builder\src\util\awaiter.ts:10:47)
>     at Object.build (C:\git\adt_tools\electron\playground\node_modules\electron-builder\src\builder.ts:192:52)
>     at Object.<anonymous> (C:\git\adt_tools\electron\playground\node_modules\electron-builder\src\build-cli.ts:27:28)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Module.runMain (module.js:575:10)
>     at run (bootstrap_node.js:352:7)
>     at startup (bootstrap_node.js:144:9)
>     at bootstrap_node.js:467:3

Problem appears both with NSIS and Squirrel target. 
I'm behind a corporate proxy, so I suspect it's somehow related to this, although I defined proxy settings (both http & https) for npm.

**UPD:**
That is a proxy issue for sure - just tried it with no proxy and it works.
Perhaps you're connecting to some server from within electron-builder code (not via npm) and then you probably should provide an option to configure proxy for electron-builder?

**Comment by develar** [comment]
https://bintray.com is used to download pre-bundled dependencies (e.g. nsis). npm configured proxy should be used, yes.

**Comment by marttinen** [comment]
I've encountered the same issue. Due to the direct usage of nodes 'https' module, http proxies wont work. See [httpRequest.ts](https://github.com/electron-userland/electron-builder/blob/master/src/util/httpRequest.ts#L42)

I'm working on a fix, using either nugget or request for downloading the binaries, just like [electron-download](https://github.com/electron-userland/electron-download/blob/master/index.js#L123) does.

**Comment by develar** [comment]
@marttinen It is better to not use nugget or request, but fix `httpRequest.ts` I think it is not a lot of work here.

**Comment by ajklotz** [comment]
Does anyone know which npm packets can be downloaded manually to bypass this error?

**Comment by develar** [comment]
@ajklotz Unpack [Archive.zip](https://github.com/electron-userland/electron-builder/files/449008/Archive.zip) to `~/.cache`

**Comment by develar** [comment]
Standard env `HTTP_PROXY` / `HTTPS_PROXY` is supported. NPM conf will be added later.

**Comment by scedge** [comment]
This still seems to be an issue, I can get it to work fine when not behind a proxy.

**Comment by neal1991** [comment]
I came across the same issue.  But I have not config any proxy for npm config. And I have tried to `ping` 54.231.33.203.  The IP is accessible. The problem still exists.
```
Error: connect ETIMEDOUT 54.231.33.203:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\neal1\project\your-own-notes\node_modules\.3.5.1@bluebird\js\release\debuggability.js:400:19)
    at Promise._then (C:\Users\neal1\project\your-own-notes\node_modules\.3.5.1@bluebird\js\release\promise.js:232:17)
    at Promise.then (C:\Users\neal1\project\your-own-notes\node_modules\.3.5.1@bluebird\js\release\promise.js:125:17)
    at Object.args [as handler] (C:\Users\neal1\project\your-own-notes\node_modules\.19.37.2@electron-builder\out\cli\cli.js:127:117)
    at Object.self.runCommand (C:\Users\neal1\project\your-own-notes\node_modules\yargs\lib\command.js:231:22)
    at Object.Yargs.self._parseArgs (C:\Users\neal1\project\your-own-notes\node_modules\yargs\yargs.js:1017:24)
    at Object.get [as argv] (C:\Users\neal1\project\your-own-notes\node_modules\yargs\yargs.js:930:19)
    at Object.<anonymous> (C:\Users\neal1\project\your-own-notes\node_modules\.19.37.2@electron-builder\out\cli\cli.js:123:418)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
