### ISSUE TITLE
electron-builder does not seem to fully support custom publish providers

### ISSUE THREAD

**Issue by strisys** [electron-userland/electron-builder#5854]
* **Versions/targets**: 
  * **electron: 12.0.5, current**
  * **electron-updater 4.3.8**
  *  **Target: windows**

The error is _not_ with electron but with the publish capability of electron-builder using a _custom_ publish provider

```
   package.json
  -----------------
   ....
    "publish": {
      "provider": "custom"
    }
```

I have a custom provider implemented to publish to Microsoft Azure ([nsis-custom-publish.zip](https://github.com/electron-userland/electron-builder/files/6415767/nsis-custom-publish.zip)) and only some of the files make it there but not all.  What is also interesting is that when I DO NOT publish (i.e. `--publish never`) I observe the following error.  

```
> electron-builder build --win --x64 --publish never

  • electron-builder  version=22.10.5 os=10.0.19042
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\electron\installer\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=12.0.5 appOutDir=dist\electron\installer\win-unpacked
  • Unpacking electron zip  zipPath=undefined
electron-publisher-custom - module loaded
  • building        target=nsis file=dist\electron\installer\Contoso Analytics Setup 1.0.41.exe archs=x64 oneClick=true perMachine=false
  • building        target=nsis-web file=dist\electron\installer\nsis-web\Contoso Analytics Web Setup 1.0.41.exe archs=x64 oneClick=true perMachine=false
  • building embedded block map  file=dist\electron\installer\nsis-web\create-deploy-autoupdate-1.0.41-x64.nsis.7z
  • building block map  blockMapFile=dist\electron\installer\Contoso Analytics Setup 1.0.41.exe.blockmap
  ⨯ Not supported provider: custom  stackTrace=
                                      Error: Not supported provider: custom
                                          at getS3LikeProviderBaseUrl (G:\web\client\_exercises\electron-create-deploy-autoupdate-trudel\source\2-nsis-custom-publish\node_modules\builder-util-runtime\src\publishOptions.ts:231:9)
                                          at computeDownloadUrl (G:\web\client\_exercises\electron-create-deploy-autoupdate-trudel\source\2-nsis-custom-publish\node_modules\app-builder-lib\src\publish\PublishManager.ts:346:15)
                                          at WebInstallerTarget.configureDefines (G:\web\client\_exercises\electron-create-deploy-autoupdate-trudel\source\2-nsis-custom-publish\node_modules\app-builder-lib\src\targets\nsis\WebInstallerTarget.ts:31:23)
                                          at WebInstallerTarget.buildInstaller (G:\web\client\_exercises\electron-create-deploy-autoupdate-trudel\source\2-nsis-custom-publish\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:240:7)
                                          at WebInstallerTarget.finishBuild (G:\web\client\_exercises\electron-create-deploy-autoupdate-trudel\source\2-nsis-custom-publish\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:110:7)
                                          at async Promise.all (index 3)
                                          at AsyncTaskManager.awaitTasks (G:\web\client\_exercises\electron-create-deploy-autoupdate-trudel\source\2-nsis-custom-publish\node_modules\builder-util\src\asyncTaskManager.ts:65:25)
                                          at Packager.doBuild (G:\web\client\_exercises\electron-create-deploy-autoupdate-trudel\source\2-nsis-custom-publish\node_modules\app-builder-lib\src\packager.ts:446:5)
                                          at executeFinally (G:\web\client\_exercises\electron-create-deploy-autoupdate-trudel\source\2-nsis-custom-publish\node_modules\builder-util\src\promise.ts:12:14)
                                          at Packager._build (G:\web\client\_exercises\electron-create-deploy-autoupdate-trudel\source\2-nsis-custom-publish\node_modules\app-builder-lib\src\packager.ts:369:31)
                                          at Packager.build (G:\web\client\_exercises\electron-create-deploy-autoupdate-trudel\source\2-nsis-custom-publish\node_modules\app-builder-lib\src\packager.ts:333:12)
                                          at executeFinally (G:\web\client\_exercises\electron-create-deploy-autoupdate-trudel\source\2-nsis-custom-publish\node_modules\builder-util\src\promise.ts:12:14)
ERROR: "eb-build" exited with 1.
```

I am doubtful this error is indicative of the real problem.   Any help would be appreciated otherwise I can write my own publisher script outside of using electron-builder.  Thank you

**Comment by mmaietta** [comment]
A custom provider should be supported in the latest 22.11.8
https://github.com/electron-userland/electron-builder/pull/5984
