### ISSUE TITLE
Node 16 support

### ISSUE THREAD

**Issue by mrgodhani** [electron-userland/electron-builder#5862]
* **Version**: 22.11.1

* **Electron Version**: 12.0.6
* **Electron Type (current, beta, nightly)**:

* **Target**:  Any

Noticing electron builder is spitting following below error:

```
success Saved 1 new dependency.
info Direct dependencies
└─ electron-builder@22.11.1
info All dependencies
└─ electron-builder@22.11.1
$ electron-builder install-app-deps

/Users/meetgodhani/Projects/ridereceiptsprov2/node_modules/errlop/edition-es5/index.js:61
		_this = _super.call(this, input.message || input) || this
                 ^
Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
```

When running against node version 15 it works fine. 

Is there any work for supporting node 16?

**Comment by zaherg** [comment]
I faced a similar issue, when I changed to  v22.10.5 with node 16 I got a different error

(sorry in advance for the formatting but this is how it was produced)
```
 OKAY  take it away `electron-builder`

  • electron-builder  version=22.10.5 os=20.4.0
  • loaded configuration  file=/Users/zaher/Sites/electron/domains/electron-builder.json
  • writing effective config  file=build/1.8.3-0/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=11.4.6 appOutDir=build/1.8.3-0/mac/x64/mac
  • Unpacking electron zip  zipPath=undefined
  • downloading     url=https://github.com/electron/electron/releases/download/v11.4.6/electron-v11.4.6-darwin-x64.zip size=78 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v11.4.6/electron-v11.4.6-darwin-x64.zip duration=11.845s
 ⨯ editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.  stackTrace=
                                                                                                          Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
                                                                                                              at new Errlop (/Users/zaher/Sites/electron/domains/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:317:21)
                                                                                                              at solicitEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                          ↳ Error: editions-autoloader-none-suitable: Unable to determine a suitable edition, as none were suitable.
                                                                                                              at new Errlop (/Users/zaher/Sites/electron/domains/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:327:19)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript source code made to be compatible with Deno] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/zaher/Sites/electron/domains/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 12 || 14 || 15 with Import for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/zaher/Sites/electron/domains/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 10 || 12 || 14 || 15 with Require for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/zaher/Sites/electron/domains/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ESNext for Node.js 14 || 15 with Require for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/zaher/Sites/electron/domains/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for web browsers with Import for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/zaher/Sites/electron/domains/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: The edition [TypeScript source code with Import for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/zaher/Sites/electron/domains/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at isCompatibleEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:252:19)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:287:4)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                          ↳ Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment
                                                                                                              at new Errlop (/Users/zaher/Sites/electron/domains/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at isCompatibleEngines (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:183:19)
                                                                                                              at isCompatibleEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:250:10)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:287:4)
                                                                                                              at determineEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/zaher/Sites/electron/domains/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/zaher/Sites/electron/domains/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
```

**Comment by mmaietta** [comment]
@zaherg your issue should be resolved with this https://github.com/electron-userland/electron-builder/pull/5851
