### ISSUE TITLE
have the same architectures (x86_64) and can't be in the same fat output file

### ISSUE THREAD

**Issue by MiGongOrg** [electron-userland/electron-builder#5891]
* **Version**: 22.10.5

* **Electron Version**:11.0.3

* **Target**: default

```javascript
mac: {
  target: [
    {
      arch: 'universal',
      target: 'default'
    }
  ]
}
```
```log
 INFO  Building app with electron-builder:
  • electron-builder  version=22.10.5 os=19.5.0
  • writing effective config  file=dist_electron/apk-beta/1.5.0/MT/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=ffi-napi@2.5.0, ref-napi@1.5.2, sqlite3@5.0.2 platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=11.4.6 appOutDir=dist_electron/apk-beta/1.5.0/MT/mac-universal--x64
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • rebuilding native dependencies  dependencies=ffi-napi@2.5.0, ref-napi@1.5.2, sqlite3@5.0.2 platform=darwin arch=arm64
  • packaging       platform=darwin arch=arm64 electron=11.4.6 appOutDir=dist_electron/apk-beta/1.5.0/MT/mac-universal--arm64
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • packaging       platform=darwin arch=universal electron=11.4.6 appOutDir=dist_electron/apk-beta/1.5.0/MT/mac-universal
ExitCodeError: Command failed with a non-zero return code (1):
lipo /private/var/folders/p7/3nf5d6n93zz3761vzp9twdp00000gn/T/electron-universal-9jTZtG/Tmp.app/Contents/Resources/app/node_modules/ffi-napi/build/Release/ffi_bindings.node /Users/color/Documents/obj/electron-luff/dist_electron/apk-beta/1.5.0/MT/mac-universal--arm64/cloudbeta.app/Contents/Resources/app/node_modules/ffi-napi/build/Release/ffi_bindings.node -create -output /private/var/folders/p7/3nf5d6n93zz3761vzp9twdp00000gn/T/electron-universal-9jTZtG/Tmp.app/Contents/Resources/app/node_modules/ffi-napi/build/Release/ffi_bindings.node

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /private/var/folders/p7/3nf5d6n93zz3761vzp9twdp00000gn/T/electron-universal-9jTZtG/Tmp.app/Contents/Resources/app/node_modules/ffi-napi/build/Release/ffi_bindings.node and /Users/color/Documents/obj/electron-luff/dist_electron/apk-beta/1.5.0/MT/mac-universal--arm64/cloudbeta.app/Contents/Resources/app/node_modules/ffi-napi/build/Release/ffi_bindings.node have the same architectures (x86_64) and can't be in the same fat output file
    at ChildProcess.<anonymous> (/Users/color/Documents/obj/electron-luff/node_modules/@malept/cross-spawn-promise/src/index.ts:172:16)
    at ChildProcess.emit (node:events:327:20)
    at maybeClose (node:internal/child_process:1055:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5) {
  cmd: 'lipo',
  args: [
    '/private/var/folders/p7/3nf5d6n93zz3761vzp9twdp00000gn/T/electron-universal-9jTZtG/Tmp.app/Contents/Resources/app/node_modules/ffi-napi/build/Release/ffi_bindings.node',
    '/Users/color/Documents/obj/electron-luff/dist_electron/apk-beta/1.5.0/MT/mac-universal--arm64/cloudbeta.app/Contents/Resources/app/node_modules/ffi-napi/build/Release/ffi_bindings.node',
    '-create',
    '-output',
    '/private/var/folders/p7/3nf5d6n93zz3761vzp9twdp00000gn/T/electron-universal-9jTZtG/Tmp.app/Contents/Resources/app/node_modules/ffi-napi/build/Release/ffi_bindings.node'
  ],
  stdout: '',
  stderr: "fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /private/var/folders/p7/3nf5d6n93zz3761vzp9twdp00000gn/T/electron-universal-9jTZtG/Tmp.app/Contents/Resources/app/node_modules/ffi-napi/build/Release/ffi_bindings.node and /Users/color/Documents/obj/electron-luff/dist_electron/apk-beta/1.5.0/MT/mac-universal--arm64/cloudbeta.app/Contents/Resources/app/node_modules/ffi-napi/build/Release/ffi_bindings.node have the same architectures (x86_64) and can't be in the same fat output file\n",
  code: 1
}
```

**Comment by mmaietta** [comment]
That might be related to this issue: https://github.com/develar/app-builder/issues/55

**Comment by mayfield** [comment]
I believe I'm running into this with sqlite3...
```
  • packaging       platform=darwin arch=universal electron=17.1.0 appOutDir=dist/mac-universal
  ⨯ Command failed with a non-zero return code (1):
lipo /private/var/folders/71/4_w74cxj79s28vhsr869b7tc0000gn/T/electron-universal-Qhfs89/Tmp.app/Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Release/node_sqlite3.node /Users/mayfield/project/sauce4zwift/dist/mac-universal--arm64/Sauce for Zwift™.app/Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Release/node_sqlite3.node -create -output /private/var/folders/71/4_w74cxj79s28vhsr869b7tc0000gn/T/electron-universal-Qhfs89/Tmp.app/Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Release/node_sqlite3.node

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /private/var/folders/71/4_w74cxj79s28vhsr869b7tc0000gn/T/electron-universal-Qhfs89/Tmp.app/Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Release/node_sqlite3.node and /Users/mayfield/project/sauce4zwift/dist/mac-universal--arm64/Sauce for Zwift™.app/Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Release/node_sqlite3.node have the same architectures (arm64) and can't be in the same fat output file  failedTask=build stackTrace=Error: Command failed with a non-zero return code (1):
lipo /private/var/folders/71/4_w74cxj79s28vhsr869b7tc0000gn/T/electron-universal-Qhfs89/Tmp.app/Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Release/node_sqlite3.node /Users/mayfield/project/sauce4zwift/dist/mac-universal--arm64/Sauce for Zwift™.app/Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Release/node_sqlite3.node -create -output /private/var/folders/71/4_w74cxj79s28vhsr869b7tc0000gn/T/electron-universal-Qhfs89/Tmp.app/Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Release/node_sqlite3.node
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /private/var/folders/71/4_w74cxj79s28vhsr869b7tc0000gn/T/electron-universal-Qhfs89/Tmp.app/Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Release/node_sqlite3.node and /Users/mayfield/project/sauce4zwift/dist/mac-universal--arm64/Sauce for Zwift™.app/Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Release/node_sqlite3.node have the same architectures (arm64) and can't be in the same fat output file
    at ChildProcess.<anonymous> (/Users/mayfield/project/sauce4zwift/node_modules/@malept/cross-spawn-promise/src/index.ts:172:16)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
make: *** [build] Error 1
```

**Comment by objectiveSee** [comment]
I am getting this error on a m1 mac running `electron-forge make --arch universal`

**Comment by spartygw** [comment]
I'm still seeing this but I see the issue is closed. Is there a work-around?

**Comment by semireg** [comment]
I'm seeing this when trying to bundle a copy of a fat Python binary. The input files are identical. The workaround is likely to detect when the inputs to lipo are the same (and fat), and then just choose one and not try to combine them.

**Comment by semireg** [comment]
Here's the relevant code in [electron/universal](https://github.com/electron/universal/blob/3a30fe989bee57d93b3da7beb9e9bf8ca29639fc/src/index.ts#L140). You'll see that they are using the sha. I enabled debug for electron-universal and then looked at the actual code in node_modules and it didn't match the above... behold, electron-builder (nay app-builder-lib) is pinned to [@electron/universal version 1.2.1](https://github.com/electron-userland/electron-builder/blob/3e9cd2c88e7f9e2bca9adc0ce0790fbdf2e18f02/packages/app-builder-lib/package.json#L52). I'm guessing that if we get that dependency updated with the hashing logic we'll be good. Thoughts?

**Comment by mmaietta** [comment]
`x64ArchFiles` is available in https://github.com/electron-userland/electron-builder/releases/tag/v23.3.0
PR introduction: https://github.com/electron-userland/electron-builder/pull/6913

**Comment by semireg** [comment]
Happy to report that I have a working Universal binary for **non-MAS** builds.

However, there's some kind of MAS-related code-signing issue happening, possibly related to x64ArchFiles. Here's what I'm seeing:

`2022-07-21 21:30:48.405 *** Error: Invalid Code Signing. The executable 'com.semireg.LabelLIVE.pkg/Payload/Label LIVE.app/Contents/Frameworks/numbers-to-csv/Python' must be signed with the certificate that is contained in the provisioning profile. With error code STATE_ERROR.VALIDATION_ERROR.90284 for id ABCD-1234-DEFGH-5678 Asset validation failed (-19208)`

I only get this when using the latest electron-builder v23.3.1.

Could it be related to copying `numbers-to-csv` over in a extraFiles/extraResources step? I've checked the offending file and nothing stands out as obviously wrong, but I'm no expert in MAS code signing.
