### ISSUE TITLE
AutoUpdater - App Just Quitting Not Installing

### ISSUE THREAD

**Issue by jeremy-frontpointds** [electron-userland/electron-builder#5928]
* **Version**: latest (22.10.5) 

* **Electron Version**: 12.0.2
* **Electron Type (current, beta, nightly)**: current

* **Electron Updater**: 4.3.9

* **Target**: nsis

Application will download update, quit, and not install. 
10% of the time, after starting the application again, it will install the new version. 
Other times nothing will happen. 

As of my last few version updates, nothing has happened. 

_Sensitive information has been redacted_
`[2021-05-27 17:13:09.771] [info]  Checking for update
[2021-05-27 17:13:11.403] [info]  Found version 1.0.48 (url: xxxx xxxx {MY APP NAME}-setup-1.0.48.exe)
[2021-05-27 17:13:11.408] [info]  Update Available
[2021-05-27 17:13:11.413] [info]  Downloading update from xxxx xxxx {MY APP NAME}-setup-1.0.48.exe
[2021-05-27 17:13:11.425] [info]  Downloading update from xxxx xxxx {MY APP NAME}-setup-1.0.48.exe
[2021-05-27 17:13:11.445] [info]  Download block maps (old: "https://xxxx-releases.s3.amazonaws.com/windows/xxxx/xxxx%20xxxx%20XXXXXXX%20XXXXXXX%20XXXXXX-setup-1.0.48.exe.blockmap", new: https://xxxx-releases.s3.amazonaws.com/windows/xxxx/xxxx%20xxxx%20XXXXXXX%20XXXXXXX%20XXXXXX-setup-1.0.48.exe.blockmap)
[2021-05-27 17:13:11.456] [info]  Download block maps (old: "https://xxxx-releases.s3.amazonaws.com/windows/xxxx/xxxx%20xxxx%20XXXXXXX%20XXXXXXX%20XXXXXX-setup-1.0.48.exe.blockmap", new: https://xxxx-releases.s3.amazonaws.com/windows/xxxx/xxxx%20xxxx%20XXXXXXX%20XXXXXXX%20XXXXXX-setup-1.0.48.exe.blockmap)
[2021-05-27 17:13:12.096] [info]  Full: 74,829.68 KB, To download: 0 KB (0%)
[2021-05-27 17:13:12.131] [info]  Full: 74,829.68 KB, To download: 0 KB (0%)
[2021-05-27 17:13:12.140] [info]  Differential download: https://xxxx-releases.s3.amazonaws.com/windows/xxxx/xxxx%20xxxx%20XXXXXXX%20XXXXXXX%20XXXXXX-setup-1.0.48.exe
[2021-05-27 17:13:12.153] [info]  Differential download: https://xxxx-releases.s3.amazonaws.com/windows/xxxx/xxxx%20xxxx%20XXXXXXX%20XXXXXXX%20XXXXXX-setup-1.0.48.exe
[2021-05-27 17:13:15.260] [error] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected JTbijFaO5ko3Z3lwLns2IMtEKKEpt1pIw8s4udlYZFaAEshHDlDwK8seISnOGENzS7I1GOqCxz+vTHQrgpfuxQ==, got +Bs4olkSnmm/JK6lpWzfnHMQBpmnGOEV7qr25OyPgnqABlD//a8Ukf18ZwmvQFmmv9EsVcJkzMUqLXE7ZvJ2zg==
    at Object.newError (C:\Users\xxxx\AppData\Local\Programs\xxxx-xxxx\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\index.js:47:19)
    at DigestTransform.validate (C:\Users\xxxx\AppData\Local\Programs\xxxx-xxxx\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:323:27)
    at WriteStream.<anonymous> (C:\Users\xxxx\AppData\Local\Programs\xxxx-xxxx\resources\app.asar\node_modules\electron-updater\out\differentialDownloader\DifferentialDownloader.js:133:41)
    at WriteStream.emit (events.js:315:20)
    at emitCloseNT (internal/streams/destroy.js:87:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
[2021-05-27 17:13:15.269] [error] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected JTbijFaO5ko3Z3lwLns2IMtEKKEpt1pIw8s4udlYZFaAEshHDlDwK8seISnOGENzS7I1GOqCxz+vTHQrgpfuxQ==, got +Bs4olkSnmm/JK6lpWzfnHMQBpmnGOEV7qr25OyPgnqABlD//a8Ukf18ZwmvQFmmv9EsVcJkzMUqLXE7ZvJ2zg==
    at Object.newError (C:\Users\xxxx\AppData\Local\Programs\xxxx-xxxx\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\index.js:47:19)
    at DigestTransform.validate (C:\Users\xxxx\AppData\Local\Programs\xxxx-xxxx\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:323:27)
    at WriteStream.<anonymous> (C:\Users\xxxx\AppData\Local\Programs\xxxx-xxxx\resources\app.asar\node_modules\electron-updater\out\differentialDownloader\DifferentialDownloader.js:133:41)
    at WriteStream.emit (events.js:315:20)
    at emitCloseNT (internal/streams/destroy.js:87:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
[2021-05-27 17:13:24.387] [info]  New version 1.0.48 has been downloaded to C:\Users\xxxx\AppData\Local\xxxx-xxxx-updater\pending\xxxx xxxx {MY APP NAME}-setup-1.0.48.exe
[2021-05-27 17:13:30.529] [error] Error: Error: ENOENT: no such file or directory, rename 'C:\Users\xxxx\AppData\Local\xxxx-xxxx-updater\pending\temp-xxxx xxxx {MY APP NAME}-setup-1.0.48.exe' -> 'C:\Users\xxxx\AppData\Local\xxxx-xxxx-updater\pending\xxxx xxxx {MY APP NAME}-setup-1.0.48.exe'
[2021-05-27 17:13:34.414] [info]  Update downloaded.
[2021-05-27 17:13:34.422] [info]  Install on explicit quitAndInstall
[2021-05-27 17:13:34.429] [info]  Install: isSilent: true, isForceRunAfter: true
[2021-05-27 17:13:34.452] [info]  Cannot run installer: error code: ENOENT, error message: "spawn C:\Users\xxxx\AppData\Local\xxxx-xxxx-updater\pending\xxxx xxxx {MY APP NAME}-setup-1.0.48.exe ENOENT", will be executed again using elevate if EACCES"
[2021-05-27 17:13:34.459] [error] Error: Error: spawn C:\Users\xxxx\AppData\Local\xxxx-xxxx-updater\pending\xxxx xxxx {MY APP NAME}-setup-1.0.48.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2021-05-27 17:13:34.516] [info]  Update installer has already been triggered. Quitting application.`

**Comment by jeremy-frontpointds** [comment]
The update was auto downloading. In my code I was triggering the download as well, causing it to run twice. This was causing the inconsistencies. 

I am not sure if it is supposed to auto download by default.

**Comment by jackple** [comment]
Have you solved this problem?

**Comment by jeremy-simplyscreens** [comment]
@jackple 

The issue that I had was that I was calling `autoUpdater.downloadUpdate();` if the update was available. Which apparently wasn't needed. Below is a snippet that has been working for multiple programs for 2+ years now. 

```JS
//Program update listeners.

  if (app.isPackaged) {
    autoUpdater.checkForUpdates().catch((e) => {
      log.error(e);
    });

    autoUpdater.on("update-available", () => {
      //show a download window or other user notification.
    });

    autoUpdater.on("download-progress", (event) => {
      //handle download progress (i.e. send progress amount to a update window)
    });

    autoUpdater.on("update-downloaded", () => {
      log.info("Downloaded Update");
      autoUpdater.quitAndInstall();
    });
  }
```

**Comment by jackple** [comment]
> @jackple
> 
> The issue that I had was that I was calling `autoUpdater.downloadUpdate();` if the update was available. Which apparently, wasn't needed. Below is a snippet that has been working for multiple programs for 2+ years now.
> 
> ```js
> //Program update listeners.
> 
>   if (app.isPackaged) {
>     autoUpdater.checkForUpdates().catch((e) => {
>       log.error(e);
>     });
> 
>     autoUpdater.on("update-available", () => {
>       //show a download window or other user notification.
>     });
> 
>     autoUpdater.on("download-progress", (event) => {
>       //handle download progress (i.e. send progress amount to an update window)
>     });
> 
>     autoUpdater.on("update-downloaded", () => {
>       log.info("Downloaded Update");
>       autoUpdater.quitAndInstall();
>     });
>   }
> ```

![image](https://github.com/electron-userland/electron-builder/assets/6183232/9ffea652-647b-4da2-b603-daec34d3d18b)
I thought you were stuck on this installation step, sorry for the interruption.
