### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by maifeeulasad** [electron-userland/electron-builder#5947]
* **Version**: `^22.10.5`

* **Electron Version**: `^13.1.1`
* **Electron Type (current, beta, nightly)**: `current`

* **Target**: *`linux`*

The error I'm getting when I'm trying to run the `AppImage` is :
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /tmp/.mount_WhatAp5J06Sw/resources/app.asar/index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Object.<anonymous> (electron/js2c/browser_init.js:193:3237)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:193:3441)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
```
Here is the source code: https://github.com/maifeeulasad/WhatApp/tree/d2987f27542c7850e51ee4d1a0b1a5bf53c147e8

I'm using babel for this project to use es6, my `.babelrc` looks like this : 
```
{ 	
           "presets": ["es2015"] 
}
```
And I use `*electron -r babel-register .*` to start the application.

**Comment by mwoz123** [comment]
I'm having same issue.

@maifeeulasad  did you manage to workaround it /find what might be wrong?

**Comment by maifeeulasad** [comment]
@mwoz123 hello, I moved into some other stuff! And I couldn't figure it out, so I used `.AppImage`.
