### ISSUE TITLE
electron builder fails

### ISSUE THREAD

**Issue by quinton-ashley** [electron-userland/electron-builder#5949]
> nostlan@1.21.0 dist-l
> electron-builder -l

  • electron-builder  version=22.10.5 os=5.10.41-1-MANJARO
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=robotjs@0.6.0, sharp@0.27.1, usb@1.7.1 platform=linux arch=x64
  • install prebuilt binary  name=sharp version=0.27.1 platform=linux arch=x64
  • install prebuilt binary  name=robotjs version=0.6.0 platform=linux arch=x64
  • build native dependency from sources  name=sharp
                                          version=0.27.1
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=/home/qashto/dev/apps/nostlan/node_modules/node-abi/index.js:30
      throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
      ^
    
    Error: Could not detect abi for version 13.1.2 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (/home/qashto/dev/apps/nostlan/node_modules/node-abi/index.js:30:9)
        at module.exports (/home/qashto/dev/apps/nostlan/node_modules/prebuild-install/rc.js:73:57)
        at Object.<anonymous> (/home/qashto/dev/apps/nostlan/node_modules/prebuild-install/bin.js:9:25)
        at Module._compile (node:internal/modules/cjs/loader:1109:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
        at Module.load (node:internal/modules/cjs/loader:989:32)
        at Function.Module._load (node:internal/modules/cjs/loader:829:14)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
        at node:internal/main/run_main_module:17:47
    
  • install prebuilt binary  name=usb version=1.7.1 platform=linux arch=x64
  • build native dependency from sources  name=robotjs
                                          version=0.6.0
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=/home/qashto/dev/apps/nostlan/node_modules/node-abi/index.js:30
      throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
      ^
    
    Error: Could not detect abi for version 13.1.2 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (/home/qashto/dev/apps/nostlan/node_modules/node-abi/index.js:30:9)
        at module.exports (/home/qashto/dev/apps/nostlan/node_modules/prebuild-install/rc.js:73:57)
        at Object.<anonymous> (/home/qashto/dev/apps/nostlan/node_modules/prebuild-install/bin.js:9:25)
        at Module._compile (node:internal/modules/cjs/loader:1109:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
        at Module.load (node:internal/modules/cjs/loader:989:32)
        at Function.Module._load (node:internal/modules/cjs/loader:829:14)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
        at node:internal/main/run_main_module:17:47
    
  • build native dependency from sources  name=usb
                                          version=1.7.1
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=/home/qashto/dev/apps/nostlan/node_modules/node-abi/index.js:30
      throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
      ^
    
    Error: Could not detect abi for version 13.1.2 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (/home/qashto/dev/apps/nostlan/node_modules/node-abi/index.js:30:9)
        at module.exports (/home/qashto/dev/apps/nostlan/node_modules/prebuild-install/rc.js:73:57)
        at Object.<anonymous> (/home/qashto/dev/apps/nostlan/node_modules/prebuild-install/bin.js:9:25)
        at Module._compile (node:internal/modules/cjs/loader:1109:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
        at Module.load (node:internal/modules/cjs/loader:989:32)
        at Function.Module._load (node:internal/modules/cjs/loader:829:14)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
        at node:internal/main/run_main_module:17:47
    
  • packaging       platform=linux arch=x64 electron=13.1.2 appOutDir=dist/linux-unpacked
  • Unpacking electron zip  zipPath=undefined
  • downloading     url=https://github.com/electron/electron/releases/download/v13.1.2/electron-v13.1.2-linux-x64.zip size=77 MB parts=4
  • downloaded      url=https://github.com/electron/electron/releases/download/v13.1.2/electron-v13.1.2-linux-x64.zip duration=4.141s
  ⨯ editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.  stackTrace=
                                                                                                          Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
                                                                                                              at new Errlop (/usr/lib/node_modules/electron-builder/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:317:21)
                                                                                                              at solicitEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                          ↳ Error: editions-autoloader-none-suitable: Unable to determine a suitable edition, as none were suitable.
                                                                                                              at new Errlop (/usr/lib/node_modules/electron-builder/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:327:19)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript source code made to be compatible with Deno] is not compatible with this environment.
                                                                                                              at new Errlop (/usr/lib/node_modules/electron-builder/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 12 || 14 || 15 with Import for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/usr/lib/node_modules/electron-builder/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 10 || 12 || 14 || 15 with Require for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/usr/lib/node_modules/electron-builder/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ESNext for Node.js 14 || 15 with Require for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/usr/lib/node_modules/electron-builder/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for web browsers with Import for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/usr/lib/node_modules/electron-builder/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: The edition [TypeScript source code with Import for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/usr/lib/node_modules/electron-builder/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at isCompatibleEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:252:19)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:287:4)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                          ↳ Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment
                                                                                                              at new Errlop (/usr/lib/node_modules/electron-builder/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at isCompatibleEngines (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:183:19)
                                                                                                              at isCompatibleEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:250:10)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:287:4)
                                                                                                              at determineEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/usr/lib/node_modules/electron-builder/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1109:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:989:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:829:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1013:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)

**Comment by mmaietta** [comment]
Hmmm, what version of node are you using? Can you please try with 14 and/or 16?

**Comment by mmaietta** [comment]
Please update to latest v22.11.x
`istextorbinary` dependency was removed from latest versions and replaced with `isbinaryfile` IIRC

**Comment by quinton-ashley** [comment]
thank you so much! that worked
