### ISSUE TITLE
AppImage fails to start on libstdc++.so.6 error: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by robertpatrick** [electron-userland/electron-builder#5956]
* **Version**: 22.10.5

* **Electron Version**: 12.0.5
* **Electron Type (current, beta, nightly)**:

* **Target**: AppImage

I am using the `electronuserland/builder:latest` image from Docker Hub to try to build Linux images (also tested with `electronuserland/builder:14-03.21` and version `electronuserland/builder:12-11.19` with the same result).  The AppImage instance will not start on Oracle Linux 7 (which likely means it won't start on RedHat 7 or CentOS 7 either):

```
[rpatrick@rpatrick-1 squashfs-root]$ ./wktui
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.DWyMjF)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/rpatrick/squashfs-root/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

It seems that the build is linking against a version of `libstdc++.so` that is not available on this platform:

```
[rpatrick@rpatrick-1 squashfs-root]$ strings  /usr/lib/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by mmaietta** [comment]
Would you be willing to open a PR for installing the correct version? Dev env setup is fairly simple 🙂  https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

**Comment by rpatrick00** [comment]
I would but I think the issue is with the keytar prebuilt binaries (see https://github.com/atom/node-keytar/issues/395) so I am not sure what approach electron-builder could use to fix this.  Any suggestions?
