### ISSUE TITLE
Error building for Windows on Linux: ENOENT. spawn prlctl ENOENT

### ISSUE THREAD

**Issue by acceleratxr** [electron-userland/electron-builder#5982]
* **Version**: 22.11.7

* **Electron Version**: 11.4.9
* **Electron Type (current, beta, nightly)**: current

* **Electron-Updater**: 4.3.9

* **Target**: 
windows x64 nsis w/ code signing

When attempting to build the win nsis and zip packages from Ubuntu 20.04 or using the electron-builder:wine docker image it always fails with the following output.

```
$ electron-builder --win nsis zip
  • electron-builder  version=22.11.7 os=5.4.72-microsoft-standard-WSL2
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=11.4.9 appOutDir=dist/win-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v11.4.9/electron-v11.4.9-win32-x64.zip size=78 MB parts=2
  • downloaded      url=https://github.com/electron/electron/releases/download/v11.4.9/electron-v11.4.9-win32-x64.zip duration=2.069s
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=739ms
⨯ Exit code: ENOENT. spawn prlctl ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn prlctl ENOENT
    at /builds/AcceleratXR/Core/tools/axrconsole/node_modules/builder-util/src/util.ts:132:18
    at exithandler (child_process.js:326:5)
    at ChildProcess.errorhandler (child_process.js:338:5)
    at ChildProcess.emit (events.js:376:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
From previous event:
    at processImmediate (internal/timers.js:462:21)
From previous event:
    at WinPackager.signApp (/builds/AcceleratXR/Core/tools/axrconsole/node_modules/app-builder-lib/src/winPackager.ts:376:27)
    at WinPackager.doSignAfterPack (/builds/AcceleratXR/Core/tools/axrconsole/node_modules/app-builder-lib/src/platformPackager.ts:315:16)
    at WinPackager.doPack (/builds/AcceleratXR/Core/tools/axrconsole/node_modules/app-builder-lib/src/platformPackager.ts:300:7)
    at WinPackager.pack (/builds/AcceleratXR/Core/tools/axrconsole/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/builds/AcceleratXR/Core/tools/axrconsole/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/builds/AcceleratXR/Core/tools/axrconsole/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/builds/AcceleratXR/Core/tools/axrconsole/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/builds/AcceleratXR/Core/tools/axrconsole/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/builds/AcceleratXR/Core/tools/axrconsole/node_modules/builder-util/src/promise.ts:12:14)
```

Building the package from windows works no problem but this is blocking our CI/CD server from producing builds.

**Comment by mmaietta** [comment]
Can you please run with `DEBUG=electron-builder` env var set and post the relevant logs back here?

**Comment by acceleratxr** [comment]
[electron-builder.log](https://github.com/electron-userland/electron-builder/files/6728968/electron-builder.log)
