### ISSUE TITLE
Build failure while publishing.

### ISSUE THREAD

**Issue by BradPrit09** [electron-userland/electron-builder#6005]
* **Version**: 22.11.7

* **Electron Version**:10.3.2

* **Target**: linux-x64

``` • publishing      publisher=S3 (bucket: endo-distribution)
  • uploading       file=EndoArchive-0.7.5.deb provider=S3
  ⨯ /home/pritam/Projects/endoarchive_website/frontend/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: /home/pritam/Projects/endoarchive_website/frontend/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/home/pritam/Projects/endoarchive_website/frontend/node_modules/builder-util/src/util.ts:249:14)
    at Object.onceWrapper (events.js:482:26)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

I really don't know what is failing. Earlier, I thought it might be node issue , so I updated node to 14.x. Can some one point out ?

The scripts:
```
    "electron-build": "webpack --config webpack.electron.js",
    "electron-build:prod": "npm run electron-build -- -c production",
    "package:linux-release": "npm run electron-build:prod && electron-builder build --linux -p always"
```
The above build script produces no error. Only package:linux-release fails.

**Comment by mmaietta** [comment]
Can you please try running with `DEBUG=electron-builder` env var applied and post back the relevant logs?

**Comment by BradPrit09** [comment]
@mmaietta Oh Sorry for being late , I got it working. Actually, the configuration for s3 was not correct. There was some issue with the documentation. I pointed that out in the discord channel.
