### ISSUE TITLE
Code sign build error

### ISSUE THREAD

**Issue by aaaaaajie** [electron-userland/electron-builder#6035]
* **Electron-Builder Version**:  22.11.7

* **Node Version**: 14.17.2 

* **Electron Version**: 13.1.5
* **Electron Type (current, beta, nightly)**: current

* **Target**:  nsis appx

I'm really sorry for taking your time to help me, but I have to solve this problem.
I think this is related to certificate signing, but I don’t know the specific reason. The error is as follows:
```shell
  ⨯ Exit code: 1. Command failed: C:\Users\123\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.6.0\windows-10\x64\makeappx.exe pack /o /f E:\worktile-projects\wt-sky-client\install-pkg\__appx-x64\mapping.txt /p 88d81ff6bb7871d0922938e026ca5fff1df792ba2ac669efd23512ff5490ea6d (sha256 hash)
Microsoft (R) MakeAppx Tool
Copyright (C) 2013 Microsoft.  All rights reserved.

The path (/p) parameter is: "\\?\E:\worktile-projects\wt-sky-client\install-pkg\worktile-8.0.0-win.appx"
The mapping file (/f) parameter is: "E:\worktile-projects\wt-sky-client\install-pkg\__appx-x64\mapping.txt"
Reading mapping file "E:\worktile-projects\wt-sky-client\install-pkg\__appx-x64\mapping.txt"
Packing 80 file(s) listed in "E:\worktile-projects\wt-sky-client\install-pkg\__appx-x64\mapping.txt" (mapping file) to "\\?\E:\worktile-projects\wt-sky-client\install-pkg\worktile-8.0.0-win.appx" (output file name).
Memory limit defaulting to 4249769984 bytes.
Using "E:\worktile-projects\wt-sky-client\install-pkg\__appx-x64\AppxManifest.xml" as the manifest for the package.
MakeAppx : error: Error info: /*[local-name()="Package" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"]/*[local-name()="Identity" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"][1]/@Publisher
'CN=????????????,O=????????????,ST=???,C=CN' ??? '(CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")(, ((CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")))*' ? pattern ???
?????? 'CN=????????????,O=????????????,ST=???,C=CN' ??? 'Publisher'?
MakeAppx : error: Package creation failed.
MakeAppx : error: 0x80080204 - The specified package format is not valid: The package manifest is not valid.
  failedTask=build stackTrace=Error: Exit code: 1. Command failed: C:\Users\123\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.6.0\windows-10\x64\makeappx.exe pack /o /f E:\worktile-projects\wt-sky-client\install-pkg\__appx-x64\mapping.txt /p 88d81ff6bb7871d0922938e026ca5fff1df792ba2ac669efd23512ff5490ea6d (sha256 hash)
Microsoft (R) MakeAppx Tool
Copyright (C) 2013 Microsoft.  All rights reserved.

The path (/p) parameter is: "\\?\E:\worktile-projects\wt-sky-client\install-pkg\worktile-8.0.0-win.appx"
The mapping file (/f) parameter is: "E:\worktile-projects\wt-sky-client\install-pkg\__appx-x64\mapping.txt"
Reading mapping file "E:\worktile-projects\wt-sky-client\install-pkg\__appx-x64\mapping.txt"
Packing 80 file(s) listed in "E:\worktile-projects\wt-sky-client\install-pkg\__appx-x64\mapping.txt" (mapping file) to "\\?\E:\worktile-projects\wt-sky-client\install-pkg\worktile-8.0.0-win.appx" (output file name).
Memory limit defaulting to 4249769984 bytes.
Using "E:\worktile-projects\wt-sky-client\install-pkg\__appx-x64\AppxManifest.xml" as the manifest for the package.
MakeAppx : error: Error info: /*[local-name()="Package" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"]/*[local-name()="Identity" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"][1]/@Publisher
'CN=????????????,O=????????????,ST=???,C=CN' ??? '(CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")(, ((CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")))*' ? pattern ???
?????? 'CN=????????????,O=????????????,ST=???,C=CN' ??? 'Publisher'?
MakeAppx : error: Package creation failed.
MakeAppx : error: 0x80080204 - The specified package format is not valid: The package manifest is not valid.

    at E:\worktile-projects\wt-sky-client\node_modules\builder-util\src\util.ts:132:18
    at ChildProcess.exithandler (child_process.js:326:5)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! worktile@8.0.0 build:win64: `npm run build && electron-builder --win --x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the worktile@8.0.0 build:win64 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\123\AppData\Roaming\npm-cache\_logs\2021-07-09T08_01_30_023Z-debug.log
```
Looking forward to your reply,thank you!

**Comment by aaaaaajie** [comment]
package.json
```json
{
 "build":{
   "win": {
      "icon": "./build/appx/StoreLogo256x256.png",
      "target": [
        "nsis",
        "appx"
      ],
      "signingHashAlgorithms": [
        "sha256"
      ],
      "certificateFile": "./build/windows/cert.pfx",
      "certificatePassword": "xxx"
    },
    "appx": {}
  }
}
```
