### ISSUE TITLE
Specify installation path on Windows and Linux

### ISSUE THREAD

**Issue by changkun** [electron-userland/electron-builder#605]
* **Version**: 5.10.5

* **Target**: Linux, Windows

For Linux Ubuntu, the installation require a root permission and it will be install on `/opt`, if my App need to do some file operation, there is no permission to do this.

For Windows, the app installed on `C:\Users\user-name\AppData\Local\Programs\`, it is quite uncomfortable, why it is not installed on `C:\Program Files\` ?

How to specify the installation path on Windows and Linux?

**Comment by develar** [comment]
On Linux use AppImage instead `deb`. Set [target](https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions) to `AppImage`.

Windows — no way for Squirrel.Windows. For NSIS target — set `perMachine` to `true`.

**Comment by changkun** [comment]
```
/myapp/node_modules/electron-builder/src/util/httpRequest.ts:122
    callback(hash === this.expected ? null : new Error(`SHA2 checksum mismatch, expected ${this.expected}, got ${hash}`))
                                             ^
Error: SHA2 checksum mismatch, expected , got 803337e37cde3857d05c187ba5d06e8ba3aa55d1524e14ce4a69e15e706fadb4
    at DigestTransform._flush (/myapp/node_modules/electron-builder/src/util/httpRequest.ts:122:46)
    at DigestTransform.<anonymous> (_stream_transform.js:118:12)
    at DigestTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DigestTransform.emit (events.js:166:7)
    at prefinish (_stream_writable.js:458:12)
    at finishMaybe (_stream_writable.js:466:7)
    at endWritable (_stream_writable.js:478:3)
    at DigestTransform.Writable.end (_stream_writable.js:443:5)
    at IncomingMessage.onend (_stream_readable.js:490:10)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
```
Whoops....What's going on here?

**Comment by develar** [comment]
Please update electron-builder to `5.15.0`.

**Comment by changkun** [comment]
Well, `AppImage` is quite confuse for fresh linux user, I probably will not using this type of target. So basically `deb` cannot specify a installation path such as `/home/user-name/AppName`, is that right?

**Comment by develar** [comment]
> basically deb cannot specify a installation path such as /home/user-name/AppName, is that right?

No, you can specify any name. PR welcome. Currently, https://github.com/electron-userland/electron-builder/blob/master/src/targets/LinuxTargetHelper.ts#L12 is hardcoded and not configurable.
