### ISSUE TITLE
'RangeError: Maximum call stack size exceeded' when packaging for win32

### ISSUE THREAD

**Issue by aulvi** [electron-userland/electron-builder#606]
* **Version**: 5.15.0

* **Target**: win32

Below is the console output. Please note that I cannot reproduce on 5.14.2.

Build environment is an Ubuntu 64 vm with 2gig ram, osslsigncode 1.7.1, wine 1.8, mono 4.4.1

```console
> vneck-electron-builder@0.0.1 dist /vagrant
> node ./node_modules/electron-builder/out/build-cli.js --win --x64

Warning: homepage in the development package.json is deprecated, please move to the application package.json
Skip app dependencies rebuild because platform is different
Packaging for platform win32 x64 using electron 1.2.8 to dist/win-unpacked

RangeError: Maximum call stack size exceeded
    at handleFile (/vagrant/node_modules/asar/lib/asar.js:141:16)
    at next (/vagrant/node_modules/asar/lib/asar.js:174:14)
    at /vagrant/node_modules/asar/lib/asar.js:175:16
    at handler (/vagrant/node_modules/asar/lib/filesystem.js:83:16)
    at Filesystem.insertFile (/vagrant/node_modules/asar/lib/filesystem.js:104:16)
    at handleFile (/vagrant/node_modules/asar/lib/asar.js:145:22)
    at next (/vagrant/node_modules/asar/lib/asar.js:174:14)
    at /vagrant/node_modules/asar/lib/asar.js:175:16
    at handleFile (/vagrant/node_modules/asar/lib/asar.js:150:14)
    at next (/vagrant/node_modules/asar/lib/asar.js:174:14)
    at /vagrant/node_modules/asar/lib/asar.js:175:16
    at handler (/vagrant/node_modules/asar/lib/filesystem.js:83:16)
    at Filesystem.insertFile (/vagrant/node_modules/asar/lib/filesystem.js:104:16)
    at handleFile (/vagrant/node_modules/asar/lib/asar.js:145:22)
    at next (/vagrant/node_modules/asar/lib/asar.js:174:14)
    at /vagrant/node_modules/asar/lib/asar.js:175:16
From previous event:
    at tsAwaiter (/vagrant/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/vagrant/node_modules/electron-builder/src/builder.ts:193:52)
    at Object.<anonymous> (/vagrant/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dist"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! vneck-electron-builder@0.0.1 dist: `node ./node_modules/electron-builder/out/build-cli.js --win --x64`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the vneck-electron-builder@0.0.1 dist script 'node ./node_modules/electron-builder/out/build-cli.js --win --x64'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vneck-electron-builder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/electron-builder/out/build-cli.js --win --x64
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vneck-electron-builder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vneck-electron-builder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```

**Comment by develar** [comment]
It seems latest asar version is broken. Will be fixed ASAP.
