### ISSUE TITLE
How to select identity for MacOS code signing?

### ISSUE THREAD

**Issue by rpatrick00** [electron-userland/electron-builder#6082]
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 14.17.3

* **Electron Version**: 12.0.14
* **Electron Type (current, beta, nightly)**: current

* **Target**: MacOS

I am trying to sign my app on my developer machine that has multiple identities following the instructions (and linked page on notarization) but I cannot seem to get the `CSC_NAME` environment variable set so that electron-builder selects the specified identity.

If I run `security find-identity -vp codesigning`, I see:

```
% security find-identity -vp codesigning 
  1) 68307094FC5A34F9222D288F9ECAA8303C6B037E "Mac Developer: Robert Patrick (F7GHKUXZFV)"
  2) 44CA2421EB0C30642C65DB3797B0BF19B9D44CCD "Developer ID Application: Robert Patrick (T9JYPMT298)"
     2 valid identities found
% 
```

if I `export CSC_NAME="Developer ID Application: Robert Patrick (T9JYPMT298)"`, I get a very clear message from electron-builder saying that the CSC_NAME is set incorrectly:

```
% npm run build:installer

> wktui@1.0.0 build:installer
> electron-builder --config electron-builder.yaml

  • electron-builder  version=22.11.7 os=20.5.0
  • loaded configuration  file=/Users/rpatrick/Projects/wktui/electron/electron-builder.yaml
  • writing effective config  file=/Users/rpatrick/Projects/wktui/dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=keytar@7.7.0 platform=darwin arch=x64
  • install prebuilt binary  name=keytar version=7.7.0 platform=darwin arch=x64 napi= 
  • packaging       platform=darwin arch=x64 electron=12.0.14 appOutDir=/Users/rpatrick/Projects/wktui/dist/mac
  ⨯ Please remove prefix "Developer ID Application:" from the specified name — appropriate certificate will be chosen automatically
% 
```

if I remove the `Developer ID Application:` prefix as instructed, electron-builder fails because it cannot resolve which identity to use:

```
% export CSC_NAME="Robert Patrick (T9JYPMT298)" 
% npm run build:installer                      

> wktui@1.0.0 build:installer
> electron-builder --config electron-builder.yaml

  • electron-builder  version=22.11.7 os=20.5.0
  • loaded configuration  file=/Users/rpatrick/Projects/wktui/electron/electron-builder.yaml
  • writing effective config  file=/Users/rpatrick/Projects/wktui/dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=keytar@7.7.0 platform=darwin arch=x64
  • install prebuilt binary  name=keytar version=7.7.0 platform=darwin arch=x64 napi= 
  • packaging       platform=darwin arch=x64 electron=12.0.14 appOutDir=/Users/rpatrick/Projects/wktui/dist/mac
  • skipped macOS application code signing  reason=cannot find valid "Mac Developer, Apple Development" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=  1) 15437472F847556CAE0A699CDA57EAF3CCB1A929 "robert.patrick@mycompany.com" (CSSMERR_TP_NOT_TRUSTED)
  2) 68307094FC5A34F9222D288F9ECAA8303C6B037E "Mac Developer: Robert Patrick (F7GHKUXZFV)"
  3) 44CA2421EB0C30642C65DB3797B0BF19B9D44CCD "Developer ID Application: Robert Patrick (T9JYPMT298)"
  4) A7E16BE121566018731123B9BA175BFBF9A5778A "0f7855fa-879d-4d9f-9fdb-1c0bdaf98e5a-MDMIdentity"
     4 identities found
                                                Valid identities only
  1) 68307094FC5A34F9222D288F9ECAA8303C6B037E "Mac Developer: Robert Patrick (F7GHKUXZFV)"
  2) 44CA2421EB0C30642C65DB3797B0BF19B9D44CCD "Developer ID Application: Robert Patrick (T9JYPMT298)"
  3) A7E16BE121566018731123B9BA175BFBF9A5778A "0f7855fa-879d-4d9f-9fdb-1c0bdaf98e5a-MDMIdentity"
     3 valid identities found
Error: spawn zip ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
% 
```

Here are the relevant pieces from my electron-builder.yaml file:

```
asar: true
afterSign: scripts/notarize.js
directories:
  output: ../dist
mac:
  category: Utility
  target: dmg
  darkModeSupport: false
  type: development
  hardenedRuntime: true
  gatekeeperAssess: false
  entitlements: entitlements.mac.plist,
  entitlementsInherit: entitlements.mac.plist
dmg:
  sign: false
```

What do I need to do to make this work properly?

**Comment by rpatrick00** [comment]
Never mind, after reading/debugging the electron-builder source, I figured it out.  I was setting CSC_NAME to point at the wrong certificate (Development ID Application versus Mac Developer).  You might want to add a blurb in the doc to clarify this for the uninitiated.
