### ISSUE TITLE
Module version mismatch. Expected 46, got 49

### ISSUE THREAD

**Issue by gopikrishnaA** [electron-userland/electron-builder#613]
* **Version**: 2.11.0

* **Target**: node 4.4.0 npm 2.15.1

I am facing issue with electron builder for node version 4.4.0 and tried to update the node version to 6.3.0 got the similar error  related to  `Error: Module version mismatch. Expected 48, got 49`.please help on this. Thanks in advance.

npm run build-signed:osx

```
> xxxxx@1.0.0 build-signed:osx /Users/xxxxxx/Desktop/xxxxx/xxxxxx
> electron-builder build/xxxxxx-darwin-x64 --platform=osx --out=dist/osx64 --config=config/builder.json

- Running electron-builder 2.11.0
/Users/akkumahg/Desktop/xxxxxxx/xxxxxxx/node_modules/electron-builder/cli.js:63
    throw error;
    ^

Error: Module version mismatch. Expected 46, got 49.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/akkumahg/Desktop/xxxxx/xxxxx/node_modules/electron-builder/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/akkumahg/Desktop/xxxxxx/xxxxxxx/node_modules/electron-builder/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias/index.js:1:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-signed:osx"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! xxxxx@1.0.0 build-signed:osx: `electron-builder build/xxxxxxx-darwin-x64 --platform=osx --out=dist/osx64 --config=config/builder.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xxxxxxx@1.0.0 build-signed:osx script 'electron-builder build/xxxxx-darwin-x64 --platform=osx --out=dist/osx64 --config=config/builder.json'.
npm ERR! This is most likely a problem with the XXXXXX package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! electron-builder build/xxxxxx-darwin-x64 --platform=osx --out=dist/osx64 --config=config/builder.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xxxxxx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls XXXXX
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/akkumahg/Desktop/xxxxxx/XXXXXX/npm-debug.log

```

**Comment by develar** [comment]
Just remove `node_modules` and `npm install` again.

**Comment by develar** [comment]
Duplicates https://github.com/electron-userland/electron-builder/issues/453#issuecomment-222737455

**Comment by gopikrishnaA** [comment]
I tried to delete the node modules but even I am facing the same issue.

**Comment by develar** [comment]
In the stack trace I see node 4 and npm 2. Did you tried to used node 6.3.1 and latest npm (before it remove `node_modules`)?

**Comment by develar** [comment]
And `npm cache clean`

**Comment by gopikrishnaA** [comment]
I am trying on node version 4.4.0 and I am doing in this way `npm clean cache && npm install`
