### ISSUE TITLE
Cannot parse blockmap issue in electron-updater

### ISSUE THREAD

**Issue by slugger941** [electron-userland/electron-builder#6184]
I have a issue in electron-updater.(Target: NSIS)
I use below module.
"electron": "13.1.4",
"electron-builder": "^22.9.1",
"electron-updater": "^4.3.9",

<package.json>
"publish": {
     "provider": "github",
     "token": <blabla>,
     .
     .
}
I faced 'Cannot parse blockmap' issue and I don't know how to solve.
And also other error is occured in this line(NsisUpdater.js).

**return JSON.parse(zlib_1.gunzipSync(data).toString());**

Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:181:17)
    at processChunkSync (zlib.js:430:12)
    at zlibBufferSync (zlib.js:169:12)
    at syncBufferWrapper (zlib.js:764:14)
    at downloadBlockMap (C:\Program Files\WatchFaceStudio\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:140:66)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async NsisUpdater.differentialDownloadInstaller (C:\Program Files\WatchFaceStudio\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:164:38)
    at async Object.task (C:\Program Files\WatchFaceStudio\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:32:40)
    at async NsisUpdater.executeDownload (C:\Program Files\WatchFaceStudio\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:507:13) {
  errno: -3,
  code: 'Z_DATA_ERROR'

And then program is closed forcely.
Let me know how to solve this issue.

**Comment by NGrey5** [comment]
I have the same issue.

"electron": "13.1.8",
"electron-builder": "^22.11.7",
"electron-updater": "^4.3.9",

Note: When changing the github repo to public, the app is able to do a differential download correctly. There seems to be an issue with private scoped repos and parsing the blockmap files.

**Comment by mmaietta** [comment]
Nice work! Will add my comments and we can get this pushed through.

**Comment by slugger941** [comment]
@mmaietta Thank you for your answer.
I have another question.
I do not want to download latest version and install. 
I just want to check updates of latest version.
Is there any way to only check updates of latest version??

**Comment by mmaietta** [comment]
There's `autoInstallOnAppQuit = false` that could do the job. It'd still download and prompt to update, but wouldn't force an install.
AFAIK, there's no way to just check for an update _existing_

**Comment by slugger941** [comment]
@mmaietta 
Thank you so much.
Your answer has been of great help.
