### ISSUE TITLE
Application entry file does not exist. Seems like a wrong configuration

### ISSUE THREAD

**Issue by raphael10-collab** [electron-userland/electron-builder#6196]
in `package.json` : 
    
    "scripts": {
          "postinstall": "electron-builder install-app-deps",
          "pack": "electron-builder --dir",
          "dist": "electron-builder"
    },
    "build": {
        "files": [
          "./dist/**/*",
          "./dist/index.html",
          "./dist/index_A.html",
          "./dist/index_B.html",
          "./src/*.js"
        ],
        "extraFiles": [
          "./src/*.py",
          "./src/*.c",
          "./src/*.cpp",
          "./src/*.json",
          "./src/scripts/**/*",
          "./src/assets/**/*",
          "./src/app_A/index_trial.html"
        ],
        "extraResources": [
          "./src/lib/**",
          "./src/assets/**"
        ],
        "appId": "raphy.template",
        "productName": "Raphy.Template",
        "copyright": "Copyright @2021-2022 Raphael Stonehorse",
        "buildVersion": "1"
      },

Running `yarn run pack` I get this error:

    (base) raphy@pc:~/Raphy-Template$ yarn run pack
    yarn run v1.22.10
    $ check-for-leaks
    $ electron-builder --dir
      • electron-builder  version=22.11.7 os=5.11.0-27-generic
      • loaded configuration  file=package.json ("build" field)
      • public/electron.js not found. Please see https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3
      • loaded parent configuration  preset=react-cra
      • writing effective config  file=dist/builder-effective-config.yaml
      • rebuilding native dependencies  dependencies=canvas@2.8.0, leveldown@5.6.0, secp256k1@4.0.2, sodium-native@3.2.1, sqlite3@5.0.2, ursa-optional@0.10.2, utp-native@2.5.3, leveldown@6.0.1 platform=linux arch=x64
      • rebuilding native dependency  name=leveldown version=5.6.0
      • rebuilding native dependency  name=canvas version=2.8.0
      • rebuilding native dependency  name=secp256k1 version=4.0.2
      • rebuilding native dependency  name=sodium-native version=3.2.1
      • rebuilding native dependency  name=sqlite3 version=5.0.2
      • rebuilding native dependency  name=ursa-optional version=0.10.2
      • rebuilding native dependency  name=utp-native version=2.5.3
      • rebuilding native dependency  name=leveldown version=6.0.1
      • packaging       platform=linux arch=x64 electron=13.2.2 appOutDir=dist/linux-unpacked
      ⨯ Application entry file "build/electron.js" in the "/home/raphy/Raphy-Template/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "build/electron.js" in the "/home/raphy/Raphy-Template/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
        at error (/home/raphy/Raphy-Template/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
        at Object.checkFileInArchive (/home/raphy/Raphy-Template/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
        at LinuxPackager.checkFileInPackage (/home/raphy/Raphy-Template/node_modules/app-builder-lib/src/platformPackager.ts:489:7)
        at LinuxPackager.sanityCheckPackage (/home/raphy/Raphy-Template/node_modules/app-builder-lib/src/platformPackager.ts:537:5)
        at LinuxPackager.doPack (/home/raphy/Raphy-Template/node_modules/app-builder-lib/src/platformPackager.ts:298:5)
        at LinuxPackager.pack (/home/raphy/Raphy-Template/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
        at Packager.doBuild (/home/raphy/Raphy-Template/node_modules/app-builder-lib/src/packager.ts:441:9)
        at Object.executeFinally (/home/raphy/Raphy-Template/node_modules/builder-util/src/promise.ts:12:14)
        at Packager._build (/home/raphy/Raphy-Template/node_modules/app-builder-lib/src/packager.ts:376:31)
        at Packager.build (/home/raphy/Raphy-Template/node_modules/app-builder-lib/src/packager.ts:337:12)
        at Object.executeFinally (/home/raphy/Raphy-Template/node_modules/builder-util/src/promise.ts:12:14)
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

node: v14.15.5
electron:  ^13.1.4
electron-builder: ^22.11.7
O.S: Ubuntu 20.04

What's wrong with my configuration? How to solve the problem?

**Comment by abhishekvarade9685** [comment]
Thanks for solution @exekg
