### ISSUE TITLE
checkIsOutdated TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by brandonros** [electron-userland/electron-builder#6216]
```
22.11.11
```

```
 $ uname -a
Darwin Brandons-MacBook-Air.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64
```

```
$ node -v
v16.4.2
```

```
$ npx electron-builder install-app-deps

/Users/brandonros/Desktop/foo/node_modules/electron-builder/out/cli/cli.js:59
        .then(async (it) => {
        ^
TypeError: Cannot read property 'then' of undefined
    at checkIsOutdated (/Users/brandonros/Desktop/foo/node_modules/electron-builder/out/cli/cli.js:59:9)
    at Object.handler (/Users/brandonros/Desktop/foo/node_modules/electron-builder/src/cli/cli.ts:50:5)
    at /Users/brandonros/Desktop/foo/node_modules/yargs/build/index.cjs:1:8973
    at j (/Users/brandonros/Desktop/foo/node_modules/yargs/build/index.cjs:1:4852)
    at _.applyMiddlewareAndGetResult (/Users/brandonros/Desktop/foo/node_modules/yargs/build/index.cjs:1:8942)
    at _.runCommand (/Users/brandonros/Desktop/foo/node_modules/yargs/build/index.cjs:1:7127)
    at Bt.[runYargsParserAndExecuteCommands] (/Users/brandonros/Desktop/foo/node_modules/yargs/build/index.cjs:1:52416)
    at Bt.parse (/Users/brandonros/Desktop/foo/node_modules/yargs/build/index.cjs:1:36100)
    at Bt.get [as argv] (/Users/brandonros/Desktop/foo/node_modules/yargs/build/index.cjs:1:55639)
    at Object.<anonymous> (/Users/brandonros/Desktop/foo/node_modules/electron-builder/src/cli/cli.ts:46:23)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    ```

**Comment by brandonros** [comment]
package-lock was giving me 22.13.x or something

**Comment by brandonros** [comment]
`NO_UPDATE_NOTIFIER=true` kind of makes it better?
