### ISSUE TITLE
Getting Error when building for mac

### ISSUE THREAD

**Issue by morpig** [electron-userland/electron-builder#625]
* **Version**: 5.20.0

* **Target**: Mac OS X

I'm getting error when doing 'build --mac'. Error Details:

Skip app dependencies rebuild because dev and app dependencies are not separated
Warning: Application icon is not set, default Electron icon will be used
Packaging for platform darwin x64 using electron 1.3.1 to dist/mac

node_modules/7zip-bin-osx is not packed into asar archive - contains executable code
node_modules/ds-store is not packed into asar archive - contains executable code
node_modules/electron-winstaller-fixed is not packed into asar archive - contains executable code
node_modules/rcedit is not packed into asar archive - contains executable code
node_modules/signcode-tf is not packed into asar archive - contains executable code
Unhandled rejection Error: ENOENT: no such file or directory, open '/Users/morpig/Documents/onetap-electron/dist/mac/Electron.app/Contents/Resources/app.asar.unpacked/node_modules/7zip-bin-osx/7za'
    at Error (native)
From previous event:
    at copyFile (/usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:392:9)
    at /usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:247:27
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at tsAwaiter (/usr/local/lib/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/usr/local/lib/node_modules/electron-builder/src/builder.ts:193:52)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

Unhandled rejection Error: ENOENT: no such file or directory, open '/Users/morpig/Documents/onetap-electron/dist/mac/Electron.app/Contents/Resources/app.asar.unpacked/node_modules/7zip-bin-osx/index.js'
    at Error (native)
From previous event:
    at copyFile (/usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:392:9)
    at /usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:247:27
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at tsAwaiter (/usr/local/lib/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/usr/local/lib/node_modules/electron-builder/src/builder.ts:193:52)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

Unhandled rejection Error: ENOENT: no such file or directory, open '/Users/morpig/Documents/onetap-electron/dist/mac/Electron.app/Contents/Resources/app.asar.unpacked/node_modules/7zip-bin-osx/LICENSE.txt'
    at Error (native)
From previous event:
    at copyFile (/usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:392:9)
    at /usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:247:27
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at tsAwaiter (/usr/local/lib/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/usr/local/lib/node_modules/electron-builder/src/builder.ts:193:52)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

Unhandled rejection Error: ENOENT: no such file or directory, open '/Users/morpig/Documents/onetap-electron/dist/mac/Electron.app/Contents/Resources/app.asar.unpacked/node_modules/7zip-bin-osx/package.json'
    at Error (native)
From previous event:
    at copyFile (/usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:392:9)
    at /usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:247:27
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at tsAwaiter (/usr/local/lib/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/usr/local/lib/node_modules/electron-builder/src/builder.ts:193:52)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

Error: ENOENT: no such file or directory, open '/Users/morpig/Documents/onetap-electron/dist/mac/Electron.app/Contents/Resources/app.asar.unpacked/node_modules/7zip-bin-osx/7za'
    at Error (native)
From previous event:
    at copyFile (/usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:392:9)
    at /usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:247:27
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at tsAwaiter (/usr/local/lib/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/usr/local/lib/node_modules/electron-builder/src/builder.ts:193:52)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

Any ideas?
Thanks

**Comment by develar** [comment]
It seems electron-builder not in your devDependencies — but must be here. It is not production dependency.
