### ISSUE TITLE
Snap file fails to publish

### ISSUE THREAD

**Issue by stamoun** [electron-userland/electron-builder#6253]
* **Electron-Builder Version**:  `22.11.7`

* **Node Version**: `v14.17.6`

* **Electron Version**: `11.2.1`
* **Electron Type (current, beta, nightly)**:

* **Target**: `ubuntu-latest`

I'm trying to get automated release update to publish binaries and so far Linux is failing (Mac and Windows seem ok, albeit unsigned binaries).

The builder fails with the following (full log here: https://github.com/stamoun/lofi/runs/3593349777?check_suite_focus=true)
```
...
  • uploading       file=lofi_1.6.0_amd64.snap provider=GitHub
  • creating GitHub release  reason=release doesn't exist tag=v1.6.0 version=1.6.0
  ⨯ Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
HttpError: 403 Forbidden
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-release"
}
Headers: {
  "server": "GitHub.com",
  "date": "Tue, 14 Sep 2021 00:19:32 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "136",
  "x-github-media-type": "github.v3; format=json",
  "x-ratelimit-limit": "1000",
  "x-ratelimit-remaining": "985",
  "x-ratelimit-reset": "1631582351",
  "x-ratelimit-used": "15",
  "x-ratelimit-resource": "core",
  "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
  "access-control-allow-origin": "*",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "content-security-policy": "default-src 'none'",
  "vary": "Accept-Encoding, Accept, X-Requested-With",
  "x-github-request-id": "0401:686B:13762D8:269AB6C:613FEA93",
  "connection": "close"
}
    at createHttpError (/home/runner/work/lofi/lofi/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at IncomingMessage.<anonymous> (/home/runner/work/lofi/lofi/node_modules/builder-util-runtime/src/httpExecutor.ts:179:18)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
...
```

Is it possible to create a `snap` file without a Ubuntu One account?

**Comment by stamoun** [comment]
Meant to post this on action-electron-builder page, closing this here.
