### ISSUE TITLE
electron-builder not build msi

### ISSUE THREAD

**Issue by msamgar** [electron-userland/electron-builder#6258]
Electron-Builder Version : 22.11.7

Node Version: 14.17.0

Electron Version: 12.0.9

Target: Windows(msi) 

I am trying to create msi file by getting build in my electron app. It returns me the following error. What is the reason?

PS C:\Projects\Klemsan Configuration Wizard> npm install

> KlemsanConfigurationWizard@1.0.0 install C:\Projects\Klemsan Configuration Wizard
> electron-builder

  • electron-builder  version=22.11.7 os=10.0.19043
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@serialport/bindings@9.2.0, lzma-native@8.0.1 platform=win32 arch=x64
  • install prebuilt binary  name=@serialport/bindings version=9.2.0 platform=win32 arch=x64 napi=
  • packaging       platform=win32 arch=x64 electron=12.0.9 appOutDir=dist\win-unpacked
  • building        target=MSI arch=x64 file=dist\Klemsan Configuration Wizard
  • MSI DOESN'T SUPPORT assisted installer. Please use NSIS instead.
  ⨯ Exit code: 311. Command failed: C:\Users\Administrator\AppData\Local\electron-builder\Cache\wix\wix-4.0.0.5512.2\light.exe -out C:\Projects\Klemsan Configuration Wizard\dist\Klemsan Configuration 
Wizard -v -spdb -sw1076 -dappDir=C:\Projects\Klemsan Configuration Wizard\dist\win-unpacked -pedantic -ext WixUIExtension project.wixobj WixUI_Assisted.wixobj
C:\Projects\Klemsan Configuration Wizard\dist\__msi-x64\project.wxs(5) : error LGHT0311 : A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.
C:\Projects\Klemsan Configuration Wizard\dist\__msi-x64\project.wxs(4) : error LGHT0311 : A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.

WiX Toolset Linker version 4.0.0.5512
Copyright (c) .NET Foundation and contributors. All rights reserved.

Updating file information.
Creating cabinet files.
There will be '8' threads used to produce CAB files.
Creating cabinet 'C:\Users\Administrator\AppData\Local\Temp\wix210914T1713253004\#cab1.cab'.
Creating cabinet 'C:\Users\Administrator\AppData\Local\Temp\wix210914T1713253004\#cab2.cab'.
Generating database.

C:\Projects\Klemsan Configuration Wizard\dist\__msi-x64\project.wxs(5) : error LGHT0311 : A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.
C:\Projects\Klemsan Configuration Wizard\dist\__msi-x64\project.wxs(4) : error LGHT0311 : A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.
  failedTask=build stackTrace=Error: Exit code: 311. Command failed: C:\Users\Administrator\AppData\Local\electron-builder\Cache\wix\wix-4.0.0.5512.2\light.exe -out C:\Projects\Klemsan Configuration Wizard\dist\Klemsan Configuration Wizard -v -spdb -sw1076 -dappDir=C:\Projects\Klemsan Configuration Wizard\dist\win-unpacked -pedantic -ext WixUIExtension project.wixobj WixUI_Assisted.wixobj
C:\Projects\Klemsan Configuration Wizard\dist\__msi-x64\project.wxs(5) : error LGHT0311 : A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.
C:\Projects\Klemsan Configuration Wizard\dist\__msi-x64\project.wxs(4) : error LGHT0311 : A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.

WiX Toolset Linker version 4.0.0.5512
Copyright (c) .NET Foundation and contributors. All rights reserved.

Updating file information.
Creating cabinet files.
There will be '8' threads used to produce CAB files.
Creating cabinet 'C:\Users\Administrator\AppData\Local\Temp\wix210914T1713253004\#cab1.cab'.
Creating cabinet 'C:\Users\Administrator\AppData\Local\Temp\wix210914T1713253004\#cab2.cab'.
Generating database.

C:\Projects\Klemsan Configuration Wizard\dist\__msi-x64\project.wxs(5) : error LGHT0311 : A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.
C:\Projects\Klemsan Configuration Wizard\dist\__msi-x64\project.wxs(4) : error LGHT0311 : A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.

    at C:\Projects\Klemsan Configuration Wizard\node_modules\builder-util\src\util.ts:132:18
    at ChildProcess.exithandler (child_process.js:326:5)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! KlemsanConfigurationWizard@1.0.0 install: `electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the KlemsanConfigurationWizard@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-09-14T14_15_14_085Z-debug.log

**Comment by msamgar** [comment]
I did not particularly understand what this phrase means "MSI DOESN'T SUPPORT assisted installer". I've done many successful compilations before. When the compilation will be successful, it connects to wix's github address and downloads. Can you explain why this is out of the blue?

**Comment by msamgar** [comment]
I found the source of the problem. I noticed that the msi file was not created due to a character I used in the package.json file. If you can't compile msi, check the characters in the project! Avoid any use other than English characters!
