### ISSUE TITLE
Electron Builder - Could not load file or assembly 'System.Core'

### ISSUE THREAD

**Issue by acuemor** [electron-userland/electron-builder#630]
* **Version**: 5.22.1

* **Target**: Windows x64

* **WIne**: 1.8
* **Electron prebuilt**: 1.3.1

I'm trying to build my app from Ubuntu 14.04 and get my Windows MSI, but I'm finding many problems.

This is my package.json (I only maintain one in root app):

> {
    "name": "MyAPP",
    "description": "MyAPP Desc",
    "version": "0.0.2",
    "author": {
        "name": "Me",
        "email": "me@email.com"
    },
    "main": "build/main.min.js",
    "scripts": {
        "start": "electron .",
        "pack": "gulp compile && build --dir",
        "dist": "gulp compile && build -w --x64"
    },
    "devDependencies": {
        "del": "^2.2.0",
        "electron-builder": "^5.22.1",
        "electron-packager": "^7.3.0",
        "electron-prebuilt": "^1.3.1",
        "gulp": "^3.9.1",
        "gulp-bower": "0.0.13",
        "gulp-clean-css": "^2.0.6",
        "gulp-ng-annotate": "^2.0.0",
        "gulp-rename": "^1.2.2",
        "gulp-sass": "^2.3.1",
        "gulp-scss-lint": "^0.3.9",
        "gulp-server-livereload": "^1.7.4",
        "gulp-shell": "^0.5.2",
        "gulp-tsc": "^1.2.0",
        "gulp-uglify": "^1.5.3",
        "run-sequence": "^1.1.5",
        "typings": "^1.0.4"
    },
    "dependencies": {
        "fs-extra": "^0.30.0",
        "nedb": "^1.8.0"
    },
    "build": {
        "appId": "com.electron.mdbmt",
        "files": [ "build\/**\/*", "node_modules\/**\/*" ]
    },
    "directories": {
        "buildResources": "tmp-build",
        "output": "dist",
        "app": "."
    }
}

Here is my Squirrel file:

> const electron = require("electron");
const app = electron.app;  // Module to control application life.
import { spawn } from "child_process";
import * as path from "path";
function run(args: string[], done: Function): void {
  const updateExe = path.resolve(path.dirname(process.execPath), "..", "Update.exe");
  console.log("Spawning `%s` with args `%s`", updateExe, args);
  spawn(updateExe, args, {
    detached: true
  })
    .on("close", done);
}
export default function handleStartupEvent(): boolean {
  if (process.platform !== "win32" || process.platform !== "win64") {
      console.log("[handleStartupEvent] Error in process platform");
      return false;
  }
  const cmd = process.argv[1];
  console.log("Processing squirrel command `%s`", cmd);
  const target = path.basename(process.execPath);
  if (cmd === "--squirrel-install" || cmd === "--squirrel-updated") {
    run(["--createShortcut=" + target + ""], app.quit);
    return true;
  }
  else if (cmd === "--squirrel-uninstall") {
    run(["" + target + ""], app.quit);
    return true;
  }
  else if (cmd === "--squirrel-obsolete") {
    app.quit();
    return true;
  }
  else {
    return false;
  }
}

And here is the error I get:

> Building Squirrel.Windows installer
Error: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  at Squirrel.Update.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
Error: Command failed: mono /mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-winstaller-fixed/vendor/Update-Mono.exe --releasify /mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/dist/win/AlstomX05App-0.0.2-full.nupkg --releaseDir /mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/dist/win
System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  at Squirrel.Update.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
  at Squirrel.Update.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
  at Squirrel.Update.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
    at /mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-winstaller-fixed/lib/spawn-promise.js:56:18
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js: 100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at exec (/mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-winstaller-fixed/lib/spawn-promise.js:45:10)
    at /mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-winstaller-fixed/lib/index.js:188:47
    at next (native)
From previous event:
    at releasify (/mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-winstaller-fixed/lib/index.js:204:16)
    at /mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-winstaller-fixed/lib/index.js:86:32
From previous event:
    at build (/mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-winstaller-fixed/lib/index.js:107:16)
    at Object.<anonymous> (/mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-winstaller-fixed/lib/index.js:31:13)
    at next (native)
    at /mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/fs-extra/lib/mkdirs/mkdirs.js:35:14
    at FSReqWrap.oncomplete (fs.js:82:15)
From previous event:
    at Object.createWindowsInstaller (/mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-winstaller-fixed/lib/index.js:41:16)
    at SquirrelWindowsTarget.<anonymous> (/mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-builder/src/targets/squirrelWindows.ts:30:33)
    at next (native)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at tsAwaiter (/mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-builder/src/builder.ts:195:52)
    at Object.<anonymous> (/mnt/Datos/Tribalyte/Proyectos/AlstomX05 App/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

**Comment by develar** [comment]
Windows MSI can be generated only on MS Windows. And are you sure that you want MSI (https://github.com/electron/windows-installer/issues/40#issuecomment-198744879)?
