### ISSUE TITLE
ENOENT: .org.chromium.Chromium.cO0UIo/SingletonSocket

### ISSUE THREAD

**Issue by CodingMonkeyzh** [electron-userland/electron-builder#6363]
* **Electron-Builder Version**:  22.13.1

* **Node Version**: v14.17.5

* **Electron Version**:13.4.0
* **Electron Type (current, beta, nightly)**:current

* **Target**: platform=darwin arch=x64

When I packaging the app, I got a "ENOENT" error:
```
• electron-builder  version=22.13.1 os=20.6.0
• author is missed in the package.json  appPackageFile=/Users/welcome/workspace/electron-demo/package.json
• writing effective config  file=dist/builder-effective-config.yaml
• packaging       platform=darwin arch=x64 electron=13.4.0 appOutDir=dist/mac
⨯ ENOENT: no such file or directory, stat '/var/folders/d7/y13nz5z92rj4f82vc0cfzym40000gn/T/.org.chromium.Chromium.cO0UIo/SingletonSocket'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, stat '/var/folders/d7/y13nz5z92rj4f82vc0cfzym40000gn/T/.org.chromium.Chromium.cO0UIo/SingletonSocket'
at processImmediate (internal/timers.js:464:21)
From previous event:
at Object.walk (/Users/welcome/workspace/electron-demo/node_modules/builder-util/src/fs.ts:76:51)
at Object.computeFileSets (/Users/welcome/workspace/electron-demo/node_modules/app-builder-lib/src/util/appFileCopier.ts:158:19)
at async Promise.all (index 0)
at AsyncTaskManager.awaitTasks (/Users/welcome/workspace/electron-demo/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
at MacPackager.doPack (/Users/welcome/workspace/electron-demo/node_modules/app-builder-lib/src/platformPackager.ts:276:5)
at MacPackager.pack (/Users/welcome/workspace/electron-demo/node_modules/app-builder-lib/src/macPackager.ts:177:7)
at Packager.doBuild (/Users/welcome/workspace/electron-demo/node_modules/app-builder-lib/src/packager.ts:441:9)
at Object.executeFinally (/Users/welcome/workspace/electron-demo/node_modules/builder-util/src/promise.ts:12:14)
at Packager._build (/Users/welcome/workspace/electron-demo/node_modules/app-builder-lib/src/packager.ts:376:31)
at Packager.build (/Users/welcome/workspace/electron-demo/node_modules/app-builder-lib/src/packager.ts:337:12)
at Object.executeFinally (/Users/welcome/workspace/electron-demo/node_modules/builder-util/src/promise.ts:12:14)
```

I have searched this issue, but not find any resolution

**Comment by vitalygashkov** [comment]
I have the same issue.
