### ISSUE TITLE
Cannot download differentially, fallback to full download: Error: Cannot parse blockmap 

### ISSUE THREAD

**Issue by Ibrahim-CloudLabs** [electron-userland/electron-builder#6399]
"electron-updater": "^4.3.9",
"electron-builder": "^22.13.1",

**The Error** 
`[info]  Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: Pr7EPgqtXBqw4tc2nWhFMTaWlsXDvPXbvBtiw9zkAHDd8ubRPvE5kzkf+0IJseNTKrGavqibCxiVT9xILodDIQ==, expected: 4S5pPwyrzFfZyqT6nxTB2dP8EmnP6IaMtEbzHnHQlpAX7LOExO1oH+F2H8V7US4LrERsGaQjIzhRHAE1d4vp2Q==. Directory for cached update will be cleaned`

`[error] Cannot download differentially, fallback to full download: Error: Cannot parse blockmap "https://api.github.com/repos/Ibrahim-CloudLabs/CloudReignLocal/releases/assets/48725451.blockmap", error: Error: incorrect header check, `

**Comment by Ibrahim-CloudLabs** [comment]
@NGrey5

**Comment by Ibrahim-CloudLabs** [comment]
@sandeep1995  I used ` npm i electron-updater@4.4.6` like you said in https://github.com/electron-userland/electron-builder/issues/4736#issuecomment-939804876 and it worked 
```

**Comment by Ibrahim-CloudLabs** [comment]
> @sandeep1995 I used ` npm i electron-updater@4.4.6` like you said in [#4736 (comment)](https://github.com/electron-userland/electron-builder/issues/4736#issuecomment-939804876) @sandeep1995 The application updates and I still get the error in the log. Here is my log 

```
[info]  App starting...
[info]  Checking for update
[info]  Current Version 1.1.8
 [info]  Found version 1.1.9 (url: CloudReignLocal-Setup-1.1.9.exe)
 [info]  update-available
 [info]  Downloading update from CloudReignLocal-Setup-1.1.9.exe
[info]  Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: 82uAwQhblwo6NSS0pNXHuiuzQsTrnuBniOGXjFJRSECM2k8tufMniNmcqnSv/5voU0wbSO29TJoqFHidJNzBbQ==, expected: fnVK4GWbwtl/CzZXUK0hzeRCKwO5jpGZGEvE+uEYOhHp3ecZ/+1sc3zpb25hc1533HXGSfkRcLbCfXi4GYvq0Q==. Directory for cached update will be cleaned
[2021-11-07 12:01:45.746] [info]  Download block maps (old: "https://api.github.com/repos/Ibrahim-CloudLabs/CloudReignLocal/releases/assets/48840557.blockmap", new: https://api.github.com/repos/Ibrahim-CloudLabs/CloudReignLocal/releases/assets/48840557.blockmap)
[2021-11-07 12:03:14.699] [error] Cannot download differentially, fallback to full download: Error: Cannot parse blockmap "https://api.github.com/repos/Ibrahim-CloudLabs/CloudReignLocal/releases/assets/48840557.blockmap", error: Error: incorrect header check
    at a (C:\Users\Ibrah\AppData\Local\Programs\CloudReignLocal\resources\app.asar\.webpack\main\index.js:2:118025)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async g.differentialDownloadInstaller (C:\Users\Ibrah\AppData\Local\Programs\CloudReignLocal\resources\app.asar\.webpack\main\index.js:2:118447)
    at async Object.task (C:\Users\Ibrah\AppData\Local\Programs\CloudReignLocal\resources\app.asar\.webpack\main\index.js:2:115946)
    at async g.executeDownload (C:\Users\Ibrah\AppData\Local\Programs\CloudReignLocal\resources\app.asar\.webpack\main\index.js:2:105741)
```

Also my application size is 615MB which is unusual. Any thoughts on this ?

**Comment by DanTaira** [comment]
I am also getting the same error.

"electron-updater": "^4.4.6"
"electron-builder": "^22.13.1"
"electron": "^15.1.2"

**Comment by mustafaabobakr** [comment]
Same. any news?

**Comment by Seraphli** [comment]
I'm having the same issue. I find out the URL of the block map should not be the "https://api.github.com/repos/somerepo/releases/assets/55976248.blockmap" with the URL of setup.exe is "https://api.github.com/repos/somerepo/releases/assets/55976248" when I use curl to call Github API.
So it might be a URL parse error.

**Comment by axelmy318** [comment]
I also face the same issue...
```
{
    "electron": "^12.2.3",
    "electron-builder": "23.0.3",
    "electron-updater": "^4.4.6",
}
```

Was anyone able to fix it yet ?

**Comment by FringeNet** [comment]
```
{
    "electron-updater": "^6.6.2",
    "electron": "^37.2.4",
    "electron-builder": "^26.0.12"
}
```
In _packages/electron-updater/src/AppUpdater.ts_ at _downloadBlockMap_:
```
try {
          return JSON.parse(gunzipSync(data).toString())
        } catch (e: any) {
          throw new Error(`Cannot parse blockmap "${url.href}", error: ${e}`)
        }
```
Potential fix?:
```
// first try parsing as plain JSON
        const jsonString = data.toString()
        try {
          return JSON.parse(jsonString)
        } catch (originalError: any) {
          // if gzip magic header, try gunzip then parse
          if (data[0] === 0x1f && data[1] === 0x8b) {
            try {
              const uncompressed = gunzipSync(data).toString()
              return JSON.parse(uncompressed)
            } catch (e2: any) {
              throw new Error(`Cannot parse gzipped blockmap "${url.href}", error: ${e2}. Original parse error: ${originalError}`)
            }
          }
          throw new Error(`Cannot parse blockmap "${url.href}", error: ${originalError}`)
        }
```

I will test this, this is happening for me as well
