### ISSUE TITLE
Cannot read property 'port' of null at getServerUrl error

### ISSUE THREAD

**Issue by yceballost** [electron-userland/electron-builder#6465]
Apparently same problem like this issue #6170

Electron-Builder Version: **v22.11.11**
Node Version: **v16.13.0**
Electron Version: **v9.4.4**
Electron-updater: **4.6.1**

When a new version is released in Github, app download the new version but at the moment of restart the app, this dialog appears.

```
Uncaught Exception:
TypeError: Cannot read property 'port' of null
at getServerUrl (/Applications/MisticaManager.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:40:48)
at Server.<anonymous> (/Applications/MisticaManager.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:62:67)
at Server.emit (events.js:223:5)
at parserOnIncoming (_http_server.js:748:12)
at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
```

![Screen Shot 2021-12-01 at 14 24 37](https://user-images.githubusercontent.com/6722153/144276475-2195d6db-a165-4484-9a60-a00a435e4fe6.png)

**Comment by aguynamedben** [comment]
Is anybody else seeing this? Last time this happened it was really bad for us.

**Comment by mfranzs** [comment]
We're encountering this as well on MacOS with:
- **electron-builder**: 22.10.5
- **electron**: 15.3.1
- **electron-updater**: 4.3.5

Do you both still have this issue?

**Comment by aguynamedben** [comment]
Not stale as of Jan 24
