### ISSUE TITLE
Build fails with multiple architecture in Mac

### ISSUE THREAD

**Issue by sibiraj-sr** [electron-userland/electron-builder#6486]
* **Electron-Builder Version**: 
v22.14.5

* **Node Version**: 
v14.15.1, v16.13.1

* **Electron Version**:
16.0.4

* **Electron Type (current, beta, nightly)**:
current

* **Target**: 

```yml
mac:
  target:
    target: dmg
    arch:
      - x64
      - arm64
```

The build works for the first time without any issues. But from the second time onwards it fails with error.

```
Error #1 --------------------------------------------------------------------------------
Error: Exit code: 1. Command failed: /usr/bin/python /Users/ghost/Documents/Electron/app/desktop/node_modules/dmg-builder/vendor/dmgbuild/core.py
Traceback (most recent call last):
  File "/Users/ghost/Documents/Electron/app/desktop/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 282, in <module>
    build_dmg()
  File "/Users/ghost/Documents/Electron/app/desktop/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 249, in build_dmg
    alias = Alias.for_file(background_file)
  File "/Users/ghost/Documents/Electron/app/desktop/node_modules/dmg-builder/vendor/mac_alias/alias.py", line 390, in for_file
    st = osx.statfs(path)
  File "/Users/ghost/Documents/Electron/app/desktop/node_modules/dmg-builder/vendor/mac_alias/osx.py", line 959, in statfs
    raise OSError(err, os.strerror(err), path)

OSError: [Errno 2] No such file or directory: '/Volumes/Electron/.background/background.png'
```

The same works well with only one arch defined. either x64 or arm64.

Using 2019 Macbook Pro.

**Comment by sibiraj-sr** [comment]
This issue is no longer happening in v23.
