### ISSUE TITLE
Error on Autoupdater.  ReferenceError: info is not defined

### ISSUE THREAD

**Issue by MarkPhsd** [electron-userland/electron-builder#6500]
Auto updater is failing after updating to node 14.17.0.  

 I had fs/promise issue and updated to node 14.17.0 to resolve the issue as shown in other posts. However, now I received this error from my electron log; I have to use electron 11 because it supports kiosk printing, and that is the last version I know that does this. I have tried just win32 and just win64 bit. 

[2021-12-15 00:55:00.998] [info]  App starting...
[2021-12-15 00:55:03.023] [info]  checkForUpdatesAndNotify
[2021-12-15 00:55:03.024] [info]  Checking for update
[2021-12-15 00:55:03.025] [info]  checking autoUpdater for App.on
[2021-12-15 00:55:03.025] [info]  Checking for update (already in progress)
[2021-12-15 00:55:03.029] [error] Error: ReferenceError: info is not defined
    at NsisUpdater.<anonymous> (C:\Users\ccs\AppData\Local\Programs\appname\resources\app.asar\index.js:347:12)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.doCheckForUpdates (C:\Users\ccs\AppData\Local\Programs\appname\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:302:14)
    at NsisUpdater.checkForUpdates (C:\Users\ccs\AppData\Local\Programs\appname\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:180:39)
    at NsisUpdater.checkForUpdatesAndNotify (C:\Users\ccs\AppData\Local\Programs\appname\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:205:21)
    at App.<anonymous> (C:\Users\ccs\AppData\Local\Programs\appname\resources\app.asar\index.js:199:17)
    at App.emit (events.js:327:22)

  node version v14.17.0

  "dependencies": {
    "@capacitor/electron": "^2.4.8",
    "electron-is-dev": "^1.1.0",
    "electron-log": "^4.4.0",
    "electron-updater": "^4.3.9",
    "winreg": "^1.2.4"
  },
  "devDependencies": {
    "electron": "^11.0.0",
    "electron-builder": "^22.14.5",
    "electron-reloader": "^1.2.1"
  },

my script

"deploy Multi Platform": "electron-builder build --win --x64 --ia32 --publish always postinstall",
"postinstall": "electron-builder install-app-deps",

**Comment by MarkPhsd** [comment]
I solved this by copying all the dependencies from a electron updater demo git.

**Comment by robertpatrick** [comment]
@MarkPhsd If this is still blocking you, you might want to try with the `latest` version of `electron-updater` to see if this resolves the issue.  If you are past this, I would suggest that you close this issue (since others, including me, are using the latest versions successfully on Windows (MacOS and Linux too).
