### ISSUE TITLE
Missing libudev-dev package for rebuild native dependencies (usb-detection)

### ISSUE THREAD

**Issue by lauer** [electron-userland/electron-builder#6569]
* **Electron-Builder Version**: 22.14.5

* **Node Version**:  v14.17.0

* **Electron Version**: 16.0.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

Using the following command to startup electron builder with wine

`docker run --rm -ti  \
        --platform linux/amd64 \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_')  \
        --env ELECTRON_CACHE="/root/.cache/electron"  \
        --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
         -v ${PWD}:/project \
         -v ${PWD##*/}-node-modules:/project/node_modules  -v ~/.cache/electron:/root/.cache/electron  -v ~/.cache/electron-builder:/root/.cache/electron-builder \
         electronuserland/builder:wine`

But when building app with prebuild for usb-detection (4.13.0) it fails with 

`    ../src/detection_linux.cpp:1:10: fatal error: libudev.h: No such file or directory
        1 | #include <libudev.h>
          |          ^~~~~~~~~~~
    compilation terminated.`

It works fine, if I run `apt-get update && apt-get install libudev-dev` before the `yarn build`

So maybe that would be nice to have included in the docker image?

**Comment by lauer** [comment]
Maybe not the complete solution. I still get error when I want to dist the packages.

  electron-builder -w --x64 -p never
    • electron-builder  version=22.14.5 os=4.15.0-162-generic
    • loaded configuration  file=package.json ("build" field)
    • writing effective config  file=dist/builder-effective-config.yaml
    • rebuilding native dependencies  dependencies=node-hid@2.1.1, usb@1.9.1, usb-detection@4.13.0 platform=win32 arch=x64
    • install prebuilt binary  name=usb-detection version=4.13.0 platform=win32 arch=x64 napi=
    • install prebuilt binary  name=node-hid version=2.1.1 platform=win32 arch=x64 napi=
                                                                                          ⨯ cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
                                      cause=exit status 1
                                      errorOut=/project/node_modules/node-abi/index.js:36
        throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
        ^

    Error: Could not detect abi for version 16.0.4 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (/project/node_modules/node-abi/index.js:36:9)
        at module.exports (/project/node_modules/prebuild-install/rc.js:52:57)
        at Object.<anonymous> (/project/node_modules/prebuild-install/bin.js:8:25)
        at Module._compile (internal/modules/cjs/loader.js:1068:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
        at Module.load (internal/modules/cjs/loader.js:933:32)
        at Function.Module._load (internal/modules/cjs/loader.js:774:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        at internal/main/run_main_module.js:17:47

                                    command=/usr/local/bin/node /project/node_modules/prebuild-install/bin.js --platform=win32 --arch=x64 --target=16.0.4 --runtime=electron --verbose --force
                                    workingDir=/project/node_modules/usb-detection
error Command failed with exit code 1.`
