### ISSUE TITLE
EEXIST dmg icon.icns after update

### ISSUE THREAD

**Issue by perry-mitchell** [electron-userland/electron-builder#6570]
* **Electron-Builder Version**: 22.14.5

* **Node Version**: 16.13.1

* **Electron Version**: 15.3.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac / dmg

After updating minor dependencies in [Buttercup password manager](https://github.com/buttercup/buttercup-desktop) (and electron-builder to `22.14.5`), I'm getting the following error:
```
  ⨯ EEXIST: file already exists, link '/Users/runner/work/buttercup-desktop/buttercup-desktop/resources/build/icon.icns' -> '/Users/runner/work/buttercup-desktop/buttercup-desktop/dist/mac/Electron.app/Contents/Resources/icon.icns'  failedTask=build stackTrace=Error: EEXIST: file already exists, link '/Users/runner/work/buttercup-desktop/buttercup-desktop/resources/build/icon.icns' -> '/Users/runner/work/buttercup-desktop/buttercup-desktop/dist/mac/Electron.app/Contents/Resources/icon.icns'
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.createMacApp (/Users/runner/work/buttercup-desktop/buttercup-desktop/node_modules/app-builder-lib/src/electron/electronMac.ts:192:60)
/Users/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:144
    at beforeCopyExtraFiles (/Users/runner/work/buttercup-desktop/buttercup-desktop/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:86:5)
				throw err;
    at MacPackager.doPack (/Users/runner/work/buttercup-desktop/buttercup-desktop/node_modules/app-builder-lib/src/platformPackager.ts:283:7)
				^
    at MacPackager.pack (/Users/runner/work/buttercup-desktop/buttercup-desktop/node_modules/app-builder-lib/src/macPackager.ts:177:7)

    at Packager.doBuild (/Users/runner/work/buttercup-desktop/buttercup-desktop/node_modules/app-builder-lib/src/packager.ts:441:9)
```
You can see it failing in [this action](https://github.com/buttercup/buttercup-desktop/runs/4906812696?check_suite_focus=true).

EDIT: After [reverting](https://github.com/buttercup/buttercup-desktop/commit/637ba7b7152aa620a20bbd6321551013fc5b60ff#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) the upgrade, everything [works](https://github.com/buttercup/buttercup-desktop/runs/4906854567?check_suite_focus=true). Revert ended up giving me version `22.11.11` which does not show this error.

**Comment by mmaietta** [comment]
Is this error isolated only to the electron-builder-action? I'd expect to have heard more issues with Github Actions with22.14.5  being out for over 4 months.
Can you try version `22.14.13`?

**Comment by 1zilc** [comment]
> Is this error isolated only to the electron-builder-action? I'd expect to have heard more issues with Github Actions with22.14.5 being out for over 4 months. Can you try version `22.14.13`?

[Problem](https://github.com/1zilc/fishing-funds/runs/5103608140?check_suite_focus=true) still exist on 22.14.13

**Comment by 1zilc** [comment]
https://github.com/electron-userland/electron-builder/issues/4301 finally solved my problem

**Comment by perry-mitchell** [comment]
Still seeing this on 23.6.0. #4301 did _not_ solve it for me.

**Comment by c3er** [comment]
@perry-mitchell 

> After [reverting](https://github.com/buttercup/buttercup-desktop/commit/637ba7b7152aa620a20bbd6321551013fc5b60ff#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) the upgrade, everything [works](https://github.com/buttercup/buttercup-desktop/runs/4906854567?check_suite_focus=true). Revert ended up giving me version 22.11.11 which does not show this error.

Interesting. I get the same error and using the mentioned version 22.11.11 did not change anything about that
