### ISSUE TITLE
dmg-license is listed as an optional dependency, yet build fails if it's not installed.

### ISSUE THREAD

**Issue by dscalzi** [electron-userland/electron-builder#6573]
* **Electron-Builder Version**: 22.13.1

* **Node Version**: 16.13.2

* **Electron Version**: 15.2.0
* **Electron Type (current, beta, nightly)**: Current

* **Target**: Multi-platform build (failure is during macOS build.

Installed dependencies using `npm ci --no-optional`. The build fails with the stack trace posted below.

Typically if a dependency is optional, the build should not fail when it is excluded. Perhaps it's more appropriate to move this to a required dependency if it is required to build macOS.

My mac config:

```
# macOS Configuration
mac:
  target:
    - target: 'dmg'
      arch:
        - 'x64'
        - 'arm64'
  artifactName: '${productName}-setup-${version}-${arch}.${ext}'
  category: 'public.app-category.games'
```

Failure:
```
> electron-builder build

  • electron-builder  version=22.13.1 os=19.6.0
  • artifacts will be published if draft release exists  reason=CI detected
  • loaded configuration  file=/Users/runner/work/HeliosLauncher/HeliosLauncher/electron-builder.yml
  ⨯ Cannot find module 'dmg-license'
Require stack:
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/dmg-builder/out/dmgLicense.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/dmg-builder/out/dmg.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/dmg-builder/out/dmgUtil.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/app-builder-lib/out/macPackager.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/app-builder-lib/out/packager.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/app-builder-lib/out/index.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/electron-builder/out/builder.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/electron-builder/out/cli/cli.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/electron-builder/cli.js  failedTask=build stackTrace=Error: Cannot find module 'dmg-license'
Require stack:
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/dmg-builder/out/dmgLicense.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/dmg-builder/out/dmg.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/dmg-builder/out/dmgUtil.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/app-builder-lib/out/macPackager.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/app-builder-lib/out/packager.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/app-builder-lib/out/index.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/electron-builder/out/builder.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/electron-builder/out/cli/cli.js
- /Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/dmg-builder/src/dmgLicense.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/dmg-builder/src/dmg.ts:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/runner/work/HeliosLauncher/HeliosLauncher/node_modules/dmg-builder/src/dmgUtil.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

**Comment by mmaietta** [comment]
It's required for Mac builds, but it needs to remain optional in order for electron-builder to be installable on windows/linux. Not sure if there's a way to resolve this issue (PR is welcome. Dev env setup is fairly simple: https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment)

**Comment by levitemkin** [comment]
This issue is preventing me from building entirely. I'm building on Linux, and I'm not even packaging an OSX app, but electron-builder won't proceed without the dmg-license package. And I can't install dmg-license, since it's restricted to OSX.

**Comment by levitemkin** [comment]
This issue is preventing me from building entirely. "electron-builder -mwl" won't proceed without dmg-license, but since I'm building on Linux, I can't install dmg-license. I don't even have a dmg target in my package.json.

**Comment by dscalzi** [comment]
I'm not sure how it works, but couldnt you just package a prebuilt and optionally load it if the platform is darwin?
