### ISSUE TITLE
Mac Universal Build - fs.rm is not a function

### ISSUE THREAD

**Issue by TC-mSundaram** [electron-userland/electron-builder#6588]
* **Electron-Builder Version**: 22.14.5

* **Node Version**: 14.12.0

* **Electron Version**: 16.0.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: Mac Universal
* **Platform**: macOS Catalina / Intel

```
electron-builder --mac --universal --config build/electron-builder.json --publish never
```

```electron-builder.json
{
...
  "mac": {
    "artifactName": "${productName}.${ext}",
    "entitlements": "./build/entitlements.mac.plist",
    "entitlementsInherit": "./build/entitlements.mac.plist",
    "gatekeeperAssess": false,
    "hardenedRuntime": true,
    "icon": "app/src/assets/icons/icon.icns",
    "target": ["dmg", "zip"]
  },
...
}
```

With the above I get the following issue:

```
  • electron-builder  version=22.14.5 os=19.6.0
  • loaded configuration  file=/Users/maheshsundaram/src/github.com/company/electron-app/build/electron-builder.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=16.0.7 appOutDir=dist/mac-universal--x64
  • packaging       platform=darwin arch=arm64 electron=16.0.7 appOutDir=dist/mac-universal--arm64
  • packaging       platform=darwin arch=universal electron=16.0.7 appOutDir=dist/mac-universal
  ⨯ fs.rm is not a function  failedTask=build stackTrace=TypeError: fs.rm is not a function
    at MacPackager.doPack (/Users/maheshsundaram/src/github.com/company/electron-app/node_modules/app-builder-lib/src/macPackager.ts:131:18)
    at MacPackager.pack (/Users/maheshsundaram/src/github.com/company/electron-app/node_modules/app-builder-lib/src/macPackager.ts:177:7)
    at Packager.doBuild (/Users/maheshsundaram/src/github.com/company/electron-app/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/maheshsundaram/src/github.com/company/electron-app/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/maheshsundaram/src/github.com/company/electron-app/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/maheshsundaram/src/github.com/company/electron-app/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/maheshsundaram/src/github.com/company/electron-app/node_modules/builder-util/src/promise.ts:12:14)
```

I suspect that I'm doing something obviously wrong.

**Comment by mmaietta** [comment]
Could you please try updating to node 14.14+?
fs.rm was introduced in 14.14.0
https://nodejs.org/docs/latest-v14.x/api/fs.html#fs_fspromises_rm_path_options

**Comment by TC-mSundaram** [comment]
Thank you! That unblocked me.
