### ISSUE TITLE
Code sign failing for Mac build

### ISSUE THREAD

**Issue by drewberk** [electron-userland/electron-builder#6591]
* **Electron-Builder Version**: 22.14.5

* **Node Version**: v16.13.2

* **Electron Version**: 13.6.6
* **Electron Type (current, beta, nightly)**: current

* **Electron Updater**: 4.6.1

* **Target**: Mac

We have been building our Electron app on Azure DevOps pipelines for over a year with a lot of success thanks to electron-builder. We've recently updated all of our NPM packages because Microsoft has sunset the old Mac build environment we were using. I have gotten most of the issues with these package updates resolved. However, I cannot figure out why our Mac version is failing during code signing. 

The error logs are pasted below. Note that I have removed some text for privacy reasons and replaced with "<redacted>".

Any advice on how to fix this is greatly appreciated.

```
Setting signing certificate and password for mac build.
  • electron-builder  version=22.5.1 os=20.6.0
  • installing production dependencies  platform=darwin arch=x64 appDir=/Users/runner/work/1/s/<redacted>/dist
  • packaging       platform=darwin arch=x64 electron=13.6.6 appOutDir=build/mac
  • downloading     url=https://github.com/electron/electron/releases/download/v13.6.6/electron-v13.6.6-darwin-x64.zip size=79 MB parts=6
  • downloaded      url=https://github.com/electron/electron/releases/download/v13.6.6/electron-v13.6.6-darwin-x64.zip duration=1.347s
  • signing         file=build/mac/<redacted> identityName=Developer ID Application: <redacted> (A26Y3LF6F4) identityHash=4F49B6F658862159A99E65EF98D46E1576CCDC30 provisioningProfile=<redacted>.provisionprofile
Error: Command failed: codesign --sign 4F49B6F658862159A99E65EF98D46E1576CCDC30 --force --keychain /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/e37dba408c3cf2bfdc5cd4c8c9e9e9199cc8707705bbec05268f3f83f699169c.keychain --timestamp --options runtime --entitlements entitlements.mac.plist /Users/runner/work/1/s/<redacted>.Electron/build/mac/<redacted>.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/Users/runner/work/1/s/<redacted>.Electron/build/mac/<redacted>.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
In subcomponent: /Users/runner/work/1/s/<redacted>.Electron/build/mac/<redacted>.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at Pipe.<anonymous> (node:net:687:12)
From previous event:
    at processImmediate (node:internal/timers:464:21)
From previous event:
    at MacPackager.signApp (/Users/runner/work/1/s/<redacted>.Electron/node_modules/app-builder-lib/src/macPackager.ts:329:27)
    at MacPackager.doPack (/Users/runner/work/1/s/<redacted>.Electron/node_modules/app-builder-lib/src/platformPackager.ts:244:16)
    at MacPackager.pack (/Users/runner/work/1/s/<redacted>.Electron/node_modules/app-builder-lib/src/macPackager.ts:130:7)
    at Packager.doBuild (/Users/runner/work/1/s/<redacted>.Electron/node_modules/app-builder-lib/src/packager.ts:444:9)
    at executeFinally (/Users/runner/work/1/s/<redacted>.Electron/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/runner/work/1/s/<redacted>.Electron/node_modules/app-builder-lib/src/packager.ts:373:31)
    at Packager.build (/Users/runner/work/1/s/<redacted>.Electron/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/Users/runner/work/1/s/<redacted>.Electron/node_modules/builder-util/src/promise.ts:12:14) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'codesign --sign 4F49B6F658862159A99E65EF98D46E1576CCDC30 --force --keychain /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/e37dba408c3cf2bfdc5cd4c8c9e9e9199cc8707705bbec05268f3f83f699169c.keychain --timestamp --options runtime --entitlements entitlements.mac.plist /Users/runner/work/1/s/<redacted>.Electron/build/mac/<redacted>.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework'
}
error Command failed with exit code 1.

```

**Comment by mmaietta** [comment]
Can you try updating to the latest version? Your console logs show `electron-builder  version=22.5.1`

**Comment by drewberk** [comment]
Thank you for the advice @mmaietta. I was able to resolve this error by adding 

`"warningsAsErrors": false,
"perMachine": false,
 "oneClick": false,` 

to the `nsis ` section of my config file.
