### ISSUE TITLE
macOS 12.3 Beta has removed the Python 2 support: spawn /usr/bin/python ENOENT

### ISSUE THREAD

**Issue by pan93412** [electron-userland/electron-builder#6606]
* **Electron-Builder Version**: 22.13.1

* **Node Version**: v16.13.1

* **Electron Version**: 16.0.8
* **Electron Type (current, beta, nightly)**: current

* **electron-updater Version**: 4.6.5

* **Target**: macOS (x86, ARM64, universal?)

[macOS 12.3 has removed the Python 2 support](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Python); thus, `/usr/bin/python` has been removed. electron-builder tries to call `/usr/bin/python` and it throws `Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT`.

## Reproducible Step

```bash
# Clone the minimum reproducible boilerplate
git clone git@github.com:electron-react-boilerplate/electron-react-boilerplate.git
cd electron-react-boilerplate

# Install dependencies
npm i

# Upgrade to the latest patch version
npm upgrade

# Package (it throws here)
npm run package
```

## Full Log

```bash=
$ npm run package
> package
> ts-node ./.erb/scripts/clean.js dist && npm run build && electron-builder build --publish never


> build
> concurrently "npm run build:main" "npm run build:renderer"

[1]
[1] > build:renderer
[1] > cross-env NODE_ENV=production TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.prod.ts
[1]
[0]
[0] > build:main
[0] > cross-env NODE_ENV=production TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.main.prod.ts
[0]
[1] npm run build:renderer exited with code 0
[0] npm run build:main exited with code 0
  • electron-builder  version=22.13.1 os=21.4.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=release/build/builder-effective-config.yaml
  • installing production dependencies  platform=darwin arch=arm64 appDir=/Users/pan93412/Projects/electron-react-boilerplate/release/app
  • packaging       platform=darwin arch=arm64 electron=16.0.8 appOutDir=release/build/mac-arm64
  • downloading     url=https://github.com/electron/electron/releases/download/v16.0.8/electron-v16.0.8-darwin-arm64.zip size=88 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v16.0.8/electron-v16.0.8-darwin-arm64.zip duration=22.373s
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=     0 identities found
                                                Valid identities only
     0 valid identities found
Skipping notarizing step. Packaging is not running in CI
  • building        target=macOS zip arch=arm64 file=release/build/ElectronReact-4.5.0-arm64-mac.zip
  • building        target=DMG arch=arm64 file=release/build/ElectronReact-4.5.0-arm64.dmg
  • installing production dependencies  platform=darwin arch=x64 appDir=/Users/pan93412/Projects/electron-react-boilerplate/release/app
  • Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+
  • packaging       platform=darwin arch=x64 electron=16.0.8 appOutDir=release/build/mac
  • downloading     url=https://github.com/electron/electron/releases/download/v16.0.8/electron-v16.0.8-darwin-x64.zip size=83 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v16.0.8/electron-v16.0.8-darwin-x64.zip duration=19.803s
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=     0 identities found
                                                Valid identities only
     0 valid identities found
Skipping notarizing step. Packaging is not running in CI
  • building        target=macOS zip arch=x64 file=release/build/ElectronReact-4.5.0-mac.zip
  • building        target=DMG arch=x64 file=release/build/ElectronReact-4.5.0.dmg
  • Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+
  ⨯ Exit code: ENOENT. spawn /usr/bin/python ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
    at /Users/pan93412/Projects/electron-react-boilerplate/node_modules/builder-util/src/util.ts:133:18
    at exithandler (node:child_process:404:5)
    at ChildProcess.errorhandler (node:child_process:416:5)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
  • Above command failed, retrying 5 more times
  • building block map  blockMapFile=release/build/ElectronReact-4.5.0-arm64-mac.zip.blockmap
  • Above command failed, retrying 4 more times
  • Above command failed, retrying 3 more times
  • Above command failed, retrying 2 more times
  • Above command failed, retrying 1 more times
  • Above command failed, retrying 0 more times
  • building block map  blockMapFile=release/build/ElectronReact-4.5.0-mac.zip.blockmap
```

**Comment by mmaietta** [comment]
I'm not sure if the current `vendor` python scripts are python 3 compatible.
Can you try running electron builder with `PYTHON_PATH=<path to python 3>` to test it?
https://github.com/electron-userland/electron-builder/blob/b01d5225631115f6f301cb113b044fd10ebb5256/packages/dmg-builder/src/dmg.ts#L301-L304

**Comment by pan93412** [comment]
```
  ⨯ Exit code: 1. Command failed: /usr/bin/python3 /Users/pan93412/Projects/electron-react-boilerplate/node_modules/dmg-builder/vendor/dmgbuild/core.py
Traceback (most recent call last):
  File "/Users/pan93412/Projects/electron-react-boilerplate/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 7, in <module>
    reload(sys)  # Reload is a hack
NameError: name 'reload' is not defined

Traceback (most recent call last):
  File "/Users/pan93412/Projects/electron-react-boilerplate/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 7, in <module>
    reload(sys)  # Reload is a hack
NameError: name 'reload' is not defined
  failedTask=build stackTrace=Error: Exit code: 1. Command failed: /usr/bin/python3 /Users/pan93412/Projects/electron-react-boilerplate/node_modules/dmg-builder/vendor/dmgbuild/core.py
Traceback (most recent call last):
  File "/Users/pan93412/Projects/electron-react-boilerplate/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 7, in <module>
    reload(sys)  # Reload is a hack
NameError: name 'reload' is not defined

Traceback (most recent call last):
  File "/Users/pan93412/Projects/electron-react-boilerplate/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 7, in <module>
    reload(sys)  # Reload is a hack
NameError: name 'reload' is not defined
```

Seems not compatible. Maybe we need to port it to Python 3 first.

**Comment by mmaietta** [comment]
Shot in the dark. Can you add `from imp import reload` to this file above `reload`?
`node_modules/dmg-builder/vendor/dmgbuild/core.py`

**Comment by pan93412** [comment]
> Shot in the dark. Can you add `from imp import reload` to this file above `reload`?
> `node_modules/dmg-builder/vendor/dmgbuild/core.py`

Sure. I will test it later.

**Comment by pan93412** [comment]
```
# -*- coding: utf-8 -*-

from importlib import reload
# from __future__ import unicode_literals

import os
import re
import sys
reload(sys)  # Reload is a hack
# sys.setdefaultencoding('UTF8')

sys.path.append(os.path.normpath(os.path.join(os.path.dirname(__file__), "..")))

try:
  {}.iteritems
  iteritems = lambda x: x.iteritems()
  iterkeys = lambda x: x.iterkeys()
except AttributeError:
  iteritems = lambda x: x.items()
  iterkeys = lambda x: x.keys()
try:
  unicode
except NameError:
  unicode = str

import biplist
from mac_alias import *
from ds_store import *

from colors import parseColor

try:
  from badge import badge
except ImportError:
  badge = None

class DMGError(Exception):
  pass


def build_dmg():
  options = {
    'icon': None,
    'badge_icon': None,
    'sidebar_width': 180,
    'arrange_by': None,
    'grid_offset': (0, 0),
    'grid_spacing': 100.0,
    'scroll_position': (0.0, 0.0),
    'show_icon_preview': False,
    'text_size': os.environ['iconTextSize'],
    'icon_size': os.environ['iconSize'],
    'include_icon_view_settings': 'auto',
    'include_list_view_settings': 'auto',
    'list_icon_size': 16.0,
    'list_text_size': 12.0,
    'list_scroll_position': (0, 0),
    'list_sort_by': 'name',
    'list_columns': ('name', 'date-modified', 'size', 'kind', 'date-added'),
    'list_column_widths': {
      'name': 300,
      'date-modified': 181,
      'date-created': 181,
      'date-added': 181,
      'date-last-opened': 181,
      'size': 97,
      'kind': 115,
      'label': 100,
      'version': 75,
      'comments': 300,
    },
    'list_column_sort_directions': {
      'name': 'ascending',
      'date-modified': 'descending',
      'date-created': 'descending',
      'date-added': 'descending',
      'date-last-opened': 'descending',
      'size': 'descending',
      'kind': 'ascending',
      'label': 'ascending',
      'version': 'ascending',
      'comments': 'ascending',
    }
  }

  # Set up the finder data
  bwsp = {
    'ShowStatusBar': False,
    'ContainerShowSidebar': False,
    'PreviewPaneVisibility': False,
    'SidebarWidth': options['sidebar_width'],
    'ShowTabView': False,
    'ShowToolbar': False,
    'ShowPathbar': False,
    'ShowSidebar': False
  }

  window_x = os.environ.get('windowX')
  if window_x:
    window_y = os.environ['windowY']
    bwsp['WindowBounds'] = '{{%s, %s}, {%s, %s}}' % (window_x,
                                                     window_y,
                                                     os.environ['windowWidth'],
                                                     os.environ['windowHeight'])

  arrange_options = {
    'name': 'name',
    'date-modified': 'dateModified',
    'date-created': 'dateCreated',
    'date-added': 'dateAdded',
    'date-last-opened': 'dateLastOpened',
    'size': 'size',
    'kind': 'kind',
    'label': 'label',
  }

  icvp = {
    'viewOptionsVersion': 1,
    'backgroundType': 0,
    'backgroundColorRed': 1.0,
    'backgroundColorGreen': 1.0,
    'backgroundColorBlue': 1.0,
    'gridOffsetX': float(options['grid_offset'][0]),
    'gridOffsetY': float(options['grid_offset'][1]),
    'gridSpacing': float(options['grid_spacing']),
    'arrangeBy': str(arrange_options.get(options['arrange_by'], 'none')),
    'showIconPreview': options['show_icon_preview'] == True,
    'showItemInfo': False,
    'labelOnBottom': True,
    'textSize': float(options['text_size']),
    'iconSize': float(options['icon_size']),
    'scrollPositionX': float(options['scroll_position'][0]),
    'scrollPositionY': float(options['scroll_position'][1])
  }

  columns = {
    'name': 'name',
    'date-modified': 'dateModified',
    'date-created': 'dateCreated',
    'date-added': 'dateAdded',
    'date-last-opened': 'dateLastOpened',
    'size': 'size',
    'kind': 'kind',
    'label': 'label',
    'version': 'version',
    'comments': 'comments'
  }

  default_widths = {
    'name': 300,
    'date-modified': 181,
    'date-created': 181,
    'date-added': 181,
    'date-last-opened': 181,
    'size': 97,
    'kind': 115,
    'label': 100,
    'version': 75,
    'comments': 300,
  }

  default_sort_directions = {
    'name': 'ascending',
    'date-modified': 'descending',
    'date-created': 'descending',
    'date-added': 'descending',
    'date-last-opened': 'descending',
    'size': 'descending',
    'kind': 'ascending',
    'label': 'ascending',
    'version': 'ascending',
    'comments': 'ascending',
  }

  lsvp = {
    'viewOptionsVersion': 1,
    'sortColumn': columns.get(options['list_sort_by'], 'name'),
    'textSize': float(options['list_text_size']),
    'iconSize': float(options['list_icon_size']),
    'showIconPreview': options['show_icon_preview'],
    'scrollPositionX': options['list_scroll_position'][0],
    'scrollPositionY': options['list_scroll_position'][1],
    'useRelativeDates': True,
    'calculateAllSizes': False,
  }

  lsvp['columns'] = {}
  cndx = {}

  for n, column in enumerate(options['list_columns']):
    cndx[column] = n
    width = options['list_column_widths'].get(column, default_widths[column])
    asc = 'ascending' == options['list_column_sort_directions'].get(column, default_sort_directions[column])

    lsvp['columns'][columns[column]] = {
      'index': n,
      'width': width,
      'identifier': columns[column],
      'visible': True,
      'ascending': asc
    }

  n = len(options['list_columns'])
  for k in iterkeys(columns):
    if cndx.get(k, None) is None:
      cndx[k] = n
      width = default_widths[k]
      asc = 'ascending' == default_sort_directions[k]

    lsvp['columns'][columns[column]] = {
      'index': n,
      'width': width,
      'identifier': columns[column],
      'visible': False,
      'ascending': asc
    }

    n += 1

  default_view = 'icon-view'
  views = {
    'icon-view': b'icnv',
    'column-view': b'clmv',
    'list-view': b'Nlsv',
    'coverflow': b'Flwv'
  }

  icvl = (b'type', views.get(default_view, 'icnv'))

  include_icon_view_settings = default_view == 'icon-view' \
                               or options['include_icon_view_settings'] not in \
                               ('auto', 'no', 0, False, None)
  include_list_view_settings = default_view in ('list-view', 'coverflow') \
                               or options['include_list_view_settings'] not in \
                               ('auto', 'no', 0, False, None)

  try:
    background_bmk = None

    background_color = os.environ.get('backgroundColor')
    background_file = os.environ.get('backgroundFile')

    if background_color:
      c = parseColor(background_color).to_rgb()

      icvp['backgroundType'] = 1
      icvp['backgroundColorRed'] = float(c.r)
      icvp['backgroundColorGreen'] = float(c.g)
      icvp['backgroundColorBlue'] = float(c.b)
    elif background_file:
      alias = Alias.for_file(background_file)
      background_bmk = Bookmark.for_file(background_file)

      icvp['backgroundType'] = 2
      icvp['backgroundImageAlias'] = biplist.Data(alias.to_bytes())

    image_dsstore = os.path.join(os.environ['volumePath'], '.DS_Store')

    f =  "icon_locations = {\n" + os.environ['iconLocations'] + "\n}"
    exec (f, options, options)

    with DSStore.open(image_dsstore, 'w+') as d:
      d['.']['vSrn'] = ('long', 1)
      d['.']['bwsp'] = bwsp
      if include_icon_view_settings:
        d['.']['icvp'] = icvp
        if background_bmk:
          d['.']['pBBk'] = background_bmk
      if include_list_view_settings:
        d['.']['lsvp'] = lsvp
      d['.']['icvl'] = icvl

      d['.background']['Iloc'] = (2560, 170)
      d['.DS_Store']['Iloc'] = (2610, 170)
      d['.fseventsd']['Iloc'] = (2660, 170)
      d['.Trashes']['Iloc'] = (2710, 170)
      d['.VolumeIcon.icns']['Iloc'] = (2760, 170)

      for k, v in iteritems(options['icon_locations']):
        d[k]['Iloc'] = v
  except:
    raise

build_dmg()
```

I followed the exception instruction from `python3` and it seems work now. However, I'm not sure whether it works correct. :/

**Comment by mmaietta** [comment]
Should be working correctly, the only difference is depending upon which version of python you're using.
>= 3.4 -> `importlib`
< 3.4 -> `imp`
< 3 (i.e. Python 2) -> `record` is built-in function

https://stackoverflow.com/a/33409066

I'll need to figure out a way to support both python 2 and python 3. I'm not sure what the other python scripts in the `vendor` dir are used for yet.

**Comment by mmaietta** [comment]
I think this might do the trick:
```
import sys
if sys.version_info.major == 3:
    try:
        from importlib import reload
    except ImportError:
        from imp import reload
```

**Comment by pan93412** [comment]
> I think this might do the trick:
> 
> ```
> import sys
> if sys.version_info.major == 3:
>     try:
>         from importlib import reload
>     except ImportError:
>         from imp import reload
> ```

Not only this. I also commented out `# from __future__ import unicode_literals` and `sys.setdefaultencoding('UTF8')` as Python 3 has supported Unicode natively.

**Comment by mmaietta** [comment]
Great point, we can add that as an if-else statement as I think we should continue supporting Python 2 since it seems unnecessary to drop support for it.

**Comment by Tenpi** [comment]
Hi, this has _**not**_ resolved the issue for me, I get same error on electron builder `23.0.0-alpha.4` on latest macOS 12.3 beta.

I cannot build my app I always get:
`⨯ Exit code: ENOENT. spawn /usr/bin/python ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT`

**Comment by adriendurepaire** [comment]
Hi, same as @Tenpi : 23.0.0.-alpha.4 doesn't seem to automatically switch to /usr/bin/python3 when /usr/bin/python doesn't exist.

**Comment by Tenpi** [comment]
Ok, it's working again in version `23.0.2`, thanks.

**Comment by hlwen** [comment]
先安装好python2.7，在添加变量执行cross-env PYTHON_PATH=you path/python/bin/python2.7 electron-builder，能编译成功

**Comment by rogeriomq** [comment]
Hi, on MacOS 12.3.1 Chip M1 Pro, I did the following procedures:
1 - Use ASDF to install python v2: 
`asdf install python 2.7.18`
2 - Set Python on shell with asdf: 
`asdf shell python 2.7.18`
3 - Export PYTHON_PATH environment: 
`export PYTHON_PATH=/Users/YOUR_USER/.asdf/shims/python`

Bingo! Now I can create the .DMG again. 

Hope this helps someone else who has gone through this too.

**Comment by magicdawn** [comment]
```
PYTHON_PATH=`pyenv which python2.7` pnpm dist
```

**Comment by eeshairfan** [comment]
I still have issues with the same issue. I am using python3.9 and I tried to upgrade electron-builder to 23.0.2 to fix the error but I cant because it potentially breaks these:

up to date, audited 299 packages in 2s

31 packages are looking for funding
  run `npm fund` for details

# npm audit report

async  <2.6.4
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
fix available via `npm audit fix --force`
Will install electron-builder@22.5.1, which is a breaking change
node_modules/async
  jake  >=8.0.1
  Depends on vulnerable versions of async
  node_modules/jake
    ejs  >=3.1.2
    Depends on vulnerable versions of jake
    node_modules/ejs
      app-builder-lib  >=22.6.0
      Depends on vulnerable versions of ejs
      node_modules/app-builder-lib
        dmg-builder  >=22.6.0
        Depends on vulnerable versions of app-builder-lib
        node_modules/dmg-builder
          electron-builder  19.25.0 || >=22.6.0
          Depends on vulnerable versions of app-builder-lib
          Depends on vulnerable versions of dmg-builder
          node_modules/electron-builder

**Comment by eeshairfan** [comment]
The thing is I have already made executables with this code and it was working all this time. Suddenly it decides to stop working.

**Comment by Stanzilla** [comment]
It still fails on .6 here as well

**Comment by mmaietta** [comment]
@eeshairfan I've just updated deps (incl. `ejs` -> `async`) in v23.0.8, that should resolve the audit issues you mentioned :)

**Comment by rancy98** [comment]
> Hi, on MacOS 12.3.1 Chip M1 Pro, I did the following procedures: 1 - Use ASDF to install python v2: `asdf install python 2.7.18` 2 - Set Python on shell with asdf: `asdf shell python 2.7.18` 3 - Export PYTHON_PATH environment: `export PYTHON_PATH=/Users/YOUR_USER/.asdf/shims/python`
> 
> Bingo! Now I can create the .DMG again.
> 
> Hope this helps someone else who has gone through this too.

`export PYTHON_PATH ...` Is it to be added to the system level or the user level?

**Comment by ok-dok** [comment]
thanks a lot, I resove this problem by this configuration in package.json:

`
{
  ...
  "devDependencies": {
    ...
     "vue-cli-plugin-electron-builder": "^2.1.1",
  },
  "resolutions": {
    "vue-cli-plugin-electron-builder/electron-builder": "^23.0.6"
  },
  ...
}
`

> It still fails on .6 here as well but I guess it's because this plugin still uses the old lib
> 
> ```
>  Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
>     at /Users/stan/projects/personal/WeakAuras-Companion/node_modules/vue-cli-plugin-electron-builder/node_modules/builder-util/src/util.ts:133:18
>     at exithandler (node:child_process:406:5)
> ```
> 
> Edit: When I force it via npm override it works:
> 
> ```json
> "overrides": {
>     "vue-cli-plugin-electron-builder": {
>       "electron-builder": "^23.0.6"
>     }
>   }
> ```

**Comment by jitendrawe360** [comment]
I've updated macOS 12.6, I'm using **electron-builder version-22.8.1** and facing same problem of missing python on path: **/usr/bin/python** I've changed the hard coded path of **/usr/bin/python** to **/usr/local/bin/python** inside package **dmg-builder** in file **out/dmg.js**. now try to build and it worked perfectly.

`await (0, _builderUtil().exec)("/usr/local/bin/python", [path.join((0, _dmgUtil().getDmgVendorPath)(), "dmgbuild/core.py")], {
    cwd: (0, _dmgUtil().getDmgVendorPath)(),
    env
  });`

**Comment by rogeriomq** [comment]
Hello, I have solved this problem on macbook using [ASDF](https://asdf-vm.com/), I set the python version in the shell where I am running the build. ex: `asdf shell python 2.7.18`
Hope this helps!!!

**Comment by Shawn-Shan** [comment]
You could also just use python3. Change the default python to python3's, for example `export PYTHON_PATH=/opt/homebrew/bin/python3`. Then it will* have two errors on the python3 compatibility. Simply resolve those two errors through simple stackoverflow search (editing the core.js file that shown in the error report).
