### ISSUE TITLE
arm64 dmg can be installed on M1 Mac,but run error:no suitable image found.

### ISSUE THREAD

**Issue by xintengbao** [electron-userland/electron-builder#6630]
* **Electron-Builder Version**: 22.10.5

* **Node Version**: v14.16.0

* **Electron Version**:12.0.6
* **Electron Type (current, beta, nightly)**:

* **Electron-updater Version**:4,3,5

* **Target**: dmg
* arch: "x64","arm64"

compile command：
package.json
"scripts"{
   "build-prod": "cross-env ENV=prod node scripts/build.js && electron-builder",
   …………
}
“mac”: {
 ……
 "target": {
  "target": "dmg",
  "arch":  ["x64","arm64"]
}

Both build x64 and arm64 at the same time, skip signature, x64 dmg on Intel chip and M1 chip run OK. arm64 dmg can be installed on M1 Mac successfully,but an error occurred while running. build universal version also run error on M1 Mac.

Uncaught Exception:
Error: dlopen(/var/folders/db/zy8jss1s0zn_3cnj1spg0y400000gn/T/.com.huawei.linknow.s6t6Y1, 1): no suitable image found.  Did find:
/var/folders/db/zy8jss1s0zn_3cnj1spg0y400000gn/T/.com.huawei.linknow.s6t6Y1: mach-o, but wrong architecture
/var/folders/db/zy8jss1s0zn_3cnj1spg0y400000gn/T/.com.huawei.linknow.s6t6Y1: stat() failed with errno=17
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
at Module.load (internal/modules/cjs/loader.js:935:32)
at Module._load (internal/modules/cjs/loader.js:776:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
at Module.require (internal/modules/cjs/loader.js:959:19)
at require (internal/modules/cjs/helpers.js:88:18)
at bindings (/Users/linknowtest/Desktop/test/build/mac-arm64/Link Now.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
[at Object.<anonymous> (/Users/linknowtest/Desktop/test/build/mac-arm64/Link Now.app/Contents/Resources/app.asar/node_modules/@cloudplatform/grs-mac/src/addonlib/](mailto:at%20Object.%3Canonymous%3E%20(/Users/linknowtest/Desktop/test/build/mac-arm64/Link%20Now.app/Contents/Resources/app.asar/node_modules/@cloudplatform/grs-mac/src/addonlib/)

**Comment by famingyuan** [comment]
you can try only build one arch one time . It works for me .

**Comment by mmaietta** [comment]
I have a hunch as to why you would get wrong arch. Might be a bug in an upstream dependency.

Can you try using `electron-rebuild` and use these settings in your electron-builder config with `beforeBuild` hook?
```
  // force arch build if using electron-rebuild
  beforeBuild: async (context) => {
    const { appDir, electronVersion, arch } = context
    await electronRebuild.rebuild({ buildPath: appDir, electronVersion, arch })
    return false
  },
  nodeGypRebuild: false,
  buildDependenciesFromSource: false,
```

**Comment by ganeshrvel** [comment]
`npmRebuild` solved my issue

```
  "build": { 
   "npmRebuild": false,
}
```
