### ISSUE TITLE
Go error proxyconnect tcp

### ISSUE THREAD

**Issue by migueljolv** [electron-userland/electron-builder#6644]
**electron-builder**: 22.14.13
**node**: v14.17.4
**electron**: 17.0.0
**electron-updater**: We don't use it
**target**: macOS, pkg
**Host OS:** macOS

We started having this issue after upgrading to Electron 17

```
• electron-builder  version=22.14.13 os=21.2.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=x64 electron=17.0.0 appOutDir=dist/mac
  ⨯ Get "https://github.com/electron/electron/releases/download/v17.0.0/electron-v17.0.0-darwin-x64.zip": proxyconnect tcp: dial tcp :0: connect: can't assign requested address
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:206
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:234
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:128
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:112
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/asm_amd64.s:1371  
  ⨯ /Users/mmartinez/Documents/workspace/agent-desktop-native/node_modules/app-builder-bin/mac/app-builder_amd64 exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: /Users/mmartinez/Documents/workspace/agent-desktop-native/node_modules/app-builder-bin/mac/app-builder_amd64 exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/Users/mmartinez/Documents/workspace/agent-desktop-native/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

Related: [#2665](https://github.com/electron-userland/electron-builder/issues/2665)

Thanks in advance.

**Comment by mmaietta** [comment]
That's an issue with `app-builder`, please open a ticket there: https://github.com/develar/app-builder

**Comment by ibtissamOlearn** [comment]
i have the same problem
