### ISSUE TITLE
Application entry file "background.js" in the "..../app.asar" does not exist. Seems like a wrong configuration.

### ISSUE THREAD

**Issue by xiongyayun428** [electron-userland/electron-builder#6663]
INFO  Building app with electron-builder:
  • electron-builder  version=22.14.13 os=21.3.0
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=17.0.1 appOutDir=dist_electron/mac
Error: Application entry file "background.js" in the "/Users/xyy/Documents/yxrt/electron-vue/dist_electron/mac/electron-vue.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/Users/xyy/Documents/yxrt/electron-vue/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (/Users/xyy/Documents/yxrt/electron-vue/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
    at MacPackager.checkFileInPackage (/Users/xyy/Documents/yxrt/electron-vue/node_modules/app-builder-lib/src/platformPackager.ts:501:7)
    at MacPackager.sanityCheckPackage (/Users/xyy/Documents/yxrt/electron-vue/node_modules/app-builder-lib/src/platformPackager.ts:549:5)
    at MacPackager.doPack (/Users/xyy/Documents/yxrt/electron-vue/node_modules/app-builder-lib/src/platformPackager.ts:310:5)
    at MacPackager.pack (/Users/xyy/Documents/yxrt/electron-vue/node_modules/app-builder-lib/src/macPackager.ts:177:7)
    at Packager.doBuild (/Users/xyy/Documents/yxrt/electron-vue/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/xyy/Documents/yxrt/electron-vue/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/xyy/Documents/yxrt/electron-vue/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/xyy/Documents/yxrt/electron-vue/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/xyy/Documents/yxrt/electron-vue/node_modules/builder-util/src/promise.ts:12:14)

**Comment by mmaietta** [comment]
The current information provided is entirely not helpful.

**Comment by LouMM** [comment]
@mmaietta Your comment is 'entirely not helpful'. Next time take a moment and determine the information you need and ask for it. 

@xiongyayun428 It seems you have a similar issue to #2030. In the future, please follow the repo's template and for all the data it is asking for, please provide details. 
What could help here is an example of your package.json file that has the "build" attributes in it. Feel free to remove any Pii from it by randomizing your path names.
What I suggest is checking out the solutions provided in #2030. If not, please provide additional details. Cheers!
