### ISSUE TITLE
Failed to sync URL as GitHub repo: A task was canceled.

### ISSUE THREAD

**Issue by wmhilton** [electron-userland/electron-builder#667]
* **Version**: 5.23.2

* **Target**: --win

I am trying to publish to Github, but getting this error. It looks like the root cause is a 404 error, but it doesn't specify what URL gave the error. Could someone provide a suggestion on how to go about debugging this?

```
> build --win --publish onTagOrDraft

Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform win32 x64 using electron 1.3.2 to dist\win-unpacked

Building Squirrel.Windows installer

Attemping to sync URL as remote RELEASES folder
Failed to sync URL as GitHub repo: A task was canceled.
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncReleases.SyncImplementations.<downloadReleasesIndex>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncReleases.SyncImplementations.<retryAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncReleases.SyncImplementations.<SyncRemoteReleases>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncReleases.Program.<main>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SyncReleases.Program.Main(String[] args)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncReleases.SyncImplementations.<downloadReleasesIndex>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncReleases.SyncImplementations.<retryAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncReleases.SyncImplementations.<SyncRemoteReleases>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncReleases.Program.<main>d__2.MoveNext()<---
```

Edit: 
Additional information
```

  "build": {
    "appId": "com.npmjs.package.ransomaware",
    "app-category-type": "public.app-category.utilities",
    "win": {
      "iconUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Folder-saved-search.svg/240px-Folder-saved-search.svg.png",
      "remoteReleases": "https://github.com/wmhilton/ransomAware"
    },
    "asar": false
  },
```

**Comment by develar** [comment]
Maybe Squirrel confuses that your previous release (0.10 before last 0.11) doesn't exist. Please file issue to https://github.com/Squirrel/Squirrel.Windows/issues

**Comment by develar** [comment]
As a workaround, you can do not build delta updates for now.

**Comment by wmhilton** [comment]
AH, do you think it's because my "RELEASES" file contains older entries that weren't uploaded? I'll try tweaking my RELEASES file and/or uploading missing delta packages.

**Comment by eanders-MS** [comment]
@develar How can I not build delta updates? I'm having a problem:

> Trying to download RELEASES index from https://github.com/.../RELEASES

It is failing to find a RELEASES file... I'm not exactly sure why.

I'm working to transition from Squirrel.Windows to NSIS. My current plan is to release a final Squirrel.Windows release, and that release will use the new electron-builder autoUpdater to find the NSIS build.

Thank you for your assistance... electron-builder is a great product.

**Comment by develar** [comment]
Delta updates are not enabled by default. Please ensure that remoteReleases not set.
