### ISSUE TITLE
Mac code signing: bundle format unrecognized, invalid, or unsuitable

### ISSUE THREAD

**Issue by nterms** [electron-userland/electron-builder#668]
* **5.25.1**: 

* **dmg**: 

I'm getting this error while trying to build my electron app using electron-builder on Mac with code signing. Identity is properly set on keychain.

> Error: Command failed: codesign --sign Company Name --force /Users/nterms/Projects/my-app/dist/mac/MyApp.app/Contents/Resources/app.asar.unpacked/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Framework.framework
/Users/nterms/Projects/my-app/dist/mac/MyApp.app/Contents/Resources/app.asar.unpacked/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Framework.framework: bundle format unrecognized, invalid, or unsuitable
at ChildProcess.exithandler (child_process.js:213:12)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at maybeClose (internal/child_process.js:827:16)
at Socket.<anonymous> (internal/child_process.js:319:11)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at Pipe._onclose (net.js:477:12)
From previous event:
at tsAwaiter (/Users/nterms/Projects/my-app/node_modules/electron-builder/src/util/awaiter.ts:10:47)
at MacPackager.sign (/Users/nterms/Projects/my-app/node_modules/electron-builder/src/macPackager.ts:100:75)
at /Users/saranga/Projects/my-app/node_modules/electron-builder/src/macPackager.ts:80:26
From previous event:
at MacPackager.<anonymous> (/Users/nterms/Projects/my-app/node_modules/electron-builder/src/macPackager.ts:80:10)
at next (native)
From previous event:
at tsAwaiter (/Users/nterms/Projects/my-app/node_modules/electron-builder/src/util/awaiter.ts:10:47)
at Object.build (/Users/nterms/Projects/my-app/node_modules/electron-builder/src/builder.ts:195:52)
at Object.<anonymous> (/Users/nterms/Projects/my-app/node_modules/electron-builder/src/build-cli.ts:27:28)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:968:3

However the building smoothly goes on the same app when packaging without code signing.

I'm on a Mac with OSX El Captain (10.11.6) and XCode is updated to the latest version.

**Comment by develar** [comment]
electron-prebuilt module must be in the devDependencies.

**Comment by nterms** [comment]
@develar electron-prebuilt is there in devDependencies. anything else I can look for to solve the issue?

**Comment by develar** [comment]
I see `app.asar.unpacked/node_modules/electron-prebuilt/dist/Electron.app` in your log. So, it is in the production dependencies. Please check

**Comment by nterms** [comment]
Thanks a lot @develar. It worked!
