### ISSUE TITLE
Linux AppImage: Error: EROFS: read-only file system

### ISSUE THREAD

**Issue by aronsommer** [electron-userland/electron-builder#6734]
* **Electron-Builder Version**: 22.14.13

* **Node Version**: 16.14.0

* **Electron Version**: 17.1.2
* **Electron Type (current, beta, nightly)**:

* **Target**: linux arm64

My Linux application (builded on macOS) needs to download files via Git to a folder inside the application.
And it needs to write new seetings to a file called settings.json inside the application.

In the unpacked Linux version everything works fine.
But with the AppImage version I have following error when I want to write new settings to the settings.json  inside the application:

```
Error: EROFS: read-only file system, open '/tmp/.mount_ElectrF5eHhx/resources/settings.json'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.writeFileSync (node:fs:2153:35)
    at writeNewSettings (/tmp/.mount_ElectrF5eHhx/resources/app.asar/main.js:361:6)
    at /tmp/.mount_ElectrF5eHhx/resources/app.asar/main.js:654:9 {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: '/tmp/.mount_ElectrF5eHhx/resources/settings.json'
}
[10886:0321/085227.648448:ERROR:node_controller.cc(585)] Trying to re-add dropped peer 467C85D0A45DA64D.E7C3DA00B86A32F1
```

**Comment by andirsun** [comment]
https://stackoverflow.com/questions/60881343/electron-problem-creating-file-error-erofs-read-only-file-system
