### ISSUE TITLE
Build arch: universal fail macOS 12.3 TypeError: Cannot read properties of undefined (reading 'Resources')

### ISSUE THREAD

**Issue by bjbk** [electron-userland/electron-builder#6735]
* **Electron-Builder Version**: 23.0.3

* **Node Version**: ~16.13.2~ [updated to 16.14.3]

* **Electron Version**: 17.1.2
* **Electron Type (current, beta, nightly)**: current

* **Electron Updater**: 5.0.0

* **Target**: `mac: { target: { target: 'default', arch: 'universal' } }`

* **Dev Machine**: Mac mini (M1, 2020)
* **Dev OS version**: macOS Monterey 12.3

After experiencing the issue raised #6606 here, I now get the following errors trying to build. 

```bash
App · Bundling app with electron-builder...

  • electron-builder  version=23.0.3 os=21.4.0
  • writing effective config  file=dist/electron/Packaged/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=17.1.2 appOutDir=dist/electron/Packaged/mac-universal--x64
  • packaging       platform=darwin arch=arm64 electron=17.1.2 appOutDir=dist/electron/Packaged/mac-universal--arm64
  • packaging       platform=darwin arch=universal electron=17.1.2 appOutDir=dist/electron/Packaged/mac-universal

 App · ⚠️  [FAIL] electron-builder could not build

TypeError: Cannot read properties of undefined (reading 'Resources')

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".
```

I can't seem to get any further diagnosis.

## EDIT:

Tried to build changing arch to arm64 - build was successful.  Now to figure out how to build a universal dmg bundle. 🤔 Was even able to build win-ia32, arm64-win, and AppImage without issues.
```
...
mac: {
  target: {
     target: 'default',
     // arch: 'universal'
     arch: 'arm64'
  },
…
```
**Build with x64 also successful.**
```
...
mac: {
  target: {
     target: 'default',
     // arch: 'universal'
     arch: 'x64'
  },
…
```
cannot build universal dmg.

**Comment by bjbk** [comment]
In looking at the app bundles, Contents and Resources seem to be there.  So wondering what in `electron/universal` is not getting satisfied?  Seems to be happening after combining the files or attempting to. 
File reference https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/macPackager.ts#L94

**Comment by mmaietta** [comment]
Hmmm, two options were added when electron/universal was updated to the latest version:
```
mac: {
   mergeASARs: 
   singleArchFiles:
}
```
I honestly don't know what the two options do (it was a community contribution PR), but it might be worth trying `mergeASARs: false`?

I wish there was a stacktrace with the thrown error to help debug this. The error message is completely ambiguous :/ 
`The promise rejected with the reason "undefined"`

**Comment by bjbk** [comment]
That did it!  I wonder if `mergeASARs: false` could be set by default.  Of course that may be an issue for the electron team instead of builder.

Could the documentation mention that this prop is mandatory if using universal?  I didn't get that from the docs as quoted below.  Thanks @mmaietta ! 
```
mergeASARs = true Boolean - Whether to merge ASAR files for different architectures or not.
This option has no effect unless building for “universal” arch.
```

**Comment by mmaietta** [comment]
If this becomes a more prevalent issue, then I'll consider making it false by default. Since this is the first report of this issue, I have a feeling that it's unique to your dev env.

`mergeASARS` is a new param in @electron/universal, and the prop is not mandatory if using universal builds.

**Comment by andirsun** [comment]
Same error here
```
 • electron-builder  version=23.1.0 os=21.5.0
  • loaded configuration  file=/Users/julianacaromoreno/projects/streamline-web/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=19.0.4 appOutDir=dist/mac-universal--x64
  • SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/julianacaromoreno/projects/streamline-web/node_modules/app-builder-lib/src/fileTransformer.ts:41:35
  • packaging       platform=darwin arch=arm64 electron=19.0.4 appOutDir=dist/mac-universal--arm64
  • SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/julianacaromoreno/projects/streamline-web/node_modules/app-builder-lib/src/fileTransformer.ts:41:35
  • packaging       platform=darwin arch=universal electron=19.0.4 appOutDir=dist/mac-universal
  ⨯ Cannot read properties of undefined (reading 'Resources')  failedTask=build stackTrace=TypeError: Cannot read properties of undefined (reading 'Resources')
    at Filesystem.getNode (/Users/julianacaromoreno/projects/streamline-web/node_modules/asar/lib/filesystem.js:132:24)
    at Filesystem.getFile (/Users/julianacaromoreno/projects/streamline-web/node_modules/asar/lib/filesystem.js:140:23)
    at Filesystem.getFile (/Users/julianacaromoreno/projects/streamline-web/node_modules/asar/lib/filesystem.js:144:19)
    at Object.module.exports.statFile (/Users/julianacaromoreno/projects/streamline-web/node_modules/asar/lib/asar.js:157:21)
    at buildUnpacked (/Users/julianacaromoreno/projects/streamline-web/node_modules/@electron/universal/src/asar-utils.ts:95:25)
    at Object.exports.mergeASARs (/Users/julianacaromoreno/projects/streamline-web/node_modules/@electron/universal/src/asar-utils.ts:108:3)
    at exports.makeUniversalApp (/Users/julianacaromoreno/projects/streamline-web/node_modules/@electron/universal/src/index.ts:205:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MacPackager.doPack (/Users/julianacaromoreno/projects/streamline-web/node_modules/app-builder-lib/src/macPackager.ts:125:9)
    at MacPackager.pack (/Users/julianacaromoreno/projects/streamline-web/node_modules/app-builder-lib/src/macPackager.ts:191:7)
    at Packager.doBuild (/Users/julianacaromoreno/projects/streamline-web/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/julianacaromoreno/projects/streamline-web/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/julianacaromoreno/projects/streamline-web/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/julianacaromoreno/projects/streamline-web/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/julianacaromoreno/projects/streamline-web/node_modules/builder-util/src/promise.ts:12:14)


Cannot build electron packages:
Error: Command failed with exit code 1: electron-builder
```

**Comment by mmaietta** [comment]
@andirsun did you try `mergeASARS: false`?

**Comment by Groxot** [comment]
Same error on Mac and Windows

**Comment by connormanning** [comment]
Just chiming in to add that I also ran into this error in precisely this same scenario, and it was also resolved by setting `mergeASARs` to false.
