### ISSUE TITLE
codesign error with locale.pak on MacOS

### ISSUE THREAD

**Issue by ym13349140** [electron-userland/electron-builder#6796]
* **Electron-Builder Version**: V22.14.13

* **Node Version**: V14.18.0

* **Electron Version**:V11.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: dmg

Hi! I'm using electron-builder to package my application on MacOS. When I run `electron:build`, the process always stopped at the signing step, the error messages are as follows:
```
  INFO  Building app with electron-builder:
17:03:40   • electron-builder  version=22.14.13 os=19.6.0
17:03:40   • artifacts will be published if draft release exists  reason=CI detected
17:03:40   • description is missed in the package.json  appPackageFile=/Users/cmo/ws/pl220221/pl220221/vue-electron-browser/dist_electron/bundled/package.json
17:03:40   • rebuilding native dependencies  dependencies=ffi-napi@4.0.3, iconv@2.3.5, ref-napi@3.0.3 platform=darwin arch=x64
17:03:41   • packaging       platform=darwin arch=x64 electron=11.3.0 appOutDir=dist_electron/mac
17:03:43   • signing         file=dist_electron/mac/Test.app identityName=Developer ID Application: XXXXX (YYYYYYYYY) identityHash=095DAE195C02605DAC29562513BBD71A7104B0C3 provisioningProfile=none
17:03:44 Error: Command failed: codesign --sign XXXXXXXXXXXXXXXXXXXXXXXX --force --timestamp --options runtime --entitlements /Users/cmo/ws/pl220221/pl220221/vue-electron-browser/node_modules/app-builder-lib/templates/entitlements.mac.plist /Users/cmo/ws/pl220221/pl220221/vue-electron-browser/dist_electron/mac/Test.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/am.lproj/locale.pak
17:03:44 
17:03:44     at ChildProcess.exithandler (child_process.js:383:12)
17:03:44     at ChildProcess.emit (events.js:400:28)
17:03:44     at maybeClose (internal/child_process.js:1058:16)
17:03:44     at Socket.<anonymous> (internal/child_process.js:443:11)
17:03:44     at Socket.emit (events.js:400:28)
17:03:44     at Pipe.<anonymous> (net.js:686:12)
17:03:44 From previous event:
17:03:44     at processImmediate (internal/timers.js:464:21)
17:03:44 From previous event:
17:03:44     at MacPackager.signApp (/Users/cmo/ws/pl220221/pl220221/vue-electron-browser/node_modules/app-builder-lib/src/macPackager.ts:432:27)
17:03:44     at MacPackager.doSignAfterPack (/Users/cmo/ws/pl220221/pl220221/vue-electron-browser/node_modules/app-builder-lib/src/platformPackager.ts:327:16)
17:03:44     at MacPackager.doPack (/Users/cmo/ws/pl220221/pl220221/vue-electron-browser/node_modules/app-builder-lib/src/platformPackager.ts:312:7)
17:03:44     at MacPackager.pack (/Users/cmo/ws/pl220221/pl220221/vue-electron-browser/node_modules/app-builder-lib/src/macPackager.ts:177:7)
17:03:44     at Packager.doBuild (/Users/cmo/ws/pl220221/pl220221/vue-electron-browser/node_modules/app-builder-lib/src/packager.ts:441:9)
17:03:44     at Object.executeFinally (/Users/cmo/ws/pl220221/pl220221/vue-electron-browser/node_modules/builder-util/src/promise.ts:12:14)
17:03:44     at Packager._build (/Users/cmo/ws/pl220221/pl220221/vue-electron-browser/node_modules/app-builder-lib/src/packager.ts:376:31)
17:03:44     at Packager.build (/Users/cmo/ws/pl220221/pl220221/vue-electron-browser/node_modules/app-builder-lib/src/packager.ts:337:12)
17:03:44     at Object.executeFinally (/Users/cmo/ws/pl220221/pl220221/vue-electron-browser/node_modules/builder-util/src/promise.ts:12:14) {
17:03:44   killed: false,
17:03:44   code: null,
17:03:44   signal: 'SIGSEGV',
17:03:44   cmd: 'codesign --sign XXXXXXXXXXXXXXXX --force --timestamp --options runtime --entitlements /Users/cmo/ws/pl220221/pl220221/vue-electron-browser/node_modules/app-builder-lib/templates/entitlements.mac.plist /Users/cmo/ws/pl220221/pl220221/vue-electron-browser/dist_electron/mac/Test.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/am.lproj/locale.pak'
17:03:44 }
17:03:44 npm ERR! code ELIFECYCLE
17:03:44 npm ERR! errno 1
17:03:44 npm ERR! cmf-pc-framework@2.0.0 electron:build: `vue-cli-service electron:build`
17:03:44 npm ERR! Exit status 1
17:03:44 npm ERR! 
17:03:44 npm ERR! Failed at the cmf-pc-framework@2.0.0 electron:build script.
17:03:44 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
17:03:44 
17:03:44 npm ERR! A complete log of this run can be found in:
17:03:44 npm ERR!     /Users/cmo/ws/pl220221/.devops/.npm/_logs/2022-04-15T09_03_38_120Z-debug.log
```
It seems to be related to language files, but I don't know what caused this error, could you please help me?

Sincerely hope for your reply, Thanks!

**Comment by cnstonicz** [comment]
Hello,
did you manage to solve this problem?

I am getting the exact same message.
Thanks

**Comment by technotip** [comment]
I still have this error!!

**Comment by mmaietta** [comment]
electron-builder uses @electron/osx-sign under the hood to work with `codesign`, and this error seems to be originating from there.

As a workaround, if you're not looking/able to support multiple languages, you can decrease your electron app size by only keeping the locales you need via config var `electronLanguages: string[]`

**Comment by Daniil-33** [comment]
Do you guys found any solutions of this issue? Thanks

**Comment by mmaietta** [comment]
One workaround that might work is to specify the explicit language `.lproj` files you want to retain in the electron app via
`electronLanguages: ["en_US"]` for instance to only package `en_US` language files

**Comment by Daniil-33** [comment]
@mmaietta like that?

`// @see https://www.electron.build/configuration/configuration
{
  "$schema": "https://raw.githubusercontent.com/electron-userland/electron-builder/master/packages/app-builder-lib/scheme.json",
  "appId": "com.dexnet.cloud",
  "asar": true,
  "productName": "Dexcloud",
  "electronLanguages": ["en_US"],
  "directories": {
    "output": "release/${version}",
    "buildResources": "dist"
  },
  "files": [
    "dist",
    "dist-electron",
  ],
  "mac": {
    "icon": "dist/assets/icons/icon.icns",
    "type": "distribution",
    "target": "mas",
    "category": "public.app-category.utilities",
    "entitlements": "entitlements.mas.plist",
    "entitlementsInherit": "entitlements.mas.inherit.plist",
    "provisioningProfile": "embedded.provisionprofile",
    "artifactName": "${productName}-Mac-${version}-Installer.${ext}",
  },
  "win": {
    "icon": "dist/assets/icons/icon.ico",
    "target": [
      {
        "target": "nsis",
        "arch": ["x64", "ia32"]
      }
    ],
    "artifactName": "${productName}-Win-${version}-Installer.${ext}"
  },
  "nsis": {
    "oneClick": false,
    "perMachine": false,
    "allowToChangeInstallationDirectory": true,
    "deleteAppDataOnUninstall": false
  },
}`

**Comment by mmaietta** [comment]
Depends, did you test it yourself before asking the question?

Just double checked though and it's supposed to be `"en"` and not `en_US`

**Comment by Daniil-33** [comment]
@mmaietta Thanks for your answer. I tried this, but it seems that problem has another reason. Event if i delete problem packages before sign the app, it will crash with another one package with same error. I double checked all certificates, and issue reproducing on another machine. So i still looking for the solution :)

**Comment by Daniil-33** [comment]
@mmaietta UPD
I finally fixed the issue, problem was bound to certificates in keychain. I don`t know why, but there is a problem, when you have the same certificates in keychain in "Login" and "System" section. Finally i deleted certificates from "Login" section, and then all works perfectly.
