### ISSUE TITLE
no valid identity in the keychain

### ISSUE THREAD

**Issue by tleunen** [electron-userland/electron-builder#680]
* **Version**: 5.29.0
* **Target**: mas

I'm trying to sign a mac application, but for some reasons it fails with a `no valid identity in the keychain` error. After running it in a debug mode, I can see it finds an identity though.

```
  electron-builder Executing security find-identity -v +1s
  electron-builder Executing security find-identity -v -p codesigning +5ms
Signing app (identity: Mac Developer: Tommy Leunen (XXXXXXXXXXX))

Error: Cannot find valid installer certificate: CSC_LINK is not specified, and no valid identity in the keychain, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
    at MacPackager.<anonymous> (/Users/tommy.leunen/dev/ppppppp/node_modules/electron-builder/src/macPackager.ts:118:15)
From previous event:
    at tsAwaiter (/Users/tommy.leunen/dev/ppppppp/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/Users/tommy.leunen/dev/ppppppp/node_modules/electron-builder/src/builder.ts:195:52)
    at Object.<anonymous> (/Users/tommy.leunen/dev/ppppppp/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I created the identity by going in xcode with my apple account and created a Mac development identity.

Is there something wrong in what I did?

**Comment by develar** [comment]
Do you have `3rd Party Mac Developer Application:` and `3rd Party Mac Developer Installer:` certs in your keychain (`security find-identity -v`)?

**Comment by tleunen** [comment]
Only a `3rd Party Mac Developer Application`, with the name of my company

**Comment by develar** [comment]
@tleunen For MAS 2 certs are required — to sign `app` and to sign `pkg`. Please create missed `3rd Party Mac Developer Installer:`

**Comment by tleunen** [comment]
I just resetter the mac installer certificate in xcode to add the identity and it seems it was the missing piece :)

Thanks @develar!
