### ISSUE TITLE
electron-builder checksum mismatch

### ISSUE THREAD

**Issue by hanwangqyq** [electron-userland/electron-builder#6850]
* **Electron-Builder Version**: 23.0.3

* **Node Version**: 16.14.2

* **Electron Version**:13.6.9
* **Electron Type (current, beta, nightly)**:current

* **electron-updater**:4.3.9

* **Target**: 

When I want to update electron client incrementally, I get error: sha512 checksum mismatch.
how to fix it?
`
[2022-05-09 18:50:44.022] [info]  Full: 248,351.35 KB, To download: 0 KB (0%)
[2022-05-09 18:50:46.340] [error] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected ejBZlgl0vvD6znRunel5v0E1FmI046cjeoJh84b1EfkDcNQUeT6NkBgs4nYOUFUmKEz+GQQALD2Gwhf4DFm4Zg==, got Z4KGp6S/o0HOmk7ENq7tfJVx62vJqBUQgcFISCaQj7jvkZZhhw4vJlN5Yq9GfE+Q1IBHJ6QIm6n4FvhAKEZ8+A==
    at Object.newError (D:\rpa-client\resources\app\node_modules\builder-util-runtime\out\index.js:47:19)
    at DigestTransform.validate (D:\rpa-client\resources\app\node_modules\builder-util-runtime\out\httpExecutor.js:323:27)
    at WriteStream.<anonymous> (D:\rpa-client\resources\app\node_modules\electron-updater\out\differentialDownloader\DifferentialDownloader.js:133:41)
    at WriteStream.emit (events.js:315:20)
    at emitCloseNT (internal/streams/destroy.js:87:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)`

**Comment by hanwangqyq** [comment]
I solve this problem via https://github.com/electron-userland/electron-builder/issues/5940

**Comment by hanwangqyq** [comment]
oh, when i use electron-differential-updater, I get this error again!! help

**Comment by Franco8888** [comment]
I am also getting the same issue with NSIS windows target
electron 22.0.0, 
electron-builder 22.6.3
electron-updater 6.1.1

Why have this not been fixed yet if in issue https://github.com/electron-userland/electron-builder/issues/5940 they found the solution?

**Comment by hanwangqyq** [comment]
I solved this problem,electron-differential-updater support Incremental update，current used config version:
"electron-builder": "22.14.13",
"electron": "13.6.9",
"@imjs/electron-differential-updater": "^5.1.7",

when you test check update more than once, you probably need delete cache file or some downloaded files,and add build client version

**Comment by Franco8888** [comment]
So you are using **electron-differential-updater** package?

**Comment by hanwangqyq** [comment]
> So you are using **electron-differential-updater** package?

yes,use electron-differential-updater instead electron-updater
