### ISSUE TITLE
windows: race condition between signtool.exe and light.exe leads to failure

### ISSUE THREAD

**Issue by link89** [electron-userland/electron-builder#6875]
* **Electron-Builder Version**:  22.10.5

* **Node Version**: 14.17.6

* **Electron Version**: 13.6.9-rc-54.0.0
* **Electron Type (current, beta, nightly)**: stable

* **Target**: msi, nsis

Recently I find the below error from time to time when I enable signature for msi build
```bash
19:12:23  light.exe : error LGHT0001 : The process cannot access the file 'c:\jws\workspace\Pipeline@2\application\dist\win-unpacked\resources\elevate.exe' because it is being used by another process.
19:12:23  
19:12:23  Exception Type: System.IO.IOException
19:12:23  
19:12:23  Stack Trace:
19:12:23     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
19:12:23     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
19:12:23     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
19:12:23     at WixToolset.Bind.Databases.UpdateFileFacadesCommand.UpdateFileFacade(FileFacade file)
19:12:23     at WixToolset.Bind.Databases.UpdateFileFacadesCommand.Execute()
19:12:23     at WixToolset.Bind.BindDatabaseCommand.Execute()
19:12:23     at WixToolset.Binder.BindDatabase(Output output, String databaseFile, IEnumerable`1& fileTransfers, IEnumerable`1& contentPaths)
19:12:23     at WixToolset.Binder.Bind(Output output, String file)
19:12:23     at WixToolset.Tools.Light.Run()
19:12:23     at WixToolset.Tools.Light.Execute(String[] args)
19:12:23  
19:12:23  WiX Toolset Linker version 4.0.0.5512
19:12:23  Copyright (c) .NET Foundation and contributors. All rights reserved.
19:12:23  
19:12:23  Updating file information.
19:12:23  Binder temporary directory located at 'C:\WINDOWS\wix220518T1910161220'.
```
It never happens when signature is disabled. 
Since the error message show that it is file access conflict, and it happens when all anti-virus services are disabled, so I use `procmon` to do some investigation.

![10_32_35_248_and_RingCentral_-_Jupiter_ODS_XMN_Desktop](https://user-images.githubusercontent.com/3314130/169065295-a5222079-fbee-4a23-9994-152982e622ed.png)
 
It shows that `signtool.exe`, whose pid=1468 and `light.exe`, whose pid=5863 are accessing the same file during the build, which leads to the failure of `light.exe`. The error code of createFile is SHARING VIOLATION shows why the error is 
`19:12:23  light.exe : error LGHT0001 : The process cannot access the file 'c:\jws\workspace\Pipeline@2\application\dist\win-unpacked\resources\elevate.exe' because it is being used by another process.`

I don't know under what condition those two command will be executed at the same time. The chance of such error is pretty high recently (maybe 80% of build fail due to this issue this week). Since `signtool.exe` need to access timestamp server, I guess the error happens when it takes too long to finish the code sign. But I don't figure out how to fix this yet.

**Comment by KaminoRyo** [comment]
Is the output folder open in Explorer? It is a trap that is easy to get caught.

**Comment by link89** [comment]
> Is the output folder open in Explorer? It is a trap that is easy to get caught.

No, it's `signtool.exe` and `light.exe` access the same file at the same time.

**Comment by KaminoRyo** [comment]
It was written that signtool.exe and WixToolKit's light.exe are in conflict. I'm sorry to skip it.🙇‍♂️

**Comment by Lancer92** [comment]
Still not fixed? Build with signing seems broken.

electron-builder  version=24.13.3 os=10.0.19041
  • loaded configuration  file=package.json ("build" field)
  • packaging       platform=win32 arch=x64 electron=31.3.1
  
  SignTool Error: The file is being used by another process.

**Comment by mmaietta** [comment]
Hmmm I'm not sure why `light.exe` would still have a handle on the file itself. Here's the code that is being executed, the `light(...)` is awaited and should be completely terminated by then.
https://github.com/electron-userland/electron-builder/blob/d5d9f3f9aaac0385cc943e30a0841669133afde8/packages/app-builder-lib/src/targets/MsiTarget.ts#L100-L104

Is there a minimum reproducible repo for this? And will I be able to repro this building on mac or an arm64 parallels VM?

**Comment by beyondkmp** [comment]
We encountered this issue as well. It tends to occur when building and signing MSI and NSIS simultaneously. However, we can't reproduce it when building them separately.
