### ISSUE TITLE
System.UriFormatException: Invalid URI

### ISSUE THREAD

**Issue by DeathHound6** [electron-userland/electron-builder#6877]
* **Electron-Builder Version**: 23.0.3

* **Node Version**: 17.8.0

* **Electron Version**: 18.2.3
* **Electron Type (current, beta, nightly)**: Current

* **Target**: Squirrel Windows

Cannot build the app due to `Unhandled exception: System.UriFormatException: Invalid URI: The format of the URI could not be determined.`

I am assuming this exception is caused by the fact that my system username contains a space, and so electron-builder cannot access the Update.com file inside my AppData/Local Windows directories.

```
Error: Exit code: 4294967295. Command failed: C:\Users\My Username Here\AppData\Local\electron-builder\Cache\Squirrel.Windows\Squirrel.Windows-1.9.0\Update.com --releasify F:\path\to\my\project\dist\squirrel-windows\projectname-1.0.0-full.nupkg --releaseDir F:\path\to\my\project\dist\squirrel-windows
2022-05-20 10:41:23> Unhandled exception: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at NuGet.ManifestMetadata.NuGet.IPackageMetadata.get_IconUrl()
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
System.UriFormatException: Invalid URI: The format of the URI could not be determined.      
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at NuGet.ManifestMetadata.NuGet.IPackageMetadata.get_IconUrl()
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
```

**Comment by DeathHound6** [comment]
I realise now that this is likely an issue on Windows' end, and is not something that this package's developers can fix, but any recommendations on how to get past this would be great (without renaming my user folder).

Thanks in advance
