### ISSUE TITLE
Can't reconcile two non-macho files node_modules/sqlite3/build-tmp-napi-v6/Makefile

### ISSUE THREAD

**Issue by bojanbizjak** [electron-userland/electron-builder#6894]
* **Electron-Builder Version**: 23.0.3, 23.0.4 or 23.0.9

* **Node Version**: 16.15.0 (macOS 21.3.1 Apple M1)

* **Electron Version**: 19.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: MAS

### Issue Summary

Error build MAC Universal with electron-builder 23.0.3, 23.0.4  or 23.0.9 (with electron-builder 22.11.5 works without problems.)

```curl
  ⨯ Can't reconcile two non-macho files node_modules/sqlite3/build-tmp-napi-v6/Makefile  failedTask=build stackTrace=Error: Can't reconcile two non-macho files node_modules/sqlite3/build-tmp-napi-v6/Makefile
    at Object.exports.mergeASARs (/Users/bojanbizjak/Documents/GitHub/GisMatrixApp/node_modules/@electron/universal/src/asar-utils.ts:151:13)
    at exports.makeUniversalApp (/Users/bojanbizjak/Documents/GitHub/GisMatrixApp/node_modules/@electron/universal/src/index.ts:205:13)
    at MacPackager.doPack (/Users/bojanbizjak/Documents/GitHub/GisMatrixApp/node_modules/app-builder-lib/src/macPackager.ts:125:9)
    at MacPackager.pack (/Users/bojanbizjak/Documents/GitHub/GisMatrixApp/node_modules/app-builder-lib/src/macPackager.ts:171:9)
    at Packager.doBuild (/Users/bojanbizjak/Documents/GitHub/GisMatrixApp/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/bojanbizjak/Documents/GitHub/GisMatrixApp/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/bojanbizjak/Documents/GitHub/GisMatrixApp/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/bojanbizjak/Documents/GitHub/GisMatrixApp/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/bojanbizjak/Documents/GitHub/GisMatrixApp/node_modules/builder-util/src/promise.ts:12:14)
```

**SQLite Version**: 5.0.8
"sqlite3": "^5.0.8"

### Steps to Reproduce

electron-builder -m mas --universal -c electron-builder-mas.json --publish never

electron-builder-mas.json
```json
{
    "appId": "com.gismatrix.app",
    "productName": "Gismatrix",
    "directories": {
        "output": "out",
        "buildResources": "build"
    },
    "files": [
        "dist"
    ],
    "mac": {
        "type": "distribution",
        "icon": "build/GM_1024x1024px.png",
        "artifactName": "${productName}-${version}-${os}.${ext}",
        "category": "public.app-category.productivity",
        "extendInfo": {
            "ITSAppUsesNonExemptEncryption": "NO"
        },
        "asarUnpack": [
            "**/*.node"
        ]
    },
    "mas": {
        "type": "distribution",
        "provisioningProfile": "build/GisMatrixApp_AppStore.provisionprofile",
        "hardenedRuntime": false,
        "gatekeeperAssess": false,
        "category": "public.app-category.utilities",
        "entitlements": "build/entitlements.mas.plist",
        "entitlementsInherit": "build/entitlements.mas.inherit.plist"
    }
}
```

**Comment by burgil** [comment]
Could be that I've found an interesting conversation on the topic check it out: https://github.com/electron/universal/issues/41
