### ISSUE TITLE
Does the installation for Windows surface work?

### ISSUE THREAD

**Issue by maxcnunes** [electron-userland/electron-builder#696]
* **Version**: 5.30.0
* **Target**: Windows 64bit

There is an [issue](https://github.com/sqlectron/sqlectron-gui/issues/220) opened in my app related to Windows Surface. The user says:

> I'm using it on a surface pro 4. It runs fine, just doesn't install. Every time I click on the download it shows a dialog that says it's installing, and then opens the app, but it's never installed anywhere. 

I have tested it on Windows 10 64bit and it works. Any idea why that could be occurring on Surface?

**Comment by Mercieral** [comment]
The same issue is happening on my Windows 10 64bit.... Assuming you are also using the squirrel.windows installer.

I click on the setup exe, sit through the installing gif, and the application opens and runs fine. But there is no installation anywhere. It says it is installed in the "uninstall a program" list, but it doesn't really seem to be installed as there is no shortcut, findable executable, or location in the "All app" list to run the program. The only way to do it is to pin the running application from the taskbar, which I cannot always expect the user to do. Hopefully this issue is similar to the one being experienced here as well.

I tried installing with administrator rights as well as deleting all old files and reinstalling with no difference. When I restart, after about 20 seconds I get a popup from myapp.exe saying "Installation has failed" with a check log option.

Here's the squirrel log if it helps
```
2016-08-24 14:11:59> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
2016-08-24 14:11:59> Program: Starting install, writing to C:\Users\myUser\AppData\Local\SquirrelTemp
2016-08-24 14:11:59> Program: About to install to: C:\Users\myUser\AppData\Local\myapp
2016-08-24 14:11:59> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\myUser\AppData\Local\myapp\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2016-08-24 14:11:59> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\myUser\AppData\Local\myapp\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-08-24 14:11:59> CheckForUpdateImpl: Reading RELEASES file from C:\Users\myUser\AppData\Local\SquirrelTemp
2016-08-24 14:11:59> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-08-24 14:11:59> ApplyReleasesImpl: Writing files to app directory: C:\Users\myUser\AppData\Local\myapp\app-0.1.0
2016-08-24 14:12:06> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\myUser\AppData\Local\myapp\app-0.1.0\myapp.exe]
2016-08-24 14:12:08> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-08-24 14:12:08> ApplyReleasesImpl: Examining Pin: Eclipse.lnk
2016-08-24 14:12:08> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-08-24 14:12:08> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2016-08-24 14:12:08> ApplyReleasesImpl: Examining Pin: Sublime Text 3.lnk
2016-08-24 14:12:08> ApplyReleasesImpl: Fixing up tray icons
2016-08-24 14:12:08> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-08-24 14:12:08> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-08-24 14:12:08> ApplyReleasesImpl: cleanDeadVersions: for version 0.1.0
2016-08-24 14:12:08> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.1.0
2016-08-24 14:12:09> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpWebRequest.MakeMemoryStream(Stream stream)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
2016-08-24 14:23:01> Program: Starting Squirrel Updater: --install . --checkInstall --silent
2016-08-24 14:23:01> Program: Starting install, writing to C:\Users\myUser\AppData\Local\SquirrelTemp
2016-08-24 14:23:01> Program: About to install to: C:\Users\myUser\AppData\Local\myapp
2016-08-24 14:23:02> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\myUser\AppData\Local\myapp\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-08-24 14:23:02> CheckForUpdateImpl: Reading RELEASES file from C:\Users\myUser\AppData\Local\SquirrelTemp
2016-08-24 14:23:02> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-08-24 14:23:03> ApplyReleasesImpl: Writing files to app directory: C:\Users\myUser\AppData\Local\myapp\app-0.1.0
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\content_resources_200_percent.pak to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\content_resources_200_percent.pak
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\content_shell.pak to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\content_shell.pak
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\ffmpeg.dll to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\ffmpeg.dll
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\d3dcompiler_47.dll to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\d3dcompiler_47.dll
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\myapp.exe to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\myapp.exe
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\libEGL.dll to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\libEGL.dll
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\icudtl.dat to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\icudtl.dat
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\libGLESv2.dll to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\libGLESv2.dll
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\natives_blob.bin to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\natives_blob.bin
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\LICENSE to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\LICENSE
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\node.dll to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\node.dll
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\snapshot_blob.bin to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\snapshot_blob.bin
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\ui_resources_200_percent.pak to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\ui_resources_200_percent.pak
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\squirrel.exe to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\squirrel.exe
2016-08-24 14:23:12> ApplyReleasesImpl: Moving file C:\Users\myUser\AppData\Local\myapp\app-0.1.0\lib\net45\xinput1_3.dll to C:\Users\myUser\AppData\Local\myapp\app-0.1.0\xinput1_3.dll
2016-08-24 14:23:20> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\myUser\AppData\Local\myapp\app-0.1.0\myapp.exe]
2016-08-24 14:23:22> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-08-24 14:23:22> ApplyReleasesImpl: Examining Pin: A desktop version of the myapp web application.lnk
2016-08-24 14:23:22> ApplyReleasesImpl: Examining Pin: Eclipse.lnk
2016-08-24 14:23:23> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-08-24 14:23:23> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2016-08-24 14:23:23> ApplyReleasesImpl: Examining Pin: Sublime Text 3.lnk
2016-08-24 14:23:23> ApplyReleasesImpl: Fixing up tray icons
2016-08-24 14:23:23> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-08-24 14:23:23> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-08-24 14:23:23> ApplyReleasesImpl: cleanDeadVersions: for version 0.1.0
2016-08-24 14:23:23> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.1.0
2016-08-24 14:23:25> IEnableLogger: Failed to create uninstaller registry entry: System.Xml.XmlException: 'Default' tag requires a nonempty 'Extension' attribute. Line 10, position 4.
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ValidateXmlAttribute(String attributeName, String attributeValue, String tagName, XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessDefaultTagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at NuGet.ZipPackage..ctor(String filePath)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-08-24 14:23:25> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: 'Default' tag requires a nonempty 'Extension' attribute. Line 10, position 4.
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ValidateXmlAttribute(String attributeName, String attributeValue, String tagName, XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessDefaultTagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at NuGet.ZipPackage..ctor(String filePath)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Xml.XmlException: 'Default' tag requires a nonempty 'Extension' attribute. Line 10, position 4.
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ValidateXmlAttribute(String attributeName, String attributeValue, String tagName, XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessDefaultTagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at NuGet.ZipPackage..ctor(String filePath)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```

**Comment by develar** [comment]
> Windows install doesn't set up start menu shortcut

So, it is not electron-builder issue. Because in case of Squirrel.Windows it is application responsibility to create shortcuts.

I believe that NSIS works much better than Squirrel.Windows.
