### ISSUE TITLE
Travis, OSX: Module version mismatch. Expected 48, got 49.

### ISSUE THREAD

**Issue by zaggino** [electron-userland/electron-builder#699]
* **Version**: 5.34.1

* **Target**: 1.3.4

Repository: https://github.com/zaggino/brackets-electron
Travis config: https://github.com/zaggino/brackets-electron/blob/master/.travis.yml
Travis build: https://travis-ci.org/zaggino/brackets-electron/jobs/154947402

Windows builds fine, Linux builds fine, Mac always fails with below. Any advice please?
```
Error: Module version mismatch. Expected 48, got 49.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/travis/build/zaggino/brackets-electron/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/travis/build/zaggino/brackets-electron/node_modules/macos-alias/index.js:1:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/travis/build/zaggino/brackets-electron/node_modules/ds-store/index.js:2:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
From previous event:
    at tsAwaiter (/Users/travis/build/zaggino/brackets-electron/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/Users/travis/build/zaggino/brackets-electron/node_modules/electron-builder/src/builder.ts:195:52)
    at Object.<anonymous> (/Users/travis/build/zaggino/brackets-electron/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by develar** [comment]
Relates: #683

**Comment by develar** [comment]
Reproduced, duplicates #683 Currently I am busy and cannot investigate.

**Comment by zaggino** [comment]
@develar I found a way around this.
Root issue is this: https://github.com/electron-userland/electron-prebuilt/issues/172
If I rollback to `electron-prebuilt@1.2.8` when installing `electron-builder` it compiles correctly.
Then I can do `npm install electron-prebuilt@latest` and everything works fine.
This problem only happens when `electron-builder` postinstall steps are done with `electron@1.3.x` present.
