### ISSUE TITLE
ERR_ELECTRON_BUILDER_CANNOT_EXECUTE in electron-builder --win --x62

### ISSUE THREAD

**Issue by Vigayuan** [electron-userland/electron-builder#6992]
ExecError: C:\Users\xxxx\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.2\Bin\makensis.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:
Command line defined: "APP_ID=WeTeach"
Command line defined: "APP_GUID=e5b1dbad-d815-5e80-b63e-68dca5b6ef7c"
Command line defined: "UNINSTALL_APP_KEY=e5b1dbad-d815-5e80-b63e-68dca5b6ef7c"
Command line defined: "PRODUCT_NAME=weteach-demo"
Command line defined: "PRODUCT_FILENAME=weteach-demo"
Command line defined: "APP_FILENAME=weteach-demo"
Command line defined: "APP_DESCRIPTION="
Command line defined: "VERSION=0.1.0"
Command line defined: "PROJECT_DIR=C:\Users\xxxx\Desktop\ssitproject\weteach-frontend"
Command line defined: "BUILD_RESOURCES_DIR=C:\Users\xxxx\Desktop\ssitproject\weteach-frontend\build"
Command line defined: "APP_PACKAGE_NAME=weteach-demo"
Command line defined: "MUI_ICON=C:\Users\xxxx\Desktop\ssitproject\weteach-frontend\public\logo.ico"
Command line defined: "MUI_UNICON=C:\Users\xxxx\Desktop\ssitproject\weteach-frontend\public\logo.ico"
Command line defined: "APP_32=C:\Users\xxxx\Desktop\ssitproject\weteach-frontend\dist_electron\weteach-demo-0.1.0-ia32.nsis.7z"
Command line defined: "APP_32_NAME=weteach-demo-0.1.0-ia32.nsis.7z"
Command line defined: "APP_32_HASH=D084724E0AC184CAC09BD4ECC3816D58F45056F188267BC51AFB892452DBC9014F5E6714313AC58F5309FCAED431A2A527C5D6318BFE37419C1170B7AE4A3386"
Command line defined: "APP_INSTALLER_STORE_FILE=weteach-demo-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "SHORTCUT_NAME=weteach-demo"
Command line defined: "UNINSTALL_DISPLAY_NAME=weteach-demo 0.1.0"
Command line defined: "ESTIMATED_SIZE=189958"
Command line defined: "COMPRESS=auto"
Command line defined: "UNINSTALLER_OUT_FILE=C:\Users\xxxx\Desktop\ssitproject\weteach-frontend\dist_electron\__uninstaller-nsis-weteach-demo.exe"
Processing config: C:\Users\xxxx\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.2\nsisconf.nsh
Processing script file: "<stdin>" (ACP)

Error output:
File: failed opening file "C:\Users\xxxx\Desktop\ssitproject\weteach-frontend\dist_electron\__uninstaller-nsis-weteach-demo.exe"
Error in macro installApplicationFiles on macroline 91
!include: error in script: "installSection.nsh" on line 63
Error in script "<stdin>" on line 163 -- aborting creation process

    at ChildProcess.<anonymous> (C:\Users\xxxx\Desktop\ssitproject\weteach-frontend\node_modules\builder-util\src\util.ts:250:14)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\xxxx\Desktop\ssitproject\weteach-frontend\node_modules\builder-util\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  exitCode: 1,
  alreadyLogged: false,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weteach-demo@0.1.0 electron:build: `vue-cli-service electron:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weteach-demo@0.1.0 electron:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxx\AppData\Roaming\npm-cache\_logs\2022-07-08T08_28_43_202Z-debug.log

**Comment by mmaietta** [comment]
What version of electron-builder is `vue-cli-service` using? Can you confirm you're using the latest electron-builder?

**Comment by Slapbox** [comment]
Similar issue with `23.0.3` through `23.3.1`. We only started seeing this after upgrading to `Electron@18.x.x`.

```
remove C:\projects\ourApp\release\dev\win-unpacked\icudtl.dat: The process cannot access the file because it is being used by another process.
github.com/develar/go-fs-util.EnsureEmptyDir
        /Volumes/data/go/pkg/mod/github.com/develar/go-fs-util@v0.0.0-20190620175131-69a2d4542206/fs.go:98
github.com/develar/app-builder/pkg/electron.UnpackElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronUnpack.go:38
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
        /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581
  ⨯ C:\projects\ourApp\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: C:\projects\ourApp\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (C:\projects\ourApp\node_modules\builder-util\src\util.ts:250:14)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.cp.emit (C:\projects\ourApp\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  • signing         file=release\dev\win-unpacked\ourApp-Dev.exe certificateFile=C:\projects\ourApp\keys\ourApp.p12
  • signing         file=release\dev\win-unpacked\resources\app.asar.unpacked\platform-assets\Win\IO\ourAppIO.exe certificateFile=C:\projects\ourApp\keys\ourApp.p12
  • building        target=nsis file=release\dev\ourApp-Dev-3.4.5.exe archs=x64 oneClick=true perMachine=false
  • signing         file=release\dev\win-unpacked\resources\elevate.exe certificateFile=C:\projects\ourApp\keys\ourApp.p12
  •   Signing NSIS uninstaller  file=release\dev\__uninstaller-nsis-ourApp.exe certificateFile=C:\projects\ourApp\keys\ourApp.p12
  • signing         file=release\dev\ourApp-Dev-3.4.5.exe certificateFile=C:\projects\ourApp\keys\ourApp.p12
  • building block map  blockMapFile=release\dev\ourApp-Dev-3.4.5.exe.blockmap
error Command failed with exit code 1.
```

The generated installer seems to have no problems though, which is unexpected. @mmaietta any thoughts on what might be going on that causes this to error but not actually fail?

**Comment by Slapbox** [comment]
Actually, I guess it's not related to Electron version... I wonder what's changed. So far, I can't find it.

This time the file that was supposedly in use was: `remove C:\projects\ourApp\release\dev\win-unpacked\electron.exe: The process cannot access the file because it is being used by another process.`

The file was successfully renamed to `ourApp-Dev.exe` though, so I have no idea what to make of this issue.

**Comment by Slapbox** [comment]
Scratch what I said above. The issue seems to be adding `yargs` as a dependency causes this. Strange. I'll make a new issue for this soon.

**Comment by nazar322** [comment]
I've gotten a similar issue, so I posted it here.

What I did:
1. Copy files from `electron-builder-master\packages\app-builder-lib\templates\nsis`
2. Paste it to `build` folder of my Electron.NET app.
3. Change `electron.manifest.json` to include a custom script 
```
"win": {
    "target": [
        "nsis"
    ]
}
```
```
"nsis": {
    "script": "../../../build/installer.nsi",
    "license": "../../../../EULA.txt"
}
```
in a pasted `installer.nsi` I only added 
```
;----EDITED-----------------------------------------------------
Function .onInstSuccess
	MessageBox MB_OK "onInstSuccess"
FunctionEnd

Function .onInstFailed
	MessageBox MB_OK "onInstFailed"
FunctionEnd
```
but it can't be built, here is the log... it mentions the installApplicationFiles and "installSection.nsh" just a slightly different lines
```
Package Electron App for Platform win...
npx electron-builder --config=./bin/electron-builder.json --win --x64 -c.electronVersion=23.2.0
  тАв electron-builder  version=24.9.1 os=10.0.19045
  тАв loaded configuration  file=C:\Users\Nazar\Documents\Work\Viddly\Frontend\obj\desktop\win\bin\electron-builder.json
  тАв packaging       platform=win32 arch=x64 electron=23.2.0 appOutDir=C:\Users\Nazar\Documents\Work\Viddly\Frontend\bin\Desktop\win-unpacked
  тАв building        target=nsis file=C:\Users\Nazar\Documents\Work\Viddly\Frontend\bin\Desktop\Viddly Setup 6.0.4.exe archs=x64 oneClick=true perMachine=false
  тАв uninstaller is not signed by electron-builder  reason=custom NSIS script is used
  тип C:\Users\Nazar\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
Output:
Command line defined: "APP_ID=com.viddly.app"
Command line defined: "APP_GUID=54a7c511-743b-5481-a3bd-fc18473a0e3b"
Command line defined: "UNINSTALL_APP_KEY=54a7c511-743b-5481-a3bd-fc18473a0e3b"
Command line defined: "PRODUCT_NAME=Viddly"
Command line defined: "PRODUCT_FILENAME=Viddly"
Command line defined: "APP_FILENAME=viddly"
Command line defined: "APP_DESCRIPTION=The easiest way to download online videos and convert them to MP3 or MP4."
Command line defined: "VERSION=6.0.4"
Command line defined: "PROJECT_DIR=C:\Users\Nazar\Documents\Work\Viddly\Frontend\obj\desktop\win"
Command line defined: "BUILD_RESOURCES_DIR=C:\Users\Nazar\Documents\Work\Viddly\Frontend\Resources"
Command line defined: "APP_PACKAGE_NAME=viddly"
Command line defined: "MUI_ICON=C:\Users\Nazar\Documents\Work\Viddly\Frontend\Resources\icon.ico"
Command line defined: "MUI_UNICON=C:\Users\Nazar\Documents\Work\Viddly\Frontend\Resources\icon.ico"
Command line defined: "APP_64=C:\Users\Nazar\Documents\Work\Viddly\Frontend\bin\Desktop\viddly-6.0.4-x64.nsis.7z"
Command line defined: "APP_64_NAME=viddly-6.0.4-x64.nsis.7z"
Command line defined: "APP_64_HASH=3784D8E542E47F4BD8F6184BE3E95D6C9DF4D926994BFED00655EED0435A7F7375D887EB66DEE4C54330B796F332175E0C9D163050EC84AEE1BFA573C9CAD7F8"
Command line defined: "APP_64_UNPACKED_SIZE=750193"
Command line defined: "COMPANY_NAME=Vitzo Ltd."
Command line defined: "APP_PRODUCT_FILENAME=Viddly"
Command line defined: "APP_INSTALLER_STORE_FILE=viddly-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "SHORTCUT_NAME=Viddly"
Command line defined: "UNINSTALL_DISPLAY_NAME=Viddly 6.0.4"
Command line defined: "ESTIMATED_SIZE=750192"
Command line defined: "COMPRESS=auto"
Command line defined: "UNINSTALLER_OUT_FILE"
Processing config: C:\Users\Nazar\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\nsisconf.nsh
Processing script file: "<stdin>" (UTF8)

Error output:
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in macro installApplicationFiles on macroline 91
!include: error in script: "installSection.nsh" on line 66
Error in script "<stdin>" on line 194 -- aborting creation process
  failedTask=build stackTrace=Error: C:\Users\Nazar\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
Output:
Command line defined: "APP_ID=com.viddly.app"
Command line defined: "APP_GUID=54a7c511-743b-5481-a3bd-fc18473a0e3b"
Command line defined: "UNINSTALL_APP_KEY=54a7c511-743b-5481-a3bd-fc18473a0e3b"
Command line defined: "PRODUCT_NAME=Viddly"
Command line defined: "PRODUCT_FILENAME=Viddly"
Command line defined: "APP_FILENAME=viddly"
Command line defined: "APP_DESCRIPTION=The easiest way to download online videos and convert them to MP3 or MP4."
Command line defined: "VERSION=6.0.4"
Command line defined: "PROJECT_DIR=C:\Users\Nazar\Documents\Work\Viddly\Frontend\obj\desktop\win"
Command line defined: "BUILD_RESOURCES_DIR=C:\Users\Nazar\Documents\Work\Viddly\Frontend\Resources"
Command line defined: "APP_PACKAGE_NAME=viddly"
Command line defined: "MUI_ICON=C:\Users\Nazar\Documents\Work\Viddly\Frontend\Resources\icon.ico"
Command line defined: "MUI_UNICON=C:\Users\Nazar\Documents\Work\Viddly\Frontend\Resources\icon.ico"
Command line defined: "APP_64=C:\Users\Nazar\Documents\Work\Viddly\Frontend\bin\Desktop\viddly-6.0.4-x64.nsis.7z"
Command line defined: "APP_64_NAME=viddly-6.0.4-x64.nsis.7z"
Command line defined: "APP_64_HASH=3784D8E542E47F4BD8F6184BE3E95D6C9DF4D926994BFED00655EED0435A7F7375D887EB66DEE4C54330B796F332175E0C9D163050EC84AEE1BFA573C9CAD7F8"
Command line defined: "APP_64_UNPACKED_SIZE=750193"
Command line defined: "COMPANY_NAME=Vitzo Ltd."
Command line defined: "APP_PRODUCT_FILENAME=Viddly"
Command line defined: "APP_INSTALLER_STORE_FILE=viddly-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "SHORTCUT_NAME=Viddly"
Command line defined: "UNINSTALL_DISPLAY_NAME=Viddly 6.0.4"
Command line defined: "ESTIMATED_SIZE=750192"
Command line defined: "COMPRESS=auto"
Command line defined: "UNINSTALLER_OUT_FILE"
Processing config: C:\Users\Nazar\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\nsisconf.nsh
Processing script file: "<stdin>" (UTF8)
                                                                                                                                                                                                                                                                                                                                                                                                                    Error output:
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in macro installApplicationFiles on macroline 91
!include: error in script: "installSection.nsh" on line 66
Error in script "<stdin>" on line 194 -- aborting creation process
                                                                                                                                                                                                          at ChildProcess.<anonymous> (C:\Users\Nazar\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.cp.emit (C:\Users\Nazar\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)


... done
```
