### ISSUE TITLE
Introducing deb and rpm auto-updates (help wanted)

### ISSUE THREAD

**Issue by mmaietta** [electron-userland/electron-builder#7061]
Hey folks!

One of the maintainers for electron-builder here. Looking for feedback on my Draft PR for deb and rpm auto-updates.

I've gotten it to work with various VMs on my local machine, but I don't know enough about the Linux ecosystem to verify I've covered enough use cases/flows (GUI sudo + package manager options). Also, need to determine if we can read a file from the linux package when instantiating autoUpdater (manually written to resources `package-type` that contains `rpm` or `deb` as text to self-identify the app's installation method). Alternative approaches/suggestions are welcome.

Please take a look when you have a chance and leave comments https://github.com/electron-userland/electron-builder/pull/7060

Thank you!

**Comment by Jaifroid** [comment]
Since the linked PR is closed, I'm commenting here. My deb errors out when trying to install (on quitting the app), on Debian GNU/Linux 11 (bullseye). It happens after every launch and quit of the app. The main error appears to be `TypeError: Cannot read properties of null (reading 'trim') at DebUpdater.spawnSyncLog (/opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/BaseUpdater.js:113:32)`. The full log of what is displayed in terminal:

```
Checking for update
Found version 2.5.6-E (url: Kiwix-JS-Electron-2.5.6-E.AppImage, kiwix-js-electron_2.5.6-E_amd64.deb, kiwix-js-electron-2.5.6-E.x86_64.rpm)
Downloading update from Kiwix-JS-Electron-2.5.6-E.AppImage, kiwix-js-electron_2.5.6-E_amd64.deb, kiwix-js-electron-2.5.6-E.x86_64.rpm
updater cache dir: /home/jaifroid/.cache/kiwix-js-electron-updater
New version 2.5.6-E has been downloaded to /home/jaifroid/.cache/kiwix-js-electron-updater/pending/kiwix-js-electron_2.5.6-E_amd64.deb
Auto install update on quit
Install: isSilent: true, isForceRunAfter: false
Executing: which gksudo || which kdesudo || which pkexec || which beesu with args:
Error: TypeError: Cannot read properties of null (reading 'trim')
    at DebUpdater.spawnSyncLog (/opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/BaseUpdater.js:113:32)
    at DebUpdater.wrapSudo (/opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/BaseUpdater.js:91:27)
    at DebUpdater.doInstall (/opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/DebUpdater.js:28:27)
    at DebUpdater.install (/opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/BaseUpdater.js:54:25)
    at /opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/BaseUpdater.js:85:18
    at App.<anonymous> (/opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/ElectronAppAdapter.js:35:48)
    at Object.onceWrapper (node:events:628:26)
    at App.emit (node:events:525:35)
    at App.<anonymous> (/opt/Kiwix JS Electron/resources/app/main.cjs:187:44)
    at App.emit (node:events:525:35)
```

**Comment by Jaifroid** [comment]
I also tried it on Fedora 36 Workstation Edition with an rpm package. Similar error, a bit more info:

```
Auto install update on quit
Install: isSilent: true, isForceRunAfter: false
Executing: which gksudo || which kdesudo || which pkexec || which beesu with args: 
/usr/bin/which: no gksudo in (/home/gkant/.local/bin:/home/gkant/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin)
/usr/bin/which: no kdesudo in (/home/gkant/.local/bin:/home/gkant/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin)
/usr/bin/pkexec
Error: TypeError: Cannot read properties of null (reading 'trim')
    at RpmUpdater.spawnSyncLog (/opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/BaseUpdater.js:113:32)
    at RpmUpdater.wrapSudo (/opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/BaseUpdater.js:91:27)
    at RpmUpdater.doInstall (/opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/RpmUpdater.js:29:27)
    at RpmUpdater.install (/opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/BaseUpdater.js:54:25)
    at /opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/BaseUpdater.js:85:18
    at App.<anonymous> (/opt/Kiwix JS Electron/resources/app/node_modules/electron-updater/out/ElectronAppAdapter.js:35:48)
    at Object.onceWrapper (node:events:628:26)
    at App.emit (node:events:525:35)
    at App.<anonymous> (/opt/Kiwix JS Electron/resources/app/main.cjs:187:44)
    at App.emit (node:events:525:35)
```

**Comment by Jaifroid** [comment]
@mmaietta OK, I've disabled autoupdate for rpm and deb by removing the update packages from the autoupdate tag release on GitHub, and by editing `latest-linux.yml` and `latest-linux-ia32.yml` to remove reference to the deb and rpm packages.

HOWEVER, this code nevertheless goes ahead and downloads the AppImage package, converting it into an `update.deb` file which is invalid (can't be installed manually either).

I'm afraid this code is pretty broken. How can I opt out of auto-update for deb and rpm, as my app is giving spurious notifications that an update is ready to install? I would much rather notify my users that a package is available from a URL to download manually than to have this buggy behaviour.

**Comment by mmaietta** [comment]
Please open a new GitHub issue and link back here. I'll take a look when I have a chance
