### ISSUE TITLE
Squirrel.Windows : Name cannot begin with the '3' character, hexadecimal value 0x33

### ISSUE THREAD

**Issue by Toobian** [electron-userland/electron-builder#707]
* **Version**: 5.34.1

* **Target**: windows (x64)

When I try to create windows installer, I have this stack :
```
Warning: Application icon is not set, default Electron icon will be used
Installing app dependencies for arch x64 to C:\Users\Quentin\jarvis\dist

Packaging for platform win32 x64 using electron 1.3.4 to out\win-unpacked

Building Squirrel.Windows installer

Warning: Cannot delete temporary dir "C:\Users\Quentin\AppData\Local\Temp\electron-builder-ez7GEJ": Error: EPERM: operation not permitted, unlink 'C:\Users\Quentin\AppData\Local\Temp\electron-builder-ez7GEJ\1-setup.zip'
    at Error (native)
Error: Command failed: C:\Users\Quentin\.cache\Squirrel.Windows\Squirrel.Windows-1.4.4\Update.com --releasify C:\Users\Quentin\jarvis\out\win\jarvis-0.1.0-full.nupkg --releaseDir C:\Users\Quentin\jarvis\out\win
2016-08-26 23:15:09> Unhandled exception: System.Xml.XmlException: Le caract�re '3', valeur hexad�cimale 0x33, ne peut pas commencer un nom. Ligne 11, position 93.
   � System.Xml.XmlTextReaderImpl.Throw(Exception e)
   � System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   � System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   � System.Xml.XmlTextReaderImpl.ParseElement()
   � System.Xml.XmlTextReaderImpl.ParseElementContent()
   � System.Xml.XmlTextReaderImpl.Read()
   � System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   � System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   � System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   � NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   � NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   � NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   � NuGet.ZipPackage.EnsureManifest()
   � NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   � Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   � Squirrel.Update.Program.executeCommandLine(String[] args)
   � Squirrel.Update.Program.main(String[] args)
System.Xml.XmlException: Le caract�re '3', valeur hexad�cimale 0x33, ne peut pas commencer un nom. Ligne 11, position 93.
   � System.Xml.XmlTextReaderImpl.Throw(Exception e)
   � System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   � System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   � System.Xml.XmlTextReaderImpl.ParseElement()
   � System.Xml.XmlTextReaderImpl.ParseElementContent()
   � System.Xml.XmlTextReaderImpl.Read()
   � System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   � System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   � System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   � NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   � NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   � NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   � NuGet.ZipPackage.EnsureManifest()
   � NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   � Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   � Squirrel.Update.Program.executeCommandLine(String[] args)
   � Squirrel.Update.Program.main(String[] args)
   � Squirrel.Update.Program.Main(String[] args)

2016-08-26 23:15:09> Program: Starting Squirrel Updater: --releasify C:\Users\Quentin\jarvis\out\win\jarvis-0.1.0-full.nupkg --releaseDir C:\Users\Quentin\jarvis\out\win

2016-08-26 23:15:09> Unhandled exception: System.Xml.XmlException: Le caract�re '3', valeur hexad�cimale 0x33, ne peut pas commencer un nom. Ligne 11, position 93.
   � System.Xml.XmlTextReaderImpl.Throw(Exception e)
   � System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   � System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   � System.Xml.XmlTextReaderImpl.ParseElement()
   � System.Xml.XmlTextReaderImpl.ParseElementContent()
   � System.Xml.XmlTextReaderImpl.Read()
   � System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   � System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   � System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   � NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   � NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   � NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   � NuGet.ZipPackage.EnsureManifest()
   � NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   � Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   � Squirrel.Update.Program.executeCommandLine(String[] args)
   � Squirrel.Update.Program.main(String[] args)
System.Xml.XmlException: Le caract�re '3', valeur hexad�cimale 0x33, ne peut pas commencer un nom. Ligne 11, position 93.
   � System.Xml.XmlTextReaderImpl.Throw(Exception e)
   � System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   � System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   � System.Xml.XmlTextReaderImpl.ParseElement()
   � System.Xml.XmlTextReaderImpl.ParseElementContent()
   � System.Xml.XmlTextReaderImpl.Read()
   � System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   � System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   � System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   � NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   � NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   � NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   � NuGet.ZipPackage.EnsureManifest()
   � NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   � Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
   � Squirrel.Update.Program.executeCommandLine(String[] args)
   � Squirrel.Update.Program.main(String[] args)
   � Squirrel.Update.Program.Main(String[] args)

    at C:\Users\Quentin\jarvis\node_modules\electron-builder\src\util\util.ts:96:16
    at ChildProcess.exithandler (child_process.js:214:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at Object.exec (C:\Users\Quentin\jarvis\node_modules\electron-builder\src\util\util.ts:77:9)
    at C:\Users\Quentin\jarvis\node_modules\electron-builder\src\targets\squirrelPack.ts:183:26
    at next (native)
From previous event:
    at tsAwaiter (C:\Users\Quentin\jarvis\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at Object.build (C:\Users\Quentin\jarvis\node_modules\electron-builder\src\builder.ts:195:52)
    at Object.<anonymous> (C:\Users\Quentin\jarvis\node_modules\electron-builder\src\build-cli.ts:27:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

For your information : app's folder is "dist" (webpack's ouput folder) and the output folder is "out".

I don't know why I have this error, '3' character is not in any config file. Help ?

Thanks

**Comment by develar** [comment]
Please enable debug — set env DEBUG=electron-builder and output.

**Comment by Toobian** [comment]
Sorry for the delay.

In fact, I have "<3" characters in my description :s

Thanks for debug param, it's very helpfull.

**Comment by develar** [comment]
Our NSIS target is better than Squirrel.Windows, but #529 not yet done.
