### ISSUE TITLE
EV Code Signing Issues 

### ISSUE THREAD

**Issue by Adamylo** [electron-userland/electron-builder#7153]
* **Electron-Builder Version**:  22.14.5

* **Node Version**: 17.1.0

* **Electron Version**:15.3.0

* **Target**:  Windows 

**Background** 
We started our Electron build a while back. We use GitLab CI/CD to roll out the Electron windows App. We could get the code signing working when we had a standard certificate. 

As with most others, we have upgraded to an EV signing certificate and having significant issues. 

We found a great article here which we followed https://interactiveknowledge.com/insights/how-code-sign-electron-app-windows 

However, we can not seem to get the code signing structure correct. The latest error is related to finding the actual certificates; see below. 

I have been digging around in GitHub and have not found any issues the same so far. 

Any help is appreciated. 

```
` Cannot find certificate Online Technology Australia PTY LTD, all certs:   failedTask=build stackTrace=Error: Cannot find certificate Online Technology Australia PTY LTD, all certs: 
    at Object.getCertificateFromStoreInfo (C:\GitLab-Runner\builds\vw-app-group\test\node_modules\app-builder-lib\src\codeSign\windowsCodeSign.ts:142:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at WinPackager.sign (C:\GitLab-Runner\builds\vw-app-group\test\node_modules\app-builder-lib\src\winPackager.ts:205:21)
    at WinPackager.signAndEditResources (C:\GitLab-Runner\builds\vw-app-group\test\node_modules\app-builder-lib\src\winPackager.ts:342:5)
From previous event:
    at processImmediate (node:internal/timers:464:21)
From previous event:
    at WinPackager.signApp (C:\GitLab-Runner\builds\vw-app-group\test\node_modules\app-builder-lib\src\winPackager.ts:376:27)
    at WinPackager.doSignAfterPack (C:\GitLab-Runner\builds\vw-app-group\test\node_modules\app-builder-lib\src\platformPackager.ts:327:16)
    at WinPackager.doPack (C:\GitLab-Runner\builds\vw-app-group\test\node_modules\app-builder-lib\src\platformPackager.ts:312:7)
    at WinPackager.pack (C:\GitLab-Runner\builds\vw-app-group\test\node_modules\app-builder-lib\src\platformPackager.ts:136:5)
    at Packager.doBuild (C:\GitLab-Runner\builds\vw-app-group\test\node_modules\app-builder-lib\src\packager.ts:441:9)
    at Object.executeFinally (C:\GitLab-Runner\builds\vw-app-group\test\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\GitLab-Runner\builds\vw-app-group\test\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (C:\GitLab-Runner\builds\vw-app-group\test\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally `(C:\GitLab-Runner\builds\vw-app-group\test\node_modules\builder-util\src\promise.ts:12:14)`
```

**Comment by Signo-Alaris** [comment]
Experiencing the same issue

**Comment by BrettHoutz** [comment]
This appears to be due to an assumption that if `certificateSubjectName` or `certificateSha1` are specified, then the certificate must be registered in the system certificate manager.

https://github.com/electron-userland/electron-builder/blob/c9d20db964cce991dab137ec0105d40d8eacd95c/packages/app-builder-lib/src/winPackager.ts#L42-L44

This assumption doesn't make sense because specifying those options can be used to differentiate between multiple certificates bundled into a single file.

I was able to work around this by adding commands to import the certificate before building to my CI workflow (this uses GitHub Actions syntax to inject the key password).

```ps1
$CscPassSecure = ConvertTo-SecureString "${{secrets.CSC_KEY_PASSWORD}}" -AsPlainText -Force
Import-PfxCertificate -FilePath .\release\csc.pfx -CertStoreLocation 'Cert:\LocalMachine\My' -Password $CscPassSecure -Exportable
```
