### ISSUE TITLE
Issue with electron-updater on github enterprise

### ISSUE THREAD

**Issue by colinfran** [electron-userland/electron-builder#7162]
* **Electron-Builder Version**:  23.3.3

* **Node Version**:  14.15.5

* **Electron Version**: 21.0.0
* **Electron Type (current, beta, nightly)**: current

* **Electron-Updater Version**:  5.2.1

* **Target**: mac - dmg

Auto update not working with Github Enterprise.

getting error:
```
Error in auto-updater.
Error: Attribute without value
Line: 100
Column: 64
Char: >
    at error (/Applications/WCD_AssetWorker.app/Contents/Resources/app.asar/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/Applications/WCD_AssetWorker.app/Contents/Resources/app.asar/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/Applications/WCD_AssetWorker.app/Contents/Resources/app.asar/node_modules/sax/lib/sax.js:1321:13)
    at Object.parseXml (/Applications/WCD_AssetWorker.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/xml.js:105:12)
    at GitHubProvider.getLatestVersion (/Applications/WCD_AssetWorker.app/Contents/Resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:41:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MacUpdater.getUpdateInfoAndProvider (/Applications/WCD_AssetWorker.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:305:19)
    at async MacUpdater.doCheckForUpdates (/Applications/WCD_AssetWorker.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:24)
```

my package.json has 
```
"build": {
    "asar": true,
    "files": [
      "build/**/*",
      "node_modules/**/*"
    ],
    "asarUnpack": [
      "**/*.node",
      "**/node_modules/puppeteer/**/*"
    ],
    "appId": "com.wcd.wcd-assetworker",
    "afterSign": "./tasks/afterSignHook.js",
    "mac": {
      "icon": "build/icons/icon.png",
      "type": "distribution",
      "hardenedRuntime": true,
      "entitlements": "build/entitlements/entitlements.mac.inherit.plist",
      "entitlementsInherit": "build/entitlements/entitlements.mac.inherit.plist",
      "gatekeeperAssess": false,
      "publish": {
        "provider": "github",
        "owner": "wcd",
        "repo": "AssetWorker",
        "releaseType": "release",
        "host": "github.mydomain.com"
      }
    },
    "dmg": {
      "sign": false
    },
    "directories": {
      "output": "releases/"
    }
  }
```

I export my github token. 

when i build i run `electron-builder build -p always`

it correctly builds, notarizes, and publishes a release to my enterprise github repo.

so I download release and install. 

everytime i open the app, it logs the above error message through
```
autoUpdater.on("error", (err) => {
  log.error("Error in auto-updater.")
  log.error(err)
})
```

**Comment by colinfran** [comment]
so i think i may have figured out this issue. although im not sure if its just a universal issue for enterprise github release auto update or just my code. 

I came to conclusion that auto-updater was not using my exported GH_TOKEN variable. which i would export when i would run the builder command. so that token was being used to publish the release correctly. but it wasn't getting used within the auto updater causing it to error.

i ended up hardcoding
```
autoUpdater.setFeedURL({
  provider: "github",
  owner: "wcd",
  repo: "AssetWorker",
  host: "github.mydomain.com",
  token: env.token,
})
```
this allowed it to work correctly.

**Comment by mmaietta** [comment]
This is a common misnomer as electron-builder is a packager, not a code bundler. The publisher logic uses the GH_TOKEN (or any other related env var) during packaging step, which is a dev dependency and not compiled/bundled into your app assets. The updater **will not** access env vars and it is bundled as part of your distributable. Updater tokens must be set manually
