### ISSUE TITLE
Differential download fails with generic provider (Google cloud storage bucket)

### ISSUE THREAD

**Issue by adityaddy** [electron-userland/electron-builder#7179]
* **Electron-Builder Version**: 23.1.0

* **Node Version**: 16.15.1

* **Electron Version**: 20.1.1
* **Electron Type (current, beta, nightly)**: current
 5.2.1

* **Target**: Windows

Differential download always fails with Status 400. I am using Generic Provider (GCS  bucket with byte range download enabled).
I can confirm the `"accept-ranges": "bytes"` in the header
```
Cannot download differentially, fallback to full download: HttpError: 400
at Object.createHttpError (C:\Users\work\AppData\Local\Programs\[appname]\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:14:12)
    at checkIsRangesSupported (C:\Users\work\AppData\Local\Programs\[appname]\resources\app.asar\node_modules\electron-updater\out\differentialDownloader\multipleRangeDownloader.js:99:39)
    at ClientRequest.<anonymous> (C:\Users\work\AppData\Local\Programs\[appname]\resources\app.asar\node_modules\electron-updater\out\differentialDownloader\multipleRangeDownloader.js:74:14)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.emit (node:domain:475:12)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)
    at SimpleURLLoaderWrapper.emit (node:events:527:28)
    at SimpleURLLoaderWrapper.emit (node:domain:475:12)
```

**Comment by LebedevGor** [comment]
Exactly the same problem.  @adityaddy could you resolve it?
