### ISSUE TITLE
error:spawn ENAMETOOLONG when builder dmg in mac m1

### ISSUE THREAD

**Issue by 826327700** [electron-userland/electron-builder#7192]
* **Electron-Builder Version**: 
v 23.6.0

* **Node Version**: 
v 16.17.0

* **Electron Version**:
v 19.1.0

* **Target**: 
macos m1

```bash
Building app with electron-builder:
  • electron-builder  version=22.14.13 os=21.6.0
  • loaded configuration  file=/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/electron-builder.yml
  • description is missed in the package.json  appPackageFile=/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/dist/bundled/package.json
  • author is missed in the package.json  appPackageFile=/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/dist/bundled/package.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=arm64 electron=19.1.0 appOutDir=dist/mac-arm64
  • empty password will be used for code signing  reason=CSC_KEY_PASSWORD is not defined
  • signing         file=dist/mac-arm64/Nbuilder渲染助手.app identityName=Developer ID Application: TONG YIN LONG (D25JRM8GLJ) identityHash=EE4BE7E89A846660666044322D78903F96BDEC21 provisioningProfile=none
  • building        target=macOS zip arch=arm64 file=dist/Nbuilder渲染助手-0.1.0-arm64-mac.zip
  • building        target=DMG arch=arm64 file=dist/nbuilder-render-desktop-0.1.0.dmg
  • Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+
  • building block map  blockMapFile=dist/Nbuilder渲染助手-0.1.0-arm64-mac.zip.blockmap
Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:713:9)
    at Object.execFile (node:child_process:329:17)
    at /Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/dmg-builder/node_modules/builder-util/src/util.ts:94:5
    at new Promise (<anonymous>)
    at Object.exec (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/dmg-builder/node_modules/builder-util/src/util.ts:93:10)
    at executePython (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/dmg-builder/src/dmg.ts:305:11)
    at customizeDmg (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/dmg-builder/src/dmg.ts:313:11)
    at Object.executeFinally (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/dmg-builder/node_modules/builder-util/src/promise.ts:12:14)
    at Object.attachAndExecute (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/dmg-builder/src/dmgUtil.ts:33:10)
    at DmgTarget.build (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/dmg-builder/src/dmg.ts:59:11)
    at async Promise.all (index 1)
    at AsyncTaskManager.awaitTasks (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at Packager.doBuild (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/app-builder-lib/src/packager.ts:453:5)
    at Object.executeFinally (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/xiaobaozi/Documents/developer/node/nbuilder-render-desktop/node_modules/builder-util/src/promise.ts:12:14) {
  errno: -63,
  code: 'ENAMETOOLONG',
  syscall: 'spawn'
}
```
Who can resolve this problem ？help me , thanks!

**Comment by 826327700** [comment]
I've found a solution，that is my mistake to set path in .zshrc
