### ISSUE TITLE
error when using electron-buider for mac on linux

### ISSUE THREAD

**Issue by buivietqng02** [electron-userland/electron-builder#7220]
electron-builder --mac

  • electron-builder version=19.56.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=19.1.3 appOutDir=dist/mac
Error: ENOENT: no such file or directory, open '/home/viet/iptp/xm-desktop/dist/mac/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist'
    at /home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/src/packager/mac.ts:43:215
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at /home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/src/packager/mac.ts:43:61
    at Generator.next (<anonymous>)
From previous event:
    at createMacApp (/home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/out/packager/mac.js:142:21)
    at /home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/src/macPackager.ts:263:11
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.beforeCopyExtraFiles (/home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/out/macPackager.js:374:11)
    at /home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/src/platformPackager.ts:200:16
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at MacPackager.doPack (/home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/out/platformPackager.js:276:11)
    at /home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/src/macPackager.ts:93:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/out/macPackager.js:219:11)
    at /home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/src/packager.ts:364:24
    at Generator.next (<anonymous>)
    at /home/viet/iptp/xm-desktop/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
    at callback (/home/viet/iptp/xm-desktop/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (fs.js:176:5)
From previous event:
    at Packager.doBuild (/home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/out/packager.js:432:11)
    at /home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/src/packager.ts:308:52
    at Generator.next (<anonymous>)
    at /home/viet/iptp/xm-desktop/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/viet/iptp/xm-desktop/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:163:23)
From previous event:
    at Packager._build (/home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/out/packager.js:376:11)
    at /home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/src/packager.ts:270:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/home/viet/iptp/xm-desktop/node_modules/electron-builder-lib/out/packager.js:332:11)
    at /home/viet/iptp/xm-desktop/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/home/viet/iptp/xm-desktop/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/viet/iptp/xm-desktop/node_modules/electron-builder/src/builder.ts:280:10)
    at /home/viet/iptp/xm-desktop/node_modules/electron-builder/src/cli/cli.ts:48:33
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Object.handler (/home/viet/iptp/xm-desktop/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/home/viet/iptp/xm-desktop/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/viet/iptp/xm-desktop/node_modules/yargs/yargs.js:1050:24)
    at Object.get [as argv] (/home/viet/iptp/xm-desktop/node_modules/yargs/yargs.js:965:21)
    at Object.<anonymous> (/home/viet/iptp/xm-desktop/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xm_electron@1.0.0 build:m: `electron-builder --mac`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xm_electron@1.0.0 build:m script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
----------------------------------------
packeage.json
{
  "name": "xm_electron",
  "productName": "XM_desktop",
  "version": "1.0.0",
  "description": "Electron Desktop App Wrapper for PWAs / IPTP Ltd",
  "homepage": "https://xm.iptp.net",
  "desktopName": "xm.desktop",
  "main": "index.js",
  "author": {
    "name": "xTools",
    "email": "sa@iptp.net"
  },
  "license": "GPLv3",
  "repository": {
    "type": "git",
    "url": "https://github.com/xtools-at/Electron-PWA-Wrapper.git"
  },
  "scripts": {
    "electron": "electron .",
    "start": "./node_modules/.bin/electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "prod": "npm run docker:build; npm run docker:run; npm run docker:buildApps",
    "build:mwl": "electron-builder -mwl",
    "build:m": "electron-builder --mac",
    "build:w": "electron-builder --win",
    "build:wl": "electron-builder -wl",
    "docker:build": "scripts/docker-build.sh",
    "docker:run": "scripts/docker.sh",
    "docker:buildApps": "scripts/docker-build-apps.sh",
    "build:main": "webpack --config ./webpack.main.js --mode development",
    "xm-build": "cd xm-web && npm run build:prod && cd .. && npm run electron",
    "xm": "cd xm-web && npm run build && cd .. && npm run electron"
  },
  "devDependencies": {
    "electron": "^19.1.3",
    "electron-builder": "^19.56.2",
    "electron-debug": "^3.2.0",
    "electron-is-dev": "^2.0.0",
    "electron-isDev": "^0.1.0",
    "electron-packager": "^16.0.0",
    "electron-reload": "^1.5.0"
  },
  "dependencies": {
    "@jitsi/electron-sdk": "^3.3.4",
    "app-builder-lib": "^24.0.0-alpha.1",
    "dmg-builder": "^23.6.0",
    "electron-context-menu": "^3.1.1",
    "emoji-regex": "^10.2.1",
    "string-width": "^5.1.2",
    "webpack": "^5.74.0",
    "webpack-cli": "^4.10.0"
  },
  "files": [
    "index1.js",
    "index.js",
    "app",
    "build",
    "build/**/*",
    "!node_modules",
    "!node_modules/**/*",
    "xm-web",
    "xm-web/**/*",
    "!xm-web/node_modules",
    "src/ipcPreloader.js"
  ],
  "build": {
    "appId": "com.electron.${name}",
    "productName": "XM_desktop",
    "copyright": "Copyright © 2021 IPTP Ltd",
    "directories": {
      "output": "dist",
      "buildResources": "build"
    },
    "asar": true,
    "files": [
      "index1.js",
      "index.js",
      "app",
      "build",
      "build/**/*",
      "node_modules",
      "node_modules/**/*",
      "xm-web",
      "xm-web/**/*",
      "!xm-web/node_modules",
      "src",
      "src/**/*"
    ],
    "mac": {
      "category": "public.app-category.finance",
      "target": [
        {
          "target": "dmg"
        }
      ],
      "icon": "build/icon.icns"
    },
    "win": {
      "target": [
        {
          "target": "portable"
        }
      ],
      "icon": "build/icon.png",
      "legalTrademarks": "Copyright © 2021 IPTP Ltd",
      "publisherName": "xTools"
    },
    "portable": {},
    "linux": {
      "target": [
        "deb"
      ],
      "vendor": "IPTP Ltd.",
      "category": "Network;InstantMessaging;Chat",
      "desktop": {
        "StartupWMClass": "xm",
        "MimeType": "x-scheme-handler/xm"
      },
      "maintainer": "xTools"
    },
    "deb": {},
    "rpm": {
      "depends": [
        "libxshmfence",
        "libdrm",
        "mesa-libgbm",
        "alsa-lib",
        "libX11-xcb"
      ]
    }
  }
}

**Comment by mmaietta** [comment]
Please use `latest` or `next` version of electron-builder, your package.json shows `"electron-builder": "^19.56.2",`

Please remove `"app-builder-lib": "^24.0.0-alpha.1",` from your dependency list

**Comment by buivietqng02** [comment]
Thanks
