### ISSUE TITLE
Cleanup fail after build

### ISSUE THREAD

**Issue by lyssdod** [electron-userland/electron-builder#724]
* **Version**: 6.3.5

* **Target**: Linux

```
Warning: Cannot delete temporary dir "/tmp/electron-builder-587b-156ef6f6827-0": Error: ENOTEMPTY: directory not empty, rmdir '/tmp/electron-builder-587b-156ef6f6827-0'
    at Error (native)
From previous event:
    at TmpDir.cleanup (/storage/work/ea-todo/node_modules/electron-builder/src/util/tmp.ts:61:18)
    at /storage/work/ea-todo/node_modules/electron-builder/src/packager.ts:98:132
    at Object.<anonymous> (/storage/work/ea-todo/node_modules/electron-builder/src/util/promise.ts:20:13)
    at throw (native)
From previous event:
    at tsAwaiter (/storage/work/ea-todo/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/storage/work/ea-todo/node_modules/electron-builder/src/builder.ts:195:52)
    at Object.<anonymous> (/storage/work/ea-todo/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```

Seems like a bug in `fs-extra` ?

**Comment by develar** [comment]
But build is not failed?

**Comment by lyssdod** [comment]
No, just cleaning :)
