### ISSUE TITLE
Unable to Build Linux installer on a Windows Maschine

### ISSUE THREAD

**Issue by MTRNord** [electron-userland/electron-builder#725]
* **Version**: 6.4.0

* **Target**: Linux

When I want to build for Linux on my Windows Maschine it Fails always with:

```
$ C:/Users/Marcel/AppData/Roaming/npm/build --linux
Skip app dependencies rebuild because platform is different
Packaging for platform linux x64 using electron 1.3.5 to dist\linux-unpacked

Warning: Application icon is not set, default Electron icon will be used
Warning: Application icon is not set, default Electron icon will be used
Warning: Application icon is not set, default Electron icon will be used
Error: spawn fpm ENOENT
    at C:\Users\Marcel\AppData\Roaming\npm\node_modules\electron-builder\src\util\util.ts:96:16
    at exithandler (child_process.js:209:5)
    at ChildProcess.errorhandler (child_process.js:221:5)
    at emitOne (events.js:90:13)
    at ChildProcess.emit (events.js:182:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:202:12)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Object.exec (C:\Users\Marcel\AppData\Roaming\npm\node_modules\electron-builder\src\util\util.ts:77:9)
    at FpmTarget.<anonymous> (C:\Users\Marcel\AppData\Roaming\npm\node_modules\electron-builder\src\targets\fpm.ts:142:15)
    at next (native)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at tsAwaiter (C:\Users\Marcel\AppData\Roaming\npm\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at Object.build (C:\Users\Marcel\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:179:52)
    at Object.<anonymous> (C:\Users\Marcel\AppData\Roaming\npm\node_modules\electron-builder\src\build-cli.ts:27:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

SourceCode is at: https://github.com/MTRNord/ls-vertretungsplan-desktop/tree/a8f92b931b23caefd53f739be7e96f984260241a

**Comment by develar** [comment]
It is not supported. It is easy to build AppImage (consider to use this target for Linux), but not yet supported. https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

Please use Docker as a simple solution https://github.com/electron-userland/electron-builder/wiki/Docker
