### ISSUE TITLE
"No identity found for signing." v24.0.0-alpha.8, macOS 13.0.1

### ISSUE THREAD

**Issue by Dotnaught** [electron-userland/electron-builder#7342]
* **Electron-Builder Version**:  ^v24.0.0-alpha.8

* **Node Version**: v16.17.1

* **Electron Version**: ^22.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  macOS 13.0.1

Attempting to resolve 6 high severity vulnerabilities related to minimatch  <3.0.5 for my RSS app [RSSputin](https://github.com/Dotnaught/rssputin), I replaced electron-builder v23.6.0 with v24.0.0-alpha.8. This eliminated the vulnerabilities detected by npm audit but broke code signing/notarization, which works as expected with electron-builder v23.6.0. Specifically: " ⨯ No identity found for signing."

> rssputin@1.0.9 pack
> electron-builder --dir

  • electron-builder  version=24.0.0-alpha.8 os=22.1.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • executing @electron/rebuild  appDir=/Users/x/Code/ghub/rssputin arch=arm64
  • loaded configuration  file=package.json ("build" field)
  • packaging       platform=darwin arch=arm64 electron=22.0.0 appOutDir=dist/mac-arm64
  • signing         file=dist/mac-arm64/rssputin.app identityName=Developer ID Application: xxxxxxxxx (xxxxxxxxxx) identityHash=xxxxxxxxxxxxxxxxxxxxxxx provisioningProfile=build/rssputin_dev.provisionprofile
  ⨯ **No identity found for signing.**  failedTask=build stackTrace=Error: No identity found for signing.
    at signApp (/Users/x/Code/ghub/rssputin/node_modules/@electron/osx-sign/src/sign.ts:360:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MacPackager.sign (/Users/x/Code/ghub/rssputin/node_modules/app-builder-lib/src/macPackager.ts:324:5)
    at /Users/x/Code/ghub/rssputin/node_modules/app-builder-lib/src/macPackager.ts:452:9
From previous event:
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at MacPackager.signApp (/Users/x/Code/ghub/rssputin/node_modules/app-builder-lib/src/macPackager.ts:449:27)
    at MacPackager.doSignAfterPack (/Users/x/Code/ghub/rssputin/node_modules/app-builder-lib/src/platformPackager.ts:329:16)
    at MacPackager.doPack (/Users/x/Code/ghub/rssputin/node_modules/app-builder-lib/src/platformPackager.ts:314:7)
    at MacPackager.pack (/Users/x/Code/ghub/rssputin/node_modules/app-builder-lib/src/macPackager.ts:194:7)
    at Packager.doBuild (/Users/x/Code/ghub/rssputin/node_modules/app-builder-lib/src/packager.ts:441:9)
    at executeFinally (/Users/x/Code/ghub/rssputin/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/x/Code/ghub/rssputin/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/x/Code/ghub/rssputin/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/Users/x/Code/ghub/rssputin/node_modules/builder-util/src/promise.ts:12:14)

Possibly related to differences in these packages, with these warnings being associated with reverting to v23.6.0.

npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different

**Comment by Dotnaught** [comment]
Appears to be related to this issue:
https://github.com/electron-userland/electron-builder/issues/7317

**Comment by filfreire** [comment]
@Dotnaught I believe this is fixed after https://github.com/electron-userland/electron-builder/pull/7351 - in latest v24.0.0-alpha.9

**Comment by Dotnaught** [comment]
Thanks, as it happens I did a build yesterday (https://github.com/Dotnaught/rssputin) with alpha.9 and it worked properly. I appreciate the follow up.
