### ISSUE TITLE
electron-builder build failed 

### ISSUE THREAD

**Issue by himaniChaine** [electron-userland/electron-builder#7347]
* **23.6.0**: 

* **v16.16.0n**: 

* **21.2.2**:

no

* **MAC**: 
also able to see ➜ 
 ```
 web-app git:(feat/electron) ✗ which python
/usr/local/bin/python
```

```⨯ spawn ENOTDIR   failedTask=build stackTrace=Error: spawn ENOTDIR
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:700:9)
    at Object.execFile (node:child_process:327:17)
    at /Users/himani/Documents/Github/chaine/.yarn/cache/builder-util-npm-23.6.0-2b87d7882d-138fb9abed.zip/node_modules/builder-util/src/util.ts:94:5
    at new Promise (<anonymous>)
    at Object.exec (/Users/himani/Documents/Github/chaine/.yarn/cache/builder-util-npm-23.6.0-2b87d7882d-138fb9abed.zip/node_modules/builder-util/src/util.ts:93:10)
    at executePython (/Users/himani/Documents/Github/chaine/.yarn/cache/dmg-builder-npm-23.6.0-d0da405dda-3e37a4b191.zip/node_modules/dmg-builder/src/dmg.ts:305:11)
    at customizeDmg (/Users/himani/Documents/Github/chaine/.yarn/cache/dmg-builder-npm-23.6.0-d0da405dda-3e37a4b191.zip/node_modules/dmg-builder/src/dmg.ts:313:5)
    at Object.executeFinally (/Users/himani/Documents/Github/chaine/.yarn/cache/builder-util-npm-23.6.0-2b87d7882d-138fb9abed.zip/node_modules/builder-util/src/promise.ts:12:14)
    at Object.attachAndExecute (/Users/himani/Documents/Github/chaine/.yarn/cache/dmg-builder-npm-23.6.0-d0da405dda-3e37a4b191.zip/node_modules/dmg-builder/src/dmgUtil.ts:33:10)
    at DmgTarget.build (/Users/himani/Documents/Github/chaine/.yarn/cache/dmg-builder-npm-23.6.0-d0da405dda-3e37a4b191.zip/node_modules/dmg-builder/src/dmg.ts:59:11)
    at async Promise.all (index 1)
    at AsyncTaskManager.awaitTasks (/Users/himani/Documents/Github/chaine/.yarn/cache/builder-util-npm-23.6.0-2b87d7882d-138fb9abed.zip/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at Packager.doBuild (/Users/himani/Documents/Github/chaine/.yarn/cache/app-builder-lib-npm-23.6.0-cb887be781-da3cc9f24e.zip/node_modules/app-builder-lib/src/packager.ts:453:5)
    at Object.executeFinally (/Users/himani/Documents/Github/chaine/.yarn/cache/builder-util-npm-23.6.0-2b87d7882d-138fb9abed.zip/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/himani/Documents/Github/chaine/.yarn/cache/app-builder-lib-npm-23.6.0-cb887be781-da3cc9f24e.zip/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/himani/Documents/Github/chaine/.yarn/cache/app-builder-lib-npm-23.6.0-cb887be781-da3cc9f24e.zip/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/himani/Documents/Github/chaine/.yarn/cache/builder-util-npm-23.6.0-2b87d7882d-138fb9abed.zip/node_modules/builder-util/src/promise.ts:12:14)
    ```

**Comment by mmaietta** [comment]
What's the error message being thrown? I only see the stacktrace so I'm not sure what's happening apart from python being executed via execFile (it tests for python3 first, before falling back to python so maybe something is going wrong there?)

**Comment by himaniChaine** [comment]
@mmaietta I am not able to make a build successfully

<img width="1340" alt="Screenshot 2023-01-06 at 10 52 36 AM" src="https://user-images.githubusercontent.com/68184659/210935765-cd7a6890-4de8-41e3-a7a5-3fc7f996d703.png">

**Comment by mmaietta** [comment]
What version of python do you have installed? Maybe there's an incompatiblity there? The ENOTDIR is a python-specific error AFAICT from a google search.

**Comment by himaniChaine** [comment]
@mmaietta 

<img width="682" alt="Screenshot 2023-01-06 at 10 46 28 PM" src="https://user-images.githubusercontent.com/68184659/211063437-a82b7f08-c14c-4c53-8f0f-25c4cad72434.png">

**Comment by himaniChaine** [comment]
@mmaietta I tried to decrease the python version as well
<img width="800" alt="Screenshot 2023-01-06 at 11 33 45 PM" src="https://user-images.githubusercontent.com/68184659/211071874-23140907-ad52-4769-8cb3-7c08836c68c3.png">

**Comment by himaniChaine** [comment]
@mmaietta could you please review bug
