### ISSUE TITLE
Runtime error trying to run Intel Mac app that was built on M1 Mac

### ISSUE THREAD

**Issue by JulieMarie** [electron-userland/electron-builder#7349]
* **Electron-Builder Version**: 23.0.6

* **Node Version**: 16.10.0

* **Electron Version**: 22.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Intel Mac x64

I am trying to build both arm64 and x64 packages on my arm64 machine.  I'm able to successfully build and run the arm64 version and I am able to successfully build the app for Intel/Mac x64, but when opening the app the user gets the following:

```
Uncaught Exception:
Error: dlopen(/var/folders/h6/wy879s8x051g61cr4_441hwm0000gp/T/.namespace.Fo8hCX, 0x0001): tried: '/var/folders/h6/wy879s8x051g61cr4_441hwm0000gp/T/.namespace.Fo8hCX' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/h6/wy879s8x051g61cr4_441hwm0000gp/T/.namespace.Fo8hCX' (no such file), '/var/folders/h6/wy879s8x051g61cr4_441hwm0000gp/T/.namespace.Fo8hCX' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/private/var/folders/h6/wy879s8x051g61cr4_441hwm0000gp/T/.namespace.Fo8hCX' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/h6/wy879s8x051g61cr4_441hwm0000gp/T/.namespace.Fo8hCX' (no such file), '/private/var/folders/h6/wy879s8x051g61cr4_441hwm0000gp/T/.namespace.Fo8hCX' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at load (/some-path/dist/release/beta/mac/SomeName.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:22:10)
at Object.<anonymous> (/some-path/dist/release/beta/mac/SomeName.app/Contents/Resources/app.asar/node_modules/ref-napi/lib/ref.js:8:53)
```

I am running `electron-builder --x64` and the mac portion of `electron-builder.yaml` looks like:
```mac:
  icon: ../../dist/apps/editor/assets/icons/some-name-here.png
  hardenedRuntime: true
  target:
    - zip
    - dmg
    - pkg
```

I saw this: https://github.com/electron-userland/electron-builder/issues/6623 but can't figure out how that relates to my issue.  I also tried adding `arch` into the `electron-builder.yaml` file, but that didn't work.

Any suggestions on what to try?

P.S. I changed names and paths to protect the innocent!

**Comment by JulieMarie** [comment]
Bah, I just added: `buildDependenciesFromSource: true` at the top level of my `electron-builder.yaml` and I believe it worked.  Checking with the user now.....

**Comment by JulieMarie** [comment]
That worked...please ignore. :-/
