### ISSUE TITLE
spctl process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE on 24.0.0-alpha.9

### ISSUE THREAD

**Issue by filfreire** [electron-userland/electron-builder#7357]
* **Electron-Builder Version**: 24.0.0-alpha.9

* **Node Version**: 16.17

* **Electron Version**: 22.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: MacOS

We're currently facing an issue when signing a Mac App where we get an error  like:
```
spctl process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
```

It seems to happen on [this line of code](https://github.com/electron-userland/electron-builder/blob/1e8dad8bc58f53780c9fac3b0c48e248a8b5467c/packages/app-builder-lib/src/macPackager.ts#L492).

This is [the config](https://github.com/Kong/insomnia/blob/1cb78093c22a2a99b4512d9f91840c77b6a7cf7f/packages/insomnia/electron-builder.config.js).

Original [debug log](https://github.com/Kong/insomnia/actions/runs/3875812475/jobs/6608865197#step:5:796): 
```
• signing         file=dist/mac-universal/Insomnia.app identityName=Developer ID Application: Kong Inc. (FX44YY62GV) identityHash=8A3A2A7038D62E18916CF6F5752BB292F289B213 provisioningProfile=none
  • spawning        command=spctl -a -t open --context context:primary-signature -v "/Users/runner/work/***/***/packages/***/dist/mac-universal/Insomnia.app"
"/Users/runner/work/***/***/packages/***/dist/mac-universal/Insomnia.app": No such file or directory
  • exited          command=spctl code=1 pid=27881
  • executing       file=security args=delete-keychain /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d586d1f05b6aa072b4f4079123b8263389cb4317b0003db560c539082840b86b.keychain
  • executed        file=security
  ⨯ spctl process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: spctl process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/Users/runner/work/***/***/packages/***/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
From previous event:
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at MacPackager.signApp (/Users/runner/work/***/***/packages/***/node_modules/app-builder-lib/src/macPackager.ts:449:27)
    at MacPackager.doSignAfterPack (/Users/runner/work/***/***/packages/***/node_modules/app-builder-lib/src/platformPackager.ts:329:16)
    at MacPackager.doPack (/Users/runner/work/***/***/packages/***/node_modules/app-builder-lib/src/macPackager.ts:150:9)
    at MacPackager.pack (/Users/runner/work/***/***/packages/***/node_modules/app-builder-lib/src/macPackager.ts:194:7)
    at Packager.doBuild (/Users/runner/work/***/***/packages/***/node_modules/app-builder-lib/src/packager.ts:441:9)
    at executeFinally (/Users/runner/work/***/***/packages/***/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/runner/work/***/***/packages/***/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/runner/work/***/***/packages/***/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/Users/runner/work/***/***/packages/***/node_modules/builder-util/src/promise.ts:12:14)
```

**Comment by filfreire** [comment]
Note - this only seems to be happening in the Github Actions runner. Locally for example:
```
  • packaging       platform=darwin arch=universal electron=22.0.0 appOutDir=dist/mac-universal
  • signing         file=dist/mac-universal/Insomnia.app identityName=Developer ID Application: Kong Inc. (FX44YY62GV) identityHash=8A3A2A7038D62E18916CF6F5752BB292F289B213 provisioningProfile=none
  • notarization successful
  • building        target=DMG arch=universal file=dist/Insomnia.Core-2022.7.0.dmg
  • building        target=macOS zip arch=universal file=dist/Insomnia.Core-2022.7.0.zip
```


So it might have something to do with this path: `/Users/runner/work/***/***/packages/***/dist/mac-universal/Insomnia.app`

**Comment by filfreire** [comment]
Closing this one after #7361
