### ISSUE TITLE
ERR_ELECTRON_BUILDER_INVALID_CONFIGURATION

### ISSUE THREAD

**Issue by SSerg-dev** [electron-userland/electron-builder#7402]
From previous event:
    at Object.writeUpdateInfoFiles (/home/runner/work/vue-electron-app/vue-electron-app/node_modules/app-builder-lib/src/publish/updateInfoBuilder.ts:213:25)
    at PublishManager.awaitTasks (/home/runner/work/vue-electron-app/vue-electron-app/node_modules/app-builder-lib/src/publish/PublishManager.ts:239:11)
    at Object.executeFinally (/home/runner/work/vue-electron-app/vue-electron-app/node_modules/builder-util/src/promise.ts:23:3) {
  code: 'ERR_ELECTRON_BUILDER_INVALID_CONFIGURATION'
}

**Comment by mmaietta** [comment]
Seems like your configuration is invalid... but there's not enough information to go off of.
