### ISSUE TITLE
Specify a configuration file for `install-app-deps` with `--config`

### ISSUE THREAD

**Issue by Rafatcb** [electron-userland/electron-builder#7408]
* **Electron-Builder Version**: 23.6.0

* **Node Version**: 16.18.0

* **Electron Version**: 22.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

My app native dependencies (`./release/app/package.json`) are not installed if I use a file for the `electron-builder` configuration. This happens because `install-app-deps` doesn't accept a `configPath` like `build` does (see [Common Configuration](https://www.electron.build/configuration/configuration#build)), so it doesn't find `build.directories.app` unless it's in `package.json`:

https://github.com/electron-userland/electron-builder/blob/3c5f9ad34766f866899ff4da1570d16f5a81cc7c/packages/electron-builder/src/cli/install-app-deps.ts#L47-L49

https://github.com/electron-userland/electron-builder/blob/53327d51101b83641ece9f497577c3ac93d3e91d/packages/app-builder-lib/src/packager.ts#L296-L314

Shouldn't `install-app-deps` accept a `--config` argument as well?

For now, I had to specify it in `package.json` just for `install-app-deps`:

```json
{
  "build": {
    "directories": {
      "app": "release/app"
    }
  }
}
```

**Comment by mmaietta** [comment]
>Shouldn't install-app-deps accept a --config argument as well?

I suppose that's an easy point for debate. Please open a PR if you'd like to support that feature request. As it currently stands, I won't be able to work on this

**Comment by Rafatcb** [comment]
I'm having no luck [setting up the local development environment](https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment) on Windows. First, I tried to run tests to see if the environment was ok, but the result was this:

```
Test Suites: 13 failed, 7 skipped, 24 passed, 37 of 44 total
Tests:       17 failed, 126 skipped, 24 passed, 289 total
Snapshots:   6 failed, 108 passed, 114 total
Time: 467.911 s
Ran all test suites.
```
So I went ahead and tried adding a `console.log` to `electron-builder/packages/electron-builder/src/cli/install-app-deps.ts` to see if I could start working on the code, but when I run `yarn electronic-builder install-app-deps` on my project, I get an error that I don't know how to fix:

```
Error: Cannot find module '@electron/rebuild'
Require stack:
- D:\my-repo\.yalc\app-builder-lib\out\util\yarn.js
- D:\my-repo\.yalc\app-builder-lib\out\packager.js
- D:\my-repo\.yalc\app-builder-lib\out\index.js
- D:\my-repo\.yalc\electron-builder\out\builder.js
- D:\my-repo\.yalc\electron-builder\out\cli\cli.js
- D:\my-repo\.yalc\electron-builder\cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\my-repo\.yalc\app-builder-lib\src\util\yarn.ts:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\my-repo\.yalc\app-builder-lib\src\packager.ts:27:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My project is using Yarn and `"@electron/rebuild": "3.2.10"` is in `devDependencies`. I used pnpm on the cloned repository `electron-builder`, following the docs.

**Comment by ZainChen** [comment]
I also hope to support the --config parameter.

**Comment by mnasyrov** [comment]
Please reopen, the issue is actual.

**Comment by snoolord** [comment]
+1, wish I could pass in --config
