### ISSUE TITLE
Cannot compute app packae download URL

### ISSUE THREAD

**Issue by ITJEONG-DEV** [electron-userland/electron-builder#7469]
* **Electron-Builder Version**: 23.6.0
* **Node Version**: 16.13.0
* **Electron Version**: 13.5.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: nsis-web

This is my package.json
```
{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "main/main.js",
  "scripts": {
    "start": "electron .",
    "build:win": "npm run build:win32 && npm run build:win64",
    "build:win32": "electron-builder --win --ia32",
    "build:win64": "electron-builder --win --x64"
  },
  "build": {
    "appId" : "electron.app",
    "productName" : "app",
    "win": {
      "target": [{
        "target": "nsis-web",
        "arch": [
          "x64",
          "ia32"
        ]
      }]
    },
    "nsisWeb": {
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true,
      "deleteAppDataOnUninstall": true,
      "artifactName":"app-Setup.${ext}",
      "runAfterFinish":true
    },
    "extraFiles" : [
      {
        "from" : "exe/",
        "to" : "exe"
      },
      {
        "from" : "settings/",
        "to" : "settings"
      }
    ]
  },
  "keywords": [],
  "author": "",
  "devDependencies": {
    "electron": "^13.5.1",
    "electron-builder": "^23.6.0",
    "electron-log": "^4.4.8"
  },
  "dependencies": {
    "electron-is-dev": "latest",
    "express": "^4.18.2",
    "ffi-napi": "^4.0.3",
    "node-gyp": "^9.3.1",
    "nvm": "^0.0.4",
    "ref-napi": "^3.0.3",
    "socket.io": "^4.5.4"
  }
}
```

When I try build using electron-builder, this error occurred.
Below is full log.
```
E:\2023_app\230207_electron>npm run build:win64

> app@1.0.0 build:win64
> electron-builder --win --x64

  • electron-builder  version=23.6.0 os=10.0.22000
  • loaded configuration  file=package.json ("build" field)
  • description is missed in the package.json  appPackageFile=E:\2023_app\230207_electron\package.json
  • writing effective config  file=dist\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=ffi-napi@4.0.3, ref-napi@3.0.3 platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=13.6.9 appOutDir=dist\win-unpacked
  • default Electron icon is used  reason=application icon is not set
  • rebuilding native dependencies  dependencies=ffi-napi@4.0.3, ref-napi@3.0.3 platform=win32 arch=ia32
  • packaging       platform=win32 arch=ia32 electron=13.6.9 appOutDir=dist\win-ia32-unpacked
  • building        target=nsis-web file=dist\nsis-web\appElectron Web Setup 1.0.0.exe archs=x64, ia32 oneClick=false perMachine=false
  • building embedded block map  file=dist\nsis-web\app-1.0.0-ia32.nsis.7z
  • building embedded block map  file=dist\nsis-web\app-1.0.0-x64.nsis.7z
  ⨯ Cannot compute app package download URL  failedTask=build stackTrace=Error: Cannot compute app package download URL
    at WebInstallerTarget.configureDefines (E:\2023_app\230207_electron\node_modules\app-builder-lib\src\targets\nsis\WebInstallerTarget.ts:28:15)
    at WebInstallerTarget.buildInstaller (E:\2023_app\230207_electron\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:274:7)
    at WebInstallerTarget.finishBuild (E:\2023_app\230207_electron\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:133:9)
    at async Promise.all (index 2)
    at AsyncTaskManager.awaitTasks (E:\2023_app\230207_electron\node_modules\builder-util\src\asyncTaskManager.ts:65:25)
    at Packager.doBuild (E:\2023_app\230207_electron\node_modules\app-builder-lib\src\packager.ts:453:5)
    at Object.executeFinally (E:\2023_app\230207_electron\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (E:\2023_app\230207_electron\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (E:\2023_app\230207_electron\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (E:\2023_app\230207_electron\node_modules\builder-util\src\promise.ts:12:14)
```

I use nsis-web because of the size ( it is bigger than 2GB )
I don't know what is the problem..

**Comment by mmaietta** [comment]
That error is coming from here: 
https://github.com/electron-userland/electron-builder/blob/c1448c6584bb5106aaa2766379fd0917508ce3bf/packages/app-builder-lib/src/targets/nsis/WebInstallerTarget.ts#L26-L29

Looks like a `publish` config is needed in order for nsis-web to work? I haven't built nsis-web before, but my best guess is that the `publish` config is needed in order for the compiled nsis to know where to download the rest of your app package from.

**Comment by ITJEONG-DEV** [comment]
I fixed this error.

Add a 'appPackageUrl' into 'nsisWeb' in package.json

I just add "appPackageUrl" as empty string("")
