### ISSUE TITLE
node is not a valid Win32 application.

### ISSUE THREAD

**Issue by Zhongxiangyun** [electron-userland/electron-builder#7470]
![image](https://user-images.githubusercontent.com/7427588/223897425-086e11ae-d1dc-4f39-b014-e5f260e3c477.png)

? C Users Administrator Ap.. cad57bcc-6988-4b37-8048-abb5912313a1.tmp.node
is not a valid Win32 application.? C: Users Administrator Ap.. cad57bcc-6988-4b37-8048-abb5912313a1.tmpnodeat process.func [as dlopen] (node:electron/js2c/asar bundle:5:1800)at Object.Module, extensions.node (node:internal/modules/cjs/loader:1199:18)at Object.func [as ,node] (node:electron/is2c/asar bundle:5:2027)at Module.load (node:internal/modules/cjs/loader:988:32)at Module. load (node:internal/modules/cjs/loader:829:12)at Functionc. load (node:electron/js2c/asar bundle:5:13331)at Module.require (node:internal/modules/cjs/loader:1012:19)at require (node:internal/modules/cjs/helpers:94:18)
at load (C:\Program Files(x86)\mousedesk\resources app.asar(node modules(node-gyp-buildvindex,js:22:10)at Object,eanonymouss (C: Program Files(x86) mousedesk resources app,asar node modules(@serialport bindings-cpp...:46)

打包配置命令:
"dist": "react-scripts build && electron-builder build",

"win": {
      "icon": "static/icon.ico",
      "artifactName": "${productName}_setup_${version}.${ext}",
      "target": [{
        "target": "nsis",
        "arch": [
          "ia32"
        ]
      }

请问怎么解决呢?

**Comment by Zhongxiangyun** [comment]
本地的配置信息:

"devDependencies": {
    "concurrently": "^7.5.0",
    "cross-env": "^7.0.3",
    "electron": "^16.0.5",
    "electron-builder": "^22.13.1",
    "electron-notarize": "^1.2.2",
    "electron-rebuild": "^3.2.9",
    "wait-on": "^6.0.1"
  }

**Comment by Zhongxiangyun** [comment]
[1] webpack compiled with 1 warning
[0]
[0] App threw an error during load
[0] Error: \\?\D:\project\mouse-desktop\node_modules\ffi-napi\build\Release\ffi_bindings.node is not a valid Win32 application.
[0] \\?\D:\project\mouse-desktop\node_modules\ffi-napi\build\Release\ffi_bindings.node
[0]     at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
[0]     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
[0]     at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
[0]     at Module.load (node:internal/modules/cjs/loader:988:32)
[0]     at Module._load (node:internal/modules/cjs/loader:829:12)
[0]     at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[0]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[0]     at require (node:internal/modules/cjs/helpers:94:18)
[0]     at load (D:\project\mouse-desktop\node_modules\node-gyp-build\index.js:22:10)
[0]     at Object.<anonymous> (D:\project\mouse-desktop\node_modules\ffi-napi\lib\bindings.js:8:43)

**Comment by Zhongxiangyun** [comment]
[1] webpack compiled with 1 warning
[0]
[0] App threw an error during load
[0] Error: \\?\D:\project\mouse-desktop\node_modules\ffi-napi\build\Release\ffi_bindings.node is not a valid Win32 application.
[0] \\?\D:\project\mouse-desktop\node_modules\ffi-napi\build\Release\ffi_bindings.node
[0]     at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
[0]     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
[0]     at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
[0]     at Module.load (node:internal/modules/cjs/loader:988:32)
[0]     at Module._load (node:internal/modules/cjs/loader:829:12)
[0]     at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[0]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[0]     at require (node:internal/modules/cjs/helpers:94:18)
[0]     at load (D:\project\mouse-desktop\node_modules\node-gyp-build\index.js:22:10)
[0]     at Object.<anonymous> (D:\project\mouse-desktop\node_modules\ffi-napi\lib\bindings.js:8:43)

**Comment by Zhongxiangyun** [comment]
] App threw an error during load
[0] Error: \\?\D:\project\mouse-desktop\node_modules\@serialport\bindings-cpp\build\Release\bindings.node is not a valid Win32 application.
[0] \\?\D:\project\mouse-desktop\node_modules\@serialport\bindings-cpp\build\Release\bindings.node
[0]     at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
[0]     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
[0]     at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
[0]     at Module.load (node:internal/modules/cjs/loader:988:32)
[0]     at Module._load (node:internal/modules/cjs/loader:829:12)
[0]     at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[0]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[0]     at require (node:internal/modules/cjs/helpers:94:18)
[0]     at load (D:\project\mouse-desktop\node_modules\node-gyp-build\index.js:22:10)
[0]     at Object.<anonymous> (D:\project\mouse-desktop\node_modules\@serialport\bindings-cpp\dist\load-bindings.js:10:46)
[0] ^CTerminate batch job (Y/N)? ^CTerminate batch job (Y/N)? ^CTerminate batch job (Y/N)? ^C cross-env BROWSER=none react-scripts start  exited with code 1
[0]  wait-on http://localhost:3000 && electron .  exited with code 1

**Comment by mmaietta** [comment]
I can't support old versions of electron-builder (or am able to release patch versions for them). Please try `24.3.0`

**Comment by Marlonzao** [comment]
> I can't support old versions of electron-builder (or am able to release patch versions for them). Please try `24.3.0`

Hi! This is also happening on the most recent release, as I am also experiencing it.
