### ISSUE TITLE
zip for macOS takes a very long time

### ISSUE THREAD

**Issue by PierBover** [electron-userland/electron-builder#754]
* **Version**: 6.4.1

* **Target**: macOS

When building for macOS the `.zip` file takes about 5 minutes, while a regular `.zip` on Finder takes 1 minute at most.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and `LOG_TIME=true` to get debug log.

**Comment by popod** [comment]
```
$ DEBUG=electron-builder ../src/node_modules/.bin/build -mw --x64 --ia32
Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform darwin x64 using electron 1.4.3 to ../pkg/dist/mac

  electron-builder Spawning <rootPath>/src/node_modules/7zip-bin-osx/7za x -bd <userPath>/.electron/electron-v1.4.3-darwin-x64.zip -o<rootPath>/pf6410e3b85c841cbaa328230a3a38ac41971052ea1b12c56407c145972434bba (sha256 hash) +0ms

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 42002861 bytes (41 MiB)

Extracting archive: <userPath>/.electron/electron-v1.4.3-darwin-x64.zip
--
Path = <userPath>/.electron/electron-v1.4.3-darwin-x64.zip
Type = zip
Physical Size = 42002861

Everything is Ok

Folders: 143
Files: 180
Size:       111883842
Compressed: 42002861
  electron-builder <rootPath>/src/node_modules/7zip-bin-osx/7za (51029) exited with code 0 +1s
  electron-builder Executing security find-identity -v +2s
  electron-builder Executing security find-identity -v -p codesigning +8ms
  1) xxx
     1 valid identities found

  1) xxx
  2) xxx
     2 valid identities found

Warning: App is not signed: CSC_LINK is not specified, and no valid identity in the keychain, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
Must be "Developer ID Application:" or custom non-Apple code signing certificate
Creating DMG
Creating MacOS zip
  electron-builder Executing wine --version +136ms
Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform win32 x64 using electron 1.4.3 to ../pkg/dist/win-unpacked

  electron-builder Spawning <rootPath>/src/node_modules/7zip-bin-osx/7za a -bd -mm=Deflate <rootPath>/pf21a291b29762be73ab891bc01c57fc047a09b32ea2365889961c8e65c70e768 (sha256 hash) <organisationName>.app +138ms
  electron-builder Found existing nsis <userPath>/.cache/nsis/nsis-3.0.1 +3ms
  electron-builder Spawning <rootPath>/src/node_modules/7zip-bin-osx/7za x -bd <userPath>/.electron/electron-v1.4.3-win32-x64.zip -o<rootPath>/p48c6790cf51fd327f2cffb405224f11598911a5d9d59638051179632cfbbca9f (sha256 hash) +1ms

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

wine-1.8.3

Scanning the drive:

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 54276365 bytes (52 MiB)

Extracting archive: <userPath>/.electron/electron-v1.4.3-win32-x64.zip
  electron-builder Executing hdiutil create -srcfolder /var/folders/g7/5y2hqvns10l1v_zz8kvglwmr0000gn/T/electron-builder-vWPxUo/t-c754-0-dmg/.background -srcfolder <rootPath>/p48b3610bc7b49e08a55455f412b1e88cfd578728e9fd2a510109d0dd788a054e (sha256 hash) -volname <organisationName> 0.1.1 -anyowners -nospotlight -quiet -fs HFS+ -fsargs -c c=64,a=16,e=16 -format UDRW /var/folders/g7/5y2hqvns10l1v_zz8kvglwmr0000gn/T/electron-builder-vWPxUo/t-c754-0-dmg/temp.dmg +6ms
--
Path = <userPath>/.electron/electron-v1.4.3-win32-x64.zip
Type = zip
Physical Size = 54276365

143 folders, 177 files, 122920870 bytes (118 MiB)

Creating archive: <rootPath>/pkg/dist/mac/<organisationName>-0.1.1-mac.zip

Items to compress: 320

Everything is Ok

Files: 74
Size:       137624721
Compressed: 54276365
  electron-builder <rootPath>/src/node_modules/7zip-bin-osx/7za (51035) exited with code 0 +2s
  electron-builder Found existing winCodeSign <userPath>/.cache/winCodeSign/winCodeSign-1.4.2 +880ms
  electron-builder Executing wine <userPath>/.cache/winCodeSign/winCodeSign-1.4.2/rcedit.exe <rootPath>/p735b1ef09115ff736a58acc4e6fd4b599ed7f17896cb8894227c926cc63f3ba7 (sha256 hash) --set-version-string CompanyName <organisationName> --set-version-string FileDescription File manager with tags --set-version-string ProductName <organisationName> --set-version-string InternalName <organisationName> --set-version-string LegalCopyright Copyright © 2016 <organisationName> --set-version-string OriginalFilename  --set-file-version 0.1.1 --set-product-version 0.1.1 --set-icon <rootPath>/build/app/images/logo.ico +0ms
  electron-builder Executing hdiutil attach -noverify -noautoopen -readwrite /var/folders/g7/5y2hqvns10l1v_zz8kvglwmr0000gn/T/electron-builder-vWPxUo/t-c754-0-dmg/temp.dmg +4s

Files read from disk: 177
Archive size: 43454716 bytes (42 MiB)
Everything is Ok
  electron-builder <rootPath>/src/node_modules/7zip-bin-osx/7za (51034) exited with code 0 +702ms
/dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	Apple_HFS                      	/Volumes/<organisationName> 0.1.1

  electron-builder Executing ln -s /Applications /Volumes/<organisationName> 0.1.1/Applications +617ms
  electron-builder Executing hdiutil detach /dev/disk2 +12ms
"disk2" unmounted.
"disk2" ejected.

Unhandled rejection TypeError: Cannot read property 'x' of undefined
    at DmgTarget.<anonymous> (<rootPath>/src/node_modules/electron-builder/src/targets/dmg.ts:77:19)
    at next (native)
From previous event:
    at tsAwaiter (<rootPath>/src/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at DmgTarget.build (<rootPath>/src/node_modules/electron-builder/out/targets/dmg.js:20:16)
    at MacPackager.packageInDistributableFormat (<rootPath>/src/node_modules/electron-builder/src/macPackager.ts:195:25)
    at nonMasPromise.doPack.then.then (<rootPath>/src/node_modules/electron-builder/src/macPackager.ts:80:16)
From previous event:
    at MacPackager.<anonymous> (<rootPath>/src/node_modules/electron-builder/src/macPackager.ts:79:10)
    at next (native)
From previous event:
    at tsAwaiter (<rootPath>/src/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (<rootPath>/src/node_modules/electron-builder/out/builder.js:138:12)
    at Object.<anonymous> (<rootPath>/src/node_modules/electron-builder/out/build-cli.js:23:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:advapi:EventRegister {5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x406ba9, 0x4c90b0, 0x4c90c8
fixme:advapi:EventSetInformation 2, 0x4c255a, 43
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
wine.bin(51060,0x406c2000) malloc: *** error for object 0x401c4308: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

Creating NSIS x64 package

Building Squirrel.Windows installer

Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform win32 ia32 using electron 1.4.3 to ../pkg/dist/win-ia32-unpacked

  electron-builder Spawning <rootPath>/src/node_modules/7zip-bin-osx/7za a -bd -mx=9 -mfb=64 -md=64m -ms=on <rootPath>/p72f33e76ea0d80190e790ba2d22fb0dc0387899f0b41b750d3bbad29f80998e1 (sha256 hash) win-unpacked +2s
  electron-builder Found existing Squirrel.Windows <userPath>/.cache/Squirrel.Windows/Squirrel.Windows-1.4.4 +3ms

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive:
3 folders, 73 files, 150989859 bytes (144 MiB)

Creating archive: <rootPath>/pkg/dist/<organisationName>-0.1.1-x64.nsis.7z

Items to compress: 76

  electron-builder Spawning <rootPath>/src/node_modules/7zip-bin-osx/7za x -bd <userPath>/.electron/electron-v1.4.3-win32-ia32.zip -o<rootPath>/p30036fc79754eb055098c284eac06edf7fb4ac73db3052979fc09dadf82a1574 (sha256 hash) +7ms

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 43981615 bytes (42 MiB)

Extracting archive: <userPath>/.electron/electron-v1.4.3-win32-ia32.zip
--
Path = <userPath>/.electron/electron-v1.4.3-win32-ia32.zip
Type = zip
Physical Size = 43981615

  electron-builder Created NuSpec file:
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id><organisationName></id>
    <version>0.1.1</version>
    <title><organisationName></title>
    <authors><organisationName></authors>
    <owners><organisationName></owners>
    <iconUrl>http://www.<organisationName>.ch/images/logo.ico</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>File manager with tags</description>
    <copyright>Copyright © 2016 <organisationName></copyright>
    <projectUrl><githubUrl></projectUrl>
  </metadata>
</package> +20ms
Everything is Ok

Files: 74
Size:       108279765
Compressed: 43981615
  electron-builder <rootPath>/src/node_modules/7zip-bin-osx/7za (51112) exited with code 0 +1s
  electron-builder Executing wine <userPath>/.cache/winCodeSign/winCodeSign-1.4.2/rcedit.exe <rootPath>/pd0e2cbc76c7b9bf88bdeffc033acb16921bef9291883c0160d6392e6c6453dc8 (sha256 hash) --set-version-string CompanyName <organisationName> --set-version-string FileDescription File manager with tags --set-version-string ProductName <organisationName> --set-version-string InternalName <organisationName> --set-version-string LegalCopyright Copyright © 2016 <organisationName> --set-version-string OriginalFilename  --set-file-version 0.1.1 --set-product-version 0.1.1 --set-icon <rootPath>/build/app/images/logo.ico +796ms
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:advapi:EventRegister {5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x406ba9, 0x4c90b0, 0x4c90c8
fixme:advapi:EventSetInformation 2, 0x4c255a, 43
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
wine.bin(51128,0x405c2000) malloc: *** error for object 0x40600710: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

Creating NSIS ia32 package

Warning: For windows consider only distributing 64-bit, see https://github.com/electron-userland/electron-builder/issues/359#issuecomment-214851130
Building Squirrel.Windows installer

Building NSIS installer

  electron-builder Spawning <rootPath>/src/node_modules/7zip-bin-osx/7za a -bd -mx=9 -mfb=64 -md=64m -ms=on <rootPath>/pc9864d9691c769c07485946ad591b05a8b1733e206004b2f7562d214965e542d (sha256 hash) win-ia32-unpacked +6s

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive:
3 folders, 73 files, 121644903 bytes (117 MiB)

Creating archive: <rootPath>/pkg/dist/<organisationName>-0.1.1-ia32.nsis.7z

Items to compress: 76

Warning: Cannot delete temporary dir "/var/folders/g7/5y2hqvns10l1v_zz8kvglwmr0000gn/T/electron-builder-vWPxUo": Error: ENOTEMPTY: directory not empty, rmdir '/var/folders/g7/5y2hqvns10l1v_zz8kvglwmr0000gn/T/electron-builder-vWPxUo'
    at Error (native)
From previous event:
    at TmpDir.cleanup (<rootPath>/src/node_modules/electron-builder/src/util/tmp.ts:63:18)
    at promise_1.executeFinally (<rootPath>/src/node_modules/electron-builder/src/packager.ts:105:121)
    at Object.<anonymous> (<rootPath>/src/node_modules/electron-builder/src/util/promise.ts:20:13)
    at throw (native)
From previous event:
    at tsAwaiter (<rootPath>/src/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (<rootPath>/src/node_modules/electron-builder/out/builder.js:138:12)
    at Object.<anonymous> (<rootPath>/src/node_modules/electron-builder/out/build-cli.js:23:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
TypeError: Cannot read property 'x' of undefined
    at DmgTarget.<anonymous> (<rootPath>/src/node_modules/electron-builder/src/targets/dmg.ts:77:19)
    at next (native)
From previous event:
    at tsAwaiter (<rootPath>/src/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at DmgTarget.build (<rootPath>/src/node_modules/electron-builder/out/targets/dmg.js:20:16)
    at MacPackager.packageInDistributableFormat (<rootPath>/src/node_modules/electron-builder/src/macPackager.ts:195:25)
    at nonMasPromise.doPack.then.then (<rootPath>/src/node_modules/electron-builder/src/macPackager.ts:80:16)
From previous event:
    at MacPackager.<anonymous> (<rootPath>/src/node_modules/electron-builder/src/macPackager.ts:79:10)
    at next (native)
From previous event:
    at tsAwaiter (<rootPath>/src/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (<rootPath>/src/node_modules/electron-builder/out/builder.js:138:12)
    at Object.<anonymous> (<rootPath>/src/node_modules/electron-builder/out/build-cli.js:23:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```
