### ISSUE TITLE
Mac update gets downloaded but gives error at install - The command is disabled and cannot be executed

### ISSUE THREAD

**Issue by vineet1984** [electron-userland/electron-builder#7564]
**Package Version**
"electron-builder": "^23.6.0"
"electron-updater": "^5.3.0"
"electron": "^24.1.3"

**Target**
Mac M1 (Arm64) Ventura 13.1 

**Node Version**
18.13.0

The Mac update gets downloaded and I get a prompt to restart the app. However, when I press restart, this behavior continues in a loop and the logs show an error "The command is disabled and cannot be executed" at MacUpdater.js (Line: this.nativeUpdater.checkForUpdates()). 

As per #5935 and #6058, I added the relevant code but the error persists.

```
autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => {
  log.info('updated-download event'+releaseName+releaseNotes)
  const dialogOpts = {
    type: 'info',
    buttons: ['Restart', 'Later'],
    title: 'Application Update',
    message: process.platform === 'win32' ? releaseNotes : releaseName,
    detail:
      'A new version has been downloaded. Restart the application to apply the updates.',
  }

  dialog.showMessageBox(dialogOpts).then((returnValue) => {
    if (returnValue.response === 0) {
      setTimeout(() => {
        autoUpdater.quitAndInstall()
        app.exit();
      }, 6000);
    }
  });
})
```

Error Logs:-

```
[2023-04-27 23:14:33.708] [info]  Checking for update
[2023-04-27 23:14:34.833] [info]  Found version 1.0.1 (url: /download/flavor/default/1.0.1/osx_arm64/<App>-1.0.1-arm64-mac.zip)
[2023-04-27 23:14:34.834] [info]  update available [object Object]
[2023-04-27 23:14:34.834] [info]  Downloading update from /download/flavor/default/1.0.1/osx_arm64/<App>-1.0.1-arm64-mac.zip
[2023-04-27 23:14:34.840] [info]  Checked for macOS Rosetta environment (isRosetta=false)
[2023-04-27 23:14:34.843] [info]  Checked 'uname -a': arm64=true
[2023-04-27 23:14:34.944] [info]  Update has already been downloaded to /Users/$user/Library/Application Support/Caches/<App>-updater/pending/<App>-1.0.1-arm64-mac.zip).
[2023-04-27 23:14:34.948] [info]  updated-download
[2023-04-27 23:14:36.993] [warn]  Error: The command is disabled and cannot be executed
    at Server.<anonymous> (/Applications/<App>/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:180:40)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitListeningNT (node:net:1774:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
[2023-04-27 23:14:36.995] [error] Error: Error: The command is disabled and cannot be executed
    at Server.<anonymous> (/Applications/Zaperon.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:180:40)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitListeningNT (node:net:1774:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

Anyone else facing this issue?

**Comment by ArmelChesnais** [comment]
Running into this too.
Wanted to add that this doesn't seem to happen in 4.3.7, but does in 4.3.8. Appears to have been introduced in this commit
https://github.com/electron-userland/electron-builder/commit/1643d569600a197858585e895e3176948d3eec85#diff-9da93fcc7c4be00ef66a6210b155ac689b7f761ec0bfc6a97346e1dfd1d77386

specifically this line (153 in that commit):
```
      // And trigger the update
      this.nativeUpdater.checkForUpdates()
```

**Comment by vineet1984** [comment]
@mmaietta I am new to electron-builder. Am I doing something wrong? Appreciate your teams help.

**Comment by bfan1256** [comment]
How did you solve this?
