### ISSUE TITLE
code sign failed to pass gatekeeper on mac & failed command on win

### ISSUE THREAD

**Issue by changkun** [electron-userland/electron-builder#757]
* **Version**: 7.0.1

* **Target**: macOS, Mac AppStore, Windows NSIS

I'm prepareing publishing my app to Mac AppStore, now I upgrade electron-builder from 5.35.0 to 7.0.1, here comes few problems and questions:

**1. build for macOS**

Once change to 7.0.1, it gives a gatekeeper error for build my app, What's going on here?

```bash
$ cnpm run build-mac                                     

> test@1.0.0 build-mac /Users/ouchangkun/Work/Git/test-desktop
> build --mac

Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform darwin x64 using electron 1.4.0 to dist/mac

Signing app (identity: Mac Developer: Changkun Ou (*****))

Error: Failed to pass Gatekeeper: : Error: Command failed: spctl --assess --type execute --verbose --ignore-cache --no-cache /Users/ouchangkun/Work/Git/test-desktop/dist/mac/测试.app
/Users/ouchangkun/Work/Git/test-desktop/dist/mac/测试.app: rejected

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
    at /Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-osx-sign-tf/index.js:215:12
    at /Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-osx-sign-tf/index.js:302:64
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at /Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-osx-sign-tf/index.js:291:14
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at verifySignApplicationAsync (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-osx-sign-tf/index.js:290:23)
    at /Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-osx-sign-tf/index.js:455:25
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at /Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-osx-sign-tf/index.js:452:10
From previous event:
    at signApplicationAsync (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-osx-sign-tf/index.js:395:6)
    at /Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-osx-sign-tf/index.js:564:14
From previous event:
    at Function.signAsync (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-osx-sign-tf/index.js:556:6)
    at MacPackager.<anonymous> (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/macPackager.ts:181:21)
    at next (native)
From previous event:
    at tsAwaiter (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at MacPackager.sign (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/macPackager.ts:98:75)
    at nonMasPromise.doPack.then (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/macPackager.ts:78:26)
From previous event:
    at MacPackager.<anonymous> (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/macPackager.ts:78:10)
    at next (native)
From previous event:
    at tsAwaiter (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/builder.ts:181:52)
    at Object.<anonymous> (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--registry=https://registry.npm.taobao.org" "--cache=/Users/ouchangkun/.npm/.cache/cnpm" "--disturl=https://npm.taobao.org/dist" "--userconfig=/Users/ouchangkun/.cnpmrc" "run" "build-mac"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 build-mac: `build --mac`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the test@1.0.0 build-mac script 'build --mac'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --mac
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ouchangkun/Work/Git/test-desktop/assets/npm-debug.log
```

**2. build for Windows**

It also give me error that code sign failed, when I build windows version. What should I do?

Here is my `package.json` related info:

```json
"win": {
    "target": "nsis",
    "certificateFile": "assets/cert.pem",
    "certificatePassword": "mypasswd"
},
"nsis": {
    "oneClick": true
}
```

> Wiki page is very unclear for me(sorry, I'm fresh...), I found  `certificateFIle`/`certificatePassword` field in an issue, but not in the wiki page. Could you please update the procedure for publishing App in this doc? It would be excellent.

Output:

```bash
$ cnpm run build-win64                                   

> test@1.0.0 build-win64 /Users/ouchangkun/Work/Git/test-desktop
> build --win --x64

Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform win32 x64 using electron 1.4.0 to dist/win-unpacked

Signing 测试.exe (certificate file "assets/cert.pem")
Error: Exit code: 255. Command failed: /Users/ouchangkun/.cache/winCodeSign/winCodeSign-1.4.2/darwin/osslsigncode -in /Users/ouchangkun/Work/Git/test-desktop/dist/win-unpacked/测试.exe -out /Users/ouchangkun/Work/Git/test-desktop/dist/win-unpacked/测试-signed-sha1.exe -t http://timestamp.verisign.com/scripts/timstamp.dll -h sha1 -n 测试 -i https://www.test.com -pass ******** (sha256 hash) /Users/ouchangkun/.cache/winCodeSign/winCodeSign-1.4.2/darwin/osslsigncode

	[ --version | -v ]

	[ sign ]
		( -certs <certfile> -key <keyfile> | -pkcs12 <pkcs12file> |
		  -pkcs11engine <engine> -pkcs11module <module> -certs <certfile> -key <pkcs11 key id>)
		[ -pass <password> ] [ -askpass ][ -readpass <file> ]
		[ -ac <crosscertfile> ]
		[ -h {md5,sha1,sha2(56),sha384,sha512} ]
		[ -n <desc> ] [ -i <url> ] [ -jp <level> ] [ -comm ]
		[ -ph ]
		[ -t <timestampurl> [ -t ... ] [ -p <proxy> ] [ -noverifypeer ] ]
		[ -ts <timestampurl> [ -ts ... ] [ -p <proxy> ] [ -noverifypeer ] ]
		[ -addUnauthenticatedBlob ]

		[ -nest ]

		[ -verbose ]

		MSI specific:
		[ -add-msi-dse ]

		[ -in ] <infile> [-out ] <outfile>

	extract-signature [ -pem ] [ -in ] <infile> [ -out ] <outfile>

	remove-signature [ -in ] <infile> [ -out ] <outfile>

	attach-signature [ -sigin ] <sigfile> [ -in ] <infile> [ -out ] <outfile>

	verify [ -in ] <infile>
		[ -require-leaf-hash {md5,sha1,sha2(56),sha384,sha512}:XXXXXXXXXXXX... ]

	add [-addUnauthenticatedBlob] [ -in ] <infile> [ -out ] <outfile>
		[ -t <timestampurl> [ -t ... ] [ -p <proxy> ] [ -noverifypeer ] ]
		[ -ts <timestampurl> [ -ts ... ] [ -p <proxy> ] [ -noverifypeer ] ]


Usage: /Users/ouchangkun/.cache/winCodeSign/winCodeSign-1.4.2/darwin/osslsigncode

	[ --version | -v ]

	[ sign ]
		( -certs <certfile> -key <keyfile> | -pkcs12 <pkcs12file> |
		  -pkcs11engine <engine> -pkcs11module <module> -certs <certfile> -key <pkcs11 key id>)
		[ -pass <password> ] [ -askpass ][ -readpass <file> ]
		[ -ac <crosscertfile> ]
		[ -h {md5,sha1,sha2(56),sha384,sha512} ]
		[ -n <desc> ] [ -i <url> ] [ -jp <level> ] [ -comm ]
		[ -ph ]
		[ -t <timestampurl> [ -t ... ] [ -p <proxy> ] [ -noverifypeer ] ]
		[ -ts <timestampurl> [ -ts ... ] [ -p <proxy> ] [ -noverifypeer ] ]
		[ -addUnauthenticatedBlob ]

		[ -nest ]

		[ -verbose ]

		MSI specific:
		[ -add-msi-dse ]

		[ -in ] <infile> [-out ] <outfile>

	extract-signature [ -pem ] [ -in ] <infile> [ -out ] <outfile>

	remove-signature [ -in ] <infile> [ -out ] <outfile>

	attach-signature [ -sigin ] <sigfile> [ -in ] <infile> [ -out ] <outfile>

	verify [ -in ] <infile>
		[ -require-leaf-hash {md5,sha1,sha2(56),sha384,sha512}:XXXXXXXXXXXX... ]

	add [-addUnauthenticatedBlob] [ -in ] <infile> [ -out ] <outfile>
		[ -t <timestampurl> [ -t ... ] [ -p <proxy> ] [ -noverifypeer ] ]
		[ -ts <timestampurl> [ -ts ... ] [ -p <proxy> ] [ -noverifypeer ] ]


	attach-signature [ -sigin ] <sigfile> [ -in ] <infile> [ -out ] <outfile>
	attach-signature [ -sigin ] <sigfile> [ -in ] <infile> [ -out ] <outfile>
    at /Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/util/util.ts:96:16
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at Object.exec (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/util/util.ts:77:9)
    at /Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/windowsCodeSign.ts:114:20
    at next (native)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at tsAwaiter (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/builder.ts:181:52)
    at Object.<anonymous> (/Users/ouchangkun/Work/Git/test-desktop/node_modules/electron-builder/src/build-cli.ts:27:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--registry=https://registry.npm.taobao.org" "--cache=/Users/ouchangkun/.npm/.cache/cnpm" "--disturl=https://npm.taobao.org/dist" "--userconfig=/Users/ouchangkun/.cnpmrc" "run" "build-win64"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 build-win64: `build --win --x64`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the test@1.0.0 build-win64 script 'build --win --x64'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --win --x64
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ouchangkun/Work/Git/test-desktop/npm-debug.log
```

**Comment by develar** [comment]
macOS code signing: duplicates #740 https://github.com/electron-userland/electron-builder/issues/740#issuecomment-245953214

**Comment by develar** [comment]
win code sign: must be pkcs12 file (`.p12` or `.pfx`) — not PEM.

**Comment by develar** [comment]
Please use certificateFile/certificatePassword only if you need to sign on macOS — because CSC_LINK is already used to specify macOS certificate. And I suggest to use the pass for win/mac — so, you can reuse the same env `CSC_KEY_PASSWORD`
