### ISSUE TITLE
Signing failed on Windows

### ISSUE THREAD

**Issue by panther7** [electron-userland/electron-builder#7578]
* **Electron-Builder Version**: 24.4.0

* **Node Version**: 20.1.0

* **Electron Version**: 24.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: win32 x64

Probably failed, if app name is with sapces(?)

LOG:
```
  • electron-builder  version=24.4.0 os=10.0.19045
  • artifacts will be published if draft release exists  reason=CI detected
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=win32 arch=x64 electron=24.3.0-seznam.1 appOutDir=builds\win-unpacked
  • copying Electron  source=C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\node_modules\electron\dist destination=C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\builds\win-unpacked
  • signing         file=builds\win-unpacked\Seznam.cz Electron.exe certificateFile=C:\pfx\www.seznam.cz.pfx
Error: Exit code: 1. Command failed: C:\Users\sbrowser\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.6.0\windows-10\x[64](https://gitlab.seznam.net/sbrowser/software/electron-analysis/-/jobs/31721111#L64)\signtool.exe sign /tr http://timestamp.digicert.com/ /f C:\pfx\www.seznam.cz.pfx /fd sha256 /td sha256 /d Seznam.cz Electron New-app-icon /du https://www.seznam.cz/prohlizec /p CENSORED (sha256 hash) /debug C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\builds\win-unpacked\Seznam.cz Electron.exe
	For more information, please see https://aka.ms/badexeformat
The following certificates were considered:
After EKU filter, 3 certs were left.
After expiry filter, 3 certs were left.
After Private Key filter, 1 certs were left.
The following certificate was selected:
The following additional certificates will be attached:
Done Adding Additional Store
	For more information, please see https://aka.ms/badexeformat
    at C:\builds\bf1ca0[75](https://gitlab.seznam.net/sbrowser/software/electron-analysis/-/jobs/31721111#L75)\0\sbrowser\software\electron-analysis\node_modules\builder-util\src\util.ts:133:18
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
From previous event:
    at processImmediate (node:internal/timers:478:21)
From previous event:
    at WinPackager.signApp (C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\node_modules\app-builder-lib\src\winPackager.ts:383:27)
    at WinPackager.doSignAfterPack (C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\node_modules\app-builder-lib\src\platformPackager.ts:332:32)
    at WinPackager.doPack (C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\node_modules\app-builder-lib\src\platformPackager.ts:317:7)
    at WinPackager.pack (C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\node_modules\app-builder-lib\src\platformPackager.ts:136:5)
    at Packager.doBuild (C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\node_modules\app-builder-lib\src\packager.ts:442:9)
    at executeFinally (C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\node_modules\app-builder-lib\src\packager.ts:3[76](https://gitlab.seznam.net/sbrowser/software/electron-analysis/-/jobs/31721111#L76):31)
    at Packager.build (C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\node_modules\app-builder-lib\src\packager.ts:337:12)
    at executeFinally (C:\builds\bf1ca075\0\sbrowser\software\electron-analysis\node_modules\builder-util\src\promise.ts:12:14)
```

**Comment by panther7** [comment]
I found probably issue.

1. Exe file is signed,
2. Apply custom icon,
3. Resign -> fail

If file is not signed, then apply icon a sign is succesful.

Before apply icon, it is need remove sign via `signtool.exe remove /s file.exe`

**Comment by panther7** [comment]
Still actualy
