### ISSUE TITLE
`electron-builder` not working with modules developed using node-addon-api when the target is s multiple and contains mas

### ISSUE THREAD

**Issue by Koppel-Zhou** [electron-userland/electron-builder#7587]
* **Electron-Builder Version**: 23.3.3\24.4.0

* **Node Version**: 16.19.1

* **Electron Version**: ^20.1.0 (20.3.8 in yarn.lock)
* **Electron Type (current, beta, nightly)**: current

* **Electron-Updater Version**: 4.0.6

* **Target**: 
'darwin': { mac: ['mas', 'dmg', 'zip'] },
'win32': { win: ['nsis'], ia32: true, x64: false }

This error only occurs when the target product is multiple and contains mas. If the target product is only mas or does not contain mas, everything works normally. **This error is because the rebuild task of the same native module is carried out in two rebuild tasks at the same time, and they conflict.**

Hope That Helps.

***The error info with `electron-builder@23.3.3`***
```
• electron-builder  version=23.3.3 os=22.4.0
  • loaded parent configuration  file=/Users/koppel/my-app/node_modules/electron-webpack/out/electron-builder.js
  • writing effective config  file=dist/online/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=node-systeminformation@1.0.8, better-sqlite3@8.3.0, bufferutil@4.0.7, utf-8-validate@5.0.10 platform=darwin arch=x64
  • install prebuilt binary  name=better-sqlite3 version=8.3.0 platform=darwin arch=x64 napi=
  • rebuilding native dependencies  dependencies=node-systeminformation@1.0.8, better-sqlite3@8.3.0, bufferutil@4.0.7, utf-8-validate@5.0.10 platform=darwin arch=x64
  • install prebuilt binary  name=better-sqlite3 version=8.3.0 platform=darwin arch=x64 napi=
  • rebuilding native dependency  name=bufferutil version=4.0.7
  • rebuilding native dependency  name=bufferutil version=4.0.7
  • rebuilding native dependency  name=node-systeminformation version=1.0.8
  • rebuilding native dependency  name=node-systeminformation version=1.0.8
  • rebuilding native dependency  name=utf-8-validate version=5.0.10
  • rebuilding native dependency  name=utf-8-validate version=5.0.10
  ⨯ cannot execute  cause=exit status 1
$ node-gyp rebuild
      CXX(target) Release/obj.target/systeminformation/src/systeminformation.o
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    
warning ../../../../../package.json: No license field
    gyp info it worked if it ends with ok
    gyp info using node-gyp@9.1.0
    gyp info using node@16.19.1 | darwin | x64
    gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
    gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
    gyp info spawn args [
    gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/koppel/my-app/node_modules/node-systeminformation/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/koppel/.electron-gyp/20.3.8/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/Users/koppel/.electron-gyp/20.3.8',
    gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/Users/koppel/.electron-gyp/20.3.8/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/Users/koppel/my-app/node_modules/node-systeminformation',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    rm: ./Release/.deps/Release/obj.target/systeminformation/src/systeminformation.o.d.raw: No such file or directory
    make: *** [Release/obj.target/systeminformation/src/systeminformation.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
    gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
    gyp ERR! System Darwin 22.4.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/koppel/my-app/node_modules/node-systeminformation
    gyp ERR! node -v v16.19.1
    gyp ERR! node-gyp -v v9.1.0
    gyp ERR! not ok 
error Command failed with exit code 1.
    
                    command=/usr/local/bin/node /usr/local/lib/node_modules/yarn/bin/yarn.js run install
                    workingDir=/Users/koppel/my-app/node_modules/node-systeminformation

/Users/koppel/my-app/node_modules/builder-util/src/util.ts:250
      reject(new ExecError(command, code, out, errorOut))
             ^
Error: /Users/koppel/my-app/node_modules/app-builder-bin/mac/app-builder_amd64 process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
2
    at ChildProcess.<anonymous> (/Users/koppel/my-app/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

***The error info with `electron-builder@24.4.0`***
```
  • electron-builder  version=24.4.0 os=22.4.0
  • loaded parent configuration  file=/Users/koppel/my-app/node_modules/electron-webpack/out/electron-builder.js
  • writing effective config  file=dist/online/builder-effective-config.yaml
  • executing @electron/rebuild  arch=x64 version=20.3.8 appDir=/Users/koppel/my-app
  • executing @electron/rebuild  arch=x64 version=20.3.8 appDir=/Users/koppel/my-app
  CXX(target) Release/obj.target/systeminformation/src/systeminformation.o
rm: ./Release/.deps/Release/obj.target/systeminformation/src/systeminformation.o.d.raw: No such file or directory
make: *** [Release/obj.target/systeminformation/src/systeminformation.o] Error 1
Error: `make` failed with exit code: 2
    at ChildProcess.onExit (/Users/koppel/my-app/node_modules/@electron/rebuild/node_modules/node-gyp/lib/build.js:203:23)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)

Error: node-gyp failed to rebuild '/Users/koppel/my-app/node_modules/node-systeminformation'
    at ChildProcess.<anonymous> (/Users/koppel/my-app/node_modules/@electron/rebuild/src/module-type/node-gyp/node-gyp.ts:131:16)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Koppel-Zhou** [comment]
Hi, @mmaietta , I think I found the cause of the [problem](https://github.com/electron-userland/electron-builder/issues/7341)

**Comment by mmaietta** [comment]
@Koppel-Zhou can you please create a minimal reproducible? (include electron-builder config and failing native modules added to package.json as well)

I have time to take a look at this now

**Comment by Koppel-Zhou** [comment]
Hi, @mmaietta , I submitted a new PR to fix this issue.
