### ISSUE TITLE
electron-builder fails with electron 25.0.1

### ISSUE THREAD

**Issue by robertpatrick** [electron-userland/electron-builder#7595]
* **Electron-Builder Version**: 24.4.0

* **Node Version**: 16.17.0 (also tried with 18.16.0)

* **Electron Version**: 25.0.1
* **Electron Type (current, beta, nightly)**: release

* **Target**: Linux x64

After upgrading to Electron 25.0.1 and Electron Builder 24.4.0, my application build no longer works:

> electron-builder -p never

  ��� electron-builder  version=24.4.0 os=5.4.17-2136.318.7.1.el8uek.x86_64
  ��� loaded configuration  file=package.json ("build" field)
  ��� executing @electron/rebuild  arch=x64 version=25.0.1 appDir=/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron
  ��� Could not detect abi for version 25.0.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron  failedTask=build stackTrace=Error: Could not detect abi for version 25.0.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/node-abi/index.js:39:9)
    at Rebuilder.get ABI [as ABI] (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/@electron/rebuild/src/rebuild.ts:124:33)
    at PrebuildInstall.prebuiltModuleExists (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/@electron/rebuild/src/module-type/prebuild-install.ts:62:149)
    at ModuleRebuilder.prebuildInstallNativeModuleExists (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/@electron/rebuild/src/module-rebuilder.ts:56:33)
    at Rebuilder.rebuildModuleAt (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/@electron/rebuild/src/rebuild.ts:179:31)
    at Rebuilder.rebuild (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/@electron/rebuild/src/rebuild.ts:158:9)
    at installOrRebuild (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/app-builder-lib/src/util/yarn.ts:27:5)
    at Packager.installAppDependencies (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/app-builder-lib/src/packager.ts:525:7)
    at LinuxPackager.doPack (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/app-builder-lib/src/platformPackager.ts:219:5)
    at LinuxPackager.pack (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/app-builder-lib/src/packager.ts:442:9)
    at executeFinally (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/scratch/wls/workspace/weblogic-kubernetes-toolkit-ui/electron/node_modules/builder-util/src/promise.ts:12:14)

**Comment by robertpatrick** [comment]
Sorry, was able to fix the issue by running `npm upgrade node-abi`...
