### ISSUE TITLE
uploader will download large size file after find .blockmap

### ISSUE THREAD

**Issue by 757566833** [electron-userland/electron-builder#7735]
* **Electron-Builder Version**: 24.6.3

* **Node Version**: v18.17.0

* **Electron Version**:25.3.2
* **Electron Type (current, beta, nightly)**:current

* **Electron Updater  Version**:6.1.1
* **Updater Server** : electron release server @ 2.1.3  docker

* **Target**: windows 

```
...
autoUpdater.on('download-progress', (progressObj) => {
    LoggerProd.debug(`download-progress ,${JSON.stringify(progressObj)}`)
    sendUpdate({ type: EUpdateType.DownloadProgress, percent: progressObj.percent })
})
```
```
[info] 1692449664919 : Checking for update
[info] 1692449664929 : Generated new staging user ID: 5493cb6f-bb21-5b2d-a628-cb8a34624ce6
[info] 1692449665078 : Found version 0.15.6 (<url>)
[info] 1692449665081 : Downloading update from <url>
[debug] 1692449665082 : updater cache dir: <path>
[warn] 1692449665084 : disableWebInstaller is set to false, you should set it to true if you do not plan on using a web installer. This will default to true in a future version.
[info] 1692449665084 : Download block maps (old: <blockmap url>, new: <blockmap url>)
[debug] 1692449665413 : RutwI+z6ASxx0Ys7JsbuqMBd duplicated in blockmap (same size), it doesn't lead to broken differential downloader, just corresponding block will be skipped)
[debug] 1692449665413 : 4b6Z8QEsNr0t89sOH98EI9uf duplicated in blockmap (same size), it doesn't lead to broken differential downloader, just corresponding block will be skipped)
[debug] 1692449665413 : +UfB7R4xDyNhPbr3IHoHP1Go duplicated in blockmap (same size), it doesn't lead to broken differential downloader, just corresponding block will be skipped)
[debug] 1692449665415 : [
  {
    "kind": 0,
    "start": 0,
    "end": 23693
  },
  {
    "kind": 1,
    "start": 23693,
    "end": 129035
  },
  {
    "kind": 0,
    "start": 129045,
    "end": 161813
  },
  {
    "kind": 1,
    "start": 161803,
    "end": 188745
  },
  {
    "kind": 0,
    "start": 188755,
    "end": 16783242
  },
  {
    "kind": 1,
    "start": 16783232,
    "end": 16991375
  },
  {
    "kind": 0,
    "start": 16991385,
    "end": 17331446
  },
  {
    "kind": 0,
    "start": 15045613,
    "end": 15111972
  },
  {
    "kind": 0,
    "start": 17397805,
    "end": 19188369
  },
  {
    "kind": 1,
    "start": 19188359,
    "end": 19215178
  },
  {
    "kind": 0,
    "start": 19215188,
    "end": 68527398
  },
  {
    "kind": 1,
    "start": 68527388,
    "end": 68727937
  },
  {
    "kind": 0,
    "start": 68727999,
    "end": 74345307
  },
  {
    "kind": 1,
    "start": 74345245,
    "end": 74397065
  },
  {
    "kind": 0,
    "start": 74397127,
    "end": 74628559
  },
  {
    "kind": 1,
    "start": 74628497,
    "end": 74786840
  }
]
[info] 1692449665425 : Full: 73,034.02 KB, To download: 759.72 KB (1%)
[info] 1692449665415 : File has 32 changed blocks
[info] 1692449665427 : Differential download: <exe url>
[debug] 1692449665430 : download range: bytes=23693-129034
[debug] 1692449666497 : download-progress ,{"total":777958,"delta":1293991,"transferred":1293991,"percent":166.33172999056504,"bytesPerSecond":1208208}
[debug] 1692449667831 : download-progress ,{"total":777958,"delta":598016,"transferred":1892007,"percent":243.20168955136396,"bytesPerSecond":786697}
[debug] 1692449668838 : download-progress ,{"total":777958,"delta":962560,"transferred":2854567,"percent":366.93073404991014,"bytesPerSecond":836626}
[debug] 1692449669863 : download-progress ,{"total":777958,"delta":675840,"transferred":3530407,"percent":453.80431848505964,"bytesPerSecond":795674}
[debug] 1692449670874 : download-progress ,{"total":777958,"delta":663897,"transferred":4194304,"percent":539.1427300702609,"bytesPerSecond":769880}
...
[debug] 1692449773506 : download-progress ,{"total":777958,"delta":678257,"transferred":74786840,"percent":9613.223335964152,"bytesPerSecond":691958}
[debug] 1692449773507 : download range: bytes=161803-188744
[debug] 1692449773869 : download-progress ,{"total":777958,"delta":858136,"transferred":74966719,"percent":9636.345278279805,"bytesPerSecond":691301}
...
[debug] 1692449883624 : download-progress ,{"total":777958,"delta":590049,"transferred":149573680,"percent":19226.446671928305,"bytesPerSecond":685495}
[debug] 1692449883674 : download range: bytes=16783232-16991374
[debug] 1692449883821 : download-progress ,{"total":777958,"delta":610203,"transferred":149593834,"percent":19229.03730021415,"bytesPerSecond":684969}
...
[debug] 1692450438655 : download-progress ,{"total":777958,"delta":158065,"transferred":523507880,"percent":67292.56335174906,"bytesPerSecond":677041}
[debug] 1692450438656 : download-progress ,{"total":777958,"delta":158065,"transferred":523507880,"percent":100,"bytesPerSecond":677040}
[error] 1692450438657 : Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected A90/iTeZV5aWmpGRR/KgUCThzM7uJaPLw8WC0AwdlLT46O/kttAjpI8q+Fy1cGRVu3xg7ysE1oDhkyDc2KIWcw==, got /46iUthtGW2EdOPmlFLooP5JoMcBaVu97+DrXdLKb1lN0iUZR6WEfpx54q8x0QE/PyILIpOBDi97Fghsms4rgw==
    at newError (G:\t\tbox\resources\app\node_modules\builder-util-runtime\out\index.js:47:19)
    at DigestTransform.validate (G:\t\tbox\resources\app\node_modules\builder-util-runtime\out\httpExecutor.js:327:40)
    at WriteStream.<anonymous> (G:\t\tbox\resources\app\node_modules\electron-updater\out\differentialDownloader\DifferentialDownloader.js:133:41)
    at WriteStream.emit (node:events:513:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

```

**Comment by 823639792** [comment]
@757566833 Are you solved the problem?

**Comment by idoodler** [comment]
I am having the same issue.
