### ISSUE TITLE
Error: Command failed: codesign --sign 

### ISSUE THREAD

**Issue by Salmankhan033** [electron-userland/electron-builder#7737]
Hey, I try code signing through **electron-builder** and also on **electron-osx-sign** but it returns the below error.
I delete all certificate and create it again but also return the same error, the F1D885152944FBF---A04342CF7621A115A9A key certificate is valid.
and also I download all these certificates from  one developer account but Apple Development: Salman Khan (FLF2--5UN) has a different team ID 

 ```
 "@electron-forge/cli": "^6.4.0",
    "@electron-forge/maker-deb": "^6.4.0",
    "@electron-forge/maker-rpm": "^6.4.0",
    "@electron-forge/maker-squirrel": "^6.4.0",
    "@electron-forge/maker-zip": "^6.4.0",
    "@electron-forge/plugin-auto-unpack-natives": "^6.4.0",
    "electron": "^25.3.2"
```

```

Error: Command failed: codesign --sign F1D885152944F*****2CF7621A115A9A --force --timestamp --options runtime --entitlements /opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/templates/entitlements.mac.plist /Users/salman/desktop_app/Order lemon - Salman/OrderLemon_Desktop/release/mac-arm64/OrderLemon.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/af.lproj/locale.pak
Warning: unable to build chain to self-signed root for signer "Apple Distribution: FABULOR (6926YY2PS8)"
/Users/salman/desktop_app/Order lemon - Salman/OrderLemon_Desktop/release/mac-arm64/OrderLemon.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/af.lproj/locale.pak: errSecInternalComponent


    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:511:28)
    at Pipe.<anonymous> (node:net:335:12)
From previous event:
    at processImmediate (node:internal/timers:478:21)
From previous event:
    at readDirectoryAndSign (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/macPackager.ts:467:29)
    at MacPackager.signApp (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/macPackager.ts:477:11)
    at MacPackager.doSignAfterPack (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:332:21)
    at MacPackager.doPack (/opt/homebrew/lib/node_modules/electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:317:7)
error Command failed with exit code 1.
```

<img width="827" alt="Screenshot 2023-08-20 at 3 18 31 AM" src="https://github.com/electron-userland/electron-builder/assets/58082294/1d11e693-49cf-4323-86ee-ac1ee24d5b8e">

<img width="426" alt="Screenshot 2023-08-20 at 3 18 38 AM" src="https://github.com/electron-userland/electron-builder/assets/58082294/32f54431-173d-4a81-8066-5b904c267b89">

**Comment by liosummer** [comment]
解决了吗？

**Comment by lmvaughan4** [comment]
> 解决了吗？

i also am getting this error, did we find a solution??

**Comment by jerryzhangdev** [comment]
me too, I am getting this error as well

**Comment by xinatcg** [comment]
it works before, but fail recently, nothing change.

**Comment by lewismvaughan** [comment]
I solved this by removing icloud file backups, icloud was basically creating circular references in the code base when auto backing up the files within it

**Comment by Usey95** [comment]
any solution?
