### ISSUE TITLE
Notarization on macOS broken since v24.9.0

### ISSUE THREAD

**Issue by nook24** [electron-userland/electron-builder#7883]
* **Electron-Builder Version**: [v24.9.0](https://github.com/electron-userland/electron-builder/releases/tag/v24.9.0)

* **Node Version**: v21.2.0

* **Electron Version**: 27.0.3
* **Electron Type (current, beta, nightly)**: current

* **Target**:  macOS Monterey (and newer)

Since today, the notarization of my macOS app fails with the error message: `APPLE_ID env var needs to be set`
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/macPackager.ts#L505

I did not changed anything in my code and it works as exacted with electron-builder version v24.8.1.

My `afterSign.js` looks like so:
```js
        try {
            await electron_notarize.notarize({
                appBundleId: appId,
                appPath: appPath,
                appleId: process.env.APPLE_ID_USR,
                appleIdPassword: process.env.APPLE_ID_PSW,
                teamId: process.env.APPLE_TEAM_ID_USR
            })
        } catch (error) {
            console.error(error)
        }
```

**Comment by dombarnes** [comment]
In my `electron-builder.yml` file i have `afterSign: 'build/notarize.js'` with a custom script to use @electron/notarize, which doesn't seem to be being used because I get the warnings 
```
Notarizing using the legacy altool system. The altool system will be disabled on November 1 2023. Please switch to the notarytool system before then.
You can do this by setting "tool: notarytool" in your "@electron/notarize" options. Please note that the credentials options may be slightly different between tools.
```
despite my js script usign
```
await notarize({
    appPath,
    appBundleId: appBundleId,
    appleId: appleId,
    appleIdPassword: appleIdPassword,
    teamId: '<my-team-id>',
    tool: 'notarytool'
  });
```
Basically it seems like afterSign isn't being used, as its using `app-builder-lib/macPackager.js` code

**Comment by dombarnes** [comment]
After some reading in macPackager, I had to add this for my MAS build
```
notarize:
    teamId: <my-team-id>
```
to my electron-builder file

Error from 
```
⨯ Cannot destructure property 'teamId' of 'options' as it is undefined.  failedTask=build stackTrace=TypeError: Cannot destructure property 'teamId' of 'options' as it is undefined.
    at MacPackager.generateNotarizeOptions (/path/to/node_modules/app-builder-lib/src/macPackager.ts:517:13)
    at MacPackager.notarizeIfProvided (/path/to/node_modules/app-builder-lib/src/macPackager.ts:502:26)
    at MacPackager.sign (/path/to/node_modules/app-builder-lib/src/macPackager.ts:335:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Have yet to debug the non-MAS version

**Comment by mmaietta** [comment]
Please try 24.9.1, seems there was a bug introduced during https://github.com/electron-userland/electron-builder/pull/7861

**Comment by dombarnes** [comment]
Yeah saw this earlier. Updated and worked. Although the pkg creation step was initially failing cos it was reading from the identity field i had set in my yml I think. Even though it should’ve been looking for a different named cert, it was using the Apple Distribution cert name id set. I had to uncomment that and let the defaults detect my 3rd party Mac installer certificate. Sent from my iPhoneOn 19 Nov 2023, at 17:38, Mike Maietta ***@***.***> wrote:﻿
Please try 24.9.1, seems there was a bug introduced during #7861

**Comment by nook24** [comment]
I can confirm that 24.9.1had resolved the issue for me.
