### ISSUE TITLE
Electron-builder failed on dmg-builder

### ISSUE THREAD

**Issue by PavelMor25** [electron-userland/electron-builder#7987]
* **Electron-Builder Version**: 24.6.4

* **Node Version**: 18

* **Electron Version**: 24.8.8
* **Electron Type (current, beta, nightly)**:

* **Target**: mac

Hello, after updating electron-builder from 22.10.5 to 24.6.4, we encountered a issue:

```shell
Error: Exit code: 1. Command failed: ln -s /Applications /Volumes/TestCafe Studio 2.0.0-arm64/Applications
ln: /Volumes/TestCafe Studio 2.0.0-arm64/Applications/Applications: File exists

ln: /Volumes/TestCafe Studio 2.0.0-arm64/Applications/Applications: File exists

    at /Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules/builder-util/src/util.ts:133:18
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:537:15)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:537:15)
    at Pipe.<anonymous> (node:net:709:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
``` 
I couldn't find whether anyone has encountered a similar issue before.

Have you encountered a similar issue? Do you have any ideas on how to resolve this issue?

The build is performed on a Mac mini 2018 running macOS Catalina with Node.js 18.

Logs:
```shell
• electron-builder  version=24.6.4 os=19.6.0
  • loaded configuration  file=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/electron-builder.json
  • writing effective config  file=_dist_/builder-effective-config.yaml
  • unresolved deps  unresolved=isarraypngjscolorsdijkstrajs nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=linux-platform-infograceful-fsos-familywhich-promiseread-file-relativearray-finddedentlodashmkdirpdebugnanoidpinkie
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=0
  • unresolved deps  unresolved=is-globis-path-insidep-mapslashgraceful-fs nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=glob nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=merge2slasharray-uniondir-globfast-globglobignore nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=clean-stack nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=jsonfileuniversalifygraceful-fs nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=signal-exitis-streamnpm-run-pathcross-spawnonetimestrip-final-newline
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=0
  • unresolved deps  unresolved=end-of-streamonce nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=isexe nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=get-caller-file nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=remove-trailing-separator nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=set-cookie-parsersource-map-supportbabel-plugin-syntax-trailing-function-commasos-familyhumanize-durationis-streamtestcafe-legacy-api@babel/core@babel/plugin-proposal-private-methods@babel/preset-envtestcafe-reporter-minimal@babel/plugin-syntax-import-metaget-os-infois-docker@babel/plugin-syntax-dynamic-importjson5url-to-optionshttp-status-codesqrcode-terminal@babel/plugin-proposal-object-rest-spreadcoffeescriptgraceful-fsdeltestcafe-reporter-jsontime-limit-promise@devexpress/callsite-recordbabel-plugin-module-resolvercallsitetestcafe-safe-storage@babel/plugin-proposal-class-properties@babel/plugin-transform-async-to-generatorimport-lazypromisify-eventlog-update-async-hooktestcafe-hammerheadnanoidpretty-hrtimetestcafe-reporter-list@babel/plugin-proposal-async-generator-functionsdevice-specsmomentmoment-duration-format-commonjsread-file-relativetestcafe-selector-generator@babel/preset-reactbowserpromptssanitize-filenametestcafe-reporter-xunit@babel/plugin-transform-for-of@babel/preset-flowglobbyerror-stack-parsertestcafe-reporter-specunquotechrome-remote-interfaceelegant-spinneremail-validatorendpoint-utilspinkie@devexpress/bin-v8-flags-filtergraphlibis-podmanreplicator@babel/plugin-proposal-decorators@babel/plugin-transform-exponentiation-operatormime-dblodashtree-kill@babel/runtimedebug
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules-list@babel/plugin-proposal-async-generator-functionsdevice-specsmomentmoment-duration-format-commonjsread-file-relativetestcafe-selector-generator@babel/preset-reactbowserpromptssanitize-filenametestcafe-reporter-xunit@babel/plugin-transform-for-of@babel/preset-flowglobbyerror-stack-parsertestcafe-reporter-specunquotechrome-remote-interfaceelegant-spinneremail-validatorendpoint-utilspinkie@devexpress/bin-v8-flags-filtergraphlibis-podmanreplicator@babel/plugin-proposal-decorators@babel/plugin-transform-exponentiation-operatormime-dblodashtree-kill@babel/runtimedebug
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     fe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=0
  • unresolved deps  unresolved=onetimesignal-exitstrip-final-newlinecross-spawnis-streamnpm-run-path
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=0
  • unresolved deps  unresolved=end-of-streamonce nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=check-errorget-func-namepathvalassertion-error nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=type-detect nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=os-tmpdir nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=is-utf8 nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=linux-platform-infomkdirppinkiewhich-promisearray-findgraceful-fslodashpifydebugmustacheos-familyread-file-relativefs-extrananoid
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules/testcafe/node_modules
                     round=0
  • unresolved deps  unresolved=linux-platform-infomkdirppinkiewhich-promisearray-findgraceful-fslodashpifydebugmustacheos-familyread-file-relativenanoid
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=1
  • unresolved deps  unresolved=is-path-cwdis-path-insidep-maprimrafslashgraceful-fs
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules/testcafe/node_modules
                     round=0
  • unresolved deps  unresolved=is-path-insidep-mapslashgraceful-fs nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=1
  • unresolved deps  unresolved=slasharray-uniondir-globfast-globglobignoremerge2
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules/testcafe/node_modules
                     round=0
  • unresolved deps  unresolved=slasharray-uniondir-globfast-globglobignoremerge2 nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=1
  • unresolved deps  unresolved=glob nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=is-streammerge-streamonetimep-finallysignal-exitstrip-final-newlineget-streamhuman-signalsnpm-run-pathcross-spawn
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules/testcafe/node_modules
                     round=0
  • unresolved deps  unresolved=is-streammerge-streamonetimesignal-exitstrip-final-newlineget-streamhuman-signalsnpm-run-pathcross-spawn
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=1
  • unresolved deps  unresolved=xtend nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=core-util-isinherits nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=graceful-fsjsonfileuniversalify nodeModuleDir=/Users/testcafe/Library/Services/actions-runnunresolved=@babel/plugin-syntax-logical-assignment-operators@babel/plugin-transform-class-properties@babel/plugin-transform-computed-properties@babel/plugin-transform-optional-chaining@babel/plugin-transform-regenerator@babel/plugin-transform-typeof-symbol@babel/plugin-syntax-import-attributes@babel/plugin-syntax-private-property-in-object@babel/plugin-transform-async-to-generator@babel/plugin-transform-duplicate-keys@babel/plugin-transform-reserved-words@babel/compat-data@babel/plugin-transform-dotall-regex@babel/plugin-syntax-unicode-sets-regex@babel/plugin-transform-member-expression-literals@babel/plugin-transform-object
  code-sets-regex@babel/plugin-transform-member-expression-literals@babel/plugin-transform-object-super@babel/plugin-syntax-top-level-await@babel/plugin-syntax-export-namespace-from@babel/plugin-transform-block-scoping@babel/plugin-transform-named-capturing-groups-regex@babel/plugin-transform-unicode-sets-regex@babel/plugin-bugfix-v8-static-class-fields-redefine-readonly@babel/plugin-transform-async-generator-functions@babel/plugin-transform-destructuring@babel/plugin-transform-for-of@babel/plugin-transform-modules-amd@babel/plugin-transform-new-target@babel/plugin-transform-property-literals@babel/plugin-transform-shorthand-properties@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@babel/plugin-transform-unicode-property-regex@babel/plugin-transform-nullish-coalescing-operator@babel/plugin-syntax-import-meta@babel/plugin-syntax-numeric-separator@babel/plugin-transform-exponentiation-operator@babel/plugin-transform-optional-catch-binding@babel/plugin-transform-unicode-escapes@babel/plugin-transform-unicode-regex@babel/helper-compilation-targets@babel/helper-validator-option@babel/plugin-syntax-dynamic-import@babel/plugin-transform-class-static-block@babel/plugin-transform-classes@babel/plugin-transform-numeric-separator@babel/plugin-transform-sticky-regex@babel/helper-plugin-utils@babel/plugin-transform-block-scoped-functions@babel/plugin-transform-json-strings@babel/plugin-transform-private-property-in-object@babel/plugin-syntax-class-propertiesbabel-plugin-polyfill-corejs3@babel/plugin-transform-spread@babel/plugin-syntax-import-assertions@babel/plugin-syntax-json-strings@babel/plugin-transform-literals@babel/plugin-transform-modules-systemjs@babel/preset-modulesbabel-plugin-polyfill-regenerator@babel/plugin-syntax-class-static-block@babel/plugin-transform-arrow-functionsbabel-plugin-polyfill-corejs2@babel/plugin-syntax-optional-chaining@babel/plugin-syntax-async-generators@babel/plugin-syntax-object-rest-spread@babel/plugin-syntax-optional-catch-binding@babel/plugin-transform-export-namespace-from@babel/plugin-transform-object-rest-spread@babel/plugin-transform-parameters@babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression@babel/plugin-syntax-nullish-coalescing-operator@babel/plugin-transform-dynamic-import@babel/plugin-transform-logical-assignment-operators@babel/plugin-transform-modules-commonjs@babel/plugin-transform-modules-umd@babel/plugin-transform-private-methodscore-js-compat@babel/plugin-proposal-private-property-in-object@babel/plugin-transform-template-literals@babel/plugin-transform-function-name
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=0
  • unresolved deps  unresolved=@babel/helper-annotate-as-pureregexpu-core nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=cross-spawnget-streamhuman-signalsis-streamonetimestrip-final-newlinenpm-run-pathsignal-exit
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=0
  • unresolved deps  unresolved=is-path-cwdis-path-in-cwdpifyrimraf nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=object-assignpinkie-promisearray-unionglob
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules/del/node_modules
                     round=0
  • unresolved deps  unresolved=object-assignpinkie-promiseglob nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=1
  • unresolved deps  unresolved=array-uniq nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=path-is-inside nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=callsiteerror-stack-parserhighlight-eslodashpinkie-promise
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=0
  • unresolved deps  unresolved=resolvefind-babel-configpkg-upreselect nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=oncefs.realpathinflightinheritsminimatch nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=p-try nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=pinkie-promise nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=wrap-ansiansi-escapes nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=@electron/asarpinkietough-cookienanoidos-family@adobe/css-toolshttp-cache-semanticsmatch-url-wildcardtunnel-agenthttpntlmlodashread-file-relativeacorn-hammerheadcrypto-md5esotope-hammerhead
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=0
  • unresolved deps  unresolved=ms nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=readable-stream nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=safe-bufferstring_decoderutil-deprecatecore-util-isinheritsprocess-nextick-args
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=0
  • unresolved deps  unresolved=safer-buffer nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=yallist nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules/testcafe-hammerhead/node_modules round=0
  • unresolved deps  unresolved=glob nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=balanced-matchconcat-map nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=punycodeurl-parsepsl nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=array-uniondir-globfast-globignoremerge2slash nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=default-shell nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=p-finallysignal-exitstrip-eof nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=pseudomap nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=isexe nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=object-assignpinkie-promise nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=inflightinheritsoncepath-is-absolutefs.realpath nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=balanced-matchconcat-map nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=@babel/types@babel/helper-module-transforms@babel/templatedebuggensync@babel/helper-compilation-targets@babel/generator@babel/helpers@babel/parser@babel/traversejson5@ampproject/remappingconvert-source-map@babel/code-frame
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=0
  • unresolved deps  unresolved=fs-extrajs-yamllazy-vallodash.isequal nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=debugsax nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=formidablelodashxml-cryptoaxios-ntlmdebugget-streamsax
                     nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules
                     round=0
  • unresolved deps  unresolved=supports-coloransi-styles nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=y18ncliuiescaladerequire-directorystring-width nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • unresolved deps  unresolved=tslib nodeModuleDir=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules round=0
  • map async       taskCount=49
  • map async       taskCount=1
  • map async       taskCount=3
  • map async       taskCount=484
  • map async       taskCount=1
  • map async       taskCount=2
  • map async       taskCount=1
  • map async       taskCount=4
  • map async       taskCount=3
  • map async       taskCount=1
  • map async       taskCount=2
  • map async       taskCount=2
  • map async       taskCount=1
  • map async       taskCount=8
  • map async       taskCount=1
  • map async       taskCount=3
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=3
  • map async       taskCount=1
  • map async       taskCount=5
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=11
  • map async       taskCount=3
  • map async       taskCount=13
  • map async       taskCount=4
  • map async       taskCount=12
  • map async       taskCount=5
  • map async       taskCount=45
  • map async       taskCount=1
  • map async       taskCount=4
  • map async       taskCount=2
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=7
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=3
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=6
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=7
  • map async       taskCount=7
  • no native dependencies  
  • packaging       platform=darwin arch=x64 electron=23.1.1 appOutDir=_dist_/mac
  • map async       taskCount=2
  • map async       taskCount=1
  • map async       taskCount=255
  • map async       taskCount=8
  • path doesn\'t exist  path=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/build/runners/mac/testcafe.icns
  • path resolved   path=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/runners/mac/testcafe.icns outputFormat=icns
  • map async       taskCount=5
  • signing
notarizing
  • building        target=macOS zip arch=x64 file=_dist_/[DevExpressTestCafeStudio-mac-2.0.0-x64.zip](https://web.telegram.org/a/DevExpressTestCafeStudio-mac-2.0.0-x64.zip)
  • building        target=DMG arch=x64 file=_dist_/DevExpressTestCafeStudio-mac-2.0.0-x64.dmg
  • map async       taskCount=49
  • map async       taskCount=1
  • map async       taskCount=3
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=2
  • map async       taskCount=1
  • map async       taskCount=4
  • map async       taskCount=3
  • map async       taskCount=2
  • map async       taskCount=484
  • map async       taskCount=1
  • map async       taskCount=2
  • map async       taskCount=8
  • map async       taskCount=1
  • map async       taskCount=3
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=4
  • map async       taskCount=1
  • map async       taskCount=5
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=11
  • map async       taskCount=3
  • map async       taskCount=45
  • map async       taskCount=13
  • map async       taskCount=12
  • map async       taskCount=5
  • map async       taskCount=1
  • map async       taskCount=3
  • map async       taskCount=1
  • map async       taskCount=4
  • map async       taskCount=2
  • map async       taskCount=7
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=7
  • map async       taskCount=1
  • map async       taskCount=7
  • map async       taskCount=1
  • map async       taskCount=3
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=1
  • map async       taskCount=6
  • map async       taskCount=1
  • map async       taskCount=1
  • no native dependencies  
  • packaging       platform=darwin arch=arm64 electron=23.1.1 appOutDir=_dist_/mac-arm64
  • map async       taskCount=2
  • map async       taskCount=1
  • map async       taskCount=255
  • map async       taskCount=8
  • map async       taskCount=5
  • signing         file=_dist_/mac-arm64/TestCafe [Studio.app](https://web.telegram.org/a/Studio.app) identityName=Developer ID Application: Developer Express Inc (UA69PNBN6P) identityHash=2F8B4662F6594720BFBCA323CCDF273B68D8A7B4 provisioningProfile=none
  • copy files      from=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/runners/mac/volume.icns
                    to=/Volumes/TestCafe Studio 2.0.0/.VolumeIcon.icns
                    isUseHardLinks=false
  • copy files      from=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/runners/mac/installer/tmpl/back.tiff
                    to=/Volumes/TestCafe Studio 2.0.0/.background/back.tiff
                    isUseHardLinks=false
  • execute command  command=sips -g pixelHeight -g pixelWidth /Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/runners/mac/installer/tmpl/back.tiff
                     workingDirectory=
  • command executed  executable=sips out=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/runners/mac/installer/tmpl/back.tiff
  pixelHeight: 405
  pixelWidth: 545

  • building block map  blockMapFile=_dist_/DevExpressTestCafeStudio-mac-2.0.0-x64.dmg.blockmap
  • building block map  blockMapFile=_dist_/DevExpressTestCafeStudio-mac-2.0.0-x64.zip.blockmap
notarizing
  • building        target=macOS zip arch=arm64 file=_dist_/[DevExpressTestCafeStudio-mac-2.0.0-arm64.zip](https://web.telegram.org/a/DevExpressTestCafeStudio-mac-2.0.0-arm64.zip)
  • building        target=DMG arch=arm64 file=_dist_/DevExpressTestCafeStudio-mac-2.0.0-arm64.dmg
  • skipped dependencies rebuild  reason=platform is different and buildDependenciesFromSource is set to true
  • packaging       platform=linux arch=x64 electron=23.1.1 appOutDir=_dist_/linux-unpacked
  • map async       taskCount=2
  • map async       taskCount=1
  • map async       taskCount=74
  • copy files      from=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/runners/mac/volume.icns
                    to=/Volumes/TestCafe Studio 2.0.0-arm64/.VolumeIcon.icns
                    isUseHardLinks=false
  • skipping "afterSign" hook as no signing occurred, perhaps you intended "afterPack"?
  • building        target=zip arch=x64 file=_dist_/[DevExpressTestCafeStudio-linux-2.0.0-x64.zip](https://web.telegram.org/a/DevExpressTestCafeStudio-linux-2.0.0-x64.zip)
  • copy files      from=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/runners/mac/installer/tmpl/back.tiff
                    to=/Volumes/TestCafe Studio 2.0.0-arm64/.background/back.tiff
                    isUseHardLinks=false
  • execute command  command=sips -g pixelHeight -g pixelWidth /Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/runners/mac/installer/tmpl/back.tiff
                     workingDirectory=
  • command executed  executable=sips out=/Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/runners/mac/installer/tmpl/back.tiff
  pixelHeight: 405
  pixelWidth: 545

  • building block map  blockMapFile=_dist_/DevExpressTestCafeStudio-mac-2.0.0-arm64.zip.blockmap
Error: Exit code: 1. Command failed: ln -s /Applications /Volumes/TestCafe Studio 2.0.0-arm64/Applications
ln: /Volumes/TestCafe Studio 2.0.0-arm64/Applications/Applications: File exists

ln: /Volumes/TestCafe Studio 2.0.0-arm64/Applications/Applications: File exists

    at /Users/testcafe/Library/Services/actions-runner1/_work/testcafe-studio/testcafe-studio/node_modules/builder-util/src/util.ts:133:18
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:537:15)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:537:15)
    at Pipe.<anonymous> (node:net:709:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
``` 
electron-builder.json:
```javascript
{
  "appId": "com.devexpress.testcafestudio",
  "productName": "TestCafe Studio",
  "artifactName": "DevExpressTestCafeStudio-${os}-${version}-${arch}.${ext}",
  "buildDependenciesFromSource": true,
  "directories": {
    "output": "_dist_"
  },
  "asar": {
    "smartUnpack": false
  },
  "electronVersion": "23.1.1",
  "files": [
    "_compiled_/**/*.*",
    "docs/**/*.*",
    "lib/**/*.*",
    "examples/**/*.*",
    "release-notes/**/*.*",
    "runners/linux/icon.png",
    "index.js",
    "package.json"
  ],
  "extraResources": [
    {
      "from": "node_modules/testcafe/ts-defs/index.d.ts",
      "to": "app.asar.unpacked/node_modules/testcafe/ts-defs/index.d.ts"
    },
    {
      "from": "node_modules/@types/node/index.d.ts",
      "to": "app.asar.unpacked/node_modules/@types/node/index.d.ts"
    },
    {
      "from": "node_modules/@types/node/base.d.ts",
      "to": "app.asar.unpacked/node_modules/@types/node/base.d.ts"
    },
    {
      "from": "node_modules/typescript/lib",
      "to": "app.asar.unpacked/node_modules/typescript/lib",
      "filter": [
        "*.d.ts"
      ]
    }
  ],
  "asarUnpack": [
    "**/*.{exe,config}",
    "examples",
    "release-notes",
    "docs",
    "node_modules/**/*"
  ],
  "win": {
    "target": [
      {
        "target": "nsis",
        "arch": ["x64"]
      }
    ],
    "icon": "runners/win/testcafe.ico",
    "publish": [
      {
        "provider": "generic",
        "url": "*******"
      }
    ],
    "artifactName": "DevExpressTestCafeStudioSetup-${os}-${version}.${ext}"
  },
  "nsis": {
    "oneClick": false,
    "license": "./docs/TESTCAFE_STUDIO_EULA.txt",
    "include": "runners/win/uninstaller.nsh",
    "installerSidebar": "runners/win/sidebar.bmp",
    "uninstallerSidebar": "runners/win/sidebar.bmp",
    "unicode": true
  },
  "mac": {
    "category": "public.app-category.developer-tools",
    "icon": "runners/mac/testcafe.icns",
    "target": [
      {
        "target": "default",
        "arch" : [
          "x64",
          "arm64"
        ]
      }
    ],
    "hardenedRuntime": true,
    "gatekeeperAssess": false,
    "entitlements": "runners/mac/entitlements.mas.plist",
    "entitlementsInherit": "runners/mac/entitlements.mas.plist",
    "extendInfo": {
      "NSAppleScriptEnabled": true,
      "NSAppleEventsUsageDescription": "TestCafe Studio requires this permission to control test execution and take screenshots."
    },
    "publish": [
      {
        "provider": "generic",
        "url": "******"
      }
    ],
    "type": "distribution"
  },
  "linux": {
    "category": "Development",
    "packageCategory": "Development",
    "target": [
      {
        "target": "zip",
        "arch": ["x64"]
      }
    ]
  },
  "dmg": {
    "icon": "runners/mac/volume.icns",
    "background": "runners/mac/installer/tmpl/back.tiff",
    "iconSize": 112,
    "contents": [
      {
        "type": "file",
        "x": 120,
        "y": 245
      },
      {
        "type": "link",
        "path": "/Applications",
        "x": 410,
        "y": 245
      },
      {
        "x": 410,
        "y": 85,
        "type": "file",
        "path": "docs/TESTCAFE_STUDIO_EULA.txt"
      }
    ]
  },
  "afterPack": "./build/after-pack.js",
  "afterSign": "./build/after-sign.js"
}
``` 
electron-build script:
```javascript
const builder = require('electron-builder');
const config  = require('./electron-builder.json');

const targets = builder.createTargets([Platform.MAC, Platform.LINUX], null, 'x64')

builder
        .build({ targets, config })
        .catch(err => console.error(err));
```

**Comment by ArmelChesnais** [comment]
@PavelMor25 have you found a solution to this? We're running into this ourselves, and unsure how to proceed at the moment
