### ISSUE TITLE
Can't Build EXE

### ISSUE THREAD

**Issue by ProdigyView** [electron-userland/electron-builder#8077]
* **Electron-Builder Version**:  24.12.0

* **Node Version**: 20.11

* **Electron Version**: 29.0.1
* **Electron Type (current, beta, nightly)**:

* **Target**:  WIndows

I get this error during the build process:
```

[=======             ] 34% 528.4s | glitch-desktop-app-1.5.9-arm64.nsis.7z to github
    [=======             ] 34% 525.0s | glitch-desktop-app-1.5.9-arm64.nsis.7z to github  ⨯ C:\Users\devin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE======              ] 30% 627.1s | glitch-desktop-app-1.5.9-x64.nsis.7z to github
Exit code:
1
Output:
Command line defined: "APP_ID=com.package.xxxx"
Command line defined: "APP_GUID=xxxxxxa"
Command line defined: "UNINSTALL_APP_KEY=zzzzzzzzzz"
Command line defined: "PRODUCT_NAME=Glitch Desktop App"
Command line defined: "PRODUCT_FILENAME=Glitch Desktop App"
Command line defined: "APP_FILENAME=glitch-desktop-app"
Command line defined: "APP_DESCRIPTION=For streaming games with Glitch."
Command line defined: "VERSION=1.5.9"
Command line defined: "PROJECT_DIR=C:\Users\zzzzz\GitHub\Glitch-Electron"
Command line defined: "BUILD_RESOURCES_DIR=C:\Usewe\zzzzzz\GitHub\Glitch-Electron\build"
Command line defined: "APP_PACKAGE_NAME=glitch-desktop-app"
Command line defined: "MUI_ICON=C:\Users\zzzzz\GitHub\Glitch-Electron\src\images\logo\icon.ico"
Command line defined: "MUI_UNICON=C:\Users\zzzzzz\GitHub\Glitch-Electron\src\images\logo\icon.ico"
Command line defined: "APP_ARM64=C:\Users\zzzzzzz\GitHub\Glitch-Electron\dist\glitch-desktop-app-1.5.9-arm64.nsis.7z"
Command line defined: "APP_ARM64_NAME=glitch-desktop-app-1.5.9-arm64.nsis.7z"
Command line defined: "APP_ARM64_HASH=30680BEC7B3E43B627EC6E7E50FB24A67F71EB33B7DF83253830C10D25850C1E99D76691DD60E4E50D0D7073E3AF90B64CEFE8434860F42F7C8030E9D03E361D"
Command line defined: "APP_ARM64_UNPACKED_SIZE=1938988"
Command line defined: "APP_64=C:\Users\zzzzzzz\GitHub\Glitch-Electron\dist\glitch-desktop-app-1.5.9-x64.nsis.7z"
Command line defined: "APP_64_NAME=glitch-desktop-app-1.5.9-x64.nsis.7z"
Command line defined: "APP_64_HASH=303C7467B6DB2A9076B2A3BD6D6170353406B10C8E8CACD730F238713DFD7E07E670F4F11A2B1B1C223F2E261682EE79D8FFB1CC03B83ADB452CFACCB44ADE43"
Command line defined: "APP_64_UNPACKED_SIZE=1932159"
Command line defined: "APP_32=C:\Users\zzzzzzz\GitHub\Glitch-Electron\dist\glitch-desktop-app-1.5.9-ia32.nsis.7z"
Command line defined: "APP_32_NAME=glitch-desktop-app-1.5.9-ia32.nsis.7z"
Command line defined: "APP_32_HASH=A49B8B9B24EE1951EFAF1DDAE44604A72771BB2AEA30DB9559E8D2026EBE5D70783CE39175D37FD4D1EE780AC278DFD179958E8EE07407F8AF3FB91CD747A432"
Command line defined: "APP_32_UNPACKED_SIZE=1905152"
Command line defined: "COMPANY_NAME=MW"
Command line defined: "APP_PRODUCT_FILENAME=Glitch Desktop App"
Command line defined: "APP_INSTALLER_STORE_FILE=glitch-desktop-app-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "SHORTCUT_NAME=Glitch Desktop App"
Command line defined: "UNINSTALL_DISPLAY_NAME=Glitch Desktop App 1.5.9"
Command line defined: "RECREATE_DESKTOP_SHORTCUT"
Command line defined: "ESTIMATED_SIZE=5776297"
Command line defined: "COMPRESS=auto"
Command line defined: "UNINSTALLER_OUT_FILE=C:\Users\zzzzz\GitHub\Glitch-Electron\dist\__uninstaller-nsis-glitch-desktop-app.exe"
Processing config: C:\Users\zzzzz\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\nsisconf.nsh
Processing script file: "<stdin>" (UTF8)

Note: you may have one or two (large) stale temporary file(s) left in your temporary directory (Generally this only happens on Windows 9x).

Error output:

Internal compiler error #12345: error mmapping file (1536011714, 67108864) is out of range.
  failedTask=build stackTrace=Error: C:\Users\zzzzzz\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1

Processing config: C:\Users\zzzzzzz\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\nsisconf.nsh
Processing script file: "<stdin>" (UTF8)






























                                                                                  Note: you may have one or two (large) stale temporary file(s) left in your temporary directory (Generally this only happens on Windows 9x).






























                                                                                  Error output:






























                                                                                  Internal compiler error #12345: error mmapping file (1536011714, 67108864) is out of range.






























                                                                                      at ChildProcess.<anonymous> (C:\Users\devin\GitHub\Glitch-Electron\node_modules\builder-util\src\util.ts:252:14)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess.cp.emit (C:\Users\devin\GitHub\Glitch-Electron\node_modules\cross-spawn\lib\enoent.js:34:29)
```

**Comment by mmaietta** [comment]
Best guess from the error code and the `"ESTIMATED_SIZE=5776297"` is that you're over the max size allowed for a nsis installer (2gb). You'll either need to split up your binaries (x32 vs x64), or maybe use web-installer, or download the game assets after a successful installation (many large games take this latter approach)
