### ISSUE TITLE
Error At Beginning of Build Process

### ISSUE THREAD

**Issue by ProdigyView** [electron-userland/electron-builder#8080]
* **Electron-Builder Version**:  24.9.1

* **Node Version**:  20.11

* **Electron Version**: 28.2.2
* **Electron Type (current, beta, nightly)**:

* **Target**: Windows

I am getting this error at the beginning of the build process:

```
C:\Users\devin\GitHub\Glitch-Electron>npm run dist

> glitch-desktop-app@1.5.9 dist
> electron-builder --publish=always

  • electron-builder  version=24.12.0 os=10.0.22631
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • "electron-squirrel-startup" dependency is not required for NSIS
  • "electron-squirrel-startup" dependency is not required for NSIS
  • "electron-squirrel-startup" dependency is not required for NSIS
  • rebuilding native dependencies  dependencies=bufferutil@4.0.8, utf-8-validate@5.0.10 platform=win32 arch=ia32
  • packaging       platform=win32 arch=ia32 electron=28.2.2 appOutDir=dist\win-ia32-unpacked
  • signing         file=dist\win-ia32-unpacked\resources\src\ffmpeg\windows\ffprobe.exe certificateFile=certs/certificate.pfx
  • signing         file=dist\win-ia32-unpacked\resources\src\ffmpeg\windows\ffmpeg.exe certificateFile=certs/certificate.pfx
  • signing         file=dist\win-ia32-unpacked\resources\src\ffmpeg\windows\ffplay.exe certificateFile=certs/certificate.pfx
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=991ms
  ⨯ exit status 2
github.com/develar/app-builder/pkg/download.ConfigureArtifactCommand.func1
        /Volumes/data/Documents/app-builder/pkg/download/artifactDownloader.go:29
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:90
runtime.main
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:255
runtime.goexit
        /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581
  ⨯ C:\Users\devin\GitHub\Glitch-Electron\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: C:\Users\devin\GitHub\Glitch-Electron\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (C:\Users\devin\GitHub\Glitch-Electron\node_modules\builder-util\src\util.ts:252:14)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess.cp.emit (C:\Users\devin\GitHub\Glitch-Electron\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
From previous event:
    at processImmediate (node:internal/timers:478:21)
From previous event:
    at walk (C:\Users\zzzzzz\GitHub\Glitch-Electron\node_modules\builder-util\src\fs.ts:77:51)
    at C:\Users\xxxxx\GitHub\Glitch-Electron\node_modules\app-builder-lib\src\fileMatcher.ts:354:12
    at C:\Users\xxxxx\GitHub\Glitch-Electron\node_modules\app-builder-lib\src\fileMatcher.ts:354:12
    
```

**Comment by ProdigyView** [comment]
Figured it out, for some reason I had to run Windows as a super adminstrator.

**Comment by lebronjs** [comment]
help me, how did you fix it
