### ISSUE TITLE
Issue with dmg-builder: `struct.error: required argument is not an integer`

### ISSUE THREAD

**Issue by coredev-uk** [electron-userland/electron-builder#8099]
* **Electron-Builder Version**: 24.13.3

* **Node Version**: 21.6.2

* **Electron Version**: 29.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: darwin - dmg - arm64

When compiling, during the DMG build step I receive this error on Python 3.12.2

```
Error: Exit code: 1. Command failed: /opt/homebrew/opt/python@3.12/libexec/bin/python /Users/core/project/node_modules/dmg-builder/vendor/dmgbuild/core.py
Traceback (most recent call last):
  File "/Users/core/project/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 290, in <module>
    build_dmg()
  File "/Users/core/project/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 286, in build_dmg
    d[k]['Iloc'] = v
    ~~~~^^^^^^^^
  File "/Users/core/project/node_modules/dmg-builder/vendor/ds_store/store.py", line 1236, in __setitem__
    self._store.insert(DSStoreEntry(self._filename, code,
  File "/Users/core/project/node_modules/dmg-builder/vendor/ds_store/store.py", line 732, in insert
    self._insert_leaf(path, node, entry)
  File "/Users/core/project/node_modules/dmg-builder/vendor/ds_store/store.py", line 695, in _insert_leaf
    if remaining < entry.byte_length():
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/core/project/node_modules/dmg-builder/vendor/ds_store/store.py", line 202, in byte_length
    value = self.type.encode(self.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/core/project/node_modules/dmg-builder/vendor/ds_store/store.py", line 25, in encode
    return struct.pack(b'>IIII', point[0], point[1],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: required argument is not an integer

Traceback (most recent call last):
  File "/Users/core/project/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 290, in <module>
    build_dmg()
  File "/Users/core/project/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 286, in build_dmg
    d[k]['Iloc'] = v
    ~~~~^^^^^^^^
  File "/Users/core/project/node_modules/dmg-builder/vendor/ds_store/store.py", line 1236, in __setitem__
    self._store.insert(DSStoreEntry(self._filename, code,
  File "/Users/core/project/node_modules/dmg-builder/vendor/ds_store/store.py", line 732, in insert
    self._insert_leaf(path, node, entry)
  File "/Users/core/project/node_modules/dmg-builder/vendor/ds_store/store.py", line 695, in _insert_leaf
    if remaining < entry.byte_length():
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/core/project/node_modules/dmg-builder/vendor/ds_store/store.py", line 202, in byte_length
    value = self.type.encode(self.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/core/project/node_modules/dmg-builder/vendor/ds_store/store.py", line 25, in encode
    return struct.pack(b'>IIII', point[0], point[1],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: required argument is not an integer
```

**Comment by coredev-uk** [comment]
Think this is an issue with my DMG configuration, closing
