### ISSUE TITLE
Can't build for Windows under a Windows environment using electron-builder `24.13.3`

### ISSUE THREAD

**Issue by ChxGuillaume** [electron-userland/electron-builder#8163]
* **Electron-Builder Version**: 24.13.3

* **Node Version**: v20.12.0

* **Electron Version**: 29.1.6
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

As seen in this [stackoverflow](https://stackoverflow.com/questions/77796243/issue-with-electron-application-build-on-windows-using-electron-builder), can't build application for Windows using a Windows environment.

Tested with the same dependencies on my work MacBook and had no issue building an executable for Windows.

```powershell
  ⨯ Cannot use 'in' operator to search for 'file' in undefined  failedTask=build stackTrace=TypeError: Cannot use 'in' operator to search for 'file' in undefined
    at doSign (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\codeSign\windowsCodeSign.ts:154:70)
    at sign (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\codeSign\windowsCodeSign.ts:60:7)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
From previous event:
    at processImmediate (node:internal/timers:478:21)
From previous event:
    at WinPackager.signApp (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\winPackager.ts:384:27)
    at WinPackager.doSignAfterPack (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\platformPackager.ts:336:32)
    at WinPackager.doPack (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\platformPackager.ts:321:7)
    at WinPackager.pack (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\platformPackager.ts:140:5)
    at Packager.doBuild (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\packager.ts:445:9)
    at executeFinally (C:\Users\<User>\WebstormProjects\<Project>\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\packager.ts:379:31)
    at Packager.build (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\packager.ts:340:12)
    at executeFinally (C:\Users\<User>\WebstormProjects\<Project>\node_modules\builder-util\src\promise.ts:12:14)
```

**Comment by beyondkmp** [comment]
Set the DEBUG environment variable to debug what electron-builder is doing:
```
set DEBUG=electron-builder
```

**Comment by ChxGuillaume** [comment]
Sadly, doesn't seem to add any details when it comes to my problem 😢 

```powershell
PS C:\Users\<User>\WebstormProjects\<Project>> set DEBUG=electron-builder
PS C:\Users\<User>\WebstormProjects\<Project>> npm run package:win       

> <Project>@1.5.1 package:win
> electron-builder --win --config

  • electron-builder  version=24.13.3 os=10.0.22631
  • loaded configuration  file=C:\Users\<User>\WebstormProjects\<Project>\electron-builder.yml
  • writing effective config  file=dist\builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=win32 arch=x64 electron=29.1.6 appOutDir=dist\win-unpacked
  ⨯ Cannot use 'in' operator to search for 'file' in undefined  failedTask=build stackTrace=TypeError: Cannot use 'in' operator to search for 'file' in undefined
    at doSign (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\codeSign\windowsCodeSign.ts:154:70)
    at sign (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\codeSign\windowsCodeSign.ts:60:7)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
From previous event:
    at processImmediate (node:internal/timers:478:21)
From previous event:
    at WinPackager.signApp (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\winPackager.ts:384:27)
    at WinPackager.doSignAfterPack (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\platformPackager.ts:336:32)
    at WinPackager.doPack (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\platformPackager.ts:321:7)
    at WinPackager.pack (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\platformPackager.ts:140:5)
    at Packager.doBuild (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\packager.ts:445:9)
    at executeFinally (C:\Users\<User>\WebstormProjects\<Project>\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\packager.ts:379:31)
    at Packager.build (C:\Users\<User>\WebstormProjects\<Project>\node_modules\app-builder-lib\src\packager.ts:340:12)
    at executeFinally (C:\Users\<User>\WebstormProjects\<Project>\node_modules\builder-util\src\promise.ts:12:14)
```

**Comment by ChxGuillaume** [comment]
Found out I had the same issue on my work MacBook, it was caused by the `sign: false` that changed behavior, it now tries to sign the executable, just removed it and fixed up my problem 👍
