### ISSUE TITLE
Electron won't start when offline or no internet connection

### ISSUE THREAD

**Issue by joyfementira** [electron-userland/electron-builder#819]
electron-builder version: 7.10.3

Building for Windows x32

Electron won't start when offline or no internet connection
Even the Electron API Demo won't start, only the installing window show and then it will stop.

**Comment by develar** [comment]
Please try nsis target or ensure that you handle Squirrel.Windows events.

**Comment by akashnimare** [comment]
BTW this is not a bug in electron-builder. @joyfementira let me know if you are still having this issue. You can solve this by using -

	  mainWindow.webContents.on('did-fail-load', (event= Event, errorCode= number, errorDescription= string, validatedURL= string, isMainFrame= boolean) => {
	  if (errorDescription === 'ERR_INTERNET_DISCONNECTED' || errorDescription === 'ERR_PROXY_CONNECTION_FAILED') {
		  console.log(errorDescription);
                 // your code..maybe show a error dialog here 
		}
	});

**Comment by joyfementira** [comment]
@akashnimare Okay, Thanks!. I'll try this one. :)

**Comment by probonopd** [comment]
Has this really been fixed? I am still occasionally running into [such issues](https://github.com/ramonreschke/clipboard-to-qrcode/issues/1#issuecomment-453845579):

```
Error: Error: net::ERR_INTERNET_DISCONNECTED
    at CancellationToken.createPromise (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/builder-util-runtime/src/CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:74:17)
    at GitHubProvider.httpRequest (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/providers/Provider.ts:29:26)
    at /run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:38:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:35:25)
    at /run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:345:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:335:32)
    at /run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:349:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at AppImageUpdater.checkForUpdates (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at App.<anonymous> (/run/firejail/appimage/.appimage-10249/resources/app.asar/main.js:131:17)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
```

Luckily, the fix seems to be easy: https://github.com/clipr/clipr/commit/eb82c638de7889f7a5ae911497f14c62cc467ee5 or https://github.com/standardnotes/desktop/commit/d8f71ba6b58ba5c4d4d2db42d04e895880f448e8

References:
* https://github.com/standardnotes/desktop/issues/168
* https://github.com/clipr/clipr/issues/1

Can this be fixed in the updater in a way that the individual application developer does not need to do anything to catch this?
