### ISSUE TITLE
notarize set false but still No authentication properties provided (e.g. appleId, appleApiKey, keychain)

### ISSUE THREAD

**Issue by oopses** [electron-userland/electron-builder#8208]
electron-builder [24.13.3](https://www.npmjs.com/package/electron-builder/v/24.13.3)

on macos when set option notarize  false，i want to notarize  on afterSign
https://www.electron.build/configuration/mac#NotarizeNotaryOptions

Error: No authentication properties provided (e.g. appleId, appleApiKey, keychain)
    at validateNotaryToolAuthorizationArgs (/Users/osxserver/jenkins/workspace/desktop/gdesk/node_modules/@electron/notarize/src/validate-args.ts:143:9)
    at authorizationArgs (/Users/osxserver/jenkins/workspace/desktop/gdesk/node_modules/@electron/notarize/src/notarytool.ts:16:51)
    at /Users/osxserver/jenkins/workspace/desktop/gdesk/node_modules/@electron/notarize/src/notarytool.ts:79:10
    at Generator.next (<anonymous>)
    at fulfilled (/Users/osxserver/jenkins/workspace/desktop/gdesk/node_modules/@electron/notarize/lib/notarytool.js:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Done in 170.52s.

**Comment by oopses** [comment]
> electron-builder [24.13.3](https://www.npmjs.com/package/electron-builder/v/24.13.3)
> 
> on macos when set option notarize false，i want to notarize on afterSign https://www.electron.build/configuration/mac#NotarizeNotaryOptions
> 
> Error: No authentication properties provided (e.g. appleId, appleApiKey, keychain) at validateNotaryToolAuthorizationArgs (/Users/osxserver/jenkins/workspace/desktop/gdesk/node_modules/@electron/notarize/src/validate-args.ts:143:9) at authorizationArgs (/Users/osxserver/jenkins/workspace/desktop/gdesk/node_modules/@electron/notarize/src/notarytool.ts:16:51) at /Users/osxserver/jenkins/workspace/desktop/gdesk/node_modules/@electron/notarize/src/notarytool.ts:79:10 at Generator.next () at fulfilled (/Users/osxserver/jenkins/workspace/desktop/gdesk/node_modules/@electron/notarize/lib/notarytool.js:28:58) at processTicksAndRejections (node:internal/process/task_queues:95:5) Done in 170.52s.

sorry， This is a problem with my local configuration and has been resolved.

**Comment by oopses** [comment]
sorry，This is a problem with my local configuration and has been resolved.
