### ISSUE TITLE
Problems caused by excessively large extraResources resources

### ISSUE THREAD

**Issue by zhEmail** [electron-userland/electron-builder#8225]
electron-builder  version=22.14.13 os=10.0.22631
vue2
window11
"electron": "^28.0.0",
"vue-cli-plugin-electron-builder": "~2.1.1",

![image](https://github.com/electron-userland/electron-builder/assets/84569709/0e01de0d-bda1-4e01-89b6-ecf2394fd378)

File: failed creating mmap of "D:\front\project\cipe-views\dist_electron\Cipe-1.0.0-ia32.nsis.7z"
Error in macro ia32_app_files on macroline 1
Error in macro compute_files_for_current_arch on macroline 11
Error in macro extractEmbeddedAppPackage on macroline 8
Error in macro installApplicationFiles on macroline 79
!include: error in script: "installSection.nsh" on line 63
Error in script "<stdin>" on line 190 -- aborting creation process

    at ChildProcess.<anonymous> (D:\front\project\cipe-views\node_modules\builder-util\src\util.ts:250:14)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.cp.emit (D:\front\project\cipe-views\node_modules\builder-util\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  exitCode: 1,
  alreadyLogged: false,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}

When I have a resource size of 1 G, it works fine

**Comment by mmaietta** [comment]
What size file are you trying to include? NSIS installers have an established max of 2gb.
