### ISSUE TITLE
SyntaxError: Unexpected token 'E', "Error: abo"... is not valid JSON

### ISSUE THREAD

**Issue by Nantris** [electron-userland/electron-builder#8259]
* **Electron-Builder Version**: 24.13.3

* **Node Version**: 20.12.0

* **Electron Version**: 28.3.x
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS DMG

After upgrading from Electron-Builder `23.6.0` to `24.13.3` we get this message. It's very cryptic and unclear where I might even begin to investigate.

Full error:

```
  ⨯ Unexpected token 'E', "Error: abo"... is not valid JSON  failedTask=build stackTrace=SyntaxError: Unexpected token 'E', "Error: abo"... is not valid JSON
SyntaxError: Unexpected token 'E', "Error: abo"... is not valid JSON
    at JSON.parse (<anonymous>)
    at /Users/me/Documents/MyProject/node_modules/@electron/notarize/src/notarytool.ts:79:25
    at Generator.next (<anonymous>)
    at fulfilled (/Users/me/Documents/MyProject/node_modules/@electron/notarize/lib/notarytool.js:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
From previous event:
    at processImmediate (node:internal/timers:478:21)
From previous event:
    at readDirectoryAndSign (/Users/me/Documents/MyProject/node_modules/app-builder-lib/src/macPackager.ts:478:29)
    at MacPackager.signApp (/Users/me/Documents/MyProject/node_modules/app-builder-lib/src/macPackager.ts:488:11)
    at MacPackager.doSignAfterPack (/Users/me/Documents/MyProject/node_modules/app-builder-lib/src/platformPackager.ts:336:21)
    at MacPackager.doPack (/Users/me/Documents/MyProject/node_modules/app-builder-lib/src/platformPackager.ts:321:7)
    at MacPackager.pack (/Users/me/Documents/MyProject/node_modules/app-builder-lib/src/macPackager.ts:198:9)
    at Packager.doBuild (/Users/me/Documents/MyProject/node_modules/app-builder-lib/src/packager.ts:445:9)
    at executeFinally (/Users/me/Documents/MyProject/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/me/Documents/MyProject/node_modules/app-builder-lib/src/packager.ts:379:31)
    at Packager.build (/Users/me/Documents/MyProject/node_modules/app-builder-lib/src/packager.ts:340:12)
    at executeFinally (/Users/me/Documents/MyProject/node_modules/builder-util/src/promise.ts:12:14)
```

**Comment by Drecula** [comment]
Aye, same error I am getting: https://github.com/electron-userland/electron-builder/issues/8258

**Comment by Nantris** [comment]
Thanks for spotting that @Drecula. I'll join you over there.

**Comment by stoefln** [comment]
Same here

**Comment by kangfenmao** [comment]
Fixed: update your package.json add resolutions version

```json
"resolutions": {
  "@electron/notarize": "2.3.2"
}
```
