### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by cybercussion** [electron-userland/electron-builder#826]
7.11.4

Electron 1.4.2

I have a project that previously went on a DVD with a lot of HTML5 content, videos etc.
I was hoping to move this into Electron and that works, but when I went to create installers for Windows / Mac using - build -mw it times out after a bit.

RangeError: Maximum call stack size exceeded
    at fs_extra_p_1.readdir.then.then.list (/usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:66:25)
From previous event:
    at walk (/usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:45:6)
    at fs_extra_p_1.lstat.then.stat (/usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:40:20)
    at /usr/local/lib/node_modules/electron-builder/node_modules/graceful-fs/polyfills.js:267:18
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at bluebird_1.Promise.map.name (/usr/local/lib/node_modules/electron-builder/src/asarUtil.ts:31:10)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback](timers.js:533:5)

**Comment by develar** [comment]
If fix will not help you, please send me your project.
