### ISSUE TITLE
auto-unpacked files are not copied

### ISSUE THREAD

**Issue by JoaoGabrielBrasil** [electron-userland/electron-builder#843]
package.json ->:
"devDependencies": {
    "electron": "^1.4.1",
    "electron-builder": "^7.14.1",
    "electron-prebuilt": "^1.4.1",
    "electron-rebuild": "^1.2.1",
    "node-gyp": "^3.4.0",
    "nslog": "^3.0.0",
    "rimraf": "^2.5.4"
  },

app/package.json ->:
"dependencies": {
    "configstore": "^2.1.0",
    "electron-debug": "^1.0.1",
    "electron-edge": "^6.5.2",
    "gulp-sass": "^2.1.0",
    "node-gyp": "^3.4.0",
    "nslog": ">= 2.0.0",
    "require-rebuild": "^1.2.8"
  },

I'm having trouble creating an installer.

I am using the electron-builder and the electron-edge and I'm having the following problem:

Packaging for ia32 platform win32 using electron 1.4.4 to dist \ win-ia32-unpacked

node_modules \ edge-cs is not packed into asar archive - contains executable code
node_modules \ electron-edge is not packed into asar archive - contains executable code

How to solve?

**Comment by virror** [comment]
This is just a warning and should not in itself stop things from working. I guessed you checked that the build actually did not work?

**Comment by JoaoGabrielBrasil** [comment]
@virror I tested the generated file and it does not work the proper shape of the electron-edge, you need the edge of the executable.

**Comment by develar** [comment]
👍 to @virror  It is just info, that this module is not packed into asar, but added directly to app resources (so, can be executed as program).

>  it does not work the proper shape of the electron-edge, you need the edge of the executable.

What error do you have in the runtime?

**Comment by JoaoGabrielBrasil** [comment]
Yes. It's in the runtime @develar.

Error: Não foi possível carregar arquivo ou assembly 'file:///C:\x\internal\electron-test\dist\win-ia32-unpacked\resources\app.asar\node_modules\edge-cs\lib\edge-cs.dll' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.
    at Error (native)
    at Object.exports.func (C:\x\internal\electron-test\dist\win-ia32-unpacked\resources\app.asar\node_modules\electron-edge\lib\edge.js:166:17)
    at new SalesController (file:///C:/x/internal/electron-test/dist/win-ia32-unpacked/resources/app.asar/src/js/modules/dashboard/sales.controller.js:35:26)
    at Object.invoke (file:///C:/x/internal/electron-test/dist/win-ia32-unpacked/resources/app.asar/vendor/angular/angular.js:4478:17)
    at extend.instance (file:///C:/x/internal/electron-test/dist/win-ia32-unpacked/resources/app.asar/vendor/angular/angular.js:9136:34)
    at nodeLinkFn (file:///C:/x/internal/electron-test/dist/win-ia32-unpacked/resources/app.asar/vendor/angular/angular.js:8248:36)
    at compositeLinkFn (file:///C:/x/internal/electron-test/dist/win-ia32-unpacked/resources/app.asar/vendor/angular/angular.js:7680:13)
    at publicLinkFn (file:///C:/x/internal/electron-test/dist/win-ia32-unpacked/resources/app.asar/vendor/angular/angular.js:7555:30)
    at file:///C:/x/internal/electron-test/dist/win-ia32-unpacked/…rces/app.asar/vendor/angular-ui-router/release/angular-ui-router.js:4026:9
    at invokeLinkFn (file:///C:/x/internal/electron-test/dist/win-ia32-unpacked/resources/app.asar/vendor/angular/angular.js:8789:9) <div data-ui-view="" data-autoscroll="false" ng-controller="CoreController" class="app-container ng-scope" data-ng-animate="1">

**Comment by develar** [comment]
Is it possible to send me sample project to reproduce and fix?

**Comment by JoaoGabrielBrasil** [comment]
Yes, @develar .

https://github.com/JoaoGabrielBrasil/test-electron-edge
