### ISSUE TITLE
[ERR_REQUIRE_ESM]: require() of ES Module ... is not supported

### ISSUE THREAD

**Issue by benbucksch** [electron-userland/electron-builder#8443]
* **Electron-Builder Version**: 24.13.3
* **Node Version**: 20.15.1
* **Electron Version**: 31.0.2
* **Target**: Linux
* **Package manager**: yarn

Project setup
===

* Electron app using electron-builder, which uses vite as build system. The build system is still almost identical to the template.
* TypeScript, with the `.ts` file extension
* ESM and `import` everywhere in our code. We do not use `require()` anywhere in our code base.
* Obviously, we're using various third-party npm libraries.

Reproduction
===

1. `npm create @quick-start/electron@latest`
  * Project name: electron-app
  * Select a framework: › svelte
  * Add TypeScript? Yes
  * Add Electron updater plugin? Yes
  * Enable Electron download mirror proxy? No
2. `cd electron-app; yarn install; yarn run dev` -- works
3. `yarn add electron-context-menu`, and `import` it to main.ts, as shown below.
4. Start the app using `yarn run dev`

Note: This is an ESM-only (!) third-party npm library, not built by me. The problem is not limited to this library. I have seen the same error multiple times in the past, with different libraries. It appears to be a generic problem with vite in combination with ESM-only modules.

Actual result
===

* Error, see below for console output

Expected result
===

(and actual result before adding `electron-context-menu`)
* App starts without errors

Code
===

Reduced code of the e2/src/main/index.ts file:
```typescript
import { BrowserWindow } from 'electron'
import contextMenu from 'electron-context-menu'; // <-- fails here

function createWindow(): void {
  contextMenu({});
  const mainWindow = new BrowserWindow({...})
  ...
}

createWindow();
...
```

You find the rest of the files, including the build config files, at https://github.com/mustang-im/mustang/tree/4fc959d/e2

Error
===
```
App threw an error during load
Error [ERR_REQUIRE_ESM]: require() of ES Module /e2/node_modules/electron-context-menu/index.js from /e2/out/main/index.js not supported.
Instead change the require of /e2/node_modules/electron-context-menu/index.js in /e2/out/main/index.js to a dynamic import() which is available in all CommonJS modules.
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Object.<anonymous> (/e2/out/main/index.js:37:21)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at loadApplicationPackage (/e2/node_modules/electron/dist/resources/default_app.asar/main.js:121:16)
    at Object.<anonymous> (/e2/node_modules/electron/dist/resources/default_app.asar/main.js:233:9)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at node:electron/js2c/browser_init:2:123937
    at node:electron/js2c/browser_init:2:124140
    at node:electron/js2c/browser_init:2:124144
    at f._load (node:electron/js2c/asar_bundle:2:13377)
A JavaScript error occurred in the main process
Uncaught Exception:
Error [ERR_REQUIRE_ESM]: require() of ES Module /e2/node_modules/electron-context-menu/index.js from /e2/out/main/index.js not supported.
Instead change the require of /e2/node_modules/electron-context-menu/index.js in /e2/out/main/index.js to a dynamic import() which is available in all CommonJS modules.
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Object.<anonymous> (/e2/out/main/index.js:37:21)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at loadApplicationPackage (/e2/node_modules/electron/dist/resources/default_app.asar/main.js:121:16)
    at Object.<anonymous> (/e2/node_modules/electron/dist/resources/default_app.asar/main.js:233:9)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at node:electron/js2c/browser_init:2:123937
    at node:electron/js2c/browser_init:2:124140
    at node:electron/js2c/browser_init:2:124144
    at f._load (node:electron/js2c/asar_bundle:2:13377)
```

Fix attempts
===

What I tried to fix it:
* Error msg suggests to "change the require of ...": We're not using `require()` at all. Very confusing and misleading error msg. I suspect vite converts the `import` into a `require()`?
* I've tried with and without `type: module` in e2/package.json (of the electron app) - same result. Does not fix it.
* Various SO answers are **not** applicable (already tried, see above) or suggest HACKs that don't address the underlying problem (see below)
  * [Error [ERR_REQUIRE_ESM]: require() of ES Module not supported](https://stackoverflow.com/questions/69081410/error-err-require-esm-require-of-es-module-not-supported)
  * [Error: require() of ES modules is not supported when importing node-fetch](https://stackoverflow.com/questions/69041454/error-require-of-es-modules-is-not-supported-when-importing-node-fetch)
  * [Error [ERR_REQUIRE_ESM]: require() of ES Module index.js not supported](https://stackoverflow.com/questions/70550799/error-err-require-esm-require-of-es-module-index-js-not-supported)
* I've filed an [SO question](https://stackoverflow.com/questions/78942085/err-require-esm-require-of-es-module-is-not-supported), and was told that it's a bug and to file a bug here.

Rejected solutions
===

What I consider a bad fix with other disadvantages and what I do not want to do:
* Use a dynamic `import()`, because completely unnecessary here.
* Rename our code files and change the file extensions
* Downgrade the third-party library and use an old, unmaintained version of it.

Possible solutions
===
What I could imagine might work:

* Change the build configuration of vite to emit `import`/ESM code instead of transpiling into `require()` code.
* Fix vite?

**Comment by mmaietta** [comment]
I think this issue is intrinsic of vite's compilation process and unrelated to electron-builder. Electron-builder simply copies compiled assets, it does not do any cross-compilation on its own.

**Comment by Wangbull** [comment]
Have you solved it? I also encountered

**Comment by benbucksch** [comment]
@mmaietta @Wangbull What I did not know nor even imagine was that electron-builder by default compiles to CommonJS, even if all my modules are ESM. As such,  the error message was highly misleading.

We fixed the error by changing the vite build config of electron-builder to compile to ESM. That fixed the problem.

That would also be my recommendation for a fix in electron-builder: Compile by default to ESM.

The underlying software stack changed a lot since the decision was made to default to CommonJS. ESM is now stable in Electron, which it has not been before. Old CommonJS code can still be compiled to ESM by vite, in the same way that currently,  ESM code is compiled to CommonJS, which causes problems.

**Comment by mmaietta** [comment]
>electron-builder by default compiles to CommonJS

electron-builder is not a compiler, it's a packager.

I've investigated having the monorepo support both cjs and esm, however, it's a massive refactor and dual compilation process before publishing. I'll look into again though

**Comment by benbucksch** [comment]
> electron-builder is not a compiler, it's a packager.

Sure.

What I mean is that `package.json` of the electron app should contain `"type": "module"` by default and the packager (vite, webpack) should be set up by default to create an ESM (not a CommonJS module) for the main, renderer and preload scripts.

FYI, I used [`electron-vite`](https://electron-vite.org/guide/) as scaffolding.

**Comment by paulm17** [comment]
@benbucksch I have this same issue as well.  Can you please confirm the configuration for the vite build config for electron-builder?

```
export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()],
  },
  preload: {
    plugins: [externalizeDepsPlugin()],
  },
  renderer: {
    build: {
      rollupOptions: {
        output: {
          esModule: true,
        },
      },
    },
  },
});
```

I still get the same error when I do this.  But when I add 

```
"type": "module",
```

to the package.json of the electron-vite directory.  The error goes away.

However, I then have another issue:

```
Error: Cannot find module '/Users/paul/development/src/github/[project]/apps/electron/out/preload/index.js'
    at Module._resolveFilename (VM56 loader:1232:15)
    at a._resolveFilename (VM112 renderer_init:2:2643)
    at Module._load (VM56 loader:1058:27)
    at c._load (VM69 node_init:2:16955)
    at s._load (VM112 renderer_init:2:30981)
    at VM112 renderer_init:2:33050
    at VM112 renderer_init:2:33519
    at ___electron_webpack_init__ (VM112 renderer_init:2:33523)
    at VM112 renderer_init:2:33646
    at BuiltinModule.compileForInternalLoader (VM7 realm:398:7)
```

**Comment by benbucksch** [comment]
For reference, @paulm17 wrote in an earlier version of the last message, among other things:

> I ... get the same error .... But when I add
> `"type": "module",`
> to the `package.json` of the electron-vite directory, the error goes away.

**Comment by paulm17** [comment]
@benbucksch Yes, the error did go away.  However, I could not track down the cause of the missing preload/index.js file.  Which when I digested your takeaway: 

> Instead, the project for our app was configured by scaffolding to compile to CommonJS

I threw out the baby with the bathwater and started again 😄.  However I think I have potentially regressed and will take a look at your repo for inspiration.

I appreciate you sharing it, many thanks!
