### ISSUE TITLE
Unable to build with custom path

### ISSUE THREAD

**Issue by BrianKnoblauch** [electron-userland/electron-builder#847]
- **Version**: 7.14.2 

- **Target**: MacOS

Legacy application.  Was on an ancient electron builder (3 series).  Is designed as an upgrade to an even older (more legacy) application.  All was well until MacOS Sierra came out.  DMG background did not show there, saw the fix in the trunk here, so decided to update.

Unfortunately, our build now blows up with:
TypeError: Cannot read property 'x' of undefined
    at DmgTarget.<anonymous> (/Users/user/app/node_modules/electron-builder/src/targets/dmg.ts:101:30)
    at next (native)
From previous event:
    at tsAwaiter (/Users/user/app/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at DmgTarget.build (/Users/user/app/node_modules/electron-builder/out/targets/dmg.js:20:16)
    at MacPackager.packageInDistributableFormat (/Users/user/app/node_modules/electron-builder/src/macPackager.ts:195:25)
    at nonMasPromise.doPack.then.then (/Users/user/app/node_modules/electron-builder/src/macPackager.ts:80:16)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback](timers.js:529:5)
From previous event:
    at MacPackager.<anonymous> (/Users/user/app/node_modules/electron-builder/src/macPackager.ts:79:10)
    at next (native)
From previous event:
    at tsAwaiter (/Users/user/app/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/Users/user/app/node_modules/electron-builder/out/builder.js:138:12)
    at Object.<anonymous> (/Users/user/app/node_modules/electron-builder/out/build-cli.js:23:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

If I remove our custom link path/use the current MacOS standard, the build will succeed, but then the installer link points at /Applications, whereas the legacy product that we need to upgrade is in a subdirectory of Applications...

**Comment by develar** [comment]
Sorry for late answer. Could you please post here you `build.dmg` configuration?

**Comment by BrianKnoblauch** [comment]
Here's the build.dmg configuration that worked before:

```
"dmg": {
      "contents": [
        {
          "x": 130,
          "y": 440
        },
        {
          "x": 410,
          "y": 440,
          "type": "link",
          "path": "/Applications/Service Spring Corporation"
        }
      ]
    }
```

Note that no path below "/Applications" that I've tried will work.  I first thought it might be sensitive to spaces, so experimented with other un-spaced names, but no change (not that it would help us anyways).  :-)

**Comment by develar** [comment]
Sorry that it was not fixed so long. Fix will be published soon.

Relates: #1054
