### ISSUE TITLE
Bintray configuration doesn't support bintray organizations

### ISSUE THREAD

**Issue by jimm1419** [electron-userland/electron-builder#848]
* **Version**: 7.14.2

* **Target**: macOS & Win NSIS

Currently BintrayClient does not support bintray accounts with organizations, using the same value `owner` for authentication and api URL's.

In the case of a bintray account with an organization, the api URL and user is different.

```
this.auth = apiKey == null ? null : `Basic ${ new Buffer(`${ owner }:${ apiKey }`).toString("base64") }`;
this.basePath = `/packages/${ this.owner }/${ this.repo }/${ this.packageName }`;
```

would probably be something like this:

```
this.auth = apiKey == null ? null : `Basic ${ new Buffer(`${ user }:${ apiKey }`).toString("base64") }`;
this.basePath = `/packages/${ this.owner }/${ this.repo }/${ this.packageName }`;
```

**Comment by develar** [comment]
👍 Please file PR.

**Comment by jimm1419** [comment]
Hi @develar .. I'll be happy to file the PR, but I'm having a problem getting the build to work.  The BintrayPublisher now successfully authenticates and uploads the file to bintray, but after I receive the follow error ... any ideas on what it could be??  It seems to be a problem with bluebird but I have not seen any bugs filed related to this.

```
[package] Building NSIS installer
[package] 
[package] Signing t-4b52-0-uninstaller.exe (certificate file "build/xxxx.p12")
[package] Signing XpressUpdateDev Setup 4.0.0-beta.exe (certificate file "build/xxxx.p12")
[package] Creating Bintray Publisher ��� user: xxxx, package: xxxxx, repository: generic, version: 4.0.0-beta
[package] 
[package] /tvx/workspace/client/pas-clients/pas-client-electron/node_modules/bluebird/js/release/generators.js:64
[package]         this._finallyPromise._fulfill();
[package]                             ^
[package] TypeError: Cannot read property '_fulfill' of undefined
[package]     at PromiseSpawn._cleanup (/tvx/workspace/client/pas-clients/pas-client-electron/node_modules/bluebird/js/release/generators.js:64:29)
[package]     at PromiseSpawn._continue (/tvx/workspace/client/pas-clients/pas-client-electron/node_modules/bluebird/js/release/generators.js:144:14)
[package]     at PromiseSpawn._promiseFulfilled (/tvx/workspace/client/pas-clients/pas-client-electron/node_modules/bluebird/js/release/generators.js:99:10)
[package]     at Promise._settlePromise (/tvx/workspace/client/pas-clients/pas-client-electron/node_modules/bluebird/js/release/promise.js:572:26)
[package]     at Promise._settlePromise0 (/tvx/workspace/client/pas-clients/pas-client-electron/node_modules/bluebird/js/release/promise.js:612:10)
[package]     at Promise._settlePromises (/tvx/workspace/client/pas-clients/pas-client-electron/node_modules/bluebird/js/release/promise.js:691:18)
[package]     at Async._drainQueue (/tvx/workspace/client/pas-clients/pas-client-electron/node_modules/bluebird/js/release/async.js:138:16)
[package]     at Async._drainQueues (/tvx/workspace/client/pas-clients/pas-client-electron/node_modules/bluebird/js/release/async.js:148:10)
[package]     at Immediate.Async.drainQueues [as _onImmediate] (/tvx/workspace/client/pas-clients/pas-client-electron/node_modules/bluebird/js/release/async.js:17:14)
[package]     at processImmediate [as _immediateCallback] (timers.js:383:17)
``

**Comment by develar** [comment]
@jimm1419 It was fixed today morning. Please update sources.

**Comment by jimm1419** [comment]
@develar Nice, thanks!
