### ISSUE TITLE
Appended space to ELECTRON_BUILDER_CACHE

### ISSUE THREAD

**Issue by ku4ndev** [electron-userland/electron-builder#8480]
* **Electron-Builder Version**: 25.0.5

* **Node Version**: 22.5.1

* **Electron Version**: 31.1.0
* **Electron Type (current, beta, nightly)**: Not using electron-updater

* **Target**: Windows, portable

Hello there,

I'm trying to set a local cache for electron-builder since I can't connect to GitHub in the network I work in. 
It seems that an unncessary space is added to the path specified in the environment variable ELECTRON_BUILDER_CACHE, as reported in this issue: https://github.com/electron-userland/electron-builder/issues/5327 .

I have also tried setting a local server and point ELECTRON_BUILDER_BINARIES_MIRROR to it, and the same issue occurs; there is an added space to the path.

Any workaround/fix for this issue? If more information is needed please ask and I will provide it ASAP.

Thank you beforehand.

**Comment by mmaietta** [comment]
Can you provide logs with env var `DEBUG=electron-builder`? Curious as to what's failing. There's a few mentions of `ELECTRON_BUILDER_CACHE` in the code, but nothing that should be causing an extra space AFAICT

**Comment by ku4ndev** [comment]
> Can you provide logs with env var `DEBUG=electron-builder`? Curious as to what's failing. There's a few mentions of `ELECTRON_BUILDER_CACHE` in the code, but nothing that should be causing an extra space AFAICT

Sure, here are the logs:
----
`• electron-builder  version=25.0.5 os=10.0.22631
  • loaded configuration  file=package.json ("build" field)
  • effective config  config=directories:
  output: dist-electron
  buildResources: build
appId: com.yourapp.id
files:
  - filter:
      - dist/**/*
      - main.js
      - package.json
      - preload.js
win:
  target: nsis
mac:
  target: dmg
linux:
  target: AppImage

  • description is missed in the package.json  appPackageFile=C:\my_project\project\myproject\package.json
  • author is missed in the package.json  appPackageFile=C:\my_project\project\myproject\package.json
  • writing effective config  file=dist-electron\builder-effective-config.yaml
  • spawning        command=C:\my_project\project\myproject\node_modules\app-builder-bin\win\x64\app-builder.exe node-dep-tree --flatten --dir C:\my_project\project\myproject
  • exited          command=app-builder.exe code=0 pid=6472 out=[{"name":"@angular/animations","version":"17.3.11","dir":"C:\\my_project\\project\\myproject\\node_modules\\@angular\\animations"},{"name":"@angular/cdk","version":"17.3.10","dir":"C:\\my_project\\project\\myproject\\node_modules\\@angular\\cdk"},{"name":"@angular/common","version":"17.3.11","dir":"C:\\my_project\\project\\myproject\\node_modules\\@angular\\common"},{"name":"@angular/compiler","version":"17.3.11","dir":"C:\\my_project\\project\\myproject\\node_modules\\@angular\\compiler"},{"name":"@angular/core","version":"17.3.11","dir":"C:\\my_project\\project\\myproject\\node_modules\\@angular\\core"},{"name":"@angular/forms","version":"17.3.11","dir":"C:\\my_project\\project\\myproject\\node_modules\\@angular\\forms"},{"name":"@angular/material","version":"17.3.10","dir":"C:\\my_project\\project\\myproject\\node_modules\\@angular\\material"},{"name":"@angular/platform-browser","version":"17.3.11","dir":"C:\\my_project\\project\\myproject\\node_modules\\@angular\\platform-browser"},{"name":"@angular/platform-browser-dynamic","version":"17.3.11","dir":"C:\\my_project\\project\\myproject\\node_modules\\@angular\\platform-browser-dynamic"},{"name":"@angular/router","version":"17.3.11","dir":"C:\\my_project\\project\\myproject\\node_modules\\@angular\\router"},{"name":"@material/animation","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\animation"},{"name":"@material/auto-init","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\auto-init"},{"name":"@material/banner","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\banner"},{"name":"@material/base","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\base"},{"name":"@material/button","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\button"},{"name":"@material/card","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\card"},{"name":"@material/checkbox","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\checkbox"},{"name":"@material/chips","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\chips"},{"name":"@material/circular-progress","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\circular-progress"},{"name":"@material/data-table","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\data-table"},{"name":"@material/density","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\density"},{"name":"@material/dialog","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\dialog"},{"name":"@material/dom","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\dom"},{"name":"@material/drawer","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\drawer"},{"name":"@material/elevation","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\elevation"},{"name":"@material/fab","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\fab"},{"name":"@material/feature-targeting","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\feature-targeting"},{"name":"@material/floating-label","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\floating-label"},{"name":"@material/focus-ring","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\focus-ring"},{"name":"@material/form-field","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\form-field"},{"name":"@material/icon-button","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\icon-button"},{"name":"@material/image-list","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\image-list"},{"name":"@material/layout-grid","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\layout-grid"},{"name":"@material/line-ripple","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\line-ripple"},{"name":"@material/linear-progress","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\linear-progress"},{"name":"@material/list","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\list"},{"name":"@material/menu","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\menu"},{"name":"@material/menu-surface","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\menu-surface"},{"name":"@material/notched-outline","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\notched-outline"},{"name":"@material/progress-indicator","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\progress-indicator"},{"name":"@material/radio","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\radio"},{"name":"@material/ripple","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\ripple"},{"name":"@material/rtl","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\rtl"},{"name":"@material/segmented-button","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\segmented-button"},{"name":"@material/select","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\select"},{"name":"@material/shape","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\shape"},{"name":"@material/slider","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\slider"},{"name":"@material/snackbar","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\snackbar"},{"name":"@material/switch","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\switch"},{"name":"@material/tab","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\tab"},{"name":"@material/tab-bar","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\tab-bar"},{"name":"@material/tab-indicator","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\tab-indicator"},{"name":"@material/tab-scroller","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\tab-scroller"},{"name":"@material/textfield","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\textfield"},{"name":"@material/theme","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\theme"},{"name":"@material/tokens","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\tokens"},{"name":"@material/tooltip","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\tooltip"},{"name":"@material/top-app-bar","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\top-app-bar"},{"name":"@material/touch-target","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\touch-target"},{"name":"@material/typography","version":"15.0.0-canary.7f224ddd4.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\@material\\typography"},{"name":"entities","version":"4.5.0","dir":"C:\\my_project\\project\\myproject\\node_modules\\entities"},{"name":"parse5","version":"7.1.2","dir":"C:\\my_project\\project\\myproject\\node_modules\\parse5","optional":true},{"name":"rxjs","version":"7.8.1","dir":"C:\\my_project\\project\\myproject\\node_modules\\rxjs"},{"name":"safevalues","version":"0.3.4","dir":"C:\\my_project\\project\\myproject\\node_modules\\safevalues"},{"name":"tslib","version":"2.6.3","dir":"C:\\my_project\\project\\myproject\\node_modules\\tslib"},{"name":"zone.js","version":"0.14.7","dir":"C:\\my_project\\project\\myproject\\node_modules\\zone.js"}]
  • executing @electron/rebuild  electronVersion=31.1.0 arch=x64 buildFromSource=false appDir=./
  • installing native dependencies  arch=x64
  • completed installing native dependencies
  • packaging       platform=win32 arch=x64 electron=31.1.0 appOutDir=dist-electron\win-unpacked
  • spawning        command=C:\my_project\project\myproject\node_modules\app-builder-bin\win\x64\app-builder.exe unpack-electron --configuration [{"platform":"win32","arch":"x64","version":"31.1.0"}] --output C:\my_project\project\myproject\dist-electron\win-unpacked --distMacOsAppName Electron.app
  • map async       taskCount=2
  • map async       taskCount=1
  • map async       taskCount=73
  • exited          command=app-builder.exe code=0 pid=5792
  • updating asar integrity executable resource  executablePath=C:\my_project\project\myproject\dist-electron\win-unpacked\my-project.exe
  • getPublishConfigsForUpdateInfo: no publishConfigs, detect using repository info
  • spawning        command=C:\my_project\project\myproject\node_modules\app-builder-bin\win\x64\app-builder.exe icon --format ico --root C:\my_project\project\myproject\build --root C:\my_project\project\myproject --out C:\my_project\project\myproject\dist-electron\.icon-ico
  • path doesn't exist  path=C:\my_project\project\myproject\build\icon.ico
  • path doesn't exist  path=C:\my_project\project\myproject\icon.ico
  • path doesn't exist  path=C:\my_project\project\myproject\build\icons
  • path doesn't exist  path=C:\my_project\project\myproject\icons
  • path doesn't exist  path=C:\my_project\project\myproject\build\icon.png
  • path doesn't exist  path=C:\my_project\project\myproject\icon.png
  • path doesn't exist  path=C:\my_project\project\myproject\build\icon.icns
  • path doesn't exist  path=C:\my_project\project\myproject\icon.icns
  • no icons found, using provided fallback sources
  • exited          command=app-builder.exe code=0 pid=13672 out={"icons":null,"isFallback":true}
  • default Electron icon is used  reason=application icon is not set
  • spawning        command=C:\my_project\project\myproject\node_modules\app-builder-bin\win\x64\app-builder.exe rcedit --args ["C:\\my_project\\project\\myproject\\dist-electron\\win-unpacked\\my-project.exe","--set-version-string","FileDescription","my-project","--set-version-string","ProductName","my-project","--set-version-string","LegalCopyright","Copyright © 2024 my-project","--set-file-version","0.0.0","--set-product-version","0.0.0.0","--set-version-string","InternalName","my-project","--set-version-string","OriginalFilename",""]
  ⨯ mkdir C:\electronCache \winCodeSign: The system cannot find the path specified.
github.com/develar/go-fs-util.EnsureDir
        /Users/runner/go/pkg/mod/github.com/develar/go-fs-util@v0.0.0-20190620175131-69a2d4542206/fs.go:75
github.com/develar/app-builder/pkg/download.CheckCache
        /Users/runner/work/app-builder/app-builder/pkg/download/artifactDownloader.go:150
github.com/develar/app-builder/pkg/download.DownloadArtifact
        /Users/runner/work/app-builder/app-builder/pkg/download/artifactDownloader.go:91
github.com/develar/app-builder/pkg/download.downloadFromGithub
        /Users/runner/work/app-builder/app-builder/pkg/download/tool.go:63
github.com/develar/app-builder/pkg/download.DownloadWinCodeSign
        /Users/runner/work/app-builder/app-builder/pkg/download/tool.go:58
github.com/develar/app-builder/pkg/rcedit.editResources
        /Users/runner/work/app-builder/app-builder/pkg/rcedit/rcedit.go:30
github.com/develar/app-builder/pkg/rcedit.ConfigureCommand.func1
        /Users/runner/work/app-builder/app-builder/pkg/rcedit/rcedit.go:25
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Users/runner/work/app-builder/app-builder/main.go:90
runtime.main
        /Users/runner/hostedtoolcache/go/1.21.12/arm64/src/runtime/proc.go:267
runtime.goexit
        /Users/runner/hostedtoolcache/go/1.21.12/arm64/src/runtime/asm_amd64.s:1650
  • exited          command=app-builder.exe code=1 pid=10256
  • Above command failed, retrying 3 more times
  • spawning        command=C:\my_project\project\myproject\node_modules\app-builder-bin\win\x64\app-builder.exe rcedit --args ["C:\\my_project\\project\\myproject\\dist-electron\\win-unpacked\\my-project.exe","--set-version-string","FileDescription","my-project","--set-version-string","ProductName","my-project","--set-version-string","LegalCopyright","Copyright © 2024 my-project","--set-file-version","0.0.0","--set-product-version","0.0.0.0","--set-version-string","InternalName","my-project","--set-version-string","OriginalFilename",""]
  ⨯ mkdir C:\electronCache \winCodeSign: The system cannot find the path specified.
github.com/develar/go-fs-util.EnsureDir
        /Users/runner/go/pkg/mod/github.com/develar/go-fs-util@v0.0.0-20190620175131-69a2d4542206/fs.go:75
github.com/develar/app-builder/pkg/download.CheckCache
        /Users/runner/work/app-builder/app-builder/pkg/download/artifactDownloader.go:150
github.com/develar/app-builder/pkg/download.DownloadArtifact
        /Users/runner/work/app-builder/app-builder/pkg/download/artifactDownloader.go:91
github.com/develar/app-builder/pkg/download.downloadFromGithub
        /Users/runner/work/app-builder/app-builder/pkg/download/tool.go:63
github.com/develar/app-builder/pkg/download.DownloadWinCodeSign
        /Users/runner/work/app-builder/app-builder/pkg/download/tool.go:58
github.com/develar/app-builder/pkg/rcedit.editResources
        /Users/runner/work/app-builder/app-builder/pkg/rcedit/rcedit.go:30
github.com/develar/app-builder/pkg/rcedit.ConfigureCommand.func1
        /Users/runner/work/app-builder/app-builder/pkg/rcedit/rcedit.go:25
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Users/runner/work/app-builder/app-builder/main.go:90
runtime.main
        /Users/runner/hostedtoolcache/go/1.21.12/arm64/src/runtime/proc.go:267
runtime.goexit
        /Users/runner/hostedtoolcache/go/1.21.12/arm64/src/runtime/asm_amd64.s:1650
  • exited          command=app-builder.exe code=1 pid=15412
  • Above command failed, retrying 2 more times
  • spawning        command=C:\my_project\project\myproject\node_modules\app-builder-bin\win\x64\app-builder.exe rcedit --args ["C:\\my_project\\project\\myproject\\dist-electron\\win-unpacked\\my-project.exe","--set-version-string","FileDescription","my-project","--set-version-string","ProductName","my-project","--set-version-string","LegalCopyright","Copyright © 2024 my-project","--set-file-version","0.0.0","--set-product-version","0.0.0.0","--set-version-string","InternalName","my-project","--set-version-string","OriginalFilename",""]
  ⨯ mkdir C:\electronCache \winCodeSign: The system cannot find the path specified.
github.com/develar/go-fs-util.EnsureDir
        /Users/runner/go/pkg/mod/github.com/develar/go-fs-util@v0.0.0-20190620175131-69a2d4542206/fs.go:75
github.com/develar/app-builder/pkg/download.CheckCache
        /Users/runner/work/app-builder/app-builder/pkg/download/artifactDownloader.go:150
github.com/develar/app-builder/pkg/download.DownloadArtifact
        /Users/runner/work/app-builder/app-builder/pkg/download/artifactDownloader.go:91
github.com/develar/app-builder/pkg/download.downloadFromGithub
        /Users/runner/work/app-builder/app-builder/pkg/download/tool.go:63
github.com/develar/app-builder/pkg/download.DownloadWinCodeSign
        /Users/runner/work/app-builder/app-builder/pkg/download/tool.go:58
github.com/develar/app-builder/pkg/rcedit.editResources
        /Users/runner/work/app-builder/app-builder/pkg/rcedit/rcedit.go:30
github.com/develar/app-builder/pkg/rcedit.ConfigureCommand.func1
        /Users/runner/work/app-builder/app-builder/pkg/rcedit/rcedit.go:25
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Users/runner/work/app-builder/app-builder/main.go:90
runtime.main
        /Users/runner/hostedtoolcache/go/1.21.12/arm64/src/runtime/proc.go:267
runtime.goexit
        /Users/runner/hostedtoolcache/go/1.21.12/arm64/src/runtime/asm_amd64.s:1650
  • exited          command=app-builder.exe code=1 pid=8160
  • Above command failed, retrying 1 more times
  • spawning        command=C:\my_project\project\myproject\node_modules\app-builder-bin\win\x64\app-builder.exe rcedit --args ["C:\\my_project\\project\\myproject\\dist-electron\\win-unpacked\\my-project.exe","--set-version-string","FileDescription","my-project","--set-version-string","ProductName","my-project","--set-version-string","LegalCopyright","Copyright © 2024 my-project","--set-file-version","0.0.0","--set-product-version","0.0.0.0","--set-version-string","InternalName","my-project","--set-version-string","OriginalFilename",""]
  ⨯ mkdir C:\electronCache \winCodeSign: The system cannot find the path specified.
github.com/develar/go-fs-util.EnsureDir
        /Users/runner/go/pkg/mod/github.com/develar/go-fs-util@v0.0.0-20190620175131-69a2d4542206/fs.go:75
github.com/develar/app-builder/pkg/download.CheckCache
        /Users/runner/work/app-builder/app-builder/pkg/download/artifactDownloader.go:150
github.com/develar/app-builder/pkg/download.DownloadArtifact
        /Users/runner/work/app-builder/app-builder/pkg/download/artifactDownloader.go:91
github.com/develar/app-builder/pkg/download.downloadFromGithub
        /Users/runner/work/app-builder/app-builder/pkg/download/tool.go:63
github.com/develar/app-builder/pkg/download.DownloadWinCodeSign
        /Users/runner/work/app-builder/app-builder/pkg/download/tool.go:58
github.com/develar/app-builder/pkg/rcedit.editResources
        /Users/runner/work/app-builder/app-builder/pkg/rcedit/rcedit.go:30
github.com/develar/app-builder/pkg/rcedit.ConfigureCommand.func1
        /Users/runner/work/app-builder/app-builder/pkg/rcedit/rcedit.go:25
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Users/runner/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Users/runner/work/app-builder/app-builder/main.go:90
runtime.main
        /Users/runner/hostedtoolcache/go/1.21.12/arm64/src/runtime/proc.go:267
runtime.goexit
        /Users/runner/hostedtoolcache/go/1.21.12/arm64/src/runtime/asm_amd64.s:1650
  • exited          command=app-builder.exe code=1 pid=14224
  • Above command failed, retrying 0 more times
  ⨯ C:\my_project\project\myproject\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: C:\my_project\project\myproject\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (C:\my_project\project\myproject\node_modules\builder-util\src\util.ts:255:14)
    at Object.onceWrapper (node:events:635:26)
    at ChildProcess.emit (node:events:520:28)
    at ChildProcess.cp.emit (C:\my_project\project\myproject\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
From previous event:
    at processImmediate (node:internal/timers:491:21)
From previous event:
    at WinPackager.signApp (C:\my_project\project\myproject\node_modules\app-builder-lib\src\winPackager.ts:388:27)
    at WinPackager.doSignAfterPack (C:\my_project\project\myproject\node_modules\app-builder-lib\src\platformPackager.ts:346:32)
    at WinPackager.doPack (C:\my_project\project\myproject\node_modules\app-builder-lib\src\platformPackager.ts:331:7)
    at WinPackager.pack (C:\my_project\project\myproject\node_modules\app-builder-lib\src\platformPackager.ts:138:5)
    at Packager.doBuild (C:\my_project\project\myproject\node_modules\app-builder-lib\src\packager.ts:458:9)
    at executeFinally (C:\my_project\project\myproject\node_modules\builder-util\src\promise.ts:12:14)
    at Packager.build (C:\my_project\project\myproject\node_modules\app-builder-lib\src\packager.ts:392:31)
    at executeFinally (C:\my_project\project\myproject\node_modules\builder-util\src\promise.ts:12:14)`
----

**Comment by ficristo** [comment]
It seems a bad interaction with npm\node.
Try a simple package.json with:
```json
{
    "scripts": {
        "test": "set foo=c:/foo && node test.js"
    }
}
```
where test.js contains only:
```js
console.log("_" + process.env.foo + "_");
```
This is what it is printed:
```
_c:/foo _
```

Then try to remove the space before &&:
```json
{
    "scripts": {
        "test": "set foo=c:/foo&& node test.js"
    }
}
```
and this is what is printed:
```
_c:/foo_
```

**Comment by ku4ndev** [comment]
Yes, that seems to be the case; although I've tried doing it with yarn and the same space is present, so probably on the node side? Anyway, seems that removing the space before && works fine; thanks!
