### ISSUE TITLE
electron-builder install-app-deps failed to rebuild re2

### ISSUE THREAD

**Issue by AndrewEQ** [electron-userland/electron-builder#8518]
* **Electron-Builder Version**:  ^25.0.5

* **Node Version**:  v22.1.0

* **Electron Version**: ^32.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: Mac: arm64

After I run 'npm I', the postinstall fails:

``` failedTask=installAppDeps stackTrace=Error: node-gyp failed to rebuild '/Users/.../node_modules/@metascraper/helpers/node_modules/re2' ```

This is the library: https://metascraper.js.org

If I remove the ```"postinstall": "electron-builder install-app-deps",``` from my package.json scripts I don't get the error ha.

What must I do to get past the error besides not running the postinstall?

Here's a bit more from the top of the error trace:
```
 • executing @electron/rebuild  electronVersion=32.1.2 arch=arm64 buildFromSource=false appDir=./
  • installing native dependencies  arch=arm64
  • preparing       moduleName=re2 arch=arm64
  ⨯ (node:13115) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
  CXX(target) Release/obj.target/re2/lib/addon.o
In file included from ../lib/addon.cc:1:
In file included from ../lib/./wrapped_re2.h:4:
../../../../../nan/nan.h:700:39: error: no member named 'IdleNotificationDeadline' in 'v8::Isolate'
  700 |     return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../../../../../nan/nan.h:2560:8: error: no member named 'SetAccessor' in 'v8::ObjectTemplate'
 2560 |   tpl->SetAccessor(
      |   ~~~~~^
../../../../../nan/nan.h:2608:8: error: no member named 'SetAccessor' in 'v8::ObjectTemplate'
 2608 |   tpl->SetAccessor(
      |   ~~~~~^
../../../../../nan/nan.h:2654:15: error: no member named 'SetAccessor' in 'v8::Object'
 2654 |   return obj->SetAccessor(
      |          ~~~~~^
../../../../../nan/nan.h:2730:19: error: no matching constructor for initialization of 'v8::NamedPropertyHandlerConfiguration'
 2730 |   tpl->SetHandler(v8::NamedPropertyHandlerConfiguration(
      |                   ^
 2731 |       getter_, setter_, query_, deleter_, enumerator_, obj));
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/aq/.electron-gyp/32.1.2/include/node/v8-template.h:772:12: note: candidate constructor not viable: no known conversion from 'imp::NativePropertyGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'NamedPropertyGetterCallback' (aka 'Intercepted (*)(Local<Name>, const PropertyCallbackInfo<Value> &)') for 1st argument
  772 |   explicit NamedPropertyHandlerConfiguration(
      |            ^
  773 |       NamedPropertyGetterCallback getter,
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/aq/.electron-gyp/32.1.2/include/node/v8-template.h:790:3: note: candidate constructor not viable: no known conversion from 'imp::NativePropertyGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'NamedPropertyGetterCallback' (aka 'Intercepted (*)(Local<Name>, const PropertyCallbackInfo<Value> &)') for 1st argument
  790 |   NamedPropertyHandlerConfiguration(
      |   ^
  791 |       NamedPropertyGetterCallback getter,          //

```

**Comment by devDoubleH** [comment]
I am also having this issue any updates ?

**Comment by mmaietta** [comment]
Best guess is that you need to upgrade your node-gyp version or force the version in your package.json. Electron-builder uses the official electron/rebuild package for building native dependencies, so I think it has a node-gyp version pinned in it that you may need to override.
Another test you could give a shot is by downgrading to node 20 and see if that works

**Comment by AndrewEQ** [comment]
Ah yeah @mmaietta, I saw the node version in the latest Electron: https://www.electronjs.org/blog/electron-32-0
Downgraded to 20.16.0 and now it works! 🥇

**Comment by AndrewEQ** [comment]
@mmaietta oh wait, it worked because I downgraded my electron-builder to 24.13.3 as well, still gives an error with 25.0.5

**Comment by t3rrey** [comment]
Im building my app in a github action when  i run `npm i` it hangings on the `electron-builder install-app-deps` , it will just time out. 

"electron": "32.1.2",
"electron-builder": "25.0.5",
   


```
2024-09-23T00:10:16.8885912Z ##[group]Run actions/setup-node@v4
2024-09-23T00:10:16.8886448Z with:
2024-09-23T00:10:16.8886803Z   node-version: 20.16.0
2024-09-23T00:10:16.8887218Z   always-auth: false
2024-09-23T00:10:16.8887621Z   check-latest: false
2024-09-23T00:10:16.8888214Z   token: ***
2024-09-23T00:10:16.8888571Z ##[endgroup]
2024-09-23T00:10:17.6721886Z Attempting to download 20.16.0...
2024-09-23T00:10:18.1429291Z Acquiring 20.16.0 - x64 from https://github.com/actions/node-versions/releases/download/20.16.0-10080284600/node-20.16.0-win32-x64.7z
2024-09-23T00:10:18.9646753Z Extracting ...
2024-09-23T00:10:20.6902149Z Adding to the cache ...
2024-09-23T00:10:26.0676906Z ##[group]Environment details
2024-09-23T00:10:28.5532780Z node: v20.16.0
2024-09-23T00:10:28.5535108Z npm: 10.8.1
2024-09-23T00:10:28.5536015Z yarn: 1.22.22
2024-09-23T00:10:28.5537468Z ##[endgroup]
2024-09-23T00:10:28.5817028Z ##[group]Run npm i
2024-09-23T00:10:28.5817786Z npm i
2024-09-23T00:10:28.5869878Z shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
2024-09-23T00:10:28.5870921Z ##[endgroup]
2024-09-23T00:10:36.7358904Z npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
2024-09-23T00:10:38.7138950Z npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
2024-09-23T00:10:43.1174839Z npm warn deprecated @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.
2024-09-23T00:10:43.8125538Z npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
2024-09-23T00:10:44.2322100Z npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
2024-09-23T00:10:44.2370589Z npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
2024-09-23T00:10:44.2538424Z npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
2024-09-23T00:10:44.5152054Z npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
2024-09-23T00:11:18.0873469Z 
2024-09-23T00:11:18.0877815Z > recorder-app@2.0.60 postinstall
2024-09-23T00:11:18.0879326Z > electron-builder install-app-deps
```

**Comment by mmaietta** [comment]
@AndrewEQ and @t3rrey can you try with `DEBUG=electron-rebuild` env var set? electron-builder v25.x uses the official electron-upstream package for handling native dependencies, so I'm curious as to where it's failing.

Note, another thing you can test with 25.x is setting config property `nativeRebuilder: legacy` to leverage the electron-builder v24.x native rebuilder.
https://www.electron.build/configuration#nativerebuilder

**Comment by t3rrey** [comment]
This is what I get when I run using env debug with both version nativerebuilder
```
Run npm i
npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

> recorder-app@2.0.62 postinstall
> electron-builder install-app-deps

  ⨯ require(...) is not a function  failedTask=installAppDeps stackTrace=TypeError: require(...) is not a function
    at loadEnv (/home/runner/work/***/***/node_modules/read-config-file/src/main.ts:140:27)
npm error code 1
```


```
require('dotenv').config()
module.exports = {
  nativeRebuilder: 'legacy',
  appId: '',
  productName: '',
  directories: {
    buildResources: 'build'
  },
  files: [
    '!**/.vscode/*',
    '!src/*',
    '!electron.vite.config.{js,ts,mjs,cjs}',
    '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}',
    '!{.env,.env.*,.npmrc,pnpm-lock.yaml}',
    '!{tsconfig.json,tsconfig.node.json,tsconfig.web.json}'
  ],
  asarUnpack: ['resources/**'],
  win: {
    executableName: '',
    icon: 'icon.ico'
  },
  nsis: {
    artifactName: '${name}-${version}-setup.${ext}',
    shortcutName: '${productName}',
    uninstallDisplayName: '${productName}',
    createDesktopShortcut: 'always'
  },
  mac: {
    icon: 'icon.icns',
    forceCodeSigning: true,
    cscLink: process.env.MAC_CSC_CERT,
    cscKeyPassword: process.env.MAC_CSC_PASSWORD,
    extendInfo: {
      NSCameraUsageDescription: "Application requests access to the device's camera.",
      NSMicrophoneUsageDescription: "Application requests access to the device's microphone.",
      NSDocumentsFolderUsageDescription:
        "Application requests access to the user's Documents folder.",
      NSDownloadsFolderUsageDescription:
        "Application requests access to the user's Downloads folder."
    },
    notarize: false,
    target: ['dmg']
  },
  dmg: {
    artifactName: '${name}-${version}.${ext}'
  },
  linux: {
    icon: 'icon.png',
    target: ['AppImage', 'deb'],
    maintainer: '****',
    category: 'Utility'
  },
  appImage: {
    artifactName: '${name}-${version}.${ext}'
  },
  npmRebuild: false,
  publish: {
    provider: 'generic',
    url: 'https://example.com/auto-updates'
  },
  electronDownload: {
    mirror: 'https://npmmirror.com/mirrors/electron/'
  }
}
```

**Comment by AndrewEQ** [comment]
@mmaietta ```nativeRebuilder: legacy``` outputs a lot of "unresolved deps  unresolved=..." and ends with:
```
 • map async       taskCount=735
 • no native dependencies  
```
can't remember if this is normal but at least its not breaking? 😊

With ```export DEBUG=electron-rebuild``` set and legacy not set, I briefly saw the same output as legacy, then a whole bunch of "exploring" logs, followed by a "identified prod deps: Set(0) {, the items that have a red X are: 
```

  '@jimp/jpeg': true,
  '@jimp/png': true,

  ⨯   '@jimp/tiff': true,
  'metascraper-url': true,
  bytes: true,
```
and
```
  'has-unicode': true,
  'wide
  ⨯ -align': true,
  'bare-events': true,
```

Followed by more scanning logs, then:
```

  • preparing       moduleName=re2 arch=arm64
  ⨯ 2024-09-23T08:58:35.874Z electron-rebuild checking re2 against []

  ⨯ 2024-09-23T08:58:35.879Z electron-rebuild rebuilding re2 with args [
  'node',
  'node-gyp',
  'rebuild',
  '--runtime=electron',
  '--target=32.1.0',
  '--arch=arm64',
  '--dist-url=https://www.electronjs.org/headers',
  '--build-from-source',
  '--verbose'
]

  ⨯ gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://www.electronjs.org/headers
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp verb find Python - executing "/Applications/Xcode.app/Contents/Developer/usr/bin/python3" to get version
gyp verb find Python - version is "3.9.6"
gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp verb get node dir compiling against --target node version: 32.1.0
gyp verb command install [ '32.1.0' ]
gyp verb download using dist-url https://www.electronjs.org/headers
gyp verb install input version string "32.1.0"
gyp verb install installing version: 32.1.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 11
gyp verb needs "installVersion" 11
gyp verb install version is good
gyp verb get node dir target node version installed: 32.1.0
gyp verb build dir attempting to create "build" dir: /Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/re2/build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb python symlink creating symlink to "/Applications/Xcode.app/Contents/Developer/usr/bin/python3" at "/Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/re2/build/node_gyp_bins/python3"
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/re2/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/re2/config.gypi
gyp verb common.gypi checking for gypi file: /Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/re2/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/@electron/rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/re2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/@electron/rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aq/.electron-gyp/32.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/aq/.electron-gyp/32.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/@electron/rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/aq/.electron-gyp/32.1.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/re2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm64
gyp verb node dev dir /Users/aq/.electron-gyp/32.1.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp verb bin symlinks adding symlinks (such as Python), at "/Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/re2/build/node_gyp_bins", to PATH
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ -o Release/obj.target/re2/lib/addon.o ../lib/addon.cc '-DNODE_GYP_MODULE_NAME=re2' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DELECTRON_ENSURE_CONFIG_GYPI' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DUSING_ELECTRON_CONFIG_GYPI' '-DV8_COMPRESS_POINTERS' '-DV8_COMPRESS_POINTERS_IN_ISOLATE_CAGE' '-DV8_31BIT_SMIS_ON_64BIT_ARCH' '-DV8_ENABLE_SANDBOX' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DOPENSSL_NO_ASM' '-DNDEBUG' '-DNOMINMAX' '-DBUILDING_NODE_EXTENSION' -I/Users/aq/.electron-gyp/32.1.0/include/node -I/Users/aq/.electron-gyp/32.1.0/src -I/Users/aq/.electron-gyp/32.1.0/deps/openssl/config -I/Users/aq/.electron-gyp/32.1.0/deps/openssl/openssl/include -I/Users/aq/.electron-gyp/32.1.0/deps/uv/include -I/Users/aq/.electron-gyp/32.1.0/deps/zlib -I/Users/aq/.electron-gyp/32.1.0/deps/v8/include -I../../nan -I../vendor/re2 -I../vendor/abseil-cpp  -O3 -gdwarf-2 -mmacosx-version-min=10.15 -arch arm64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++2a -stdlib=libc++ -fno-rtti -fno-exceptions -fno-strict-aliasing -std=c++2a -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -O3 -g -MMD -MF ./Release/.deps/Release/obj.target/re2/lib/addon.o.d.raw   -c
In file included from ../lib/addon.cc:1:
In file included from ../lib/./wrapped_re2.h:4:
../../nan/nan.h:700:39: error: no member named 'IdleNotificationDeadline' in 'v8::Isolate'
  700 |     return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../../nan/nan.h:2560:8: error: no member named 'SetAccessor' in 'v8::ObjectTemplate'
 2560 |   tpl->SetAccessor(
      |   ~~~~~^
../../nan/nan.h:2608:8: error: no member named 'SetAccessor' in 'v8::ObjectTemplate'
 2608 |   tpl->SetAccessor(
      |   ~~~~~^
../../nan/nan.h:2654:15: error: no member named 'SetAccessor' in 'v8::Object'
 2654 |   return obj->SetAccessor(
      |          ~~~~~^
../../nan/nan.h:2730:19: error: no matching constructor for initialization of 'v8::NamedPropertyHandlerConfiguration'
 2730 |   tpl->SetHandler(v8::NamedPropertyHandlerConfiguration(
      |                   ^
 2731 |       getter_, setter_, query_, deleter_, enumerator_, obj));
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/aq/.electron-gyp/32.1.0/include/node/v8-template.h:772:12: note: candidate constructor not viable: no known conversion from 'imp::NativePropertyGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'NamedPropertyGetterCallback' (aka 'Intercepted (*)(Local<Name>, const PropertyCallbackInfo<Value> &)') for 1st argument
  772 |   explicit NamedPropertyHandlerConfiguration(
      |            ^
  773 |       NamedPropertyGetterCallback getter,
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/aq/.electron-gyp/32.1.0/include/node/v8-template.h:790:3: note: candidate constructor not viable: no known conversion from 'imp::NativePropertyGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'NamedPropertyGetterCallback' (aka 'Intercepted (*)(Local<Name>, const PropertyCallbackInfo<Value> &)') for 1st argument
  790 |   NamedPropertyHandlerConfiguration(
      |   ^
  791 |       NamedPropertyGetterCallback getter,          //
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/aq/.electron-gyp/32.1.0/include/node/v8-template.h:752:3: note: candidate constructor not viable: requires at least 7 arguments, but 6 were provided
  752 |   NamedPropertyHandlerConfiguration(
      |   ^
  753 |       NamedPropertyGetterCallback getter,          //
      |       ~~~~~~~~~~~~~~~~~~~~~
  ⨯ node-gyp failed to rebuild '/Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/re2'  failedTask=installAppDeps stackTrace=Error: node-gyp failed to rebuild '/Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/re2'
    at ChildProcess.<anonymous> (/Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:118:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error code 1
npm error path /Users/aq/www/rbt/netclicker2/netclicker2/desktop/netclicker_tv_vite
npm error command failed
npm error command sh -c electron-builder install-app-deps
```

**Comment by AndrewEQ** [comment]
@mmaietta though I'm using the legacy builder, I get a node_module missing error on launching the app:
```
Cannot find module 'strip-ansi'...
```

I'm currently thinking of finding an alternative to the module I use that uses re2 lol

**Comment by dancarasco** [comment]
> @mmaietta though I'm using the legacy builder, I get a node_module missing error on launching the app:
> 
> ```
> Cannot find module 'strip-ansi'...
> ```
> 
> I'm currently thinking of finding an alternative to the module I use that uses re2 lol

Unsure if related to this specific problem, but when building on a mac (m2) for both win+mac (electron-builder --mac --win) electron-builder rebuilds native deps for mac, but when packaging for win, it doesn't run the native rebuild again, resulting in a dependency platform mismatch (in my case sqlite.node).

The reason I mention this here is that it only occurs on 25.05., and I receive the same error @AndrewEQ received when launching the app (cannot find module.) This does not occur on 24.13.3, and the native rebuild (correctly) executes for each platform.

If unrelated I will raise as a separate issue but thought it was worth a mention.

> @mmaietta though I'm using the legacy builder, I get a node_module missing error on launching the app:
> 
> ```
> Cannot find module 'strip-ansi'...
> ```
> 
> I'm currently thinking of finding an alternative to the module I use that uses re2 lol

Unsure if related as I don't have a postinstall hook, but electron-builder 25.0.5 is also giving me the same "Cannot find module" when building with dependencies that require native rebuilds. Does not occur with 24.13.3. I've raised a separate issue for this https://github.com/electron-userland/electron-builder/issues/8528

**Comment by dancarasco** [comment]
> @mmaietta though I'm using the legacy builder, I get a node_module missing error on launching the app:
> 
> ```
> Cannot find module 'strip-ansi'...
> ```
> 
> I'm currently thinking of finding an alternative to the module I use that uses re2 lol

Unsure if related as I don't have a postinstall hook, but electron-builder 25.0.5 is also giving me the same "Cannot find module" when building with dependencies that require native rebuilds. Does not occur with 24.13.3. I've raised a separate issue for this https://github.com/electron-userland/electron-builder/issues/8528

**Comment by AndrewEQ** [comment]
Just an update ...so I ended up using another module / manually doing more specific things making the app a little leaner and rebuild just works now :)

**Comment by leey0818** [comment]
Since the re2 module provides pre-built binaries, you may kindly consider trying the following:

- Please use electron-builder@25.1.7 or later. (#8537)
- Alternatively, use electron-builder@25.1.0 or later with the nativeRebuilder=legacy option. (#8450)

**Comment by mmaietta** [comment]
Closing per ☝️
