### ISSUE TITLE
hdiutil error when building for mac

### ISSUE THREAD

**Issue by stefanedberg** [electron-userland/electron-builder#854]
hdiutil outputs an error when building my Electron project. The app is generated and seem to work (tested on two Mac's with different macOS versions). If I run the hdiutil command manually it doesn't output anything.

build platform: macOS Sierra 10.12.1
target platform: macOS
node: v7.0.0 (also tested on v6.9.1)
electron: v1.4.4
electron-builder: 7.14.2

```
$ DEBUG=electron-builder node_modules/.bin/build -m
Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform darwin x64 using electron 1.4.4 to dist/mac

  electron-builder Spawning /Users/stefan/Documents/Development/Electron/electron-project/node_modules/7zip-bin-mac/7za x -bd /Users/stefan/.electron/electron-v1.4.4-darwin-x64.zip -o/Users/stefan/Documents/Development/Electron/electron-project/dist/mac +0ms

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 42004724 bytes (41 MiB)

Extracting archive: /Users/stefan/.electron/electron-v1.4.4-darwin-x64.zip
--
Path = /Users/stefan/.electron/electron-v1.4.4-darwin-x64.zip
Type = zip
Physical Size = 42004724

Everything is Ok

Folders: 143
Files: 180
Size:       111898036
Compressed: 42004724
  electron-builder /Users/stefan/Documents/Development/Electron/electron-project/node_modules/7zip-bin-mac/7za (2024) exited with code 0 +2s
  electron-builder Executing security find-identity -v +15s
  electron-builder Executing security find-identity -v -p codesigning +15ms
  1) 3674B13AC4B3F29509C7D08D9FBE27C735583EEB "Company name #1 AB"
  2) F96DBB184A79B1BB61B5D652C029E59616D2771D "Company name #2 AB"
     2 valid identities found

  1) 7622AC77D96864FE8F6306129A143C16C33194DC "com.apple.idms.appleid.prd.4969564e66456a5a4a785a765074415978646b526d513d3d"
  2) 3674B13AC4B3F29509C7D08D9FBE27C735583EEB "Company name #1 AB"
  3) F96DBB184A79B1BB61B5D652C029E59616D2771D "Company name #2 AB"
     3 valid identities found

Signing app (identity: Company name #1 AB)

Creating DMG
Creating MacOS zip
  electron-builder Spawning /Users/stefan/Documents/Development/Electron/electron-project/node_modules/7zip-bin-mac/7za a -bd -mm=Deflate /Users/stefan/Documents/Development/Electron/electron-project/dist/mac/Synchronize-0.1.0-mac.zip Synchronize.app +23s
  electron-builder Executing hdiutil create -srcfolder /var/folders/4x/dqxg9wkj1w38n7wz143kjqhm0000gn/T/electron-builder-jpnSeC/t-7e7-0-dmg/.background -srcfolder /Users/stefan/Documents/Development/Electron/electron-project/dist/mac/Synchronize.app -volname Synchronize 0.1.0 -anyowners -nospotlight -quiet -fs HFS+ -fsargs -c c=64,a=16,e=16 -format UDRW /var/folders/4x/dqxg9wkj1w38n7wz143kjqhm0000gn/T/electron-builder-jpnSeC/t-7e7-0-dmg/temp.dmg +15ms

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive:
151 folders, 185 files, 143023290 bytes (137 MiB)

Creating archive: /Users/stefan/Documents/Development/Electron/electron-project/dist/mac/Synchronize-0.1.0-mac.zip

Items to compress: 336

Error: Exit code: 1. Command failed: hdiutil create -srcfolder /var/folders/4x/dqxg9wkj1w38n7wz143kjqhm0000gn/T/electron-builder-jpnSeC/t-7e7-0-dmg/.background -srcfolder /Users/stefan/Documents/Development/Electron/electron-project/dist/mac/Synchronize.app -volname Synchronize 0.1.0 -anyowners -nospotlight -quiet -fs HFS+ -fsargs -c c=64,a=16,e=16 -format UDRW /var/folders/4x/dqxg9wkj1w38n7wz143kjqhm0000gn/T/electron-builder-jpnSeC/t-7e7-0-dmg/temp.dmg

    at /Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/util/util.ts:102:16
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at Object.exec (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/util/util.ts:80:3)
    at DmgTarget.<anonymous> (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/targets/dmg.ts:49:15)
    at Generator.next (<anonymous>)
    at /Users/stefan/Documents/Development/Electron/electron-project/node_modules/fs-extra-tf/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/stefan/Documents/Development/Electron/electron-project/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/stefan/Documents/Development/Electron/electron-project/node_modules/fs-extra-tf/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:111:15)
From previous event:
    at tsAwaiter (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at DmgTarget.build (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/out/targets/dmg.js:20:16)
    at MacPackager.packageInDistributableFormat (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/macPackager.ts:195:25)
    at nonMasPromise.doPack.then.then (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/macPackager.ts:80:16)
From previous event:
    at MacPackager.<anonymous> (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/macPackager.ts:79:10)
    at Generator.next (<anonymous>)
From previous event:
    at tsAwaiter (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/out/builder.js:138:12)
    at Object.<anonymous> (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/out/build-cli.js:23:11)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

Files read from disk: 185
Archive size: 47025365 bytes (45 MiB)
Everything is Ok
```

```
{
  "name": "Synchronize",
  "description": "<description>",
  "version": "0.1.0",
  "author": "<author>",
  "main": "electron.js",
  "build": {
    "appId": "com.visitortoolbox.synchronize",
    "mac": {
      "category": "public.app-category.productivity"
    },
    "win": {
      "iconUrl": "https://vtfiles.blob.core.windows.net/app/com.visitortooblox.synchronize.ico"
    }
  }
  },
  "scripts": {
    ...
    "pack": "build --dir",
    "dist": "build --mac"
  },
  "dependencies": {
    ...
  },
  "devDependencies": {
   ...
  }
}
```

**Comment by develar** [comment]
> tested on two Mac's with different macOS versions

An error occurred on both?

**Comment by stefanedberg** [comment]
Sorry @develar , I wasn't really clear. The Synchronize.app works fine on both macOS versions. But I guess thats not relevant for my problem with hdiutils.

**Comment by develar** [comment]
I don't see any clear error from `hdiutil` If you can — please try to modify source code of installed electron-builder node module to add flag `-debug` to command. If cannot — I am going to automatically add this flag, but currently I am busy and maybe it will be implemented only next week.

**Comment by stefanedberg** [comment]
@develar I added the -debug flag.

Error: Exit code: undefined. stderr maxBuffer exceeded

Output:
http://pastebin.com/KCqe7fPG

**Comment by stefanedberg** [comment]
I got it to work once just now. No error and a fully functional dmg was generated. At first I thought it had something to do with me changing the app/package.json file, but it doesn't seem like that was the problem. Same error now.

@develar

**Comment by develar** [comment]
Error is not reported because we pass `-quiet` flag by mistake. Fixed, please try next version (will be published today/tomorrow.

**Comment by develar** [comment]
Please try 7.15.0

**Comment by develar** [comment]
Strange, thanks for confirmation. Probably spawn vs exec makes the deal :)

**Comment by stefanedberg** [comment]
I though the problem was resolved but it seems like it appears after I have built the application once. hdiutil cannot unmount the dmg even though I have manually unmounted and deleted the old one.

´´´
detachTempimageFile: synchronous unmount /dev/disk2s1 returned 49168
retrying unmount (#1)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/Sync 0.1.5 (/dev/disk2s1) returned 49168
retrying unmount (#2)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/Sync 0.1.5 (/dev/disk2s1) returned 49168
retrying unmount (#3)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/Sync 0.1.5 (/dev/disk2s1) returned 49168
2016-11-01 10:29:09.887 diskimages-helper[3521:121671] -processKernelRequest: flush received
2016-11-01 10:29:09.911 diskimages-helper[3521:121599] *useEffectiveIDs**** euid/egid changed to 501,20 (uid/gid is 501,20)
DIHLDiskImageCreate() returned 49168
2016-11-01 10:29:10.915 diskimages-helper[3521:121592] *** -[NSMachPort handlePortMessage:]: dropping incoming DO message because the connection is invalid
hdiutil: create: returning 49168
hdiutil: create failed - Resursen upptagen
´´´

hdiutil eject -force /dev/disk2s1 just returns hdiutil: eject failed - Not found.

@develar

**Comment by develar** [comment]
Could you please attach full build log?

**Comment by stefanedberg** [comment]
Sorry about that, here it is.

If I run hdiutil command manually:

```
$ hdiutil create -srcfolder /var/folders/4x/dqxg9wkj1w38n7wz143kjqhm0000gn/T/electron-builder-3ELKq2/t-1442-0-dmg/.background -srcfolder /Users/stefan/Documents/Development/Electron/electron-project/dist/mac/Sync.app -volname Sync 0.1.5 -anyowners -nospotlight -fs HFS+ -fsargs -c c=64,a=16,e=16 -format UDRW -verbose /var/folders/4x/dqxg9wkj1w38n7wz143kjqhm0000gn/T/electron-builder-3ELKq2/t-1442-0-dmg/temp.dmg +12ms
hdiutil: create: Only one image can be created at a time.
hdiutil: create: returning 0
Usage:	hdiutil create <sizespec> [options] <imagepath>
	hdiutil create -help
```

Build log:

```
> DEBUG='electron-builder' CSC_NAME='Company name #1 AB' build -m --x64 --ia32

  electron-builder Spawning /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js rebuild --production --cache-min 999999999 --build-from-source +0ms
Rebuilding app dependencies for arch x64 to /Users/stefan/Documents/Development/Electron/electron-project/app

  electron-builder /usr/local/bin/node (5187) exited with code 0 +549ms
Packaging for platform darwin x64 using electron 1.4.4 to dist/mac

  electron-builder Spawning /Users/stefan/Documents/Development/Electron/electron-project/node_modules/7zip-bin-mac/7za x -bd /Users/stefan/.electron/electron-v1.4.4-darwin-x64.zip -o/Users/stefan/Documents/Development/Electron/electron-project/dist/mac +404ms

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 42004724 bytes (41 MiB)

Extracting archive: /Users/stefan/.electron/electron-v1.4.4-darwin-x64.zip
--
Path = /Users/stefan/.electron/electron-v1.4.4-darwin-x64.zip
Type = zip
Physical Size = 42004724

Everything is Ok

Folders: 143
Files: 180
Size:       111898036
Compressed: 42004724
  electron-builder /Users/stefan/Documents/Development/Electron/electron-project/node_modules/7zip-bin-mac/7za (5188) exited with code 0 +2s
  electron-builder Executing security find-identity -v +311ms
  electron-builder Executing security find-identity -v -p codesigning +10ms
  1) 3674B13AC4B3F29509C7D08D9FBE27C735583EEB "Company name #1 AB"
  2) F96DBB184A79B1BB61B5D652C029E59616D2771D "Company name #2 AB"
     2 valid identities found

  1) 7622AC77D96864FE8F6306129A143C16C33194DC "com.apple.idms.appleid.prd.4969564e66456a5a4a785a765074415978646b526d513d3d"
  2) 3674B13AC4B3F29509C7D08D9FBE27C735583EEB "Company name #1 AB"
  3) F96DBB184A79B1BB61B5D652C029E59616D2771D "Company name #2 AB"
  4) D3C693B27194731B691457D4815E6E8D22CE96E3 "com.apple.idms.appleid.prd.4969564e66456a5a4a785a765074415978646b526d513d3d"
     4 valid identities found

Signing app (identity: Company name #2 AB)

Creating DMG
Creating MacOS zip
  electron-builder Spawning /Users/stefan/Documents/Development/Electron/electron-project/node_modules/7zip-bin-mac/7za a -bd -mm=Deflate /Users/stefan/Documents/Development/Electron/electron-project/dist/mac/Sync-0.1.5-mac.zip Sync.app +20s

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive:
  electron-builder Spawning hdiutil create -srcfolder /var/folders/4x/dqxg9wkj1w38n7wz143kjqhm0000gn/T/electron-builder-3ELKq2/t-1442-0-dmg/.background -srcfolder /Users/stefan/Documents/Development/Electron/electron-project/dist/mac/Sync.app -volname Sync 0.1.5 -anyowners -nospotlight -fs HFS+ -fsargs -c c=64,a=16,e=16 -format UDRW -verbose /var/folders/4x/dqxg9wkj1w38n7wz143kjqhm0000gn/T/electron-builder-3ELKq2/t-1442-0-dmg/temp.dmg +12ms
151 folders, 185 files, 113792025 bytes (109 MiB)

Creating archive: /Users/stefan/Documents/Development/Electron/electron-project/dist/mac/Sync-0.1.5-mac.zip

Items to compress: 336

Initierar…
Skapar…
Kopierar…
............................................................................................................................
Avslutar…

Files read from disk: 185
Archive size: 41170491 bytes (40 MiB)
Everything is Ok
  electron-builder /Users/stefan/Documents/Development/Electron/electron-project/node_modules/7zip-bin-mac/7za (5236) exited with code 0 +11s
Error: hdiutil exited with code 1
Error output:
2016-11-01 11:44:16.613 diskimages-helper[5239:176983] *useEffectiveIDs**** euid/egid changed to 501,20 (uid/gid is 501,20)
2016-11-01 11:44:16.614 diskimages-helper[5239:176983] *useRealIDs******** euid/egid changed to 501,20 (uid/gid is 501,20)
2016-11-01 11:44:16.616 diskimages-helper[5239:176983] *useEffectiveIDs**** euid/egid changed to 501,20 (uid/gid is 501,20)
2016-11-01 11:44:16.638 copy-helper[5240:176985] estimating /private/var/folders/4x/dqxg9wkj1w38n7wz143kjqhm0000gn/T/electron-builder-3ELKq2/t-1442-0-dmg/.background
2016-11-01 11:44:17.663 copy-helper[5241:177034] estimating /Users/stefan/Documents/Development/Electron/electron-project/dist/mac/Sync.app
2016-11-01 11:44:18.809 diskimages-helper[5239:176983] *useRealIDs******** euid/egid changed to 501,20 (uid/gid is 501,20)
DIDiskImageCreatorProbe: interface  1, score    -1000, CSparseBundleDiskImage
DIDiskImageCreatorProbe: interface  2, score    -1000, CSparseDiskImage
DIDiskImageCreatorProbe: interface  3, score     1000, CRawDiskImage
DIDiskImageCreatorProbe: interface  7, score    -1000, CWOUDIFDiskImage
DIDiskImageCreatorProbe: interface  9, score    -1000, CCFPlugInDiskImage
DIDiskImageCreateWithCFURL: CRawDiskImage
DIFileEncodingCreatorProbe: interface  2, score    -1000, CEncryptedEncoding
DIBackingStoreCreatorProbe: interface  0, score      100, CBSDBackingStore
DIBackingStoreCreatorProbe: interface  1, score    -1000, CBundleBackingStore
DIBackingStoreCreatorProbe: interface  2, score        0, CRAMBackingStore
DIBackingStoreCreatorProbe: interface  3, score      300, CCarbonBackingStore
DIBackingStoreCreatorProbe: interface  5, score     -100, CCURLBackingStore
DIBackingStoreCreateWithCFURL: CCarbonBackingStore
DIBackingStoreCreateWithCFURL: creator returned 0
DIDiskImageCreateWithCFURL: creator returned 0
DI_kextWaitQuiet: about to call IOServiceWaitQuiet...
DI_kextWaitQuiet: IOServiceWaitQuiet took 0.000004 seconds
DI_kextWaitQuiet: about to call IOServiceWaitQuiet...
DI_kextWaitQuiet: IOServiceWaitQuiet took 0.000005 seconds
2016-11-01 11:44:19.827 diskimages-helper[5239:177101] DIHelperHDID serveImage: attaching drive
{
    autodiskmount = 1;
    "hdiagent-drive-identifier" = "6967E5CE-93E7-4133-9182-E2397B9FCC84";
    "skip-auto-fsck-for-system-images" = 1;
    "system-image" = 1;
    "unmount-timeout" = 0;
}
2016-11-01 11:44:19.828 diskimages-helper[5239:177101] DIHelperHDID serveImage: connecting to myDrive 0x570B
2016-11-01 11:44:19.828 diskimages-helper[5239:177101] DIHelperHDID serveImage: register _readBuffer 0x110ba8000
2016-11-01 11:44:19.828 diskimages-helper[5239:177101] DIHelperHDID serveImage: activating drive port 21783
2016-11-01 11:44:19.828 diskimages-helper[5239:177101] DIHelperHDID serveImage: set cache enabled=TRUE returned FAILURE.
2016-11-01 11:44:19.835 diskimages-helper[5239:177101] DIHelperHDID serveImage: set on IO thread=TRUE returned SUCCESS.
2016-11-01 11:44:19.835 diskimages-helper[5239:177101] -processKernelRequest: will sleep received
2016-11-01 11:44:19.953 diskimages-helper[5239:176983] _mountDevEntries: disk2s1 aborting mountpoint postflight because disk image has no band size specified.
2016-11-01 11:44:19.957 diskimages-helper[5239:176983] *useEffectiveIDs**** euid/egid changed to 501,20 (uid/gid is 501,20)
2016-11-01 11:44:20.061 diskimages-helper[5239:176983] *useRealIDs******** euid/egid changed to 501,20 (uid/gid is 501,20)
2016-11-01 11:44:20.063 diskimages-helper[5239:176983] *useEffectiveIDs**** euid/egid changed to 501,20 (uid/gid is 501,20)
2016-11-01 11:44:20.087 copy-helper[5263:177236] copying /private/var/folders/4x/dqxg9wkj1w38n7wz143kjqhm0000gn/T/electron-builder-3ELKq2/t-1442-0-dmg/.background to /Volumes/Sync 0.1.5/.background
2016-11-01 11:44:20.088 copy-helper[5263:177236] About to copy "/var/folders/4x/dqxg9wkj1w38n7wz143kjqhm0000gn/T/electron-builder-3ELKq2/t-1442-0-dmg/.background".
2016-11-01 11:44:20.096 copy-helper[5263:177236] Copy finished.
2016-11-01 11:44:21.111 copy-helper[5264:177292] copying /Users/stefan/Documents/Development/Electron/electron-project/dist/mac/Sync.app to /Volumes/Sync 0.1.5/Sync.app
2016-11-01 11:44:21.111 copy-helper[5264:177292] About to copy "/Users/stefan/Documents/Development/Electron/electron-project/dist/mac/Sync.app".
2016-11-01 11:44:23.901 copy-helper[5264:177292] Copy finished.



detachTempimageFile: synchronous unmount /dev/disk2s1 returned 49168
retrying unmount (#1)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/Sync 0.1.5 (/dev/disk2s1) returned 49168
retrying unmount (#2)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/Sync 0.1.5 (/dev/disk2s1) returned 49168
retrying unmount (#3)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/Sync 0.1.5 (/dev/disk2s1) returned 49168
2016-11-01 11:44:26.434 diskimages-helper[5239:177101] -processKernelRequest: flush received
2016-11-01 11:44:26.459 diskimages-helper[5239:176983] *useEffectiveIDs**** euid/egid changed to 501,20 (uid/gid is 501,20)
DIHLDiskImageCreate() returned 49168
2016-11-01 11:44:27.463 diskimages-helper[5239:176978] *** -[NSMachPort handlePortMessage:]: dropping incoming DO message because the connection is invalid
hdiutil: create: returning 49168
hdiutil: create failed - Resursen upptagen

    at ChildProcess.childProcess.once.code (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/util/util.ts:160:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/util/util.ts:123:3)
    at /Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/targets/dmg.ts:46:11
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/out/targets/dmg.js:223:11)
    at MacPackager.packageInDistributableFormat (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/macPackager.ts:193:25)
    at /Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/macPackager.ts:77:16
From previous event:
    at /Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/macPackager.ts:76:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/out/macPackager.js:154:11)
    at /Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/packager.ts:134:22
From previous event:
    at Packager.doBuild (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/out/packager.js:254:11)
    at /Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/packager.ts:102:32
    at Generator.next (<anonymous>)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/out/packager.js:206:11)
    at /Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/src/builder.ts:234:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/out/builder.js:81:21)
    at Object.<anonymous> (/Users/stefan/Documents/Development/Electron/electron-project/node_modules/electron-builder/out/build-cli.js:66:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
```

**Comment by stefanedberg** [comment]
Damn. I've been running the build on my work computer which has AVG AntiVirus installed... The realtime protection caused the problem, now the build runs fine. Thanks again @develar.

**Comment by develar** [comment]
Ouch... AntiVirus on macOS :) Thanks for update.

**Comment by RooTooZ** [comment]
Ohhhhh!!! With AVG Cleaner i have same errors! Thank you @develar and @stefanedberg!

**Comment by karimhossenbux** [comment]
Got the error with Sophos too, works properly by deactivate it

**Comment by bkniffler** [comment]
Also, this might appear if you have installed XCode but did not yet run it, thus some components are not installed. Make sure to run at least once.

**Comment by antronic** [comment]
> Got the error with Sophos too, works properly by deactivate it

Hi @karimhossenbux , I'm also using Sophos, I already stop scanning and turn off all of the features, but it looks like it doesn't work.

How do you deactivate it?

**Comment by michaelkozakovsc** [comment]
Also getting the same 

> detachTempimageFile: synchronous unmount /dev/disk2s1 returned 49168
> retrying unmount (#1)...
> detachTempImageFile: synchronous retry (#1) unmount /Volumes/Sync 0.1.5 (/dev/disk2s1) returned 49168
> retrying unmount (#2)...
> detachTempImageFile: synchronous retry (#1) unmount /Volumes/Sync 0.1.5 (/dev/disk2s1) returned 49168
> retrying unmount (#3)...

Getting the same log output on my end too. Is there a way to increase the number of retries @develar ? Once in a blue moon i do see it passing...
