### ISSUE TITLE
[bug] can't find visual studio 2022

### ISSUE THREAD

**Issue by xyloflake** [electron-userland/electron-builder#8580]
* **Electron-Builder Version**: 25.1.7

* **Node Version**: 21.7.3

* **Electron Version**: 31
* **Electron Type (current, beta, nightly)**: Current

* **Target**: exe (win11)

Logs:

```
> electron-builder install-app-deps

  • electron-builder  version=25.1.7
  • loaded configuration  file=C:\Users\Xylo\Documents\muffon\muffon\electron-builder.json
  • executing @electron/rebuild  electronVersion=31.7.0 arch=x64 buildFromSource=false appDir=./
  • installing native dependencies  arch=x64
  • preparing       moduleName=register-scheme arch=x64
  ⨯ Error: Could not find any Visual Studio installation to use
    at VisualStudioFinder.fail (C:\Users\Xylo\Documents\muffon\muffon\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
    at C:\Users\Xylo\Documents\muffon\muffon\node_modules\node-gyp\lib\find-visualstudio.js:75:16
    at VisualStudioFinder.findVisualStudio2013 (C:\Users\Xylo\Documents\muffon\muffon\node_modules\node-gyp\lib\find-visualstudio.js:380:14)
    at C:\Users\Xylo\Documents\muffon\muffon\node_modules\node-gyp\lib\find-visualstudio.js:71:14
    at VisualStudioFinder.findVisualStudio2015 (C:\Users\Xylo\Documents\muffon\muffon\node_modules\node-gyp\lib\find-visualstudio.js:364:14)
    at C:\Users\Xylo\Documents\muffon\muffon\node_modules\node-gyp\lib\find-visualstudio.js:67:12
    at VisualStudioFinder.parseData (C:\Users\Xylo\Documents\muffon\muffon\node_modules\node-gyp\lib\find-visualstudio.js:237:5)
    at C:\Users\Xylo\Documents\muffon\muffon\node_modules\node-gyp\lib\find-visualstudio.js:143:14
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)


  ⨯ node-gyp failed to rebuild 'C:\Users\Xylo\Documents\muffon\muffon\node_modules\register-scheme'  failedTask=installAppDeps stackTrace=Error: node-gyp failed to rebuild 'C:\Users\Xylo\Documents\muffon\muffon\node_modules\register-scheme'
    at ChildProcess.<anonymous> (C:\Users\Xylo\Documents\muffon\muffon\node_modules\@electron\rebuild\lib\module-type\node-gyp\node-gyp.js:121:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
 ELIFECYCLE  Command failed with exit code 1.
```

Visual studio 2019/2015/2013 is outdated and it looks like 2022 isn't supported. 24.13.3 did not have this problem.

**Comment by xyloflake** [comment]
tried this https://stackoverflow.com/a/70799513 but it changes absolutely nothing

**Comment by xyloflake** [comment]
> I've just merged the update to electron/rebuild 3.7.0 which also changes node-gyp to @electron/node-gyp. Wondering if that will resolve your issue. It's in 26.0.0-alpha.1 (just released)
> 

Thanks, we try to avoid alpha dependencies in our production code for obvious reasons. But I'll give it a try to just report if that's fixed or not.

> Re: you PR on `muffon` and the "repatch". `next` v6.4.0-alpha.0 version of electron-updater has the pacman implementation if you're willing to update to it
> 

Thank you for the generous consideration but as mentioned above, we are not really planning to include alpha dependencies in our code ^_^

I am pretty sure you get the gist of the "why"s behind it :)

> Also, if you're willing to test with `nativeRebuilder: "legacy"` in your electron-builder config, that'd also help confirm whether there's a bug in electron/rebuild or if it is truly node-gyp 🙂 
> `legacy` is the previous native module rebuilder used in 24.13.3

Will do when I get some free time and report back. Thanks.

**Comment by mmaietta** [comment]
Totally understand the policy around alpha versions 🙂 

We have some big underlying changes coming up for electron-builder in v26, namely migrating to the official electron/asar to support asar integrity+other newer features and migrating from app-builder-bin Go binary to a JS-implemented node module collector with proper dependency hoisting resolution logic (so we can fully control the logic and implementation). That and removing deprecated configuration vars because the clean up just needs to happen 😅

**Comment by xyloflake** [comment]
@mmaietta `nativeRebuilder: "legacy"` worked fine! Look like I still need to manually repatch everything tho but it did work so I guess there's a bug in `electron/rebuild`.

> We have some big underlying changes coming up for electron-builder in v26, namely migrating to the official electron/asar to support asar integrity+other newer features and migrating from app-builder-bin Go binary to a JS-implemented node module collector with proper dependency hoisting resolution logic (so we can fully control the logic and implementation). That and removing deprecated configuration vars because the clean up just needs to happen 😅

Sounds super cool! But would switching from the go binary to JS-implemented node module become slower? Also, happy to know deprecation cleanup is happening!

> I've just merged the update to electron/rebuild 3.7.0 which also changes node-gyp to @electron/node-gyp. Wondering if that will resolve your issue. It's in 26.0.0-alpha.1 (just released)

Works as well! `26.0.0-alpha.1` works without `nativeRebuilder: "legacy"` so we can say it's officially solved! Thank you!

**Comment by mmaietta** [comment]
That's lovely to hear! Glad to hear it's resolved 🙂
