### ISSUE TITLE
Yarn Support (rebuild)

### ISSUE THREAD

**Issue by amilajack** [electron-userland/electron-builder#861]
**yarn version: 0.16.0, node 7.0.0**
- **Version: latest**: 

- **All: This is a cross-platform issue**: 

(I should note that I am installing with yarn) I think the issue is that `electron-builder` tries to find incorrect flags that were passed to it and its somehow validating flags from npm. I found that when running `install-app-deps` from npm scripts, the [--cache-min](https://docs.npmjs.com/misc/config#cache-min) option seems to be validated by `electron-builder`. Here's the stack trace:

```
    at ChildProcess.childProcess.once.code (/Users/amila/Documents/Projects/builder-test/node_modules/electron-builder/src/util/util.ts:160:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
From previous event:
    at spawn (/Users/amila/Documents/Projects/builder-test/node_modules/electron-builder/src/util/util.ts:123:3)
    at spawnNpmProduction (/Users/amila/Documents/Projects/builder-test/node_modules/electron-builder/src/util/util.ts:49:3)
    at installDependencies (/Users/amila/Documents/Projects/builder-test/node_modules/electron-builder/src/util/util.ts:20:122)
    at /Users/amila/Documents/Projects/builder-test/node_modules/electron-builder/src/install-app-deps.ts:31:2
    at Generator.next (<anonymous>)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at main (/Users/amila/Documents/Projects/builder-test/node_modules/electron-builder/out/install-app-deps.js:29:21)
    at Object.<anonymous> (/Users/amila/Documents/Projects/builder-test/node_modules/electron-builder/out/install-app-deps.js:73:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
```

Everything seems to work fine when installing with `npm`

**Comment by develar** [comment]
Yarn will be not supported until https://github.com/yarnpkg/yarn/issues/756 is not fixed or rebuild will be not implemented on our side.

**Comment by develar** [comment]
This error is fixed, but you cannot in any case use yarn because yarn cannot rebuild native dependencies.

**Comment by ConorIA** [comment]
yarn's website provides `yarn install --force` as equivalent to `npm rebuild`, but I imagine that implementing this would require a substantial re-write. As mentioned in the closed issue, replacing the rebuild commands with `install` does help get past the first bug, but then I was hitting the `--cache-min` issue even in builder 7.18.0.

**Comment by develar** [comment]
> replacing the rebuild commands with install does help get past the first bug

No. `install` doesn't respect arch. If previously was installed for ia32, new arch via env is ignored and you will get broken build. It is the reason why `rebuild` is used. I don't know is this bug fixed in the yarn or not.

**Comment by ConorIA** [comment]
Ok. Thanks @develar. I'll follow the issue on yarn closely.

**Comment by develar** [comment]
yarn will be supported as soon as https://github.com/yarnpkg/yarn/issues/1749 will be fixed.

**Comment by develar** [comment]
If you do not use `yarn run` to run build, but execute it directly, you can set env `FORCE_YARN=true`

**Comment by develar** [comment]
Result of `installDependencies` is not yet fully tested and proven (because yarn doesn't support `--build-from-source`). Use `yarn` in this case on your own risk.
