### ISSUE TITLE
`not a mach-o file` error

### ISSUE THREAD

**Issue by moltenice** [electron-userland/electron-builder#8646]
* **Electron-Builder Version**: 25.1.7

* **Node Version**: 22.11.0

* **Electron Version**: 32.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**:
  ```typescript
  mac: {
        icon: "build/logo512.png",
        category: "public.app-category.utilities",
        target: "zip",
      }
  ```

Hello everyone.

I upgraded electron-builder from `24.13.3` to `25.1.7`. Nothing else has changed, not even the version of better-sqlite3. I usually build the unsigned Mac target above on Linux using the `electronuserland/builder:wine` docker image.

On version `24.13.3` this built and ran fine on my Mac M1 arm laptop. Upgrading to `25.1.7` gives me the error below:

```bash
Uncaught Exception:
Error: dlopen(/Applications/My.app/Contents/Resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node, 0x0001): tried: '/Applications/My.app/Contents/Resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/My.app/Contents/Resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node' (no such file), '/Applications/My.app/Contents/Resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node' (not a mach-o file)
at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
at Module.load (node:internal/modules/cjs/loader:1295:32)
at Module._load (node:internal/modules/cjs/loader:1111:12)
at Function.c._load (node:electron/js2c/node_init:2:17025)
at Module.require (node:internal/modules/cjs/loader:1318:19)
at require (node:internal/modules/helpers:179:18)
at bindings (/Applications/My.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
at new Database (/Applications/My.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64)
```

So far I tried force building to arm (which gave me damaged file due to it being unsigned) and x64 which gave the same error above because I assume the target is x64 by default for "zip" if nothing is specified.

Does anyone know what changed and if there's a special option I need to use to fix this?

**Comment by mmaietta** [comment]
Can you please try `latest` 25.1.8? From what you're describing, it sounds like electron/rebuild is downloading the incorrect platform for prebuilt binaries, which I patched upstream on `electron/rebuild` implementation and should be in v25.1.8 of electron-builder

**Comment by moltenice** [comment]
@mmaietta thanks for your reply. I just tried it twice with "@electron/rebuild": "^3.7.0" and "electron-builder": "^25.1.8" with the same issue.

I suspect something changed at some point to start causing this?

Your analysis on downloading the incorrect binaries seems right though, since the error points to it probably using x64 than arm.

Are you able to replicate this using the wine docker image on Linux with the target being zip? Perhaps zip by default only does x64?

**Comment by mmaietta** [comment]
@moltenice can you try setting `nativeRebuilder: legacy` in your electron-builder config? That'll flip electron-builder back to the previous native rebuilder (app-builder-bin)
https://www.electron.build/app-builder-lib.interface.commonconfiguration#nativerebuilder

**Comment by moltenice** [comment]
@mmaietta that was it! That fixed it, I can now use version 25.1.8 perfectly. Thanks for the tip!

Do you know how I could migrate this particular configuration away from legacy and towards using `@electron/rebuild`? I use this package directly anyway to run my app locally so that it builds native code for electron's Node version and not the repo's Node version.

I wonder if there's a way to pass in an argument to `@electron/rebuild` through the `electron-builder` config to get it to generate a universal Mac zip image. I think the legacy builder compiles to universal which works on both x64 and arm. Or possibly it just builds x64 and arm runs in some sort of compatibility mode, my knowledge is a bit hazy here 😅

**Comment by mmaietta** [comment]
I don't think that's possible in terms of `rebuild` (or in general?). I'm not deeply familiar with node-gyp which electron-rebuild and app-builder-bin leverage under the hood, but I thought there was no concept of a universal node module (as you can't even supply `universal` as a cmd-line arg for `--arch`), rather other tools stitch (`lipo` cmd for mac) together the finalized assets.

Could you share a minimum reproducible repo? That might help identify here what's going wrong. I might need to push another fix upstream if I can determine it

**Comment by mmaietta** [comment]
@moltenice can you try v26.0.0-alpha.6 and see if you can leverage electron-builder without `nativeRebuilder: legacy`? I contributed some changes upstream to `electron/rebuild` that might have solved your issue as well. Hard to say without a minimum repro repo

**Comment by moltenice** [comment]
@mmaietta sorry just got back from holiday. Here's the config you need to put onto a "hello world" electron-builder project:

```typescript
import { Configuration } from "electron-builder";

export default function electronBuilderConfig(): Configuration {
  return {
    appId: "com.simplybusiness.test",
    productName: "Test",
    files: ["build/**/*", "node_modules/**/*"],
    mac: {
      icon: "build/logo512.png",
      category: "public.app-category.utilities",
      target: "zip",
    },
    win: {
      icon: "build/logo512.png",
    },
    linux: {
      icon: "build/logo512.png",
      target: "AppImage",
    },
  };
}
```

Then you need to run electron-builder on a Linux system (I used Ubuntu) with Docker installed with this command:

```bash
docker run --rm \
  --env CSC_IDENTITY_AUTO_DISCOVERY=false \
  -v $(pwd):/project \
  -v ~/.cache/electron:/root/.cache/electron \
  -v ~/.cache/electron-builder:/root/.cache/electron-builder \
  -v /var/run/docker.sock:/var/run/docker.sock \
  electronuserland/builder:wine \
  /bin/bash -c "electron-builder -c.extraMetadata.main=build/electron/main.js --config=electron-builder-config.ts --mac --windows --linux"
```

Hope that helps you reproduce this. And then when you add in `nativeRebuilder: "legacy"` it should fix itself.
