### ISSUE TITLE
Packaging breaks with local package imports

### ISSUE THREAD

**Issue by Stoyvo** [electron-userland/electron-builder#8673]
* **Electron-Builder Version**: 25.1.8

* **Node Version**: 20.18.0

* **Electron Version**: 31.7.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: arm64

My package.json has a local package, eg:
```json
{
  "name": "my-app",
  "author": "Me",
  "version": "0.11.2",
  "productName": "myapp",
  "main": "main.js",
  "homepage": ".",
  "type": "commonjs",
  "dependencies": {
    "@stoyvo/api-client": "file:../../api-client",
```

I get the error:

```
  • packaging       platform=darwin arch=arm64 electron=31.7.3 appOutDir=dist/mac-arm64
  ⨯ /Users/stoyvo/Development/api-client/.openapi-generator-ignore must be under /Users/stoyvo/Development/electron/  failedTask=build stackTrace=Error: /Users/stoyvo/Development/api-client/.openapi-generator-ignore must be under /Users/stoyvo/Development/electron/
    at getRelativePath (/Users/stoyvo/Development/electron/node_modules/app-builder-lib/src/util/filter.ts:32:13)
    at AsarPackager.unpackPattern (/Users/stoyvo/Development/electron/node_modules/app-builder-lib/src/util/filter.ts:57:22)
    at AsarPackager.createPackageFromFiles (/Users/stoyvo/Development/electron/node_modules/app-builder-lib/src/asar/asarUtil.ts:129:82)
```

I believe there is resemblance to this issue recently closed: #8345

**Comment by beyondkmp** [comment]
Could you test the https://github.com/electron-userland/electron-builder/releases/tag/v26.0.0-alpha.6?

**Comment by Red-Asuka** [comment]
@beyondkmp I had the same issue, and upgrading to 26.0.0-alpha.6 resolved it.

**Comment by funwithtriangles** [comment]
Had the same issue with my monorepo, can confirm updating to `26.0.0-alpha.6` fixed it 🙃

**Comment by 3eif** [comment]
What electron version are you all using. I've spent 10 hours trying to fix this issue. Not sure why the package is so buggy.

**Comment by funwithtriangles** [comment]
Was having the issue with `24.13.3` before updating to `26.0.0-alpha.6`
