### ISSUE TITLE
yarn doesn't recognize 'rebuild' command

### ISSUE THREAD

**Issue by ConorIA** [electron-userland/electron-builder#870]
* **Version**: 7.18.0

* **Target**: Linux x64, unpacked dir

I was playing around to see if I could get yarn to work with electron-builder. However, if the builder decides to run rebuild, the command fails with an unknown command error. This is because yarn understands 'install --force' instead of 'rebuild'. 

I tried simply replacing the term "rebuild" in `electron-builder/out/build-cli.js` with "install --force", but it still gives an error. However, if I replace the commands with "install" without the flag, I get passed that error and hit the '--cache-min' error that was fixed in a recent commit. 

EDIT: Just noticed the dependency issue that you highlighted in #861. I can close this if it is an issue that needs to be fixed on the yarn side.

```
build --linux --x64 
Rebuilding app dependencies for arch x64 to /home/conor/git/wire-desktop/electron

Error: /usr/bin/node exited with code 1
Output:
yarn rebuild v0.16.1

Error output:
error Command "rebuild" not found.

    at ChildProcess.childProcess.once.code (/home/conor/git/wire-desktop/node_modules/electron-builder/src/util/util.ts:160:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (/home/conor/git/wire-desktop/node_modules/electron-builder/src/util/util.ts:123:3)
    at spawnNpmProduction (/home/conor/git/wire-desktop/node_modules/electron-builder/src/util/util.ts:49:3)
    at installDependencies (/home/conor/git/wire-desktop/node_modules/electron-builder/src/util/util.ts:20:122)
    at /home/conor/git/wire-desktop/node_modules/electron-builder/src/packager.ts:244:17
From previous event:
    at Packager.installAppDependencies (/home/conor/git/wire-desktop/node_modules/electron-builder/out/packager.js:343:11)
    at /home/conor/git/wire-desktop/node_modules/electron-builder/src/packager.ts:127:20
    at next (native)
From previous event:
    at Packager.doBuild (/home/conor/git/wire-desktop/node_modules/electron-builder/out/packager.js:254:11)
    at /home/conor/git/wire-desktop/node_modules/electron-builder/src/packager.ts:102:32
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/home/conor/git/wire-desktop/node_modules/electron-builder/out/packager.js:206:11)
    at /home/conor/git/wire-desktop/node_modules/electron-builder/src/builder.ts:234:33
    at next (native)
From previous event:
    at build (/home/conor/git/wire-desktop/node_modules/electron-builder/out/builder.js:81:21)
    at Object.<anonymous> (/home/conor/git/wire-desktop/node_modules/electron-builder/out/build-cli.js:66:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ConorIA** [comment]
Just saw the option to disable npmRebuild. This solves my issue for now.

**Comment by develar** [comment]
Yarn will be not supported until https://github.com/yarnpkg/yarn/issues/756 is not fixed or rebuild will be not implemented on our side.

Duplicates #861
