### ISSUE TITLE
electron-builder fails when list of node_modules files is too big to pass in a glob

### ISSUE THREAD

**Issue by abram** [electron-userland/electron-builder#8705]
This recent change causes electron-builder to fail in my project:

https://github.com/electron-userland/electron-builder/blob/6a6bed46c428b45105ada071a9cb89b5d4f93d9e/packages/app-builder-lib/src/asar/asarUtil.ts#L49

It attempts to take a potentially large file list and put it into a glob pattern string. This causes an error due to exceeding a hard coded limit in minimatch:
```
pattern is too long
    at assertValidPattern (node_modules\minimatch\minimatch.js:280:11)
    at minimatch (node_modules\minimatch\minimatch.js:116:3)
    at isUnpackedDir (node_modules\@electron\asar\src\asar.ts:24:41)
    at handleFile (node_modules\@electron\asar\src\asar.ts:148:17)
    at next (node_modules\@electron\asar\src\asar.ts:185:5)
    at AsarPackager.executeElectronAsar (node_modules\app-builder-lib\src\asar\asarUtil.ts:77:5)
    at AsarPackager.pack (app-builder-lib\src\asar\asarUtil.ts:51:5)
```

You can see the limit code here:
https://github.com/isaacs/minimatch/blob/main/src/assert-valid-pattern.ts#L1

I'm not familiar with the asar module, but there must be a better way to pass a file list than using a giant glob.

**Comment by beyondkmp** [comment]
https://github.com/electron-userland/electron-builder/pull/8645 can fix this issue. It only add the node_modules/xxx into unpackedPaths intead of all sub directories in node_modules/xxx.

**Comment by beyondkmp** [comment]
@abram This #8645 has been merged into [v26.0.0-alpha.7](https://github.com/electron-userland/electron-builder/releases/tag/v26.0.0-alpha.7).  Can you help try it?

**Comment by abram** [comment]
Thanks so much @beyondkmp! I can confirm that your fix is working for me.
