### ISSUE TITLE
macOS codesign with external executable.

### ISSUE THREAD

**Issue by zh99998** [electron-userland/electron-builder#873]
* **Version**: 7.18.0

* **Target**: macOS Sierra

I can't sign my app after I imported a node module `electron-sudo` with executable code.
electron-build will put its executable in asar unpacked directory but seems apple don't allow to put executable here.

full log
```
bash-3.2$ npm run dist

> mycard@3.0.0-dev.5 dist /Users/zh99998/mycard
> tsc && build

CSC_KEY_PASSWORD is not defined, empty password will be used
Skip app dependencies rebuild because dev and app dependencies are not separated
Packaging for platform darwin x64 using electron 1.4.5 to dist/mac

node_modules/electron-sudo is not packed into asar archive - contains executable code
Signing app (identity: Developer ID Application: XIAOCHI CHEN (ZNVDEVDRX3))

Error: Command failed: codesign --sign Developer ID Application: XIAOCHI CHEN (ZNVDEVDRX3) --force --keychain /var/folders/6z/w51w9rgx2z34q5z6jhzps0t40000gn/T/electron-builder-dcAiAf/t-dfb1-0.keychain /Users/zh99998/mycard/dist/mac/MyCard.app/Contents/Resources/app.asar.unpacked/node_modules/electron-sudo/dist/bin/applet.app/Contents/MacOS/applet
/Users/zh99998/mycard/dist/mac/MyCard.app/Contents/Resources/app.asar.unpacked/node_modules/electron-sudo/dist/bin/applet.app/Contents/MacOS/applet: unsealed contents present in the bundle root

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at MacPackager.sign (/Users/zh99998/mycard/node_modules/electron-builder/out/macPackager.js:235:11)
    at /Users/zh99998/mycard/node_modules/electron-builder/src/macPackager.ts:75:26
From previous event:
    at /Users/zh99998/mycard/node_modules/electron-builder/src/macPackager.ts:75:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/zh99998/mycard/node_modules/electron-builder/out/macPackager.js:154:11)
    at /Users/zh99998/mycard/node_modules/electron-builder/src/packager.ts:134:22
From previous event:
    at Packager.doBuild (/Users/zh99998/mycard/node_modules/electron-builder/out/packager.js:254:11)
    at /Users/zh99998/mycard/node_modules/electron-builder/src/packager.ts:102:32
    at Generator.next (<anonymous>)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/Users/zh99998/mycard/node_modules/electron-builder/out/packager.js:206:11)
    at /Users/zh99998/mycard/node_modules/electron-builder/src/builder.ts:234:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/zh99998/mycard/node_modules/electron-builder/out/builder.js:81:21)
    at Object.<anonymous> (/Users/zh99998/mycard/node_modules/electron-builder/out/build-cli.js:66:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! mycard@3.0.0-dev.5 dist: `tsc && build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the mycard@3.0.0-dev.5 dist script 'tsc && build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mycard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mycard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mycard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zh99998/mycard/npm-debug.log
```

**Comment by zh99998** [comment]
oh it's only electron-sudo's problem. it contains wrong files.
sorry for open this issue
