### ISSUE TITLE
electron-builder encountered an error during packaging

### ISSUE THREAD

**Issue by GiockL** [electron-userland/electron-builder#8754]
icon directory C:\Users\25819\Desktop\pudding-ui\build\icons doesn't contain icons
github.com/develar/app-builder/pkg/icons.CollectIcons
        C:/Users/develar/Desktop/app-builder/pkg/icons/collect-icons.go:73
github.com/develar/app-builder/pkg/icons.doConvertIcon
        C:/Users/develar/Desktop/app-builder/pkg/icons/icon-converter.go:191
github.com/develar/app-builder/pkg/icons.ConvertIcon
        C:/Users/develar/Desktop/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
        C:/Users/develar/Desktop/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        C:/Users/develar/Desktop/app-builder/main.go:90
runtime.main
        C:/Program Files/Go/src/runtime/proc.go:225
runtime.goexit
        C:/Program Files/Go/src/runtime/asm_amd64.s:1371
github.com/develar/app-builder/pkg/icons.doConvertIcon
        C:/Users/develar/Desktop/app-builder/pkg/icons/icon-converter.go:193
github.com/develar/app-builder/pkg/icons.ConvertIcon
        C:/Users/develar/Desktop/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
        C:/Users/develar/Desktop/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        C:/Users/develar/Desktop/app-builder/main.go:90
runtime.main
        C:/Program Files/Go/src/runtime/proc.go:225
runtime.goexit
        C:/Program Files/Go/src/runtime/asm_amd64.s:1371
  ⨯ C:\Users\25819\Desktop\pudding-ui\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: C:\Users\25819\Desktop\pudding-ui\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (C:\Users\25819\Desktop\pudding-ui\node_modules\builder-util\src\util.ts:249:14)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
From previous event:
    at processImmediate (node:internal/timers:476:21)
From previous event:
    at WinPackager.signApp (C:\Users\25819\Desktop\pudding-ui\node_modules\app-builder-lib\src\winPackager.ts:376:27)
    at WinPackager.doSignAfterPack (C:\Users\25819\Desktop\pudding-ui\node_modules\app-builder-lib\src\platformPackager.ts:315:16)
    at WinPackager.doPack (C:\Users\25819\Desktop\pudding-ui\node_modules\app-builder-lib\src\platformPackager.ts:300:7)
    at WinPackager.pack (C:\Users\25819\Desktop\pudding-ui\node_modules\app-builder-lib\src\platformPackager.ts:136:5)
    at Packager.doBuild (C:\Users\25819\Desktop\pudding-ui\node_modules\app-builder-lib\src\packager.ts:441:9)
    at Object.executeFinally (C:\Users\25819\Desktop\pudding-ui\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\Users\25819\Desktop\pudding-ui\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (C:\Users\25819\Desktop\pudding-ui\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (C:\Users\25819\Desktop\pudding-ui\node_modules\builder-util\src\promise.ts:12:14)
PS C:\Users\25819\Desktop\pudding-ui> E:\Ai\pudding-ui
E:\Ai\pudding-ui : The term 'E:\Ai\pudding-ui' is not recognized as the name of a cmdlet, function, script file, or ope
rable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again
.
At line:1 char:1
+ E:\Ai\pudding-ui
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (E:\Ai\pudding-ui:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\25819\Desktop\pudding-ui> cd E:\Ai\pudding-ui
PS E:\Ai\pudding-ui> npm run builde

> pudding@0.1.0 builde
> electron-builder

  • electron-builder  version=24.13.3 os=10.0.19045
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist_electron\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=20.3.8 appOutDir=dist_electron\win-unpacked
  ⨯ icon directory E:\Ai\pudding-ui\build\icons doesn't contain icons
github.com/develar/app-builder/pkg/icons.CollectIcons
        /Volumes/data/Documents/app-builder/pkg/icons/collect-icons.go:73
github.com/develar/app-builder/pkg/icons.doConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:191
github.com/develar/app-builder/pkg/icons.ConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:90
runtime.main
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:255
runtime.goexit
        /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581
github.com/develar/app-builder/pkg/icons.doConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:193
github.com/develar/app-builder/pkg/icons.ConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:90
runtime.main
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:255
runtime.goexit
        /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581
  ⨯ E:\Ai\pudding-ui\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: E:\Ai\pudding-ui\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (E:\Ai\pudding-ui\node_modules\builder-util\src\util.ts:252:14)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.cp.emit (E:\Ai\pudding-ui\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
From previous event:
    at processImmediate (node:internal/timers:476:21)
From previous event:
    at WinPackager.signApp (E:\Ai\pudding-ui\node_modules\app-builder-lib\src\winPackager.ts:384:27)
    at WinPackager.doSignAfterPack (E:\Ai\pudding-ui\node_modules\app-builder-lib\src\platformPackager.ts:336:32)
    at WinPackager.doPack (E:\Ai\pudding-ui\node_modules\app-builder-lib\src\platformPackager.ts:321:7)
    at WinPackager.pack (E:\Ai\pudding-ui\node_modules\app-builder-lib\src\platformPackager.ts:140:5)
    at Packager.doBuild (E:\Ai\pudding-ui\node_modules\app-builder-lib\src\packager.ts:445:9)
    at executeFinally (E:\Ai\pudding-ui\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (E:\Ai\pudding-ui\node_modules\app-builder-lib\src\packager.ts:379:31)
    at Packager.build (E:\Ai\pudding-ui\node_modules\app-builder-lib\src\packager.ts:340:12)
    at executeFinally (E:\Ai\pudding-ui\node_modules\builder-util\src\promise.ts:12:14)

**Comment by mmaietta** [comment]
>icon directory C:\Users\25819\Desktop\pudding-ui\build\icons doesn't contain icons

What does your `icons` folder contain? Are you able to try renaming it and see if this issue persists?
