### ISSUE TITLE
electron-builder fails to package with native node module on Ubuntu

### ISSUE THREAD

**Issue by epezhman** [electron-userland/electron-builder#876]
* **Version**: 7.14.1

* **Target**: Ubuntu 16.04 64bit

I'm trying to use [node-system-idle-time](https://github.com/paulcbetts/node-system-idle-time) in my electron app, I got the app running with `electron-prebuilt` by navigating to `node-modules/@paulcbetts/system-idle-time` and running
`sudo HOME=~/.electron-gyp node-gyp rebuild --target=1.3.4 --arch=x64 --dist-url=https://atom.io/download/atom-s`h

but when I'm trying to build the app by `electron-builder` I get this: any ideas? Thanks

```
Output:

> @paulcbetts/system-idle-time@1.0.4 install /home/epezhman/Projects/demand-manager-app/app/node_modules/@paulcbetts/system-idle-time
> node-gyp rebuild

make: Entering directory '/home/epezhman/Projects/demand-manager-app/app/node_modules/@paulcbetts/system-idle-time/build'
  CXX(target) Release/obj.target/system_idle_time/src/module.o
system_idle_time.target.mk:95: recipe for target 'Release/obj.target/system_idle_time/src/module.o' failed
make: Leaving directory '/home/epezhman/Projects/demand-manager-app/app/node_modules/@paulcbetts/system-idle-time/build'

Error output:
In file included from /usr/include/errno.h:28:0,
                 from /home/epezhman/.electron-gyp/.node-gyp/iojs-1.4.3/deps/uv/include/uv-errno.h:25,
                 from /home/epezhman/.electron-gyp/.node-gyp/iojs-1.4.3/deps/uv/include/uv.h:48,
                 from ../../../nan/nan.h:46,
                 from ../src/module.h:4,
                 from ../src/module.cc:1:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/system_idle_time/src/module.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-45-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/epezhman/Projects/demand-manager-app/app/node_modules/@paulcbetts/system-idle-time
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "rebuild" "--production" "--cache-min" "999999999" "--build-from-source"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! @paulcbetts/system-idle-time@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @paulcbetts/system-idle-time@1.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @paulcbetts/system-idle-time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @paulcbetts/system-idle-time
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @paulcbetts/system-idle-time
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/epezhman/Projects/demand-manager-app/app/npm-debug.log

    at ChildProcess.<anonymous> (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/util.ts:160:14)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at spawn (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/util.ts:123:3)
    at spawnNpmProduction (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/util.ts:49:3)
    at Object.installDependencies (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/util.ts:20:122)
    at Packager.<anonymous> (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/packager.ts:239:34)
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at tsAwaiter (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/out/builder.js:138:12)
    at /home/epezhman/Projects/demand-manager-app/tasks/build.js:59:28
    at _fulfilled (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:796:13)
    at /home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:604:44
    at runSingle (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:137:13)
    at flush (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)

```

**Comment by develar** [comment]
Do not rebuild manually. Please use https://github.com/electron-userland/electron-builder#two-packagejson-structure if you have native deps —  electron-builder will rebuild native dependencies for you correctly.

If you do not use "Two package.json structure" and have native deps — electron-builder cannot help you.

So, I can advise only — do not use `sudo` (maybe your did `npm install` using sudo — it is not correct, in this case please remove all node_modules and install it without sudo).

**Comment by epezhman** [comment]
Thanks a lot for the answer, I do have a Two package.json structure. I'm now following this procedure but still getting an error. 

1. first I deleted `./node_modules` and `./app/node_modules`

2. in` ./package.json`

```
"build": {
    .....
    "nodeGypRebuild": true,
    ...
}
```

2. 
```
~: cd app 
~: npm install --save @paulcbetts/system-idle-time
~: cd ..
~: gulp build

```
I'm using gulp to build it programmatically and it's been working fine for me so far.  but now I get this:

```
[11:06:35] Error: Exit code: 1. Command failed: node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.6.1 | linux | x64
gyp info spawn /home/epezhman/IDE/miniconda2/bin/pf927eab7c96ff95f2e19ebd3b6822935e3dcd09dffa139677a6eaf3856bcc1c6 (sha256 hash) info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/epezhman/Projects/demand-manager-app/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/epezhman/.electron-gyp/.node-gyp/iojs-1.4.3/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/epezhman/.electron-gyp/.node-gyp/iojs-1.4.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/epezhman/Projects/demand-manager-app',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home/epezhman/Projects/demand-manager-app) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-45-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/epezhman/Projects/demand-manager-app
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.6.1 | linux | x64
gyp info spawn /home/epezhman/IDE/miniconda2/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/epezhman/Projects/demand-manager-app/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/epezhman/.electron-gyp/.node-gyp/iojs-1.4.3/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/epezhman/.electron-gyp/.node-gyp/iojs-1.4.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/epezhman/Projects/demand-manager-app',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home/epezhman/Projects/demand-manager-app) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-45-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/epezhman/Projects/demand-manager-app
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

    at /home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/util.ts:102:16
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at Object.exec (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/util.ts:80:3)
    at Packager.<anonymous> (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/packager.ts:228:17)
    at next (native)
From previous event:
    at tsAwaiter (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/out/builder.js:138:12)
    at /home/epezhman/Projects/demand-manager-app/tasks/build.js:42:28
    at Promise.apply (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:788:41)
    at /home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:1391:14
    at runSingle (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:137:13)
    at flush (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

after that I even tried:

```
~: npm install --save-dev electron-rebuild
~: ./node_modules/.bin/electron-rebuild
```

any idea if I'm doing something wrong? thanks

**Comment by develar** [comment]
`nodeGypRebuild` is not required for you and must be not used — it only if your app is native. But you only have native deps. Do not use `nodeGypRebuild`.

**Comment by epezhman** [comment]
Thanks again for the answer, with those fixes now it's building fine when targeting Linux x64 but when I'm trying to build for Linux ia32 I get the following error. does that mean the target node in native module is not compatible or? I'm on Ubuntu 16.04 x64 ,thanks


```
Output:

> @paulcbetts/system-idle-time@1.0.4 install /home/epezhman/Projects/demand-manager-app/app/node_modules/@paulcbetts/system-idle-time
> node-gyp rebuild

make: Entering directory '/home/epezhman/Projects/demand-manager-app/app/node_modules/@paulcbetts/system-idle-time/build'
  CXX(target) Release/obj.target/system_idle_time/src/module.o
system_idle_time.target.mk:95: recipe for target 'Release/obj.target/system_idle_time/src/module.o' failed
make: Leaving directory '/home/epezhman/Projects/demand-manager-app/app/node_modules/@paulcbetts/system-idle-time/build'

Error output:
In file included from /usr/include/errno.h:28:0,
                 from /home/epezhman/.electron-gyp/.node-gyp/iojs-1.4.3/deps/uv/include/uv-errno.h:25,
                 from /home/epezhman/.electron-gyp/.node-gyp/iojs-1.4.3/deps/uv/include/uv.h:48,
                 from ../../../nan/nan.h:46,
                 from ../src/module.h:4,
                 from ../src/module.cc:1:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/system_idle_time/src/module.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-45-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/epezhman/Projects/demand-manager-app/app/node_modules/@paulcbetts/system-idle-time
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "rebuild" "--production" "--cache-min" "999999999" "--build-from-source"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! @paulcbetts/system-idle-time@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @paulcbetts/system-idle-time@1.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @paulcbetts/system-idle-time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @paulcbetts/system-idle-time
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @paulcbetts/system-idle-time
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/epezhman/Projects/demand-manager-app/app/npm-debug.log

    at ChildProcess.<anonymous> (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/util.ts:160:14)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at spawn (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/util.ts:123:3)
    at spawnNpmProduction (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/util.ts:49:3)
    at Object.installDependencies (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/util.ts:20:122)
    at Packager.<anonymous> (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/packager.ts:239:34)
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at tsAwaiter (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/home/epezhman/Projects/demand-manager-app/node_modules/electron-builder/out/builder.js:138:12)
    at /home/epezhman/Projects/demand-manager-app/tasks/build.js:59:28
    at _fulfilled (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:796:13)
    at /home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:604:44
    at runSingle (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:137:13)
    at flush (/home/epezhman/Projects/demand-manager-app/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

**Comment by develar** [comment]
See [To build app in 32 bit from a machine with 64 bit](https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#to-build-app-in-32-bit-from-a-machine-with-64-bit)
