### ISSUE TITLE
I don't know - build errors yarn (maybe because rebuild)

### ISSUE THREAD

**Issue by mnewmedia** [electron-userland/electron-builder#895]
* **electron**: "^1.4.6",
* **electron-builder**: "^8.0.0",
* **electron-packager**: "^8.2.0",
* **regenerator-runtime**: "^0.9.6"
* **Target**:  Windows x64

Feel free to close if you know what or why it appears, or if your time allows help me what i should change to fix it, else i just revert to previous versions where everything worked.

When I run build i get:
```cmd
C:\projekte\ai\electron-ner>node_modules\.bin\build --win --x64
Rebuilding native production dependencies for arch x64
Packaging for win32 x64 using electron 1.4.6 to dist\win-unpacked
RangeError: Maximum call stack size exceeded
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:80:17)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
    at flatDependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:91:7)
From previous event:
    at dependencies (C:\projekte\ai\electron-ner\node_modules\electron-builder\src\yarn.ts:71:6)
    at C:\projekte\ai\electron-ner\node_modules\electron-builder\src\platformPackager.ts:189:13
    at next (native)
From previous event:
    at C:\projekte\ai\electron-ner\node_modules\electron-builder\src\packager\dirPackager.ts:58:11
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at pack (C:\projekte\ai\electron-ner\node_modules\electron-builder\out\packager\dirPackager.js:43:21)
    at C:\projekte\ai\electron-ner\node_modules\electron-builder\src\platformPackager.ts:186:5
    at next (native)
From previous event:
    at WinPackager.doPack (C:\projekte\ai\electron-ner\node_modules\electron-builder\out\platformPackager.js:307:11)
    at C:\projekte\ai\electron-ner\node_modules\electron-builder\src\winPackager.ts:119:16
    at next (native)
From previous event:
    at WinPackager.pack (C:\projekte\ai\electron-ner\node_modules\electron-builder\out\winPackager.js:192:11)
    at C:\projekte\ai\electron-ner\node_modules\electron-builder\src\packager.ts:132:22
From previous event:
    at Packager.doBuild (C:\projekte\ai\electron-ner\node_modules\electron-builder\out\packager.js:260:11)
    at C:\projekte\ai\electron-ner\node_modules\electron-builder\src\packager.ts:100:32
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (C:\projekte\ai\electron-ner\node_modules\electron-builder\out\packager.js:212:11)
    at C:\projekte\ai\electron-ner\node_modules\electron-builder\src\builder.ts:233:33
    at next (native)
From previous event:
    at build (C:\projekte\ai\electron-ner\node_modules\electron-builder\out\builder.js:81:21)
    at Object.<anonymous> (C:\projekte\ai\electron-ner\node_modules\electron-builder\out\build-cli.js:66:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by develar** [comment]
> i just revert to previous versions where everything worked.

7.x?

Definitely it is bug. Thanks for trying prelease 8.

**Comment by mnewmedia** [comment]
7.24.1 everything above fails.

**Comment by develar** [comment]
Is it possible to share link to your project (it will help me to reproduce and write test)?

**Comment by mnewmedia** [comment]
Just take the starter template or something like it and add to package.json `"pouchdb-node": "^6.0.7"`. This is causing the issue.

**Comment by TakenPilot** [comment]
This is happening to me too with the exact same versions of everything, on [this project.](http://github.com/yhat/rodeo)

**Comment by mnewmedia** [comment]
Cool! Thanks a lot!

**Comment by dingdangdog** [comment]
`electron-builder 26.0.12` have this error again(use npm):

-   "electron-log": "^5.4.0",
-   "electron-updater": "^6.6.2",
-   "electron": "^35.3.0", / `36.1.0，have the same error`
-   "electron-builder": "^26.0.12"

```
  • electron-builder  version=26.0.12 os=10.0.22631
  • loaded configuration  file=package.json ("build" field)
  • description is missed in the package.json  appPackageFile=E:\Code\VwordAi\package.json
  • writing effective config  file=package\builder-effective-config.yaml
  • executing @electron/rebuild  electronVersion=35.3.0 arch=x64 buildFromSource=false appDir=./
  • installing native dependencies  arch=x64
  • preparing       moduleName=bufferutil arch=x64
  • finished        moduleName=bufferutil arch=x64
  • preparing       moduleName=utf-8-validate arch=x64
  • finished        moduleName=utf-8-validate arch=x64
  • completed installing native dependencies
  • packaging       platform=win32 arch=x64 electron=35.3.0 appOutDir=package\win-unpacked
  • downloading     url=https://npmmirror.com/mirrors/electron/v35.3.0/electron-v35.3.0-win32-x64.zip size=120 MB parts=8
  • downloaded      url=https://npmmirror.com/mirrors/electron/v35.3.0/electron-v35.3.0-win32-x64.zip duration=10.452s
  ⨯ Maximum call stack size exceeded  failedTask=build stackTrace=RangeError: Maximum call stack size exceeded
    at NpmNodeModulesCollector._getNodeModules (E:\Code\VwordAi\node_modules\app-builder-lib\src\node-module-collector\nodeModulesCollector.ts:194:36)
    at NpmNodeModulesCollector._getNodeModules (E:\Code\VwordAi\node_modules\app-builder-lib\src\node-module-collector\nodeModulesCollector.ts:202:14)
    at NpmNodeModulesCollector._getNodeModules (E:\Code\VwordAi\node_modules\app-builder-lib\src\node-module-collector\nodeModulesCollector.ts:202:14)
    at NpmNodeModulesCollector._getNodeModules (E:\Code\VwordAi\node_modules\app-builder-lib\src\node-module-collector\nodeModulesCollector.ts:202:14)
    at NpmNodeModulesCollector._getNodeModules (E:\Code\VwordAi\node_modules\app-builder-lib\src\node-module-collector\nodeModulesCollector.ts:202:14)
    at NpmNodeModulesCollector._getNodeModules (E:\Code\VwordAi\node_modules\app-builder-lib\src\node-module-collector\nodeModulesCollector.ts:202:14)
    at NpmNodeModulesCollector._getNodeModules (E:\Code\VwordAi\node_modules\app-builder-lib\src\node-module-collector\nodeModulesCollector.ts:202:14)
    at NpmNodeModulesCollector._getNodeModules (E:\Code\VwordAi\node_modules\app-builder-lib\src\node-module-collector\nodeModulesCollector.ts:202:14)
    at NpmNodeModulesCollector._getNodeModules (E:\Code\VwordAi\node_modules\app-builder-lib\src\node-module-collector\nodeModulesCollector.ts:202:14)
    at NpmNodeModulesCollector._getNodeModules (E:\Code\VwordAi\node_modules\app-builder-lib\src\node-module-collector\nodeModulesCollector.ts:202:14)
```

Lowering the `electron-builder` version to `25.1.8` can be executed

```log
PS E:\Code\vwordai> npm run builder

> vwordai@0.1.0 builder
> electron-builder

  • electron-builder  version=25.1.8 os=10.0.22631
  • loaded configuration  file=package.json ("build" field)
  • description is missed in the package.json  appPackageFile=E:\Code\VwordAi\package.json
  • writing effective config  file=package\builder-effective-config.yaml
  • executing @electron/rebuild  electronVersion=35.3.0 arch=x64 buildFromSource=false appDir=./
  • installing native dependencies  arch=x64
  • preparing       moduleName=bufferutil arch=x64
  • finished        moduleName=bufferutil arch=x64
  • preparing       moduleName=utf-8-validate arch=x64
  • finished        moduleName=utf-8-validate arch=x64
  • completed installing native dependencies
  • packaging       platform=win32 arch=x64 electron=35.3.0 appOutDir=package\win-unpacked
  • updating asar integrity executable resource  executablePath=package\win-unpacked\VwordAi.exe
  • signing with signtool.exe  path=package\win-unpacked\VwordAi.exe
  • no signing info identified, signing is skipped  signHook=false cscInfo=null
  • building        target=nsis file=package\VwordAi-Setup-0.1.0.exe archs=x64 oneClick=false perMachine=false
  • signing with signtool.exe  path=package\win-unpacked\resources\elevate.exe
  • no signing info identified, signing is skipped  signHook=false cscInfo=null
  • signing with signtool.exe  path=package\__uninstaller-nsis-vwordai.exe
  • no signing info identified, signing is skipped  signHook=false cscInfo=null
  • signing with signtool.exe  path=package\VwordAi-Setup-0.1.0.exe
  • no signing info identified, signing is skipped  signHook=false cscInfo=null
  • building block map  blockMapFile=package\VwordAi-Setup-0.1.0.exe.blockmap
```

I don't know if it's a problem with the version I'm using or a problem with the new version?
