### ISSUE TITLE
npmArgs Error doing npm install in Ubuntu Desktop

### ISSUE THREAD

**Issue by aesalazar** [electron-userland/electron-builder#903]
* **Version**: 8.5.3

* **Target**:  Linux AppImage

When I do an npm install electron-builder --save-dev I get:

```
TypeError: Cannot read property 'npmArgs' of undefined
    at computeExtraArgs (/home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electron-
builder/src/yarn.ts:31:24)
    at /home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electron-builder/src/yarn.t
s:9:16
    at next (native)
From previous event:
    at installOrRebuild (/home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electron-
builder/out/yarn.js:33:21)
    at /home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electron-builder/src/instal
l-app-deps.ts:29:2
    at next (native)
From previous event:
    at main (/home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electron-builder/out/
install-app-deps.js:27:21)
    at Object.<anonymous> (/home/user/git/NodeElectronOpenFinWebPerformance/node_modules/electro
n-builder/out/install-app-deps.js:73:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

BUT only on my VirtualBox VM for Ubuntu Desktop 16.04LTS (dont see it in Windows 10).  I tried on two different VMS one brand new.  This was not happening with version 7.24.1.  I am still able to run my app without issue and it successfully builds the installation programmatically but I am only hitting a portion of the code.

Ernie

**Comment by develar** [comment]
Please do not use `install-app-deps` script if your package.json doesn't have `build` configuration.

**Comment by aesalazar** [comment]
Got it, thanks.  Sorry for the unneeded post.
