### ISSUE TITLE
Unable to build package because of asarUnpack

### ISSUE THREAD

**Issue by vincent-t** [electron-userland/electron-builder#937]
* **Version**: 9.1.0

* **Target**: linux x64

```
Rebuilding native production dependencies for arch x64
Packaging for linux x64 using electron 1.4.6 to dist/linux-unpacked
TypeError: A value  was yielded that could not be treated as a promise

    See http://goo.gl/MqrFmX

From coroutine:
    at Promise.coroutine (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/bluebird/js/release/generators.js:194:17)
    at AsarPackager.createPackageFromFiles (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/out/asarUtil.js:276:70)
    at /media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/src/asarUtil.ts:107:16
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/bluebird/js/release/promise.js:612:10)
    at AsarPackager.createPackageFromFiles (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/out/asarUtil.js:276:70)
    at /media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/src/asarUtil.ts:107:16
    at Generator.next (<anonymous>)
    at /media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/fs-extra-tf/lib/mkdirs/mkdirs.js:35:14
    at FSReqWrap.oncomplete (fs.js:111:15)
From previous event:
    at AsarPackager.createPackageFromFiles (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/out/asarUtil.js:375:11)
    at /media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/src/asarUtil.ts:107:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at AsarPackager.pack (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/out/asarUtil.js:191:11)
    at /media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/src/asarUtil.ts:71:70
    at Generator.next (<anonymous>)
From previous event:
    at createAsarArchive (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/out/asarUtil.js:70:22)
    at /media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/src/platformPackager.ts:249:17
From previous event:
    at LinuxPackager.doPack (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/out/platformPackager.js:316:11)
    at /media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/src/platformPackager.ts:157:16
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.pack (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/out/platformPackager.js:213:11)
    at /media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/src/packager.ts:132:22
From previous event:
    at Packager.doBuild (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/out/packager.js:256:11)
    at /media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/src/packager.ts:100:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/out/packager.js:208:11)
    at /media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/src/builder.ts:240:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/out/builder.js:89:21)
    at Object.<anonymous> (/media/disk2/Development/Spotify-Web-Player-for-Linux/node_modules/electron-builder/out/cli/build-cli.js:62:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! spotifywebplayer@1.0.25 dist: `build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the spotifywebplayer@1.0.25 dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spotifywebplayer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spotifywebplayer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spotifywebplayer
npm ERR! There is likely additional logging output above.
```

**Comment by Jonovono** [comment]
@vincent-t  How did you fix this?

**Comment by develar** [comment]
@vincent-t fixed in the electron-builder.

**Comment by vincent-t** [comment]
@Jonovono look at devlar's post.
