### ISSUE TITLE
build error about`Error: electron must be in the devDependencies` 

### ISSUE THREAD

**Issue by koalaylj** [electron-userland/electron-builder#939]
electron : 1.4.8
electron-packager:8.3.0
target : mac

my project is [here](https://github.com/koalaylj/bitmap-font-maker).

when i run `npm start dist` or `npm start dist:osx` it went error.
```bash
MACdeiMac:bitmap-font-maker mac$ npm run dist:osx

> bitmap-font-maker@0.0.1 dist:osx /Users/mac/github/bitmap-font-maker
> build --mac

Error: electron must be in the devDependencies
    at checkDependencies (/Users/mac/github/bitmap-font-maker/node_modules/electron-builder/src/packager.ts:324:13)
    at Packager.checkMetadata (/Users/mac/github/bitmap-font-maker/node_modules/electron-builder/src/packager.ts:187:5)
    at /Users/mac/github/bitmap-font-maker/node_modules/electron-builder/src/packager.ts:93:10
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/Users/mac/github/bitmap-font-maker/node_modules/electron-builder/out/packager.js:208:11)
    at /Users/mac/github/bitmap-font-maker/node_modules/electron-builder/src/builder.ts:240:40
    at next (native)
From previous event:
    at build (/Users/mac/github/bitmap-font-maker/node_modules/electron-builder/out/builder.js:89:21)
    at Object.<anonymous> (/Users/mac/github/bitmap-font-maker/node_modules/electron-builder/out/build-cli.js:62:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist:osx"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! bitmap-font-maker@0.0.1 dist:osx: `build --mac`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the bitmap-font-maker@0.0.1 dist:osx script 'build --mac'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bitmap-font-maker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --mac
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bitmap-font-maker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bitmap-font-maker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/github/bitmap-font-maker/npm-debug.log
```

but `electron`is already included in my devDependencies.where am i wrong?

I tried add [.travis.yml](https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml) to root directory of my project , got same error.

thanks for any help.

**Comment by develar** [comment]
No, as far I see, electron IN THE production dependencies — https://github.com/koalaylj/bitmap-font-maker/blob/master/package.json#L48
![screen shot 2016-11-26 at 17 46 51](https://cloud.githubusercontent.com/assets/350686/20641812/580be448-b400-11e6-9d0d-018d5d75f027.png)
