### ISSUE TITLE
Don't understand wiki?????

### ISSUE THREAD

**Issue by sourceskyboxer** [electron-userland/electron-builder#942]
Hello I am trying to electron-builder - I don't understand why do you explain bad readme???

Please explain step to step!
I have tried it.
"X:\electron-quick-start>build --win --x64"
output error:
"Error: Please specify 'build' configuration in the development package.json ('C:\Users\Jens\electron-quick-start\package.json'), at least

  build: {
    "appId": "your.id",
    "category": "your.app.category.type"
  }
}

is required.

    at Packager.checkMetadata (C:\Users\Jens\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:198:13)
    at C:\Users\Jens\AppData\Roaming\npm\node_modules\electron-builder\src\packager.ts:93:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (C:\Users\Jens\AppData\Roaming\npm\node_modules\electron-builder\out\packager.js:208:11)
    at C:\Users\Jens\AppData\Roaming\npm\node_modules\electron-builder\src\builder.ts:240:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\Jens\AppData\Roaming\npm\node_modules\electron-builder\out\builder.js:89:21)
    at Object.<anonymous> (C:\Users\Jens\AppData\Roaming\npm\node_modules\electron-builder\out\build-cli.js:62:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
"

I am using Windows 7 Pro x64 - Node.js 7.20 upgraded
i have installed successful all important libraries from npm-modules.
Please do not lie me!

Because I saw all developers use only Electron Applications. That is why I want to know.....

**Comment by develar** [comment]
And?  What is not clear? Have you read https://github.com/electron-userland/electron-builder#quick-setup-guide?

**Comment by sourceskyboxer** [comment]
Sorry I am here now. I don't understand that wiki. that is why I just make simple:

1. Download electron binary

2. Create html, js and css....

3. Set path=%path%;"path-to-electron\electron.exe"

4. Type "electron .

It works fine.

But I don't understand why does wiki mess up because they use old version of codes
like this

```
var app = require('app');
var BrowserWindow = require('browser-window');
var mainWindow = null;

app.on('ready', function() {
    mainWindow = new BrowserWindow({
        height: 600,
        width: 800
    });
    mainWindow.loadUrl('file://' + __dirname + '/app/index.html');
});
```

Please format all fresh and clean version for current version 1.4.8 of Electron.
what is ipc??

But for me doesn't work why???
I don't understand ipcRender or ipc/remote

I really miss tutorial of https://github.com/shama/letswritecode/blob/master/multi-window-electron-desktop-app/app.js

How do I replace to new version? How does ipc work for 1.4.8?

**Comment by develar** [comment]
I am sorry but it is out of electron-builder project scope. Please see Community https://github.com/electron/electron#community

**Comment by sourceskyboxer** [comment]
Thanks for answer I have tried and it works fine. Check my post into multi window of electron https://github.com/electron/electron/issues/323#issuecomment-263147461

But I have problem if I click close "X" from window border and I re click to open new window but it gets error.... If new BrowserWindow was destroyed. Thanks!
