### ISSUE TITLE
electron builder not creating new build after signing installer.

### ISSUE THREAD

**Issue by nidhir-systango** [electron-userland/electron-builder#944]
i have signed my installer by using signtool(windows msi installer)
by following command:

    signtool sign /t http://timestamp.comodoca.com/authenticode  /f "C:\Users\admin\Downloads\Certificates.p12" /p mypassword C:\Users\admin\Downloads\New folder\new2\win_desktop\dist\win\CoDesktop Setup 1.0.1.msi"

after that i have made some changes in my code and again making built by command 

    build -w

 but this time getting error-

    Rebuilding app dependencies for arch x64 to C:\Users\admin\Downloads\New   folder\new2\win_codesktop\app

    Packaging for platform win32 x64 using electron 1.4.3 to dist\win-unpacked

    node_modules\electron-screencapture\node_modules\recordrtc is not packed into asar archive -    contains executable code
       Signing CoDesktop.exe (certificate file "C:\Users\admin\AppData\Local\Temp\electron-builder-1a14-    158aadefd67-0\t-1a14-0.p12")
       Error: Exit code: 1. Command failed: C:\Users\admin\.cache\winCodeSign\winCodeSign-        1.4.2\windows-   10\signtool.exe sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f        C:\Users\admin\AppData\Local\Temp\electron-builder-
        1a14-158aadefd67-0\t-1a14-0.p12 /d CoDesktop /du https://app.onepgr.com/ /p rajivrohan        C:\Users\admin\Downloads\New folder\new2\win_codesktop\dist\win-unpacked\CoDesktop.exe
    SignTool Error: An error occurred while attempting to load the signing
        certificate from: C:\Users\admin\AppData\Local\Temp\electron-builder-1a14-158aadefd67-0\t-1a14-0.p12

      SignTool Error: An error occurred while attempting to load the signing
         certificate from: C:\Users\admin\AppData\Local\Temp\electron-builder-1a14-158aadefd67-0\t-       1a14-0.p12

    at C:\Users\admin\AppData\Roaming\npm\node_modules\electron-builder\src\util\util.ts:102:16
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)
    From previous event:
    at Object.exec (C:\Users\admin\AppData\Roaming\npm\node_modules\electron-builder\src\util\util.ts:80:3)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\electron-  builder\src\windowsCodeSign.ts:117:20
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
    From previous event:
    at tsAwaiter (C:\Users\admin\AppData\Roaming\npm\node_modules\electron-  builder\src\util\awaiter.ts:10:47)
    at Object.build (C:\Users\admin\AppData\Roaming\npm\node_modules\electron-  builder\out\builder.js:138:12)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\electron-  builder\out\build-cli.js:23:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

my  temp folder does not have any file or folder named in the error.

please help me out of this.

Thanks in advance!

**Comment by nidhir-systango** [comment]
it was some issue with windows powershell ,by running it with cmd works fine!
