### ISSUE TITLE
Error when building .deb with icon.

### ISSUE THREAD

**Issue by brpaz** [electron-userland/electron-builder#992]
10.6.1

Linux

Hello.
I am trying to use Electron builder for the first time and I have a problem when I set an icon:

```
Error: Exit code: ENOENT. spawn gm ENOENT
    at /media/DATA/Code/dext/node_modules/electron-builder/src/util/util.ts:76:16
    at exithandler (child_process.js:218:5)
    at ChildProcess.errorhandler (child_process.js:230:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at exec (/media/DATA/Code/dext/node_modules/electron-builder/src/util/util.ts:54:3)
    at resize (/media/DATA/Code/dext/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:147:16)
    at /media/DATA/Code/dext/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:150:46
    at Generator.next (<anonymous>)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at LinuxTargetHelper.createFromIcns (/media/DATA/Code/dext/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:187:11)
    at /media/DATA/Code/dext/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:28:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/media/DATA/Code/dext/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:58:11)
    at new LinuxTargetHelper (/media/DATA/Code/dext/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:16:23)
    at getHelper (/media/DATA/Code/dext/node_modules/electron-builder/src/linuxPackager.ts:42:18)
    at outDir (/media/DATA/Code/dext/node_modules/electron-builder/src/linuxPackager.ts:71:122)
    at mapper (/media/DATA/Code/dext/node_modules/electron-builder/src/targets/targetFactory.ts:29:16)
    at LinuxPackager.createTargets (/media/DATA/Code/dext/node_modules/electron-builder/src/linuxPackager.ts:71:7)
    at createTargets (/media/DATA/Code/dext/node_modules/electron-builder/src/targets/targetFactory.ts:36:12)
    at /media/DATA/Code/dext/node_modules/electron-builder/src/packager.ts:132:41
From previous event:
    at Packager.doBuild (/media/DATA/Code/dext/node_modules/electron-builder/out/packager.js:260:11)
    at /media/DATA/Code/dext/node_modules/electron-builder/src/packager.ts:100:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/media/DATA/Code/dext/node_modules/electron-builder/out/packager.js:212:11)
    at /media/DATA/Code/dext/node_modules/electron-builder/src/builder.ts:241:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/media/DATA/Code/dext/node_modules/electron-builder/out/builder.js:89:21)
    at Object.<anonymous> (/media/DATA/Code/dext/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3


```

Here is my build part of package.json:

```
 "build": {
    "mac": {
      "category": "public.app-category.utilities",
      "target": ["dmg"],
      "icon": "resources/icon.icns"
    },
    "linux": {
      "category": "Utility",
      "arch" : 64,
      "target" : ["deb"]
    }
  }
```

What I am missing?

**Comment by smithalan92** [comment]
@brpaz It appears it can't find your icon. Try using an absolute path and ensure the `icon.icns` file exists at that location. Also you should note that Mac applications can only be code signed when building on OSX.

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux Please install graphicsmagick.

**Comment by develar** [comment]
Please note — AppImage is recommended instead of deb.
