### ISSUE TITLE
NSIS on Linux: FATAL: main argv conversion failed!

### ISSUE THREAD

**Issue by pyriand3r** [electron-userland/electron-builder#994]
* **Version**: 10.7.0

* **Target**: win nsis

I'm having problems to build the nsis installer under linux. I have the same error under my main system (Arch x64) and a Docker-container i created for automated build purposes (debian jessie). The linux AppImage is created without problems. Squirrel for window is also no problem. But when i try to build an nsis installer i get the above mentioned error. Haven't found anything about it on the internet so far.

Here's the complete log:

```
build --win nsis --x64
Skip app dependencies rebuild because platform is different
Packaging for win32 x64 using electron 1.4.5 to dist/win-unpacked
⚠️  Application icon is not set, default Electron icon will be used
Packaging NSIS installer for arch x64
Building NSIS installer
Error: /root/.cache/electron-builder/nsis/nsis-3.0.2/linux/makensis exited with code 29
Output:
FATAL: main argv conversion failed!

    at ChildProcess.childProcess.once.code (/usr/lib/node_modules/electron-builder/src/util/util.ts:136:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
From previous event:
    at /usr/lib/node_modules/electron-builder/src/targets/nsis.ts:330:5
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at NsisTarget.executeMakensis (/usr/lib/node_modules/electron-builder/out/targets/nsis.js:375:11)
    at /usr/lib/node_modules/electron-builder/src/targets/nsis.ts:203:62
From previous event:
    at NsisTarget.buildInstaller (/usr/lib/node_modules/electron-builder/out/targets/nsis.js:296:11)
    at /usr/lib/node_modules/electron-builder/src/targets/nsis.ts:76:18
    at next (native)
From previous event:
    at NsisTarget.finishBuild (/usr/lib/node_modules/electron-builder/out/targets/nsis.js:151:11)
    at /usr/lib/node_modules/electron-builder/src/packager.ts:150:31
From previous event:
    at Packager.doBuild (/usr/lib/node_modules/electron-builder/out/packager.js:271:11)
    at /usr/lib/node_modules/electron-builder/src/packager.ts:114:38
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/usr/lib/node_modules/electron-builder/out/packager.js:223:11)
    at /usr/lib/node_modules/electron-builder/src/builder.ts:241:40
    at next (native)
From previous event:
    at build (/usr/lib/node_modules/electron-builder/out/builder.js:89:21)
    at Object.<anonymous> (/usr/lib/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Any ideas on this? Or is this an nsis bug?

Greetings,
pyriand3r

**Comment by develar** [comment]
Our tests works on Linux CI. Probably something wrong on your setup. Please specify Linux distro.

**Comment by develar** [comment]
@pyriand3r Please use our docker image — https://github.com/electron-userland/electron-builder/wiki/Docker
