### ISSUE TITLE
Win 10 build problem

### ISSUE THREAD

**Issue by igorcandeia** [electron-userland/electron-builder#997]
build --win --x64
```
Rebuilding native production dependencies for arch x64
Packaging for win32 x64 using electron 1.4.12 to dist\win-unpacked
⚠️  Application icon is not set, default Electron icon will be used
Packaging NSIS installer for arch x64
Building NSIS installer
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at exports.execFile (child_process.js:143:15)
    at default (C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\src\util\util.ts:56:5)
    at exec (C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\src\util\util.ts:55:3)
    at C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\src\targets\nsis.ts:204:13
From previous event:
    at NsisTarget.buildInstaller (C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\out\targets\nsis.js:296:11)
    at C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\src\targets\nsis.ts:76:18
    at next (native)
From previous event:
    at NsisTarget.finishBuild (C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\out\targets\nsis.js:151:11)
    at C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\src\packager.ts:150:31
From previous event:
    at Packager.doBuild (C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\out\packager.js:271:11)
    at C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\src\packager.ts:114:38
    at next (native)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Packager.build (C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\out\packager.js:223:11)
    at C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\src\builder.ts:241:40
    at next (native)
From previous event:
    at build (C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\out\builder.js:89:21)
    at Object.<anonymous> (C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\electron-builder\out\cli\build-cli.js:68:41)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

Package:
"win": {
      "target": ["nsis"]
    },
    "nsis": {
      "oneClick": false
    },

**Comment by develar** [comment]
Please set env DEBUG=electron-builder to get debug logs.

**Comment by igorcandeia** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Igor\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-windows' ]
2 info using npm@4.0.1
3 info using node@v6.5.0
4 verbose run-script [ 'prebuild-windows', 'build-windows', 'postbuild-windows' ]
5 info lifecycle BatteryTag@1.0.0~prebuild-windows: BatteryTag@1.0.0
6 silly lifecycle BatteryTag@1.0.0~prebuild-windows: no script for prebuild-windows, continuing
7 info lifecycle BatteryTag@1.0.0~build-windows: BatteryTag@1.0.0
8 verbose lifecycle BatteryTag@1.0.0~build-windows: unsafe-perm in lifecycle true
9 verbose lifecycle BatteryTag@1.0.0~build-windows: PATH: C:\Users\Igor\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Users\Igor\AppData\Local\Microsoft\WindowsApps;C:\Users\Igor\AppData\Roaming\npm
10 verbose lifecycle BatteryTag@1.0.0~build-windows: CWD: C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app
11 silly lifecycle BatteryTag@1.0.0~build-windows: Args: [ '/d /s /c', 'build --win --x64' ]
12 silly lifecycle BatteryTag@1.0.0~build-windows: Returned: code: 4294967295  signal: null
13 info lifecycle BatteryTag@1.0.0~build-windows: Failed to exec build-windows script
14 verbose stack Error: BatteryTag@1.0.0 build-windows: `build --win --x64`
14 verbose stack Exit status 4294967295
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Igor\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Igor\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid BatteryTag@1.0.0
16 verbose cwd C:\Users\Igor\Enersys\batterytag\BatteryTagDesktop\app
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Igor\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-windows"
19 error node v6.5.0
20 error npm  v4.0.1
21 error code ELIFECYCLE
22 error BatteryTag@1.0.0 build-windows: `build --win --x64`
22 error Exit status 4294967295
23 error Failed at the BatteryTag@1.0.0 build-windows script 'build --win --x64'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the BatteryTag package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     build --win --x64
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs BatteryTag
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls BatteryTag
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```


this?

**Comment by develar** [comment]
No, the console out as in your original message, but when DEBUG env is set to electron-builder.

**Comment by igorcandeia** [comment]
I fixed the problem, just run as administrator
